### ISSUE TITLE
Error on install with already installed python 3.4 from WinPython

### ISSUE THREAD

**Issue by pacif-coder** [biolab/orange3#1017]
Install detail log:
==============================================================
Ignoring indexes: https://pypi.python.org/simple
Requirement already satisfied (use --upgrade to upgrade): setuptools in d:\winpython\python-3.4.3.amd64\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): pip in d:\winpython\python-3.4.3.amd64\lib\site-packages
Output folder: C:\Users\Pacif\AppData\Local\Temp\orange-installer\wheelhouse
Extract: Bottlechest-0.7.1-cp34-none-win32.whl... 100%
Extract: Jinja2-2.7.3-py3-none-any.whl... 100%
Extract: MarkupSafe-0.23-cp34-none-win32.whl... 100%
Extract: Orange-3.2.dev0+dfc525c-cp34-none-win32.whl... 100%
Extract: PyQt4-4.11.4-cp34-none-win32.whl... 100%
Extract: Pygments-2.0.2-py3-none-any.whl... 100%
Extract: certifi-14.5.14-py2.py3-none-any.whl... 100%
Extract: chardet-2.3.0-py2.py3-none-any.whl... 100%
Extract: decorator-3.4.0-py3-none-any.whl... 100%
Extract: docutils-0.12-py3-none-any.whl... 100%
Extract: ipython-2.4.1-py3-none-any.whl... 100%
Extract: matplotlib-1.4.2-cp34-none-win32.whl... 100%
Extract: networkx-1.9.1-py2.py3-none-any.whl... 100%
Extract: numpy-1.9.2-cp34-none-win32.whl... 100%
Extract: pyparsing-2.0.7-py2.py3-none-any.whl... 100%
Extract: pyqtgraph-0.9.10-py3-none-any.whl... 100%
Extract: pyreadline-2.1-py3-none-any.whl... 100%
Extract: python_dateutil-2.4.2-py2.py3-none-any.whl... 100%
Extract: pytz-2015.7-py2.py3-none-any.whl... 100%
Extract: pyzmq-14.5.0-cp34-none-win32.whl... 100%
Extract: scikit_learn-0.16.1-cp34-none-win32.whl... 100%
Extract: scikit_learn-0.17-cp34-none-win32.whl... 100%
Extract: scipy-0.15.1-cp34-none-win32.whl... 100%
Extract: setuptools-19.2-py2.py3-none-any.whl... 100%
Extract: six-1.10.0-py2.py3-none-any.whl... 100%
Extract: sqlparse-0.1.13-py3-none-any.whl... 100%
Extract: tornado-4.1-cp34-none-win32.whl... 100%
Extract: xlrd-0.9.4-py3-none-any.whl... 100%
Output folder: C:\Users\Pacif\AppData\Local\Temp\orange-installer\wheelhouse\nosse
Extract: numpy-1.9.2-cp34-none-win32.whl... 100%
Extract: scipy-0.15.1-cp34-none-win32.whl... 100%
Output folder: C:\Users\Pacif\AppData\Local\Temp\orange-installer\wheelhouse\sse2
Extract: numpy-1.9.2-cp34-none-win32.whl... 100%
Extract: scipy-0.15.1-cp34-none-win32.whl... 100%
Output folder: C:\Users\Pacif\AppData\Local\Temp\orange-installer\wheelhouse\sse3
Extract: numpy-1.9.2-cp34-none-win32.whl... 100%
Extract: scipy-0.15.1-cp34-none-win32.whl... 100%
Output folder: C:\Users\Pacif\AppData\Local\Temp\orange-installer\wheelhouse
Output folder: C:\Users\Pacif\AppData\Local\Temp\orange-installer
Extract: requirements.txt... 100%
Installing scipy stack (sse3)
Ignoring indexes: https://pypi.python.org/simple
Requirement already satisfied (use --upgrade to upgrade): numpy in d:\winpython\python-3.4.3.amd64\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): scipy in d:\winpython\python-3.4.3.amd64\lib\site-packages
Installing required packages
Ignoring indexes: https://pypi.python.org/simple
Collecting scikit-learn==0.16.1 (from -r C:\Users\Pacif\AppData\Local\Temp\orange-installer\requirements.txt (line 3))
  Could not find any downloads that satisfy the requirement scikit-learn==0.16.1 (from -r C:\Users\Pacif\AppData\Local\Temp\orange-installer\requirements.txt (line 3))
  No distributions at all found for scikit-learn==0.16.1 (from -r C:\Users\Pacif\AppData\Local\Temp\orange-installer\requirements.txt (line 3))
Could not install all requirements

**Comment by pacif-coder** [comment]
Windows Build - 2016-02-08, install file Orange3-3.2.dev0+dfc525c.win32-py3.4-install

**Comment by ales-erjavec** [comment]
You seem to be using a 64 bit Python, but Orange 3 windows installer only contains 32-bit extensions, i.e. it will only install into 32-bit Python environment. I am not sure why it even picks up the winpython in your case. If I remember correctly the location of the Python installation that is read from registry is using the appropriate 32 bit registry view, so it should not find a 64 bit Python.

**Comment by ajdapretnar** [comment]
@pacif-coder Has the issue been resolved for you or do you need additional info? In other words, can the issue be closed?

**Comment by pacif-coder** [comment]
After re-install windiows, Orage was be successful installed - it's mast be error on prevision windiows  from several different Python version installed
And "Yes", it issue  can be closed
