### ISSUE TITLE
Report of Rank Widget does not contain the feature names in the table.

### ISSUE THREAD

**Issue by jamartinh** [biolab/orange3#1022]
Report of Rank Widget does not contain the feature names in the table.
Windows 10 64 bits

**Comment by kumargaurav2596** [comment]
I have spoted the reason for this issue. The report_standard_model(model) function in  report_table() method in canvas/report/report.py checks for horizontal header and append it if present but it has no such check for vertical header. Should I include this check here or should I just add vertical headers as additional column in the table before passing them to report_table() method in widget/data/owrank.py send_report() method.

**Comment by kernc** [comment]
@kumargaurav2596 Thanks for figuring it out. I think we should check for vertical headers in _report.py_.

**Comment by kumargaurav2596** [comment]
Please check the PR #1142 and let me know if anything is wrong.
