### ISSUE TITLE
[request] Flow cytometry add-on

### ISSUE THREAD

**Issue by peterch405** [biolab/orange3#1027]
I see great potential of orange3 to analyze high-dimensional flow cytometry data. I have started writing small snippets in the python script widget to read in fcs files, but what would really be amazing if we could have widgets for things like tsne, spade and other data analysis algorithms implemented. The ability to selecting subsets of data already make orange3 great for the type of data manipulation required in flow cytometry (mass cytometry).

**Comment by BlazZupan** [comment]
Peter, thanks for your note. Widgets for tsne and other 2d embedding are coming (MDS and PCA are already there). We are also thinking about methods to characterize data selections from these visualizations. Can't promise you andy dates, but at least tsne should be soon.

**Comment by ajdapretnar** [comment]
Manifold learning implements 2D embeddings, while [scOrange](https://singlecell.biolab.si/) takes care of a lot of cell-level analyses. @peterch405 Perhaps give it a look and check if there is something missing.

**Comment by ajdapretnar** [comment]
As usual, it is RAM dependent and method-dependent. We impose no strict upper limit as such.
