### ISSUE TITLE
missing distance file icon in Unsupervised

### ISSUE THREAD

**Issue by JUILLET** [biolab/orange3#1031]
HI,
since the new version, I don't have anymore the Distance file icon to be able to upload a file in orange 3.2.
![bug orange canvas](https://cloud.githubusercontent.com/assets/17417086/13233785/b8439520-d9b5-11e5-8b6c-1f74f694250f.png)
coud you please tell me how to fix it?

**Comment by janezd** [comment]
What a coincidence: I just submitted the code for the widgets for saving and loading distances (PR #1026). It has to be checked by another colleague, so it's going to be included in the distribution in a few days, hopefully.

**Comment by JUILLET** [comment]
thanks a lot for your prompt reply
I will wait for the next distribution kit.
tell me as soon as it will be available

**Comment by janezd** [comment]
I hope you're still interested in Distance Matrix widget --- releasing a new build is taking longer than expected.

These are release candidates that contain the widget.

* OSX: http://orange.biolab.si/download/files/nightly/Orange3-3.3.dev0%2b861098e.dmg
* Windows: http://orange.biolab.si/download/files/nightly/Orange3-3.3.dev0%2b861098e.win32-py3.4-install.exe

**Comment by JUILLET** [comment]
Hi

thanks a lot
now it's OK
regards
  ----- Original Message -----
