### ISSUE TITLE
Nothing happens when I run installer

### ISSUE THREAD

**Issue by cau83** [biolab/orange3#1035]
At first I thought it might be my work network which has a lot of security (though it usually stops me at the point of accessing a web site or downloading a file-- once I download, things are usually okay). The file appears to download successfully. I have tried both the 2.7 and up-to-date version. I do not see how it would be a network security issue.

I switched to a laptop (rather than virtual machine) and on the install, IE shows up a pop up that says the file "is not commonly downloaded and could harm your computer."

And then when I try to run directly from the file, I get a pop up from Windows SmartScreen that wants administrator approval. I have Admin privileges on my virtual machine (wasn't sure about the laptop, but when I enter credentials it doesn't tell me I do not have, and then does nothing with the install once again).

VM: Windows 7, 64 bit.
Laptop: W8,64 bit.

**Comment by kernc** [comment]
Hi,

Yes, in Windows 10, Edge (IE) warns that the installer file is "by an unverified publisher". Nevertheless, you click Run and it proceeds with installation. Should work in Windows 7 and 8 likewise.

Could you, perhaps, temporarily disable SmartScreen and similar non-features?

**Internal note:**
We should probably apply for a certificate and [digitally sign our windos installers](https://msdn.microsoft.com/en-us/library/windows/desktop/aa388170%28v=vs.85%29.aspx)?

**Comment by cau83** [comment]
Disabling SmartScreen is not relevant, in that I want it to work on my virtual machine (the laptop was just to sandbox, it's not mine to use regularly). I don't know enough about Windows 7 security features to know where to start on this.

I did a better test by trying to install on my home pc outside of my work network (Windows 10, so not completely apples to apples). The installer started up immediately. So it must be something about my work network and or security settings (and i'm going to have little to no control over that) :(

thanks.

**Comment by ajdapretnar** [comment]
@cau83 Can we consider the issue closed?

**Comment by cau83** [comment]
Yes

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=ti&cv=6.0.64&pv=8.2]
On Wed, Apr 13, 2016 at 4:04 AM, Ajda <notifications@github.com> wrote:
@cau83 [https://github.com/cau83] Can we consider the issue closed?
