### ISSUE TITLE
Dataset credits

### ISSUE THREAD

**Issue by doblak** [biolab/orange3#1040]
Dataset files (or accompanying sidecar files or something) should probably contain links to it's sources/licenses/citation requests.

If someone can give any advices on how to accomplish that (dataset file, sidecar file, json info used by update_list.py to include the info at least in datasets.info?), I can prepare a PR.

**Comment by ajdapretnar** [comment]
@doblak Can we close this issue?

**Comment by kernc** [comment]
@ajdapretnar How about we fix it first?

**Comment by ajdapretnar** [comment]
This is a month old issue. I'm just asking whether this has been resolved or not to clear the list of stale issues. If this is not desired, I'll leave it alone.

**Comment by kernc** [comment]
I think datasets meta data (including proper attribution) is still an open issue. :smiley_cat:

**Comment by ajdapretnar** [comment]
Ok. Is it possible to resolve it in a week or so? @doblak @kernc Yes, I'll be your issue nazi from now on.  :smile:

**Comment by kernc** [comment]
> Ok. Is it possible to resolve it in a week or so?

I don't think so. We haven't even discussed it. Except the idea of a "Fetch Data" widget like the one in Bio. Good luck! :metal:

**Comment by astaric** [comment]
For datasets included in the distribution, we could add a separate <dataset_name>.metadata file, which could include (hopefully machine readable) description of the data, source url, license (and anything else we might consider relevant). The refactored Reader interface could easily be modified to include a metadata method/property that would parse this file and present the information to the user.

As for the actual format, I have no idea what to use. XML? :smiling_imp:

**Comment by janezd** [comment]
YAML should suffice. A small subset of it, actually. Just associative arrays. :)

I volunteer to write a proprietary parser with at most 50 states. In pure Cython, for speed.

**Comment by kernc** [comment]
So why not *.tab?

**Comment by BlazZupan** [comment]
A data set browser is coming. A special widget that will also contain data set description and link to original web page with distribution. This will take a while (few months) since it depends on moving serverfiles functionality from bioinformatics add-on to core distribution.

**Comment by kernc** [comment]
@BlazZupan is anyone already working on this?

**Comment by doblak** [comment]
In case it helps resolving this issue - here is the attribution info (single page pdf, part of a publication) for most of classification datasets: 

https://www.dropbox.com/s/ww55ovjzkwgwpqf/datasets.pdf?dl=0

And some sidenotes:

- brown-selected and yeast are duplicates
- I was unable to identify the source of geo-gds360 and hair-eye-sex in timely fashion

**Comment by ajdapretnar** [comment]
@BlazZupan Did we not introduce .metadata files recently? Also, Data Sets is now working and it does reference sources, but it doesn't contain most of the documentation data sets. Can we figure out what to do?

**Comment by ajdapretnar** [comment]
Partially solved in https://github.com/biolab/datasets/pull/67 and https://github.com/biolab/datasets/pull/65.
