### ISSUE TITLE
Color widget delet exception

### ISSUE THREAD

**Issue by fsaina** [biolab/orange3#1041]
When deleting the 'Color' widget an Exception occurs in owcolor.py:

> line 302, in storeSpecificSettings
>     for var in self.disc_colors]
> AttributeError: 'NoneType' object has no attribute 'disc_data'

The issue seems that the 'current_context' variable(with disc_colors and count_data attributes) isn't initialized although it is used in overriding methods: 'storeSpecificSettings' and 'retrieveSpecificSettings'

With enough info on the expected behaviour I could make a PR.

**Comment by ales-erjavec** [comment]
The `current_context` is initialized and valid between calls to `openContext` and `closeContext`. This is done in `set_data` method.
The `storeSpecificSettings` should check if `current_context` is None (this is a perfectly valid state); and do nothing in that case.

**Comment by ales-erjavec** [comment]
The same problem exists in in 'Distance Matrix' widget.

**Comment by iamved** [comment]
Fixed issue with PR #1075
