### ISSUE TITLE
Rank widgets crashes when some target values are missing

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#1046]
I tried this with regression data; classification probably has the same problem.

**Comment by rahulroxx** [comment]
I would like to address this problem wait for my PR !

**Comment by mudit5bachhawat** [comment]
Any updates on this? I have also started to work on this?

**Comment by mudit5bachhawat** [comment]
I am not able to find any crash.

![screenshot from 2016-03-11 13 05 37](https://cloud.githubusercontent.com/assets/6140491/13696095/275d906e-e78a-11e5-9fa6-b388ec58adf5.png)

**Comment by ajdapretnar** [comment]
Your data says it has discrete class with no missing values. The problem is when the data **has** missing values (that is missing target variables). Also Rank crashes even directly on iris data, so there's another issue with it anyway.

**Comment by kernc** [comment]
@ajdapretnar Rank doesn't crash on iris? Perhaps recompile.
