### ISSUE TITLE
Select Columns does not trigger auto apply

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#1047]
Place Select Columns within some schema and check the auto apply checkbox. Change the order of attributes by dragging within the list box. The widget does not emit the new data table although the auto apply is enabled.

**Comment by rahulroxx** [comment]
@ales-erjavec 	Fixed Issue #1047

**Comment by rahulroxx** [comment]
@ales-erjavec Fixed issue with PR #1064

**Comment by ajdapretnar** [comment]
Fixed via #1353.
