### ISSUE TITLE
Scatter plot should hide attributes with no defined values

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#1048]
If an attribute does not have any defined values (all nan) and the user selects it, the scatter plot should show a warning.

**Comment by themistoklik** [comment]
Hello @janezd ,

A warning can be displayed by adding a data.has_missing() check to owscatterplot in the set_data function.

Such a warning would be displayed not only when all values of an attribute are NaN, but also if any attribute value is NaN (which I think is useful information).

What would be more useful would be to pinpoint the feature names where the NaNs exist so the user is informed. How do i go about getting each attribute's values to run a has_missing() there and warn about NaNs specifically in that attribute?

I do understand that for large datasets such a warning could prove dysfunctional, so if you disagree , please answer me for future reference.

**Comment by ajdapretnar** [comment]
The warning can be: Columns with missing values have been removed.

I still believe Scatter Plot should not offer empty attributes (NaN) in the 'Axis data' dropdowns as there is absolutely no point in having them there.

**Comment by janezd** [comment]
I agree with both: attributes with no defined values should be removed since they are not useful. If any such attributes were removed, we need a warning. Second, as @themistoklik suggested, we can warn if any data points were removed due to missing values -- that is, if an attribute has some missing values, but at least one value is defined.

I don't thing that marking the attributes with missing values in advance (say in the combo) would be practical. If the data set has missing values, a large number of attributes would have them and marking those wouldn't be so useful.

For large data, read directly from database, the widget would stay as it is. We can't check whether all data is missing, and for plotting we use sampling anyway.

**Comment by wadhwasahil** [comment]
@janezd . If I have the attribute name "age", so how can I print all the values of "age" in the dataset?
Also, how to check if there is a missing value? Do you have any pre defined function for it?

**Comment by wadhwasahil** [comment]
@janezd Please can you see my PR and suggest changes.
1. How to remove warnings from the console if I had posted it. I tried graph.update().
2. I have considered only those attributes with Nan or "?" values and generated warnings.

Waiting for your reply.
Thanls

**Comment by kernc** [comment]
> If I have the attribute name "age", so how can I print all the values of "age" in the dataset?

The following is standard in numpy, pandas, and works with Orange as well:
```python
print(data[:, 'age'])   # all rows, 'age' column
```

**Comment by wadhwasahil** [comment]
Please see my PR and suggest  changes @kernc

**Comment by wadhwasahil** [comment]
@kernc Have a look at the new PR :)

**Comment by ajdapretnar** [comment]
Fixed with PR #1230. Closing the issue. Thank you everyone for trying to solve it and sorry for making it so complicated. :smile:
