### ISSUE TITLE
Meta attributes in Sieve and Mosaic

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#1049]
Sieve and Mosaic do not let the user choose meta attributes. Add them to the combo.

**Comment by kwikadi** [comment]
Sieve's [layout](https://drive.google.com/file/d/0B4s3vRi7f8BsV1JIR1dMR2lESlk/view?usp=drivesdk)  (on master, I haven't tried other branches yet)  currently looks significantly different compared to other tools, and its look defined in the [orange docs](https://github.com/biolab/orange3/blob/965077fd4a296f44dcad73e4d246c79ef9ab7540/doc/visual-programming/source/widgets/visualize/sievediagram.rst) . Is this intended, and are the meta attributes also supposed to be laid out in a similar fashion?

**Comment by janezd** [comment]
> Sieve's layout (on master, I haven't tried other branches yet) currently looks significantly different compared to other tools, and its look defined in the orange docs . Is this intended, and are the meta attributes also supposed to be laid out in a similar fashion?

Meta attributes are supposed to be added to the same combo within the existing layout - not in a new combo. The layout does not matter (in principle, though the changes should of course be applied to the new layout, not the old one).

**Comment by janezd** [comment]
Meta attributes are supposed to be added to the same combo within the
existing layout - not in a new combo. The layout does not matter (in
principle, though the changes should of course be applied to the new
layout, not the old one).

Cheers,
       Janez
