### ISSUE TITLE
Numeric attributes in Sieve and Mosaic

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#1050]
If the data contains numeric attributes, Sieve and Mosaic show a warning that instructs the user to discretize them. The widget should discretize numeric attributes using a default discretization (4 quantiles, that is, 4 intervals containing the same number of data instances).

**Comment by RachitKansal** [comment]
@janezd  I would like to take up this issue, I have recreated it in my local machine and will send a PR soon.

**Comment by RachitKansal** [comment]
@janezd I have added more commits to fix the above issue. By mistake I added them to my old PR for issue #1051
So you can find these changes in PR #1053 

Sorry for the inconvenience

**Comment by themistoklik** [comment]
Hello @RachitKansal , @janezd  . I was working on the same issue with a fix similar to Rachit's, with the equal width option. I add these lines to owmosaic.py
```python
disc = Discretize()
disc.method = discretize.EqualWidth(n=4)
self.data = disc(self.data)
```
with the proper imports and I comment out the prompt to discretize.

When I run the application though ,using the Iris dataset ,the mosaic plot is not the same as the one I get if I put the file through a discretizer widget and then plot it. Namely, I can't get the variables to appear in the dropdown boxes ( ie sepal-width), I only get Iris. Am I missing something here?

**Comment by janezd** [comment]
This fix is wrong. It does the opposite from what we need.

This issue is about letting the user select numeric attributes in visualization. On the other hand, the output of the widget must stay numeric.

Discretizing the data immediately, before filling the combos, would solve the first part. But it would also change the output, which we don't want.

**Comment by RachitKansal** [comment]
Okay, I will just look into it.

**Comment by wadhwasahil** [comment]
hi @janezd . I am thinking of using One Hot encoding for discretization. Is it fine for you?

**Comment by wadhwasahil** [comment]
@janezd Since, there is already an option to discretize the numeric data using the widget, what is the need for doing it manually?
"This issue is about letting the user select numeric attributes in visualization." How does the user selects the attributes, using a widget? 
Could you please explain what do you actually need?
Thanks in advance.

**Comment by janezd** [comment]
What is actually needed is explained above.

You have a good question: why? To minimize the number of widgets. There's a balance between how "basic" do you want the widgets to be and how many widgets does the user need to put in a workflow. If a widget A is always preceded with B, the functionality of B should be integrated with A -- unless this requires that the whole GUI of B is included in A, too. There are of course cases where we're not sure where the line is; an example of that is the Predictions widget, which used to include a table, then we simplified it to just a few checkboxes, and then we saw that we always connect it to a table, so we re-added the table to Predictions.

But sometimes it's a clear cut. Mosaic and Sieve are examples of this. When I observe the attributes in Mosaic and Sieve I will always want to see the numeric attributes, too, so I will always add Discretization widget in front. If discretization is added to Mosaic and Sieve it does not affect the GUI at all. It does not make the widget more complicated, just more useful.

As I said - this was a good question, and I hope I provided a good answer. :)

**Comment by wadhwasahil** [comment]
Yeah. The answer was satisfactory. Has it been resolved?

**Comment by janezd** [comment]
No, not yet.

**Comment by wadhwasahil** [comment]
Could you provide some hint as how to proceede since the above described methods dont seem to work

**Comment by janezd** [comment]
See the later commits in https://github.com/biolab/orange3/pull/1053. Half of a problem is solved there. The interesting part - that of selection a subset of instances - is still open.

**Comment by wadhwasahil** [comment]
Can you please elaborate by selection of subset of instances.

**Comment by janezd** [comment]
In Mosaic and Sieve, if I select one or more rectangles in the plot, the corresponding data instances appear on the output. This works for discrete features. The solution in #1053 does not support this (yet). See #1053 for details.
