### ISSUE TITLE
Crash on color tool

### ISSUE THREAD

**Issue by DiscoRogers** [biolab/orange3#1055]
I have 100 rows, 124 fields, text and numeric.
When I try to load colors the widget crashes.

**Comment by kernc** [comment]
Can you share the data file?

**Comment by DiscoRogers** [comment]
[Data.xlsx](https://github.com/biolab/orange3/files/161307/Data.xlsx)

**Comment by DiscoRogers** [comment]
I found that if I filter out a few columns then there's no problem.  The problem is that the widget dialogue tries to color all of the columns at once, so it goes crazy slow and in the worst case, stops responding.  Maybe if you had to choose the columns that you wanted to color instead of coloring them all by default?

**Comment by janezd** [comment]
Thanks for identifying the problem. The palettes were supposed to be generated while they were being shown. PR #1069 should fix the problem.

**Comment by kernc** [comment]
Thanks for reporting.
