### ISSUE TITLE
Table not loading breast-cancer.tab

### ISSUE THREAD

**Issue by wadhwasahil** [biolab/orange3#1065]
When I try to load the file breast-cancer.tab in a data table format, the column under tumor size is showing missing values whereas they exist in the original file.
Why is it happening as all the other files tested by me are working/opening correctly?

**Comment by s-alexey** [comment]
It happens because of the `tumor size` column type. Just change the second line in the file 
from
d	d	d	**0-4 5-9**	0-2 3-5 6-8 9-11 12-14 15-17	d	d	d	d	d
to 
d	d	d	**d**	0-2 3-5 6-8 9-11 12-14 15-17	d	d	d	d	d

*note:* do not remove tab spaces around 0-4 5-9

**Comment by wadhwasahil** [comment]
oh. Thanks (y) .
But how does system knows which intervals are for which column?
I mean, **0-4 5-9** are for tumor-size and **0-2 3-5 ..... 15-17**  are for inv-nodes. They are only seperated by spaces while **d** are seperated by a tab. So, how does system knows which intervals are for which column?

**Comment by s-alexey** [comment]
Look carefully, there is a tab between 5-9 and 0-2.

**Comment by wadhwasahil** [comment]
Okay. got it!

**Comment by lanzagar** [comment]
Nice catch!
However, I would not close this issue yet - the fix has not been applied in the Orange repository yet.
Maybe one of you wants to create a pull request with it?

**Comment by lanzagar** [comment]
Thank you both for noticing the issue and fixing it.

**Comment by wadhwasahil** [comment]
I have also generated PR for this. LOL
