### ISSUE TITLE
Report for Confusion Matrix

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#1077]
Report for Confusion Matrix widget looks strange. Implement gridlines, color correct and misclassified instances accordingly (as in the widget), variable names and sums in bold.

**Comment by smkuls** [comment]
Is this fine? [owconfusionmatrix.py ](https://github.com/biolab/orange3/blob/master/Orange/widgets/evaluate/owconfusionmatrix.py) is internally calling report_table which is used by other widgets too (such as Test Learners). If I modify it to add colors, it will affect the others (right now I just added an optional border parameter to the call). I can customize it individually for Confusion Matrix but I don't know if that will be a good idea.

![image](https://cloud.githubusercontent.com/assets/5889240/13665553/1ac872a4-e6d3-11e5-93ee-f9acd17d73d7.png)

**Comment by wadhwasahil** [comment]
how did u make the test bold? Can you provide the line of change?

**Comment by smkuls** [comment]
I updated the report_list function in [report.py](https://github.com/biolab/orange3/blob/master/Orange/canvas/report/report.py)

` def report_list(data,
                        header_rows=header_rows, header_columns=header_columns,border=border):
            if border:
                cells = ["<td style=\"border : 1px solid black\">{}</td>", "<th>{}</th>"]
            else:
                cells = ["<td>{}</td>", "<th>{}</th>"]
            return join("  <tr>\n    {}</tr>\n".format(
                join(cells[rowi < header_rows or coli < header_columns]
                     .format(fmtnum(elm)) for coli, elm in enumerate(row))
            ) for rowi, row in enumerate(data))
`

**Comment by wadhwasahil** [comment]
@smkuls `self.report_table(
                "Confusion matrix for {} (showing {})".
                format(self.learners[index],
                       self.quantities[self.selected_quantity].lower()),
                self.tablemodel, header_rows = 2, header_columns =2)`
Is this you mean?

**Comment by wadhwasahil** [comment]
Some One please check my PR and suggest changes. 2 issues are being solved in the above PR of mine. 
Thanks in advance.

**Comment by smkuls** [comment]
@wadhwasahil  If you ask somebody for a fix then you don't include that in "your" pull request. Have some courtesy.

**Comment by wadhwasahil** [comment]
@smkuls . I think we are here to help each other. If you want I will change the (2,2) line and do something different. I don't know what offends you. After all we are a community and here to share our thoughts and ideas. 
#1065 I created this issue and submitted a PR after some time before that someone had merged his PR. I didn't tell the people to merge mine as the overall aim was to contribute. 
So, please be polite and patient. Submit your PR as well and get it merged if that what's make you happy.

**Comment by smkuls** [comment]
@wadhwasahil - Had you submitted it on your own I wouldn't have had any issue at all (which is what I presume happened with you). I agree we are here to help each other but what we aren't here for is to take credit for somebody else's efforts. The least you could have done was to say "thanks" or asked if you could include it in your PR. 

Anyway, go ahead! Both of us have loads of issues to fix. Peace!

**Comment by smkuls** [comment]
Btw an advice, the instructions mention that you should address only one issue in a single PR. See the [post](https://groups.google.com/forum/#!topic/orange-gsoc/mcPVaSmvGJ4).

**Comment by wadhwasahil** [comment]
I will fix it.

**Comment by janezd** [comment]
Please be patient. First, not everybody lives in the same time zone. Do not expect an answer in one hour - or two or five - although we try. Pull requests sometimes need a month to be checked. Of course, for potential GSoC students we're doing it as fast as we can and we answer most in matter of hours, but we cannot rush things and merge changes that are not carefully tested.

It would be a huge help if PRs were well structured - with sensible commits (squashed when necessary) and only a single issue per PR. It takes a lot of time to just distinguish what belongs where.

**Comment by ajdapretnar** [comment]
Fixed via #1309.
