### ISSUE TITLE
Report for Stochastic Gradient Regression

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#1078]
Implement Report function in Stochastic Gradient Regression as in other widgets. Report on learner name, model parameters and data.

**Comment by iamved** [comment]
issue almost fixed,will send PR soon.

**Comment by wadhwasahil** [comment]
I am facing one problem here. When I open the Stochastic Gradient Regression widget, it doesn't fit on my laptop and I can't see the `Apply` button on the screen.
How to fit the widget to the screen or make the widget scrollable?

**Comment by iamved** [comment]
I am also facing the same issue, Please tell us how to fit the widget to screen.

**Comment by wadhwasahil** [comment]
I have done it. Will send the PR soon.

**Comment by kernc** [comment]
@wadhwasahil, @iamved On GNU/Linux standard window managers (Gnome and quite possibly Unity, KDE, Xfce, Lxde, ...), there's a setting, normally enabled by default, to move the window by holding `Alt` and left-clicking and dragging anywhere on the window surface.

**Comment by wadhwasahil** [comment]
I did it on unix :smile:
