### ISSUE TITLE
Report for Univariate Regression

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#1080]
Implement Report button function in Univariate Regression as is in other widgets (e.g. Scatter Plot widget). Report on learner name, model parameters and data.

**Comment by iamved** [comment]
I have been done with learner name and data but facing issue with adding parameters. Please tell me how to add variable such polynomial expansion and Target. I tried for both but getting some errors.

**Comment by janezd** [comment]
See how it's done in #1092. Also, see comments in #1091.

**Comment by iamved** [comment]
sorry I forget to delete the comment and the issue was solved already at that point of time.
