### ISSUE TITLE
Report button on Distances widget

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#1081]
Implement Report button function in Distances widget as is in other widgets (see Scatter Plot widget). Report on the used parameters.

**Comment by wadhwasahil** [comment]
There is no report button on Scatter Plot Widget. So, do we have to add that?

**Comment by janezd** [comment]
There is report on scatter plot. You meant scatter map? Scatter map will be removed, so no point in improving it.

**Comment by wadhwasahil** [comment]
i have added it to distance transformation widget.
