### ISSUE TITLE
Remove.py: Purge meta attributes

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#1084]
Purging should be applied also to meta attributes (constant and unused metas). See Purge Domain widget for example.

**Comment by kwikadi** [comment]
I think I've done this, but just to be sure, the GUI should look like [this](http://imgur.com/1qymGfg), correct?

**Comment by kwikadi** [comment]
I'm slightly confused, sorry for the multiple comments, but I'm not sure what the issue is, exactly.
https://github.com/biolab/orange3/commit/fa1ebea3128fc6ceb65a9d0245b0826ecda62842
This commit has already added support for meta vars in remove.py. What, then, is the problem to be solved?

**Comment by ajdapretnar** [comment]
@kwikadi Purge Domain widget does not remove unused or constant meta attributes. It needs to include the option for removing it.
