### ISSUE TITLE
Tutorials: open tutorials with the intended data set

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#1086]
Check tutorials and make sure they open with the intended data set. Now, they open with the last file that was loaded with the File widget. 
Run Orange with `--clear-widget-settings` and load a tutorial to see the proper data set.

**Comment by shark-S** [comment]
hello @ajdapretnar  we can use parse and set "python -m Orange.canvas"  to  "python -m Orange.canvas --clear-widget-settings" so  when we type  "python -m Orange.canvas" it  automatically work like "python -m Orange.canvas --clear-widget-settings" . Is this okay ??

**Comment by kernc** [comment]
If that's your proposed solution, I don't think it's ok. `--clear-widget-setting` clears all settings and widgets' state. We can't reset those every time Orange starts?

**Comment by shark-S** [comment]
@kernc when user make new file then data set will load by them manually and when workflow is opened then it will open its default dataset and when we apply this configuration then tutorials will also opened with there intended data set.it this right??

**Comment by kernc** [comment]
Actually, @shark-S, I'm not sure I understand or can reproduce the issue here. The tutorials seem to open with their intended data set. For me at least. Let's wait for @ajdapretnar to give some feedback.

**Comment by shark-S** [comment]
okk @kernc  .

**Comment by ajdapretnar** [comment]
For me, the issue persists. When I load my own data set in the widget, then discard the workflow and open the tutorials, the File widget in the tutorials workflow is empty. If I have previously loaded data from url, the url is remembered and the data from it loaded in the tutorials' File widget. I believe this is not the desired behaviour.

Also, *Exploring the Latent Factors* tutorial reports an error, perhaps this could be fixed within the same PR.

**Comment by kernc** [comment]
@ajdapretnar, can confirm the issues, thanks!

**Comment by shark-S** [comment]
@ajdapretnar correct me if anypoint i am wrong. when we load tutorial it data set it  is  not loaded automatically we have to load it manually. and every time when i open it i have to set data manually.
Working on it .

**Comment by ajdapretnar** [comment]
Yes. Not sure whether to leave the File widget in 'Classification Tree' empty as a part of the tutorial on how to load the data or not, but all other tutorials should be loaded with the suggested or optimal data set.
The fix should apply only to the **File widget**, all other widgets should be set to defaults, allowing the user to follow the tutorials on her own.

**Comment by shark-S** [comment]
Yeah thanks  understood.Working on it.Sending a PR soon.

**Comment by shark-S** [comment]
@ajdapretnar  I have found that there is no error in code it is mistake in workflow if we improve them then it work as proper and when we open a tutorials it gives no error.I have send a PR please guide me.
