### ISSUE TITLE
Preprocess: add a random selection of features

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#1087]
Add 'Random feature selection' to Preprocessor widget. It should be similar to 'Select relevant features' , but implemented as a separate preprocessor. It should allow a selection per proportion or a number of features (again, see 'Select relevant features').

**Comment by shark-S** [comment]
can we also implement 'Best fit selection  feature' for that model ?

**Comment by ajdapretnar** [comment]
What do you mean by 'best fit'? Relevant features can already be selected in a different preprocessor. Here we only need random selection.

**Comment by shark-S** [comment]
okk . I thought of if user don't have understanding of model then we can represent of Best fitting model  which give good accuracy .But here is no need of it ??

**Comment by wadhwasahil** [comment]
Don't we have randomize option in the pre-process widget?

**Comment by ajdapretnar** [comment]
Randomize doesn't randomly select a subset of features, it randomly switches classes, metas or features. Please give a look at what these preprocessors do in order to understand what the tasks requires.

**Comment by matevzkren** [comment]
Submitted a pull request at https://github.com/biolab/orange3/pull/1112 ..

Hopefully, this is what you had in mind (the 'redesigned' icon included). Tips & corrections appreciated!
