### ISSUE TITLE
Hierarchical Clustering widget: show group ID on cluster selection

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#1088]
Dendrogram in Hierarchical Clustering widget should display cluster IDs when clusters are selected. Think about where to put the label: onto the cluster, to the left, or to the right of the cluster. TBD.

**Comment by kumargaurav2596** [comment]
how about placing the cluster id vertically , starting from the point at which branches intersect 
or
making the cluster id follow the mouse pointer as long as a particular cluster remains in focus.

which one sounds better?

**Comment by janezd** [comment]
If I understood your first suggestion correctly - you meant this?
![labels](https://cloud.githubusercontent.com/assets/2387315/13702962/8387cd2a-e792-11e5-8067-b84f5d96ad56.png)
I like it.

**Comment by kumargaurav2596** [comment]
Great, then I guess I will go with this one only.

**Comment by kumargaurav2596** [comment]
Any other suggestion?

**Comment by janezd** [comment]
While you're at it, could you also add cluster id's as tooltips?

**Comment by kumargaurav2596** [comment]
I am a little new to orange, what exactly is a tooltips?

**Comment by kumargaurav2596** [comment]
Also should I put cluster id's permanently at each intersection or should they be visible as long as its respective cluster is in focus.

**Comment by janezd** [comment]
Permanently.

Tooltip is a text that appears when the mouse is hovering over an object.

**Comment by kumargaurav2596** [comment]
Correct me if I am wrong, their is no predefined cluster id declared for each cluster. So I have to put C1,C2,C3... in level order tree traversal.

**Comment by kernc** [comment]
I think it should follow the coloring.

**Comment by ajdapretnar** [comment]
@kumargaurav2596 Is this already included in any PR?

**Comment by kumargaurav2596** [comment]
@ajdapretnar  I have implemented the "c1, c2, c3 ..." leveling but it gets really messy specially a the lower levels due to lack of space. Can we rethink of the naming style.

**Comment by kernc** [comment]
Can you show an example image?

**Comment by kumargaurav2596** [comment]
![clustering](https://cloud.githubusercontent.com/assets/10504619/14710107/b3281ff6-07f1-11e6-9c5a-f943eb67646e.png)

Their isn't enough space to squeeze the levels in the lower branches of dendrogram.

**Comment by janezd** [comment]
It wasn't meant like this. 

- If the user selects some clusters, mark them.
- If the user sets a threshold (e.g. by dragging the cut-off line), mark the resulting clusters.

We can assume that there would not be more that 99 clusters. If there are more (which does not make sense, though), don't show labels.

I like bigger labels -- at least in the picture at the beginning of the conversation they looked nice. If needed, use a larger font when there are <= 9 clusters, and smaller when there are <= 99.

Don't place the labels at the "roots" of subclusters, but above and to the left, like in the picture.

You can also assume that the labels won't appear at the far right.

**Comment by kumargaurav2596** [comment]
sorry, I guess I misunderstood last time, I am working on it...

**Comment by ajdapretnar** [comment]
@kumargaurav2596 Is the fix perhaps ready? If you need any help, feel free to ask.

**Comment by ajdapretnar** [comment]
@janezd Is this still something we want implemented or did we decide not to go through with it?

**Comment by janezd** [comment]
We want this, but it's not trivial and it requires some designing (possibly with trial and error). This may not be the optimal test task for GSoC.
