### ISSUE TITLE
Setting Handler: doesn't overwrite super class settings.

### ISSUE THREAD

**Issue by s-alexey** [biolab/orange3#1105]
Settings from subclass are replaced by super class ones.
##### Steps to reproduce the behavior

Create Regression Tree (or SVM Regression) widget and check it default name.

**Comment by shark-S** [comment]
@s-alexey  its default name is "SVM Regression". can you explain a little bit more?

**Comment by s-alexey** [comment]
It's probably my fault. As I have figured it out settings were pickled (.local/Orange/widges/) with wrong names (but I don't know why). So default values were taken from pickle file.

**Comment by kernc** [comment]
> As I have figured it out settings were pickled (.local/Orange/widges/) with wrong names (but I don't know why).

Possibly something to do with https://github.com/biolab/orange3/pull/1072?

**Comment by s-alexey** [comment]
@kernc, probably not. It's actually a bug.

**Steps to reproduce the behavior:**
- Remove `Orange.widgets.classify.owclassificationtree.OWClassificationTree.pickle` from `~/.local/share/Orange/*/widgets/`
- Create Classification Tree widget.
- Select gini method.
- Delete widget (save settings)
- Create Regression Tree widget.

**Comment by astaric** [comment]
I have created a PR with the fix. Can you try it and see if it fixes your problem?

**Comment by s-alexey** [comment]
@astaric, it doesn't crash now.
