### ISSUE TITLE
Add ReliefF and FCBF to Preprocessor

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#1126]
Measures from Rank widget (ReliefF and FCBF) should also be available in Preprocessor widget for 'Select Relevant Features' preprocessor. Add them to the Score dropdown.

**Comment by shark-S** [comment]
@ajdapretnar task is implement Relief  and FCBF in classification like knn, naive-bayes etc.
I have made code to implement Relief and FCBF(started) but problem is icons ? can you provide it? or have to choose my self?

**Comment by kernc** [comment]
This task is about adding ReliefF and FCBF (both implemented in Orange.preprocess.score) to the relevant combo box in the Preprocess widget. @shark-S If you need icons, you're free to find some suitable ones. :smile:

**Comment by shark-S** [comment]
thanks for reply @kernc . can we use QtDesigner (convert *.ui to python code(*.py) then implement in orange) you know it is time saving?

**Comment by shark-S** [comment]
@kernc  and @ajdapretnar look at [PR](https://github.com/biolab/orange3/pull/1133). if anything wrong guide me.

**Comment by janezd** [comment]
There was a question about Qt Designer, but now it disappeared from the thread. Anyway: don't use it. Perhaps for drawing the interface, but the actual interface must be written manually, using functions from module `gui`.

One reason is that this lets Orange save and load settings; if you use Qt Designer, it will save you some work initially, but you'll pay the price later on. The other reason is that all widgets are currently coded manually.

**Comment by shark-S** [comment]
Thanks for reply.
    I have tried to use Qt Designer (for another work). It is fast to
design but then after as you said it more time consuming. :(

**Comment by kernc** [comment]
Fixed in https://github.com/biolab/orange3/commit/0cc7e419d85f6c8434e5b0247d3198aa79d471bc. Thanks!
