### ISSUE TITLE
Icons missing in Orange Canvas

### ISSUE THREAD

**Issue by MEL27** [biolab/orange3#1143]
##### Orange version

3.3.1.dev0+5d39ea2

##### Expected bahavior
Icons showing up.

##### Actual behavior
Icons didn't show up, except the ones in Help.

##### Steps to reproduce the behavior
Launch orange-canvas

##### Additional info (worksheets, data, screenshots, ...)

OS: Windows 10 Home
Orange installed from installer from official website

![screenshot](https://cloud.githubusercontent.com/assets/10842148/14145440/6f91884a-f6c6-11e5-90b2-ad5b0020101c.png)

**Comment by ajdapretnar** [comment]
@MEL27 Thank you very much for such precise description!
I'm running the same version on Win8 and am not experiencing the same issue.
Perhaps @thocevar can check for Win10?

**Comment by kernc** [comment]
Does this help?

https://stackoverflow.com/questions/34629635/orange-canvas-does-not-show-any-icon/

**Comment by MEL27** [comment]
@kernc
Yes, it does. After I created a qt.conf according to the instruction, the problem is solved.
I didn't see the answer when I searched. Thanks for the link!

**Comment by MEL27** [comment]
Instead of adding a qt.conf, using `QtCore.QCoreApplication.addLibraryPath('./Lib/site-packages/PyQt4/plugins')` may be a better solution. [(from stackoverflow)](http://stackoverflow.com/a/23525640)

**Comment by kernc** [comment]
Thanks!

@ales-erjavec, can we use this?

**Comment by ajdapretnar** [comment]
@kernc @ales-erjavec Are we using the above fix? Perhaps @MEL27 you could submit a PR?

**Comment by MEL27** [comment]
I've submitted a pull request #1194 . The hack is dirty given that we still don't know what exactly happens under the hood. But yeah it works.

**Comment by kernc** [comment]
Should be fixed now. Thanks again!
