### ISSUE TITLE
Issue when installing network and spark add-on without a compiler

### ISSUE THREAD

**Issue by roya0045** [biolab/orange3#1161]
Greetings,

I installed most of the add-ons that were available but when I try to install the Network and the Spark add-ons(from Orange and from the command line), I end up getting an error telling me that Microsoft Visual C++ 10 is needed ( mostly for the file vcvarsall.bat). I have MinGW and Notepad++ installed, I don't know if those two could help or if I absolutely need to install VisualStudio in order to use those two add-ons.

**Comment by ajdapretnar** [comment]
@roya0045 I solved this by adjusting the compiler (used MinGW).
When running setup, enter:
python setup.py build_ext -i --compiler=mingw32 install

You might also have to add C:\MinGW\bin to PATH (system-wide) before compiling.

**Comment by ajdapretnar** [comment]
@roya0045 Does it work now? If so, could you please close the issue?

**Comment by astaric** [comment]
Add-on installation issues should be raised on their issue trackers.

Orange3-Network addon now provides binary packages for windows on pypi, so it should be able to install without compiler. Orange3-Spark issue tracker is available here: https://github.com/jamartinh/Orange3-Spark/issues
