### ISSUE TITLE
Problem reading Weka .arff files (Orange 2.7, with solution)

### ISSUE THREAD

**Issue by mrihtar** [biolab/orange3#1172]
##### Orange version
Orange version: **2.7.8.dev-a238ebf**  (git revision: a238ebf)

##### Expected behavior
Widget 'File' should be able to read Weka .arff files as defined by Weka, including attributes of type string and proper parsing of single/double quoted values, which could include delimiter (',').

##### Actual behavior
The code for doing this (**Orange/data/io.py**) has several bugs:
- cutting off everything after '%' (comment) without checking if '%' is inside quotes
- splitting values on ',' without checking if ',' is inside quotes
- ignoring '"' as possible quote in attributes
- not checking if index in value array is overflown

##### Steps to reproduce the behavior
Try to read in the following .arff example:
```
@relation test  
@attribute "Par 1" string
@attribute "Par 2 (%)" numeric
@attribute "Par 3" date "M/d/yyy"
@data
"43-47%17,5", 23.5,"4/1/2015"
"55-60%18", 19.1,"12/11/2015"
```
Result should be:  
- **File** widget:  
  2 data instances, 2 features, 0 metas  
  Class is neither discrete nor continuous.
- **Data Table** widget:  
<table><tr>
<th></th><th>Par 1</th><th>Par 2 (%)</th><th>Par 3</th>
</tr><tr>
<td>1</td><td>43-47%17,5</td><td>23.5</td><td>4/1/2015</td>
</tr><tr>
<td>1</td><td>55-60%18</td><td>19.1</td><td>12/11/2015</td>
</tr></table>

##### Solution
Attached is fixed **io.py** which fixes most of these bugs (except % inside quotes, which is kind of circumvented :-).

[io.py.txt](https://github.com/biolab/orange3/files/213890/io.py.txt)

**Comment by kernc** [comment]
This issue should probably better be raised on Orange 2's repository: https://github.com/biolab/orange
You might even want to submit the patch as a pull request?

**Comment by mrihtar** [comment]
Thanks! There are so many repositories under biolab I just didn't see the old repository.

**Comment by kernc** [comment]
Well, there's some brief mention of it in the README. :stuck

**Comment by kernc** [comment]
Indeed. No problem. Thanks for your willingness to contribute! :smiley:
