### ISSUE TITLE
Integrate Orange with OpenML.org

### ISSUE THREAD

**Issue by brylie** [biolab/orange3#1184]
The OpenML.org website provides buttons to export flows for Weka, MOA, and RapidMiner. E.g.
http://www.openml.org/t/1940

As an Orange user, how do I import a data-flow from OpenML.org into an Orange data flow graph?
# Related issues
- #1264 OpenML Authentication widget
- #1265 OpenML Data Set widget

**Comment by kernc** [comment]
We don't support loading Weka, MOA, or RapidMiner projects. Orange has its own workflow scheme (.ows). Incidentally, OpenML doesn't (yet) support Orange. If you care, perhaps you can write them and express your interest? :smiley:

**Comment by brylie** [comment]
@kernc good suggestion. There is some middle ground here it seems.

**Comment by brylie** [comment]
I posed the Orange Data Mining + OpenML question on the [OpenML discussion list](https://groups.google.com/forum/#!topic/openml/W_QeCy3BP8w), and got a response:

> We definitely hope to support Orange, as well as other Python libraries. We have a Python interface under development: http://www.openml.org/guide#!python

> It currently allows you to download data, run experiments, and upload results. We also have some examples in scikit-learn. What is does not yet support are Orange-specific procedures to export Orange workflows.

> As far as I know nobody is currently working on the latter but of course we greatly encourage work in this direction and will help as much as we can. It just takes someone (or a few people) to get this started.

**Comment by kernc** [comment]
Thanks!

> It just takes someone (or a few people) to get this started.

Would you like to work on it?

**Comment by brylie** [comment]
Well, I am rather new to the entire ML realm, having just started learning Orange in the past couple of weeks. I can certainly try, but may need a someone to break the task into small chunks.

**Comment by brylie** [comment]
I got basic approval to pursue this task at work, so can dedicate some time to the task given guidance.

**Comment by brylie** [comment]
One starter idea is to create a UI widget that can be used to enter OpenML credentials.

**Comment by brylie** [comment]
Also, where can I find instructions describing how to set up a development environment? I am running Linux, with primary experience in JavaScript development.

**Comment by cheral** [comment]
https://github.com/biolab/orange3/wiki/Installation-on-Ubuntu-13.04
http://orange-development.readthedocs.org/index.html
http://orange.biolab.si/docs/

**Comment by kernc** [comment]
Actually, these are the up-to-date instructions: https://github.com/biolab/orange3#installing If you seem to be missing any packages, install them from your distribution channels.

**Comment by brylie** [comment]
I have followed the "how to install for development" instructions, and am browsing the source. Where would be a good place to define OpenML related widget(s)? How do I define UI elements (e.g. is there a tool such as QtCreator or other approach)?

**Comment by brylie** [comment]
Basically, this task is a lot of "uphill" for me. I am willing to learn, but have very little experience here. There is also very little documentation for me to lean on.

**Comment by brylie** [comment]
One counter-example would be the Node-RED platform, where there is relatively clear documentation about creating new nodes:
http://nodered.org/docs/creating-nodes/first-node

**Comment by rahulroxx** [comment]
@brylie You can look at Documentation at [](http://orange.biolab.si/docs/)

> How do I define UI elements (e.g. is there a tool such as QtCreator or other approach)?

 Please don't use QtCreator or QtDesigner for coding widgets , as it will hard at later point of time when dealing with loading and saving settings in Orange . You can use them to design layout of the widget . but widgets should be coded manually .  
You can use functions from **gui.py ** 
[]( https://github.com/biolab/orange3/blob/master/Orange/widgets/gui.py)

**Comment by brylie** [comment]
I am working through the widget development [getting started tutorial](http://orange-development.readthedocs.org/tutorial-cont.html), but cannot get the example widget to appear. I have done the following:

1. added the `orange-demo` folder inside `/orange3/Orange/widgets/`
2. created the file structure as outlined in that document
  - orangedemo
    - icons
      - `DataSamplerA.svg`
    - `__init__.py`
    - `OWDataSamplerA.py`
  - `setup.py`
3. Add the following to `orange-demo/setup.py`:
```py
from setuptools import setup

setup(name="Demo",
      packages=["orangedemo"],
      package_data={"orangedemo": ["icons/*.svg"]},
      classifiers=["Example :: Invalid"],
      # Declare orangedemo package to contain widgets for the "Demo" category
      entry_points={"orange.widgets": ("Demo = orangedemo")},
      )
```
4. Add the following to `orange-demo/orangedemo/OWDataSamplerA.py`:
```py
import sys
import numpy

import Orange.data
from Orange.widgets import widget, gui

class OWDataSamplerA(widget.OWWidget):
    name = "Data Sampler A"
    description = "Randomly selects a subset of instances from the data set"
    icon = "icons/dice.svg"
    priority = 10

    inputs = [("Data", Orange.data.Table, "set_data")]
    outputs = [("Sampled Data", Orange.data.Table)]

    want_main_area = False

    def __init__(self):
        super().__init__()

        # GUI
        box = gui.widgetBox(self.controlArea, "Info")
        self.infoa = gui.widgetLabel(box, 'No data on input yet, waiting to get something.')
        self.infob = gui.widgetLabel(box, '')

    def set_data(self, dataset):
        if dataset is not None:
            self.infoa.setText('%d instances in input data set' % len(dataset))
            indices = numpy.random.permutation(len(dataset))
            indices = indices[:int(numpy.ceil(len(dataset) * 0.1))]
            sample = dataset[indices]
            self.infob.setText('%d sampled instances' % len(sample))
            self.send("Sampled Data", sample)
        else:
            self.infoa.setText('No data on input yet, waiting to get something.')
            self.infob.setText('')
            self.send("Sampled Data", None)
```
5. run `pip install -e .` (both with and without `sudo`)
6. run `python -m Orange.canvas`

I do see that a `Demo.egg-info` directory was created when running without `sudo`.

Where might I be going wrong?

**Comment by rahulroxx** [comment]
@brylie You can find your custom widget as shown below , 
![screenshot from 2016-04-22 08 10 01](https://cloud.githubusercontent.com/assets/16189966/14745976/55efdb14-0862-11e6-9fff-b34a92ce4619.png

Custome Widgets are under  Demo in my case .

**Comment by kernc** [comment]
If you run `python -m Orange.canvas -l 4`, do you get any errors? Your `orange.widgets` entry point is not a tuple, rather a single value enclosed in braces — missing a comma there.

**Comment by brylie** [comment]
Ok, thanks @kernc. For what it's worth, that code comes directly from the [demo widget tutorial](http://orange-development.readthedocs.org/tutorial-cont.html#a-package-named-demo)

**Comment by brylie** [comment]
@kernc given the current entry points:

```py
entry_points={"orange.widgets": ("Demo = orangedemo")}
```

Should the `entry_points` line be changed to this?

```py
entry_points=("orange.widgets", ("Demo = orangedemo"))
```

**Comment by brylie** [comment]
After some searching (and following a broken link in the Orange documentation), I found an example of an `entry_points` definition. So, changing the code as follows seems to resolve the problem:

```py
entry_points={"orange.widgets": "Demo = orangedemo"}
```

**Comment by ajdapretnar** [comment]
@brylie How's it going with the widget development? If there's something we need to improve in the documentation (and I'm sure there is), I'd be glad to hear it. Any contribution to a better documentation is highly appreciated. :star:

**Comment by brylie** [comment]
@ajdapretnar thanks for following up. I will keep working on a simple widget for now, perhaps an OpenML authentication widget that has text field(s) for authentication details. The authentication details can then be passed into other OpenML related widgets.

**Comment by brylie** [comment]
As an aside, there is a related ML project called [TPOT](http://rhiever.github.io/tpot/). In the TPOT repository, there are two ideas related to TPOT + Orange integration:

- https://github.com/rhiever/tpot/issues/51
- https://github.com/rhiever/tpot/issues/137

**Comment by ajdapretnar** [comment]
@brylie Sounds great! When you have a PR ready, submit it and our folks here will review it. We really appreciate all the enhancements to Orange. :heart: Once you're done with the widget, you are very welcome to write a guest blog for us on how the development went and how the widget can be used for OpenML tasks.

**Comment by brylie** [comment]
I will open an issue to track the "OpenML Authentication" widget development.

**Comment by brylie** [comment]
I renamed this issue to indicate that it is a high-level issue. I updated the issue description with a link to the first sup-task: #1264 OpenML Authentication widget

**Comment by joaquinvanschoren** [comment]
Hi, I just noticed this thread. Great that you want to integrate OpenML and Orange. Let me know if you need any help from the OpenML side. You're also welcome to one of our next hackathons to speed things up :).

**Comment by brylie** [comment]
@joaquinvanschoren when/where are your upcoming hackathons?

**Comment by joaquinvanschoren** [comment]
Next one is the last week of February (Feb 27 - Mar 30) in Munich.
The one after that will be the Lorentz Center (Leiden) early September.
We're planning one at EMBL in Heidelberg in between, but no details yet.

**Comment by brylie** [comment]
Cool, I am in Finland, so might be able to 'hop the Baltic' for a hackathon in Germany. Any plans of visiting, for instance, Helsinki?

**Comment by joaquinvanschoren** [comment]
You mean me personally?
If you want to organize an OpenML Hackathon in Helsinki, that would also be
great :).

**Comment by janezd** [comment]
In the interest of keeping the list of issues at manageable size, I'm closing this one, but keeping #1265. This one is too complicated and general, and nothing substantial happened in 2.5 years, while #1265 is small enough to be doable, and I believe the OpenML repository is big and well-organized, so it's worth investing some time into it eventually.
