### ISSUE TITLE
Is there any webservice to get the OrangeHRM functionalities ?? So that I can use it in my java program.

### ISSUE THREAD

**Issue by bishnu-zwayam** [biolab/orange3#1222]

**Comment by kernc** [comment]
Sorry, this is not OrangeHRM. Their website, including the issue tracker, is [on SourceForge](https://sourceforge.net/projects/orangehrm/).
They also offer a [trial](https://www.orangehrm.com/orangehrm_hrms_hris_free_trial.php) on their hosted solution. You can deploy the open-source distribution to any supporting PHP hosting, including [free ones](https://www.google.si/search?q=free+php+hosting).
