### ISSUE TITLE
Big Feature request: bayesian belief networks

### ISSUE THREAD

**Issue by wibrt** [biolab/orange3#1243]
Not present in orange at the moment,
but it would be a nice feature:
https://en.wikipedia.org/wiki/Bayesian_network
for example http://netica.org/

**Comment by janezd** [comment]
This would indeed be nice, but in three years nobody signed up for it, and there is no interest within the core group to add it. We'll be happy if somebody implements it (perhaps as an add-on?), but keeping this on the list of issues doesn't increases the chances -- anybody who ventures into such a big project will do so out of his personal interest.
