### ISSUE TITLE
Feature request: re-haul Heat map visualization

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#1256]
Writing this as a sum up of a longer feature request from a user.
1. Extend the choice for color scale. E.g. the user would like to define the color for the lowest, highest and zero value separately. 
2. Enable fine-adjusting the color scale (i.e. color 'slope').
3. Implement search (for a variable) and display the result it in the visualization. Also enable column selection that could be used as an output.
4. Implement zoom for heat map.
5. Add colored bars on the side of rows and columns to display data profile (e.g. tumor properties or proteins per group). Could follow this example: http://www.broadinstitute.org/cancer/software/GENE-E/
6. Prettify the visualization. (highcharts?)

**Comment by markotoplak** [comment]
We will improve the display of colors in #3884.

**Comment by ajdapretnar** [comment]
I think this requires a bit more explanation.

1. I am not sure we would like to go with this. Probably up for debate.
2. This is already done in Gamma option.
3. This is what Select Columns is for.
4. We would refrain from this. If there is a really good use case, we might reconsider it.
5. Mean for rows is already implemented. Not sure if we wish to add mean for columns?
6. Unlikely to happen anytime soon. Especially not with Highcharts due to licensing.

**Comment by janezd** [comment]
Thanks Ajda; I'm just finishing my comment. :) Mostly the same as yours.

I've looked into this widget. It is a complicated combination of the dendrogram component from the Hierarchical clustering and fancy layouts on graphics scene with some complicated sizing.

1, 2. @markotoplak will look into colors (see #3884). 
3. Searching for variables would complicate the interface and the code; I guess Select columns will have to do.
4. Zooming will/would require total rehauling of how the graphics scene is put together; this can be a part of #1745, so I've put a notice there.
5. Row profile is already shown, column profile fits into #1745, too.
6. It's indeed not nice, but highcharts' license is incompatible with Orange's. We also don't want to draw bitmaps in javascript.
