### ISSUE TITLE
OpenML Data Set widget

### ISSUE THREAD

**Issue by brylie** [biolab/orange3#1265]
# User story

```
As a researcher
I would like to import an OpenML data set into Orange
so that I can easily integrate the data into my machine learning workflow
```
# Feature

Add a widget that allows an end-user to select a [data set from OpenML.org](http://www.openml.org/search?type=data&from=200). The widget should output the selected dataset into an Orange canvas data-flow, perhaps as an `Orange.data.Table`.

**Comment by janezd** [comment]
Issue moved to #4090.
