### ISSUE TITLE
Not Importing the Orange.multilabel.MLkNNLearner

### ISSUE THREAD

**Issue by bhaveshoswal** [biolab/orange3#1280]
##### Orange version
3.3.4.dev0+b34afd8

>>>k = Orange.multilabel.MLkNNLearner(k=5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'multilabel'

**Comment by ajdapretnar** [comment]
The example is from the documentation for Orange 2. Please refer to the documentation for Orange 3: http://docs.orange.biolab.si/3/data-mining-library/reference/classification.html#k-nearest-neighbors

All the documentation can be found here:
http://docs.orange.biolab.si/3/data-mining-library/

**Comment by bhaveshoswal** [comment]
Yes that's write actually i wanted the ML-kNN implementation for Multi Label Classification and that is in Orange 2.7.8 and not in Orange 3.x.x

**Comment by ajdapretnar** [comment]
@bhaveshoswal Yes, Orange 3 indeed does not yet have all the features of Orange 2. If you need ML-kNN implementation, I suggest you to use Orange 2. Can I consider the issue closed?

**Comment by bhaveshoswal** [comment]
thanks

**Comment by kernc** [comment]
Scikit does support multitarget in its kNN implementation. We might want to consider wrapping scikit stuff more transparently.
