### ISSUE TITLE
No widgets

### ISSUE THREAD

**Issue by RokSkyWatcher** [biolab/orange3#1286]
##### Orange version
Version: 3.3.1.dev0+5d39ea2

##### Expected bahavior

Widgtes should load with no problem

##### Actual behavior

There's no widgets for Visualize, Classify, Regression,...

##### Steps to reproduce the behavior

Python3 -m Orange.canvas
Open Orange

##### Additional info (worksheets, data, screenshots, ...)

![issue](https://cloud.githubusercontent.com/assets/13365700/15628097/cabc9a10-24f8-11e6-9c4d-6bf1007ca136.PNG)

**Comment by kernc** [comment]
Can you please try again with [the latest version](http://orange.biolab.si/download/windows/)?

**Comment by RokSkyWatcher** [comment]
I tried that many times, no luck

**Comment by kernc** [comment]
Was just asking because you stated the version as 3.3.1.dev0+5d39ea2, and this version is from about two months ago.

If you run as `python -m Orange.canvas --log-level 4`, what errors do you get? Did the Python distribution come with Orange or did you have it before? Is it a 64-bit Python?

**Comment by RokSkyWatcher** [comment]
[OrangeLog.txt](https://github.com/biolab/orange3/files/288275/OrangeLog.txt)

This is my output. I've noticed lots of these kind of erros: 
ImportError: cannot import name 'moduleTNC'
Could not import 'Orange.widgets.data.owdatasampler'.

**Comment by kernc** [comment]
Leaving Textable errors aside (Textable hasn't been ported to Orange 3, fwik), it appears something is wrong with your SciPy installation. Can you try to reinstall the scipy package? Are you using Anaconda? Does [this](https://github.com/scikit-learn/scikit-learn/issues/4830) help?

**Comment by RokSkyWatcher** [comment]
Yes i'm using Anaconda. I reinstall scipy using these two commands:
```
conda remove scipy scikit-learn -y
conda install scipy scikit-learn -y
```

But this did't solved my problem. I also installed Orange 2 with Python 2 and it's working, so i guess there must be some problem with my Python 3 libraries? Is it possible that Anaconda effects on these libraries? 
Orange 2 works perfectly.

**Comment by ajdapretnar** [comment]
@RokSkyWatcher Have you installed Orange2 after you've installed Orange3? It is fairly impossible to keep both versions running normally because of the Python path in Environment Variables. Please check your PATH and if Python2 is listed first, then this is the likely issue.

For running Orange3, you must type:
```
set PATH=C:\Python35\Lib\site-packages\PyQt4; %PATH%
python -m Orange.canvas
```

I hope this helps.

**Comment by ajdapretnar** [comment]
@RokSkyWatcher Have you managed to solve the problem?

**Comment by Kronecker82** [comment]
I have the same issue too. I have a fresh Anaconda installation (Anaconda3-4.0.0-Windows-x86_64)
I ran `python -m Orange.canvas --log-level 4` and get:

```
C:\Users\Alessandro>python -m Orange.canvas --log-level 4
Setting up Canvas main window.
'CanvasScene(objectName='', ...)' intitialized.
Setting registry 'None on 'CanvasScene(objectName='', ...)'.
Scheme node properties sync (changed: False)
'CanvasScene(objectName='', ...)' cleared.
'CanvasScene(objectName='', ...)' intitialized.
Setting registry 'None on 'CanvasScene(objectName='', ...)'.
Setting scheme '<Orange.canvas.scheme.widgetsscheme.WidgetsScheme object at 0x000001A83393B5E8>' on 'CanvasScene(objectName='', ...)'
Stack transition start ()
Stack transition finished ()
Dock transition finished (new width 120)
Dock transition started.
Loading widget registry cache ('C:\\Users\\Alessandro\\AppData\\Roaming\\Orange\\3.3.1.dev\\Cache\\canvas\\registry-cache.pck').
Could not load 'Orange Widgets = Orange.widgets' (unsatisfied dependencies).
Traceback (most recent call last):
  File "C:\Users\Alessandro\AppData\Local\Continuum\Anaconda3\lib\site-packages\Orange\canvas\registry\discovery.py", line 89, in run
    point = entry_point.load()
  File "C:\Users\Alessandro\AppData\Local\Continuum\Anaconda3\lib\site-packages\setuptools-20.3-py3.5.egg\pkg_resources\__init__.py", line 2201, in load
    self.require(*args, **kwargs)
  File "C:\Users\Alessandro\AppData\Local\Continuum\Anaconda3\lib\site-packages\setuptools-20.3-py3.5.egg\pkg_resources\__init__.py", line 2218, in require
    items = working_set.resolve(reqs, env, installer)
  File "C:\Users\Alessandro\AppData\Local\Continuum\Anaconda3\lib\site-packages\setuptools-20.3-py3.5.egg\pkg_resources\__init__.py", line 830, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'joblib' distribution was not found and is required by the application
Saving widget registry cache with 1 entries ('C:\\Users\\Alessandro\\AppData\\Roaming\\Orange\\3.3.1.dev\\Cache\\canvas\\registry-cache.pck').
'set_global_registry()' - setting registry.
Setting registry '<Orange.canvas.registry.qt.QtWidgetRegistry object at 0x000001A83397D678> on 'CanvasScene(objectName='', ...)'.
```

**Comment by Kronecker82** [comment]
I can view the widgets now with `pip install orange` but I don't know if evrething is fixed at the moment

**Comment by RokSkyWatcher** [comment]
@ajdapretnar i tried, it works. Many thanks for this solution
