### ISSUE TITLE
Discrete attributes with a large number of values

### ISSUE THREAD

**Issue by mstrazar** [biolab/orange3#1297]
##### Orange version

3.3.5
##### Expected behavior

The file contains Discrete attributes with a large number of values.
##### Actual behavior

Orange fills up memory. This issue might be relevant for Recommendation system add-on, which would require such functionality (Discrete attributes with a large number of values.)
##### Steps to reproduce the behavior

Load the data file below.
##### Additional info (worksheets, data, screenshots, ...)

http://193.2.72.50/biolab/Misc/ccdm_largeO.tab

**Comment by kernc** [comment]
Even after some 10 minutes, Orange.data.Table didn't complete loading the file as it ValueErrored with "Non-continuous value" in line 53058, column 17 (—we don't treat "null" as nan).

On a very positive note, pandas loads it in under 6 seconds, and the dataframe is a joy to work with afterwords.

**Comment by kernc** [comment]
> relevant for Recommendation system add-on

I'd suggest ensuring the algorithms work primarily with primitive data structures, like numpy (and scipy.sparse) arrays.

**Comment by ajdapretnar** [comment]
@mstrazar @kernc Anyone working on this? Waiting for pandas?

**Comment by kernc** [comment]
Yes.

**Comment by sstanovnik** [comment]
On a dataset with two discrete attributes with n distinct values and where n = 1 000 000, the pandas implementation takes about 20 seconds to load the data (~14 MB) and then 6 seconds every time you open the file widget. For n = 100 000, the times are 2 and 1 seconds respectively. Is this acceptable?

**Comment by astaric** [comment]
Reading speed is probably ok, but the per open cost should be IMHO constant, and not related to the dataset size.

**Comment by sstanovnik** [comment]
See #1524 :)

**Comment by ajdapretnar** [comment]
@mstrazar The sample file seems to be deleted. I'd like to see if the problem persists with the current version. Just to know where to file this bug. :)
