### ISSUE TITLE
Selection of multiple objects (nodes, annotations, arrows) is not always visible

### ISSUE THREAD

**Issue by sirjamesgray** [biolab/orange3#1301]
##### Orange version

3.3.5

##### Expected bahavior

cmd + click to select multiple objects should highlight each object

##### Actual behavior

when selecting certain objects, (especially multiple arrows and textboxes) objects often appear "unselected" but when moving the objects they are apparently selected. 

##### Steps to reproduce the behavior

try selecting multiple objects (nodes, textboxes, and arrows) and drag them around.

##### Additional info (worksheets, data, screenshots, ...)

thanks @astaric for helping me clarify the problem

**Comment by astaric** [comment]
I am not sure to which part of the program are you referring as main view. In canvas (workflow editor), I can select (and unselect) multiple widgets using the CMD click.

**Comment by sirjamesgray** [comment]
@astaric to clarify:

I cannot select multiple "text" or "arrow" objects with cmd + click. 

I'll edit the issue comment to clarify.

**Comment by astaric** [comment]
Can you try cmd clicking multiple arrows and then move one of them. When I try to do this, all of the selected arrows move.
