### ISSUE TITLE
Warning message is truncated

### ISSUE THREAD

**Issue by sirjamesgray** [biolab/orange3#1302]
##### Orange version

3.3.5

##### Expected bahavior

expected to be able to:
1. expand size of window by grabbing corner
2. click the warning message to expand into more lines
3. on cursor hover, scroll horizontally with two fingers to scroll the message 

##### Actual behavior

1. the window is a fixed size; cannot be adjusted
2. clicking the warning does nothing
3. that didn't work either

##### Steps to reproduce the behavior

I tried to connect a "scatter plot" node to a "linear regression" node, and apparently the "scatter plot" contains a "single target value" 

##### Additional info (worksheets, data, screenshots, ...)

![screen shot 2016-06-03 at 12 55 58 am](https://cloud.githubusercontent.com/assets/16139439/15770085/9af488b0-2926-11e6-89e5-6e988c7e81d1.jpg)

**Comment by lanzagar** [comment]
3. on cursor hover you should see the entire message (without scrolling)

**Comment by ajdapretnar** [comment]
This issue had a 3.3.7 milestone, but I don't think the newest version fixed the issue. At least my warnings are still truncated.

**Comment by kernc** [comment]
I think this is WIP in https://github.com/biolab/orange3/pull/1490

**Comment by ajdapretnar** [comment]
Already fixed via #1490.

**Comment by kernc** [comment]
How does #1490 fix this? The error message is still truncated?
