### ISSUE TITLE
Can't "pinch to zoom" in main view

### ISSUE THREAD

**Issue by sirjamesgray** [biolab/orange3#1303]
##### Expected bahavior

in the main view (is it called the "classification tree"?) I was hoping I could zoom in / out by using "pinch to zoom" gesture on OS X
##### Actual behavior

"pinch" gesture does not affect the viewer
##### Steps to reproduce the behavior

try to "pinch to zoom" in the main window

**Comment by kernc** [comment]
Does "pinch to zoom" internally translate into scroll wheel events?

**Comment by ajdapretnar** [comment]
@astaric Is this a wontfix or do we plan to implement this on Tree Viewer? I have reservations about this, since Scatter Plot works with, as @kernc mentioned, scroll wheel events. I reckon 'pinch-to-zoom' is touchpad-only.

**Comment by ajdapretnar** [comment]
@astaric?

**Comment by astaric** [comment]
I guess it is a wont fix.

**Comment by kernc** [comment]
Pinch-to-zoom is a feature on all multi-touch trackpads with supporting software with gestures enabled; also touchscreens.

Why is this a wontfix? Do we expressly _not want it_? We have an open-source community; meaning no one in particular has to do it for the general wishlist item to remain open and awaiting anyone willing to tackle it.
