### ISSUE TITLE
Time Series Analysis in Orange

### ISSUE THREAD

**Issue by cheral** [biolab/orange3#1304]
I am interested to create widgets for Time Series Analysis Algorithms like ARIMA, Holt Winters , etc. and Visualizations for Time Series, if Required.
Under which category should I include them?
Has any work been done on this before in orange 3 or 2.7 ?
Or  does orange have basic support for time series?

**Comment by kernc** [comment]
There is already a Time Series add-on for Orange 3 in final stages of production and should be published very soon. Will ping here once it is.

![screenshot - 06022016 - 06 52 08 pm](https://cloud.githubusercontent.com/assets/684364/15772580/27cc84fe-2972-11e6-8021-cc9af8a3741f.png)
