### ISSUE TITLE
Parameter Tuning for SVM/Trees/...

### ISSUE THREAD

**Issue by TDVvDlunn** [biolab/orange3#1327]
I'm missing some parameter tuning widget because there is no way to get best performance out of the dataset without parameter tuning.
### Example for SVM Classification

I would expect a widget where the user can set the stepsize (linear and exponential) and the range for the parameter C and gamma.

This widget would act like this pseudocode which is quite friendly for multicore implementations

```
nFolds as input from user
C_array as input from user
gamma_array as input from user

best_c = 0
best_gamma = 0
best performance = 1
best_model =  []

Do this stuff on all processors in parallel
for all parameters in gamma_array
   for all parameters in C_array
      [ perf_i , model_i ] = crossvalidate( SVM(dataset,C_i,gamma_i) , nFolds )

      if best_performance > perf_i
          perf_i = act_performance
          best_c = C_i
          best_gamma = gamma_i
          best_model = model_i
      end
   end
end

return best_model, best_c , best_gamma
```

**Comment by kernc** [comment]
Great idea! Something like GridSearchCV in sklearn.

We can idealize it most general and have this new widget accept any parameterizable learner.

@astaric, since @s-alexey's django forms didn't come to be, how about something like more lightweight function annotations:
```py
class XYClassifier(Learner):
    def __init__(self,
                 C:float=1,
                 method:['this', 'that']='this',
                 ...):
        ...
```

**Comment by astaric** [comment]
As long as they are compatible with [PEP484](https://www.python.org/dev/peps/pep-0484/), I do not see a problem.

**Comment by janezd** [comment]
Issue moved to #4090.

**Comment by KOLANICH** [comment]
May worth looking: https://gitlab.com/KOLANICH/UniOpt.py
