### ISSUE TITLE
TABLESAMPLE clause can only be applied to tables and materialized views

### ISSUE THREAD

**Issue by klonuo** [biolab/orange3#1350]
Trying auto-discover variables on a sample from large view (SQL Table dialog), raises:

> TABLESAMPLE clause can only be applied to tables and materialized views

Could there be a workaround for sampling a view?

I'm using latest Orange 3.3. on Windows

**Comment by astaric** [comment]
@lanzagar One option would be to just use the first 1000 rows from the view. This will not work if the view is complicated (takes a long time to return first 1000 rows).
Another thing I am not certain of is whether we should use the fallback everywhere sampling is used for tables, or just for the guessing of domain.

**Comment by ajdapretnar** [comment]
@lanzagar @astaric Solved, due to be solved or unsolvable? :smile:

**Comment by lanzagar** [comment]
I started working on this, but it turned into a bigger refactoring process with various changes. Will try to continue with it next week.
But as for this PR - yes TABLESAMPLE can only be used on tables and materialized views, and Orange depends quite a lot on sampling, so I would suggest not using views over large data anyway.

**Comment by ajdapretnar** [comment]
Ok, let's wait for the PR from @lanzagar, we'll reference it and close once it's merged. :+1:

**Comment by ajdapretnar** [comment]
@lanzagar Has this been fixed somewhere? I can't find a corresponding PR, so I ask. :)

**Comment by ajdapretnar** [comment]
I suppose this was fixed with recent changes. If not, changes will be address in solving #3565.
