### ISSUE TITLE
Installing Issue: Previous Python Installs?

### ISSUE THREAD

**Issue by Pelonza** [biolab/orange3#1359]
##### Orange version

Latest (3.3)

##### Expected bahavior

When running the combined installer, detect an installed version of Python 3.4/3.5 and skip that, OR ask users, OR overwrite environmental variables.

##### Actual behavior

The python installer errors out if Python Environmental Variables are already set, because the installer does not call specific test location (it couldn't get the popup window that runs a script to open originally).

##### Steps to reproduce the behavior

Install Python 2.7 and set your environmental variables (PYTHONHOME, PYTHONPATH, PYTHONSCRIPT) ... or at least that worked for me. 

##### Additional info (worksheets, data, screenshots, ...)

I just deleted the other python variables and it seems to have installed just fine. 

Alternatively, you could have just an "orange" installer available. 

Yes- I realize I could have worked around this from the git-hub repository myself...but what happens if a user had already installed python for something else?

**Comment by ajdapretnar** [comment]
@astaric @janezd @ales-erjavec Any idea on this one?

**Comment by ales-erjavec** [comment]
> When running the combined installer, detect an installed version of Python 3.4/3.5 and skip that

We do that. We only run the python installer (currently 3.4) if it is not already installed. The python environments can live side by side, without major difficulty, although only one can be (first) on the PATH and registered as the launcher for .py files (and you are presented with an option for that during the Python installation).

> **Steps to reproduce the behavior**
Install Python 2.7 and set your environmental variables (PYTHONHOME, PYTHONPATH, PYTHONSCRIPT) ... or at least that worked for me. 

Don't set those variable (at least not globally/permanently). It might be a good idea for the installer to unset them (locally in it's process) during the installation, but that would still leave you with a non-functioning install until you again unset/change them.

Those variables change the behavior of the python interpreter and imply specific intent (by whomever set them in the first place). The installer will/should never change those for you.

> Alternatively, you could have just an "orange" installer available.

If you have all the necessary dependencies (which are not themselves pip installable; notably scipy and PyQt4) already installed you can use pip: `pip install orange3`

**Comment by ajdapretnar** [comment]
@Pelonza @kernc @ales-erjavec Can we consider this as solved? It seems like we're doing what we can on our end....

**Comment by Pelonza** [comment]
Probably. Apparently i hid just broken things my self.

Dr. Karl Schmitt
Assistant Professor
Department of Mathematics and Statistics
Department of Computing and Information Sciences
Director of Data Science Program
Director of Analytics and Modeling Graduate Program
Valparaiso University, Indiana

**Comment by ajdapretnar** [comment]
Ok. We can reopen if we find some new information.
