### ISSUE TITLE
Add-ons window raises an error

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#1365]
Urgent: When one opens Options - Add-ons, one gets an error instead of a list of add-ons. I get a ProtocolError, while someone else also got AttributeError.

![clgins_wiaamxr7](https://cloud.githubusercontent.com/assets/12524972/16257512/555a2ea8-3859-11e6-8cfe-69d2a5b274b9.jpg)

**Comment by astaric** [comment]
Does the error occur on master branch? It should have been fixed in #1343

**Comment by ajdapretnar** [comment]
Ah, no. Du bist recht. I never check add-ons from master, because it causes a mess. Closing the issue.
