### ISSUE TITLE
Problems creating a Word Cloud in Orange 3.3.5

### ISSUE THREAD

**Issue by rmianalytics** [biolab/orange3#1370]
##### Orange version

Orange 3.3.5, git revision f97240f, using Anaconda Navigator (orange app 1.0)

##### Expected behavior
Create a Wordcloud using the files already processed

##### Actual behavior
Gives an error message (reproduced below) and can not create the word could.

##### Steps to reproduce the behavior
Just try to create a wordcloud and the issue appears.

##### Additional info (worksheets, data, screenshots, ...)
--------------------------------------------------------------------------------
AttributeError                                Traceback (most recent call last):
  File "c:\anaconda3\lib\site-packages\Orange\canvas\scheme\widgetsscheme.py", line 341, in create_widget_instance
    widget.__init__()
  File "c:\anaconda3\lib\site-packages\orangecontrib\text\widgets\owwordcloud.py", line 84, in __init__
    self._create_layout()
  File "c:\anaconda3\lib\site-packages\orangecontrib\text\widgets\owwordcloud.py", line 138, in _create_layout
    self.table = gui.TableWidget(box,
AttributeError: module 'Orange.widgets.gui' has no attribute 'TableWidget'

**Comment by kernc** [comment]
This widget is part of text mining add-on which has its issue tracker here: https://github.com/biolab/orange3-text/

As for the solution to your issue, please update the Orange3-Text add-on (via Options > Add-ons) and try again.

**Comment by nikicc** [comment]
@kernc updating the Orange3-Text will not solve the problems since we did not make a release after accepting the bugfix. 

@rmianalytics again, this has already been fixed but is not yet released. You have three options. You can:

- wait till tomorrow for a new version of Orange3-Text,
- install Orange3-Text from the latest master on github,
- or manually apply [the fix](https://github.com/biolab/orange3-text/commit/85843c9145ae1c16870fed8f4dbb356c55264165).

**Comment by ajdapretnar** [comment]
I'm closing this since:
a) it is an Orange3-Text issue
b) possible solutions are listed above
@rmianalytics Thank you for reporting this, though!

**Comment by nikicc** [comment]
@rmianalytics we just released a new version (0.1.11) of Orange3-Text addon so after a few hours it should be available on pip. Also, make sure you have the latest version of Orange (3.3.6).
