### ISSUE TITLE
sample_time requires installation of extension in orange3/Orange/data/sql/table.py

### ISSUE THREAD

**Issue by titaniumtroop** [biolab/orange3#1388]
##### Orange version

3.3.5

##### Expected behavior

Sampling of large table for attribute discovery
![screen shot 2016-06-29 at 08 48 43](https://cloud.githubusercontent.com/assets/13068310/16454569/ddc2554a-3dd6-11e6-9c52-6bce59226f44.png)

##### Actual behavior

Error that method system_time doesn't exist

##### Steps to reproduce the behavior

Connect to postgres database, Answer "Yes, on a sample" to the popup box.

![screen shot 2016-06-29 at 08 48 28](https://cloud.githubusercontent.com/assets/13068310/16454548/cce1922c-3dd6-11e6-84b8-3e136ae13cd9.png)

##### Additional info (worksheets, data, screenshots, ...)

The solution is to [create the system_time extension](https://www.postgresql.org/docs/9.5/static/tsm-system-time.html) in Postgres 9.5+ (not available before then).

Suggested solution is to check for Postgres 9.5+ and the existence of the system_time method. If it doesn't exist, create the method using the following:

`CREATE EXTENSION tsm_system_time;`

After installing the extension, the sampling works properly.

**Comment by ajdapretnar** [comment]
@lanzagar Could you please check? :rose:

**Comment by lanzagar** [comment]
Nothing to check really, this is not unexpected behaviour, but how it works for now.
Having the extension is a requirement for using (larger) SQL data.
We could try and create the extension automatically, but it will still work only in some cases. The extension might not be available on the server at all (needs to be installed first), or the user could have only read and no write permissions.

But it would not hurt to try and run the CREATE EXTENSION command in case it can be done.
Will add this as an enhancement request on the TODO list.
