### ISSUE TITLE
Time series add-on installation fails

### ISSUE THREAD

**Issue by kielhauser** [biolab/orange3#1457]
##### Orange version
3.3.6 (git revision ee294bc) on OSX 10.11 and Windows 10

##### Expected behaviour

The time series add-on should install without problems via the Options -> Add-on -> Orange3-Timeseries -> Install

##### Actual behaviour

An error is given (see attached files) both on Windows and OSX

##### Steps to reproduce the behavior

(see expected behaviour)

##### Additional info (worksheets, data, screenshots, ...)

[Orange3-Timeseries_Error_Msg_Win_10.txt](https://github.com/biolab/orange3/files/363533/Orange3-Timeseries_Error_Msg_Win_10.txt)

[Orange3-Timeseries_Error_Msg_OSX_11.11.txt](https://github.com/biolab/orange3/files/363535/Orange3-Timeseries_Error_Msg_OSX_11.11.txt)

**Comment by astaric** [comment]
Add-on installation issues should be raised on their issue trackers. You can find issue tracker for timeseries add-on here: https://github.com/biolab/orange3-timeseries/issues
