### ISSUE TITLE
k-means max number of clusters is too small

### ISSUE THREAD

**Issue by AILearner** [biolab/orange3#1459]
##### Orange version
3.3.6

##### Expected behavior
I need a range of 200 to 500 clusters for a large task. Not a baby play toy that only does 30. I'm willing to wait hours/days for it to compute.

##### Actual behavior
k-means has a max of 30 clusters. It wont allow more then that.

##### Steps to reproduce the behavior
Number of clusters "fixed", and "optimized from" max out at 30.

**Comment by kernc** [comment]
Would you like to submit a pull request? The relevant code is [here](https://github.com/biolab/orange3/blob/9a0853ee5fc2909ba87670937c831f624075f4ce/Orange/widgets/unsupervised/owkmeans.py#L71-L88).

**Comment by janezd** [comment]
Open Orange/widgets/unsupervised/owkmeans.py, find the line `sb, self, "k", minv=2, maxv=30,` (at around line 72) and change 30 to 99999 if you wish. The time needed to converge should not depend much on the number of clusters; I suspect it will run (to the local minimum) even faster.

We wouldn't accept a pull request with this change, though. 30 is a very reasonable upper limit; baby play toy makers didn't set it by mistake. :) They could easily allow unlimited number of clusters if they thought that numbers above 30 make sense.

I recommend you to consider again whether you indeed have this many clusters. Even if you do, I'm not sure that k-means is indeed the method that can find them. My intuition is that you'll have much better chance with single-linkage hierarchical clustering (if the distance matrix will fit into memory, that is).

**Comment by AILearner** [comment]
Thank you for the responses. I definitely have more then 30, some of the data is similar and needs to be clustered, while the rest of the data is unique and needs to go into its own personal cluster so-to-speak. I ended up running it on H2O with 500 clusters. 
Thanks for pointing out the variable in the code though.
I'll look into single-linkage hierarchical clustering, and see if it gives better results.

**Comment by ajdapretnar** [comment]
I am closing this issue since defaults are intentional and the issue seems to be solved.
