### ISSUE TITLE
Naive bayes fails to pass updated name

### ISSUE THREAD

**Issue by Pelonza** [biolab/orange3#1463]
##### Orange version

3.3.5

##### Expected bahavior

When two copies of the same classifier algorithm are created on a canvas and are renamed, they pass those names on to "down-the-line" widgets.

##### Actual behavior

Definitely with naive bayes, but I believe we also saw this with SVM.
If you create two "naive bayes" widgets, then rename them on the canvas. Send their outputs to the "test and score" widget. Both appear as naive bayes rather than the new name given. 

This makes it a LOT harder to determine which model was actually doing better!

**Comment by kernc** [comment]
All learner widgets have a name setting one can set.
![screenshot - 07152016 - 03 16 04 pm](https://cloud.githubusercontent.com/assets/684364/16875347/499492f4-4a9f-11e6-9ab6-978da9bb49c6.png)
Could this work for you? I don't think it would be as easy honoring widget's canvas name. Or it would, but which of the two names would have priority? How would this work?

**Comment by ajdapretnar** [comment]
I am closing this since learners are renamed in the widget itself not from the canvas. If there's an issue with that, you can open another issue.

**Comment by Pelonza** [comment]
Sorry, I should have responded to Kernc, I thought I had.

Kernc's example would be just fine. This issue isn't with the widgets renaming themselves. You can do that, and it shows up fine. The problem is with the passing to other widgets (as kernc showed in his images).

My priority would be to honor the name typed into the box. I.e. your "Naive Bayes X and Naive Bayes 1" ... but I'm pretty sure that (at least for Naive Bayes), typing a name into that box renames it on the canvas.

**Comment by ajdapretnar** [comment]
I'm not entirely sure I understand what you're referring to. Learners in Test&Score are named as defined in the learner's widget. See below: alpha and beta. This name is further passed to any other widgets that accept learners and such, i.e. Data Table, Confusion Matrix and so on.

Widget names on the canvas are a different thing and are changed separately by renaming them.

![naming-widgets](https://cloud.githubusercontent.com/assets/12524972/17214327/b0d3e42c-54d8-11e6-92ad-d811fee5ac5f.PNG)

**Comment by ajdapretnar** [comment]
Or do you mean you would want to apply renaming of the learner **within** the widget, i.e. alpha, also to the widget on the canvas? Thus if I rename my learner to _alpha_, the widget should also be renamed to _alpha_?

**Comment by Pelonza** [comment]
So, at least on the install of orange that my students have been running we do NOT see the behavior you are showing. That is, where you name it on the widget open, and it shows up differently in "Test and score"

**Comment by Pelonza** [comment]
Let me confirm with them and their models... I'll get back to you today.

**Comment by Pelonza** [comment]
Ok. I downloaded and checked against the test file they'd left me.
The behavior works as you've shown (sort of). If you change the name with the widget set to "auto send", the name does not get updated, unless you close and open the file again. 
Example:
Create a Naive Bayes Widget
Connect it to the test & score
Open the Widget editor (the double click, not the F2 rename).
Change the name.
Close the widget editor.
If I open the widget editor again, it's "saved" the new name. But the name has not gotten sent to the test&score.

This is probably most relevant on the Naive Bayes actually. I just tested on classification trees, and the same "behavior" happens, but if you change any of the widgets actual parameters, it DOES send the new name. 

Not sure how/why my student using SVM didn't get the names to change/work...**Shrug** I'll try to check with her later today.

**Comment by Pelonza** [comment]
Hmm. I guess also relevant to the example setup:
Already have test/score on the canvas. With learners connected in. I.E. already computed/computing things. The key is to change the name after the widget has "sent" the data. Basically a changed name doesn't force a new "send automatically". which is perhaps a minor actual issue, but can lead to confusion for novice users (as happened to my students).

**Comment by ajdapretnar** [comment]
Ok, I see what you mean. When you are typing in a new name, you should see a small 'Enter' icon appear next to the entry field. If you press Enter or that icon or, as you said, close the widget, changes get saved and applied automatically. Otherwise I reckon names would be updated per every key stroke.

I've tried Naive Bayes, Classification Tree and SVM and all of them get the 'enter' icon once I start changed the learner name.

Can you see whether this is the same for you? We really wish to support intuitive use of the software for novices, but some issues are difficult to solve elegantly and intuitively at the same time. :)

**Comment by Pelonza** [comment]
Ah.. I do NOT get an "enter" icon. Or at least it's not obvious to me where it is. Nor when I hit "enter" does it update. I tried Naive Bayes and Classification trees. 

I'm not sure if my Mac-User also saw this, but I'm running it on windows.

**Comment by ajdapretnar** [comment]
:open_mouth:  I have this on Windows. 

![enter-button](https://cloud.githubusercontent.com/assets/12524972/17217139/96103fcc-54e3-11e6-8aa2-d5a8e059af6f.PNG)

I've only noticed you're running a 3.3.5 version. Perhaps you can update Orange and report back if the icon still doesn't appear?

**Comment by Pelonza** [comment]
So the version I'm running at home on my computer is 3.3.6....and I don't see that enter button. 
git revision ee294bc

I just downloaded it this week. Though I did open an older .ows file to load the example.

**Comment by astaric** [comment]
This issue might have been fixed in 1008ae0, which has been merged after 3.3.6 was released. It will be included in 3.3.7 which should be available by the end of next week.

It should work with the latest set of [nightly builds](http://orange.biolab.si/download/files/nightly/).

**Comment by ajdapretnar** [comment]
The problem I noticed is that the model gets recalculated every time one changes the model name. I don't think this should happen.

**Comment by Pelonza** [comment]
Ok. Thanks for looking into this and addressing it! My apologies on
apparently raising something that was already fixed.

Dr. Karl Schmitt
Assistant Professor
Department of Mathematics and Statistics
Department of Computing and Information Sciences
Director of Data Science Program
Director of Analytics and Modeling Graduate Program
Valparaiso University, Indiana
