### ISSUE TITLE
TimeVariable: repr_val() uses incorrect rounding

### ISSUE THREAD

**Issue by stuart-cls** [biolab/orange3#1465]
Hi @kernc , in `Orange.data.variable.TimeVariable.repr_val()` , the following line (910)

    microseconds = int(round((val - seconds) * 1e6))

will fail `ValueError: microsecond must be in 0..999999` in the following case:

    val = 1444393718.900992
    seconds =  1444393719
    microseconds = -99008

Thanks

##### Orange version
3.3.6 or master

**Comment by kernc** [comment]
That's interesting because if `val` is 1444393718.900992, then [`seconds` should be 14439371**8**](https://github.com/biolab/orange3/blob/7f464a6f81438a1fddb719b41cb9852bf3a6997b/Orange/data/variable.py#L909), and microseconds should be strictly positive. How did you get those values?

**Comment by stuart-cls** [comment]
Good point, if I step through the commands from repr_val() in a shell, I also get `seconds = 1444393718`.

I got the values by inserting a `print()` into the repr_val() function.

I can reproduce this in the gui by making a datatable with:

```
start time
time
meta
1444393718.90099
```
loading into Orange and then trying to view with a Data Table. Also happens if the third line is not "meta"

**Comment by kernc** [comment]
Works for me on master. Indeed, this was [fixed only recently](https://github.com/biolab/orange3/compare/stable...0c05cc1), after the last 3.3.6 release. Thanks.

**Comment by stuart-cls** [comment]
Quite right, I missed that. Thanks.
