### ISSUE TITLE
Test & Score overwrites Univariate Polynomial Regression learner domain

### ISSUE THREAD

**Issue by stuart-cls** [biolab/orange3#1469]
##### Orange version
3.3.6

##### Expected behavior
Connect multiple Univariate Polynomial Regression learners (each of which is training on a different attribute, but same target variable) to the Test & Score widget to compare the resulting models.

##### Actual behavior
Test & Score reports the same scores and outputs the same predictions for all the learners.

##### Steps to reproduce the behavior
Connect data to Univariate, select desired variable -> connect to Test & Score which has the data set on the data input.
Repeat for a second Univariate learner, select a different variable
Output will be the same between the two (and a Linear Regression learner)

##### Additional info (worksheets, data, screenshots, ...)
If you monitor the learner.domain while doing this, you can see the initial UPR domain contains only the attribute of interest and the target variable of interest. Once you connect UPR -> Test & Score, the domain changes to that of the original dataset, and the learner essentially becomes the normal Linear Regression learner.

**Comment by VesnaT** [comment]
Test & Score widget takes learners (not models) as inputs. Therefore, you can only influence learner properties (i.e. polynomial expansion) by setting Univariate Polynomial Regression widget and not the data for training. The learners are than trained on data, sent to Test & Score widget, so all learners are trained on the same data.

If you want to try UPR for different attributes, you can use Select Columns widget before sending data to Test & Score.

**Comment by stuart-cls** [comment]
Hmm, okay. In our use case we are interested in comparing the performance of a few different univariate models on the same data set. Since the relationship is known to be 1st order, we were more interested in the "univariate" part than the "polynomial" part. In the learner case at least, the name "univariate" seems to be misleading, since the Test & Score ends up running a multivariate regression.

For our use case, does this mean to compare different models we must separate the data using many Select Columns widgets and compare the output of multiple Test & Score widgets?

**Comment by kernc** [comment]
If you're interested in relative feature importances, you can use the Rank widget.
![univarlinreg](https://cloud.githubusercontent.com/assets/684364/17028655/8dd6ee8a-4f68-11e6-8f50-892d75b04afa.png)
The descending importances should correspond with increasing MSE in Test & Score.

**Comment by stuart-cls** [comment]
Thank you, that's very helpful.

**Comment by markotoplak** [comment]
@stuart-cls If you would like to compare classifier performance on subsets of features, then yes, the only option is to use multiple Test & score widgets.
