### ISSUE TITLE
Strip empty columns in .xlsx files

### ISSUE THREAD

**Issue by mlopezheredia** [biolab/orange3#1471]
Hi,
I am new to orange and I get the error while importing my data. Hope you could help me.
##### Orange version

3.3.6 (on windows 7)
##### Expected bahavior

Dataset has 61 columns and 338 rows. It is read as a XLSX file but not as a CSV file
##### Actual behavior

Gives the error: "Cannot parse dataset libro1.csv: too many indices for array".
##### Additional info (worksheets, data, screenshots, ...)

[Libro1.xlsx](https://github.com/biolab/orange3/files/371787/Libro1.xlsx)

**Comment by kernc** [comment]
In Orange 3.3.7~dev, I can read this xlsx, either as-is or transformed into CSV, just fine. Can you attach the exact CSV file that fails to load?

**Comment by mlopezheredia** [comment]
Here is the file. I tried again and failed either from its location in a file server or from the desktop. Thanks in advance.
[AllData_20160719_pca.zip](https://github.com/biolab/orange3/files/373052/AllData_20160719_pca.zip)

**Comment by ajdapretnar** [comment]
@mlopezheredia Your .csv file is a bit 'corrupted'. It has extra blank columns with no headers and this is what's causing the problem. If you import your file in Excel as text, you will see the issue. Once I've copied only the actual data and saved it as a .csv file, the data was loaded.

However, I think Orange should somehow strip empty columns automatically. What do you think, @kernc?

**Comment by mlopezheredia** [comment]
@ajdapretnar  Thanks for the information and help. I have not seen them. It would be a good idea to strip empty columns automatically.

**Comment by mlopezheredia** [comment]
Removing the extra blank columns with no headers from the .csv file solved the issue. Thanks @ajdapretnar for the tip.

**Comment by sstanovnik** [comment]
Reading the file works in the pandas implementation. However, it leaves empty columns in the data. The Purge Domain widget is useful in thhis case.

**Comment by ajdapretnar** [comment]
I vote for fixing this before pandas and striping empty columns in pandas, too. Thus a gsoc label.
