### ISSUE TITLE
Error on QtWebkit

### ISSUE THREAD

**Issue by pomoke** [biolab/orange3#1494]
##### 
![2016-08-02 09-38-44]

Don't work.

##### Additional info (worksheets, data, screenshots, ...)

![](https://cloud.githubusercontent.com/assets/5499007/17314179/ee95d454-5894-11e6-8d9c-ca7d00c5011a.png)

![2016-08-02 09-36-54](https://cloud.githubusercontent.com/assets/5499007/17314193/016995a2-5895-11e6-9f98-8e3e2b944f65.png)

**Comment by ajdapretnar** [comment]
@pomoke Which version of Orange are you running?

**Comment by ales-erjavec** [comment]
Which Linux distribution are using? Some (most) Linux distributions partition the PyQt4 into several packages (with QtWebKit a likely candidate for a separate package). Do a `apt-cache search pyqt4` or equivalent for you system to find the appropriate package and install it.

**Comment by pomoke** [comment]
Debian testing;pip install orange3

**Comment by ajdapretnar** [comment]
@pomoke Have you then tried `apt-cache search pyqt4` and install the package? Does it work?

**Comment by ales-erjavec** [comment]
It seems that Qt4's QtWebKit module was specifically removed from Debian stretch (https://lists.debian.org/debian-devel-announce/2015/05/msg00001.html).

You can try to install and use a [anaconda/miniconda](https://www.continuum.io/downloads) python distribution and use conda provided pyqt4 package.

**Comment by ajdapretnar** [comment]
@pomoke Can we consider this solved?
