### ISSUE TITLE
Document passing JS code into Highcharts options

### ISSUE THREAD

**Issue by trhallam** [biolab/orange3#1500]
Orange '3.3.6' via Anaconda 
Python 3.5.2 |Anaconda 4.1.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]

Hi,

I've been trying to create some widgets using Highcharts and for the most part it is pretty smooth. I have run into problems however with options that require a function such as tooltip_formatter.

For example
`tooltip_formatter = ("function() {return 'Hello World';})"` 
does not result in a tooltip that always says Hello World

As best I can tell the option when passed to the Java interpreter has additional quotation marks which mean the function cannot be interpreted.

Are there any examples of how to address this issue?

Cheers
Tony

**Comment by kernc** [comment]
There are. If a string starts with an empty JS block comment (`/**/`), its content is evaluated in JS and that value is replaced with evaluation result. E.g. this should work:
```py
tooltip_formatter = "/**/function() { return 'Hello World'; }"
```

**Comment by trhallam** [comment]
Thanks @kernc .

I think we are almost there but not quite. I have tried a few combinations.

This creates an alert so it appears to evaluate the content correctly when looking at the tooltip_formatter option. The original tooltip_formatter format remains unchanged in the plot itself.
`tooltip_formatter = '''/**/alert('Hello');'''`

If i take the (`/**/`) away then the tooltip_formatter does not work and there is no alert generated.
`tooltip_formatter = '''alert('Hello');'''`

There seems to be a difference however when you actually define the function inline though, as that still does not result in a working tooltip.

This is the Highcharts example I have been working from.
[http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/tooltip/formatter-simple/](url)

**Comment by kernc** [comment]
A string without leading `/**/` is always _just a literal string_.

The respective value in the Highcharts options object should be replaced with its evaluated content. How did you test this?

Note, setting `tooltip_formatter` to an anonymous function, be sure to encapsulate the function in parenthesis:
```js
tooltip_formatter = "(function () { return 'Tooltip'; })"
```
Otherwise `eval()` throws a syntax error.

**Comment by trhallam** [comment]
Legendary, that appears to have solved my issues. Thank you!

**Comment by ajdapretnar** [comment]
@kernc Is this a work-in-progress issue or just something yet to document?

**Comment by kernc** [comment]
I guess [this behavior](https://github.com/biolab/orange3/issues/1500#issuecomment-238027108) should be mentioned somewhere besides here.

**Comment by ajdapretnar** [comment]
Agree. Would you have time for this quick mention and I promise to merge asap. 😃

**Comment by kernc** [comment]
See https://github.com/biolab/orange3/pull/1957.
