### ISSUE TITLE
Database is missing extension: quantile

### ISSUE THREAD

**Issue by klonuo** [biolab/orange3#1501]
I get this error in SQL Table dialog.

quantile seems to be extension available on extensions network: http://pgxn.org/dist/quantile/1.0.0/
but this is hard to possible to install on Windows.

Also asking user to install extension for every database he's working on in Orange, does look strange to me.

What would you suggest Windows user with PG 9.5?

**Comment by kernc** [comment]
> What would you suggest Windows user with PG 9.5?

To sample 50k rows into a CSV file and work with that.

**Comment by lanzagar** [comment]
Orange uses the quantile extension for faster conversion between numeric and categorical variables (discretization). You can continue working with data from a database without the extension even if the error is shown, at the risk of errors later when/if discretization will be used.
As suggested, you could also download the data into local memory (if it is too big, sample it first) and work with that (possibly even save it into a file for subsequent reuse).

**Comment by klonuo** [comment]
Thanks for your replies.

I guess I should close this.

**Comment by witwall** [comment]
without quantile extension, SQL Table would not work.

2unda has included quantile, but some times I want to use remote postgresql(of course I can use postgre_fdw).

another way plpython3u needs 64bit python34, but Orange only have 32bit Python34, right? 

![orange001](https://cloud.githubusercontent.com/assets/3222056/21446737/06c593bc-c905-11e6-8b89-7b904901d593.png)
