### ISSUE TITLE
Could not load repository. Add-ons.

### ISSUE THREAD

**Issue by gvisniuc** [biolab/orange3#1504]
URL needs to be **https**.

##### Orange version

2.7.8

##### Steps to reproduce the behavior

From Options→Add-ons

![addon-repo](https://cloud.githubusercontent.com/assets/1614747/17481512/e4fbe53a-5d7d-11e6-84c3-2cb77b872173.png)

To fix simply modify the URL in the addons.py file, line 135 to.

`pypi = xmlrpclib.ServerProxy('https://pypi.python.org/pypi')`

In my case the location is:

~/anaconda/pkgs/orange-2.7.8-py27_3/lib/python2.7/site-packages/Orange/utils/addons.py

**Comment by kernc** [comment]
Was already fixed in https://github.com/biolab/orange/pull/43. Wait for our next release shortly, or poke Anaconda to build the git source instead of the available, dated release. You might also consider trying the next version, [Orange 3](https://github.com/biolab/orange3).

**Comment by gvisniuc** [comment]
@kernc Thanks for the info. I will give Orange 3 a try.

**Comment by kernc** [comment]
With anaconda, `conda install orange3` or `pip install orange3` may work.
