### ISSUE TITLE
Problems with Confusion matrix

### ISSUE THREAD

**Issue by JelenaKitanovic** [biolab/orange3#1505]
I cannot put Confusion matrix on canvas it shows error: 

Could not create 'Confusion Matrix'

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\Orange\canvas\scheme\widgetsscheme.py", line 342, in create_widget_instance
    widget.__init__()
  File "C:\Python34\lib\site-packages\Orange\widgets\evaluate\owconfusionmatrix.py", line 116, in __init__
    callback=self._learner_changed
  File "C:\Python34\lib\site-packages\Orange\widgets\gui.py", line 1254, in listBox
    clist = ControlledList(clist, lb)
  File "C:\Python34\lib\site-packages\Orange\widgets\gui.py", line 2254, in __init__
    super().__init__(content)
TypeError: 'NoneType' object is not iterable

I used the Iris dataset, and yesterday everything worked properly. Today I can't use Confusion matrix at all.

Orange version 3.3

**Comment by JelenaKitanovic** [comment]
*Version 3.3.7

**Comment by kernc** [comment]
Can you share a minimum working example workflow? On 3.3.7 with below scheme, I can't reproduce.

[untitled.ows.zip](https://github.com/biolab/orange3/files/408843/untitled.ows.zip)

**Comment by JelenaKitanovic** [comment]
Yes of course.
![1](https://cloud.githubusercontent.com/assets/15958687/17515973/f68fe4b8-5e3b-11e6-8773-4a47f77528be.png)
![2](https://cloud.githubusercontent.com/assets/15958687/17515976/f9bbf92e-5e3b-11e6-9a80-b8c8989cc672.png)

Thank you for your response.

**Comment by JelenaKitanovic** [comment]
Even when the canvas is empty, I get an error.

**Comment by JelenaKitanovic** [comment]
I don't have errors anymore. I don't know why . I started Orange again a minute ago and it works. 😄

**Comment by kernc** [comment]
Do you remember what scheme you had and what you did right before the problem started manifesting?

**Comment by ajdapretnar** [comment]
@JelenaKitanovic Is there any chance to reproduce this bug?

**Comment by gbrian** [comment]
Hi,
Same here.

Steps to reproduce:
![image](https://cloud.githubusercontent.com/assets/767180/17844725/b52a1a6a-683c-11e6-9a2b-31524004e4b0.png)

- Add multiple learners and a confusion matrix.
- Open confusion matrix (not sure if needed)
- Remove connection to confusion matrix before saving
- Save
- Reopen project

Temporal fix I done to be able to continue working:
At guy.py (line 1253) check if clist (the expected selected learner list) is None

```
if value is not None:
        clist = getdeepattr(master, value)
        #if clist is not None and not isinstance(clist, (int, ControlledList)):
        if not isinstance(clist, (int, ControlledList)):
            clist = ControlledList(clist, lb)
            master.__setattr__(value, clist)
        setattr(master, value, clist)
        connectControl(master, value, callback, lb.itemSelectionChanged,
                       CallFrontListBox(lb), CallBackListBox(lb, master))

```

Hope this helps.

Great job!

**Comment by gbrian** [comment]
Hi again, 
Seems that: **ConfunsionMatrix** is reusing settings when creating new instances. 
So maybe _selected_learner_ property should be ignored when building a new instance.

![image](https://cloud.githubusercontent.com/assets/767180/17845313/4569d0b2-6841-11e6-8531-ae99149e6e88.png)

It breaks as soon as you create and remove a connection setting the _selected_learner_ as None.

right?
Thanks

**Comment by janezd** [comment]
Thanks, you've really nailed it. I guess #1523 should fix it.
