### ISSUE TITLE
[pandas] Speedup Feature Constructor

### ISSUE THREAD

**Issue by astaric** [biolab/orange3#1519]
Open adult dataset, add a feature constructor widget that turns age into a new string variable.

It takes about a second on current master, but about 5 seconds on pandas branch.

**Comment by kernc** [comment]
Blocks https://github.com/biolab/orange3/pull/1347.

**Comment by sstanovnik** [comment]
It now takes about half a second for me. Try it :)

**Comment by sstanovnik** [comment]
Oh, the issue was that pandas is column-oriented and .iterrows() is VERY slow (in comparison to e.g. numpy). I switched it to a better implementation that also avoids needless recursion.

**Comment by sstanovnik** [comment]
Refactored into a list comprehension.

**Comment by astaric** [comment]
The issue related to a PR that has not been merged and is no longer relevant.
