### ISSUE TITLE
File widget: check if transformations of data type are possible

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#1520]
When changing data type from numeric to datetime and connecting it to Data Table, Data Table crashes. I reckon conversion is not possible (not ISO). Such transformations should probably be only offered if conversion is possible, e.g. if numeric attribute can indeed be transformed to datetime. I think the problem is only with datetime anyway.

p.s. Can strings never be numeric? There's no such option available. Neither there is one for converting nominal to numeric.

**Comment by kernc** [comment]
Strings and categoricals should be convertible too.

**Comment by ajdapretnar** [comment]
I am not sure this is solved. Now I can't change string to datetime, but this is not exactly what this issue is about.
@kernc What do you think? Keep or close?

**Comment by ajdapretnar** [comment]
From testing several data sets I conclude the issue is now solved properly for the time being. Nothing crashes and conversion for now make sense.
