### ISSUE TITLE
AdaBoost Naive Bayes fails to use SAMME

### ISSUE THREAD

**Issue by ngageorange** [biolab/orange3#1521]
##### Orange version

Orange Version 3.3.6
##### Expected behaviour

File --> Selected Column --> Discretize --> Test & Score

Connecting AdaBoost to test & score works well as it assumes a base-classifier to be a tree classifier.
Connecting a Naive Bayes should change the base classifier. Ada boost widget should then work with SAMME instead of SAMME.R
No error should be produced
##### Actual behaviour

Connecting naive bases to adaboost widget assumes SAMME.R making Test& Score widget unable to run.
Error suggests changing algorithm to SAMME.
Doing this continues to give the same error. I.E. Drop-down dialogue for AdaBoost algorithm (SAMME , or SAMME.R) makes no difference 
##### Additional info (worksheets, data, screenshots, ...)

![screen shot 2016-08-24 at 16 44 55](https://cloud.githubusercontent.com/assets/6945849/17937480/26b62d3e-6a1a-11e6-81b8-3336fae151d3.png)
![screen shot 2016-08-24 at 16 45 04](https://cloud.githubusercontent.com/assets/6945849/17937486/29fa2c2a-6a1a-11e6-8c02-89dff1cda37c.png)

**Comment by kernc** [comment]
Ack. Seems like we should check if the connected learner's base sklearn model has `predict_proba()` method and set algorithm to SAMME otherwise. Would you like to make a pull request for this?

**Comment by ajdapretnar** [comment]
https://sentry.io/biolab/orange3/issues/208869953/

I tried to replicate, but now I'm getting this. It is not the same, but I do get an error with Naive Bayes, so linking here.

**Comment by rokgomiscek** [comment]
Connecting Naive Bayes to AdaBoost gives the following error:
![image](https://user-images.githubusercontent.com/3206671/48940838-512e2680-ef19-11e8-80eb-9c0899667935.png)
Can we close this issue?
