### ISSUE TITLE
Color widget modifies existing instances of Variable instead of creating new ones

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#1526]
<img width="268" alt="screen shot 2016-08-28 at 18 16 29" src="https://cloud.githubusercontent.com/assets/2387315/18037505/c1fe2bb4-6d4b-11e6-9d9b-9daf6d0cc48f.png">

Load, say, heart disease and change the color for 'female' to pink. The color also changes in the Box plot.

**Comment by ajdapretnar** [comment]
Cannot reproduce in 3.3.10. I guess it's fixed, I'll try to fish the corresponding PR, but so far I had no luck.
