### ISSUE TITLE
Edit Domain crashes if discrete attributes are re-colored

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#1527]
<img width="316" alt="screen shot 2016-08-28 at 18 19 44" src="https://cloud.githubusercontent.com/assets/2387315/18037515/10fca97a-6d4c-11e6-8d17-d12d6ebf5e5c.png">

```
  File "/Users/janez/Dropbox/orange3/Orange/widgets/data/oweditdomain.py", line 459, in transform
    if vdesc in self.domain_change_hints:
TypeError: unhashable type: 'list'
```

since the Variable contains colors as a list.

Thanks to bug #1526, this also crashes if Edit Domain is connected to File, as in the screenshot in #1526.

**Comment by astaric** [comment]
Another take on this is in PR#1552. The problem occurs because the descriptions of variables in the old domain are not hashable, but we can perform the matching of variables on type, name and values alone.

**Comment by markotoplak** [comment]
Related: color widget should survive even when colors are invalid.
