### ISSUE TITLE
File widget always loads last opened file

### ISSUE THREAD

**Issue by gbrian** [biolab/orange3#1528]
Unexpected behavior with File widget

##### Orange version
3.3.7

##### Expected bahavior
When adding a new File widget no action should be performed just add the new widget

##### Actual behavior
The new File widget added loads last file found on the recent files list

##### Steps to reproduce the behavior

- Add a new File widget
- Load a file
- Add a new one File widget - widget will load same file as first one-

##### Additional info (worksheets, data, screenshots, ...)

On File widget initialization method a "load data" event is shot always.

owfile.py 204
```
# Must not call open_file from within __init__. open_file
# explicitly re-enters the event loop (by a progress bar)
QtCore.QTimer.singleShot(0, self.load_data)

```
I guess this should only be fired if the widget has been loaded from a saved project, maybe could be enough if the widget has an uninitialized data source to control when is a new instance or a loaded one.

Thanks

**Comment by ajdapretnar** [comment]
Dear @gbrian, this is the intended behavior and we consider it a feature. If you wish not to start your workflow with a previously used data set, you can use 'Options - Reset widget settings' or use flag 'clear-widget-settings' if running Orange from the terminal (e.g. `orange-canvas --clear-widget-settings`).

**Comment by gbrian** [comment]
Ops, that explains! :) thanks @ajdapretnar
