### ISSUE TITLE
progress bar shows percentage in thousands

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3#1536]
##### Orange version
3.3.7

##### Expected bahavior
progress should be between 0 and 100

##### Actual behavior
progress in the window bar of Score Plots goes to thousands, say to 12300%

##### Steps to reproduce the behavior
Open fresh Orange, in File read the data from http://bit.ly/1EEB4FX, connect Scatter Plot, click Score Plots and then Start. It is interesting that the wrong scoring appears only the first time this function is used (pressing Pause and then Continue would display the correct counting).

**Comment by kernc** [comment]
When I try this on master, or say on geo-gds360 data set, I get:
```text
--------------------------------------------------------------------------------
TypeError                                     Traceback (most recent call last):
  File "/home/user/orange3/Orange/widgets/visualize/utils/__init__.py", line 209, in toggle
    self.run()
  File "/home/user/orange3/Orange/widgets/visualize/utils/__init__.py", line 187, in run
    for state in self.iterate_states(self.saved_state):
  File "/home/user/orange3/Orange/widgets/visualize/owscatterplot.py", line 59, in iterate_states
    self.attrs = self.score_heuristic()
  File "/home/user/orange3/Orange/widgets/visualize/owscatterplot.py", line 89, in score_heuristic
    attrs = sorted(zip(weights, mdomain.attributes), reverse=True)
TypeError: unorderable types: ContinuousVariable() < ContinuousVariable()
```

**Comment by janezd** [comment]
#1535 fixes that.
