### ISSUE TITLE
Rank Widget Improvements

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3#1547]
##### Orange version
3.3

##### Expected behavior
1. Add “Scoring” box. Shows scoring methods, full name, with checkboxes to decide if the column associated with the scoring method is displayed. Like in Orange2, but plain, with no parameters (always use defaults). Content (classification or regression) based on type of input data set (default, when no data, shows for classification). By default, following methods are checked: Classification: Gain Ratio, Gini Index, Regression: Linear regression, RReliefF (there are no others for now).
2. Scores should have a full name (shown with the checkboxes) and shorter name (column headers).
3. Scores should compute when the scoring method is enabled (checked). If the user unchecks a method, keep the scoring method in cache.
4. Selection of attributes is context dependent (applicable only if attributes are selected manually, not with None, All or Best ranked).
5. Adding scoring methods to the input of the widget only adds a new scoring column (does not alter the content of the box with checkboxes). These columns are always displayed.
6. Implement progress bar (with fat data sets, feature scoring takes quite some time).
7. Consider implementing the score in the background, check how this is done in Test & Score (this feature is optional, but may take substantial time if we postpone it after other issues with this widget are fixed).

##### Actual behavior
Currently the widget displays scores for all the measures. For classification, there are many, and can be quite confusing for the user. Plus computing them all can take substantial time.

**Comment by ajdapretnar** [comment]
Please see also #1495 for this issue. Tnx!
