### ISSUE TITLE
Rank widgets on data without the class variable

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#1556]
... should still show results if it has scorers (such as PCA) that do not need the class attribute.

**Comment by mstrazar** [comment]
When connecting the signal from PCA, the signal doesn't get processed by the signalmanager, and consequently the owrank.set_learner is never reached. 

Stderr output whn connecting PCA to owrank input:
2016-09-16 10:29:19.910 python[22808:3503627] modalSession has been exited prematurely - check for a reentrant call to endModalSession

Any ideas?
