### ISSUE TITLE
Cannot remove single condition in Select Rows widget

### ISSUE THREAD

**Issue by smihael** [biolab/orange3#1588]
This is feature request, not bug report. In Orange 3.3.7 c829d67, there is no possibility to remove a single condition from the "Select Rows" widget, but only Remove all. Would be nice if the button to remove only the selected condition would be added. 

Furthermore but not directly related to that, it would be nice, if the "Select Columns" widget would provide the same filtering options (if the column contain a value then, it should be ignored etc.)

**Comment by RachitKansal** [comment]
@smihael can I work on this issue. I feel that feature to remove just the required condition should also be available.

**Comment by kernc** [comment]
> Furthermore but not directly related to that, it would be nice, if the "Select Columns" widget would provide the same filtering options (if the column contain a value, then it should be ignored etc.)

I completely agree. Please open a separate issue for that.
