### ISSUE TITLE
Variable reuse does not take Variable.attributes into account

### ISSUE THREAD

**Issue by ales-erjavec** [biolab/orange3#1592]
##### Orange version

3.3.*
##### Expected behavior

Loading the following two datasets in the same session

```
image
s
type=image origin=https://example.org/
image.png
```

```
image
s
type=image origin=/some/local/path
image.png
```

should produce two distinct variables with different `v.attributes` dictionary
##### Actual behavior

Only one variable instance is created (depending on which is loaded first) and then reused.

**Comment by astaric** [comment]
@janezd, could we solve this by returning variable proxies in make?

**Comment by janezd** [comment]
No, I guess. `make` must return the same variable, otherwise it won't match in any dicts we use for various fast mappings. Besides, sometimes you want to copy attributes.

Do we have two kinds of `Variable.attributes`? Those that are unique (related to images), so they shouldn't get copied and have to match; and those that are shared, like colors?

**Comment by kernc** [comment]
Couldn't it be a question of:

1. redefining `__eq__` and `__hash__` into something sensible:
    ```py
    def __eq__(self, other):
        return self.name == other.name

    def __hash__(self):
        return hash(self.name)
```
2. not using `Variable.make`,
3. totally defining the vartype → vartype transformation matrix.

Let me know if no. 3 needs any explaining. Currently, we are inconsistent anyway (cf. `__eq__`, `__hash__`).

**Comment by ajdapretnar** [comment]
@ales-erjavec What is the status of this issue? From what I could reproduce (noob skills), the problem remains, but we have two merged PRs as reference...

**Comment by ales-erjavec** [comment]
It seems to be fixed.
