### ISSUE TITLE
Distances outputs data without Apply

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#1596]
*Apply automatically * is off by default in Distances. Yet the widget outputs data (check in HierClust).
I think by default, *Apply automatically* should be on. However, when I changed the defaults to 'checked' and unchecked *Apply* when running Orange, the widget still output the data. The the issue is still somewhere else, not only in defaults.
When I uncheck *Apply* and I change the parameters, the widget is not sending data onwards (which is correct). It also behaves well when *Apply automatically* is on and I change the parameters - it updates the output.
Only when connecting the widget for the first time, the issue is there.

**Comment by janezd** [comment]
Works as intended, although not always (but still often) desired.
