### ISSUE TITLE
Distances widget could include an option for deciding whether to include targets or not

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#1604]
Although this could be achieved by Select Columns, a part of the motivation is also to make the user aware of the issue. Currently it is not clear if targets are currently included or not.

**Comment by ajdapretnar** [comment]
That's an easy one, but do we still want it? @janezd

**Comment by janezd** [comment]
No. It does not make much sense in most contexts, and it would be a slight complication in computation of distances. I'm closing this for until we migrate to pandas.
