### ISSUE TITLE
Support for Qt 5.x on anaconda orange3

### ISSUE THREAD

**Issue by brylie** [biolab/orange3#1613]
##### Orange version

orange3
##### Expected bahavior

Orange 3 should be compatible with the latest version of Qt 5.x via the Anaconda Python platform.
##### Actual behavior

When trying to install `orange3` via conda, the following message appears

```
conda install orange3
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /home/brylie/anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    qt-4.8.7                   |                4        32.7 MB

The following NEW packages will be INSTALLED:

    orange3:            3.3.6-py35_0     
    pyqtgraph:          0.9.10-py35_1    

The following packages will be DOWNGRADED due to dependency conflicts:

    anaconda-navigator: 1.3.1-py35_0      --> 1.2.3-py35_0     
    matplotlib:         1.5.3-np111py35_0 --> 1.5.1-np111py35_0
    pyqt:               5.6.0-py35_0      --> 4.11.4-py35_4    
    qt:                 5.6.0-0           --> 4.8.7-4          
    qtconsole:          4.2.1-py35_1      --> 4.2.1-py35_0     
    spyder:             3.0.0-py35_0      --> 2.3.9-py35_1
```
##### Steps to reproduce the behavior
1. Install Anaconda
2. Upgrade Qt to 5.x
3. Try to install orange 3 `conda install orange3`
##### Additional info (worksheets, data, screenshots, ...)

Anaconda packages, such as anaconda-navigator and Spyder have recently added Qt 5 support. After upgrading these packages, it is not possible to install orange 3 without downgrading them.

**Comment by goanpeca** [comment]
Is there any plan to make orange qt5 compatible? This can be achieved gradually by using https://github.com/spyder-ide/qtpy, we use that approach in Spyder to great success.

**Comment by kernc** [comment]
We have a Qt5-compatible branch mostly ready in https://github.com/biolab/orange3/pull/1171. Unfortunately, we seem to currently rely on an in-house [yet another abstraction layer](https://github.com/ales-erjavec/anyqt/).

Base Orange does work with qtpy quite nicely, happy to report. Personally, I'd prefer to use qtpy, but there is, for what I've been able to quickly test, one bug (https://github.com/spyder-ide/qtpy/issues/76) that should be addressed on either of sides.

The other bug is more feature-requestish and structural (https://github.com/spyder-ide/qtpy/issues/77). Orange depends on lots of third-parties and has add-on, not all can be expected to keep up with pace. If PyQtGraph didn't yet work with PyQt5 or if some other package we depend on, like a simple package containing a [QRangeSlider widget](https://github.com/rsgalloway/qrangeslider), or whatever, hasn't yet been updated to work with PyQt5, we would be _barred from trying PyQt5_ lest we fork and patch everything. Anyway, it just seems a reasonable thing to expect from an abstraction layer to convenience apps that import modules that import from some other version of PyQt if this can be achieved without much effort. AnyQt does this, I think. So all the add-ons and third-parties remain to work, at least to a significant degree.

**Comment by brylie** [comment]
OK, cool. Hopefully these issues can be resolved upstream. :smiley:

**Comment by brylie** [comment]
@kernc is there an issue or place where we can follow progress for Orange Qt5 support?

**Comment by ajdapretnar** [comment]
@brylie Support was introduced on Oct 21 with #1171. There have been some subsequent bugs related to introduction of PyQt5, you can find in PR section. PyQt5 support is being added also to add-ons, e.g. [Text](https://github.com/biolab/orange3-text/pulls?q=is%3Apr+is%3Aclosed).

**Comment by kernc** [comment]
In a Qt5 environment, you can test it by setting `QT_API` env variable:
```bash
$ QT_API=pyqt5 python -m Orange.canvas
```

**Comment by brylie** [comment]
Cool beans. I am just hoping that Orange3 gets added back to the Anaconda Navigator, since it is a really convenient way to install/manage Python projects. It is also good visibility for Orange3 :smiley:

**Comment by goanpeca** [comment]
@kernc if you could make the PRs against QtPy we would welcome them.

**Comment by ajdapretnar** [comment]
Orange is Qt5 compatible since 3.3.9. Subsequent bugs should be resolved as separate issues.

**Comment by brylie** [comment]
@goanpeca any chance of getting Orange >= 3.3.9 back on the Anaconda Navigator front page? Should I open, or comment in, any upstream issue?
