### ISSUE TITLE
Hierarchical clustering shows wrong labels when distances are computed from columns

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3#1626]
##### Orange version

3.8
##### Expected bahavior

By default, dendrogram should show Attribute names, and while this is marked in Annotation box, it actually shows attribute ids.
##### Actual behavior

Annotation shows "Attribute names", while attribute ids are shown as labels.
##### Steps to reproduce the behavior

File (Iris) -> Distances (between columns) -> Hierarchical Clustering

**Comment by RachitKansal** [comment]
@BlazZupan have a look at PR #1701. Does it solve the problem?

**Comment by janezd** [comment]
Fixed via #1748.
