### ISSUE TITLE
Column distances seem too large

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3#1627]
##### Orange version

3.8
##### Expected bahavior

Column distances from the Distance widget seem too large compared to row distances.
##### Actual behavior

When distances are computed from columns, the numbers look too high, compared to distances computed from rows. Looks like no normalization was done. 
##### Steps to reproduce the behavior

File (say, Iris) -> Distances (compare distances between rows and columns).

**Comment by robertcv** [comment]
There was really no normalization. In Orange version 3.9 a normalize checkbox was added to Distance Widget.
