### ISSUE TITLE
File should not autoload the last file used, if file too large.

### ISSUE THREAD

**Issue by ecerulm** [biolab/orange3#1631]
##### Orange version

3.3.7
##### Expected bahavior

Adding File should not autoload the last file used, if loading that file requires too much time,
##### Actual behavior

Adding File makes Orange to completely freezes since it tries to load the last file I tried (a csv that is 1.5GB and it's malformed). Orange enter the "(Not Responding)" state and will never complete.
##### Steps to reproduce the behavior

Add a very big CVS file , kill Canvas, and add a File and it will freeze right away (since it's trying to load the last file again). 
##### Additional info (worksheets, data, screenshots, ...)

I guess that there is no point of loading the whole CSV until it's really needed so I would suggest to defer the loading. Probably is loaded for preview purposes (?), maybe it's possible to check size of file first and load only first 100 rows. 

Right now I'm was forced to move the file so that Canvas fails gracefully to load it. But the hardest part was to figure out what was happening, I didn't realize straight away that it was trying to load the last recently used file. And I had to guess which file it was.

**Comment by ajdapretnar** [comment]
You can always use Options - Reset widget settings... to clear widget settings and start anew. The scripting alternative is `orange-canvas --clear-widget-settings`.
However, I agree Orange might refer from loading excessively large data sets by default.

**Comment by kernc** [comment]
It should be possible to check the size first, and defer if too large.
