### ISSUE TITLE
Anaconda distributions requires pyqt4 but using pyqt5

### ISSUE THREAD

**Issue by opengeostat** [biolab/orange3#1666]
Please add pyqt=4 in dependencies. When installing orange3 with Anaconda it uses pyqt5. This can be fixed by forcing a pyqt4 installation, for example: 

(py3) C:\Users\adrian>conda install -f -c conda-forge oranege3 pyqt=4

**Comment by astaric** [comment]
pyqt requirement has been pinned in the conda-forge recipe:

https://github.com/conda-forge/orange3-feedstock/commit/0ac787a157338d2de15b866676612b596c1062dc

In the future, please open such issues directly on https://github.com/conda-forge/orange3-feedstock/issues
