### ISSUE TITLE
[REQUEST] ruledatastopping criteria needs to be more flexible

### ISSUE THREAD

**Issue by dheerajvc** [biolab/orange3#1682]
##### Orange version

2.7.8
##### Expected behavior

in Orange.classification.rules.RuleLearner, I want to stop rule specialization when  a minimum number of observations in target class are reached.
##### Actual behavior

I dont see any option to specify any other function other than **RuleDataStoppingCriteria_NoPositives**

**Comment by ajdapretnar** [comment]
This refers to Orange2, while this repository if for Orange3. Mind you, Orange2 is no longer actively maintained, so I suggest you to try Orange3. We currently have CN2 algorithm for rule induction and a separate add-on for [Association Rules](https://github.com/biolab/orange3-associate), if you care to give it a go.
We're open for improvements in current projects (however, you can always contribute to Orange2 yourself, if you want to),

**Comment by ajdapretnar** [comment]
@dheerajvc Would you like to submit a feature request for Orange3? If yes, please edit the issue. If not, kindly close this issue.

**Comment by ajdapretnar** [comment]
I'm closing this as not relevant to Orange3. If desired, a feature request can be opened as a separate issue.
