### ISSUE TITLE
Missing compiler_cxx fix for MSVCCompiler + ubuntu

### ISSUE THREAD

**Issue by anilkodepaka** [biolab/orange3#1700]
ERROR while building windows version installer, It stops with this error.

~/orange3$ scripts/windows/build-win-application.sh
.
.
.
.
build_src: building npy-pkg config files
running build_py
copying Orange/version.py -> build/lib.linux-x86_64-3.4/Orange
running build_ext
No module named 'numpy.distutils.msvccompiler' in numpy.distutils; trying from distutils
customize MSVCCompiler
customize MSVCCompiler using build_ext
No module named 'numpy.distutils.msvccompiler' in numpy.distutils; trying from distutils
customize MSVCCompiler
Missing compiler_cxx fix for MSVCCompiler
customize MSVCCompiler using build_ext
building 'Orange.classification._simple_tree' extension
compiling C sources
error: Python was built with Visual Studio version 6, and extensions need to be built with the same version of the compiler, but it isn't installed.

Python Ver: 3.4.4
pip 8.1.2
numpy (1.9.2)
scipy (0.16.1)

OS: Ubuntu 14.04

Has anyone faced this issue? thanks for your tips.

**Comment by anilkodepaka** [comment]
Here is the full log:

(orange3venv) ubuntu@:~/orange3$ scripts/windows/build-win-application.sh
Requirement already satisfied (use --upgrade to upgrade): pip==8.1.2 in /home/ubuntu/orange3venv/lib/python3.4/site-packages

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,1 CPU)

Processing archive: build/temp.download-cache/numpy-1.9.2-win32-superpack-python3.4.exe

Extracting  $PLUGINSDIR/cpucaps.dll
Extracting  numpy-1.9.2-sse3.exe
Extracting  numpy-1.9.2-sse2.exe
Extracting  numpy-1.9.2-nosse.exe

Everything is Ok

Files: 4
Size:       12389009
Compressed: 8247992

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,1 CPU)

Processing archive: build/temp.download-cache/scipy-0.16.1-win32-superpack-python3.4.exe

Extracting  $PLUGINSDIR/cpucaps.dll
Extracting  scipy-0.16.1-sse3.exe
Extracting  scipy-0.16.1-sse2.exe
Extracting  scipy-0.16.1-nosse.exe

Everything is Ok

Files: 4
Size:       65612163
Compressed: 65670173
Collecting numpy==1.10.4
  Using cached numpy-1.10.4-cp34-cp34m-manylinux1_x86_64.whl
  Saved ./build/temp.win32-py3.4-installer/wheelhouse/numpy-1.10.4-cp34-cp34m-manylinux1_x86_64.whl
Collecting scipy==0.16.1
  Using cached scipy-0.16.1-cp34-cp34m-manylinux1_x86_64.whl
  Saved ./build/temp.win32-py3.4-installer/wheelhouse/scipy-0.16.1-cp34-cp34m-manylinux1_x86_64.whl
Skipping numpy, due to already being wheel.
Skipping scipy, due to already being wheel.
Requirement already satisfied (use --upgrade to upgrade): pip==8.1.2 in /home/ubuntu/orange3venv/lib/python3.4/site-packages
Ignoring indexes: https://pypi.python.org/simple
Requirement already satisfied (use --upgrade to upgrade): numpy==1.9.2 in /home/ubuntu/orange3venv/lib/python3.4/site-packages
Collecting wheel==0.26.*
  Using cached wheel-0.26.0-py2.py3-none-any.whl
Installing collected packages: wheel
  Found existing installation: wheel 0.29.0
    Uninstalling wheel-0.29.0:
      Successfully uninstalled wheel-0.29.0
Successfully installed wheel-0.26.0
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "Orange.classification._simple_tree" sources
building extension "Orange.classification._tree_scorers" sources
building extension "Orange.data._valuecount" sources
building extension "Orange.data._contingency" sources
building extension "Orange.data._io" sources
building extension "Orange.data._variable" sources
building extension "Orange.preprocess._discretize" sources
building extension "Orange.preprocess._relieff" sources
building extension "Orange.widgets.utils._grid_density" sources
build_src: building npy-pkg config files
running build_py
copying Orange/version.py -> build/lib.linux-x86_64-3.4/Orange
running build_ext
No module named 'numpy.distutils.msvccompiler' in numpy.distutils; trying from distutils
customize MSVCCompiler
customize MSVCCompiler using build_ext
No module named 'numpy.distutils.msvccompiler' in numpy.distutils; trying from distutils
customize MSVCCompiler
Missing compiler_cxx fix for MSVCCompiler
customize MSVCCompiler using build_ext
building 'Orange.classification._simple_tree' extension
compiling C sources
error: Python was built with Visual Studio version 6, and extensions need to be built with the same version of the compiler, but it isn't installed.
(orange3venv) ubuntu:~/orange3$

**Comment by anilkodepaka** [comment]
hei, what happened to this url reference in scripts/windows/build-win-application.sh??


(orange3venv) ubuntu@:~/orange3$ wget https:/orange.biolab.si/files/3rd-party/34/vcredist_x86.exe
--2016-11-02 16:16:05--  ftp://https//orange.biolab.si/files/3rd-party/34/vcredist_x86.exe
           => ‘vcredist_x86.exe’
Resolving https (https)... failed: Name or service not known.
wget: unable to resolve host address ‘https’

As a result function function "prepare_msvredist " is missing from prepare all list!!

**Comment by ales-erjavec** [comment]
Sorry but the windows installer can only be build on windows.

**Comment by anilkodepaka** [comment]
hei..tried on windows + conda 
It somehow got stuck at this numpy again!!


PS C:\Users\Desktop\ORANGE\orange3> python setup.py build_ext --inplace --compile=mingw32
C:\Program Files (x86)\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.5.egg\setuptools\dist.py:331: UserWarning: Normalizing '3.3.9.dev0+Unknown' to '3.3.9.dev0+unknown'
running build_ext
running build_src
build_src
building extension "Orange.classification._simple_tree" sources
building extension "Orange.classification._tree_scorers" sources
building extension "Orange.data._valuecount" sources
building extension "Orange.data._contingency" sources
building extension "Orange.data._io" sources
building extension "Orange.data._variable" sources
building extension "Orange.preprocess._discretize" sources
building extension "Orange.preprocess._relieff" sources
building extension "Orange.widgets.utils._grid_density" sources
build_src: building npy-pkg config files
Traceback (most recent call last):
  File "setup.py", line 277, in <module>
    setup_package()
  File "setup.py", line 273, in setup_package
    **extra_args
  File "C:\Program Files (x86)\Anaconda3\lib\site-packages\numpy\distutils\core.py", line 169, in setup
    return old_setup(**new_attr)
  File "C:\Program Files (x86)\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Program Files (x86)\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Program Files (x86)\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Program Files (x86)\Anaconda3\lib\site-packages\numpy\distutils\command\build_ext.py", line 117, in run
    force=self.force)
  File "C:\Program Files (x86)\Anaconda3\lib\site-packages\numpy\distutils\ccompiler.py", line 597, in new_compiler
    compiler = klass(None, dry_run, force)
  File "C:\Program Files (x86)\Anaconda3\lib\site-packages\numpy\distutils\mingw32ccompiler.py", line 58, in __init__
    dry_run, force)
  File "C:\Program Files (x86)\Anaconda3\lib\distutils\cygwinccompiler.py", line 126, in __init__
    if self.ld_version >= "2.10.90":
TypeError: unorderable types: NoneType() >= str()

**Comment by ajdapretnar** [comment]
Initial issue not accurate (Win packages cannot be run on Ubuntu). The rest is a replicate of #1732.
