### ISSUE TITLE
Outdated screenshots

### ISSUE THREAD

**Issue by lanzagar** [biolab/orange3#1705]
This issue is intended for keeping track of GUI modifications in widgets, which require the screenshots to be updated and the documentation to be reviewed.
**Note**: Documentation (text) should be kept up to date and reflect the current features. This is only to avoid frequent and unnecessary retaking of screenshots for a widget that is being changed (perhaps in multiple PRs).

The proposed plan is to do a batch update before each new major release.

**Comment by lanzagar** [comment]
List of widget changes for 3.3.9
(Edit this comment instead of posting new ones)

- Data/Preprocess (Randomize) #1704

**Comment by kernc** [comment]
This is a better idea than
```bash
git log --numstat 3.3.8..HEAD | 
    awk '/Orange\/.+\/ow.+\.py$/{ print $3 }' | 
    awk -F'/' '{ print $NF }' | 
    sort | 
    uniq -c
```
?

**Comment by astaric** [comment]
AnyQt PR touched all the widgets. The same might happen with refactorings/moving stuff around/... As the screenshot are currently remade manually, I would prefer if we avoid false positives (which the automatic solution would generate).

**Comment by kernc** [comment]
If not immediately, I fear sooner than later recall will get low with any such manual tracking.

On a side note, I find it somewhat problematic that the repository grows by 20MB whenever the docs are overhauled.
```bash
% du -hc doc/visual-programming/source/widgets/*/images
2.0M	doc/visual-programming/source/widgets/classify/images
5.9M	doc/visual-programming/source/widgets/data/images
2.0M	doc/visual-programming/source/widgets/evaluation/images
1.5M	doc/visual-programming/source/widgets/regression/images
2.7M	doc/visual-programming/source/widgets/unsupervised/images
3.4M	doc/visual-programming/source/widgets/visualize/images
18M	total
```
Indexed PNGs would take one third of the size without noticeable loss of quality.

**Comment by lanzagar** [comment]
Have you tried running that command? It prints 95 filenames - which is more or less all widgets (find `ow*.py` prints 102). So for this version the git command is useless. I think for a smaller release in the future it might be different and have no objections against using it too.
But the point of having an issue open for tracking this is so people have a place for discussion (maybe a widget changed, but has further changes planned, and we want to wait until it's finished). Also, we can all see the list (instead of multiple people going over that git output) etc.
And I don't think it is bad, that someone making widget changes is actually forced to think about this issue too - changing the GUI has consequences and they should be kept in mind when redesigning.

In the end I think the person who takes over this task will see what works best for him/her and can track it as they see fit.

As for the side note - I completely agree that we should pay attention to size. Indexed PNGs sound good to me.
