### ISSUE TITLE
Widget properties bug

### ISSUE THREAD

**Issue by lanzagar** [biolab/orange3#1708]
##### Orange version

3.3.8

##### Steps to reproduce the behavior
Bug reported from orange. I was not able to reproduce, but @ales-erjavec will probably be able to recognize the problem.

##### Additional info (worksheets, data, screenshots, ...)
The line: https://github.com/biolab/orange3/blob/master/Orange/canvas/scheme/widgetsscheme.py#L92
can fail with:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Can you see in what circumstances the properties being compared are a numpy array and fix the comparison?

(This was from bug report
Orange.widgets.data.owfile/3.3.8/Orange.canvas.scheme.widgetsscheme%3A93/2016-11-03T08%3A10%3A09.925948.txt )

**Comment by ajdapretnar** [comment]
Is this still relevant for 3.3.10?

**Comment by ajdapretnar** [comment]
@lanzagar Is this relevant for the current version?

**Comment by lanzagar** [comment]
Not sure as I didn't know how to reproduce this bug from Sentry.
I guess we can close, and if it reappears in newer versions open again.
