### ISSUE TITLE
Mosaic Display not working with data subset

### ISSUE THREAD

**Issue by rokgomiscek** [biolab/orange3#1710]
##### Actual behavior
Widget displays error message, no visualization

##### Steps to reproduce the behavior
File -> Mosaic Display
File -> Data Table (select some rows) -> Mosaic Display

**Comment by ajdapretnar** [comment]
@rokgomiscek Could you please test if the problem persists with the latest version? I can't replicate on iris.tab, is there any specific data set that causes such behavior?

**Comment by astaric** [comment]
This has been fixed in #2014. The problem was that discretizer removed constant features (all features are constant if you only select one instance).
