### ISSUE TITLE
owfile: Memory errors

### ISSUE THREAD

**Issue by lanzagar** [biolab/orange3#1713]
##### Orange version

3.3.8

##### Expected behavior
Orange shows an error when an operation runs out of memory.
(Might be hard to catch?)

##### Actual behavior
Orange crashes with error reporting option shown.

##### Steps to reproduce the behavior
The reported error crashed in apply_edit_domain:
https://github.com/biolab/orange3/blob/master/Orange/widgets/data/owfile.py#L419
But we need to consider other locations with big memory allocations.

**Comment by ajdapretnar** [comment]
@lanzagar What is the status of this? I know @jerneju has been dealing with memory errors diligently some time ago.

#2521 
#2441 
#2374 
#2397 
#2316 

But nothing has been done regarding the File widget. Could we sample, just like in SQL? If the file is too big, load only the first n lines and m columns? (column restriction should probably be very loose)

**Comment by lanzagar** [comment]
I think this was opened as a more general todo item, for us to consider. As it is over a year old, we can probably close this and work on specific problems encountered more recently.
