### ISSUE TITLE
Windows installation fails to recognize Anaconda Python

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#1736]
##### Orange version
3.3.8

##### Expected behavior
Windows installation should recognize existing Anaconda Python installation and use it.

##### Actual behavior
Python 3.4 is installed alongside Anaconda.

##### Steps to reproduce the behavior
Clean Windows OS with Anaconda pre-installed. Install built version of Orange from the website.

**Comment by anilkodepaka** [comment]
Do you have multiple instances of Python? what does PATH list contain? is there a conflict? Also check for order.

**Comment by astaric** [comment]
I am not sure that orange installer can/should install orange into conda python. Conda is not really fond of packages installed by external installers.

Perhaps we just need to add conda installation steps to the download pages for windows (they are currently only included on linux pages.
