### ISSUE TITLE
Box Plot labels fall out of view

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#1737]
##### Orange version
3.3.9.dev0+7dca993

##### Expected behavior
All important information in Box Plot are in place (visible).

##### Actual behavior
Sometimes labels and even visualizations fall out of view.

##### Steps to reproduce the behavior
Housing.tab with Box Plot. CHAS attribute.

##### Additional info (worksheets, data, screenshots, ...)
![box-plot-fallout](https://cloud.githubusercontent.com/assets/12524972/20142878/d7d385cc-a696-11e6-837b-17137f002de5.png)

**Comment by astaric** [comment]
@janezd, while the box no longer falls out of the view, the left number still does. Can you have a look?

**Comment by janezd** [comment]
@lanzagar wrote: *But in addition to elements falling out of viewport, there seem to be factual errors in box plot, e.g. CHAS variable shows median at 1, when it should be 0 (lots of 0 values, few 1s).*

**Comment by ajdapretnar** [comment]
What for the love of God is this:
<img width="893" alt="screen shot 2018-07-24 at 14 04 03" src="https://user-images.githubusercontent.com/12524972/43136922-779f49d6-8f4a-11e8-8ca7-87230ce9446c.png">


- [ ] Fix left number falling out of view.
- [ ] Fix display of axis numbers (shorten decimal places if 0, avoid overlapping, don't display axis number like in the example above).
- [ ] Fix computation of median for CHAS (see the above comment).

**Comment by ajdapretnar** [comment]
Fixed the two issues that can be solved easily. The first one supposedly requires a larger rewrite, so the introduced solutions will have to do for now.
