### ISSUE TITLE
Unable to load AddOns list from Options -> Addons (Windows 7)

### ISSUE THREAD

**Issue by lcota** [biolab/orange3#1757]
Orange version 3.3.6

##### Expected behavior
Show list of installable addons, and install

##### Actual behavior
Unable to get Addons list 

** Appears to be an issue with treating pypi.python.org as a trusted host

##### Additional info (worksheets, data, screenshots, ...)
TimeoutError: [WinError 10060] A connection attempt failed because the connecte
d party did not properly respond after a period of time, or established connect
ion failed because connected host has failed to respond

**Comment by kernc** [comment]
Indeed, this has been fixed already a while ago. Download a fresher copy: http://orange.biolab.si/download/
Thanks.

**Comment by lcota** [comment]
Is it possible to install a fresher copy using pip or conda to make use of an existing python install?

**Comment by ajdapretnar** [comment]
Yes, you can always update to the latest release with `pip install --upgrade orange3`. As for conda, the recipe is:
```
conda config --add channels conda-forge
conda install --upgrade orange3
```

**Comment by bhrigs** [comment]
Does not seem to be fixed for me with the latest copy. Help!

**Comment by PrimozGodec** [comment]
See: https://github.com/biolab/orange3/issues/3001
