### ISSUE TITLE
Can't save a Classifier that was created with Features that come from a Feature Constructor

### ISSUE THREAD

**Issue by lopezco** [biolab/orange3#1758]
## Orange version
3.3.9.dev0+1036e49

## Expected behavior
Be able to save a classifier that was created with features that come from a feature constructor

## Actual behavior
Orange3 crashes  because lambda functions can't be serialized using pickle

**Exception:**```_pickle.PicklingError: Can't pickle <function <lambda> at 0x7fe4d99df1e0>: attribute lookup <lambda> on __main__ failed```

**Module:**```Orange.widgets.classify.owsaveclassifier:84```

**Widget Name:** ```Save Classifier```

**Widget Module:** ```Orange.widgets.classify.owsaveclassifier:116```

**Environment:** ```Python 3.5.2 on Linux 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64```

**Stack Trace:**
```Traceback (most recent call last):
  File "Orange/widgets/classify/owsaveclassifier.py", line 116, in browse
    self.save(filename)
  File "Orange/widgets/classify/owsaveclassifier.py", line 84, in save
    pickle.dump(self.model, f)
_pickle.PicklingError: Can't pickle <function <lambda> at 0x7fe4d99df1e0>: attribute lookup <lambda> on __main__ failed
```
**Local Variables:**
```
OrderedDict([('f', <_io.BufferedWriter name='/home/jose.lopez/qsdqsdqs.pkcls'>),
             ('filename', '/home/jose.lopez/qsdqsdqs.pkcls'),
             ('self',
              <Orange.widgets.classify.owsaveclassifier.OWSaveClassifier object at 0x7fe4d871f168>)])

```

## Steps to reproduce the behavior
1- Load a file
2- Create some features
3- Add a classifier
4- Try to save ir

## Additional info (worksheets, data, screenshots, ...)
![orange_error](https://cloud.githubusercontent.com/assets/6637618/20387563/fb41e488-acc0-11e6-9bbf-a119fee2260d.png)

**Comment by kernc** [comment]
Thanks for a tidy bug report!

A proposed solution in https://github.com/biolab/orange3/pull/1759.
