### ISSUE TITLE
File Widget doesn't persist column mappings

### ISSUE THREAD

**Issue by alew3** [biolab/orange3#1773]
##### Orange version

3.3.8 git revision ba271f1
MacOS Sierra 10.12.1

##### Expected behavior

Column role mappings (meta, target values, nominal, etc..) on the File Widget should persist after saving a project and reloading.

##### Actual behavior

After closing and opening a project they don't persist and I have to manually reconfigure them.

##### Steps to reproduce the behavior

Save a project and open the project again.

**Comment by ajdapretnar** [comment]
Can confirm this bug on Windows, too.

**Comment by lanzagar** [comment]
This will not be finished and tested today, so bumping to 3.3.10
