### ISSUE TITLE
Build error on windows7 64 bit

### ISSUE THREAD

**Issue by binggouxsm** [biolab/orange3#1780]
##### Orange version
Orange=3.3.8

##### Expected behavior
Application build successfully

##### Actual behavior
```
(orange3venv) D:\My Documents\GitHub\orange3>pip install -e .
Obtaining file:///D:/My%20Documents/GitHub/orange3
Requirement already satisfied: bottleneck>=1.0.0 in d:\anaconda3\lib\site-packag
es (from Orange3==3.3.8)
Requirement already satisfied: chardet>=2.3.0 in d:\workspace\project\orange\ora
nge3venv\lib\site-packages (from Orange3==3.3.8)
Requirement already satisfied: docutils in d:\anaconda3\lib\site-packages (from
Orange3==3.3.8)
Requirement already satisfied: joblib>=0.9.4 in d:\workspace\project\orange\oran
ge3venv\lib\site-packages (from Orange3==3.3.8)
Requirement already satisfied: keyring in d:\workspace\project\orange\orange3ven
v\lib\site-packages (from Orange3==3.3.8)
Requirement already satisfied: keyrings.alt in d:\workspace\project\orange\orang
e3venv\lib\site-packages (from Orange3==3.3.8)
Requirement already satisfied: numpy>=1.9.0 in d:\anaconda3\lib\site-packages (f
rom Orange3==3.3.8)
Requirement already satisfied: pyqtgraph>=0.9.10 in d:\workspace\project\orange\
orange3venv\lib\site-packages (from Orange3==3.3.8)
Requirement already satisfied: scikit-learn>=0.18 in d:\workspace\project\orange
\orange3venv\lib\site-packages (from Orange3==3.3.8)
Requirement already satisfied: scipy>=0.11.0 in d:\anaconda3\lib\site-packages (
from Orange3==3.3.8)
Requirement already satisfied: xlrd>=0.9.2 in d:\anaconda3\lib\site-packages (fr
om Orange3==3.3.8)
Requirement already satisfied: pywin32-ctypes; sys_platform == "win32" in d:\wor
kspace\project\orange\orange3venv\lib\site-packages (from keyring->Orange3==3.3.
8)
Installing collected packages: Orange3
  Found existing installation: Orange3 3.3.8
    Uninstalling Orange3-3.3.8:
      Successfully uninstalled Orange3-3.3.8
  Running setup.py develop for Orange3
    Complete output from command d:\workspace\project\orange\orange3venv\scripts
\python.exe -c "import setuptools, tokenize;__file__='D:\\My Documents\\GitHub\\
orange3\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().rep
lace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no
-deps:
    running develop
    running egg_info
    writing entry points to Orange3.egg-info\entry_points.txt
    writing Orange3.egg-info\PKG-INFO
    writing dependency_links to Orange3.egg-info\dependency_links.txt
    writing top-level names to Orange3.egg-info\top_level.txt
    writing requirements to Orange3.egg-info\requires.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'Orange3.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.basket' under directory 'Orange\datasets
'
    warning: no files found matching '*.css' under directory 'Orange\widgets\_hi
ghcharts'
    warning: no files found matching 'COPYING'
    writing manifest file 'Orange3.egg-info\SOURCES.txt'
    Cannot compile extensions. numpy is required to build Orange.

    ----------------------------------------
  Rolling back uninstall of Orange3
Command "d:\workspace\project\orange\orange3venv\scripts\python.exe -c "import s
etuptools, tokenize;__file__='D:\\My Documents\\GitHub\\orange3\\setup.py';f=get
attr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.clo
se();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error
 code 1 in D:\My Documents\GitHub\orange3\
```

##### Steps to reproduce the behavior
1. install Anaconda 4.2.0 for 64 bit windows based on python 3.5
2. conda install virtualenv 
3. install Cygwin
4. virtualenv --python=python3 --system-site-packages orange3venv
5. set PATH , INCLUDE . LIBPATH

SET “PATH=D:\workspace\project\orange\orange3venv\Scripts;D:\Anaconda3;D:\Anaconda3\Scripts;D:\Anaconda3\Library\bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include;C:\cygwin64;C:\cygwin64\bin;C:\cygwin64\lib;%PATH%”

echo %PATH%

SET “INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib;C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt;C:\Program Files (x86)\Windows Kits\8.1\Include\shared;C:\Program Files (x86)\Windows Kits\8.1\Include\um;C:\Program Files (x86)\Windows Kits\8.1\Include\winrt;”

SET “LIBPATH=C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib;C:\Program Files (x86)\Windows Kits\8.1\References\CommonConfiguration\Neutral;”

6. copy lib files from visual studio to virtual env lib directory
source : C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib
target :  D:\workspace\project\orange\orange3venv\libs

7.download orange source code using git
git clone https://github.com/biolab/orange3.git
I choose the stable branch 

8.activate orange3venv
D:\workspace\project\orange\orange3venv\Scripts\activate

9.start to build 
pip install -r requirements-core.txt
pip install -r requirements-dev.txt
pip install -r requirements-doc.txt
pip install -r requirements-gui.txt
pip install -r requirements-sql.txt
pip install -e .

##### Additional info (worksheets, data, screenshots, ...)
pip list 

alabaster (0.7.9)
anaconda-clean (1.0)
anaconda-client (1.5.1)
anaconda-navigator (1.3.1)
argcomplete (1.0.0)
astroid (1.4.7)
astropy (1.2.1)
Babel (2.3.4)
backports.shutil-get-terminal-size (1.0.0)
beautifulsoup4 (4.5.1)
bitarray (0.8.1)
blaze (0.10.1)
bokeh (0.12.2)
boto (2.42.0)
Bottleneck (1.1.0)
certifi (2016.9.26)
cffi (1.7.0)
chardet (2.3.0)
chest (0.2.3)
click (6.6)
cloudpickle (0.2.1)
clyent (1.2.2)
colorama (0.3.7)
CommonMark (0.5.4)
comtypes (1.1.2)
conda (4.1.12)
conda-build (2.0.2)
conda-env (2.5.0a0)
configobj (5.0.6)
contextlib2 (0.5.3)
cryptography (1.5)
cycler (0.10.0)
Cython (0.24.1)
cytoolz (0.8.0)
dask (0.11.0)
datashape (0.5.2)
decorator (4.0.10)
dill (0.2.5)
docutils (0.12)
dynd (c328ab7)
et-xmlfile (1.0.1)
fastcache (1.0.2)
filelock (2.0.6)
flake8 (3.2.1)
flake8-polyfill (1.0.1)
Flask (0.11.1)
Flask-Cors (2.1.2)
gevent (1.1.2)
greenlet (0.4.10)
h5py (2.6.0)
HeapDict (1.0.0)
idna (2.1)
imagesize (0.7.1)
ipykernel (4.5.0)
ipython (5.1.0)
ipython-genutils (0.1.0)
ipywidgets (5.2.2)
itsdangerous (0.24)
jdcal (1.2)
jedi (0.9.0)
Jinja2 (2.8)
joblib (0.10.3)
jsonschema (2.5.1)
jupyter (1.0.0)
jupyter-client (4.4.0)
jupyter-console (5.0.0)
jupyter-core (4.2.0)
keyring (10.0.2)
keyrings.alt (1.1.1)
lazy-object-proxy (1.2.1)
llvmlite (0.13.0)
locket (0.2.0)
lxml (3.6.4)
mando (0.3.3)
MarkupSafe (0.23)
matplotlib (1.5.3)
mccabe (0.5.2)
menuinst (1.4.1)
mistune (0.7.3)
mpmath (0.19)
multipledispatch (0.4.8)
nb-anacondacloud (1.2.0)
nb-conda (2.0.0)
nb-conda-kernels (2.0.0)
nbconvert (4.2.0)
nbformat (4.1.0)
nbpresent (3.0.2)
networkx (1.11)
nltk (3.2.1)
nose (1.3.7)
notebook (4.2.3)
numba (0.28.1)
numexpr (2.6.1)
numpy (1.11.1)
numpydoc (0.6.0)
odo (0.5.0)
openpyxl (2.3.2)
pandas (0.18.1)
partd (0.3.6)
path.py (0.0.0)
pathlib2 (2.1.0)
patsy (0.4.1)
pep8 (1.7.0)
pickleshare (0.7.4)
Pillow (3.3.1)
pip (9.0.1)
pkginfo (1.3.2)
ply (3.9)
prompt-toolkit (1.0.3)
psutil (4.3.1)
psycopg2 (2.6.2)
py (1.4.31)
pyasn1 (0.1.9)
pycodestyle (2.2.0)
pycosat (0.6.1)
pycparser (2.14)
pycrypto (2.6.1)
pycurl (7.43.0)
pyflakes (1.3.0)
Pygments (2.1.3)
pylint (1.5.4)
pyOpenSSL (16.0.0)
pyparsing (2.1.4)
pyqtgraph (0.10.0)
pytest (2.9.2)
python-dateutil (2.5.3)
pytz (2016.6.1)
pywin32 (220)
pywin32-ctypes (0.0.1)
PyYAML (3.12)
pyzmq (15.4.0)
QtAwesome (0.3.3)
qtconsole (4.2.1)
QtPy (1.1.2)
radon (1.4.2)
recommonmark (0.4.0)
requests (2.11.1)
rope-py3k (0.9.4.post1)
ruamel-yaml (-VERSION)
scikit-image (0.12.3)
scikit-learn (0.18.1)
scipy (0.18.1)
setuptools (29.0.0)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.10.0)
snowballstemmer (1.2.1)
sockjs-tornado (1.0.3)
sphinx (1.4.6)
spyder (3.0.0)
SQLAlchemy (1.0.13)
statsmodels (0.6.1)
sympy (1.0)
tables (3.2.2)
toolz (0.8.0)
tornado (4.4.1)
traitlets (4.3.0)
transaction (1.6.1)
unicodecsv (0.14.1)
virtualenv (15.0.3)
wcwidth (0.1.7)
Werkzeug (0.11.11)
wheel (0.30.0a0)
widgetsnbextension (1.2.6)
win-unicode-console (0.5)
wincertstore (0.2)
wrapt (1.10.6)
xlrd (1.0.0)
XlsxWriter (0.9.3)
xlwings (0.10.0)
xlwt (1.1.2)
zope.interface (4.3.2)
zope.sqlalchemy (0.7.7)

Thank you!!

**Comment by ales-erjavec** [comment]
> ```Cannot compile extensions. numpy is required to build Orange.```

The problem seems to be that numpy is not importable during the build. This is strange because the preceding steps should have made sure it is installed.
Can you  please run `python -c "import numpy.distutils.core"` immediately before invoking `pip install -e ./`? Does it throw any errors?

**Comment by binggouxsm** [comment]
Thank you very much for your reply. I ran python -c and got this error : 
```
from . import multiarray
ImportError: DLL load failed
```
I searched the internet.This is caused by 32 bit dll run on 64 bit OS. So I reomved numpy and reinstalled an unofficial windows binaries 64-bit version of numpy. The problem is solved. Maybe it is the problem of Anaconda3. 

PS : I'm a beginner to Python. I found it's so hard to build Orange3 on windows. I spent a whole day on fixing "Missing compiler_cxx fix for MSVCCompiler" .  I really hope that there is a manual on how to build and run Orange3 on windows.

**Comment by ajdapretnar** [comment]
> I spent a whole day on fixing "Missing compiler_cxx fix for MSVCCompiler" .

This should not happen with Anaconda. I run it normally with provided [instructions](https://github.com/biolab/orange3/blob/master/README.md#anaconda-installation), except for keyrings issue, which is fixed with:
`pip install keyring keyrings.alt`
after running `conda install orange3`.

The rest works normally for me. 😮

**Comment by binggouxsm** [comment]
Oh, I see why it's so hard . I gave up installing orange3 using Anaconda, because S3 Amazonaws Service is too slow in my country. I can not download Orange3 package.

**Comment by binggouxsm** [comment]
Sorry, me again. This time I built application on my laptop. OS is Win10 64-bit. 

##### Orange version
Orange=3.3.8

##### Expected behavior
Application build successfully

##### Actual behavior
```
(orange3venv) D:\workspace\project\orange\orange3>pip install -e .
Obtaining file:///D:/workspace/project/orange/orange3
Requirement already satisfied: bottleneck>=1.0.0 in d:\anaconda3\lib\site-packages (from Orange3==3.3.8)
Requirement already satisfied: chardet>=2.3.0 in d:\anaconda3\lib\site-packages (from Orange3==3.3.8)
Requirement already satisfied: docutils in d:\anaconda3\lib\site-packages (from Orange3==3.3.8)
Requirement already satisfied: joblib>=0.9.4 in d:\anaconda3\lib\site-packages (from Orange3==3.3.8)
Requirement already satisfied: keyring in d:\anaconda3\lib\site-packages (from Orange3==3.3.8)
Requirement already satisfied: keyrings.alt in d:\anaconda3\lib\site-packages (from Orange3==3.3.8)
Requirement already satisfied: numpy>=1.9.0 in d:\anaconda3\lib\site-packages (from Orange3==3.3.8)
Requirement already satisfied: pyqtgraph>=0.9.10 in d:\anaconda3\lib\site-packages (from Orange3==3.3.8)
Requirement already satisfied: scikit-learn>=0.18 in d:\anaconda3\lib\site-packages (from Orange3==3.3.8)
Requirement already satisfied: scipy>=0.11.0 in d:\anaconda3\lib\site-packages (from Orange3==3.3.8)
Requirement already satisfied: xlrd>=0.9.2 in d:\anaconda3\lib\site-packages (from Orange3==3.3.8)
Requirement already satisfied: pywin32-ctypes; sys_platform == "win32" in d:\anaconda3\lib\site-packages (from keyring->Orange3==3.3.8)
Installing collected packages: Orange3
  Running setup.py develop for Orange3
    Complete output from command d:\workspace\project\orange\orange3venv\scripts\python.exe -c "import setuptools, tokenize;__file__='D:\\workspace\\project\\orange\\orange3\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps:

    running develop
    running build_scripts
    running egg_info
    running build_src
    build_src
    building extension "Orange.classification._simple_tree" sources
    building extension "Orange.data._valuecount" sources
    building extension "Orange.data._contingency" sources
    building extension "Orange.data._io" sources
    building extension "Orange.data._variable" sources
    building extension "Orange.preprocess._discretize" sources
    building extension "Orange.preprocess._relieff" sources
    building extension "Orange.widgets.utils._grid_density" sources
    build_src: building npy-pkg config files
    writing requirements to Orange3.egg-info\requires.txt
    writing top-level names to Orange3.egg-info\top_level.txt
    writing Orange3.egg-info\PKG-INFO
    writing entry points to Orange3.egg-info\entry_points.txt
    writing dependency_links to Orange3.egg-info\dependency_links.txt
    reading manifest file 'Orange3.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.basket' under directory 'Orange\datasets'
    warning: no files found matching '*.css' under directory 'Orange\widgets\_highcharts'
    warning: no files found matching 'COPYING'
    writing manifest file 'Orange3.egg-info\SOURCES.txt'
    running build_ext
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
    customize MSVCCompiler using build_ext
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
    Missing compiler_cxx fix for MSVCCompiler
    customize MSVCCompiler using build_ext
    building 'Orange.classification._simple_tree' extension
    compiling C sources
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Id:\anaconda3\lib\site-packages\numpy\core\include -Id:\anaconda3\include -Id:\anaconda3\include -Id:\anaconda3\include -Id:\anaconda3\include -I"D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" -I"D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" -I"C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" -I"C:\Program Files (x86)\Windows Kits\8.1\include\\shared" -I"C:\Program Files (x86)\Windows Kits\8.1\include\\um" -I"C:\Program Files (x86)\Windows Kits\8.1\include\\winrt" -I"D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include" -I"D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib" -I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt" -I"C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\Include\um" -I"C:\Program Files (x86)\Windows Kits\8.1\Include\shared" -I"C:\Program Files (x86)\Windows Kits\8.1\Include\um" -I"C:\Program Files (x86)\Windows Kits\8.1\Include\winrt" /TcOrange\classification\_simple_tree.c /Fobuild\temp.win-amd64-3.5\Release\Orange\classification\_simple_tree.obj
    Found executable D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:d:\anaconda3\Libs /LIBPATH:d:\workspace\project\orange\orange3venv\libs /LIBPATH:d:\workspace\project\orange\orange3venv\PCbuild\amd64 /LIBPATH:"D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" /LIBPATH:"D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64" /EXPORT:build_tree /EXPORT:destroy_tree /EXPORT:new_node /EXPORT:predict_classification /EXPORT:predict_regression /EXPORT:PyInit__simple_tree build\temp.win-amd64-3.5\Release\Orange\classification\_simple_tree.obj /OUT:Orange\classification\_simple_tree.cp35-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.5\Release\Orange\classification\_simple_tree.cp35-win_amd64.lib
    Found executable D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe
    error: Command "D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:d:\anaconda3\Libs /LIBPATH:d:\workspace\project\orange\orange3venv\libs /LIBPATH:d:\workspace\project\orange\orange3venv\PCbuild\amd64 /LIBPATH:"D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" /LIBPATH:"D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64" /EXPORT:build_tree /EXPORT:destroy_tree /EXPORT:new_node /EXPORT:predict_classification /EXPORT:predict_regression /EXPORT:PyInit__simple_tree build\temp.win-amd64-3.5\Release\Orange\classification\_simple_tree.obj /OUT:Orange\classification\_simple_tree.cp35-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.5\Release\Orange\classification\_simple_tree.cp35-win_amd64.lib" failed with exit status 1120
    _simple_tree.obj : warning LNK4197: export 'PyInit__simple_tree' specified multiple times; using first specification
    _simple_tree.obj : warning LNK4197: export 'new_node' specified multiple times; using first specification
    _simple_tree.obj : warning LNK4197: export 'predict_regression' specified multiple times; using first specification
    _simple_tree.obj : warning LNK4197: export 'predict_classification' specified multiple times; using first specification
    _simple_tree.obj : warning LNK4197: export 'destroy_tree' specified multiple times; using first specification
    _simple_tree.obj : warning LNK4197: export 'build_tree' specified multiple times; using first specification
       Creating library build\temp.win-amd64-3.5\Release\Orange\classification\_simple_tree.cp35-win_amd64.lib and object build\temp.win-amd64-3.5\Release\Orange\classification\_simple_tree.cp35-win_amd64.exp
    _simple_tree.obj : error LNK2001: unresolved external symbol __security_check_cookie
    _simple_tree.obj : error LNK2001: unresolved external symbol __imp_exit
    _simple_tree.obj : error LNK2001: unresolved external symbol __imp__isnan
    _simple_tree.obj : error LNK2001: unresolved external symbol __imp_calloc
    _simple_tree.obj : error LNK2001: unresolved external symbol __imp_srand
    _simple_tree.obj : error LNK2001: unresolved external symbol __imp_rand
    _simple_tree.obj : error LNK2001: unresolved external symbol __imp_qsort
    _simple_tree.obj : error LNK2001: unresolved external symbol __imp_free
    _simple_tree.obj : error LNK2001: unresolved external symbol __imp_malloc
    LINK : error LNK2001: unresolved external symbol _DllMainCRTStartup
    Orange\classification\_simple_tree.cp35-win_amd64.pyd : fatal error LNK1120: 10 unresolved externals

    ----------------------------------------
Command "d:\workspace\project\orange\orange3venv\scripts\python.exe -c "import setuptools, tokenize;__file__='D:\\workspace\\project\\orange\\orange3\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in D:\workspace\project\orange\orange3\
```

#####Steps to reproduce the behavior
install Anaconda 4.2.0 for 64 bit windows based on python 3.5
2.conda install virtualenv
3.install Cygwin
4.virtualenv --python=python3 --system-site-packages orange3venv
5.set PATH , INCLUDE . LIBPATH

SET “PATH=D:\workspace\project\orange\orange3venv\Scripts;D:\Anaconda3;D:\Anaconda3\Scripts;D:\Anaconda3\Library\bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include;C:\cygwin64;C:\cygwin64\bin;C:\cygwin64\lib;%PATH%”

echo %PATH%

SET “INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib;C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt;C:\Program Files (x86)\Windows Kits\8.1\Include\shared;C:\Program Files (x86)\Windows Kits\8.1\Include\um;C:\Program Files (x86)\Windows Kits\8.1\Include\winrt;”

SET “LIBPATH=C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib;C:\Program Files (x86)\Windows Kits\8.1\References\CommonConfiguration\Neutral;”
6.copy lib files from visual studio to virtual env lib directory
 source : C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib
 target : D:\workspace\project\orange\orange3venv\libs

7.download orange source code using git
 git clone https://github.com/biolab/orange3.git
 I choose the stable branch

8.activate orange3venv
 D:\workspace\project\orange\orange3venv\Scripts\activate

9.start to build
 pip install -r requirements-core.txt
 pip install -r requirements-dev.txt
 pip install -r requirements-doc.txt
 pip install -r requirements-gui.txt
 pip install -r requirements-sql.txt
 pip install -e .

**Comment by ajdapretnar** [comment]
For Anaconda, please follow [Anaconda instructions](https://github.com/biolab/orange3#anaconda-installation).

**Comment by binggouxsm** [comment]
Just as I told you before , I can not follow  Anaconda instructions. Because anaconda place their files on S3 Amazonaws Service. The Service is too slow for me. I can not download the orange application

**Comment by ajdapretnar** [comment]
But you state in report you are using Anaconda:

> 1.install Anaconda 4.2.0 for 64 bit windows based on python 3.5

Your Python is from Anaconda, so effectively you are using it....
If you believe Anaconda is causing problems, then uninstall it completely and install regular Python and build from there.

The only difference to instructions is:
python setup.py build_ext --inplace --compiler=msvc install

Mingw32 doesn't work on Windows.

**Comment by ajdapretnar** [comment]
Make sure Visual Studio is in your path in environment variables.
Also, you need to run
`python setup.py build_ext -inplace --compiler=msvc install`
to compile the C sources. Careful, one dash with inplace.
I'd still suggest you to run a standalone .exe installer.

**Comment by ajdapretnar** [comment]
Can we consider this... well... not solved, but what is there to solve for Windows builds anyway? Now we promote straightforward standalone distributions that don't require compiling (or Anaconda).
@kernc What do you think?

**Comment by kernc** [comment]
> Careful, one dash with inplace.

`python setup.py build_ext --help` says it's two. It's normally two for long-options and one for short.

AFAIC if you can't build it, you can't build it. Might look good, though, to export whatever build steps we take on Windos into legible build instructions for anyone caring to build from source.

**Comment by ajdapretnar** [comment]
Instructions are as legible as I can make them. If anyone else wants to give it a go, feel free to go wild.
