### ISSUE TITLE
OWSelectRows: Error it is not possible to use "." as decimal separator and "," produces an error

### ISSUE THREAD

**Issue by lopezco** [biolab/orange3#1782]
## Context
__Exception:__ ```ValueError: could not convert string to float: '0,6'```
__Module:__ ```Orange.widgets.data.owselectrows:392```
__Widget Name:__ ```Select Rows```
__Widget Module:__ ```Orange.widgets.data.owselectrows:362```
__Version:__ ```3.3.9.dev0+f3f5ca0```
__Environment:__ ```Python 3.5.2 on Linux 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64```
__Local Variables:__ ```OrderedDict([('.0', <tuple_iterator object at 0x7f285621ab70>), ('v', '0,6')])```

### Expected behavior

To work with '.' decimal separator

### Actual behavior

An exception is risen

```python
Traceback (most recent call last):
  File "/home/workspace/git/orange3/Orange/widgets/data/owselectrows.py", line 362, in conditions_changed
    self.commit()
  File "/home/workspace/git/orange3/Orange/widgets/gui.py", line 1972, in unconditional_commit
    do_commit()
  File "/home/workspace/git/orange3/Orange/widgets/gui.py", line 1980, in do_commit
    commit()
  File "/home/workspace/git/orange3/Orange/widgets/data/owselectrows.py", line 392, in commit
    attr_index, oper, *[float(v) for v in values])
  File "/home/workspace/git/orange3/Orange/widgets/data/owselectrows.py", line 392, in <listcomp>
    attr_index, oper, *[float(v) for v in values])
ValueError: could not convert string to float: '0,5'
```

### Steps to reproduce the behavior

1 - Load a dataset with continuous variables
2 - Use a select columns to subset the dataset with decimal values
3 - Try to use '.' as separator = wont work
4 - Try to use ',' as separate = error

### Possible Solution
We can change the numeric validator with a QRegExpValidator

```python
        def add_numeric(contents):
            le = add_textual(contents)
            le.setValidator(QRegExpValidator(QRegExp("[-]{0,1}\d{1,}[\.]{0,1}\d{0,}e{0,1}[-]{0,1}\d{1,}[\.]{0,1}\d{0,}")))
            return le
```

**Comment by ajdapretnar** [comment]
Dot works for me normally.
Comma indeed produces an error and it should not.

**Comment by lopezco** [comment]
I think it has to do with my machine locale (FR).
