### ISSUE TITLE
Scatter Plot

### ISSUE THREAD

**Issue by adelsing** [biolab/orange3#1788]
##### Orange version
 3.3.8

##### Expected behavior
The ability to pull a scatter plot in while following the training on Youtube.

##### Actual behavior
![image](https://cloud.githubusercontent.com/assets/21203069/20770287/6f2b9114-b702-11e6-9e77-24fa8eae8ba1.png)

##### Steps to reproduce the behavior
1) Pulled in file widget
2) Verified it opens iris.tab
3) Added Data Table
4) Verified Data showed up in Data Table
5) Pulled in Scatter Plot and received error: 
![image](https://cloud.githubusercontent.com/assets/21203069/20770359/b09f83e4-b702-11e6-809d-5d63ef4abc22.png)

##### Additional info (worksheets, data, screenshots, ...)

When I attempted to attach directly from file and received a load of errors obviously when attempting to pull in different widgets.

**Comment by ajdapretnar** [comment]
Please update to the latest version and try again.

**Comment by ajdapretnar** [comment]
Is this working with the latest version?

**Comment by ajdapretnar** [comment]
@adelsing Any progress on the issue?

**Comment by adelsing** [comment]
I got it to work with anaconda, thanks
