### ISSUE TITLE
[REQUEST] PFA/PMML import/export support

### ISSUE THREAD

**Issue by lopezco** [biolab/orange3#1789]
> The Predictive Model Markup Language (PMML) is an XML-based predictive model interchange format conceived by Dr. Robert Lee Grossman, then the director of the National Center for Data Mining at the University of Illinois at Chicago. PMML provides a way for analytic applications to describe and exchange predictive models produced by data mining and machine learning algorithms. 
[Wikipedia -  Predictive Model Markup Language](https://en.wikipedia.org/wiki/Predictive_Model_Markup_Language)

- More information [here](http://dmg.org/pmml/v4-3/GeneralStructure.html)
- [Industry players / open source projects that support PMML](http://www.dmg.org/products.html)

I think it would be a great idea to handle persistence / loading of models across platforms like R/Rattle, scikit-learn, weka, and others.

As most of Orange models come from scikit-learn, we can use the [SkLearn2PMML](https://github.com/jpmml/sklearn2pmml) library coupled with [JPMML-SkLearn](https://github.com/jpmml/jpmml-sklearn) as sugested on [this issue](https://github.com/scikit-learn/scikit-learn/issues/1596) and on [Scikit-Learn's Related Projects](https://github.com/scikit-learn/scikit-learn/blob/master/doc/related_projects.rst) under **Interoperability and framework enhancements**

# **Update:**

Since PFA is like the evolution of PMML, it may be easier to implement.

![image](https://cloud.githubusercontent.com/assets/6637618/23696810/90f8708e-03e5-11e7-910d-07fc75acf076.png)

> New functionality has been added to PMML over the past 17 years, but it is still based on tables of model parameters. Even a modest extension of a scoring engine requires a new version of PMML to be adopted, which can take years.
> 
> PFA serves this purpose with far more generality. (...) The author of a PFA document can construct new types of models from building blocks without waiting for the new model to be explicitly added to the specification.
> 
> PFA is more flexible than PMML, but safer than custom code (...)
> 

- More information [here](http://dmg.org/pfa/docs/motivation/)

**Comment by janezd** [comment]
I don't see a good way to implement this in Orange. Even if Orange used only sklearn models (it doesn't, and we try to get rid of as many as we can since they are not really suitable for us), Orange wraps it and adds additional info that may not be present in PMML. And this was "even if"...

**Comment by animator** [comment]
@lopezco @janezd 
Please have a look at the orange3-scoring addon created to import PFA and PMML models and use them in orange.
https://github.com/animator/orange3-scoring
