### ISSUE TITLE
[REQUEST] Widget(s) for Regression Diagnostics

### ISSUE THREAD

**Issue by lopezco** [biolab/orange3#1802]
It would be nice to have a widget, or a set of them, to asses regression performance the way it's possible with classification models.

Here some examples pulled from R :
http://www.statmethods.net/stats/rdiagnostics.html
http://data.library.virginia.edu/diagnostic-plots/

**Comment by janezd** [comment]
I checked these examples. How many - if any - are applicable to regression models in general and not just to linear regression? They are mostly about checking for linearity and normality of residuals, which does not make much sense in, say, kNN regression, I suppose. I'd hesitate to add a set of widgets for a single method, which, while being important and the basis for many others, is neither the only one not the state-of-the-art one.

**Comment by lopezco** [comment]
@janezd 
You're right, at the time I was mostly interested on linear regression.

**Comment by janezd** [comment]
I'm closing this then. Still, thanks for suggestion and we'll keep eyes open for something more general.
