### ISSUE TITLE
Not showing widgets

### ISSUE THREAD

**Issue by sumanksaha** [biolab/orange3#1815]
##### Orange version
 3.3.8 (python 3.4) (git revision ba271)

##### Expected behavior
 Showing all the widgets

##### Actual behavior
 Various widgets are not showing (Claasify,  regression and evaluation)
![2016-12-10](https://cloud.githubusercontent.com/assets/17468128/21071636/b7341b80-becc-11e6-8cf7-4a9a4d9a91fa.png)

##### Steps to reproduce the behavior
 It occurs when  i start the application

##### Additional info (worksheets, data, screenshots, ...)
Screenshot has been added.
It first happened when i updated from3 3.7 to 3.38. Uninstalling and reinstalling doesnot help. Previous to this, I had used orange for 18 months

**Comment by ajdapretnar** [comment]
Could you please check with the latest version? Thanks!

**Comment by sumanksaha** [comment]
After 3 months and 5 times reinstallation, orange 3.3.8 works perfectly again. I have updated it to 3.3.10. All widgets are functioning.
