### ISSUE TITLE
Classification Tree Example broken in 3.3.9

### ISSUE THREAD

**Issue by michelemostarda** [biolab/orange3#1820]
##### Orange version

Orange 3.3.9

##### Expected behavior

The Classification Tree Example loads correctly.

##### Actual behavior

The Classification Tree Example misses a widget and relative connections.

It shows the popup Error occurred while loading the workflow.
UnknownWidgetDefinition('Orange.widgets.classify.owclassificationtreegraph.OWClassificationTreeGraph',)

##### Steps to reproduce the behavior

Help > Examples > choose Classification Tree

##### Additional info (worksheets, data, screenshots, ...)

It shows the popup Error occurred while loading the workflow.
UnknownWidgetDefinition('Orange.widgets.classify.owclassificationtreegraph.OWClassificationTreeGraph',)

**Comment by ajdapretnar** [comment]
Fixed in #1804.

**Comment by ajdapretnar** [comment]
Thank you for reporting the issue, we appreciate it. 😃
