### ISSUE TITLE
data attributes don't change

### ISSUE THREAD

**Issue by amandasaksida** [biolab/orange3#1821]
Orange version 3.3.9 on OS X Yosemite (10.10.5)

Expected behavior: data attributes can be changed sing the dropdown menu in the file widgets, and all the functions and analyses should take the changes into account once applied.

Actual behavior: when i change the attributes from nominal to target in the file widgets (in the case below for the variables fam, WO) and apply the change, the analysis tools keep sending the error message saying my data has no target variables.

Additional info: the dataset i'm using is attached below
[alldata.xlsx](https://github.com/biolab/orange3/files/651575/alldata.xlsx)

**Comment by ajdapretnar** [comment]
Could you please attach a screenshot of the workflow as well?

**Comment by amandasaksida** [comment]
Here:

**Comment by ajdapretnar** [comment]
Image didn't get through. You can just select it from your computer using the blue highlighted link just below the message window.

**Comment by amandasaksida** [comment]
ok, trying again: 
![screen shot 2016-12-14 at 13 59 01](https://cloud.githubusercontent.com/assets/2984161/21205811/870a3440-c25e-11e6-89cb-b1138fa0d1c1.png)

**Comment by markotoplak** [comment]
Most learners can only work with a single target variable. Try selecting just one column as target.

Orange's error message seems wrong here.

**Comment by ajdapretnar** [comment]
Marko is right, Orange cannot work with multitarget predictions (yet), so there can only be one gray column. However, the error message needs to be fixed. Opening a new issue for it.

Here's how the workflow should look like:

![all-data](https://cloud.githubusercontent.com/assets/12524972/21215480/d39beb1c-c2a1-11e6-89a4-a341dae2bd5e.PNG)

**Comment by amandasaksida** [comment]
Thanks, haven't thought of it.

**Comment by ajdapretnar** [comment]
Continued in #1823.

Thanks for the report! :)
