### ISSUE TITLE
Orange does not start

### ISSUE THREAD

**Issue by CornelisRemmert** [biolab/orange3#1829]
##### Orange version
3.3
##### Expected behavior
Start of Orange

##### Actual behavior
Orange does not start

##### Steps to reproduce the behavior
On a new Orange3 environment in Anaconda, I Installed Orange3:
conda config --add channels conda-forge
conda install orange3

after installation I start:
orange-canvas

##### Additional info (worksheets, data, screenshots, ...)
then this happens:

![afbeelding](https://cloud.githubusercontent.com/assets/20670746/21272834/1b2df48c-c3c1-11e6-9b22-e3c7ac5e7d34.png)

**Comment by CornelisRemmert** [comment]
Having downgraded in Anaconda Navigator to 3.3.8, Orange starts again, though adding Text Mining is not a working option anymore.

**Comment by kernc** [comment]
In the upgraded version, you could try installing PyQt5: `pip install pyqt5`

**Comment by CornelisRemmert** [comment]
So I did and Orange starts again, but not without problems

![afbeelding](https://cloud.githubusercontent.com/assets/20670746/21288780/0ccf66de-c48c-11e6-9ec9-00345780681a.png)

**Comment by astaric** [comment]
Conda-forge release of Orange 3.3.9 should work with pyqt4 (which has been installed, as can be seen from the first log). If you installed pyqt5, you should uninstall it.

The probable cause of problem is that the environment defines a variable named QT_API with value pyqt5, forcing AnyQt to import PQt5. If it does, please unset the variable or set it to pyqt4 before running orange-canvas.

**Comment by CornelisRemmert** [comment]
Thanks astaric,

Could it be this document where I should unset or reset:
C:\Users\datazin\Anaconda3\envs\Orange3\Lib\site-packages\AnyQt\QtGui.py

![afbeelding](https://cloud.githubusercontent.com/assets/20670746/21294962/4851aab4-c54a-11e6-848f-482f4164adc6.png)

have you suggestions how to best alter these lines?

**Comment by kernc** [comment]
You should [set `QT_API=pyqt4`](https://superuser.com/questions/79612/setting-and-getting-windows-environment-variables-from-the-command-prompt) before running `orange-canvas`.

**Comment by CornelisRemmert** [comment]
in the prompt?

**Comment by kernc** [comment]
Yes, I think that might work.

**Comment by CornelisRemmert** [comment]
I'm afraid it did not work

![afbeelding](https://cloud.githubusercontent.com/assets/20670746/21296154/029c8596-c565-11e6-9a32-8a5ce1aa5f72.png)

**Comment by astaric** [comment]
Is the pyqt5 package still installed? Can you run pip freeze and paste the output?

**Comment by CornelisRemmert** [comment]
I removed the environment, created a new one and installed orange3 on it 

![afbeelding](https://cloud.githubusercontent.com/assets/20670746/21296251/c85a4776-c567-11e6-87cd-e03751456e7c.png)

**Comment by nikicc** [comment]
> Having downgraded in Anaconda Navigator to 3.3.8, Orange starts again, though adding Text Mining is not a working option anymore.

@CornelisRemmert I assume you had the latest version of Text, i.e. 0.2.2. If so, than it's expected that it stopped working after the downgrade to 3.3.8 since Text 0.2.2 requires Orange 3.3.9. If you decide to stick to Orange 3.3.8 then you should also downgrade Text to 0.2.1.

**Comment by astaric** [comment]
Hmm, pip freeze does not list PyQt4. could you run conda list and paste the output of that?

You can also try reinstalling pyqt4 (with conda) and check if `python -c "import PyQt4.QtCore"` does not return an error.

btw, which version of windows are you running + is it 32 or 64bit? (So I can try to reproduce your issue in a virtual machine)

**Comment by CornelisRemmert** [comment]
@astaric do you mean `conda uninstall pyqt4` and then `conda install pyqt4`?

There is no error for `python -c "import PyQt4.QtCore"`

I run Windows10 64bit.

`conda list` returns:

![afbeelding](https://cloud.githubusercontent.com/assets/20670746/21325436/abee7098-c626-11e6-8319-600d55520bb0.png)

**Comment by CornelisRemmert** [comment]
@nikicc how can I downgrade Text? Orange is easy in te navigator, but Text I do not know. Can I install specific versions using the version number in the command somehow?

**Comment by nikicc** [comment]
@CornelisRemmert I would uninstall the current version through pip by running `pip uninstall Orange3-Text` and then install the desired version with `pip install Orange3-Text==0.2.1`.

**Comment by astaric** [comment]
If there is no error for python -c "import PyQt4.QtCore",
can you try running Orange using `python -m Orange.canvas`?

**Comment by CornelisRemmert** [comment]
I tried, but  the behaviour did not change

**Comment by CornelisRemmert** [comment]
I have replicated (as I always do) the procedure on another workstation (also windows10) and I have to say `set QT_API=pyqt4` does have the desired effect there. But without this code it will not run either.

**Comment by CornelisRemmert** [comment]
I reinstalled Anaconda and now `set QT_API=pyqt4` does help.
Unfortunately some new errors are also introduced, but if necessary I will open a new issue for it.

**Comment by CornelisRemmert** [comment]
by the way, I like to mention it also depends on which prompt I use:

**cmd:**

Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. Alle rechten voorbehouden.

C:\Users\datazin>activate orange3

(orange3) C:\Users\datazin>orange-canvas
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\gensim\utils.py:855: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")

**via anaconda navigator**


(C:\Users\datazin\Anaconda3\envs\orange3) C:\Users\datazin>orange-canvas
Traceback (most recent call last):
  File "C:\Users\datazin\Anaconda3\envs\orange3\Scripts\orange-canvas-script.py", line 3, in <module>
    import Orange.canvas.__main__
  File "C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\__main__.py", line 20, in <module>
    from AnyQt.QtGui import QFont, QColor, QDesktopServices
  File "C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\AnyQt\QtGui.py", line 138, in <module>
    from PyQt5.QtGui import *
ImportError: No module named 'PyQt5'

(C:\Users\datazin\Anaconda3\envs\orange3) C:\Users\datazin>set qt_api=pyqt4

(C:\Users\datazin\Anaconda3\envs\orange3) C:\Users\datazin>orange-canvas
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\gensim\utils.py:855: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
