### ISSUE TITLE
Missing or tiny images on report

### ISSUE THREAD

**Issue by JohnTarr** [biolab/orange3#1834]
##### Orange version
3.3.8

##### Expected behavior
When clicking report, software should add image, as displayed, to the report list.

##### Actual behavior
Am seeing the "missing image" icon in the report list, or in some cases, the graph shows up, but is surrounded by excess white space, causing it to appear tiny.

##### Steps to reproduce the behavior
I started with a file import of a CSV, sent that into a row selector, and then into a distribution visualization. Double clicked the visualization, and then clicked the "Report" button. Saw the behavior mentioned above, and attempted printing to confirm it wasn't just an issue with the report viewer. Saw same behavior on printout. Note that I printed to PDF using Cute PDF Writer.

**Comment by kernc** [comment]
Addendum to reproduction steps: Before clicking Report, make the window as small as possible.

**Comment by JohnTarr** [comment]
@kernc  - Issue occurs without changing window size.

**Comment by JohnTarr** [comment]
Strange. I created a new project before creating this issue, and it happened even in a new project. Now, I can't get it to re-create either. Sorry for the trouble. I'll close this issue.
