### ISSUE TITLE
pip installation bug on Linux

### ISSUE THREAD

**Issue by gabriel-fallen** [biolab/orange3#1838]
PIP tries to install binary version (Orange3-3.3.9-cp35-none-any.whl) which lacks C extensions.
This leads to error
```
ImportError: cannot import name '_variable'
```

Correct command to install Orange 3 is
```
pip3 install --no-binary orange3 orange3
```

I suggest to put it into installation instructions on GitHub Readme or on the webpage.

##### Orange version
3.3.9 (on Linux 4.4.0-57-generic #78-Ubuntu, pip 9.0.1, python 3.5)

##### Expected behavior
`orange-canvas` launches Orange

##### Actual behavior
```
ImportError: cannot import name '_variable'
```

##### Steps to reproduce the behavior
```
pip3 install orange3
orange-canvas
```

**Comment by markotoplak** [comment]
@gabriel-fallen, was there perhaps a problem with pip caches as in #1942?

**Comment by gabriel-fallen** [comment]
@markotoplak I don't think it's a problem with PIP caches. I was performing first in my life installation of Orange. :) PIP was constantly downloading the wrong .whl file until I requested building from source.

**Comment by markotoplak** [comment]
Do you still have the problems with the newer versions? 

I have no idea where did pip find your file as it is not listed on https://pypi.python.org/pypi/Orange3/3.3.9

**Comment by gabriel-fallen** [comment]
Just uninstalled Orange 3.3.9 and `pip3 install orange3` installed Orange 3.3.12.
This time PIP downloaded source tarball and recompiled Orange. But I don't know whether PIP caches `--no-binary` setting for a package.

**Comment by robertour** [comment]
I was getting the same error as @gabriel-fallen, I what he suggested

    pip3 install --no-binary orange3 orange3

Then I got another error:

     ImportError: PyQt4, PyQt5 or PySide are not available for import

So I run `pip3 install PyQt5`, and now my orange3 is working.

**Comment by arun-shaji** [comment]
I am getting the same error as pointed out here.
`ImportError: PyQt4, PyQt5 or PySide are not available for import`
I have tried `pip3 install PyQt5` as @robertour pointed. Then I got an error
`Could not find a version that satisfies the requirement sip>=4.19.1 (from PyQt5) (from versions: )
No matching distribution found for sip>=4.19.1 (from PyQt5)`
I am working on Ubuntu 14.04, python 3.4 inside virtualenv

**Comment by astaric** [comment]
There are currently no .whl packages for Linux on PyPi. If something goes wrong, `--no-binary` flag solves the problem, so I am closing the issue.

For new installations on linux, we prefer miniconda (installation guide is on our [web site](https://orange.biolab.si/download/linux/)), as it make installation of dependencies much easier.
