### ISSUE TITLE
Broken link to SQL Table widget documentation

### ISSUE THREAD

**Issue by ysmartin** [biolab/orange3#1853]
##### Orange version

3.3.9

##### Expected behavior
The help page for the SQL Table widget is shown.

##### Actual behavior
A 404 error page appears.

##### Steps to reproduce the behavior
Add an instance of SQL Table widget and open help (right click -> help or F1).

##### Additional info (worksheets, data, screenshots, ...)
The link from http://orange.biolab.si/toolbox/ was also broken a few hours ago, but it seems to be working now, so I guess the same fix should be applied.

**Comment by kernc** [comment]
Thanks. Seems to already be fixed on master branch.
