### ISSUE TITLE
Warn when predicting with failed domain conversion

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#1868]
##### Expected behavior

When predicting data that can not be converted into model's domain warn the user (widgets Test & Score and Predicitons). 

Test & Score with Titanic data should produce a warning, if only first two columns are used for Train data and only the last is used for Test data. 

Currently, Test & Score does show an error if class variable is not the same. Test if this also works for class variables constructed with compute_value - it should.

Predictions widget should also warn in case of incompatible domains.

**Comment by janezd** [comment]
@markotoplak, done, right?

**Comment by markotoplak** [comment]
Fixed in #3323
