### ISSUE TITLE
No Icons on macOS Sierra

### ISSUE THREAD

**Issue by luketilley** [biolab/orange3#1894]
##### Behavior
When the application loads there are no icons visible throughout the application.

The terminal is spitting out the following error quite frequently:
QPixmap::scaled: Pixmap is a null pixmap

This happens every time I launch the application

##### Other Info
I'm using the latest version of anaconda as my python distribution and I tried to install the orange3 package as specified on the github page.

**Comment by astaric** [comment]
Try running orange using

python -m Orange.canvas

**Comment by luketilley** [comment]
Thank you, that worked

-Luke

**Comment by astaric** [comment]
I am closing this issue as there is nothing (reasonable) we can do about it. The issue has been reported upstream (https://github.com/ContinuumIO/anaconda-issues/issues/974), but as pyqt4 is no longer supported, I guess this will not be fixed.

The problem will hopefully go away once we start using pyqt5 by default. Most of out osx users luckily use the .dmg bundle from website, which works.
