### ISSUE TITLE
It is no longer possible to add comments in reports

### ISSUE THREAD

**Issue by lopezco** [biolab/orange3#1899]
##### Orange version
3.3.10.dev0+917b3cb

##### Expected behavior
User can add comments in reports

##### Actual behavior
It is no longer possible to add comments in reports

##### Steps to reproduce the behavior
1. Open Orange
2. Add a widget
3. Click Report

**Comment by ajdapretnar** [comment]
I'd add that report for File also fails to report properly on the file name and format. I've tried housing.tab and titanic.tab and got unknown in both cases.

**Comment by lopezco** [comment]
I've tried to add a comment after the update but couldn't do it because the textbox doesn't appear.

**Version:** 3.4.dev0+5373929

**Comment by kernc** [comment]
Closed incorrectly via commit log, sorry.
