### ISSUE TITLE
errors and warnings using Orange 3.3.9

### ISSUE THREAD

**Issue by CornelisRemmert** [biolab/orange3#1910]
##### Orange version

3.3.9

##### Expected behavior

to open an existing workflow without errors/warnings

##### Actual behavior

when I open a workflow with classyfying tasks I get several errors and warnings. 
The flow is made using 3.3.8 where I did not experience these errors. 

##### Steps to reproduce the behavior
Windows10, installation with Anaconda in a separate environment. 
set QT_API=pyqt4
orange-canvas
open the flow

##### Additional info (worksheets, data, screenshots, ...)
the flow:

![afbeelding](https://cloud.githubusercontent.com/assets/20670746/21884043/0b3adae4-d8b2-11e6-987a-c95d360200d1.png)

the prompt:

![afbeelding](https://cloud.githubusercontent.com/assets/20670746/21884069/23abdede-d8b2-11e6-8d05-c0cb294a21fe.png)

**Comment by ajdapretnar** [comment]
Personally, I cannot see what your prompt output was. The image is too small....

**Comment by CornelisRemmert** [comment]
Sorry, I should have copied the content, here it is including starting Orange, opening the workflow and playing around a bit (the first part concerns the pyqt4 setting):

(C:\Users\datazin\Anaconda3) C:\Users\datazin>activate orange3

(orange3) C:\Users\datazin>orange-canvas
Traceback (most recent call last):
  File "C:\Users\datazin\Anaconda3\envs\orange3\Scripts\orange-canvas-script.py", line 3, in <module>
    import Orange.canvas.__main__
  File "C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\__main__.py", line 20, in <module>
    from AnyQt.QtGui import QFont, QColor, QDesktopServices
  File "C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\AnyQt\QtGui.py", line 138, in <module>
    from PyQt5.QtGui import *
ImportError: No module named 'PyQt5'

(orange3) C:\Users\datazin>set QT_API=pyqt4

(orange3) C:\Users\datazin>orange-canvas
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\gensim\utils.py:855: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\Orange\widgets\settings.py:374: UserWarning: Could not read defaults for widget <class 'Orange.widgets.data.owrank.OWRank'>
The following error occurred:

super(): empty __class__ cell
  .format(self.widget_class, ex))
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\Orange\widgets\settings.py:374: UserWarning: Could not read defaults for widget <class 'Orange.widgets.evaluate.owconfusionmatrix.OWConfusionMatrix'>
The following error occurred:

super(): empty __class__ cell
  .format(self.widget_class, ex))
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\Orange\widgets\settings.py:374: UserWarning: Could not read defaults for widget <class 'Orange.widgets.visualize.owsieve.OWSieveDiagram'>
The following error occurred:

'attrX'
  .format(self.widget_class, ex))
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\Orange\evaluation\testing.py:350: OrangeWarning: Working with small-enough data; single-threaded sequential excecution will (probably) be faster. Setting n_jobs=1
  "Setting n_jobs=1", OrangeWarning)
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\sklearn\metrics\classification.py:1113: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\sklearn\metrics\classification.py:1113: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\Orange\widgets\evaluate\owcalibrationplot.py:200: RuntimeWarning: divide by zero encountered in double_scalars
  gamma = 1. / (2 * sigma ** 2)
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\Orange\widgets\evaluate\owcalibrationplot.py:201: RuntimeWarning: divide by zero encountered in double_scalars
  a = 1. / (sigma * numpy.sqrt(2 * numpy.pi))
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\Orange\widgets\evaluate\owcalibrationplot.py:207: RuntimeWarning: invalid value encountered in multiply
  W = a * numpy.exp(-gamma * ((xs - x) ** 2))
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\numpy\lib\nanfunctions.py:236: RuntimeWarning: All-NaN axis encountered
  warnings.warn("All-NaN axis encountered", RuntimeWarning)
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\numpy\lib\nanfunctions.py:343: RuntimeWarning: All-NaN slice encountered
  warnings.warn("All-NaN slice encountered", RuntimeWarning)
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\pyqtgraph\functions.py:1314: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if connect == 'finite':
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\pyqtgraph\functions.py:1317: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if connect == 'all':
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\pyqtgraph\graphicsItems\ScatterPlotItem.py:717: RuntimeWarning: invalid value encountered in greater
  (pts[1] + w > viewBounds.top()) &
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\pyqtgraph\graphicsItems\ScatterPlotItem.py:717: RuntimeWarning: invalid value encountered in less
  (pts[1] + w > viewBounds.top()) &
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\pyqtgraph\graphicsItems\ScatterPlotItem.py:718: RuntimeWarning: invalid value encountered in less
  (pts[1] - w < viewBounds.bottom())) ## remove out of view points
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\Orange\evaluation\testing.py:350: OrangeWarning: Working with small-enough data; single-threaded sequential excecution will (probably) be faster. Setting n_jobs=1
  "Setting n_jobs=1", OrangeWarning)
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\sklearn\metrics\classification.py:1113: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\sklearn\metrics\classification.py:1113: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\Orange\widgets\evaluate\owcalibrationplot.py:200: RuntimeWarning: divide by zero encountered in double_scalars
  gamma = 1. / (2 * sigma ** 2)
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\Orange\widgets\evaluate\owcalibrationplot.py:201: RuntimeWarning: divide by zero encountered in double_scalars
  a = 1. / (sigma * numpy.sqrt(2 * numpy.pi))
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\Orange\widgets\evaluate\owcalibrationplot.py:207: RuntimeWarning: invalid value encountered in multiply
  W = a * numpy.exp(-gamma * ((xs - x) ** 2))
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\numpy\lib\nanfunctions.py:236: RuntimeWarning: All-NaN axis encountered
  warnings.warn("All-NaN axis encountered", RuntimeWarning)
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\numpy\lib\nanfunctions.py:343: RuntimeWarning: All-NaN slice encountered
  warnings.warn("All-NaN slice encountered", RuntimeWarning)
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\Orange\evaluation\testing.py:350: OrangeWarning: Working with small-enough data; single-threaded sequential excecution will (probably) be faster. Setting n_jobs=1
  "Setting n_jobs=1", OrangeWarning)
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\sklearn\metrics\classification.py:1113: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\sklearn\metrics\classification.py:1113: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\pyqtgraph\functions.py:1314: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if connect == 'finite':
C:\Users\datazin\Anaconda3\envs\orange3\lib\site-packages\pyqtgraph\functions.py:1317: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if connect == 'all':
