### ISSUE TITLE
Test&Score: Some results are not shown completly

### ISSUE THREAD

**Issue by lanzagar** [biolab/orange3#1917]
##### Orange version

3.3.10

##### Expected behavior
I can see the reported numbers in Test&Score.
Or resize columns if numbers too big and not visible right away.

##### Actual behavior
I can't see the reported numbers in Test&Score.
Sorting results using a column with a problematic number does update the table and show the number correctly.

##### Steps to reproduce the behavior
Housing data and Mean learner should show the problem.

##### Additional info (worksheets, data, screenshots, ...)
![score](https://cloud.githubusercontent.com/assets/4579717/21927096/f6b87918-d984-11e6-9b64-996032d65c28.png)

**Comment by astaric** [comment]
For me, the issue resolves itself if I resize the widget a bit

**Comment by ajdapretnar** [comment]
I can't reproduce this on OSX. Does the issue still persist?
