### ISSUE TITLE
Discretizers only work on columns

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#192]
This test fails, but should work. This code is also included in the documentation for Instance.

class TestInstanceConversion(TestCase):
    def test_single_instance(self):
        from Orange.data import Table, discretization, Instance
        iris = Table("iris")
        inst = Instance(iris.domain, [5.2, 3.8, 1.4, 0.5, "Iris-virginica"])
        d_iris = discretization.DiscretizeTable(iris)
        Instance(d_iris.domain, inst)

**Comment by thocevar** [comment]
This works just fine, I guess.

```python
class TestInstanceConversion(TestCase):
    def test_single_instance(self):
        from Orange.data import Table, Instance
        from Orange.preprocess import Discretize
        iris = Table("iris")
        inst = Instance(iris.domain, [5.2, 3.8, 1.4, 0.5, "Iris-virginica"])
        d_iris = Discretize(iris)
        Instance(d_iris.domain, inst)
```
