### ISSUE TITLE
Update of connected widgets are inconsistent when data is modified in Paint Data widget

### ISSUE THREAD

**Issue by larvian** [biolab/orange3#1926]
##### Orange version

'3.3.6'
Github ee294bc

##### Expected behavior
Changes made to data in the Paint Data widget should be updated when the send button is pressed or automatically if the check box next to the button is ticked (Send Automatically).

##### Actual behavior
Changes to data in the Paint Data widget by certain actions does not result in expected update happening to connected widgets.
E.g when modifying data by using the Jitter tool and pressing send (auto send not checked) there is no update happening in a connected Scatter Plot widget, but in in connected Heat Map, Distribution or Paint Data widgets update happens after the same change in the Paint Data widget.
For the Heat Map and Distributions widgets only Selecting data followed by deleting the selected data does not get updated as expected. For the Scatter plot widget there are several change actions in the Paint data tool that don't result in the expected update happening.

These tables shows if expected change actions in the Paint data tool happens or not.

**Scatter Plot widget**
```
                 Send         Auto send
Brush            YES           YES
Put              YES           YES
Jitter/Magnet    NO            NO
Select->drag     NO            NO
Select->delete   YES           NO
Clear            YES           YES
```

**Heat map/Distributions/Data Paint widgets**
```
                 Send         Auto send
Brush            YES           YES
Put              YES           YES
Jitter/Magnet    YES           YES
Select->drag     YES           YES
Select->delete   YES           NO
Clear            YES*          YES*
```
\* When data is cleared by pressing the Clear button, then there is a python exception displayed in the ouput window that pops up. This happens for Heat Map and Distributions widgets but not for connected Paint tool widget.
```
--------------------------------------------------------------------------------
ValueError                                    Traceback (most recent call last):
  File "C:\Continuum\Anaconda3\lib\site-packages\Orange\canvas\scheme\widgetsscheme.py", line 724, in process_signals_for_widget
    handler(*args)
  File "C:\Continuum\Anaconda3\lib\site-packages\Orange\widgets\visualize\owheatmap.py", line 703, in set_dataset
    self.update_heatmaps()
  File "C:\Continuum\Anaconda3\lib\site-packages\Orange\widgets\visualize\owheatmap.py", line 710, in update_heatmaps
    self.construct_heatmaps(self.data)
  File "C:\Continuum\Anaconda3\lib\site-packages\Orange\widgets\visualize\owheatmap.py", line 864, in construct_heatmaps
    parts = self._make_parts(effective_data, group_var, group_label)
  File "C:\Continuum\Anaconda3\lib\site-packages\Orange\widgets\visualize\owheatmap.py", line 754, in _make_parts
    minv, maxv = np.nanmin(data.X), np.nanmax(data.X)
  File "C:\Continuum\Anaconda3\lib\site-packages\numpy\lib\nanfunctions.py", line 225, in nanmin
    res = np.fmin.reduce(a, axis=axis, out=out, keepdims=keepdims)
ValueError: zero-size array to reduction operation fmin which has no identity
--------------------------------------------------------------------------------
```

Other widget types have not been checked and may have similar issues. 

##### Steps to reproduce the behavior
Connect Paint Data widget output to the inputs of Scatter Plot, Heat map, Distributions and Paint Data widgets like this...
![bild](https://cloud.githubusercontent.com/assets/260246/21958622/a0901a08-dab2-11e6-8e37-0431590fdbce.png)

Enter data and do modifications to the data in the Paint Data widget (the leftmost one) using different tools. Observe if the data modifications results in update of the connected widget.

**Comment by ajdapretnar** [comment]
As of 3.3.10, only Scatter Plot fails to update. Namely for:
- jitter
- magnet
- select & move

Heat Map error is fix and the rest works fine.

**Comment by ales-erjavec** [comment]
This seems serious. It would indicate that Paint Data modifies the data inplace for the jitter/magnet/move tools.

**Comment by ajdapretnar** [comment]
Well, it does output the changes in Data Table, so I guess the issue is not with Paint Data.....

**Comment by ales-erjavec** [comment]
> Well, it does output the changes in Data Table, so I guess the issue is not with Paint Data.....

No. The problem is definitely in Paint Data, Scatter Plot just has a specific logic/optimization that makes this manifest more clearly.

**Comment by ajdapretnar** [comment]
Oh, ok. 😃 It's good someone spotted it then!
