### ISSUE TITLE
Linear Projection - segfault

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#1927]
##### Orange version
3.3.10-dev

##### Expected behavior
Select and move all the features to Display Features.

##### Actual behavior
Segfault on selecting and dragging the features from the menu.

##### Steps to reproduce the behavior
File - Preprocess (normalize features) - LinProj
Select all features available and plot them.

##### Additional info (worksheets, data, screenshots, ...)
[WA_Fn-UseC_-HR-Employee-Attrition.xlsx](https://github.com/biolab/orange3/files/708558/WA_Fn-UseC_-HR-Employee-Attrition.xlsx)
Dataset for testing.

**Comment by ales-erjavec** [comment]
Probably [QTBUG-22569](https://bugreports.qt.io/browse/QTBUG-22569).
Can you please also post the OS and PyQt version.

**Comment by ajdapretnar** [comment]
OS Sierra, PyQt4.

**Comment by ajdapretnar** [comment]
Tested this with PyQt5 and it works. Since Qt says they will likely not fix this for Qt4, I'm tagging it as wontfix and closing it.
