### ISSUE TITLE
Scatter Plot's show density does not work with pyqtgraph 0.10

### ISSUE THREAD

**Issue by astaric** [biolab/orange3#1948]
Update pyqtgraph to the latest version, then connect iris to scatter plot and select "Show class density". The background changes to gray, while it should change to a colored map of class densities. 

<img width="536" alt="screen shot 2017-01-24 at 17 17 49" src="https://cloud.githubusercontent.com/assets/588601/22255849/10736a70-e259-11e6-96f0-91b267e3bf5a.png">

If pyqtgraph is downgraded to 0.9.*, class density works.

**Comment by ajdapretnar** [comment]
@astaric Seems like this has been fixed?

**Comment by astaric** [comment]
Fixed in #1990
