### ISSUE TITLE
AUC systematically low

### ISSUE THREAD

**Issue by CornelisRemmert** [biolab/orange3#1953]
##### Orange version

3.3.9

##### Expected behavior
AUC with classification tasks to coalign with results from comparable software.

##### Actual behavior
The AUC that is reported using the Test & Score Widget is structurally lower than the AUC reported in R, Weka, KNIME. This is tested very often under equal circumstances and I found this behavior was earlier reported at stackoverflow:  https://stackoverflow.com/questions/41091483/very-weird-auc-value-with-orange-compare-to-sas-r.

##### Additional info (worksheets, data, screenshots, ...)
example;

same datasets Orange compared to Weka (practically the same confusion matrix)

Orange:

![afbeelding](https://cloud.githubusercontent.com/assets/20670746/22285824/78206242-e2ed-11e6-950f-008243d03db7.png)

Weka

![afbeelding](https://cloud.githubusercontent.com/assets/20670746/22286078/49ca0c30-e2ee-11e6-86f3-1a8cd25977ed.png)

**Comment by markotoplak** [comment]
Which data set did you use here? Perhaps weather from R's rattle library? Did you use all the features? Thanks.

**Comment by CornelisRemmert** [comment]
Here are training and validation set:
[weathertrain.txt](https://github.com/biolab/orange3/files/750310/weathertrain.txt)
[weathervalidate.txt](https://github.com/biolab/orange3/files/750311/weathervalidate.txt)

**Comment by markotoplak** [comment]
I was able to confirm your scores in 3.3.9 and 3.3.10. On master branch my score was 0.835 (which is lower than Weka due to one more misclassification)

This seem to have been fixed in #1826 (not yet released).

**Comment by markotoplak** [comment]
Scheduled for release in 3.3.11.
