### ISSUE TITLE
Esc should close active window

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#1955]
##### Orange version
3.3.10

##### Expected behavior
Esc key closes active window. Works for all widgets.

##### Actual behavior
Esc doesn't work for Geo Map and Word Cloud (perhaps for some other as well). Maybe a WebView issue?

##### Steps to reproduce the behavior
File - Geo Map / Corpus - Word Cloud.

##### Additional info (worksheets, data, screenshots, ...)
This is a port of an issue from our issue board.

**Comment by kernc** [comment]
Fixed in https://github.com/biolab/orange3/pull/1929/commits/47afbd910cbbfc5f55decd4d466dc7b02b7971d6.
