### ISSUE TITLE
Scatter Plot label from string type meta attribute

### ISSUE THREAD

**Issue by processo** [biolab/orange3#1958]
##### Orange version
3.3.9

##### Expected behavior
I would like to use `string` `meta` attributes as labels in Scatter Plot, but they don't show up in the dropdown menu. I know it is possible with `nominal` ones, but those are included in the analysis.

**Comment by ajdapretnar** [comment]
I cannot replicate this. My labels work just fine.

<img width="1055" alt="screen shot 2017-01-26 at 08 16 13" src="https://cloud.githubusercontent.com/assets/12524972/22322981/d463ba6a-e39f-11e6-835e-67df573f4af6.png">

**Comment by processo** [comment]
I've tried the same, but no `name` shows up.

![image](https://cloud.githubusercontent.com/assets/5299789/22323209/8f4b2e7a-e3a1-11e6-8137-87202c0d5d7a.png)

**Comment by ajdapretnar** [comment]
I see, it happens in a standalone installation. We're on it!

**Comment by astaric** [comment]
Btw, could you try reproducing this in version 3.3.10?

3.3.10 was a bugfix release that was supposed to fix this bug (among others). If the issue still occurs in other environments (beside standalone windows installation) we would like to know so we can figure out the cause and fix it.

**Comment by processo** [comment]
In 3.3.10 it works fine. Thanks.
