### ISSUE TITLE
Select Rows filter different from the one shown

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#1962]
File -> Data Table -> Select Rows -> Data table

Load iris. In the first data table, select instances 40 - 60. In Select Rows set condition Iris is Iris-setosa. The second data table shows the correct result.

Now select a single row in the first table. Select Rows resets (it shouldn't).

However, although the GUI is reset, the filter somehow remains active. In the first table, select *at least two* instances of setosa. Or, say, instances 45-55. The second table shows filtered data. Also, some attributes are purged from the data although they are not constant.

**Comment by astaric** [comment]
Fixed in gh-2065
