### ISSUE TITLE
Expand Guide to compiling and installing TSM_SYSTEM_TIME && QUANTILE

### ISSUE THREAD

**Issue by paulgrant999** [biolab/orange3#1975]
for postgres 9.4.  I'm installing Orange3 for a course, and I'm trying to get it to connect to postgres instance.  I did not build postgres; I downloaded precompiled binaries for the server install (which does not include tsm_system_time).  I am unfamiliar with python, and its corresponding psycopg2 library.  

I would like to learn how to build an extension, for a precompiled version of postgres, on windows.  So far make (either under cmd.exe or msys) keeps crapping out on pg_config; under cmd, it dies on the " " in program files.  under msys it can't start the pg_config program.   So if its possible, a step-by-step guide to compiling the tsm_system_time extension, or barring that, a generic makefile (that doesn't use pg_config) for tsm_system_time, and/or quantile.

output of pg_config.   ignore the short names; make is using the full expanded name syntax.  I can't generate either of the configured makefiles in order to compile.  I would like to get this working before I need it.

BINDIR = C:/PROGRA~1/POSTGR~1/9.4/bin
DOCDIR = C:/PROGRA~1/POSTGR~1/9.4/doc
HTMLDIR = C:/PROGRA~1/POSTGR~1/9.4/doc
INCLUDEDIR = C:/PROGRA~1/POSTGR~1/9.4/include
PKGINCLUDEDIR = C:/PROGRA~1/POSTGR~1/9.4/include
INCLUDEDIR-SERVER = C:/PROGRA~1/POSTGR~1/9.4/include/server
LIBDIR = C:/PROGRA~1/POSTGR~1/9.4/lib
PKGLIBDIR = C:/PROGRA~1/POSTGR~1/9.4/lib
LOCALEDIR = C:/PROGRA~1/POSTGR~1/9.4/share/locale
MANDIR = C:/Program Files/PostgreSQL/9.4/man
SHAREDIR = C:/PROGRA~1/POSTGR~1/9.4/share
SYSCONFDIR = C:/Program Files/PostgreSQL/9.4/etc
PGXS = C:/Program Files/PostgreSQL/9.4/lib/pgxs/src/makefiles/pgxs.mk
CONFIGURE = --enable-thread-safety --enable-integer-datetimes --enable-nls --with-ldap --with-ossp-uuid --with-libxml --with-libxslt --with-tcl --with-perl --with-python
VERSION = PostgreSQL 9.4.10

**Comment by astaric** [comment]
I do not think you can do this with postgres 9.4, as the tsm_system_time has been added in postgres 9.5 (https://www.postgresql.org/docs/9.5/static/tsm-system-time.html).

You might also consider trying the 2UDA installer (https://2ndquadrant.com/en/resources/2uda/) which  probably includes all required postgres extensions (@lanzagar is this true?)

**Comment by lanzagar** [comment]
That is correct, TABLESAMPLE was added in postgresql 9.5 (and the tsm extension just adds another sampling method).

2UDA would be the easiest way to install a fresh postgresql server on windows which should work out of the box. If limited to some custom server, it needs to be updated to at least 9.5 first.

**Comment by ajdapretnar** [comment]
@lanzagar Should this be documented somewhere or is this implied?

**Comment by ajdapretnar** [comment]
Fixed in #3196 and #3113.
