### ISSUE TITLE
Allow manual entry of proxy server.

### ISSUE THREAD

**Issue by astaric** [biolab/orange3#1999]
On networks, where proxy use is mandatory, Orange cannot access the network.

We could add a setting to canvas where users could specify which proxy server to use and modify the widgets to access this setting and use proxy, if the setting has a value.

Addon dialog, file widget, image embedings (addon), twitter (addon) and some more need to be modified.

**Comment by kernc** [comment]
If we have the setting set `http_proxy` environment variable and require a restart, this is all that's needed for requests / urllib code to use it.

**Comment by astaric** [comment]
Set it when canvas is opened or did you have a more permanent way in mind? Why is the restart necessary?

**Comment by kernc** [comment]
Yes, when the canvas is open, check the setting and set the environ. The restart is necessary because any existing Request/Session objects ~~would~~might not honor this setting.

**Comment by astaric** [comment]
Fixed in #2906
