### ISSUE TITLE
HiDPI not supported

### ISSUE THREAD

**Issue by loekiedepo** [biolab/orange3#2009]
##### Orange version

3.3.11

##### Expected behavior
When I open Orange, I expect to be able to read and click things.

##### Actual behavior
Everything is rendered so small that it's nearly impossible to click or read anything on screen

##### Steps to reproduce the behavior
Load Orange into a 4k screen

##### Additional info (worksheets, data, screenshots, ...)
![untitled](https://cloud.githubusercontent.com/assets/9716643/22879338/d71c7fb6-f1dd-11e6-971b-7557bbf7c3c4.png)

**Comment by astaric** [comment]
Are you using windows? Do you have content scaling turned on? If so, to what percentage? (trying to recreate the exact environment)

**Comment by loekiedepo** [comment]
Heya sorry, I'm indeed on Windows 10 build 1677. I've turned content scaling on and off, using all percentages, but even at 350% scaling it's still barely readable. Current screenshot is at 250%.
