### ISSUE TITLE
Sieve Diagram fails to compute Chi2 value

### ISSUE THREAD

**Issue by CornelisRemmert** [biolab/orange3#2020]
##### Orange version

3.3.12

##### Expected behavior
Sieve Diagram to compute Chi2 values (and consequently be ranked on these values in Sieve Rank).

##### Actual behavior
For many crosstabulations the following is returned: X2=nan, p=nan.
Not a number I assume.

##### Steps to reproduce the behavior
For instance try to combine feature "housing" with feature "y" using this dataset:

[bank.txt](https://github.com/biolab/orange3/files/780088/bank.txt)

##### Additional info (worksheets, data, screenshots, ...)
 "housing" with "y" example:

![afbeelding](https://cloud.githubusercontent.com/assets/20670746/23021722/b8e817ea-f44d-11e6-84a6-8dc6c62e9ae1.png)

**Comment by jerneju** [comment]
We tested Steve Diagram using your data on the latest Windows and Ubuntu operating systems and it worked fine. The screenshot is attached. Could you please send us more information about your schema? It would be greatly appreciated if you could send us your schema (.ows) file.

![screenshot_20170216_142725](https://cloud.githubusercontent.com/assets/22157215/23024389/653ce078-f45a-11e6-97e2-ebafb1efc783.png)

**Comment by CornelisRemmert** [comment]
Appearently I cannot upload .ows files, so changed the extension to .txt:

[Quick Steps.txt](https://github.com/biolab/orange3/files/780469/Quick.Steps.txt)

**Comment by CornelisRemmert** [comment]
[Quick Steps - Sieve.txt](https://github.com/biolab/orange3/files/780484/Quick.Steps.-.Sieve.txt)

**Comment by jerneju** [comment]
Thank you for reporting us this issue. Problem is now solved (#2031) and should work fine. The fix is going to be included in the new release.
