### ISSUE TITLE
Replicable sampling in Test & Score

### ISSUE THREAD

**Issue by astaric** [biolab/orange3#2035]
Add an option to choose replicable sampling in Test & Score widget. It should do the same as the Replicable checkbox in Data Sampler

**Comment by MaxGreil** [comment]
I can have a look at this issue.

**Comment by astaric** [comment]
@MaxGreil, how is it going? Did you encounter any problems adding the checkbox?

**Comment by MaxGreil** [comment]
Hi @astaric , I am sorry but I couldn't start to implement yet. I had some troubles installing the software on my Ubuntu `(ImportError: ../lib/python3.5/site-packages/PyQt5/QtCore.so: undefined symbol: PySlice_AdjustIndices)`.
The solution to this was to add `pyqt5==5.10.1` in the `requirement-dev.txt`.

**Comment by ajdapretnar** [comment]
Similar to #3104, no? @markotoplak Would you be interested in adding this?

**Comment by markotoplak** [comment]
Hmmm, @astaric, the Test & Score already seems to pass a fixed random seed forward. Do we need a non-replicable option?

**Comment by astaric** [comment]
Is there another way to get different AUC results on a dataset?

**Comment by markotoplak** [comment]
Shuffle your data? But perhaps in a different widget? 

Currently, data sampler can do a len-1 sample, which is almost shuffling.

**Comment by astaric** [comment]
This could work. In order to consider this issue resolved, I would like the following though:
  1. Modified DataSampler that allows selecting all instances (not just n-1)
  2. DataSampler doc mentioning that the widget shuffles the dataset
  3. A test that checks that DataSampler really shuffles the dataset
  4. An example in Test & Score docs showcasing how this can be done (like #3245)

@markotoplak, what do you think?

**Comment by markotoplak** [comment]
I like the concept to have a randomization on one place only. But perhaps it would be more natural for that functionality to come in the Randomize widget. I would certainly look for it there first.
