### ISSUE TITLE
Rank Informative projections with regard to the color variable

### ISSUE THREAD

**Issue by astaric** [biolab/orange3#2037]
Scatter plot's find informative projections currently uses the class_variable to rank different projections. This should be modified to use the variable selected in color instead.

**Comment by jerneju** [comment]
Nope, this issue has not been solved yet. Yes, the PR was merged but then it has been reverted (See #2237).

**Comment by ajdapretnar** [comment]
Oh right. Could this be referenced in the future, so we can keep track of the state?
