### ISSUE TITLE
Loss of mouse function on the orange canvas

### ISSUE THREAD

**Issue by BobbyTables42** [biolab/orange3#2052]
##### Orange version

Orange 3.3.12

##### Expected behavior
Can use my mouse to connect widgets, double click to perform edits within the widgets

##### Actual behavior
I can use the mouse to drag widgets to the canvas if I do them all at the same time and don't stop to edit anything. As soon as I open the file widget to adjust something, I can perform my adjustment, but after I commit, I no longer have mouse function within the canvas-- clicking anywhere in the gui results in nothing. What is perplexing, is I can still use my laptop's touch screen to then connect widgets or place additional widgets, but, this is too much of an interruption to work flow. 

##### Steps to reproduce the behavior
Running Orange 3.3.12 on a Dell XPS 15 9550, with Fedora 25 as the os. Place the file widget in the canvas, double click it to open a data set. Select iris from the drop down menu, change Sepal.Length to target, all others to feature. Apply changes. Mouse no longer works at this point for my setup.

**Comment by binoz** [comment]
I had a similar issue, not only with orange, but with every jetbrains ide. My issue was caused by the use of Wayland instead of Xorg in Fedora 25. Disabling Wayland solved the problem for me

**Comment by ajdapretnar** [comment]
@BobbyTables42 Could you confirm this solves the issue for you?

**Comment by BobbyTables42** [comment]
I can confirm this remedied the issue; running gnome on xorg resulted in expected operation. Now if wayland support just becomes more natural of a thing to have... Thanks @binoz for the advice.
