### ISSUE TITLE
Nomogram Widget is missing

### ISSUE THREAD

**Issue by CornelisRemmert** [biolab/orange3#2053]
##### Orange version

Orange 3.3.12

##### Expected behavior
I expected to find the Nomogram Widget in the Tool Dock.

##### Actual behavior
The Nomogram Widget is not to be found.

##### Additional info (worksheets, data, screenshots, ...)
Windows 10

![afbeelding](https://cloud.githubusercontent.com/assets/20670746/23342912/eb398cd4-fc62-11e6-8c95-2c52a57cc036.png)

**Comment by ajdapretnar** [comment]
Nomogram is not yet in the official distribution. Please check [changelog](https://github.com/biolab/orange3/blob/master/CHANGELOG.md) for updates and available features.
