### ISSUE TITLE
Select Rows: "is defined" fails

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3#2054]
##### Orange version
3.3.12

##### Expected behavior
Given a data set the widget would be able to select only instances where the value of some attributes are defined.

##### Actual behavior
The widget issues a warning "need more than 0 values to unpack".

##### Steps to reproduce the behavior
Fails on any data set with missing values. Try on housing.tab, use "major vessels colored" attribute.

##### Additional info (worksheets, data, screenshots, ...)
![](https://dl.dropboxusercontent.com/u/28911943/orange-bugs/select-rows-is-defined.png)

**Comment by jerneju** [comment]
I tested it on version 3.3.12 as well and the widget issued a different message: "not enough values to unpack (expected 2, got 0)".
![screenshot_20170228_093922](https://cloud.githubusercontent.com/assets/22157215/23397726/01c83c1a-fd9a-11e6-9167-f0786284809b.png)
