### ISSUE TITLE
Select columns and multiple target variables problems

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#2086]
##### Orange version
master

##### Actual behavior

If there are multiple Target variables, Select columns have a box for Target variables that is too small: in some cases I only see one variable and need to scroll for others.

If I move one target variable somewhere else, I can not move it back if there is already one target variable. So I can not even get into the original state unless I click reset.

**Comment by jerneju** [comment]
Yes, the only option to have more than one target variable in a box "Target Variable" is to press reset button. Then all target variables are listed there.

Maybe we should upgrade the box "Target Variable" to "Target Variable**s**".

**Comment by jerneju** [comment]
Assign @jerneju
