### ISSUE TITLE
Test & Score: AUC is not computed if some class value in missing in the test set

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#2088]
##### Orange version
master

##### Steps to reproduce the behavior
Take iris data set, Logistic Regression, build the classifier on the whole data set and only use some instances for testing in Test&Score. Even if samples with two different class values are present in the test set, AUC is not computed.

I understand that AUC can not be computed with a test set with only a single class value, but two class values should be enough.

**Comment by janezd** [comment]
Fixed in #3676.
