### ISSUE TITLE
Fitter preprocessors

### ISSUE THREAD

**Issue by lanzagar** [biolab/orange3#2091]
##### Orange version

3.4.0

##### Expected behavior
Learners use preprocessors.

##### Actual behavior
Learners extending the Fitter base class do not use preprocessors.

##### Steps to reproduce the behavior
Use a learner on e.g. hearth_disease data set

**Comment by lanzagar** [comment]
This is a very high priority bug in the latest version that needs a fix.
@pavlin-policar do you have time to check this out as you are most familiar with the code?

**Comment by pavlin-policar** [comment]
Sure thing, I'll get right on it.

**Comment by pavlin-policar** [comment]
Should be fixed with #2093
