### ISSUE TITLE
README to update as PyQt5.8.1 is now pip installable starting Python-3.5

### ISSUE THREAD

**Issue by stonebig** [biolab/orange3#2096]
The readme on Github/Pypi incorrectly writes the PyQt is not pip-installable at all.

PyQt5 is now pip installable for  Python-3.5 and later

##### Orange version

**Comment by astaric** [comment]
You are correct. 

If you want, you can go to https://github.com/biolab/orange3/blob/master/README.md and select edit, modify the instructions and propose the new text. Then we can simply merge your changes.

**Comment by ajdapretnar** [comment]
Should be updated now.
