### ISSUE TITLE
Not able to Save Model

### ISSUE THREAD

**Issue by rladha** [biolab/orange3#2099]
##### Orange version
3.4.0 (standalone version) on Windows 10 and Windowns 7

##### Expected behavior

Using this example http://docs.orange.biolab.si/3/visual-programming/widgets/classify/saveclassifier.html

I am trying to save the model to local drive but the SAVE but under Save Model widget is always disable. also, instead of using Logistic Regression - I have tried Naive Bayes but same results. 

Any thoughts? as what I am doing wrong?

Rahim

**Comment by kernc** [comment]
Has the model been trained?

![screenshot - 03132017 - 11 58 55 pm](https://cloud.githubusercontent.com/assets/684364/23878703/47fbe678-0849-11e7-891c-7ab8fd59793b.png)

**Comment by rladha** [comment]
Thanks - Issue is resolved!

Possible you can guide a good example as how to use the load Model? I am trying to use the example in the documentation but it is not working.

**Comment by kernc** [comment]
Do you mean like this?
![screenshot - 03142017 - 12 16 32 pm](https://cloud.githubusercontent.com/assets/684364/23898133/2528d914-08b0-11e7-9868-6811b31ee012.png)

Please see our [Orange tutorials on YouTube](https://www.youtube.com/playlist?list=PLmNPvQr9Tf-ZSDLwOzxpvY-HrE0yv-8Fy).
