### ISSUE TITLE
Installing Orange3 in Anaconda: Mismatching g++ and libstdc++

### ISSUE THREAD

**Issue by marhoy** [biolab/orange3#2107]
I'm running Fedora 25, which comes with gcc/g++/libstdc++ version 6.3.1. I'm also running Anaconda version 4.3.1, which comes with libstdc++ 6.0.19.

When I install Orange3-3.4.0 under Anaconda (by saying "pip install orange3"), some files are compiled with Fedoras g++, but linked against Anacondas libstdc++:

Note the third line of output:

```
$ ldd ~/anaconda3/lib/python3.6/site-packages/Orange/widgets/utils/_grid_density.cpython-36m-x86_64-linux-gnu.so
linux-vdso.so.1 (0x00007ffe9b5a2000)
libpython3.6m.so.1.0 => /home/marhoy/anaconda3/lib/libpython3.6m.so.1.0 (0x00007efc3a6ef000)
libstdc++.so.6 => /home/marhoy/anaconda3/lib/libstdc++.so.6 (0x00007efc3a3d9000)
libm.so.6 => /lib64/libm.so.6 (0x00007efc3a0ad000)
libgcc_s.so.1 => /home/marhoy/anaconda3/lib/libgcc_s.so.1 (0x00007efc39e97000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00007efc39c79000)
libc.so.6 => /lib64/libc.so.6 (0x00007efc398b1000)
libdl.so.2 => /lib64/libdl.so.2 (0x00007efc396ad000)
libutil.so.1 => /lib64/libutil.so.1 (0x00007efc394aa000)
librt.so.1 => /lib64/librt.so.1 (0x00007efc392a2000)
/lib64/ld-linux-x86-64.so.2 (0x000055a3c43d1000)
```

This causes problems, as there are differences between 6.3.1 and 6.0.19. So when I try to use the scatter-plot widget, I get:

```
_grid_density.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __cxa_throw_bad_array_new_length
```
If I LD_PRELOAD Fedoras libstdc++, everything seems to work fine. And if I install Orange3 outside of Anaconda (by using pip3 install --user orange3), it also works.

The reason I'm not installing Orange3 from the conda repository is because it is outdated.

So: How can I make the Orange-files link against my Fedora libstdc++ ?

**Comment by ajdapretnar** [comment]
> The reason I'm not installing Orange3 from the conda repository is because it is outdated.

For the recent version you need to add a conda-forge channel and you'll get the latest release of Orange. E.g.:

`conda config --add channels conda-forge`

**Comment by marhoy** [comment]
Thanks, but the latest Orange-version (3.4.0, released 10 days ago) is not in conda-forge either:

`$ conda search orange3 --channel conda-forge | grep 3.4`

Or am I just being too impatient? How frequent do they update?

**Comment by astaric** [comment]
You are being too impatient :)

**Comment by astaric** [comment]
Conda packages are usually built within a day or two after the release, thanks for notifying us they are not there yet.

There was a problem with the build, I have triggered a restart. Some packages are already available while the rest will be uploaded as they are build in the next day or so.

**Comment by astaric** [comment]
(Linux builds have all been uploaded, conda install orange3 should now install the 3.4.0 version)
