### ISSUE TITLE
Saving images as PDF

### ISSUE THREAD

**Issue by lanzagar** [biolab/orange3#2108]
##### Orange version

3.4.0

##### Expected behavior
Save image should offer PDF as a format

##### Actual behavior
Only SVG and PNG available

**Comment by ajdapretnar** [comment]
Just a comment - this never worked. We only ever supported svg and png. But I reckon pdf could be nice.
Even though - is this not the function of the Report?

**Comment by astaric** [comment]
Maybe we should create another template for feature requests :)

If I remember correctly, report does not contain vector images, so it cannot be used for this. Pdf images are meant as an alternative to svg, as most of the people do not know what to do with svgs.

**Comment by ajdapretnar** [comment]
Fixed in #2210.
