### ISSUE TITLE
Fixed axis scales on visualizations

### ISSUE THREAD

**Issue by lanzagar** [biolab/orange3#2109]
##### Orange version

3.4.0

##### Expected behavior
For some plots, you would want e.g. the y-axis scale to be 0-100 and not computed from current data.

**Comment by ajdapretnar** [comment]
Not only fixed axis to 0-100 but perhaps custom length, too.

**Comment by ajdapretnar** [comment]
And logarithmic scale axes.

**Comment by ajdapretnar** [comment]
This will be solved in #3086 for graph exports.
