### ISSUE TITLE
Legible labels of axis values

### ISSUE THREAD

**Issue by lanzagar** [biolab/orange3#2110]
##### Orange version

3.4.0

##### Expected behavior
Visualizations such as Distributions widget, but also others, should have readable labels of the axis values

##### Actual behavior
For many/long labels they overlap and become unreadable.

**Comment by janezd** [comment]
This issue is too general to be actionable - I don't like issues that we can never close. I'm labelling it as "needs discussion" so it's tagged for Friday. I suppose we need to decide how to handle this and then probably open separate issues for individual widgets (and close this one).

**Comment by ajdapretnar** [comment]
First thing is probably tilting labels for x axis. This would already solve many issues. When solving for Distributions (but also applying to Scatter Plot), we need to show datetime variable in a nicer way (currently shown as float, not datetime).

**Comment by janezd** [comment]
Tilting is so Excelishly ugly, imho. Vertical, if we must.

**Comment by ajdapretnar** [comment]
Closing in favour of the above.
