### ISSUE TITLE
Normalization in distances

### ISSUE THREAD

**Issue by lanzagar** [biolab/orange3#2111]
##### Orange version

3.4.0

##### Expected behavior
We should be more explicit about whether e.g. euclidean distance is computed on normalized data or not.
We could include a checkbox for normalization, or have two distances in the dropdown ("euclidean" and "normalized euclidean")

##### Actual behavior
No indication or warning for computing raw euclidean distance.

**Comment by ajdapretnar** [comment]
For what I know, this has been implemented?

**Comment by janezd** [comment]
Yes, in 5adf86f0a9fa555ba9417789a1d17cb71686a119.
