### ISSUE TITLE
Line Chart not working?

### ISSUE THREAD

**Issue by ajhayes83** [biolab/orange3#2119]
[Orange version 3.4.1, same in earlier versions I've tried too]

Expect to get line graph plotted by 'Line Chart' when inputing time series data from 'As Timeseries' into 'Line Chart' (in 'Time Series' add-on)

On opening Line Chart, I see my two column headings 'temperature' and 'activity' inside the left hand side box under the 'Logarithmic axis', but I get a large empty box on the right hand side where I would expect a plot. Can you help? Is this just me or is there a problem with 'Line Chart'?

Many thanks for help!

**Comment by kernc** [comment]
Continued in https://github.com/biolab/orange3-timeseries/issues/11.
