### ISSUE TITLE
[ENH] OWMerge : Chose multiple variables in the 'where' condition

### ISSUE THREAD

**Issue by lopezco** [biolab/orange3#2121]
##### Expected behavior

Being able to merge choosing multiple grouping variables. Maybe using a VariableList instead of a combobox

##### Actual behavior

At the moment only one variable can be chosen to merge

##### Additional info (worksheets, data, screenshots, ...)

Example
![merge](https://cloud.githubusercontent.com/assets/6637618/24093856/3cc1bb72-0d56-11e7-90b7-db85905f4698.png)

**Comment by janezd** [comment]
What if variables don't have matching names?

**Comment by ajdapretnar** [comment]
Just display an error. 😆

**Comment by janezd** [comment]
They may have different names. Currently you can match sex with gender.

**Comment by ajdapretnar** [comment]
I know, I know. I don't think there's really a good solution to this. Only perhaps adding the fourth option 'Merge by several variables' and having the VariableList there, while keeping combo boxes for the rest. VariableList would then require matching names (combos wouldn't).

**Comment by janezd** [comment]
Multiple combo boxes. Similar as, say, line edits in Create class.
