### ISSUE TITLE
Console has no flush() method

### ISSUE THREAD

**Issue by jonmillard** [biolab/orange3#2140]
##### Orange version
3.4

##### Expected behavior
Keras running in a python scripting environment writes to the console

##### Actual behavior
Script fails with error: AttributeError: 'PythonConsole' object has no attribute 'flush'

##### Steps to reproduce the behavior
Use the Keras model.fit() command

##### Additional info (worksheets, data, screenshots, ...)
I am running Keras inside a python script environment.  When running the model.fit method, the Keras code is calling the flush() method on stdout.  As the console is not equipped with that method, the script fails.  I have added a dummy method into the Orange code on my machine as a workaround.  It would however be great if Orange handled that feature where there is substantial output from operations that should be updated in the console as it runs.

**Comment by kernc** [comment]
Fixed in #3039.
