### ISSUE TITLE
Impute: output same variable/column descriptors

### ISSUE THREAD

**Issue by Pelonza** [biolab/orange3#2153]
##### Orange version

3.4.1

##### Expected behavior

When merging two subsets of data, drawn originally from the same data-set, I should end up with precisely the same columns as I started with. 

##### Actual behavior

I seem to either lose columns when using the "intersection" option, or get a bunch of duplicate columns with the "union" option. 

Specifically, I've lost the "age", "Parch", and "PassengerId" columns....

##### Steps to reproduce the behavior

I took the titanic data-set, used two "select row" widgets to split out the male/female passengers, then used impute on those sub-sets to replace ages. 

##### Additional info (worksheets, data, screenshots, ...)

Also... there seems to be no way to "unselect" in the "data table" widget.... this is kind of a problem...
I attached a screen-shot showing all the data-tables open, and the work-flow I was using...

![screenshot 2017-03-29 10 42 30](https://cloud.githubusercontent.com/assets/12863059/24463457/73a7feea-146c-11e7-9d20-338a5cc9dc6f.png)

**Comment by ajdapretnar** [comment]
I think you need to set the input from the first table to Primary data (not Additional data).

**Comment by ales-erjavec** [comment]
The reason for this is that Impute widget actually outputs new variable/column descriptors. They are copies of the inputs but have attached to them a function that computes new values for the (missing) values of the original variable.

The Concatenate widget then treats these variable/column descriptors as distinct.

It is probably a mistake that Impute widget operates this way. Looking back at Orange 2.7, it did output the original variables).

**Comment by Pelonza** [comment]
Thanks for clearing up what's at least happening @ales-erjavec . 
Though it seems sort of weird that SOME columns remained unchanged (and mergable) but others didn't... this might be related to Orange's inability to "clear" un-done commands. I.E., if I selected to impute at least once...even if I turned it off, it's still doing that.

If I had a magic wand to wave here's what I'd do:
1) For any variable where "don't impute" is selected, the column should remain completely unchanged (allowing easy merging back of stuff you didn't change!)
2) Include a check-box for: "Create a new column with the imputed Values" (default is to replace the original column)  -- This might simplify later re-merging and allows the preservation of original data for checking if the imputation makes sense or skews your results in any way.
3) Tag new/replaced columns with an "original" label so that when data was re-merged/joined, they would be combined. 

(3) Is perhaps a _little_ less important, since you could achieve the same effects with a careful application of concatenate and merge (I think).

**Comment by ales-erjavec** [comment]
> Though it seems sort of weird that SOME columns remained unchanged (and mergable) but others didn't... this might be related to Orange's inability to "clear" un-done commands. I.E., if I selected to impute at least once...even if I turned it off, it's still doing that.

I think you are experiencing #2184. Can you just double check that If you uncheck the 'Apply automatically' and only run 'Apply' when the Impute widget is not already performing calculations, you see consistent behavior. Otherwise there might be another error.

**Comment by demiurgo30** [comment]
Is there any solution for this? As of 3.24 I still see new descriptors.

**Comment by ajdapretnar** [comment]
@janezd @lanzagar @markotoplak I think this is something to inspect and discuss.

**Comment by janezd** [comment]
Works for me. Looking at Impute widget's code, I don't think it adds new descriptors when it doesn't impute.

@demiurgo30, can you describe how to replicate the problem? (Preferrably in the smallest possible workflow and with public data.)

**Comment by janezd** [comment]
Cannot replicate. Closed due to inactivity. Re-re-open if needed.
