### ISSUE TITLE
Manifold Learning should work on sparse

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#2158]
##### Orange version

3.5.dev

##### Expected behavior
Manifold Learning works on sparse.

##### Actual behavior
Manifold Learning fails on sparse.

##### Steps to reproduce the behavior
Corpus - Bag of Words - Manifold Learning.

**Comment by kernc** [comment]
According to docs, Isomap and TSNE (with O(n²) `method='exact'`) work with sparse matrix input ...
