### ISSUE TITLE
PCA should work on sparse

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#2159]
##### Orange version

3.5.dev

##### Expected behavior
PCA works on sparse.

##### Actual behavior
PCA fails on sparse.

##### Steps to reproduce the behavior
Corpus - Bag of Words - PCA.

**Comment by nikicc** [comment]
PCA probably cannot work on sparse data efficiently since it requires the data to be centered before computing the covariance matrix.

Maybe we should introduce the SVD widget, since it doesn't center the data and can hence efficiently work on sparse data.
