### ISSUE TITLE
Sieve Diagram should work on sparse

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#2160]
##### Orange version

3.5.dev

##### Expected behavior
Sieve Diagram works on sparse.

##### Actual behavior
Sieve Diagram fails on sparse.

##### Steps to reproduce the behavior
Corpus - Bag of Words - Sieve Diagram.

**Comment by jerneju** [comment]
https://sentry.io/biolab/orange3/issues/244854556/
