### ISSUE TITLE
Paint Data should work on sparse

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#2163]
##### Orange version

3.5.dev

##### Expected behavior
Paint Data works on sparse (at least doesn't fail).

##### Actual behavior
Paint Data fails on sparse.

##### Steps to reproduce the behavior
Corpus - Bag of Words - Paint Data.

**Comment by janezd** [comment]
I think 'doesn't fail' could suffice here. Or do you have a reasonable example of sparse data for Paint?

**Comment by ajdapretnar** [comment]
Couldn't think of any, really. Left it open for interpretation intentionally (perhaps for someone with a wilder imagination).
But in essence, yes, **should not fail on sparse**.

**Comment by nikicc** [comment]
Fixed by #2298.
