### ISSUE TITLE
Venn Diagram should work on sparse

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#2164]
##### Orange version

3.5.dev

##### Expected behavior
Venn Diagram works on sparse.

##### Actual behavior
Venn Diagram fails on sparse.

##### Steps to reproduce the behavior
Corpus - Bag of Words - Venn Diagram.

**Comment by mstrazar** [comment]
This is a more general problem with existing sparse table structure.
Issue #2253

**Comment by mstrazar** [comment]
Solution pending; depends on pull requests #2294 and #2285 .

**Comment by mstrazar** [comment]
Solution ready; waiting to merge PR #2286 .
