### ISSUE TITLE
Nomogram fails on sparse

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#2165]
##### Orange version

3.5.dev

##### Expected behavior
Nomogram works on sparse.

##### Actual behavior
Nomogram fails on sparse.

##### Steps to reproduce the behavior
Corpus - Bag of Words - Nomogram (with Logistic Regression)

##### Additional info (worksheets, data, screenshots, ...)
<img width="446" alt="screen shot 2017-03-30 at 11 28 27" src="https://cloud.githubusercontent.com/assets/12524972/24497530/06a5770c-153c-11e7-8384-12ef74699ac5.png">

**Comment by nikicc** [comment]
Maybe the problem is only in SharedComputeValues https://github.com/biolab/orange3-text/issues/224?

**Comment by nikicc** [comment]
Fixed with https://github.com/biolab/orange3/pull/2197.
