### ISSUE TITLE
Orange considered unsafe at any speed

### ISSUE THREAD

**Issue by ales-erjavec** [biolab/orange3#2184]
##### Orange version

1.*, 2.*, 3.*

##### Expected behavior

When the orange widgets are computing something while using the [OWWidget.progressBar](http://orange-development.readthedocs.io/tutorial-utilities.html#progress-bar-class), the user should be able to interact safely with the GUI if the widget allows it (i.e. does not disable the GUI).

##### Actual behavior

In most cases interaction with the GUI while the widget is already 'working' will result in spurious results on output/display. By that I mean the output will not be the one that is consistent with the GUI state, but instead the one that was initially 'scheduled'.

##### Steps to reproduce the behavior

1.)
File (brown-seleced.tab) -> Impute -> Table

In impute check the 'Apply automatically' select the 'Average/Most frequent' from the Default Method then quickly change it back to 'Don't impute'. When the widget finishes and outputs the final table, it contains the imputed values.

2.)
For instance in 'Test & Score' widget, selecting 'Leave one out' then changing the sampling to 'Cross Validation' before the widget finishes with the existing task will at the end display (and output) the results for 'Leave one out', while proudly displaying the Cross Validation as selected. 

##### Additional info (worksheets, data, screenshots, ...)

The reason is in [ProgressBarMixin.progressBarSet](https://github.com/biolab/orange3/blob/master/Orange/widgets/utils/progressbar.py#L81), which calls unrestrained QApplication.processEvents. Doing this after the event loop is already running is in most cases pure insanity.

**Comment by kernc** [comment]
Fixed in https://github.com/biolab/orange3/issues/2186.
