### ISSUE TITLE
Evaluation of Trained Models on New Data

### ISSUE THREAD

**Issue by nikicc** [biolab/orange3#2191]
##### Usecase scenario
Say I once trained and saved a classifier. Later, when some more labeled data arrives, I would like to asses the performance of my trained model on the new data (like with Test & Score). Hence I load the model and new data set but can only pass them to `Predictions`. What's missing is the calculation of various metrics, like we have it in Test & Score, from the predictions on new data.

Similarly, this would be useful for training a classifier and evaluating it on the held out data set. Though, this could be done with `Test & Score` to obtain the score, the user has no access to the classifier trained in `Test & Score` and is required to train an other model if he want's to save it.

#### Possible approaches
* `Test & Score` could also accept classifiers and not only learners and would only offer options `Test on test data` and `Test on train data`. Though, this somehow conflicts with the `Test` part of the widget name.
* `Test & Score` could accept predictions (evaluation results) from the `Predictions` widget and it would only calculate and show scores. Same concern as above.
* A new widget for calculating metrics that accepts trained models and new data. Some functionality would probably be duplicated with `Test & Score`.

**Comment by janezd** [comment]
Split the main area of Predictions widget, show the table with CA, AUC... above the current table.

Of course, don't copy the code from Test & Score, but move the code into a separate model.

**Comment by janezd** [comment]
Like this. Any objections?

<img width="728" alt="Screenshot 2019-06-06 at 16 09 54" src="https://user-images.githubusercontent.com/2387315/59039730-a8706480-8875-11e9-9637-72f2b1839c33.png">

(Splitter is adjustable.)
