### ISSUE TITLE
Wrong prediction (inconformity to probability) in random forest in Orange2

### ISSUE THREAD

**Issue by zealseeker** [biolab/orange3#2199]
I am not sure whether it will be an inherit problem for Orange3. But at least in Orange2 it happened.

##### Orange version

2.7.8.dev-8f964e2

##### Expected behavior
By default, when the probabilty is higher than 0.5, its preditve class should be 1 or else it will be 0.
if we set the cutoff to 0.5 `orngStat.computeConfusionMatrices(res,1,cutoff=0.5)` Nothing will change.
And if we set the cuttoff other than 0.5, the preditive classes will change according to the predictive probabilities.

##### Actual behavior
In experimental results, the preditive classes didnot give "true prediction" , i.e. it returned 0 when the probability of the positive example was higher than 0.5. And in some other examples, the it returned 1 when the probability of the positive example is lower than 0.5.

This lead to that the SE and SP calculated by the scoring package can not be mapped to the ROC curve.

By a trick, I set the cutoff to 0.50001, it will work correctly
`cm = orngStat.computeConfusionMatrices(res,1,cutoff=0.50001)`
(However, If I set the cutoff to 0.5, nothing will change and it will be still wrong).

##### Steps to reproduce the behavior
```python
data = Orange.data.Table(xx)
ex = Orange.data.Table(xx)
forest = Orange.ensemble.forest.RandomForestLearner(trees=50,name='rf')
model = forest(data)
res = Orange.evaluation.testing.test_on_data([ex])
ROC = Orange.evaluation.scoring.compute_ROC(res)[0]
SE = Orange.evaluation.scoring.Sensitivity(res)[0]
SP = Orange.evaluation.scoring.Specificity(res)[0]
```

##### Additional info (worksheets, data, screenshots, ...)
Wrong data: 
These items predict 0 when p>0.5  :  7, 50, 177, 184,
These items predict 1 when p<0.5  :  72, 87, 121,116, 117, 151, 161, 168

**Comment by zealseeker** [comment]
[rf_results.xlsx](https://github.com/biolab/orange3/files/904441/rf_results.xlsx)

**Comment by markotoplak** [comment]
I do not know whether there are some other effects here, but Random forests (as defined by Breiman and as implemented in Orange 2) do not compute predictions from probabilities. They predict the class with voting, which can sometimes differ from probabilites.

**Comment by ajdapretnar** [comment]
Could this be considered resolved?

**Comment by zealseeker** [comment]
@ajdapretnar You can close the issue now since it (only) occurs in Orange2. I'll try using Orange3 to reproduce the problem. If it also exists, I'll reopen this issue.

**Comment by ajdapretnar** [comment]
Great, thanks!
