### ISSUE TITLE
SVM can't compute scores on image embeddings

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#2201]
##### Orange version
3.5.dev

##### Expected behavior
SVM computes scores on image embeddings data.

##### Actual behavior
SVM in run, but doesn't return scores. 
1. 'NoneType' object is not subscriptable.
2. Some scores could not be computed.

Any reason for this?

##### Steps to reproduce the behavior
Import Images (any data set) - Image Embeddings - Test and Score with SVM.

##### Additional info (worksheets, data, screenshots, ...)
<img width="635" alt="screen shot 2017-04-07 at 11 29 54" src="https://cloud.githubusercontent.com/assets/12524972/24794347/8fb41630-1b85-11e7-90ed-e912b83c544b.png">

**Comment by jerneju** [comment]
To the best of my ability I cannot reproduce this error. However different sort of an error is thrown:

_IndexError: index 14 is out of bounds for axis 2 with size 14_

**Comment by ajdapretnar** [comment]
I can confirm. Perhaps the first bug has been fixed somewhere in between. Now I am also getting IndexError.

**Comment by ajdapretnar** [comment]
Closing, since I can't reproduce anymore.
