### ISSUE TITLE
[REGRESSION] Progressbar is not displayed anymore

### ISSUE THREAD

**Issue by lopezco** [biolab/orange3#2204]
##### Orange version
3.5.0.dev0+68727b4

##### Expected behavior
Display progress-bar on widgets (ex: Impute, Test&Score...)

##### Actual behavior
Problem occurred around this commit: a367f1089970234556887d7ab514825aa1e9f658

##### Steps to reproduce the behavior
File (brown-selected.tab) --> Impute

**Comment by ajdapretnar** [comment]
This has been fixed for most widgets, at least certainly for Impute and Test&Score. Not sure what other widgets would benefit from this. I suggest a single new issue is opened for each desired progress bar.
