### ISSUE TITLE
Canvas: delete button to remove link between two widgets

### ISSUE THREAD

**Issue by jerneju** [biolab/orange3#2218]
##### Orange version
Current master (3.5dev)

##### Expected behavior
Use delete button to remove link which connects two widgets. A user moves mouse cursor above the link, presses delete button on the keyboard, and the link is removed.

##### Actual behavior
- One moves a mouse cursor above the link, then presses right mouse button, and then clicks _Remove_.
- One moves a mouse cursor above the link, then double clicks, and then removes the link using _Edit Links_ window.

**Comment by astaric** [comment]
I do not like the idea of deleting on "hover". In order for deleting with delete to make sense, links should be made selectable. (thus allowing to select multiple links and pressing delete to remove them all)

**Comment by simon1tan** [comment]
right click and click "remove" vs select with mouse and press delete button...not much benefit there for the work required.

**Comment by ajdapretnar** [comment]
I think it would make sense to close this as wontfix.
