### ISSUE TITLE
Classification tree does not work with "big" data and multiprocessing

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#2222]
##### Orange version
master

##### Actual behavior
When I have a data that is big enough, Test Learners does not play well with a Tree. With Collagen from the Datasets widget, it shows an error 'tree failed with error:\nValueError: buffer source array is read-only'. The same happens with adult.tab (in the Tree widget deselect Induce binary tree). 

##### Additional info (worksheets, data, screenshots, ...)
Happened both on Ubuntu 16.04 and a Mac with Anaconda.

Everything is OK If I decrease the size of the data sets enough (for collagen data set the limit of the data going to a Tree was 1MB).

If I disable multiprocessing in the widget it works fine.

The test (if added to test_owtestlearners) below fails:

    def test_tree_big(self):
        data = Table("adult.tab")
        data = data[::3]  # set to higher than 3 and the test would pass
        self.send_signal("Data", data)
        self.send_signal("Learner", TreeLearner(), 0)
        self.assertFalse(self.widget.Warning.scores_not_computed.is_shown())

Everything is OK If I decrease the size of the data sets enough (for collagen data set the limit of the data going to a Tree was 1MB). If I disable multiprocessing in the widget it works fine.

If I try cross-validation from a script below with n_proc=1 both data sets work. If I use n_jobs=2, adult.tab crashes with some other error and collagen just gives a very low score (different to n_jobs=2).

    if __name__ == '__main__':
        import multiprocessing as mp
        mp.freeze_support()
        import Orange
        data = Orange.data.Table("adult")
        #data = Orange.data.Table("/home/marko/collagen.csv")
        tl = Orange.modelling.TreeLearner()
        res = Orange.evaluation.CrossValidation(data, [tl], k=10, n_jobs=2)
        print(Orange.evaluation.AUC(res)

This might be connected with cython and numpy views, see https://github.com/pandas-dev/pandas/pull/12033

**Comment by ajdapretnar** [comment]
I am not getting any errors on this. Is this still an issue?

**Comment by rokgomiscek** [comment]
The widgets work fine, the proposed test doesn't fail, and cross-validation from a script doesn't crash. I am closing this issue.
