### ISSUE TITLE
Bug in Prediction Widget??

### ISSUE THREAD

**Issue by alexfussan** [biolab/orange3#2244]
Hi there,

someone wrote recently the following comment concerning the Prediction widget: 

_"I am facing an issue, when I attach the test file to the Predictions widget it says "One or more predictors failed..." All my columns in the test file are same as my training data file. Also I have set the target variable in the File widget. Can you please help?"_

I have the same problem ... Ist there a bug in Orange 3.4??

Regards from Alex

**Comment by ajdapretnar** [comment]
There was indeed a bug in Orange 3.4.1 that was fixed in the current 3.4.2 release.
Fixed with #2183.
Sorry for the inconvenience!
