### ISSUE TITLE
Report: not working anymore on PyQt5 5.8

### ISSUE THREAD

**Issue by jerneju** [biolab/orange3#2248]
##### Orange version
3.5dev
PyQt5 5.8
Kubuntu 16.04

##### Expected behavior
Should work like on previous version of PyQt5 (5.7) (or at least similarly).

##### Actual behavior
See screenshot below. Report widget window is on the right side.

##### Steps to reproduce the behavior
Upgrade to PyQt5 and start Orange. Have no idea how it works on other computer platforms.

##### Additional info (worksheets, data, screenshots, ...)
![screenshot_20170420_111217](https://cloud.githubusercontent.com/assets/22157215/25223084/b26d8d20-25ba-11e7-9f53-154f7ab83602.png)

**Comment by ajdapretnar** [comment]
@jerneju Does the issue still persist? I cannot replicate it on OSX.

**Comment by jerneju** [comment]
No, it does not persist anymore.
