### ISSUE TITLE
AUC calculation changed from version 3.3.9 to 3.3.12 and later

### ISSUE THREAD

**Issue by Nuoezguen** [biolab/orange3#2250]
##### Orange version
Transition from version 3.3.9 to 3.3.12

##### Expected behavior
AUC calculations should be same for the same data set

##### Actual behavior
version 3.3.12 and later calculates ca. 5% higher AUC for the same data

##### Steps to reproduce the behavior
I am working with a 2-class data set. There is a change in the way the AUC is calculated. For the same data set version 3.3.9 is calculating:
 
Method	AUC	CA	F1	Precision	Recall
SVM	0.951	0.951	0.952	0.952	0.951
Random Forest Classification	0.937	0.937	0.936	0.938	0.937
Logistic Regression	0.931	0.931	0.931	0.931	0.931
kNN	0.825	0.825	0.828	0.825	0.825
Naive Bayes	0.883	0.883	0.881	0.883	0.883

version 3.3.12 prints out:
Method	AUC	CA	F1	Precision	Recall
SVM Learner	0.989	0.951	0.951	0.952	0.951
Random Forest Learner	0.986	0.937	0.939	0.938	0.937
Logistic Regression	0.981	0.931	0.931	0.931	0.931
kNN	0.917	0.828	0.822	0.830	0.828
Naive Bayes	0.936	0.883	0.885	0.883	0.883

Please note, that version 3.3.12 AUC's are ca. 5% higher than version 3.3.9 for the same data set. Which version is correct?

**Comment by jerneju** [comment]
Have you tried version 3.4.1 or 3.4.2?

**Comment by Nuoezguen** [comment]
Yes, version 3.4.2 is behaving like version 3.3.12.

[cid:image001.jpg@01D2B9BB.85303E40]

[cid:image002.jpg@01D2B9BB.85303E40]

**Comment by astaric** [comment]
The AUC from the latest version should be correct. See issue #1953 The fix was merged in #1826, which was as part of 3.3.11, released on 2017-02-03.
