### ISSUE TITLE
Initializing and resizing sparse Tables

### ISSUE THREAD

**Issue by mstrazar** [biolab/orange3#2253]
##### Orange version
'3.5.0.dev0+29835e2'

##### Actual behavior
Cannot initialize a sparse data table using `Orange.data.Table.from_domain`.
Resizing a sparse table requires manual creation of a new sparse table and filling in data at correct indices. 

##### Additional info (worksheets, data, screenshots, ...)
Required for e.g. Venn diagram to work on sparse data.

**Comment by ajdapretnar** [comment]
Closed for similar reasons as in #1719. Need to tackle sparse support in a separate consistent effort.
