### ISSUE TITLE
Dropping widgets directly onto connections

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#2265]
Sometimes is would be nice to be able to add a certain widget onto a current connection. This is currently cumbersome - you have to remove the connection first, add the new widget and reconnect. See this:

https://youtu.be/vYreeoCoQPI?t=2m45s

**Comment by ajdapretnar** [comment]
Perhaps something @irgolic would be interested in? Sounds like quite a difficult task, though... 🤔
