### ISSUE TITLE
OneHot issue

### ISSUE THREAD

**Issue by jackalhan** [biolab/orange3#2267]
Orange 3.4.2

In the following example, https://orange3-associate.readthedocs.io/en/latest/scripting.html, 
it is utilizing ```python X, mapping = OneHot.encode(data, include_class=True)``` command, however I could not find OneHot module in the Orange lib. What should be done as the following step for this case? 

Thank you.

**Comment by kernc** [comment]
It's imported by the `from orangecontrib.associate.fpgrowth import *` line at the top, i.e. it comes with the add-on, not with Orange.

This is the project's repository: https://github.com/biolab/orange3-associate/
