### ISSUE TITLE
Orange.associate module

### ISSUE THREAD

**Issue by jackalhan** [biolab/orange3#2268]
Orange version 3.4.2

I would like to use associate module from the following example : https://docs.orange.biolab.si/2/reference/rst/Orange.associate.html

But there is no similar module in Orange3. Do you have any tutorial that shows finding frequent items in dataset by using orange3? 

Thank you.

**Comment by kernc** [comment]
If you install [Orange3-Associate](https://pypi.python.org/pypi/Orange3-Associate), this API is available: https://orange3-associate.readthedocs.io/en/latest/scripting.html
