### ISSUE TITLE
Windows 10, Postgresql problem installing Quantile

### ISSUE THREAD

**Issue by paulnijssen** [biolab/orange3#2271]
##### Orange version
Version: 3.4.2
git reversion: f3076cb

##### Expected behavior
Provide instructions on how to do this in Windows 10

##### Actual behavior
See related issue #1501 

##### Steps to reproduce the behavior
Windows 10
Clean install postgres (9.6)
Clean install Orange Canvas
(python 3.4)

##### Additional info (worksheets, data, screenshots, ...)
the quantile.controler isn't installed by default i tried using pgxn to install it but i'm not realy sure if this is goning to work because i think i need a dll version of the extention and not the C version that's in the repository. 
( https://pgxn.org/dist/quantile/1.0.0/ , https://github.com/tvondra/quantile )

![image](https://cloud.githubusercontent.com/assets/1046813/25606250/b8065762-2f10-11e7-8ca3-72e469e264b8.png)
![image](https://cloud.githubusercontent.com/assets/1046813/25606258/bff8133e-2f10-11e7-8f2a-bae6ec64fa8a.png)

**Comment by fizcris** [comment]
I am facing the same issue... Have you found any solution?

**Comment by paulnijssen** [comment]
Not realy, i was testing it on way to big db so i swiched to files

**Comment by ajdapretnar** [comment]
This would not be considered an Orange issue. I suggest you ask on postgresql channels how to compile for Windows.
Here are some suggestions:
https://wiki.postgresql.org/wiki/Building_and_Installing_PostgreSQL_Extension_Modules
https://blog.2ndquadrant.com/compiling-postgresql-extensions-visual-studio-windows/
