### ISSUE TITLE
Orange Canvas Shall handle dirty data containing Double-Double Quotes

### ISSUE THREAD

**Issue by drsampson** [biolab/orange3#2293]
##### Orange version

3.5.0.dev0+eb541f1

##### Expected behavior
Load a CSV file from http://open.canada.ca/data/dataset/4ed351cf-95d8-4c10-97ac-6b3511f359b7/resource/d0df95a8-31a9-46c9-853b-6952819ec7b4/download/inventory.csv

##### Actual behavior
"too many indices for array" error presented

##### Steps to reproduce the behavior
* Download file from http://open.canada.ca/data/dataset/4ed351cf-95d8-4c10-97ac-6b3511f359b7/resource/d0df95a8-31a9-46c9-853b-6952819ec7b4/download/inventory.csv
* Open canvas
* Add file widget, point to file
* indices error is presented

##### Additional info (worksheets, data, screenshots, ...)
* the issue is the presence of double-double quotes eg. ""something""
* Search for "" and replace with '
* After removing 182 occurrences of double-double quotes the file loads fine despite a plethora of other bad formatting in the file
* how can Orange be improved to handle this type of dirty data?

**Comment by ajdapretnar** [comment]
Thanks for reporting it, @drsampson! This has been bothering me for a while.

**Comment by ajdapretnar** [comment]
Related to #1471. Reading of xlsx files is indeed problematic.
