### ISSUE TITLE
SQLTable: improve documentation.

### ISSUE THREAD

**Issue by brylie** [biolab/orange3#2296]
This comment came in the Orange3 chat:

> I'm trying to connect to a SQL Server database on a remote server, but if I select SQL table, I get an error that says I need to install a backend to use this widget. I already have pymssql installed, what am I missing?
>
> Nevermind, I installed psycopg2 and that worked. 

To improve usability, perhaps the SQL widget could document which SQL libraries it supports. I.e. the error message could be more helpful to the end-user.

**Comment by simon1tan** [comment]
I absolutely agree it is a very baffling message. Even a link to a webpage with some instructions would be a good start.

**Comment by ajdapretnar** [comment]
I don't think warnings can afford to be very long, so I don't see how we could squeeze in the link or some more elaborate message. Ideas welcome.

However, F1 (or a right-click on the widget - Help) open widget help which defines what dependencies need to be installed. Perhaps it could be better elaborated in the docs, I agree.
