### ISSUE TITLE
Concatenate's union and intersection strange attribute matching

### ISSUE THREAD

**Issue by nikicc** [biolab/orange3#2304]
##### Orange version

master

##### Expected behavior
If one passes a data set thorough two discretize widgets and then concatenates them, selecting either `union` or `intersection` of attributes should probably produce the same result.

##### Actual behavior
Intersection is empty, union contains duplicated attributes.

##### Steps to reproduce the behavior
See schema on the screenshot below.

##### Additional info (worksheets, data, screenshots, ...)
![screen shot 2017-05-09 at 16 47 43](https://cloud.githubusercontent.com/assets/713026/25856761/415ab0d2-34d7-11e7-98e8-4d6a9b1e7da8.png)

![screen shot 2017-05-09 at 16 47 11](https://cloud.githubusercontent.com/assets/713026/25856731/2e5913c0-34d7-11e7-9896-13c7693abf41.png)

**Comment by robertcv** [comment]
According to my discussion with @markotoplak this issue goes very deep into variables and compute_value and a much brother discussion and solution is needed for this kind of problem.
The simplest solution for this concrete issue would be to just add a checkbox like "compare raw" that would create new raw domains (without compute_values) and then compare them. @janezd what's your opinion?

**Comment by janezd** [comment]
Removing `compute_value` is a bad idea. If data with these attributes is later used for training and another part of data from this file will serve for testing, predictors won't be able to discretize the latter.

Attributes from two discretize widgets are in fact different attributes, they just happen to have the same name. They may be discretized with different thresholds. Orange cannot deep-analyze them to check whether attributes coming from `compute_value` (which can be just any function or class) are the same.

I think Orange behaves correctly in this case. Even when we change the way we compare identity of variables, it should keep behaving the same. This issue should be closed, in my opinion.
