### ISSUE TITLE
Orange3 stops working after installing Orange3-Text addon (Windows)

### ISSUE THREAD

**Issue by gbrian** [biolab/orange3#2306]
##### Orange version
**All requested packages already installed.**
**packages in environment at C:\Program Files\Anaconda3:**
orange3                   3.4.1                    py35_0

##### Expected behavior
Continue working ;)

##### Actual behavior
When executing it shows splah screen and some messages about loading modules.
After the splash screen disappears nothing else is shown.

##### Steps to reproduce the behavior
On windows 10. 

* Install Orange3
* Orange3-Text it fails because scipy
* Try to fix with `conda install scipy` 

##### Additional info (worksheets, data, screenshots, ...)
* pythonw.exe stills running

IMPORTANT:
**It worked again after unistalling `Orange3-Text`**

**Comment by kernc** [comment]
How do you know it fails because of scipy?

**Comment by gbrian** [comment]
Hi, not 100% was caused by `scipy` sorry, but that was the error thrown during the installation process.
BTW I have been able to make it work after following: Anaconda Installation
````
First, install Anaconda for your OS (Python version 3.5+). Create virtual environment for Orange:

conda create python=3 --name orange3 
In your Anaconda Prompt add conda-forge to your channels:

conda config --add channels conda-forge
This will enable access to the latest Orange release. Then install Orange3:

conda install orange3 
````
So don't really know what happened.
Thanks

**Comment by nikicc** [comment]
FYI Orange3-Text it is also available on conda-forge and can be installed with: `conda install orange3-text`.

**Comment by gbrian** [comment]
Thanks @nikicc . I did this way and i have all working fine now. Orange3-text was installed without any issue. Great tool
