### ISSUE TITLE
Error Installing Add Ons

### ISSUE THREAD

**Issue by cameronstewart** [biolab/orange3#2323]
##### Orange version

3.3.12
git revision: 2385b94

##### Expected behavior

Install Addon

##### Actual behavior

Errors

##### Steps to reproduce the behavior

Options > Addins > Select Addin > Okay 

##### Additional info (worksheets, data, screenshots, ...)

Error message

Sreenshot - https://twitter.com/cameronstewart/status/865020803078701056

-Collecting Orange3-Textable
  Could not fetch URL https://pypi.python.org/simple/orange3-textable/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600) - skipping
  Could not find a version that satisfies the requirement Orange3-Textable (from versions: )
No matching distribution found for Orange3-Textable

**Comment by jerneju** [comment]
Please upgrade Orange. This issue has been fixed a month ago (#2239).

**Comment by cameronstewart** [comment]
How do I fix.  Do I have to reinstall orange 3?

**Comment by kernc** [comment]
Unfortunately.

**Comment by tastyminerals** [comment]
I receive the same message with Orange 3.21.0. Trying to install it via conda and many add-ons are not found so.
