### ISSUE TITLE
Orange 3.4 crash on exit; error report attached

### ISSUE THREAD

**Issue by stephaniemdavis** [biolab/orange3#2328]
[Orange3.0_CrashReport.txt](https://github.com/biolab/orange3/files/1015373/Orange3.0_CrashReport.txt)

##### Orange version

Orange 3.4.1 Git Version 6b9ec52
OSX Sierra 10.12.4 

##### Expected behavior
Exit the program without generating an error report.

##### Actual behavior
Error report generated after exit when electing NOT to save a particular workflow. Notice that when starting the program from Spotlight, the icon indicates Version 1.0.0 with a 2015 date. Please see attached screenshot of this as well.
![screenshot 2017-05-19 15 58 05](https://cloud.githubusercontent.com/assets/3942106/26264822/2e5ade94-3cac-11e7-9974-ebf2dd649514.png)

##### Steps to reproduce the behavior
Create a workflow, it doesn't matter which one. Upon exiting, when asked if I would like to save the workflow and I respond "no" the program will generate 

##### Additional info (worksheets, data, screenshots, ...)
Error report attached.

**Comment by ajdapretnar** [comment]
Could you perhaps update Orange and see whether the issue still persists? I can't reproduce this. How did you install Orange?

**Comment by stephaniemdavis** [comment]
I installed Orange via the dmg installer I downloaded from your web page.
