### ISSUE TITLE
Slow Image Viewer

### ISSUE THREAD

**Issue by john-bonachon** [biolab/orange3#2332]
##### Orange version
3.4.2

##### Expected behavior
Optimize image loading or memory resources

##### Actual behavior
I have a dataset of ~5000 images. It's not such a large number, but after connecting data to it, it turns really slow.

Also, if I remove the image viewer it seems like memory used for images isn't get released.

**Comment by simon1tan** [comment]
"It's not such a large number" that really depends on a number of factors (CPU, memory, image resolutions). I think thumbnails would help and double-clicking would display the full image.

**Comment by ajdapretnar** [comment]
I think we should think about this in https://github.com/biolab/orange3-imageanalytics/issues/110.
