### ISSUE TITLE
Corpus concatenate

### ISSUE THREAD

**Issue by mstrazar** [biolab/orange3#2333]
##### Orange version
'3.5.0.dev0+bd777d7'

##### Expected behavior
Concatenating two or more Corpuses should return a Corpus with all the relevant data. 

##### Actual behavior
Indexing does not work, as there seems to be preprocessing of documents involved.

Required so that e.g. Venn diagram will be able to output Corpuses, not just sparse Tables.

##### Steps to reproduce the behavior

    ```
    from Orange.data import Table
    from orangecontrib.text.corpus import Corpus
    from orangecontrib.text.vectorization.bagofwords import BowVectorizer
    cp = Corpus.from_file("bookexcerpts.tab")
    bow = BowVectorizer()
    data = bow.transform(cp)

    cp_A = data[:10].copy()
    cp_B = data[10:20].copy()
    cp_concat = Table.concatenate([cp_A, cp_B], axis=0)

    # Now test this:
    >>> len(cp_concat)  # Works correctly
    20
    >>> cp_concat[11]   # Index error
    IndexError
```

**Comment by lanzagar** [comment]
Concatenate should work, using the new method `Corpus.extend` introduced in https://github.com/biolab/orange3-text/pull/258.
It is currently limited to data with same domains.
