### ISSUE TITLE
CreateClass should create variables through make

### ISSUE THREAD

**Issue by nikicc** [biolab/orange3#2346]
##### Orange version

3.5.0.dev0+cf2da75

##### Expected behavior
CreateClass uses `make` to create class variables so that one is able to create the same class variable as present in train data.

##### Actual behavior
CreateClass doesn't use `make`. Hence created class outputs a different variable.

##### Steps to reproduce the behavior
Load two image data sets and pass them through embedding. Then try to create the same target variables as present in the train data and use it in `Test & Score` as test data.

##### Additional info (worksheets, data, screenshots, ...)

![screen shot 2017-05-29 at 11 24 20](https://cloud.githubusercontent.com/assets/713026/26544246/65262296-4461-11e7-8dc3-d4e6b893a8de.png)

**Comment by jerneju** [comment]
It reports the same error if you use _File_ widget instead of _Import Images_ and _Image Embedding_.

**Comment by hikea** [comment]
I've got the same issue with Neural Net. I tired using categories from a file marked as a target variable and via creating classes, but it still says "Test and train data sets have different target variables".
In fact, even choosing the same file on both ends doesn't help.

**Comment by lanzagar** [comment]
We are leaning towards removing (the need for) `make`. Hence this should probably wait until that decision.

**Comment by janezd** [comment]
Eliminating `make` is not on the horizon yet. While I argued (in #2304) that two discretized variables are not necessarily the same variable, they *sometimes* are. We are not able to resolve this problem in general (and it's going to be huge problem in the variable matching that will/would replace `make`), but a fix for this particular widget is trivial enough.
