### ISSUE TITLE
VizRank: does not calculate or show results properly

### ISSUE THREAD

**Issue by jerneju** [biolab/orange3#2347]
##### Orange version
Since `cac4eebc0ad9c1aea1a51757787f3ee0d9d3f025`.

##### Expected behavior
As it did before the commit mentioned above.

##### Actual behavior
Does not work always properly. Set the image below. Sometimes shows two columns instead of one or it shows more rows that it should. New cells are filled with _None_.

##### Steps to reproduce the behavior
_File_ widget and connect it with _Mosaic_. Click _Find Informative Mosaics_. Run _Vizrank_ several times. One must _change the number of attributes_ every time in order to run the _Vizrank_.

##### Additional info (worksheets, data, screenshots, ...)
![screenshot_20170529_104553](https://cloud.githubusercontent.com/assets/22157215/26545571/5eade7dc-4466-11e7-8ee5-a6ed61976b6c.png)

**Comment by ajdapretnar** [comment]
I can't reproduce this. Is this still an issue? @markotoplak? @jerneju?

**Comment by jerneju** [comment]
This issue seems to be fixed.
