### ISSUE TITLE
OWCreateClass: Cannot decode variable without domain

### ISSUE THREAD

**Issue by nikicc** [biolab/orange3#2352]
##### Orange version

3.5.0.dev0+65d59f0

##### Expected behavior
CreateClass doesn't crash when you play around in SelectColumns.

##### Actual behavior
CreateClass crashes sooner or later with `ValueError: Cannot decode variable without domain`

##### Steps to reproduce the behavior
Load Iris, pass it through Select Columns and then to Create Class. Go into Select Columns and drag all features around. For me, it always happens if I drag first all features to metas, then all to Attributes, and them once again all to metas. 

##### Additional info (worksheets, data, screenshots, ...)
https://sentry.io/biolab/orange3/issues/282530151/

**Comment by nikicc** [comment]
https://sentry.io/biolab/orange3/issues/282530151/

**Comment by robertcv** [comment]
Cannot reproduce with Orange version 3.15. Please upgrade and try if this fixes your issue.
