### ISSUE TITLE
Select Columns: densify X

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#2359]
##### Orange version

3.5.dev

##### Expected behavior
Don't crash with resetting a sparse matrix in Select Columns.

##### Actual behavior
Test&Score crashes when a sparse class column on input.

##### Steps to reproduce the behavior
Corpus (bookexcerpts) - Bag of Words - Topic Modelling - Select Columns (put one topic in place of a category) - Test&Score.

##### Additional info (worksheets, data, screenshots, ...)
When checking a Data Table, the class column is sparse. I assume this is the issue.
<img width="1107" alt="screen shot 2017-05-31 at 09 12 14" src="https://cloud.githubusercontent.com/assets/12524972/26620005/4040a8ee-45e1-11e7-9a2e-634ace1274fb.png">

**Comment by jerneju** [comment]
> When checking a Data Table, the class column is sparse. I assume this is the issue.

Agree, this is the issue. But the actual problem is in _Select Columns_ widget. It has to make class column(s) as dense array and not sparse. `Y` should be always dense.

**Comment by ajdapretnar** [comment]
Yeah, that makes sense.

**Comment by ajdapretnar** [comment]
Duplicate of #2498.
