### ISSUE TITLE
Find Informative Projections in Scatter Plot Orange 3.4.2 Crashes Python

### ISSUE THREAD

**Issue by KRKirov** [biolab/orange3#2363]
Going through the basic example of loading iris.tab connecting the file widget to a scatter plot widget produces the expected plot. However, the Find Informative Projections function crashes the app when the Start button is pressed. Anaconda produces the following error message:

## Main error
Application <b>orange3</b> launch may have produced errors.
## Traceback
```
UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
Slow version of gensim.models.doc2vec is being used
An error occurred while fetching help inventory 'PyQt5.QtCore.QUrl('http://example.com/my-widget/docs/')'

```
## System information
```
python: 3.6.0
language: en_GB
os: Windows;8.1;6.3.9600;AMD64;Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.2.13
```

**Comment by brechtm** [comment]
I'm experiencing the same problem. Pressing _Start_ in the Score Plots window shows "0% complete", quickly followed by "(Not Responding)". I have seen it get to "16% complete" once too. Task Manager shows 0% CPU usage.

* Orange 3.4.2
* Python 3.6.1 | packaged by conda-forge | (default, May 23 2017, 14:21:39) [MSC v.1900 64 bit (AMD64)] on win32
* Windows 7 Enterprise SP1 64-bit

**Comment by Dominiquini** [comment]
I'm experiencing the same problem!

**Comment by kernc** [comment]
The fix (https://github.com/biolab/orange3/pull/2389) was merged into master on Friday and will be available in the next release. Thanks.

**Comment by muba1** [comment]
experiencing the same problem, Find Informative Projections was disabled in the last version 3.17 and it had the problem with the 3.16. @markotoplak

**Comment by muba1** [comment]
not it is just a normal spectroscopy data file names are in text variables and , i have also categorical data as targets , after performing k-means i cant use it for finding the informative projecttions. the same data set even the same orange file was working fine with the previous versions. so remiving the text variables did not help.
