### ISSUE TITLE
Orange Crashes when Ranking the Variables

### ISSUE THREAD

**Issue by skappal7** [biolab/orange3#2365]
##### Orange version
3.4.2

##### Expected behavior
Orange should rank attributes helping in reducing the data to work on.

##### Actual behavior
It shuts down by throwing up a message "pythonw.exe has stopped working" 

##### Steps to reproduce the behavior
Use a data set with >=8K rows worth of data with approximately 400 variables and try using the Rank widget. 

##### Additional info (worksheets, data, screenshots, ...)

![orange rank error](https://cloud.githubusercontent.com/assets/7206940/26682219/4d0b90f8-46fd-11e7-9b2f-47a7ae507986.jpg)

**Comment by ajdapretnar** [comment]
I don't think this is an Orange issue. It's your RAM that's giving up and there's nothing we can do about it.
I tried Rank on two giant data sets and it works fine for me (slow but not errors).

**Comment by skappal7** [comment]
Great Thanks for your help, I will try it on another machine and see if ram is causing this. However, the RAM installed on my system is around 6 GB, it will be great to know what should be the bare min. RAM size to make this awesome application work the way it should.

**Comment by ajdapretnar** [comment]
Also, I forgot to mention it would probably help if you had a 64-bit Python via [Anaconda](https://www.continuum.io/downloads).

**Comment by thocevar** [comment]
I can't replicate this on a 32-bit system with the size of the data set that you reported. Ranking did take some time but consumed memory was not an issue. Can you provide an example data set where this happens?

**Comment by ajdapretnar** [comment]
@skappal7 Is this still an issue? Could we try this on a data set where the issue happens?

**Comment by skappal7** [comment]
Hi Ajda,

I turns out to be an issue with the internal memory of my machine as it was
unable to handle the data size on which I was applying the ranking.
However, when I used the same data file on another machine with better RAM
(16 GB) with i7 process it worked fine though it took some time to process
the request.

Data file size 500MB

Please let me know if you need additional information.

Thanks for reaching out!

Regards
Sunil

**Comment by ajdapretnar** [comment]
Ok, great information! I will close the issue.
