### ISSUE TITLE
Predictions Not Working

### ISSUE THREAD

**Issue by skappal7** [biolab/orange3#2366]
##### Orange version
3.4.2

##### Expected behavior
Orange should be able to predict the results using the defined model (Classification Tree, Naive Bayes). However, the application is generating an error that says "The Target is not the same as predictions" where as the target variable and position is the same in both the data sets. Target (FCR)

##### Actual behavior
It should predict based on the training data set. 

##### Steps to reproduce the behavior

Use two data sets one Training and the other Test apply the prediction widget and connect it with the training and the test data sets (post utilizing the classification or any other modeling widget), please refer to the attached screenshot to better understand the workflow and error.

##### Additional info (worksheets, data, screenshots, ...)
Train Data Set
![image](https://cloud.githubusercontent.com/assets/7206940/26683443/71df8638-4701-11e7-8b35-199c4f4327b2.png)

Test Data Set
![image](https://cloud.githubusercontent.com/assets/7206940/26683475/8c12b6d8-4701-11e7-8c4c-d8ed3e4b1fb6.png)

Workflow Screenshot
![image](https://cloud.githubusercontent.com/assets/7206940/26683508/9ec53bb6-4701-11e7-8809-6894556a5ff1.png)

Error Screenshot
![image](https://cloud.githubusercontent.com/assets/7206940/26683525/b2329c20-4701-11e7-998d-e3eccc1a0e9e.png)

**Comment by jerneju** [comment]
Please attach screenshots of **Train Data** and **Test Data** widgets.

**Comment by skappal7** [comment]
I believe I have already done that not sure if you are looking for a specific widget other than what is there within the original issue.

**Comment by jerneju** [comment]
You have attached screenshots of **Data Table** and **Data Table (1)** widgets.

**Comment by skappal7** [comment]
I think I solved it, looking deep into the data field I found out that the data table for Test had an additional Numerical field which was changing the number of predictor variables in the Test Data Set compared to Train data set causing the error. 

Thanks for asking me to check the Data Widget. I believe we can close the case look at the results that I am getting for the NB Model

![image](https://cloud.githubusercontent.com/assets/7206940/26686694/6371ba30-470b-11e7-96d4-ac4e280f49a0.png)

![image](https://cloud.githubusercontent.com/assets/7206940/26686724/79a27a9c-470b-11e7-83e9-82684127a0b8.png)
