### ISSUE TITLE
Can't find Interactive k-Means after installing add-on Educational

### ISSUE THREAD

**Issue by duohappy** [biolab/orange3#2372]
##### Orange version

version: 3.3.6

##### Expected behavior
![](http://oqalccg1p.bkt.clouddn.com/zhouww_orange_Interactive_k-Means.jpg)

##### Actual behavior
![](http://oqalccg1p.bkt.clouddn.com/zhouww_orange_educational.gif)

##### Steps to reproduce the behavior
install add-on Educational successfully
but can't find Interactive k-Means

**Comment by kernc** [comment]
Please [update Orange to the latest version](https://orange.biolab.si/download/) (3.4.3 or so). Orange 3.3.6 was released almost a year ago, and we're a fast-moving target.
