### ISSUE TITLE
Select Rows: Does not filter

### ISSUE THREAD

**Issue by ThirstyGeo** [biolab/orange3#2387]
##### Orange version

3.4.3

##### Expected behavior
"Select Rows --> is not" filters to value

##### Actual behavior
"Select Rows --> is not" does not filter as expected. 

##### Steps to reproduce the behavior
Create a dataframe with a column of nominal data. Label some values with classes, leave others as null.
Use "Select Rows-->is not" to exclude certain rows
All rows that are not null appear to be selected

##### Additional info (worksheets, data, screenshots, ...)

![orange row error](https://user-images.githubusercontent.com/17868615/26909006-752a84b0-4c41-11e7-8990-740f284b575a.png)

**Comment by kernc** [comment]
Were there any missing values in that column?

**Comment by ajdapretnar** [comment]
@ThirstyGeo  Since this is impossible for us to replicate, would you mind sharing the data with us? Or at least describe it?

**Comment by ThirstyGeo** [comment]
Sorry for the delay; this issue has been resolved in the current
