### ISSUE TITLE
"field larger than field limit (131072)" error

### ISSUE THREAD

**Issue by pdc-kaminaga** [biolab/orange3#2404]
I tried File / CSV File Load.
But I got a "field larger than field limit (131072)" error.
Please tell me how to solve this problem.

**Comment by kernc** [comment]
`cut -c -200 in > out`

More seriously, if your file doesn't contain single fields of over 130K of characters, then you might have a delimiter mismatch. Can you paste an example line from the file?

-----
While using `csv`, we might want to [increase field_size_limit](https://stackoverflow.com/questions/15063936/csv-error-field-larger-than-field-limit-131072).

**Comment by pdc-kaminaga** [comment]
It was as you pointed out.
I update the data and try again.
Thank you.

**Comment by X4** [comment]
Reopening, because I run into the same issue, like many others who may have long texts in their dataset.
What's the apparent solution here? Becaues adding a python widget into the pane with the stackoverflow fix doesn't solve it.

**Comment by kernc** [comment]
Fixed in https://github.com/biolab/orange3/pull/2564.
