### ISSUE TITLE
How to group multiple records

### ISSUE THREAD

**Issue by pdc-kaminaga** [biolab/orange3#2406]
Orange version
3.4.3

Please tell me how to process data segment of group of data records.

My data has many document numbers.
The document has many paragraph text records.
Paragraph text records have word list.
A few important paragraphs are selected.
I want to do a test to select important paragraphs.

DOCNO, PARAGRAPH_NO, PARAGRAPH_TEXT, EXTRACT_WORD_LIST, IMPORTANT_PARAGRAPH
000001, 0001, XXXXXXXXXXXXXXX, XXXXX XXXXX XXXXX, 0
000001, 0002, XXXXXXXXXXXXXXX, XXXXX XXXXX XXXXX XXXXX XXXXX, 1
·
000001, nnnn, XXXXXXXXXXXXXXX, XXXXX XXXXX XXXXX XXXXX, 1
·
000002, 0001, XXXXXXXXXXXXXXX, XXXXX XXXXX XXXXX XXXXX XXXXX, 1
000002, 0002, XXXXXXXXXXXXXXX, XXXXX XXXXX XXXXX , 0
·
000002, nnnn, XXXXXXXXXXXXXXX, XXXXX XXXXX XXXXX XXXXX, 1
·
·
Nnnnnn, 0001, XXXXXXXXXXXXXXX, XXXXX XXXXX XXXXX XXXXX XXXXX, 0
Nnnnnn, 0002, XXXXXXXXXXXXXXX, XXXXX XXXXX XXXXX, 0
·
Nnnnnn, nnnn, XXXXXXXXXXXXXXX, XXXXX XXXXX XXXXX XXXXX, 1

**Comment by ajdapretnar** [comment]
I am not entirely sure what you want to do. Can't this be done with Bag of Words and simple predictive modelling? Also, this is an issue to post on https://github.com/biolab/orange3-text rather than here.

**Comment by pdc-kaminaga** [comment]
I will try your advice.
Thank you.
