### ISSUE TITLE
Re-run add-on installation when failing on a package

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#2407]
##### Orange version

3.5.dev

##### Expected behavior
Add-ons that can be installed, get installed on Orange.

##### Actual behavior
When one add-on installation fails, the add-on window closes and none of the checked add-ons after the failing one gets installed.

##### Steps to reproduce the behavior
Windows. Try to install Networks or Timeseries. Then tick an add-on that is listed after one of these two. The add-ons fail and the final add-on doesn't get installed because the windows closes.

##### Additional info (worksheets, data, screenshots, ...)
Can we make the add-on installation continue after the error was reported? Perhaps catch the error, write it as the status of the add on (e.g. Timeseries - Error), then run the installation for the rest of the selected add-ons?

**Comment by ajdapretnar** [comment]
Probably fixed in #2561.

**Comment by astaric** [comment]
Not really. I plan to remove that commit from #2561, as it causes more problems I do not want to tackle in that PR.

**Comment by ajdapretnar** [comment]
Ok. 😞

**Comment by janezd** [comment]
Moved to https://github.com/biolab/orange-canvas-core/issues/71.
