### ISSUE TITLE
Empty Icons on Orange3-spark addon

### ISSUE THREAD

**Issue by mshadi** [biolab/orange3#2419]
##### Expected behavior 
====================
There should be some widgets in the Spark ML section

##### Actual behavior
====================
The Spark ML is empty, 
No error messages where shown, 

##### Steps to reproduce the behavior
====================
Installed Apache Spark 2.1.1 with Hadoop 2.7 on a Windows 10 machine.
Scala 2.11.8 (comes with Spark)
Checked Spark using (spark-shell) in command prompt
Installed Anaconda 4.4.0 Python 3.6 version
Verified that Pandas is installed within Anaconda
Installed Orange
Installed Spark Addon (GUI,,from orange)

##### Additional info (worksheets, data, screenshots, ...)
Should I keep the command prompt open after I execute the (spark-shell) command ? I left it open since it worked and continued to install everything else.
I have never used Python before, I know the job of most of the above-mentioned components, however, this is the first time that I install any of the above. So please please bear with me and be clear with your comments ;))

**Comment by ajdapretnar** [comment]
@mshadi Spark is not our proprietary add-on, thus we cannot offer any help with the bug. Please report the issue to [Spark repository](https://github.com/jamartinh/Orange3-Spark/issues).
