### ISSUE TITLE
Distributions: show probabilities upon selection

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#2420]
##### Orange version

3.5.dev

##### Expected behavior
When selecting Show probabilities the probability line(s) are immediately displayed.

##### Actual behavior
The lines are not immediately displayed. One needs to switch the visualization to see probabilities. Re-drawing the plot should be run upon selection.

##### Steps to reproduce the behavior
File - Distributions. Press Show probabilities.

**Comment by jerneju** [comment]
My bad. This issue occurred because of my wrongly made PR #2383 .
