### ISSUE TITLE
[ENH] Group-by widget.

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#2421]
##### Feature Request
Have the option in Geo Map to have the size of the dot correspond to the sum of instances with the same lat/lon value.

E.g.

lat | lon
------------ | -------------
46.3 | 14.3
46.3 | 14.3
46.3 | 14.3
45.1 | 13.2
45.1 | 13.2

The first three instances would be plotted as one large dot, the last two as a smaller dot.

**Comment by kernc** [comment]
This is a group-by–count operation and it doesn't belong into this widget in my opinion. Any vis widget could benefit from additional aggregate data that group-by provides, such as occurrence counts.

We shouldn't intend to maintain the same code in two places. FWIU, Geo Map in core is deprecated in favor of the [Geo add-on](https://github.com/biolab/orange3-geo/).

**Comment by janezd** [comment]
This will be fixed in #2860, the famous pivot widget.
