### ISSUE TITLE
File widget: change attribute type from numeric to nominal

### ISSUE THREAD

**Issue by brunap** [biolab/orange3#2425]
##### Orange version
3.4.4.

##### Expected behavior
If attribute type change from numeric to nominal, the nominal values shall be listed to the right of the attribute.

##### Actual behavior
If attribute type change from numeric to nominal, no nominal values are listed.

##### Steps to reproduce the behavior
open attached data sheet (test.xlsx) with file widget
change attribute type for 'code' from numeric to nominal 

##### Additional info (worksheets, data, screenshots, ...)

data file
[test.xlsx](https://github.com/biolab/orange3/files/1095211/test.xlsx)

before attribute type change

![one](https://user-images.githubusercontent.com/11367976/27440764-0158851a-576c-11e7-9a2b-910f9d838558.png)

after attribute type change

![numeric-nominal](https://user-images.githubusercontent.com/11367976/27440812-18b27112-576c-11e7-8030-6ff8479910d4.png)

**Comment by thocevar** [comment]
File widget shows the list of nominal values as read from the input file. Updating these values on changes would introduce a lot of complexity. The suggested method to view the list of nominal values after making a change is to use the Edit Domain widget.

**Comment by brunap** [comment]
ok
