### ISSUE TITLE
slightly incorrect attribute name for impute widget in the help

### ISSUE THREAD

**Issue by Igorok75** [biolab/orange3#2432]
##### Orange version

3.4.4

##### Expected behavior

help should contain "remove instances with unknown value"

##### Actual behavior
"Remove examples with missing values"

##### Steps to reproduce the behavior
place  impute icon onto canvas ; open it and open "help" for it.
compare the actual attribute name and what it's said in help

**Comment by ajdapretnar** [comment]
@Igorok75 Thanks for reporting this! However, Orange is constantly evolving and this is not the only outdated example in Help. We are aware of this, but changing the entire documentation every month is quite unfeasible.
We will be updating docs in due time, however. :)

**Comment by astaric** [comment]
@Igorok75, help for Impute widget is generated from this file:
https://github.com/biolab/orange3/blob/master/doc/visual-programming/source/widgets/data/impute.rst

If you want, you can edit the file on Github (there is an edit icon on top of the page), and submit a pull request. When we merge, help will be automatically updated and the change will be attributed to you.
