### ISSUE TITLE
[ENH] Over/undersampling widget

### ISSUE THREAD

**Issue by Zefeng-Wu** [biolab/orange3#2436]
How to deal with unbanlanced data, for example, too much negative instances and few positive instances?
 Is there an option of class weight  to solve the unbanlance when building a model like SVM or other classifiers?

**Comment by tastyminerals** [comment]
This question is not related to **Orange** specifically.
There is plenty of information about unbalanced datasets and they way to handle them, just google.
Here is one paper that might help you: http://sci2s.ugr.es/keel/pdf/algorithm/congreso/kubat97addressing.pdf

**Comment by MrMauricioLeite** [comment]
but do we have SMOTE to oversample our datasets on Orange GUI?
Would we be able to undersample a dataset based on a specific classification forcing, let's say, result A to pre 50% of the output sample?

This would be a great start for unbalanced data mining as the options usually are Ignore it, Undersample it or Oversample it.

**Comment by ajdapretnar** [comment]
This calls for the implementation of a new Over/undersampling widget.
Suggestions for implementation and contributions welcome.
