### ISSUE TITLE
Test & Score: Evaluation Results Not Displaying

### ISSUE THREAD

**Issue by Protesuiq** [biolab/orange3#2442]
##### Orange version
3.4.4

##### Expected behavior
Evaluation Results displaying Method, CA, Sens, Spec, AUC and Brier values

##### Actual behavior

Evaluation Results not displaying Method, CA, Sens, Spec, AUC and Brier values

##### Steps to reproduce the behavior
1. Open File (Iris.tab)
2. Connect Iris data to Test & Score
3. Connect Learner to Test & Score
4. Double click to open Test & Score

##### Additional info (worksheets, data, screenshots, ...)
![image](https://user-images.githubusercontent.com/14926709/27673427-fd9d2086-5ca0-11e7-9ca3-c1e3bd7fc3e4.png)

**Comment by Protesuiq** [comment]
In Python27 env. I have Orange Version 2.7.8.dev-4456761. There I have no problem

![image](https://user-images.githubusercontent.com/14926709/27673538-860eba7e-5ca1-11e7-9c50-9ec80ddc5a5e.png)

**Comment by Protesuiq** [comment]
I can see the issue is already opened 2 days ago [here](https://github.com/biolab/orange3/issues/2435)  I will close this one

**Comment by janezd** [comment]
Thanks. It was also already fixed (#2437), but we forgot to close the issue.
