### ISSUE TITLE
Polynomial Regression Prediction

### ISSUE THREAD

**Issue by Norsusan** [biolab/orange3#2444]
##### Orange version

Orange3 3.4.4

##### Expected behavior
Predictions in Data Table 1 
Expected prediction for -4 should be -16.680
Expected prediction for 0 should be -4.997
Expected prediction for -1 should be 4.010

##### Actual behavior
Prediction for -4 is -5.00
Prediction for 0 is -5.00
Prediction for -1 is -5.00

##### Steps to reproduce the behavior
Use Attached Model
[Data.xlsx](https://github.com/biolab/orange3/files/1112326/Data.xlsx)
[DataTest.xlsx](https://github.com/biolab/orange3/files/1112327/DataTest.xlsx)

**Comment by ales-erjavec** [comment]
The predictor columns `x` in your Data.xlsx and DataTest.xlsx differ in capitalization ('x' vs 'X' respectively). They have to match.

**Comment by Norsusan** [comment]
Thank you

 

Norm
