### ISSUE TITLE
Distributions: Plot doesn't update

### ISSUE THREAD

**Issue by pavlin-policar** [biolab/orange3#2460]
##### Orange version
3.5.0.dev0+942877a

##### Expected behavior
Plot updates when checking "Show relative frequencies". Plot updates when changing "Show probabilities".

##### Actual behavior
The plot only updates on redraw (by changing any other option in the control area).

##### Steps to reproduce the behavior
1. Connect File to Distributions
2. Check "Show relative frequencies" (_plot doesn't change, but should_)
3. Change selection of "Show probabilities" (_plot doesn't change, but should_)

**Comment by ajdapretnar** [comment]
Possible duplicate of #2420?

**Comment by pavlin-policar** [comment]
Yes, pretty much, the only difference being that this also happens when checking "Show relative frequencies".

**Comment by ajdapretnar** [comment]
Fixed in #2428.
