### ISSUE TITLE
Random order of input/output lists

### ISSUE THREAD

**Issue by ales-erjavec** [biolab/orange3#2468]
##### Orange version

3.5.0.dev0+773d80c

##### Expected behavior

The order of Input/Output ports in the GUI (Edit Links dialog) presented to the user is consistent. For instance as in 3.4.4:

<img width="719" alt="screen shot 2017-07-14 at 09 41 01" src="https://user-images.githubusercontent.com/4716745/28203122-96e61bf2-6878-11e7-9e4b-5fc046cec8f6.png">

##### Actual behavior

The order of Input/Output ports in the GUI is random

<img width="719" alt="screen shot 2017-07-14 at 09 46 30" src="https://user-images.githubusercontent.com/4716745/28203323-869a190a-6879-11e7-9aad-8c4ca1f7cd03.png">

<img width="719" alt="screen shot 2017-07-14 at 09 51 12" src="https://user-images.githubusercontent.com/4716745/28203437-04a29a16-687a-11e7-9be7-30c543e39131.png">

<img width="719" alt="screen shot 2017-07-14 at 09 53 49" src="https://user-images.githubusercontent.com/4716745/28203541-75870a32-687a-11e7-95ef-dd9cea05f54a.png">

This happens on Python < 3.6

##### Steps to reproduce the behavior

Run `orange-canvas --force-discovery`, add PCA -> Scatter Plot

**Comment by ajdapretnar** [comment]
+1 on the issue. I keep getting Components as priority output for PCA-Scatter Plot, which should not be the case. :(
