### ISSUE TITLE
Database connection widget should be reingeneered.

### ISSUE THREAD

**Issue by KOLANICH** [biolab/orange3#2482]
Hello. I have tried to implement an SQLite3 backend and encountered some troubles.

1 Current implementation splits servertext into host and port. This is unneeded. Anyway these hist and port are just passed to backends. I think it's more wise to let backend parse that. So I think we should rename that field to ```source``` and pass to backends as it is.

2 I don't know why, but all the rows captured in fact is the first row times the count of rows in the result.

3 I have found some hardcoded stri gs in sql/table.py like ```tablesample```. I know that sqlite doesn't have this keyword.

It seems that database connection widget should be reingeneered.

**Comment by astaric** [comment]
1) I agree that the host and port could be combined in a single field. If you prepare a PR, I can review that.

2) If you can share the code, I can check what is going on. Sounds like limit/offset are not properly passed to the database.

3) Sampling code has not (yet) been moved to the backend class. Even if it were, sqlite would not be able to handle this as it does not support block-level sampling (at least I am not aware of it). One way to avoid this code being called is by forcing the "Download data to memory" checkbox on widget.

**Comment by astaric** [comment]
About the reengineering of the widget, I was playing around with the idea of separating the widget into two, "PostgreSQL" (with connection parameters) and "Select" (where you could select a table/write sql queries)

With this separation, additional widgets could be created for other databases (we currently also support mssql, you are working on sqlite, others have been asking for oracle/odbc support). This way, each "backend" could specify its own parameters in GUI, with names that are meaningful for that backend (for sqlite, you would probably want filename box with "browse" button, for mssql one could implement support for server browser, ...). What do you think?

**Comment by ajdapretnar** [comment]
Joining all database issues in #3565.
