### ISSUE TITLE
Bag of words and Predictive Model

### ISSUE THREAD

**Issue by gthiveos** [biolab/orange3#2491]
Hello, i loaded the Election-2016-Tweets.tab and i make the following flow:
Corpus(Election-2016-Tweets.tab) --> Preprocessing --> Bag of Words
In order to make a predictive Model i used the 'SVM' model and 'Test-Score' evaluate method and then there is an error.
With 'Naive Bayes' method there is no problem.
This error should be indicated, cause there is lot of instances to be processed(?)
If anyone has idea for this please help me. 
Thanks in advance!

**Comment by ajdapretnar** [comment]
The error is:
ValueError: non-zero offset for normalization.... or something like that. :D I'd reproduce it, but it takes forever to get the results.
Need to check libsvm, scikit and computation of SVM on sparse matrices.

**Comment by ajdapretnar** [comment]
This issue should probably be moved to https://github.com/biolab/orange3-text.

**Comment by ajdapretnar** [comment]
Also I can't reproduce it anymore. @gthiveos Would you please try again with the latest version and open the issue at Text repository? Thank you!

**Comment by nikicc** [comment]
I can still reproduce, so I opened the issue on text: https://github.com/biolab/orange3-text/issues/312

@gthiveos please follow there for any updates.
