### ISSUE TITLE
Problem with miniconda installer

### ISSUE THREAD

**Issue by JssRiveraG** [biolab/orange3#2495]
##### Expected behavior
[Doc2.docx](https://github.com/biolab/orange3/files/1175298/Doc2.docx)
[Doc2.docx](https://github.com/biolab/orange3/files/1175299/Doc2.docx)
[Doc2.docx](https://github.com/biolab/orange3/files/1175300/Doc2.docx)

**Comment by ajdapretnar** [comment]
@JssRiveraG Thank you for reporting the issue. It would be nice if you could describe the error and post the screenshot directly into the issue, so it's easier to see what's the problem. :)

**Comment by ajdapretnar** [comment]
For the others:
NSIS Error
Installer integrity check has failed.

**Comment by ales-erjavec** [comment]
This is most probably just an corrupted download. Can you please re-download the installer and try again.

**Comment by ajdapretnar** [comment]
@JssRiveraG Can you confirm it works on re-downloading the installer?
