### ISSUE TITLE
Test and Score Widget: Performance Statistics Not Showing

### ISSUE THREAD

**Issue by sraghavan89** [biolab/orange3#2502]
##### Orange version
<Version 3.3.4 on Mac OSX>

##### Expected behavior
It should show both model names and performance statistics in this view.

##### Actual behavior
Showing model names, but not showing any performance statistics (AUC, CA, F1, etc.)

##### Steps to reproduce the behavior
Use Iris dataset, set up the workflow as shown in image below in Mac OSX, Orange version 3.3.4
<img width="1271" alt="screen shot 2017-07-26 at 2 55 20 pm" src="https://user-images.githubusercontent.com/14940258/28638310-7e8370e8-7212-11e7-9c1a-bb18875c2901.png">

**Comment by markotoplak** [comment]
Thank you reporting this. 

This was fixed and will be released in the next release. Please see #2435 for a workaround.
