### ISSUE TITLE
Tweet Profiler Stopped working

### ISSUE THREAD

**Issue by riksri1** [biolab/orange3#2504]
Suddenly Tweet Profiler Widget Stop working. Even tried to install it again (2 times) but the error persists. Our report is solely dependent on the working of it, please correct it please

**Comment by ajdapretnar** [comment]
This is an issue for Text add-on. Could you please open an issue [(t)here](https://github.com/biolab/orange3-text/issues)? Thanks!

**Comment by riksri1** [comment]
I didn't get you!!
![tweet profiler](https://user-images.githubusercontent.com/1832806/28674620-fb07c38c-72f6-11e7-9e02-fcedea46932d.png)

**Comment by ajdapretnar** [comment]
Closing this due to a new issue being opened on Text.
