### ISSUE TITLE
Tweet Profiler stopped working

### ISSUE THREAD

**Issue by riksri1** [biolab/orange3#2505]
##### Orange version
Orange 3.4.4
##### Expected behavior
Tweet Profiler should give the desired outcomes.

##### Actual behavior
Not working at all and system stops.

##### Steps to reproduce the behavior
No idea

##### Additional info (worksheets, data, screenshots, ...)

Screen Shot attached
![tweet profiler](https://user-images.githubusercontent.com/1832806/28674552-c605c17a-72f6-11e7-9e0a-f4446dbc8438.png)

**Comment by nikicc** [comment]
Closing, since this is an [Orange3-Text issue](https://github.com/biolab/orange3-text/issues/292).
