### ISSUE TITLE
Problem with  lod file by File Widget

### ISSUE THREAD

**Issue by rmvaliev** [biolab/orange3#2511]
dear team

I can not load csv file when file contains more then 22 fields (features).
Pls find attached zip file.

![image](https://user-images.githubusercontent.com/19163381/28755215-678b5122-755e-11e7-95be-d6ed35e6459b.png)

[tbl_xxx.zip](https://github.com/biolab/orange3/files/1185829/tbl_xxx.zip)

**Comment by ajdapretnar** [comment]
@rmvaliev You're file is not comma separated. If you are loading a .csv file, your values need to be separated by commas. Please make sure that your editor (Excel, LibreCalc) is saving the file as comma delimited.
Alternatively you can load .xlsx files, but again, each value needs to be in each own proprietary field. Your values are all in one field and this is how Orange reads them.
