### ISSUE TITLE
Add-on installation not working: text- and image analytics

### ISSUE THREAD

**Issue by martijnlamb** [biolab/orange3#2516]
##### Additional info (worksheets, data, screenshots, ...)
Command failed: python -m pip install. Orange 3 text exited with non zero status

**Comment by ajdapretnar** [comment]
Can you please report which OS you are using, how you installed Orange and what version are you using?
Thanks!

**Comment by nikicc** [comment]
Perhaps, can you also share a more detailed log of the failure?

**Comment by martijnlamb** [comment]
Hi Adja,

 

I downloaded it from: https://orange.biolab.si/download/

 

Version: 3.4.5 Python: 3.4.4

Further info about OS:  

 



 

More deatailed info about the error:  

 

 



 

 

Collecting Orange3-Text

Using cached Orange3-Text-0.2.5.tar.gz

Requirement already satisfied: Orange3>=3.4.3 in c:\program files (x86)\orange\lib\site-packages (from Orange3-Text)

Collecting beautifulsoup4 (from Orange3-Text)

Using cached beautifulsoup4-4.6.0-py3-none-any.whl

Collecting docx2txt>=0.6 (from Orange3-Text)

Using cached docx2txt-0.6.tar.gz

Collecting gensim>=0.12.3 (from Orange3-Text)

Using cached gensim-2.3.0.tar.gz

Collecting lxml (from Orange3-Text)

Using cached lxml-3.8.0-cp34-none-win32.whl

Collecting nltk>=3.0.5 (from Orange3-Text)

Using cached nltk-3.2.4.tar.gz

Requirement already satisfied: numpy in c:\program files (x86)\orange\lib\site-packages (from Orange3-Text)

Collecting odfpy>=1.3.5 (from Orange3-Text)

Using cached odfpy-1.3.5.tar.gz

Collecting pdfminer3k>=1.3.1 (from Orange3-Text)

Using cached pdfminer3k-1.3.1.tar.gz

Requirement already satisfied: scikit-learn in c:\program files (x86)\orange\lib\site-packages (from Orange3-Text)

Requirement already satisfied: scipy in c:\program files (x86)\orange\lib\site-packages (from Orange3-Text)

Collecting setuptools-git (from Orange3-Text)

Using cached setuptools_git-1.2-py2.py3-none-any.whl

Collecting simhash (from Orange3-Text)

Using cached simhash-1.7.1.tar.gz

Collecting tweepy (from Orange3-Text)

Using cached tweepy-3.5.0-py2.py3-none-any.whl

Requirement already satisfied: typing in c:\program files (x86)\orange\lib\site-packages (from Orange3-Text)

Collecting validate_email (from Orange3-Text)

Using cached validate_email-1.3.tar.gz

Collecting wikipedia (from Orange3-Text)

Using cached wikipedia-1.4.0.tar.gz

Requirement already satisfied: AnyQt>=0.0.8 in c:\program files (x86)\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text)

Requirement already satisfied: CommonMark>=0.5.5 in c:\program files (x86)\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text)

Requirement already satisfied: keyring in c:\program files (x86)\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text)

Requirement already satisfied: chardet>=2.3.0 in c:\program files (x86)\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text)

Requirement already satisfied: bottleneck>=1.0.0 in c:\program files (x86)\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text)

Requirement already satisfied: docutils in c:\program files (x86)\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text)

Requirement already satisfied: dill in c:\program files (x86)\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text)

Requirement already satisfied: joblib>=0.9.4 in c:\program files (x86)\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text)

Requirement already satisfied: pyqtgraph>=0.10.0 in c:\program files (x86)\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text)

Requirement already satisfied: keyrings.alt in c:\program files (x86)\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text)

Requirement already satisfied: xlrd>=0.9.2 in c:\program files (x86)\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text)

Requirement already satisfied: setuptools>=11.3 in c:\program files (x86)\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text)

Requirement already satisfied: six>=1.5.0 in c:\program files (x86)\orange\lib\site-packages (from gensim>=0.12.3->Orange3-Text)

Collecting smart_open>=1.2.1 (from gensim>=0.12.3->Orange3-Text)

Using cached smart_open-1.5.3.tar.gz

Collecting pytest>=2.0 (from pdfminer3k>=1.3.1->Orange3-Text)

Using cached pytest-3.2.0-py2.py3-none-any.whl

Collecting ply>=3.4 (from pdfminer3k>=1.3.1->Orange3-Text)

Using cached ply-3.10.tar.gz

Collecting requests-oauthlib>=0.4.1 (from tweepy->Orange3-Text)

Using cached requests_oauthlib-0.8.0-py2.py3-none-any.whl

Collecting requests>=2.4.3 (from tweepy->Orange3-Text)

Using cached requests-2.18.3-py2.py3-none-any.whl

Requirement already satisfied: future in c:\program files (x86)\orange\lib\site-packages (from CommonMark>=0.5.5->Orange3>=3.4.3->Orange3-Text)

Requirement already satisfied: pywin32-ctypes; sys_platform == "win32" in c:\program files (x86)\orange\lib\site-packages (from keyring->Orange3>=3.4.3->Orange3-Text)

Requirement already satisfied: pyreadline>=1.7.1 in c:\program files (x86)\orange\lib\site-packages (from dill->Orange3>=3.4.3->Orange3-Text)

Collecting boto>=2.32 (from smart_open>=1.2.1->gensim>=0.12.3->Orange3-Text)

Using cached boto-2.48.0-py2.py3-none-any.whl

Collecting bz2file (from smart_open>=1.2.1->gensim>=0.12.3->Orange3-Text)

Using cached bz2file-0.98.tar.gz

Collecting colorama; sys_platform == "win32" (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text)

Using cached colorama-0.3.9-py2.py3-none-any.whl

Collecting py>=1.4.33 (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text)

Using cached py-1.4.34-py2.py3-none-any.whl

Collecting oauthlib>=0.6.2 (from requests-oauthlib>=0.4.1->tweepy->Orange3-Text)

Using cached oauthlib-2.0.2.tar.gz

Collecting urllib3<1.23,>=1.21.1 (from requests>=2.4.3->tweepy->Orange3-Text)

Using cached urllib3-1.22-py2.py3-none-any.whl

Collecting idna<2.6,>=2.5 (from requests>=2.4.3->tweepy->Orange3-Text)

Using cached idna-2.5-py2.py3-none-any.whl

Collecting certifi>=2017.4.17 (from requests>=2.4.3->tweepy->Orange3-Text)

Using cached certifi-2017.7.27.1-py2.py3-none-any.whl

Installing collected packages: beautifulsoup4, docx2txt, boto, bz2file, urllib3, idna, certifi, requests, smart-open, gensim, lxml, nltk, odfpy, colorama, py, pytest, ply, pdfminer3k, setuptools-git, simhash, oauthlib, requests-oauthlib, tweepy, validate-email, wikipedia, Orange3-Text

Exception:

Traceback (most recent call last):

File "C:\Program Files (x86)\Orange\lib\site-packages\pip\basecommand.py", line 215, in main

status = self.run(options, args)

File "C:\Program Files (x86)\Orange\lib\site-packages\pip\commands\install.py", line 342, in run

prefix=options.prefix_path,

File "C:\Program Files (x86)\Orange\lib\site-packages\pip\req\req_set.py", line 784, in install

**kwargs

File "C:\Program Files (x86)\Orange\lib\site-packages\pip\req\req_install.py", line 851, in install

self.move_wheel_files(self.source_dir, root=root, prefix=prefix)

File "C:\Program Files (x86)\Orange\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files

isolated=self.isolated,

File "C:\Program Files (x86)\Orange\lib\site-packages\pip\wheel.py", line 345, in move_wheel_files

clobber(source, lib_dir, True)

File "C:\Program Files (x86)\Orange\lib\site-packages\pip\wheel.py", line 316, in clobber

ensure_dir(destdir)

File "C:\Program Files (x86)\Orange\lib\site-packages\pip\utils\__init__.py", line 83, in ensure_dir

os.makedirs(path)

File "C:\Python34\lib\os.py", line 237, in makedirs

mkdir(name, mode)

PermissionError: [WinError 5] Access is denied: 'C:\\Program Files (x86)\\Orange\\Lib\\site-packages\\beautifulsoup4-4.6.0.dist-info'

 

 

Thanks for your help,

Martijn

**Comment by ajdapretnar** [comment]
Seems like a simple permission error. Can you try with a [standalone installer](https://orange.biolab.si/download/windows/) and see whether the problem persists? It's the second option in the link.

**Comment by martijnlamb** [comment]
I tried the stand –alone option but same error appears

**Comment by martijnlamb** [comment]
Cheers! it is working now J

**Comment by ajdapretnar** [comment]
How did you fix it? :)

**Comment by martijnlamb** [comment]
I intalled the latest version, the option on top of the site

**Comment by Pearapon** [comment]
martijnlamb

what is the latest version and "the option on top of the site", that you installed to solve the problem.

**Comment by astaric** [comment]
@Pearapon, The version on top of the site at that time was Classic, though we recommend using the Miniconda installer.

If you have encountered the same error after installing Orange for all users (into Program Files/...) and add-on installation fails with permission error, you can try running Orange as Administrator when you want to update/install add-ons (that usually helps).
