### ISSUE TITLE
Problem with miniconda installer

### ISSUE THREAD

**Issue by guanshuicheng** [biolab/orange3#2531]
The version of Orange3-3.4.5-Python34-win32.exe always download faild,Should you optimize the download link?

**Comment by astaric** [comment]
There was a problem with the VM running the website, it was randomly dropping connections. I have restarted it and the problem seems to have gone away.

Can you try downloading again?

**Comment by ajdapretnar** [comment]
@guanshuicheng Does the problem persist or is the installer now downloaded properly?
