### ISSUE TITLE
Considerations for supporting on- and off-line analysis of neural time-series data

### ISSUE THREAD

**Issue by brylie** [biolab/orange3#2532]
We are [discussing extending Orange3 as part of a tool for neural time-series data (EEG) analysis](https://github.com/cbrnr/mnelab/issues/7), and want to reach out to the Orange3 community. 

- What are some considerations with Orange3 related to time-series analysis? 
- What kinds of challenges might we face related to on-line (real-time) analysis of streaming data in Orange3 environment?

**Comment by brylie** [comment]
There seems to be a [related project called Neuropype](https://www.neuropype.io/), with as-of-yet undisclosed source code, that is building EEG analysis modules on top of Orange3.

![Neuropype screen animation](https://www.neuropype.io/images/NeuroPype/gifs/Accelerate.gif)

I will open a second issue regarding license 'adherence' of the Neuropype project.

**Comment by kernc** [comment]
> What are some considerations with Orange3 related to time-series analysis?
> What kinds of challenges might we face related to on-line (real-time) analysis of streaming data in Orange3 environment?

There's a Timeseries add-on that would likely be of limited utility in this use case. Unfortunately, no algorithms or visualizations or even preprocessors or filters currently work on-line, i.e. very few, if any, widgets could be reused as-is. Definitely a more apt data structure would also need to be developed.

Related: https://github.com/biolab/orange3/issues/1833

**Comment by ajdapretnar** [comment]
Considering this is a very old question and that we can give now is no better than the one above, I am closing this. Orange at this point in time is not geared for analysis of streams. Any contribution towards extending the Orange functionality is welcome, though.
