### ISSUE TITLE
License adherence for Neuropype project (Orange3 derivative)

### ISSUE THREAD

**Issue by brylie** [biolab/orange3#2533]
When researching the [idea of using Orange3 as a visual programming environment for EEG data analysis](https://github.com/biolab/orange3/issues/2532), we found a project called [NeuroPype](https://www.neuropype.io/), which clearly uses Orange3 as a basis:

![Neuropype screen animation](https://www.neuropype.io/images/NeuroPype/gifs/Accelerate.gif)

# License compliance?
On the NeuroPype front page, under the 'Accessible' header, it states:

> NeuroPype Community Edition is provided 100% free with source code for non-commercial use.

Additionally, from the [Neuropype academic version page](https://neuropype.io/academic):
> We're delighted to announce the release of our new Neuropype Suite Academic Edition,
which we are making available for free to academics, researchers and students around the world
for non-commercial use and research. 

Does Orange3's use of the GPL v3 allow for downstream projects/packages to add 'non-commercial usage' terms?

# Open-source track record
For what it's worth, the [Qusp Neurotechnologies organization](https://www.qusp.io), which is developing NeuroPype, [consists of people](https://www.qusp.io/#tm-bottom-a) who have made many [open-source contributions](http://www.qusp.io/). So, I have high confidence the NeuroPype stakeholders could discuss the subtleties of license compatibility as well as the guiding principles of the Free Software movement.

Here are the Qusp team members whom I could find on GitHub:

- Christian Kothe (@chkothe)
- Nima Bigdely Shamlo (@bigdelys)

# Reaching out?
Would it be advisable for a member of the Orange3 leadership team to [contact Qusp Neurotechnologies](https://www.qusp.io/contact) to open a dialogue?

**Comment by Timopheym** [comment]
@brylie How is it going?

**Comment by brylie** [comment]
Pretty good @Timopheym. How are you doing?

**Comment by brylie** [comment]
Basically, it should be up to the Neuropype developers to articulate how *non-commercial* license terms are compatible with the Orange 3 license (GPL).

cc: @chkothe @bigdelys

**Comment by ajdapretnar** [comment]
@brylie I have contacted their developers and they seem to comply well with GPL. I am posting parts of their response as clarification:

> 
> NeuroPype Suite is a software bundle that includes a number of separate applications with different licenses:
> 
> - NeuroPype™, a python-based signal processing and dataflow programming application that is accessed locally or on the cloud over a REST API. NeuroPype is not based on Orange in any way, and is released under its own proprietary licenses (Enterprise, Academic, Developer, etc).
> 
> - Pipeline Designer, a visual designer application, based on portions of Orange3, that can be used to design pipelines using a “drag and drop” interface. Pipeline Designer is open sourced under the GPLv3. As per the GPLv3, we include the full source code of Pipeline Designer in the installation that is provided with the NeuroPype Suite, without any restrictions on the user’s ability to use, modify, publicly redistribute, etc. the program or code under the GPLv3.

I am considering the issue closed.
