### ISSUE TITLE
One module one widget?

### ISSUE THREAD

**Issue by richdyang** [biolab/orange3#2545]
I am writing Orange widgets right now. I found I cannot place multiple widget class in one module file. Otherwise, the Orange cannot discover the widgets other than the first one. 

I am wondering if this is as design? or where do I get wrong?

**Comment by ajdapretnar** [comment]
Widgets are defined it Orange/widgets/ folder, each in a separate file. This make it easier to follow changes, make edits, (re)move widgets.

Scripting part is separate and placed in a corresponding folder, e.g. Orange/distance for Distances.

**Comment by kernc** [comment]
> I am wondering if this is as design?

Yes, don't worry, this is by design. Can't be asked to properly rationalize it, though.
