### ISSUE TITLE
orange-canvas cannot start due to numpy ImportError "DLL load failed"

### ISSUE THREAD

**Issue by phiedulxp** [biolab/orange3#2546]
##### Orange version

orange3=3.4.5
##### Expected behavior

show the orange GUI

##### Actual behavior

Traceback (most recent call last):
  File "E:\Anaconda2\envs\orange\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Anaconda2\envs\orange\Scripts\orange-canvas-script.py", line 3, in <module>
    import Orange.canvas.__main__
  File "E:\Anaconda2\envs\orange\lib\site-packages\Orange\__init__.py", line 11, in <module>
    from .misc.lazy_module import _LazyModule
  File "E:\Anaconda2\envs\orange\lib\site-packages\Orange\misc\__init__.py", line 3, in <module>
    from .distmatrix import DistMatrix
  File "E:\Anaconda2\envs\orange\lib\site-packages\Orange\misc\distmatrix.py", line 1, in <module>
    import numpy as np
  File "E:\Anaconda2\envs\orange\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "E:\Anaconda2\envs\orange\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "E:\Anaconda2\envs\orange\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "E:\Anaconda2\envs\orange\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "E:\Anaconda2\envs\orange\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: 找不到指定的模块。

##### Steps to reproduce the behavior

conda create -n orange python=3.5.4
conda install -n orange orange3=3.4.5
activate orange
orange-canvas

**Comment by kernc** [comment]
Can you run in that env: `python -m site`.

**Comment by phiedulxp** [comment]
@kernc 
```
python -m site
sys.path = [
    'C:\\Users\\xxx',
    'E:\\Anaconda2\\envs\\orange\\python35.zip',
    'E:\\Anaconda2\\envs\\orange\\DLLs',
    'E:\\Anaconda2\\envs\\orange\\lib',
    'E:\\Anaconda2\\envs\\orange',
    'E:\\Anaconda2\\envs\\orange\\lib\\site-packages',
    'E:\\Anaconda2\\envs\\orange\\lib\\site-packages\\win32',
    'E:\\Anaconda2\\envs\\orange\\lib\\site-packages\\win32\\lib',
    'E:\\Anaconda2\\envs\\orange\\lib\\site-packages\\Pythonwin',
    'E:\\Anaconda2\\envs\\orange\\lib\\site-packages\\setuptools-27.2.0-py3.5.egg',
]
USER_BASE: 'C:\\Users\\xxx\\AppData\\Roaming\\Python' (exists)
USER_SITE: 'C:\\Users\\xxx\\AppData\\Roaming\\Python\\Python35\\site-packages' (doesn't exist)
ENABLE_USER_SITE: True
```

**Comment by kernc** [comment]
Nevermind. Likely this bug: https://github.com/numpy/numpy/issues/9272. Try:
```py
conda install numpy
orange-canvas
```
Else try to update Python to 3.6.2 beforehand.

**Comment by phiedulxp** [comment]
@kernc 
```
conda install -n orange numpy
Package plan for installation in environment E:\Anaconda2\envs\orange:

The following packages will be UPDATED:

    bottleneck:   1.2.1-np112py35_0  conda-forge --> 1.2.1-np113py35_0  conda-forge
    numpy:        1.12.1-py35_0                  --> 1.13.1-py35_0
    scikit-learn: 0.19.0-np112py35_0             --> 0.19.0-np113py35_0
    scipy:        0.19.1-np112py35_0             --> 0.19.1-np113py35_0

The following packages will be DOWNGRADED:

    orange3:      3.4.5-np112py35_0  conda-forge --> 3.4.1-py35_0
```
As  3.4.1 version doesn't have  Orange3-text Add-on,
I just want to try Orange3-text Add-on, it tell me to upgrade to 3.4.5

**Comment by phiedulxp** [comment]
@kernc 
it work well with  Python 3.6.2 , thanks.

**Comment by astaric** [comment]
It looks like the problem was solved by updating to latest python (which probably uses the latest numpy) and the problem went away. As numpy is used all around the code, I do not think we can do anything else in such cases.
