### ISSUE TITLE
Orange Data Mining Scripting Does Not Execute

### ISSUE THREAD

**Issue by ghost** [biolab/orange3#2554]
##### Orange version
Orange 3.5 Version: 3.5.0.dev0+2dc1334

##### Expected behaviour

Referring to: https://docs.orange.biolab.si/3/data-mining-library/#tutorial

Using the Python3 REPL, the expected behaviour was:

$ python3
>>> import Orange
>>> Orange.version.version
'3.2.dev0+8907f35'
>>>

##### Actual behaviour
jna ~ >> python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04)
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Orange
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'Orange'
>>>

##### Steps to reproduce the behaviour
Invoke Python3 REPL
>>> import Orange

##### Additional info (worksheets, data, screenshots, ...)
O/S: Ubuntu 17.04 (Zesty Zapus)
Kernel: Linux soapbox 4.10.0-32-generic #36-Ubuntu SMP Tue Aug 8 12:10:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Orange 3.5: Built as per instructions at https://github.com/biolab/orange3

Prior to every time this system shutdowns, the orange3* directories are rm -rf.
After successful reboot, Orange3 is built from scratch using the Github instructions.

**Comment by ales-erjavec** [comment]
Did you install orange in an v virtual env? Make sure that the python environment in which orange is installed is active. I.e. run `source ~/orange3env/bin/activate` (replace  `orange3env` with your chosen env prefix if you choose a different one) and run `python` (note the lack of `3`).

**Comment by justinant** [comment]
As stated in the above issue report:

"Orange 3.5: Built as per instructions at https://github.com/biolab/orange3" ... exactly.

That said, I just redid Orange as per those instructions, executed "python" as per your suggestion which then failed, but executing "python3" worked. However in both case "python" & "python3", the version is in fact Python 3.5.

Output:

(o3) jna orange3 >> python
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Orange
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jna/orange3/Orange/__init__.py", line 6, in <module>
    import dill
ImportError: No module named 'dill'
>>> 
(o3) jna orange3 >> python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Orange
>>> Orange.version.version
'3.5.0.dev0+c3a7d1a'

I guess that something in the code base changed in the last day or so and now it works. This issue can be closed off if you believe it is rectified.
