### ISSUE TITLE
Orange documentation: outdated Input/Output signal documentation

### ISSUE THREAD

**Issue by Juriell** [biolab/orange3#2560]
I was trying to make input and output signals using classe Orange.widgets.widget.Input output Orange.widgets.widget.Output and could not understand why my widget is not appearing after i install it.
After about 3 hours it struck me that i could check the object class with dir(Orange.widgets.widget)
and there i noticed that the classes are actually Orange.widgets.widget.InputSignal  and Orange.widgets.widget.OutputSignal

Please update this documentation: https://orange-development.readthedocs.io/widget.html#input-output-signal-definitions
I think you have to update the whole section: http://orange3.readthedocs.io/projects/orange-development/tutorial-cont.html#
because when i started widget developing i just could not get anything working

Edit: Also please include that you define the output as  outputs = [widget.OutputSignal("Data", Table)] and then send data to it with self.send("Data",table) where table is an orange Table.
This is crucial because if you follow the documentation and define an Outputs class replacing Output() with Outputsignal() and then send data with self.Outputs.table.send() - you get an error because the OutputSignal has no method send().

**Comment by astaric** [comment]
Could you please check which version of Orange are you using? 

The latest version is 3.5.0. The "new style signals" mentioned in the documentation have been available since 3.4.3 released in June.

**Comment by astaric** [comment]
@nikicc, @kernc, can we somehow make readthedocs show the version of Orange the documentation was built for? (They way it is done on [django documentation (bottom right corner)](https://docs.djangoproject.com/en/1.11/))

**Comment by Juriell** [comment]
I'm using Orange 3.4.1.

**Comment by kernc** [comment]
@astaric I guess it can. It's done now: http://orange-development.readthedocs.io/en/3.4.1/
All the docs links scattered around the web are currently broken, though. I hate to contribute to link rot, so I might toggle the [single version preference](https://readthedocs.org/dashboard/orange-development/advanced/) back in an hour. We'll have to discuss this.

**Comment by astaric** [comment]
@kernc It would be nice if they redirected old urls to something, but as they do not, I agree, change it back and let's discuss this before we switch.

**Comment by astaric** [comment]
@Juriell I guess you are using anaconda with packages from the default channel only. If it is not a problem, I suggest you add the conda-forge channel and get the latest orange version from there. For details, see the [Download page](https://orange.biolab.si/download/windows/#anaconda)

As long as the 3.4.1 documentation is online on readthedocs, you can use that, but I would strongly suggest you update Orange instead.

**Comment by Juriell** [comment]
Thanks. I Upgraded to 3.5.0 and got it working. I understand that you need to make changes so the processes become more effective but some kind of message is needed when a user built widget is installed and fails to load. Currently the widget is just not shown and the user has no idea what is wrong. Usually this happens when an import fails.

**Comment by astaric** [comment]
When orange is run as
```
python -m Orange.canvas -l 4
```
(enabled debug logging), all widget discovery errors are displayed in the terminal. Those include any import errors encountered when loading widgets.

When we develop new widgets, we usually include [a short script at the end of the file](https://github.com/biolab/orange3/blob/master/Orange/widgets/visualize/ownomogram.py#L1184), which allows us to run a single widget. This way, any errors are encountered directly (no need to construct a workflow).

Were you following the [Getting Started Tutorial](http://orange-development.readthedocs.io/index.html)? If you did, we probably need to mention the verbose logging option there. The "main" script is mentioned as a part of the [Getting Started (Continued)](http://orange-development.readthedocs.io/tutorial-cont.html#testing-your-widget-outside-orange-canvas), but should probably be displayed in the index as well.

**Comment by Juriell** [comment]
Thanks, i will take a look at it.  I did started with the Getting Started Tutorial but since i used an outdated orange version and failed to run the example and had no clue what i was missing, i went a different road - i started searching for working widgets and learned from them. I might have missed the "testing widget outside orange canvas" section.
Also i greatly appreciate the time you spend to educating me on how to build and test new widgets. I hope i can later give something back.

**Comment by astaric** [comment]
Since #2886, any errors during loading of widgets are logged as errors which means they should be always displayed.
