### ISSUE TITLE
Choropleth widget missing

### ISSUE THREAD

**Issue by klonuo** [biolab/orange3#2576]
Hi, 

I use latest Orange git version.

Reading recent blog post: https://blog.biolab.si/2017/08/28/can-we-download-orange-faster/ it seems like there should be choropleth widget, probably in geo addon (I have installed latest 1.8 version), but I don't have such widget.

Any ideas?

Thanks

**Comment by ajdapretnar** [comment]
Would you care to submit this issue to the corresponding Geo add-on? https://github.com/biolab/orange3-geo/issues

**Comment by klonuo** [comment]
Sure.

https://github.com/biolab/orange3-geo/issues/11
