### ISSUE TITLE
Automated testing on python 3.6

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#2585]
Do I understand correctly that Orange is tested on Python 3.4, while Mac bundle uses Python 3.6?

**Comment by astaric** [comment]
Automated tests are run on python 3.4 and 3.5, both on windows (appveyor) and linux (travis).

**Comment by janezd** [comment]
So the issue solved(?) by #2584 wouldn't be detected (even if we actually ran the tests for reports). I think we should either downgrade the python version in the bundle, or test on 3.6.

**Comment by astaric** [comment]
Testing on 3.6 is easy. See #2592

**Comment by astaric** [comment]
Done in #2592
