### ISSUE TITLE
Data Info widget obsolete

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#2587]
Data Info widget is most likely obsolete, since we now have an enhanced File widget + the new status bar is coming up.
Perhaps remove it from the pane for a leaner version.

**Comment by janezd** [comment]
I never use it, but some people (@BlazZupan?) do. It still has some info that won't be included in the status bar.

I'm all for decreasing the number of widgets, but it's a lost cause in the long term. We need tags.
