### ISSUE TITLE
Outliers: Multiple class value error instead of No class value error

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#2588]
##### Orange version

3.5.dev

##### Expected behavior
Outliers returns a correct error message. If there are no class values in the data, it says 'Data missing a class variable'.

##### Actual behavior
Outliers returns 'Multiple class data is not supported.'

##### Steps to reproduce the behavior
File (iris) - Select Columns (move iris to metas) - Outliers.

**Comment by janezd** [comment]
Can't reproduce this exact problem, but Outliers ignore classes.

**Comment by jerneju** [comment]
This can be reproduced in **3.6.0**.  See #2647 .

**Comment by janezd** [comment]
Indeed, but this was a rather superficial fix. Outliers consider only `X` anyway. #2677 does it better.
