### ISSUE TITLE
Errors installing add-ons

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#2600]
I got this in a version checked out from github (I use Python 3.5) and in the macOs bundle. In the former case, I was installing Education and Bioinformatics, in bundle I tried installing Infrared.

<img width="420" alt="screen shot 2017-09-19 at 14 34 37" src="https://user-images.githubusercontent.com/2387315/30611747-de1d1ee0-9d47-11e7-91fc-0f55850ffcac.png">

In the bundle, `pip3 install --upgrade setuptools` solved the problem by upgrading setuptools from 28.8.0 to 36.5.0.

In the checked out version, even pip would no longer execute, so I had to manually patch it with [this](https://github.com/pypa/setuptools/issues/885#issuecomment-307696027).

I'm not sure how to reproduce this. Some of students also got the same error. 

Can we, for a start, upgrade the setuptools in the bundle?

**Comment by markotoplak** [comment]
I got the same error when I installed the Educational add-on from the canvas into my checked-out version (all the other add-ons were installed with pip install -e .). Pip did not execute. When I deleted all traces of the Educational add-on from my site-packages, pip and other python modules started working again.

Then I checked out that add-on and installed it with "pip install -e ." and it worked.
