### ISSUE TITLE
Names of models are not saved as settings

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#2601]
1. Put logistic regression on the canvas.
2. Edit its name
3. Save the schema
4. Close canvas
5. Open Orange and load the schema

The logistic regression name is reverted back to Logistic regression.

--------

The base class for learners sets `self.learner_name = self.name` in `__init__`, where `self.name` is the widgets class attribute `name`, which is set later in the derived classes. So `learner_name = Setting(name)` or `learner_name = Setting(OWWidget.name)` won't work since the name is only defined later. Having `learner_name = Setting("")` would require some magic.

`OWBaseLearner` already has a meta class. This may be the point where the setting can be properly initialized since the `name` is already set then.

**Comment by astaric** [comment]
I opted for `learner_name=Setting(None)` to allow saving of empty names in workflows. See #2608 for details.
