### ISSUE TITLE
Hierarchical: Data output empty when multiple clusters are selected

### ISSUE THREAD

**Issue by astaric** [biolab/orange3#2604]
##### Orange version
latest

##### Expected behavior
When multiple clusters are selected in Hierarchical Clustering Widget, the Data output should not be empty.

##### Actual behavior
Only Selected Data output is present when cut-off is selected.

##### Additional info (worksheets, data, screenshots, ...)

![screen shot 2017-09-20 at 14 42 20](https://user-images.githubusercontent.com/588601/30644250-17f79198-9e12-11e7-9042-8c3fbc86ced5.png)

**Comment by janezd** [comment]
Fixed in #who-know-when-and-not-important-enough-to-try-to-find.

**Comment by janezd** [comment]
It annoyed me, too, though. :)
