### ISSUE TITLE
Label Size in Scatter Plot

### ISSUE THREAD

**Issue by astaric** [biolab/orange3#2605]
##### Orange version
latest

##### Expected behavior
Labels can be enlarged so they can be seen on projector screen/high-res display

**Comment by janezd** [comment]
I agree in principle, but it's hard to implement without adding another option to the widget that is already too large. If we go this path, we'll add too many customization options all around Orange.

**Comment by ajdapretnar** [comment]
Is is possible not to have this customization options fixed, but as a new window or at least hidden somewhere?

**Comment by lanzagar** [comment]
I am not sure if we want to go this path either, but if we do, I would expect this and similar options to be available through a right-click menu on the image area.
I think we can agree that adding them to the widget's controlArea is not a good idea. Possibly this could be a global option (in Orange's settings), which would probably make more sense if it was a single "presentation mode" option that changes several different sizes.

**Comment by markotoplak** [comment]
I agree with @lanzagar about some way to set data independent plot properties that does not take space in control area. One of them could be the label size, the others could hide/show axis names, their sizes, and we will be always able to find something new.

How to do it? I do not know. Maybe as a context menu, maybe as a button in the control panel that opens a dialog/new pane/whatever.

I do not find ta global option relevant.

**Comment by janezd** [comment]
When/If we implement a popup menu on right-click, we can have such settings there. Until then, we won't burden the GUI with this.
