### ISSUE TITLE
Add jittering of 5% and 10 %

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#2606]
2 % turned out to be too small to separate the points in the MDS. Probably in other visualizations, too.

**Comment by jerneju** [comment]
In Scatter Plot it is possible to set jittering up to 10%.

**Comment by jerneju** [comment]
New MDS  (#2448) allows jitter sizes `[0, 0.1, 0.5, 1, 2, 3, 4, 5, 7, 10]` (same as Scatter Plot).
