### ISSUE TITLE
Orange Canvas will not open Mac OS 10.9.5

### ISSUE THREAD

**Issue by umendi** [biolab/orange3#2607]
##### Orange version

I have downloaded the last Orange3 version for Mac (Orange3-3.5.0.dmg)

##### Expected behavior

Installed it as described and tried to open it using right click, open. I expected to have the app GUI opened.

##### Actual behavior

The orange icon appears briefly in the dock, bounce twice, and then disappears. No GUI is loaded. I managed to keep the Orange3 icon on the dock but no matter what I try do to open it, it always automatically closes (meaning it stops bouncing) without providing any system error.

##### Steps to reproduce the behavior

Download the DMG file, open it, move the icon to the Applications folder, navigate to the Applications folder, right click, Open.

I did not have any version of Python installed on this system (which was the issue I read here for another user with Windows 7).

8 GB free on the HD. Tried reinstalling and rebooting as well. 

##### Additional info (worksheets, data, screenshots, ...)

I have tried as well the following with no change. GUI still do not load at all.

https://datascience.stackexchange.com/questions/17375/does-anyone-actually-have-orange-running-on-a-mac-to-test

> The easiest way to install Orange's addons is through the application itself. Open Orange, in the menu click Options -> Addons. In the popup window mark Orange3-Prototypes and click OK. Note, that doing so you will get the latest version that is published on PyPi.

> If you would want to install the bleeding edge version directly from github — assuming that you installed Orange by downloading a bundle from it's website and not for example by using Anaconda — do the following. Open a terminal and paste this command:

> /Applications/Orange3.app/Contents/MacOS/pip install git+https://github.com/biolab/orange3-prototypes.git

> Doing so you will trigger the pip that came with the bundle and instruct it to install the addon directly from github.

> Further, to install opencv, which is required by some widgets (e.g. webcamecapture) run

> /Applications/Orange3.app/Contents/MacOS/pip install opencv-python

> Note, however, that this is unofficial version of opencv but it seems easier to install.

**Comment by astaric** [comment]
Could you run
```
/Applications/Orange3.app/Contents/MacOS/python -m Orange.canvas -l 4
```
and post its output?

**Comment by umendi** [comment]
Thanks for the reply @astaric 

This is what I get now. Note that after installation of the dmg file I have run the following two codes as commented in the post above:
`/Applications/Orange3.app/Contents/MacOS/pip install git+https://github.com/biolab/orange3-prototypes.git
`
and
`/Applications/Orange3.app/Contents/MacOS/pip install opencv-python
`
```
Last login: Thu Sep 21 11:29:09 on ttys000
apples-MacBook-Pro:~ apple$ /Applications/Orange3.app/Contents/MacOS/python -m Orange.canvas -l 4
Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/__init__.py", line 37, in <module>
    from AnyQt.QtCore import QObject
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/AnyQt/QtCore.py", line 247, in <module>
    from PyQt5.QtCore import *
ImportError: dlopen(/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyQt5/QtCore.so, 2): Symbol not found: _LSCopyDefaultApplicationURLForURL
  Referenced from: /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore
  Expected in: /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore
apples-MacBook-Pro:~ apple$ 

```

**Comment by umendi** [comment]
Thanks for your feedback ajdapretnar. Any idea how could I proceed? 

Below is what I get now when I run the codes commented above again. It seems that no error installing those:

`/Applications/Orange3.app/Contents/MacOS/pip install git+https://github.com/biolab/orange3-prototypes.git
`
```
Last login: Thu Sep 21 13:27:28 on ttys000
apples-MacBook-Pro:~ apple$ /Applications/Orange3.app/Contents/MacOS/pip install git+https://github.com/biolab/orange3-prototypes.git
Collecting git+https://github.com/biolab/orange3-prototypes.git
  Cloning https://github.com/biolab/orange3-prototypes.git to /private/var/folders/54/4c9dmg_j39q9jswq5w35fv940000gn/T/pip-2nfknq6q-build
  Requirement already satisfied (use --upgrade to upgrade): Orange3-Prototypes==0.5.1 from git+https://github.com/biolab/orange3-prototypes.git in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Requirement already satisfied: Orange3 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Prototypes==0.5.1)
Requirement already satisfied: numpy in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Prototypes==0.5.1)
Requirement already satisfied: scipy in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Prototypes==0.5.1)
Requirement already satisfied: scikit-learn in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Prototypes==0.5.1)
Requirement already satisfied: pyqtgraph in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Prototypes==0.5.1)
Requirement already satisfied: AnyQt>=0.0.8 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Prototypes==0.5.1)
Requirement already satisfied: serverfiles in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Prototypes==0.5.1)
Requirement already satisfied: docutils in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3->Orange3-Prototypes==0.5.1)
Requirement already satisfied: keyrings.alt in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3->Orange3-Prototypes==0.5.1)
Requirement already satisfied: CommonMark>=0.5.5 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3->Orange3-Prototypes==0.5.1)
Requirement already satisfied: keyring in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3->Orange3-Prototypes==0.5.1)
Requirement already satisfied: bottleneck>=1.0.0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3->Orange3-Prototypes==0.5.1)
Requirement already satisfied: joblib>=0.9.4 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3->Orange3-Prototypes==0.5.1)
Requirement already satisfied: setuptools>=11.3 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3->Orange3-Prototypes==0.5.1)
Requirement already satisfied: xlrd>=0.9.2 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3->Orange3-Prototypes==0.5.1)
Requirement already satisfied: dill in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3->Orange3-Prototypes==0.5.1)
Requirement already satisfied: chardet>=2.3.0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3->Orange3-Prototypes==0.5.1)
Requirement already satisfied: requests>=2.11.1 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from serverfiles->Orange3-Prototypes==0.5.1)
Requirement already satisfied: six in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from keyrings.alt->Orange3->Orange3-Prototypes==0.5.1)
Requirement already satisfied: future in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from CommonMark>=0.5.5->Orange3->Orange3-Prototypes==0.5.1)
Requirement already satisfied: certifi>=2017.4.17 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests>=2.11.1->serverfiles->Orange3-Prototypes==0.5.1)
Requirement already satisfied: idna<2.7,>=2.5 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests>=2.11.1->serverfiles->Orange3-Prototypes==0.5.1)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests>=2.11.1->serverfiles->Orange3-Prototypes==0.5.1)
apples-MacBook-Pro:~ apple$ 
```

And this is what I get when I run the other one:
`/Applications/Orange3.app/Contents/MacOS/pip install opencv-python`

```
Last login: Thu Sep 21 13:40:42 on ttys000
apples-MacBook-Pro:~ apple$ /Applications/Orange3.app/Contents/MacOS/pip install opencv-python
Requirement already satisfied: opencv-python in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Requirement already satisfied: numpy>=1.11.1 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from opencv-python)
apples-MacBook-Pro:~ apple$ 

```

**Comment by astaric** [comment]
I have found this: https://bugreports.qt.io/browse/QTBUG-61800

It seems that Qt 5.9 included in the bundle no longer supports OSX 10.9 or earlier. If updating OSX is not an option, you can still install orange using [ana/miniconda](https://orange.biolab.si/download/#anaconda), which includes qt 5.6.

**Comment by ales-erjavec** [comment]
Try running `/Applications/Orange3.app/Contents/MacOS/pip install PyQt5==5.8.2`

**Comment by umendi** [comment]
Looks like installing and older version as @ales-erjavec suggested worked ok for my OSX 10.9

**Installation:**
`Last login: Thu Sep 21 13:43:02 on ttys000
apples-MacBook-Pro:~ apple$ /Applications/Orange3.app/Contents/MacOS/pip install PyQt5==5.8.2
Collecting PyQt5==5.8.2
  Downloading PyQt5-5.8.2-5.8.0-cp35.cp36.cp37-abi3-macosx_10_6_intel.whl (73.5MB)
    100% |████████████████████████████████| 73.5MB 13kB/s 
Requirement already satisfied: sip<4.20,>=4.19 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from PyQt5==5.8.2)
Installing collected packages: PyQt5
  Found existing installation: PyQt5 5.9
    Uninstalling PyQt5-5.9:
      Successfully uninstalled PyQt5-5.9
Successfully installed PyQt5-5.8.2
apples-MacBook-Pro:~ apple$ `

Now I can open Orange correctly both with the shortcut or running /Applications/Orange3.app/Contents/MacOS/python -m Orange.canvas -l 4

Thanks a lot to the three of you (BTW, I am using Orange in my Supply Chain Management course from MITx).
