### ISSUE TITLE
Cannot read file AdaBoost.svg，because: Encoding iso-8859-1 is unsupported (line 1)

### ISSUE THREAD

**Issue by andrewchenshx** [biolab/orange3#2619]
##### Orange version

3.5.0

##### Expected behavior
no error messages

##### Actual behavior
when invoked from cmdline(python -m Orange.canvas), 
Cannot read file 'C:/Users/Andrew/Anaconda3/lib/site-packages/Orange/widgets/model/icons/AdaBoost.svg', because: Encoding iso-8859-1 is unsupported (line 1)
Cannot read file 'C:/Users/Andrew/Anaconda3/lib/site-packages/Orange/widgets/model/icons/AdaBoost.svg', because: Encoding iso-8859-1 is unsupported (line 1)

##### Steps to reproduce the behavior
1)start anaconda prompt
2)input: python -m Orange.canvas

**Comment by kernc** [comment]
All SVG files should probably define `encoding="utf-8"`.

@andrewchenshx Pull requests are very welcome.
