### ISSUE TITLE
Error loading Geo addin:  OSError: [WinError 126]

### ISSUE THREAD

**Issue by ThirstyGeo** [biolab/orange3#2626]
##### Orange version

3.5.0

##### Expected behavior
Add-in downloading and loading.
This issue has been opened and closed previously
(https://github.com/biolab/orange3-geo/issues/9)

##### Actual behavior
Error received and add-in dialogue box shuts

##### Steps to reproduce the behavior
Attempt to load the 'Geo' add-in

##### Additional info (worksheets, data, screenshots, ...)

Here is the error log:

Collecting Orange3-Geo
  Using cached Orange3-Geo-0.1.8.tar.gz
Requirement already satisfied: Orange3 in c:\users\hoods\appdata\local\orange\lib\site-packages (from Orange3-Geo)
Requirement already satisfied: scikit-learn in c:\users\hoods\appdata\local\orange\lib\site-packages (from Orange3-Geo)
Requirement already satisfied: pandas in c:\users\hoods\appdata\local\orange\lib\site-packages (from Orange3-Geo)
Collecting scipy>=0.17 (from Orange3-Geo)
  Using cached scipy-0.19.1.tar.gz
Collecting shapely (from Orange3-Geo)
  Using cached Shapely-1.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\hoods\AppData\Local\Temp\pip-build-3icadxd6\shapely\setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "C:\Users\hoods\AppData\Local\Temp\pip-build-3icadxd6\shapely\shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos_c.dll")
      File "C:\Python34\lib\ctypes\__init__.py", line 351, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] The specified module could not be found
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\hoods\AppData\Local\Temp\pip-build-3icadxd6\shapely\

**Comment by ajdapretnar** [comment]
Please report add-on errors to appropriate [add-on issue trackers](https://github.com/biolab/orange3-geo/issues). Thank you.

**Comment by ajdapretnar** [comment]
Even more, the error you report is still an open issue there, so you can do a +1 on it.

**Comment by ThirstyGeo** [comment]
Reporting this in the add-on issue trackers. 
Closed
