### ISSUE TITLE
An error occurred while fetching help inventory PyQt5.QtCore.QUrl

### ISSUE THREAD

**Issue by andrewchenshx** [biolab/orange3#2634]
##### Expected behavior
no error messages

##### Actual behavior
(C:\Users\Andrew\Anaconda3\envs\py35) C:\Users\Andrew>python -m Orange.canvas
An error occurred while fetching help inventory 'PyQt5.QtCore.QUrl('http://docs.
orange.biolab.si/3/visual-programming/')'

##### Steps to reproduce the behavior
i work on a win7 system which is behind a proxy. 
input 
`python -m Orange.canvas` in the command line window, then u get the above error messages.

**Comment by diegomcarvalho** [comment]
Same error on a MacOS X 10.12.6, Orange 3.6, Python 3.6.

An error occurred while fetching help inventory 'PyQt5.QtCore.QUrl('http://orange3-geo.readthedocs.io/en/latest/')'

**Comment by ajdapretnar** [comment]
For the latter, the error is nothing major, since this repository doesn't exist yet. I believe the developer just stated it there for... khm, future reference,
