### ISSUE TITLE
Hierarchical Clustering: Buggy visualization

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#2650]
##### Orange version

3.6.0

##### Expected behavior
Hierarchical Clustering shows a dendrogram.

##### Actual behavior
Hierarchical Clustering shows a distorted image (probably for small numbers).

##### Steps to reproduce the behavior
[orange-fb-data.tab.zip](https://github.com/biolab/orange3/files/1355044/orange-fb-data.tab.zip)
Corpus (post_message as text feature) - Preprocess - BoW - Distances (cosine) - HierClust.

##### Additional info (worksheets, data, screenshots, ...)
I thought this was already fixed! 😮 

<img width="963" alt="screen shot 2017-10-04 at 10 19 40" src="https://user-images.githubusercontent.com/12524972/31166166-0c253988-a8ee-11e7-91cb-1babcccfd00a.png">

**Comment by janezd** [comment]
@ajdapretnar, does this still happen?

**Comment by ajdapretnar** [comment]
Yes, yes it does. 😢

**Comment by ajdapretnar** [comment]
Still happening.

**Comment by ajdapretnar** [comment]
Behaviour is ok when I remove datetime variable.

**Comment by janezd** [comment]
#4310 contains a partial fix, but also a comment with the description of the problem's cause. (I'm adding this pointer here for the case that #4310 is merged in its current form.)
