### ISSUE TITLE
Image Embedding: Memory Error

### ISSUE THREAD

**Issue by ThirstyGeo** [biolab/orange3#2653]
##### Orange version

3.6.0

##### Expected behavior
Widget completes processing

##### Actual behavior
Widget gets to ~80% and fails due to a Memory Error

##### Steps to reproduce the behavior
Load a 'moderately sized' directory of images

##### Additional info (worksheets, data, screenshots, ...)
1830 images, 307MB total.

Computer is running:
Windows 10 Pro
Intel i7-6700K CPU @ 4GHz
64 GB RAM total (62 GB available during processing the images)

**Comment by ajdapretnar** [comment]
Please report this to the corresponding [issue tracker](https://github.com/biolab/orange3-imageanalytics/issues).

**Comment by ThirstyGeo** [comment]
Moved to appropriate area

**Comment by kernc** [comment]
Cross-referencing makes it easier to follow up: https://github.com/biolab/orange3-imageanalytics/issues/64
