### ISSUE TITLE
OWDistances: add progress bar

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#2662]
##### Orange version

3.7.dev

##### Expected behavior
Distances display progress bar when computing the matrix.

##### Actual behavior
No progress bar.

##### Steps to reproduce the behavior
Use a large dataset to see how annoying this is. :)

**Comment by janezd** [comment]
A progress bar would either slow the code down considerably, or make it way more complicated. It would also have to be implemented for each distance type separately, hence a lot of work.
