### ISSUE TITLE
OWHierarchialClustering: HC computes sth even once the data is removed

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#2663]
##### Orange version

3.7.dev

##### Expected behavior
Hierarchical Clustering empties instantly once the data input gets disconnected/empty.

##### Actual behavior
Hierarchical Clustering stalls and appears to be computing something even when the input data gets empty (removed).

##### Steps to reproduce the behavior
File (really large data set) - Distances - Hierarchical Clustering. Remove connection before Distances and observe HC.

**Comment by jerneju** [comment]
Widget spends a lot of time clearing all the items.

**Comment by ales-erjavec** [comment]
This is still an issue and can be fixed/improved.
