### ISSUE TITLE
Double title bar of widgets on Mac

### ISSUE THREAD

**Issue by borondics** [biolab/orange3#2672]
##### Orange version

3.7.0.dev0+a85299b

##### Expected behavior
The widget window should show only a single titlebar.

##### Actual behavior
I have a double titlebar of all widgets.

##### Additional info (worksheets, data, screenshots, ...)
![image](https://user-images.githubusercontent.com/6304794/31433800-bd17bd2e-ae7a-11e7-8c06-2b4685cc560f.png)

**Comment by janezd** [comment]
Your Mac must be drunk.

**Comment by borondics** [comment]
In that case it is rather a hangover, but one that is not going away even with reboots :)

**Comment by ajdapretnar** [comment]
Is this still present? I am not experiencing the same behaviour.

**Comment by markotoplak** [comment]
I still saw it the last time I saw @borondics's computer.

**Comment by ajdapretnar** [comment]
What the hell? 😕 How can we reproduce and fix this? Any ideas?

**Comment by borondics** [comment]
I'll reinstall my Mac soon. If it is still there we will try to reproduce
it...

**Comment by ajdapretnar** [comment]
I finally managed to see someone with the same issue!
11-inch Mac, 1.7 GHz Intel Core i5, 4GB RAM, Intel HD Graphics 4000 1536 MB. macOS High Sierrra, v. 10.13.4.
Now at least we have some reference on which computers this happens.

**Comment by borondics** [comment]
Mine is:
MacOSX High Sierra (10.13.5 (17F77))
Model Name: MacBook Pro
  Model Identifier: MacBookPro11,1
  Processor Name: Intel Core i5
  Processor Speed: 2.6 GHz
  Number of Processors: 1
  Total Number of Cores: 2
  L2 Cache (per Core): 256 KB
  L3 Cache: 3 MB
  Memory: 16 GB
  Boot ROM Version: MBP111.0146.B00
  SMC Version (system): 2.16f68


But I have the feeling that it is more configuration specific, not hardware
specific...

**Comment by ajdapretnar** [comment]
Could it be something specific for the 11 inch monitors? 🤔

**Comment by markotoplak** [comment]
The Ferenc's description above probably means Macbook Pro model 11. He has a retina Macbook pro, which are only made in 13 and 15 inch. :)

**Comment by borondics** [comment]
Marko is right, this was a copy-paste of my system report.

**Comment by ajdapretnar** [comment]
Ok, I didn't get that. Nevermind then. 😃
