### ISSUE TITLE
File: Mark modifications in DomainEditor

### ISSUE THREAD

**Issue by astaric** [biolab/orange3#2673]
There is no clear indication whether the header has been modified after the file has been loaded. (in the Columns part of the widget)

The least we could do is to indicate which rows have been modified, either with color or some other indicator (checkbox?). We could also use a Reset button which resets variables to their default values, it should be disabled if no modifications have been made.

Modifications are done manually by the user or restored from settings (when a dataset that has been modified is loaded again).

**Comment by janezd** [comment]
Checkbox is not meant to be an indicator, it's used for input. I'd prefer colors, but these are already used for placement (X, y, meta). Would printing the modified lines in bold help? This should be trivial to implement through a model. It just needs to store the original values and implement the `FontRole` to make the font bold when the values in the models differ from the stored originals.

The Reset button just needs to call `set_domain` again, AFAIK. This part should be in the widget.

**Comment by lanzagar** [comment]
Bold or italics for the whole line could be ok. An asterisk in front of the field that was changed could be another (more specific) option, but might not look as good.
I agree that some sort of an indicator would be welcome. Someone probably needs to try a few different options and see how they look.

**Comment by janezd** [comment]
Mark changed variables with **bold** font.
