### ISSUE TITLE
Status bar: improve icons

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#2676]
While I love the new status bar, I think icons might not be very obvious for a new user. Is there any way we can get better icons (also nicer looking)?

I'd love if @larazupan can help us with that! :)

Current situation:
<img width="102" alt="screen shot 2017-10-12 at 10 03 37" src="https://user-images.githubusercontent.com/12524972/31485591-a9689342-af34-11e7-8efe-f9e245dd73b3.png">

- symbol for help is ok, perhaps just make it less... um, square :)
- clearer symbols for save image and report

If you think current icons are fine, close the issue. @janezd @astaric @BlazZupan

**Comment by janezd** [comment]
+1

**Comment by ajdapretnar** [comment]
Fixed in https://github.com/biolab/orange3/pull/3009.
