### ISSUE TITLE
categorical type of reading excel not clean

### ISSUE THREAD

**Issue by jngai2** [biolab/orange3#2682]
##### Expected behavior
expect clear previous file categorical types 

##### Actual behavior
File read xls, categorical type, 
first round: data has type a,b

change file to read another file has type c,d

it shows  a,b,c,d type in file widget, and subsequent scatter plot also show a,b,c,d type 

but saving the workflow, reopen, it will only have c,d.

suspect categorical internal buffer not clear for reading new file, or reload of file.

**Comment by kernc** [comment]
This is due to compatible variables with the same name and of the same type being reused. In this project developers' opinion, this is the correct behavior.

If you rename the variable in the second File to a different name, it won't be reused.
