### ISSUE TITLE
ScatterPlot Crashes on Data With Infinity Values

### ISSUE THREAD

**Issue by nikicc** [biolab/orange3#2684]
##### Orange version

3.7.0.dev0+8534e2a

##### Expected behavior
ScatterPlot doesn't crash on data with `inf` values.

##### Actual behavior
ScatterPlot crashes with ```Exception: Cannot set range [nan, nan]```

##### Steps to reproduce the behavior
![screen shot 2017-10-16 at 13 23 34](https://user-images.githubusercontent.com/713026/31609723-9cbad512-b275-11e7-8fd9-6250d68e187b.png)

**Comment by nikicc** [comment]
I cannot find the issue on Sentry, hence the link directly to the website: https://qa.orange.biolab.si/errors/Orange.widgets.visualize.owscatterplot/3.7.0.dev0%2B2d08fc6/pyqtgraph.graphicsItems.ViewBox.ViewBox%3A532/2017-10-16T11%3A41%3A16.121273.txt

**Comment by jerneju** [comment]
I got warning that 'X1' is missing for all data points.

**Comment by nikicc** [comment]
Hmmm, strange. I tested it one more time on `Orange3==3.7.0.dev0+445176c` and it still crashes for me with the same error. Did you make all values in a column `inf`? Did you check if all went ok in the Table?

**Comment by jerneju** [comment]
Yes, I made all values in a column `inf`. Everything went ok in the table.

**Comment by jerneju** [comment]
Now I can reproduce this error.
