### ISSUE TITLE
Pickling Error in Select Column on Attributes from Feature Constructor

### ISSUE THREAD

**Issue by nikicc** [biolab/orange3#2686]
##### Expected behavior
In Select Columns, one can move around attributes created in Feature Constructor.

##### Actual behavior
Moving attributes created with Feature Constructor crashes with ```_pickle.PicklingError: Can't pickle <function <lambda> at 0x11b2f3268>: attribute lookup <lambda> on __main__ failed```

##### Steps to reproduce the behavior

![screen shot 2017-10-16 at 15 09 44](https://user-images.githubusercontent.com/713026/31613908-ccf9ab2c-b284-11e7-8209-472443467ee2.png)

##### Additional info (worksheets, data, screenshots, ...)
Probably related to #1758.

**Comment by ajdapretnar** [comment]
I'm not sure this is related to Feature Constructor. I think it happened to me in other cases as well.

**Comment by jerneju** [comment]
Pickling Error occurs here: https://github.com/biolab/orange3/blob/master/Orange/widgets/utils/itemmodels.py#L751

Reason:
https://github.com/biolab/orange3/blob/master/Orange/widgets/data/owfeatureconstructor.py#L936
https://github.com/biolab/orange3/blob/master/Orange/widgets/data/owfeatureconstructor.py#L855

Lambda function in an object added as `compute_value` in a Variable cannot be pickled by `QAbstractItemModel`'s `mimeData` method.

You can also try to pickle `Variable` created by _Feature Constructor_ in _Python Script_ widget. `pickle.dumps(domain[x])` returns `PicklingError`, however `dill.dumps` works ok.

**Comment by kernc** [comment]
We could define `__getstate__` and `__setstate__` upon [`FeatureFunc`](https://github.com/biolab/orange3/blob/707e83ad63c5dc8d6da99031e65aa6a310e79742/Orange/widgets/data/owfeatureconstructor.py#L936) and just pickle the non-lambda arguments the lambda can be reconstructed from.
