### ISSUE TITLE
Small values

### ISSUE THREAD

**Issue by brunap** [biolab/orange3#2692]
##### Orange version
<img width="520" alt="screen shot 2017-10-18 at 11 15 27" src="https://user-images.githubusercontent.com/11367976/31710567-b10c661c-b3f5-11e7-9955-179bcd82d9cd.png">

##### Expected behavior
Small values shall be visible in exp format: e.g. 0.000001 as  1e-6

##### Actual behavior
Value 0.000001 is shown as 0

##### Steps to reproduce the behavior
open attached excel file 

check Data Table 

check Scatter Plot with  show labels

##### Additional info (worksheets, data, screenshots, ...)
[small-numbers.xlsx](https://github.com/biolab/orange3/files/1394064/small-numbers.xlsx)
<img width="1590" alt="scatter-plot" src="https://user-images.githubusercontent.com/11367976/31710704-18784820-b3f6-11e7-906a-11af52af4f33.png">
<img width="1060" alt="data-table" src="https://user-images.githubusercontent.com/11367976/31710710-1bc79a26-b3f6-11e7-956d-54650e38fdce.png">

**Comment by janezd** [comment]
The number of decimals shown equals the number of decimals that Orange encountered in the file from which the variable comes, or 3 (by default) if it doesn't come from a file. Otherwise, it is difficult to guess how many decimals to show and to distinguish between rounding error and actual non-zero values.

As for the format, I don't think that muggles know what is 3.14e-06. Perhaps 3.14⋄10<sup>-6</sup>? It takes same amount of space and people understand it.

**Comment by brunap** [comment]
what shall we do then?

**Comment by ajdapretnar** [comment]
Yes, this was indeed fixed some time ago to non-scientific notation, just to make it more user friendly.
3.14⋄10<sup>-6</sup> is fine with me! 👌

**Comment by kernc** [comment]
Yes, we shall roll our own format! What less can we give our muggles.

https://en.wikipedia.org/wiki/Scientific_notation#E-notation

> Design a system an idiot can use and only an idiot will want to use it.

**Comment by brunap** [comment]
If we change format to 3.14⋄10<sup>-6</sup>, there are also Scatter Plot axis number notations to be changed ...

**Comment by janezd** [comment]
- We have to decide which format to use. Kernc may be right, too. :) And now, looking at 3.14⋄10<sup>-6</sup>, it's a lot of numbers. 3.14e-6 may be easier to read.
- We have to decide how should Orange choose the appropriate format. I will be difficult to work out some universal rules.
-  Implementation would be straightforward for well-behaving widgets that leave formatting to the instance of `Variable`, e.g. the Table widget, I presume. It may be next to impossible for those who use 3rd party visualization libraries.

**Comment by janezd** [comment]
1. Check file readers. Excel file reader could be a problem.
2. If the variable has defined number of decimals (those read from files have it), print out with the given number of decimals -- unless the string is too long (check whether %g is appropriate). If >7, use scientific notation. If the number of decimals is still set to 3 as default, use scientific notation if necessary.
