### ISSUE TITLE
Saving what the widget is showing as data

### ISSUE THREAD

**Issue by borondics** [biolab/orange3#2694]
##### Expected behavior

Sometimes the user would like to save the elements that some visualization in showing for visualization elsewhere. For example, Scatterplot could export a file of coordinates of (jittered) points and their classes. This could also be added to other widgets, such as Box Plot.

With the addition of the Widget status bar it could be nice to move some Widget functionality directly into the Widgets itself instead of using another one for a particular task. For example saving data could be a small icon in the status bar instead of a separate widget. This would make workflows cleaner and smaller and also allow file handling easier, since the save functionality would know where it is called from. As a matter of fact all (three) saving could be done this way instead of widgets...

##### Actual behavior
At this point the "Save Data" widget can receive data from other Widgets and save it in some format selected by the user.

**Comment by markotoplak** [comment]
@astaric and I agree that this would be useful.

**Comment by janezd** [comment]
We discussed this at the Friday meeting. (@markotoplak was absent, but he can always argue and even reopen the issue.) It would be comfortable to have such a button, but:

- it would add another element to GUI, and some widgets are already crowded;
- it would add some functionality (+ 20-30 lines of code) to each widget, which would have to be maintained;
- for many widgets, it is not clear what they would save, or it is ambiguous; I thought about challenging @borondics and @markotoplak to go through the list and specify what each widget would save, but:
- @BlazZupan also commented that he doesn't like going in this direction: each widget should have a distinct function and do well what it does. Saving is a separate functionality for a separate widget.
