### ISSUE TITLE
Scatterplots reports wrong r

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3#2700]
##### Orange version

3.6.0

##### Expected behavior

Instead of the slope, Scatt Plot should display R^2, a [statistical measure](https://en.wikipedia.org/wiki/Coefficient_of_determination) of how close the data are to the fitted regression line.

##### Actual behavior

Scatter Plot displays the slope of the line.

<img width="1034" alt="scatterplot-r-fail" src="https://user-images.githubusercontent.com/726604/31826610-cdd09180-b5b5-11e7-93c9-64e77b53c292.png">

##### Steps to reproduce the behavior

Use Scatter Plot on the data from the following data file:

[scatterplot-r-fail.tab.zip](https://github.com/biolab/orange3/files/1402324/scatterplot-r-fail.tab.zip)

**Comment by jerneju** [comment]
> Best-fit values	 
> Slope	0.02325 ± 0.001349
> Y-intercept	0.4201 ± 0.1362
> X-intercept	-18.07
> 1/Slope	43.00
>  
> 95% Confidence Intervals	 
> Slope	0.02055 to 0.02596
> Y-intercept	0.1469 to 0.6933
> X-intercept	-33.39 to -5.718
>  
> Goodness of Fit	 
> R square	0.8438
> Sy.x	0.4563
>  
> Is slope significantly non-zero?	 
> F	297.0
> DFn,DFd	1,55
> P Value	< 0.0001
> Deviation from horizontal?	Significant
>  
> Data	 
> Number of XY pairs	57
> Equation	Y = 0.02325*X + 0.4201
>
