### ISSUE TITLE
Orange starting issues on RHEL6 Server

### ISSUE THREAD

**Issue by vudisai** [biolab/orange3#2702]
Hello,
Installed orange on RHEL6 but throwing these errors.
 **python -m Orange.canvas
QXcbConnection: Could not connect to display
Aborted (core dumped)**

**Comment by kernc** [comment]
Please try:
```bash
DISPLAY=:0 python -m Orange.canvas
```
What Qt and Python version?
```bash
python -m pip freeze
```

**Comment by kernc** [comment]
Please try:
```bash
DISPLAY=:0 python -m Orange.canvas
```
What Qt and Python version?
```bash
python -m pip freeze
```

**Comment by vudisai** [comment]
**DISPLAY=:0 python -m Orange.canvas
QXcbConnection: Could not connect to display :0
Aborted (core dumped)**
**Versions**
QtAwesome==0.4.4
qtconsole==4.3.0
QtPy==1.2.1

Python 3.6.3 :: Anaconda custom (64-bit)

**Comment by kernc** [comment]
Limited answer, limited support. Are you on Wayland perhaps?

**Comment by vudisai** [comment]
Sorry was in different work and was unable to elaborate issue.Yes I am on wayland.

**Comment by kernc** [comment]
Orange has not yet been tested on Wayland. Try xwayland? Feel free to [investigate](https://www.google.com/search?q=qt+wayland). Pull requests / ideas welcome.

**Comment by vudisai** [comment]
Yea.Sure thank you.

**Comment by kernc** [comment]
If your Qt5 was built with Wayland support, try:
```bash
python -m Orange.canvas --qt='-platform wayland'
```

**Comment by ajdapretnar** [comment]
Any news on this?
