### ISSUE TITLE
Saving Report to PDF Crashes

### ISSUE THREAD

**Issue by nikicc** [biolab/orange3#2708]
##### Orange version

3.7.0.dev0+445176c

##### Expected behavior
One can save the report to PDF.

##### Actual behavior
Orange crashes with `AttributeError: 'WebviewWidget' object has no attribute 'print_'`.

##### Steps to reproduce the behavior
![screen shot 2017-10-24 at 11 55 52](https://user-images.githubusercontent.com/713026/31936594-4fab86e8-b8b2-11e7-9bf4-2e554d0c6693.png)

**Comment by jerneju** [comment]
What happens when you write this in a Python console:
`from Orange.widgets.utils.webview import WebviewWidget`

**Comment by nikicc** [comment]
```
>>> from Orange.widgets.utils.webview import WebviewWidget
>>> from AnyQt.QtWebKitWidgets import QWebView
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/Niko/PyCharmProjects/virtual-envs/orange3-ve/lib/python3.6/site-packages/AnyQt/QtWebKitWidgets.py", line 14, in <module>
    from PyQt5.QtWebKitWidgets import *
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'
>>> 
```
