### ISSUE TITLE
Problem with miniconda installer

### ISSUE THREAD

**Issue by KuberV** [biolab/orange3#2711]
##### Orange version

 I installed Orange3-3.6.0-Miniconda-x86_64.exe version as I have 64-bit Windows 8, but was not able to successfully deploy logistic model.

**Comment by ajdapretnar** [comment]
Please elaborate on the issue as suggested in the issue template. A screenshot of the error would be valuable.

**Comment by ajdapretnar** [comment]
Closing due to lack of response from OP.
