### ISSUE TITLE
Ability to interact with the terminal from a python script widget?

### ISSUE THREAD

**Issue by Bowiemb** [biolab/orange3#2713]
Apologize if there's a better place to post this question. 

Is there a way to interact with the local terminal / bash from the python script widget?

I would love to call some OpenRefine functions inside the python widget in the middle of a workflow, mainly for data cleaning purposes.

Thank you for any advice. 

My best,
Michael

**Comment by kernc** [comment]
You could always [`import subprocess`](https://docs.python.org/3/library/subprocess.html#subprocess.Popen)?

**Comment by Bowiemb** [comment]
That's more convoluted than what I was hoping for, but that may work. Thank you!
