### ISSUE TITLE
Remove column metadata when saving .csv

### ISSUE THREAD

**Issue by mstrazar** [biolab/orange3#2717]
The metadata columns when storing .csv are a pain in my case, as I have to manually remove
rows 2 and 3 each time I want to re-use the .csv in Orange or other software. Do we agree these
could be removed?

    Mean,Variance,Dispersion,CV,Feature
    continuous,continuous,continuous,continuous,string
    ,,,,meta
    15.5751916218,0.76979502127,0.049424433417,0.0563318676775,ENSG00000228253.1
    14.2245580669,0.438983177545,0.0308609360994,0.0465784633072,ENSG00000198899.2

**Comment by janezd** [comment]
Fixed in #3427
