### ISSUE TITLE
Wide range zoom on Canvas

### ISSUE THREAD

**Issue by borondics** [biolab/orange3#2722]
##### Orange version

all versions

##### Expected behavior
Could we have a continuous zoom (within some reasonable limits of course) on the Canvas? Some of our workflows (especially those in OASYS) are pretty large and this would make life easier. The most useful part of this, therefore, would be to zoom out and see the big picture.

##### Actual behavior
There is a two-level zoom which actually zooms in, but not out.

**Comment by janezd** [comment]
Done, long ago, right?
