### ISSUE TITLE
Allow custom (generic) names in Transpose Widget

### ISSUE THREAD

**Issue by astaric** [biolab/orange3#2729]
When I transpose a dataset with no meta attributes, I end up with variables named Feature 1, Feature 2, Feature 3, ...
It would be nice if I could specify my own prefix (such as User, Transaction, Cell, House, ...).

The text box with the prefix (the default can stay Feature, although I would vote for Row) could be placed below the Generic options, the way variable combo is placed below the From meta attribute option.
![screen shot 2017-11-02 at 11 09 31](https://user-images.githubusercontent.com/588601/32320544-5f62aeaa-bfbe-11e7-9e16-e7bc03cdf5c5.png)

**Comment by janezd** [comment]
+1 for Row.
