### ISSUE TITLE
Can`t get map when using Geo Map

### ISSUE THREAD

**Issue by Caoxiann** [biolab/orange3#2731]
##### Orange version

3.7

##### Expected behavior
Geo Map should show the map of the world.

##### Actual behavior
Can`t see anything of map when using Geo Map.
![image](https://user-images.githubusercontent.com/16267304/32323861-64add682-c004-11e7-91a5-f7c0cace0da6.png)

##### Steps to reproduce the behavior
Just start Orange and open a Geo map.

##### Additional info (worksheets, data, screenshots, ...)
My OS is ubuntu 16.10 and my python version is 3.5.2.
My PyQt version is 5.9.
I got two warnings when I start Orange:
qt.network.ssl: QSslSocket: cannot resolve SSLv2_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv2_server_method

And I got more warning when I start Geo Map:
![image](https://user-images.githubusercontent.com/16267304/32324016-d7c5ca6c-c004-11e7-9d3b-78f68b128c5e.png)

I guess that something about openssl goes wrong.
How can I fix this and get the map in Geo Map?

**Comment by kernc** [comment]
Does [this](https://stackoverflow.com/a/46618227/1090455) work, i.e. installing this [package](https://packages.ubuntu.com/trusty/amd64/libssl0.9.8/download)?

Can you confirm this is PyQt5.9; please dump `python3 -m pip freeze`.

Can you re-run as `python3 -m Orange.canvas -l 4`.

If you open the debug-printed link http://127.0.0.1:12088 in **Chromium** browser, and click on the running Map session, are there any errors in the console?

Thanks.

**Comment by astaric** [comment]
Since map widget was removed from core, I am closing this issue. Any further problems with map widget can be opened on the [orange3-geo](https://github.com/biolab/orange3-geo/issues) issue tracker.
