### ISSUE TITLE
[Feature Request]: Add options for 0,1 and -1,1 normalization in Preprocess

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#2739]
##### Feature
Add options to normalize to range [0,1] or [-1,1].

##### Use case
Great for comparing values in Timeseries add-on, e.g. when plotting two attributes against one another in Line Chart.
With current preprocessing:
<img width="727" alt="screen shot 2017-11-03 at 14 57 13" src="https://user-images.githubusercontent.com/12524972/32377256-4cc6983a-c0a7-11e7-8ae0-f332cb007d37.png">

Ideally, both attributes would be scaled to 0,1.

**Comment by kernc** [comment]
You want something like `Preprocess > Normalize > Scale by span` in this widget, with options for no scaling, or scaling to [0, 1] or [-1, 1]?

**Comment by ajdapretnar** [comment]
Scaling to [0, 1] or [-1, 1].

Current preprocessing doesn't allow comparing peaks in timeseries in case you want to align these. It's a bit off with scale by span.

**Comment by kernc** [comment]
Right, was just checking.

Out of scope for the widget, wont fix.

**Comment by kernc** [comment]
`Preprocess > Normalize > Scale by span` should scale you to [0, 1].

**Comment by ajdapretnar** [comment]
<img width="545" alt="screen shot 2017-11-03 at 16 52 48" src="https://user-images.githubusercontent.com/12524972/32383145-766fa2a2-c0b7-11e7-9ee5-d7107212d989.png">

How again is this scaled to [0,1]?

I have checked the procedure before with @lanzagar and @astaric and it was confirmed this is not yet implemented. This is an ORC, however you want to call it. No need to close it.
