### ISSUE TITLE
[ENH] Canvas option for visually impaired

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#2749]
##### Orange version
3.8.dev

##### Expected behavior
The user can set the canvas to colors for visually impaired.

##### Actual behavior
The user is limited to white canvas.

##### Additional info (worksheets, data, screenshots, ...)
Request from LBS. Would be nice to switch to a view for [visually impaired](https://webdesign.tutsplus.com/articles/accessibility-basics-designing-for-visual-impairment--cms-27634).

**Comment by janezd** [comment]
@ajdapretnar, what does this issue involve? It sounds like it's about changing the canvas background, but it's probably (more) about palettes? Will this thus be resolved within #1924 by adding some appropriate palettes?

I guess Orange already uses colors just for aesthetics and doesn't actually encode any information (except, say error vs. info, but they also use different icons).

**Comment by irgolic** [comment]
A great accessibility option, which might also be useful for exporting visualizations, is larger font sizes.

Colors-wise, we could design a couple different palettes for different types of color blindness.

<img width="721" alt="Screenshot 2019-12-27 at 23 17 53" src="https://user-images.githubusercontent.com/24586651/71534439-c2979000-28f6-11ea-971c-d218504e5764.png">
https://www.color-blindness.com/types-of-color-blindness/

The most common variants of color blindness are forms of protanopia (missing/malfunctioning red cone) and deuteranopia (missing/malfunctioning green cone).

![1200px-Cone-fundamentals-with-srgb-spectrum svg](https://user-images.githubusercontent.com/24586651/71534354-32f1e180-28f6-11ea-8405-c061b30b5fbf.png)

As the two cones preceive similar wavelengths of light, one color palette can catch both.

![color-blind-friendly-palette-12](https://user-images.githubusercontent.com/24586651/71534415-9714a580-28f6-11ea-9ce5-cb33537ce087.png)
https://venngage.com/blog/color-blind-friendly-palette/

To assist people with two or three missing/malfunctioning cones, you turn to monochromatic color schemes (single hue color schemes). Does Orange use opacity in visualizations? If so, this isn't viable.

Alternatively, something like this?
<img width="656" alt="Screenshot 2019-12-27 at 23 06 51" src="https://user-images.githubusercontent.com/24586651/71534219-38026100-28f5-11ea-80ac-bd1767a11c78.png">
https://webdesign.tutsplus.com/articles/accessibility-basics-designing-for-visual-impairment--cms-27634

**Comment by ajdapretnar** [comment]
Yes, this request does not mean only options for color blind, but also for people who generally don't see well. OS systems offer high contrast options and larger fonts. At the workshop we had a person who wanted dark mode, because white was too bright for him, and I think now there's already an option for that. I think...

**Comment by janezd** [comment]
- **High contrast and larger fonts:** these are controlled by OS and they work; nothing to do here.

- **Palettes** should be handled as part of #1924.

- **Dark mode:** I don't see it. Mac has an accessibility option to invert colors, which works. I suppose similar options exist in other systems, too. 

    Qt seems to support dark mode, but Orange doesn't switch. I don't know how much work this would involve. @ales-erjavec? 

Unless there are other ideas particularly related to Orange, I would open an issue in the canvas repository to support dark mode (or to add any specific accessibility features in the canvas), and close this issue here.

**Comment by janezd** [comment]
Continued in #1924 and https://github.com/biolab/orange-canvas-core/issues/67.
