### ISSUE TITLE
[QUESTION] How to import dataset from csv (Orange 3.7, Python 3.5)

### ISSUE THREAD

**Issue by gtzinos** [biolab/orange3#2768]
Orange Version: 3.7.0
Python Version: 3.5

Hi all,

I am using your great library some days ago and i facing an issue with import data. All working great when i use your existing datasets but when i am trying to use a custom csv file then your classifiers throws errors. Lets give an example (* Dataset: [wdbc.csv.tar.gz](https://github.com/biolab/orange3/files/1463527/wdbc.csv.tar.gz)):

```
import Orange

# load the dataset from csv file
dataset = Orange.data.Table('./wdbc.csv')

print(dataset)

# Define CN2 Learner
learner = Orange.classification.CN2Learner()


# Train learner
classifier = learner(dataset)

# Cross validating results
res = Orange.evaluation.testing.CrossValidation(dataset, [learner], k=5)
```

When i execute the code it throws this exception:
```

File "/usr/local/lib/python3.5/dist-packages/Orange/base.py", line 105, in __call__
    raise ValueError(self.learner_adequacy_err_msg)
ValueError: Discrete class variable expected.
```

**Comment by kernc** [comment]
Loaded like this, I don't think your `dataset` has a class variable set. Confirm with `assert dataset.class_var is None`.

Add a [one](https://orange-visual-programming.readthedocs.io/loading-your-data/index.html#header-with-attribute-type-information) or [three-line header](https://orange-visual-programming.readthedocs.io/loading-your-data/index.html#three-row-header-format) to your CSV, marking the first column as ignored and the second column as class.

**Comment by gtzinos** [comment]
Great thanks!
