### ISSUE TITLE
Data contains a single target value

### ISSUE THREAD

**Issue by darjusp** [biolab/orange3#2770]
##### Orange version

3.7.0

##### Expected behavior
Hi guys,
Tried to make a regression based on selected target variable. In this case it was numeric, but tried with others, was the same result.

##### Actual behavior
Throws an error - data contains a single target value, and doesn't produce any output. Any ideas what can be done?

##### Steps to reproduce the behavior
I used adults.tab data from the Orange3 package.

##### Additional info (worksheets, data, screenshots, ...)
![class_slides_9](https://user-images.githubusercontent.com/10597360/32690147-42be2142-c6fa-11e7-9d7a-887c28d54e54.jpg)

**Comment by kernc** [comment]
You should omit Data Table widget. This widget passes on just its selection, and you likely had selected just a single row, or a couple of rows of the same class.

**Comment by darjusp** [comment]
Yeap, my stupidity. Thanks a lot for explaining how the widget works
