### ISSUE TITLE
Edit Domain destroys datetime format

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#2776]
##### Orange version

3.8.dev

##### Expected behavior
Edit Domain retains the set datetime iso format, e.g. 2017-11-14 12:12.

##### Actual behavior
Edit Domain converts datetime to floats, creating a mess downstream.

##### Steps to reproduce the behavior
Use on any datetime data set.

<img width="305" alt="screen shot 2017-11-14 at 13 40 05" src="https://user-images.githubusercontent.com/12524972/32780509-c71245ce-c941-11e7-83dc-1a4dfe2a3932.png">

##### Additional info (worksheets, data, screenshots, ...)

Original data
<img width="590" alt="screen shot 2017-11-14 at 13 39 49" src="https://user-images.githubusercontent.com/12524972/32780516-d35c4ef6-c941-11e7-8cb5-d29a5f586a09.png">

After Edit Domain
<img width="608" alt="screen shot 2017-11-14 at 13 39 57" src="https://user-images.githubusercontent.com/12524972/32780527-dd4341e0-c941-11e7-9f55-646e701440e9.png">

**Comment by astaric** [comment]
This requires creating a custom TimeVariableEditor that copies have_date and have_time to the new variable in `get_data`, as well as modifying `variable_description` and `variable_from_description` to be able to serialize and deserialize TimeVariables with their corresponding have_date/have_time options.

bonus points for being able to modify the format used to display date/time.
