### ISSUE TITLE
Scatter Plot: variable values which are not in a data are shown

### ISSUE THREAD

**Issue by jerneju** [biolab/orange3#2783]
##### Orange version
Probably all versions since **3.3.12** or even before.

##### Expected behavior
Maybe variable values which are not in a data should not be shown.

##### Actual behavior
In **Data Table** widget only data with _Iris-setosa_ and _Iris-versicolor_ are selected. However **Scatter Plot** shows also _Iris-virginica_ in a legend.

##### Additional info (worksheets, data, screenshots, ...)
![screenshot_20171117_140349](https://user-images.githubusercontent.com/22157215/32948643-4bc7ea70-cba0-11e7-83e0-764423882cff.png)

**Comment by ajdapretnar** [comment]
@astaric I am still confused whether this is a feature or a bug. 🙈 Is this not similar to #3094?
