### ISSUE TITLE
DOC: File widget doesn't have Import Options

### ISSUE THREAD

**Issue by diroru** [biolab/orange3#2785]
##### Expected behavior
In the Orange GUI, I would like to set the delimiter for a file to be imported. The documentation mentions **import options** here: https://docs.orange.biolab.si/3/visual-programming/widgets/data/file.html

##### Actual behavior
I could not find **import options** for the `file widget` in any menu.

##### Steps to reproduce the behavior
Make an empty project, create a new file widget.

**Comment by kernc** [comment]
These options are not. Edit the file in a outside editor and reload.

Curious, what file / separator are you working with?

**Comment by diroru** [comment]
Thank you very much for the swift reply!

The problem with the file was, that it had `.csv` as extension, but was tab-separated. After renaming it to `.tsv` everything worked fine!

Many thanks again, also for the great tool!

**Comment by diroru** [comment]
It is a “hand-coded” (i.e. library-less) result of a web-scraping. I think the issue is, that there are some commata inside columns with String-value, which apparently leads to the generation of additional columns.

![Screenshot from OS X Finder’s preview](http://dimitarruszev.com/misc/issues/orange/finder.png)

![atom with tablr plugin gets it right](http://dimitarruszev.com/misc/issues/orange/atom.png)

[Original data](http://dimitarruszev.com/misc/issues/orange/171116_asn_data_working.csv)

Many thanks for looking into this!

**Comment by kernc** [comment]
Thanks! Do you mind if we maybe retain (and thus redistribute) a couple of lines as a test case (as in https://github.com/biolab/orange3/pull/2791)? In future versions, loading a dataset like this one should hopefully work out-of-the-box. 🤞

**Comment by diroru** [comment]
Of course, no problem!

**Comment by ajdapretnar** [comment]
Considering #2791, I am closing the issue. Docs should now be in line with existing options.
