### ISSUE TITLE
Table.from_numpy crashes on Inf values

### ISSUE THREAD

**Issue by nikicc** [biolab/orange3#2788]
##### Orange version

3.8.0.dev0+301d13a

##### Expected behavior
One can create `Table` with `from_numpy` that contains infinity values.

##### Actual behavior
ValueError `Array contains infinity.` is raised in `_check_arrays`, not really sure why.

##### Steps to reproduce the behavior
Pass numpy array with inf values to `Table.from_numpy`

**Comment by astaric** [comment]
Do we really want to allow inf values in X/Y? IMHO they should be converted to nan (=unknowns) before the table is constructed.

**Comment by janezd** [comment]
I agree with @astaric. A table with inf values is a corrupted table.

**Comment by nikicc** [comment]
When calculating new features out of existing ones, `np.inf` is not really the same as `np.nan`.

But if we don't support them, I will convert them to `np.nan`.

**Comment by nikicc** [comment]
An argument for this is that ScatterPlot seems to be handling `inf` values (https://github.com/biolab/orange3/pull/2709).

**Comment by ajdapretnar** [comment]
This need to be resolved. I vote for converting inf to nan. @lanzagar @BlazZupan if you agree, let us propose a solution so someone can implement this.

**Comment by lanzagar** [comment]
I don't see enough benefit in supporting inf values for the amount of problems I expect we would encounter in various widgets, at least for now.
I think converting to nan is the most practical solution.
