### ISSUE TITLE
Scatter Plot: selection is not working with very high feature values

### ISSUE THREAD

**Issue by brunap** [biolab/orange3#2789]
##### Orange version
3.8.0.dev0+301d13a

##### Expected behavior
If a feature value is much higher than the rest of the data, scatter plot shall perform normally.

##### Actual behavior
If a feature value is much higher than the rest of the data, scatter plot does not allow point selection. Mouse rectangle selection is also not working ok (e.g. in my two instances dataset if I select the instance with the extra-high value with rectangle, the second instance is selected :) ).

##### Steps to reproduce the behaviour

Load attached data, go with them to Scatter Plot, try to select data

##### Additional info (worksheets, data, screenshots, ...)
![screen shot 2017-11-21 at 17 19 06](https://user-images.githubusercontent.com/11367976/33083610-2077b8bc-cee0-11e7-8b0e-9221e6a0bf8e.png)

[data.xlsx](https://github.com/biolab/orange3/files/1492119/data.xlsx)

**Comment by janezd** [comment]
The problem occurs when the transformation matrix (from data coordinate system to view) has very large floats. The problem can be replicated by zooming out the graph for any data to around 1e+15.

Mouse coordinates are transformed to data coordinates by Qt's `mapRectToParent`, which calls `QTransform.invert`. `QTransform.invert` has floating-point instabilities (see https://github.com/pyqtgraph/pyqtgraph/blob/develop/pyqtgraph/functions.py#L2295) and in such cases returns an identity matrix (and an error flag, which is not propagated). Hence the coordinates are left untransformed, selection rectangle is not shown and data is not selected.
