### ISSUE TITLE
Code Climate does not work

### ISSUE THREAD

**Issue by jerneju** [biolab/orange3#2795]
##### Expected behavior
Code Climate should produce report.

##### Actual behavior

> Invalid .codeclimate.yml configuration fileView the build
> C12 ERROR
> Please see the codeclimate validate-config step below for more details.
> 
> Here are some ways you might troubleshoot this problem:
> 
> Use our CLI to validate or generate your configuration locally.
> Read our documentation for more information about the .codeclimate.ymlformat.
> codeclimate validate-config
> ERROR: 'exclude_paths' must be one of array, string
> WARNING: engine duplication: 'exclude_paths' has been deprecated, please use 'exclude_patterns' instead
> WARNING: 'engines' has been deprecated, please use 'plugins' instead
> WARNING: 'exclude_paths' has been deprecated, please use 'exclude_patterns' instead
> WARNING: 'ratings' has been deprecated, and will not be used

**Comment by astaric** [comment]
Code climate is no longer enabled on this repository.
