### ISSUE TITLE
Unable to find scatter map

### ISSUE THREAD

**Issue by mrn-aglic** [biolab/orange3#2798]
I checked the [widget catalog](https://orange.biolab.si/toolbox/) for scatter map, and it is displayed there under visualize. However, I am unable to find the said widget in Orange 3.4 on Mac, nor Orange 3.7 on windows... has the widget been removed?  

If the widget was removed, is there any way I can get a link to download Orange 3.3?

**Comment by kernc** [comment]
The widget was removed in https://github.com/biolab/orange3/pull/1985. Still available in [Prototypes](https://github.com/biolab/orange3-prototypes/) [Orange add-on](https://www.youtube.com/watch?v=OANsA6fMJKg).
