### ISSUE TITLE
Port or implement widget for training neural networks

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#28]

**Comment by akors** [comment]
Hi! What's the status on the Neural Network Widget? I wanted to use Orange3 for data analysis, but a lot of widgets are missing.

Are there still plans to port those from Orange 2?

**Comment by janezd** [comment]
Yes, there are still quite a few widgets that haven't been ported yet. We don't wish to port without some maintenance, redesign, refactoring... Everything that was useful in Orange 2 will be ported eventually, and neural networks are still on the list, of course.

If you miss some specific widgets from Orange 2, you can perhaps stay with Orange 2 for now.

**Comment by akors** [comment]
Thank you, I will use Orange 2 for now. I wish you success with porting!

**Comment by janezd** [comment]
Closing this issue. It is one of the topics for GSoC 2016.

**Comment by akors** [comment]
Why close it now? You can close it after the Summer student ;)

I am happy to help with some Testing, if you need it.

p.s.: congratulations on getting GSoC student!

**Comment by janezd** [comment]
You're right. :)

**Comment by ajdapretnar** [comment]
@janezd Since we're not doing it for GSoC and since NN are out of scope of Orange as we discussed on several occasions, can we close the isssue?

**Comment by janezd** [comment]
Yes, IMHO.

Let issues be about things that need and will be done, not about wishes and plans.

**Comment by ajdapretnar** [comment]
Agree 100%.

**Comment by kernc** [comment]
I object to your inexperience and absolute incompetence in deciding about this matter.

**Comment by ajdapretnar** [comment]
You're a bully. Stop it.

**Comment by janezd** [comment]
@kernc, I disapprove of what you say w.r.t. what belongs to issues, but I will defend to the death your right to say it. Not in this manner, though. ;)

I would really appreciate it if we treat each other with respect we deserve. @ajdapretnar is one of the most capable and multi-talented people I know. A true renaissance woman. :) There are also other bright programmers in the team (you very included), which do not deserve being publicly degraded when they make (or seem to have made) a mistake.

Since I always value your opinion a lot, I will also try to see the purpose of the issue list from your perspective. But please do not consider those who want to use the list differently as incompetent.

**Comment by ajdapretnar** [comment]
Closed via #2553.
