### ISSUE TITLE
Add Self-Organizing Maps (SOM) widget

### ISSUE THREAD

**Issue by hikea** [biolab/orange3#2800]
##### Orange version

Version: 3.7.1

##### Expected behavior

Self-organizing maps add-on/widget is not present in Orange3. I used to use it in Orange2.7. Are there any plans to get it back? How easy it is to port it from the old version?

##### Actual behavior

Would be great to have SOM add-on back!

##### Steps to reproduce the behavior

N/A

##### Additional info (worksheets, data, screenshots, ...)

N/A

**Comment by ThirstyGeo** [comment]
It would definitely be good to bring it back!
I wonder how hard it would be to port the code over to a new widget?

**Comment by ajdapretnar** [comment]
@ThirstyGeo I have no idea how hard, objectively, it would be to port it, but there's code in [orange2 repository](https://github.com/biolab/orange/blob/master/Orange/projection/som.py), there are [instructions on porting widgets](https://github.com/biolab/orange3/wiki/Porting-Orange2-widgets-to-Orange3) and we are always happy to review and comment the code. If you are up for the challenge, we can offer you an Orange T-shirt in return. 😉

**Comment by saudalwasly** [comment]
me too, I came to a point where I needed the Self-Organizing Maps (SOM) widget in Orange3.

**Comment by ThirstyGeo** [comment]
@ajdapretnar Oooooooo! I'm not a talented programmer, but I will have to give it a go - I'd probably be the only guy at the university with a Biolabs Orange T-shirt

**Comment by ajdapretnar** [comment]
There's a great team that can help, so fret not! :) Write to our Biolab contact and let us know your address so we can send the T-shirt!

**Comment by janezd** [comment]
Closed via #3928.
