### ISSUE TITLE
About normalization

### ISSUE THREAD

**Issue by rmvaliev** [biolab/orange3#2816]
Dear team

To imporve results of dataminig one of recommendation is data normalization. 
We should normalize training data (for example by mean and SD) and after that also normalize test data using same mean and SD as was used for training data.
But at present I dont see any tools/settings to save mean/SD for training data and any option to enter these saveed values to process of normalization of test data.

##### Expected behavior
Feature to save normalization process parameters (for example mean/SD)
Feature to allow specify saved parameters to process of normalization of test data.

##### Actual behavior

No any feature to save and reuse normalization parameters.

**Comment by kernc** [comment]
The normalization parameters are saved as properties of the transformed data domain. Whenever you use new (test) data with the transformed training data, the transformation of the test data happens automatically.
![screenshot_2017-12-02_19-06-02](https://user-images.githubusercontent.com/684364/33518357-f54e3b04-d793-11e7-880a-8ff6e37a0cac.png)
