### ISSUE TITLE
Miniconda Installer (Windows) - handle missing/corrupted Anaconda installation

### ISSUE THREAD

**Issue by obarak** [biolab/orange3#2826]
##### Orange version
3.8-Win64 (Installer file name is Orange3-3.8.0-Miniconda-x86_64.exe)

##### Actual behavior:
1. I've downloaded and ran the Miniconda installer. 
2. Installer detected that I already have Anaconda installed. Installation continued and completed with no error messages. Only that...
3. ...Orange wouldn't start (nothing happens when clicking on the shortcut).
4. Making a long story short - turns out I had *two* Anacondas installed on my machine: 
    - An old one that was completely removed from everywhere except for the Windows Registry (there were no physical files on disk). That was the one Orange installer tried to use.
    - A new one, working perfectly, but undetected by the installer.
5. Turns out that corrupted Anaconda installations on Windows are actually [quite common](https://stackoverflow.com/questions/29337928/how-to-remove-anaconda-from-windows-completely/45360960#45360960), due to Anaconda's broken uninstaller and backward incompatibility issues.
6. Examining the Orange installer log revealed the following lines:  

```
Creating a conda env in "C:\Users\obarak\AppData\Local\Orange"
The system cannot find the path specified.
```
Last line is an error but, again, it didn't cause any error message to appear.
7. Removing the orphaned Anaconda registry key and then re-installing solved the issue.

##### Expected behavior:
Ideally, if the installer can't find the ```conda.exe``` file it needs for installation, it will try other Anacondas available on the machine (if exist), and finally revert to installing Miniconda from scratch.
Less ideal, but still good - show an error to the user and cancel installation.

**Comment by astaric** [comment]
The installers were modified in #2827 to do a basic validation of the conda environment (they check for presence of python and conda executable). If they are not found, a new miniconda installation is forced (not ideal, but should avoid the error)

The new installers will be built when 3.9 is released (probably later this month).
