### ISSUE TITLE
Orange 3.8 Huge Fonts and graphics on Windows 10 4k hidpi laptop

### ISSUE THREAD

**Issue by hermandr** [biolab/orange3#2832]
##### Orange version

Orange 3.8

##### Expected behavior
Normal screen and display of Orange

##### Actual behavior
The screenshots below covers the entire 4k screen.

![screen shot 12-17-17 at 10 34 am 001](https://user-images.githubusercontent.com/10177608/34076092-ea1b7156-e315-11e7-8a2a-0af17970883f.JPG)
![screen shot 12-17-17 at 10 17 am](https://user-images.githubusercontent.com/10177608/34076095-f0e5c96e-e315-11e7-9793-37bc00cc292b.JPG)
![screen shot 12-17-17 at 10 34 am](https://user-images.githubusercontent.com/10177608/34076096-f6bd394e-e315-11e7-804f-04e1a9fe2269.JPG)

##### Steps to reproduce the behavior
Double click on Orange icon to launch Orange 3.8

"C:\Program Files\Orange\pythonw.exe" -m Orange.canvas
![image](https://user-images.githubusercontent.com/10177608/34076106-367da2ee-e316-11e7-8cfa-b8aac36dd935.png)

**Comment by loekiedepo** [comment]
Do you perhaps have zooming enabled? (right click on Desktop > Display Preferences). 4k usually comes with a 250% zoom default in Windows. I have mine at 200% and Orange seems to work fine.

**Comment by hermandr** [comment]
I have set zooming to 100% and my desktop is really tiny but Orange is
correct size.
Any other suggestion?
Thank you for your time.

Regards,
Herman

**Comment by ajdapretnar** [comment]
My Orange on 4k screen with Win looks ok, but I remember there being some issues on smaller screens. However, usually it was the opposite - the icons were too small.
Perhaps @acopar will know how to handle this?

**Comment by acopar** [comment]
I recall this issue on older Qt4 versions when combined with touchscreen or hidpi laptop screens. Recent versions of Qt have better support for hidpi:
http://doc.qt.io/qt-5/highdpi.html

Use orange miniconda installer and update to the latest pyqt version (which will also upgrade qt as a dependency):
C:\Program Files\Orange\Scripts\conda.bat install pyqt
or
C:\Program Files\Orange\Scripts\conda.bat update pyqt

**Comment by markotoplak** [comment]
@acopar this also happened on a Win 10 miniconda install (so with Qt5) that a guest had in the lab this week. So upgrading Qt would not help.

**Comment by hermandr** [comment]
Hi,

I have tried to update using
Use orange miniconda installer and update to the latest pyqt version (which
will also upgrade qt as a dependency):
C:\Program Files\Orange\Scripts\conda.bat install pyqt
or
C:\Program Files\Orange\Scripts\conda.bat update pyqt

the result is the same, no change.

**Comment by ales-erjavec** [comment]
Which scaling level do you have set? Qt5 does not handle non integer scale factors well [QTBUG-65061](https://bugreports.qt.io/browse/QTBUG-65061),  https://bugzilla.redhat.com/show_bug.cgi?id=1381828

Still the discrepancy looks too big.

Do you by any chance have `QT_SCALE_FACTOR` environment variable set?
You can check this by running
```batch
set
```
from the Command Prompt

Can you please also try running:
```batch
set QT_AUTO_SCREEN_SCALE_FACTOR=0
"C:\Program Files\Orange\python.exe" -m Orange.canvas --qt "-platform windows:dpiawareness=0"
```
(try also with `...dpiawareness=1` and `...dpiawareness=2`)

**Comment by hermandr** [comment]
Thank you it works!

**Comment by kernc** [comment]
What fixed it?

**Comment by ajdapretnar** [comment]
@ales-erjavec Thank you so much for working on this and figuring it out! :star2: This bug has been bothering several users.

**Comment by ajdapretnar** [comment]
I tried to set the scale factor on Linux Mint, but didn't work. I can try again and if it doesn't work, I can bring my laptop to work and we can check.

**Comment by lanzagar** [comment]
I think @robertcv has a similar problem on Ubuntu and he does not have a hidpi screen. Maybe @ajdapretnar and @robertcv can show the problem to @ales-erjavec and he might have some idea about what else to try.

BTW, is the current state of this issue fixed for windows with hidpi, and there are just similar problems on linux (even on non hidpi)?

**Comment by lanzagar** [comment]
Well the title of this issue said windows and hidpi. I suggest we close this, and if @ajdapretnar or @robertcv can still reproduce the problem on ubuntu and/or non-hidpi, they should open a new issue and probably ask @ales-erjavec for help in solving it.
