### ISSUE TITLE
Allow oversampling in Data Sampler widget

### ISSUE THREAD

**Issue by astaric** [biolab/orange3#2850]
When using `Fixed Sample Size` in Data Sampler Widget, `Instances` spinbox is limited to the number of rows in the dataset. It makes sense when we sample without replacement, but when sampling with replacement there is no need for such upper bound.

When `Sample with replacement` checkbox is selected, `Instances` spin should allow entry of arbitrary high numbers.

**Comment by pramud** [comment]
I am interested in getting started with this issue, could you guide me on how to get started ?

**Comment by h3xstream** [comment]
@pramud It seems like this class would need to be modified : 
https://github.com/biolab/orange3/blob/19fdc54d2c159d5de3330dbf9a917c9c9b6bed26/Orange/widgets/data/owdatasampler.py#L241
Ideally a warning message instead of an error.

Note : I'm not an Orange developer ... I'm just passing by,

**Comment by astaric** [comment]
Another place where sample size is limited is here:

https://github.com/biolab/orange3/blob/19fdc54d2c159d5de3330dbf9a917c9c9b6bed26/Orange/widgets/data/owdatasampler.py#L172
