### ISSUE TITLE
Is orange multi-threaded?

### ISSUE THREAD

**Issue by xelcho** [biolab/orange3#2859]
##### Orange version

3.8
OS - Ubuntu gnome 16.04.3

##### Expected behavior
all cpus used in calculations

##### Actual behavior
Seemingly single threaded behavior.

##### Steps to reproduce the behavior
trigger the test & score widget

##### Additional info (worksheets, data, screenshots, ...)

![screenshot from 2018-01-09 15-32-40](https://user-images.githubusercontent.com/30007489/34742012-be2c7be0-f552-11e7-843c-c230d9e568de.png)

**Comment by kernc** [comment]
Widgets implement multi-processing as they see fit. _Test & Score_ computes each Learner's results in a separate thread. You only have one learner, hence a single thread.

**Comment by xelcho** [comment]
Hey, thanks for the input! I have a couple of questions:
1 Where would I find documentation on this.
2 Is it possible to modify these settings via conf file or such?

Thank you for making/supporting this awesome software! :)
