### ISSUE TITLE
Pivot widget [was: Confusion Matrix for ordinary data]

### ISSUE THREAD

**Issue by astaric** [biolab/orange3#2860]
I want to compare cluster assignments to the ground truth (a column in original data that was not used to do the clustering).

I can do that in Box Plot, but there is currently no way to show this in a Confusion Matrix.

**Comment by kernc** [comment]
For "ordinary data", this sounds like a _Pivot Table_.

**Comment by astaric** [comment]
That link on *Pivot Table* is not working, where can I find one? :)

**Comment by ajdapretnar** [comment]
I did a little research. There are two things that pivots can display - contingency tables and aggregates.

The old Orange 2 showed a version of contingency table. The user can select a discrete attribute, whose values are rows, and a discrete attribute, whose values are column names. The third attribute is used as the value of cells and can be either discrete or continuous (different aggregations apply).
<img width="669" alt="Screen Shot 2019-04-11 at 13 20 58" src="https://user-images.githubusercontent.com/12524972/55953885-98654b80-5c5d-11e9-9c13-2e78492a5a3a.png">

The new Orange 3 already has Contingency table in Prototypes. It shows counts for discrete attributes (no third attribute, only the size of subgroups).
<img width="826" alt="Screen Shot 2019-04-11 at 13 26 32" src="https://user-images.githubusercontent.com/12524972/55954207-699ba500-5c5e-11e9-9cd5-cadaa652ff0f.png">

Pivot in Excel is a bit different (much more complicated). In a simple form, they allow you to use any kind of attribute for rows (even continuous). Then the user can select which attributes she wants to show in the pivot table. We are not talking about a values of a single discrete attribute, but aggregates of attributes in a data table. Each attribute can be given a specific kind of aggregation. 
<img width="378" alt="Screen Shot 2019-04-11 at 13 25 32" src="https://user-images.githubusercontent.com/12524972/55954651-8a182f00-5c5f-11e9-9e4e-28c1ce35bd82.png">

The fun part is that you can easily create contingency table by selecting two discrete attributes (one for row, one for column) and duplicate one of the two to values. Really neat.
<img width="443" alt="Screen Shot 2019-04-11 at 13 46 35" src="https://user-images.githubusercontent.com/12524972/55954921-4a9e1280-5c60-11e9-9ab6-d76f431427bb.png">


I think it makes no sense to try to be like Excel, but we can still have a powerful widget with a simple interface if done right. Perhaps one option is to have a contingency table when only one discrete attribute is selected as a column.

**Comment by janezd** [comment]
Implemented via #3823
