### ISSUE TITLE
data attribute affect following data item in scatter plot

### ISSUE THREAD

**Issue by jngai2** [biolab/orange3#2879]
##### Orange version
 3.8.0
![untitled](https://user-images.githubusercontent.com/7262285/35136411-5fd53946-fd1e-11e7-9eb3-8c2fa19c52ce.JPG)

**Comment by kernc** [comment]
Can you construct a simple, minimal dataset and workflow we can follow to reproduce/observe the issue?

**Comment by jngai2** [comment]
problem suddenly disappeared, I will close it for the time being.
