### ISSUE TITLE
Problem with add ons

### ISSUE THREAD

**Issue by Drmoca** [biolab/orange3#2888]
Add-ons send error or never finish loading the retrieving list window

**Comment by ajdapretnar** [comment]
Please elaborate on the issue.

**Comment by Drmoca** [comment]
![image](https://user-images.githubusercontent.com/7161111/35437851-f10c31c0-029c-11e8-97fc-c6e517a4aa56.png)

**Comment by ajdapretnar** [comment]
Does it happen with all add-ons?
How did you install Orange? Which version are you running?

**Comment by ajdapretnar** [comment]
Can't reproduce on OSX, Orange 3.8 (add-ons not installed with conda).

**Comment by Drmoca** [comment]
Yes, all.
![image](https://user-images.githubusercontent.com/7161111/35438102-f0816436-029d-11e8-84cd-5f507cbbc375.png)
Windows 10

**Comment by Drmoca** [comment]
solved by restarting the program with administrative rights...
Thanks

**Comment by astaric** [comment]
After #2883 is merged, the error should be more informative
