### ISSUE TITLE
Unable to install Orange3

### ISSUE THREAD

**Issue by adamchui** [biolab/orange3#2891]
##### Orange version

Orange 3
Python 3.6

##### Actual behavior

Executed command
pip install --user Orange3

Error ocured:
Orange/classification/_simple_tree.c:772:20: fatal error: Python.h: No such file or directory

##### Additional info (worksheets, data, screenshots, ...)

  running build_ext
  building 'bottleneck.reduce' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/bottleneck
  creating build/temp.linux-x86_64-3.6/bottleneck/src
  gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/lib64/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -c bottleneck/src/reduce.c -o build/temp.linux-x86_64-3.6/bottleneck/src/reduce.o -O2
  In file included from bottleneck/src/reduce.c:1:0:
  bottleneck/src/bottleneck.h:4:20: fatal error: Python.h: No such file or directory
   #include <Python.h>
                      ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1

**Comment by astaric** [comment]
The preferred way to install Orange on linux is by installing Miniconda and following instructions on https://orange.biolab.si/download/linux/.

If you want to compile from source, you probably need to install python3-dev package that includes python header files.
