### ISSUE TITLE
psycopg2 installation doesn't help

### ISSUE THREAD

**Issue by araud** [biolab/orange3#2892]
##### Orange version

No way to copy text from About dialog. No idea where to insert this code.
![image](https://user-images.githubusercontent.com/6527024/35551253-22a72ca0-0543-11e8-9ee6-40de7e9b4710.png)

##### Expected behavior

Connect to postgre

##### Actual behavior

Wants backend

##### Steps to reproduce the behavior

sudo pip install psycopg2
run Orange and try to add SQL Table

##### Additional info (worksheets, data, screenshots, ...)
![image](https://user-images.githubusercontent.com/6527024/35551202-f1bfed70-0542-11e8-919d-c3562deee3b6.png)

**Comment by astaric** [comment]
macOS bundle from the website comes with its own python and pip. You need to use pip from bundle to install psycopg2.

Assuming you copied Orange3 app into /Applications, you can run:
```
/Applications/Orange3.app/Contents/MacOS/pip install psycopg2
```

Or, you can download [psycopg2 wheel](https://pypi.python.org/packages/39/cf/76707dc80505b35482a9a8a24a35e326cd7453dda5dca9ff18df1ec29280/psycopg2-2.7.3.2-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl#md5=7bc5642f2b450d7ac58c57a07f25512d) from pypi and drag-drop it onto the add-ons dialog.

**Comment by araud** [comment]
Yes, this helped.
But of you're shipping own python, why not having two main db connectors on board?

**Comment by kernc** [comment]
Why don't we really?

**Comment by franko108** [comment]
Hi, 
I've just installed Orange 3.20.1.
The above example is useful for connection to Postgres ( psycopg2) on my linux system.  
I do have `mysql-connector-python` installed as well as `mysqlclient`.   

When loading Orange->SQL Table, only PostgreSQL is available, not Mysql as well.  
Is there support for connection on Mysql db?

**Comment by robertcv** [comment]
The sql connection packages required are listed in [requirements-sql.txt](https://github.com/biolab/orange3/blob/master/requirements-sql.txt). For Microsoft SQL Server you have to install the `pymssql` package.

**Comment by franko108** [comment]
> The sql connection packages required are listed in [requirements-sql.txt](https://github.com/biolab/orange3/blob/master/requirements-sql.txt). For Microsoft SQL Server you have to install the `pymssql` package.

Yes, thank you, I see that MS SQL server is available, seems there is no available connection to _MySQL_ server.  
Are there any plans to implement connection to Mysql?

**Comment by robertcv** [comment]
Sorry I misread what you wanted. There is #3565 which would also allow connection to MySQL but this probably won't be implemented in the near future.
