### ISSUE TITLE
Correspondence Analysis: improve data point inspection

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#2898]
##### Orange version

3.10.dev

##### Expected behavior
It is easy to inspect instances from the plot.

##### Actual behavior
One can neither select nor see a tooltip for data points in the plot.

##### Steps to reproduce the behavior
File - Correspondence Analysis.

##### Additional info (worksheets, data, screenshots, ...)
Some attribute values overlap, but I cannot see which.

<img width="798" alt="screen shot 2018-02-02 at 12 38 47" src="https://user-images.githubusercontent.com/12524972/35731564-585921f2-0816-11e8-9539-471c27ef5397.png">

**Comment by ajdapretnar** [comment]
I think CA should support both, selection of instances, which would correspond to Select Rows functionality and tooltips.

**Comment by ajdapretnar** [comment]
A fix with an overhauled widget is pending. Will be solved.

**Comment by janezd** [comment]
Merged into #2538.
