### ISSUE TITLE
Heat Map: show selected cluster

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#2902]
##### Orange version

3.10.dev

##### Requested feature
Cluster selection in Heat Map is not obvious. It would be nice to have the selected cluster colored just like in Hierarchical Clustering (with light blue for example).

##### Additional info (worksheets, data, screenshots, ...)
From this image, it is not very obvious which cluster is selected. Show selection also in dendrogram, not only in the plot.

<img width="480" alt="screen shot 2018-02-09 at 11 46 46" src="https://user-images.githubusercontent.com/12524972/36024095-ed5003ca-0d8e-11e8-82a2-f52bf442b91e.png">

**Comment by janezd** [comment]
We discussed this. It seems that a reasonable solution is to have two modes of selecting rows: in the dendrogram part or in the heatmap. The two modes are exclusive, you can't mix them. Selecting in the heatmap works as it is (with possible creation of groups, if #2983 is implemented). Selecting in dendrogram will show clusters with colors, like in the Hierarchical Clustering widget.

Technically, selection will probably be stored in two different places - either in the heatmap or in the dendrogram. Selecting in one place will annul the selection in the other.

**Comment by janezd** [comment]
Issue moved to #4090.
