### ISSUE TITLE
Value.__hash__ is wrong

### ISSUE THREAD

**Issue by astaric** [biolab/orange3#2912]
Hash function should return the same value for all objects that are considered equal.

steps to reproduce:
```
from Orange.data.variable import StringVariable, Value
val = Value(StringVariable("s"), "test")
val == "test"
# True
hash(val) == hash("test")
# False
```

**Comment by kernc** [comment]
> Hash function should return the same value for all objects that are considered equal.

Could you back this claim?

**Comment by astaric** [comment]
https://docs.python.org/3/reference/datamodel.html#object.__hash__
