### ISSUE TITLE
K-means: work on sparse

### ISSUE THREAD

**Issue by kietdinh** [biolab/orange3#2913]
https://github.com/biolab/orange3/blob/1eb9b69d37e35b159bd6892a606606803c537da1/Orange/clustering/kmeans.py#L29

```len(X)``` should be ```X.shape[0]``` beacause it raise error ```sparse matrix length is ambiguous; use getnnz() or shape[0]``` when use tf-idf sparse matrix with Kmeans

Error flow
![error](https://user-images.githubusercontent.com/19968582/36337906-45b179cc-13d4-11e8-8ee9-a499f9666891.PNG)

**Comment by coco-egaliciar** [comment]
Any update for this? I have the same situation

![image](https://user-images.githubusercontent.com/38989410/44998113-a9880480-af78-11e8-8bae-f26de240fa14.png)

**Comment by coco-egaliciar** [comment]
Any update for this? I have the same situation
Orange Version: 3.13

![image](https://user-images.githubusercontent.com/38989410/44998161-f66bdb00-af78-11e8-9c37-a62c54ad36ed.png)

**Comment by ajdapretnar** [comment]
This was fixed in #3140. Please upgrade Orange.
