### ISSUE TITLE
Permission denied: 'C:\\Program Files\\Orange\\Scripts\\conda'

### ISSUE THREAD

**Issue by h3xstream** [biolab/orange3#2921]
##### Orange version

3.10.0
Windows 10

##### Expected behavior

No stack trace / Proper loading

##### Actual behavior

```
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda\cli\activate.py", line 168, in main
    conda.install.symlink_conda(prefix, context.root_prefix, shell)
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda\install.py", line 113, in symlink_conda
    symlink_conda_hlp(prefix, root_dir, where, symlink_fn)
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda\install.py", line 130, in symlink_conda_hlp
    symlink_fn(root_file, prefix_file)
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda\install.py", line 86, in win_conda_bat_redirect
    with open(dst, "w") as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\Orange\\Scripts\\conda'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda\cli\main.py", line 151, in main
    activate.main()
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda\cli\activate.py", line 174, in main
    raise CondaEnvironmentError(msg)
conda.exceptions.CondaEnvironmentError: Environment error: Cannot activate environment cmd.exe.
User does not have write access for conda symlinks.
```

##### Steps to reproduce the behavior

1. Install the latest version Orange with **Miniconda installer**
2. Launch Orange Command Prompt

**Comment by h3xstream** [comment]
## Temporary fix

Launch the shortcut (or activate.bat) as Administrator

**Comment by h3xstream** [comment]
Administrator is required anyway if you need to update the python packages from Orange.
Maybe it should be mandatory to run as Administrator.

**Comment by astaric** [comment]
Administrator is only required when you install Orange into Program Files (or any other location where your current user does not have write permission).

We cannot assume that the user installing/running Orange has admin privileges so I do not think that forcing running as Administrator is the solution.

I have managed to reproduce the problem you mention, though I noticed something else. Run as administrator is only needed for the first time you run Orange Command prompt. After that, you can run it as an ordinary user (unless you intend to install new packages). It will take longer to start, but once it loads, the environment is functional.

This looks like there are some files that need to be created the first time the environment is activated. I will take a look whether we can try to activate the environment for the first time during the installation, which would solve the original problem.
