### ISSUE TITLE
Feature request: named entities

### ISSUE THREAD

**Issue by gholmberg** [biolab/orange3#2922]
I see you already use NLTK for text processing.  It would be very useful to expose NLTK's named entity recognition.

Another good named entity recognizer for Python is spaCy.

**Comment by ajdapretnar** [comment]
@gholmberg Please migrate this issue to the corresponding [Text issue tracker](https://github.com/biolab/orange3-text/issues). Thank you!

**Comment by ajdapretnar** [comment]
Thank you for the suggestion though!
