### ISSUE TITLE
Select Rows: Gets slow with many variables

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#2925]
##### Orange version

3.10.dev

##### Expected behavior
Select Rows works fast for data sets with 390 rows and 3100 columns.

##### Actual behavior
Select Rows quite slow.

##### Steps to reproduce the behavior
Corpus - BOW - Select Rows.

##### Additional info (worksheets, data, screenshots, ...)
Could be a sparse issue?

**Comment by smiks** [comment]
If it helps. 
I've tested it with one of my data sets and geo-gds360.

Geo-gds360
In: 9486 variables
Out: 9480 variables

My data set has 200 rows and 6700 columns.
In: 6700 variables
Out: 6700 variables

I tested with both purging methods (unused features and unused classes).
Took around 1 second for both (Orange version 3.10.0).

**Comment by astaric** [comment]
@ajdapretnar, it probably is a sparse issue. Could you attach a workflow that reproduces the issue?

**Comment by ajdapretnar** [comment]
Sure!
Corpus (bookexcerpts) - Bag of Words - Select Rows. Widget is slow even to open, let alone work with it. Any speed ups would be greatly appreciated.

**Comment by ajdapretnar** [comment]
With election-tweets-2016 this widget is practically useless. 😞

**Comment by ales-erjavec** [comment]
Like always, uncheck the 'Remove unused features/classes in the *Purging* section of the widget.
