### ISSUE TITLE
BUG: Test & Score dialog Evaluation Results grid does not auto sort

### ISSUE THREAD

**Issue by dsanalytics** [biolab/orange3#2926]
Test & Score dialog Evaluation Results grid does not auto sort values based on selected column ordering. 

Environment: Orange 3.10, Windows 10 64bit Home, Anaconda

Thank you.

![orange3-autosort-not-working-annotated](https://user-images.githubusercontent.com/32625394/36818553-25ff0060-1cab-11e8-9f4a-83024f93bdbe.png)

**Comment by ajdapretnar** [comment]
I can't reproduce this on a simple iris example. Could you perhaps provide the entire workflow and/or see if this happens on some Orange dataset? Thank you!

**Comment by astaric** [comment]
I managed to reproduce it with the following workflow on hear-disease:

<img width="510" alt="screen shot 2018-03-01 at 10 42 32" src="https://user-images.githubusercontent.com/588601/36837675-560eafac-1d3d-11e8-821b-0c5fd3d7ccf7.png">

Upon resampling, scores change, but the table does not get re-sorted.

**Comment by dsanalytics** [comment]
Thanks @astaric - that's exactly what I have, Data Sampler feeding T&S.

**Comment by dsanalytics** [comment]
@astaric - Thanks for doing the work! Much appreciated! Would you mind taking on https://github.com/biolab/orange3/issues/2935 as well? Essentially 5 numbers (parameters max limits) to change in some Orange widgets GUIs.

**Comment by dsanalytics** [comment]
@astaric Does closing this issue mean that your fix was accepted (PR approved) and that the next version of Orange (v3.11?) would have that fix in place? Please advise - thanks.

**Comment by lanzagar** [comment]
Yes, as the (auto-generated) messages says, this was closed automatically by merging the pull request with commit efcba80. You can also check that the PR that referenced this #2931 is now merged.
It will be in the next release, which you might be happy to learn should be available today! ;)

**Comment by PrimozGodec** [comment]
@dsanalytics New release is now available.
