### ISSUE TITLE
Q: Re Python Script widget - pandas dataframe to out_data

### ISSUE THREAD

**Issue by dsanalytics** [biolab/orange3#2932]
Is there a code example converting pandas dataframe to out_data? What I'm trying to accomplish is to get data from MySql using Python Script widget and then pass it to e.g. Data Sampler, Impute, etc.

Thank you.

**Comment by kernc** [comment]
With a recent version, this should mostly work:
```py
from Orange.data.pandas_compat import table_from_frame

table = table_from_frame(df)
```

**Comment by dsanalytics** [comment]
@kernc Where does one set continuous/discrete and feature/meta/class?
Also, what about index column that may be e.g. datetime or guid? How is that converted in out_data? 
If your code indeed suffices, would the last line be out_data = table?

**Comment by kernc** [comment]
You prepare the columns beforehand on the frame. `pd.Categorical` or string columns (`df.Column.astype(str)`) are interpreted as discrete. Metas not supported. Datetime columns are interpreted as TimeVariable. Any index besides a simple range index is converted to a column. Yes.

**Comment by dsanalytics** [comment]
@kernc And that's exactly why I asked for a full working example from the community, instead of incomplete two-liners with comments like, you need to do X first, followed by Y, and perhaps Z.

P.S. Why don't you change your problematic avatar - imagine one browsing this post at work and a manager passing by. How's your avatar beneficial to Orange?

**Comment by kernc** [comment]
Beg your pardon? `table = table_from_frame(df)` is a full, working example. The function is used in [one widget in Prototypes](https://github.com/biolab/orange3-prototypes/blob/8022ffe6f9a9fd989ab8b2dda790208d424e0939/orangecontrib/prototypes/widgets/owsignificantgroups.py#L312) and [in Timeseries](https://github.com/biolab/orange3-timeseries/blob/f3f42488a303623c6bc3169dae0f186e7f827c52/orangecontrib/timeseries/datasources.py#L83). Unfortunately, no docs other than the docstring exist for the moment. Welcome to contrib a more helpful example if you'd like.

**Comment by duohappy** [comment]
@kernc , I can not find out "table_from_frame" function in help documention, [https://docs.orange.biolab.si/3/data-mining-library/reference/data.html](url). In here, I get it.

**Comment by ajdapretnar** [comment]
For me, this works. @dsanalytics If you think something else should be added, please provide a detailed description.

**Comment by pchristian4481** [comment]
table_from_frame does work, but the output when connected to a Data Table widget, does not have the column names?  How to include these?  I am using the in_data to create something different with different column names (feature names).  How can I include these new feature names?  Thanks for the help.

**Comment by pmirla** [comment]
Same question as pchristian4481. How do I retain column names? when I link this downstream?
My code:
colnames = [i.name for i in in_data.domain]
df = Y_df.set_axis(colnames, axis=1, inplace=False)
table = table_from_frame(Y_df)
out_data = table

**Comment by pmirla** [comment]
This works. Might help others

import random
from Orange.data import Domain, Table
import numpy as np
import pandas as pd
from Orange.data.pandas_compat import table_from_frame


colnames = [i.name for i in in_data.domain]
arr_in_data =  np.array(in_data)
col_to_search = "Date"
col_index = colnames.index(col_to_search)
df = pd.DataFrame(in_data.X)
table = table_from_frame(df)


from Orange.data import Domain, Table
domain = Domain([attr for attr in in_data.domain.attributes
                 if attr.is_continuous or len(attr.values) <= 5],
                in_data.domain.class_vars)

out_data = Orange.data.Table(domain, df, in_data.Y)

                
out_data = Table(domain, out_data)
