### ISSUE TITLE
Need network proxy input to get add-ons and use network

### ISSUE THREAD

**Issue by JRockML** [biolab/orange3#2934]
##### Orange version

3.4.1

##### Expected behavior
Add-ons manager opens and lists packages, may be needed in a global sense prior to SQL login etc.

##### Actual behavior
package list not populated because of timeout from being on network behind proxy server

##### Steps to reproduce the behavior
require a proxy and then try to list add-ons : operation times out

##### Additional info (worksheets, data, screenshots, ...)
![image](https://user-images.githubusercontent.com/37002214/36923393-329a098e-1e39-11e8-969a-66f0977fb545.png)

**Comment by kernc** [comment]
Orange 3.4.1 is about a year old. Current version is 3.10. Please confirm this is still an issue with the [latest version](https://orange.biolab.si/download/).

**Comment by JRockML** [comment]
The update and the proxy options in the settings worked well.  Thanks!

*I was using 3.4 because it was the default with Anaconda and hadn't added the conda-forge repository to the available package locations.  Following the instructions on the Orange download page regarding Anaconda provided the update.
