### ISSUE TITLE
[IDEA] Include errors/warnings in widget help

### ISSUE THREAD

**Issue by astaric** [biolab/orange3#2937]
While Errors and Warnings should be as descriptive as possible, they usually describe the problem, not the way to solve it.

One way to address this would be to list the error/warning messages in documentation along with the suggested solutions.

**Comment by ajdapretnar** [comment]
Where would you put this file? I can prepare a template with some examples, just let me know what is the proper location for this.

**Comment by astaric** [comment]
I would include it in widget's help file. Not sure where though. Maybe a separate section?

**Comment by janezd** [comment]
@ajdapretnar, let us consider this a guideline and remember it when writing or improving documentation. But guidelines don't belong to issues, so let's close it.
