### ISSUE TITLE
Inquiry: Price prohibitive commercial use (timeseries widget)

### ISSUE THREAD

**Issue by dsanalytics** [biolab/orange3#2941]
Current commercial license for Highcharts begins at $1,445 USD and that pretty much prevents me from using Timeseries and any other widgets that utilize it for EDA. I do indeed know that replacing that library would be a non-trivial amount of work, and knowing that, are there any plans to replace it and keep Orange caveat-free?

Here're plenty of free-for-commercial-use alternatives: http://socialcompare.com/en/comparison/javascript-graphs-and-charts-libraries 

Thoughts?

**Comment by ajdapretnar** [comment]
A larger discussion can be found at #2044. I have opened a [separate issue](https://github.com/biolab/orange3-timeseries/issues/58) in Timeseries add-on. Help in addressing this issue would be appreciated.

I will close this as core Orange doesn't use Highcharts.
