### ISSUE TITLE
Python has stopped working

### ISSUE THREAD

**Issue by tsherwood7** [biolab/orange3#2946]
Hello,

When i try to import a file in the file widget I keep getting an error that Python has stopped working. When I click on the solve for error the program shuts down and no other information is given to address the problem. I have tried reinstalling both Python 3.4.4 and Orange 3.10 and still have the same problem.

**Comment by kernc** [comment]
Is it possible that some lengthy computation is taking place is one of the widgets?

Can you attach a screenshot of the error you get or any further information?

**Comment by tsherwood7** [comment]
Problem has been solved had to install the 32 bit version instead of the 64 bit version of Orange 3.10 and now is working
