### ISSUE TITLE
Problem with update miniconda installer - Directory Not Empty

### ISSUE THREAD

**Issue by JoeB-UT** [biolab/orange3#2954]
##### Orange 
Orange version 3.11.0

##### Expected behavior
Miniconda3 4.3.14 (64-bit) setup upgrade from previous Orange 3.10 version. Upgrade miniconda to support Orange 3.11

##### Actual behavior
Miniconda3 4.3.14 (64-bit) setup upgrade from previous Orange 3.10 version. Install reports "Directory 'C:\ProgramData\Miniconda3' is not empty, please choose a different location."

##### Steps to reproduce the behavior
Install Anaconda 64 bit in Windows 10.
Install Orange 3.10 and Miniconda (64-bit) in windows 10 with defaults and path set.
Try to update with Orange 3.11 and Miniconda (64-bit) in Windows 10.

##### Additional info (worksheets, data, screenshots, ...)
![image](https://user-images.githubusercontent.com/36177068/37305039-d822a430-25f8-11e8-861d-562882f29df1.png)

**Comment by ajdapretnar** [comment]
This is not an Orange issue, but a Miniconda one. They don't replace the old folders. You need to uninstall and re-install Miniconda.

**Comment by markotoplak** [comment]
@ajdapretnar, is there an open miniconda issue?

**Comment by ajdapretnar** [comment]
https://github.com/conda/conda/issues/7534

**Comment by Jivabhaiandsons** [comment]
I think you need to put Minianaconda3.exe than it should be download itself it works for me
