### ISSUE TITLE
Expand Contingency Table widget

### ISSUE THREAD

**Issue by lanzagar** [biolab/orange3#2966]
##### Enhancement proposal
Contingency Table widget could be expanded to show the data instead of just constructing the output Table.
We should think about the GUI layout and additional features. For a start:
- table shown like in Confusion Matrix
- Chi-squared computed like in Sieve, possibly also adjusted Rand index
- option to sort values of both variables to see patterns better (biclustering)
- find informative pairs like in Sieve?

Some considerations include:
- do we need two widgets (this and Sieve)
- do we want more scoring metrics (i.e. this widget becomes the way to score clusters and even regular discrete features for a classification task; sort of categorical correlation thing)

**Comment by BlazZupan** [comment]
Perhaps the most simple way to start:

Take Contingency Table from Prototypes.
Consider Confusion Matrix from main Orange, see if the table can be directly re-used in Contingency Table.
Include [Adjusted Rand Index](http://scikit-learn.org/stable/modules/generated/sklearn.metrics.adjusted_rand_score.html), [adjusted mutual information score](http://scikit-learn.org/stable/modules/generated/sklearn.metrics.adjusted_mutual_info_score.html#sklearn.metrics.adjusted_mutual_info_score), and chi-squared and associated p-value (from Sieve Diagram).

**Comment by jurijsteblaj** [comment]
The table from Confusion Matrix cannot be reused as it is because it's implemented as a QTableView and a sequence of attribute changes.
```
view = self.tableview = QTableView(
    editTriggers=QTableView.NoEditTriggers)
view.setModel(self.tablemodel)
view.horizontalHeader().hide()
view.verticalHeader().hide()
view.horizontalHeader().setMinimumSectionSize(60)
view.selectionModel().selectionChanged.connect(self._invalidate)
view.setShowGrid(False)
view.setItemDelegate(BorderedItemDelegate(Qt.white))
view.setSizePolicy(QSizePolicy.MinimumExpanding,
                   QSizePolicy.MinimumExpanding)
view.clicked.connect(self.cell_clicked)
box.layout().addWidget(view)
```
I could create a class which would extend QTableView with these attributes.

**Comment by ajdapretnar** [comment]
Implemented in Prototypes add-on.
