### ISSUE TITLE
Error when loading 'large' file

### ISSUE THREAD

**Issue by ruudfiers** [biolab/orange3#2967]
Multiple .TAB files can't be read, via the file widget or the corpus widget. Files bigger than 25.000 kb give an error message. 

##### Orange version
<3.11.0>

##### Expected behavior
Loading a file (59.207 kb)

##### Actual behavior
Error message: Cannot parse dataset H:/Documents/Orange-files/Data/[name file].tab: line contains NULL byte

##### Steps to reproduce the behavior
Looks like a RAM issue, but the file is relatively small for that I would say

**Comment by kernc** [comment]
> Could it be a similar problem?

The exact same.

**Comment by ruudfiers** [comment]
And is there a way to fix it when you're a rookie like me?

**Comment by kernc** [comment]
Yeah, aside from following one of the recipes on the address you posted, raise this issue with [Orange3-SMA add-on](https://github.com/amcat/orange3-sma) developers.

**Comment by ajdapretnar** [comment]
I will consider this closed since it is an issue of an external add-on.

**Comment by kernc** [comment]
Opened https://github.com/amcat/orange3-sma/issues/1.

**Comment by kernc** [comment]
@ruudfiers The add-on issue has been [fixed and fix released](https://github.com/amcat/orange3-sma/issues/1#issuecomment-383825153). Perhaps try again.
