### ISSUE TITLE
OWDistributions crashes

### ISSUE THREAD

**Issue by pavlin-policar** [biolab/orange3#2970]
##### Orange version
3.11.0.dev0+5043829

##### Expected behavior
Distributions widget does not crash

##### Actual behavior
Crashes.

Further investigation shows this issue appeared in 30cada3, but I don't really understand the change, so leaving it here.

##### Steps to reproduce the behavior
Using single cell addon:

File "iris" → Distributions

##### Additional info (worksheets, data, screenshots, ...)

Exception: | ValueError: Buffer dtype mismatch, expected 'int8_t' but got 'long'
-- | --
Module: | Orange.data._contingency:12
Widget Name: | Distributions
Widget Module: | Orange.widgets.visualize.owdistributions:623
Widget Scheme: | /tmp/ows-z2ykichr.ows.xml
Version: | 3.11.0.dev0+5043829
Environment: | Python 3.6.4 on Linux 4.15.10-1-ARCH #1 SMP PREEMPT Thu Mar 15 12:24:34 UTC 2018 x86_64
Installed Packages: | AnyQt==0.0.8, Babel==2.5.3, Bottleneck==1.2.1, CacheControl==0.12.4, CommonMark==0.5.4, Cython==0.27.3, Jinja2==2.10, MarkupSafe==1.0, Orange3-ImageAnalytics==0.1.16, Orange3-Network==1.3.2, Orange3-Pavlin==0.0.1, Orange3-Prototypes==0.9.0, Orange3-SingleCell==0.2.4, Orange3==3.11.0.dev0+5043829, Pillow==5.0.0, PyQt5==5.10, Pygments==2.2.0, SecretStorage==2.3.1, Sphinx==1.7.0, alabaster==0.7.10, asn1crypto==0.24.0, beautifulsoup4==4.6.0, certifi==2018.1.18, cffi==1.11.4, chardet==3.0.4, cryptography==2.1.4, cycler==0.10.0, decorator==4.1.2, docutils==0.14, fire==0.1.3, future==0.16.0, h2==2.6.2, hpack==3.0.0, hyper==0.7.0, hyperframe==3.2.0, idna==2.6, imagesize==1.0.0, ipython-genutils==0.2.0, ipython==6.2.1, jedi==0.11.1, joblib==0.11, jsonschema==2.6.0, jupyter-core==4.4.0, keyring==11.0.0, keyrings.alt==3.0, lockfile==0.12.2, matplotlib==2.1.2, msgpack-python==0.5.4, nbformat==4.4.0, networkx==2.1, numpy==1.14.0, numpydoc==0.7.0, packaging==16.8, pandas==0.22.0, parso==0.1.1, pexpect==4.4.0, pickleshare==0.7.4, pip==9.0.1, plotly==2.4.0, prompt-toolkit==1.0.15, ptyprocess==0.5.2, pycparser==2.18, pyparsing==2.2.0, pyqtgraph==0.10.0, python-dateutil==2.6.1, pytz==2018.3, recommonmark==0.4.0, requests==2.18.4, scikit-learn==0.19.1, scipy==1.0.0, seaborn==0.8.1, serverfiles==0.2.1, setuptools==38.5.1, simplegeneric==0.8.1, sip==4.19.7, six==1.11.0, snowballstemmer==1.2.1, sphinxcontrib-websupport==1.0.1, traitlets==4.3.2, urllib3==1.22, wcwidth==0.1.7, wheel==0.30.0, xlrd==1.1.0
Machine ID: | 172461168621546
Stack Trace: | Traceback (most recent call last):  File "/home/pavlin/dev/orange3/Orange/widgets/visualize/owdistributions.py", line 623, in _on_variable_idx_changed    self._setup()  File "/home/pavlin/dev/orange3/Orange/widgets/visualize/owdistributions.py", line 367, in _setup    contingency.get_contingency(data, self.var, self.cvar)  File "/home/pavlin/dev/orange3/Orange/statistics/contingency.py", line 251, in get_contingency    return Continuous(dat, col_variable, row_variable, unknowns, unknown_rows)  File "/home/pavlin/dev/orange3/Orange/statistics/contingency.py", line 162, in __init__    return self.from_data(dat, col_variable, row_variable)  File "/home/pavlin/dev/orange3/Orange/statistics/contingency.py", line 194, in from_data    conts, self.unknown_rows = data._compute_contingency([col_variable], row_variable)  File "/home/pavlin/dev/orange3/Orange/data/table.py", line 1539, in _compute_contingency    col_data, classes_, n_rows, W_)  File "Orange/data/_contingency.pyx", line 12, in Orange.data._contingency.contingency_floatarray (Orange/data/_contingency.c:1511)ValueError: Buffer dtype mismatch, expected 'int8_t' but got 'long'
Local Variables: | OrderedDict([('__builtins__', <module 'builtins' (built-in)>),             ('__doc__', None),             ('__file__',              '/home/pavlin/dev/orange3/Orange/data/_contingency.cpython-36m-x86_64-linux-gnu.so'),             ('__loader__',              <_frozen_importlib_external.ExtensionFileLoader object at 0x7ff5c7a0f160>),             ('__name__', 'Orange.data._contingency'),             ('__package__', 'Orange.data'),             ('__spec__',              ModuleSpec(name='Orange.data._contingency', loader=<_frozen_importlib_external.ExtensionFileLoader object at 0x7ff5c7a0f160>, origin='/home/pavlin/dev/orange3/Orange/data/_contingency.cpython-36m-x86_64-linux-gnu.so')),             ('__test__', {}),             ('contingency_floatarray',              <built-in function contingency_floatarray>),             ('numpy',              <module 'numpy' from '/home/pavlin/miniconda3/envs/orange3/lib/python3.6/site-packages/numpy/__init__.py'>)])

Exception: | ValueError: Buffer dtype mismatch, expected 'int8_t' but got 'long'
-- | --
Module: | Orange.data._contingency:12
Widget Name: | Distributions
Widget Module: | Orange.widgets.visualize.owdistributions:623
Widget Scheme: | /tmp/ows-5_oxod8j.ows.xml
Version: | 3.11.0.dev0+5043829
Environment: | Python 3.6.4 on Linux 4.15.10-1-ARCH #1 SMP PREEMPT Thu Mar 15 12:24:34 UTC 2018 x86_64
Installed Packages: | AnyQt==0.0.8, Babel==2.5.3, Bottleneck==1.2.1, CacheControl==0.12.4, CommonMark==0.5.4, Cython==0.27.3, Jinja2==2.10, MarkupSafe==1.0, Orange3-ImageAnalytics==0.1.16, Orange3-Network==1.3.2, Orange3-Pavlin==0.0.1, Orange3-Prototypes==0.9.0, Orange3-SingleCell==0.2.4, Orange3==3.11.0.dev0+5043829, Pillow==5.0.0, PyQt5==5.10, Pygments==2.2.0, SecretStorage==2.3.1, Sphinx==1.7.0, alabaster==0.7.10, asn1crypto==0.24.0, beautifulsoup4==4.6.0, certifi==2018.1.18, cffi==1.11.4, chardet==3.0.4, cryptography==2.1.4, cycler==0.10.0, decorator==4.1.2, docutils==0.14, fire==0.1.3, future==0.16.0, h2==2.6.2, hpack==3.0.0, hyper==0.7.0, hyperframe==3.2.0, idna==2.6, imagesize==1.0.0, ipython-genutils==0.2.0, ipython==6.2.1, jedi==0.11.1, joblib==0.11, jsonschema==2.6.0, jupyter-core==4.4.0, keyring==11.0.0, keyrings.alt==3.0, lockfile==0.12.2, matplotlib==2.1.2, msgpack-python==0.5.4, nbformat==4.4.0, networkx==2.1, numpy==1.14.0, numpydoc==0.7.0, packaging==16.8, pandas==0.22.0, parso==0.1.1, pexpect==4.4.0, pickleshare==0.7.4, pip==9.0.1, plotly==2.4.0, prompt-toolkit==1.0.15, ptyprocess==0.5.2, pycparser==2.18, pyparsing==2.2.0, pyqtgraph==0.10.0, python-dateutil==2.6.1, pytz==2018.3, recommonmark==0.4.0, requests==2.18.4, scikit-learn==0.19.1, scipy==1.0.0, seaborn==0.8.1, serverfiles==0.2.1, setuptools==38.5.1, simplegeneric==0.8.1, sip==4.19.7, six==1.11.0, snowballstemmer==1.2.1, sphinxcontrib-websupport==1.0.1, traitlets==4.3.2, urllib3==1.22, wcwidth==0.1.7, wheel==0.30.0, xlrd==1.1.0
Machine ID: | 172461168621546
Stack Trace: | Traceback (most recent call last):  File "/home/pavlin/dev/orange3/Orange/widgets/visualize/owdistributions.py", line 623, in _on_variable_idx_changed    self._setup()  File "/home/pavlin/dev/orange3/Orange/widgets/visualize/owdistributions.py", line 367, in _setup    contingency.get_contingency(data, self.var, self.cvar)  File "/home/pavlin/dev/orange3/Orange/statistics/contingency.py", line 251, in get_contingency    return Continuous(dat, col_variable, row_variable, unknowns, unknown_rows)  File "/home/pavlin/dev/orange3/Orange/statistics/contingency.py", line 162, in __init__    return self.from_data(dat, col_variable, row_variable)  File "/home/pavlin/dev/orange3/Orange/statistics/contingency.py", line 194, in from_data    conts, self.unknown_rows = data._compute_contingency([col_variable], row_variable)  File "/home/pavlin/dev/orange3/Orange/data/table.py", line 1539, in _compute_contingency    col_data, classes_, n_rows, W_)  File "Orange/data/_contingency.pyx", line 12, in Orange.data._contingency.contingency_floatarray (Orange/data/_contingency.c:1511)ValueError: Buffer dtype mismatch, expected 'int8_t' but got 'long'
Local Variables: | OrderedDict([('__builtins__', <module 'builtins' (built-in)>),             ('__doc__', None),             ('__file__',              '/home/pavlin/dev/orange3/Orange/data/_contingency.cpython-36m-x86_64-linux-gnu.so'),             ('__loader__',              <_frozen_importlib_external.ExtensionFileLoader object at 0x7fdf0a73b438>),             ('__name__', 'Orange.data._contingency'),             ('__package__', 'Orange.data'),             ('__spec__',              ModuleSpec(name='Orange.data._contingency', loader=<_frozen_importlib_external.ExtensionFileLoader object at 0x7fdf0a73b438>, origin='/home/pavlin/dev/orange3/Orange/data/_contingency.cpython-36m-x86_64-linux-gnu.so')),             ('__test__', {}),             ('contingency_floatarray',              <built-in function contingency_floatarray>),             ('numpy',              <module 'numpy' from '/home/pavlin/miniconda3/envs/orange3/lib/python3.6/site-packages/numpy/__init__.py'>)])

**Comment by ales-erjavec** [comment]
You have to recompile the module. I.e. run `./setup.py build_ext -i` from the source root.

**Comment by pavlin-policar** [comment]
Oh, yes. That did it. Silly mistake on my part. Sorry.
