### ISSUE TITLE
Can't retrieve package list from Add-ons in Menu

### ISSUE THREAD

**Issue by LuckyDao** [biolab/orange3#2976]
##### Orange version
Version 3.11.0

##### Expected behavior
Expected to populate add ons

##### Actual behavior
Throws max() error

##### Steps to reproduce the behavior
enter Orange3, click Options>Add-ons

##### Additional info (worksheets, data, screenshots, ...)

![image](https://user-images.githubusercontent.com/35459931/37984761-c8806b78-31bc-11e8-9397-2d98e56fe859.png)

**Comment by Varidrix** [comment]
Encountering the same problem. Reinstall of doesn't seem to work.

**Comment by janezd** [comment]
MeToo

**Comment by kernc** [comment]
Fixed. For now.

**Comment by LuckyDao** [comment]
Thank you!
