### ISSUE TITLE
Heat Map: Allow creation of groups

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#2983]
##### Idea
Heat Map allows clustering rows and columns, resulting in nice visualizations. It would be nice if one could create groups from this clustering, just like one can create groups in Scatter Plot.

##### When no clustering is selected
Heat Map allows selection of individual rows, just like it does now. No change here, except maybe consider a more obvious selection square (black is very inconspicuous).

<img width="127" alt="screen shot 2018-03-30 at 14 26 07" src="https://user-images.githubusercontent.com/12524972/38137685-6cba7efc-3426-11e8-8441-145651894470.png">

##### With clustering
Heap Map disables selection of individual rows and allows selection only of clusters. Clusters are colored just like in Hierarchical Clustering. The output of this selection is the same as in HierClust - if all rows are selected, each is described with the Cluster label (C1, C2, C3) in the new Cluster column.

<img width="226" alt="screen shot 2018-03-30 at 14 26 26" src="https://user-images.githubusercontent.com/12524972/38137688-70bfb706-3426-11e8-85ee-794f47726ab6.png">

##### Implement
- implement selection of multiple clusters (C1, C2, C3)
- coloring of selected clusters
- rows from selected clusters are colored accordingly and clearly
- disable individual row selection
- add output where clusters are described in Cluster column
- add option to not split by class

**Comment by janezd** [comment]
Issue moved to #4090.
