### ISSUE TITLE
how to deal orange 3 as numpy for association learning?

### ISSUE THREAD

**Issue by PeterXiaoGuo** [biolab/orange3#2984]
##### Orange version

I'm taking data mining course now and my prof. let us to use orange 2 to write codes in python. I find orange's data type is really different from that in numpy. I cannot utilize data smoothly as in numpy or pandas.

Is there any suggestion on it? I just want to find each step to calculate frequent itemsets and find the association rule (calculate confidence by removing a item)... 

I think I have spent 5 hours to work on this non-flexible library.

Thank you very much... It's the first time that I really feel angry and disappointed on a python library.

**Comment by PeterXiaoGuo** [comment]
I know orange 3 is released and it's a GUI... 

but,

1. how could i write programs in codes.
2. how could i pick data smoothly like in numpy? after I read "data" from ".basket", it seems I can do nothing but to use some really fixed api......................

**Comment by kernc** [comment]
> A python library

Orange is not.

-----

With Orange 3, association rules mining is separated in Orange3-Associate, which can be (should be) used conveniently with numpy. http://orange3-associate.readthedocs.io/en/latest/scripting.html

**Comment by duohappy** [comment]
Associate rule in Orange3 is really good. If you want to use it in Orange3 GUI, you must have a file of special format. If you want to use it in python script file, help document is enough clear.
