### ISSUE TITLE
SQL Backend Widget: add support for cx_Oracle or pyodbc

### ISSUE THREAD

**Issue by andrenam** [biolab/orange3#2985]
##### Orange version
3.11.0

##### Enhancement / Feature request
Orange supports psycopg2 for PostgreSQL and pymssql for MS SQL Server. 
It would be nice if cx_Oracle for Oracle (or pyodbc) would be supported.

**Comment by kernc** [comment]
Oracle connector has gotten into Orange3-Prototypes add-on: https://github.com/biolab/orange3-prototypes/pull/118
Install it from source to test it. :+1:
