### ISSUE TITLE
merge data widget does not work well in my computer

### ISSUE THREAD

**Issue by duohappy** [biolab/orange3#2987]
##### Orange version

orange 3.11

##### Expected behavior
I start studying kinds of Orange widget. In help document [https://docs.orange.biolab.si/3/visual-programming/widgets/data/mergedata.html](url), the merge data widget works well

##### Actual behavior
In "find matching rows", I can't get dropdown box including "name".
I tried it in windows 10 and Ubuntu 16.04 installed on virtualbox, and failed to get right result.
![](http://op7cim63s.bkt.clouddn.com/Orange_merge_data.png)

**Comment by kernc** [comment]
[Toothed frog](https://www.newscientist.com/article/dn25100-zoologger-sabre-toothed-frog-is-an-evolutionary-loner/) has a portrait.

**Comment by ales-erjavec** [comment]
The zoo data set is from http://archive.ics.uci.edu/ml/datasets/zoo (see the comment about the frog). It should not change.

**Comment by duohappy** [comment]
>The reason name is not available with Find matching rows and Concatenate is that it is not **unique** (there are two frogs in the first dataset, do not ask me why)
thank you for reminding me of that.

I think that merging data should not require **unique** condition, which is also not found in help file. It will be better to merge data like SQL(inner join, left join, outer join) or Pands.merge
``` python
import pandas as pd
df1 = pd.DataFrame({'a':[1,1,2,2],'b':['p','p','y','y']})
df2 = pd.DataFrame({'a':[1,1,2,2],'c':['t','t','o','o']})
df1.merge(df2, how='inner', on='a')
'''
   a  b  c
0  1  p  t
1  1  p  t
2  1  p  t
3  1  p  t
4  2  y  o
5  2  y  o
6  2  y  o
7  2  y  o
'''
```

**Comment by ajdapretnar** [comment]
@astaric I am also mostly thinking about pandas when merging, so I am indeed having problems with Orange here. But I am happy to update the documentation for now.

**Comment by astaric** [comment]
Sure, could you open a new issue describing how the merging should work for non-unique values and link it here? Possibly with examples for each of the three merges.
