### ISSUE TITLE
MSI file for SCCM deployment

### ISSUE THREAD

**Issue by darylnoguera** [biolab/orange3#2990]

**Comment by ajdapretnar** [comment]
@ales-erjavec Is this something to consider?

**Comment by Wolfereign** [comment]
This or an offline silent installer with everything bundled in would work.  Unfortunately the miniconda/anaconda installer is not completely silent.

**Comment by ales-erjavec** [comment]
The installers respect the standard NSIS flags `/S` (silent) and `/D=destination`.

To install for current user
```batch
Orange3-SomeVersion.exe /S /CurrentUser /D=%INSTALLPATH%
```

For all users (must be run with Admin privileges)
```batch
Orange3-SomeVersion.exe /S /AllUsers /D=%INSTALLPATH%
```
