### ISSUE TITLE
Applying domain to a new data table works in Python interpreter, but not Python Script widget

### ISSUE THREAD

**Issue by ThirstyGeo** [biolab/orange3#2995]
##### Orange version

Orange 3.11

##### Expected behavior
Produce orange data table in both Canvas and via code

##### Actual behavior
The code below works in an Ipython notebook, but not in the Python Script widget (in canvas)

##### Steps to reproduce the behavior

    import Orange
    print(Orange.version)
    import numpy as np
    from Orange.data import Domain, Table
    from imblearn.over_sampling import SMOTE

    # below code only for code window, not for scripting widget in canvas
    #in_data = Orange.data.Table('WORKING_temp.csv')

    df = in_data.copy()

    # set variables for SMOTE
    sm = SMOTE(random_state=42)

    # get table of data (X) and class variables (y)
    X, y = df.X, df.Y

    # resample data and classes
    X_res, y_res = sm.fit_sample(X, y)

    df.X = X_res
    df.Y = y_res

    temp = Orange.data.Table(df.X, df.Y)
    temp.domain = df.domain

    out_data = Orange.data.Table(temp)

##### Additional info (worksheets, data, screenshots, ...)
There is likely a better way to construct the final table for out_data. The error raised in Canvas is related to the number of array headers (domain names) in the original data table not matching the number of columns in the derived data table. Note that the SMOTE function changes the number of rows (it's for class imbalance fixing), and so I also can't simply replace the original in_data.X and replace with the resampled data (as the index will be off)

**Comment by astaric** [comment]
You can try replacing
```
temp = Orange.data.Table(df.X, df.Y)
temp.domain = df.domain
out_data = Orange.data.Table(temp)
```
with 
```
d = Domain(df.domain.attributes, df.domain.class_vars)
out_data = Orange.data.Table(d, X_res, y_res)
```

You should consider .X, .Y and .domain to be read-only, and construct a new table for the balanced dataset.

**Comment by ThirstyGeo** [comment]
This worked perfectly, thanks!

I have posted the solution to StackExchange, should anyone stumble onto this thread:
https://datascience.stackexchange.com/questions/30206/scripting-code-for-class-imbalance-in-biolabs-orange/30353#30353

I know that there are scripting tutorials for Orange, but these seem to focus on common recipes or helpful examples. What is the best place to see all attributes, keywords, and parameters that are specific to working with scripts within Orange canvas?

**Comment by astaric** [comment]
There is nothing specific to using the scripting library in canvas, but you need to make sure your code works with many different kinds of tables.

In your case, my guess is that when file was read through file widget, one of the features was marked as meta - a feature you do not learn from but would like to see as a label/color in some visualizations. This is done by changing the role in the bottom part of the file widget.

The old code for construction of balanced table did not account for that, as it created a new table with X and Y (and no meta data), but passed the original domain that declared that there is one meta variable. This discrepancy between data and domain lead to the error you encountered. The fix I proposed constructs a new domain that matches the data.

**Comment by astaric** [comment]
Since the problem you had is fixed, I am closing this issue.

Balancing of datasets looks like something that could be used to others as well. If you would consider wrapping it into a standalone widget, you can submit it to the [prototypes repository](https://github.com/biolab/orange3-prototypes).

You already have the code that does the work, you just need to define the gui. For a guide on how to do that, see the [Widget Development Documentation](http://orange-development.readthedocs.io)

**Comment by Sudharshan96** [comment]
Hello guys need help in how to install imblearn in orange tool
