### ISSUE TITLE
File: Column with ? as missing values read as string

### ISSUE THREAD

**Issue by astaric** [biolab/orange3#2997]
Open attached file in Orange (change extension to csv): [text.txt](https://github.com/biolab/orange3/files/1906808/text.txt)

Versions before 400eea9d read the column as numeric, versions after as text.

IMHO, it should be read as numeric.

**Comment by kernc** [comment]
> IMHO, it should be read as text.

Numeric.

Or, better yet, missing value akin to the rest of the column values.
