### ISSUE TITLE
Installed Addon from terminal but widgets not appearing

### ISSUE THREAD

**Issue by bhrigs** [biolab/orange3#3004]
##### Expected behavior
Show the installed addon as a new widget in the toolbox in Orange window

##### Actual behavior
Installed addons from command prompt (bioinformatics and educational) but the new widgets are not appearing in the toolbox even after restarting orange

##### Steps to reproduce the behavior
install addons from command prompt and restart orange

**Comment by kernc** [comment]
Duplicate of https://github.com/biolab/orange3/issues/3001!

**Comment by PrimozGodec** [comment]
Look my answer at https://github.com/biolab/orange3/issues/3003
