### ISSUE TITLE
Addons: Sort packages in a predictable way

### ISSUE THREAD

**Issue by astaric** [biolab/orange3#3007]
<img width="470" alt="screen shot 2018-04-19 at 06 58 08" src="https://user-images.githubusercontent.com/588601/38972127-1488eb0a-439f-11e8-8040-e6e0c45ffd10.png">

It does not look like they are sorted by stability, nor alphabetically. If the current order is not deliberate, I would go with alphabetical sort.

**Comment by markotoplak** [comment]
Fixed in #3013
