### ISSUE TITLE
Test&Score Recall results differ from calculated Confusion Matrix values

### ISSUE THREAD

**Issue by Erebusbelow** [biolab/orange3#3021]
##### Orange version

Version 3.4.1

##### Expected behavior
Recall should be True Positive/Actual Yes = 1011/2140 = 0.47. In the evaluation results I see 0.774. I thought maybe this was switched because of the target class being "no", which might be 4107/4470 = 0.92, also not correct. I don't see how this is being calculated from the confusion matrix.

##### Actual behavior
![image](https://user-images.githubusercontent.com/18754768/39368347-503e79ee-4a07-11e8-95bb-d1604ea206c0.png)

##### Steps to reproduce the behavior
1. Load titanic.tab and make "survived" target feature
2. Select columns > remove age from features > target variable = "survived"
3. Test & Score widget > Random Sampling repeat 10 times, training set  = 70%, stratified
4. Logistic Regression > Ridge C = 0.600

##### Additional info (worksheets, data, screenshots, ...)
Used the titanic.tab data provided with Orange

Please let me know if I can provide any more details.

**Comment by PrimozGodec** [comment]
Hello, you are right about assumption how the recall is calculated in case of target class `No` is selected (recall should be 0.92). If you select `Yes` as a target class you should get 0.47 in your case. 

You are using an old version of Orange (the current version is 3.13.0) and bugs in `Test & Score` widget has been fixed after the version 3.4.1 (the version you use). Updating Orange to the newest version should fix your issue.
