### ISSUE TITLE
[BUG] .ows drag and drop doesn't work on Win

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3034]
##### Orange version

3.14.0

##### Expected behavior
Can drag and drop .ows files in any OS.

##### Actual behavior
On Win I can't drag and drop workflows. On OSX, I can.

##### Steps to reproduce the behavior
Drag and drop an .ows file onto canvas in Windows.

**Comment by ales-erjavec** [comment]
I can duplicate this, but only when running orange for the first time immediately from the installers' finish page (i.e. *Start Orange* check box in the installer). If I run orange afterwards DnD works fine.

**Comment by ajdapretnar** [comment]
This is true. What a strange bug. If you think this is not relevant, you can close the issue.

**Comment by ajdapretnar** [comment]
Can I consider this a wontfix?

**Comment by janezd** [comment]
Yes. :)
