### ISSUE TITLE
Crash: GtkDialog mapped without a transient parent. This is discouraged.

### ISSUE THREAD

**Issue by valeriy67** [biolab/orange3#3037]
##### Orange version
3.13.0

##### Expected behavior
Open an report in module File,  DataTable, k-Means and other/

##### Actual behavior
python3 -m Orange.canvas

##### Orange version
3.13.0

##### Actual behavior
GtkDialog mapped without a transient parent. This is discouraged.
./Orange/statistics/util.py:327: RuntimeWarning: All-NaN slice encountered  
 np.nanmin(X, axis=0),
./Orange/statistics/util.py:328: RuntimeWarning: All-NaN slice encountered
  np.nanmax(X, axis=0),
./Orange/statistics/util.py:329: RuntimeWarning: Mean of empty slice
  np.nanmean(X, axis=0) if not weighted else weighted_mean(),

**Comment by ajdapretnar** [comment]
I don't think this is an Orange problem.
https://www.linuxquestions.org/questions/debian-26/%5Bsolved%5D-gtk-message-gtkdialog-mapped-without-a-transient-parent-this-is-discouraged-4175550278/

Does Orange crash because of this or it is just a warning?

**Comment by kernc** [comment]
It's not, and these are mostly harmless warnings anyway.
