### ISSUE TITLE
Orange Go Browser does not accept reference set

### ISSUE THREAD

**Issue by eifos13** [biolab/orange3#3045]
I have problems using a reference data set in Orange GO Browser. It accepts data from a data file, but not as a reference set. 

##### Orange version
3.13.0

##### Expected behavior
Should compare data against data from reference st.

##### Actual behavior
Does not include reference set and produces an error. 

![error reference data](https://user-images.githubusercontent.com/39738495/40668447-74657e8a-635c-11e8-9001-b3e6560ce80f.JPG)

**Comment by ajdapretnar** [comment]
This should probably be better reported in [Orange3-Bioinformatics](https://github.com/biolab/orange3-bioinformatics). @JakaKokosar
