### ISSUE TITLE
AttributeError: module 'bottleneck' has no attribute 'anynan'

### ISSUE THREAD

**Issue by arunshaji95** [biolab/orange3#3046]
##### Expected behavior
It should be able to use any model listed in the GUI.

##### Actual behavior
When data is given to any model in the gui, there is an error symbol is showing. Upon double clicking the model, it shows an error traceback.

##### Steps to reproduce the behavior

1. Open canvas using ```python -m Orange.canvas```.
2. Start a new project.
3. Add a file input to canvas.
4. Add any model to canvas(Eg: CN2 rule induction).
5. Draw an arrow connecting file and model.
6. An error pop up is coming up.

##### Additional info (worksheets, data, screenshots, ...)
Traceback
```
Traceback (most recent call last):
  File "/home/arun/lab/ML/orange3/Orange/canvas/scheme/widgetsscheme.py", line 907, in process_signals_for_widget
    handler(*args)
  File "/home/arun/lab/ML/orange3/Orange/widgets/utils/sql.py", line 31, in new_f
    return f(widget, data, *args, **kwargs)
  File "/home/arun/lab/ML/orange3/Orange/widgets/utils/owlearnerwidget.py", line 141, in set_data
    self.update_model()
  File "/home/arun/lab/ML/orange3/Orange/widgets/model/owrules.py", line 329, in update_model
    self.model = self.learner(self.data)
  File "/home/arun/lab/ML/orange3/Orange/base.py", line 112, in __call__
    data = self.preprocess(data)
  File "/home/arun/lab/ML/orange3/Orange/base.py", line 138, in preprocess
    data = pp(data)
  File "/home/arun/lab/ML/orange3/Orange/data/filter.py", line 84, in __call__
    return data._filter_has_class(self.negate)
  File "/home/arun/lab/ML/orange3/Orange/data/table.py", line 1154, in _filter_has_class
    retain = bn.anynan(self._Y, axis=1)
AttributeError: module 'bottleneck' has no attribute 'anynan'
```
![Screenshot](https://user-images.githubusercontent.com/19943684/40762088-aaf61dd6-64bc-11e8-86cd-0ea7c4c5f8f2.png)

**Comment by kernc** [comment]
Is it possible your bottleneck version is pre 1.0.0? Try `pip3 install -U --no-deps bottleneck` (with pip from the same env Orange is installed in).

**Comment by arunshaji95** [comment]
@kernc:  I am using Bottleneck==1.2.1. Tried uninstalling bottleneck, still, the issue is there.

**Comment by kernc** [comment]
Is bottleneck compiled correctly? What does `pip3 uninstall bottleneck ; pip3 install bottleneck` print?

**Comment by arunshaji95** [comment]
@kernc: I have tried that too.
```
$ pip3 uninstall bottleneck
Uninstalling Bottleneck-1.2.1:
    Would remove:
orange3env/lib/python3.5/site-packages/Bottleneck-1.2.1.dist-info/*
orange3env/lib/python3.5/site-packages/bottleneck/*
Proceed (y/n)? y
  Successfully uninstalled Bottleneck-1.2.1
```
After that I have installed bottleneck on the same environment.
```
$ pip3 install bottleneck
Collecting bottleneck
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from bottleneck) (1.11.0)
recommonmark 0.4.0 has requirement commonmark<=0.5.4, but you'll have commonmark 0.7.5 which is incompatible.
Installing collected packages: bottleneck
Successfully installed bottleneck-1.2.1
```
But still the issue is there.

**Comment by kernc** [comment]
Well, that's not much to work with. This is the kind of _works for me_ issue that is much easier to investigate by yourself than us.

Perhaps run `python -m site` and see if you can find another instance of defunct bottleneck in any of the listed paths. `site.py` on Debian-based distros is known to behave funny wrt assembling those paths.

**Comment by arunshaji95** [comment]
I have checked inside bottleneck library. Uninstalled `Bottleneck==1.2.1` and installed `Bottleneck==1.0.0`. Now it works. Thank you @kernc  for your guidance.
