### ISSUE TITLE
K-means: crahses on large data sets

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3050]
##### Orange version

3.14.dev

##### Expected behavior
K-means works for large data.

##### Actual behavior
On ~54000 rows, k-Means crashes with segfault.

##### Steps to reproduce the behavior
File (https://www.kaggle.com/zynicide/wine-reviews --> winemag-data-130k-v2.csv) - Select Rows (country is US) - k-Means.

**Comment by thocevar** [comment]
This data set has several discrete variables with a large number of values. K-means performs continuization, which inflates the number of variables to ~3000 and you end up with a table of size 1.2 GB.

**Comment by ajdapretnar** [comment]
Shoot. Is there any sensible way around this? 🤔

**Comment by janezd** [comment]
Not really. K-means can't cope with discrete variables, AFAIK.
