### ISSUE TITLE
Scatter Plot, MDS: selection of groups in wrong colors

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3#3051]
Group selections in scatter diagrams are marked in a wrong color. For instance, take Iris and group-select two subsets (press shift when selecting the second group):

![screen shot 2018-06-04 at 13 37 46](https://user-images.githubusercontent.com/726604/40915460-7bb6ed8c-67fc-11e8-8593-f31000e877e7.png)

Take feed the selected data into another scatterplot, and select Group for color:

![screen shot 2018-06-04 at 13 38 44](https://user-images.githubusercontent.com/726604/40915507-9c8a6a98-67fc-11e8-9154-3f7cb83fbb11.png)

Notice that in selection red and green colors were used to mark the points of different groups, while the rest of Orange uses different coloring palette for first two discrete classes.

**Comment by PrimozGodec** [comment]
An issue is connected with the issue in an image grid (image-analytics) https://github.com/biolab/orange3-imageanalytics/issues/89
