### ISSUE TITLE
Mosaic Display: legend falls out of view

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3052]
##### Orange version

3.14.dev

##### Expected behavior
Legend is clearly visible.

##### Actual behavior
When many items in legend, legend falls out of view.

##### Steps to reproduce the behavior
File - Mosaic
data: https://www.kaggle.com/usdot/pipeline-accidents/data
color by: Cause Category

##### Additional info 
While viewing so many values is likely impractical, Mosaic is still one of the nicer visualizations for such purpose.

**Comment by ajdapretnar** [comment]
<img width="1077" alt="screen shot 2018-06-29 at 12 08 24" src="https://user-images.githubusercontent.com/12524972/42087010-27f61040-7b95-11e8-93c8-7c12bc16578e.png">

Legend currently horizontal. Perhaps have it on the right side, where each color is in a new line? Similar to Scatter Plot? Also limit legend display to 10 items, 9 + other. Like in Scatter Plot, so there is consistency.

**Comment by janezd** [comment]
The legend below wastes less space than one beside the graph -- with everything under the legend being empty.

An alternative suggestion, though I'm not sure I like it: instead of a legend there could be a list box in the control area, in which the user would be able to select (by clicking, which selects/deselects) an element the classes that are actually shown. We may not actually need this functionality, but it serves as a de facto legend which is placed where we have too much space (the control area is mostly empty) instead of in the graph, where it would just add a lot of white space.

If we decide for this, the `send_report` method needs to add a legend after the plot.

**Comment by markotoplak** [comment]
I agree with Janez: the legend is currently placed well. The easiest fix might be to elide text.

**Comment by ajdapretnar** [comment]
Yes, it's a good point. Elide or break the legend and place it into a new line where it falls out of view?

**Comment by janezd** [comment]
I implemented (with a few glitches) wrapping of legend items. However, I don't know how to arrange the items. Currently they are centered

<img width="453" alt="Screenshot 2019-06-07 at 11 25 40" src="https://user-images.githubusercontent.com/2387315/59094858-60098300-8917-11e9-9419-ffddaf17b571.png">

or left-aligned

<img width="446" alt="Screenshot 2019-06-07 at 11 33 43" src="https://user-images.githubusercontent.com/2387315/59095201-2dac5580-8918-11e9-829e-4ca350b9a998.png">

Another option is a grid

<img width="517" alt="Screenshot 2019-06-07 at 11 31 20" src="https://user-images.githubusercontent.com/2387315/59095265-52a0c880-8918-11e9-8825-9ca79d5de3ba.png">

but this would break if one (or more) labels are significantly longer than another.

An option is to use a grid *unless* the longest label is twice the width of the median label, in which case it switches to left-aligned.

Opinions?

**Comment by janezd** [comment]
Currently = in my current implementation. "Currently" in Orange they are of course in a single line and fall out of view, as the issue describes.

**Comment by ajdapretnar** [comment]
I like either of the first two options. Perhaps solution to long labels is simply elide and tooltip on hover?

**Comment by janezd** [comment]
Here. When it fits into a single line, it's centered. If it doesn't, it's put into grid. If this grid would have just a single column, it's left-aligned. See the animation.

![mosaic](https://user-images.githubusercontent.com/2387315/59098806-9d730e00-8921-11e9-8a5e-36d96c5a9f73.gif)
