### ISSUE TITLE
Feature Constructor: easier categorical features

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#3056]
Categorical features are hard to create, because currently:
- the user has to list all possible values
- and then the expression has to return indices for the list of values

I propose that the expression could directly return strings and that possible values were automatically created.

**Comment by janezd** [comment]
@markotoplak, you mean that a list of possible values would be created from the values returned by the function on the given input data? I like the idea, but what happens if the function returns some values that don't occur on the input data?

Another thought: it may be easier for a function to return int's than strings. (But then it can always use those ints as indices into an array.)

**Comment by markotoplak** [comment]
I was wrong. Indices are not the only way! I tried creating a feature with values A and B on iris. So my list of values was: `A, B`

Works:
- `0 if sepal_length < 5 else 1` (as shown in the documentation) 
- `A if sepal_length < 5 else B` (surprisingly! I never dared trying it)

Does not work:
- `"A" if sepal_length < 5 else "B"`

I think we should make the last example work.

Then, the list of values could be optional: it could be obtained by executing the expression on the data. For new data (in later domain transformations), if the expression returned a new value, we should make it a "?".

**Comment by ajdapretnar** [comment]
I quite often want to create categorical variables from text, say:

    text.split(';')[0]

But then I have to list all possible values of this attribute without often knowing what they might be. Perhaps in such cases categorical variables aren't the best option ("If you can't list them, don't have them."), but still...

Two other issues with Feature Constructor.

- It doesn't support creating datetime variables. https://github.com/biolab/orange3/issues/2900
- Sometimes one would like to define a new variable based on all existing variables say, sum of values or count non-zero). Currently not possible.
