### ISSUE TITLE
ROC Analysis widget: show thresholds

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#3057]
The widget does not provide any way to get the threshold that was used for a point on curve. I would suggests a tooltip.

Threshold is important to understand results of cost optimization.

**Comment by astaric** [comment]
One way to implement tooltips with ScatterPlotItems: https://groups.google.com/forum/#!topic/pyqtgraph/3osqs25pEIc

**Comment by ales-erjavec** [comment]
This was done in gh-3172
