### ISSUE TITLE
Addon - show only trusted add-ons

### ISSUE THREAD

**Issue by pokro** [biolab/orange3#3059]
##### Orange version
3.13

##### Expected behavior
When going to Options -> Add-ons, I should see an option that says "show only trusted add-ons", and be able to turn that off to see more add-ons.

##### Actual behavior
There is no option that says "show only trusted add-ons", so I can only see a small list of 'trusted' add-ons.

##### Steps to reproduce the behavior
Opening the add-on menu.

**Comment by ajdapretnar** [comment]
There should be a button on the right "Add more...". This is where you enter other add-ons with their pip install command, e.g. pip install orange3-recommendation.
