### ISSUE TITLE
Box Plot documentation is incorrect

### ISSUE THREAD

**Issue by thocevar** [biolab/orange3#3065]
Box Plot documentation has mean, median, quantiles and standard deviation mixed up.

Standard deviation is centered on the mean and seems to be represented by the solid blue line and not the highlighted area as the documentation suggests. The highlighed area in fact (as usual in box plots) shows the first and third quantile with the yellow line indicating the median value.

How did this go unnoticed so long or did I get something wrong?

**Comment by ajdapretnar** [comment]
These were the answers acquired in a lab-wide survey. :)

I always thought that the dotted line on the left and right were the quantiles. If not, what are they? But I agree, this would go against the standard box plot. Let me know what is correct and I will fix it.

**Comment by thocevar** [comment]
reference: https://github.com/biolab/orange3/blob/master/Orange/widgets/visualize/owboxplot.py#L878
- dotted line extends from minimum to maximum value
- vertical blue line is the mean
- horizontal solid blue line indicates one standard deviation from the mean
- yellow line is the median (second quartile)
- blue box spans from the first to the third quartile
