### ISSUE TITLE
Data Table doesn't display Unicode characters properly

### ISSUE THREAD

**Issue by yurivict** [biolab/orange3#3070]
I connected the search in the "Guardian" widget to "Data Table", and Unicode characters aren't displayed properly in the "Headline" column.

**Comment by janezd** [comment]
@ejmric, weren't you fixing that? I forgot -- is it done? @ajdapretnar?

**Comment by ajdapretnar** [comment]
Fixed in https://github.com/biolab/orange3-text/pull/406.
