### ISSUE TITLE
pypy does't able to read Orange

### ISSUE THREAD

**Issue by AhmedArslan** [biolab/orange3#3073]
##### Expected behavior
I am working on python 2.7 and occasionally run pypy for speed purpose

##### Actual behavior
pypy gives error while trying to run my script to run enrichment analysis with Orange bioinformatics.
How can I make Orange run with pypy?

**Comment by ajdapretnar** [comment]
Orange3 doesn't work with Python 2.7. You will need Python 3+.

**Comment by markotoplak** [comment]
Also, I think Orange might have problems with pypy. Parts of orange are in C and I do not think they would work with anything but cpython.
