### ISSUE TITLE
Problem with miniconda installer

### ISSUE THREAD

**Issue by drakemax** [biolab/orange3#3074]
##### Orange version

tried installing 64 bit win version of conda. 
orange stopped about 3/4 in and said error 1 for conda.
deleted orange folder and tried again.
now trying the  python 34 version install

**Comment by ajdapretnar** [comment]
Could you provide more details? What OS are you using? Win 10? Could you make a screenshot of the error?

**Comment by janezd** [comment]
Closed due to inactivity. Besides, it's an old version and also probably Python 3.4.
