### ISSUE TITLE
Orange reading in new features from Tab-Delimited File

### ISSUE THREAD

**Issue by ChahnaP** [biolab/orange3#3080]
##### Expected behavior

In my tab delimited file I have 65 features and 1 target variable that are numerical and continuous. My data is supposed to be used for regression models. There should be 65 features and 1 target variable in the columns when I upload the file to orange. 

##### Actual behavior
There are actually 68 features, 2 new features called "Feature 1" and "Feature 2" show up that shouldn't be there. Both of them are categorical. Why are these two new features showing up? I counted the amount of variables I put and the amount of domain and attribute types corresponding to each variable. They both add up to 66 so I don't know what the problem is. 

Below I have attached the tab delimited file.

[wekanewregression.txt](https://github.com/biolab/orange3/files/2121002/wekanewregression.txt)

**Comment by kernc** [comment]
I open up the attached file, I get six columns. Seems right.

![screenshot_2018-06-20_22-52-14](https://user-images.githubusercontent.com/684364/41684057-b1c4cdee-74dc-11e8-902e-52a42fc85125.png)

**Comment by ChahnaP** [comment]
Im sorry I uploaded the wrong file. Here is the right one: 
[wekanewregressiontext.txt]
(https://github.com/biolab/orange3/files/2121089/wekanewregressiontext.txt)

**Comment by kernc** [comment]
Fire a spreadsheet editor (LibreOffice Calc or similar) and notice you have two additional Tab characters on lines where ATContent is a round number.

**Comment by kernc** [comment]
For some obscure reason you need to _Options > Reset Widget Settings_.

**Comment by ajdapretnar** [comment]
You seem to have two extra tabs after PE column.

**Comment by markotoplak** [comment]
As this was a case of wrongly formatted file, I am closing the issue.
