### ISSUE TITLE
Segmentation Fault while loading a project from "Recent" form

### ISSUE THREAD

**Issue by lucarebuffi** [biolab/orange3#3081]
##### Orange version
Version: 3.13.0 (git revision: 488803f)

##### Expected behavior

Load a workspace while the "Recent" form is still loading previews should not be a problem

##### Actual behavior

Load a workspace (button Open) while the "Recent" form is still loading previews cause a Segmentation Fault and the application crashes.

##### Steps to reproduce the behavior

Open Orange, click the button "Recent" in the welcome form, then click the button "open" while the form is still loading the previews. You need several recent projects and a slow computer (and be fast).

##### Additional info (worksheets, data, screenshots, ...)

I made a video:

https://www.dropbox.com/s/04q5y6d1zsk89lf/Segmentation_Fault.mov?dl=0

**Comment by ajdapretnar** [comment]
@janezd @lucarebuffi I don't know how to reproduce this. 🤷‍♀️ Is there something we can do about this?

**Comment by janezd** [comment]
As I recall, @lucarebuffi warned us about not using the new version of Qt until they fix some bugs. It may also be related to what @ales-erjavec wrote yesterday about neigh useless versions of Qt on macOs.

I believe (well: hope!) this is no longer relevant.

**Comment by lucarebuffi** [comment]
I'll check it asap. Cheers.
