### ISSUE TITLE
Widget: Distance matrix -> no output

### ISSUE THREAD

**Issue by porenti1** [biolab/orange3#3082]
##### Orange version

3.13

##### Expected behavior
Distance matrix would generate data for scatter plot.

##### Actual behavior
Distance matrix widget does not give output.

##### Steps to reproduce the behavior
Distances -> Distance matrix -> Scatter plot (or Data Table

**Comment by ajdapretnar** [comment]
This is because you need to make a selection in Distance Matrix. This will output selected data instances.

However, I think Selected Data would be a better name for the output, since it would correspond to the rest of the widgets that support selection.
