### ISSUE TITLE
Opening data without column names and Variable.make

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#3087]
A user tried to open multiple unannotated files, which were opened with default feature names (Feature X) and couldn't be concatenated afterwards. Such are files if you use export csv from Matlab.

I checked, and `FileFormat.data_table` explicitly creates anonymous features without `Variable.make`, which makes them incompatible. Why is Orange being so strict (even tests pass if I change it)?

I also checked what happens with the domain if the user edits it in the bottom part of OWFile. There, `.make` is used for all Variable types except for conversion into a DiscreteVariable. 

Does anyone remembers why domain editor creates DiscreteVariable without make? I think it is inconsistent to use .make at file reading and not to use if a user choses to create a variable manually. I know discrete variables are a pain as Variables values depend on file reading order.

For starters, I propose making all non-nominal anonymous features with `.make`.

**Comment by astaric** [comment]
> Why is Orange being so strict (even tests pass if I change it)?
+1 for using make for files without headers

> Does anyone remembers why domain editor creates DiscreteVariable without make?
It used to create all variables without make until https://github.com/biolab/orange3/commit/29ccd88ca59d30fa521223854458a6c18199928f. I chose to change only String/Numeric paths as they are without side effects. Using make for Categorical can introduce new values to existing vars, so simply switching one column to categorical and back to string type can result in another column having some extra values.
