### ISSUE TITLE
Reporting segfaults on Ubuntu 18.04

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#3092]
##### Orange version
Any.

##### Expected behavior
No segfaults when trying to report.

##### Actual behavior
Segfaults

##### Steps to reproduce the behavior
Ubuntu 18.04, virtual environment with python3 without system site packages, PyQt5==5.9.2 installed from pip (binary install). The problem also persists with any PyQt5 I tried.

Open canvas, add File widget, click on report button.

The segfault happens when QWebEngineView is shown. A simpler test: 

`python -c "from PyQt5.Qt import *; app = QApplication([]); w = QWebEngineView();  w.load(QUrl('https://google.com')); w.show(); app.exec_()"`

Can anyone reproduce this?

**Comment by markotoplak** [comment]
The problem seems to be my graphics drivers. 

The tests work If I install pyopengl and then run `python -c "from OpenGL import GL; from PyQt5.Qt import *; app = QApplication([]); w = QWebEngineView();  w.load(QUrl('https://google.com')); w.show(); app.exec_()"`

If I then add `from OpenGL import GL` to webview.py then reports start working normally.

Spyder git repo has an interesting solution that does not require installing pyopengl: spyder-ide/spyder/pull/7029

**Comment by jerneju** [comment]
I have the same problem. Orange crashes on Ubuntu 16.04 in a virtual environment when I try to use Report, Help, or any widget which uses web engine (Word Cloud, Parallel Coordinates). But when I use Anaconda it does not crash.

Spyder git repo's solution does not fix this error on my configuration.

**Comment by markotoplak** [comment]
@jerneju, thank you for the confirmation. Which graphics card do you and which driver does it use?

So, just to be clear, which of these works for you:
-  `python -c "from OpenGL import GL; from PyQt5.Qt import *; app = QApplication([]); w = QWebEngineView(); w.load(QUrl('https://google.com')); w.show(); app.exec_()"` (you need pyopengl  for this)
- `python -c "import ctypes; ctypes.CDLL('libGL.so.1', mode=ctypes.RTLD_GLOBAL); from PyQt5.Qt import *; app = QApplication([]); w = QWebEngineView(); w.load(QUrl('https://google.com')); w.show(); app.exec_()"`

**Comment by ajdapretnar** [comment]
We had the same issue (I think) at our workshop (Ubuntu platform). The user tried Corpus Viewer from Text and Interactive k-Means from Educational and they both resulted in segfault. Could this be the same issue?

**Comment by markotoplak** [comment]
@ajdapretnar, I think it could be.

**Comment by jerneju** [comment]
@markotoplak :

NVIDIA GeForce that is all I know.

Now it works. I have downgraded **PyQt5** from _5.10.1_ to _5.10_. But maybe I had a different issue.

**Comment by markotoplak** [comment]
@jerneju, so Orange still crashes if used without changes but both test commands work? Thanks!

**Comment by jerneju** [comment]
@markotoplak : I tested the second command. It crashes when I have _5.10.1_ installed but it works on _5.10_.

**Comment by ales-erjavec** [comment]
@jerneju You are probably seeing https://github.com/biolab/orange3/issues/3015

**Comment by lanzagar** [comment]
Should be fixed by #3100
