### ISSUE TITLE
BoxPlot: Hide groups with no instances

### ISSUE THREAD

**Issue by astaric** [biolab/orange3#3094]
When BoxPlot displays filtered data, grouped by a variable that has many different values (state, country, ...), but many of them are not present in the dataset, an empty row is created for each of them.

This can be worked around by including a purge domain widget before the boxplot, but I would prefer if boxplot could do this (semi) automatically. The same problem was present in scatterplot where the legend displayed all possible values but has since been fixed to include only the values present in data.

In the following workflow (using `cyber-security-breaches` documentation dataset), the first boxplot is used to select only instances with state AR, which are then displayed in the second boxplot. The suggested change would result in only the AR row being drawn in the second boxplot

<img width="1398" alt="screen shot 2018-06-26 at 23 34 46" src="https://user-images.githubusercontent.com/588601/41940616-9cba7798-7999-11e8-9cd0-108ebc45f1c8.png">

**Comment by ajdapretnar** [comment]
+1 for this issue!
