### ISSUE TITLE
Replicable workflows

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#3103]
Same data set + same algorithm = same results, unless explicitly randomized

So we have to set random seed in widgets to some fixed value by default. I propose these to saved as widget setting `random_state` (an integer).

Widgets that need changing:
- [ ] Data Sampler need a default Replicable sampling as chosen by default
- [x] k-means needs a set random seed #3075
- [X] Random forests already have a `random_state` setting
- [ ] Is this an issue in Test&Score? #2035
- [ ] Logistic regression with liblinear solver (used in the widgets) can be stochastic

There is still a question whether we want to expose these seeds. Would perhaps be the Data Sampler (which could shuffle the data if we allow the proportion to go to 100%) be enough for showing effects of randomness?

**Comment by kernc** [comment]
Could we make our "Learners" have a default param `random_state=0` (instead of `=None`). It's simple but covers a lot.

**Comment by janezd** [comment]
#3955 solves the first point and sets random seed for the last point - logistic regression. Is there another source of randomness within the solver?

Test & Score is already non-random, I think.

Does this close the issue? If we want to make all workflows replicable, somebody must comb through all the code. The task may be neigh impossible. For instance, even using `max(d, key=d.get)` to find the dict key belonging to the maximal value may yield random results.

**Comment by markotoplak** [comment]
I think for LR this should be it. By default, sklearns  `random_state` is None and we usually leave it as default.

Should we fix such random seeds only in widgets or in the library and we could then leave widgets as they are?

Also PCA (and probably many other projection) would need to have random_seed fixed by default, because we are using a randomized variant of it for speed. Just last week I was wondering for a while why I was getting different results.

**Comment by markotoplak** [comment]
I checked this a bit. So, in the library, we are currently using `random_state=None` everywhere but in pca.randomized_pca(), CrossValidation(), ShuffleSplit(). There, the default is 0.
