### ISSUE TITLE
Error when attempting to decrypt the wallet kdewallet using GPG

### ISSUE THREAD

**Issue by yurivict** [biolab/orange3#3120]
The version 3.14 now keeps popping up this message:
```
Error when attempting to decrypt the wallet kdewallet using GPG. If you're using a SmartCard, please ensure it's inserted then try again.

GPG error was Decryption failed`
```

This is repeated despite pressing "Cancel".
You should only complain once, add a button "Ignore this in the future".

**Comment by kernc** [comment]
Not sure, but this sounds like something to do with kdewallet via [keyring package](https://github.com/jaraco/keyring) Orange depends on.

What is certain is that the dialog you see is not under our control.

**Comment by jaraco** [comment]
Can you confirm the issue did not occur with the release prior to 3.14? If so, can you identify what that implies for keyring and other possible dependencies?

**Comment by janezd** [comment]
Closed for inactivity.
