### ISSUE TITLE
HierClust: implement scaling when resizing the window

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3125]
##### Orange version

3.15.dev

##### Idea
Would it be possible to scale the dendrogram also horizontally, not just vertically? Zoom scales vertically, which is fine. But sometimes, we would want to shrink the window further, especially when hiding the control area. It would be nice to scale the entire dendrogram when resizing the window. But of course not past some sensible size.

##### Steps to reproduce the behavior
Use Grades from Datasets.
Perform Hierarchical Clustering.
Scale the window to the smallest size.
Hide Control area.
Visualization gets bigger, but the user cannot resize it any more that the fixed size (horizontally, vertically you can).

**Comment by janezd** [comment]
@ajdapretnar, I don't really understand this one. You mean shrinking or expanding? I can expand (horizontally) across the entire screen, or shrink to a reasonably small limit. While doing this, the dendrogram scales horizontally to fit.

Has this already been fixed or did you have something else in mind?

**Comment by ajdapretnar** [comment]
I don't think I can remember what exactly I had in mind.
