### ISSUE TITLE
Additional uncommited files in 3.14.0 source on pypi

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#3137]
##### Orange version
orange3==3.14.0 source package from pypi

##### Actual behavior
There are additional files in there. I saw them unexpectedly because canvas complained about a missing dependency. I built a package myself with `python setup.py sdist` and found these additional files in our distributed version:

Only in Orange3-3.14.0: appveyor.yml
Only in Orange3-3.14.0: benchmark
Only in Orange3-3.14.0: .ci_tools
Only in Orange3-3.14.0: .codeclimate.yml
Only in Orange3-3.14.0: codecov.yml
Only in Orange3-3.14.0: conda-recipe
Only in Orange3-3.14.0: .coveragerc
Only in Orange3-3.14.0/distribute: icon-256.png
Only in Orange3-3.14.0/distribute: icon-48.png
Only in Orange3-3.14.0: doc
Only in Orange3-3.14.0: .gitattributes
Only in Orange3-3.14.0: .github
Only in Orange3-3.14.0: .gitignore
Only in Orange3-3.14.0/Orange/canvas: source-revision.txt
Only in Orange3-3.14.0/Orange/canvas: WidgetTabs.txt
Only in Orange3-3.14.0/Orange/datasets: philadelphia-crime.csv.xz
Only in Orange3-3.14.0/Orange/distance: distances.md
Only in Orange3-3.14.0/Orange/distance/tests: calculation.xlsx
Only in Orange3-3.14.0/Orange/ensembles: stack.py
Only in Orange3-3.14.0/Orange/evaluation: interpret.py
Only in Orange3-3.14.0/Orange/widgets/data: owdatasets.old.py
Only in Orange3-3.14.0/Orange/widgets/evaluate: owexplain.py
Only in Orange3-3.14.0/Orange/widgets/model: owstack.py

Does anyone know what went wrong? @lanzagar, were you doing this release? If so, how did you generate the pypi package?

**Comment by lanzagar** [comment]
Two problems here:
1) completly my fault, I ran python setup.py sdist in a dirty working dir, which included extra untracked files
2) for some reason, even when running the command in a clean repository, I get a .tar.gz with tracked files like .gitignore and the icons in distribute/ that shouldn't be included?

**Comment by ales-erjavec** [comment]
Please uninstall and blacklist setuptools-git.

**Comment by lanzagar** [comment]
I also discovered it was this package that was causing problems.
Is it possible to make sure (in our setup.py) that it is not used even if installed? I can uninstall it, but I don't remember even installing it explicitly, and I think creeps its way onto quite a few systems like that.

One option is to add exclude directives to MANIFEST for tracked files we do not want to distribute, but that requires some upkeep :/

**Comment by lanzagar** [comment]
Fixed in Orange 3.15
