### ISSUE TITLE
The splitter that hides control panel is not shown on Windows

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#3143]
On Macs, for example, we see a good enough visual indication of the splitter:

![splitter](https://user-images.githubusercontent.com/552182/42993347-6ef43a68-8c0b-11e8-947d-5f8c24491f06.png)

On stock Ubuntu, less so:

![splitter_ubuntu](https://user-images.githubusercontent.com/552182/42993363-7dc15e5e-8c0b-11e8-99a9-aaed8a697698.png)

While on Windows we only see a cursor change on mouse over.

As we are using the splitter in a less standard way, for showing and hiding something, we could go for some custom visual that would be the same on all platforms.

**Comment by thocevar** [comment]
I've just tried this and it's rather tricky. You can set the splitter's style `__splitter.setStyle(QStyleFactory.create("fusion"))` to one of available styles, which depend on your platform. On my windows machine it's "windows" or "fusion". The latter looks like your Ubuntu version.

Another option is to set the style of the handle using stylesheets (`setStyleSheet("background-color: red")`). Unfortunatelly, it seems that some styles ignore certain stylesheet parameters as I can set the background color but not a background image.

At this point, I'm a bit out of my Qt depth.

**Comment by janezd** [comment]
On Windows, the splitter is thinner. We can have either a smaller indicator 

![narrow-splitter](https://user-images.githubusercontent.com/2387315/71419507-12185a80-2670-11ea-81fb-59c21cccc3f2.gif)

(enlarge the picture)

or we can make the splitter wider. 

![wider-splitter](https://user-images.githubusercontent.com/2387315/71419518-1b092c00-2670-11ea-809d-4aa47a8b3cfb.gif)

I guess I like the narrow one - in my temporary opinion it is just bit enough to perhaps tell the user that there's something to click there. @markotoplak?

Should anybody wish to play: the following code needs to be added to the `_Handle` class in widget.py.

Narrow:

```python
        class _Handle(QSplitterHandle):
            def paintEvent(self, event):
                super(QSplitterHandle, self).paintEvent(event)
                painter = QPainter(self)
                painter.setBrush(QColor(192, 192, 192))
                painter.setPen(QColor(160, 160, 160))
                painter.drawEllipse(self.width() / 2 - 1, self.height() / 2 - 1, 2, 2)
```

Wide:

```python
        class _Handle(QSplitterHandle):
            def minimumSizeHint(self):
                size = super().minimumSizeHint()
                size.setWidth(10)
                return size

            sizeHint = minimumSizeHint

            def paintEvent(self, event):
                super(QSplitterHandle, self).paintEvent(event)
                painter = QPainter(self)
                painter.setBrush(QColor(192, 192, 192))
                painter.setPen(QColor(160, 160, 160))
                painter.drawEllipse(self.width() / 2 - 2, self.height() / 2 - 2, 4, 4)
```

(We would of course add a condition to run this only on Windows.)

**Comment by janezd** [comment]
> As we are using the splitter in a less standard way, for showing and hiding something, we could go for some custom visual that would be the same on all platforms.

Makes sense. The circle that we have now is not recognizable, I wouldn't be tempted to click it.

What about this -- on all platforms?

![out](https://user-images.githubusercontent.com/2387315/71448946-144be900-2744-11ea-979b-e9c6f7038d4c.gif)

**Comment by ajdapretnar** [comment]
Very much in favour of the little arrow.

**Comment by janezd** [comment]
See https://github.com/biolab/orange-widget-base/pull/33.

**Comment by janezd** [comment]
Fixed in https://github.com/biolab/orange-widget-base/pull/33.
