### ISSUE TITLE
Appveyor constantly failing

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3149]
Appveyor is reporting the same issue over and over, even for trivial PRs.
ImportError: cannot import name '__check_build'

Could someone please check, because now most of our tests are failing and it is super annoying.

**Comment by ales-erjavec** [comment]
This was already fixed in #3139. Old pull requests that failed just need to be rebuild.

**Comment by ajdapretnar** [comment]
Gotcha.
