### ISSUE TITLE
Version Numpy 1.9.3 installing some Add-ons

### ISSUE THREAD

**Issue by dgasper11** [biolab/orange3#3153]
The issue is about add-ons but I consider it relevant.

##### Orange version
3.14

Windows 7 Ultimate - 32 bits

##### Expected behavior
Install all add-ons

##### Actual behavior
Fails to install Add-ons:

1. Geo
2. Prototypes
3 . Network
4. Timeseries

All the other were installed without problems

##### Steps to reproduce the behavior

Just try to install add-ons on 3.14 version.

##### Additional info (worksheets, data, screenshots, ...)
The Error message:

Could not find a version that satisfies the requirement numpy==1.9.3 (from versions: 1.10.4, 1.11.0, 1.11.1rc1, 1.11.1, 1.11.2rc1, 1.11.2, 1.11.3, 1.12.0b1, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.12.1rc1, 1.12.1, 1.13.0rc1, 1.13.0rc2, 1.13.0, 1.13.1, 1.13.3, 1.14.0rc1, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.15.0rc1, 1.15.0rc2, 1.15.0)
No matching distribution found for numpy==1.9.3
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by markotoplak** [comment]
Which platform are you using and how did you install Orange?

**Comment by dgasper11** [comment]
Updated!

**Comment by ajdapretnar** [comment]
> how did you install Orange?

From our Download page, with Anaconda Navigator or in some other way?

**Comment by dgasper11** [comment]
Downloaded - Orange3-3.14.0-Python34-win32

**Comment by dgasper11** [comment]
I installed the miniconda win32 version and now I can install all add ons. Consider the issue close!
