### ISSUE TITLE
File: Provide percent missing values in Info box 

### ISSUE THREAD

**Issue by stuart-cls** [biolab/orange3#3157]
Hi,

The Data Table widget provides a nice overview of the dataset in the "Info" box, specifically including the percent missing values. It would be nice if the File widget "Info" box did the same to help diagnosing problematic datasets.

Thanks!

##### Orange version
3.14.0

##### Expected behavior
File "Info" box provides the same text as Data Table "Info" box.

##### Actual behavior
File "Info" has less info.

**Comment by rokgomiscek** [comment]
Closed via #3305
