### ISSUE TITLE
Distances: column normalization doesn't work as expected

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3160]
##### Orange version

3.15.dev

##### Expected behavior
File - Distances (columns + normalized) and File - Transpose - Distances (rows + normalized) should produce the same result for binary data.

##### Actual behavior
Distance matrices different for these two workflows.

##### Steps to reproduce the behavior
It could be that I am just missing something obvious, but I think this doesn't work as expected.
[Dataset](https://docs.google.com/spreadsheets/d/1Dty81T7chY2NYzbtRKSob_vjJaPuT9pw5uqqV2rl9uU/edit#gid=0)
Follow the above steps.
<img width="416" alt="screen shot 2018-07-26 at 15 20 48" src="https://user-images.githubusercontent.com/12524972/43264892-96d8a8d0-90e7-11e8-8c56-7f9e1058d64a.png">

##### Additional info (worksheets, data, screenshots, ...)
<img width="451" alt="screen shot 2018-07-26 at 15 21 15" src="https://user-images.githubusercontent.com/12524972/43264900-9d033d06-90e7-11e8-9498-21df679cf363.png">
<img width="451" alt="screen shot 2018-07-26 at 15 21 21" src="https://user-images.githubusercontent.com/12524972/43264901-9d206ea8-90e7-11e8-9083-6a4a0304b847.png">

**Comment by rokgomiscek** [comment]
I think this works as expected. 
Regardless of whether we calculate the distance between rows or columns, the widget normalizes the columns. In the case of transposed data, this means the rows in the original data.
Maybe we should add some clarification in the documentation about the normalize checkbox?

**Comment by janezd** [comment]
@ajdapretnar? I think @rokgomiscek is right.

**Comment by ajdapretnar** [comment]
I agree. I will add this to the documentation. Probably I have to add this to both Preprocess and Distances? Even though in Preprocess it is quite clear that columns are normalized, while in Distances it might not be as much.

**Comment by janezd** [comment]
Preprocess doesn't need it, imho. It could be even confusing.
