### ISSUE TITLE
Please give better Text Editor in Python Script widget

### ISSUE THREAD

**Issue by Avicena507** [biolab/orange3#3167]
Orange version 3.13

 Expected :
better text editor in Python Script widget

Python Script widget have bad editor . When i  want to write code , i must write it in other Text Editor like Notepad ++ then copy it. And sometimes when i copy the code from Notepad ++ and paste it in Python Script Widget, indentation error occur. That's because Python Script widget sometimes read Tab as Space if the code copied from other Text Editor

i hope Orange will have better text editor . Thanks

**Comment by janezd** [comment]
We too. We are discussing using jupyter within the widget.

The widget is however not meant for some heavy coding, hence external tools will always be better.
