### ISSUE TITLE
Impute: don't construct new variables if Don't impute is selected

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3169]
##### Orange version

3.15.dev

##### Expected behavior
If Don't impute is selected, do not construct new variable.

##### Actual behavior
Impute create new variable even when the user decides not to impute, hence preventing further merging.

##### Steps to reproduce the behavior
Please check if the above is true with Concatenate and Merge. I could not reproduce this, when I was trying to test #2153 (first comment). If Impute works as expected, please close this issue and the other one as well. 

##### Additional info (worksheets, data, screenshots, ...)
As per #2153, we would like to fix only comment no.1. The rest is probably something we wish to avoid as for not to confuse the user (and enable later automatic imputation in Test & Score). Other solutions welcome.

**Comment by ales-erjavec** [comment]
The variables are preserved for 'Do not impute'.
