### ISSUE TITLE
Data Table: raises exception when showing a categorical attribute constructed from text attribute 

### ISSUE THREAD

**Issue by matejklemen** [biolab/orange3#3173]
##### Orange version

3.15.0.dev0+213c3c8

##### Expected behavior
Data Table shows the original and newly constructed attribute.

##### Actual behavior
An exception gets raised: _IndexError: cannot fit 'int' into an index-sized integer_.

##### Steps to reproduce the behavior
1. Create a csv file as described in 'Additional Info', load it and change the type of the single attribute to 'text'.
2. Connect it to a Feature Constructor, where you create a categorical attribute from the attribute (the expression is 'D1 := Col', using values A, B).
3. Connect the results to a Data Table and try to open it.

##### Additional info (worksheets, data, screenshots, ...)
File that I used looks like this:
```
Col
1
2
```

**Comment by janezd** [comment]
Works for me. We probably fixed it as a side effect of some other change. Please tell us if the problem persists in newer versions and we'll reopen the issue.
