### ISSUE TITLE
Hamming distance

### ISSUE THREAD

**Issue by thocevar** [biolab/orange3#3185]
There is no distance in Orange that can be used for distance calculations between columns in data with discrete attributes. 

Implement Hamming distance in distance.py and add it to the OWDistances widget.

**Comment by ajdapretnar** [comment]
Likely also useful for text.

**Comment by clone95** [comment]
Good morning, i'm a Master student and our professor taught us how to use orange. i find it a very useful tool and i would like to help out with small things. could you give me an example of how this distance between two columns of discrete values would be calculated?

**Comment by kernc** [comment]
> how this distance between two columns of discrete values would be calculated?

Similarly to [simple matching coefficient](https://en.wikipedia.org/wiki/Simple_matching_coefficient), increase the distance by 1 for each index at which two vectors differ.

**Comment by clone95** [comment]
ok thanks. Now i'm going to explore the project a bit before doing this. Thanks a lot.

**Comment by atyamsriharsha** [comment]
Hey, @thocevar I can see that there is no development started on this issue and I would like to contribute to this issue. I was looping through the code and found out that in eucledian distance metric we are using means are used as offset for normalization and two standard deviations in scaling whereas medians are used as offset for normalization and two MADS are used in scaling in Manhattan distance model . Can you please provide some insight how do we select these parameters and what are the metrics we should use while implementing Hamming distance . Thanks :)

**Comment by janezd** [comment]
See https://github.com/biolab/orange3/files/1128190/distances.pdf, referenced in https://github.com/biolab/orange3/pull/2454. As I recall a later changed some parts, but the reasoning for using two standard deviations is still as explained there.
