### ISSUE TITLE
Please strip shared libraries

### ISSUE THREAD

**Issue by yurivict** [biolab/orange3#3191]
Currently you install unstripped ones, ex:
```
$ file ./work-py36/stage/usr/local/lib/python3.6/site-packages/Orange/widgets/utils/_grid_density.so
./work-py36/stage/usr/local/lib/python3.6/site-packages/Orange/widgets/utils/_grid_density.so: ELF 64-bit LSB shared object, x86-64, version 1 (FreeBSD), dynamically linked, not stripped
```

**Comment by ales-erjavec** [comment]
Can you try:
```sh
LDFLAGS="-Xlinker -strip-all" ./setup.py ...
```

**Comment by yurivict** [comment]
This works. Could you please add these flags internally?

**Comment by ales-erjavec** [comment]
No. We use python's distutils for building and configuration, and they are not exactly easy tune, plus the flags are toolchain dependent.

If you are trying to make a FreeBSD port and conform to the port policy, take a look at how other python packages are done (e.g. scipy, scikit-learn, ...)

**Comment by yurivict** [comment]
Ok, thanks, I added these flags to the FreeBSD port.
