### ISSUE TITLE
Canvas: wrong size upon pane expansion

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3193]
##### Orange version

3.16.dev

##### Expected behavior
When the user extends the pane, canvas size doesn't change (i.e. extends across the entire window).

##### Actual behavior
Canvas gets really small.

##### Steps to reproduce the behavior
OSX, don't know about other platforms.

##### Additional info (worksheets, data, screenshots, ...)
Before extending:
<img width="600" alt="screen shot 2018-08-08 at 11 16 08" src="https://user-images.githubusercontent.com/12524972/43886422-f28c9432-9bbb-11e8-9c45-4bbfe3bf1d30.png">

After extending:
<img width="600" alt="screen shot 2018-08-08 at 11 16 11" src="https://user-images.githubusercontent.com/12524972/43886431-f5cce44e-9bbb-11e8-96cc-b1330164eaf2.png">

**Comment by ales-erjavec** [comment]
I can only duplicate this using Qt 5.9.6 from conda (from the default channel). Downgrading to 5.9.5 (`conda install qt=5.9.5`) seems to fix this.

**Comment by ales-erjavec** [comment]
This seems to be [QTBUG-68939](https://bugreports.qt.io/browse/QTBUG-68939).

**Comment by ajdapretnar** [comment]
Ok, thanks for the info!

**Comment by ajdapretnar** [comment]
I will reopen. We should consider forcing qt to 5.9.5 until this is fixed.

**Comment by ajdapretnar** [comment]
Bug was fixed and the problem is no longer present.
