### ISSUE TITLE
ReliefF error in Orange 3.15

### ISSUE THREAD

**Issue by Avicena507** [biolab/orange3#3199]
Orange version : 3.15

Error occured when i use ReliefF feature selection. After warning appear, Python software close immediately

![tt](https://user-images.githubusercontent.com/41800734/43989216-b5507290-9d6f-11e8-8f4c-b09e98ef6a05.png)

**Comment by ajdapretnar** [comment]
Please describe your issue in more detail. Which dataset are you using or can you reproduce this on a standard dataset (iris, titanic)? What are the preprocessing steps?
I can't reproduce this with iris, normalize in Preprocess, Select Rows (not setosa) and ReliefF in Rank.

**Comment by janezd** [comment]
Closed as inactive.
