### ISSUE TITLE
Orange stopped loading after 3.15 Upgrade

### ISSUE THREAD

**Issue by joenobk** [biolab/orange3#3201]
<!--
Upgraded from 3.14 to 3.15 with standard Miniconda x86_64 for windows 10 and on Windows 7.
Orange loads first time.
Tried to upgrade textable a few times unsuccessfully. Close Orange 
Orange won't load. Startup screen doesn't appear.
Rerun the upgrade file
Orange loads
Running quick menus from right click or dragging results in error  
quickmenu.py line 342 in filterAcceptaRow name=description.name
AttributeError: 'NoneType' object has no attribute 'name'

##### Orange version
3.15.0

##### Expected behavior
Load and show widget menu on right click

##### Actual behavior
May not load. Shows error on right click

**Comment by ales-erjavec** [comment]
Can you please provide more info. Like which operating system do you use? The method of upgrade?

**Comment by joenobk** [comment]
Happened on two computers. One with Windows 10 and one with Windows 7.
Each upgrade was with standard Orange3-3.15.0-Miniconda-x86_64.exe (64 bit) installation executable choosing to overwrite existing install.

On Windows 10. I later uninstalled orange 3.15 and miniconda. I notice that Orange 3.11 is still listed as installed. I did not uninstall orange 3.11.

I Reinstalled 3.15 and added all add-ons through the orange canvas options menu. After closing orange, it wouldn't open again. Even after a restart.

I reinstalled Orange 3.15 again the same way with exe and overwrite and it has loaded and closed successfully several times. Right click does not return error.

The windows 7 instance will load but returns an error on right click on canvas. I have not tried to uninstall/reinstall on Windows 7 yet. It also shows orange 3.11 listed in control panel programs uninstall.

**Comment by ajdapretnar** [comment]
This is quite serious as our current installers don't work at all. Could we force the sip to downgrade? We really _need_ to fix this!
@lanzagar @BlazZupan

**Comment by ales-erjavec** [comment]
Can you please try this installer: [Orange3-3.15.0-Miniconda-x86_64.exe](https://ci.appveyor.com/api/buildjobs/t0cqqc6hcsl4l67n/artifacts/installers%2FOrange3-3.15.0-Miniconda-x86_64.exe) (build as part of https://ci.appveyor.com/project/ales-erjavec/orange3-installers/build/1.0.276 which includes pyqt 5.6.2 from the start)

**Comment by ajdapretnar** [comment]
The installer works for me.

**Comment by joenobk** [comment]
The modified 3.15 installer fixed the issue. But installing 3.16 without first installing the modified 3.15, still seems to cause a problem.

**Comment by ajdapretnar** [comment]
3.16 should be modified with the same patch as 3.15.

**Comment by janezd** [comment]
@ajdapretnar, this can now be closed I suppose?
