### ISSUE TITLE
SVM fails when mixing original and BoW attributes

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3202]
##### Orange version

3.16.dev

##### Expected behavior
SVM works with election-tweets-2016.tab from Text add-on.

##### Actual behavior
SVM shows 'Fitting failed. Non-zero offset in normalization of sparse data.'
This only happens when additional, non-bag-of-words attributes are present.

##### Steps to reproduce the behavior
Corpus - Data Table (select a couple of instances for performance) - Bag of Words (Count) - SVM.

##### Additional info (worksheets, data, screenshots, ...)
Try to remove original attributes (Favourite count, Retweet count, Latitude, Longitude, Is retweet and Language) and SVM starts working. I think the issue might be in different handling of attributes (from original data and from bag of words).

See https://github.com/biolab/orange3-text/issues/312

**Comment by janezd** [comment]
@ajdapretnar, could you attach some simple data for easier replication/fixing? I, for instance, can't look into this because I don't know exactly how to prepare the data.

**Comment by ajdapretnar** [comment]
This should work.
[svm-fails.pkl.gz](https://github.com/biolab/orange3/files/2918605/svm-fails.pkl.gz)

Load the data with Corpus and pass it to SVM.
If you use Select Columns and remove the first 7 attributes (those with normal names), SVM starts working. Potential issue could be that these weren't properly transformed to sparse, since these attributes were there before BoW construction.

**Comment by ajdapretnar** [comment]
<img width="367" alt="screen shot 2019-03-01 at 09 42 31" src="https://user-images.githubusercontent.com/12524972/53626574-5aa8e800-3c06-11e9-9510-487e2622f46e.png">
