### ISSUE TITLE
Problem with miniconda installer- Exits with an error

### ISSUE THREAD

**Issue by raindropsfromsky** [biolab/orange3#3204]
##### Orange version
v3.15.0, Windows 64 bit version

##### Expected behavior
Should install without any problem.

##### Actual behavior
Halfway through the installer reports error:

ERROR conda.core.link: _execute_actions(335): An error occurred while installing package '<unknown>::python-3.6.6-hea74fb7_0' 
CondaError: Cannot link a source that does not exist C:\Users\NA\Miniconda3\pkgs\python-3.6.6-hea74fb7_0\DLLs\py.ico

Attempting to roll back, 
CondaError: Cannot link a source that does not exist. 
•conda• command exited with 1. Cannot continue. 

##### Steps to reproduce the behavior
I get the same error in four different experiments:
1. Run the exe normally. Install in the default path.
2. Run the exe as administrator. Install in the default path.
3,4: Repeat the above steps with a non-default path.

##### Additional info (worksheets, data, screenshots, ...)
I have not pre-installed Python 3.6 separately. Is that needed?
If so, the latest version of Python is 3.7.0 (not 3.6.6, as reported in the error). 
Is that OK?

**Comment by raindropsfromsky** [comment]
update: I explored the path specified in the error.
I confirmed that Python 3.6.6 is installed.
But the DLLs folder does not have the "py.ico" file.

BTW even if this issue is resolved, it may encounter further missing files.
IMHO this installer needs to be tested further.

**Comment by raindropsfromsky** [comment]
Update-2: 

I confirmed that several files are missing from the DLLs folder.
I copied and addde the py.ico file, and retried,
This time the error reported that pyc.ico was missing.
I again copied that file into the DLLs folder and retried installation.
The error message changed to another file missing (this time with dll extension).

Thus it is likely that several files are missing from this folder.

**Comment by ales-erjavec** [comment]
Did you have Miniconda installed before installing Orange? If so which version of conda is installed in it (run `Miniconda3\Scripts\conda.exe --version`)

Can you copy/paste the installer 'Details' log when the error happens. Click the 'Show details' button, right click on the log view and select 'Copy Details to Clipboard'. 

Also, there should be a second log in your Temp folder (usually in `C:\Users\%USERNAME%\AppData\Local\Temp\Orange3-3.15.0-install-log.txt`). Can you please post that too.

**Comment by raindropsfromsky** [comment]
Well, I have not installed Miniconda specifically, but other software may have installed it (just like Orange).
I ran the command, and it says **Conda 4.3.14**.

BTW I always uninstall all my older software before installing the latest version. But in case of Orange, there is a vestigial 3.10.0 version, which I am unable to uninstall using the **Apps & features** window of Windows 10. It always gives the following error:

[Window Title]
C:\Program Files\Util\Orange\Orange-Uninstall.exe

[Content]
Windows cannot find 'C:\Program Files\Util\Orange\Orange-Uninstall.exe'. Make sure you typed the name correctly, and then try again.

[OK]

I saw this error while installing the last two versions of Orange (3.13, 3.14) also, but it apparently did not  cause any more issues. So I was ignoring it. 

Here is the installer log text (details):
[Installer log.txt](https://github.com/biolab/orange3/files/2302988/Installer.log.txt)

As regards the error log files, I could not find the orange install log, but there is an orange uninstall log.
I am attaching both log files I found in that folder.
[Orange logs.zip](https://github.com/biolab/orange3/files/2302976/Orange.logs.zip)

**Comment by ales-erjavec** [comment]
Basically I am unable to reproduce the error.

The `pkgs` folder is where conda unpacks its package archives and then links or copies the contents of that folder to the destination. The .tar.bz archive does contain the py.ico file and it is unpacked in the folder when I run the installer.

Do you run any antivirus software that maybe moves/quarantines the files as they are unpacked?

**Comment by raindropsfromsky** [comment]
I have AVG, but it did not produce any errors during the installation. (I know its behavior well.)

Secondly, the same file (py.ico) is already installed in several other subdirectories. So logically speaking, my antivirus may not be creating this issue.

BTW all the **py.ico** files in the different subdirectories have the same size, so I took a chance and copied the file from another subfolder. When I re-attempted to install Orange, it produced a different file missing error message. I kept on copying those file, and each time the next attempt produced another file missing error.

Thus I think an entire set of files is missing.

**Comment by raindropsfromsky** [comment]
Assuming there is no problem with the installer, what should I do to overcome the local factors?
(Please suggest steps including uninstallation, so that there is mess left by the old installation.)

**Comment by raindropsfromsky** [comment]
I deleted the **miniconda** folder and then removed all registry entries that had "orange" and "miniconda" in them. Then I tried the original exe file, and the installation was completed without any hitch.

I think this may be a registry corruption issue.
