### ISSUE TITLE
Widgets are never garbage collected

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#3206]
Widgets are not garbage collected when they are deleted. Even a the simplest widget, which contains nothing, is not. If I add the following to `test_widget.py`, the tests fail.

    def test_garbage_collect(self):
        widget = MyWidget()
        ref = weakref.ref(widget)
        del widget
        gc.collect()
        self.assertIsNone(ref())

    def test_garbage_collect_from_scheme(self):
        new_scheme = WidgetsScheme()
        w_desc = WidgetDescription.from_module("Orange.widgets.tests.test_widget")
        node = new_scheme.new_node(w_desc)
        widget = new_scheme.widget_for_node(node)
        new_scheme.remove_node(node)
        ref = weakref.ref(widget)
        del widget
        del node
        gc.collect()
        self.assertIsNone(ref())

I can make these tests pass, if I comment out the contests of `statechanged()` in `widget.py`. But even then, deleting widget in Canvas (and even doing gc.collect() afterwards) does not collect it.

But I can make Orange collect the empty widget if I:
1. Delete it from my workflow.
2. Open a new workflow, and close the old one.
3. Run `gc.collect()`

If I only do (2) and (3), the widget is not collected.

**Comment by enjoysmath** [comment]
You may wan to look into when Qt widgets get deleted because I believe Canvas is coded using PyQt5.

**Comment by markotoplak** [comment]
@ales-erjavec, do you perhaps see this also?

For me, the easiest way to see if this issue also occurs for you is to make an empty widget with just 1 huge numpy array and try adding/deleting it.

**Comment by ales-erjavec** [comment]
Which version of PyQt5 and sip (or PyQt5-sip) are you using?

I see it using PyQt5==5.9.2 and sip==4.19.8, but this is the version that exhibits this: https://riverbankcomputing.com/pipermail/pyqt/2018-March/040174.html

**Comment by janezd** [comment]
@ales-erjavec, @markotoplak, this is fixed, right? Can you close the issue?

**Comment by janezd** [comment]
@ales-erjavec, @markotoplak, this is fixed, right? Can we close this issue?
