### ISSUE TITLE
The miniconda installer should be able to accept folder with a space

### ISSUE THREAD

**Issue by raindropsfromsky** [biolab/orange3#3215]
I have created a **C:\Program Files\Util** subfolder, where I install all my apps. The Orange app is installed there only.

But during installation of miniconda, the installer refuses to accept this path, and states that the path has a space, which can cause malfunction. So I have to let it have its default path.

But IINW any version of Windows later than **Windows 95** can easily handle paths with spaces!
So why is this restriction still applied here?

**Desired:** The installer should allow me to use a path with a space, which are very common for years.

**Comment by ales-erjavec** [comment]
This should be addressed to the https://github.com/conda/conda.

**Comment by stevesimmons** [comment]
This is mentioned in the [Anaconda FAQ](https://docs.anaconda.com/anaconda/faq/#in-what-folder-should-i-install-anaconda-on-windows), which says:

**In what folder should I install Anaconda on Windows?**

We recommend installing Anaconda or Miniconda into a directory that contains only 7-bit ASCII characters and no spaces, such as C:\anaconda. Do not install into paths that contain spaces such as C:\Program Files or that include Unicode characters outside the 7-bit ASCII character set. This helps ensure correct operation and no errors when using any open source tools in either Python 3 or Python 2 conda environments.
