### ISSUE TITLE
Is there a way to load a model in orange canvas into a Neural Network?

### ISSUE THREAD

**Issue by enjoysmath** [biolab/orange3#3222]
I am able to save a Neural Network model because one of its outputs is Model and there's a Save Model widget.

How do I do the opposite?

**Comment by kernc** [comment]
[Load Model](https://docs.orange.biolab.si/3/visual-programming/widgets/model/loadmodel.html) widget.

**Comment by enjoysmath** [comment]
@kernc but what does that connect to?  Neural Network widget doesn't have a Model input.

**Comment by gbaptista** [comment]
@enjoysmath Connect to `Predictions` widget.

**Comment by gbaptista** [comment]
@enjoysmath Example of a common workflow saving and loading a model:
![screenshot_20180901_144832](https://user-images.githubusercontent.com/29520/44948563-1e7f0100-adf6-11e8-8226-cc391046a7be.png)
