### ISSUE TITLE
How do I run Orange3 dev version source code from IDE?

### ISSUE THREAD

**Issue by enjoysmath** [biolab/orange3#3224]
If I select Orange.canvas.__main__.py as the main entry point, the first exception I get is import error:

`from Orange.widgets.utils.webview import WebviewWidget`

Then another import error for `cv2`.

There's no way to ignore and jump over these, they are fatal.

I'm using dev version 3.16 and WingWare IDE pro 6.

Thanks.

**Comment by markotoplak** [comment]
How did you install dependencies?

`python Orange/canvas/__main__.py` work for me and so does `python -m Orange.canvas`. Both work in command line or PyCharm.

The warnings you mentioned should not be fatal. Please post the full output.

**Comment by astaric** [comment]
The first error looks like PyQt does not have Webview/Webengine installer. Either one is ok, but you need one of them for Orange to work.

I use miniconda's python for development, pyqt conda package already contains webengine (I'm using mac). If you are using something else, you might have to install it separately.
