### ISSUE TITLE
How to make predictions in a python module using a saved RandomForest model from Orange GUI

### ISSUE THREAD

**Issue by andre-motta** [biolab/orange3#3225]
I used Orange GUI and trained a RandomForest model that i later saved using the SaveModel widget.

Orange saves its models with pickle, therefore I went and wrote the following python script:

    import Orange, pickle

    model = pickle.load(open('model', 'rb'))

The problem is, I extensively searched the web yesterday. And couldn't find any example to make a prediction with my data (which is the same format as the data I used in the Orange GUI) or sufficient documentation on how to use the model.

Upon later research I found that I could supposedly evaluate a pre-trained module that was unpickled with the following code

    results = Orange.evaluation.testing.TestOnTestData(data, test, [lambda testdata: model])

The thing is to load data I'm supposed to do:

    data = Orange.data.Table('trainingData.csv');
    test = Orange.data.Table('testData.csv');

And I haven't been able to find documentation regarding how to differentiate between the target and the features in these `*.csv` files.

Appart from that even if I'm able create this files. I would have to do some gimmick where `testData.csv` would need to be only one line long (the line I want to predict) with a target value of 1. And I would see what the model predicted by checking if the score was `100%` or `0%`

So I know my questions are multiple but I could really use some help on the follwing points:

 1. How to define in a `*.csv` file what is the target among the features for the `Orange.data.Table()` function
 2. How to use a pickled Orange RandomForest model to make a prediction instead of using a gimmicked evaluation to make a prediction. (So that i could predict more than one item at a time..)

Thank you very much for your time

**Comment by lanzagar** [comment]
1. See documentation on [Loading your data](https://orange-visual-programming.readthedocs.io/loading-your-data/index.html). You can either use a 3 row header (names, variable types, variable roles) or use prefixes in a single row header.
Using Save Data in Orange GUI will use the 3 row header and that is actually a good way to double-check how to do something - you can load the data in the GUI, set the target and anything else that is needed and then save to .tab or .csv and inspect the file to see how it was saved.

2. Models are classes that are intended to make predictions so there is a very simple way - just call the model with the data.
```py
data = Orange.data.Table('iris')
pred_ind = model(data)  # array of predicted target values (indices)
[model.domain.class_var.str_val(i) for i in pred_ind]  # convert to value names (strings)
```

Bonus:
As you can see in the example above, the model stores the domain it was trained on. This means you actually don't even need to bother with 1. When the model is given data to predict, it will first convert it to the domain it was trained on and use the same variables as the target and independent features (obviously they need to be present in the data).

**Comment by andre-motta** [comment]
Thank you very much. I Will do it tonight when i get home, but i will close the issue!

**Comment by kernc** [comment]
If it works, could you perhaps also answer [your StackOverflow question](https://stackoverflow.com/questions/52130635/how-to-make-predictions-using-a-saved-randomforest-model-from-orange-gui)?

**Comment by andre-motta** [comment]
I will answer it =) as soon as it works
