### ISSUE TITLE
FeatureRequest: MongoDB connector in category data

### ISSUE THREAD

**Issue by avolution** [biolab/orange3#3232]
Same as the SQL Connector, but for MongoDB.

**Comment by janezd** [comment]
Nobody seems to want to own this issue. It is also not clear how unrelational data base would fit into Orange. Put differently, Orange can't really handle something that doesn't fit into relational databases (and not even all of that).

Feel free to reopen an issue and provide more details about use cases and the proposed GUI. The core development group however does not work with MongoDB, so it is unlikely to invest any time in this. Not just the wish, but also its implementation will have to come from outside.

**Comment by avolution** [comment]
Usecase is for example unstructured Data

Timeseries Data for example

**Comment by avolution** [comment]
@"Orange can't really handle something that doesn't fit into relational databases "

I do not understand your point here.

What have that to do with "relational databases"?

**Comment by avolution** [comment]
Please reopen the ticket (I have no rights to to this)

**Comment by janezd** [comment]
PR doesn't have to be reopened for discussion to continue.

Time series is far from Orange's strong point. Orange works mostly with tabular data, hence it makes more sense to cover the common SQL databases (AFAIK we don't excel in this respect either). That said, I barely know about Mongo. Which brings us back to the crucial point:

> The core development group however does not work with MongoDB, so it is unlikely to invest any time in this. Not just the wish, but also its implementation will have to come from outside.

That is, if somebody (you?) provides the connector in a good shape, with tests and documentation, we'll gladly include it. Same for other databases that have been requested. However nobody came up with it in half a year, so I closed this PR during yesterday's purge of lonely pull requests.
