### ISSUE TITLE
It is not clear to me with what to mark the columns with in .tab format ("c", "d", "text", "class", etc.)

### ISSUE THREAD

**Issue by enjoysmath** [biolab/orange3#3235]
The documentation says no where how to build up your .tab file.  I'm building my .tab file using another program.  

I've tried things like labeling with "c" for continuous and "d" for discrete, but things get messed up such as several columns being merged together.

Also looking in the examples directory on github doesn't paint a complete or consistent picture of what we should do here.

The result is that I'm using NO type markers whatsoever, and letting Orange figure out the types automatically.  The result is almost perfect except that I have to keep setting a column from Categorical to Text when I hit "Reload" on the file widget.

**Comment by astaric** [comment]
Does https://orange-visual-programming.readthedocs.io/loading-your-data/index.html help?
