### ISSUE TITLE
Problem with adding addons in Windows OS when you load them the application restarts but crashes when you try to reopen Orange

### ISSUE THREAD

**Issue by Warrior4996** [biolab/orange3#3236]

**Comment by ajdapretnar** [comment]
Please explain in more details what is the issue and please follow the issue template. Also attach screenshots where possible.

**Comment by astaric** [comment]
Probably the same problem as https://github.com/biolab/orange3/issues/3201.

@Warrior4996, can you try the installer from the linked issue?
