### ISSUE TITLE
How can I solve this problem: CondaValueError: Value error: invalid package specification: ...?

### ISSUE THREAD

**Issue by IllMindx** [biolab/orange3#3241]
I am trying to install the Orange3-3.15.0-Miniconda-x86_64, but after the installation of miniConda, it happens the error below:

Creating an new conda env in "C:\Users\Wesley Almeida\AppData\Local\Orange"
Output folder: C:\Users\Wesley Almeida\AppData\Local\Temp\nsi4525.tmp\Orange-installer-data\conda-pkgs
Extract: anyqt-0.0.8-py36_1.tar.bz2
Extract: asn1crypto-0.24.0-py36_0.tar.bz2
Extract: blas-1.0-mkl.tar.bz2
Extract: bottleneck-1.2.1-py36h452e1ab_1.tar.bz2
Extract: ca-certificates-2018.03.07-0.tar.bz2
Extract: certifi-2018.4.16-py36_0.tar.bz2
Extract: cffi-1.11.5-py36h945400d_0.tar.bz2
Extract: chardet-3.0.4-py36_1.tar.bz2
Extract: commonmark-0.7.5-py36_0.tar.bz2
Extract: conda-spec.txt
Extract: cryptography-2.3-py36h74b6da3_0.tar.bz2
Extract: cryptography-vectors-2.3-py36_0.tar.bz2
Extract: decorator-4.3.0-py36_0.tar.bz2
Extract: dill-0.2.8.2-py36_0.tar.bz2
Extract: docutils-0.14-py36h6012d8f_0.tar.bz2
Extract: future-0.16.0-py36_1.tar.bz2
Extract: icc_rt-2017.0.4-h97af966_0.tar.bz2
Extract: icu-58.2-ha66f8fd_1.tar.bz2
Extract: idna-2.7-py36_0.tar.bz2
Extract: install.bat
Extract: intel-openmp-2018.0.3-0.tar.bz2
Extract: joblib-0.12.1-py36_0.tar.bz2
Extract: jpeg-9b-hb83a4c4_2.tar.bz2
Extract: keyring-9.0-py36_0.tar.bz2
Extract: keyrings.alt-3.1-py36_0.tar.bz2
Extract: libpng-1.6.34-h79bbb47_0.tar.bz2
Extract: mkl-2018.0.3-1.tar.bz2
Extract: mkl_fft-1.0.4-py36h1e22a9b_1.tar.bz2
Extract: mkl_random-1.0.1-py36h77b88f5_1.tar.bz2
Extract: networkx-2.1-py36_0.tar.bz2
Extract: numpy-1.13.3-py36h5c71026_4.tar.bz2
Extract: openssl-1.0.2o-hfa6e2cd_1.tar.bz2
Extract: orange3-3.15.0-py36h830ac7b_0.tar.bz2
Extract: pip-10.0.1-py36_0.tar.bz2
Extract: pycparser-2.18-py36_1.tar.bz2
Extract: pyopenssl-18.0.0-py36_0.tar.bz2
Extract: pyqt-5.9.2-py36h1aa27d4_0.tar.bz2
Extract: pyqtgraph-0.10.0-py36h28b3542_3.tar.bz2
Extract: pyreadline-2.1-py36_1.tar.bz2
Extract: pysocks-1.6.8-py36_0.tar.bz2
Extract: python-3.6.6-hea74fb7_0.tar.bz2
Extract: python-louvain-0.11-py_0.tar.bz2
Extract: pywin32-223-py36hfa6e2cd_1.tar.bz2
Extract: qt-5.9.5-vc14he4a7d60_0.tar.bz2
Extract: requests-2.19.1-py36_0.tar.bz2
Extract: scikit-learn-0.19.1-py36hae9bb9f_0.tar.bz2
Extract: scipy-0.19.1-py36h7565378_3.tar.bz2
Extract: serverfiles-0.2.1-py36_0.tar.bz2
Extract: setuptools-40.0.0-py36_0.tar.bz2
Extract: sip-4.19.8-py36h6538335_0.tar.bz2
Extract: six-1.11.0-py36_1.tar.bz2
Extract: sqlite-3.24.0-h7602738_0.tar.bz2
Extract: urllib3-1.23-py36_0.tar.bz2
Extract: vc-14.1-h0510ff6_3.tar.bz2
Extract: vs2015_runtime-15.5.2-3.tar.bz2
Extract: wheel-0.31.1-py36_0.tar.bz2
Extract: win_inet_pton-1.0.1-py36_1.tar.bz2
Extract: wincertstore-0.2-py36h7fe50ca_0.tar.bz2
Extract: xlrd-1.1.0-py36_1.tar.bz2
Extract: zlib-1.2.11-h8395fce_2.tar.bz2
Output folder: C:\Users\Wesley Almeida\AppData\Local\Temp\nsi4525.tmp\Orange-installer-data\conda-pkgs
Installing packages (this might take a while)
Executing: cmd.exe /c install.bat "C:\Users\Wesley Almeida\AppData\Local\Orange" "C:\Users\Wesley Almeida\Miniconda3\Scripts\conda.exe"
Creating a conda env in "C:\Users\Wesley Almeida\AppData\Local\Orange"
Fetching package metadata ...........
Solving package specifications: 
Package plan for installation in environment C:\Users\Wesley Almeida\AppData\Local\Orange:

 To activate this environment, use:
 > activate C:\Users\Wesley Almeida\AppData\Local\Orange

 To deactivate this environment, use:
 > deactivate C:\Users\Wesley Almeida\AppData\Local\Orange
 * for power-users using bash, you must source

**CondaValueError: Value error: invalid package specification: C:\Users\Wesley Almeida\AppData\Local\Temp\nsi4525.tmp\Orange-installer-data\conda-pkgs\python-3.6.6-hea74fb7_0.tar.bz2**

"conda" command exited with 1. Cannot continue.

##### Steps to reproduce the behavior
1-Execute the Orange3-3.15.0-Miniconda-x86_64.exe;
2-Starts the installtion of Orange;
3-If you don't have the miniConda, it'll start the installation of it;
4-When it's finishing the installation of Orange the error happens.

**Comment by astaric** [comment]
What worked for me was:
1. Open Anaconda Prompt (as administrator if it was installed for all users)
2. Run `conda update conda`
3. Run the installer again

**Comment by IllMindx** [comment]
Thank you, it also solved my problem.

**Comment by juanmercadoit** [comment]
> What worked for me was:
> 
> 1. Open Anaconda Prompt (as administrator if it was installed for all users)
> 2. Run `conda update conda`
> 3. Run the installer again

thanks a lot man ! runnig fine !

**Comment by promiseve** [comment]
Hey, i don't have the permission to update the conda because it is on a shared cluster. 
How do i resolve this same error?
