### ISSUE TITLE
Selecting visualizations in VizRank dialogs

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#3255]
Double clicking a cell allows the user to edit it, which does not make sense.

If the user selects a pair in the scatter plot vizrank, then changes the attribute in one of the combos in the widget, and then again clicks the same (already selected) cell in the vizrank dialog, the selection should be passed to the widget. It however doesn't because the selection is not changed.

**Comment by ajdapretnar** [comment]
Is there no Qt flag such as `table.setEditTriggers(QAbstractItemView::NoEditTriggers)`?

**Comment by janezd** [comment]
Sorry, I don't understand this comment.

**Comment by ajdapretnar** [comment]
I thought we are just talking about editable fields. Then I realized the issue is also that the selection isn't communicated onwards. I prefer the second solution. If I click on the field x times, the widget should be updated x times... I guess.

**Comment by markotoplak** [comment]
As long is changing selection with a keyboard still works. :)

**Comment by janezd** [comment]
I've implemented an improved version of the first alternative (https://github.com/biolab/orange3/commit/c67d22ec46c87f4c2c5b826faaf3215b6a704b85). When the user changes the selection in the widget, the corresponding row in vizrank should be highlighted, otherwise the widget and vizrank are not synchronized.

Communication between the widget and vizrank is trivial if we use signals.

**Comment by janezd** [comment]
Fixed in #3276.
