### ISSUE TITLE
Title text layout in Example Workflows window

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3#3257]
This is how I see the titles in the Orange official release 3.15.0:

<img width="692" alt="screen shot 2018-09-17 at 14 55 21" src="https://user-images.githubusercontent.com/726604/45646832-137ccf80-ba8a-11e8-8845-12876ee14172.png">

Note that the titles of the workflows are nicely aligned and occupy two rows, as expected.

If I check this window in a current master (Help->Welcome, and then Examples), I get the following window:

<img width="692" alt="screen shot 2018-09-17 at 14 59 40" src="https://user-images.githubusercontent.com/726604/45646979-5b9bf200-ba8a-11e8-836e-344073c07216.png">

Note that workflow titles are not set correctly: the column space is too narrow, and the titles span over several lines instead of two.

**Comment by ales-erjavec** [comment]
`pip install PyQt5~=5.9.0` for now. This will be fixed in Qt 5.11.2 ([QTBUG-69404](https://bugreports.qt.io/browse/QTBUG-69404)).
