### ISSUE TITLE
Plot axis extremely faint

### ISSUE THREAD

**Issue by jasonhfuller** [biolab/orange3#3259]
##### Orange version
3.15.0  git revision bf95ddc

KDE Plasma: 5.8.9
KDE Frameworks Version: 5.36.0
QT Version 5.6.1

##### Expected behavior
`scatter plot` and `paint data` widgets should produce plots with visible axis

##### Actual behavior
`scatter plot` and `paint data` widgets should produce plots with nearly invisible axis when using KD5 and `breeze dark` theme

##### Steps to reproduce the behavior

Install KDE5 on BSD or Linux. Click on `Application Launcher` and search for settings; search for and open  "Look and Feel"; choose `Breeze Dark` Theme and click `Ok`

Launch Orange

Open `Paint Data` widget and axis will be hard to see

##### Additional info (worksheets, data, screenshots, ...)

![scatter](https://user-images.githubusercontent.com/43356236/45651482-98261880-ba9f-11e8-807b-028199b60bf9.png)

**Comment by janezd** [comment]
The widget uses defaults from pyqtgraph. If problem occurred generally, we'd fix it, but we wouldn't like to customize defaults or hardcode specific settings to fix problems that 3rd party libraries have on particular themes in particular distributions.
