### ISSUE TITLE
Data Table doesn't select full row

### ISSUE THREAD

**Issue by AndrejaKovacic** [biolab/orange3#3261]
##### Orange version

3.16.0

##### Expected behavior
If select full row is checked in Data Table, full row should always be selected, even when data changes.

##### Actual behavior
Widget now seems to remember which row was selected and how many attributes were there, so when you change data set from one with 4 attributes to one with 10, only first four attributes are selected initially.

##### Steps to reproduce the behavior
In File widget choose Iris data set, connect it to Data Table, select a line. Now change the data set to heart_disease. Data Table will now select only first four attributes.

##### Additional info (worksheets, data, screenshots, ...)
![screenshot from 2018-09-21 12-28-40](https://user-images.githubusercontent.com/17765889/45876564-3ca7a380-bd9b-11e8-96f2-18cec67c388d.png)

**Comment by ajdapretnar** [comment]
This annoys the hell out of me. Shouldn't selection be context-dependent? If the domain changes, selection should be reset.
