### ISSUE TITLE
Getting Fitting Failed all the time now after fresh install of Orange3-dev

### ISSUE THREAD

**Issue by enjoysmath** [biolab/orange3#3262]
This is with the latest dev version of Orange3.16.  I'm getting consitently "Fitting Failed" with regards to a NN and a loaded 120MB .tab file.  Now in my install at home, all that is required is that I restart orange and try again.  Now, it happens every time I try loading the dataset.  Fitting Failed, right away.

How can I fix this error?  It's not to do with memory limitations as I have it running on a 16GB VM running Windows Server 2016 Datacenter OS, with nothing else running.

The data has 137 features and 83,000 instances.

Tried: git cloning again and then
pip install -e .
It installed 3.17, same issue.

I installed on same server, the release version of orange (the one on the main website) and it does not have this issue.  So a temporary solution for this is to train in release, save model, load model into dev version where you run your live mode predictions with custom widgets (what we have).

**Comment by ajdapretnar** [comment]
I can't replicate this on the latest 3.17-dev (2018-09-24) with adult.tab data set. @enjoysmath Does it happen to you with adult.tab as well?

**Comment by janezd** [comment]
Closed for inactivity.
