### ISSUE TITLE
AUTHORS file missing

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#3264]
A collaborator on the Spectroscopy add-on expressed a wish that contributors should be mentioned somewhere so that they could be easily verified by project proposal reviewers. We will add an AUTHORS file there and also mention contributors on the web page.

Maybe we could have something like this for core Orange too. I propose we start an AUTHORS file in the repository root. Here is GIMP's AUTHORS file: https://github.com/GNOME/gimp/blob/master/AUTHORS

**Comment by janezd** [comment]
Like taking the list from `git shortlog --summary --numbered` and trying to guess as many names as we can?

**Comment by ajdapretnar** [comment]
+1 on this. We don't want to complicate our lives too much. I think is someone wants to be included in the list, they can submit a PR (include themselves in the list) with a link to actual contributions in the comment.

**Comment by janezd** [comment]
We decided against it, to make our lives easier and to also not forget somebody. List of contributors is accessible on github.
