### ISSUE TITLE
Distances: difference between Orange2 and Orange3

### ISSUE THREAD

**Issue by cincyamyK** [biolab/orange3#3265]
There are differences in calculation of distances between Orange2 and Orange3. Is there a white paper or a documentation regarding the changes?

**Comment by ajdapretnar** [comment]
@janezd

**Comment by janezd** [comment]
Not really, but kind of: [here](https://github.com/biolab/orange3/files/1128190/distances.pdf). As I recall, I later fixed some mistakes in my derivations, and I also implemented some things differently after discussions in #2454.

But to answer your questions more directly: yes, there are differences. Data representation is completely different, so you can expect differences in treatment of missing values as well as in normalization. None of implementations is *the* correct one, you always have to make some choices.
