### ISSUE TITLE
Problem with miniconda installer

### ISSUE THREAD

**Issue by dudester4** [biolab/orange3#3266]
##### Expected behavior

Orange to launch from Anaconda Win64 interface.

##### Actual behavior

Nothing happens

##### Steps to reproduce the behavior

Prior install worked great.  Installed Rapid Miner which seemed to prevent Orange opening- would not open.  Uninstalled Anaconda, python, and then reinstalled Anaconda.   Reinstalled Orange from Anaconda which still refuses to open.

**Comment by ajdapretnar** [comment]
@lanzagar @acopar Could this be something similar to what you were solving yesterday? It seems to be an issue with prior installation. The installer works fine with a clean Win.

**Comment by acopar** [comment]
Which version of Orange installer did you use?

Perhaps this is the same problem as #3201, which can be solved by upgrading to 3.16.

**Comment by janezd** [comment]
Close for inactivity.

**Comment by dudester4** [comment]
Dunno.  I did have an earlier install of Orange, where I did NOT use the
Anaconda installer, but I believe the Win msi file.  Anyway, got around it
by manually downloading the zip packaged files from the Weka Pentaho
repository.  Thanks for the reply.

Don Schindler
