### ISSUE TITLE
QWidget::setWindowModified: The window title does not contain a '[*]' placeholder

### ISSUE THREAD

**Issue by jasonhfuller** [biolab/orange3#3267]
##### Orange version
3.16.0

##### Expected behavior
Orange should launch with no errors / warnings

##### Actual behavior
I'm getting a QWidget::setWindowModified: The window title does not contain a '[*]' placeholder

##### Steps to reproduce the behavior

$ orange-canvas
libpng warning: iCCP: known incorrect sRGB profile
QWidget::setWindowModified: The window title does not contain a '[*]' placeholder

##### Additional info (worksheets, data, screenshots, ...)

Possibly relevant solution: https://forum.qt.io/topic/2070/solved-qwidget-setwindowmodified-the-window-title-does-not-contain-a-placeholder

Possibly related to bug https://github.com/biolab/orange3/issues/3259

**Comment by janezd** [comment]
@thocevar, can you replicate this? If so, can you check whether the proposed solution works?

**Comment by thocevar** [comment]
Yes, I can (http://doc.qt.io/qt-5/qwidget.html#windowModified-prop). We should add this placeholder in OWWidget if it's not present in the window title.
