### ISSUE TITLE
unable to add add-ons (text add-on)

### ISSUE THREAD

**Issue by dariasin** [biolab/orange3#3268]
Collecting Orange3-Text
  Downloading https://files.pythonhosted.org/packages/69/06/40c8eb64755885e6028dc3dc8b18fc1301cfec0bba65398f70abe691ba2c/Orange3_Text-0.5.1-py3-none-any.whl (17.5MB)
Requirement already satisfied: beautifulsoup4 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Text)
Requirement already satisfied: nltk>=3.0.5 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Text)
Requirement already satisfied: pdfminer3k>=1.3.1 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Text)
Requirement already satisfied: scikit-learn in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Text)
Requirement already satisfied: setuptools-git in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Text)
Requirement already satisfied: Orange3>=3.4.3 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Text)
Requirement already satisfied: validate-email in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Text)
Requirement already satisfied: tweepy in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Text)
Requirement already satisfied: simhash in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Text)
Requirement already satisfied: scipy in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Text)
Requirement already satisfied: biopython in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Text)
Requirement already satisfied: lxml in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Text)
Collecting wikipedia (from Orange3-Text)
Requirement already satisfied: odfpy>=1.3.5 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Text)
Requirement already satisfied: docx2txt>=0.6 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Text)
Requirement already satisfied: numpy in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Text)
Collecting ufal.udpipe (from Orange3-Text)
  Using cached https://files.pythonhosted.org/packages/f7/20/9fdf23855a8dbb018b91f798d5923fd3aadff5d1d8bee39187973f8e17bc/ufal.udpipe-1.2.0.1.tar.gz
Requirement already satisfied: gensim>=0.12.3 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Text)
Requirement already satisfied: six in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from nltk>=3.0.5->Orange3-Text)
Requirement already satisfied: ply>=3.4 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pdfminer3k>=1.3.1->Orange3-Text)
Requirement already satisfied: pytest>=2.0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pdfminer3k>=1.3.1->Orange3-Text)
Requirement already satisfied: docutils in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3>=3.4.3->Orange3-Text)
Requirement already satisfied: pip>=9.0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3>=3.4.3->Orange3-Text)
Requirement already satisfied: keyring in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3>=3.4.3->Orange3-Text)
Requirement already satisfied: CommonMark>=0.5.5 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3>=3.4.3->Orange3-Text)
Requirement already satisfied: keyrings.alt in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3>=3.4.3->Orange3-Text)
Requirement already satisfied: AnyQt>=0.0.8 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3>=3.4.3->Orange3-Text)
Requirement already satisfied: networkx in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3>=3.4.3->Orange3-Text)
Requirement already satisfied: setuptools>=36.3 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3>=3.4.3->Orange3-Text)
Requirement already satisfied: python-louvain in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3>=3.4.3->Orange3-Text)
Requirement already satisfied: xlrd>=0.9.2 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3>=3.4.3->Orange3-Text)
Requirement already satisfied: joblib>=0.9.4 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3>=3.4.3->Orange3-Text)
Requirement already satisfied: serverfiles in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3>=3.4.3->Orange3-Text)
Requirement already satisfied: bottleneck>=1.0.0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3>=3.4.3->Orange3-Text)
Requirement already satisfied: chardet>=3.0.2 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3>=3.4.3->Orange3-Text)
Requirement already satisfied: pyqtgraph>=0.10.0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3>=3.4.3->Orange3-Text)
Requirement already satisfied: PySocks>=1.5.7 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from tweepy->Orange3-Text)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from tweepy->Orange3-Text)
Requirement already satisfied: requests>=2.11.1 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from tweepy->Orange3-Text)
Requirement already satisfied: smart-open>=1.2.1 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gensim>=0.12.3->Orange3-Text)
Requirement already satisfied: more-itertools>=4.0.0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text)
Requirement already satisfied: attrs>=17.4.0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text)
Requirement already satisfied: py>=1.5.0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text)
Requirement already satisfied: atomicwrites>=1.0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text)
Requirement already satisfied: pluggy>=0.7 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text)
Requirement already satisfied: future in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from CommonMark>=0.5.5->Orange3>=3.4.3->Orange3-Text)
Requirement already satisfied: decorator>=4.1.0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from networkx->Orange3>=3.4.3->Orange3-Text)
Requirement already satisfied: oauthlib>=0.6.2 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests-oauthlib>=0.7.0->tweepy->Orange3-Text)
Requirement already satisfied: idna<2.8,>=2.5 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests>=2.11.1->tweepy->Orange3-Text)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests>=2.11.1->tweepy->Orange3-Text)
Requirement already satisfied: certifi>=2017.4.17 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests>=2.11.1->tweepy->Orange3-Text)
Requirement already satisfied: bz2file in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from smart-open>=1.2.1->gensim>=0.12.3->Orange3-Text)
Requirement already satisfied: boto3 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from smart-open>=1.2.1->gensim>=0.12.3->Orange3-Text)
Requirement already satisfied: boto>=2.32 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from smart-open>=1.2.1->gensim>=0.12.3->Orange3-Text)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from boto3->smart-open>=1.2.1->gensim>=0.12.3->Orange3-Text)
Requirement already satisfied: s3transfer<0.2.0,>=0.1.10 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from boto3->smart-open>=1.2.1->gensim>=0.12.3->Orange3-Text)
Requirement already satisfied: botocore<1.13.0,>=1.12.7 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from boto3->smart-open>=1.2.1->gensim>=0.12.3->Orange3-Text)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1; python_version >= "2.7" in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from botocore<1.13.0,>=1.12.7->boto3->smart-open>=1.2.1->gensim>=0.12.3->Orange3-Text)
Building wheels for collected packages: ufal.udpipe
  Running setup.py bdist_wheel for ufal.udpipe: started
  Running setup.py bdist_wheel for ufal.udpipe: finished with status 'error'
  Complete output from command /Applications/Orange3.app/Contents/MacOS/PythonApp -u -c "import setuptools, tokenize;__file__='/private/var/folders/mz/wn4rsn9x671_y6ds8z4nn33m0000gn/T/pip-build-swbum7ko/ufal.udpipe/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/mz/wn4rsn9x671_y6ds8z4nn33m0000gn/T/tmpknim_bgcpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.6-intel-3.6
  creating build/lib.macosx-10.6-intel-3.6/ufal
  copying ufal/__init__.py -> build/lib.macosx-10.6-intel-3.6/ufal
  copying ufal/udpipe.py -> build/lib.macosx-10.6-intel-3.6/ufal
  running build_ext
  building 'ufal_udpipe' extension
  creating build/temp.macosx-10.6-intel-3.6
  creating build/temp.macosx-10.6-intel-3.6/udpipe
  /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -Iudpipe/include -I/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c udpipe/udpipe.cpp -o build/temp.macosx-10.6-intel-3.6/udpipe/udpipe.o -std=c++11 -fvisibility=hidden -w -stdlib=libc++
  clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
  clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
  error: command '/usr/bin/clang' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for ufal.udpipe
  Running setup.py clean for ufal.udpipe
Failed to build ufal.udpipe
Installing collected packages: wikipedia, ufal.udpipe, Orange3-Text
  Running setup.py install for ufal.udpipe: started
    Running setup.py install for ufal.udpipe: finished with status 'error'
    Complete output from command /Applications/Orange3.app/Contents/MacOS/PythonApp -u -c "import setuptools, tokenize;__file__='/private/var/folders/mz/wn4rsn9x671_y6ds8z4nn33m0000gn/T/pip-build-swbum7ko/ufal.udpipe/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/mz/wn4rsn9x671_y6ds8z4nn33m0000gn/T/pip-8122n_j8-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-intel-3.6
    creating build/lib.macosx-10.6-intel-3.6/ufal
    copying ufal/__init__.py -> build/lib.macosx-10.6-intel-3.6/ufal
    copying ufal/udpipe.py -> build/lib.macosx-10.6-intel-3.6/ufal
    running build_ext
    building 'ufal_udpipe' extension
    creating build/temp.macosx-10.6-intel-3.6
    creating build/temp.macosx-10.6-intel-3.6/udpipe
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -Iudpipe/include -I/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c udpipe/udpipe.cpp -o build/temp.macosx-10.6-intel-3.6/udpipe/udpipe.o -std=c++11 -fvisibility=hidden -w -stdlib=libc++
    clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
    clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
    error: command '/usr/bin/clang' failed with exit status 1
    
    ----------------------------------------
Command "/Applications/Orange3.app/Contents/MacOS/PythonApp -u -c "import setuptools, tokenize;__file__='/private/var/folders/mz/wn4rsn9x671_y6ds8z4nn33m0000gn/T/pip-build-swbum7ko/ufal.udpipe/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/mz/wn4rsn9x671_y6ds8z4nn33m0000gn/T/pip-8122n_j8-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/mz/wn4rsn9x671_y6ds8z4nn33m0000gn/T/pip-build-swbum7ko/ufal.udpipe/
You are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
 
![screen shot 2018-09-27 at 6 25 01 pm](https://user-images.githubusercontent.com/43657290/46178037-2d38c680-c283-11e8-9537-73e99a5ef353.png)

**Comment by dariasin** [comment]
Hello,

Darwin


[Process completed]


This is what I am getting.


Attached please see the screenshot of the error. Thanks!



Best regards,

Daria

**Comment by viitormiiguel** [comment]
Some resolution? That happened in windows too.

**Comment by dariasin** [comment]
What do you mean?

**Comment by viitormiiguel** [comment]
The same problem happened on windows. 

![image](https://user-images.githubusercontent.com/37383230/46238019-c25cbd80-c35e-11e8-98df-77b9cd5bf732.png)

Collecting Orange3-Text
  Using cached https://files.pythonhosted.org/packages/69/06/40c8eb64755885e6028dc3dc8b18fc1301cfec0bba65398f70abe691ba2c/Orange3_Text-0.5.1-py3-none-any.whl
Collecting odfpy>=1.3.5 (from Orange3-Text)
Requirement already satisfied: scikit-learn in c:\orange\lib\site-packages (from Orange3-Text) (0.19.2)
Requirement already satisfied: setuptools-git in c:\orange\lib\site-packages (from Orange3-Text) (1.2)
Requirement already satisfied: simhash in c:\orange\lib\site-packages (from Orange3-Text) (1.9.0)
Requirement already satisfied: scipy in c:\orange\lib\site-packages (from Orange3-Text) (1.1.0)
Requirement already satisfied: validate-email in c:\orange\lib\site-packages (from Orange3-Text) (1.3)
Collecting biopython (from Orange3-Text)
  Using cached https://files.pythonhosted.org/packages/59/25/1f27e85f6462b4ae4f2b112715f174b4bc370341f0adf2f63bb5acd43052/biopython-1.72-cp36-cp36m-win32.whl
Requirement already satisfied: beautifulsoup4 in c:\orange\lib\site-packages (from Orange3-Text) (4.6.3)
Collecting tweepy (from Orange3-Text)
  Using cached https://files.pythonhosted.org/packages/05/f1/2e8c7b202dd04117a378ac0c55cc7dafa80280ebd7f692f1fa8f27fd6288/tweepy-3.6.0-py2.py3-none-any.whl
Collecting ufal.udpipe (from Orange3-Text)
  Using cached https://files.pythonhosted.org/packages/f7/20/9fdf23855a8dbb018b91f798d5923fd3aadff5d1d8bee39187973f8e17bc/ufal.udpipe-1.2.0.1.tar.gz
Requirement already satisfied: Orange3>=3.4.3 in c:\orange\lib\site-packages (from Orange3-Text) (3.16.0)
Collecting docx2txt>=0.6 (from Orange3-Text)
Requirement already satisfied: numpy in c:\orange\lib\site-packages (from Orange3-Text) (1.14.5)
Requirement already satisfied: wikipedia in c:\orange\lib\site-packages (from Orange3-Text) (1.4.0)
Requirement already satisfied: nltk>=3.0.5 in c:\orange\lib\site-packages (from Orange3-Text) (3.3)
Requirement already satisfied: gensim>=0.12.3 in c:\orange\lib\site-packages (from Orange3-Text) (3.6.0)
Requirement already satisfied: lxml in c:\orange\lib\site-packages (from Orange3-Text) (4.2.5)
Collecting pdfminer3k>=1.3.1 (from Orange3-Text)
Collecting PySocks>=1.5.7 (from tweepy->Orange3-Text)
  Using cached https://files.pythonhosted.org/packages/53/12/6bf1d764f128636cef7408e8156b7235b150ea31650d0260969215bb8e7d/PySocks-1.6.8.tar.gz
Requirement already satisfied: six>=1.10.0 in c:\orange\lib\site-packages (from tweepy->Orange3-Text) (1.10.0)
Collecting requests-oauthlib>=0.7.0 (from tweepy->Orange3-Text)
  Using cached https://files.pythonhosted.org/packages/94/e7/c250d122992e1561690d9c0f7856dadb79d61fd4bdd0e598087dce607f6c/requests_oauthlib-1.0.0-py2.py3-none-any.whl
Requirement already satisfied: requests>=2.11.1 in c:\orange\lib\site-packages (from tweepy->Orange3-Text) (2.19.1)
Requirement already satisfied: keyrings.alt in c:\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (2.2)
Requirement already satisfied: joblib>=0.9.4 in c:\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (0.11)
Requirement already satisfied: keyring in c:\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (10.3.1)
Requirement already satisfied: setuptools>=36.3 in c:\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (40.2.0)
Requirement already satisfied: xlrd>=0.9.2 in c:\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (1.0.0)
Requirement already satisfied: python-louvain in c:\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (0.11)
Requirement already satisfied: bottleneck>=1.0.0 in c:\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (1.2.0)
Requirement already satisfied: docutils in c:\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (0.13.1)
Requirement already satisfied: networkx in c:\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (2.1)
Requirement already satisfied: matplotlib>=2.0.0 in c:\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (2.2.3)
Requirement already satisfied: chardet>=3.0.2 in c:\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (3.0.4)
Requirement already satisfied: pip>=9.0 in c:\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (10.0.1)
Requirement already satisfied: pyqtgraph>=0.10.0 in c:\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (0.10.0)
Requirement already satisfied: AnyQt>=0.0.8 in c:\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (0.0.8)
Requirement already satisfied: serverfiles in c:\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (0.2.1)
Requirement already satisfied: smart-open>=1.2.1 in c:\orange\lib\site-packages (from gensim>=0.12.3->Orange3-Text) (1.7.1)
Collecting pytest>=2.0 (from pdfminer3k>=1.3.1->Orange3-Text)
  Using cached https://files.pythonhosted.org/packages/0c/9a/592314ceda78f3307afb6cf56d7fdbb92c5a5960a88a6d2fd25c11312ead/pytest-3.8.1-py2.py3-none-any.whl
Collecting ply>=3.4 (from pdfminer3k>=1.3.1->Orange3-Text)
  Using cached https://files.pythonhosted.org/packages/a3/58/35da89ee790598a0700ea49b2a66594140f44dec458c07e8e3d4979137fc/ply-3.11-py2.py3-none-any.whl
Collecting oauthlib>=0.6.2 (from requests-oauthlib>=0.7.0->tweepy->Orange3-Text)
  Using cached https://files.pythonhosted.org/packages/e6/d1/ddd9cfea3e736399b97ded5c2dd62d1322adef4a72d816f1ed1049d6a179/oauthlib-2.1.0-py2.py3-none-any.whl
Requirement already satisfied: urllib3<1.24,>=1.21.1 in c:\orange\lib\site-packages (from requests>=2.11.1->tweepy->Orange3-Text) (1.23)
Requirement already satisfied: certifi>=2017.4.17 in c:\orange\lib\site-packages (from requests>=2.11.1->tweepy->Orange3-Text) (2018.8.24)
Requirement already satisfied: idna<2.8,>=2.5 in c:\orange\lib\site-packages (from requests>=2.11.1->tweepy->Orange3-Text) (2.7)
Requirement already satisfied: pywin32-ctypes; sys_platform == "win32" in c:\orange\lib\site-packages (from keyring->Orange3>=3.4.3->Orange3-Text) (0.0.1)
Requirement already satisfied: decorator>=4.1.0 in c:\orange\lib\site-packages (from networkx->Orange3>=3.4.3->Orange3-Text) (4.3.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\orange\lib\site-packages (from matplotlib>=2.0.0->Orange3>=3.4.3->Orange3-Text) (2.2.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\orange\lib\site-packages (from matplotlib>=2.0.0->Orange3>=3.4.3->Orange3-Text) (2.7.3)
Requirement already satisfied: pytz in c:\orange\lib\site-packages (from matplotlib>=2.0.0->Orange3>=3.4.3->Orange3-Text) (2018.5)
Requirement already satisfied: cycler>=0.10 in c:\orange\lib\site-packages (from matplotlib>=2.0.0->Orange3>=3.4.3->Orange3-Text) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\orange\lib\site-packages (from matplotlib>=2.0.0->Orange3>=3.4.3->Orange3-Text) (1.0.1)
Requirement already satisfied: boto3 in c:\orange\lib\site-packages (from smart-open>=1.2.1->gensim>=0.12.3->Orange3-Text) (1.9.14)
Requirement already satisfied: bz2file in c:\orange\lib\site-packages (from smart-open>=1.2.1->gensim>=0.12.3->Orange3-Text) (0.98)
Requirement already satisfied: boto>=2.32 in c:\orange\lib\site-packages (from smart-open>=1.2.1->gensim>=0.12.3->Orange3-Text) (2.49.0)
Collecting atomicwrites>=1.0 (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text)
  Using cached https://files.pythonhosted.org/packages/3a/9a/9d878f8d885706e2530402de6417141129a943802c084238914fa6798d97/atomicwrites-1.2.1-py2.py3-none-any.whl
Collecting colorama; sys_platform == "win32" (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text)
  Using cached https://files.pythonhosted.org/packages/db/c8/7dcf9dbcb22429512708fe3a547f8b6101c0d02137acbd892505aee57adf/colorama-0.3.9-py2.py3-none-any.whl
Collecting py>=1.5.0 (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text)
  Using cached https://files.pythonhosted.org/packages/c8/47/d179b80ab1dc1bfd46a0c87e391be47e6c7ef5831a9c138c5c49d1756288/py-1.6.0-py2.py3-none-any.whl
Collecting attrs>=17.4.0 (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text)
  Using cached https://files.pythonhosted.org/packages/3a/e1/5f9023cc983f1a628a8c2fd051ad19e76ff7b142a0faf329336f9a62a514/attrs-18.2.0-py2.py3-none-any.whl
Collecting more-itertools>=4.0.0 (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text)
  Using cached https://files.pythonhosted.org/packages/79/b1/eace304ef66bd7d3d8b2f78cc374b73ca03bc53664d78151e9df3b3996cc/more_itertools-4.3.0-py3-none-any.whl
Collecting pluggy>=0.7 (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text)
  Using cached https://files.pythonhosted.org/packages/f5/f1/5a93c118663896d83f7bcbfb7f657ce1d0c0d617e6b4a443a53abcc658ca/pluggy-0.7.1-py2.py3-none-any.whl
Requirement already satisfied: s3transfer<0.2.0,>=0.1.10 in c:\orange\lib\site-packages (from boto3->smart-open>=1.2.1->gensim>=0.12.3->Orange3-Text) (0.1.13)
Requirement already satisfied: botocore<1.13.0,>=1.12.14 in c:\orange\lib\site-packages (from boto3->smart-open>=1.2.1->gensim>=0.12.3->Orange3-Text) (1.12.14)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in c:\orange\lib\site-packages (from boto3->smart-open>=1.2.1->gensim>=0.12.3->Orange3-Text) (0.9.3)
Installing collected packages: odfpy, biopython, PySocks, oauthlib, requests-oauthlib, tweepy, ufal.udpipe, docx2txt, atomicwrites, colorama, py, attrs, more-itertools, pluggy, pytest, ply, pdfminer3k, Orange3-Text
  Running setup.py install for PySocks: started
    Running setup.py install for PySocks: finished with status 'done'
  Running setup.py install for ufal.udpipe: started
    Running setup.py install for ufal.udpipe: finished with status 'error'
    Complete output from command C:\Orange\Scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\vitor\\AppData\\Local\\Temp\\pip-install-4i46xm_7\\ufal.udpipe\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\vitor\AppData\Local\Temp\pip-record-m4hvvl6u\install-record.txt --single-version-externally-managed --compile --install-headers C:\Orange\include\site\python3.6\ufal.udpipe:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.6
    creating build\lib.win32-3.6\ufal
    copying ufal\__init__.py -> build\lib.win32-3.6\ufal
    copying ufal\udpipe.py -> build\lib.win32-3.6\ufal
    running build_ext
    building 'ufal_udpipe' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    
    ----------------------------------------
Command "C:\Orange\Scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\vitor\\AppData\\Local\\Temp\\pip-install-4i46xm_7\\ufal.udpipe\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\vitor\AppData\Local\Temp\pip-record-m4hvvl6u\install-record.txt --single-version-externally-managed --compile --install-headers C:\Orange\include\site\python3.6\ufal.udpipe" failed with error code 1 in C:\Users\vitor\AppData\Local\Temp\pip-install-4i46xm_7\ufal.udpipe\
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by dariasin** [comment]
So what should I do?

**Comment by dariasin** [comment]
I don’t have windows. How long will you take to solve the issue?

**Comment by PrimozGodec** [comment]
@dariasin We released a new version. Can you try to install the add-on now? The new version is 0.5.2.

**Comment by dariasin** [comment]
Hi there,

I was able to add the Text add-on without updating Orange to a new version.
What I did was, I
went to orange > preferences> add-ons and I *unchecked* conda. Then I
reloaded Orange and I got my add on working!
Should I still update the version? I am just a bit concerned that it won't
work again.
Please advise.

**Comment by PrimozGodec** [comment]
@dariasin unchecking Conda does not affect your installation on Mac. I think that the reason for you being able to install addon is patch we released yesterday. 

We suggest updating Orange. I think it should not affect the add-on. With updating, you will get some new Orange features.

**Comment by PrimozGodec** [comment]
Since I think we resolved the issue, I am closing it. You are welcome to reopen it again if the bug appears again.
