### ISSUE TITLE
Is there a way to split the data set into 90% past 10% future?

### ISSUE THREAD

**Issue by enjoysmath** [biolab/orange3#3273]
I have a dataset that is sequentially captured points, and I want to split it at 90% / 10% meaning the first 90% of the sequential timeseries data will be training data and the last 10% is test data.  This is working for us.  However, I'm doing the split by setting a column as P or F and in the external program that generates the dataset file we have to set `numTrainingSamples` to whatever is needed to reach 90/10%.  So this is ridiculous right?  How can I just split up the dataset??

**Comment by matejklemen** [comment]
_One way to do this_ would be to use 2x Python Script widget (Data -> Python Script) and use one to select the first 90% of the data and the other to select the last 10% of the data.

More specifically, the first script (_Train_ in the picture) should contain something like `out_data = in_data[:int(0.9 * len(in_data)), :]` and the second script (_Test_) should contain `out_data = in_data[int(0.9 * len(in_data)):, :]`.

![screenshot from 2018-10-02 23-31-40](https://user-images.githubusercontent.com/17293960/46378282-64e8a980-c69b-11e8-9a07-7a06ba66201d.png)

Disclaimer: there might be a better (easier) way to do this, but the described approach might be atleast a tiny bit better than what you're doing right now.

**Comment by enjoysmath** [comment]
@matejklemen Thanks.  I didn't think of that method. 

What we decided to do is make a Data Splitter widget with a slider on it! :)

Making widgets for Orange is easy.  Once you have one down, the rest is just PyQt5 which I've done for 4 years now.

**Comment by ajdapretnar** [comment]
Perhaps is would make sense to have a look at this issue: https://github.com/biolab/orange3/issues/3198. Is there a way to include this in a Data Sampler, make it better? :)
