### ISSUE TITLE
MemoryError loading 100MB pickled Neural Net model in Dev Version of code.

### ISSUE THREAD

**Issue by enjoysmath** [biolab/orange3#3274]
Version: 3.17.0.dev0+ac7d919
git revision: ac7d919

I need to use the dev version of Orange in order to install custom widgets, right?  So I am doing that, but not without annoying Errors.  So I had to train with the release version (don't need custom widgets for that stage of our process.  

It's just at loading a 100MB 140 feature NN model, it fails with Memory error and more specifically:

[This screen shot](https://prnt.sc/l0bqv7)

And when I first start Orange, it presents a more comprehensive error box with this text:

```
Exception:
MemoryError
Module:
Orange.widgets.model.owloadmodel:105
Widget Name:
Load Model
Widget Module:
Orange.widgets.model.owloadmodel:95
Widget Scheme:
C:\Users\FRUITF~1\AppData\Local\Temp\2\ows-251fxb70.ows.xml
Version:
3.17.0.dev0+ac7d919
Environment:
Python 3.5.2 on Windows 10 10.0.14393 AMD64
Installed Packages:
AnyQt==0.0.8, BinaryBuyOrder==0.0.0, Bottleneck==1.2.1, MetaTraderDataCapture==0.0.0, Orange3==3.17.0.dev0+ac7d919, PyQt5-sip==4.19.12, PyQt5==5.9, certifi==2018.8.24, chardet==3.0.4, cycler==0.10.0, decorator==4.3.0, docutils==0.14, entrypoints==0.2.3, idna==2.7, joblib==0.12.5, keyring==15.1.0, keyrings.alt==3.1, kiwisolver==1.0.1, matplotlib==3.0.0, networkx==2.2, numpy==1.15.1, pandas==0.23.4, pip==18.0, psycopg2==2.7.5, pymssql==2.1.4, pynput==1.4, pyparsing==2.2.1, pypiwin32==223, pyqtgraph==0.10.0, python-dateutil==2.7.3, python-louvain==0.11, pytz==2018.5, pywin32-ctypes==0.2.0, pywin32==223, requests==2.19.1, scikit-learn==0.19.2, scipy==1.1.0, selenium==3.14.1, serverfiles==0.2.1, setuptools==40.4.2, sip==4.19.8, six==1.11.0, urllib3==1.23, xlrd==1.1.0
Machine ID:
143789007684672
Stack Trace:
Traceback (most recent call last):
  File "c:\users\fruitfulapproach\desktop\mechanikos\orange3\Orange\widgets\model\owloadmodel.py", line 95, in browse
    self.load(filename)
  File "c:\users\fruitfulapproach\desktop\mechanikos\orange3\Orange\widgets\model\owloadmodel.py", line 105, in load
    model = pickle.load(f)
MemoryError

Local Variables:
OrderedDict([('f',
              <_io.BufferedReader name='C:/Users/fruitfulapproach/Desktop/Mechanikos/MECHANIKOS-ORANGE-NERF/OrangeModels/NeuralNet_USDJPY_60mins.pkcls'>),
             ('filename',
              'C:/Users/fruitfulapproach/Desktop/Mechanikos/MECHANIKOS-ORANGE-NERF/OrangeModels/NeuralNet_USDJPY_60mins.pkcls'),
             ('self',
              <Orange.widgets.model.owloadmodel.OWLoadModel object at 0x15F88120>)])

```

How can I install my widgets into a working release version or how can I get around these memory errors?  We have plenty of memory for training therefore there's more than enough memory for prediction, namely 32GB of memory on a GCP server running Windows DataCenter 2016 Server.

**Comment by markotoplak** [comment]
Not connected with your bug, but you could also add custom widgets to the released version. Just copy corresponding files into the correct folder (search for existing widgets and just copy them there - they will be detected the next time you run Orange).

**Comment by enjoysmath** [comment]
@markotoplak I looked and there is no such directory of widgets.  Please show me how to find it.  It must be somewhere else (not in application dir C:\Orange)...  Thanks.  I've coded a PostgresSQLWriter widget if you would like it.

**Comment by markotoplak** [comment]
Try to find a file called "owneuralnetwork.py" on your computer and you will find your directory.

**Comment by enjoysmath** [comment]
> Try to find a file called "owneuralnetwork.py" on your computer and you will find your directory.

Mark, I tried exactly what you would expect.  Created a directory called mechanikos in widgets or even tried this in widgets itself;  with a folder called icons and each of the custom widget main files.  Nothing showed up upon running Orange.  However doing this in each of the widget directories at the command line worked:

C:\Orange\python.exe -m pip install .

Where in particular we earlier decided to install Orange3.16 to C:\Orange\ and not the default location.  This is the reason to do that.

**Comment by enjoysmath** [comment]
> Probably the best idea, if you want to write new widgets, is to fork [example add-on](https://github.com/biolab/orange3-example-addon) and add widgets there. Then you can either decide to rebrand it as your own add-on, or submit a PR to prototypes or one of the existing add-ons.
> 
> Add-ons can be installed to any orange installation, even stable release versions.

They should be really specific about which pip to use this being a Miniconda thing and all.  I found that doing C:\Orange\python -m pip worked for my standard install.  See above.
