### ISSUE TITLE
How do you catch exceptions in debugging IDE instead of in a QMessageBox that's used?

### ISSUE THREAD

**Issue by enjoysmath** [biolab/orange3#3275]
Hello, 

Trying to learn how to debug orange and was wondering if there is a flag to direct exceptions to the IDE (let them raise through).

**Comment by kernc** [comment]
Don't know what you mean by raise through, but you can hook into `sys.excepthook` like we do in
https://github.com/biolab/orange3/blob/a782062a514f8376c5b2371c8f89aa1c460842e9/Orange/canvas/__main__.py#L506-L508
and
https://github.com/biolab/orange3/blob/a782062a514f8376c5b2371c8f89aa1c460842e9/Orange/canvas/application/errorreporting.py#L178-L268

If you set a breakpoint somewhere inside the set exception hook, your IDE should "get" it.

Aside, exception backtraces should always be printed to stderr when Orange is run from the console. If not, that's a bug.
