### ISSUE TITLE
Hello, I'm using orange Canvas and once I drop the preprocess text I keep getting an error which I have tried using different PC but the same error keep popping up.

### ISSUE THREAD

**Issue by ahmadalshammeri** [biolab/orange3#3277]
##### Additional info (worksheets, data, screenshots, ...)

![preprocess text error](https://user-images.githubusercontent.com/43742168/46287654-e18c6280-c58b-11e8-84c2-5f79eb2f12e7.JPG)

**Comment by ajdapretnar** [comment]
Please use the issue temple to report the issue. Also, this should be reported to [Orange3-Text](https://github.com/biolab/orange3-text/issues).

**Comment by robertcv** [comment]
See [#386](https://github.com/biolab/orange3-text/issues/386).
