### ISSUE TITLE
Set a fixed random seed in Louvain Clustering

### ISSUE THREAD

**Issue by mstrazar** [biolab/orange3#3278]
##### Expected behavior
Clusters in Louvain clustering are reproducible between different runs.

##### Actual behavior
Clusters are always different because random seed is not set. Set random seed to 0.

##### Additional info (worksheets, data, screenshots, ...)
See orange3-single-cell/OWTsne.

**Comment by mstrazar** [comment]
@pavlin-policar have time for this?

**Comment by pavlin-policar** [comment]
I'll try to get it done as soon as possible.

**Comment by iamved** [comment]
`<!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Box | Secure content-sharing that users and IT love and adopt</title>

	
	
		
			<link rel="stylesheet" href="https://cdn01.boxcdn.net/_assets/css/vendor/box/box-ui-0.7.7-xRyNay.css" type="text/css" media="screen" />
		
			<link rel="stylesheet" href="https://cdn01.boxcdn.net/_assets/css/signup/core_signup-WOF6mZ.css" type="text/css" media="screen" />
		
			<link rel="stylesheet" href="https://cdn01.boxcdn.net/_assets/css/core-DVQw4k.css" type="text/css" media="screen" />
		
			<link rel="stylesheet" href="https://cdn01.boxcdn.net/_assets/css/sprites/signup_login-sprite-XkBrsz.css" type="text/css" media="screen" />
		
			<link rel="stylesheet" href="https://cdn01.boxcdn.net/_assets/css/login/core_login-X6Uhui.css" type="text/css" media="screen" />
		
			<link rel="stylesheet" href="https://cdn01.boxcdn.net/_assets/css/dmca/core-f57Qan.css" type="text/css" media="screen" />
		
	
</head>
<style type="text/css">
	td {
	width: 50%;
}
</style>
<body id="site_body">




 <body> 
	<div class="marketing-content">
		
		
<div id="envelope-background">
	<div class="center_container double-width">
		<div class="container_header ptl">
			<div class="title-logo sprite_signup_login_box_logo">&nbsp;</div>
			<div class="title_text">
				
				Copyright Complaint Form
			</div>
			<div class="title_subtext txt-small pts"></div>
		</div>

		<div class="login_form txt_l txt-small dmca-form">

			<div align="center">
				

				
			</div>

			<br />
			<form method="post" action="/index.php?rm=dmca_takedown_process_request">
				<input type="hidden" name="request_token" value="adb83a36840ccc493255626459089a0a1c65f4abd7fcd007eb94a5cb9bf84a8c"/>
				<ul class="field_set">
					<div id="login_fields">
						<table cellspacing="0">
							<tr>
								
								<td><span class="required-placeholder">*</span>&nbsp;<span class="title_subtext txt-small pts">Copyright Owner's Full Name</span></td>
								<td><input type="text" size="25" maxlength="255" name="copyright_owner_name" id="copyright-owner-name" value="" placeholder="Copyright Owner's Full Name" required/></td>
							</tr>
							<tr><td colspan="2"><br><br></tr>
							<tr>
								
								<td><span class="required-placeholder">*</span>&nbsp;<span class="title_subtext txt-small pts">Requester's Full Name</span></td>
								<td><input type="text" size="25" maxlength="255" name="requester_full_name" id="requester-full-name" value="" placeholder='Your Full Name' required/></td>
							</tr>
							<tr><td colspan="2"><br><br></tr>
							<tr>
								
								<td ><span class="required-placeholder">*</span>&nbsp;<span class="title_subtext txt-small pts">Requester's Identity (Individual / Company Name)</span></td>
								<td ><input type="text"  size="25" maxlength="255" name="requester_individual_company" id="requester-individual-company" value="" placeholder="Company / Individual" required/></td>
							</tr>
							<tr><td colspan="2"><br><br></tr>
							<tr>
								
								<td><span class="required-placeholder">*</span>&nbsp;<span class="title_subtext txt-small pts">Requester's Email Address</span></td>
								<td><input type="email" size="25" maxlength="255" name="requester_email_address" id="requester-email-address" value="" placeholder="Your Email (ex: support@box.com)" required/></td>
							</tr>
							<tr><td colspan="2"><br><br></tr>
							<tr>
								
								<td><span class="required-placeholder">*</span>&nbsp;<span class="title_subtext txt-small pts">Requester's Address</span></td>
								<td><textarea cols="40" ows="5" name="requester_address" id="requester-address" placeholder="Your Complete Address" required></textarea></td>
							</tr>
							<tr><td colspan="2"><br><br></tr>
							<tr>
								
								<td><span class="required-placeholder">*</span>&nbsp;<span class="title_subtext txt-small pts">URLs of Offending Content</span></td>
		`

**Comment by iamved** [comment]
`<!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Box | Secure content-sharing that users and IT love and adopt</title>

	
	
		
			<link rel="stylesheet" href="https://cdn01.boxcdn.net/_assets/css/vendor/box/box-ui-0.7.7-xRyNay.css" type="text/css" media="screen" />
		
			<link rel="stylesheet" href="https://cdn01.boxcdn.net/_assets/css/signup/core_signup-WOF6mZ.css" type="text/css" media="screen" />
		
			<link rel="stylesheet" href="https://cdn01.boxcdn.net/_assets/css/core-DVQw4k.css" type="text/css" media="screen" />
		
			<link rel="stylesheet" href="https://cdn01.boxcdn.net/_assets/css/sprites/signup_login-sprite-XkBrsz.css" type="text/css" media="screen" />
		
			<link rel="stylesheet" href="https://cdn01.boxcdn.net/_assets/css/login/core_login-X6Uhui.css" type="text/css" media="screen" />
		
			<link rel="stylesheet" href="https://cdn01.boxcdn.net/_assets/css/dmca/core-f57Qan.css" type="text/css" media="screen" />
		
	
</head>
<style type="text/css">
	td {
	width: 50%;
}`

**Comment by iamved** [comment]
`<style type="text/css">
	td {
	width: 50%;
}
</style>`

**Comment by iamved** [comment]
`<!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Box | Secure content-sharing that users and IT love and adopt</title>

	
	
		
			<link rel="stylesheet" href="https://cdn01.boxcdn.net/_assets/css/vendor/box/box-ui-0.7.7-xRyNay.css" type="text/css" media="screen" />
		
			<link rel="stylesheet" href="https://cdn01.boxcdn.net/_assets/css/signup/core_signup-WOF6mZ.css" type="text/css" media="screen" />
		
			<link rel="stylesheet" href="https://cdn01.boxcdn.net/_assets/css/core-DVQw4k.css" type="text/css" media="screen" />
		
			<link rel="stylesheet" href="https://cdn01.boxcdn.net/_assets/css/sprites/signup_login-sprite-XkBrsz.css" type="text/css" media="screen" />
		
			<link rel="stylesheet" href="https://cdn01.boxcdn.net/_assets/css/login/core_login-X6Uhui.css" type="text/css" media="screen" />
		
			<link rel="stylesheet" href="https://cdn01.boxcdn.net/_assets/css/dmca/core-f57Qan.css" type="text/css" media="screen" />
		
	
</head>
<style type="text/css">
	td {
	width: 50%;
}
</style>`

**Comment by mstrazar** [comment]
You can monitor a more general issue #3287

**Comment by pavlin-policar** [comment]
So is this really an issue with Louvain clustering? Apparently, I had considered this when I was writing the code, and Louvain clustering should be deterministic. Louvain clustering could be randomized, but there is no good way to set a random seed for the library we currently use, we can only choose to randomize or not randomize, so not randomize is better.

I also tested this by running Louvain clustering repeatedly on a fairly large data set (5000 samples) and visualizing the cluster colors in scatterplot, and, indeed, the colors don't change.

I'm guessing some other part of the workflow had randomness that wasn't addressed? Could you provide a workflow where this issue occurs?
