### ISSUE TITLE
Failed to concatenate

### ISSUE THREAD

**Issue by Avicena507** [biolab/orange3#3298]
Orange version

3.13

Expected behavior

Concatenate two tables horizontally

Actual behavior

Combines the two tables but not all values copied, questionmarks appear

Make new table manually , using Table.from_domain(domain,n_rows=1), 
make several table and then concatenate them using Table.concatenate([table_1, table_2], axis=0)

result:

![image](https://user-images.githubusercontent.com/41800734/46623401-b8ee0500-cb57-11e8-8f90-817ff414851f.png)

**Comment by markotoplak** [comment]
Orange will only concatenate columns with the same feature descriptor (Orange.data.Variable).

If you are constructing the table manually, the features have to be the same objects. If you created domains independently, it will not work.

If you are reading data from files, however, columns from different files with the same name, type (and for nominal features, number of values) will be assigned the same feature descriptor.
