### ISSUE TITLE
URL used in file widget disappeared when saved

### ISSUE THREAD

**Issue by tpotipiti** [biolab/orange3#3309]
##### Orange version

3.13

##### Expected behavior
URL in the file widget should be saved when the .ows was saved.

##### Actual behavior
URL in the file widget disappeared after save .ows and reload.

##### Steps to reproduce the behavior
1. open a file widget
2. enter any URL
3. save the workflow
4. open the workflow saved. 
5. check the URL in the file widget

**Comment by ajdapretnar** [comment]
I cannot reproduce this.
