### ISSUE TITLE
Louvain clustering: after deletion still using resources

### ISSUE THREAD

**Issue by AndrejaKovacic** [biolab/orange3#3312]
##### Orange version

3.17.dev

##### Expected behavior
If Louvain  clustering widget is deleted, it should terminate calculations and release all used memory.

##### Actual behavior
When the widget is deleted, calculations continue and in best case terminate some times later. If the widget is deleted early on, sometimes it seems it becomes stuck on some step (maybe it can't receive some signal?), and never terminates on it's own.

##### Steps to reproduce the behavior
Load some dataset, connect in to louvain clustering, delete the widget before it is done.

**Comment by markotoplak** [comment]
Nice find. Ales is fixing the problem for the base widget class (see gh-3296). 

When that is fixed, we should check all individual widgets, because it is so easy to do something stupid that prevents GC.

**Comment by janezd** [comment]
@AndrejaKovacic, can you check this again? If Ales fixed it, you can close the issue.

**Comment by AndrejaKovacic** [comment]
It seems fixed, closing the issue.
