### ISSUE TITLE
Problem with orange installation 

### ISSUE THREAD

**Issue by Polina1609** [biolab/orange3#3314]
##### Orange version

3.16

##### Expected behavior
Should start working after installation

##### Actual behavior
However it writes an error because it could not find or load the Qt platform plugin "windows" in ""

##### Additional info (worksheets, data, screenshots, ...)

![default](https://user-images.githubusercontent.com/44099825/46888621-aaf6f780-ce69-11e8-96dc-4a9d5d7a6648.PNG)

**Comment by ales-erjavec** [comment]
Which installer did you use to install orange (the one with Miniconda or the 'classic' one)?

What path did you install orange in?

Did you install for all users or single user only?

**Comment by janezd** [comment]
Closed for inactivity.
