### ISSUE TITLE
Eliminate sizing by overlap in scatter plot (and other projections)

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#3315]
Projections show data instances as symbols of different sizes, colors and shapes, and marked with labels. We also have jittering, backgrounds colored by majority and add-ons for particular projections, such as regression lines in the scatter plot. Subset can be represented with filled symbols.

When overlap is enabled, projections show data symbols of different sizes<strike>, colors and shapes, and marked with labels. We also have jittering, backgrounds colored by majority and add-ons for particular projections, such as regression lines in the scatter plot. Subset can be represented with filled symbols.</strike>

It's a completely different beast. Trying to implement this properly is like stuffing another visualization into an existing one. All methods have to have a special condition that overrides the default behaviour. (One particular annoyance is that even the number of points change from len(data) to the number of combinations.) Yes, colors can be replaced with majority colors, but this is wrong anyway. (Or, yes, we can use pie charts, but consider that the plot's basic ingredient is then no longer a ScatterplotItem but a list of QGraphicsEllipseItems - it's another plot altogether.) Shapes and labels must be disabled, and jittering too. Background must be computed from distributions. Regression lines and similar stuff must be disabled. There are no more subsets. 

The cost is great: it makes the current neat implementation a hodgepodge of special cases. But the benefit is zero. Symbol sizes are not a good visualization for numerical quantities. For pairs of discrete features, we have box plots (or Mosaic, to add colors). If we want to have discrete + numeric, let's add violin plots. For numeric vs. numeric, there is either no overlap or they can be discretized or scatter plot with jittering should do the job.

If, however, scatter plots of pie charts seem useful, let us have another widget for that. Overlaps in current projections must be gone asap.

**Comment by ajdapretnar** [comment]
I really like this feature, but more from an aesthetic point of view than a practical one. I agree, it has little sense to use this in core visualizations. But where it would really come in handy, it would be Geo Map from the Geo add-on. There, you would often have overlapping geolocations and you would, for example, want to observe how many tweets came from which location. It would also be nice to set some 'sameness criterium', that would allow you to group together data points with geolocation distance lower then some number.

**Comment by janezd** [comment]
Can we agree that sizing by overlaps disables coloring? In this case, everything a widget needs to implement overlaps is contained in two methods (https://github.com/biolab/orange3/pull/3316/files#diff-40432802b4e54da15ba8e276c795d9d6L101  and https://github.com/biolab/orange3/pull/3316/files#diff-40432802b4e54da15ba8e276c795d9d6L175) that can be packed into a mixin (the second one would be called from the geo widgets override of `get_size_data`). Plus some logic for disabling sizes, of course; again in a mixin if needed.

If we don't agree, then sizing by overlap should replace symbols with pie charts. In this case, the widget should switch between the scatter plot and an entirely different visualization. If so, the above methods belong to this new visualization.
