### ISSUE TITLE
Why does Orange allow plotting discrete variables in scatter plots?!

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#3318]
I'm just preparing lectures and I'm thinking about how to persuade students against using scatter plots for showing discrete variables. Student often (ab)use the scatter plot instead of using more appropriate visualizations. But then I thought --- why does Orange allow it in the first place?!?!

A semi-useful case is to put the gender on y-axis and age on x-axis and see whether the age of women in our data is lower or higher or more spread out than the men's. However, what we actually observe in this case are distributions, and there's another, better widget for that (Distribution, Box plot). (And which does not require explaining away the jittering of genders.)

Plotting two discrete variables in a scatter plot is probably always a bad idea. If we plot, say, gender vs. four different types of chest pain, we project all data into just 2 x 4 = 8 points and then use jittering to spread them around these eight points. What kind of information can we get from this visualization? We can count the points around each of the few points (8, in above case). Or use the famous "overlap by size" feature to represent the counts by sizes --- which are known to be a bad way to visualize and compare magnitudes. This information is presented much better in Box plots, Distributions and Mosaic. This also goes for observing colors of jittered points; mosaic does it better.

Does anybody have a good argument for allowing discrete variables for scatter plots axes? Something that is not done much better with Distributions, Mosaic and Sieve? Aren't we promoting a bad practice here?

**Comment by lanzagar** [comment]
I agree with the above.
Another drawback of having categorical variables is that vizrank becomes much less useful. The "quality scores" for pairs with categorical variables cannot be directly/fairly compared to continuous ones.

So are we thinking about just filtering out all categorical vars and allowing only numeric ones in the x/y axis dropdowns? This is quite a big backwards-incompatible change. What do we do with old saved workflows - it would be nice to still see which variables were selected, but show an error saying only numeric vars are allowed now (and maybe even suggest alternatives such as Mosaic, Distributions, ...)? But from an implementation perspective, that is much more hassle than just not allowing vars in the dropdowns and clearing settings :)
