### ISSUE TITLE
Orange 3-Text does not download

### ISSUE THREAD

**Issue by riksri1** [biolab/orange3#3319]
When updated to Orange 3.16 Text Addon does not download since 2 days
<img width="960" alt="orange 3 text" src="https://user-images.githubusercontent.com/1832806/47200810-94c8ca00-d388-11e8-88d1-f6eabae75a09.png">

**Comment by robertcv** [comment]
Please go to Options -> Settings -> Add-ons and check "Install add-ons with conda". Then try installing the Text add-on again.

**Comment by riksri1** [comment]
Done as suggested still unable to install
