### ISSUE TITLE
Errors - crashes / some suggestions

### ISSUE THREAD

**Issue by Vasco10** [biolab/orange3#3324]
##### Orange version
3.16.0 - git rev: 4cfa80c

##### Actual behavior
Erratic behavior concerning some unexpected errors - it crashes. Even don't have the time to do a print-screen of the error mentioned.
Asked my peers if they experienced the same, some more others less.

##### Steps to reproduce the behavior
NA

##### Additional info (worksheets, data, screenshots, ...)
If there are some log files, please tell me where these are.

#### SUGGESTION ####
* It would be good to have an 'automatic save' for those who forgot to save their work. If not, you have to start from scratch! In my case I thought I had saved, lost about two hours intensive work - my bad!
* If there aren't any log files for any errors, it would be nice to have this feature.

**Comment by ajdapretnar** [comment]
Could you perhaps provide the information how you installed Orange and what add-on you have (or are using during the crash). I would say this is a segfault, which are notoriously difficult to catch. Normally, there are logs for errors that happen within the program, but if the program crashes, I am not sure we are catching anything.

**Comment by Vasco10** [comment]
I am using the classic installer from Orange3 site.
These frequent crashes come mainly from the add-on 'Text Mining', sometimes from other widgets.

**Comment by ajdapretnar** [comment]
We highly discourage installation via the classic installer. I would suggest going with the Miniconda installer, which solves the above-mentioned issues.

**Comment by Vasco10** [comment]
OK, I will have a try.

**Comment by janezd** [comment]
The problem is too unspecific to fix. As @ajdapretnar assumes, these must be core dumps, so Orange can't create any logs.
