### ISSUE TITLE
Orange 3 Recommendations

### ISSUE THREAD

**Issue by riksri1** [biolab/orange3#3325]
Fail to understand how to use Orange 3 Recommendations.

Addons does not have Orange 3 Recommendation widget.

Need help

**Comment by riksri1** [comment]
May be we can have a Video tutorial for step by step set up.

**Comment by ajdapretnar** [comment]
Orange3 Recommendations is, unfortunately not among our supported add-ons. Please write to the corresponding issue tracker if developer is willing to provide some guidance for you: https://github.com/biolab/orange3-recommendation/issues
