### ISSUE TITLE
Image Embedding not connecting to server

### ISSUE THREAD

**Issue by Deeprp** [biolab/orange3#3348]
Im using my office laptop and connecting to Orange 3 software using a proxy. But while using the Image analytic add on, Image embedding is not functioning. Below are the steps im taking,

1. Imported images from file folder
2. Can view in Image viewer
3. Can see it on a Data table
4. Connected to Image Embedding Widget and it throws up the error "No Connection with server", Click apply to try again

Can someone help in solving this issue?

##### Additional info (worksheets, data, screenshots, ...)
![image](https://user-images.githubusercontent.com/44636272/47777424-baf05180-dd1a-11e8-9a53-b0d2c9e35e27.png)

**Comment by ajdapretnar** [comment]
Could you perhaps ask this in the corresponding add-on repo: https://github.com/biolab/orange3-imageanalytics/issues
Thanks!

**Comment by ajdapretnar** [comment]
As a note to the side, you can set the proxy in Preferences - Network (probably Options - Network on Windows?).
