### ISSUE TITLE
UnsatisfiableError installing Orange on Ubuntu

### ISSUE THREAD

**Issue by vpejovic** [biolab/orange3#3366]
On Ubuntu 16.04 installing Orange3 via Conda:

"conda install orange3"

returns:

UnsatisfiableError: The following specifications were found to be in conflict:
- functools32
- orange3

**Comment by lanzagar** [comment]
Looks to me like functools32 is a library for python 2. Orange3 is for python 3.
I am guessing you installed one of the two libraries into the wrong python environment.
If you are trying this on python 3, then it should be safe to just remove functools32.

**Comment by vpejovic** [comment]
Thanks! That was it - a polluted environment.
