### ISSUE TITLE
Non-intrusive notifications in Canvas

### ISSUE THREAD

**Issue by irgolic** [biolab/orange3#3372]
##### Orange version
3.17.0

##### Expected behavior
Pop-up windows are aggressive, bringing immediate attention to themselves, disabling the program until the user responds to them. Available update notifications are currently delivered this way once per day if the user is not running the latest version of Orange.

Implementing a non-intrusive notifications system is integral to communicating news to the user in a friendly way.

An example of such a system is that of Jetbrains programs (PyCharm, CLion ...), appearing in the bottom-right corner of the program:
<img width="431" alt="screenshot 2018-11-08 at 15 18 03" src="https://user-images.githubusercontent.com/24586651/48207975-b7d41180-e369-11e8-988b-828279006457.png">

In addition to new updates, such a system could deliver notifications about:
- requesting permission to track usage statistics,
- Orange in media,
- blog posts.

Notifications of secondary importance should include a 'never show again' option.

A publicly hosted notification feed should consist of small JSON objects containing the following information:
- publish date/expiry date,
- notification type (critical, blog, ...),
- title,
- message, able to include hyperlink,
- when it should appear (wait time after application start).

A preferences pane should be added, allowing the user to enable/disable different types of notifications.

What are the use cases for this? Are there many different types of notifications we would want to display? If not, notification types could be generalized into only critical and trivial.

**Comment by janezd** [comment]
I agree. I wouldn't put this at the top priority, but it would be nice to have.

If you could implement it so that (some GUI) code can be reused in #3377, it would be even better. I think #3377 is even more important than this.

**Comment by ajdapretnar** [comment]
@janezd This can be closed, no?

**Comment by janezd** [comment]
@irgolic commented #3855 as "The first of (likely) three pull requests implementing #3372"

**Comment by janezd** [comment]
Closed via #3933.
