### ISSUE TITLE
Skip CI for maintenance PRs

### ISSUE THREAD

**Issue by astaric** [biolab/orange3#3374]
Both Travis and Appveyor can skip builds if a certain flag is present in the commit message:

- https://www.appveyor.com/docs/how-to/filtering-commits/
- https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build

Currently, when documentation or installation scripts change, appveryor spends an hour running the tests that fail only when they are indeterministic. Skipping the tests in such cases would free up appveyor for other PRs waiting in queue.

* [ ] update CI configuration (if needed)
* [ ] mention this in [Contributing Guide](https://github.com/biolab/orange3/blob/master/CONTRIBUTING.md)
* [ ] mention this in PR template?

**Comment by janezd** [comment]
We don't need to change anything: adding `[skip ci]` already works.
... and doesn't: Travis and AppVeyor don't report any results, but Github expects them, so the build is stalled.

We sped up Appveyor, so builds now finish in ~10 minutes.

**Comment by janezd** [comment]
I thought about this, but I think it's better that checks are mandatory unless explicitly overridden.

I'd prefer going the opposite way: we can use `[skip ci]` and use administrative privileges to merge. Not running CI tests is an exception that must be confirmed.

Another argument against disabling checks is that PRs for which we don't need to run them are exceptionally rare. Even when @ajdapretnar modifies documentation, she wants to see it built on Travis.

A use case that I can think of is when you're trying to fix a fail on Appveyor and don't want to run test on Travis or vice-versa. In this case, you can use `[skip travis]` until you succeed, and then change the commit to re-enable Travis. So stalled build is not a problem in this case, either.
