### ISSUE TITLE
Wrong installation when Anaconda already installed

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3375]
##### Orange version

3.17.0

##### Expected behavior
The Miniconda installer creates a separate virtual environment when installing Orange.

##### Actual behavior
Installation fails to create a proper venv when Anaconda already installed on the system. Then Orange runs with pip and cannot install certain add-ons.

##### Steps to reproduce the behavior
Have Anaconda installed previously!!! Then install Orange Miniconda .exe on top of it. Orange does not begin installing a new Python, since Anaconda is already installed. But the new environment is not where one would expect and CMD is not working properly.

**Comment by ajdapretnar** [comment]
It seems like Orange recognized Anaconda being installed, but it did not create a new virtual environment. Consequently, add-on are installed with pip directly. I might be wrong, but searching for a conda environment doesn't produce any results.

**Comment by ajdapretnar** [comment]
@ales-erjavec @acopar Could you please have a look?

**Comment by ales-erjavec** [comment]
Which version of conda is installed in the base environment?

**Comment by ajdapretnar** [comment]
Huh, whatever comes with the latest Anaconda distribution. I did a fresh installation of both Anaconda and Orange.
