### ISSUE TITLE
Widget errors are hard to notice

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#3377]
One of my colleagues commented that looking for red triangles is part of the fun in using Orange. 

If the widget is open, errors (in the status bar) are hard to notice. While that could be fine for information and (maybe) warnings, errors should be more noticeable. I do not know a good way to do it, but #3372  inspired me to write this issue.

Also, they could include hyperlinks (perhaps into documentation).

**Comment by janezd** [comment]
Test red background for errors.
