### ISSUE TITLE
Hierarchical Clustering: output Data when setting clusters with cutoff

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3385]
##### Orange version

3.18.dev

##### Expected behavior
HC outputs Data when selecting all the clusters.

##### Actual behavior
HC outputs this as Selected Data.

**Comment by ajdapretnar** [comment]
@janezd I hope I got this right. Please check.

**Comment by janezd** [comment]
It should output both. The same data for both, I suppose.
