### ISSUE TITLE
orange  3.17 installation

### ISSUE THREAD

**Issue by rosariorusso** [biolab/orange3#3391]
##### Orange version
3.17

##### Expected behavior
process installtion fault caused by :
ERROR conda.core.link:_execute(502): An error occurred while installing package 'conda-forge::commonmark-0.8.1-py_0'.
CondaError: Cannot link a source that does not exist.

**Comment by ajdapretnar** [comment]
Please provide more details. How did you install Orange and as what point does this error occur? Which OS are you using?

**Comment by JakaKokosar** [comment]
Running, 

```
conda update conda 
conda clean --all -y
```
 may resolve this.

**Comment by rosariorusso** [comment]
i used anaconda 5.3.

that's what i have found about : 
https://github.com/conda-forge/sphinx-argparse-feedstock/issues/12 

... Recently commonmark was bumped to 0.8.1 where the installed module is .... The following packages will be DOWNGRADED:

    commonmark: 0.8.1-py_0 conda-forge --> 0.7.5-py_0 conda-forge

**Comment by lanzagar** [comment]
Is this issue still relevant for the 3.18 installer?

**Comment by BlazZupan** [comment]
I am closing this issue. New installers became available. If this reemerges with new installers, please reopen. Thank you.
