### ISSUE TITLE
Merge large data sets

### ISSUE THREAD

**Issue by Lari30** [biolab/orange3#3397]
##### Orange version

3.17.0

##### Expected behavior
Merge two data sets on the chosen columns.

##### Actual behavior
For the first table I can choose the column name but for the second it shows only 'Position (Index)' in the Drop-Down List. This only happens with large data sets (mine are around 200'000 to 1'000'000 rows each).

##### Steps to reproduce the behavior
Merge two large data sets

##### Additional info (worksheets, data, screenshots, ...)
![orangeissue](https://user-images.githubusercontent.com/32925512/48468536-766db700-e7ec-11e8-8bcd-ce0ad4c2b67f.png)

**Comment by ajdapretnar** [comment]
It is very possible you don't have unique User-IDs. This is when the widget won't allow merging by the column.

**Comment by ajdapretnar** [comment]
Also, this is likely because instances aren't unique as they should be when merging.
