### ISSUE TITLE
Problem with miniconda installer (in order to install Orange)

### ISSUE THREAD

**Issue by YogevLatin** [biolab/orange3#3415]
- After running the next command: 'conda install orange'

- Got the following error:
Fatal Python error: Py_Initialize: unable to load the file system codec
  File "C:\Users\yogevl.UPTRADE\AppData\Local\Continuum\anaconda2\Lib\encodings\__init__.py", line 123
    raise CodecRegistryError,\
                            ^
SyntaxError: invalid syntax

Current thread 0x00001fe0 (most recent call first):
------

- **And when I run the next command:**
C:\Users\yogevl.UPTRADE>pip install orange3

- Got the following error:

Collecting orange3
  Using cached https://files.pythonhosted.org/packages/a6/fa/f46ea86a262ca80d36143239a794df25209ea75f7ca518944a8394e44c9c/Orange3-3.18.0.tar.gz
    Complete output from command python setup.py egg_info:
    Orange requires Python >= 3.4

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\yogevl~1.upt\appdata\local\temp\pip-install-8d0roj\orange3\

- I have python 3.6 and 2.7 installed (I'm using 2.7)

**Comment by ales-erjavec** [comment]
Orange3 is Python 3+  only. You cannot install it in a Python 2.7 environment.

**Comment by ajdapretnar** [comment]
Please see [installation instructions ](https://github.com/biolab/orange3)for details.
