### ISSUE TITLE
conda can not install orange3=3.18.0 on Windows

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#3421]
In a fresh Miniconda env

    conda install -v orange3=3.18.0

fails with

    conda.exceptions.NoPackagesFoundError: Dependencies missing in current win-64 channels:
      - orange3 3.18.0* -> fasttsne -> numba >=0.38.1
      - orange3 3.18.0* -> fasttsne -> scikit-learn >=0.20

Windows 7 64-bit.

Installation of 3.17 works fine.

**Comment by markotoplak** [comment]
I was using miniconda that came with Orange installation, with conda 4.3.14. If I updated conda to 4.3.30 (`conda update conda`), then I could install Orange 3.18.0 easily.

Do we have specific reasons to supply miniconda 4.3.14 (with python 3.6.0) in our Windows conda installer or these are just versions that were available when the installer scripts were made? @astaric @ales-erjavec

**Comment by astaric** [comment]
I currently use
MINICONDA_VERSION=4.5.11
PYTHON_VERSION=3.7.0
in installers I build.

**Comment by janezd** [comment]
@ales-erjavec, @markotoplak, can this be closed?
