### ISSUE TITLE
Cannot find a widget for SMOTE

### ISSUE THREAD

**Issue by Franjey** [biolab/orange3#3422]
I saw in this link that the code for SMOTE is already ready: https://github.com/biolab/orange3/issues/2995

I was wondering how can I find the widget for it.  Thanks.

**Comment by ajdapretnar** [comment]
@Franjey The referenced issue just calls a function from imblearn. These is no code for SMOTE in Orange nor a widget. If you wish to have it, feel free to implement it in the [Prototypes repository](https://github.com/biolab/orange3-prototypes).

**Comment by ajdapretnar** [comment]
Ah, sorry. My bad, didn't see this PR.
