### ISSUE TITLE
tSNE indeterministically fails on appveyor

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#3431]
Rerunning it (several times, if need be) helps. @pavlin-policar, can you take a look?

**Comment by pavlin-policar** [comment]
Looking at the build history on appveyor, I found one instance of this [here](https://ci.appveyor.com/project/biolab/orange3-75xll/builds/20685087) where it failed on sparse data. Is this what you meant? I suppose it may have failed more than once but rerunning the build probably removes the logs from when it failed.

I'll see if I can make it fail myself, like you suggested, but do you have anything else that might help reproduce this?

**Comment by janezd** [comment]
I got one or two more in tSNE, but then I also got a similar one (a random core dump) somewhere unrelated to tSNE. Now it stopped, so let's wait and see.
