### ISSUE TITLE
t-SNE: Change PCA to Truncated SVD for sparse data

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3441]
##### Orange version

3.19.0

##### Expected behavior
t-SNE automatically switches to Truncated SVD when receiving sparse data on the input.

##### Actual behavior
t-SNE fails on sparse.

##### Steps to reproduce the behavior
Corpus - Bag of Words - t-SNE.

##### Additional info (worksheets, data, screenshots, ...)
If we don't wish to support Truncated SVD in t-SNE, there should at least be a proper error, not the widget crashing. Even though I think automatic switch to T. SVD is totally ok and doable.

**Comment by VesnaT** [comment]
Sentry issue: [ORANGE3-24H](https://sentry.io/biolab/orange3/issues/797858972/?referrer=github_plugin)
