### ISSUE TITLE
Refactor or simplify class OWPlotGui

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#3446]
The purpose of `OWPlotGui` was to unify the GUI of visualizations, with focus on the scatterplot-like ones. These visualizations now use a common base widget. Do we still need OWPlotGui? The new base widget for projections is about the only widget that uses it. One of the past commits already broke backward compatibility AFAIK.

The class (which is rather a namespace) contains a lot of exotic settings, for instance checkboxes for animating plots and jittering numeric values. If the class is not dissolved, it may make sense to at least clean it.

**Comment by VesnaT** [comment]
Whatever you (or anyone) decide to do with the class pay attention to OWLinePlot and OWNxExplorer. They also use OWPlotGui.

**Comment by ajdapretnar** [comment]
@janezd I believe this is solved?

**Comment by janezd** [comment]
No. This is not about reimplementing visualizations.

`OWPlotGui` creates boxes with combos, sliders and checkboxes to be used in visualization widgets. The idea was that all widgets would use this class to create GUIs, and thus look the same. But now all projections are actually derived from the same widget, which in turn calls `OWPlotGui`. It just adds another layer without any clear benefit.

I propose that all useful functions are moved to the base widget for visualizations, and the rest is removed. But, as @VesnaT noted, we have to make sure that no other widgets use it. If they do, `OWPlotGui` still needs cleaning up and refactoring.

**Comment by janezd** [comment]
Closing this: its eventual implementation does not depend on the issue being present in the list.
