### ISSUE TITLE
Print report for "feature statistics" widget doesn't work

### ISSUE THREAD

**Issue by hansdev123** [biolab/orange3#3468]
##### Orange version

Version: 3.18.

##### Expected behavior

statistics feature values and output table is also in the report visible

##### Actual behavior

the report is empy and doesn't include any values of the widget

##### Additional info (worksheets, data, screenshots, ...)

<img width="848" alt="image" src="https://user-images.githubusercontent.com/15907791/49860824-ddd25300-fdfa-11e8-8fab-89df69b2f374.png">

**Comment by atyamsriharsha** [comment]
can you describe more briefly about the steps to reproduce the error?

**Comment by BlazZupan** [comment]
I am closing this issue, as it cannot be reproduced. Please include steps to reproduce (data, workflow) if reopened.
