### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'copy'

### ISSUE THREAD

**Issue by Franjey** [biolab/orange3#3472]
##### Expected behavior
Python script does not crash

##### Actual behavior
AttributeError: 'NoneType' object has no attribute 'copy'

##### Steps to reproduce the behavior
```
# Get libraries
import Orange
import numpy as np
from Orange.data import Domain, Table
from imblearn.over_sampling import SMOTE

# How Orange passes data to widget
df = in_data.copy()

# set variables for SMOTE
sm = SMOTE(random_state=42)

# get table of data (X) and class variables (y)
X, y = df.X, df.Y

# resample data and classes
X_res, y_res = sm.fit_sample(X, y)

# Get the target and feature variables
d = Domain(df.domain.attributes, df.domain.class_vars)

# Create a new Orange Table object with the appropriate headers
# This is how Orange passes the data on to the next widget
out_data = Orange.data.Table(d, X_res, y_res)
```

I connect the file to the Python Script widget and ran the script.  It used to work without problems a few days ago.

**Comment by Franjey** [comment]
Can be closed. It seems to now be working ... strange.

**Comment by Mateus-M-Reis** [comment]
The `conda-forge` version gives me this error still today. 
Uninstalling and installing through `anaconda` fixed it.
