### ISSUE TITLE
Orange install error

### ISSUE THREAD

**Issue by Marciozilli** [biolab/orange3#3476]
I downloaded Orange 3.18 for windows-64 installation win. 
And presented aborted during installation. Introducing the following error.

CondaError: Cannot link a source that does not exist. C:\Users\Marcio Zilli\Miniconda3\pkgs\python-3.6.7-h33f27b4_1\pythonw.exe

Creating an new conda env in "C:\Users\Marcio Zilli\AppData\Local\Orange14"
Output folder: C:\Users\MARCIO~1\AppData\Local\Temp\nsqF469.tmp\Orange-installer-data\conda-pkgs
Extract: anyqt-0.0.10-py36_0.tar.bz2
Extract: asn1crypto-0.24.0-py36_0.tar.bz2
Extract: backports-1.0-py36_1.tar.bz2
Extract: backports.functools_lru_cache-1.5-py_1.tar.bz2
Extract: blas-1.0-mkl.tar.bz2
Extract: bottleneck-1.2.1-py36h452e1ab_1.tar.bz2
Extract: ca-certificates-2018.03.07-0.tar.bz2
Extract: certifi-2018.10.15-py36_0.tar.bz2
Extract: cffi-1.11.5-py36h74b6da3_1.tar.bz2
Extract: chardet-3.0.4-py36_1.tar.bz2
Extract: commonmark-0.8.1-py36_0.tar.bz2
Extract: conda-spec.txt
Extract: cryptography-2.3-py36h74b6da3_0.tar.bz2
Extract: cryptography-vectors-2.3.1-py36_0.tar.bz2
Extract: cycler-0.10.0-py36h009560c_0.tar.bz2
Extract: decorator-4.3.0-py36_0.tar.bz2
Extract: docutils-0.14-py36h6012d8f_0.tar.bz2
Extract: entrypoints-0.2.3-py36_2.tar.bz2
Extract: fasttsne-0.2.13-py36h452e1ab_1.tar.bz2
Extract: freetype-2.7-vc14_0.tar.bz2
Extract: future-0.17.1-py36_0.tar.bz2
Extract: icc_rt-2017.0.4-h97af966_0.tar.bz2
Extract: icu-58.2-ha66f8fd_1.tar.bz2
Extract: idna-2.7-py36_0.tar.bz2
Extract: install.bat
Extract: intel-openmp-2019.0-118.tar.bz2
Extract: joblib-0.12.5-py36_0.tar.bz2
Extract: jpeg-9b-vc14_1.tar.bz2
Extract: keyring-16.0.0-py36_0.tar.bz2
Extract: keyrings.alt-3.1-py36_0.tar.bz2
Extract: libpng-1.6.35-h2a8f88b_0.tar.bz2
Extract: llvmlite-0.25.0-py36_0.tar.bz2
Extract: matplotlib-2.1.0-py36_0.tar.bz2
Extract: mkl-2019.0-118.tar.bz2
Extract: mkl_fft-1.0.6-py36hdbbee80_0.tar.bz2
Extract: mkl_random-1.0.1-py36h77b88f5_1.tar.bz2
Extract: networkx-2.2-py36_1.tar.bz2
Extract: numba-0.40.0-py36hf9181ef_0.tar.bz2
Extract: numpy-1.14.6-py36hc27ee41_4.tar.bz2
Extract: numpy-base-1.14.6-py36h8128ebf_4.tar.bz2
Extract: openssl-1.0.2o-vc14_0.tar.bz2
Extract: orange3-3.18.0-py36h830ac7b_0.tar.bz2
Extract: pip-18.1-py36_0.tar.bz2
Extract: pycparser-2.19-py36_0.tar.bz2
Extract: pyopenssl-18.0.0-py36_0.tar.bz2
Extract: pyparsing-2.3.0-py36_0.tar.bz2
Extract: pyqt-5.6.0-py36ha878b3d_6.tar.bz2
Extract: pyqtgraph-0.10.0-py36h28b3542_3.tar.bz2
Extract: pysocks-1.6.8-py36_0.tar.bz2
Extract: python-3.6.7-h33f27b4_1.tar.bz2
Extract: python-dateutil-2.7.5-py36_0.tar.bz2
Extract: python-louvain-0.11-py36h28b3542_0.tar.bz2
Extract: pytz-2018.7-py36_0.tar.bz2
Extract: pywin32-223-py36hfa6e2cd_1.tar.bz2
Extract: qt-5.6.2-vc14h6f8c307_12.tar.bz2
Extract: requests-2.20.0-py36_0.tar.bz2
Extract: scikit-learn-0.20.0-py36heebcf9a_1.tar.bz2
Extract: scipy-1.0.1-py36hce232c7_0.tar.bz2
Extract: serverfiles-0.2.1-py36_0.tar.bz2
Extract: setuptools-40.5.0-py36_0.tar.bz2
Extract: sip-4.18.1-py36h6538335_2.tar.bz2
Extract: six-1.11.0-py36_1.tar.bz2
Extract: sqlite-3.25.2-hfa6e2cd_0.tar.bz2
Extract: tornado-5.1.1-py36hfa6e2cd_0.tar.bz2
Extract: urllib3-1.23-py36_0.tar.bz2
Extract: vc-14.1-h0510ff6_4.tar.bz2
Extract: vs2015_runtime-14.15.26706-h3a45250_0.tar.bz2
Extract: wheel-0.32.2-py36_0.tar.bz2
Extract: win_inet_pton-1.0.1-py36_1.tar.bz2
Extract: wincertstore-0.2-py36h7fe50ca_0.tar.bz2
Extract: xlrd-1.1.0-py36_1.tar.bz2
Extract: zlib-1.2.11-vc14_0.tar.bz2
Output folder: C:\Users\MARCIO~1\AppData\Local\Temp\nsqF469.tmp\Orange-installer-data\conda-pkgs
Installing packages (this might take a while)
Executing: cmd.exe /c install.bat "C:\Users\Marcio Zilli\AppData\Local\Orange14" "C:\Users\Marcio Zilli\Miniconda3\Scripts\conda.exe"
Creating a conda env in "C:\Users\Marcio Zilli\AppData\Local\Orange14"
Fetching package metadata ...........
Solving package specifications: 
Package plan for installation in environment C:\Users\Marcio Zilli\AppData\Local\Orange14:

#
# To activate this environment, use:
# > activate C:\Users\Marcio Zilli\AppData\Local\Orange14
#
# To deactivate this environment, use:
# > deactivate C:\Users\Marcio Zilli\AppData\Local\Orange14
#
# * for power-users using bash, you must source
#

ERROR conda.core.link:_execute_actions(335): An error occurred while installing package '<unknown>::python-3.6.7-h33f27b4_1'.
CondaError: Cannot link a source that does not exist. C:\Users\Marcio Zilli\Miniconda3\pkgs\python-3.6.7-h33f27b4_1\pythonw.exe

Attempting to roll back.

CondaError: Cannot link a source that does not exist. C:\Users\Marcio Zilli\Miniconda3\pkgs\python-3.6.7-h33f27b4_1\pythonw.exe

"conda" command exited with 1. Cannot continue.

**Comment by ales-erjavec** [comment]
Can you please run
```
"C:\Users\Marcio Zilli\Miniconda3\Scripts\conda" info
```
from the Command Prompt and post its output?

Can you also try running
```
"C:\Users\Marcio Zilli\Miniconda3\Scripts\conda" clean --all
```
and then rerun the installer.

**Comment by Marciozilli** [comment]
I believe the sub directory SCRIPT was not created

Look

In installation should not have created


[image: image.png]



*Marcio Zilli*
*+551998192 7507*

blog: https://zct-consultoria.blogspot.com/

site: https://www.zctconsultoria.com

Linkedin: https://br.linkedin.com/in/marcio-zilli-z11i1957







[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Remetente
notificado por
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
17/12/18
18:52:54

Em seg, 17 de dez de 2018 às 06:31, Aleš Erjavec <notifications@github.com>
escreveu:

**Comment by ajdapretnar** [comment]
I tested latest installers (3.18) and they work well on clean version of Windows. I do not understand the last comment. Is there some progress on this?

**Comment by Marciozilli** [comment]
No progress.


*Marcio Zilli*
*+551998192 7507*

blog: https://zct-consultoria.blogspot.com/

site: https://www.zctconsultoria.com.br

Linkedin: https://br.linkedin.com/in/mar
<https://br.linkedin.com/in/marcio-zilli-z11i1957>cio-zilli-z11i1957
<https://br.linkedin.com/in/marcio-zilli-z11i1957>






Em sex, 1 de fev de 2019 às 10:35, Ajda <notifications@github.com> escreveu:

**Comment by ajdapretnar** [comment]
@Marciozilli I am afraid I don't understand your comments. Could you post the output of the above command as suggested by @ales-erjavec? Did you try to run the installer again after the second command?

**Comment by Marciozilli** [comment]
I downloaded and reinstalled. Looks like it worked.

Do you have tutorials in Portuguese?

[image: image.png]


*Marcio Zilli*
*+551998192 7507*

blog: https://zct-consultoria.blogspot.com/

site: https://www.zctconsultoria.com.br

Linkedin: https://br.linkedin.com/in/mar
<https://br.linkedin.com/in/marcio-zilli-z11i1957>cio-zilli-z11i1957
<https://br.linkedin.com/in/marcio-zilli-z11i1957>






Em seg, 4 de fev de 2019 às 06:19, Ajda <notifications@github.com> escreveu:

**Comment by ajdapretnar** [comment]
> Do you have tutorials in Portuguese?

Unfortunately, no. But we would be happy if someone prepared them.
