### ISSUE TITLE
attributeError: 'CrossValidation' object has no attribute 'probabilities'

### ISSUE THREAD

**Issue by Franjey** [biolab/orange3#3479]
Hi, I am following this example: https://blog.biolab.si/2018/05/03/data-mining-course-at-higher-school-of-economics-moscow/

After utilizing the code in the Python Script widget, I am getting the following error:  AttributeError: 'CrossValidation' object has no attribute 'probabilities'

Has the name of the attribute recently changed? 

Appreciate the help.  Thanks.

**Comment by atyamsriharsha** [comment]
Hey @Franjey i can execute code successfully without any error as shown below . 
![untitled](https://user-images.githubusercontent.com/10818570/50182809-29867000-02c5-11e9-90ae-e4a8f214d09e.png)
Can you please check your version of Orange

**Comment by janezd** [comment]
Closed for inactivity.
