### ISSUE TITLE
Need informative error if Orange does not find compiled libraries needed

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#3482]
Importing Orange should fail with a more informative error if its compiled parts can not be found. Now it just complains about not finding _variable, like in #3481 or #1838.

Even installation should fail with an error in such cases.

**Comment by janezd** [comment]
@markotoplak, so the idea could be that Orange imports all compiled libraries before importing anything else, and report an error if this fails?

And that installation also ends by importing those libraries and reporting an error if needed?

**Comment by robertcv** [comment]
I manage to reproduce this issue but I'm not sure why it occurs.
Install Orange from source. Run `pip install .` in two different virtual environments.
The `import Orange` will faile in the second one.
