### ISSUE TITLE
Lasso cross validation to select best lamda

### ISSUE THREAD

**Issue by bernard-liew** [biolab/orange3#3489]
Hi,

Is there a way to do cross validation to select the best lambda value for lasso in Orange3?

Regards,
Bernard

**Comment by janezd** [comment]
No. We have been thinking of hyperparameter fitting for long time, but we haven' t implemented it yet because we want to define a general framework that will also allow for fitting of other parameters for other algorithms.

I'm closing this, but we are keeping this in mind.
