### ISSUE TITLE
OWCorrelations: fixes and enhancements

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3504]
Fixes:
- When data changes, the output shows old data instead of the new one. Call commit when new data on input.

Enhancements:
- Split attribute pairs into two columns (in view) and elide as in Data Table.
- Add p-values to Correlations table output.
- Add option to compute all correlations with a chosen feature.
- Check heuristics. Needs discussion: @lanzagar

**Comment by ajdapretnar** [comment]
> You don't get any additional functionality by having two columns

We have discussed this with @lanzagar, who is also using this widget and while I also thought it is worse visually at first, now [I am a believer](https://www.youtube.com/watch?v=wB9YIsKIEbA). The idea is that you can easily read two names of different length. Try using a data set with names of different length and you will see how annoying this is. Also it would be nice to be able to filter by variable, get that variable in column 1 and see the paired attributes in column 2.

> I would be however OK with computing p-values

For now, we would have p-values only in the Correlations table output, not visually in the widget. I got a request by a user as to how on Earth do we not have p-value reported for correlations, hence this enhancement. We can easily add this in the docs, but not sure about the tooltip, if we keep it in the output only (where would this tooltip be?).

**Comment by janezd** [comment]
> Try using a data set with names of different length and you will see how annoying this is. 

I'm not sold on this one. If names are of very different lengths, two columns won't help much. But the change is trivial, so we can try and see.

Filtering is already possible by just typing the name.

>  I got a request by a user as to how on Earth do we not have p-value reported for correlations

Have you asked him why on Earth would he like to see them? :) I suspect he wants to have an automated way to look for "significant correlations", which is exactly why we should not have p-values.

I could write an essay about why we shouldn't compute p-values here, but in summary: correlations are already on the scale from -1 to 1, so no scaling/normalization is needed. P-values are just a very crappy way to take the number of observations into account, which is wrong in many different ways. The proper way to do this is to use [Bayesian estimation of correlations](https://gist.github.com/j-faria/7f0a6671565e13586ac3), but it uses Monte Carlo and may be too slow for a large number of pairs.
