### ISSUE TITLE
TSNE causes segfaults on travis

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#3510]
Travis now fails with a segfault. I saw some problems with llvmlite and suspected numba:

/lib/x86_64-linux-gnu/libc.so.6(+0x155336)[0x7f9b7b404336]
/usr/lib/x86_64-linux-gnu/libLLVM-3.4.so.1(_ZN4llvm15SmallVectorImplINS_15LayoutAlignElemEEaSERKS2_+0xcb)[0x7f9b5dae1e3b]
/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/llvmlite/binding/libllvmlite.so(+0x1077e0e)[0x7f9b38fcae0e]
/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/llvmlite/binding/libllvmlite.so(+0x1078480)[0x7f9b38fcb480]
/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/llvmlite/binding/libllvmlite.so(+0x107bc5a)[0x7f9b38fcec5a]
/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/llvmlite/binding/libllvmlite.so(+0x257001)[0x7f9b381aa001]

If I remove TSNE from manifold.py then the segfault is gone.

**Comment by markotoplak** [comment]
Oh, and numba and llvmlite were updated on Dec 31.

**Comment by janezd** [comment]
Temporarily resolved by pinning numba and llvmlite versions.
