### ISSUE TITLE
Orange.projection loads slowly after introduction of fastTSNE

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#3523]
After f5eeaa6cf24b7ab62a8a24847b43ec8489647048 (tSNE: Implement Orange wrapper around Pavlin's implementation of tSNE) loading of Orange.projection became even slower.

On my computer, it used to take 0.9 second, now it takes 2.3 second.

Should we import fastTSNE only when actually needed?

**Comment by janezd** [comment]
@pavlin-policar, @markotoplak, is this still an issue and will we (ehm, you :)) do something about it?

**Comment by markotoplak** [comment]
Yes, it is still an issue. Now it takes ~2.6 seconds. It can be fixed by not using numba (@pavlin-policar 
, did anyone try to work on this?) or importing some things more lazily.

**Comment by pavlin-policar** [comment]
I don't see the t-SNE library not-depending on numba any time soon. I've been looking for alternatives, but have found none that would make sense. Eventually, I might write my own implementation of the library depending on numba, but that will require a fair bit of work.

In the meantime, I'll look into how we could load things lazily.
