### ISSUE TITLE
Problem with miniconda installer (silent installation)

### ISSUE THREAD

**Issue by Wolfereign** [biolab/orange3#3524]
Can the orange 3 miniconda installer be silently installed for all users?  I cannot find any documentation and the regular miniconda silent install flags do not work.

Here's the powershell script i'm using to install
```
#Requires -RunAsAdministrator

# PSScriptRoot For PS 2.0 Compat
$ScriptDir = Split-Path $MyInvocation.MyCommand.Path -Parent

# Setup Variables
$Exe = "$ScriptDir\Orange3-3.18.0-Miniconda-x86_64.exe"
$Args = "/S /InstallationType=AllUsers /AddToPath=0 /RegisterPython=0 /D=`"$Env:ProgramData\Orange3`""

# Install Program
$proc = Start-Process -FilePath $Exe -ArgumentList $Args -WorkingDirectory $ScriptDir -NoNewWindow -Wait -PassThru
if($proc.ExitCode -ne 0) {Exit $proc.ExitCode}
```
This silently installs (takes forever) but it ignores all the flags after '/S' and does not install for all users.

**Comment by ales-erjavec** [comment]
Try  `/S /AllUsers /D=$Env:ProgramData\Orange3`  (no quotes around the path, or maybe put quotes around the whole /D=... e.g `"/D=$Env:ProgramData\Orange3"`

`/AddToPath=0` and `/RegisterPython=0` are not recognized.

**Comment by ales-erjavec** [comment]
Yes. Although a wiki entry describing the silent installation should also be created.

**Comment by ales-erjavec** [comment]
It has been created: [Unattended-Installation-on-Windows](https://github.com/biolab/orange3/wiki/Unattended-Installation-on-Windows)
