### ISSUE TITLE
OWNeighbors: prevent crash when domains don't match

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3533]
##### Orange version

3.20.dev

##### Expected behavior
Neighbors returns a nicely formatted error message when Data and Reference don't match.

##### Actual behavior
Widget crashes.

##### Steps to reproduce the behavior
Use iris.tab as Data and titanic.tab as Reference.

**Comment by bingert** [comment]
I understand that there needs to be an action if the widget has a bug. But I would not delete it out of the "prototype" section. I used and still use the widget.

**Comment by ajdapretnar** [comment]
The widget is still available. We just moved it to core Orange out of Prototypes.

**Comment by janezd** [comment]
Fixed in #3547.
