### ISSUE TITLE
Hierarchical Clustering: broken visualization upon resizing

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3546]
##### Orange version

scOrange 0.9.0

##### Expected behavior
Hierarchical Clustering resizes nicely.

##### Actual behavior
Part of visualization remain upon resizing.

##### Steps to reproduce the behavior
Load data from https://www.sciencedirect.com/science/article/pii/S1534580718307834#app2, use normalized data. Load Data - Filter (genes, detection count, min 30) - Distances (cosine) - Hierarchical Clustering.
I can't reproduce on iris.tab. Likely due to the size of the data.

##### Additional info (worksheets, data, screenshots, ...)
<img width="804" alt="screen shot 2019-01-21 at 14 24 17" src="https://user-images.githubusercontent.com/12524972/51477980-5a593980-1d8a-11e9-9804-45ac6d40b940.png">

**Comment by ales-erjavec** [comment]
Try running:

```
/Applications/scOrange.app/Contents/MacOS/pip install PyQt5~=5.9.0
```

(replacing the `/Applications/scOrange.app` with the location of your scOrange install if it is not installed in the default location)

**Comment by ajdapretnar** [comment]
This seems to have fixed the issue. Thanks!

**Comment by markotoplak** [comment]
Why did this work? In the macos/requirements.txt I already see 5.9 (both in Orange and orange3-single-cell). If this fixed things for Ajda, we need to fix the installer.

**Comment by ales-erjavec** [comment]
The scOrange .dmg installer ships with Qt 5.11.2. Qt 5.10 and 5.11 are neigh unusable on macOS (large changes in the macOS platform/style backend)
