### ISSUE TITLE
Installing Add-ons ERROR

### ISSUE THREAD

**Issue by sisiphos2018** [biolab/orange3#3577]
I have anaconda installed on my system.
I launch orange3 via the anaconda navigator.

I get the error:
command failed: python -m pip install
Orange3-Geo exited with non zero status.

Details:

Collecting Orange3-Geo
  Downloading https://files.pythonhosted.org/packages/96/d0/2f849d65a70c261959f7f45be8cd2fb742f0e38b5faa190cc0de855053ae/Orange3-Geo-0.2.3.tar.gz (14.9MB)
Requirement already satisfied: Orange3 in c:\programdata\anaconda3\lib\site-packages (from Orange3-Geo) (3.19.0)
Requirement already satisfied: scikit-learn in c:\programdata\anaconda3\lib\site-packages (from Orange3-Geo) (0.20.1)
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (from Orange3-Geo) (0.23.4)
Requirement already satisfied: scipy>=0.17 in c:\programdata\anaconda3\lib\site-packages (from Orange3-Geo) (1.1.0)
Collecting shapely (from Orange3-Geo)
  Downloading https://files.pythonhosted.org/packages/a2/fb/7a7af9ef7a35d16fa23b127abee272cfc483ca89029b73e92e93cdf36e6b/Shapely-1.6.4.post2.tar.gz (225kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\mail2\AppData\Local\Temp\pip-install-x1wjf3ti\shapely\setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "C:\Users\mail2\AppData\Local\Temp\pip-install-x1wjf3ti\shapely\shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos_c.dll")
      File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] Das angegebene Modul wurde nicht gefunden
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\mail2\AppData\Local\Temp\pip-install-x1wjf3ti\shapely\

**Comment by ajdapretnar** [comment]
@sisiphos2018 Please report this to the corresponding [Orange Geo add-on.](https://github.com/biolab/orange3-geo/issues)
