### ISSUE TITLE
[doc] API docs are missing

### ISSUE THREAD

**Issue by woutdenolf** [biolab/orange3#3584]
The API docs on https://orange-development.readthedocs.io are missing, more specifically the doc strings  (autodoc fails?)

**Comment by ajdapretnar** [comment]
I do not quite understand the issue. It seems like all the docs are building just fine.

**Comment by janezd** [comment]
They're not. I noticed it a while ago but forgot to open an issue or fix it.

See https://orange-development.readthedocs.io/widget.html. Everything after the subtitle **Class Member Documentation** (that is, all docstrings) are missing. Also the docstrings in **Input/Output Signal Definitions**.

**Comment by rokgomiscek** [comment]
The documentation looks fine.
