### ISSUE TITLE
Installation error - Failed building wheel for llvmlite

### ISSUE THREAD

**Issue by baqwas** [biolab/orange3#3586]
##### Orange version

Trying to install Orange using instructions from biolab/orange3 GitHub site. Failed at the following step:

pip3 install -r requirements-core.txt

##### Expected behavior

Installation succeeded and then on to the next set of pre-requisite installation commands.

##### Actual behavior

Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-zf34s2t9/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-j636mnje-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" **failed with error code 1 in /tmp/pip-build-zf34s2t9/llvmlite/**

##### Steps to reproduce the behavior

pip3 install -r requirements-core.txt

##### Additional info (worksheets, data, screenshots, ...)
Platform is Raspberry Pi Zero W:
Linux raspbari3 4.14.79+ #1159 Sun Nov 4 17:28:08 GMT 2018 armv6l GNU/Linux

Python3, pip3, etc. installed.

Thanks!

**Comment by janezd** [comment]
Apologies for not responding earlier - and for not really responding now, either. While I see no good reason for running Orange on a Raspberry, I am still very curious whether it can be done. Orange does not depend heavily on llvmlite (and it may depend even less in the future), so even if llvmlite can't run on Raspberry, a large subset of Orange could still work.

I'm keeping your report in mind and will try it someday (I don't have a Zero, but I have a 3 B+). If you're willing to play, you can start by removing openTSNE from the list of requirements and see if Orange installs.

**Comment by baqwas** [comment]
Apologies for the delayed response. Getting back to working with Orange just now after a lapse.

Orange works fine on the controller node (RPI3B) of my ClusterHAT. https://clusterhat.com/buy The four RPi0 nodes are used for headless tasks (i.e. scraping data & monitoring). Understand your comment about Orange on RPi0. I just needed some feedback and your comment is fine with me - not an issue at all. In fact, as soon as I get my hands on RPi4, Orange deployment will be one of the first packages.

Kind regards.

**Comment by janezd** [comment]
Thanks for reporting. This is cool.

I'm waiting to get my hands on RPi4, too.

**Comment by markotoplak** [comment]
@baqwas, are your perhaps still using Orange? How do you perform the installation? Do newer versions work for you? Thanks!

**Comment by baqwas** [comment]
Hello @markotoplak, I haven't used Orange for a while. Let me try it on RPi02W. Here's the result:

`Failed to build orange3
ERROR: Could not build wheels for orange3 which use PEP 517 and cannot be installed directly
`
I really don't need anyone to re-open the issue. However, it someone wants to me test further by providing guidance, I'll gladly try. Thanks.

Kind regards.

**P.S.**
`$ uname -a
Linux hostname 5.10.63-v7+ #1488 SMP Thu Nov 18 16:14:44 GMT 2021 armv7l GNU/Linux`
