### ISSUE TITLE
Slow plotting in Scatter Plot

### ISSUE THREAD

**Issue by borondics** [biolab/orange3#3589]
##### Orange version

3.21.0.dev0+920e474

##### Expected behavior
Plots should not slow down drastically when receiving big(ish) datasets.

##### Actual behavior
Plotting 40000 points in scatterplot is already very slow.

##### Steps to reproduce the behavior
Load big dataset
Connect Scatter Plot
Change Axes and observe replotting speed

##### Additional info (worksheets, data, screenshots, ...)
Using the following code in command line pyqtgraph plots 100000 points in  about 1 sec.
```
import pyqtgraph as pg
import numpy as np
a = np.random.random(100000)
b = np.random.random(100000)
pg.plot(a, b, pen=None, symbol='o')
```

**Comment by markotoplak** [comment]
I've looked into this a bit. Behind the scenes, pyqtgraph's scatterplot builds an atlas of symbols to use, but at least for same color scatterplots and scatterplots colored with a continuous feature, we prepare data in a way which prevents pyqtgraph to be efficient.

If I make the following change to `OWScatterPlotBase._get_same_colors` I get more than 5x speedup on data with 40000 rows.

```
@@ -845,7 +845,8 @@ class OWScatterPlotBase(gui.OWComponent, QObject):
             (tuple): a list of pens and list of brushes
         """
         color = self.plot_widget.palette().color(OWPalette.Data)
-        pen = [_make_pen(color, 1.5) for _ in range(self.n_shown)]
+        single_pen = _make_pen(color, 1.5)
+        pen = [single_pen for _ in range(self.n_shown)]
         if subset is not None:
             brush = np.where(
                 subset,
@@ -854,7 +855,8 @@ class OWScatterPlotBase(gui.OWComponent, QObject):
         else:
             color = QColor(*self.COLOR_DEFAULT)
             color.setAlpha(self.alpha_value)
-            brush = [QBrush(color) for _ in range(self.n_shown)]
+            single_brush = QBrush(color)
+            brush = [single_brush for _ in range(self.n_shown)]
         return pen, brush
```

**Comment by markotoplak** [comment]
Also, for new pairs of features, graph is redrawn each time a certain property (positions, colors, sizes, ...) is set. For a new pair of attributes, I see 7 calls to `updateSpots` in pyqtgraph, but only one is needed.

When I profile with the changes from the previous comment, `updateSpots` takes approximately 70% of time for updates, so reducing the number of calls could make plots a bit more than 50% faster. 

So altogether, we could make it 10x faster.
