### ISSUE TITLE
Cannot install Orange3-3.18.0-Python36-win32.exe 

### ISSUE THREAD

**Issue by colinodonnell** [biolab/orange3#3595]
##### Orange version

Orange3-3.18.0-Python36-win32.exe 

##### Expected behavior

Installation of Orange Classic so that I can then access the Text Mining Add On

##### Actual behavior

I have Miniconda installed (Orange 3.18.0 (64 bit)

When the IT company tried to install Orange Classic version the got the following error:
Python installation failed (error value: error)

Then the company uninstalled Miniconda and then tried to install Orange Classic but get the same error. 
We do not know why.

I have a 64 bit Operating System. Not sure if this is relevant.
The Miniconda version installs no problem. 

##### Steps to reproduce the behavior

Try to install Orange3-3.18.0-Python36-win32.exe 
either when Miniconda:
is installed or 
not installed.

**Comment by ajdapretnar** [comment]
Orange Classic does not support installing Text, because Text requires a part of its libraries to be compiled and pre-compiled versions are only available via Miniconda. Classic installer does not install Miniconda, you should be using Miniconda (recommended) installer.

**Comment by colinodonnell** [comment]
Thank you, I have now been able to add Text via the add ons in Mininconda.
Fixed.
