### ISSUE TITLE
Cannot install Text addon

### ISSUE THREAD

**Issue by Benoit007** [biolab/orange3#3596]
When I try to install the text add-on, I get the following popup

![image](https://user-images.githubusercontent.com/47596186/52707409-ef191680-2f87-11e9-88ef-0e05e07de0eb.png)

Here is the detailled message:

Collecting Orange3-Text
Requirement already satisfied: docx2txt>=0.6 in c:\anaconda3\lib\site-packages (from Orange3-Text) (0.7)
Requirement already satisfied: setuptools-git in c:\anaconda3\lib\site-packages (from Orange3-Text) (1.2)
Collecting ufal.udpipe; platform_system != "Darwin" (from Orange3-Text)
  Using cached https://files.pythonhosted.org/packages/f7/20/9fdf23855a8dbb018b91f798d5923fd3aadff5d1d8bee39187973f8e17bc/ufal.udpipe-1.2.0.1.tar.gz
Requirement already satisfied: validate-email in c:\anaconda3\lib\site-packages (from Orange3-Text) (1.3)
Requirement already satisfied: gensim>=0.12.3 in c:\anaconda3\lib\site-packages (from Orange3-Text) (3.7.1)
Requirement already satisfied: scikit-learn in c:\anaconda3\lib\site-packages (from Orange3-Text) (0.19.1)
Requirement already satisfied: Orange3>=3.4.3 in c:\anaconda3\lib\site-packages (from Orange3-Text) (3.17.0)
Requirement already satisfied: scipy in c:\anaconda3\lib\site-packages (from Orange3-Text) (1.1.0)
Requirement already satisfied: numpy in c:\anaconda3\lib\site-packages (from Orange3-Text) (1.14.3)
Requirement already satisfied: tweepy in c:\anaconda3\lib\site-packages (from Orange3-Text) (3.7.0)
Requirement already satisfied: biopython in c:\anaconda3\lib\site-packages (from Orange3-Text) (1.73)
Requirement already satisfied: nltk>=3.0.5 in c:\anaconda3\lib\site-packages (from Orange3-Text) (3.3)
Requirement already satisfied: pdfminer3k>=1.3.1 in c:\anaconda3\lib\site-packages (from Orange3-Text) (1.3.1)
Requirement already satisfied: simhash in c:\anaconda3\lib\site-packages (from Orange3-Text) (1.9.0)
Requirement already satisfied: wikipedia in c:\anaconda3\lib\site-packages (from Orange3-Text) (1.4.0)
Requirement already satisfied: beautifulsoup4 in c:\anaconda3\lib\site-packages (from Orange3-Text) (4.6.0)
Requirement already satisfied: lxml in c:\anaconda3\lib\site-packages (from Orange3-Text) (4.2.1)
Requirement already satisfied: odfpy>=1.3.5 in c:\anaconda3\lib\site-packages (from Orange3-Text) (1.4.0)
Requirement already satisfied: smart-open>=1.7.0 in c:\anaconda3\lib\site-packages (from gensim>=0.12.3->Orange3-Text) (1.8.0)
Requirement already satisfied: six>=1.5.0 in c:\anaconda3\lib\site-packages (from gensim>=0.12.3->Orange3-Text) (1.11.0)
Requirement already satisfied: AnyQt>=0.0.8 in c:\anaconda3\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (0.0.10)
Requirement already satisfied: bottleneck>=1.0.0 in c:\anaconda3\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (1.2.1)
Requirement already satisfied: chardet>=3.0.2 in c:\anaconda3\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (3.0.4)
Requirement already satisfied: docutils in c:\anaconda3\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (0.14)
Requirement already satisfied: joblib>=0.9.4 in c:\anaconda3\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (0.13.0)
Requirement already satisfied: keyring in c:\anaconda3\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (17.0.0)
Requirement already satisfied: keyrings.alt in c:\anaconda3\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (3.1.1)
Requirement already satisfied: matplotlib>=2.0.0 in c:\anaconda3\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (2.2.2)
Requirement already satisfied: networkx in c:\anaconda3\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (2.1)
Requirement already satisfied: pip>=9.0 in c:\anaconda3\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (10.0.1)
Requirement already satisfied: pyqtgraph>=0.10.0 in c:\anaconda3\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (0.10.0)
Requirement already satisfied: python-louvain in c:\anaconda3\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (0.11)
Requirement already satisfied: requests in c:\anaconda3\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (2.18.4)
Requirement already satisfied: serverfiles in c:\anaconda3\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (0.3.0)
Requirement already satisfied: setuptools>=36.3 in c:\anaconda3\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (39.1.0)
Requirement already satisfied: xlrd>=0.9.2 in c:\anaconda3\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (1.1.0)
Requirement already satisfied: PySocks>=1.5.7 in c:\anaconda3\lib\site-packages (from tweepy->Orange3-Text) (1.6.8)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\anaconda3\lib\site-packages (from tweepy->Orange3-Text) (1.2.0)
Requirement already satisfied: ply>=3.4 in c:\anaconda3\lib\site-packages (from pdfminer3k>=1.3.1->Orange3-Text) (3.11)
Requirement already satisfied: pytest>=2.0 in c:\anaconda3\lib\site-packages (from pdfminer3k>=1.3.1->Orange3-Text) (3.5.1)
Requirement already satisfied: defusedxml in c:\anaconda3\lib\site-packages (from odfpy>=1.3.5->Orange3-Text) (0.5.0)
Requirement already satisfied: boto>=2.32 in c:\anaconda3\lib\site-packages (from smart-open>=1.7.0->gensim>=0.12.3->Orange3-Text) (2.48.0)
Requirement already satisfied: bz2file in c:\anaconda3\lib\site-packages (from smart-open>=1.7.0->gensim>=0.12.3->Orange3-Text) (0.98)
Requirement already satisfied: boto3 in c:\anaconda3\lib\site-packages (from smart-open>=1.7.0->gensim>=0.12.3->Orange3-Text) (1.9.92)
Requirement already satisfied: entrypoints in c:\anaconda3\lib\site-packages (from keyring->Orange3>=3.4.3->Orange3-Text) (0.2.3)
Requirement already satisfied: pywin32 in c:\anaconda3\lib\site-packages (from keyring->Orange3>=3.4.3->Orange3-Text) (223)
Requirement already satisfied: cycler>=0.10 in c:\anaconda3\lib\site-packages (from matplotlib>=2.0.0->Orange3>=3.4.3->Orange3-Text) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\anaconda3\lib\site-packages (from matplotlib>=2.0.0->Orange3>=3.4.3->Orange3-Text) (2.2.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\anaconda3\lib\site-packages (from matplotlib>=2.0.0->Orange3>=3.4.3->Orange3-Text) (2.7.3)
Requirement already satisfied: pytz in c:\anaconda3\lib\site-packages (from matplotlib>=2.0.0->Orange3>=3.4.3->Orange3-Text) (2018.4)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\anaconda3\lib\site-packages (from matplotlib>=2.0.0->Orange3>=3.4.3->Orange3-Text) (1.0.1)
Requirement already satisfied: decorator>=4.1.0 in c:\anaconda3\lib\site-packages (from networkx->Orange3>=3.4.3->Orange3-Text) (4.3.0)
Requirement already satisfied: idna<2.7,>=2.5 in c:\anaconda3\lib\site-packages (from requests->Orange3>=3.4.3->Orange3-Text) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\anaconda3\lib\site-packages (from requests->Orange3>=3.4.3->Orange3-Text) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in c:\anaconda3\lib\site-packages (from requests->Orange3>=3.4.3->Orange3-Text) (2018.11.29)
Requirement already satisfied: oauthlib>=3.0.0 in c:\anaconda3\lib\site-packages (from requests-oauthlib>=0.7.0->tweepy->Orange3-Text) (3.0.1)
Requirement already satisfied: py>=1.5.0 in c:\anaconda3\lib\site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (1.5.3)
Requirement already satisfied: attrs>=17.4.0 in c:\anaconda3\lib\site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (18.1.0)
Requirement already satisfied: more-itertools>=4.0.0 in c:\anaconda3\lib\site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (4.1.0)
Requirement already satisfied: pluggy<0.7,>=0.5 in c:\anaconda3\lib\site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (0.6.0)
Requirement already satisfied: colorama in c:\anaconda3\lib\site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (0.3.9)
Requirement already satisfied: botocore<1.13.0,>=1.12.92 in c:\anaconda3\lib\site-packages (from boto3->smart-open>=1.7.0->gensim>=0.12.3->Orange3-Text) (1.12.92)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in c:\anaconda3\lib\site-packages (from boto3->smart-open>=1.7.0->gensim>=0.12.3->Orange3-Text) (0.9.3)
Requirement already satisfied: s3transfer<0.3.0,>=0.2.0 in c:\anaconda3\lib\site-packages (from boto3->smart-open>=1.7.0->gensim>=0.12.3->Orange3-Text) (0.2.0)
Building wheels for collected packages: ufal.udpipe
  Running setup.py bdist_wheel for ufal.udpipe: started
  Running setup.py bdist_wheel for ufal.udpipe: finished with status 'error'
  Complete output from command C:\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\XXX~1\\AppData\\Local\\Temp\\pip-install-cqwj4d99\\ufal.udpipe\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\XXX~1\AppData\Local\Temp\pip-wheel-n22xjjsk --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\ufal
  copying ufal\__init__.py -> build\lib.win-amd64-3.6\ufal
  copying ufal\udpipe.py -> build\lib.win-amd64-3.6\ufal
  running build_ext
  building 'ufal_udpipe' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
  
  ----------------------------------------
  Failed building wheel for ufal.udpipe
  Running setup.py clean for ufal.udpipe
Failed to build ufal.udpipe
Installing collected packages: ufal.udpipe, Orange3-Text
  Running setup.py install for ufal.udpipe: started
    Running setup.py install for ufal.udpipe: finished with status 'error'
    Complete output from command C:\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\XXX~1\\AppData\\Local\\Temp\\pip-install-cqwj4d99\\ufal.udpipe\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\XXX~1\AppData\Local\Temp\pip-record-xag_b3yo\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\ufal
    copying ufal\__init__.py -> build\lib.win-amd64-3.6\ufal
    copying ufal\udpipe.py -> build\lib.win-amd64-3.6\ufal
    running build_ext
    building 'ufal_udpipe' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
    
    ----------------------------------------
Command "C:\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\XXX~1\\AppData\\Local\\Temp\\pip-install-cqwj4d99\\ufal.udpipe\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\XXX~1\AppData\Local\Temp\pip-record-xag_b3yo\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\XXX~1\AppData\Local\Temp\pip-install-cqwj4d99\ufal.udpipe\
You are using pip version 10.0.1, however version 19.0.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by ajdapretnar** [comment]
This is a Text related error and should be reported to the corresponding repository.

That said, from what I know it is not possible to install Orange via Anaconda platform and then install Text. I don't know why. It should work when using the recommended Miniconda installer.
