### ISSUE TITLE
Orange Logo becomes Empty-Page Doc Icon 

### ISSUE THREAD

**Issue by VETURISRIRAM** [biolab/orange3#3606]
##### Orange version
3.19.0

##### Expected behavior
The Orange logo should not change to a Empty Page Doc Icon. When you hover over it, it should say 'Orange'

##### Actual behavior
It changes to an Empty Page Doc Icon. When you hover over the icon, it says 'Python'

##### Steps to reproduce the behavior
Launch Orange

##### Additional info (worksheets, data, screenshots, ...)
<img width="1680" alt="screen shot 1397-11-19 at 2 06 11 pm" src="https://user-images.githubusercontent.com/33236428/52879480-d7c36000-3124-11e9-88ba-5f7f271b10b4.png">

##### Session Info
macOS High Sierra 
10.13.6

**Comment by janezd** [comment]
Just to make sure: you launch Orange as an app, which you installed from .dmg bundle that you downloaded from the website? Not from the terminal?

**Comment by janezd** [comment]
Can't replicate.
