### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by Void-light** [biolab/orange3#3607]
##### Orange version

orange version: 3.21.0.dev0+259c257

##### Expected behavior
scatter plot should show visualization from file widget

##### Actual behavior
nothing to display it is empty

##### Steps to reproduce the behavior

`orange-canvas`

##### Additional info (worksheets, data, screenshots, ...)

![orange webview issue](https://user-images.githubusercontent.com/35738633/52894825-53311a00-31d6-11e9-8551-02280676e933.png)

issue as shown on linux terminal:
**(orange3venv) _user-name@computer-name_:~/orange3$ orange-canvas
/home/bk/orange3/Orange/widgets/io.py:19: UserWarning: WebView from QWebKit or QWebEngine is not available. Orange widgets that depend on it will fail to work.
  warn('WebView from QWebKit or QWebEngine is not available. Orange '
QNetworkReplyHttpImplPrivate::_q_startOperation was called more than once QUrl("https://docs.orange.biolab.si/3/visual-programming/")
**

**Comment by janezd** [comment]
Scatter plot showed you a warning message in its status bar. What does it say?

Scatter plot does not depend on QWebEngine/QWebKit, AFAIK, so the warning from the log that you included is almost certainly unrelated.

**Comment by Void-light** [comment]
when I click the warning it doesn't do anything . Hence, I am unable to read it.

**Comment by Void-light** [comment]
> ##### Orange version
> 
> orange version: 3.21.0.dev0+259c257
> ##### Expected behavior
> 
> scatter plot should show visualization from file widget
> ##### Actual behavior
> 
> nothing to display it is empty
> ##### Steps to reproduce the behavior
> 
> `orange-canvas`
> ##### Additional info (worksheets, data, screenshots, ...)
> 
> ![orange webview issue](https://user-images.githubusercontent.com/35738633/52894825-53311a00-31d6-11e9-8551-02280676e933.png)
> 
> issue as shown on linux terminal:
> **(orange3venv) _user-name@computer-name_:~/orange3$ orange-canvas
> /home/bk/orange3/Orange/widgets/io.py:19: UserWarning: WebView from QWebKit or QWebEngine is not available. Orange widgets that depend on it will fail to work.
> warn('WebView from QWebKit or QWebEngine is not available. Orange '
> QNetworkReplyHttpImplPrivate::_q_startOperation was called more than once QUrl("https://docs.orange.biolab.si/3/visual-programming/")
> **

when I click the warning it doesn't do anything . Hence, I am unable to read it.

**Comment by janezd** [comment]
Open the scatter plot (by double-clicking it). The warning is shown at the bottom of the scatter plot widget.

**Comment by Void-light** [comment]
Please view the scatter plot.

![sp](https://user-images.githubusercontent.com/35738633/52898911-d91a8880-3209-11e9-818e-8c46981d8632.png)

**Comment by janezd** [comment]
Where is the bottom line? Is the resolution too low, so the status line of the widget is covered by the toolbar at the bottom?

You can also go back to the canvas, move the mouse over the orange triangle above the widget icon and see the tooltip there. (Don't click it, just hover.)

I suspect that your data does not have any numeric variables, so scatter plot has nothing to show. This should be (and probably is) reported in the warning.

**Comment by Void-light** [comment]
when hovered the triangle it showed as 

> Data has no continuous variable

> I uploaded zoo.tab from the datasets

**Comment by janezd** [comment]
Alright, works as intended. Try some data data has numeric variables, like Iris.
