### ISSUE TITLE
OWSql does not load the stored tables [with fix]

### ISSUE THREAD

**Issue by fondamenti-dev** [biolab/orange3#3609]
##### Orange version
3.20.1 (but also 3.19)

##### Expected behavior
When I load an ows file all the SQL Tables automatically reconnect to the server

##### Actual behavior
The SQL Tables do not select the correct tables, and I should open each one in turn to select the proper table

##### Steps to reproduce the behavior
Open an ows file containing a saved SQL Table

##### Additional info (worksheets, data, screenshots, ...)
the problem arises because the TableModel is not yet filled with the tables' names when __init__ select the table. This should be done AFTER connecting to the DB.

Solution: edit the file Orange/widgets/data/owsql.py and in the OWSql.__init__ method move the lines 

```
        index = self.tablecombo.findText(str(self.table))
        if index != -1:
            self.tablecombo.setCurrentIndex(index)
        # set up the callback to select_table in case of selection change
        self.tablecombo.activated[int].connect(self.select_table)
```

at the end of the metod, just after the line 

```
        self.connect()
```

**Comment by janezd** [comment]
@lanzagar, @robertcv, could one of you try this?

**Comment by fondamenti-dev** [comment]
Perhaps there is a more elegant solution :) this is a quick hack

**Comment by robertcv** [comment]
Looks ok to me.
