### ISSUE TITLE
Can't pull widget to front

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3610]
##### Orange version

3.21.dev

##### Expected behavior
Widget window stays open and on top.

##### Actual behavior
Widget window closes and cannot be re-opened.

##### Steps to reproduce the behavior
File (or any other widget). Open the widget. Minimize it. Then double click the widget to bring it back to the front. The widget opens, then immediately closes and cannot be reopened. Does not happen with Display widgets on top turned off.

##### Additional info (worksheets, data, screenshots, ...)
MacOS, High Sierra.
qt                        5.6.2
pyqt                      5.6.0

**Comment by janezd** [comment]
Can't replicate (Qt 5.9.7, PyQt 5.9.2). Can you?

**Comment by ajdapretnar** [comment]
PyQt5==5.12.2, Qt==5.9.7.
Issue persists.

**Comment by janezd** [comment]
Nobody except for @ajdapretnar is able to pull this trick. It doesn't bother her. Hence closing until somebody else reports it.
