### ISSUE TITLE
Test which version is installed with Anaconda Navigator

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#3621]
In https://github.com/biolab/orange3-network/issues/105, @ajdapretnar commented that "*we need some testing on Anaconda Navigator, because many people seem to use it and we are not even sure which version is installed when*".

**Comment by ajdapretnar** [comment]
Some notes.
Anaconda seems to promote Orange on its home screen. The version available is 3.17. When I click and install Orange, it works fine, 3.17 is installed. When I open Orange, it prompts me to download the latest version, 3.20. When I click this, it redirects me to the website, where I can download Orange. If I install it, it won't recognize Anaconda and it will install Orange separately, so I have two versions installed, 3.17 from Anaconda and 3.20 from the installer.
To check: installation of add-ons on the 3.17 version from Anaconda.

**Comment by ajdapretnar** [comment]
Some add-ons fail on 3.17 and also on updated 3.20, namely Geo (shapely), ImageAnalytics (compiler, libbrotli), Network (compiler missing) and Text (compiler, UDPipe).
Some work on 3.20 while they failed on 3.17, namely SingleCell.

**Comment by ajdapretnar** [comment]
I have unassigned myself since this issue can be solved by someone who knows a bit more about conda environments.

**Comment by PrimozGodec** [comment]
Nov Anaconda navigator has version 3.23. Anaconda navigator uses the version from anaconda channel. It is just required to ping the maintainers after new release at conda-forge is available. It can be done with opening an issue on this repository https://github.com/AnacondaRecipes/orange3-feedstock

**Comment by PrimozGodec** [comment]
If you agree we can add this to Orange installation instructions.
