### ISSUE TITLE
The transform widgets error

### ISSUE THREAD

**Issue by toop** [biolab/orange3#3675]
##### Orange version
3.20.1

##### Expected behavior
![transform](https://user-images.githubusercontent.com/1625023/54323435-5b913f00-4634-11e9-92a3-4c460f37f029.png)

##### Steps to reproduce the behavior
win 10 64，py：3.6.7，Orange3 3.20.1，pip install，Pyqt5

**Comment by VesnaT** [comment]
Sentry issue: [ORANGE3-26N](https://sentry.io/organizations/biolab/issues/882920981/?project=124497&referrer=github_plugin)

**Comment by janezd** [comment]
Fixed in #3673
