### ISSUE TITLE
Scatter Plot and/or t-SNE: Show more than 10 clusters

### ISSUE THREAD

**Issue by mstrazar** [biolab/orange3#3679]
Application of scOrange typically involve tens of clusters. Showing them on a single plot is one of the key results of the relevant studies.

Upgrade scatter plot to associate cluster labels to the cluster centers, as shown below:
<img width="408" alt="scorange-clusters" src="https://user-images.githubusercontent.com/5073833/54437814-c5ddd880-4735-11e9-80f2-69c5e0319577.png">

**Comment by markotoplak** [comment]
I also had such request from people doing spectroscopy - they are sometimes working with more that 10 strains.

Maybe we could approach this feature with custom color palettes. Orange could use only its 10 color palette by default, and then, if a user set another color palette, all the colors should be used.

**Comment by janezd** [comment]
Issue moved to #4090.
