### ISSUE TITLE
Scatter Plot data updates

### ISSUE THREAD

**Issue by lanzagar** [biolab/orange3#3684]
##### Orange version

3.21-dev (master on 2019-03-19) : 9e0d4eb0

##### Expected behavior
Scatter Plot shows correct data

##### Actual behavior
Scatter Plot does not update and shows old data after a categorical variable changed in the input data.

##### Steps to reproduce the behavior
File (heart-disease) -> Edit Domain -> Scatter Plot
First connect all 3 widgets without any changes. SP shows blue and red points colored by diameter narrowing, legend says 0/1.
Then rename the values in ED, e.g. 0->foo and 1->bar. Click Apply which sends new data. SP still shows old data in legend, tooltip etc. Making changes does not help. After disconnecting and connecting the signal to SP it updates.

##### Additional info (worksheets, data, screenshots, ...)
Other visualization widgets should be checked too. Maybe @janezd or @VesnaT can take a look?

**Comment by janezd** [comment]
Removing these two lines should fix it: https://github.com/biolab/orange3/blob/master/Orange/widgets/visualize/owscatterplot.py#L317.

At around the same time when Moses and Israelites crossed the Red sea (or not much later), Orange had no context settings and some widget (including Scatter plot) used this trick to not reset (like setting x and y to defaults) every time they received the same data for any reason. I believe they no longer serve any purpose.

<img width="747" alt="Screenshot 2019-03-19 at 19 12 32" src="https://user-images.githubusercontent.com/2387315/54630815-fd70bb80-4a7a-11e9-8854-22e59905e233.png">
