### ISSUE TITLE
Support for chemical structure handling

### ISSUE THREAD

**Issue by apahl** [biolab/orange3#3686]
Hi, I just (re-)discovered Orange and it has really impressively developed.
I like the very intuitive use covering a broad range of functionality, the nice visualizations and the fact that it is written in Python (as opposed to some related tools).  
Installation on Linux via Anaconda worked perfectly.

In addition to the already available functionality (the single cell extension looks very promising) I would be interested in handling chemical structures and might want to work on some extension (no commitment!). For starters, I would like to know if the `Data Table` widget supports displaying images?

Note: I am aware of the [AstraZeneca](https://github.com/AZCompTox/AZOrange) extensions, but they have been unmaintained for too long to be of much help, I guess.

Many thanks for this great project.

Kind regards,  
Axel

**Comment by ajdapretnar** [comment]
Data Table does not support displaying images, but Image Viewer from Image Analytics add-on does. You might also want to look at Chemoinformatics add-on, but I am not sure in what state it is in.

**Comment by apahl** [comment]
Ok, thanks a lot for the hints, I'll look into it. The [Cheminformatics](https://pypi.org/project/Orange3-Chemoinformatics/) extension looks interesting, I hadn't found it before and it uses [RDKit](http://rdkit.org/), which I would also like to do.

**Comment by borondics** [comment]
@ajdapretnar This is very interesting to me as well. Is there a GitHub repository for the Cheminformatics toolbox?

**Comment by ajdapretnar** [comment]
Unofficial add-on developed by an enthusiastic student: https://github.com/mat-cor/orange3-chem
