### ISSUE TITLE
K-means centroids output has no labels

### ISSUE THREAD

**Issue by lanzagar** [biolab/orange3#3687]
K-means has an output containing cluster centroids. Plotting them in e.g. MDS (or doing whatever else with them) is problematic, since the user can't label the points and does not know which cluster they correspond to (to see for example which clusters are similar).

I propose we add a meta column "Cluster" with cluster ids "C1", "C2", ... just as in the default Data output from K-means. Up for discussion - for the sake of consistency we could add the Silhouette meta attribute too.

**Comment by janezd** [comment]
Also, this would be cool but doesn't work.

<img width="617" alt="Screenshot 2019-03-22 at 12 24 04" src="https://user-images.githubusercontent.com/2387315/54819947-d2b27d00-4c9d-11e9-978f-a923210475a2.png">

Attribute columns are doubled after concatenate. Either k-means (or its base class, projection) creates new attributes, or concatenate incorrectly computes the set.
