### ISSUE TITLE
DiscreteVariable.base_value

### ISSUE THREAD

**Issue by lanzagar** [biolab/orange3#3690]
##### Orange version

3.20

##### Expected behavior
base_value can be used or does not pollute the code

##### Actual behavior
I think no one ever uses discrete variables with base_value set, and quite possibly this functionality can't even be used by users of Orange Canvas (gui), at least I don't know how to set/change this anywhere.

I think rather than improving the usability of this feature, we could simply remove it.
Open for discussion.

**Comment by janezd** [comment]
We decided to remove it.

The first option in OWContinuize has to be changed accordingly.
