### ISSUE TITLE
Abort trap when deleting widget with Progress Bar

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3696]
##### Orange version

3.21.dev

##### Expected behavior
Orange doesn't crash when deleting the widget in the middle of a progress bar.

##### Actual behavior
Orange crashes when deleting Topic Modeling. It could be only related to this particular widget. Reporting here so we don't forget.

**Comment by ajdapretnar** [comment]
It seems like this is a problem with Text add-on. Moving the issue.

**Comment by markotoplak** [comment]
I fixed a similar problem (but unrelated to the progress bar) in one of Spectroscopy widgets last week. There, an event tried to access previously freed memory: Quasars/orange-spectroscopy#319. Voila, crash!
