### ISSUE TITLE
Dashboar and visualization

### ISSUE THREAD

**Issue by sherifhassanahmed** [biolab/orange3#3698]
Dears ,

I have some questions related to Orange data mining 

Can we use it to present our model findings which we have obtained via RapidMiner
Capabilities as a Visualization tool e.g., scalability in users and dataset size, security, storytelling, etc.
What is the possibility to have an Orange Server presenting our model findings as dashboards

**Comment by ajdapretnar** [comment]
This is an issue tracker. For question about Orange please use Contact Form from the website and our Gitter channel.

**Comment by sherifhassanahmed** [comment]
My last question can integrate between orange and R or python not from the output , i mean  can use import orange widgets or library in R programming language or vice versa .
