### ISSUE TITLE
Normalization always applied on Distance Correlation widget

### ISSUE THREAD

**Issue by vibarco** [biolab/orange3#3704]
##### Orange version

3.20.1
##### Expected behavior
The posibility to uncheck normalization checkbox on Distance widget
##### Actual behavior
Normalization is applied always, checkbox to disable normalization grey.
##### Additional info (worksheets, data, screenshots, ...)
https://stackoverflow.com/questions/55342904/what-type-of-normalization-uses-orange3-on-distance-pearson-correlation-widget

**Comment by ajdapretnar** [comment]
See reply at StackOverflow: https://stackoverflow.com/a/55419242/6081821
