### ISSUE TITLE
Extending the neural network widget to preset the initial value for the random number generator used in the underlying neural network library.

### ISSUE THREAD

**Issue by WolframRinke** [biolab/orange3#3714]
##### Expected behavior
The neural network widget should have an additional option to set or reset the initial number for the randomnumber generator used in the underlying ANN package. The list of parameters to train the model, alows this parameter, but does not pass it through to the widget. I have attached the necessary code changes to use the default behavior (value = 0) or set the initial value greater than zero.

##### Actual behavior
The initial value for the neural network random number generator could not be reset. Which makes it difficult to reproduce ANN results for diagnoses.

##### Additional info (worksheets, data, screenshots, ...)
I have attached modified owneuralnetwork.py file including the necessary changes.
[owneuralnetwork.py.zip](https://github.com/biolab/orange3/files/3029701/owneuralnetwork.py.zip)

**Comment by ajdapretnar** [comment]
Thank you for this. I suggest you make this a pull request rather than an issue. This will allow us to review the changes and assign you contribution.
The way we handle random seeds is to set them to default for every instance (default is 0). Advanced users can than change them in the code. This makes workflows replicable, while keeping complexity low. See https://github.com/biolab/orange3/pull/3392/files for example.

**Comment by WolframRinke** [comment]
Hi,
I did already a pull request few weeks ago to make and test this changes.
I am not that familiar with github, so maybe you can give me an advice what exactly you need.
Do you need access to my pull request?

Regards, Wolfram

Am 01.04.2019 um 16:22 schrieb Ajda <notifications@github.com<mailto:notifications@github.com>>:


Thank you for this. I suggest you make this a pull request rather than an issue. This will allow us to review the changes and assign you contribution.
The way we handle random seeds is to set them to default for every instance (default is 0). Advanced users can than change them in the code. This makes workflows replicable, while keeping complexity low. See https://github.com/biolab/orange3/pull/3392/files for example.

**Comment by WolframRinke** [comment]
Ok, I managed to do the pull request.
;-)

Am 01.04.2019 um 16:22 schrieb Ajda <notifications@github.com<mailto:notifications@github.com>>:


Thank you for this. I suggest you make this a pull request rather than an issue. This will allow us to review the changes and assign you contribution.
The way we handle random seeds is to set them to default for every instance (default is 0). Advanced users can than change them in the code. This makes workflows replicable, while keeping complexity low. See https://github.com/biolab/orange3/pull/3392/files for example.
