### ISSUE TITLE
Unexpected error AmCAT

### ISSUE THREAD

**Issue by Minoukernst** [biolab/orange3#3716]

**Comment by Minoukernst** [comment]
Can somebody help me with this 'Unexpected error'?



Exception: | requests.exceptions.SSLError: HTTPSConnectionPool(host='sma.amcat.nl', port=443): Max retries exceeded with url: /api/v4/get_token?format=json (Caused by SSLError(CertificateError("hostname 'sma.amcat.nl' doesn't match either of 'amcat.nl', 'www.amcat.nl'",),))
-- | --
Module: | requests.adapters:514
Widget Name: | AmCAT
Widget Module: | orangecontrib.sma.widgets.OWAmcat:140
Widget Scheme: | /var/folders/x6/1kst65095c9fvqkg_40kj3440000gn/T/ows-w20ml_ke.ows.xml
Version: | 3.20.1
Environment: | Python 3.6.1 on Darwin 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64
Installed Packages: | AnyQt==0.0.10, Bottleneck==1.2.1, Orange3-Text==0.6.0, Orange3-sma==0.3.3, Orange3==3.20.1, PyQt5==5.9.2, PySocks==1.6.8, Whoosh==2.7.4, XlsxWriter==1.1.4, amcatclient==3.4.12, atomicwrites==1.3.0, attrs==19.1.0, beautifulsoup4==4.7.1, biopython==1.73, boto3==1.9.126, boto==2.49.0, botocore==1.12.126, bz2file==0.98, certifi==2018.11.29, chardet==3.0.4, cycler==0.10.0, decorator==4.3.2, defusedxml==0.5.0, docutils==0.13.1, docx2txt==0.7, gensim==3.7.1, idna==2.8, jmespath==0.9.4, joblib==0.11, keyring==10.3.1, keyrings.alt==2.2, kiwisolver==1.0.1, llvmlite==0.27.1, lxml==4.3.3, matplotlib==3.0.2, more-itertools==7.0.0, networkx==2.2, nltk==3.4, numba==0.42.1, numpy==1.14.6, oauthlib==3.0.1, odfpy==1.4.0, openTSNE==0.3.0, pdfminer3k==1.3.1, pip==9.0.1, pluggy==0.9.0, ply==3.11, progressmonitor==0.5, py==1.8.0, pyparsing==2.3.1, pyqtgraph==0.10.0, pytest==4.4.0, python-dateutil==2.8.0, python-louvain==0.13, requests-oauthlib==1.2.0, requests==2.21.0, s3transfer==0.2.0, scikit-learn==0.20.2, scipy==1.1.0, serverfiles==0.3.0, setuptools-git==1.2, setuptools==40.8.0, simhash==1.9.0, singledispatch==3.4.0.3, sip==4.19.8, six==1.10.0, smart-open==1.8.0, soupsieve==1.9, tweepy==3.7.0, ufal.udpipe-temp==1.2.0.4, urllib3==1.24.1, validate-email==1.3, wheel==0.33.0, wikipedia==1.4.0, xlrd==1.0.0
Machine ID: | 182521018568705
Stack Trace: | Traceback (most recent call last):  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen    chunked=chunked)  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request    self._validate_conn(conn)  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn    conn.connect()  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connection.py", line 364, in connect    _match_hostname(cert, self.assert_hostname or server_hostname)  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connection.py", line 374, in _match_hostname    match_hostname(cert, asserted_hostname)  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 321, in match_hostname    % (hostname, ', '.join(map(repr, dnsnames))))ssl.CertificateError: hostname 'sma.amcat.nl' doesn't match either of 'amcat.nl', 'www.amcat.nl'During handling of the above exception, another exception occurred:Traceback (most recent call last):  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/adapters.py", line 449, in send    timeout=timeout  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen    _stacktrace=sys.exc_info()[2])  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment    raise MaxRetryError(_pool, url, error or ResponseError(cause))urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sma.amcat.nl', port=443): Max retries exceeded with url: /api/v4/get_token?format=json (Caused by SSLError(CertificateError("hostname 'sma.amcat.nl' doesn't match either of 'amcat.nl', 'www.amcat.nl'",),))During handling of the above exception, another exception occurred:Traceback (most recent call last):  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/canvas/scheme/widgetsscheme.py", line 579, in create_widget_instance    widget.__init__()  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orangecontrib/sma/widgets/OWAmcat.py", line 140, in __init__    self.api_dlg.accept(silent=True)  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orangecontrib/sma/widgets/OWAmcat.py", line 91, in accept    self.check_credentials(drop_token = not silent) ## first time loading, use token from last session  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orangecontrib/sma/widgets/OWAmcat.py", line 76, in check_credentials    api = AmcatAPI(self.host_input, self.user_input, self.passwd_input, token)  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/amcatclient/amcatclient.py", line 147, in __init__    self.token, self.version = self.renew_token(token)  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/amcatclient/amcatclient.py", line 193, in renew_token    resp = self.request(URL.get_token, method='post', expected_status=200)  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/amcatclient/amcatclient.py", line 238, in request    r = requests.request(method, url, data=data, params=options, headers=headers)  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/api.py", line 60, in request    return session.request(method=method, url=url, **kwargs)  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 533, in request    resp = self.send(prep, **send_kwargs)  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 646, in send    r = adapter.send(request, **kwargs)  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/adapters.py", line 514, in send    raise SSLError(e, request=request)requests.exceptions.SSLError: HTTPSConnectionPool(host='sma.amcat.nl', port=443): Max retries exceeded with url: /api/v4/get_token?format=json (Caused by SSLError(CertificateError("hostname 'sma.amcat.nl' doesn't match either of 'amcat.nl', 'www.amcat.nl'",),))
Local Variables: | OrderedDict([('cert', None),             ('chunked', False),             ('conn',              <urllib3.connectionpool.HTTPSConnectionPool object at 0x130cb1828>),             ('proxies', OrderedDict()),             ('request', <PreparedRequest [POST]>),             ('self', <requests.adapters.HTTPAdapter object at 0x130cb1080>),             ('stream', False),             ('timeout', <urllib3.util.timeout.Timeout object at 0x130cb1908>),             ('url', '/api/v4/get_token?format=json'),             ('verify', True)])

**Comment by ajdapretnar** [comment]
We are not the developers of the sma add-on. Please report this to the corresponding repository.
