### ISSUE TITLE
I'm using Orange trough anaconda and I get error any time I try to add "text" as well as with other several  adds on. Any idea why?

### ISSUE THREAD

**Issue by LunardonR** [biolab/orange3#3720]

**Comment by LunardonR** [comment]
![image](https://user-images.githubusercontent.com/49252569/55510599-ec20d500-565e-11e9-81b0-ce97c11993d4.png)

**Comment by LunardonR** [comment]
![image](https://user-images.githubusercontent.com/49252569/55511532-20959080-5661-11e9-82bc-a5b16ce6ae83.png)

**Comment by ajdapretnar** [comment]
Please click on the Show Details button and post the log in here. Thank you.

**Comment by vvovvovvo** [comment]
I cannot install the Text add-on on Windows 10 System 32.
![Issue](https://user-images.githubusercontent.com/39279170/57599312-ed4af900-755e-11e9-9c26-d6c2bddbcdd7.jpg)

For Windows 10 System 64 it works correctly.

How can I fix this?

**Comment by ajdapretnar** [comment]
Text add-on cannot be installed on 32-bit systems.

**Comment by ajdapretnar** [comment]
I added a reference in [README](https://github.com/biolab/orange3-text#orange3-text).
The issue was also discussed in https://github.com/biolab/orange3-text/issues/430.

**Comment by DaveCooperUAB** [comment]
Same issue, here is the log file.
Windows 10
64-bit

[Orange3-text install log.txt](https://github.com/biolab/orange3/files/9078031/Orange3-text.install.log.txt)
