### ISSUE TITLE
Test & Score widget - How do I see Classification results instead of Regression results

### ISSUE THREAD

**Issue by oherna5** [biolab/orange3#3733]
![Captura de Pantalla 2019-04-08 a la(s) 2 45 54 p  m](https://user-images.githubusercontent.com/49414230/55752342-580f8e80-5a0d-11e9-99da-d51989b9d631.png)
![Captura de Pantalla 2019-04-08 a la(s) 2 46 25 p  m](https://user-images.githubusercontent.com/49414230/55752346-5ba31580-5a0d-11e9-9b41-f1f397b0234a.png)

What do I have to do for the Test & Score widget to show me CA, AUC, etc instead of MSE, RMSE, R2, etc ?
I want to see the Classification results for my classification tree and SVM but it doesn't show me it. Thank you

**Comment by oherna5** [comment]
1st screenshot is my sreen. 2nd screenshot is a video on youtube which I'm trying to follow but when he uses the Test & Score widget it automatically does CA, AUC, F1, etc.

**Comment by markotoplak** [comment]
Probably your working on a data set with a numeric target variable (check in your File widget), which means that your are doing regression. Then, Orange seems to work as expected.

To do classification (and see classification measures) you need a data set with a categorical target variable.

Please reopen this issue if that was not the case.
