### ISSUE TITLE
not able to install orange3 in virtualenv

### ISSUE THREAD

**Issue by laocoon6** [biolab/orange3#3734]
##### Orange version
3.21

##### Expected behavior
- installation: follow the instruction guide on https://github.com/biolab/orange3 and it should work

##### Actual behavior
- a lot of widgets weren't loaded because WebView wasn't available:
`UserWarning: WebView from QWebKit or QWebEngine is not available. Orange widgets that depend on it will fail to work.
  warn('WebView from QWebKit or QWebEngine is not available. Orange '
Error while importing 'orangecontrib.geo.widgets.owchoropleth'. The widget will not be shown.`

##### Additional info (worksheets, data, screenshots, ...)
- `pip install PyQtWebEngine` solved the problem, but the in the instruction guide mentioned `pip install PyQt5` did not suffice.

**Comment by janezd** [comment]
Core widgets do not depend on WebView, thus Orange would work (except for reports, see also #3661). The problem that you reported occurred in the geo add-on.

Some distributions of PyQt5 already include QWebEngine and some don't, so I'd prefer not to add PyQtWebEngine to instructions. I instead added a paragraph about solving this issue.

Thanks!
