### ISSUE TITLE
OWDistributions: legible axis labels

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3736]
Follow up from #2110.

Current state of Distributions widget.
<img width="720" alt="Screen Shot 2019-04-12 at 10 13 19" src="https://user-images.githubusercontent.com/12524972/56022359-c0ab8380-5d0b-11e9-9185-1df5e5f95a47.png">

Suggested solution:
![image](https://user-images.githubusercontent.com/12524972/56022430-f6e90300-5d0b-11e9-9bba-8eb7a84e802e.png)

Labels should not be tilted, but vertical if len < 10 char, if more, elide the label and show every n-th. Tooltips provide access to full labels.

**Comment by ajdapretnar** [comment]
Also fix showing of datetime variable. Currently, datetime is converted to float (which in the background it definitely should), but it should be displayed to the user as datetime.

**Comment by janezd** [comment]
Datetime is fixed in #3846. @VesnaT, can you fix the overlapping labels in the same way as you did in line plot?

**Comment by janezd** [comment]
Don't work on this (if at all) before #3896 is finished.
