### ISSUE TITLE
OWMosaicDisplay: legible axis labels

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3739]
Follow up from #2110.

Current status of Mosaic Display widget. The widget discretizes to 4 values, which normally results in nice visualizations. Only when it doesn't - values are very small or discrete variables has many and/or long labels.
<img width="668" alt="Screen Shot 2019-04-12 at 10 43 19" src="https://user-images.githubusercontent.com/12524972/56024268-f2264e00-5d0f-11e9-9414-803d80efe078.png">

I propose we elide the label that goes over the width of its own field. If field smaller than some width, hide the label.

**Comment by ajdapretnar** [comment]
Also fix showing of datetime variable. Currently, datetime is converted to float (which in the background it definitely should), but it should be displayed to the user as datetime.

**Comment by janezd** [comment]
I implemented eliding (in #3845). As for other problems (number formatting, datetime values): the widget shows whatever is in the `Variable`'s `values`. Badly formatted numbers and deformed datetimes come from discretization.

**Comment by janezd** [comment]
Improper discretization of `TimeVariable` as well as printing of small numbers is fixed in #3846.
