### ISSUE TITLE
OWBoxPlot: legible axis labels

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3740]
Follow up from #2110.

Current status of Box Plot widget. Long labels illegible. Elide if labels longer than 10 chars or show just every n-th.
<img width="913" alt="Screen Shot 2019-04-12 at 11 00 09" src="https://user-images.githubusercontent.com/12524972/56025418-5f3ae300-5d12-11e9-9d99-736bdb19d394.png">

At the same time, handle reading of datetime variables better. Display datetime, not float.

**Comment by asmaier** [comment]
Having more readable datetime labels would be very helpful for plots and especially timeseries.

**Comment by janezd** [comment]
@asmaier, #3847 and #3847 fix this for most visualizations. You'll get it in the next release.

Boxplot is a different story and it highlights a problem we have with datetime variables (which also affects other visualizations, to a lesser extent).

<img width="735" alt="Screenshot 2019-06-12 at 17 22 37" src="https://user-images.githubusercontent.com/2387315/59364351-03eb9800-8d37-11e9-81cd-8ed4c1813a32.png">

**Scale.** Numeric variables remember the (maximal) number of decimals for each variable. Datetime variables don't have this. In the above picture, we don't care about microseconds (which are currently printed out for the mean!); dates would suffice. In other cases, all events would happen in a single day, so we may print out only hours - and maybe without seconds, if they are all 00.

**Differences.** The difference between two `float`s is a `float`. The difference between two dates is not a date. Hence the variance in the above graph is printed as a number of, well, seconds. Solving this requires both, knowing the scale and being able to print out the difference - which the current `str_val` methods doesn't.

**Comment by janezd** [comment]
#3877 actually makes the issue with axis labels worse. :)
