### ISSUE TITLE
OWSieveDiagram: legible axis labels

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3742]
Follow up on #2110.

Current widget status.
<img width="549" alt="Screen Shot 2019-04-12 at 11 13 15" src="https://user-images.githubusercontent.com/12524972/56026253-0cfac180-5d14-11e9-8f05-bc67277a8e98.png">

Solve overlap by eliding over the width of the column. If column too small, hide the label.
Also, display proper datetime, not floats.

**Comment by janezd** [comment]
See #3845 for a fix of a similar problem on OWMosaic
