### ISSUE TITLE
OWLinearProjection: legible axis labels

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3743]
Follow up on #2110.

Current widget status. Linear Projection is hard to 'destroy'. But if one has a really, really large number of attributes, it is possible. I suggest limiting the number of attributes that can be displayed to, say, 20. If feature names are reaaaaaaaaallllly long, elide them at... dunno, 20 chars.
<img width="1132" alt="Screen Shot 2019-04-12 at 11 21 29" src="https://user-images.githubusercontent.com/12524972/56026790-336d2c80-5d15-11e9-981b-27d794067ffa.png">

**Comment by janezd** [comment]
Same as #3744: we need to define the gui for this.

**Comment by janezd** [comment]
@robertcv, you solved this for Radviz in #3744. Would you, as an expert, do the same here?
