### ISSUE TITLE
OWRadViz: legible axis labels

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3744]
Follow up on #2110.

Current widget status. Similar to #3743. Limit the number of features displayed to 20. If features names are long, elide them after 20 chars.
<img width="869" alt="Screen Shot 2019-04-12 at 11 26 33" src="https://user-images.githubusercontent.com/12524972/56027315-1dac3700-5d16-11e9-9db9-1dc1d7dced5e.png">

**Comment by janezd** [comment]
Propose an interface for limiting the number of shown attributes. If the 21st is added, the bottom one disappears?

**Comment by janezd** [comment]
This widget requires some love. In the above example, Japan is written over the point that is actually Kenya. Labels for points on the left should be on the left side. The labels on the bottom overlap... @robertcv?
