### ISSUE TITLE
OWMDS: legible labels

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3745]
Follow up on #2110.

Current widget status. This evidently does not concern axis labels, but labels in general. A common problem in MDS are overlapping labels. If labels are small numerical values, I vote for scientific notation. I have no idea what to do with labels when points are close together. We could compute some distance to points and if distance is closer than some arbitrary measure, then elide or hide the labels. But I think this is too much work for little effect.
<img width="843" alt="Screen Shot 2019-04-12 at 11 59 56" src="https://user-images.githubusercontent.com/12524972/56029447-a7f69a00-5d1a-11e9-8e7e-249f4a8501d7.png">

The issue can easily be closed if you think this is not something we would be willing to solve.

**Comment by markotoplak** [comment]
We started tackling small values in #3574.

The widget either doesn't use the variables' `val_to_str()` or the number of decimals is set to something high. If the first, the fix is trivial, if the second, we could perhaps make `val_to_str()` always use `%g` if the number of decimal is too large.

**Comment by janezd** [comment]
I believe this has been fixed in #3757; @ajdapretnar, can you check?

As for overlapping labels - it's too complicated, we won't do it.

**Comment by ajdapretnar** [comment]
Yes, it is fixed.
