### ISSUE TITLE
An easier way to update Orange

### ISSUE THREAD

**Issue by acopar** [biolab/orange3#3749]
Issue: The current way to update existing Orange installation is difficult and time-consuming.

When a new Orange version is available, the following procedure is needed:
1) A dialog opens upon starting Orange (which is impossible to bring back once closed).
2) The dialog points you to the Orange download web page.
3) You need to download the installer about 500MB in size.
4) You follow the installer dialog which may have to reinstall the complete environment during major version changes (ex. python 3.6 -> 3.7).

There is an alternative approach, but it is not well-known:
1) Follow the menu Options -> Add-ons.
2) Click "Add more" button.
3) Type "Orange3" in the dialog box that appears and click "Add".
4) Make sure you have checked the Orange3 checkbox (black square symbolizes out-of-date, checkbox symbolizes marked for update). Click "Ok" to update Orange.

I propose a new procedure:
1) A new menu item in Help -> Check for updates.
2) A dialog opens that shows you if Orange is up-to-date or if a new version is available (similar to the one that opens at startup).
3) The dialog contains an update button.
4) The update button runs "conda update Orange3" in a separate progress window.

The new approach would only download about 4.5MB of data (according to https://anaconda.org/conda-forge/orange3/files) and perhaps some dependencies. It is also at least ten times faster when the alternative requires you to build the environment from scratch. 

Current MacOS builds are not shipped with Miniconda, but as a standalone python environment, therefore the update procedure for MacOS may need to be kept as-is.

**Comment by markotoplak** [comment]
@acopar, we could use conda or pip depending on the installing. For pip-based installation, `pip install --upgrade --upgrade-strategy only-if-needed Orange3` could work.

**Comment by markotoplak** [comment]
In our packages we manually choose (some) versions of dependencies. These manually included dependencies are usually higher that a minimum needed version for the requirement. Therefore, if we will upgrade a dependency in our package, the users that upgraded the fast way may have different dependency versions that the users who installed fresh. I am not sure if that is a problem.

**Comment by ajdapretnar** [comment]
Could an upgrade come with a list of updated dependencies? Like a diff? Then run the updates if necessary...

**Comment by astaric** [comment]
5. Orange is automatically restarted (or closed, before the separate progress window is shown), as modifying the source under a running python application can lead to crashes.
(any local imports will lead the module from the new version, if it is not cached yet)

Also note that Orange version in Control Panel > Programs will not get updated, and when uninstalling, the uninstaller will show the "original" version.

**Comment by astaric** [comment]
Alternatively, a separate "Update" installer can be built (using nsis), which contains only the packages that need to be upgraded (no miniconda installer, no mkl, ...). It will be much smaller and can do any registry tweaks required for windows to recognise the new version.

**Comment by ajdapretnar** [comment]
Such an option would also enable us to distinguish Downloads from Updates, as in new users from existing ones. ❗️

**Comment by janezd** [comment]
I wouldn't touch anything before #2792 (standalone canvas), which will also affect how Orange is packaged, distributed and updated. After #2792, Orange widgets will taste more like an add-on.

**Comment by acopar** [comment]
@astaric Yes, the update procedure should:
1) Stop Orange and prompt user to save any work.
2) Update the necessary packages, ideally with minimal amount of user input.
3) Start Orange again and perhaps open the previous workflow.

@markotoplak If the version was manually chosen, it is better to use conda updates rather than a new environment, otherwise you would have to repeat the procedure. If the installer can re-use the environment, there would not be much difference between standalone or fast update.

@janezd I agree, this feature is perhaps best included with/after the release of Orange 4.

**Comment by janezd** [comment]
This will be solved when the canvas is separated from Orange.
