### ISSUE TITLE
Widget development documentation is wrongly built or out of date

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#3754]
The Orange web page links widget development documentation to http://orange-development.readthedocs.org/. There, the documentation is not built properly: docstrings of functions are missing (see https://orange-development.readthedocs.io/gui.html).

We also have another documentation page that used to be the one linked. There, docstrings work (see https://docs.biolab.si/3/development/gui.html), but that one seems to be outdated.

**Comment by ajdapretnar** [comment]
I have tried to debug this for the past hour and I have no idea how to solve this. When make html is run in development, it shows it cannot import PyQt and such, but when I add PyQt back to the requirements-doc.txt, nothing changes. I have tried modifying the path and nothing worked. I have tried mocking import, but I am not sure that's what we should be doing anyway and it took me on a downward spiral of new and new errors.

**Comment by markotoplak** [comment]
Does anyone remember why did we move this part of the documentation to read the docs? Because it used to be hosted on our server (I remember setting this long time ago). Scripting tutorial and reference are still hosted locally.

**Comment by ajdapretnar** [comment]
From what I see scripting is also hosted on rtfd: https://orange-data-mining-library.readthedocs.io/en/latest/.

**Comment by markotoplak** [comment]
@ajdapretnar, yes, but at least the link from our docs page goes to our server. :)
