### ISSUE TITLE
Inconsistent behavior without auto-apply on new input signals

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#3755]
##### Orange version
3.20

##### Expected behavior
According to #3455, widgets should Apply, Send or Run when their input signals changed even if auto-apply/send/run is disabled. 

##### Actual behavior
Widgets are a bit inconsistent. For the following screenshot I made sure that the widget would output something on Apply (selecting things if needed), disabled all auto- checkboxes and reloaded the workflow.

![Screen Shot 2019-04-17 at 13 27 09](https://user-images.githubusercontent.com/552182/56304659-fdfd8000-6114-11e9-8f42-2c5dd112e7cb.png)

**Comment by PrimozGodec** [comment]
This issue has been split in three separate issues #3761, #3762 and #3763.
