### ISSUE TITLE
Widgets don't Apply, Send or Run when their input signals changed and widgets do not remember selected subset

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/orange3#3763]
##### Orange version

3.21-dev

##### Expected behavior

According to #3455 and #3755, widgets should Apply, Send or Run when their input signals changed even if auto-apply/send/run is disabled.
Widgets should also remember what data were selected for the dataset.

##### Actual behavior

Widgets are not consistent. Some widgets do not Apply, Send or Run when the input signal change and at the same time widgets do not remember what data were selected before.
Those widgets are:

- [ ] Line Plot
- [ ] Heat Map
- [ ] Data Table
- [ ] Venn Diagram

... and the following projections widgets:

- [ ] Scatter Plot
- [ ] FreeViz
- [ ] Linear Projection
- [ ] RadViz
- [ ] MDS
- [ ] tSNE (apply works)

##### Steps to reproduce the behavior

For selection: 
Connect the widget's input to the data source (e.g. File Widget) set dataset to `Iris`. Select part of data in widget. Change data to some other dataset and change data back to `Iris`. The selection for `Iris` should be still present but it is not. 

For apply: 
Uncheck apply automatically checkbox and change the input data. Observe if output data changes (widget do something with the input).

##### Additional info

Venn Diagram does not remove selection when different dataset at the input.

**Comment by janezd** [comment]
Storing selections actually works as intended. Selections are saved as schema-only setting because data instances are not a part of the context, so they cannot be reliably retrieved on context switches.

The only widget that needs fixing selections is Heat map, where this is also noted in Todo in the code.
