### ISSUE TITLE
New project with a similar GUI

### ISSUE THREAD

**Issue by caballerofelipe** [biolab/orange3#3767]
Hi Orange Team, I've used Orange and I love the interface.

I would like to create a GUI for a project of my own using Python that would work in a similar manner to Orange ( [1] nodes conected by lines, [2] a node library on the left and [3] node execution sequence depending on the path of the connections).

I don't know how to get started on this task so I thought of forking Orange but the source code is extensive and I don't know where to start looking. Could  you point me in the right direction in one of the possible paths I see or maybe show me a new one I haven't. These are the paths I currently visualize:

* If I created a fork of Orange how could I strip all functionalities except for the node connections?
* If I try creating a program from scratch, could you give me any pointer on where to look? I'm guessing Orange uses some libraries... so I guess those would be handy.
* If I try and customize Orange, where should I begin? Where is the entry point for executing the Orange GUI? Is there some flow chart to understand how it's built?

Thanks a lot.

**Comment by ajdapretnar** [comment]
I think this is heavily related to: https://github.com/biolab/orange3/pull/2792

@caballerofelipe Orange will soon be split into 3 packages, one of them being a standalone canvas with the functionality of building 'plain' Orange - no ML package, just GUI components. Given @ales-erjavec's meticulousness, I think there will be nice documentation too. There already is one in our [docs](https://orange-development.readthedocs.io/) and [Wiki](https://github.com/biolab/orange3/wiki) page.

**Comment by caballerofelipe** [comment]
Thanks a lot for your reply!

I'll read on, it seems promising.

**Comment by caballerofelipe** [comment]
Hi @ajdapretnar and @ales-erjavec, I've read https://github.com/biolab/orange3/pull/2792 and apparently there is something already in place (https://github.com/biolab/orange3/issues/2331#issuecomment-303348617).

So...

- Is there usable something already? (If so please provide a link)
- Do you have some time frame in which you would release **officially** this separation?

Thanks a lot.

**Comment by ajdapretnar** [comment]
Usable? At the moment, no. There's only one stellar developer that's able to do this, hence the lag, but once it will be done, it will be really good (and done well).
Time frame? Also no. Any predictions would be misleading at best. I reckon a month, but it could be many more, should any unexpected complications arise. But be sure we are actively working on this and are looking forward to it as much as you.

**Comment by caballerofelipe** [comment]
@ajdapretnar thanks a lot for the feedback. I feel you give really generous responses which is something not seen too frequently on the web :)

So, nothing usable yet... now, I'm feeling inclined on doing the following:
- Remove (or hide) all Widgets
- Remove the welcome screen
- Add my own Widgets
- Use Orange's way of doing things and making it work for me

How could I remove widgets? How can I add Wigets and bundle them in a single package (so if shared with someone they wouldn't have to install other stuff)?

Thanks

**Comment by ajdapretnar** [comment]
I would suggest not to replicate the effort yourself. Mostly for future compatibility. There is already a PR in the making: https://github.com/biolab/orange3/pull/3772
Once this is done, you will be able to install just Canvas, base widget (for making widgets), ML widgets separately or in combination. If you start doing something on your own you would likely need to maintain a lot of code in the future. Going with the new standalone Orange Canvas would make it a lot easier for you, because you can simply pin the version or get the updates directly from us. I think it is really worth waiting for 3772 to be done.

**Comment by caballerofelipe** [comment]
@ajdapretnar thanks 😉

**Comment by caballerofelipe** [comment]
@ajdapretnar do you know about another project that could be used in the way I need? To create a workflow node based interface...
