### ISSUE TITLE
ModuleNotFoundError when running custom code using Python Script 

### ISSUE THREAD

**Issue by cyberandy** [biolab/orange3#3776]
##### Orange version

3.18 

##### Expected behavior

I am trying to run custom code that requires a library and I am wondering if this is possible. 

##### Actual behavior

I read the following error in the console.
ModuleNotFoundError: No module named 'feedparser'

##### Steps to reproduce the behavior

here is the list of libraries I have in my script

```
import feedparser
import time
from subprocess import check_output
import sys
import pandas as pd
import re

```

##### Additional info (worksheets, data, screenshots, ...)

You are doing an amazing work!

**Comment by markotoplak** [comment]
Are you sure you have installed feedparser into the same python environment Orange runs from?

Orange on Windows and Macs comes with its own Python and libraries. If you are on Windows, open Orange command prompt and install the missing library there.

If you are on Mac, there is pip inside the application that you can use to install other libraries into the image.

**Comment by cyberandy** [comment]
Hi @markotoplak thanks for your prompt reply - I am on Mac and I was able to install the module using the pip install inside the app 👍

Now I get the error that 'data' needs to be an instance of 'Table' but I can probably look into the documentation and solve the problem.
