### ISSUE TITLE
How can I package orange3 so that it can be used on another computer?

### ISSUE THREAD

**Issue by zzzzhuqi** [biolab/orange3#3785]
I want to package orange3 as exe and use it on another computer. What should I do?thanks

**Comment by ajdapretnar** [comment]
Download exe to that computer? 🤔

**Comment by zzzzhuqi** [comment]
I want to use pyinstaller to package orange3 to generate orange-canvas.exe. I need to package exe instead of downloading exe because I changed a few things

**Comment by markotoplak** [comment]
I have no experience with using pyinstaller. We use NSIS.

The repository we use to make installers with is fully public: https://github.com/ales-erjavec/orange3-installers. If you need something customized, you can start with the code there.

If you find an easy way of packing Orange with pyinstaller, please share it with us.

**Comment by FP440** [comment]
Hi, 
I had the same thought about packing Orange (with additional personal add-ons) with pyinstaller, and I did manage to create one, as in 2026 !
Here is a pyinstaller spec file canvas that I used to build a standalone (no installation required which is great !) customized executable of Orange3.
Hope this helps.

python 3.12
pyinstaller 6.18
Orange 3.40
pip install

---------------------------------------------------------------------------
```
# -*- mode: python ; coding: utf-8 -*-

# some hidden modules to import
from fabio.fabioformats import _default_codecs
hidden = ['fabio.' + module for module, _ in _default_codecs]
hidden += ['skimage.registration']
hidden += ['sympy']

# need to copy into the exe some full modules in a brute force workaround (pyinstaller misses sometimes the full import even with hiddenimports parameter) 
datas = [
         ( './.venv/Lib/site-packages/Orange', './Orange' ),
         ( './.venv/Lib/site-packages/orangecanvas', './orangecanvas' ),
         ( './.venv/Lib/site-packages/orangewidget', './orangewidget' ),
         ( './.venv/Lib/site-packages/AnyQt', './AnyQt' ),
		]

# add default built-in categories entry points
from PyInstaller.utils.hooks import copy_metadata
datas += copy_metadata('orange3')

a = Analysis(
    ['./dist/orange-canvas-script.py'],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=hidden,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Orange3-standalone',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)

```
---------------------------------------------------------------------------
