### ISSUE TITLE
Installer file for the linux

### ISSUE THREAD

**Issue by dkmauryabarc** [biolab/orange3#3798]
Can you develop installer file for linux version also which contain all the dependencies. So that it can be install even on the proxy server based internet connection.
Regards
Dharmendra

**Comment by janezd** [comment]
We discussed this at today's core team meeting. We wouldn't like to maintain such packages for different versions of Linux, nor would we like to try to create one that would work everywhere and thus have to include all dependencies itself (to only depend on the kernel). Even if we could do it now, it could be cumbersome to maintain.

In short, while this would be doable, nobody is able to dedicate his/her time at the moment and promise his/her commitment for the foreseeable future.
