### ISSUE TITLE
Different interfaces for clustering methods

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/orange3#3805]
##### Orange version

Any

##### Expected behavior

Clustering algorithms should have the same interface, such that other scripts can use them the same way or even replace the clustering method.

##### Actual behavior

There are different interfaces for clustering algorithms. 

1. `KMeans` has `fit` function that accepts `X` and `Y` matrices and returns the instance of `KMeansModel` class as the result. `KMeansModel` has a `__call__` function that accepts either a `Table`, `Instance`, or `np.ndarray`.

2. `DBSCAN` has `fit` function that accepts `X` and `Y` matrices or `Table` and returns the instance of `DBSCANModel` class as the result. `DBSCANModel` has a `__call__` function that accepts either a `Table`, `Instance` (even it is not supported), or `np.ndarray`.

3. `Louvain` has `fit` function that accepts `X` and `Y` matrices or `Table` and does not return anything. It has also a `__call__` function that returns clusters directly.

The `__call__` function of `KMeasnModel` and `DBSCANModel` also does not work when getting the `Table` at the input since there is a bug - checking if `Domain` matches with `self.pre_domain` which do not exist.

`DBSCANModel` call `fit_predict` instead of predict. It is probably made since `sklearn.cluster.DBSCAN` does not have `predict` method implemented, but what is then the purpose of having `Projector` and `Projection` a separate class.

**Comment by pavlin-policar** [comment]
Following the discussion with @PrimozGodec and @markotoplak I propose the following interface for clustering methods:

```python
class Clustering:
    preprocessors = []
    
    def __init__(self):
        self.labels = None
        
    def preprocess(self, data):
        for pp in self.preprocessors:
            data = pp(data)
        return data

    def __call__(self, data: Table) -> np.ndarray:
        data = self.preprocess(data)
        return self.fit_predict(data.X, data.Y)

    def fit(self, X: np.ndarray, y: np.ndarray = None) -> None:
        """Run clustering on the data."""
        raise NotImplementedError()

    def fit_predict(self, X: np.ndarray, y: np.ndarray = None) -> np.ndarray:
        """Run clustering on the data and return the assigned labels."""
        self.fit(X)
        return self.labels
```

It's stateful like scikit-learn models i.e. attributes are set in `fit`. That's not ideal, but if we really want to compute the silhouette score during clustering (like KMeans currently does), that's pretty much the only option.

If the method implements a `predict` method, as KMeans does, then this should be implemented in that class only. As far as I am aware, only KMeans gives a principled way to `predict`, so it's more of an exception than the rule.

**Comment by PrimozGodec** [comment]
I agree with the suggested interface. :) Beside unifying the interface it will also make it clear and understandable, what currently isnot.
