### ISSUE TITLE
Hiding Links Between Widgets

### ISSUE THREAD

**Issue by Guillaumes33** [biolab/orange3#3806]
Hello,

Is it possible to hide some of the links between widgets? I'm setting up a workflow that may be used by various people. I have some widgets that don't need any modification or input while others do; I'd like to move the widgets that don't need changing away from the others and essentially hide them by hiding the links to them. Is this possible?

**Comment by ajdapretnar** [comment]
Currently, this is not possible. There was some discussion already about a meta widget, that would 'shrink' some widgets into a single unit, but so far there is no functionality for this. Any contribution is welcome.
