### ISSUE TITLE
Access model details 

### ISSUE THREAD

**Issue by T4mmi** [biolab/orange3#3816]
Hi there,

Thanks for Orange, that's a great tool for fast prototyping/testing !

**However I'm looking for a way to investigate the trained models**
I managed to try and learn several models using different classifiers but my aim is to go further and see the influence of each individual feature inside the models...

*How to display them ? or at least export them in a non-pickled format ?*

**Comment by markotoplak** [comment]
Display depends on a model. Some output coefficients (like Logistic regression), some can be used with the Rank widget (Log Regression, Random forests) to display feature importance, for Naive Bayes use Nomograms, for trees/forrest their corresponding viewers.

There are no widgets that could export models in a text format. If you really need this, connect models to the Python Script widget and try to explore them there.

**Comment by T4mmi** [comment]
Is there any doc related ?
'cause I couldn't found anything about the correct way to do it ...

> output coefficients (like Logistic regression), some can be used with the Rank widget (Log Regression, Random forests) to display feature importance

How do you display them ? *tried to link the widgets but they put learner > scorer, nothing about coefficients...*

**Comment by markotoplak** [comment]
You are right, there is no documentation on this.

For output coefficients, connect File -> Logistic Regression -> Data Table.

To see feature importances, try: File -> Rank and Random forests -> Rank; now Rank has two inputs connected.
