### ISSUE TITLE
Problem with miniconda installer 3.21.0

### ISSUE THREAD

**Issue by elimisael** [biolab/orange3#3819]
##### Orange version

Orange 3.21.0 for Windows, Minoconda installer, show the following error, when was installed

##### Additional info (worksheets, data, screenshots, ...)

![image](https://user-images.githubusercontent.com/32252966/58344577-b5279e00-7e1b-11e9-8c45-e6c8861fd963.png)

**Comment by markotoplak** [comment]
Thank you! Which Windows version do you use?

Did you already have a version of Orange installed previously? If so, which? Does it help if you first remove Orange and try again?

**Comment by markotoplak** [comment]
I just tried in on a Win 10 computer and I could not reproduce the bug. Could you describe your system better and previous Orange/python installations so I can try reproduce the bug? 

Also, could you try if the previous version works for you? You can download it from https://download.biolab.si/download/files/Orange3-3.20.1-Miniconda-x86_64.exe

**Comment by ales-erjavec** [comment]
Did you have Miniconda installed before installing Orange? If so which version?
Can you please run
```
C:\Users\<USERNAME>\Miniconda3\Scripts\conda info
```
or
```
C:\ProgramData\Miniconda3\Scripts\conda info
```
(depending on where miniconda is installed) from the command prompt and post the output.

Can you also try running
```
<same prefix as before>\conda clean --all
```
and then rerun the Orange installer.

**Comment by stuart-cls** [comment]
Hi, I'm getting this as well (https://github.com/Quasars/quasar/issues/5).

I tried `conda clean --all`, with no success.

If I run `C:\Users\reads\AppData\Local\Continuum\miniconda3\Scripts\conda info` I get

```
     active environment : None
       user config file : C:\Users\reads\.condarc
 populated config files : C:\Users\reads\.condarc
          conda version : 4.6.12
    conda-build version : not installed
         python version : 3.7.2.final.0
       base environment : C:\Users\reads\AppData\Local\Continuum\miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\Users\reads\AppData\Local\Continuum\miniconda3\pkgs
                          C:\Users\reads\.conda\pkgs
                          C:\Users\reads\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\reads\AppData\Local\Continuum\miniconda3\envs
                          C:\Users\reads\.conda\envs
                          C:\Users\reads\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.12 requests/2.21.0 CPython/3.7.2 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by markotoplak** [comment]
In Quasars/quasar#5 @stuart-cls also reported getting the same error if he installed a testing package with qt-5.9.7.

**Comment by markotoplak** [comment]
@stuart-cls, can you try "conda create -n test123 python=3.6 qt"

**Comment by ales-erjavec** [comment]
Can you please test with a patched [installer](https://www.dropbox.com/s/gjneshsj915bu4h/Orange3-3.21.0-Miniconda-x86_64.exe?dl=1) from gh-3843

**Comment by stuart-cls** [comment]
@ales-erjavec the patched installer works.

@markotoplak I can create that environment without issue.

**Comment by ferlocar** [comment]
I had the same issue. The patched installer fixed it for me too.
