### ISSUE TITLE
Using a function in separate Python Scripts

### ISSUE THREAD

**Issue by Guillaumes33** [biolab/orange3#3820]
Hello,

Is it possible to define a function in one Python Script in my workflow and call it in a different script with or without them being connected? The closest I've found is using the function as the in_object and out_object.
![Functions](https://user-images.githubusercontent.com/50418145/58351112-6e00d380-7e42-11e9-8e5b-e685fe174dd4.png)

**Comment by janezd** [comment]
This is doable, but we must think if we're ready to accept the consequences. I suppose that you would also like to be able to define a class in one widget and use it in another. Or prepare some data in one widget and use it in others? In other words, all Python Script widgets would share a common namespace.

Setting `x = 1` in one widget and `x = 2` in another and `x = 3` in the third one would set x to ... well, it depends upon which widget was executed the last. If we agree that this is user's problem, not ours, I suppose implementing shared namespaces shouldn't be a problem.

(Ehm. If you open multiple schemas at the same time, we wouldn't like to share namespaces across them. I suppose we could share namespace across all widgets that share the same instance of signal manager? This is not very nice.)

**Comment by Guillaumes33** [comment]
I wouldn't want a shared namespace. Even something like being able to say 'from Function import F' would be helpful. Sharing variables across scripts would be a problem.

**Comment by ajdapretnar** [comment]
Why is out_object not ok?

**Comment by Guillaumes33** [comment]
Using out_object works, but it's tedious when I need the same function in four or five different scripts, or need to pass in more important objects.
Can I connect multiple in_objects to a single script?
