### ISSUE TITLE
Problem with Widget test & score [BUG ?]

### ISSUE THREAD

**Issue by junglejf** [biolab/orange3#3835]
##### Orange version
3.21

##### Expected behavior

Test and score should give the results 

##### Actual behavior

It gets stucked in 0%, i already left it running for more than 24 hours.

##### Steps to reproduce the behavior
load my crime_teste_29_05_2019.ows
load table dados_teste
load table dados_treinamento

##### Additional info (worksheets, data, screenshots, ...)

If i put few data (10 instances) to test it runs but if i put more than 50.000 instances its get stucked. Even when i reduce the test data from 12 months to only 1 month(~11.000 instances
) it stills getting stucked but now at 49%,
![image](https://user-images.githubusercontent.com/12838919/58635375-193ade00-82c4-11e9-9ac3-23a7efde5c99.png)
![image](https://user-images.githubusercontent.com/12838919/58635402-2d7edb00-82c4-11e9-91fa-86fafe7ead4b.png)

orange project
[crime_teste_29_05_2019.zip](https://github.com/biolab/orange3/files/3237128/crime_teste_29_05_2019.zip)

The data files are bigg so i uploaded them in google drive.
https://drive.google.com/open?id=18iJc_f0bz2ZmcsqeXr-JTH2c5NTxsWm6
treinamento = train data
teste = test data

**Comment by markotoplak** [comment]
It does not seem like a bug. kNN is a very slow method when there are many instances. CN2 in Orange is not optimized - it is merely meant for education.

Rather try some other algorithms. Start with Logistic regression, then move on to Random Forests (both should be quite fast) and then perhaps try with SVMs.
