### ISSUE TITLE
Help:  the latest version for Windows doesn't run

### ISSUE THREAD

**Issue by MrDavidGB** [biolab/orange3#3837]
##### Orange version

The latest version for Windows: Orange 3.21

Windows 10.

##### Expected behavior
Orange should run.

##### Actual behavior
I double clicked in the icon, but Orange doesn't run.

##### Steps to reproduce the behavior
Installing Orange with the latest installer
Run executable as Admin.
Orange is installed correctly. 
Orage doesn't run.

**Comment by ales-erjavec** [comment]
Can you please open the 'Orange Command Prompt' (search for it in the Win 10 search bar. At the prompt type `python -m Orange.canvas` and post the output.

**Comment by MrDavidGB** [comment]
Hello ales-erjavec, thanks for reply.

> Can you please open the 'Orange Command Prompt' (search for it in the Win 10 search bar. At the prompt type `python -m Orange.canvas` and post the output.

![Captura](https://user-images.githubusercontent.com/51217438/58758498-a018d200-84e1-11e9-82c7-ad5021628f52.JPG)

**Comment by ales-erjavec** [comment]
Can you also run
```
python -c "import numpy"
```
That import error actually hides import errors from numpy, so it is impossible to tell if the message is correct.

**Comment by janezd** [comment]
Closed because of inactivity.

**Comment by CrashLandonB** [comment]
I've been having this same issue, and I'm getting the same output from the `python -m Orange.canvas` command as the OP above.  Do I need to open a new issue?

**Comment by ajdapretnar** [comment]
Please open a new issue and describe the issue in as much details as possible, please.
