### ISSUE TITLE
ComboBox: filter variables by typing search query

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3848]
##### Orange version

3.21.dev

##### Expected behavior
Comboboxes limit the length of the variable list to display. The list becomes scrollable at a sensible length.

##### Actual behavior
Comboboxes with many variables open across the entire screen, making things very awkward.

##### Steps to reproduce the behavior
Datasets (HDI) - Scatter Plot (or any kind of widget with comboboxes).

**Comment by markotoplak** [comment]
For me, opening on the whole screen is not an issue. I like it, because I see more and I need to scroll less.

**Comment by janezd** [comment]
I'm with him.

**Comment by ajdapretnar** [comment]
Really? I hate it so much I want to punch my screen. I everyone likes it, then fine.

**Comment by ajdapretnar** [comment]
I asked the users and they say they would prefer filter at the top to look for a variable. I imagine something similar to what we have in Select Columns.

**Comment by janezd** [comment]
Combos already support filtering, by default. Just start typing.

As for limiting the number of items, we just need to set `QComboBox`'s `maxVisibleItems`, perhaps in `gui.comboBox`, so it applies everywhere.

**Comment by ajdapretnar** [comment]
That's not really filtering, it's more a search. What the users has in mind is seeing all the variables matching the search term.

**Comment by janezd** [comment]
@irgolic checks whether it's possible/easy to replace the combo's pop-up with a line edit + list view.

**Comment by irgolic** [comment]
It's possible but it'll take some time to implement a filtered comboBox, mostly due to how complex our current implementation of comboBox already is. I'll play around with it a bit more next week.

Limiting the number of variables displayed (as per the original issue) should be simpler, I'll open a PR with just that if it takes too long to figure out filtering.

**Comment by janezd** [comment]
Don't limit the number of variables. I guess we (mostly Marko and I :)) decided against it. Even (or especially) if we don't succeed with filtering.

**Comment by janezd** [comment]
`orangewidget.utils.combobox import ComboBoxSearch` implements this. To properly use it, we need to construct it via `gui.comboBox` (https://github.com/biolab/orange-widget-base/issues/26), or synchronize settings manually (see bug #4192).
