### ISSUE TITLE
Categorical feature not plotted

### ISSUE THREAD

**Issue by rizkidewanto** [biolab/orange3#3870]
##### Orange version

Latest Version Orange 3.21 Windows

##### Expected behavior
Categorical Variables are displayed on scatter plot list

##### Actual behavior
Categorical Variables are not displayed on scatter plot list

##### Steps to reproduce the behavior
1. Choose any dataset that contain categorical variables
2. Select Scatter Plot
3. Drag line from data to scatter plot
4. Open Scatter Plot
5. See list on axis x or axis y

**Comment by ajdapretnar** [comment]
This is not a bug. Categorical variables have been removed from Scatter Plot in #3434. Scatter Plot is is meant for displaying numeric variables. Please use Box Plot, Distributions or other visualizations that are designed for categorical variables.
