### ISSUE TITLE
CSV with semicolon separated data and comma as decimal separator

### ISSUE THREAD

**Issue by asmaier** [biolab/orange3#3875]
##### Orange version
3.21.0 git revision: 4a6f2c7

I tried to load a CSV file with the following data:

```
Datum;Temperatur (Celsius)
2019-06-12 09:54:17;28,7
2019-06-12 09:44:17;28,95
2019-06-12 09:34:17;29,08
2019-06-12 09:24:17;29,12
2019-06-12 09:14:17;29,07
2019-06-12 09:04:17;28,99
2019-06-12 08:54:17;28,86
2019-06-12 08:44:17;28,83
2019-06-12 08:34:17;28,73
2019-06-12 08:24:17;28,65
2019-06-12 08:14:17;28,62
2019-06-12 08:04:17;28,59
2019-06-12 07:54:17;28,53
```

##### Expected behavior
 I expected the first column to be of type datetime and the second column of type numeric.

##### Actual behavior
Orange detects the first column to be datetime as expected. But it detects the second column as text and there is no possibility to fix that. I can only select text or categorical. So it seems to me Orange doesn't allow to use commas as decimal separator in a semicolon separated CSV. 

It would be nice if Orange would be more flexible when importing CSV data. For example in Excel I can select which character to use as separator, which character to use as decimal separator and which character to use for quotes.

**Comment by ajdapretnar** [comment]
There is a CSV File Import widget in Prototypes add-on. It is on its way to the core Orange, but for now, you can use it from the add-on.

**Comment by asmaier** [comment]
Thank you. That was exactly what I needed.
