### ISSUE TITLE
Widget with histogram on top of each column

### ISSUE THREAD

**Issue by asmaier** [biolab/orange3#3882]
Recently RapidMiner introduced a feature called TurboPrep:

https://rapidminer.com/products/turbo-prep/

Most notably it introduces an interactive histogram on top of each column. This histogram can then be used to select data values. In addition they feature a quality bar showing missing values and other quality problem. 

There are many more features which are possible with this type of interactive visualization. But it quickly seems to become an industry standard, as it is also available in Google Cloud Data Prep solution:

https://cloud.google.com/dataprep/docs/html/Data-Grid-Panel_57344857

It would be nice, if Orange could offer widget with similar features. Is there any chance that we could see such an interactive data preparation widget in a future version of Orange?

**Comment by asmaier** [comment]
It seems this feature was first available in Data Wrangler developed at the Standford university: http://vis.stanford.edu/wrangler/
A research paper is available here: http://vis.stanford.edu/papers/wrangler

**Comment by ajdapretnar** [comment]
I check Data Wrangler and it is really cool. It almost seems like a proper continuation of Feature Constructor. If anybody feels competent to do it, I highly support it.

**Comment by janezd** [comment]
Issue moved to #4090.
