### ISSUE TITLE
Font issue on Debian

### ISSUE THREAD

**Issue by pprw** [biolab/orange3#3892]
##### Orange version : 3.19

After installing Orange3 (via anaconda) on debian sid, font are not well supported (see screenshot)

![Capture d’écran_2019-06-19_10-36-40](https://user-images.githubusercontent.com/5262986/59750042-78b25b00-927e-11e9-87f7-5a4ac90903fa.png)

**Comment by markotoplak** [comment]
@pprw, do you own a HiDPI display?

**Comment by janezd** [comment]
Closed due to inactivity.

**Comment by pprw** [comment]
> @pprw, do you own a HiDPI display?

no. 1920x1080

**Comment by janezd** [comment]
We discussed this at today's meeting. Nobody in the group can replicate this, but some people said that Orange sometimes "becomes ugly" and reinstallation (of Orange? of Qt?) fixes it. We are closing this issue but next time this happens to anybody we will debug instead of reinstalling.
