### ISSUE TITLE
Origin of distribution values

### ISSUE THREAD

**Issue by gugarosa** [biolab/orange3#3899]
Hello! Hope everything is alright!

Could you point out to me where did these values come from? If they come from a specific distribution or something like that.

`d = {("nemenyi", "0.05"): [0, 0, 1.959964, 2.343701, 2.569032, 2.727774,
                               2.849705, 2.94832, 3.030879, 3.101730, 3.163684,
                               3.218654, 3.268004, 3.312739, 3.353618, 3.39123,
                               3.426041, 3.458425, 3.488685, 3.517073,
3.543799]`

It is located under `computed_CD()` in `https://github.com/biolab/orange3/blob/master/Orange/evaluation/scoring.py`.

Thank you for attention,
Gustavo.

**Comment by janezd** [comment]
http://www.jmlr.org/papers/volume7/demsar06a/demsar06a.pdf
