### ISSUE TITLE
Problem with miniconda installer

### ISSUE THREAD

**Issue by danoz9** [biolab/orange3#3900]
##### Orange version
Orange3-3.21.0-Miniconda-x86_64.exe (64 bit)

##### Actual behavior
Program doesn't open after installing. The error is shown in the picture below.
pythonw.exe - Ordinal Not Found
the ordinal 242 could not be located in the dynamic link library C:\Program\Files\Orange\Library\bin\mkl_intel_thread.dll

##### Additional info (worksheets, data, screenshots, ...)
![image](https://user-images.githubusercontent.com/52142362/59984425-56994e00-966d-11e9-9e73-89a63d482d7c.png)

**Comment by ajdapretnar** [comment]
Perhaps something our resident Windows expert will know @thocevar.

**Comment by thocevar** [comment]
I've just tried with the latest installer Orange3-3.22.0-Miniconda-x86_64.exe on a clean Windows 10 machine and it worked without errors.

Could https://conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#numpy-mkl-library-load-failed be the cause? See if setting the environment variable CONDA_DLL_SEARCH_MODIFICATION_ENABLE to 1 helps.

**Comment by ajdapretnar** [comment]
Closed due to inactivity.
