### ISSUE TITLE
Widgets are not repainted if closed on PyQt5==5.12.3

### ISSUE THREAD

**Issue by robertcv** [biolab/orange3#3906]
##### Orange version
3.22.0.dev0+660e8a6
##### Expected behavior
Widgets are normal when reopened.
##### Actual behavior
Widgets get black after reopening them. They get back to normal when resized.
![Screenshot from 2019-06-27 13-25-26](https://user-images.githubusercontent.com/13180057/60263178-4e951480-98e0-11e9-88db-d593730e60ce.png)
##### Steps to reproduce the behavior
Use PyQt5==5.12.3. Open, close and reopen any widget.
##### Additional info (worksheets, data, screenshots, ...)
I am using Ubuntu 18.04 and pip to install Python packages.
This doesn't happen with PyQt5==5.12.2 so it's probably an PyQt5 issue but nevertheless, we should be aware of that.

**Comment by markotoplak** [comment]
Something similar happens to me on PyQt 5.12.3. 5.12.2 is fine.

![5 12 3](https://user-images.githubusercontent.com/552182/60343636-c3398300-99b4-11e9-983e-63d406ef4424.png)

**Comment by ajdapretnar** [comment]
Yours, Marko, is waaaaay cooler. :)

**Comment by ajdapretnar** [comment]
Can confirm on OSX, too. Mine is just a dull gray.

<img width="897" alt="Screen Shot 2019-06-28 at 15 10 21" src="https://user-images.githubusercontent.com/12524972/60344482-ef560380-99b6-11e9-82ab-64bdce3000da.png">

**Comment by markotoplak** [comment]
It happens only if I close/reopen the window. If I minimize/unminimize it, it is fine.

**Comment by markotoplak** [comment]
I tried with PyQt=5.13, and everything seems fine there.

**Comment by janezd** [comment]
Can we close this?

**Comment by markotoplak** [comment]
I think we should not close it. We need to investigate it because conda will eventually move to Qt 5.12 
(this one is LTS). Furthermore, some changes from 5.12.3 could be ported to 5.13 and then we really have a problem.

**Comment by markotoplak** [comment]
For me, the problem only appears if I close the window from my window manager (alt-shift-C in dwm or clicking the window's close button). If I close it with Esc it opens fine.

**Comment by markotoplak** [comment]
This bug seems to have been fixed upstream: https://bugreports.qt.io/browse/QTBUG-76509. The new release of Qt is planned for September 5 and PyQt will likely follow shortly afterwards.

Let's wait for updated packages and then we can close it.

**Comment by markotoplak** [comment]
Fixed in PyQt's packages that now include Qt 5.12.5: https://www.riverbankcomputing.com/pipermail/pyqt/2019-September/042178.html
