### ISSUE TITLE
Unsure how to set metas

### ISSUE THREAD

**Issue by Guillaumes33** [biolab/orange3#3908]
Hello,

I'm trying to create a data table from scratch, and I can't figure out how to add meta attributes to a table. This is what I have as a sample. I just want to able to replace the ? with a meta value.
![image](https://user-images.githubusercontent.com/50418145/60281252-2f49b780-98df-11e9-8bea-6b049c0131c2.png)

**Comment by janezd** [comment]
Methods that modify the table length are deprecated and will be removed in the future (#3501). I have to check why calling `append` did not give a deprecation warning. And I see that documentation still doesn't mention this.

Do it like this:

```
from Orange.data import Table, Domain, ContinuousVariable
import numpy as np

dom = Domain([ContinuousVariable("y")], metas=[ContinuousVariable("m")])
X = np.random.random((5, 1))
m = np.random.random((5, 1))
tab = Table(dom, X, None, metas=m)
```

**Comment by Guillaumes33** [comment]
Thanks. Is this a good way to make a table from an existing one? Anything else that should be deprecated?
![image](https://user-images.githubusercontent.com/50418145/60667941-535c4a00-9e45-11e9-961f-69a0574825e4.png)

**Comment by Guillaumes33** [comment]
I can't figure out how to set non-float metas. I keep getting this error when trying to set metas or class_vars. What's going wrong? @janezd 
![image](https://user-images.githubusercontent.com/50418145/60683984-ac43d680-9e75-11e9-9656-65b0faeed11d.png)

**Comment by Guillaumes33** [comment]
Using StringVariable when setting the metas works. I'd recommend updating the docs to show how to build a table from scratch. It's currently not at all obvious.
