### ISSUE TITLE
Inconsistency in style of auto-apply checkbox

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/orange3#3910]
In #3844 @ajdapretnar started the conversation about the style of auto-commit buttons:

*I think considering this PR is dealing with apply, it would be nice if it fixed the mismatching buttons in Color and Concatenate, which are unlike those of other widgets.*

@janezd comment on this was:

*This is one of supported generic options. It is more obvious than the usual (checkbox without a label) but we seldom use it because most widgets are not wide enough. I can of course remove it (the label is set by an explicit argument to gui.auto_commit, so I just have to remove the extra argument), but I'm undecided about whether the extra explanatory label indeed bothers me. @markotoplak, @irgolic, what are your opinions?*

So I am opening this issue for further discussion.

**Comment by janezd** [comment]
Decision: we allow different designs, but check guis of all widgets.

**Comment by janezd** [comment]
Fixed via #4024.
