### ISSUE TITLE
Unable to install add-ons on Windows 10

### ISSUE THREAD

**Issue by iva-c** [biolab/orange3#3912]
##### Orange version
3.22.0 and 3.21.0

##### Expected behavior
Instaling add-ons via Options on Windows 10

##### Actual behavior
Orange is unable to retrieve pacage list

##### Additional info (worksheets, data, screenshots, ...)
![add-ons error](https://user-images.githubusercontent.com/48483052/60333981-bc9e1200-999a-11e9-99d9-1225afa7f019.PNG)

**Comment by acopar** [comment]
Thanks for reporting this. The issue is now resolved.
