### ISSUE TITLE
Regarding the number of iterations functionality in Orange

### ISSUE THREAD

**Issue by GuestA16** [biolab/orange3#3924]
I have a query regarding the number of iterations functionality in Orange, which is available with several widgets.

For instance, in the neural networks widget, the maximum number of iterations is currently 10000. However, I often come across problems where it takes more than 10000 iterations for a problem to converge.

Is there a way to increase the number of iterations to for instance 1000000?

**Comment by ajdapretnar** [comment]
You can change the number here:
https://github.com/biolab/orange3/blob/master/Orange/widgets/model/owneuralnetwork.py#L138

We do not wish to change the maximum number in Orange, but you can do it locally.

**Comment by ajdapretnar** [comment]
Sorry, I though we explicitly decided against increasing MaxIter in NN, but this was not so.
https://github.com/biolab/orange3/issues/2935

Still, for this to work, we would have to enable progress bar and interruption of the process.

**Comment by GuestA16** [comment]
Thanks for your response ajdapretnar; much appreciated. 

My knowledge of programming is almost non-existential, but will try to change the code locally as suggested. Could you kindly tell me where can I find this file? Will I need to do any other changes to the code locally or just changing the number works?

**Comment by GuestA16** [comment]
Thanks for your response ajdapretnar; much appreciated.

My knowledge of programming is almost non-existent, but will try to change the code locally as suggested.

Could you kindly tell me where can I find this file? Will I need to do any other changes to the code locally or just changing the number will work?

Thanks and kind regards....



On 5 Jul 2019, at 10:23, Ajda <notifications@github.com<mailto:notifications@github.com>> wrote:


You can change the number here:
https://github.com/biolab/orange3/blob/master/Orange/widgets/model/owneuralnetwork.py#L138

We do not wish to change the maximum number in Orange, but you can do it locally.

**Comment by janezd** [comment]
We decided to increase this.
