### ISSUE TITLE
Rank Widget - Select best ranked attributes

### ISSUE THREAD

**Issue by leeherman99** [biolab/orange3#3934]
##### Orange version

3.22

##### Change request
When one species the number of best ranked attributes, the counter stops at 100. It would be nice if the counter could go higher (say, 999).

Also, a numerical threshold for the importance would also be convenient.

**Comment by leeherman99** [comment]
Also, a numerical threshold for the importance would also be convenient.

**Comment by janezd** [comment]
Isn't 100 already a lot? You'd like to select 999 out of ... how many? But I see on strong argument against, so #3937 increases it to 999.

I don't like the idea of thresholds, though. I think these number don't have any absolute, interpretable meaning, and the user cannot set a number without knowing what it means - in absolute terms. What does it mean to have a gini decrease of 0.15?
