### ISSUE TITLE
Orange and Miniconda 32bit installer unavailable

### ISSUE THREAD

**Issue by deepanshumaan** [biolab/orange3#3939]
##### Orange version
3.22

##### Actual behavior
Orange and Miniconda 32bit installer unavailable.
When trying to install with the setup provided on orange website, error occurs Miniconda 64 bit installer.

##### Steps to reproduce the behavior
Try installing Orange setup which includes Miniconda 64 bit installer on a 32 bit Windows.

**Comment by ales-erjavec** [comment]
There is no 32-bit Miniconda installer because conda-forge [dropped 32-bit support](https://github.com/conda-forge/staged-recipes/issues/5640).
