### ISSUE TITLE
Pivot Table subcategory unavailable

### ISSUE THREAD

**Issue by deepanshumaan** [biolab/orange3#3940]
##### Orange version
3.22

##### Expected behavior
I wanted to be able to view  subcategory wise frequency of my data. For example, I have a data set which has multiple columns say city, date, treatment, age :
Further my columns have multiple categories , like my column treatment contains- dialysis, surgery, consultancy etc.
I want to be able to view my data **per city**, **each day**, for **different treatments** and then the total treatments of all days. The option to view my data category wise is unavailable.

##### Actual behavior
 The option to view my data subcategory wise with respect to each day is unavailable , it only consists of three option rows, columns and values.

**Comment by ajdapretnar** [comment]
I don't think this is something we want to implement. This is not like Pivot Table in Excel - for such purpose Excel would be the appropriate tool. What do you think, @janezd?

**Comment by janezd** [comment]
I thought so myself, too, but I wanted to let somebody else give her opinion first.

It's nice that Orange has a pivot widget, but perfecting it to support everything one can wish, would require too much effort; there are many other, more urgent things to take care of. We could leave the issue open, but I don't believe it would ever surface to the highest priority.

**Comment by ajdapretnar** [comment]
Just to clarify a bit further - Orange _could_ do a lot of things, but probably not as well as the tools specifically designed to do them. For example Excel - it is a great piece of software for managing your spreadsheets. Orange is not and does not aspire to be one. We think our strength is in the simplicity of predictive modeling and other ML tasks. I think it makes sense keeping it that way.
