### ISSUE TITLE
[ENH] request: save workflow as Python Notebook and HDF5

### ISSUE THREAD

**Issue by farhi** [biolab/orange3#3941]
This is a feature request (not a bug, but rather en Enhancement):

It would be nice to be able to export an Orange3 workflow as:
- a Python/Jupyter Notebook: the Orange3 workflow file is already XML based with pickles inside.
- an HDF5 file: a widget could export its input data (output from other widgets) into an HDF5 file.

**Comment by ajdapretnar** [comment]
Ad 1: See #1341

Ad 2: Please see #945 and  #3701.

Closing as a duplicate.
