### ISSUE TITLE
New changes delete some features

### ISSUE THREAD

**Issue by borondics** [biolab/orange3#3942]
#2845 and #2843 were two small changes I made, which I think were useful both visually and practically, but they disappeared from the current **master** branch. Is this due to the Canvas / Base widgets separation?

Could we put them back?

**Comment by ales-erjavec** [comment]
Sorry about that. The relevant changes have been transplanted to https://github.com/biolab/orange-canvas-core

**Comment by borondics** [comment]
Thanks!!!
