### ISSUE TITLE
Scatter Plot axes labels not updated automatically

### ISSUE THREAD

**Issue by Guillaumes33** [biolab/orange3#3944]
##### Orange version

3.22.0

##### Expected behavior
Scatter Plot should update axes labels whenever it updates its data.

##### Actual behavior
The axes labels only change when being connected to a new widget. Changing the column names for the input table is not reflected in Scatter Plot.

**Comment by ajdapretnar** [comment]
Could you please provide a screenshot and a minimum example?

**Comment by Guillaumes33** [comment]
![image](https://user-images.githubusercontent.com/50418145/61954700-f828fd80-af93-11e9-9c5c-f6bf940238c8.png)
When I change the names of the ContinuousVariables, it doesn't always update in Scatter Plot. Trying to reproduce this, it sometimes works and sometimes doesn't. I think the labels are only changed if the data is also changed.
![image](https://user-images.githubusercontent.com/50418145/61955051-c9f7ed80-af94-11e9-8c93-7a45817e702e.png)
Above, I've changed "A" to "NEW" but it doesn't change in the graph.
![image](https://user-images.githubusercontent.com/50418145/61955093-dd0abd80-af94-11e9-9670-45349dff0ad0.png)
Here I change the data, and the axes labels are updated.

**Comment by ajdapretnar** [comment]
Yeah, I can confirm. The domain itself is updated (variables are renamed), but the plot doesn't reflect it.
