### ISSUE TITLE
Bug: Test and Score Evaluation results sort alphabetically

### ISSUE THREAD

**Issue by Pigankle** [biolab/orange3#3947]
##### Orange version

3.22

##### Expected behavior
In the Test&Score module window, there are five columns by default: Model, MSE, RMSE, MAE & R2.  All but the first column contains numeric values.  It is possible to click on any of the column headers to sort the table by that column.  Expected behavior:  sorting by the numeric columns will use numeric sort behavior.

##### Actual behavior
Clicking on a numeric column header sorts with alphabetic/lexicographic behavior, so a possible "sorted" list might look like:
16992
178
355
4536

##### Steps to reproduce the behavior
1. Associate multiple model modules with a Test and Score module
2. Once the Test and Score module results window
3. Click on a column header to sort by a numeric column.

In the attached screenshot, the table is sorted by column 3, RMSE, alphabetically ascending:
12630
1389
20510
2194779950371
37742
<img width="823" alt="screenshot_200" src="https://user-images.githubusercontent.com/24887253/62026009-9c769400-b18e-11e9-87b5-fae996ac35af.png">

For sorting to be useful, these values should be sorted:

1389
12630
20510
37742
2194779950371

**Comment by janezd** [comment]
Thanks! Funny that nobody noticed this before. Fixed in #3951.

@ajdapretnar, other widgets (such as GEO Data Sets) can be fixed in a similar way, but not by reusing the code from #3951. Test & Score is specific because we want to have strings and Nones (both representing errors) always at the bottom of the table. Most other widgets should expect just numbers and empty cells, which can be treated as `-np.inf`.

**Comment by ajdapretnar** [comment]
> @ajdapretnar, other widgets (such as GEO Data Sets) can be fixed in a similar way, but not by reusing the code from #3595 

Gotcha! 👌

**Comment by ales-erjavec** [comment]
Or maybe just undo b4196790548a57ff4de9e52c2a7f87a4b9c0ad4f and go on from there.

```diff
diff --git a/Orange/widgets/evaluate/owtestlearners.py b/Orange/widgets/evaluate/owtestlearners.py
index 139f2cb9c..9a2d77de9 100644
--- a/Orange/widgets/evaluate/owtestlearners.py
+++ b/Orange/widgets/evaluate/owtestlearners.py
@@ -533,7 +533,7 @@ class OWTestLearners(OWWidget):
                 for stat, scorer in zip(stats, self.scorers):
                     item = QStandardItem()
                     if stat.success:
-                        item.setText("{:.3f}".format(stat.value[0]))
+                        item.setData(float(stat.value[0]), Qt.DisplayRole)
                     else:
                         item.setToolTip(str(stat.exception))
                         if scorer.name in self.score_table.shown_scores:
diff --git a/Orange/widgets/evaluate/utils.py b/Orange/widgets/evaluate/utils.py
index ebe060327..6caa6811b 100644
--- a/Orange/widgets/evaluate/utils.py
+++ b/Orange/widgets/evaluate/utils.py
@@ -109,6 +109,12 @@ class ScoreTable(OWComponent, QObject):
             size = super().sizeHint(*args)
             return QSize(size.width(), size.height() + 6)
 
+        def displayText(self, value, locale):
+            if isinstance(value, float):
+                return "{:.3f}".format(value)
+            else:
+                return super().displayText(value, locale)
+
     def __init__(self, master):
         QObject.__init__(self)
         OWComponent.__init__(self, master)
```
