### ISSUE TITLE
Large values (1e22) break Zoom tool in Scatterplot

### ISSUE THREAD

**Issue by hugobuddel** [biolab/orange3#395]
Data with large values break the zoom tool in the scatterplot widget. Values around 1e12 work fine, but values around 1e22 cause problems. The break-point seems to be around 1e16.

The zoom tool does not show the yellow rectangle when dragging with the zoom tool (hourglass) selected. Releasing the mouse jumps to a seemingly arbitrary range in the parameter space. Zooming with the scroll wheel still works fine. The data shows up nicely in the Datatable viewer widget.

The following file can be used to reproduce the error. It seems that github replaces the tab-characters by spaces.
<pre>
small1	small2	largeok	largebad	iris
c	c	c	c	d
				class
5.1	3.5	1.4e12	1.2e22	Iris-setosa
4.9	3.0	1.4e12	1.2e22	Iris-setosa
4.7	3.2	1.2e12	1.2e22	Iris-setosa
5.0	3.3	2.4e13	2.2e23	Iris-setosa
7.0	3.2	4.7e12	1.2e22	Iris-versicolor
6.4	3.2	4.5e13	2.2e23	Iris-versicolor
6.9	3.1	4.9e13	2.2e23	Iris-versicolor
5.5	2.3	4.0e13	2.2e23	Iris-versicolor
</pre>

**Comment by ajdapretnar** [comment]
@hugobuddel For me the issue no longer persists. Can I close it?

**Comment by hugobuddel** [comment]
@ajdapretnar I haven't used Orange in a couple of months (although I'd like to get back to it), so I'll take your word for it on whether the problem is fixed. Feel free to close the issue.

**Comment by ajdapretnar** [comment]
I've used the data set you provided and I didn't encounter any problems. I'm closing the issue for now, if any problem occurs, you can open a new one. :smile:
Thank you for reporting the issue!
