### ISSUE TITLE
Error reporting reports version of orange-widget-base

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#3953]
Error report on the Orange development version does in fact (contrary to what I have been told) send error reports to the server. Good.

Currently, it reports the of orange-widget-base (4.0.1) as the version. Should it?

Now, nothing is being lost. We can still get the version of the Orange3 package from submitted "Installed Packages". For Sentry view it would be perhaps nicer to report Orange3 version.

**Comment by janezd** [comment]
@ales-erjavec, @markotoplak, @ajdapretnar: https://github.com/biolab/orange-widget-base/pull/8 fixed this, so it can be closed?
