### ISSUE TITLE
Orange: update within GUI

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3965]
A while ago we have discuss having a nice way to update Orange. I think the separation of canvas and core would allow this to be implemented now.

The idea is the user can update Orange from within GUI without having to download the entire package yet again. Just like we do for the add-ons.

Things to keep in mind:
- Orange checks for updates, prompts the user to update Orange. A click on the Update button should start the update. A restart is required. Pressing restart actually restarts Orange.
- Updating Orange should be logged somewhere to keep track of existing users. Perhaps as a script working with our KPI Google sheet.
- Updating canvas and widget base? Probably orange3 would depend on higher versions of these two packages and would update them itself?

**Comment by janezd** [comment]
This is related to canvas, not just Orange. @ales-erjavec will consider whether it is possible to implement lighter updates.
