### ISSUE TITLE
Add chi**2 to boxplot when multiple categorical features are selected

### ISSUE THREAD

**Issue by djrscally** [biolab/orange3#3971]
**Is your feature request related to a problem? Please describe.**
Nope not really, just an enhancement.

**Describe the solution you'd like**
The box plot widget outputs student's t-test or ANOVA statistics, including p-values, when selecting a categorical and numerical feature. I really like that; eyeballing is great and all but having the test stats so easily available really enhances the experience. In the same way that that's useful when comparing group means, I think that a Chi**2 statistic would be useful when comparing two categorical features in the same widget. For example using the [census](https://archive.ics.uci.edu/ml/datasets/adult) dataset, we can compare Income (the target) to the "workclass" feature and get this output in the boxplot widget:

![image](https://user-images.githubusercontent.com/4592235/62765244-997d7c80-ba87-11e9-947c-12c95718dbf1.png)

We can calculate the chi**2 statistic and p-value for these 2 features with scipy.stats.chi2_contingency:

```Python
import scipy.stats as ss
import pandas as pd

# instantiate the census data into a dataframe called df

ss.chi2_contingency(pd.crosstab(df.workclass, df.income).values)
```
Output is chi2 statistic: 1045.7085997281692 and p-value: 2.026505431120716e-220

I think it'd be nice to have those printed on the bottom of the box plot widget when comparing categorical features.

**Describe alternatives you've considered**
Calculating it isn't especially arduous so that alternative exists. This is definitely a _nice to have_.

**Additional context**
None necessary I think.

**Comment by ajdapretnar** [comment]
Best described enhancement I've seen in a while! 🌟

Box Plot already computes Chi**2 in Order by relevance, so it should be easy reporting it below the visualization as well. I agree this would be a good feature!

**Comment by thocevar** [comment]
Chi^2 that is used to order the variables by relevance might be incorrect - the number of degrees of freedom seems off. To match the output of `chi2_contingency` it would need to be `sum(observed.shape)-2`. @janezd 

https://github.com/biolab/orange3/blob/42f88945cfd90e7bdf4fcfa974687ce7b4ac5e99/Orange/widgets/visualize/owboxplot.py#L360

**Comment by janezd** [comment]
> Chi^2 that is used to order the variables by relevance might be incorrect - the number of degrees of freedom seems off. To match the output of `chi2_contingency` it would need to be `sum(observed.shape)-2`.

Maybe `sum(observed.shape) - 1`? This would assume that the sample size is fixed and each data instance "chooses" a cell in the contingency table independently. So we are free to choose `sum(observed.shape) - 1` counts.

We could also use `np.prod(observed.shape - 1)`? This assumes that every data instance chooses the value for each variable independently, but the marginal distributions are fixed.

The current formula may assumes that the marginal distribution of `self.attribute` is fixed (The comment says: `# Chi-square with the given distribution into groups`), but then we should have `len(self.attribute.values) * (n_groups - 1)` degrees of freedom, I think.

**Comment by janezd** [comment]
Oops, sorry, I got it: you're talking about `ddof`, not `dof`. Your formula is correct - for fixed marginal distributions.

**Comment by djrscally** [comment]
@thocevar @janezd Thanks for working on this!
