### ISSUE TITLE
Specificity is wrong

### ISSUE THREAD

**Issue by gengyabc** [biolab/orange3#3973]
**Describe the bug**
In the calibration plot widget, specificity definition is wrong
![image](https://user-images.githubusercontent.com/12781437/63067764-15be0700-bf43-11e9-896b-a3586b8e99b4.png)

**To Reproduce**
1. Go to cavans
2. open calibration plot widget
3. in 'Merics' scroll to 'Sensitivity and specificity'

**Orange version:**
3.23

**Expected behavior**
TN/N

**Operating system:**
Mac

**Comment by PrimozGodec** [comment]
Thank you for submitting the issue, you are right. The description is wrong. I already created the pull request that fixes this issue. The formula used for calculation is correct already.
