### ISSUE TITLE
Venn Diagram should work on features

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3#3991]
Current Venn Diagram widget operates on data instances and shows overlap in data instances for the input data sets. Here we propose to extend this functionality to features. In Orange, several widgets support feature selection and preprocessing, and would be exciting to analyze the similarities and differences of such procedure.

Redesign Venn Diagram according to the proposed sketch. The default selections are marked.

![ven-diagram-redesigned](https://user-images.githubusercontent.com/726604/64009782-c8cc5a00-cb18-11e9-9efa-aa73ac79d1b4.png)

* When "Rows", the domain of the data sets should match entirely, in features, classes, and meta-features. If it does not, then display error "Input data domains do not match."
* When "Columns", the set of instances should be equal (sets of instance IDs are the same). If not, error "Data sets do not contain the same instances."
* "Use identifier" shows a list of string-typed meta-features with the same name present in all input data sets. If there is no such feature, "Use identifier" is disabled, "Use instance equality" is checked and the list box is empty.
* If "Rows", the output of the widget are rows that correspond to instances selected in the Venn diagram.
* When comparing columns, use column identifier (not names).

**Comment by ajdapretnar** [comment]
I would flip the order of Elements box. Rows seems to be (and should be) the default, hence I'd have it listed first. Then Columns.

**Comment by janezd** [comment]
Implemented via #4006.
