### ISSUE TITLE
With CSV File Import I cannot select feature and target variable 

### ISSUE THREAD

**Issue by asmaier** [biolab/orange3#3998]
**Describe the bug**
Using the CSV File Import widget as input for a Model like Linear Regression doesn't work. It says
"Data has no target variable". 

**To Reproduce**
1. Import some CSV with CSV File Import
2. Connect the CSV with Linear Regression widget

**Orange version:**
3.22

**Expected behavior**
It should be possible to mark a column as target variable, so that widgets, which need a target variable do work. 

**Operating system:**
OSX 10.14.6

**Comment by ajdapretnar** [comment]
One can always use Select Columns to set the target variable. I would not describe this as a bug.

Also, this should probably be solved also with https://github.com/biolab/orange3/issues/3997.

**Comment by asmaier** [comment]
Ok, thanks for the workaround with "Select Columns" .

**Comment by MAI0881** [comment]
> One can always use Select Columns to set the target variable. I would not describe this as a bug.
> 
> Also, this should probably be solved also with #3997.

thanks
