### ISSUE TITLE
"conda" command exited with 1. Cannot continue. Orange installation

### ISSUE THREAD

**Issue by wfrsilva** [biolab/orange3#4013]
Hello people
I tried two versions:
Orange3-3.22.0-Miniconda-x86_64.exe
Orange3-3.21.0-Miniconda-x86_64.exe

But both made the same error.

Installing packages (this might take a while)
Executing: cmd.exe /c install.bat "C:\Users\Avell\AppData\Local\Orange" "C:\Users\Avell\Anaconda3\Scripts\conda.exe"
"conda" command exited with 1. Cannot continue.

Windows 10 64 bits.
I Tried too :
conda install orange3
12h and no finish the installation

pip install orange3 - install but when I run, crash because miss DLLs

The complete script:
Creating an new conda env in "C:\Users\Avell\AppData\Local\Orange"
Output folder: C:\Users\Avell\AppData\Local\Temp\nst8738.tmp\Orange-installer-data\conda-pkgs
Extract: anyqt-0.0.10-py36_0.tar.bz2
Extract: asn1crypto-0.24.0-py36_0.tar.bz2
Extract: blas-1.0-mkl.tar.bz2
Extract: bottleneck-1.2.1-py36h452e1ab_1.tar.bz2
Extract: ca-certificates-2019.5.15-0.tar.bz2
Extract: certifi-2019.6.16-py36_0.tar.bz2
Extract: cffi-1.12.3-py36h7a1dbc1_0.tar.bz2
Extract: chardet-3.0.4-py36_1.tar.bz2
Extract: conda-spec.txt
Extract: cryptography-2.7-py36h7a1dbc1_0.tar.bz2
Extract: cycler-0.10.0-py36h009560c_0.tar.bz2
Extract: decorator-4.4.0-py36_1.tar.bz2
Extract: docutils-0.14-py36h6012d8f_0.tar.bz2
Extract: entrypoints-0.3-py36_0.tar.bz2
Extract: freetype-2.9.1-ha9979f8_1.tar.bz2
Extract: icc_rt-2019.0.0-h0cc432a_1.tar.bz2
Extract: icu-58.2-ha66f8fd_1.tar.bz2
Extract: idna-2.8-py36_0.tar.bz2
Extract: install.bat
Extract: intel-openmp-2019.4-245.tar.bz2
Extract: joblib-0.13.2-py36_0.tar.bz2
Extract: jpeg-9b-hb83a4c4_2.tar.bz2
Extract: keyring-18.0.0-py36_0.tar.bz2
Extract: keyrings.alt-3.1.1-py36_0.tar.bz2
Extract: kiwisolver-1.1.0-py36ha925a31_0.tar.bz2
Extract: libpng-1.6.37-h2a8f88b_0.tar.bz2
Extract: llvmlite-0.29.0-py36ha925a31_0.tar.bz2
Extract: matplotlib-3.1.0-py36hc8f65d3_0.tar.bz2
Extract: mkl-2019.4-245.tar.bz2
Extract: mkl-service-2.0.2-py36he774522_0.tar.bz2
Extract: mkl_fft-1.0.12-py36h14836fe_0.tar.bz2
Extract: mkl_random-1.0.2-py36h343c172_0.tar.bz2
Extract: networkx-2.3-py_0.tar.bz2
Extract: numba-0.44.1-py36hf9181ef_0.tar.bz2
Extract: numpy-1.16.4-py36h19fb1c0_0.tar.bz2
Extract: numpy-base-1.16.4-py36hc3f5095_0.tar.bz2
Extract: openssl-1.1.1c-he774522_1.tar.bz2
Extract: opentsne-0.3.8-py36hc8d92b1_1.tar.bz2
Extract: orange3-3.22.0-py36h6538335_0.tar.bz2
Extract: pandas-0.24.2-py36ha925a31_0.tar.bz2
Extract: pip-19.1.1-py36_0.tar.bz2
Extract: pycparser-2.19-py36_0.tar.bz2
Extract: pynndescent-0.3.0-py_0.tar.bz2
Extract: pyopenssl-19.0.0-py36_0.tar.bz2
Extract: pyparsing-2.4.0-py_0.tar.bz2
Extract: pyqt-5.9.2-py36h6538335_2.tar.bz2
Extract: pyqtgraph-0.10.0-py36h28b3542_3.tar.bz2
Extract: pysocks-1.7.0-py36_0.tar.bz2
Extract: python-3.6.8-h9f7ef89_7.tar.bz2
Extract: python-dateutil-2.8.0-py36_0.tar.bz2
Extract: python-louvain-0.13-py_0.tar.bz2
Extract: pytz-2019.1-py_0.tar.bz2
Extract: pywin32-223-py36hfa6e2cd_1.tar.bz2
Extract: qt-5.9.7-vc14h73c81de_0.tar.bz2
Extract: requests-2.22.0-py36_0.tar.bz2
Extract: scikit-learn-0.21.2-py36h6288b17_0.tar.bz2
Extract: scipy-1.2.1-py36h29ff71c_0.tar.bz2
Extract: serverfiles-0.3.0-py36_0.tar.bz2
Extract: setuptools-41.0.1-py36_0.tar.bz2
Extract: sip-4.19.8-py36h6538335_0.tar.bz2
Extract: six-1.12.0-py36_0.tar.bz2
Extract: sqlite-3.28.0-he774522_0.tar.bz2
Extract: tornado-6.0.2-py36he774522_0.tar.bz2
Extract: urllib3-1.24.2-py36_0.tar.bz2
Extract: vc-14.1-h0510ff6_4.tar.bz2
Extract: vs2015_runtime-14.15.26706-h3a45250_4.tar.bz2
Extract: wheel-0.33.4-py36_0.tar.bz2
Extract: win_inet_pton-1.1.0-py36_0.tar.bz2
Extract: wincertstore-0.2-py36h7fe50ca_0.tar.bz2
Extract: xlrd-1.2.0-py36_0.tar.bz2
Extract: xlsxwriter-1.1.8-py_0.tar.bz2
Extract: zlib-1.2.11-h62dcd97_3.tar.bz2
Output folder: C:\Users\Avell\AppData\Local\Temp\nst8738.tmp\Orange-installer-data\conda-pkgs
Installing packages (this might take a while)
Executing: cmd.exe /c install.bat "C:\Users\Avell\AppData\Local\Orange" "C:\Users\Avell\Anaconda3\Scripts\conda.exe"
"conda" command exited with 1. Cannot continue.

**Comment by janezd** [comment]
Did you have Miniconda installed before installing Orange? If so which version?

Can you please run
```
C:\Users\Avell\Anaconda3\Scripts\conda.exe info
```

Can you also try running
```
<same prefix as before>\conda clean --all
```
and then rerun the Orange installer?

**Comment by wfrsilva** [comment]
> Did you have Miniconda installed before installing Orange? If so which version?
> 
> Can you please run
> 
> ```
> C:\Users\Avell\Anaconda3\Scripts\conda.exe info
> ```
> 
> Can you also try running
> 
> ```
> <same prefix as before>\conda clean --all
> ```
> 
> and then rerun the Orange installer?

C:\Users\Avell>C:\Users\Avell\Anaconda3\Scripts\conda.exe info

     active environment : None
       user config file : C:\Users\Avell\.condarc
 populated config files : C:\Users\Avell\.condarc
          conda version : 4.7.11
    conda-build version : 3.18.9
         python version : 3.6.9.final.0
       virtual packages : __cuda=10.0
       base environment : C:\Users\Avell\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Avell\Anaconda3\pkgs
                          C:\Users\Avell\.conda\pkgs
                          C:\Users\Avell\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Avell\Anaconda3\envs
                          C:\Users\Avell\.conda\envs
                          C:\Users\Avell\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.11 requests/2.22.0 CPython/3.6.9 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False


C:\Users\Avell>

**Comment by ajdapretnar** [comment]
And did you run 
`C:\Users\Avell\Anaconda3\Scripts\conda clean --all`
And re-ran Orange installer?
Did it help?

**Comment by janezd** [comment]
Cannot replicate, closed due to inactivity.

**Comment by jeremy3298** [comment]
I am also having this issue: 
<img width="392" alt="image" src="https://github.com/biolab/orange3/assets/36802989/606074bb-1e15-4d6f-b915-b97be8dfc69e">
