### ISSUE TITLE
Error in certain add-ons display

### ISSUE THREAD

**Issue by Hrovatin** [biolab/orange3#4015]
**Describe the bug**
Error (in parsing) reported when selecting certain add-ons.
![Screenshot from 2019-09-09 13-41-20](https://user-images.githubusercontent.com/47607471/64527939-87516100-d307-11e9-850e-49a445fbfe7c.png)
![Screenshot from 2019-09-09 13-35-46](https://user-images.githubusercontent.com/47607471/64527867-5c670d00-d307-11e9-9e1a-6b017b7ba51a.png)

**Orange version:**
3.23

**Operating system:**
Various

**Comment by janezd** [comment]
Will be fixed via #4025?

**Comment by ajdapretnar** [comment]
I would refrain from having add-on related issues here. I suggest we open them in their corresponding repositories.
