### ISSUE TITLE
Issues loading data from Excel in scOrange on a Mac OS

### ISSUE THREAD

**Issue by YuriB85** [biolab/orange3#4017]
I am OSX 10.14.6 user and I am having difficulties opening Excel files in scOrange (v.  1.3.0). 

I have tried multiple Excel files and even following the YouTube video "Single Cell Orange 03: Loading Single Cell Data from Tab-Delimited Files" I downloaded the file Dicty.xlsx from the source linked in YouTube, but it does not open. On the other hand, It works perfectly on a Win10 PC.

**Comment by markotoplak** [comment]
Yuri, what is your system's locale or language? Might be something connected to encodings or decimal separators.

**Comment by YuriB85** [comment]
My system's language is US English, I am based in Singapore. I've now tried with 2 macbooks and 1 iMac, each has a different macOS version,  I can never open excel files. On the other hand, I can open the files if I save them in .csv.

**Comment by VesnaT** [comment]
I'm closing this due to https://github.com/biolab/orange3-single-cell/issues/365.
