### ISSUE TITLE
Data Table: showing text files is slow

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#4019]
**Describe the bug**
When Data Table is fed longer text files, showing the data table gets really slow.

**To Reproduce**
1. Load any corpus, say *bookexcerpts*.
2. Connect a Data Table and open it.

**Orange version:**
3.23.dev

**Expected behavior**
Data Table shows data immediately / on-the-fly.

**Operating system:**
OSX

**Comment by janezd** [comment]
Investigate whether eliding strings helps.

**Comment by janezd** [comment]
Closed for now. @ajdapretnar will reopen when/if she manages to replicate.
