### ISSUE TITLE
Unresponsive Test and Score

### ISSUE THREAD

**Issue by robertcv** [biolab/orange3#4028]
**Describe the bug**
Test and Score widget doesn't respond to change in input data/learners during computation. Also if I try to delete the widget it takes some time to truly stop and delete it.

**To Reproduce**
Input any large data and computational heavy model. The computation of results doesn't stop if data or learners change (are removed). 

**Orange version:**
3.24.0.dev

**Expected behavior**
If I use a computational heavy model in Test and Score and it takes to long to compute I would expect to stop it by removing the connectin to that model.

**Operating system:**
Ubuntu 18.04

**Comment by janezd** [comment]
Check the widget: it must stop on fold, and it must stop (on fold) when the input is changed.

**Comment by robertcv** [comment]
I retested the widget. It seems that when trying to delete it, it realy deletes itself on folds. As for changing input, it does not stop on the fold, it always runs tilt the end.
