### ISSUE TITLE
Prediction: scores for regression are wrong and are different from Test & Score

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3#4029]
**Describe the bug**
Predictions widget displays wrong RMSE.

**To Reproduce**
Paint the data, select the columns to place y as a target, use linear regression for prediction. Feed Predictions with the training data. Choose L2 regularization. With increasing L2 regularization, RMSE should increase. Instead, RMSE decreases and with increased regularization converges to zero. R2 is not shown.

Minor: the table with results is resizes upon any change of the input.

**Orange version:**
3.23.0

**Expected behavior**
The widget should display scores that are equal to those displayed in Test & Score under appropriate setting (e.g., test on train data for Test & Score).

**Screenshots**
<img width="1291" alt="predictions-different-from-test-score" src="https://user-images.githubusercontent.com/726604/65071310-269fd500-d954-11e9-97cb-2b114b743837.png">

**Operating system:**
Windows, OSX or Linux? Which version?

**Additional context**

**Comment by janezd** [comment]
#4030 should fix it.

It's my fault. "Test and Score" and "Predictions" use the same class to show the table. I wrote it and I used in in `OWPredictions`. I merged #3943, which added two columns. If anybody, I should have known that it wouldn't affect only Test and Score but also  OWPredictions.

If you want to use this widget at lectures (with the current release of Orange) so much that you don't bother some further embarassment, you can right-click the header of the table, and make the first two columns visible. The missing numbers will appear ... except that the header will be wrong - the number in the first column should be in the third and so forth.

Or you can merge #4030 and use the unreleased master at lectures.
