### ISSUE TITLE
Scatterplot saves a PDF by cropping the image and not showing the axis labels

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3#4043]
**Describe the bug**
When Save Image is used to export the image rendered by the Scatter Plot, the image in the PDF is cropped, hiding the labels of the y-axis and the feature name of the x-axis. 

**To Reproduce**
File (iris) -> Scatter Plot, Save Image

**Orange version:**
3.23.0

**Screenshots**
This is how the output PDF looks:
[iris-pdf.pdf](https://github.com/biolab/orange3/files/3639575/iris-pdf.pdf)

**Comment by BlazZupan** [comment]
For a better illustration, here is the rendering of the resulting PDF in a PDF viewer:

<img width="586" alt="iris-pdf" src="https://user-images.githubusercontent.com/726604/65385338-fe3a2100-dd2d-11e9-9b85-fad579bf785a.png">

**Comment by markotoplak** [comment]
This was already fixed for PyQt >= 5.12 in #3694, but our packages are still on PyQt 5.9.

**Comment by ajdapretnar** [comment]
@markotoplak Should we pin the version to >=5.12? Or are we waiting for conda to automatically install a higher version?

**Comment by markotoplak** [comment]
@ajdapretnar, I do not know.

@ales-erjavec, you once said there are some problems on Macs with Qt > 5.9 (if I remember correctly, due to some changes in how Qt draws things). How is it now?

**Comment by ales-erjavec** [comment]
Qt 5.12 and 5.13 seem to be OK.

**Comment by markotoplak** [comment]
Opened ales-erjavec/orange3-installers#5

**Comment by ajdapretnar** [comment]
This seems solved.
