### ISSUE TITLE
Orange error message when opening workflow - lost widgets

### ISSUE THREAD

**Issue by AMC-WHZ** [biolab/orange3#4054]
When opening previous workflows in Orange the following error message appears:
UnknownWidgetDefinition('orangecontrib.text.widgets.owcorpus.OWCorpus',)
UnknownWidgetDefinition('orangecontrib.text.widgets.owpreprocess.OWPreprocess',)
UnknownWidgetDefinition('orangecontrib.text.widgets.owbagofwords.OWTBagOfWords',)
UnknownWidgetDefinition('orangecontrib.text.widgets.owwordcloud.OWWordCloud',)
UnknownWidgetDefinition('orangecontrib.text.widgets.owwordcloud.OWWordCloud',)
UnknownWidgetDefinition('orangecontrib.text.widgets.owconcordance.OWConcordance',)
UnknownWidgetDefinition('orangecontrib.text.widgets.owcorpus.OWCorpus',)
UnknownWidgetDefinition('orangecontrib.text.widgets.owpreprocess.OWPreprocess',)
UnknownWidgetDefinition('orangecontrib.text.widgets.owbagofwords.OWTBagOfWords',)
UnknownWidgetDefinition('orangecontrib.text.widgets.owwordcloud.OWWordCloud',)
UnknownWidgetDefinition('orangecontrib.text.widgets.owconcordance.OWConcordance',)

Error appears each time even after updating to the newest version.
The widgets named in the error message are not drawn and are not shown on the widget list.
The error message appears for both workflows I tried to open.

1. Go to 'Open'
2. Select workflow to open
3. Error appears

Orange - Version 3.21 and version 3.23

I expected the workflows (created in May 2019 and on 23 September 2019) to open as before and to be able to use all widgets as usual.

![grafik](https://user-images.githubusercontent.com/55755010/65526355-448bad80-def1-11e9-917e-b9c6f1680e93.png)

![grafik](https://user-images.githubusercontent.com/55755010/65526444-68e78a00-def1-11e9-90dd-2ac0d5c561a5.png)

**Comment by AMC-WHZ** [comment]
Issue solved, forgot to install the Add-Ons

**Comment by ajdapretnar** [comment]
Perhaps Orange could still format this error in a nicer way? @janezd @markotoplak
