### ISSUE TITLE
OWPredictions: issues with predicting text

### ISSUE THREAD

**Issue by CrtGrahonja** [biolab/orange3#4059]
**Describe the bug**
When trying to predict a class from text using Logistic regression (but any other regression as well) errors happen, as can be seen from the attached picture 'Errors': 
 * Only one class present in y_true. ROC AUC score not defined in that case.
 * Input contains NaN, infinity ora  value too large for dtype('float64'). [4 times]
 * Data does not have the same target as predictors.
The data to be estimated have the same format as the training data, except for the class variable, which is always '?'.

This happens, when a Python Script is used to manipulate the input data. In the example a discretization of the target class has been done in the form of 2 classes: 1 (variable value 'je') when the original class variable was positive and 0 (variable value 'ni') when it's 0. As explained above, in the data to be estimated, the value was always '?'.
As can be seen from the attached files and picture, the format of the variables is the same in both files.

This issue was not present when the Python script wasn't used (the branch "Estimate Continious").

**To Reproduce**
1. Include a Python Script that manipulates the target class in the workflow.
2. Run a basic text mining model.
3. Try to predict binary values.
4. See error in the 'Predictions' widget.

**Orange version:**
3.22.0

**Expected behavior**
Normal prediction executed like in the branch "Estimate Continious".

**Screenshots**
![Errors](https://user-images.githubusercontent.com/39695964/65693906-539b6880-e075-11e9-9716-363da475f3d5.png)

**Operating system:**
Windows 7.

**Additional context**
I attach the whole workflow, all three .TAB files used and the Python Script file.
[Prediction_TM_Errors.zip](https://github.com/biolab/orange3/files/3658145/Prediction_TM_Errors.zip)

**Comment by ajdapretnar** [comment]
I assume the bulk of the problem will be solved via https://github.com/biolab/orange3/pull/3925.
Discrete variables from Estimate Discrete and from Training are not the same. Before, one had to use Variable.make to make them the same. Will be fixed in the next release.

Also, remove the target variable from the Estimate Discrete. You don't need it.
On this topics, there should be no crash when passing an empty target variable. Continued in  #4060.
