### ISSUE TITLE
Polynomal regression variable reset when widget is refreshed

### ISSUE THREAD

**Issue by domburgb** [biolab/orange3#4064]
##### Orange version

3.22

##### Expected behavior
When something in the workflow is changed then the polynomal regression grah should be refreshed with the new settings, but keeping the layout the same

##### Actual behavior
When something is changed in the workflow or the file is just loaded then the variables chosen for the axes are changed into something else (usually the y-axis is changed into the last possible variable)

**Comment by ajdapretnar** [comment]
Polynomial Regression is a widget from the Educational add-on. Please report the issue to the corresponding repository: https://github.com/biolab/orange3-educational/issues

**Comment by ajdapretnar** [comment]
Also please describe the issue in more details, because I cannot reproduce it (or I do not understand what is the issue here).
