### ISSUE TITLE
Merge data may output domain with duplicated names

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#4070]
The God sayeth: "*Thou shall not create domains with two variables of the same name.*"

And the Merge widget came forth and said: "*Watch me*", and dared to even announce:

```
    class Warning(widget.OWWidget.Warning):
        duplicate_names = Msg("Duplicate variable names in output.")
```

**Expected behavior**

Maybe put variables through `get_unique_names`. Though this one is a bit more complicated. `get_unique_names` is appropriate when a variable name may already exist and we need to add a number to the name. Here, variables come together from different domains. I would prefer that all variables get numbers if there is a conflict. If both domains have variable `foo`, I'd like to see `foo (1)` and `foo (2)`, not `foo` and `foo (1)`. 

Conceptually (this code doesn't actually fit anywhere literally, but probably works):

```
conflict = set(left_vars) & set(right_vars)
left_vars = [get_unique_names(var, conflict) for var in left_vars]
right_vars = [get_unique_names(var, conflict | left_vars) for var in right_vars]
```

Variables in `left_vars` are renamed if they are in conflict with `right_vars`. `right_vars` are then renamed to consecutive numbers.

**Comment by VesnaT** [comment]
The God sayeth: "Thou shall not rename variables."

And the Merge widget complained: "But I have duplicate names after merging two datasets, shall I just show a warning?"

**Comment by VesnaT** [comment]
As far as getting names with numbers goes: the proposed solution is already implemented in `get_unique_names_duplicates`.

**Comment by janezd** [comment]
God just doesn't want us to rename variables in-place. Like Edit Domain, which renames them, but these are new variables. No penance for this.

Thanks for the hint about `get_unique_names_duplicates`. This is exactly what I meant.
