### ISSUE TITLE
k-Means widget does not normalize numeric features

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#4075]
**Describe the bug**

k-means should normalize numeric data, e.g. scale by span or variance.

**To Reproduce**

The most embarassing way to demonstrate this during a lecture is to cluster the heart disease data into two clusters and then connect it to Distributions and show the distribution of cholesterol with the data split by cluster. It is obvious that cholesterol value splits the two clusters perfectly ... which happens because the span of values for cholesterol is larger than the span of any other attributes.

**Orange version:**

Any.

**Expected behavior**

Normalize by mean and variance. Or span. @lanzagar, @BlazZupan, others: opinions?

**Additional context**

Don't tell anyone about this.

**Comment by lanzagar** [comment]
Definitely not a bug, at least I am not aware of any definition/implementation of k-means that would transform the data first, before starting the main loop.
The obvious problem is that the space transformation depends very much on the data and it would not make sense to say a specific one is part of the method.

That said, our widgets are also obviously not just single methods but do often include many additional options. And you could argue that this would be a sensible thing to include (as an option!). Someone else could argue that we already have a Preprocess widget that solves this very problem and should definitely be at the forefront of someones mind, when dealing with features with different scales.

So I would say this is a feature request which needs discussion :)

**Comment by janezd** [comment]
Let us add a checkbox so the user are aware that the widget normalizes data.
