### ISSUE TITLE
orange-canvas won't start

### ISSUE THREAD

**Issue by CrashLandonB** [biolab/orange3#4080]
When I run orange-canvas, my mouse indicates "busy" for a second, then the next terminal prompt appears, but the app does not start up.

I usually start this via my Anaconda Prompt, with or without running it as admin, by typing `orange-canvas` at the prompt, and the GUI will open.  At this time, it does not open and there is no feedback.

Running:
Windows 10
Orange v3.23.1 (run in a venv)

Thanks in advance.

**Comment by ajdapretnar** [comment]
Please run `python -m orange.canvas -l 4` in the prompt.

**Comment by CrashLandonB** [comment]
```
(orange-env) (base) C:\Users\xxxxx\Documents\Python\_Data Analytics\orange_test\orange-env>python -m Orange.canvas -l 4
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\xxxxx\Documents\Python\_Data Analytics\orange_test\orange-env\lib\site-packages\Orange\__init__.py", line 9, in <module>
    "pip install --no-binary Orange3") from None
ImportError: Compiled libraries cannot be found.
Try reinstalling the package with:
pip install --no-binary Orange3
```

**Comment by ajdapretnar** [comment]
This looks like there's something wrong with the virtual environment.
How exactly did you install Orange? And the update?

**Comment by CrashLandonB** [comment]
I created the venv, then installed Orange via pip.  Note though that my company has their own approved "mirror" of pip, so it's not installed from the public pypy repository.

What update are you referring to?

**Comment by ajdapretnar** [comment]
You mentioned somewhere that you updated Orange to the latest version recently. Or perhaps I misunderstood.

So one of the issues is that you can install Orange with pip on Windows. You need conda for this, so since you are using Anaconda, install Orange with `conda install orange3`. See detailed instructions in README. I think this should solve your problems.

**Comment by CrashLandonB** [comment]
Ah, yes.  I mentioned I've used a couple different versions in the other Issue that is closed (where you suggested I open a new issue).  I've always used pip to install Orange.  I've had a couple different versions of Anaconda over the years as a starting point, but then use our approved internal pip to install it.

...

Solution found!  I was curious why you were saying I have to use conda, so I went to the following page:
[https://pypi.org/project/Orange3/](url)

This page shows you can install via pip, but more importantly, it shows that I need to run `pip install PyQt5 PyQtWebEngine` as well.  I did this and the Orange GUI fired up as expected!

Thanks for your input!
