### ISSUE TITLE
Discord invite link on website has expired

### ISSUE THREAD

**Issue by newzealandpaul** [biolab/orange3#4087]
At the bottom of the homepage (https://orange.biolab.si/blog/) under Community there is a link to a Discord chat channel. The invite has expired so nobody can join the group.

**Comment by ajdapretnar** [comment]
Yes, we know. 😞 Discord banned our channel because of 'suspected spam activity'. We think the real reason might be too many guest accounts. We are in the process of setting up a new server, but we have to make sure Discord whitelists it first, so the same thing doesn't happen again.
