### ISSUE TITLE
Output for correspondence analysis 

### ISSUE THREAD

**Issue by GottM** [biolab/orange3#4088]
Hi,
It would be cool to have an output with the coordinates of the points in the correspondence analysis widget so we may export them and possibly plot them also outside Orange.
Thank you for all the great stuff in Orange!

**Comment by GottM** [comment]
Thanks @PrimozGodec ! But I (so far) can’t see the implementation of CA outputs in the latest release of Orange. Is this normal, just a matter of being patient? 🙂

**Comment by ajdapretnar** [comment]
This will be available in the next release. :)

**Comment by GottM** [comment]
Ah great 👍. Funny that the help docs already mention it... A hint when the next release will come out?

**Comment by GottM** [comment]
In version 3.23.1, there’s still no output for correspondence analysis even though the help doc already mentions it!

![162B38EB-6D79-4008-BC54-A94AB06CCF99](https://user-images.githubusercontent.com/47322724/69902350-c9c98d80-138c-11ea-943e-f63c0497f3ed.jpeg)
