### ISSUE TITLE
Lift Curve should remember the choice of target class

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3#4115]
**Current state**
Lift curve does not remember anything and resets the interface after any change of the input.

**Requested Change**
Make target class a context-dependent setting.

**Example**
Switch between Telecom customer churn or Hearth disease data sets in the following workflow, set the target class to Yes (churn) and 1 (heart disease).

![image](https://user-images.githubusercontent.com/726604/67083514-93003500-f19b-11e9-96b9-bd3f617f68c8.png)

**Comment by janezd** [comment]
Fixing context settings doesn't sound like "good first issue". Although it is mostly about copy&pasting, it requires knowing where to copy&paste from. :)
