### ISSUE TITLE
OWNeighbors: check matching of attributes only

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#4117]
**Describe the bug**
Neighbors widget doesn't work when meta attributes are different. Should probably only check if X matches, since it doesn't consider metas anyway.

**To Reproduce**
1. Import Images - Image Embedding.
2. Import Images - Face Detector - Image Embedding.
3. Send both to Neighbors.

**Orange version:**
3.23.1

**Expected behavior**
If attributes of both outputs match (data.domain.attributes == reference_data.domain.attributes), Neighbors works.

**Comment by ajdapretnar** [comment]
This seems to be already fixed a long time ago in https://github.com/biolab/orange3/pull/3555.
However, the domain matching fails on the latest release. Not on master. I suspect Variable.make has something to do with this.

**Comment by ajdapretnar** [comment]
I think a release of the current master should fix this. A test would be nice. Domains have to come from two different sources I think - Image Embedding works well for testing.

**Comment by PrimozGodec** [comment]
I assume that it must be the same bug than at https://github.com/biolab/orange3/issues/4108 since both use a `domain.transform`. Also, the test is already available: https://github.com/biolab/orange3/blob/5febf5f14c303f0ad6e6429ee66b7ea58d9192db/Orange/widgets/data/tests/test_owneighbors.py#L402-L457

**Comment by ajdapretnar** [comment]
If tests are already available, I can't understand how they could pass with the last release... Neighbors now doesn't work for demo workflow (lookalike).

**Comment by PrimozGodec** [comment]
You are right, those tests didn't exactly cover the issue you had. The problem was that in this case, all attributes have the same names are different objects. I added a test case for that in #4131.

**Comment by ajdapretnar** [comment]
Yeah, that was the case. Thanks!
