### ISSUE TITLE
Remove `_RefuseDataInConstructor`

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#4122]
In the mists of time, Orange classes would accept data in constructor, e.g. `TreeLearner(data)` instead of proper `TreeLearner()(data)`. Only a few classes (`DomainDiscretizer`, `DomainContinuizer`, `Scorer`, `Preprocess` and, I suppose, the subclasses of the latter two) still allow this unruly calls. They do so through mixin `_RefuseDataInConstructor`, which also triggers a warning - for three years now.

The mixin was written by @kernc, probably with the same amount of enthusiasm as some recent prime minister's letter to the EU about some extension of something. They both accompanied their code/letter with a separate writing saying they don't agree with what they just wrote. In @kernc's case, it is formulated as: `# TODO: drop this as soon as possible`. I suggest we remove the class `_RefuseDataInConstructor` by Oct 31. No extensions.

**Comment by ajdapretnar** [comment]
_RefuseDataInConstructorxit.

**Comment by janezd** [comment]
See this, Boris!
