### ISSUE TITLE
Crashing Error

### ISSUE THREAD

**Issue by MohammadHizam1416** [biolab/orange3#4124]
We are using your great program in [Knowledge Managament] course at our university.

I noticed a small, yet annoying problem that leads to Orang crash.

**When I connect my PC in the university WiFi, it crashes after I open it immediately.
But when I connect to  other WiFi network or switch it off, it works fine.**
Even the doctor faced the same problem 

I think this issue is related to connection privileges/policy 

##### Orange version
v3.23.0

**Comment by ajdapretnar** [comment]
Could you please post the error and/or describe the issue in more details?

**Comment by MohammadHizam1416** [comment]
What type of detailes do you want?

The only thing I missed is the OS, which is : Windows 10 (on both mechines)
It is as simple as that

**Comment by ajdapretnar** [comment]
What does it mean it crashes? Is there an output with an error log? If not, does the crash happen if you have Orange open and disconnect from the internet or only if you try to run Orange when connected to the university WiFi?

The OS information is important, but now we can begin debugging. Please open Orange Command Prompt and run `python -m Orange.canvas -l4` in both modes and then post the output with an error here.

**Comment by janezd** [comment]
Cannot replicate, closed due to inactivity.
