### ISSUE TITLE
orange3 select column error.

### ISSUE THREAD

**Issue by tytom2003** [biolab/orange3#4132]
**Describe the bug**

**To Reproduce**
below is my data table.

When i use select columns function to choos sex, embarked, age_group, pclass_group. Then, i show the data table. It show one row data only. How to solve the issue?
Thank you very much

**Orange version:**
Orange - About - 3.23.1.

**Expected behavior**
it will show servived_group , sex, embarked, Age_group, pclass_group all data in data table.

**Screenshots**
![image](https://user-images.githubusercontent.com/25719095/67371442-f8df2900-f5ae-11e9-8867-4f11a077cb46.png)

![image](https://user-images.githubusercontent.com/25719095/67372152-0648e300-f5b0-11e9-83ce-a9c465613907.png)

![image](https://user-images.githubusercontent.com/25719095/67371774-7b67e880-f5af-11e9-8752-ad97ddf36c30.png)

**Operating system:**
Windows 7

**Additional context**

**Comment by PrimozGodec** [comment]
Thank you for submitting the issue. I cannot reproduce your issue, but it looks strange. Can you please submit your workflow and data (if they can be shared) that we can reproduce your issue.

**Comment by ajdapretnar** [comment]
The data is the original titanic data set that can be downloaded from https://www.kaggle.com/c/titanic/data.

**Comment by janezd** [comment]
These two widgets and the data are so commonly used that (assuming there are indeed just these two widgets in the schema), we won't be able to replicate it without clearer instructions.
