### ISSUE TITLE
Warning when opening a workflow created by a newer of Orange

### ISSUE THREAD

**Issue by irgolic** [biolab/orange3#4134]
Backwards compatibility of workflows is ensured with migrations.
While we don't develop with forwards compatibility in mind, users are still free to open an ows file with any version of Orange.

When opening a workflow created by a **newer** version of Orange, the user should receive a warning that things may not work as expected.

This is similar to the 'Errors occured while loading the workflow' popup which appears when opening a workflow containing widgets one does not have installed. 

Perhaps this message could be displayed in the same interface as the aforementioned popup, in a more user-friendly style, as suggested by @ajdapretnar in https://github.com/biolab/orange3/issues/4054.

**Comment by janezd** [comment]
This can only be solved in orange-canvas-core, I guess. It is not only about Orange but also about add-ons. It may be possible to upgrade Orange when loading the scheme, just like it is currently possible to install the missing (but not also the outdated) add-ons.

Continued in https://github.com/biolab/orange-canvas-core/issues/66
