### ISSUE TITLE
Tutorial for writing addon: link not working

### ISSUE THREAD

**Issue by saurabhgayali** [biolab/orange3#4152]
I am willing to make a server where through an addon people can submit and view different workflows but the tutorial page for writing addons is not found. 
http://orange.biolab.si/trac/wiki/AddOns

**Comment by janezd** [comment]
This is a wrong link. We stopped using trac a very very very long time ago. Where did you find it?!

Proper links are at https://orange.biolab.si/docs/.

**Comment by ajdapretnar** [comment]
@saurabhgayali I am not sure how that would work. Why does it have to be a widget? I think it would be best to have a repository with a corresponding website, that would serve the workflows. Probably something like Github Pages.
