### ISSUE TITLE
Make community shared workflows as an option and downloading shared workflows also an option.

### ISSUE THREAD

**Issue by saurabhgayali** [biolab/orange3#4153]
Suggestion-
Include an option to upload workflows and share with the community, so that we can also see and download user shared workflows. I work in filterforge which is also a non programmatic node based editor for image editing. https://www.filterforge.com/filters/
They have a filter gallery for user community.

**Comment by janezd** [comment]
Thanks for suggestion. We are aware of such tools and have this in mind, but it is currently not a priority.

**Comment by ajdapretnar** [comment]
We currently store our workflows here: https://orange.biolab.si/workflows/

If you have some that you'd like to share, we can include them. Best way to do this is probably to send us the workflow and the description to info@biolab.si. We would consider how to solve attribution.
