### ISSUE TITLE
Prettify Workflow instead of Snap to Grid

### ISSUE THREAD

**Issue by irgolic** [biolab/orange3#4154]
I feel like snap to grid isn't too useful, its role could be better fulfilled by a prettify workflow button.

**Describe the solution you'd like**
Upon a click of a button, the workflow is rearranged into an aesthetically pleasing configuration, as such:
<img width="355" alt="Screenshot 2019-10-31 at 12 17 35" src="https://user-images.githubusercontent.com/24586651/67946097-7242d100-fbd8-11e9-91a8-a8d66366e29d.png">

**Comment by janezd** [comment]
Actually, I don't like the prettify button. This should be like Illustrator's "Snap to object". When you drag a widget, it would snap to position in which the connection line is horizontal, or the widget is horizontally/vertically aligned with other widgets. The former has the priority.

We don't even need a checkbox for this functionality. It could be just enabled, always.

**Comment by ajdapretnar** [comment]
> It could be just enabled, always.

I think that would satisfy only us, super OCD people. I am not sure this is useful when building complex workflows where many connections overlap. I've seen such workflows and they would probably grow even bigger with this option.

**Comment by janezd** [comment]
> I think that would satisfy only us, super OCD people.

Of course. It's far from a must-have.

**Comment by irgolic** [comment]
I think it's nice to give the user agency over where nodes are placed. The prettify feature should serve the same purpose as a code reformat action in an IDE.

I imagine it'd also be useful for creating examples for screenshots.

**Comment by janezd** [comment]
This is a canvas issue. Continued in https://github.com/biolab/orange-canvas-core/issues/53.

**Comment by irgolic** [comment]
A button for recomputation of all widget positions is what I meant.

I'd like to take this

<img width="583" alt="Screenshot 2019-11-08 at 17 47 14" src="https://user-images.githubusercontent.com/24586651/68498868-d35d4b00-024f-11ea-8972-fb6fafe5eec4.png">

and with a click of a button, produce this

<img width="408" alt="Screenshot 2019-11-08 at 17 48 37" src="https://user-images.githubusercontent.com/24586651/68498957-030c5300-0250-11ea-9923-0cb7c2dd5723.png">

Why do you believe a such a solution isn't feasible?

**Comment by janezd** [comment]
I just wanted to say it's so difficult that it won't be implemented. Plus, I suspect that automated positioning won't always give the desired results. I think that snapping is easier and also more useful. But of course I wouldn't object to this solution, if you (or somebody else) implements it.
