### ISSUE TITLE
Model for image tranformation

### ISSUE THREAD

**Issue by saurabhgayali** [biolab/orange3#4166]
I am developing model for image transformation like image magnification, black and white to color transformation and sketch conversion all based on supervised learning through imagesets. 
I can load image and turn into embedded images by imagenet but no learning module accepts two inputs for data.
It would be easier for a simpler widget.

**Comment by ajdapretnar** [comment]
It is not clear what the issue/objective is.

Learners are learners - just procedures to apply to the data. Models are trained in Test&Score, which accepts both the learner and the data. To apply the model on new data, you need Predictions.

**Comment by saurabhgayali** [comment]
Image set 1 contains color images
Image set 2 contains greyscale images

Model is supposed to learn coloring greyscale images based on corresponding images from both imageset.
The learner takes one data node and one text classification node and hence learning in this scenerio is not possible.

The final deployed model will produce colored image when user provide black and white image [Current widgets only support image analysis and classification]

Image based learning with images as output have many applications including Geology, medical science, Astrological sciences and many more.

**Comment by janezd** [comment]
Orange implements models from standard machine learning (or predictive modeling). They require tabular data - like rows and rows of data instances described with a set of variables - and can then predict one target variable based on dependent variables. Your data problem is not like this.

Orange indeed has an add-on image analytics, but it does not contain anything like this - it can embed images and classify them, but not manipulate them, e.g. by coloring. Hence, you will need to implement such a model yourself. If it fits into Orange's add-on, you can submit a pull request with you widget to the add-on repository (https://github.com/biolab/orange3-imageanalytics).
