### ISSUE TITLE
Normalizer not always normalizing correctly

### ISSUE THREAD

**Issue by mtsch** [biolab/orange3#4167]
**Describe the bug**
Normalizing by span with `zero_based=False` works slightly incorrectly for some data.

**To Reproduce**
```
from Orange.data import Table
from Orange.preprocess import Normalize

data = Table("iris")
norm = Normalize(zero_based=False, norm_type=Normalize.NormalizeBySpan)
result = norm(data).X.max()
print(f"{result}, {1-result}")
# 1.0000000000000002, -2.220446049250313e-16
```
This could be fixed by changing the way normalization is performed, e.g.:
```
temp = input - input.min()
result = 2 * (temp / max(temp)) - 1
```

**Orange version:**
master

**Comment by janezd** [comment]
Isn't this just rounding error? Would it be OK if we clip it to [0, 1]?

You propose a different kind of normalization, that is, to [-1, 1] instead of [0, 1]. This is OK, but it's not the same thing and it's not for the same circumstances (e.g. it wouldn't work well when computing distances).

Even then, wouldn't you get numbers outside [-1, 1] due to rounding error?

**Comment by mtsch** [comment]
This only happens with `Normalizer(zero_based=False, norm_type=Normalize.NormalizeBySpan)`, which normalizes to [-1, 1]. As far as I can tell, normalizing to [0, 1] (`zero_based=True`) works fine.

It is just rounding error, but it can be avoided by reordering the operations. I realize this is not trivial to implement because of the way transformations work, so maybe it's best to leave it as is.

**Comment by janezd** [comment]
It shouldn't be difficult. We can just add another class like `Normalizer`, but for normalization to [-1, 1].

**Comment by janezd** [comment]
I realized the whole problem only implementing a (non-)solution.

Normalization is similar to fitting and applying a model. If the span of the "training data" is smaller than the span of data being normalized, normalized values can fall outside of [0, 1] (or [-1, 1]) interval. We can't/shouldn't apply clipping in this case. We could clip if we knew that data is the same, but we don't know this.

@lanzagar further commented that if it's just rounding error, we'll survive (and don't need to clip). If it's not just rounding error, we shouldn't clip.
