### ISSUE TITLE
Widget: small window size

### ISSUE THREAD

**Issue by aturanjanin** [biolab/orange3#4170]
**Is your feature request related to a problem? Please describe.**
When input and output info about data is shown in the status bar and a warning appears, because of the fixed size of widget neither warning message displays fully nor input/output numbers. Also input/output icons become smaller.

On the picture below input should be 50, output 100 and warning message *Sample is bigger than input*.

![Capture](https://user-images.githubusercontent.com/43814754/68372473-37ddb480-0141-11ea-9af3-0db76244f225.PNG)

**Describe the solution you'd like**
One possibility is that for a warning message in the status bar only the yellow triangle warning icon is shown and when a user presses it or goes over it, the warning message is displayed.

**Comment by ajdapretnar** [comment]
I like the solution you propose. An icon is enough (in my opinion), with the full message displayed on click and on hover. We should also test what happens with truly large data, e.g. 1,000,000 input rows. These numbers wouldn't fit the status bar regardless of how small we make the icons. 😞

**Comment by janezd** [comment]
Moved to https://github.com/biolab/orange-widget-base/issues/23.
