### ISSUE TITLE
Data Table widget not saving selection

### ISSUE THREAD

**Issue by iva-c** [biolab/orange3#4184]
Data table does not save all selected data and always resets to no data selected upon the reopening of the workflow.

**Comment by PrimozGodec** [comment]
@iva-c I cannot reproduce this issue. What version of Orange do you use? I remember it was an issue but it must be fixed now.

**Comment by iva-c** [comment]
I haven't managed to reproduce it either, I guess I called it too early. So, I'm closing this issue.

**Comment by iva-c** [comment]
Came acorss a workflow where this happens. 
[human_osteoarthritis.zip](https://github.com/biolab/orange3/files/3851621/human_osteoarthritis.zip)

Orange version: 3.22
OS: W10

**Comment by PrimozGodec** [comment]
I was able to reproduce the issue on macOS too (Orange version 3.23.1, master).
What I found out is that when data comes from PCA (either components or transformed data) the selection is not saved. Here is the simplified workflow that shows the issue.

[human_osteoarthritis – kopija.ows.zip](https://github.com/biolab/orange3/files/3904846/human_osteoarthritis.kopija.ows.zip)
