### ISSUE TITLE
Orange asks to save a schema even if it was just saved

### ISSUE THREAD

**Issue by iva-c** [biolab/orange3#4185]
Even when a workflow is saved, when closing it, a prompt “Save the changes to the workflow “untitled”?”" pops up. 

OS: Windows 10
Orange version 3.22.0

**Comment by markotoplak** [comment]
@irgolic, we were talking about this. @iva-c, this is actually a very strange feature, which should probably be removed. In this case, "untitled" is the workflow name, not the file name.

**Comment by PrimozGodec** [comment]
I noticed that it happens when I open the workflow from the file. Then I save it. When I close Orange this message appears. So it seems that when I opened the workflow from file some empty workflow remains in the background which then want to be saved.

**Comment by janezd** [comment]
This is not related to loading schema from a file. Open Orange, add a widget, save schema, try to close. It will ask whether to save the schema. (And it's now just Windows.)

**Comment by irgolic** [comment]
Hoping to alleviate this with https://github.com/biolab/orange-canvas-core/pull/44, where the workflow will automatically save on close.

Referencing the filename instead of the 'workflow title' was merged in https://github.com/biolab/orange-canvas-core/pull/43.

**Comment by janezd** [comment]
@ales-erjavec, I think the problem in is https://github.com/biolab/orange-canvas-core, not in Orange. True?

**Comment by ales-erjavec** [comment]
orange-canvas-core and orange-widget-base. OWWidget has no way to notify the canvas that any settings have been modified and a save is necessary.

So as a workaround canvas stores all [settings in memory whenever a save is performed](https://github.com/biolab/orange-canvas-core/blob/master/orangecanvas/document/schemeedit.py#L585). Then when a workflow is closed it collects all the settings again and [compares them (by equality) with last saved version](https://github.com/biolab/orange-canvas-core/blob/master/orangecanvas/document/schemeedit.py#L594). If they do not match it asks to save again. And for most orange widgets (at least the ones using context settings):
```
widget.settingsHandler.pack_data(widget) != widget.settingsHandler.pack_data(widget)
```
hence the assumption that the parameters have changed.

**Comment by janezd** [comment]
Continues in https://github.com/biolab/orange-widget-base/pull/27.
