### ISSUE TITLE
Application crashes after launch (Mac OS)

### ISSUE THREAD

**Issue by MartinMarzi** [biolab/orange3#4186]
**Describe the bug**
After launching the application (bundle Orange.dmg installation) the logo of Orange shortly appears and then the application crashes. 

When launching the application from the terminal within a conda environment the application works as expected.

**Orange version:**
Orange 3.23.1 (mac)

**Operating system:**
OS X 10.15.1

I attach the crash report:
[Organe_crash_report.pdf](https://github.com/biolab/orange3/files/3836426/Organe_crash_report.pdf)

**Additional context**

**Comment by ales-erjavec** [comment]
Can you try running:
```
/Applications/Orange3.app/Contents/MacOS/pip install pyqt5==5.12.3 pyqtwebengine==5.12.1
```
from the terminal then try starting orange again.

**Comment by WolframRinke** [comment]
Thank you, this helped to fix my problem

**Comment by MartinMarzi** [comment]
Hvala Aleš.

FYI: sedaj sem ponovno inštaliral mac pacakgez vaše spletne strani in dela,
verjetno ste kaj posodobili.

hvala lp

Martin
