### ISSUE TITLE
Heatmap color scale centre

### ISSUE THREAD

**Issue by Hrovatin** [biolab/orange3#4191]
Could an option be added to heatmap to center colour scale at some value (e.g. 0). For example, differential expression is oft visualised as fold change between two samples , centered at zero, with one colour representing underexpression (FC<0) and the other overexpression (FC>0) (e.g. with  green-black-red or blue-white red).

**Comment by leeherman99** [comment]
Just opened this issue up again.

The option to center the color palette at 0 is gone in Orange 3.25. Also, the ability to set the center point at an arbitrary value is important.

**Comment by Hrovatin** [comment]
For 0-centering you can use the _Diverging_ pallets which are centered at 0. A work around for visually centering the palette at a specific value might be the use of Feature Constructor. A new feature could be generated so that it has 0 at the desired center of the original feature. However, this would be impractical for large number of features and the legend would be shifted due to the processing of the original feature.
