### ISSUE TITLE
Feature statistics colour scale

### ISSUE THREAD

**Issue by Hrovatin** [biolab/orange3#4195]
Orange 2.23, linux
When colouring by a feature in Feature statistics the colour scale of last bin is off (eg. same as at the left side of histogram). This does not happen in scatter plot. 
 Example: colouring by petal length in Orange iris dataset - look at histogram of same feature.

![Screenshot from 2019-11-15 15-42-29](https://user-images.githubusercontent.com/47607471/68951841-22126400-07bf-11ea-9f24-b5f8488e291d.png)

**Comment by janezd** [comment]
The problem is here: https://github.com/biolab/orange3/blob/master/Orange/widgets/data/utils/histogram.py#L373,

```
biny = self.y[mask[bin_idx]]
if np.isfinite(biny).any():
    mean = ut.nanmean(biny) / ut.nanmax(self.y)
else:
    mean = 0  # bin is empty, color does not matter
```

If I changed mean = 0 to mean = 1, the color changes. The bin is not empty although
