### ISSUE TITLE
Neighbors fails on embedded image data

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3#4197]
**Describe the bug**
Feeding an embedded images into Neighbors widget issues a warning "Every data instance is same as some reference", and the output of the widget is empty.

<img width="784" alt="image" src="https://user-images.githubusercontent.com/726604/68998018-24eb8280-08ad-11ea-9495-a9442467cc0e.png">

<img width="480" alt="image" src="https://user-images.githubusercontent.com/726604/68998022-2f0d8100-08ad-11ea-9f82-e1b05ee87587.png">

**Comment by janezd** [comment]
I think this works as intended. The message is correct. I guess you should uncheck "Exclude rows (equal to) references".

**Comment by PrimozGodec** [comment]
@BlazZupan you need to connect all embeddings to the data input of the neighbors and selection from the Image Viewer should be connected as a reference. In the example above you mixed those two. 

So, in this case, Neighbours will output the images that are the most similar to the reference selected in the Image Viewer.

**Comment by BlazZupan** [comment]
This was stupid from my side. Thanks for the comments.
