### ISSUE TITLE
Install error: Text exited with non zero status.

### ISSUE THREAD

**Issue by ByronJames** [biolab/orange3#4199]
##### Expected behavior
Install "Text:" add on.

##### Actual behavior
Command failed: python python -m pip install --constraint /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmp1u9odvn8.txt Orange3-Text exited with non zero status.

details: 
Collecting Orange3-Text
  Using cached https://files.pythonhosted.org/packages/db/6c/b82646170d616c8498121d4f1e421cdca6d66bbd40902d1aea2d50b07eee/Orange3_Text-0.7.4-py3-none-any.whl
Requirement already satisfied: beautifulsoup4 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Text) (4.8.1)
Requirement already satisfied: biopython in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Text) (1.75)
Requirement already satisfied: docx2txt>=0.6 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Text) (0.8)
Requirement already satisfied: pdfminer3k>=1.3.1 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Text) (1.3.1)
Collecting ufal.udpipe>=1.2.0.2 (from Orange3-Text)
  Using cached https://files.pythonhosted.org/packages/99/1a/9fbf9658cb3a24bfa2e462b4fda554f48b6fe7a7ee44f5036b1f7d181ca8/ufal.udpipe-1.2.0.2.tar.gz
Requirement already satisfied: Orange3<4.0a,>=3.20 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from -c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (3.23.1)
Requirement already satisfied: scikit-learn in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Text) (0.21.3)
Collecting wikipedia (from Orange3-Text)
Requirement already satisfied: docutils==0.14.* in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Text) (0.14)
Requirement already satisfied: odfpy>=1.3.5 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Text) (1.4.0)
Requirement already satisfied: simhash in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Text) (1.9.0)
Requirement already satisfied: gensim>=0.12.3 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Text) (3.8.1)
Requirement already satisfied: nltk>=3.0.5 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Text) (3.4.5)
Requirement already satisfied: numpy in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Text) (1.16.5)
Requirement already satisfied: lxml in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Text) (4.4.1)
Requirement already satisfied: tweepy in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Text) (3.8.0)
Requirement already satisfied: setuptools-git in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Text) (1.2)
Requirement already satisfied: scipy in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3-Text) (1.2.2)
Requirement already satisfied: soupsieve>=1.2 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from beautifulsoup4->Orange3-Text) (1.9.5)
Requirement already satisfied: ply>=3.4 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pdfminer3k>=1.3.1->Orange3-Text) (3.11)
Requirement already satisfied: pytest>=2.0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pdfminer3k>=1.3.1->Orange3-Text) (5.2.4)
Requirement already satisfied: joblib>=0.9.4 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (0.11)
Requirement already satisfied: pyqtgraph>=0.10.0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (0.10.0)
Requirement already satisfied: matplotlib>=2.0.0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (3.1.1)
Requirement already satisfied: orange-canvas-core<0.2a,>=0.1.7 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (0.1.7)
Requirement already satisfied: requests in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (2.22.0)
Requirement already satisfied: keyring in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (10.3.1)
Requirement already satisfied: python-louvain>=0.13 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (0.13)
Requirement already satisfied: pip>=9.0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (19.2.3)
Requirement already satisfied: pyyaml in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (5.1.2)
Requirement already satisfied: keyrings.alt in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (2.2)
Requirement already satisfied: networkx in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (2.3)
Requirement already satisfied: serverfiles in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (0.3.0)
Requirement already satisfied: xlsxwriter in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (1.2.1)
Requirement already satisfied: AnyQt>=0.0.8 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (0.0.10)
Requirement already satisfied: bottleneck>=1.0.0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (1.2.1)
Requirement already satisfied: setuptools>=36.3 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (40.6.2)
Requirement already satisfied: openTSNE>=0.3.11 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (0.3.11)
Requirement already satisfied: pandas in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (0.25.1)
Requirement already satisfied: xlrd>=0.9.2 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (1.2.0)
Requirement already satisfied: chardet>=3.0.2 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (3.0.4)
Requirement already satisfied: orange-widget-base<4.1a,>=4.0a in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (4.0.1)
Requirement already satisfied: defusedxml in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from odfpy>=1.3.5->Orange3-Text) (0.6.0)
Requirement already satisfied: six>=1.5.0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gensim>=0.12.3->Orange3-Text) (1.12.0)
Requirement already satisfied: smart-open>=1.8.1 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from gensim>=0.12.3->Orange3-Text) (1.9.0)
Requirement already satisfied: PySocks>=1.5.7 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from tweepy->Orange3-Text) (1.7.1)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from tweepy->Orange3-Text) (1.3.0)
Requirement already satisfied: attrs>=17.4.0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (19.3.0)
Requirement already satisfied: pluggy<1.0,>=0.12 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (0.13.0)
Requirement already satisfied: packaging in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (19.2)
Requirement already satisfied: py>=1.5.0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (1.8.0)
Requirement already satisfied: importlib-metadata>=0.12; python_version < "3.8" in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (0.23)
Requirement already satisfied: wcwidth in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (0.1.7)
Requirement already satisfied: atomicwrites>=1.0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (1.3.0)
Requirement already satisfied: more-itertools>=4.0.0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (7.2.0)
Requirement already satisfied: cycler>=0.10 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from matplotlib>=2.0.0->Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from matplotlib>=2.0.0->Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (2.4.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from matplotlib>=2.0.0->Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (1.1.0)
Requirement already satisfied: python-dateutil>=2.1 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from matplotlib>=2.0.0->Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (2.8.0)
Requirement already satisfied: commonmark in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from orange-canvas-core<0.2a,>=0.1.7->Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (0.9.0)
Requirement already satisfied: cachecontrol[filecache] in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from orange-canvas-core<0.2a,>=0.1.7->Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (0.12.5)
Requirement already satisfied: idna<2.9,>=2.5 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests->Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests->Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (2019.9.11)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests->Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (1.25.6)
Requirement already satisfied: decorator>=4.3.0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from networkx->Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (4.4.0)
Requirement already satisfied: pynndescent>=0.3 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from openTSNE>=0.3.11->Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (0.3.3)
Requirement already satisfied: pytz>=2017.2 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pandas->Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (2019.2)
Requirement already satisfied: boto3 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from smart-open>=1.8.1->gensim>=0.12.3->Orange3-Text) (1.10.19)
Requirement already satisfied: boto>=2.32 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from smart-open>=1.8.1->gensim>=0.12.3->Orange3-Text) (2.49.0)
Requirement already satisfied: oauthlib>=3.0.0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests-oauthlib>=0.7.0->tweepy->Orange3-Text) (3.1.0)
Requirement already satisfied: zipp>=0.5 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (0.6.0)
Requirement already satisfied: future in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from commonmark->orange-canvas-core<0.2a,>=0.1.7->Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (0.17.1)
Requirement already satisfied: msgpack in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from cachecontrol[filecache]->orange-canvas-core<0.2a,>=0.1.7->Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (0.6.2)
Requirement already satisfied: lockfile>=0.9; extra == "filecache" in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from cachecontrol[filecache]->orange-canvas-core<0.2a,>=0.1.7->Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (0.12.2)
Requirement already satisfied: numba>=0.39 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pynndescent>=0.3->openTSNE>=0.3.11->Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (0.45.1)
Requirement already satisfied: s3transfer<0.3.0,>=0.2.0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from boto3->smart-open>=1.8.1->gensim>=0.12.3->Orange3-Text) (0.2.1)
Requirement already satisfied: botocore<1.14.0,>=1.13.19 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from boto3->smart-open>=1.8.1->gensim>=0.12.3->Orange3-Text) (1.13.19)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from boto3->smart-open>=1.8.1->gensim>=0.12.3->Orange3-Text) (0.9.4)
Requirement already satisfied: llvmlite>=0.29.0dev0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from numba>=0.39->pynndescent>=0.3->openTSNE>=0.3.11->Orange3<4.0a,>=3.20->-c /var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/tmpc6sx62t5.txt (line 1)) (0.29.0)
Building wheels for collected packages: ufal.udpipe
  Building wheel for ufal.udpipe (setup.py): started
  Building wheel for ufal.udpipe (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /Applications/Orange3.app/Contents/MacOS/PythonApp -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/pip-install-omue8j33/ufal.udpipe/setup.py'"'"'; __file__='"'"'/private/var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/pip-install-omue8j33/ufal.udpipe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/pip-wheel-t6924v3q --python-tag cp36
       cwd: /private/var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/pip-install-omue8j33/ufal.udpipe/
  Complete output (16 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.6-intel-3.6
  creating build/lib.macosx-10.6-intel-3.6/ufal
  copying ufal/__init__.py -> build/lib.macosx-10.6-intel-3.6/ufal
  copying ufal/udpipe.py -> build/lib.macosx-10.6-intel-3.6/ufal
  running build_ext
  building 'ufal_udpipe' extension
  creating build/temp.macosx-10.6-intel-3.6
  creating build/temp.macosx-10.6-intel-3.6/udpipe
  gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -Iudpipe/include -I/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c udpipe/udpipe.cpp -o build/temp.macosx-10.6-intel-3.6/udpipe/udpipe.o -std=c++11 -fvisibility=hidden -w -stdlib=libc++
  clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
  clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for ufal.udpipe
  Running setup.py clean for ufal.udpipe
Failed to build ufal.udpipe
Installing collected packages: ufal.udpipe, wikipedia, Orange3-Text
  Running setup.py install for ufal.udpipe: started
    Running setup.py install for ufal.udpipe: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /Applications/Orange3.app/Contents/MacOS/PythonApp -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/pip-install-omue8j33/ufal.udpipe/setup.py'"'"'; __file__='"'"'/private/var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/pip-install-omue8j33/ufal.udpipe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/pip-record-tvaeilbr/install-record.txt --single-version-externally-managed --compile
         cwd: /private/var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/pip-install-omue8j33/ufal.udpipe/
    Complete output (16 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-intel-3.6
    creating build/lib.macosx-10.6-intel-3.6/ufal
    copying ufal/__init__.py -> build/lib.macosx-10.6-intel-3.6/ufal
    copying ufal/udpipe.py -> build/lib.macosx-10.6-intel-3.6/ufal
    running build_ext
    building 'ufal_udpipe' extension
    creating build/temp.macosx-10.6-intel-3.6
    creating build/temp.macosx-10.6-intel-3.6/udpipe
    gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -Iudpipe/include -I/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c udpipe/udpipe.cpp -o build/temp.macosx-10.6-intel-3.6/udpipe/udpipe.o -std=c++11 -fvisibility=hidden -w -stdlib=libc++
    clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
    clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Applications/Orange3.app/Contents/MacOS/PythonApp -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/pip-install-omue8j33/ufal.udpipe/setup.py'"'"'; __file__='"'"'/private/var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/pip-install-omue8j33/ufal.udpipe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/5v/ntp79y055cx3qd0vf3y6fzmr0000gn/T/pip-record-tvaeilbr/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
<img width="419" alt="Screen Shot 2019-11-18 at 6 04 49 PM" src="https://user-images.githubusercontent.com/6851794/69043435-fa750300-0a2d-11ea-85b8-62b7354062b9.png">

##### Steps to reproduce the behavior
Install "Text" add on.

##### Additional info (worksheets, data, screenshots, ...)
N/A

**Comment by ajdapretnar** [comment]
Please report this to the corresponding add-on issue tracker: https://github.com/biolab/orange3-text/issues

**Comment by ByronJames** [comment]
Done.
