### ISSUE TITLE
GeoMap Cannot Fetch Map

### ISSUE THREAD

**Issue by junaidabid77** [biolab/orange3#4203]
##### Orange version
3.23.1. Running on MACOS

##### Expected behavior

Show Geomap with the data linked.

##### Actual behavior

Warning sign saying: Cannot fetch map from the internet. Displaying cached parts.

##### Steps to reproduce the behavior
Not sure. I just selected the geomap.

##### Additional info (worksheets, data, screenshots, ...)
<img width="1440" alt="Screenshot 2019-11-19 at 01 51 10" src="https://user-images.githubusercontent.com/43321357/69109272-249ae500-0a6f-11ea-9a90-8c65324ab0c7.png">

**Comment by robertcv** [comment]
Please report this to the corresponding add-on issue tracker: https://github.com/biolab/orange3-geo/issues
