### ISSUE TITLE
Can't save an .OWS file

### ISSUE THREAD

**Issue by schaiken** [biolab/orange3#4205]
**Describe the bug**
Can't save an .OWS file; dialog box says file not found? Windows-10 environment new instance of 3.23 and reload of anaconda.

**To Reproduce**
1. Go to 'File'
2. Click on 'Save or Save As.'
3. Scroll down to 'Save or Save As.
4. See error dialog box "Save /orange Workflow File"
"File not found, check the file name and try again"

**Orange version:**
Orange - About - version number 3.23.1
**Expected behavior**
should have been able to save the workflow file anywhere
**Screenshots**
![image](https://user-images.githubusercontent.com/6562153/69247367-4df36800-0b78-11ea-84f0-63f876e8c94d.png)

**Operating system:**
Windows-10 Home; latest updates

**Additional context**
just started to happen with older instance so uploaded new environment including Python Anaconda; problem persists

**Comment by janezd** [comment]
This looks weird. Your computer has directory `c:\Users\schai\Desktop`, right?

**Comment by schaiken** [comment]
This has been resolved! Turns out during a Windows-10 update , a 'feature' was turned on in anti-ransomware protection of all folders in Defender. It precluded updating any folder with a new file from a "suspect" application, in this case Orange, but also affected creating a backup Quicken file as well.  Thanks for responding!
