### ISSUE TITLE
Recent workflows displayed as untitled

### ISSUE THREAD

**Issue by iva-c** [biolab/orange3#4208]
Saved titled workflows appear to be untitled when viewed in recend workflows

![recent_workflows](https://user-images.githubusercontent.com/48483052/69412216-bb390180-0d0e-11ea-9841-65e182bb8bf1.png)

OS: W12
Orange version: 3.22

**Comment by markotoplak** [comment]
What happens if you set the title in File->Workflow info?

**Comment by iva-c** [comment]
@markotoplak After that the name is displayed correctly

**Comment by markotoplak** [comment]
So the workflow name is then always correctly displayed, it is just that it was not set before. Maybe we should abolish this workflow names as they cause confusion? @irgolic

**Comment by ajdapretnar** [comment]
I agree. Distinguishing between workflow name and file name is confusing.

**Comment by wvdvegte** [comment]
If I want to close an open workflow that already has a name, it is also referred to as "untitled" in the alert box. Could this be related ?
![Screenshot 2019-12-04 at 10 36 58](https://user-images.githubusercontent.com/55989717/70131222-35a84080-1682-11ea-8e49-f5e94cbbae88.png)

**Comment by wvdvegte** [comment]
Ah, now I understand why I'm always getting messages like "Do you want to save the changes you made to workflow "untitled"?" even if I thought I'd named the workflow (NOT)...
Is it doable to give a workflow the same name as the file name, by default, once it's being saved - unless the user has specified a different name for the workflow (but then again, why would they?)

**Comment by irgolic** [comment]
The save dialogue was changed in https://github.com/biolab/orange-canvas-core/pull/43.
