### ISSUE TITLE
Merge data remember Row matching

### ISSUE THREAD

**Issue by Hrovatin** [biolab/orange3#4210]
Merge data should remember Row matching feature names even when input data changes. For example, when inserting/removing preprocessing widgets or changing preprocessing applied by Single cell preprocessing before merging the Row matching features are forgotten. Same happens when data comes from selection on plots and an empty selection is made by mistake between selections. This can be very frustrating if there are hundreds of features which need to be scrolled through to reach the desired one - maybe a search box could be added as well.

Furthermore, sometimes extra data may come from different sources (e.g. clustering or tSNE) and has same feature names which could be used for merging. Thus an instance of Merge widget could remember what was last set for Row matching and apply it automatically if new data has features with such names.

**Comment by ajdapretnar** [comment]
Search kind of works if you start typing the name of the variable. Doesn't it?

**Comment by Hrovatin** [comment]
Yes it does. I did not notice it as there was no box to type in.
