### ISSUE TITLE
Connection order in loaded workflows is mixed up for Inputs with multiple=True

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#4211]
**Describe the bug**
When I draw a workflow, inputs with multiple=True respect the order in which I connected the widgets. If I load a saved workflow, they can get mixed up. It seems the the order in loaded workflows depends on the order in which I added widgets to the canvas.

**To Reproduce**

Create a workflow with three widgets as shown here (add widgets in the order as written on the screenshot). Then, connect the second-added File to Data table first, and then connect first-added File to the Data table. The File you connected the first will be shown in the first tab of Data table. For the bug to appear the widget-adding order needs to be different than the connection-order.

![out](https://user-images.githubusercontent.com/552182/69417911-e6751e00-0d19-11ea-81c3-cd10fecc0bca.png)

Save and reload. Now, the other file is shown in the first tab. 

I first discovered this but with the Python script widget, where the ordering is critical. The same reordering also happens there.

**Orange version:**
master

**Comment by ajdapretnar** [comment]
Isn't this something for orange-widget-base?

**Comment by markotoplak** [comment]
I honestly do not know. Could be also orange-canvas-core. :)

**Comment by janezd** [comment]
@ales-erjavec, to which repository do these issues this belong?

**Comment by ales-erjavec** [comment]
Could be in either. Depending on which level the signals delivery order should (and can) be defined.

**Comment by markotoplak** [comment]
Fixed in biolab/orange-widget-base#29
