### ISSUE TITLE
The order of inputs with multiple=True is not shown in the workflow

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#4216]
**Describe the bug**
The order is multiple inputs is mostly stable within a run of Orange (barring #4215), but there is no visual indication of it in the canvas.

**Orange version:**
master

**Comment by janezd** [comment]
Is it needed and do you have any idea how?

Also, maybe move this issue to https://github.com/biolab/orange-canvas-core?

**Comment by janezd** [comment]
Moved to https://github.com/biolab/orange-canvas-core/issues/85.
