### ISSUE TITLE
Variable comparison in domain conversion is too strict

### ISSUE THREAD

**Issue by vpodpecan** [biolab/orange3#4221]
**Describe the bug**
This is more like a semantic bug. When doing domain conversion, variables are compared using the ``is`` operator (see line 353 in [Orange/data/variable.py](https://github.com/biolab/orange3/blob/774c4be7e172d730b301646ef3732967018c18b3/Orange/data/variable.py#L353)).

**To Reproduce**
Consider the following example:
```python
import Orange

v1 = Orange.data.DiscreteVariable(name='dvar1', values=['a', 'b', 'c'])
v2 = Orange.data.DiscreteVariable(name='dvar2', values=['a', 'b', 'c'])
d1 = Orange.data.Domain([v1, v2])

v3 = Orange.data.DiscreteVariable(name='dvar1', values=['a', 'b', 'c'])
v4 = Orange.data.DiscreteVariable(name='dvar2', values=['a', 'b', 'c'])
d2 = Orange.data.Domain([v3, v4])

# prints [None, None]
print(Orange.data.domain.DomainConversion(d1, d2).attributes)
```
This is perfectly OK for some simple scenarios where the very same Variable objects are used in both domains. However, when variables are not the same objects but still have the same type, name and values, the conversion fails. Consequently, models can't be used when the domain on the test set is constructed anew rather than composed of the same variable objects.

**Orange version:**
3.23.1 (current master branch)

**Expected behavior**
I believe that a more common `==` type comparison should be implemented for domain variables.

**Comment by janezd** [comment]
On master branch it prints `[<function DomainConversion.__init__.<locals>.match.<locals>.<lambda> at 0x1273d6b90>, <function DomainConversion.__init__.<locals>.match.<locals>.<lambda> at 0x1273d6cb0>]`. Are you sure you're looking at the current master? #3925 made some huge changes to how variables are compared, and models should now work in much more complex scenarios.

Line 353 in Orange/data/variable.py (https://github.com/biolab/orange3/blob/774c4be7e172d730b301646ef3732967018c18b3/Orange/data/variable.py#L353) uses `is` to compare types (within `Variable.__eq__`).

**Comment by vpodpecan** [comment]
You are right. The latest version on PyPi at the moment (3.23.1) exhibits this behaviour while in the the master branch this is fixed. I think this issue can now be closed.

Incidentally, I found another small bug. If an empty table is created, an exception will happen when pretty-printing it (the nonexisting X attribute is referenced):
```python
import Orange
a = Orange.data.Table()
a  # or print(a)
```

**Comment by janezd** [comment]
Thanks. I moved the bug to a new issue.
