### ISSUE TITLE
Aggregate widget (not time-series only) with group-by option

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3#4227]
It is often useful to aggregate data items by zooming out on the time scale for time-series data (e.g., per day, per hour), but also for time-series and other data based on one of the columns that has recurring values (e.g. aggregate by user ID, product ID). This is now a cumbersome job in Orange, see my discussion on the Discord Support forum with Ajda, starting 24 Nov 2019 16:51

An aggregate widget similar to what RapidMiner offers could be a good solution, https://docs.rapidminer.com/latest/studio/operators/blending/table/grouping/aggregate.html

Alternatives and screenshots: see discussion on Discord.

**Comment by ajdapretnar** [comment]
My apologies. Pivot widget actually supports this. You just need to use the Grouped Data output. Like this for iris:

<img width="1124" alt="Screen Shot 2019-11-28 at 10 41 20" src="https://user-images.githubusercontent.com/12524972/69795016-a9060a00-11cb-11ea-90f8-ab9bce35a970.png">

**Comment by wvdvegte** [comment]
You're completely right, I've used that before. I remember it was hard to find.
So, actually, the only things that remain are

1. having a widget to manipulate date-time variables (e.g. extracting the date from date-time) that is more straightforward than having to use code like "day:=str(date_time)[:-9]", and
2. having a widget to convert categorical variables to 1-0 type columns for each of the possible categories, so that the number of 1's for each category can be counted by the time-series Aggregate widget.

Do you think those two would be worth a feature request?

**Comment by ajdapretnar** [comment]
Number 2 already exists. In Continuize use 'One attribute per value'.

**Comment by wvdvegte** [comment]
OK, nice!
