### ISSUE TITLE
Option to selectively normalize features, each individually in the most appropriate way

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3#4228]
Normalizing features can be done in the Preprocessing widget, but the only option is to normalize all numerical feautures, and all of them in the same way. If for instance, I have one feature with values ranging from -100 to +100, another ranging from 0 to 1000 ansd yet another one that is already normalized, I have to split up the dataset and merge it back after normalization. This is cumbersome.

**Comment by janezd** [comment]
Why would you like to have different normalizations for different features? For instance, the widget currently normalizes to [0, 1] or [-1, 1]. And you'd like to have the option to normalize features to different intervals? Can you describe a scenario where this would be useful?

The discretization widget supports something like this, but I doubt anybody uses this functionality.

**Comment by wvdvegte** [comment]
My understanding has been that normalization to [-1,1] is useful for features that can have both positive and negative values and where 0 means something like “neutral”, while [0,1] is useful for features that can only have positive values and where 0 means something like “nothing”. Consider two features velocity and weight, where velocity can be negative, corresponding to “going backwards”. If we normalize both to [0,1], the distinction between forwards and backwards gets lost in the case of velocity. If we normalize both to [-1,1], and let’s assume that the weight feature has no samples with zero weight, there is no way to find out which normalized value would correspond top weightless (actually it’ll be a value < -1).
For instance, if you do linear regression, in both examples, the case where the intercept (or offset) is zero has a special meaning which also goes lost after the “wrong” type of normalization.
 
I will check out the discretization widget, thanks.

**Comment by janezd** [comment]
If velocities appearing in the data are between -20 and 50, you would like to normalize it to [-1, 1] so that negative velocities would have negative normalized values? How would that work!? Would the scale be different for negative and positive?

**Comment by wvdvegte** [comment]
I'm not at all an expert on normalization, but I would expect, in that case, the normalization to work as follows:

Find the largest absolute value, maxabs, in this case maxabs = 50
map -maxabs to -1, +maxabs to +1, and 0 to 0

Thus -20 would normalize to -0.4, and 50 would normalize to 1, and 0 would retain its meaning corresponding to motionless.

**Comment by janezd** [comment]
Huh, I never saw such normalization.

Why would this be useful? It doesn't bring features to the same scale (because symmetric features would have larger span of normalized values). Which machine learning or statistical method would need such kind of normalization?

**Comment by wvdvegte** [comment]
Actually I vaguely remember having seen cases where the interval [-0.5,0.5] was used rather than [-1,1] - which would make sense.
Since, admittedly, I don't know a lot about normalization, I started looking round and was surprised that I hardly could find any literature that suggests best practices.
I guess my request was motivated by a desire to preserve the explainability of regression models, but why normalize if you want to explain the coefficients? And, after all, [regression is insensitive to normalization](https://towardsdatascience.com/understand-data-normalization-in-machine-learning-8ff3062101f0) so let's forget about it.

**Comment by markotoplak** [comment]
I'd say regression stops being insensitive to normalization as soon as you use any kind of regularization, because features with a greater span are going to be regularized more strongly.

**Comment by wvdvegte** [comment]
Yes, of course, in that case you can end up with both very large and very small coefficients. I guess the point is that the point of that statement was that the algorithm that has to find the coefficients won't be faster if you normalize, nor will the outcomes be more accurate (in the sense that 1.23E9 and 1.23E-9 have the same number of significant digits)
