### ISSUE TITLE
Copy-pasting a selection of widgets to another open workflow

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3#4236]
**Is your feature request related to a problem? Please describe.**
Reusing partial workflows doesn't seem easy because widgets can only be copy-pasted (duplicated) into the workflow where they already exist

**Describe the solution you'd like**
Being able to copy-paste selected widgets with their connections to another workflow that is open

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by irgolic** [comment]
This was implemented in https://github.com/biolab/orange-canvas-core/pull/33, and will be included in the next release.
