### ISSUE TITLE
Orange main window does not show anything

### ISSUE THREAD

**Issue by oco27** [biolab/orange3#4239]
The main windows does not show anything when opening a workflow. It looks like it is only a drawing problem because if i click on areas where i guess there should be something (like the menu bar), action works (main menu, popup menu). 

It was already there with 3.22. Then i have installed 3.23.1. It has work for a few days and suddenly it has stopped working again. Maybe it was after reducing the size of the main Window and then restoring the original position.

My computer has two screens with different resolutions.

All modal windows show up properly (from the menu or from popup menu when guessing object positions).

**To Reproduce**
I don't know exactly how to reproduce, but once the problem is there it happen all the time.

**Orange version:**
Orange - About - version number.

**Screenshots**

Main window after opening a workflow.

![OrangeMainWindow](https://user-images.githubusercontent.com/15720028/69884752-25870e80-12da-11ea-918c-18b092c3753f.PNG)

**Operating system:**
Windows 10

**Additional context**
[OrangeLog.txt](https://github.com/biolab/orange3/files/3906123/OrangeLog.txt)
[canvas.log](https://github.com/biolab/orange3/files/3906136/canvas.log)

**Comment by ajdapretnar** [comment]
Please add how you installed Orange.
If you installed it via the installer, please open Orange Command Prompt, run `pip freeze` and post the output here. Thank you.

**Comment by oco27** [comment]
It was installed with the installer. 

Here is the result of pip freeze in the Orange Command Prompt :
[Pip_freeze.log](https://github.com/biolab/orange3/files/3923198/Pip_freeze.log)

I have tried to uninstall and reinstall, without any difference.

**Comment by markotoplak** [comment]
So, if I understand correctly, this problem already appeared with 3.22? Or is it new to 3.23.1?

**Comment by ajdapretnar** [comment]
I was looking for a clue on Qt/PyQt version, but it's entirely lacking in the log. How about you run
`pip install PyQt5 PyQtWebEngine` in the Orange Command Prompt?

**Comment by ajdapretnar** [comment]
Sorry, one more request. Could you also post `conda list` output?

(Please ignore my previous post.)

**Comment by oco27** [comment]
Here is the "conda list" command result :
[conda_list.log](https://github.com/biolab/orange3/files/3926709/conda_list.log)

**Comment by markotoplak** [comment]
@oco27, thanks. Can you try "conda install pyqt=5.12"? That is the version of pyqt that is going to be distributed with the new release.

What are the resolutions of your two screens?

**Comment by oco27** [comment]
I know : resolutions are a bit odd :

 - 1600 * 900 (16/9) (on the left)
 - 1280/1024 (4/3) (on the right)

One thing i forgot to mention : the "main" screen for Windows is the one on the right. We have found bugs related to this in our own software.

Here is the result of conda install pyqt=5.12. There is a conflict.
I have tried with conda install pyqt=5.12 --update-deps without success too (i am not familiar with conda though : might not be the right command to force the update of dependencies) :

[Conda_install.txt](https://github.com/biolab/orange3/files/3927135/Conda_install.txt)

**Comment by ajdapretnar** [comment]
I was dealing with the same issue recently. I have to manually update icu and one other dependency I can't remember. I would say `conda update --all`, but this could break the environment even further... 🤷‍♀ I can check specifically what I did to solve it.

**Comment by ajdapretnar** [comment]
I tried reproducing this with 1280/1024 screen and pyqt=5.9.2 on a Win machine, but it didn't work. I might be missing something...

**Comment by oco27** [comment]
Finally found the reason : i completely forgot to specify that i used this computer through a distant connection (mstsc.exe). It has definitively work with both 3.22 and 3.23.1 using this setup though. Maybe it was a windows update that has changed the behavior ?
At least, drawing is OK now with a physical screen attached...

**Comment by janezd** [comment]
This seems like a Qt problem, so it's beyond what we can control. I guess we can close the issue.
