### ISSUE TITLE
Continuize "one class per value" does not work if n_classes=4

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3#4243]
**Describe the bug**
When trying to use the continuize widget for _one-hot encoding_ of a categorical variable that has four possible values, columns are created for only three of the values 

**To Reproduce**
The enclosed example convincingly shows what's going wrong
[Workflow with input file.zip](https://github.com/biolab/orange3/files/3916946/Workflow.with.input.file.zip)
![Screenshot 2019-12-03 at 14 50 01](https://user-images.githubusercontent.com/55989717/70057421-671b0080-15dd-11ea-9ba0-6ad857a4a4b2.png)

**Orange version:**
3.23.1

**Expected behavior**
In the example above, there should have been an additional column for category-A

**Screenshots**
See above

**Operating system:**
Mac OSX 10.14.6

**Comment by ajdapretnar** [comment]
The categorical variable in your case is not an outcome (target variable), but a regular categorical variable, which is continuized with 'First value as base'. This works as expected.

**Comment by wvdvegte** [comment]
OK, sorry for overlooking this distinction. But basically this means "no column for the first value" (which was A in the example above). I see this mostly works as expected but in this case it's the third occurring value that gets no column (this one got me confused in the first place):
![Screenshot 2019-12-04 at 09 58 43](https://user-images.githubusercontent.com/55989717/70128474-2a9ee180-167d-11ea-8753-c0a3db7669cb.png)
?

**Comment by ajdapretnar** [comment]
First value sorted alphabetically.

**Comment by wvdvegte** [comment]
Oh, Ok, thanks. Perhaps that could be explained a bit better in the widget's help window ...
