### ISSUE TITLE
Random Forest: output feature importance

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#4246]
Who doesn't love explainable models?

While Naive Bayes, Logistic Regression and Tree can already be interpreted, I believe RF could be as well. We already provide the option to score features in Rank with RF. Perhaps an output to the model with ranked features would be a welcome addition?

I read that sklearn's models provide `feature_importances_` property which we could potentially use as an output.

Just an idea.

**Comment by janezd** [comment]
Isn't this exactly the information you get by connecting Random Forest to Rank?

Just as trees can be interpreted via Tree Viewer, random forests can be interpreted via Pythagorean Random Forest (kind of).

Learning algorithms in Orange generally don't output feature scores (with exception of Logistic regression). If Random Forest output scores, then also Bayes would have to output ... something.

**Comment by ajdapretnar** [comment]
I checked the code for scorer and it is exactly what it does. It just never occurred to me to explain RF via Rank until now. We can close this, I guess.
