### ISSUE TITLE
Wrong conversion for NaNs in table, created from csv file

### ISSUE THREAD

**Issue by itslarin** [biolab/orange3#4260]
**Describe the bug**
Data table, created from csv file has wrong representation for undefined value

**To Reproduce**
1. Use Titanic train dataset (https://www.kaggle.com/c/titanic/download/train.csv)
2. In Orange use 'CSV file import', connect it to 'Python script' (Data -> Data)
3. In script type:
3.1 tab=in_data.copy()
3.2 tab[61]
3.3 tab.metas[61]
4. See error - the value for 'Embarked' column is recognised as ? in 3.2, but considered to be '' (empty string) in 3.3. If u connect 'CSV File Import' to 'PythonScript' with Object -> Object link, the resulting dataframe will show this row with NaN value, what i believe is correct.

The wrong interpretation of value in tab.metas leads to wrong results if u convert data table into dataframe with table_to_frame function, where u will have empty string as a value instead of NaN

**Orange version: 3.23.1
Orange - About - version number.

**Expected behavior**
I believe there should be NaN in tab.metas

**Screenshots**

**Operating system:**
Windows. 7x64

**Additional context**
The example is based on Titanic train set, it is row with PassengerID = 62

**Comment by janezd** [comment]
```
tab=in_data.copy()
print(tab[61])
print(tab.metas[61])
```

outputs

```
[62, 1, 1, female, 38.00, 0, 0, 80.0000, ?] {Icard, Miss. Amelie, 113572, B28}
['Icard, Miss. Amelie' '113572' 'B28']
```

This is correct. You will get an empty string for string variables, which is again correct: Orange represents unknown strings by empty strings, not by strings `"?"` (which could be a legal, known strain). If Orange 3.2 behaved differently in some circumstances, this would be a bug, though I'd doubt it because this representation of unknown strings is not new.

Have you changed your data so that Embarked is a string?

> I believe there should be NaN in tab.metas

It can't be: string variables are not stored as floats.

**Comment by itslarin** [comment]
Hi, Janezd. Thanks for ur reply. First of all i need to say that we have different reproduction of this issue.

When i run python script with the same code like you posted, i have this output:

>>> 
Running script:
[62, 1, 1, 38, 0, 0, 80] {Icard, Miss. Amelie, female, 113572, B28, ?}  (for print(tab[61]))
['Icard, Miss. Amelie' 'female' '113572' 'B28' ''] (fro print(tab.metas[61]))

Here you can see, that unknown value is shown as undefined when i call tab[61] and represented as empty string when i call tab.metas[61]

I suppose the general question is - should the function from pandas_compat module reproduce pandas behaviour. Because when you use pandas read_csv function with default params it will consider empty value as NaN.


>>Have you changed your data so that Embarked is a string?
Could you please clarify what do you mean, please. 

Thank you

**Comment by janezd** [comment]
Oh, I see. It's just a question of how it's printed out.

Unknown value is stored as an empty string. The second print shows you this -- because you are directly printing out the row from the matrix.

But when you print out a data instance, Orange prints it out a bit differently and shows an unknown value as ?.

>> Have you changed your data so that Embarked is a string?

> Could you please clarify what do you mean, please.

I couldn't reproduce this because your data is apparently different from mine: Embarked is not stored as categorical variable with three value but as text.

**Comment by janezd** [comment]
> I suppose the general question is - should the function from pandas_compat module reproduce pandas behaviour. Because when you use pandas read_csv function with default params it will consider empty value as NaN.

Orange understands empty values as unknown. Pandas reads them into NaN, which is the same. But it depend upon the type of the variable and upon what are you going to do with this data.

**Comment by itslarin** [comment]
Allow me please to downgrade the situation to an exact case, that might avoid some possible confusion.

My case is  - I made an attempt to work with titanic dataset in Orange. Before that i used Jupyter notebook.

1. When working with notebook i downloaded the dataset from csv file and the resulting dataframe showed me that i have 2 NaNs in Embarked column. Which i can impute with moda or remove rows or make smth else to prepare my dataset for further work.

2. When i started my work with orange i realised that missed values from Embarked positions of csv have been transformed into empty strings what brings totally different meaning to the dataset - it can be interpreted as 4 discrete categorical values as well.

If i want to use Orange tools and transform table into frame and back for usability purposes i might get stuck with problem of having two different (in minor) datasets after such transformations:

In scenario 1 i read csv file with pandas and get frame with 2 NaNs in Embarked column 3 distinct values ('S','C' and 'Q')

In scenario 2 i read the same csv file with Orange into table and transform table into frame and get Embarked column with 4 disctinct values: 'S','C','Q' and ''

And - the most important moment - if i connect 'import from csv' block with 'python script' block by 'dataframe-object' link, i will get frame with 2 NaNs in Embarked again. So i have different dataframes in Orange  from the same file depends on what tools i use

What is recommended way for such situation? I was expekting to get completely the same frames in all 3 cases. Maybe there should be some parameter in the function to manage the behaviour?

**Comment by janezd** [comment]
I don't know which CSV are you using. The link that you posted doesn't work so I downloaded one (of many) files with Titanic from Kaggle. It works for me. Can you attach the file, please?

**Comment by itslarin** [comment]
Sure, sorry for incorrect link

[titanic.zip](https://github.com/biolab/orange3/files/3961640/titanic.zip)
