### ISSUE TITLE
portable version for Windows?

### ISSUE THREAD

**Issue by jawz101** [biolab/orange3#4264]
**Is your feature request related to a problem? Please describe.**
I work in an environment that is strict on software installation priveleges.  Easier to use portabalized versions of software

**Describe the solution you'd like**
A portable (self-contained) packaging of Orange.  A popular, example distribution might be PortableApps

**Describe alternatives you've considered**
Maybe Chocolatey?  I don't know if you can set up a chocolatey instance completely as a non-administrator user

**Additional context**
https://portableapps.com
https://chocolatey.org

**Comment by thocevar** [comment]
I used our standalone miniconda installer to install Orange and selected the "install just for me" option. After a successful installation I tried to move the installation folder around. Qt breaks but I only had to change the absolute paths in `qt.conf` to relative paths (e.g. "./Library") to fix it. I also created an `Orange.bat` file to launch the application with `pythonw.exe -m Orange.canvas` as an alternative for the broken shortcuts. I managed to install an add-on, move the entire Orange folder to a different Windows instance and it still works.

I guess we can automate this and provide a zipped Orange folder as a portable Windows version.

**Comment by matjazp** [comment]
> I used our standalone miniconda installer to install Orange and selected the "install just for me" option. After a successful installation I tried to move the installation folder around. Qt breaks but I only had to change the absolute paths in `qt.conf` to relative paths (e.g. "./Library") to fix it. I also created an `Orange.bat` file to launch the application with `pythonw.exe -m Orange.canvas` as an alternative for the broken shortcuts. I managed to install an add-on, move the entire Orange folder to a different Windows instance and it still works.
> 
> I guess we can automate this and provide a zipped Orange folder as a portable Windows version.

Great! This is simpler and thus a better solution than portableapps distribution, imo.

**Comment by thocevar** [comment]
Another pitfall is the location of widget settings. From my experiments it's a matter of setting  `__WIDGET_SETTINGS_DIR` in `orange-widget-base/orangewidget/settings.py`. What's inconvenient is that it's a different package.

**Comment by ales-erjavec** [comment]
Closed by https://github.com/ales-erjavec/orange3-installers/commit/6c6c4ab6ee2694b2269bb1cf6c102a27d1c67630
