### ISSUE TITLE
kNN: domain transformation produced no defined values

### ISSUE THREAD

**Issue by huangkai31** [biolab/orange3#4268]
**Describe the bug**
After use kNN save a model, by using the load model to predicate some data 
The predictions widget get an error and can't predicte result:
One or more predictors failed (see more...)
kNN: domain transformation produced no defined values

**To Reproduce**
Please download the  ows and dataset here:
https://github.com/huangkai31/learningorange/tree/master/knn

**Orange version:**
3.19.0

**Expected behavior**
it should predicate the result with the load model

**Screenshots**
https://github.com/huangkai31/learningorange/blob/master/knn/knn1.jpg
https://github.com/huangkai31/learningorange/blob/master/knn/knn2.jpg

**Operating system:**
MacOS 10.13.6

**Comment by janezd** [comment]
The workflow is incorrect. Don't do this:

<img width="532" alt="Screenshot 2019-12-16 at 12 17 32" src="https://user-images.githubusercontent.com/2387315/70902933-1accb900-1ffe-11ea-805c-5487db2804ed.png">

Do this:

<img width="516" alt="Screenshot 2019-12-16 at 12 17 48" src="https://user-images.githubusercontent.com/2387315/70902948-1f916d00-1ffe-11ea-8770-0c1dfa38aa8d.png">

When kNN is used on test data, feature selection and normalization (or other preprocessing) you've done on training data is applied automatically.

You are preprocessing testing data in a different way than training data (at least in principle), so this data is no longer comparable to the one on which you trained knn. For instance, if preprocessing normalizes it, normalization is going to be different for the testing data, which will degrade knns performance.
