### ISSUE TITLE
Transpose widget: Should feature variable not be in a data?

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/orange3#4273]
When one transposes data with the transpose widget and selects `from variable` option for feature names, the variable selected for feature names is still in the data. When I am thinking about possible cases I think this variable should be removed from data. What do you think? Is there a case where it is good to have this variable in data?

**Comment by ajdapretnar** [comment]
I am not sure what you mean 'in the data'. From what I see, it is the attribute of attributes, no? In case of zoo, these are the name and the type. We were just discussing this yesterday and we had a use case where it was necessary to transpose the data twice. In the second transpose, it would be impossible then to retrieve these attributes. I am not sure this works atm, but it probably should? Probably @Hrovatin can give more details.
