### ISSUE TITLE
PREDICTIONS function not accepting learner.

### ISSUE THREAD

**Issue by siddhantwade** [biolab/orange3#4274]
**Describe the bug**
I am trying to produce predictions on a banking data using various learners that have been trained on the training set which i created using the DATA SAMPLER function.

**Orange version:**
3.23.1

**Expected behavior**
As the youtube tutorial for this steps suggests, I should be able to obtain model predictions against my test data sample. 
link: [https://www.youtube.com/watch?v=D6zd7m2aYqU](url)

**Screenshots**
![orange sc](https://user-images.githubusercontent.com/20797807/71070268-6dde7180-21a0-11ea-9f8b-5158867351d9.PNG)

**Operating system:**
Windows 10.

**Comment by ajdapretnar** [comment]
Predictions widget never was accepting a learner, always a model. Please watch the video carefully.
