### ISSUE TITLE
Should we remove the Mahalanobis distance from the Distances widget?

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/orange3#4277]
Before on a meeting with @lanzagar and @BlazZupan we discussed that Mahalanobis distance should be removed from the Distance widget. The problem appears when someone accidentally clicks at this distance in the dropdown. On slightly bigger data Orange takes a long time to compute the Mahalanobis distances and there is no other option than to restart the Orange in order to continue with work.

**Comment by janezd** [comment]
What if the widget checked the dimensionality before computing, and if it's too high, it shows an error?

I'd like to keep the Mahalanobis distance for education purposes.

**Comment by PrimozGodec** [comment]
I think it is a good solution.
