### ISSUE TITLE
Widgets gets weird auto reset 

### ISSUE THREAD

**Issue by leon90dm** [biolab/orange3#4278]
**Describe the bug**

When i put several "Select Rows" widgets after a "Select Column" widget, Nearly every time
i do something change in "Select Column" widget such as Moving one column to "meta"
every "Select Rows" widgets get reseted to arbitrary condition, and I have to set old condition
each by each. It's is not sweet and fun!

**To Reproduce**
1. put a "File" or "Select Column" widget
2. put "Select Row" widget after "File" or "Select Column" widget and make some filter condition
3. do some change in "File" or "Select Column" widget, such as changing column type or move column to filter etc.
4. See conditions in "Select Row" widget changes to something else without letting you know :(

**Orange version:**
Orange 3 

**Expected behavior**
Every rules user made in widgets should stay what they are, Even If some error will happen after user 
change those settings such as losing some columns, widgets should raise up information to notice User rather than automatically resetting to something else

**Screenshots**
![image](https://user-images.githubusercontent.com/5271193/71144300-8316d700-2258-11ea-9739-dc0cf553732a.png)

**Operating system:**
 OSX 10.15.1 (19B88)

**Additional context**

**Comment by janezd** [comment]
Thanks for reporting, but I can't replicate this. Is it possible that these conditions come from some old workflows? Orange remembers old conditions and tries to reuse them when possible, if the current set of conditions cannot be applied to the newly arrived data.

That said, this widget did indeed have problems with retrieving settings, which were fixed last week in #4254. This part has been written anew, so the problem should disappear in the next release.
