### ISSUE TITLE
Orange 3.24 fails to start on Mac OS X El Capitan (10.11.6)

### ISSUE THREAD

**Issue by fmoncomble** [biolab/orange3#4323]
The latest version of Orange (3.24), installed from the Mac Bundle, does not start on my iMac late 2009 running OS X 10.11.6 El Capitan: the icon bounces a couple of times in the Dock, the process appears briefly in the Activity Monitor, but does not launch.

No crash report is generated.

Running `/Applications/Orange3.app/Contents/MacOS/pip install pyqt5==5.12.3 pyqtwebengine==5.12.1` does not work ('Requirement already satisfied')

Running `/Applications/Orange3.app/Contents/MacOS/Orange -l4` yields the following output:

> Traceback (most recent call last):
>   File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 183, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 109, in _get_module_details
>     __import__(pkg_name)
>   File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/__init__.py", line 30, in <module>
>     from AnyQt.QtCore import QObject
>   File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/AnyQt/QtCore.py", line 247, in <module>
>     from PyQt5.QtCore import *
> ImportError: dlopen(/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyQt5/QtCore.so, 2): Symbol not found: __os_activity_create
>   Referenced from: /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (which was built for Mac OS X 10.12)
>   Expected in: /usr/lib/libSystem.B.dylib
>  in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore

**Comment by ales-erjavec** [comment]
Qt 5.9 is the last Qt release that supports El Capitan. You can try:
```
/Applications/Orange3.app/Contents/MacOS/pip install pyqt5~=5.9
```

**Comment by fmoncomble** [comment]
Thank you! Here's the output:

> /Applications/Orange3.app/Contents/MacOS/pip install pyqt5~=5.9
> Requirement already satisfied: pyqt5~=5.9 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (5.12.3)
> Requirement already satisfied: PyQt5_sip<13,>=4.19.14 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pyqt5~=5.9) (12.7.0)

So unfortunately the issue remains…

**Comment by ales-erjavec** [comment]
Sorry, that should have been:
```
/Applications/Orange3.app/Contents/MacOS/pip install pyqt5~=5.9.0
```

**Comment by fmoncomble** [comment]
Thank you very much Ales.

There was an error in the output:

> ERROR: pyqtwebengine 5.12.1 has requirement PyQt5>=5.12, but you'll have pyqt5 5.9.2 which is incompatible.
> Installing collected packages: sip, pyqt5
>   Found existing installation: PyQt5 5.12.3
>     Uninstalling PyQt5-5.12.3:
>       Successfully uninstalled PyQt5-5.12.3
>   WARNING: The scripts pylupdate5, pyrcc5 and pyuic5 are installed in '/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/bin' which is not on PATH.
>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
> Successfully installed pyqt5-5.9.2 sip-4.19.8
but Orange launches anyway.

However, I seem to be missing widget categories:
![Screen Shot 2020-01-11 at 19 47 02](https://user-images.githubusercontent.com/59739627/72209114-3dda7380-34ab-11ea-9d3c-f621699b84b9.png)
I only get the first five categories, no sign of the other ones. Any ideas?

**Comment by fmoncomble** [comment]
Thanks a lot Ales, working perfectly!
