### ISSUE TITLE
Testing: switch to tox

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#4324]
`python setup.py test` issues a warning:
`WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.`

We should look into tox and see how to test with it.

**Comment by ajdapretnar** [comment]
https://tox.readthedocs.io/en/latest/

**Comment by JakaKokosar** [comment]
related issue https://github.com/pypa/setuptools/issues/1684
