### ISSUE TITLE
Python stops working

### ISSUE THREAD

**Issue by Norsusan** [biolab/orange3#4325]
Orange3 Version 3.21 Windows 7 32 bit 

Error:broker_win.cc(59) Error reading broker pipe: The pipe has been ended, (0X6D)

![image](https://user-images.githubusercontent.com/29728592/72255899-e7b61f00-35d5-11ea-949f-9c32dc360c95.png)

I get this error also on Orange3 3.24 Windows 7 32 bit when accessing widget help.

**Comment by ales-erjavec** [comment]
How did you install orange3 on 32-bit windows? With pip?

Which version of 'PyQt5'  and 'PyQtWebEngine' are installed in the environment from which you are running orange (run `python -m pip list` and look for the version)?

**Comment by Norsusan** [comment]
Hello,

 

I installed Orange3 3.21 using the download from the Orange3 website.

The software installs Python36-32 and Orange3 3.21.

 

I installed Orange3 3.24  by first installing Python37-32, creating a Python environment using venv, installing numpy-1.16.5-cp37-cp37m-win32.whl, 

Installing Orange3-3.24.0-cp37-cp37m-win32.whl and installing other requirements.

 

I installed each on a different Windows 7 32 bit computer.

 

Norm

 

Norman Abraham CFP

Tel: (613) 261-0947

Email:  <mailto:norman.abraham@teksavvy.com> norman.abraham@teksavvy.com

              <mailto:risk.analytics@teksavvy.com> risk.analytics@teksavvy.com

Web:   <http://www.riskanalytics.ca/> www.RiskAnalytics.ca

“Think Outside The Box”

**Comment by Norsusan** [comment]
Orange3 3.21 and Orange3 3.24

**Comment by ales-erjavec** [comment]
I cannot duplicate this.

You can force the help pages to open in an external browser. Go to *Options* -> *Settings*, open the  *Output* tab and check the *Help window*: *Open in external browser* option.

**Comment by ajdapretnar** [comment]
I would also add that we no longer support 32-bit Orange, so, unfortunately, you're on your own with this one.

**Comment by Norsusan** [comment]
Thank you ales-erjavec, your suggestion "You can force the help pages to open in an external browser. Go to Options -> Settings, open the Output tab and check the Help window: Open in external browser option" worked perfectly to correct the problem with Orange3 3.21 & 3.24. 

When I installed 3.21, I did not check that option.

When I built 3.24, I did not check that option.

Again thank you very much for your help.

**Comment by Norsusan** [comment]
Thank you ales-erjavec, your suggestion "You can force the help pages to open in an external browser. Go to Options -> Settings, open the Output tab and check the Help window: Open in external browser option" worked perfectly to correct the problem with Orange3 3.21 & 3.24. 

When I installed 3.21, I did not check that option.

When I built 3.24, I did not check that option.

Again thank you very much for your help.
