### ISSUE TITLE
Topic modelling and MDS

### ISSUE THREAD

**Issue by GottM** [biolab/orange3#4332]
Re: [Topic modelling widget documentation](https://orange.biolab.si/widget-catalog/text-mining/topicmodelling-widget/).

The workflow described in this help page does not work as expected. The topic modelling widget does not output 5 topics but 3719 instances through the "All Topics - Data" link. Thus, the MDS link does not behave as shown in the help page.

Orange version: 3.24.0
Operating system: Windows 7 - 64 bit

Regards,
G.

**Comment by ajdapretnar** [comment]
Yes, sorry about that. Will be fixed with the new release of Text. Upcoming in the following two weeks.

**Comment by GottM** [comment]
Ok, great!
