### ISSUE TITLE
Visualizations do not work with pyqtgraph 0.11.0 release candidate

### ISSUE THREAD

**Issue by SamiurRahman1** [biolab/orange3#4336]
**Describe the bug**
After successful installation of orange3, when visualization tools such as scatterplot, line plot, distributions widget are opened, even without connecting them to a dataset, they throw an error of some sort.

**To Reproduce**
1. Open orange canvas
2. Right click to add a new widget in the workflow
3. Select scatter plot or distributions or line plot
4. See the error

**Orange version:**
Orange version 3.24.0

**Expected behavior**
Functioning scatter plot when dataset is provided.

**Screenshots**
![image](https://user-images.githubusercontent.com/59823980/72524434-3c6dca00-3862-11ea-91ce-6e8bf3fb8ea3.png)

**Operating system:**
Ubuntu 18.04

**Additional context**

**Comment by markotoplak** [comment]
We had some similar error reports. I strongly believe you have pyqtgraph version 0.11.0rc0 installed. As of yet, this version is not supported in Orange.

Until Orange supports 0.11.0, please install version 0.10.0 for new, perhaps with `conda install pyqtgraph=0.10.0`.

**Comment by SamiurRahman1** [comment]
Hello! Thank you so much. It really solved my problem.. really appreciate your help. :)

**Comment by markotoplak** [comment]
@SamiurRahman1, thanks. I am leaving this open until we have a permanent solution.

**Comment by markotoplak** [comment]
The pyqtgraph issue directly connected with this report has been noted in pyqtgraph/pyqtgraph#1094 and solved in its develop branch, but this is not the only problem.

**Comment by markotoplak** [comment]
Another pyqtgraph issue has an open PR pyqtgraph/pyqtgraph#1063.

**Comment by janezd** [comment]
(Copied from #4468, written by @markotoplak)

Line plot tests fail in pyqtgraph 0.11 pre-release.

At least one of the bugs can be solved upstream (there is a PR in pyqtgraph pyqtgraph/pyqtgraph#1063), but as they are not that keen on accepting PR, we should try to avoid it.

They are some other fails which should be checked.
