### ISSUE TITLE
Workflow text annotation styles

### ISSUE THREAD

**Issue by Hrovatin** [biolab/orange3#4341]
Currently, there is an option to add text to Orange workflows. However, there is only one size/colour of  text. Thus all the annotations seem equally important although when preparing a workflow this is rarely the case. It would be very beneficial if there was an option to change at least size of the text for different annotations and possibly the colour as well. The use of markdown would be an option.

**Comment by ajdapretnar** [comment]
I think this issue belongs to [orange-canvas-core](https://github.com/biolab/orange-canvas-core).
