### ISSUE TITLE
Pythagorean tree labels

### ISSUE THREAD

**Issue by GottM** [biolab/orange3#4347]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by GottM** [comment]
Hello,
Pythagorean trees are an awesome way to display decision trees, I love it. I think it would be even greater if Orange Biolab would enable labeling of square surfaces and vertices of decision triangles. Labels would contain the same info seen when hovering over the pythagorean tree : what split is a given square about, respectively what split option is shown by a given triangle vertex (to the next square). This would save the hovering and enable explicit printouts of the tree. I hope you like the idea... Thank you in advance!

**Comment by irgolic** [comment]
Maybe if there were an info box in the sidebar displaying the tooltip contents.

I keep a personal list of stuff I want to fix in Orange, here's my list for Pythagorean Tree/Forest if anyone feels like having a go at it:

-

**Comment by GottM** [comment]
Thank you @ajdapretnar 
Your concern about the tiny final squares surely makes sense and is a challenge. I can see a number of non exclusive turnarounds for this :
• only filling in the large (enough) squares
• putting arrows to tags outside but next to the squares (at least for tiny squares)
• writing just ref. numbers in or next to the squares and adding an info box with details

Somehow, if one wants to share the tree with someone in print, in an email or a slideshow, one will surely do something like that by hand, otherwise one loses a critical part of the info. Well that's what I think...

**Comment by thocevar** [comment]
We could consider adding the information from the tooltips to the report that can be generated if someone wants to share such visualization. I see two ways to do this:
- Add reference numbers to the picture and extend the report with a list of tooltip data for each reference number.
- Don't change the visualization and instead extend the report with another (concise but not visually pretty) structural representation of the tree that would include required data.

**Comment by janezd** [comment]
We also discussed this last week. This visualization was meant to get an insight into shapes of very large trees or a forest. In this cases you can't (and don't even want to) know and check properties of individual nodes. I don't think you want to have such trees in a slide show, the talk would be too long. :) You can however export the image and annotate the interesting nodes manually.

For smaller trees, you can use the standard tree viewer.
