### ISSUE TITLE
Installtion via pip fails

### ISSUE THREAD

**Issue by ftastisch** [biolab/orange3#4348]
**Describe the bug**
Trying to install orange3 via pip. llvmlite is alreasy installed, but during installation of orange3 rollback to older version is started and fails.

**To Reproduce**
1. Use out of the box Manjaro
2. Install LLVM
3. Create virtual environment
4. try pip install orange3
5. See error

**Orange version:**
n/a

**Expected behavior**
Installation of orange3.

**Screenshots**
Error Message:
ERROR: Command errored out with exit status 1: /home/user/orange_env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-r1_v1jxz/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-r1_v1jxz/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-nbew1q7u/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/orange_env/include/site/python3.8/llvmlite Check the logs for full command output.

**Operating system:**
Linux, Manjaro

**Comment by NejcDebevec** [comment]
@ftastisch I can't reproduce the error. Maybe there were some problems when the new version was released and now the problem is already fixed. Please try again and let us know.
