### ISSUE TITLE
tSNE and numba

### ISSUE THREAD

**Issue by rhinsall** [biolab/orange3#4353]
tSNE has stopped working (which is a pity, it's fabulous) - it crashes with the error:

Exception: | numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend) scalar type Tuple() given for non scalar argument #4 File "anaconda3/envs/env2/lib/python3.7/site-packages/pynndescent/pynndescent_.py", line 93: def initialized_nnd_search( <source elided> for i in numba.prange(query_points.shape[0]): ^ [1] During: lowering "id=0[LoopNest(index_variable = parfor_index.37, range = (0, $14binary_subscr.5, 1))]

I've checked by reinstalling Orange in a new environment - seems to be permanent.

Using a current Ubunbtu install

**Comment by ajdapretnar** [comment]
Which version of numba are you running?

**Comment by rhinsall** [comment]
Have tried both 0.47 and 0.45 (to see if a recent update broke it)

Sent from my iPhone

On 22 Jan 2020, at 08:15, Ajda <notifications@github.com> wrote:

﻿

Which version of numba are you running?

**Comment by ajdapretnar** [comment]
Thanks! We will check.

**Comment by rhinsall** [comment]
Seems to be Linux specific - still works on my Mac.  The big GPU is on the Linux though.

Sent from my iPhone

On 22 Jan 2020, at 08:37, Ajda <notifications@github.com> wrote:

﻿

Thanks! We will check.

**Comment by pavlin-policar** [comment]
Sorry for the late reply. Does this issue still persist? If so, could you please paste a dump of your environment `pip freeze` and `conda list` if you're using conda.

**Comment by rhinsall** [comment]
I’ll have a look


On 14 Feb 2020, at 18:48, Pavlin Poličar <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry for the late reply. Does this issue still persist? If so, could you please paste a dump of your environment pip freeze and conda list if you're using conda.

**Comment by janezd** [comment]
Closed for now. We'll reopen it if the issue persists.

**Comment by rhinsall** [comment]
Oh!  I did a dump, updated everything and checked, and it was still happening; sent it.  But it plainly didn’t arrive.  Dammit.

I will be away for 2 weeks and will have another try then.

R

On 28 Feb 2020, at 07:24, Janez Demšar <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed for now. We'll reopen it if the issue persists.

**Comment by rhinsall** [comment]
It's a memory issue.

Doing eitherthe first or second half of the file makes it work again.

**Comment by rhinsall** [comment]
Maybe an issue between the CPU and GPU memory?  Am I right oragne is using the GPU through numba?

**Comment by pavlin-policar** [comment]
> Maybe an issue between the CPU and GPU memory? Am I right oragne is using the GPU through numba?

No, this is incorrect. Numba is used only by a dependency of openTSNE, the t-SNE implementation that Orange uses, and it runs a nearest neighbor search only on the CPU. I am working to get rid of numba altogether. However, Orange only switches to the numba implementation of nearest neighbor search if the number of samples is large enough. How many samples are you working with?

**Comment by rhinsall** [comment]
**ahem** 11500

**Comment by rhinsall** [comment]
sorry, cruel to computer & cruel to software.  It works fine with 10,000.  It also used to work fine with 11,500, and it works fine on other machines (with less RAM); but at least we know the issue.

**Comment by rhinsall** [comment]
Just checked - Mac(unix) fine on that dataset with 24G RAM; Ubuntu crashing with 32.  Presume there's a data leak in Ubuntu Python or (more particularly) numba.
