### ISSUE TITLE
Import text is missing

### ISSUE THREAD

**Issue by ftastisch** [biolab/orange3#4355]
**Describe the bug**
Text import is missing, e.g. to load pdfs.

**To Reproduce**
1. install orange3
2. install text-addon
3. try to import text files an notice that videos have a button that is not available in your instance.

**Orange version:**
3.24.1

**Expected behavior**
Be able to import e.g. pdfs.

**Screenshots**

**Operating system:**
Windows 10, Manjaro and Ubuntu were tested.

**Additional context**

**Comment by ajdapretnar** [comment]
It is probably best to report this to the [Text add-on](https://github.com/biolab/orange3-text/issues/).

**Comment by ftastisch** [comment]
> 
> 
> It is probably best to report this to the [Text add-on](https://github.com/biolab/orange3-text/issues/).

Thanks for your advice, reported it to the addon.
