### ISSUE TITLE
New widget suggestion for World Bank Database

### ISSUE THREAD

**Issue by borondics** [biolab/orange3#4357]
Accessing World Bank Data from Orange and doing data mining on it would be awesome and probably would also spark wide interest.

There is a python package that deals with the logistics called [wbdata](https://wbdata.readthedocs.io/).

**Comment by janezd** [comment]
This sounds more like an add-on widget?

**Comment by ajdapretnar** [comment]
This was already implemented here: https://github.com/biolab/orange3-datasets, but it was deprecated a long time ago.

**Comment by borondics** [comment]
@ajdapretnar thanks for the link! I wonder if it is still functional... I'll check it out.
