### ISSUE TITLE
Transpose remembers old unexisting data

### ISSUE THREAD

**Issue by Hrovatin** [biolab/orange3#4359]
I have a table file  that I overwrite with different values (rows and columns stay the same). When using a certain version of the file with certain workflow the workflow remembers old data, that was previously overwritten (and does not exist on my disk anymore).  I could not replicate this in a new workflow made from scratch or with Orange data sets. However, it occurs even when I reopen Orange or when I copy the workflow to a new file. 
Below are the workflow and the data and an image of what is happening. 

![Screenshot from 2020-01-23 11-41-55](https://user-images.githubusercontent.com/47607471/72978198-46e61180-3dd6-11ea-9d14-94cf9f1af850.png)

[transpose_remembering.zip](https://github.com/biolab/orange3/files/4102632/transpose_remembering.zip)

Orange: Last master.

**Comment by Hrovatin** [comment]
It was explained to me that the issue arises due to the displayed value being categorical (as it has only 2 values) and not numerical. This affects storing and subsequent display of the data before and after transpose. The issue is thus not in how the data is remembered in  the workflow.

**Comment by janezd** [comment]
Show a warning when transposing categorical data.
