### ISSUE TITLE
Time series Seasonal adjustment error

### ISSUE THREAD

**Issue by yannis72400** [biolab/orange3#4360]
##### Orange version
3.24.1

##### Expected behavior
Seasonal adjustment to work

##### Actual behavior
Get an error and no data is calculated

##### Steps to reproduce the behavior
See enclosed project screenshot. Nothing too complicated.

##### Additional info (worksheets, data, screenshots, ...)
Error is below. Enclosed screenshot
![Screen Shot 2020-01-23 at 2 37 52 PM](https://user-images.githubusercontent.com/60240600/73026116-0e523200-3dee-11ea-9263-121e0a8aa057.png)
 of the workflow

Exception: | ValueError: concatenated tables must have the same domain
-- | --
Module: | Orange.data.table:881
Widget Name: | Seasonal Adjustment
Widget Module: | orangecontrib.timeseries.widgets.owseasonaladjustment:124
Version: | 3.24.1
Environment: | Python 3.6.8 on Darwin 18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64 x86_64
Installed Packages: | AnyQt==0.0.10, Bottleneck==1.2.1, CacheControl==0.12.6, Orange3-Educational==0.2.1, Orange3-Geo==0.2.6, Orange3-ImageAnalytics==0.4.1, Orange3-Prototypes==0.12.0, Orange3-Timeseries==0.3.3, Orange3==3.24.1, Pillow==7.0.0, PyQt5-sip==12.7.0, PyQt5==5.12.3, PyQtWebEngine==5.12.1, PyYAML==5.3, Pygments==2.5.2, Shapely==1.6.4.post2, XlsxWriter==1.2.7, appnope==0.1.0, backcall==0.1.0, beautifulsoup4==4.8.2, brotlipy==0.7.0, certifi==2019.11.28, cffi==1.13.2, chardet==3.0.4, commonmark==0.9.1, cycler==0.10.0, decorator==4.4.1, docutils==0.13.1, et-xmlfile==1.0.1, h2==2.6.2, hpack==3.0.0, hyperframe==3.2.0, hypertemp==0.8.0, idna==2.8, ipython-genutils==0.2.0, ipython==7.11.1, jdcal==1.4.1, jedi==0.15.2, joblib==0.11, keyring==10.3.1, keyrings.alt==2.2, kiwisolver==1.1.0, llvmlite==0.30.0, lockfile==0.12.2, lxml==4.4.2, matplotlib==3.1.2, msgpack==0.6.2, ndf==0.1.4, networkx==2.4, numba==0.46.0, numpy==1.16.6, openTSNE==0.3.12, openpyxl==3.0.3, orange-canvas-core==0.1.11, orange-widget-base==4.3.0, pandas-datareader==0.8.1, pandas==0.25.3, parso==0.5.2, patsy==0.5.1, pexpect==4.8.0, pickleshare==0.7.5, pip==19.3.1, plotly==4.4.1, prompt-toolkit==3.0.2, ptyprocess==0.6.0, pycparser==2.19, pynndescent==0.4.4, pyparsing==2.4.6, pyqtgraph==0.10.0, python-dateutil==2.8.1, python-louvain==0.13, pytz==2019.3, requests==2.22.0, retrying==1.3.3, rfc3986==1.3.2, scikit-learn==0.22.1, scipy==1.2.2, serverfiles==0.3.0, setuptools==40.6.2, simplejson==3.17.0, six==1.14.0, soupsieve==1.9.5, statsmodels==0.10.2, traitlets==4.3.3, urllib3==1.25.7, wcwidth==0.1.8, wheel==0.33.6, xlrd==1.2.0
Machine ID: | 73a10a0a-9999-4b27-a090-8616a523d1cd
Stack Trace: | Traceback (most recent call last):  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orangewidget/gui.py", line 1579, in do_commit    commit()  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orangecontrib/timeseries/widgets/owseasonaladjustment.py", line 124, in commit    ts = Timeseries(Timeseries.concatenate((data, adjusted_data)))  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/data/table.py", line 881, in concatenate    raise ValueError('concatenated tables must have the same domain')ValueError: concatenated tables must have the same domain
Local Variables: | OrderedDict([('axis', 0),             ('cls', <class 'orangecontrib.timeseries.timeseries.Timeseries'>),             ('collect',              <function Table.concatenate.<locals>.collect at 0x141b892f0>),             ('domain', [Date, High, Low, Open, Close, Volume \| Adj Close]),             ('merge1d',              <function Table.concatenate.<locals>.merge1d at 0x141b89488>),             ('tables',              ([[2015-01-26, 313, 307.52, 311.82, 309.66, ... \| 309.66], [2015-01-27, 310.24, 302.63, 306.3, 306.75, ... \| 306.75], [2015-01-28, 311.51, 303.8, 309.81, 303.91, ... \| 303.91], [2015-01-29, 312.8, 299.33, 304.73, 311.78, ... \| 311.78], [2015-01-30, 359.5, 340.74, 346.32, 354.53, ... \| 354.53], ...],               [[309.5, 1.00052, 295.92, 1.04589], [306.916, 0.99946, 306.773, 1.00046], [303.903, 1.00002, 307.48, 0.988367], [311.619, 1.00052, 323.407, 0.963551], [354.722, 0.99946, 343.593, 1.03239], ...])),             ('vstack',              <function Table.concatenate.<locals>.vstack at 0x1339fbbf8>)])

**Comment by ajdapretnar** [comment]
I can't reproduce this on the latest master.

A note to the side: this is an issue of Timeseries add-on, not core Orange. Any issues should be reported to https://github.com/biolab/orange3-timeseries/issues. I think the problem is with the lack of release since 2018. I will try to make one today.
