### ISSUE TITLE
correspondence analysis

### ISSUE THREAD

**Issue by GottM** [biolab/orange3#4362]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by GottM** [comment]
Hello @ajdapretnar ,
Again a new idea to enhance the correspondence analysis widget (which already delivers great stuff). I would love to be able to do within Orange something that I so far need to process outside, within Excel. Namely, it can be useful once (M)CA coordinates have been calculated for each categorical feature to use these coordinates to map every data point to the same space. We know that data point coordinates will be the barycenters of their feature coordinates (it basically just takes a matrix dot product of the CDT and the MCA coordinate table). This could also be an additional option embedded in the "PreProcess" widget as it is a very efficient way to continuize categorical data. Thanks!

**Comment by GottM** [comment]
Hello @ajdapretnar ,
Please find enclosed a proptotype workflow showing what I suggest. I used the python widget to do the dot product and mapped Titanic data to its MCA space... I hope this helps!
Regards,
G.
[Map to CA space.zip](https://github.com/biolab/orange3/files/4138883/Map.to.CA.space.zip)

**Comment by janezd** [comment]
Thanks for your suggestion.

Correspondence analysis is under reconstruction. I merged this suggestion into issue #2538.
