### ISSUE TITLE
CUR Matrix Decomposition rises an error on data with missing values

### ISSUE THREAD

**Issue by aturanjanin** [biolab/orange3#4368]
**Describe the bug**
When a dataset is connected to the Preprocess widget, and CUR Matrix Decomposition is selected if the dataset has missing values the error rises.

**To Reproduce**
1. Select File widget and brown-selected.tab
2. Select Preprocess widget and connect it to File widget
3. In Preprocess choose CUR Matrix Decomposition

**Orange version:**
3.24.1

**Screenshots**
![issue](https://user-images.githubusercontent.com/43814754/73171260-a73fc080-4100-11ea-80cd-2947ef58c42f.PNG)

**Operating system:**
Windows 10

**Comment by janezd** [comment]
I can't reproduce this. Which version of scipy do you have?

I tried 1.3.1 and 1.4.1, both work for me.

**Comment by aturanjanin** [comment]
Version was 1.2.1 and even with this version I couldn't reproduce this on master, but I got the error in the Orange installed on my laptop. Then I upgraded its version of scipy to 1.4.1 and the error didn't occur.

I think when Orange 3.24.1 is installed it installs version 1.2.1 of scipy and with it there is the error but when the version is upgraded then error doesn't show anymore.

**Comment by janezd** [comment]
We don't pin scipy version, so this should then work in the next release, I guess.
