### ISSUE TITLE
Scatter plot missing value rows are selected

### ISSUE THREAD

**Issue by robertcv** [biolab/orange3#4369]
**Describe the bug**
For some subsets of selected data in scatterplot, the output `Selected` column is `Yes` for data with missing values. 

**To Reproduce**
File (brown-selected.tab) -> Scatter Plot (select subset, set Data as output) -> Data Table (sort by alpha 7 to see missing values). If it doesn't work at first, then try some other selection in scatterplot.

**Orange version:**
master

**Expected behavior**
Rows with missing values are not shown so they shouldn't be selected.

**Operating system:**
Ubuntu 18.04

**Comment by AndrejaKovacic** [comment]
The issue is probably in create_annotated_table, it seems to permute the values.
