### ISSUE TITLE
Feature Constructor can fail due to missing variables

### ISSUE THREAD

**Issue by GottM** [biolab/orange3#4373]
When using train data including a target feature calculated with feature construction widget (log10 function) the predictions widget fails. When instead saving exactly the same dataset with the calculated field and then retrieving it from the file, applying predictions works just fine.

Here is more detail.
Target data is numerical and has to be changed to their log10 before training.
Training done using stochastic gradient descent or random forrest or adaboost on random forrest.
Test and score widget works fine.
Predictions widget fails if log10 function applied in the workflow prior to training.
Predictions succeeds if receiving directly data with target feature changed to their log10 (saved file).

I hope someone can figure this out...
Regards,
G.

**Comment by janezd** [comment]
Nice one, thanks. The problem is in Feature constructor.
