### ISSUE TITLE
UMAP in future versions?

### ISSUE THREAD

**Issue by ElviMagda** [biolab/orange3#4376]
Hi,

I was wondering if UMAP plots are planned to be implemented in future versions of Orange? It would be very nice to have it for some types of analysis.

Thanks!

**Comment by ajdapretnar** [comment]
We currently don't plan UMAP, but there's t-SNE and Manifold Learning widget for dimensionality reduction and plotting.
You can always, of course, submit a UMAP widget and we'll help you with the code review.
