### ISSUE TITLE
Problem with SVM-Predictions widgets

### ISSUE THREAD

**Issue by AlessandroCal** [biolab/orange3#4377]
Hi, I have a problem with the combined use of the SVM widget with the Predictions widget.
 I have a dataset which consists of three classes: ColiteUlc, Crohn and HC.
 When I connect the SVM widget to the Predictions widget the result I get is the one shown in the figure.
 Apparently everything seems to be ok: for each row there are three probabilities (the first is relative to the ColiteUlc class, the second to the Crohn class and the third to HC) and after the arrow there is the target class, which is the one with the most probability high.
 In reality, as you can see, this is not always the case; for example, in lines 26 and 28 the algorithm seems not to work correctly, since in line 26 the highest probability is attributed to the third class (HC), however the predicted target class is Crohn, that is the second. In row 28 the highest probability is attributed to the third class (HC), however the predicted target class is ColiteUlc, which is the first.
 Obviously these are errors because in the other lines the program works correctly. I really can't understand the reason for these mistakes.
 Has anyone already encountered this problem or can you tell me something about it? Is this an Orange bug?

**Orange version:**
Orange version: 3.23.1.

**Screenshots**
![ImmagineOrange](https://user-images.githubusercontent.com/60392644/73270039-3c64b700-41de-11ea-81de-dfc2589ea672.png)

**Comment by ales-erjavec** [comment]
This is most likely the documented behavior of [svm probability estimation](https://scikit-learn.org/0.22/modules/svm.html#scores-and-probabilities). Note the second paragraph:

> ... (E.g., in binary classification, a sample may be labeled by `predict` as belonging to a class that has probability <½ according to `predict_proba`.)

**Comment by ajdapretnar** [comment]
Yep, it looks like this could be the reason. Thanks @ales-erjavec for looking it up!

@AlessandroCal Orange in most cases wraps sklearn's learners, so in these cases there's not much we can do about it.

**Comment by AlessandroCal** [comment]
Thanks a lot!

**Comment by AlessandroCal** [comment]
There is a way to solve this problem in Orange?
