### ISSUE TITLE
Heatmap annotations

### ISSUE THREAD

**Issue by Hrovatin** [biolab/orange3#4380]
Currently the heatmap allows splitting of rows by category. However, this visualisation is often not very useful for large heatmaps (see examples below). Also, the columns can not be split.Thus it would be nice if categorical (or numerical) meta attributes could be visualised as annotations (e. g. https://lh6.googleusercontent.com/proxy/E5cDEnykkJVtu9rQO1TvuGHGhdfKWSVZSO_ckiPzbrAC4Bamp2KEMIwCyV-Kqtxbn9J47XnSLqkGc8GrZ5VJ-SjkLOSr ).
Example heatmap:
The rows show strains and time (ordered by strain and then ascending time). It is not very clear which rows belong to which strain. 
![Screenshot from 2020-01-30 09-47-03](https://user-images.githubusercontent.com/47607471/73433826-ce3b0400-4345-11ea-9f5b-e73dd25f63f1.png)
If the heatmap is split by strain the rows get squished and it is impossible to see temporal patterns in individual strains. 
![Screenshot from 2020-01-30 09-47-17](https://user-images.githubusercontent.com/47607471/73433896-f9255800-4345-11ea-879a-435556069a7a.png)
If the keep aspect ratio is ticked the cells get larger, but now one must scroll quite a lot (there are more than 200 rows). Therefore it is hard to get the "bigger picture" of the temporal process.
![Screenshot from 2020-01-30 09-47-27](https://user-images.githubusercontent.com/47607471/73434002-3ab60300-4346-11ea-9932-ffb823cc49c2.png)
Currently the best option seems to be to squeeze the window as mush as possible to reduce the width of the columns (and hence the height of rows). But there is a limit on how narrow the columns can be. Besides, this does not seem to be a very elegant solution. 
![Screenshot from 2020-01-30 09-54-38](https://user-images.githubusercontent.com/47607471/73434262-af893d00-4346-11ea-8806-eed005027886.png)

**Comment by janezd** [comment]
Moved to #4090.
