### ISSUE TITLE
The File widget can be tricked into producing a table with non-unique column names

### ISSUE THREAD

**Issue by mtsch** [biolab/orange3#4381]
**Describe the bug**
The File widget can be tricked into producing a table with non-unique column names.

**To Reproduce**
Open a file with the following contents with the File widget:

```
x,x,x_1
1,2,3
```

The resulting variable names are "x_1", "x_2" and "x_1".

**Orange version:**
3.24.0

**Comment by ajdapretnar** [comment]
Ha!
