### ISSUE TITLE
Domain: Prevent constructing domain with non-unique variable names

### ISSUE THREAD

**Issue by VesnaT** [biolab/orange3#4382]
**Is your feature request related to a problem? Please describe.**
We have an agreement to construct domains with unique variable names, but there are no checks for that in the code.

**Describe the solution you'd like**
Raise an error when constructing a domain with duplicated variable names.

**Describe alternatives you've considered**
Create unique variable names under the hood when constructing the domain.

**Comment by janezd** [comment]
I support raising an exception because we should prefer failing early. The cost of this will be unhandled exceptions at various places, but this is better than unreported errors in various places (and miscomputations later).

I don't like the under-the-hood idea.

**Comment by VesnaT** [comment]
Before we accept this enhancement, it is necessary to fix all widgets that may construct a new domain (which seems impossible).

**Comment by AndrejaKovacic** [comment]
### Widgets, that are changing domains
#### Data widgets
  * File allows changing of names indiscriminately
  * Paint data
  * Pivot
    * change var name by which you are aggregating to Aggregate
  * Concatenate
    * name id column iris or whatever you please
  * Transpose
    * make class var for iris : Feature 001 Iris-setosa
  * Preprocess
    * for PCA: class var for iris : PC1, resulting column names are perhaps incosistent with the rest of widgets, no duplicates though
  * Python script
  * Feature constructor
   * any name goes

**Comment by VesnaT** [comment]
Another proposal: Prevent constructing domains from tuples and lists. Create custom collection e.g. SortedSet. The collection in returned by `get_unique_names`. The purpose is to force the user to always use the `get_unique_names` when constructing the domain.

**Comment by janezd** [comment]
Clever idea. But it would be backwards incompatible. Plus ... think about tests with hardcoded names - which are obviously unique. I'd hate having to call `get_unique_names` there. Plus if everybody just called `get_unique_names`, this is not much different from `Domain` calling it itself, I guess.

**Comment by janezd** [comment]
I usually remember to edit "Partially fixes ..." to "Fixes (partially) ..." to prevent closing of an issue. In #4578 I forgot. :)
