### ISSUE TITLE
Download for Windows not working. Get the error: Internal Server Error The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application

### ISSUE THREAD

**Issue by Tarna8** [biolab/orange3#4386]
**Describe the bug**

**To Reproduce**

**Orange version:**
Orange - About - version number.

**Expected behavior**

**Screenshots**

**Operating system:**
Windows, OSX or Linux? Which version?

**Additional context**

**Comment by acopar** [comment]
This issue is resolved.
