### ISSUE TITLE
Scatter plot shows floats instead of dates on axes

### ISSUE THREAD

**Issue by Minna300** [biolab/orange3#4395]
How to get dates as date form in scatter plot? They are in date form in datatable but in numeric form in scatter plot.
![image](https://user-images.githubusercontent.com/60651045/73739062-3c206a80-474e-11ea-9c53-84c07896e8d4.png)

**Comment by janezd** [comment]
Thanks for reporting this. It's ugly enough to be classified as bug.

To whomever who will work on this: I suppose the nicest solution would be to use `Orange.preprocess.discretize.time_binnings` to get an appropriate number of sensible labels.
