### ISSUE TITLE
Cannot install any Add-ons Orange 3.24.1

### ISSUE THREAD

**Issue by jdzucker** [biolab/orange3#4399]
**Describe the bug**
After starting Orange 3.24.1 and trying to install any of the Add On, I get an error.
"An error occurred while running a subprocess"

**To Reproduce**
1. Go to Menu Option
2. Click on Add-ons
3. Scroll down to tick any Add-ons

**Orange version:**
3.24.1

**Expected behavior**
Installing add-ons

**Screenshots**
![image](https://user-images.githubusercontent.com/12623800/73886474-01135980-486a-11ea-8b9f-d7384d4fb8fc.png)

**Operating system:**
 OS X 10.15.3

**Additional context**
Command failed: python python -m pip install --constraint /var/folders/gp/k6tp6k3n76q63n9fj89b26k40000gq/T/tmpgcl283ul.txt conda install orange3-text Orange3-Network exited with non zero status.
#
In the window it is written 
Collecting conda
  Using cached https://files.pythonhosted.org/packages/74/4e/c533c3136427be62c38cc0e038cabf167bb54489c2ced2f6df903c456861/conda-4.3.16.tar.gz
ERROR: Could not find a version that satisfies the requirement install (from versions: none)
ERROR: No matching distribution found for install
WARNING: You are using pip version 19.3.1; however, version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by robertcv** [comment]
How did you install Orange? I would suggest you try with the dmg available on our [download page](https://orange.biolab.si/download/#macos).

**Comment by janezd** [comment]
Closed due to inactivity. Reopen if needed.

**Comment by mrgalindo** [comment]
I have the same issue, running it from anaconda or downloading the dmg directly from your website. The attached  error is given after installing from dmg

Operating system:
OS X 10.15.5

[error.txt](https://github.com/biolab/orange3/files/4924911/error.txt)

**Comment by markotoplak** [comment]
@mrgalindo, you are missing command line tools (some packages need access to compilers). Follow this guide to install them: https://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/

**Comment by wvdvegte** [comment]
I have two students reporting this same problem. One of them is using Windows. What is the equivalent of command line tools on Windows, and how to install them?

**Comment by markotoplak** [comment]
@wvdvegte, could you be more specific? Which add-ons onto which version of Orange? How was their version of Orange installed.

Usually this should not be an issue if Orange was installed with the standard Orange download from the web-page (which works through conda).

@thocevar, what is the best way to install compilers on Windows?

**Comment by thocevar** [comment]
The easiest way to get a C++ compiler on Windows is to download Microsoft Visual Studio C++ Build Tools (https://visualstudio.microsoft.com/visual-cpp-build-tools/).

But you shouldn't need a C++ compiler in the vast majority of cases, there is likely something else going on.

**Comment by wvdvegte** [comment]
> Which add-ons onto which version of Orange? How was their version of Orange installed.

Timeseries 0..5.1 in Orange 3.33 installed from download (not Anaconda)
