### ISSUE TITLE
Silhouette Plot could output silhouette score

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3#4403]
**Is your feature request related to a problem? Please describe.**
Silhouette Plot uses categorized data to compute cluster centrality of data instances. It visualizes this score as a silhouette plot, where data instances can be selected manually. It outputs the selection, or the whole data table with a selection indicator. Strangely, the output lacks the new meta column that would report the silhouette score.

**Describe the solution you'd like**
Both outputs of this widget should include a new meta attribute called "Silhouette" with the silhouette value of data instances.

**Comment by janezd** [comment]
There's a checkbox "Add silhouette scores" just above the send button. It doesn't work for you?
