### ISSUE TITLE
huge discrepancy between confusion matrix and precision/recall values in kaggle project

### ISSUE THREAD

**Issue by vmelnich** [biolab/orange3#4404]
**Describe the bug**

**To Reproduce**

**Orange version:**
Orange - About - version number.

**Expected behavior**

**Screenshots**

**Operating system:**
Windows, OSX or Linux? Which version?

**Additional context**

**Comment by vmelnich** [comment]
I was using Medical Appointment No Shows data from https://www.kaggle.com/joniarroba/noshowappointments to build a binary classification model for my students. The data set has 110,527 records. I selected 70% records for model training for logistic regression. Precision and Recall were .704 & .795. But confusion matrix gave me TP=347, TN=87500, FP=708, FN=21767. It means that Precision ~30% (not 70%) and extremely small Recall . I was using only six features: age, scholarship, diabetes, alcogolism, SMS and derived variable elapsed time. No-show is a target. I replicated the model in R and found that Confusion Matrix was correct but Precision/Recall were wrong.

**Comment by janezd** [comment]
Which version of Orange do you have?

**Comment by ajdapretnar** [comment]
Please stick to the issue template. This helps us identify the issues much easier.

**Comment by ajdapretnar** [comment]
I have tried this and Orange works as expected.

What you have to be careful of is the fact that Orange reports 'Average over classes'. If you wish to see Precision and Recall for No-show==Yes, then select Yes under 'Target variable'.

**Comment by vmelnich** [comment]
Hi Ajda,

This is to confirm that Orange works as expected when I select Yes under
'Target' variable.
Thanks a lot for clarification.
By the way, my students are using Orange, RapidMiner & Weka. But they have
strong preference for Orange.

Vadim Melnitchouk, Ph.D.
