### ISSUE TITLE
Concatenate categorical

### ISSUE THREAD

**Issue by GottM** [biolab/orange3#4406]
Hello @ajdapretnar ,
The Concatenate widget seems dysfunctional whenever categorical or text values are involved. Fields which should be recognized as same in both data tables are either handled as different or concatenated wrongly.
I enclose the simplest case I could find for you to reproduce the bug (see attached screenshots). I load two tables containing respectively A, B, C, D and E, F, G in one single column. The expected output of concatenation of the two would be a column containing A, B, C, D, E, F, G. Instead I get: A, B, C, D, A, B, C.
I hope that you guys will easily find the fix...
Regards,
G.
![Concatenate bug](https://user-images.githubusercontent.com/47322724/74139368-8b094c80-4bf3-11ea-8972-922c9d50831b.png)

**Comment by janezd** [comment]
@ajdapretnar, this is wider than just concatenation. There are two bugs, and the first one is pretty scary.

1. The first is related to #3925, removal of `Variable.make`.

    Additional data is not properly converted into the new domain because `Domain.get_conversion` uses cached conversions, which it gets from a dictionary whose keys are domains. `Domain.__eq__` and `Domain.__hash__` use `Variable.__eq__` and `Variable.__hash__`, which ignore `Discrete.values` -- as they should. But it bites us here.

    I think that `Domain.__eq__` behaves properly, but `Domain.get_conversion` should require the cached domain is the same, not just equal. Or we can remove caching (@markotoplak?)

2. The second bug is in `OWConcatenate`. For categorical attributes with the same name, which are merged into one attribute, it should construct a new attribute with values from both (or all) original attributes.

    If I remove domain caching, it will construct a column with the attribute from the primary data, so all values from the second table that have no corresponding value in the primary table will be missing.

#### Test

Here is a test to be added to the PR that will fix this issue. (I hope it's correct. :)

```python

    def test_same_var_name(self):
        widget = self.widget

        var1 = DiscreteVariable(name="x", values=list("abcd"))
        data1 = Table.from_numpy(Domain([var1]),
                                 np.arange(4).reshape(4, 1), np.zeros((4, 0)))
        var2 = DiscreteVariable(name="x", values=list("def"))
        data2 = Table.from_numpy(Domain([var2]),
                                 np.arange(3).reshape(3, 1), np.zeros((3, 0)))

        self.send_signal(widget.Inputs.primary_data, data1)
        self.send_signal(widget.Inputs.additional_data, data2)
        output = self.get_output(widget.Outputs.data)
        np.testing.assert_equal(output.X, np.arange(7).reshape(7, 1))
```

Before fixing the first bug, `output.X.flatten()` equals `[0, 1, 2, 3, 0, 1, 2]`. After fixing the first bug, but not the second, `output.X.flatten()` is `[0, 1, 2, 3, 3, np.nan, np.nan]`.

**Comment by ajdapretnar** [comment]
@janezd Should we break this into two separate issues, one for make and the other for Concatenate?
