### ISSUE TITLE
Problem with Bioinformatics Add on

### ISSUE THREAD

**Issue by asfarias11** [biolab/orange3#4407]
I am having problem with practically all bioinformatics widgets. I am using Mac version of Orange 3. 
 Differential expression and volcano plot widgets seem to be in conflict with Python.

**Comment by janezd** [comment]
Please report this in the corresponding repository, https://github.com/biolab/orange3-bioinformatics.

Please also include information about how you installed Orange (from dmg) and the log of installation of add-on (uninstall and reinstall if needed) as well as any other output (open View / Log and copy-paste what's there).
