### ISSUE TITLE
Consistency of widget resizability

### ISSUE THREAD

**Issue by irgolic** [biolab/orange3#4410]
Some widgets shouldn't be resizable, but they are.

<p align="center">
 <img src="https://user-images.githubusercontent.com/24586651/74242701-499d9d80-4cd6-11ea-89ff-397a650e7415.png">
</p>
<p align="center">
<b>OWNeighbors</b>
</p>
<br>
<br>
Some widgets are resizable, but don't utilise the <code>resizing_enabled</code> setting, opting for an explicit call to <code>self.layout().setSizeConstraint(self.layout().SetFixedSize)</code>.

<p align="center">
 <img src="https://user-images.githubusercontent.com/24586651/74243241-4ce55900-4cd7-11ea-847e-6e52d77770cf.png">
</p>
<p align="center">
<b>OWDistances</b>
</p>
<br>
<br>

Upon drawing the status bar in https://github.com/biolab/orange-widget-base/pull/36, should the widget be non-resizable (based on <code>resizing_enabled</code>), some space is added to the right to make up for there being no size grip. As seen in the second screenshot, this margin is missing.

It'd be good to take a look at all the widgets and fix any inconsistencies.

**Comment by ajdapretnar** [comment]
This is a job for me! :)
