### ISSUE TITLE
Splitting and saving datasets

### ISSUE THREAD

**Issue by borondics** [biolab/orange3#4411]
**Is your feature request related to a problem? Please describe.**
Sometimes it is necessary to split datasets and export each row into its own file. 

**Describe the solution you'd like**
Would it be possible to have Save Data handle such operations by adding a counter at the end of a base filename?

**Describe alternatives you've considered**
This is currently possible only by feeding the whole dataset into a selector widget like Data Table and the doing the save manually.

**Additional context**
The issue comes up a lot for Quasar and Spectroscopy data processing.

**Comment by janezd** [comment]
We discussed this: it seems to unusual to be included in core widgets.
