### ISSUE TITLE
Support for Union types in custom widgets

### ISSUE THREAD

**Issue by jpavlich** [biolab/orange3#4417]
When creating custom widgets I frequently need to let the type of input or output types to accept more than one type, e.g., str and int. However the only way I know to achieve this is to use a more general type (e.g. object). 

It would be nice to support Union types, so the above problem could be solved as follows:

`source = Input("source", Union[str, int])`

Thanks

**Comment by ales-erjavec** [comment]
You can already do this with `source = Input("source", (str, int))`

**Comment by jpavlich** [comment]
Great! Thanks
