### ISSUE TITLE
Export confusion matrix as image

### ISSUE THREAD

**Issue by SamiurRahman1** [biolab/orange3#4426]
**Is your feature request related to a problem? Please describe.**
It would be really helpful if the confusion matrix or test & score evaluation data could be exported as image or table. 

**Describe the solution you'd like**
After generating the predictions, confusion matrix and model test & score, there could be an option to export these tables as image or actual tables.

**Describe alternatives you've considered**
Taking a screen shot and crop the result parts.

**Comment by janezd** [comment]
Click the Report button (at the bottom left, next the the question mark). The table will be shown in the report window. There you can save it as HTML or copy & paste it as text.

Tables as images do not seem very useful. If you really want them, you can make screen shots.

**Comment by SamiurRahman1** [comment]
Thanks. That really helps. The "report" button confused me a bit. I thought it was there to report an error in the widget, i should have first checked what it does. :)
