### ISSUE TITLE
Predictions widget: change selection mode for a list box

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/orange3#4427]
In the `show probabilities for` list box in Predictions widget, we are currently using the MultiSelection selection mode, which is OK when the number of target values is low. The problem appears when number of target values is hight (let say 30). In this case, many of them are selected by default, and I want to deselect all of them to get rid of a long list of probabilities in each row of the view. In MultiSelection mode more items can be toggled off/on by dragging mouse through but I think it is very unnatural for a user. 

I suggest changing the selection mode to ExtendedSelection like it is done in some other Orange's widgets.  Here selecting and deselecting of multiple items can be done with the help of shift/control keys. It seems more natural to me.

**Comment by janezd** [comment]
I agree. I even thought that MultiSelection already behaves like this.

**Comment by PrimozGodec** [comment]
Not exactly like this. Selecting/deselecting multiple items is done with dragging through them (not with ctrl/shift keys). I needed to check in Qt documentation to find that out - have never seen before that mode elsewhere.
