### ISSUE TITLE
Predictions: smarter resizing

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#4430]
**Is your feature request related to a problem? Please describe.**
Predictions widget has a very interesting approach to resizing. Main area is uniformly resized, meaning the model (left) part and data (right) part are resized both at the same time. This often makes the model part full of white space and then the user has to drag the parting line around to adjust it.

**Describe the solution you'd like**
Resizing the left part would stop once all the learners are visible.
Probably not easy to implement. Perhaps even impossible. But it would be nice.

**Additional context**
Left part too big, right part too small. It is annoying.
<img width="728" alt="Screen Shot 2020-02-17 at 11 59 10" src="https://user-images.githubusercontent.com/12524972/74647951-ed76c580-517c-11ea-83c5-893750db64de.png">

**Comment by janezd** [comment]
Does this happen only when you resize the window? Does #4433 fix it?

**Comment by ajdapretnar** [comment]
Yes, it's just an issue of resizing. #4433 is great and wonderful and exactly what I've been looking for. Anyone else excited?
