### ISSUE TITLE
Scatter plot widget reverse axis

### ISSUE THREAD

**Issue by bn805** [biolab/orange3#4435]
Could the scatter plot include controls to have the option to reverse the X axis, and another for Y axis?
Maybe using 2 checkboxes.
![scatter_plot_reverse_axis_big](https://user-images.githubusercontent.com/61159052/74675648-f61dca80-5181-11ea-87cc-574788d6e92e.png)

**Comment by janezd** [comment]
We could add many features to scatterplot -- if we weren't striving to keep it simple. Scatter plots don't even have logarithmic scales, for instance. Reverted axes sound more like bells and whistles. Besides, they would require refactoring of so much code that underlies the widget...
