### ISSUE TITLE
An option to group less common values

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/orange3#4436]
**Is your feature request related to a problem? Please describe.**

Sometimes I want to reduce number of different values for a discrete variable. It is helpful when I want to observe it in the box plot, to make cross-validation (without training on values that appears just in few cases), and observe it in the confusion matrix.
Currently, I make it in the python script.

**Describe the solution you'd like**

I suggest an option to group values (let say in preprocess widget) that appears:
- less than n times
- reduce the least common values when number of values is less than n

**Comment by ajdapretnar** [comment]
It is also possible to do this in Edit Domain. Use merge option to merge different categorical values into one. Not exactly what you are looking for, but close.

**Comment by PrimozGodec** [comment]
That is a good option. I didn't know that it exists. 
Anyway, I think we should still think about an option I suggested -- where you do not need to manually click every option. What do you think?

**Comment by janezd** [comment]
I'd say it doesn't belong to Preprocessor widget. The idea of preprocessors is to be a part of the learning process. With Preprocess widget, you apply the same procedure at, say, each fold of cross validation.

I suggest we add a button to Edit Domain that would merge the least common values. Perhaps just an additional button in the current toolbar, that would ask for the name and the number of features.

Alternatively, the existing button currently opens a dialog that asks for a name. Instead, it could also contain a radio button to choose whether to merge the selected items or the least common items; the latter would also enable a line edit or a spin in which the user would specify the number of values that (s)he would like to keep.
