### ISSUE TITLE
Colour palettes not ending with white

### ISSUE THREAD

**Issue by Hrovatin** [biolab/orange3#4438]
Some of the new colour palettes end in white (after yellow). When this is used in a heatmap and Colour High is changed the heatmaps looks like it has holes (e.g. white in the palette is the same as the background). Could white be changes to very pale yellow?
![heatmap_palete](https://user-images.githubusercontent.com/47607471/74732578-d3a3b400-524a-11ea-8dc6-7326985636d2.png)

**Comment by markotoplak** [comment]
I think this is a bug.

**Comment by ajdapretnar** [comment]
Also for Fire, Linear protanopic and Linear tritanopic.

**Comment by janezd** [comment]
It's not a bug. These palettes just end with white.

I think linear protanopic is OK - it's not white, at least not on my screen.

Please checkout #4440 and report whether it's OK.
