### ISSUE TITLE
Subset marking on heatmap

### ISSUE THREAD

**Issue by Hrovatin** [biolab/orange3#4439]
Some widgets (e. g. scatter plot) enable subset marking via Data Subset input. Could this be added to the heatmap? Namely, a subset would be marked with unfilled rectangle, as is currently done for the selection.

**Comment by janezd** [comment]
This is not the same as projections. I wonder whether it wouldn't be more useful (not to mention simpler to implement) if every rectangle would represent a different subset?

**Comment by janezd** [comment]
Will become unnecessary after #4443.
