### ISSUE TITLE
Fix plot axes scale

### ISSUE THREAD

**Issue by Hrovatin** [biolab/orange3#4441]
Currently when viewing different subsets of the data in plots (Scatter Plot, Line Plot) the axes resize every time the data is changed.  Thus it can be harder to visually compare the data subsets. Could there be an option to fix plot axes range (x or y) to the current one? This would be especially beneficial for when there is a known range of values the data can take.

**Comment by janezd** [comment]
Decision at discussion: @Hrovatin will explore relevant software, give us a demo(?) and we'll start collecting ideas about things we would add through an "advanced options" dialogue.

**Comment by janezd** [comment]
Included in #4493.
