### ISSUE TITLE
OWLinePlot fail on pyqtgraph 0.11 pre-release

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#4468]
**Describe the bug**
Line plot tests fail in pyqtgraph 0.11 pre-release.

At least one of the bugs can be solved upstream (there is a PR in pyqtgraph pyqtgraph/pyqtgraph#1063), but as they are not that keen on accepting PR, we should try to avoid it.

They are some other fails which should be checked.

Necessary for fixing #4336.

**Comment by janezd** [comment]
Moved to #4336.
