### ISSUE TITLE
autoencoder

### ISSUE THREAD

**Issue by GottM** [biolab/orange3#4470]
Hello @ajdapretnar ,
Are there any plans for an autoencoder widget to help discover hidden features in data? A similar or midway feature could be an output pin on neural nets enabling access to values of neurons (not weights) in hidden layers...
Regards,
G.

**Comment by GottM** [comment]
Hello @ajdapretnar ,
Are there any plans for an autoencoder widget to help discover hidden features in data? A similar or midway feature could be an output pin on neural nets enabling access to values of neurons (not weights) in hidden layers...
Regards,
G.

**Comment by janezd** [comment]
No, we don't currently plan to extend neural networks and related widgets.
