### ISSUE TITLE
Load file asynchronously?

### ISSUE THREAD

**Issue by gengyabc** [biolab/orange3#4476]
When load reletively large dataset using file widget, the software seems dead. Is it possible to load file asynchronously?

When I load a not so large dataset, say only 60M, it still need some waiting time that I can do nothing but just wait. 

So I think maybe it is better that file widget could load file asynchronously. So people can see what is happening and not thinking the software is dead.

**Comment by janezd** [comment]
Good suggestion. If not too complicated, this will be handled within #3997. There may not be progress bars for every data format, but at least reading will run in a separate thread so Orange will stay responsive.
