### ISSUE TITLE
OSX: Can not run Orange.app from a path with non-ASCII characters

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#4488]
**Describe the bug**

The app from the dmg works normally from a folder called `test`.

Then I moved Orange.app to a folder `testš`. When starting it `testš/Orange3.app/Contents/MacOS/python -m Orange.canvas`, it crashes with:

```
qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Abort trap: 6
```

Renaming the folder `testš` back to `test` restores normal operation. Also, I get the same error if I rename the app to `Orange3š.app`, while renaming it to `a.app` does not cause any problems. 

**Orange version:**
3.24.1

**Operating system:**
OS X 10.14

**Comment by janezd** [comment]
I don't think we can do much here. @ales-erjavec alread asked Phil Thompson about this in Nov '18 (https://pyqt.riverbankcomputing.narkive.com/VhCNMeo2/wrong-unicode-text-encoding-in-the-embedded-qt-etc-qt-conf) and apparently no fix is coming.
