### ISSUE TITLE
Customizing plots (a summary of possible customization options)

### ISSUE THREAD

**Issue by Hrovatin** [biolab/orange3#4493]
The Orange plots could be improved with the following customisations:
**Changing text:** 

- [X] Font, size, italic
Applicability: General
Importance: High for size, low for others (KH).
- [ ] Orientation
Applicability: Multiple plots, especially plots with text based axes values (e.g. Line Plot, Mosaic Display).
Importance: Medium (KH). 

Currently there is a problem of displaying long axis value labels. This could be solved by (combination of) text size, orientation, and name shortening with full name display on hover (as in Mosaic Display); the latter is not a solution for plot saving. The Line Plot even hides some axis labels if it runs out of space; this is not appropriate.
- [ ] Colour
Applicability: General
Importance: Low (KH).
- [ ] Notation (%, currency, scientific, number of decimal places, short (5k))
Applicability: General.
Importance: Low for addition of signs (%, $ - this can be done for axis title) and medium for others (e.g. short notation would be useful when there are numbers in thousands). (KH)

**Annotations:**

- [X] Graph title and description
Applicability: General.
Importance: Medium (KH) (can be done in the report description for saving).
- [X] Changing axis titles
Applicability: General. Multiple plots are missing axes titles (e.g. Boxplot, Line Plot for y axis).
Importance: High (KH).
- [ ] Annotations on graph (comments/pointers/lines)
Applicability: General.
Importance: Low. Sometimes it is easier to add pointer/text on a graph than describe the trend in the report. For scatter plot this can be done to some extent by selecting points, which is shown in the report. However, as this is more applicable for editing already saved images it should probably be done outside of Orange. (KH)
     - **JD**: This sounds too complicated
     - **VT:** Seems doable if necessary. 
- [ ] Vertical/horizontal lines
Applicability: General, all plots with numerical axes.
Importance: Medium. One or a few lines can be an useful visual guide. It might also be useful if they could be frozen when changing plotted variables (KH).
- [ ] Statistical (stdev, significant differences on box/bar plot - e.g. between individual groups, ...)
Applicability: Bar plot, box plot.
Importance: Low (KH).

**Changing plots:**

- [X] Graph elements (choosing shapes for individual categories of categorical variable, opacity of lines/other elements, line type, symbol orientation in scatter plot (e.g. arrows), ...)
Applicability: Multiple plots (e.g. Scatter Plot, Line Plot).
Importance: High, except for orientation - medium. Choice of shapes could be done as for colours with a widget. This would also enable allowing the use of more different shapes as for some plots with specific patterns/clusters using more shapes would not be a problem. Lines on saved Line Plots are poorly visible so changing of opacity and line width is needed. (KH) 
    - **JD:** I'm not sure about this, either.
    - **VT:** One can already choose shape for projections. 

**Showing multiple data sets at once:**
    - **JD:** I think this entire category is too difficult and perhaps out of our scope

- [ ] Multiple overlapping graph types (line, bar)
Applicability: New widget(s) (e.g. bar plot with line, scatter plot with line, violin plots (bar plot with scattered points).
Importance: Depends on a case. Violin plots are popular in biology. (KH)

**Comment by janezd** [comment]
Just to note the decision on this Friday: we start step by step.

@VesnaT will add a button (of some kind, somewhere) on the base projection widget (or is it a mixin that can also be attached to other visualization widgets?) that opens a non-modal dialog with settings that are partially defined by the widget.

This dialog will, for the beginning, allow the user to define something simple, e.g. something related to some fonts.

**Comment by janezd** [comment]
This was split into smaller issues.
