### ISSUE TITLE
Header type annotation (colours) not saved correctly

### ISSUE THREAD

**Issue by Hrovatin** [biolab/orange3#4515]
Colours are not saved/reloaded correctly. I tried to set colours for a categorical feature and then saved the file with header type annotation.  Upon importing the new file into the Orange the data does not have correct colours. The colours from the saved data are loaded correctly in terms of hues, but the categorical instances are mixed between the categories. 
![Screenshot from 2020-03-09 13-32-24](https://user-images.githubusercontent.com/47607471/76213504-1da90580-620b-11ea-9b27-955ac9d524b5.png)

**Comment by janezd** [comment]
@Hrovatin, I can't reproduce, but I think I know what's wrong. Please check whether #4535 fixes it.

**Comment by janezd** [comment]
Reading my previous comment, I see it sounds very wrong. I can't reproduce *the bug you encountered*, but I think I know what's wrong *with Orange*.

**Comment by janezd** [comment]
Am I correct in guessing that this happens only in projections (scatter plot, mds, radviz...)? I can reproduce this in scatter plot, while box plot and table use correct colors. If I'm right, this is a consequence of merging values when there are too many.
