### ISSUE TITLE
Heatmap problems with split by and data pre-filtering

### ISSUE THREAD

**Issue by Hrovatin** [biolab/orange3#4527]
Lately, when I have been changing input data the heatmap widgets kept encountering issues (I have sent the issue reports). Version 3.25.0, Linux.
One of them happens when I use Heatmap's Split by with a categorical variable and then pre-select data based on the same categorical variable with Select Rows. The heatmap starts to look like I would have Keep aspect ratio selected, although it is not selected. Also, the heatmap does not update (displays old data). To get the normal aspect ration the only thing that helps is to delete the widget and add a new one. However, I even get an error popup when I delete the widget. Using Purge Domain between Select Rows and Heatmap sometimes helps.
Additionally, sometimes the heatmap does not have anything drawn after a change in Select rows - the heatmap is empty except for the notation of the group splits, despite the data Table not being empty.

**Comment by janezd** [comment]
@Hrovatin, can you check #4530?

**Comment by Hrovatin** [comment]
It seems to work now. Although it now also works on my current master (I updated it according to biolab's master during the weekend and added #4520), so there might have been something else that fixed it.
