### ISSUE TITLE
Error in File 

### ISSUE THREAD

**Issue by Hrovatin** [biolab/orange3#4537]
When opening a tsv/tab file in Orange 3.25 with File widget I get the below error for certain files. This does not happen when using CSV File Import.

```
Error encountered in widget File:

Traceback (most recent call last):
File "/home/karin/Documents/git/orange3/Orange/widgets/data/owfile.py", line 310, in browse_file
filename, reader, _ = open_filename_dialog(start_file, None, readers)
File "/home/karin/Documents/git/orange-widget-base/orangewidget/utils/filedialogs.py", line 164, in open_filename_dialog
file_format = file_formats[filters.index(filter)]
ValueError: '' is not in list
Merge state

```

**Comment by janezd** [comment]
Can you attach one of such files? It looks very strange that this would be file-specific. It would seem that `QFileDialog.getOpenFileName` returns an empty string for a filter (that is, extension). The file does have an extension, right?

Which version of Linux and Qt?

**Comment by Hrovatin** [comment]
Yes, the files have extensions. 
[colour.zip](https://github.com/biolab/orange3/files/4336880/colour.zip)
I do not remember having such issues on my computer at work, but I am currently on my laptop, so it might be specific to the system. 
Version of operating system: VERSION="18.04.4 LTS (Bionic Beaver)"
Qt version (I am not sure which one is relevant):
AnyQt==0.0.10
PyQt5==5.13.0
PyQt5-sip==4.19.18
pyqtgraph==0.10.0
PyQtWebEngine==5.13.0
qtconsole==4.5.5

**Comment by robertcv** [comment]
I cannot reproduce this. @Hrovatin are you always getting this issue with those files?

**Comment by Hrovatin** [comment]
Previously I was getting the error every time and also with some (but not all) other files. However, it seems to be working now. So I can no longer reproduce it.

**Comment by janezd** [comment]
I would still add a "blind fix" -- if filter is `None` and the extension is one of the known formats, we set it.

**Comment by janezd** [comment]
Moved to https://github.com/biolab/orange-widget-base/pull/53.
