### ISSUE TITLE
Can't install on macOS with Apple-provided Python 3

### ISSUE THREAD

**Issue by avibrazil** [biolab/orange3#4557]
**Describe the bug**
Installation through pip3 on macOS fails on `Bottleneck-1.3.2` installation.

**To Reproduce**
Install Apple's Python 3 (part of Xcode command line tools) with command `xcode-select —install`.
I can't use that bloatware called Anaconda.

Then try to install Orange with:

`pip3 install orange3 —user`

I usually don't have problems installing other Python packages with same method, including those that need compiling.

**Output of Failure**

> Collecting bottleneck>=1.0.0 (from orange3)
>   Downloading https://files.pythonhosted.org/packages/5b/08/278c6ee569458e168096f6b51019cc1c81c288da3d1026a22ee2ccead102/Bottleneck-1.3.2.tar.gz (88kB)
>     100% |████████████████████████████████| 92kB 91kB/s
>   Installing build dependencies ... error
>   Complete output from command /Library/Developer/CommandLineTools/usr/bin/python3 /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/w6/51n__71d6xs7g0044513r8cshrm6n9/T/pip-build-env-ugwrlitb/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel "numpy==1.13.3; python_version=='2.7' and platform_system!='AIX'" "numpy==1.13.3; python_version=='3.5' and platform_system!='AIX'" "numpy==1.13.3; python_version=='3.6' and platform_system!='AIX'" "numpy==1.14.5; python_version=='3.7' and platform_system!='AIX'" "numpy==1.17.3; python_version>='3.8' and platform_system!='AIX'" "numpy==1.16.0; python_version=='2.7' and platform_system=='AIX'" "numpy==1.16.0; python_version=='3.5' and platform_system=='AIX'" "numpy==1.16.0; python_version=='3.6' and platform_system=='AIX'" "numpy==1.16.0; python_version=='3.7' and platform_system=='AIX'" "numpy==1.17.3; python_version>='3.8' and platform_system=='AIX'":
>   Ignoring numpy: markers 'python_version == "2.7" and platform_system != "AIX"' don't match your environment
>   Ignoring numpy: markers 'python_version == "3.5" and platform_system != "AIX"' don't match your environment
>   Ignoring numpy: markers 'python_version == "3.6" and platform_system != "AIX"' don't match your environment
>   Ignoring numpy: markers 'python_version >= "3.8" and platform_system != "AIX"' don't match your environment
>   Ignoring numpy: markers 'python_version == "2.7" and platform_system == "AIX"' don't match your environment
>   Ignoring numpy: markers 'python_version == "3.5" and platform_system == "AIX"' don't match your environment
>   Ignoring numpy: markers 'python_version == "3.6" and platform_system == "AIX"' don't match your environment
>   Ignoring numpy: markers 'python_version == "3.7" and platform_system == "AIX"' don't match your environment
>   Ignoring numpy: markers 'python_version >= "3.8" and platform_system == "AIX"' don't match your environment
>   Collecting setuptools
>     Using cached https://files.pythonhosted.org/packages/70/b8/b23170ddda9f07c3444d49accde49f2b92f97bb2f2ebc312618ef12e4bd6/setuptools-46.0.0-py3-none-any.whl
>   Collecting wheel
>     Using cached https://files.pythonhosted.org/packages/8c/23/848298cccf8e40f5bbb59009b32848a4c38f4e7f3364297ab3c3e2e2cd14/wheel-0.34.2-py2.py3-none-any.whl
>   Collecting numpy==1.14.5
>     Using cached https://files.pythonhosted.org/packages/a0/31/f01ac16f0e8adbb94cd4e3de4920b49a470cf4ca7d452eefd960d4b0248f/numpy-1.14.5-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
>   Installing collected packages: setuptools, wheel, numpy
>   Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/3.7'
>   Consider using the `--user` option or check the permissions.
> 
>   You are using pip version 19.0.3, however version 20.0.2 is available.
>   You should consider upgrading via the 'pip install --upgrade pip' command.
> 
>   ----------------------------------------
> Command "/Library/Developer/CommandLineTools/usr/bin/python3 /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/w6/51n__71d6xs7g0044513r8cshrm6n9/T/pip-build-env-ugwrlitb/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel "numpy==1.13.3; python_version=='2.7' and platform_system!='AIX'" "numpy==1.13.3; python_version=='3.5' and platform_system!='AIX'" "numpy==1.13.3; python_version=='3.6' and platform_system!='AIX'" "numpy==1.14.5; python_version=='3.7' and platform_system!='AIX'" "numpy==1.17.3; python_version>='3.8' and platform_system!='AIX'" "numpy==1.16.0; python_version=='2.7' and platform_system=='AIX'" "numpy==1.16.0; python_version=='3.5' and platform_system=='AIX'" "numpy==1.16.0; python_version=='3.6' and platform_system=='AIX'" "numpy==1.16.0; python_version=='3.7' and platform_system=='AIX'" "numpy==1.17.3; python_version>='3.8' and platform_system=='AIX'"" failed with error code 1 in None

**Comment by janezd** [comment]
> I can't use that bloatware called Anaconda.

Huh, this is a matter of opinion. My environment is much cleaner now that I use conda or pip (and npm for js etc.). And how does conda differ from pip, which you *do* use?

Apparently you don't have write permissions for `/Library/Python/3.7`, which is very reasonable -- you don't want to ruin your system Python.

You will need some package manager. You can use miniconda, which doesn't download anything unless needed? (Or is it still bloatware?) Otherwise, create a pip environment instead of conda environment and install Orange there.

I'll close the issue (because this is not Orange's fault), but we can still use it for communication.

**Comment by avibrazil** [comment]
Then the problem is still with the build system of the package, bacause I used --user which doesn't install anything on system folders.
