### ISSUE TITLE
Can't install on macOS with Apple-provided Python 3

### ISSUE THREAD

**Issue by avibrazil** [biolab/orange3#4570]
**Describe the bug**
Reopening bug #4557 because analysis was incomplete, not considering I'm using `--user` with pip and solution was not provided.

Installation through pip3 on macOS fails on `Bottleneck-1.3.2` installation.

I also noticed many IBM AIX-related messages when this is macOS.

**To Reproduce**
Install Apple's Python 3 (part of Xcode command line tools) with command `xcode-select —install`.

Then try to install Orange with:

`pip3 install orange3 --user`

I usually don't have problems installing other Python packages with same method, including those that need compiling.

Apparently the error bellow is related to lack of permissions to install on `/Library/Python/3.7` which doesn't make sense since I'm using `--user` to avoid system folders. Which makes it still a module bug.

**Output of Failure**

> Collecting bottleneck>=1.0.0 (from orange3)
>   Downloading https://files.pythonhosted.org/packages/5b/08/278c6ee569458e168096f6b51019cc1c81c288da3d1026a22ee2ccead102/Bottleneck-1.3.2.tar.gz (88kB)
>     100% |████████████████████████████████| 92kB 91kB/s
>   Installing build dependencies ... error
>   Complete output from command /Library/Developer/CommandLineTools/usr/bin/python3 /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/w6/51n__71d6xs7g0044513r8cshrm6n9/T/pip-build-env-ugwrlitb/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel "numpy==1.13.3; python_version=='2.7' and platform_system!='AIX'" "numpy==1.13.3; python_version=='3.5' and platform_system!='AIX'" "numpy==1.13.3; python_version=='3.6' and platform_system!='AIX'" "numpy==1.14.5; python_version=='3.7' and platform_system!='AIX'" "numpy==1.17.3; python_version>='3.8' and platform_system!='AIX'" "numpy==1.16.0; python_version=='2.7' and platform_system=='AIX'" "numpy==1.16.0; python_version=='3.5' and platform_system=='AIX'" "numpy==1.16.0; python_version=='3.6' and platform_system=='AIX'" "numpy==1.16.0; python_version=='3.7' and platform_system=='AIX'" "numpy==1.17.3; python_version>='3.8' and platform_system=='AIX'":
>   Ignoring numpy: markers 'python_version == "2.7" and platform_system != "AIX"' don't match your environment
>   Ignoring numpy: markers 'python_version == "3.5" and platform_system != "AIX"' don't match your environment
>   Ignoring numpy: markers 'python_version == "3.6" and platform_system != "AIX"' don't match your environment
>   Ignoring numpy: markers 'python_version >= "3.8" and platform_system != "AIX"' don't match your environment
>   Ignoring numpy: markers 'python_version == "2.7" and platform_system == "AIX"' don't match your environment
>   Ignoring numpy: markers 'python_version == "3.5" and platform_system == "AIX"' don't match your environment
>   Ignoring numpy: markers 'python_version == "3.6" and platform_system == "AIX"' don't match your environment
>   Ignoring numpy: markers 'python_version == "3.7" and platform_system == "AIX"' don't match your environment
>   Ignoring numpy: markers 'python_version >= "3.8" and platform_system == "AIX"' don't match your environment
>   Collecting setuptools
>     Using cached https://files.pythonhosted.org/packages/70/b8/b23170ddda9f07c3444d49accde49f2b92f97bb2f2ebc312618ef12e4bd6/setuptools-46.0.0-py3-none-any.whl
>   Collecting wheel
>     Using cached https://files.pythonhosted.org/packages/8c/23/848298cccf8e40f5bbb59009b32848a4c38f4e7f3364297ab3c3e2e2cd14/wheel-0.34.2-py2.py3-none-any.whl
>   Collecting numpy==1.14.5
>     Using cached https://files.pythonhosted.org/packages/a0/31/f01ac16f0e8adbb94cd4e3de4920b49a470cf4ca7d452eefd960d4b0248f/numpy-1.14.5-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
>   Installing collected packages: setuptools, wheel, numpy
>   Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/3.7'
>   Consider using the `--user` option or check the permissions.
> 
>   You are using pip version 19.0.3, however version 20.0.2 is available.
>   You should consider upgrading via the 'pip install --upgrade pip' command.
> 
>   ----------------------------------------
> Command "/Library/Developer/CommandLineTools/usr/bin/python3 /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/w6/51n__71d6xs7g0044513r8cshrm6n9/T/pip-build-env-ugwrlitb/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel "numpy==1.13.3; python_version=='2.7' and platform_system!='AIX'" "numpy==1.13.3; python_version=='3.5' and platform_system!='AIX'" "numpy==1.13.3; python_version=='3.6' and platform_system!='AIX'" "numpy==1.14.5; python_version=='3.7' and platform_system!='AIX'" "numpy==1.17.3; python_version>='3.8' and platform_system!='AIX'" "numpy==1.16.0; python_version=='2.7' and platform_system=='AIX'" "numpy==1.16.0; python_version=='3.5' and platform_system=='AIX'" "numpy==1.16.0; python_version=='3.6' and platform_system=='AIX'" "numpy==1.16.0; python_version=='3.7' and platform_system=='AIX'" "numpy==1.17.3; python_version>='3.8' and platform_system=='AIX'"" failed with error code 1 in None

**Comment by janezd** [comment]
Is this a problem with Orange or with pip, with bottleneck or with your configuration? Can you try to install just bottleneck to verify this?

Orange is a huge project developed by a small group. We support the normal ways of installing it. For most mac users, this would be a .dmg, while for developers this would be installing into a conda or pip environment. If you are a developer with a specific need to install Orange into your system Python (although I still do not understand why would anybody want to do this), you are unfortunately on your own.

If you however discover a problem in Orange's setup that prevents you from installing Orange this way, and if you provide a fix that is clean, maintainable and does not introduce any new problems, we will be happy to review and merge your pull request. This is the idea of open source. Fair enough?

**Comment by avibrazil** [comment]
A plain `pip3 install Bottleneck --user` yields same error.
Other packages get correctly installed in my home dir, even those that need compile.

**Comment by ajdapretnar** [comment]
This makes it a bottleneck issue.

**Comment by avibrazil** [comment]
I opened a bug there:

https://github.com/pydata/bottleneck/issues/338
