### ISSUE TITLE
ValueError: concatenated tables must have the same domain on seasonality adjustment widget

### ISSUE THREAD

**Issue by anamilkochar** [biolab/orange3#4573]
hi, i am facing the same error when i try to run seasonal adjustment widget on a time series data. Please help on the same.

3.24.1 orange version

error below:

Exception:
ValueError: concatenated tables must have the same domain
Module:
Orange.data.table:881
Widget Name:
Seasonal Adjustment
Widget Module:
orangecontrib.timeseries.widgets.owseasonaladjustment:124
Widget Scheme:
C:\Users\ADMIN\AppData\Local\Temp\ows-_lh5jpe0.ows.xml
Version:
3.24.1
Environment:
Python 3.6.10 on Windows 10 10.0.17763 AMD64
Installed Packages:
AnyQt==0.0.10, Bottleneck==1.2.1, CacheControl==0.12.5, Orange3-Timeseries==0.3.4, Orange3==3.24.1, PyQt5-sip==4.19.18, PyQt5==5.12.3, PyQtWebEngine==5.12.1, PySocks==1.7.1, PyYAML==5.2, XlsxWriter==1.2.7, asn1crypto==1.3.0, certifi==2019.11.28, cffi==1.13.2, chardet==3.0.4, commonmark==0.9.1, cryptography==2.8, cycler==0.10.0, decorator==4.4.1, docutils==0.15.2, entrypoints==0.3, et-xmlfile==1.0.1, future==0.18.2, idna==2.8, importlib-metadata==1.3.0, jdcal==1.4.1, joblib==0.14.1, keyring==20.0.0, keyrings.alt==3.1.1, kiwisolver==1.1.0, llvmlite==0.31.0, lockfile==0.12.2, lxml==4.5.0, matplotlib==2.2.2, mkl-fft==1.0.15, mkl-random==1.1.0, mkl-service==2.3.0, more-itertools==8.0.2, msgpack==0.6.1, networkx==2.4, numba==0.47.0, numpy==1.16.5, openTSNE==0.3.11, openpyxl==3.0.2, orange-canvas-core==0.1.11, orange-widget-base==4.3.0, pandas-datareader==0.8.1, pandas==0.25.3, patsy==0.5.1, pip==19.3.1, pyOpenSSL==19.1.0, pycparser==2.19, pynndescent==0.3.3, pyparsing==2.4.6, pyqtgraph==0.10.0, python-dateutil==2.8.1, python-louvain==0.13, pytz==2019.3, pywin32-ctypes==0.2.0, requests==2.22.0, scikit-learn==0.22.1, scipy==1.2.1, serverfiles==0.3.0, setuptools==44.0.0.post20200106, six==1.13.0, statsmodels==0.11.1, tornado==6.0.3, urllib3==1.25.7, wheel==0.33.6, win-inet-pton==1.1.0, wincertstore==0.2, xlrd==1.2.0, zipp==0.6.0
Machine ID:
89abc96a-0346-4793-9516-4e5277bb3ce0
Stack Trace:
Traceback (most recent call last):
File "C:\Program Files\Orange\lib\site-packages\orangewidget\gui.py", line 1579, in do_commit
commit()
File "C:\Program Files\Orange\lib\site-packages\orangecontrib\timeseries\widgets\owseasonaladjustment.py", line 124, in commit
ts = Timeseries(Timeseries.concatenate((data, adjusted_data)))
File "C:\Program Files\Orange\lib\site-packages\Orange\data\table.py", line 881, in concatenate
raise ValueError('concatenated tables must have the same domain')
ValueError: concatenated tables must have the same domain

Windows

**Comment by ajdapretnar** [comment]
Not related to core Orange. Issue already raised in Timeseries.
