### ISSUE TITLE
PLS implementation in Orange 3?

### ISSUE THREAD

**Issue by realrk69** [biolab/orange3#4579]
I have two questions...

**1:**
I was recently reading the documents of Orange 2.7 and noticed that it had a [PLS Regression Learner](https://docs.biolab.si/2/reference/rst/Orange.regression.pls.html). I'm wondering if there is a reason why it was removed in the first place. I'm trying to implement optimised PLS with various changes which make the modelling better for Spectral, or in general multivariate data (as a widget). Is there a need for this?
I also noticed that there is no implementation of PCR.

PLS - Partial Least Squares
PCR - Principle Component Regression

**2:**
There is a need for making models which work on cross-platform applications (iOS or Android for example). We can serialize trained models into JSON and export them so they can be used on any platform without compromise.

I'm working on both of these currently, and wanted to know if someone has/had already done some work in it.

**Comment by janezd** [comment]
1. PLS was not dropped, it just wasn't reimplemented in Orange 3.0, which was written from scratch with very little code reuse. The only reason that it is not included is that nobody wanted it badly enough. It would be great if you can implement it and make a pull request. Perhaps you should first sketch a widget and propose its functionality before you start coding, so that we'd be more sure to arrive to something we will all like. I'm leaving this issue open so we can continue discussion.

2. The second idea seems less attractive, at least to me. There are too many ways to compute even such trivial models as naive Bayesian classifier, and with that I don't think any standard data format would ensure that computation on another platform would match that in Orange.

    I don't know of anybody serializing Orange's models (except for pickling). If there is a semi-standard json format and you can serialize most of Orange's classifiers, we can perhaps include this format in the widget. We however need to see -- and I again count on your contribution and opinions of others (like @VesnaT, @markotoplak, @lanzagar) -- how to implement this systematically. Unless this can be done properly, without some weird code sticking out, I would be hesitant, though.

**Comment by realrk69** [comment]
1. Thanks for the response janezd. I have attached an image of the widget and its components as I had planned. We can even have adjusting of weights in an additional tabwidget or stackwidget. Also, just to mention, I will be using Scikit-Learn's implementation of PLS. There are other implementations available so we can use those too, but in my tests, this is the most flexible.

Functionality:

Inputs: Data and Preprocessor
Outputs: Learner, Model and Outliers (optional)

Learners are based on [this](https://scikit-learn.org/stable/modules/generated/sklearn.cross_decomposition.PLSRegression.html).

Optimisations are based on selection of parts of data which reveal most relation to target values.

Dependencies:
numpy
scikit-learn
orange itself

2. I understand the implementation of JSON will be perused by the community. I'll try to make the code as readable as possible. I use a lot of shortcuts which sadly won't be compatible. So this would take some time.

Here's the PLS Widget:
Please provide your suggestions to improve or remove structures.
![Screenshot (167)](https://user-images.githubusercontent.com/40699981/77759747-43336d00-705b-11ea-9b02-f52351de5348.png)

New Question:
Is it necessary to stick with Orange's naming convention for placing pls regression file in Orange/regression, can't this be done in the widget itself?

**Comment by realrk69** [comment]
I have almost finished. I'll create the pull request today itself. I need some additional information, which doesn't seem to be mentioned in user guide for creating widgets:

1. What is correct way of using update_model() inside a widget? I see that in many cases it outputs coefficients (Linear Regression) or support vectors (SVM). But I want to send a plottable data table through this. 
2. I have created pls file in Orange/regression and Orange/modelling. But for the optimizations, I want to modify the data being passed (reference SkLearner in Orange/base.py). Is it better to implement this change in Orange/regression/pls by creating a new learner class or in the widget itself by modifying the X, Y data in the input (see SkLearner)?

I am frankly very impressed with the structure and ease of creating widgets. Very nice work by all the developers.
Cheers!

**Comment by realrk69** [comment]
Here's the updated widget. Debugged most of the stuff. A few changes need to be made.
![Screenshot (168)](https://user-images.githubusercontent.com/40699981/77820566-2b1a2700-7109-11ea-816f-e17c45bc2164.png)

**Comment by realrk69** [comment]
### Update:

Here is a working sample on an example spectral dataset of wheat. Let me know if this is satisfactory:

What's working:
1. The model itself (takes only data with 1 target for regression)
2. Predictions
3. Pickling save model and importing/running again

What's not working:
Coefficients output (refer def update_model). Am working on debugging this.

Question: How do we modify the data recevied in @Inputs for the widget? I'm running optimizations so we're gonna need the self.data.X to be modified (not preprocessed).

I'm implementing the Variable selection and moving window PLS in a pull request for orange-spectroscopy, since the models are customized to work specifically for spectral/hyperspectral data. I'm also creating LDA (similar to PLS-LDA) in the supervised section. Let me know if this is okay with you guys before I create the pull request here. I have not added a custom icon yet. Am using the icon of SVM.

Image:
![Screenshot (173)](https://user-images.githubusercontent.com/40699981/77851024-16ff2400-71f4-11ea-836d-249d13e42dbe.png)

Predictions:
![Screenshot (174)](https://user-images.githubusercontent.com/40699981/77851043-30a06b80-71f4-11ea-9163-1cec895cd606.png)

**Comment by realrk69** [comment]
I also found noticed something surprising. Neural Network with the following config:

Neurons: 100,
Activation: Identity
Solver: L-BFGS-B
Max iter = 500
and everything else default, was giving very very similar results to PLS.
PLS: 88.6 (R2)
NN: 86.2 (R2)

**Comment by ajdapretnar** [comment]
@realrk69 
Orange.data.Table's X is essentially a numpy array, yes. You can use any numpy function with it.

As for the PLS, I don't understand fully whether you plan to submit a PR to orange-spectroscopy or core Orange? If it is for spectroscopy (or even otherwise), @markotoplak would definitely be someone to include in the discussion. Either way, I think it is best if you submit a PR first and then we can review the code and comment. Tag the PR with [WIP] (work-in-progress) and our team will have a look. Don't worry about icons and stuff, this can be fixed later.

Most importantly, if you are creating a widget for both classification and regression, then put the widget into model folder and make it work for both discrete and continuous target variables. See Random Forest for example. The code implementing the learners goes to Orange.classification and Orange.regression.

If you have any additional questions, let us know!

**Comment by realrk69** [comment]
@ajdapretnar Hey, I understand @markotoplak, I'll be looking forward to your perusal. Just wanted to confirm, I've been trying to implement cross decomposition of multivariate data which has canonical and PLS algos. The widget I've made implements both and their variations. Kernel and Wide Kernel PLS would sadly not be possible since I made some implementations in keras and tensorflow, but I don't know if Orange supports that. As far as I know, only scikit learn has some documentation and reference code to be used inside of Orange (correct me if I'm wrong).

This PR will be submitted in core orange, since it can be used on other kinds of multivariate data.
The optimizations however, are specific for Spectral data and will show most improvements there. So I'm planning to add the optimization widgets (which basically contain customised PLS) in Orange-Spectroscopy.

I've made the classification and regression in Orange/classification and Orange/regression along with definitions of regression and classification pointers in Orange/modelling. Will be creating pull request soon.

**Comment by realrk69** [comment]
@janezd , @markotoplak , @ajdapretnar. I am attaching the demo spectra you can use to validate. Am facing problems with getting coefficients output. Will fix in subsequent commits.

Also let me know if I should implement all algorithms in cross-decomposition ie:
1. PLS
2. PLS SVD
3. PLS Canonical
4. Canonical Correlation Analysis

I'm gonna create the spectral specific widgets now and will be waiting for your go ahead.

[Datasets.zip](https://github.com/biolab/orange3/files/4411518/Datasets.zip)

**Comment by realrk69** [comment]
Any update guys? Did it work for you?

**Comment by ajdapretnar** [comment]
@realrk69 We have team meeting today, someone will check and get back to you.

**Comment by markotoplak** [comment]
Continued in quasars/orange-spectroscopy#417
