### ISSUE TITLE
Line plot does not show instances with unknowns anymore

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#4580]
**Describe the bug**

Newer QT versions changed how they draw curves with nans. Before, they skipped nan elements. Qt that is distributed in PyQt5 5.12.3 and 5.13.1 changed this and it is not showing anything in such cases.

Now, I do not see any lines if I feed Line Plot data that contains NaN, like:

```
data = Table("brown-selected")
data.X[:, 40] = np.nan
```

Related:
- A connected pyqtgraph bug: pyqtgraph/pyqtgraph#1057 (with a suggested fix) 
- A quick workaround from spectroscopy that handles just the cases there: Quasars/orange-spectroscopy#409

**Orange version:**

Doesn't matter, the Qt version does. Problem confirmed on Mac and Windows.

**Comment by VesnaT** [comment]
The widget has never displayed instances with missing values. It shows a warning "Instances with unknown values are not shown." instead.
