### ISSUE TITLE
Use palettes for >20 colors

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#4581]
@lanzagar commented that more frequent values should have more distinct palettes. This led to the idea that palettes generated by going through hues may not be a good idea and that we could instead use one of categorical palettes from https://colorcet.holoviz.org/ -- one that uses the whole spectra, not just, say, "cool" colors.

So the idea is to 

- [ ] The chosen categorical colorcet palette would be provided as one of `DiscretePalettes` (beside the current `default` and `dark`).
- [ ] `LimitedDiscretePalette` would no longer fallback to hues but instead use the first `n` colors from that colorcet palette. 
- [ ] whereas the current code that generates a hue palette,

    ```python
                hues = np.linspace(0, 1, number_of_colors, endpoint=False)
                palette = 255 * np.array([colorsys.hsv_to_rgb(h, 1, 1) for h in hues])
    ```

    would remain available in a separate class `HuePalette` to whomever who might actually want it.

**Comment by ajdapretnar** [comment]
These look super weird, but perhaps one just has to see them in practice. :)
