### ISSUE TITLE
Line Charts run together

### ISSUE THREAD

**Issue by Norsusan** [biolab/orange3#4586]
Charts run together.

Charts are not clearly separated.

Time series flow using "air passenger" data set

Orange3 3.24.1 on Windows 10 64 bit

[Time Series Line Chart .pdf](https://github.com/biolab/orange3/files/4395853/Time.Series.Line.Chart.pdf)

**Comment by janezd** [comment]
Please report this in the Time series repository, https://github.com/biolab/orange3-timeseries.

Also, please provide better instructions to reproduce. I don't know the time series add-on well enough, but to me it seems as if data passes through the first few widgets and is ammended with new columns. If so, the widget works as intended.

Please use text and pictures, not PDFs.
