### ISSUE TITLE
Table widget could output sorted data

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#4597]
#### Write a clear and concise description of what the problem is.

I sorted a table by some column (i.e. I sorted countries by number of confirmed Covid-19 cases per million). Then I wanted to know the rank of Slovenia. The table's horizontal header shows row numbers from the original data, which is correct, but not helpful in this case. So I hoped that if I connect another table widget to this one, I get re-ordered data. This is not the case.

#### Describe the solution you'd like

I'd like the output data in the some order as presented in the table, if this is not too difficult.

**Comment by ajdapretnar** [comment]
+1

**Comment by janezd** [comment]
Also, save sorting as schema-only setting.
