### ISSUE TITLE
SOM on Covid data uses constant color

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#4598]
**Provide a clear and concise description of what the bug is**

All circles in SOM are of the same colors, and so are all rectangles in the legend.

**To Reproduce**

Load https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv into File widgets, remove Lat and Long, connect it to SOM and color by any date. All circles are blue. Sizing by number of instances can be disabled for a cleaner effect.

Clicking "Show Pie Charts" does change the color for some circles, but the legend stays the same.

**Orange version:**

Orange - current master (87849a8729cc06214535542631d695d2b7233ec6).

This may be related to new palettes, though I doubt it. The bug doesn't appear on Iris. It probably has something to do with this particular data set.

**Screenshots**

<img width="362" alt="Screenshot 2020-03-30 at 23 26 39" src="https://user-images.githubusercontent.com/2387315/77963625-fb704800-72dd-11ea-8138-15706b903726.png">

<img width="371" alt="Screenshot 2020-03-30 at 23 26 52" src="https://user-images.githubusercontent.com/2387315/77963633-ff9c6580-72dd-11ea-8d50-7f4a1a2a6aa0.png">

**Comment by janezd** [comment]
It would be nice if we could fix this for the release in a few days -- it may be useful for the blog/videos about Covid.

**Comment by ajdapretnar** [comment]
Similar can be tested with Auto MPG or Housing.
