### ISSUE TITLE
Import Sounds WIdget missing in Orange 3.24.1

### ISSUE THREAD

**Issue by mohitrao2007** [biolab/orange3#4606]
After upgrading Orange to 3.24.1, Import Sounds activity inside Audio-IJS is missing

Working with Version 3.23.0 But missing widget in 3.24.1
Ad-On Version - Orange3-Audio-IJS-0.1 (latest)

OS Version - Windows 10

**Comment by ajdapretnar** [comment]
Audio-IJS is not part of this repository nor an add-on developed by the core team. Please report this to the developers of the add-on.
