### ISSUE TITLE
Category "More..." 

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#4622]
In response to #4620, @irgolic wrote that

> Maybe we should add an empty category named 'More...' at the end, which would open the add-on menu on-click.

which is worth a separate issue. It doesn't have to be (or look like) a category.

**Comment by ajdapretnar** [comment]
I interpreted this differently. I think 'More...' should be visible on the website in the widget catalogue, not in Orange itself. If I have installed an add-on I want to see it and use it.

**Comment by janezd** [comment]
Result of discussion: we agree this would make sense. We wait for @irgolic to implement it when he has time, unless somebody else does it before.
