### ISSUE TITLE
Feature names not being recognised - and Freeviz issue

### ISSUE THREAD

**Issue by Fishgraph** [biolab/orange3#4623]
**Describe the bug**
Hi! I tried finding answers online but could only find videos (official Youtube channel) and some pdfs, which I followed, but the behaviour is not the same. Orange Facebook page sent me here. Two issues:
1) The top row from data files is treated as data instead of feature names. How to fix?
2) Also freeviz issue I will describe below.

**Here**, provide a clear and concise description of what the bug is.
I use Pages on Mac. I export as .xlsx file. Spreadsheet has:
139 columns
38 rows.

1st column contains text. Orange recognises it as metadata, calls it 'Table 1'. Good.
1st row contains text. Orange does not take them as the names of the features. Column headings from 2nd column on are instead 'Feature 1', 'Feature 2' etc.
All other cells contain numbers. 

Basically my spreadsheet is the same style as the one in 'A Gentle Introduction to Data Science March 2019' - Lesson 3: Loading Your Own Data Set, which is from the Orange website. But does not give the same result.

I can find no way to change this. Help much appreciated!

2) As a workaround I have used a data table, then selected all except the 1st row. From this I can:
a) output to MDS. It works.
b) output to distances, and from there to MDS or Hierarchical Clustering, also works. I.e. File>Data table> (selected data removing that first row) > Distances>Heirarchical Clustering

But some steps from the tutorial 'A Gentle Introduction to Data Science' do not work. This:
File>Data table> (selected data removing that first row) > Distances>Heirarchical Clustering > Scatter Plot

...gives an error. A **yellow warning sign** and no plot.

Also from the Youtube tutorial **'Getting Started with Orange 20: Multivariate Projection - Freeviz**' I cannot get FreeViz to work. 

1)File>FreeViz
or
2)File>Data table> (selected data removing that first row) >Freeviz

Both of those give a **red warning sign**, and no result or plot or anything.

So far as I can see in all these examples I am following the instructions in the tutorial precisely.

**Orange version:**
3.24.1

**Expected behavior**
I think that's clear from the above. Basically something similar to the tutorials, rather than error signs and no results. And features that have the names I gave them rather than numbered 1,2,3...
**Screenshots**
<img width="480" alt="Screenshot 2020-04-04 at 15 27 43" src="https://user-images.githubusercontent.com/63154415/78453322-da667900-7688-11ea-94cc-380486243de7.png">
<img width="618" alt="Screenshot 2020-04-04 at 15 28 45" src="https://user-images.githubusercontent.com/63154415/78453346-03870980-7689-11ea-9aca-49ffce380b72.png">

**Operating system:**
Mac OS 10.14.6

Thanks!

**Comment by ajdapretnar** [comment]
Yes, this is normal. The way Numbers saves the file includes a bunch of formatting and your Excel file has probably 'Table 1' at the very top as the first row. There's nothing we can do about it (right, @janezd?). Remove the first row with Table 1 and it should work fine.

**Comment by ajdapretnar** [comment]
Signs in Orange have a content as well. Hover over the sing and read what it says. This should answer your question.
