### ISSUE TITLE
Feature Constructor reducing numeric presicion

### ISSUE THREAD

**Issue by revelation1** [biolab/orange3#4639]
**Describe the bug**

Using a function on a numeric in feature constructor with a numeric output will reduce precision to 3 decimal places.  The precision loss is significant and not a typical floating point estimation problem.

I tried a few functions.  fmod, modf, division, basically anything that produces a float output is getting reduced.

**To Reproduce**

Create a numeric feature constructor attribute with this function.

float(1.100001)

Output is 1.100.

**Orange version:**
3.24.1

**Expected behavior**
Floats should retain original precision

**Screenshots**
![image](https://user-images.githubusercontent.com/7517411/78941099-db721e80-7a6b-11ea-9de2-1facba231479.png)
![image](https://user-images.githubusercontent.com/7517411/78941149-f3e23900-7a6b-11ea-9f9c-1a53d6531c7d.png)

**Operating system:**
Windows 10

**Comment by janezd** [comment]
Add another Feature Constructor and multiply this variable by 1000.

The number is not rounded, it's just printed with a fixed number of decimals (3). The new release (published today) partially fixes this. A proper fix comes in #4645.
