### ISSUE TITLE
Requesting a way to use a term-document matrix as an input

### ISSUE THREAD

**Issue by jkaupanger** [biolab/orange3#4646]
I have a csv with tokens as columns and documents as rows. Because of the nature of the data, that's how it is starting; in other words, I don't really have access to the "untokenized" data because it doesn't exist.

As far as I can tell, there isn't a way to input a term-document matrix into Orange.

Specifically, what I'm trying to do is conduct some topic modelling (HDP and LDA).

**Comment by janezd** [comment]
I suppose this belongs to the Text mining add-on repository, https://github.com/biolab/orange3-text, not here?

**Comment by jkaupanger** [comment]
Quite possibly. I'm still new to all of this, so I'm equating everything.

**Comment by janezd** [comment]
No problem.
