### ISSUE TITLE
Missing pictures in orange help

### ISSUE THREAD

**Issue by FroggyTest** [biolab/orange3#4648]
Hello,
I just updated Orange to 3.24 on windows10.

**Here**, provide a clear and concise description of what the bug is.
Before I had a great documentation on-line available from the widget.
Now the window opens with the text but missing the picture.

**To Reproduce**

Steps to reproduce the behavior go **here**:
1. Go to any widget and 
2. click on the "?" at the bottom left of the window
3. the help file opens,
4. the images are missing

**Orange version:**
Orange - About - 3.24.1.

**Expected behavior**
The images on the flow show show up

**Screenshots**
See attached screenshot

**Operating system:**
Windows 10  64 bits

![OrangeBug](https://user-images.githubusercontent.com/63545457/79069360-e2986700-7ccd-11ea-9436-e10d432c2752.JPG)

**Comment by markotoplak** [comment]
@FroggyTest, thank you for reporting this.

@acopar, is this perhaps connected with changes to server urls on Friday? If I open Orange docs in the Browser, I get the same rendering: without the images.

**Comment by acopar** [comment]
Unrelated, the images are not uploaded with the rest of the documentation: https://github.com/biolab/orange3/blob/e1bc1ca741577a1cbbf8d4d3de0571f18e6a18f7/.travis/upload_doc.sh#L18

I recommend we use Github Actions to build and Github Pages to serve the documentation directly. We could re-use this script: https://github.com/biolab/orange3/blob/e1bc1ca741577a1cbbf8d4d3de0571f18e6a18f7/doc/build_doc.sh#L28

**Comment by FroggyTest** [comment]
Hello,

thank you all for your comments.
If it  helps at all, I loaded today the "Associate", "Educational" and "Geo" add-onsand there the help works well, with images included.
All except "Geo" are in a different format, it seems, but even more readable

best regards. Stay safe.

**Comment by FroggyTest** [comment]
thanks
