### ISSUE TITLE
No Way to Cross-Validate Timeseries Data

### ISSUE THREAD

**Issue by dancaron** [biolab/orange3#4650]
Orange is amazing. It's a joy to work with. To the best of my knowledge, there is no appropriate cross-validator for timeseries data. There is an implementation in sklearn that I believe could be used: https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.TimeSeriesSplit.html

**Comment by janezd** [comment]
Have you checked the Time Series add-on? There's a widget Model Evaluation. Does it do the job for you?

**Comment by dancaron** [comment]
Yup. This will do it for now. Thanks!
