### ISSUE TITLE
Name dataset for Venn Diagram 

### ISSUE THREAD

**Issue by Hrovatin** [biolab/orange3#4653]
Naming a dataset is essential for Venn Diagram (otherwise identity of each displayed dataset can be determined only by checking the number of rows). However, datasets are currently named only on data import into the Orange. If two (or more) Select Rows are done on the same dataset they are named equally and can not be distinguished in Venn  Diagram. One of the widgets (e.g. Edit Domain) should enable renaming of individual data streams. Thus every data passing through it would have the same name (so that the name would be retained after changing the Select Rows filtering).
Related to #1083.

**Comment by janezd** [comment]
On a weekly meeting, we agreed to put this into Edit Domain widget.
