### ISSUE TITLE
BoxPlot crashes when saving selection

### ISSUE THREAD

**Issue by VesnaT** [biolab/orange3#4663]
**Describe the bug**
Box Plot widget crashes when removed from canvas after selecting some instances on the plot.

**To Reproduce**

1. Place a File (Iris) widget on canvas.
2. Connect it to a BoxPlot.
3. Select e.g. Iris-setosa box in the plot area.
4. Remove the Box Plot widget from canvas.

**Orange version:**
Master

**Expected behavior**
No crash when deleting the widget.
Selection is a schema-only setting of a [valid type](https://github.com/biolab/orange-widget-base/issues/20).

**Comment by janezd** [comment]
I can replicate the problem, but it's obvious what's wrong.

Writing as many context handlers as possible seems to have become my corona work-at-home project.
