### ISSUE TITLE
R support

### ISSUE THREAD

**Issue by J-Savage** [biolab/orange3#4671]
Is there any possibilities or plans for including support for R code. The Python widget is great but I'm more familiar with R.

**Comment by janezd** [comment]
I think not because it would add a dependency that could be problematic to maintain.

Such a widget could be provided as an add-on, though. None of the core developers is an active R user, so an "official" add-on is unlikely, but a third-party add-on shouldn't be a problem.

**Comment by pavlin-policar** [comment]
On a side note, full compatibility between Orange and R would probably be impossible (or at least very difficult).

Some things would be easy, like Orange tables to R data frames. It should be fairly straightforward to do this with rpy2.

How would R packages be managed and installed? The easy way to do this might be to point rpy2 to an existing R installation and have the user manage their own packages through that. So R packages would not be managed by Orange.

Other things, such as models and learners would be more difficult. Trying to convert those between R and Python would be a nightmare. Some widget outputs send out trees, which can be visualized. I don't even know what the R equivalent of that would be.

However, if you wanted to do this for tables alone, which would already achieve a lot of functionality, this should be fairly straightforward.
