### ISSUE TITLE
Neural Network: the output (prediction) will be saturated in some cases.

### ISSUE THREAD

**Issue by huginnhuginn** [biolab/orange3#4701]
**Describe the bug**

I design an experiment to see the effects of different training data on the models and their prediction. The structure could be presented by the picture below.
![未命名1587737698](https://user-images.githubusercontent.com/61767878/80222513-8c3a0980-8679-11ea-8397-3bc21b085fc5.jpg)

**To Reproduce**

Steps to reproduce the behaviour go **here**:
1. download the following .zip
use .ows file and data excel file I provided
[neural network.zip](https://github.com/biolab/orange3/files/4529482/neural.network.zip)

2. Click on 'data table' before the neural network to select training data

3. Click the file widget below, which is one of the two inputs of prediction widget, set the input data as: file "20200419data.xlsx" sheet "Sheet2 (4)"

4. Click on the line chart on the right hand to see the result

5. See error (saturated outputs are constant after a certain period of time)
![未命名1587738606](https://user-images.githubusercontent.com/61767878/80224118-d9b77600-867b-11ea-903a-57d5a886b18a.jpg)

**Orange version:**
Orange - About - 3.24.1

**Expected behavior**
The output would never keep constant for a long time. 
They are expected to climb slowly.

**Operating system:**
Windows

**Comment by janezd** [comment]
I'm almost sure there is nothing wrong with neural networks, the cause of the apparent problem must be in your procedure or misunderstanding of its results. Orange developpers debug Orange, but can't debug users' workflows.

If you are certain there is a problem in Orange, please provide a simpler example to reproduce it.

**Comment by huginnhuginn** [comment]
> I'm almost sure there is nothing wrong with neural networks, the cause of the apparent problem must be in your procedure or misunderstanding of its results. Orange developers debug Orange, but can't debug users' workflows.
> 
> If you are certain there is a problem in Orange, please provide a simpler example to reproduce it.

I can get what I want when I use one neural network in orange.
I can apply this idea, which is shown by this workflow and very simple, in rapidminer and get what I want.
Something must be wrong. I can not tell.

**Comment by huginnhuginn** [comment]
> I'm almost sure there is nothing wrong with neural networks, the cause of the apparent problem must be in your procedure or misunderstanding of its results. Orange developers debug Orange, but can't debug users' workflows.
> 
> If you are certain there is a problem in Orange, please provide a simpler example to reproduce it.

The outputs do act as I expected at the beginning.
