### ISSUE TITLE
Documentation - Page not found

### ISSUE THREAD

**Issue by mkosovic1981** [biolab/orange3#4702]
It seems this link does not work:
https://orange.biolab.si/widget-catalog/unsupervised/PCA

**Comment by ajdapretnar** [comment]
Thanks for reporting this.

I cannot find the fault. Index is ok, the local build works, every other file works. Any ideas @markotoplak, @acopar?

**Comment by markotoplak** [comment]
Thank you. @ajda, there is some caps issue. If we use `pca` instead of `PCA` it works. I'll see where does this come from.
