### ISSUE TITLE
Paint data should support a domain outside of [0,1]

### ISSUE THREAD

**Issue by mfrawley** [biolab/orange3#4705]
**I would like to draw data on it's actual range/scale**

I would like to be able to specify the min, max of each variable I'm drawing. The same way I would when using a plotting library, since you cannot auto-infer this from my imagination ;)

**Comment by mfrawley** [comment]
I see you need to discuss, if you need more information, please ask.

**Comment by janezd** [comment]
We discussed this at the core group meeting and decided that we would prefer to keep this widget simple.

The widget is meant for drawing some data *in some shape* for testing and for education purposes, for instance plotting a few points for polynomial regression or clustering. These use cases do not require scaling - at least in our practice we never missed it.

For scaling and more, you can put the data through Feature Constructor.

To generate random data from some particular distribution, you can use the widget Random Data from add-on Educational. There you can choose, for instance, normal distribution with a specific mean and variance.

Does this help?
