### ISSUE TITLE
Getting an Internet error with Options_Add Ons

### ISSUE THREAD

**Issue by I-Zapp** [biolab/orange3#4707]
**Describe the bug**
When I click Options and then choose Add-Ons I obtain the Warning "There's an issue with your Internet connection ..." and then the list is empty.

Windows 10 with Internet fully working.

![OrangeBug](https://user-images.githubusercontent.com/30356056/80591599-433dd880-8a1e-11ea-8dfa-3801c2a442e4.png)

**Comment by ales-erjavec** [comment]
Can you click show details and post its contents.

**Comment by I-Zapp** [comment]
Traceback (most recent call last):
  File "S:\Orange\lib\site-packages\urllib3\connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "S:\Orange\lib\site-packages\urllib3\util\connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "S:\Orange\lib\socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "S:\Orange\lib\site-packages\urllib3\connectionpool.py", line 662, in urlopen
    self._prepare_proxy(conn)
  File "S:\Orange\lib\site-packages\urllib3\connectionpool.py", line 948, in _prepare_proxy
    conn.connect()
  File "S:\Orange\lib\site-packages\urllib3\connection.py", line 300, in connect
    conn = self._new_conn()
  File "S:\Orange\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x000001DB3BE65888>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "S:\Orange\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "S:\Orange\lib\site-packages\urllib3\connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "S:\Orange\lib\site-packages\urllib3\util\retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='orange.biolab.si', port=443): Max retries exceeded with url: /addons/list (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001DB3BE65888>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "S:\Orange\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "S:\Orange\lib\site-packages\orangecanvas\application\addons.py", line 679, in <lambda>
    lambda config=config: (config, list_available_versions(config)),
  File "S:\Orange\lib\site-packages\orangecanvas\application\addons.py", line 1205, in list_available_versions
    defaults = config.addon_defaults_list()
  File "S:\Orange\lib\site-packages\Orange\canvas\config.py", line 158, in addon_defaults_list
    return session.get(OFFICIAL_ADDON_LIST).json()
  File "S:\Orange\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "S:\Orange\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "S:\Orange\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "S:\Orange\lib\site-packages\requests\adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='orange.biolab.si', port=443): Max retries exceeded with url: /addons/list (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001DB3BE65888>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')))

**Comment by I-Zapp** [comment]
I may add that version 3.25 is working perfectly on my MacBook Pro, on the same network, with all addons

**Comment by ales-erjavec** [comment]
Can you open Options/Settings from the main window and check the Network tab to see if you have any proxy setting set, and if so that they are correct.

**Comment by I-Zapp** [comment]
![Network](https://user-images.githubusercontent.com/30356056/80742343-82058880-8b1b-11ea-86b1-7bb0ede4caab.png)

**Comment by I-Zapp** [comment]
My MacBook Pro, on the same network, is pretty happy with the same settings (nothing, nothing)

**Comment by ajdapretnar** [comment]
Yes, I think you should enter your proxy details here, otherwise the connection won't work.

**Comment by I-Zapp** [comment]
Thank'you for your answer; as I said, my mac is on the same network and everything works with no proxi.

**Comment by I-Zapp** [comment]
Anyway, I have no proxy, should I try the router's IP?

**Comment by ales-erjavec** [comment]
Can you open Orange, add a Python Script widget to a new workflow and run the following script

```python
import os
from urllib.request import getproxies
print("getproxies():", getproxies())
print("env http-proxy:", os.environ.get("http-proxy"))
print("env https-proxy:", os.environ.get("https-proxy"))
```

**Comment by I-Zapp** [comment]
Here it is:

Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(PythonConsole)
>>> 
Running script:
getproxies(): {}
env http-proxy: None
env https-proxy: None
>>>

**Comment by ales-erjavec** [comment]
Sorry the script was wrong. Can you repeat with
```python
from urllib.request import getproxies, getproxies_environment
print("getproxies():", getproxies())
print("getproxies_environment()", getproxies_environment())
```

**Comment by I-Zapp** [comment]
Done, here is what I see:

Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(PythonConsole)
>>> 
Running script:
getproxies(): {}
getproxies_environment() {}
>>>

**Comment by ales-erjavec** [comment]
Well I'm stumped. Those are AFAIK the only sources of proxy config that could cause the proxy to be involved in the process.

**Comment by ajdapretnar** [comment]
I had a couple of similar reports recently from the users. I got the feeling that none were behind a proxy, yet they got this error. As if Orange somehow wrongly assumed there was a proxy involved. 🤷

**Comment by I-Zapp** [comment]
I can assure you I'm not behind a proxi: my macbook on the same network has no problem with Orange :-)

**Comment by markotoplak** [comment]
I double checked this and I do not know where to look for the bug either. @I-Zapp, if you think of anything that could help us debug it, please notify us.

**Comment by markotoplak** [comment]
@I-Zapp, can you please also try the following script in Python script widget?

```
import os
import requests
from urllib.request import getproxies
print("getproxies():", getproxies())
print("env http-proxy:", os.environ.get("http-proxy"))
print("env https-proxy:", os.environ.get("https-proxy"))
print("env for addons list:", requests.utils.get_environ_proxies('https://orange.biolab.si/addons/list'))
```

**Comment by markotoplak** [comment]
Also, are you perhaps using some kind of a VPN?

**Comment by I-Zapp** [comment]
Any other way I can download the addon to my filesystem and then trick Orange into thinking to get its addon from there? A config file maybe?
On a different track: is there any cointainerized version that I can download from somewhere?

And, since we are here, I would like to have a contact with your maths guys (I am a mathematician and director of a phd and post-doc research group in ML and AI) to explore some possible opportunities for the future that I am sure you might find interesting.

Thanks

A.D.

**Comment by ajdapretnar** [comment]
@I-Zapp On Windows, you should have Orange Command Prompt (provided you installed Orange via its official installer). You can open the prompt and manually install add-ons, for example:
`conda install orange3-text`

As for containerized version, see https://orange.biolab.si/blog/2020/2020-01-16-orange-cloud/. Also @acopar might be able to help with issues if needed.

For cooperation, please send an e-mail to info@biolab.si.

**Comment by I-Zapp** [comment]
Thank'you for your answer, I'll try and test the docker version next week.

Also, the command line version of the addon installer looks promising. Where can I find the names of the different addons? (orange3-text in your example).

AD

**Comment by I-Zapp** [comment]
Found it: https://anaconda.org/search?q=orange3

**Comment by I-Zapp** [comment]
I'm happy to report that thanks to the 

conda install [addin name]

trick I have a working Orange3 on my main PC with al addons installed.

Now I'll have to study the container setup for my lab's cloud.

Thanks for now, I'll get back to you for the collaboration opportunities.

Andrea

**Comment by markotoplak** [comment]
@I-Zapp, does the Datasets widget work for you? It also uses similar network libraries.

**Comment by I-Zapp** [comment]
Hi Marko, yes, the Datasets widget works perfectly.

Bye

Andrea

**Comment by yuanxin-cq** [comment]
I installed Win64OpenSSL_Light-1_1_1g.msi and get rid of this problem .My os is windows10.

**Comment by janezd** [comment]
@I-Zapp, can you try this?

I vaguely remember having some problems with conda or pip on some faculty computers, which were caused by incompatibility between Windows 10 libraries and Python's ssl modules.

**Comment by dsoasti** [comment]
> 
> 
> I installed Win64OpenSSL_Light-1_1_1g.msi and get rid of this problem .My os is windows10.

How did you install it?

**Comment by dsoasti** [comment]
I´ve installed this Win64OpenSSL_Light-1_1_1g.msi, but I still can´t make it work... 
![Captura](https://user-images.githubusercontent.com/1807299/84122433-b6346900-aa38-11ea-975d-2947d51daa7f.PNG)
Any help?

**Comment by markotoplak** [comment]
@dsoasti, your error message is different; for a solution to your problem see #4720.

**Comment by dsoasti** [comment]
Thanks!

**Comment by janezd** [comment]
I fear this will be filed under "unresolved misteries". Unless the error happens to somebody who can debug it.

**Comment by PerryGogas** [comment]
> Thank'you for your answer, I'll try and test the docker version next week.
> 
> Also, the command line version of the addon installer looks promising. Where can I find the names of the different addons? (orange3-text in your example).
> 
> AD

How can I do this guys? like this? I did this and didn't work...

![screenshot_974](https://github.com/user-attachments/assets/faf181ff-f8d9-4a73-bb9e-1d223f47de40)

**Comment by ajdapretnar** [comment]
@PerryGogas These are just preferences, not installation dialogue. To install add-ons, go to Options - Add-ons. There, you don't need to type the commands, just select the add-on you wish to install. If you wish to add another package to Orange environment, go to Add more... on the right, and enter the name of the package as seen on PyPi.

**Comment by PerryGogas** [comment]
> @PerryGogas These are just preferences, not installation dialogue. To install add-ons, go to Options - Add-ons. There, you don't need to type the commands, just select the add-on you wish to install. If you wish to add another package to Orange environment, go to Add more... on the right, and enter the name of the package as seen on PyPi.

Thanks! I tried it like that as you described but then I get this.

![image](https://github.com/user-attachments/assets/d827f29b-2c16-4511-ad9b-85255109a4ec)

**Comment by ajdapretnar** [comment]
Are you using conda? Because this could be the underlying issue. Conda often doesn't have up-to-date Orange versions, so there might be incompatibility with certain add-ons (my guess). To further solve the issue I'd need the OS, Orange version and how you installed it.

**Comment by PerryGogas** [comment]
> Are you using conda? Because this could be the underlying issue. Conda often doesn't have up-to-date Orange versions, so there might be incompatibility with certain add-ons (my guess). To further solve the issue I'd need the OS, Orange version and how you installed it.

I installed this as was required by Orange

![image](https://github.com/user-attachments/assets/aa67c0d9-1f7e-4d1a-822e-7e7bc1341a42)

The version is 3.36.0

I am trying to manually install the addons becasue I had this isssue:

![image](https://github.com/user-attachments/assets/fa78ed58-7115-4706-b94e-aa779dcafbc1)

The OS is Windows 10.
I installed it from: https://oldorange.biolab.si/download/#windows

**Comment by ajdapretnar** [comment]
@PerryGogas Would you mind posting the details from the previous error here? From when you tried to install the add-on manually? Click Show details and post it here, please.

**Comment by PerryGogas** [comment]
> @PerryGogas Would you mind posting the details from the previous error here? From when you tried to install the add-on manually? Click Show details and post it here, please.

If you mean this:
![image](https://github.com/user-attachments/assets/744f39cd-8c57-4658-b63b-c507484b3545)

The details are:

Traceback (most recent call last):
  File "C:\Program Files\Orange\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Program Files\Orange\lib\site-packages\orangecanvas\application\addons.py", line 510, in <lambda>
    lambda config=config: (config, list_available_versions(config)),
  File "C:\Program Files\Orange\lib\site-packages\orangecanvas\application\utils\addons.py", line 369, in list_available_versions
    response = session.get(PYPI_API_JSON.format(name=p))
  File "C:\Program Files\Orange\lib\site-packages\requests_cache\session.py", line 102, in get
    return self.request('GET', url, params=params, **kwargs)
  File "C:\Program Files\Orange\lib\site-packages\requests_cache\session.py", line 158, in request
    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore
  File "C:\Program Files\Orange\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files\Orange\lib\site-packages\requests_cache\session.py", line 194, in send
    actions.update_from_cached_response(cached_response, self.cache.create_key, **kwargs)
  File "C:\Program Files\Orange\lib\site-packages\requests_cache\policy\actions.py", line 184, in update_from_cached_response
    usable_response = self.is_usable(cached_response)
  File "C:\Program Files\Orange\lib\site-packages\requests_cache\policy\actions.py", line 152, in is_usable
    or (cached_response.is_expired and self._stale_while_revalidate is True)
  File "C:\Program Files\Orange\lib\site-packages\requests_cache\models\response.py", line 149, in is_expired
    return self.expires is not None and datetime.utcnow() >= self.expires
TypeError: can't compare offset-naive and offset-aware datetimes

**Comment by PerryGogas** [comment]
> @PerryGogas Would you mind posting the details from the previous error here? From when you tried to install the add-on manually? Click Show details and post it here, please.

When I go to:
![image](https://github.com/user-attachments/assets/d6c65578-24b1-4f72-9474-405c3cf6d7b2)

And I type this:

![image](https://github.com/user-attachments/assets/bf4d7f75-f8fb-4fc4-9263-6dc2c653932c)

I get:
![image](https://github.com/user-attachments/assets/589947c4-9d82-44ff-9fcd-d20a6c116aec)

But when I click OK I get:
![image](https://github.com/user-attachments/assets/b9de26a5-107b-41e9-9429-d1627ea96378)

The details are:
ERROR: Invalid requirement: 'conda-forge::orange3-explain'
WARNING: There was an error checking the latest version of pip.

**Comment by ajdapretnar** [comment]
Thanks for your report. I think this warrants opening a new issue. I'll discuss with the team and open one if necessary.

**Comment by PerryGogas** [comment]
> Thanks for your report. I think this warrants opening a new issue. I'll discuss with the team and open one if necessary.

**Thank you so much!**
I use Orange in my graduate courses and my students now have this issue while they have to submit their MBA thesis...

It all started from installing the 3.37.0 version.

**Comment by ajdapretnar** [comment]
p.s. Could you also add the "Show details" from the second error after trying to install orange3-explain.

**Comment by PerryGogas** [comment]
> p.s. Could you also add the "Show details" from the second error after trying to install orange3-explain.

Yes, I get this:

ERROR: Invalid requirement: 'conda-forge::orange3-explain'
WARNING: There was an error checking the latest version of pip.

**Comment by ajdapretnar** [comment]
Idea from a colleague: did you remove the pip arguments you had entered in the Settings?
![image](https://github.com/user-attachments/assets/a542baf2-bfb3-47e2-a625-5273d4aaa716)

**Comment by PerryGogas** [comment]
> From: [#6744 (comment)](https://github.com/biolab/orange3/issues/6744#issuecomment-1959335669)
> 
> Can you try moving/deleting 'C:\Users\%USERNAME%\AppData\Local\Orange\cache\networkcache' where %USERNAME% is your login name

I did it and while I was able to get to this screen:
![image](https://github.com/user-attachments/assets/35ff2409-488f-4daa-9e4b-9687565c267c)


After pressing OK to install the explain addon I got:
![image](https://github.com/user-attachments/assets/12d042a5-9a71-4521-96b8-9bdd2306422a)

And the details say:
ERROR: Invalid requirement: 'conda-forge::orange3-explain'
WARNING: There was an error checking the latest version of pip.

**Comment by PerryGogas** [comment]
> Idea from a colleague: did you remove the pip arguments you had entered in the Settings? ![image](https://private-user-images.githubusercontent.com/12524972/357400022-a542baf2-bfb3-47e2-a625-5273d4aaa716.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5ODE1ODksIm5iZiI6MTcyMzk4MTI4OSwicGF0aCI6Ii8xMjUyNDk3Mi8zNTc0MDAwMjItYTU0MmJhZjItYmZiMy00N2UyLWE2MjUtNTI3M2Q0YWFhNzE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDExNDEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjZTVjMjM0NzVhNjYzOWM1NTdhOTU1ZjU3YWIwNzRkNTZhNWI3OGEwYzQwYTMwZGRlNmZjYjA5NWQwOWQ5MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lje71gw16Gy2_cVC6BNJ3oeQG-OqRh7DalXpU85pKMQ)

I will try that.

**Comment by PerryGogas** [comment]
> Idea from a colleague: did you remove the pip arguments you had entered in the Settings? ![image](https://private-user-images.githubusercontent.com/12524972/357400022-a542baf2-bfb3-47e2-a625-5273d4aaa716.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5ODE5ODcsIm5iZiI6MTcyMzk4MTY4NywicGF0aCI6Ii8xMjUyNDk3Mi8zNTc0MDAwMjItYTU0MmJhZjItYmZiMy00N2UyLWE2MjUtNTI3M2Q0YWFhNzE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDExNDgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViMDA2ZDQwMGNiMGZkMjliN2JjNjZiNjNhM2Q0OTAzNGY2OWUwM2Q1NDJmY2EwMmU4NTU5ODc0MjE1MmY0N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TNpFHZ3OqriRt7uDayPthRAKIPo3VlwPq4o61RhlGtY)

I tried this:
![image](https://github.com/user-attachments/assets/e527de04-d136-481f-aaa0-b2f9feb18948)


And I managed to install "Explain" addon for the first time but now again ALL SVM models do not work:
![image](https://github.com/user-attachments/assets/a6dc83b2-9247-4fe2-b73d-10a8e9aef49c)

**Comment by kerrylmusungu** [comment]
Hello, I have the same problem but I do not have a mac, I have a Windows 11
Any help?

**Comment by PerryGogas** [comment]
> Hello, I have the same problem but I do not have a mac, I have a Windows 11 Any help?

The issue was solved in the new version.

**Comment by kerrylmusungu** [comment]
The new version of the orange software?

**Comment by PerryGogas** [comment]
> The new version of the orange software?

Yes, download the latest. It works now.

**Comment by kerrylmusungu** [comment]
Thanks

Kind regards,

[image: Kerryl A. Musungu]

[image: photo]

Kerryl A. Musungu
Data Scientist | Secret Clearance, US Army

240-758-1456  |  ***@***.***

Fort Cavasoz, Texas 76544
<https://maps.google.com/?q=Fort+Cavasoz,+Texas+76544>

[image: github] <https://github.com/kerrylmusungu>

[image: facebook] <https://www.facebook.com/kerryl.musungu/>

[image: instagram] <https://www.instagram.com/kerrylmusungu/>

[image: linkedin] <https://www.linkedin.com/in/kerryl-musungu/>

[image: twitter] <https://x.com/AjKerryll>
Create your own email signature
<https://www.wisestamp.com/lp/promo/professional-email-signature?utm_source=promotion&utm_medium=signature&utm_campaign=create_your_own&srcid=>

[image: __tpx__]
