### ISSUE TITLE
Numba Support?

### ISSUE THREAD

**Issue by realrk69** [biolab/orange3#4723]
Been using numba addon for internal company app development and backend services for some time now. Since orange heavily uses numpy loops and functions, is it not feasible to use numba to speed up or parallelize processes?

I have also recently seen numba reduce the training and optimization times heavily in tensorflow and keras.

**Comment by janezd** [comment]
Thanks for the suggestion, but we are actually trying to get rid of it. Orange depends on numba through one of it's libraries, but it causes various problems on different platforms, so we don't like it. I know it's just our experience, but ... that's how it is.

Numpy mostly does the job; when not, we prefer to do it in Cython.

**Comment by realrk69** [comment]
I understand. I tried using it for a widget I was working on, because of many loops that involve numpy iteration, it was considerably faster, but it is less important than the stability of the overall platform.
