### ISSUE TITLE
Line Chart missing graph output

### ISSUE THREAD

**Issue by Norsusan** [biolab/orange3#4724]
![2020-05-03_090617](https://user-images.githubusercontent.com/29728592/80916520-30314e00-8d27-11ea-82f2-987950762b79.jpg)
**Orange version:**
Orange3 3.25.0

**Expected behavior**
Line Chart should show Forecast, 95% CI Upper and 95% Lower

Also label description for High (Forecast: 95% CI) missing "Lower"

**Operating system:**
Windows 10 64 Bit

**Additional context**
![2020-05-03_095648](https://user-images.githubusercontent.com/29728592/80916523-345d6b80-8d27-11ea-9a81-64f7cadc2ba2.jpg)

**Comment by ajdapretnar** [comment]
Please report this to the corresponding Timeseries add-on.
