### ISSUE TITLE
Orange 3.23.1 Launches from Anaconda Navigator then closes.

### ISSUE THREAD

**Issue by psychofarm** [biolab/orange3#4731]
Orange 3.23.1 Launches from Anaconda Navigator then closes.

The application launches and is visible for a moment then closes.

1. Go to Anaconda Navigator
2. Click on Launch for Orange 3
3. App appears
4. Watch it close even if you try and click on something

**Orange version:**
Orange 3.23.1

**Expected behavior**
The app should open and allow the user to select items.

**Screenshots**
none

**Operating system:**
Windows 10

**Additional context**
Reinstalled Anaconda and reinstalled Orange 3.
Orange 3 is in a virtual environment.
Tried running from command line:
C:\Users\c131305\Anaconda3\envs\orange\lib\site-packages\Orange\canvas\__main__.py:479: DeprecationWarning: 'Orange.canvas.config.widget_settings_dir' is deprecated.
  config.widget_settings_dir(), "DELETE_ON_START")

**Comment by ales-erjavec** [comment]
Can you please run 
```
conda list -n orange --explicit > C:\Users\c131305\orange-env.txt 
```
from the Command Prompt and post the contents of the C:\Users\c131305\orange-env.txt file.

**Comment by janezd** [comment]
Closed due to inactivity.
