### ISSUE TITLE
Display failure Distribution Widget

### ISSUE THREAD

**Issue by dorangezs** [biolab/orange3#4736]
Using distribution widget with "Normal"-distribution, shows mue and sigma^2 (variance) in the diagram (top-right).
The value for mue is correct, but the value for sigma^2 is wrong. Its the value for sigma.
So you have to change sigma^2 to sigma (without changing the value) or have to show value^2.

See the picture, sigma is 17.6.. , sigma^2 would be 309....

![grafik](https://user-images.githubusercontent.com/64842403/81062745-d1aad200-8ed6-11ea-8d8a-803f84c7dc29.png)

**Orange version:**
3.23.1.

**Operating system:**
Windows 7

**Comment by janezd** [comment]
You're right. Thanks.
