### ISSUE TITLE
Documentation: Update images

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#4752]
Here is a list of widgets whose images in the documentation have to be updated. Tag minor means a single button changed or something similar. Some widgets have such insignificant differences, that were not listed here.

- [x] Rank
- [ ] Merge Data (minor)
- [ ] Transpose (minor)
- [x] Edit Domain
- [x] Save Data
- [x] Box Plot
- [x] Distributions
- [x] Scatter Plot
- [ ] Mosaic Display (minor)
- [ ] FreeViz
- [x] Linear Projection
- [ ] RadViz
- [ ] HeatMap
- [ ] Silhouette Plot (minor)
- [ ] Nomogram (minor)
- [ ] Random Forest (minor)
- [ ] Neural Network
- [ ] SGD
- [ ] Save Model
- [ ] Predictions
- [ ] Confusion Matrix
- [ ] Calibration Plot
- [x] t-SNE
- [ ] Hierarchical Clustering
- [ ] k-Means
- [ ] Louvain Clustering
- [ ] Manifold Learning
- [ ] MDS
- [ ] Save Distance Matrix

**Comment by janezd** [comment]
Maybe add a script (test) to check whether the widget has visually changed.
