### ISSUE TITLE
Saving data into CSV file

### ISSUE THREAD

**Issue by ferri1374** [biolab/orange3#4756]
**Describe the bug**

I can't convert data into CSV file

**To Reproduce**

I have made a data table of clustering results and I want to save it into a CSV or EXCEL file. Is this practicable in Orange3? How can I export data into a CSV file?

**Orange version:**
Orange3.24

**Expected behavior**

**Screenshots**

**Operating system:**
Windows

**Additional context**

**Comment by ajdapretnar** [comment]
https://orange.biolab.si/widget-catalog/data/save/

**Comment by ferri1374** [comment]
I tried it. But I want to save it in CSV format. It just supports .pkl

**Comment by ajdapretnar** [comment]
Then you either are not saving the right thing or your question is ill-posed. Clustering in Orange results in an Orange.data.Table, which can be saved as .csv. Alternatively, expand on your question.

**Comment by ferri1374** [comment]
Well, I did it. Thank you for your response. 
I deactivated 'select full row' option in data table and selected needed data. So, It worked.

**Comment by ferri1374** [comment]
Well, I did it. Thank you for your response. 
I deactivated 'select full row' option in data table and selected needed data. So, It worked.
