### ISSUE TITLE
Orange3.25.0 Select columns does not apply filter on output

### ISSUE THREAD

**Issue by Jmolenberghs** [biolab/orange3#4759]
**Select columns does not apply filter on output**

Select Columns widget when 1 column is selected connected to a Venn Diagram widget should give **the number of unique values** of said column, however **all rows are returned**.

**To Reproduce**

1. Connect "File" widget (eg Iris dataset) to "Select Columns" widget
2. Open 'Select columns' widget
3. Select "petal width" as feature, "iris" as target variable
4. Connect "Venn Diagram"-widget to Select Columns"-widget
5. Open "Venn Diagram"-widget
6. See incorrect data (150)

**Orange version:**
3.25.0

**Expected behavior**
In previous versions it would give 27 instances in step 6

**Screenshots**
in orange3.25.0:
![screenshot_venndiagram](https://user-images.githubusercontent.com/37439103/81568957-d4a63680-939e-11ea-914c-0e0486942b24.png)

Expected behavior in orange3.24.1:
![image](https://user-images.githubusercontent.com/37439103/81569092-13d48780-939f-11ea-81e9-dfc7b7c57876.png)

**Operating system:**
Windows 10
Ubuntu 19.10

**Additional context**
NA

**Comment by janezd** [comment]
Select Columns selects and rearranges columns (http://docs.biolab.si/3/visual-programming/widgets/data/selectcolumns.html) It doesn't do anything related to unique values.

Venn Diagram shows sets whose elements are rows, identified by suitable (key-like) identifiers (which are not present in this data). (https://orange3.readthedocs.io/en/3.5.0/widgets/visualize/venndiagram.html)

Everything works as expected.

There's a Unique widget in the prototype add-on. It may not be complete and fully stable and mature, but might help you.

**Comment by Jmolenberghs** [comment]
Ok, but why did the same sequence give this venn diagram in orange3.24.1?
![image](https://user-images.githubusercontent.com/37439103/81602346-b3f4d580-93cc-11ea-8968-9771fb0c4442.png)

**Comment by janezd** [comment]
Venn has been largely rewritten. This must had been one of its bugs. It wasn't supposed to do that.
