### ISSUE TITLE
Why the Distributions widget UI different from Docs?

### ISSUE THREAD

**Issue by GF-Huang** [biolab/orange3#4761]
![image](https://user-images.githubusercontent.com/4510984/81719006-0dcdcc00-94af-11ea-890c-37db4867d249.png)

I had import continuous data, but it show as discrete, how can I force it displayed as continuous?

**Orange version:**
`3.25.0` by Anaconda

**Operating system:**
`Windows 1909`

**Comment by janezd** [comment]
I'm sorry, I don't understand you. The distribution widget looks empty. Does it have any data at all? What do you mean by "It shows as discrete"?

**Comment by GF-Huang** [comment]
@janezd Look this, please.

![image](https://user-images.githubusercontent.com/4510984/81733286-593ea500-94c4-11ea-8ae1-b9da86812758.png)

**Comment by janezd** [comment]
OK, so Price Change is a numeric variable and Distribution shows it as numeric - in form of a (cumulative) histogram. What do you mean by "showing it as continuous"? What do you expect it to look like?

**Comment by GF-Huang** [comment]
I hope them displayed like this, because PriceChange is continuous attribute.

![image](https://user-images.githubusercontent.com/4510984/81736303-ebe14300-94c8-11ea-9680-85febab01dd4.png)

![image](https://user-images.githubusercontent.com/4510984/81736374-087d7b00-94c9-11ea-9507-20b60410668d.png)

**Comment by janezd** [comment]
To fit a curve to your data, you have to choose a type of curve to fit. There's a nice choice of them under "Fitted distribution".

Documentation is not really updated, but if the widget looks different from its docs, feel free to click around. :)

**Comment by GF-Huang** [comment]
Understood, thank you.
