### ISSUE TITLE
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)

### ISSUE THREAD

**Issue by GF-Huang** [biolab/orange3#4762]
**Describe the bug**
![image](https://user-images.githubusercontent.com/4510984/81771998-325d8e80-9517-11ea-9bb9-77f104333658.png)

![image](https://user-images.githubusercontent.com/4510984/81771966-19ed7400-9517-11ea-8941-7ec40ff4defb.png)

**Orange version:**
`3.25.0` by Anaconda

**Expected behavior**
No errors.

**Operating system:**
`Windows 10 x64 1909`

**Comment by PrimozGodec** [comment]
Thank you for reporting this. I tried to reproduce this bug on a few datasets but did not get the error. Is there any possibility (if data are ok to share with us) that you send us data or a small subset on which the error happens.

**Comment by GF-Huang** [comment]
Could you give me an email for receiving my data? I’m outside now, I will send you later.

**Comment by janezd** [comment]
You could also upload it here, but it seems very large. Could you try to reduce the number of rows and see if the error remains? Try to see what you must change to make the error go away. This will help you provide us with a better error report. Also, by doing this you will possibly find the cause of the problem yourself and thus help us resolve it (if it will turn out it needs resolving).

**Comment by GF-Huang** [comment]
When I reduce the dataset to 10,000 records, it show me this:

![image](https://user-images.githubusercontent.com/4510984/81900773-137efb00-95f0-11ea-8369-07ee095a98fe.png)

**Comment by janezd** [comment]
So this problem is probably related to the size of the data set. The error message probably comes from sklearn, so the problem is in that library. It might be that Orange cannot help here.

The messagethat  you got is OK. If the sample is too large, Orange does not compute the silhouette score because it would be too slow.

**Comment by GF-Huang** [comment]
OK, thank you.
