### ISSUE TITLE
Heatmap colour annotation not updating

### ISSUE THREAD

**Issue by Hrovatin** [biolab/orange3#4766]
Latest master:
When I use heatmap colour annotations and I try to switch between categorical features the heatmap is not updated. 
Example: 
I start with categorical_A as annotation -> The heatmap displays annotation and the annotation selection menu is set to categorical_A. 
Then I switch to categorical_B. - > The annotation selection menu changes to categorical_B, but the heatmap still displays categorical_A. 
I can only set the categorical_B to be displayed in the heatmap by first setting the colour annotation _(None)_ and then switching to categorical_B.
The same bug is present in Split by.

**Comment by ajdapretnar** [comment]
I cannot reproduce on the latest master. 🤷

**Comment by Hrovatin** [comment]
It seems to be data instance specific. When I saved heatmap input data with header annotations and loaded it  again this did not happen anymore. 
I can no longer switch between categorical after Merge Data (1), but before it I have only 1 categorical variable so I can not test if this happens due to the Merge Data.
![Screenshot from 2020-05-15 14-44-07](https://user-images.githubusercontent.com/47607471/82051704-ac7a4880-96ba-11ea-96a1-391d3e3ba7c7.png)

**Comment by ajdapretnar** [comment]
It is very hard to debug such a complex workflow. Any chance to reproduce this on a smaller one?

I have tried with Merge Data and everything works fine.

**Comment by ales-erjavec** [comment]
A simpler case:
![Screen Shot 2020-05-15 at 16 13 08](https://user-images.githubusercontent.com/4716745/82059994-084ace80-96c7-11ea-92d1-0d56f196ab7a.png)

The error is that `domain["Cluster"] == domain["Cluster New"]` which shortcircuts the update in https://github.com/biolab/orange3/blob/24a49675f3cf8df90babb95397050cfe225925b1/Orange/widgets/visualize/owheatmap.py#L953

**Comment by ajdapretnar** [comment]
Thanks @ales-erjavec for this example!
I think this is way beyond just calling update() at the right time. Probably @janezd has to have a say in this, because it most likely goes all the way to `__eq__`.

**Comment by janezd** [comment]
I don't have anything to say. I don't think we can change `__eq__`.

`__eq__` is quite imperfect, but still better than `Variable.make`. We have different levels of equality, and this example would require a stricter one than most other contexts.

**Comment by ajdapretnar** [comment]
My dumbass fix would be `if self.annotation_color_var.name != var.name`.... But I suppose this could lead to other sorts of problems.

**Comment by ales-erjavec** [comment]
On a related note, this is a problem:
```python
>>> domain["Cluster"] == domain["Cluster New"]
True
>>> hash(domain["Cluster"]) == hash(domain["Cluster New"])
False
```

**Comment by Hrovatin** [comment]
The same issue happens in other widgets, like Venn Diagram. 
![Screenshot from 2020-05-26 13-15-04](https://user-images.githubusercontent.com/47607471/82894487-eff27380-9f52-11ea-8e57-fe7d46947139.png)
Here I have two tables - one of them has a column _Gene_ and the other does not have it, so I had changed one of the columns to _Gene_ with Edit Domain. When I try to compare them in Venn Diagram I can not select the column Gene for matching, as it thinks it is missing from one of the tables. If I  change the column names in the file before loading data into the Orange the Venn Diagram matching works as expected.
