### ISSUE TITLE
Feature statistics does not write anything into the report.

### ISSUE THREAD

**Issue by WolframRinke** [biolab/orange3#4773]
**Describe the bug**
Take any data from file or dataset and connect it toa  feature widget.
This generates a nice table and statistics with historgrams. But when pressing the report butten it generates a report entry, which is empty.

**Here**, provide a clear and concise description of what the bug is.

**To Reproduce**
Take any data from file or dataset and connect it toa  feature widget.
This generates a nice table and statistics with historgrams. But when pressing the report butten it generates a report entry, which is empty.

Steps to reproduce the behavior go **here**:

**Orange version:**
Orange - 3.24.1 and 3.25.0

**Expected behavior**

**Screenshots**

**Operating system:**
Windows, OSX or Linux? Which version?

**Additional context**

**Comment by janezd** [comment]
Or, to quote the widget's code:

```python
    def send_report(self):
        pass
```

:)

I noticed that not so long ago, but forgot to write the issue, so thanks for reporting.

Don't expect the solution soon. It will require some work. That *pass* there isn't without a reason. :)

**Comment by WolframRinke** [comment]
Ohhh, maybe the report button can be deactivated unless a solution is found.

:-)

Thank you for the feedback,
Wolfram


Am 14.05.2020 um 18:52 schrieb Janez Demšar <notifications@github.com<mailto:notifications@github.com>>:



Or, to quote the widget's code:

    def send_report(self):
        pass

:)

I noticed that not so long ago, but forgot to write the issue, so thanks for reporting.

Don't expect the solution soon. It will require some work. That pass there isn't without a reason. :)

**Comment by PrimozGodec** [comment]
I can work on this one. @janezd, so report for this widget would have a table, similar to one in the widget right?

![Screenshot 2020-05-21 at 11 35 31](https://user-images.githubusercontent.com/6421558/82545704-580e1780-9b57-11ea-97a2-6fbee0358d58.png)

**Comment by janezd** [comment]
Great.

Yes, it should look the same. With images, too.

**Comment by WolframRinke** [comment]
Yes this would be great. I can feed the output to a table and weite it to a report, but doing this in one step is more easy.
Kind regards, Wolfram

Von meinem iPhone gesendet

Am 21.05.2020 um 11:37 schrieb Primož Godec <notifications@github.com>:

﻿

I can work on this one. @janezd<https://github.com/janezd>, so report for this widget would have a table, similar to one in the widget right?

[Screenshot 2020-05-21 at 11 35 31]<https://user-images.githubusercontent.com/6421558/82545704-580e1780-9b57-11ea-97a2-6fbee0358d58.png>
