### ISSUE TITLE
How to reduce DBSCAN memory usage?

### ISSUE THREAD

**Issue by GF-Huang** [biolab/orange3#4774]
![image](https://user-images.githubusercontent.com/4510984/81967234-38ee2200-964d-11ea-8be8-7b84fe693965.png)

**Orange version:**
`3.25.0` by Anaconda

**Expected behavior**
Less memory usage.

**Operating system:**
`Windows 10 1909 x64`

**Comment by janezd** [comment]
You can't. This is DBSCAN from scikit-learn and it does what it does. (I believe it is well-written because sklearn is not some garage library...)
