### ISSUE TITLE
Edit Domain: replace Ordered with Sort numerically

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#4778]
**Is your feature request related to a problem? Please describe.**

Orange sorts labels in categorical variables alphabetically. I often have numeric labels, such as months of the year (1, 2, 3, 4, 5,...11, 12). When using Pivot Table or some visualization, the labels would be ordered in a wrong way, that is 1, 11, 12, 2, 3,...

**Describe the solution you'd like**

Remove Ordered checkbox from Edit Domain. We assume it does not do anything (is not considered anywhere). Check before removing.
Then replace this with a radio button (or something appropriate) that enables switching between numeric and alphabetic sorting. If labels cannot be interpreted as ints or floats (probably doesn't apply to time variable), then always sort alphabetically.

**Describe alternatives you've considered**
When constructing a Data Table we could check if labels are numbers and sort numerically by default.

**Additional context**
Perhaps it would be nice to have this option in Edit Domain to enable the user some flexibility.

**Comment by PrimozGodec** [comment]
I think that numbers should be always sorted as numbers. I don't see the case when numbers should be sorted as ["1", "12", "2", ...]. This is why I propose a solution where numbers would be always sorted as numbers even in the middle of the string. 
E. g.:
```
[ 
    "something1",
    "something12",
    "something29"
    "something17",
    "something2",
    "something25",
]
```
should be sorted as:
```
[ 
    "something1",
    "something2",
    "something12",
    "something17",
    "something25",
    "something29"
]
```
So, in my opinion, we don't need an option to select the type of sorting but just sort all numbers as numbers. If we decide on a solution with two types of sorting as you proposed. Then the second option (sort as numbers) should include the case where we have letters and numbers mixed.

**Comment by ajdapretnar** [comment]
No, I am absolutely fine with always sorting by numbers. I just thought there might be a use case for alphabetical sorting, but I can't think of one.

While doing this, we should check whether 'Ordered' does anything at all and remove it if not.

**Comment by PrimozGodec** [comment]
Great. I can dig into it. :)
