### ISSUE TITLE
CSV File Import: save file as relative

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#4784]
**Describe the bug**
Sharing workflows with CSV File Import is impossible, because CSV File Import stores absolute path rather than relative.

**To Reproduce**
Save a workflow with CSV File Import.
Move both the workflow and file somewhere else.
Reload the workflow.

**Orange version:**
3.26.0.dev

**Expected behavior**
CSV File Import behaves like File, load the file if it is in the same directory (or subdirectories) to the workflow.

**Comment by ajdapretnar** [comment]
Not sure if part of this issue, but when trying to reload a file by manually selecting it, settings are not restored.
So the file in CSV File Import widget should be test.csv. I saved it with 'split by semicolon' and such and such column roles.
Then I manually select test.csv on a different computer, because as mentioned above, it didn't load correctly. None of my settings are stored.
The widget should remember separator and everything, then try to apply it to the new file.

**Comment by janezd** [comment]
Merged into #3997.
