### ISSUE TITLE
Discretize widget Entropy-MDL can not select

### ISSUE THREAD

**Issue by GF-Huang** [biolab/orange3#4786]
**Describe the bug**
![image](https://user-images.githubusercontent.com/4510984/82198094-662d1f80-992e-11ea-8c63-da6d7f1fd834.png)

**Orange version:**
`3.25.0` by Anaconda

**Expected behavior**
Entropy-MDL can select, not gray.

**Operating system:**
`Windows 10 1909 x64`

**Comment by janezd** [comment]
When an option is disabled, it's usually with a reason. Have you checked what this method does and requires, and whether your data fulfills this requirements?

From [documentation](http://docs.biolab.si/3/visual-programming/widgets/data/discretize.html): *Entropy-MDL, invented by Fayyad and Irani is a top-down discretization, which recursively splits the attribute at a cut maximizing information gain, until the gain is lower than the minimal description length of the cut.* Is this doable on your data?

**Comment by ales-erjavec** [comment]
Entropy-MDL requires data with a categorical target variable.
