### ISSUE TITLE
Heat map center value feature request

### ISSUE THREAD

**Issue by leeherman99** [biolab/orange3#4789]
**Is your feature request related to a problem? Please describe.**

When generating Heat Maps, I would like to be able to display the data relative to some central value. For instance, if 1 is a "no effect" value, I'd like to see values >1 light up as red, <1 as green, for instance. 

**Describe the solution you'd like**

I'm using the latest Orange available in Anaconda, v3.25.

Scaling in the heat map widget seems to be a moving target. You used to be able to center the colors around 0. That was sometimes useful when you had data that was actually centered around 0. Now that's gone. It would be nice to be able to center around an arbitrary value. For instance, I have some data that's centered around 0, others that is centered around 1.

**Describe alternatives you've considered**
My only alternative now is to use the sliders that control the High and Low values manually. However, that has to be changed as the data changes.

**Additional context**

**Comment by Hrovatin** [comment]
For 0-centering you can use the Diverging pallets which are centered at 0. A work around for visually centering the palette at a specific value might be the use of Feature Constructor. A new feature could be generated so that it has 0 at the desired center of the original feature. However, this would be impractical for large number of features and the legend would be shifted due to the processing of the original feature.

**Comment by leeherman99** [comment]
Thanks for the suggestion, but I'm in the situation you mentioned - lots of features. Also, that workaround is not useful when you want to examine the original values in the heatmap.

**Comment by janezd** [comment]
@leeherman99, we discussed this at today's meeting. This is one of "would be nice to have" features. We'll see whether it is easy to implement and incorporate into user interface. If it is (which will be the case, I'm guessing), we'll add it. If it would overly complicate the code or the interface, we'll decide it is not nice enough to have. :)

**Comment by leeherman99** [comment]
Janez

I would remind you that you already have the code to do this, since the
capability to center on zero existed for a long time on this widget, until
the very latest version. All you would have to do is parameterize the
center point.

Lee

**Comment by janezd** [comment]
Heatmap still centers to zero if you choose one of diverging palettes (at least it should). The code is still there, we just eliminated the checkbox because it doesn't make sense to use a diverging palette unless you want to center, and it doesn't make sense to center without a diverging palette.

**Comment by leeherman99** [comment]
Yes, but as I mentioned earlier, sometimes you want to center on a value other than zero (one, for example).

**Comment by janezd** [comment]
Yes, sure, I just wanted to answer that the code for centering is still there. :) We'll add parametrization if it doesn't complicate things. Sometimes a simple request can turn out to be ugly to implement.

**Comment by leeherman99** [comment]
Yes, I understand that. Somehow I doubt that this the case here.

Another advantage of tuneable centers is that it gives you the flexibility
to make just about any color scheme approximate a diverging palette.
