### ISSUE TITLE
Heat Map - possible bug

### ISSUE THREAD

**Issue by mkosovic1981** [biolab/orange3#4790]
I have made a heat map of the raw iris data and a heat map after of the same data after hierarchical clustering. It seems that there are no difference at all. Could you please check it?

Orange version 3.25.0

[clustering-iris-possibleBug.zip](https://github.com/biolab/orange3/files/4645296/clustering-iris-possibleBug.zip)

**Comment by ajdapretnar** [comment]
Your issue is insufficiently described. What are you expecting to see in Heat Map? It shows numeric attributes. Seems nothing wrong to me.
