### ISSUE TITLE
CN2 with multiplicative weights

### ISSUE THREAD

**Issue by EnriMK** [biolab/orange3#4792]
One of the algorithms that I'm implementing is CN2-SD, which can be simulated using the algorithm CN2 of Orange with the "unordered" and "multiplicative weights" parameters. Therefore, I'm using your software to contrast my results and to validate them.

However, there is one part in which our implementations differ and one of them does not work properly. After decreasing the weights, the rules discovered by the Orange implementation are not the same that the ones discovered using my implementation. I've done some simulations by hand and thoroughly debugged and I don't understand how your implementation is selecting a new rule after decreasing the weights. Let me illustrate this issue with an example.

##### Orange version
3.23.1

##### Expected behavior
Let's focus just on the type = mammal rule induction (see next picture).
In the first beam search (as described by Lavrac et. al, 2004), the rule "milk = 1 -> type = mammals" with quality 0.241 is discovered. 
Then, the weights of the covered examples decrease by multiplying by 0.1. 
A second beam search for the type = mammal is launched and the rule "milk != 0 AND eggs = 0", whose quality is 0.058, is discovered.
![Expected results](https://user-images.githubusercontent.com/43936050/82304938-485acb80-99bd-11ea-9659-785593a741e7.png)

##### Actual behavior
My implementation also discovers the rule "milk = 1 -> type = mammals" with WRAcc 0.241
Then, the weights are also decreased.
In the second beam search, however, the rule discovered is again "milk = 1 -> type = mammals", which has a higher quality (0.06). In the original algorithm, it is not specified that repeated rules should avoided (and I would like to know how orange avoid it). In any case, "milk != 0 -> type = mammals" and "feather = 0 AND milk = 1 -> type = mammals" has still better quality than the rule discovered by Orange. (Trace at the end of the document)
In the following beam searchs, the rule "milk = 1 -> type = mammals" will be discovered again and again.

##### Steps to reproduce the behavior
The database used will be zoo.tab, included in the Orange tool
The parameters used will be:
	Rule ordering: Unordered
	Covering algorithm: Weighted, gamma = 0.1
	Evaluation measure: WRAcc
	Beam width = 2
	Minimum rule coverage = 1
	Maximum rule length = 3
Use CN2 rules and CN2 rules viewer

##### Overall question
What does Orange CN2 to avoid finding the rules again and again like in my algorithm and why? Is that included in the original algorithm by Lavrac? Also, is there a internal minimum quality for the induced rules?

My idea is that Orange removes from the beam search the conditions that have already been used. For this example, milk = 1 will not be used in the second beam search. However, we could still use milk != 0 which in this case is virtually the same (and the results would still be different).

##### Additional info (worksheets, data, screenshots, ...)
Subgroups founded be my algorithm:
```
Subgroups founded
Subgroup 0: Condition: [milk = one], Target: (type = mammal)
	 Quality: 0.24115282815410255
Subgroup 1: Condition: [eggs != zero, fins != zero], Target: (type = fish)
	 Quality: 0.11214586805215175
Subgroup 2: Condition: [feathers != zero], Target: (type = bird)
	 Quality: 0.1588079600039212
Subgroup 3: Condition: [airborne != one, backbone != one], Target: (type = invertebrate)
	 Quality: 0.08724634839721596
Subgroup 4: Condition: [aquatic != one, legs = six], Target: (type = insect)
	 Quality: 0.07293402607587492
Subgroup 5: Condition: [aquatic != zero, hair != one, legs = four], Target: (type = amphibian)
	 Quality: 0.03764336829722576
Subgroup 6: Condition: [feathers != one, hair != one, tail != zero], Target: (type = reptile)
	 Quality: 0.03872169395157337
```

My trace for type = mammal
[Beam search trace.txt](https://github.com/biolab/orange3/files/4649401/Beam.search.trace.txt)

**Comment by janezd** [comment]
To be honest: CN2 was programmed by somebody who did this as a single gig, and who's no longer available. (It was at Google's Summer of code, many years ago.) Since then, nobody touched this code and nobody knows it. You are as much (and probably more) of an expert as anybody else. Would you have time to investigate this and fix it, if needed?

**Comment by EnriMK** [comment]
> To be honest: CN2 was programmed by somebody who did this as a single gig, and who's no longer available. (It was at Google's Summer of code, many years ago.) Since then, nobody touched this code and nobody knows it. You are as much (and probably more) of an expert as anybody else. Would you have time to investigate this and fix it, if needed?

Yes, I really would like to work on it. However, I cannot tell you when I will finish to fix or investigate the issue.

How can I start collaborating?

Best regards, Enrique

**Comment by janezd** [comment]
Fork the repository and clone it, or just clone it, then start looking at the code... When you find something you'd want to change, do it -- or discuss it here, if you want.

I'll close the issue for now, just for the sake of keeping the number small (we go through entire list every Friday, so we prefer to keep those that we need to act on). But you're very welcome to work on it.
