### ISSUE TITLE
CSV Import interpret discrete variables from the CSV file as StringVariable

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/orange3#4794]
**Describe the bug**

CSV Import interprets discrete variables from the CSV file as StringVariable.

**To Reproduce**

1. Place CSV import widget at the canvas
2. Open a CSV file that has columns that should be categorical - Iris column in the Iris dataset.
3. Leave Column Type Automatic
4. Connect data table and see that categorical features are in meta as String variables

**Orange version:**

master

**Expected behavior**

CSV Import interprets discrete variables from the CSV file as DiscreteVariable - the same heuristic can be used as in the File widget.

**The question here is, is it worth to invest time and fix this issue since we are planning to merge this widget with the File widget?**

**Comment by janezd** [comment]
Friday's note: @PrimozGodec will explore whether it is possible to improve detection of variable types without hurting the speed and memory requirements.

**Comment by ales-erjavec** [comment]
Closed by gh-4838
