### ISSUE TITLE
PCA widget fails: "list index out of range"

### ISSUE THREAD

**Issue by dgraselli** [biolab/orange3#4795]
**Describe the bug**
PCA widget fails at once

**Here**, provide a clear and concise description of what the bug is.
When simply add PCA and connect from file dataset, fails showing a trace of python code with the las msg: ''list index out of range" 

**To Reproduce**
just add a File widget, (ie. iris) and connect to PCA 

Steps to reproduce the behavior go **here**:
1. Go to 'new File'
2. Right Click on 'workspace'
3. Scroll down to 'select File'
4. Configure with 'iris' dataset
5. Conect to new clean PCA widget
6. After a seconds, fails with a trace log error msg. 

**Orange version:**
Orange version 3.23.1

**Expected behavior**
I expect to works like in the video tutorial 09
https://www.youtube.com/watch?v=OmaAC8a52YI&list=PLmNPvQr9Tf-ZSDLwOzxpvY-HrE0yv-8Fy&index=9

**Screenshots**

![Peek 19-05-2020 12-33](https://user-images.githubusercontent.com/3998003/82346616-0fc2ee00-99cd-11ea-88e6-f2248eab6f1b.gif)

**Operating system:**
Linux Mint 19.1 Cinnamon

**Additional context**
Anaconda Navigator 1.9.12

**Comment by PrimozGodec** [comment]
Thank you for submitting the issue. It happened since one of the packages we used was changed. We are fixing it in https://github.com/biolab/orange3/pull/4768
For a meanwhile, you can manually downgrade the version of the scikit-learn package with 
```
conda install scikit-learn==0.22.*
```
