### ISSUE TITLE
Warn the user if updating/installing add-ons will also update Orange

### ISSUE THREAD

**Issue by marcusmills** [biolab/orange3#4797]
When you have Orange 3.24.1 installed and install all the add-ons (excluding the 3.24.1 < 3.25 option, Orange gets automatically upgraded to 3.25

Steps to reproduce:
1. Install Orange 3.24.1 on Windows
2. Click on 'Options'
3. Click on ' Add-ons...'
4. Tick all checkboxes except the last one.
5. Click "OK"
6. Click "Close"
7. Start Orange
8. Orange has now been upgraded to 3.25

**Orange version:**
Orange - About - version number.

**Expected behavior**

**Screenshots**

**Operating system:**
Windows, OSX or Linux? Which version?

**Additional context**

**Comment by ajdapretnar** [comment]
Yes, it was supposed to be like that. Add-on require latest version of Orange.

**Comment by janezd** [comment]
@ajdapretnar, you closed it before I even got notification.

I agree this can't be any different, but perhaps we may want warn the user about it?

**Comment by marcusmills** [comment]
I have narrowed the upgrade down to just the Orange3-ImageAnalytics Add-on - when this is not selected Orange is not upgraded.

**Comment by PrimozGodec** [comment]
It should happen in the case of orange3-text too. Both add-ons depend on changes added in orange with the version 3.25.0

**Comment by marcusmills** [comment]
orange-text add-on that was installed is version 0.7.1 and is offering an upgrade to 0.9.1 - If I upgrade to 0.9.1, yes that triggers the orange upgrade to 3.25 but it does not get updated, with this error: https://gist.github.com/marcusmills/48b98b61a976a5b669e710472e8fca73
Running the upgrade again, after restarting Orange seems to work ok

**Comment by janezd** [comment]
Note from today's discussion: we should notify the user that updating add-ons will result in updating Orange (hopefully, we can easily detect this?) and let him/her cancel the update.
