### ISSUE TITLE
Data sampler: cross validation sampling type is inconsistent

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#4802]
**Describe the bug**

Not exactly a bug, just slight inconsistency.

Bootstrap sends the "training" data to the Data Sample output, while Cross Validation sends the single chosen fold, analogous to testing data. The fixed proportion of data with its default of 70% also implies that the training set goes to the Data Sample output.

This is a problem when switching between sampling types, because the outputs need to be reconnected for CV.

![Screenshot 2020-05-21 at 20 49 37](https://user-images.githubusercontent.com/552182/82595164-6c790100-9ba5-11ea-82e4-28c6e52e8323.png)

We could solve it by changing by swapping the output meaning and, for clarity, changing "Selected fold" into "Remaining fold".

This would break saved workflows, which we could avoid by detecting the old version, put up a warning that shows that the widget is in "compatibility mode", and show label "Sampled fold" instead of "Selected fold".

**Comment by janezd** [comment]
Friday's note: rename "folds" to "subsets", and "Selected fold" to something more informative (but maybe nicer than "Unselected subset" :).
