### ISSUE TITLE
Scatter Plot: Disable opacity on subset input

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#4808]
**Describe the bug**

Opacity in Scatter Plot is effectively disabled on subset input. However, GUI doesn't reflect this.

**To Reproduce**

File (iris) - Scatter Plot.
File - Data Table (select subset) - Scatter Plot.
Try to move Opacity slider.

**Orange version:**
3.26.0.dev

**Expected behavior**
Buttons that don't have an effect in a particular situation are disabled.

**Comment by janezd** [comment]
Huh, works for me?!?!

The code that disables it is here: https://github.com/biolab/orange3/blob/master/Orange/widgets/visualize/utils/widget.py#L472.

**Comment by ajdapretnar** [comment]
Um, I have this code on master...? 😕 Yet it doesn't seem to work. What is happening?

```
AnyQt==0.0.10
PyQt5==5.14.2
PyQt5-sip==12.7.2
pyqtgraph==0.10.0
PyQtWebEngine==5.14.0
QtPy==1.9.0
```

**Comment by janezd** [comment]
Could you debug it by, say, just adding `print(subset is None)` after the line that should disable the slider?

**Comment by ajdapretnar** [comment]
`False.` 🤷

**Comment by janezd** [comment]
🤷🏻‍♂️ An hitherto unknown Qt's glitch/feature?

**Comment by ajdapretnar** [comment]
Possibly. It increasingly seems like my computer decided to go rouge.
