### ISSUE TITLE
Orange instalation

### ISSUE THREAD

**Issue by Terezia-cell** [biolab/orange3#4814]
**Unexpected error during the instalation

**Orange version:**
Orange - 3.25.0

**Expected behavior**
To install the Orange for Windows 64bit

**Screenshots**
![image](https://user-images.githubusercontent.com/65908346/82821649-c24ef100-9ea4-11ea-80a0-d0969e730149.png)

**Operating system:**
Windows

**Additional context**

**Comment by ales-erjavec** [comment]
Can you please post the entire error contents (right click on the text and copy all to clipboard).

**Comment by Terezia-cell** [comment]
Yes :)

Creating an new conda env in "C:\Program Files\Orange"
Output folder: C:\Users\terez\AppData\Local\Temp\nscD32B.tmp\Orange-installer-data\conda-pkgs
Extract: anyqt-0.0.10-py37_0.conda
Extract: asn1crypto-1.3.0-py37_0.conda
Extract: baycomp-1.0.2-py_1.tar.bz2
Extract: blas-1.0-mkl.conda
Extract: bottleneck-1.2.1-py37h452e1ab_1.conda
Extract: brotlipy-0.7.0-py37h4ab8f01_1000.tar.bz2
Extract: ca-certificates-2020.1.1-0.conda
Extract: cachecontrol-0.12.6-py_0.tar.bz2
Extract: certifi-2020.4.5.1-py37_0.conda
Extract: cffi-1.14.0-py37h7a1dbc1_0.conda
Extract: chardet-3.0.4-py37_1003.conda
Extract: commonmark-0.9.1-py_0.tar.bz2
Extract: conda-spec.txt
Extract: cryptography-2.8-py37h7a1dbc1_0.conda
Extract: cycler-0.10.0-py37_0.conda
Extract: decorator-4.4.2-py_0.conda
Extract: dictdiffer-0.8.0-py_0.tar.bz2
Extract: docutils-0.16-py37_0.conda
Extract: entrypoints-0.3-py37_0.conda
Extract: et_xmlfile-1.0.1-py37_0.conda
Extract: freetype-2.9.1-ha9979f8_1.conda
Extract: future-0.18.2-py37_0.conda
Extract: h11-0.9.0-py_0.tar.bz2
Extract: h2-3.2.0-py37_1.tar.bz2
Extract: hpack-3.0.0-py37h28b3542_0.conda
Extract: hstspreload-2020.5.5-py_0.tar.bz2
Extract: httpx-0.12.1-py_0.tar.bz2
Extract: hyperframe-5.2.0-py_0.tar.bz2
Extract: icc_rt-2019.0.0-h0cc432a_1.conda
Extract: icu-64.2-he025d50_1.tar.bz2
Extract: idna-2.9-py_1.conda
Extract: importlib_metadata-1.5.0-py37_0.conda
Extract: install.bat
Extract: intel-openmp-2020.0-166.conda
Extract: jdcal-1.4.1-py_0.tar.bz2
Extract: joblib-0.14.1-py_0.conda
Extract: jpeg-9c-hfa6e2cd_1001.tar.bz2
Extract: keyring-21.1.1-py37_2.conda
Extract: keyrings.alt-3.1.1-py37_0.conda
Extract: kiwisolver-1.2.0-py37h74a9793_0.conda
Extract: libclang-9.0.1-default_hf44288c_0.conda
Extract: libpng-1.6.37-h2a8f88b_0.conda
Extract: llvmlite-0.32.0-py37ha925a31_0.conda
Extract: lockfile-0.12.2-py37_0.conda
Extract: matplotlib-base-3.1.3-py37h64f37c6_0.conda
Extract: mkl-2020.0-166.conda
Extract: mkl-service-2.3.0-py37hb782905_0.conda
Extract: mkl_fft-1.0.15-py37h14836fe_0.conda
Extract: mkl_random-1.1.0-py37h675688f_0.conda
Extract: msgpack-python-1.0.0-py37h74a9793_1.conda
Extract: networkx-2.4-py_0.tar.bz2
Extract: numba-0.49.0-py37h47e9c7a_0.conda
Extract: numpy-1.16.6-py37h5510c5b_0.conda
Extract: numpy-base-1.16.6-py37hc3f5095_0.conda
Extract: openpyxl-3.0.3-py_0.conda
Extract: openssl-1.1.1g-he774522_0.conda
Extract: opentsne-0.3.11-py37he774522_1.conda
Extract: orange-canvas-core-0.1.12-py_1.tar.bz2
Extract: orange-widget-base-4.5.0-py_0.tar.bz2
Extract: orange3-3.25.0-py37h1834ac0_1.tar.bz2
Extract: pandas-1.0.3-py37h47e9c7a_0.conda
Extract: pip-20.0.2-py37_1.conda
Extract: pycparser-2.20-py_0.conda
Extract: pynndescent-0.3.3-py_0.tar.bz2
Extract: pyopenssl-19.1.0-py37_0.conda
Extract: pyparsing-2.4.7-py_0.conda
Extract: pyqt-5.12.3-py37h1834ac0_2.tar.bz2
Extract: pyqtgraph-0.10.0-py37h28b3542_3.conda
Extract: pysocks-1.7.1-py37_0.conda
Extract: python-3.7.6-h60c2a47_2.conda
Extract: python-dateutil-2.8.1-py_0.tar.bz2
Extract: python-louvain-0.13-py_0.tar.bz2
Extract: python_abi-3.7-1_cp37m.tar.bz2
Extract: pytz-2020.1-py_0.conda
Extract: pywin32-ctypes-0.2.0-py37_1000.conda
Extract: pyyaml-5.3.1-py37he774522_0.conda
Extract: qt-5.12.5-h7ef1ec2_0.tar.bz2
Extract: requests-2.23.0-py37_0.conda
Extract: rfc3986-1.3.2-py_0.tar.bz2
Extract: scikit-learn-0.22.1-py37h6288b17_0.conda
Extract: scipy-1.2.1-py37h29ff71c_0.conda
Extract: serverfiles-0.3.0-py37_0.conda
Extract: setuptools-46.1.3-py37_0.conda
Extract: sitecustomize.py
Extract: six-1.14.0-py37_0.conda
Extract: sniffio-1.1.0-py37hc8dfbb8_2.tar.bz2
Extract: sqlite-3.31.1-h2a8f88b_1.tar.bz2
Extract: tbb-2020.0-h74a9793_0.conda
Extract: tornado-6.0.4-py37he774522_1.conda
Extract: urllib3-1.25.8-py37_0.conda
Extract: vc-14.1-h0510ff6_4.conda
Extract: vs2015_runtime-14.16.27012-hf0eaf9b_1.conda
Extract: wheel-0.34.2-py37_0.conda
Extract: win_inet_pton-1.1.0-py37_0.conda
Extract: wincertstore-0.2-py37_0.conda
Extract: xlrd-1.2.0-py37_0.conda
Extract: xlsxwriter-1.2.8-py_0.conda
Extract: yaml-0.1.7-hc54c509_2.conda
Extract: zipp-3.1.0-py_0.conda
Extract: zlib-1.2.11-h62dcd97_4.tar.bz2
Output folder: C:\Users\terez\AppData\Local\Temp\nscD32B.tmp\Orange-installer-data\conda-pkgs
Installing packages (this might take a while)
Executing: cmd.exe /c install.bat "C:\Program Files\Orange" "C:\Users\terez\Desktop\Programy\Quasar\Scripts\conda.exe"
Creating a conda env in "C:\Program Files\Orange"
WARNING: A space was detected in your requested environment path
'C:\Program Files\Orange'
Spaces in paths can sometimes be problematic.

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\terez\Desktop\Programy\Quasar\lib\site-packages\conda\core\package_cache_data.py", line 301, in _make_single_record
        repodata_record = read_repodata_json(extracted_package_dir)
      File "C:\Users\terez\Desktop\Programy\Quasar\lib\site-packages\conda\gateways\disk\read.py", line 130, in read_repodata_json
        with open(join(extracted_package_directory, 'info', 'repodata_record.json')) as fi:
      File "C:\Users\terez\Desktop\Programy\Quasar\lib\site-packages\conda\common\compat.py", line 177, in open
        closefd=closefd)
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\terez\\Desktop\\Programy\\Quasar\\pkgs\\anyqt-0.0.10-py37_0\\info\\repodata_record.json'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "C:\Users\terez\Desktop\Programy\Quasar\lib\site-packages\conda\core\package_cache_data.py", line 318, in _make_single_record
        raw_json_record = read_index_json(extracted_package_dir)
      File "C:\Users\terez\Desktop\Programy\Quasar\lib\site-packages\conda\gateways\disk\read.py", line 116, in read_index_json
        with open(join(extracted_package_directory, 'info', 'index.json')) as fi:
      File "C:\Users\terez\Desktop\Programy\Quasar\lib\site-packages\conda\common\compat.py", line 177, in open
        closefd=closefd)
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\terez\\Desktop\\Programy\\Quasar\\pkgs\\anyqt-0.0.10-py37_0\\info\\index.json'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "C:\Users\terez\Desktop\Programy\Quasar\lib\site-packages\conda\exceptions.py", line 1074, in __call__
        return func(*args, **kwargs)
      File "C:\Users\terez\Desktop\Programy\Quasar\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Users\terez\Desktop\Programy\Quasar\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\Users\terez\Desktop\Programy\Quasar\lib\site-packages\conda\cli\main_create.py", line 37, in execute
        install(args, parser, 'create')
      File "C:\Users\terez\Desktop\Programy\Quasar\lib\site-packages\conda\cli\install.py", line 195, in install
        explicit(specs, prefix, verbose=not context.quiet, index_args=index_args)
      File "C:\Users\terez\Desktop\Programy\Quasar\lib\site-packages\conda\misc.py", line 84, in explicit
        pfe.execute()
      File "C:\Users\terez\Desktop\Programy\Quasar\lib\site-packages\conda\core\package_cache_data.py", line 627, in execute
        self.prepare()
      File "C:\Users\terez\Desktop\Programy\Quasar\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "C:\Users\terez\Desktop\Programy\Quasar\lib\site-packages\conda\core\package_cache_data.py", line 612, in prepare
        for prec in self.link_precs)
      File "C:\Users\terez\Desktop\Programy\Quasar\lib\site-packages\conda\core\package_cache_data.py", line 612, in <genexpr>
        for prec in self.link_precs)
      File "C:\Users\terez\Desktop\Programy\Quasar\lib\site-packages\conda\core\package_cache_data.py", line 503, in make_actions_for_record
        ), None)
      File "C:\Users\terez\Desktop\Programy\Quasar\lib\site-packages\conda\core\package_cache_data.py", line 500, in <genexpr>
        pcrec for pcrec in concat(PackageCacheData(pkgs_dir).query(pref_or_spec)
      File "C:\Users\terez\Desktop\Programy\Quasar\lib\site-packages\conda\core\package_cache_data.py", line 501, in <genexpr>
        for pkgs_dir in context.pkgs_dirs)
      File "C:\Users\terez\Desktop\Programy\Quasar\lib\site-packages\conda\core\package_cache_data.py", line 126, in query
        return (pcrec for pcrec in itervalues(self._package_cache_records)
      File "C:\Users\terez\Desktop\Programy\Quasar\lib\site-packages\conda\core\package_cache_data.py", line 244, in _package_cache_records
        self.load()
      File "C:\Users\terez\Desktop\Programy\Quasar\lib\site-packages\conda\core\package_cache_data.py", line 96, in load
        package_cache_record = self._make_single_record(base_name)
      File "C:\Users\terez\Desktop\Programy\Quasar\lib\site-packages\conda\core\package_cache_data.py", line 340, in _make_single_record
        extract_tarball(package_tarball_full_path, extracted_package_dir)
      File "C:\Users\terez\Desktop\Programy\Quasar\lib\site-packages\conda\gateways\disk\create.py", line 219, in extract_tarball
        conda_package_handling.api.extract(tarball_full_path, dest_dir=destination_directory)
      File "C:\Users\terez\Desktop\Programy\Quasar\lib\site-packages\conda_package_handling\api.py", line 58, in extract
        SUPPORTED_EXTENSIONS[ext].extract(fn, dest_dir, components=components)
      File "C:\Users\terez\Desktop\Programy\Quasar\lib\site-packages\conda_package_handling\conda_fmt.py", line 59, in extract
        _extract_component(fn, file_id, component, dest_dir)
      File "C:\Users\terez\Desktop\Programy\Quasar\lib\site-packages\conda_package_handling\conda_fmt.py", line 41, in _extract_component
        _tar_xf(component_filename, dest_dir)
      File "C:\Users\terez\Desktop\Programy\Quasar\lib\site-packages\conda_package_handling\tarball.py", line 88, in _tar_xf
        archive_utils.extract_file(tarball)
    NameError: name 'archive_utils' is not defined

`$ C:\Users\terez\Desktop\Programy\Quasar\Scripts\conda-script.py create --yes --quiet --prefix C:\Program Files\Orange --file conda-spec.txt`

  environment variables:
                 CIO_TEST=<not set>
                    CONDA=C:\Users\terez\Desktop\Programy\Quasar\Scripts\conda.exe
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\terez\Desktop\Programy\Quasar\Scripts\conda.exe
             CONDA_PREFIX=C:\Users\terez\Desktop\Programy\Quasar
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\terez\Desktop\Programy\Quasar\python.exe
               CONDA_ROOT=C:\Users\terez\Desktop\Programy\Quasar
              CONDA_SHLVL=1
                 HOMEPATH=\Users\terez
                     PATH=C:\Users\terez\Desktop\Programy\Quasar;C:\Users\terez\Desktop\Programy
                          \Quasar\Library\mingw-w64\bin;C:\Users\terez\Desktop\Programy\Quasar\L
                          ibrary\usr\bin;C:\Users\terez\Desktop\Programy\Quasar\Library\bin;C:\U
                          sers\terez\Desktop\Programy\Quasar\Scripts;C:\Users\terez\Desktop\Prog
                          ramy\Quasar\bin;C:\Users\terez\Desktop\Programy\Quasar\condabin;C:\Pro
                          gram Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32
                          ;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerS
                          hell\v1.0;c:\Program Files (x86)\Microsoft SQL
                          Server\100\Tools\Binn;c:\Program Files\Microsoft SQL
                          Server\100\Tools\Binn;c:\Program Files\Microsoft SQL Server\100\DTS\Bi
                          nn;C:\WINDOWS\System32\OpenSSH;C:\Users\terez\AppData\Local\Microsoft\
                          WindowsApps
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\Users\terez\Desktop\Programy\Quasar
            shell level : 1
       user config file : C:\Users\terez\.condarc
 populated config files : C:\Users\terez\Desktop\Programy\Quasar\.condarc
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.6.10.final.0
       virtual packages : 
       base environment : C:\Users\terez\Desktop\Programy\Quasar  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\terez\Desktop\Programy\Quasar\pkgs
                          C:\Users\terez\.conda\pkgs
                          C:\Users\terez\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\terez\Desktop\Programy\Quasar\envs
                          C:\Users\terez\.conda\envs
                          C:\Users\terez\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.23.0 CPython/3.6.10 Windows/10 Windows/10.0.18362
          administrator : True
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

Upload successful.
"conda" command exited with 1. Cannot continue.

**Comment by markotoplak** [comment]
Could you uninstall all Quasar, Orange and Miniconda packages from your computer and then try again?

If you could not find them, perhaps deleting this folder will be enough: `C:\Users\terez\Desktop\Programy\Quasar\`

**Comment by Terezia-cell** [comment]
Ok, I will try. Thank you.
