### ISSUE TITLE
How to refresh workflow  and output automatically and in cycle?

### ISSUE THREAD

**Issue by yuanxin-cq** [biolab/orange3#4820]
Is there any widgets that can refresh data source, workflow and output automatically and in cycle?

I have a real time data source,the data is time series, how can I make a schedule to refresh input data and  trige my workflow to update  output in cycle?

**Comment by ajdapretnar** [comment]
You could use Google Sheets widget from the Educational add-on, which iteratively reads Google Sheets and updates the results.

That said, Orange is not really intended for real-time data, but for interactive visualization and data exploration.

**Comment by yuanxin-cq** [comment]
Thank you  for your reply,really helpful!

Google Sheets also can open local csv in this way: file:///drive:/xxx/xxx.csv

I can update csv  data from data source  and reload it in cycle.

Thanks again!
