### ISSUE TITLE
Scatter plot legend positioning

### ISSUE THREAD

**Issue by Hrovatin** [biolab/orange3#4823]
Currently, Scatter Plot legend is always positioned in the bottom right corner. This is sometimes the least optimal position, as it overlaps datapoints that are present in the same corner. As the legend is semi-opaque the shade of the underlying datapoints is also changed, creating misleading datapoint colours. It would be nice if a corner was selected so that the legend overlapped the smallest number of data points.

**Comment by janezd** [comment]
And you're too lazy to drag it manually? :)

I guess it could be confusing if Orange would select it's place heuristically, it could look too random to users.

**Comment by Hrovatin** [comment]
Wops, I have not yet realised that this is possible.

**Comment by ajdapretnar** [comment]
Orange, a gift that keeps on giving. 🎁
