### ISSUE TITLE
orange installation aborted "no python.exe found"

### ISSUE THREAD

**Issue by a-jacoto** [biolab/orange3#4824]
Can't install Orange using Windows installer. Right after Miniconda setup, installation is aborted with error message "no python.exe found". Is it necessary to install python previously?

**Comment by ajdapretnar** [comment]
Yes, Python is the blood of Orange. Without it, you just get the bones. I assume you have cancelled Miniconda setup?

**Comment by a-jacoto** [comment]
Miniconda setup was successful, right after it finishes, I get this error message.
Should I install python before Orange installation?
Thanks in advance

**Comment by ales-erjavec** [comment]
Can you try locating and posting  %TEMP%\Orange3-3.25.0-Miniconda37-x86_64.exe-install-log.txt
where %TEMP% is your temporary directory usually %USERPROFILE%\AppData\Local\Temp

**Comment by a-jacoto** [comment]
Txt log follows below and screenshot of Orange installation
<img width="960" alt="orange-err" src="https://user-images.githubusercontent.com/66036538/83186248-9fba1380-a102-11ea-9401-1a41771b8862.png">

------------------------
Orange 3.25.0 Install Log
------------------------
Setting 64 bit registry view.
Anaconda in HKCU: 
Anaconda in HKLM: 
Anaconda Prefix: 
Anaconda Install Type: -1
DirectoryLeave
InstDir: C:\Users\adria\AppData\Local\Orange
InstDir state: -1
Anaconda in HKCU: 
Anaconda in HKLM: 
nsExec::ExecToLog: cmd.exe /C "C:\Users\adria\AppData\Local\Temp\nsyE2C7.tmp\Orange-installer-data\Miniconda3-4.7.12-Windows-x86_64.exe"  /InstallationType=CurrentUser 
Anaconda in HKCU: 
Anaconda in HKLM:

**Comment by ales-erjavec** [comment]
Can you please run regedit.exe (press <kbd>Win + R</kbd> and enter `regedit.exe`)and check that `HKEY_LOCAL_MACHINE/SOFTWARE/Python/ContinuumAnalytics/Anaconda37-64/InstallPath` or `HKEY_CURRENT_USER/SOFTWARE/Python/ContinuumAnalytics/Anaconda37-64/InstallPath` exist, and if so what are the contents.

Are there by any chance other entries under `SOFTWARE/Python/ContinuumAnalytics/`

**Comment by a-jacoto** [comment]
Under anaconda install path there are three registries:
(standard) C:\Users\...\Miniconda3
ExecutablePath C:\Users\...\Miniconda3\pyhton.exe
WindowedExecutablePath C:\Users\...\Miniconda3\pythonw.exe
No entries othen than anaconda under ContinuumAnalytics, but there is PythonCore under Python (please see attached image)
<img width="710" alt="orange-err2" src="https://user-images.githubusercontent.com/66036538/83255267-79d65280-a186-11ea-8bd7-6317c7490f7d.png">

**Comment by ales-erjavec** [comment]
Just to make sure but you are using a 64-bit Windows?

Do the `C:\Users\%USERNAME%\Miniconda3\python.exe` and `C:\Users\%USERNAME%\Miniconda3\Scripts\conda.exe` files exist?

**Comment by a-jacoto** [comment]
Yes, 64-bits Windows 10 Home Single Language.
No, python.exe and Scripts folder are not there.
Does it means Miniconda setup failed?
<img width="487" alt="orange-err3" src="https://user-images.githubusercontent.com/66036538/83265884-82378900-a198-11ea-9fac-3afabc2f7d94.png">

**Comment by ales-erjavec** [comment]
> Does it means Miniconda setup failed?

Yes

 Can you try running Miniconda uninstaller and then retry?

**Comment by a-jacoto** [comment]
I have installed Miniconda alone first, and then retried Orange installation and it worked. Thanks a lot!

**Comment by gabrielstorti** [comment]
I continue with this issue. Believe it is a general issue.
