### ISSUE TITLE
DataFusion Widget, Examples Do Not Work

### ISSUE THREAD

**Issue by Kwanikaze** [biolab/orange3#4825]
**Describe the bug**
I installed the DataFusion add-on.
When trying to run these two examples:
- Exploring the Latent Factors,it crashes when I open the example
- Matrix Tri-Factorization, I get a 'Unexpected Error" popup to send send an error report when I open the example, then Orange3 freezes when I press "Run" in the Fusion Graph widget. 

**Here**, provide a clear and concise description of what the bug is.

  File "/home/kwanale1/anaconda3/lib/python3.7/site-packages/orangecontrib/datafusion/widgets/owfusiongraph.py", line 123, in selectionChanged
    assert len(deselected) > 0
AssertionError
Aborted (core dumped)

  File "/home/kwanale1/anaconda3/lib/python3.7/site-packages/orangecontrib/datafusion/widgets/owfusiongraph.py", line 123, in selectionChanged
    assert len(deselected) > 0
AssertionError

**To Reproduce**
Welcome to Orange >  Examples > Exploring the Latent Factors
Welcome to Orange >  Examples > Matrix Tri-Factorization > Fusion Graph > Run

**Orange version:**
Orange - About - version number.
3.25.1

**Expected behavior**
The examples to run.

**Screenshots**

**Operating system:**
Windows, OSX or Linux? Which version?
Linux - Ubuntu 18.04, MATE 1.20.1

**Additional context**

**Comment by Kwanikaze** [comment]
Also does not work on Windows 10

**Comment by ajdapretnar** [comment]
This is the issue for https://github.com/biolab/orange3-datafusion/issues. Please note that Data Fusion is no longer our supported add-on, so we cannot really help you here much.
