### ISSUE TITLE
ordinal 242 could not be located

### ISSUE THREAD

**Issue by gbpowell** [biolab/orange3#4826]
Tried loading the latest version on two computers and got the same message:

"The ordinal 242 could not be located in the dynamic link library libiomp5md.ll"

I tried uninstalling and then reinstalling for "one user" but that did not seem to help.

I think Cura uses Python, could this be causing a conflict?

**Comment by ajdapretnar** [comment]
Please use the issue template to describe your issue and provide more details. I have no idea what 'Cura' is.

**Comment by gbpowell** [comment]
Cura is a 3d printing program that uses python.  I am not too python savvy but wondered if there was any possibility of conflict between different flavors.   When I try to start Orange I get the message I showed above.. which looks like maybe an path issue?

**Comment by ales-erjavec** [comment]
This is probably relevant: https://conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#numpy-mkl-library-load-failed

Can you open Orange Command Prompt and run

```batch
where libiomp5md.dll
```

**Comment by janezd** [comment]
Closed due to inactivity. Also, this (probably) can't be fixed in Orange.

But if you have can check what @ales-erjavec has written, please do and report back, so that we know what exactly is going on.
