### ISSUE TITLE
Which part is used to load left icons

### ISSUE THREAD

**Issue by xiaoyaosheng** [biolab/orange3#4837]
**Describe the bug**
Which part is used to load left icons。As it's show in the picture,Left area shows nothing,can I know which part codes is used to control this .Ths
**Here**, provide a clear and concise description of what the bug is.

**To Reproduce**

Steps to reproduce the behavior go **here**:

**Orange version:**
Orange - About - version number.

**Expected behavior**

**Screenshots**

**Operating system:**
Windows

**Additional context**
![image](https://user-images.githubusercontent.com/9269036/83476244-bfff1f00-a4c2-11ea-8b64-93acdc505d1f.png)

**Comment by ales-erjavec** [comment]
Mostly [this](https://github.com/biolab/orange-canvas-core/blob/master/orangecanvas/registry/discovery.py) and [this](https://github.com/biolab/orange-widget-base/blob/master/orangewidget/workflow/discovery.py)

How did you install Orange?

Can you run ```python -m Orange.canvas -l4``` from the command prompt and post output

**Comment by ajdapretnar** [comment]
Also, please stick to the issue template and fill out the missing details.

**Comment by xiaoyaosheng** [comment]
> Mostly [this](https://github.com/biolab/orange-canvas-core/blob/master/orangecanvas/registry/discovery.py) and [this](https://github.com/biolab/orange-widget-base/blob/master/orangewidget/workflow/discovery.py)
> 
> How did you install Orange?
> 
> Can you run `python -m Orange.canvas -l4` from the command prompt and post output

thx ,It's works ..

**Comment by xiaoyaosheng** [comment]
> Also, please stick to the issue template and fill out the missing details.

ok
