### ISSUE TITLE
Send one row at a time from one data table to another data table using the python script widget

### ISSUE THREAD

**Issue by luizgabriel0102** [biolab/orange3#4841]
Hi, people! 

Please look at the file below for a better understanding. Thank you!

[https://i.stack.imgur.com/s86tS.jpg](url)

I would like to know if there is a possibility to make a loop somehow work on orange, where this loop consists of the script(1) pulling one line at a time from the database and throwing it to the models, then the script(2) play the line n+1, that is, the next line for the test, so that the models perform the forecast; finally, the script(3) stores this and saves these forecast entries accumulated in a single data table. Then, the script(1) pulls line 2 from the database, so lines 1 and 2 are in the training base, and line 3 is put to test by script(2) ... this goes on until all lines 1...n are placed for training, while line (1...n)+1 is placed on the test. The loop ends when even the penultimate line has been trained and the last tested. 

It is possible?

Thank you friends!

**Comment by ales-erjavec** [comment]
No this is not possible in orange.

**Comment by luizgabriel0102** [comment]
> No this is not possible in orange.

Thanks for the reply, friend! Oh what a pity! But is there anything I can do using widgets that I can replace or assist in this task?

**Comment by janezd** [comment]
Python Script may be hacked to do this, but Orange is not intended to be used in this way. It would be simpler to write the whole thing in Python, using scikit-learn or, if you wish, Orange as pure Python library, without GUI (https://orange-data-mining-library.readthedocs.io/en/latest/#reference).

I'm closing the issue just to put it of the radar (we like to keep the list short and neat), but you can still post new comments to it.

**Comment by luizgabriel0102** [comment]
> Python Script may be hacked to do this, but Orange is not intended to be used in this way. It would be simpler to write the whole thing in Python, using scikit-learn or, if you wish, Orange as pure Python library, without GUI (https://orange-data-mining-library.readthedocs.io/en/latest/#reference).
> 
> I'm closing the issue just to put it of the radar (we like to keep the list short and neat), but you can still post new comments to it.

Okay, buddy! Thanks for the considerations. If this were done through the python script, would it require a lot from the programmer? Because I intend to pay for a freelancer to develop such a service, as I am not a programmer, just a programming enthusiast and a big fan of Orange. I have never known a tool so simple to use and so powerful. Thanks to the developers! I am concluding the undergraduate course in Economic Sciences at the Federal University of Campina Grande (Paraíba/Brazil) and I am already grateful for the space granted to us users for any questions about Orange. Thank you!
