### ISSUE TITLE
Installing new add-on trigers scikit-learn upgrade

### ISSUE THREAD

**Issue by yatendra3192** [biolab/orange3#4844]
##### Additional info (worksheets, data, screenshots, ...)

![image](https://user-images.githubusercontent.com/30041081/83965390-13ada600-a8d1-11ea-9aa1-af8ba4951e5a.png)

Error log

Exception:
IndexError: list index out of range
Module:
Orange.base:512
Version:
3.25.0
Environment:
Python 3.7.6 on Windows 10 10.0.18362 AMD64
Installed Packages:
AnyQt==0.0.10, Bottleneck==1.2.1, CacheControl==0.12.6, Orange3-ImageAnalytics==0.5.1, Orange3-Text==0.7.1, Orange3==3.25.0, Pillow==7.1.2, PyJWT==1.7.1, PyQt5-sip==4.19.18, PyQt5==5.12.3, PyQtChart==5.12, PyQtWebEngine==5.12.1, PySocks==1.7.1, PyYAML==5.3.1, XlsxWriter==1.2.8, asn1crypto==1.3.0, atomicwrites==1.4.0, attrs==19.3.0, baycomp==1.0.2, beautifulsoup4==4.9.1, biopython==1.76, blinker==1.4, boto3==1.9.66, boto==2.49.0, botocore==1.12.189, brotlipy==0.7.0, bz2file==0.98, cachetools==4.1.0, certifi==2020.4.5.1, cffi==1.14.0, chardet==3.0.4, colorama==0.4.3, commonmark==0.9.1, cryptography==2.8, cycler==0.10.0, decorator==4.4.2, defusedxml==0.6.0, dictdiffer==0.8.0, docutils==0.16, docx2txt==0.8, entrypoints==0.3, et-xmlfile==1.0.1, future==0.18.2, gensim==3.8.3, google-api-core==1.17.0, google-auth==1.16.0, google-cloud-core==1.3.0, google-cloud-storage==1.28.1, google-resumable-media==0.5.0, googleapis-common-protos==1.51.0, h11==0.9.0, h2==3.2.0, hpack==3.0.0, hstspreload==2020.5.5, httpx==0.12.1, hyperframe==5.2.0, idna==2.9, importlib-metadata==1.5.0, jdcal==1.4.1, jmespath==0.10.0, joblib==0.14.1, keyring==21.1.1, keyrings.alt==3.1.1, kiwisolver==1.2.0, llvmlite==0.32.0, lockfile==0.12.2, lxml==4.5.1, matplotlib==3.1.3, mkl-fft==1.0.15, mkl-random==1.1.1, mkl-service==2.3.0, more-itertools==8.3.0, msgpack==1.0.0, ndf==0.1.4, networkx==2.4, nltk==3.4.4, numba==0.49.0, numpy==1.18.5, oauthlib==3.0.1, odfpy==1.4.1, olefile==0.46, openTSNE==0.3.11, openpyxl==3.0.3, orange-canvas-core==0.1.12, orange-widget-base==4.5.0, packaging==20.4, pandas==1.0.3, pdfminer3k==1.3.1, pip==20.0.2, pluggy==0.13.1, ply==3.11, protobuf==3.12.3, py==1.8.1, pyOpenSSL==19.1.0, pyasn1-modules==0.2.7, pyasn1==0.4.8, pycparser==2.20, pynndescent==0.3.3, pyparsing==2.4.7, pyqtgraph==0.10.0, pytest==5.4.3, python-dateutil==2.8.1, python-louvain==0.13, pytz==2020.1, pywin32-ctypes==0.2.0, requests-oauthlib==1.2.0, requests==2.23.0, rfc3986==1.3.2, rsa==4.0, s3transfer==0.1.13, scikit-learn==0.23.1, scipy==1.4.1, serverfiles==0.3.0, setuptools-git==1.2, setuptools==46.1.3.post20200330, simhash==1.9.0, six==1.14.0, smart-open==2.0.0, sniffio==1.1.0, soupsieve==2.0.1, threadpoolctl==2.1.0, tornado==6.0.4, tweepy==3.8.0, ufal.udpipe-temp==1.2.0.5, ufal.udpipe==1.2.0.3, urllib3==1.25.8, validate-email==1.3, wcwidth==0.2.3, wheel==0.34.2, wikipedia==1.4.0, win-inet-pton==1.1.0, wincertstore==0.2, xlrd==1.2.0, zipp==3.1.0
Machine ID:
fbcf22d2-56c4-499c-801b-a093e787311a
Stack Trace:
Traceback (most recent call last):
  File "C:\Program Files\Orange\lib\site-packages\orangecanvas\scheme\widgetmanager.py", line 378, in __process_init_queue
    self.ensure_created(node)
  File "C:\Program Files\Orange\lib\site-packages\orangecanvas\scheme\widgetmanager.py", line 326, in ensure_created
    self.__add_widget_for_node(node)
  File "C:\Program Files\Orange\lib\site-packages\orangecanvas\scheme\widgetmanager.py", line 242, in __add_widget_for_node
    w = self.create_widget_for_node(node)
  File "C:\Program Files\Orange\lib\site-packages\orangewidget\workflow\widgetsscheme.py", line 296, in create_widget_for_node
    widget = self.create_widget_instance(node)
  File "C:\Program Files\Orange\lib\site-packages\orangewidget\workflow\widgetsscheme.py", line 396, in create_widget_instance
    klass = name_lookup(desc.qualified_name)
  File "C:\Program Files\Orange\lib\site-packages\orangecanvas\utils\__init__.py", line 80, in name_lookup
    module = __import__(module_name, fromlist=[class_name])
  File "C:\Program Files\Orange\lib\site-packages\Orange\widgets\model\owlogisticregression.py", line 8, in <module>
    from Orange.widgets.utils.owlearnerwidget import OWBaseLearner
  File "C:\Program Files\Orange\lib\site-packages\Orange\widgets\utils\owlearnerwidget.py", line 6, in <module>
    from Orange.modelling import Fitter, Learner, Model
  File "C:\Program Files\Orange\lib\site-packages\Orange\modelling\__init__.py", line 6, in <module>
    from .ada_boost import *
  File "C:\Program Files\Orange\lib\site-packages\Orange\modelling\ada_boost.py", line 2, in <module>
    from Orange.ensembles import (
  File "C:\Program Files\Orange\lib\site-packages\Orange\ensembles\__init__.py", line 5, in <module>
    from .stack import *
  File "C:\Program Files\Orange\lib\site-packages\Orange\ensembles\stack.py", line 92, in <module>
    class StackedClassificationLearner(StackedLearner, LearnerClassification):
  File "C:\Program Files\Orange\lib\site-packages\Orange\ensembles\stack.py", line 100, in StackedClassificationLearner
    def __init__(self, learners, aggregate=LogisticRegressionLearner(), k=5,
  File "C:\Program Files\Orange\lib\site-packages\Orange\classification\logistic_regression.py", line 46, in __init__
    self.params = vars()
  File "C:\Program Files\Orange\lib\site-packages\Orange\base.py", line 505, in params
    self._params = self._get_sklparams(value)
  File "C:\Program Files\Orange\lib\site-packages\Orange\base.py", line 512, in _get_sklparams
    assert spec.args[0] == "self"
IndexError: list index out of range

Local Variables:
OrderedDict([('self',
              LogisticRegressionLearner(penalty=<?>, dual=<?>, tol=<?>, C=<?>, fit_intercept=<?>, intercept_scaling=<?>, class_weight=<?>, random_state=<?>, solver=<?>, max_iter=<?>, multi_class=<?>, verbose=<?>, n_jobs=<?>)),
             ('skllearner',
              <class 'sklearn.linear_model._logistic.LogisticRegression'>),
             ('spec', Arguments(args=[], varargs='args', varkw='kwargs')),
             ('values',
              {'C': 1.0,
               '__class__': <class 'Orange.classification.logistic_regression.LogisticRegressionLearner'>,
               'class_weight': None,
               'dual': False,
               'fit_intercept': True,
               'intercept_scaling': 1,
               'max_iter': 100,
               'multi_class': 'ovr',
               'n_jobs': 1,
               'penalty': 'l2',
               'preprocessors': None,
               'random_state': None,
               'self': LogisticRegressionLearner(penalty=<?>, dual=<?>, tol=<?>, C=<?>, fit_intercept=<?>, intercept_scaling=<?>, class_weight=<?>, random_state=<?>, solver=<?>, max_iter=<?>, multi_class=<?>, verbose=<?>, n_jobs=<?>),
               'solver': 'liblinear',
               'tol': 0.0001,
               'verbose': 0})])

**Comment by PrimozGodec** [comment]
Hi. Thank you for submitting the issue. The problem is that you have a version of scikit-learn that is not compatible with with orange3-3.25. There are two options: 1. Upgrade orange3 to version 3.25.1 or 2. downgrade scikit-learn package to version 0.22.1.

If you let me know how did you install Orange I can help to resolve the issue.

**Comment by yatendra3192** [comment]
I have installed via 
https://orange.biolab.si/download/#windows
Standalone installer (default)
Orange3-3.25.0-Miniconda37-x86_64.exe (64 bit)

I have the latest version on my system 3.25

**Comment by yatendra3192** [comment]
Not able to upgrade 

C:\WINDOWS\system32>pip install --upgrade  Orange3==3.25.1
Collecting Orange3==3.25.1
  Using cached Orange3-3.25.1-cp38-none-win32.whl (2.5 MB)
Collecting pyqtgraph>=0.10.0
  Using cached pyqtgraph-0.10.0.tar.gz (1.5 MB)
Collecting python-louvain>=0.13
  Using cached python-louvain-0.14.tar.gz (19 kB)
Collecting orange-widget-base>=4.5.0
  Using cached orange_widget_base-4.5.0-py3-none-any.whl (215 kB)
Collecting AnyQt>=0.0.8
  Downloading AnyQt-0.0.10-py2.py3-none-any.whl (45 kB)
     |████████████████████████████████| 45 kB 91 kB/s
Requirement already satisfied, skipping upgrade: pandas in c:\python\python38\lib\site-packages (from Orange3==3.25.1) (1.0.3)
Collecting orange-canvas-core<0.2a,>=0.1.9
  Downloading orange_canvas_core-0.1.13-py3-none-any.whl (449 kB)
     |████████████████████████████████| 449 kB 27 kB/s
Requirement already satisfied, skipping upgrade: setuptools>=36.3 in c:\python\python38\lib\site-packages (from Orange3==3.25.1) (46.1.3)
Collecting openpyxl
  Downloading openpyxl-3.0.3.tar.gz (172 kB)
     |████████████████████████████████| 172 kB 726 kB/s
Collecting networkx
  Using cached networkx-2.4-py3-none-any.whl (1.6 MB)
Requirement already satisfied, skipping upgrade: joblib>=0.9.4 in c:\python\python38\lib\site-packages (from Orange3==3.25.1) (0.15.1)
Collecting keyring
  Using cached keyring-21.2.1-py3-none-any.whl (31 kB)
Collecting openTSNE>=0.3.11
  Using cached openTSNE-0.4.3.tar.gz (874 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Yatendra\\AppData\\Local\\Temp\\pip-install-6hfe5yus\\openTSNE\\setup.py'"'"'; __file__='"'"'C:\\Users\\Yatendra\\AppData\\Local\\Temp\\pip-install-6hfe5yus\\openTSNE\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Yatendra\AppData\Local\Temp\pip-pip-egg-info-fbvg45ow'
         cwd: C:\Users\Yatendra\AppData\Local\Temp\pip-install-6hfe5yus\openTSNE\
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Yatendra\AppData\Local\Temp\pip-install-6hfe5yus\openTSNE\setup.py", line 224, in <module>
        if has_c_library("fftw3"):
      File "C:\Users\Yatendra\AppData\Local\Temp\pip-install-6hfe5yus\openTSNE\setup.py", line 116, in has_c_library
        compiler.link_executable(compiler.compile([name]), name)
      File "c:\python\python38\lib\distutils\_msvccompiler.py", line 360, in compile
        self.initialize()
      File "c:\python\python38\lib\distutils\_msvccompiler.py", line 253, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "c:\python\python38\lib\site-packages\setuptools\msvc.py", line 314, in msvc14_get_vc_env
        return _msvc14_get_vc_env(plat_spec)
      File "c:\python\python38\lib\site-packages\setuptools\msvc.py", line 268, in _msvc14_get_vc_env
        raise distutils.errors.DistutilsPlatformError(
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by yatendra3192** [comment]
![image](https://user-images.githubusercontent.com/30041081/83969645-c6d8c800-a8ee-11ea-8d2a-6fcc6258551e.png)

**Comment by yatendra3192** [comment]
Update Issue is happening after I install Add-Ons image analytics.
![image](https://user-images.githubusercontent.com/30041081/83971785-ce05d300-a8fa-11ea-93ca-4f1934eaedae.png)

**Comment by yatendra3192** [comment]
Upgrade orange3 to version 3.25.1 fixed the issue

**Comment by PrimozGodec** [comment]
Great. Thank you for reporting this. I will reopen this issue since we need to solve the reason behind it. When someone installs an add-on scikit-learn get upgraded (Orange itself is packed with version 3.22.1). We need to find out the reason why it happens (it happens only on Windows where conda is used) and eventually make a new release of Orange.
