### ISSUE TITLE
regular bugs with widgets

### ISSUE THREAD

**Issue by bcautres** [biolab/orange3#4848]
Hello, I have regular bugs with the Model set of widgets : either a warning signal or a red circle with a cross. I have try to reinstall, does not help. Thanks for help !

**Comment by PrimozGodec** [comment]
I do not see the bottom part of the error message but I assume that you are facing the same issue than here: https://github.com/biolab/orange3/issues/4844

If you need the solution immediately please open the Orange command line (you can find it in the folder where Orange is installed). There upgrade Orange to 3.25.1 with `conda upgrade orange3`

We are planning the new release soon (probably tomorrow) which will solve the issue.

**Comment by bcautres** [comment]
So many thanks for your help and response ! I am going to wait the upgrade 3.24.1 and come back to you. All the best !

**Comment by bcautres** [comment]
3.25.1, I wanted to say
