### ISSUE TITLE
Unify add-on descriptions

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/orange3#4850]
**Describe the bug**

Add-on descriptions in add-on dialog are inconsistent.

**Expected behavior**

All supported addons should have the following form of the description:
- introductory paragraph with description, about three sentences, see Orange3 Text
- intro paragraph finishes with “See documentation.“, where “documentation” has a link to documentation pages (descriptions of widgets)
- Features, which lists core functionality of the add ons (see Textable for an idea)

The description in the dialog is taken from the PyPi. For some add-ons, the description is specified in README for others description is taken from README.pypi. Make that all addons have README.pypi with this format of description.

**Comment by kernc** [comment]
If README.pypi files are formatted in markdown, setup.py should declare [`long_description_content_type='text/markdown'`](https://packaging.python.org/guides/making-a-pypi-friendly-readme/#including-your-readme-in-your-package-s-metadata).

**Comment by janezd** [comment]
@BlazZupan, could you check whether these changes are OK, merge the corresponding pull request and close this issue?
