### ISSUE TITLE
White screen & not responding

### ISSUE THREAD

**Issue by JonasBerx** [biolab/orange3#4868]
**Bug reports that do not sufficiently describe a bug are not helpful and will most likely be ignored.**

- I opened orange after finishing an exam to revisit my model and my screen went white. There is little information online about this bug, it could be client sided too.
So regarding reproduction its literally just trying to open Orange.

-  Installed it using the normal .exe installer and tried it with pip. Both return the same error

- WIN10 
![image](https://user-images.githubusercontent.com/43341402/85629575-6da0c080-b672-11ea-9a8e-d9a7af086cec.png)

**Comment by ales-erjavec** [comment]
Can you open 'Orange Command Prompt' (for the exe install or just activate the env for custom install) and run
```batch
set QT_OPENGL=software
python -m Orange.canvas
```

Run the same with `QT_OPENGL=software`, `QT_OPENGL=desktop` and `QT_OPENGL=angle`

Is there any change between runs?

**Comment by ajdapretnar** [comment]
Closed due to inactivity.
