### ISSUE TITLE
Is there a reason for TimeVariable to be a float, not an int?

### ISSUE THREAD

**Issue by irgolic** [biolab/orange3#4882]
Specifically, if TimeVariable were made up of only integers, one could calculate the greatest common divisor of time deltas to determine the granularity OWTimeSlice's slider. Right now it uses the minimum timedelta, making the assumption that all timedeltas are divisible by the minimum one (often the case).

I suppose this is also a question of what granularity of time Orange should natively support. If TimeVariable were to use integers instead of floats, it would limit precision to seconds. I don't know whether there's been any discussion on this in the past. OWTimeSlice shows custom step size options ranging from 1 second to 100 years.

Note: TimeVariable (to my knowledge) holds the same information as ISO format time, which really only specifies time to a second's precision. Should one be working with millisecond-precision data, they're probably specifying time in terms of milliseconds elapsed since the start of the experiment, not since 1970-01-01?

**Comment by PrimozGodec** [comment]
@lanzagar based on the discussion in the morning we can close this issue, right?

**Comment by irgolic** [comment]
Right, everything is stored as a float in Orange, so I'll just cast the values to integers.
