### ISSUE TITLE
Changing plots: Shape widget

### ISSUE THREAD

**Issue by VesnaT** [biolab/orange3#4886]
- Graph elements (choosing shapes for individual categories of categorical variable, opacity of lines/other elements, line type, symbol orientation in scatter plot (e.g. arrows), ...)
Applicability: Multiple plots (e.g. Scatter Plot, Line Plot).
Importance: High, except for orientation - medium. Choice of shapes could be done as for colours with a widget. This would also enable allowing the use of more different shapes as for some plots with specific patterns/clusters using more shapes would not be a problem. Lines on saved Line Plots are poorly visible so changing of opacity and line width is needed. (KH) 
    - **JD:** I'm not sure about this, either.
    - **VT:** One can already choose shape for projections.

**Comment by irgolic** [comment]
This functionality could be abstracted into the Color widget (perhaps renaming it to something such as Variable Style widget).

**Comment by janezd** [comment]
Continues in #5377.
