### ISSUE TITLE
Changing plots: Distributions

### ISSUE THREAD

**Issue by VesnaT** [biolab/orange3#4888]
- Larger range of histogram bin sizes
Applicability: Distributions.
Importance: Medium. I had cases where I wanted more bins to see if there are two very close distributions/where they separate. (KH)
    - **JD:** Isn't it large enough? It goes from 2 to like 30-50?

- Sorting categories in histogram by size
Applicability: Bar plot, (maybe also Distributions).
Importance: Medium. (KH)
    - **JD:** This could be requested as a separate issue, it's related only to Distributions widget.

**Comment by janezd** [comment]
The current maximal maximal number of bins is 50 (depending on rounding; but the smallest maximum is 25, I believe). Should we really go higher? How high?

Bar plot is a separate issue.

The remaining issue is implemented in #4959.
