### ISSUE TITLE
Bar Plot

### ISSUE THREAD

**Issue by VesnaT** [biolab/orange3#4889]
**Annotations:**
- Statistical (stdev, significant differences on box/bar plot - e.g. between individual groups, ...)
Importance: Low (KH).

**Changing plots:**
- Sorting categories in histogram by size
Importance: Medium. (KH)

**Showing multiple data sets at once:**
- Splitting graph by category 
Applicability: Especially histogram, but may be used elsewhere as well.
Importance: Medium. Would be useful when showing multiple categories at once makes the graph too cluttered. Aligning multiple widgets is impractical (changing parameters for each one, dealing with multiple widows ,...). (KH)
    - **VT:** Can probably be achieved by using multiple widget of the same type along with filtering (Select rows).

- Splitting graph (e. g. bar plot) by multiple categories (hierarchically)
Applicability: Bar plot.
Importance: Medium. The order of categorical columns could probably be sorted with another widget. (KH)

- Multiple overlapping graph types (bar pot with line)
Importance: Depends on a case. Violin plots are popular in biology. (KH)

**Comment by irgolic** [comment]
This is basic functionality, still missing in Orange, so it's very welcome.

With columns on x-axis, allow either stacking bars or putting them side by side.
Select attributes in a list view.
Never show more than x (30?) bars. Perhaps try to be smart depending on the number of rows.

**Comment by ManuelLevi** [comment]
I was looking for this. It is essential I believe.

**Comment by janezd** [comment]
Closed via #4923.
