### ISSUE TITLE
Loading pre-defined colour schemes

### ISSUE THREAD

**Issue by VesnaT** [biolab/orange3#4890]
- Loading pre-defined colour schemes (e.g. for categorical variables with many groups)
Applicability: General.
Importance: High. Sometimes multiple datasets have the same categorical variables. Colour widget could try to read colours from a HEX column. Then a single table of unique category-colour mapping entries could be merged with data sets that have the categorical variable with same categories to assign the colours (I am not sure if this can be currently done by Merge Data - e.g. if the Data has more rows with the same category to which to append the Extra Data columns). (KH)
    - **JD:** Could this be an enhancement of the Color widget?

**Comment by janezd** [comment]
What about the color widget having an option to read and write a file with mapping of categories to colors? The file would have some simple form like *category, possibly with spaces*, a tabulator, then color as name or hex?

```
male     blue
female   red
above average    red
average  yellow
below average    #2222ff
```

When you read the file, it assigns colors to all categories of all variables that are found in the file. Other categories are not affected. You can thus also read multiple files; later files override the earlier.

**Comment by janezd** [comment]
Let us use json.
