### ISSUE TITLE
Expired certificate for https://docs.orange.biolab.si

### ISSUE THREAD

**Issue by gusunavarro** [biolab/orange3#4893]
Hello

Iam new in orange. I install under anaconda, but when I activate the orange
I have these error

ERROR:orangecanvas.help.provider:An error occurred while fetching help inventory 'PyQt5.QtCore.QUrl('https://docs.orange.biolab.si/3/visual-programming/')'

I have version 3.2.3 and install under anaconda.
I use Distro: Linux Mint 19.3 Tricia base: Ubuntu 18.04 bionic

**Comment by gusunavarro** [comment]
Today I install the new version 3.26 , and now is ok

**Comment by markotoplak** [comment]
While newer version uses new addresses, I am reopening because our servers still need to support older version for a while. 

The certificate for this page expired and we need to renew it.

**Comment by markotoplak** [comment]
Resolved.
