### ISSUE TITLE
Install orange3 on ubuntu linux fails

### ISSUE THREAD

**Issue by udimaha** [biolab/orange3#4897]
Hello, I try to install orange3 on my ubuntu version 18.04.1 (linux) machine, with python 3.7.8:
user@user-HP-Z230-Tower-Workstation:~$ python --version
Python 3.7.8
user@user-HP-Z230-Tower-Workstation:~$ pip install orange3
Collecting orange3
  Using cached https://files.pythonhosted.org/packages/92/ff/0a5af26c88ebba6cbc5b5e08c7eb463c567d6a6413f7fc9fb071ca3a4f6b/Orange3-3.26.0.tar.gz
    Complete output from command python setup.py egg_info:
    Orange requires Python >= 3.4
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kyCnO8/orange3/
user@user-HP-Z230-Tower-Workstation:~$ 

Can someone help me?

**Comment by ales-erjavec** [comment]
Can you run 
```
pip --version
```
to check if pip corresponds to the Python 3.7.8

Note: Please do not install orange3 into the system python environment. Create a new venv
```
python -m venv orange3venv
source orange3venv/bin/activate
````

**Comment by udimaha** [comment]
user@user-HP-Z230-Tower-Workstation:~$ pip --version
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)

**Comment by markotoplak** [comment]
@udimaha, installation into Ubuntu's system python environment will always fail for two reasons: (1) you would need to be root and (2) Ubuntu is using python 2.7.

As ales wrote, you will need to open a virtual python environment. See instructions here: https://github.com/biolab/orange3/blob/stable/README.md.
