### ISSUE TITLE
Inserting widget scrambles signals

### ISSUE THREAD

**Issue by borondics** [biolab/orange3#4909]
Consider this workflow, where the channels are set up in a non-default way.
![image](https://user-images.githubusercontent.com/6304794/87780969-0ec50600-c830-11ea-9040-0a009d48cd99.png)

Then, when inserting a widget on the link between Rank and Scatter Plot the signals are scrambled in a weird way.
![image](https://user-images.githubusercontent.com/6304794/87781029-30be8880-c830-11ea-8355-5590983e7c99.png)

It happens with other widgets as well, not only Transpose.
![image](https://user-images.githubusercontent.com/6304794/87781149-6cf1e900-c830-11ea-8e2c-a56f9086b8bd.png)

Orange: 3.270.dev installed from GitHub master
OS X 10.15.5

**Comment by irgolic** [comment]
Fixed by biolab/orange-canvas-core#117
