### ISSUE TITLE
Issue using comma as decimal point with float

### ISSUE THREAD

**Issue by htsnet** [biolab/orange3#4913]
I am trying to use a CSV file with numeric fields using comma as decimal point, but I am receiving an error: "ValueError: could not convert string to float: '6,5':
![decimalPointCommaIssue](https://user-images.githubusercontent.com/9755885/87974289-3ae6be00-caa0-11ea-9ee6-524b348e1fc2.png)

In the Import Options this numbe (line 2 , column 23 is OK)
![decimalPointCommaIssueDefinition](https://user-images.githubusercontent.com/9755885/87974311-45a15300-caa0-11ea-97cc-b07f27afea4a.png)

If I change the decimal to . the number turns red (this is correct, because the decimal point is comma):
![redWhenDotIsUsed](https://user-images.githubusercontent.com/9755885/87974350-5356d880-caa0-11ea-886b-db34ff03c815.png)

To reproduce this issue, use the file csvToReproduceIssue.csv (zipped), set Semicolon as delimiter and comma as decimal point. From colum 14 to the end, change to Numeric and ignore column 20.
[csvToReproduceIssue.zip](https://github.com/biolab/orange3/files/4949511/csvToReproduceIssue.zip)

You will receive a error message: 
![image](https://user-images.githubusercontent.com/9755885/87974692-d710c500-caa0-11ea-8fe8-58b38033960f.png)

I am using Windows 10 with Orange 3.26 installed with Orange3-3.26.0-Miniconda37-x86_64.exe.

Thanks.

**Comment by ajdapretnar** [comment]
I can also reproduce it with a smaller file:
[csvToReproduceIssue2.csv.zip](https://github.com/biolab/orange3/files/4958631/csvToReproduceIssue2.csv.zip)

I manually created this file:
```
A;B
1;6,4
2;1,3
3;1,8
4;2,3
5;7,6
```

and it gets read correctly.

I can't figure out what is different with the first one.

**Comment by ales-erjavec** [comment]
Ultimately this is https://github.com/pandas-dev/pandas/issues/35365

**Comment by htsnet** [comment]
I found the same "CSV File import" in other group: Prototypes (the green one).
![image](https://user-images.githubusercontent.com/9755885/88180259-7b128180-cc03-11ea-9e90-9c5f86ec368e.png)


Using this other widget, the import works well!

![image](https://user-images.githubusercontent.com/9755885/88180197-659d5780-cc03-11ea-8250-252ce0640161.png)
