### ISSUE TITLE
Edit Domain - reset of merged values

### ISSUE THREAD

**Issue by che9900** [biolab/orange3#4914]
Orange 3.26 / using new EDITDOMAIN

What was the task: group average_price into 3 segments: LOW, MEDIUM, HIGH. 

Ideally this segmentation would be based on the pre-defined values (I tried using DISCRETIZE, but that only offers pre-defined equal frequency / equal width / and some additional options)

I selected multiple values and using [M] key merged the values and added the label LOW. When merging a second group of values (for MED) the first merge (LOW) is removed. The only way at the moment to have multiple merged groups is a manual process for each numerical value. With larger data sets this is obviously not workable solution.

Request: adding a new merge does not remove all other merges/ labelings

**Comment by ajdapretnar** [comment]
You are right, it does remove them. However, I think these are two separate issues.

1.) Provide custom values in Discretize.

2.) Enable multiple merging in Edit Domain (the problem here is to distinguish between different merges).
