### ISSUE TITLE
'Drag and drop' on canvas

### ISSUE THREAD

**Issue by irgolic** [biolab/orange3#4918]
If a loadable file is dropped onto canvas, add a widget (File or Load Distances or Load Model) at that position and load the file.

It would be sensible to implement #3997 before this.

Related to #4917 in terms of reusable code.

**Comment by janezd** [comment]
Approved. 👍 

Widget should declare, whilch file extensions they handle (if any).

**Comment by borondics** [comment]
This would be another great addition!

@markotoplak are there any extra things we would need to do to enable this for Orange Spectroscopy readers like `Multifile` (and any other we might have later)?
