### ISSUE TITLE
Unable to Open Add-Ons from Menu

### ISSUE THREAD

**Issue by wscwt01** [biolab/orange3#4947]
I have Orange 3 version 3.26 installed as stand-alone i.e. not from within Anaconda.
When I select add-ons I get an error message.
Screenshot
![Capture](https://user-images.githubusercontent.com/69965611/90758661-46afe500-e2d7-11ea-8f9c-2af0f3f9f4b5.JPG)
 attached.

**Comment by ales-erjavec** [comment]
Duplicate of gh-4944
