### ISSUE TITLE
Rank: use PCA by default on unsupervised data

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#4948]
**Is your feature request related to a problem? Please describe.**

It is unclear how to do unsupervised ranking.

**Describe the solution you'd like**

Use PCA ranking as a default for unsupervised data sets.

**Additional information**

While at it, make attribute selection stick to the top of the widget, not the bottom.

**Comment by janezd** [comment]
Hm, what is the use case for PCA ranking, actually? What does ranking mean, in the context of unsupervised data?

**Comment by janezd** [comment]
Remove the tip about PCA from Rank Widget's tooltip and documentation.
