### ISSUE TITLE
Invalid ELF file(s) in wheel: `_distance.cpython-38-x86_64-linux-gnu.so`

### ISSUE THREAD

**Issue by DavHau** [biolab/orange3#4956]
Hello, I'm the maintainer of https://github.com/DavHau/mach-nix , a package management tool for python.

Mach-nix relies on patching binaries contained in wheels via patchelf as a measure to ensure reproducibility.

But the wheel package of orange3 seems to contain one or more invalid binaries. patchelf fails with:

```
searching for dependencies of /nix/store/46bqlqvhxg2v7dkj1dhbggd00mjjckjn-python3.8-orange3-3.26.0/lib/python3.8/site-packages/Orange/distance/_distance.cpython-38-x86_64-linux-gnu.so
readelf: Error: Reading 1080 bytes extends past end of file for section headers
readelf: Error: the dynamic segment offset + size exceeds the size of the file
patchelf: section header table out of bounds
```

The problem seem to be with `Orange/distance/_distance.cpython-38-x86_64-linux-gnu.so`

I'm not sure to what extend this file is broken and if it works at all. But it's header is definitely corrupt.

Any idea what could be the reason?
I have not seen this problem yet with wheel distributions of other packages.

**Comment by ales-erjavec** [comment]
I cannot make patchelf (0.9) or readelf (2.30) to report an error on Ubuntu 18.04.

Can you describe the exact sequence of commands that lead to the error?

**Comment by janezd** [comment]
Closed due to inactivity.
