### ISSUE TITLE
how to install widgest/addon by hand,where is the dir for it?

### ISSUE THREAD

**Issue by Franklyn1987** [biolab/orange3#4962]
**Bug reports that do not sufficiently describe a bug are not helpful and will most likely be ignored.**

- [ ] **A clear and concise description.** "*I'm getting an error when I open a tree viewer*" is far from enough (what kind of error? what kind of data you give it?). "*I'm getting an error*" is even worse.

- [ ] **How to reproduce the problem.** Upload a zip with a workflow and data, or describe the steps (open this widget, click there, then add this ...)

- [ ] **Which version of Orange are you using? How did you install it?**

- [ ] **What is your operating system?**

**Comment by ajdapretnar** [comment]
Bug reports that do not sufficiently describe a bug are not helpful and will most likely be ignored.

**Comment by markotoplak** [comment]
@ajdapretnar, you might have missed the title; in this case it may be clear enough. @Franklyn1987, thank you for pointing it out missing documentation.

There is no magic folder, though. Python's entry point mechanism is used to register widgets from a directory.

You can try various approaches depending on what are you trying to do:
- To install existing add-ons without the UI, you can do `pip install add-on-name-or-file`, just be careful that you use the `pip` command that is linked to the same python installation as Orange.
- If you want to quickly develop a new widget and try it out, just put that widget into a directory already containing existing widgets.
- To develop add-ons and see how entry points are registered, study https://github.com/biolab/orange3-example-addon (note `Orange.widgets` entry point definition in `setup.py`).
