### ISSUE TITLE
Unbalanced target variable

### ISSUE THREAD

**Issue by robertcv** [biolab/orange3#4986]
If I understand correctly there is no simple way to handle unbalanced target variables in Orange.
One possible solution would be to oversample but then we could end up having the same sample in the training and testing data. Another solution would be to subsample but I cannot use it as I, unfortunately, have a small dataset.
The solution I would propose is to expose `class_weight='balanced'` as an option in the GUI. This parameter can be used on some of the sklearn's models ([LogisticRegression](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html), [RandomForestClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html), [SVM](https://scikit-learn.org/stable/modules/generated/sklearn.svm.LinearSVC.html)) and solves the unbalance in the target variable.

**Comment by janezd** [comment]
We add a checkbox for learners for which this is supported in scikit-learn.

We add warning that this can decrease performance.

**Comment by janezd** [comment]
Fixed via #5026.

**Comment by zy-tech** [comment]
I came to this issuse just now. 

for the unbalanced target variable, could we use random forest with some sampling trick: we use all the minorities in each tree, but we random sample majorities in each tree. So in each tree, we got the balanced data with majority subsample, but for the forest, it is a minority oversample.

**Comment by janezd** [comment]
It is an idea. You can try it...

As for adding it to Orange, we're not to keen about adding experimental stuff. Experience taught us it often ends as dead code.

**Comment by zy-tech** [comment]
I used to use this tech in KNIME, they provide this method in their "Ensemble Learner", I have tried and it works very well. You can have a try it in KNIME
