### ISSUE TITLE
Show model response in scatter plot

### ISSUE THREAD

**Issue by robertcv** [biolab/orange3#4988]
**What's your use case?**
Show pre-trained model response in scatter plot (similar to color regions and [sklearn docs](https://scikit-learn.org/stable/auto_examples/classification/plot_classifier_comparison.html)). It would be a nice way to show how the model works and how regions of data would be classified. Perhaps this would be more suitable for Educational-add-on. Something like this was already implemented in the old OWMap.

**Comment by PrimozGodec** [comment]
Something similar is also implemented in Polynomial Classification widget. There you put the **learner** at the input and widget trains the model and shows model probabilities as colours. 

If I understand you correctly you would prefer to have the option to visualise already trained model with a similar widget? Polynomial classification is implemented as it is since it also shows the effect of polynomial features on classification regions. 

If we decide to implement this we can maybe think about extending this widget or implementing new widget to avoid confusion.

**Comment by markotoplak** [comment]
This is already possible. Just connect the Scatterplot to Predictions. Or am I missing a use case?

**Comment by markotoplak** [comment]
Oh, or you'd just like separate colors for dots and densities?

**Comment by PrimozGodec** [comment]
@markotoplak yes scatterplot partially supports this, you can also enable colours, but colours are computed based on points. I think what @robertcv wants is that you see points and that colour grid is computed base on the model, not just points. This way you can see how model probability toward a class would change when x, y value changes. This is implemented in Polynomial Classification widget but you cannot provide the model  to the widget (just learner).

**Comment by robertcv** [comment]
My original thought was to use pre-trained models to visalize the response. While writinkg this response I discoverd that it is actualy not possible to do it the way I wanted it to work. I was thinking about clasifying a gird of points and then interpolating the assigned classes/colors (this is similar to how color regions are calculated but thy use distance between points). This is actualy only possible for two features and cannot (or is wary hard to) be extended to more features. 
As this could probebly not be used generaly I am ok with you closing this issue.

**Comment by janezd** [comment]
Yes, if you would like to do this, you would have to sample values of other features, and this sample would need to have the correct structure, that is, observe dependencies between variables. This is difficult to model, so the only generally appropriate way to do this is to sample from the data --- which is exactly what you get by connecting Predictions to Scatter plot.

**Comment by markotoplak** [comment]
Perhaps there is something we could do, but in the Predictions widget. We could introduce new rows that are old rows + some noise. That would handle sensible sampling (as @janezd just mentioned) plus show model instability.
