### ISSUE TITLE
Feature Statistics: compute in parallel and enable cancelling the task

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#5009]
- [ ] **What's wrong?**

Feature Statistics stalls for an indeterminate amount of time when given a certain data set.

- [ ] **How can we reproduce the problem?** 

Use hotel-bookings data from https://www.kaggle.com/jessemostipak/hotel-booking-demand  or https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-02-11/readme.md  and feed it to Feature Statistics.

The data has 119390 instances and 29 features with 1 meta feature.

- [ ] **Which version of Orange are you using? How did you install Orange?**

3.27.dev

- [ ] **What is your operating system?**
OSX

**Comment by ales-erjavec** [comment]
Probably fixed by gh-5152. If not, please reopen.
