### ISSUE TITLE
Explain Model (Prototypes) truncates longer labels

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3#5020]
Explain Model truncates most of the attribute value names even when feature names are relatively short. Current setting would allow for feature names to be displayed in one row and feature value in the next row. This applies only to categorical features, for continuos features feature values are not displayed.

<img width="795" alt="image" src="https://user-images.githubusercontent.com/726604/95510871-e542f300-09b6-11eb-93bf-c4862d366ae8.png">

**Comment by PrimozGodec** [comment]
Closed via https://github.com/biolab/orange3-explain/issues/5
