### ISSUE TITLE
ScatterplotBase: set fixed legend

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#5023]
- [ ] **What's your use case?**

When using Time Slice, one wishes to see a fixed legend when feeding the data to a plot. The legend now takes only min and max of subset. Global min, max should be used.

- [ ] **What's your proposed solution?**

Feed all data to the plot and use min, max. Not like plotting a subset, but a different approach. Need to figure out.

- [ ] **Are there any alternative solutions?**
Checkbox where the user fixed the scale? 🤔

**Comment by janezd** [comment]
Notes from discussion.

The solution seems to have attributes of attributes that store the range.

- Who sets them? They are set at loading? How can the user change them? In widgets like Color, Edit Domain? Do we do it with a specific widget, like Feature Statistics? How would the users know that that's what they should do? Do we have a specific widget?

- Related to above: there are just a few cases where the whole issue matters. One is time slice, another is picking a bin in distribution and clicking left and right. Maybe only these widget should set the range?

- But how are these attributes copied and when are they removed? There are many places where we create a new attribute. Attributes of attributes are copied (e.g. colors). Min/max attributes may sometimes be copied (rename), sometimes they must be discarded ("preprocessors"). 

Next, how does this look in widgets that can use the frozen ranges?

- There would be either a checkbox in the widget or in plot settings for using the min and max from the attribute; if unchecked, it uses input data range, like now.

I would not rush this. A possible path forward is that somebody starts experimenting.

**Comment by janezd** [comment]
Notes from a new discussion:

- File widget could set attributes' attributes with min and max.

**Comment by kaimikael** [comment]
Actually, it would be nice to set the ranges of axes manually—for example because you want to create multiple plots to a common scale, this should also be an option.

**Comment by irgolic** [comment]
> Actually, it would be nice to set the ranges of axes manually—for example because you want to create multiple plots to a common scale, this should also be an option.

Couple this with a settable export DPI, and you're able to set a fixed height/width for raster exports.

**Comment by janezd** [comment]
Continues in #5377.
