### ISSUE TITLE
improved Segmentation function requesting

### ISSUE THREAD

**Issue by Jzh1004** [biolab/orange3#5025]
- [ ] **What's your use case?**

Hi, I am a graduate student from China. The text mining of orange 3 is really powerful and quick, but it doesn't support  segmenting Chinese characters, which really upset me.

- [ ] **What's your proposed solution?**

1. hope to add Chinese word segmentation function to orange.
2. recommending using jieba, a third-party python library which do well in Chinese corpus.

- [ ] **Are there any alternative solutions?**
3. building a widget for receiving Chinese tokenization  results or so on to make users to continue the process.

Really thank you!

**Comment by ajdapretnar** [comment]
Duplicate of https://github.com/biolab/orange3-text/issues/536.

**Comment by Jzh1004** [comment]
How to integrate orange and jieba？
