### ISSUE TITLE
Distribution widget may have more y axis options

### ISSUE THREAD

**Issue by zy-tech** [biolab/orange3#5029]
- [ ] **What's your use case?**
for example, I use kc_house dataset from kaggle. I'd like to compare the mean of price with different 'waterfront'. But  I can't do it using the distribution widget now. 

So What I would like to see is that the x axis is 'waterfront' and the y axis is the mean(or sum or others) of the price.  

like this:
![image](https://user-images.githubusercontent.com/54013300/95667897-cacb6e00-0b9e-11eb-9178-3ab260641f3b.png)

**Comment by janezd** [comment]
Distribution widget shows distributions of variables. In case of categorical variables, it shows columns that correspond to individual values, and their heights correspond to the number of data instances with such value. What you would like to have does not fit into this.

For a plot like yours, you need the Bar plot widget from Orange 3.27. (We built a release this Friday, but apparently it's not available for download yet.) You will need to connect File -> Pivot -> Bar Plot. In pivot, choose aggregation by mean (or whatever you wish). Then double click the connection between Pivot and Bar Plot and drag a line from Grouped data to Data. In Bar Plot choose Group By 'waterfront' and Color By 'waterfront'.
