### ISSUE TITLE
Pivot Table is slow when the categories are large

### ISSUE THREAD

**Issue by zy-tech** [biolab/orange3#5030]
- [ ] **What's your use case?**
I see that orange can [do `pd.groupby` like thing by Pivot Table](https://orange.biolab.si/blog/2019/2019-08-27-pivot-table/), but when the categories are large, the widget is dead, or almost dead. I can do the same groupby using pandas in seconds. 

- [ ] **What's your proposed solution?**

I don't known why it is so slow in Orange. Maybe because Orange has to show the resuls? If so, could we select to not to see the results, or just see part of the result? Many times, we don't need to see all the results, because we just want to `groupby` and do other tasks in other widgets.

**Comment by janezd** [comment]
> Many times, we don't need to see all the results, because we just want to groupby and do other tasks in other widgets.

And how many times would that be, considering that I only suggested this trick to you yesterday? :)))))

Any data that is output needs to be computed. I very much doubt that filling the table's cells with data takes more time than computing that data. It would help us if you described your data (or even uploaded/linked to it) and tell us how many groups you create, how, what aggregation functions you compute. Without that, we have nothing to work on.

Also, in general: if you create so many groups that their computation takes time, all or most of them would contain very small samples so any aggregates would be unreliable. So Pivot with a large number of categories is not really useful.

**Comment by zy-tech** [comment]
here is the data:  https://drive.google.com/file/d/1mXknFu6VmVojELGLk9z9jhXaotn-DA1U/view?usp=sharing
(I will delete this data once the issue is closed, sorry)

my python code:
```py
# ex is this data
group_ex = ex.groupby('id').agg({'sales': ['mean', 'min', 'max', 'sum']})
group_ex = group_ex.reset_index()
group_ex.columns = ['id', 'mean', 'min', 'max', 'sum']
```
I tried the same thing with pivot table, but the failed.

**Comment by ajdapretnar** [comment]
While this issue is closed, we could think about separating Group By and Pivot Table. The above use case is one that we could still support. Just aggregating by one (or more) variables (discrete or continuous) and outputting an aggregated table, without the need for display and computation of a pivot table.

What I mean is that we perform two operations every thing in one widget, which can get slow. How about we make it two widgets and avoid overloading this one?
