### ISSUE TITLE
network explorer fails with book-excerpts dataset

### ISSUE THREAD

**Issue by matinho13** [biolab/orange3#5047]
- [ ] **What's wrong?**

In your corpus to network example with the book-excerpts.tab dataset, I cannot get the network link between the corpus to network and the network explorer widgets. I get the following error message:
''' node data is given, graph data is missing'''

- [ ] **How can we reproduce the problem?** 

- [ ] **Which version of Orange are you using? How did you install Orange?**

3.27, installed via .dmg on mac. all otehr programs I have run fine!

- [ ] **What is your operating system?**

**Comment by ajdapretnar** [comment]
This should be reported in https://github.com/biolab/orange3-text/issues.

I cannot reproduce. Please make sure you are running Text v 1.2.0 and Network 1.5.1.

**Comment by kotenok-xyz** [comment]
I have the same problem. How do you solve it?

**Comment by ajdapretnar** [comment]
@kotenok-xyz Can you confirm you are running Orange 3.27.1, Text 1.3.1 and Network 1.5.1?

**Comment by kotenok-xyz** [comment]
Thank you, I am updating Text Add-on.

**Comment by kotenok-xyz** [comment]
Yes, I am running Orange 3.27.1, Text 1.3.1 and Network 1.5.1, but I can't still get the network due to "graph data is missing"

**Comment by ajdapretnar** [comment]
Please attach a screenshot of your workflow and other relevant information.

**Comment by kotenok-xyz** [comment]
![image](https://user-images.githubusercontent.com/37558190/106910687-c274e100-6701-11eb-8216-632ade0759c7.png)
![image](https://user-images.githubusercontent.com/37558190/106910745-d0c2fd00-6701-11eb-93f3-eafe783bb91b.png)

Please see the red circles. I am trying different options in the workflow, but none of them works.

**Comment by ajdapretnar** [comment]
Well, you have not connected the Network signal to Network Explorer. Just like the warning says.
In Network Analysis, you also have produced no output, so Network Explorer cannot show anything. Dashed line means no output.

**Comment by kotenok-xyz** [comment]
How to connect Network signal to Network explorer?

**Comment by ajdapretnar** [comment]
https://youtu.be/2xS6QjnG714?t=120

**Comment by kotenok-xyz** [comment]
Could you highlight which branch of my workflow is correct?
This is when I double click the link between Corpus to network & Network explorer 
![image](https://user-images.githubusercontent.com/37558190/106915625-8728e100-6706-11eb-8733-be5e737c3064.png)

**Comment by kotenok-xyz** [comment]
Then I did this. Is it correct? 
![image](https://user-images.githubusercontent.com/37558190/106916087-146c3580-6707-11eb-9012-0afb8d8d1201.png)

**Comment by kotenok-xyz** [comment]
Now it works, Thank you very much!
