### ISSUE TITLE
Logistic regression coefficient estimates and predictions are different on Windows and Mac

### ISSUE THREAD

**Issue by robertasgabrys** [biolab/orange3#5052]
- [ ] **What's wrong?**

**When I run logistic regression on windows and mac, orange gives different coefficient estimates and also different predictions. Differences for my data are not huge. Is this a bug in the code or there is a reason why this is the case.** 

- [ ] **How can we reproduce the problem?** 

![Logistic regression in Orange on Windows and Mac](https://user-images.githubusercontent.com/31359004/97502241-fa64cf00-192f-11eb-8506-b9d4b6f46410.JPG)
[TrojanHorseData.xlsx](https://github.com/biolab/orange3/files/5455079/TrojanHorseData.xlsx)

- [ ] **Which version of Orange are you using? How did you install Orange?**

Tried both 3.27.1 and 3.27.0. Installed them from the Orange website. 

- [ ] **What is your operating system?**

I tried on both Windows and Mac. I gave a test to my students and those who used mac got slightly different results. After investigating the results I realized that the coefficient estimates and predicted logistic regression probabilities are slightly different depending on Windows or Mac. 

Thank you for great software. My students and I love it. 

Best
Robertas Gabrys 
University of Southern California
Los Angeles

**Comment by ajdapretnar** [comment]
@robertasgabrys Does this happen also on the entire data set (without sampling)?

**Comment by robertasgabrys** [comment]
@ajdapretnar yes, it does.

**Comment by ajdapretnar** [comment]
@robertasgabrys It could be that randomization is bound to system settings. I am unsure of how numpy handles this.

@janezd Any ideas?

**Comment by robertasgabrys** [comment]
@ajdapretnar @janezd : first of all thank you for you help! The following two examples might help identify the issue:

1. I built a logistic regression using **titanic.tab** data that is imbedded in orange. Logistic regression coefficient estimates are the same on both windows and mac for both sampled and not sampled data. 

2. I built a logistic regression using **heart_disease.tab** data that is imbedded in orange. Logistic regression coefficient estimates are NOT the same on both windows and mac.

3. **heart_desease.tab** data has both numeric and categorical data while **titanic.tab** ONLY categorical data.

**Comment by markotoplak** [comment]
I can confirm this behaviour with 3.27.1 on Mac and Windows running `scikit-learn=0.23.2` and `numpy=1.19.2` on Mac and Windows. Then I also tried to directly run scikit-learn with:

```
import Orange
from sklearn.linear_model import LogisticRegression

data = Orange.data.Table("iris")

X, y = data.X, data.Y
X = X.round(decimals=0)  # to discount remove potential reading artifacts

lr = LogisticRegression(random_state=0, fit_intercept=True)
lr.fit(X, y)
print(lr.coef_)
```

On Mac I get: 

```
[[-0.55154026  0.89775639 -2.21394015 -1.34056263]
 [ 0.63008983 -0.47549926 -0.21305348 -0.33778282]
 [-0.07854957 -0.42225713  2.42699362  1.67834545]]
```

**Comment by markotoplak** [comment]
The same behaviour also happens in scikit-learn (logistic regression in Orange uses it), see scikit-learn/scikit-learn#18715. They say that these kind of differences are expected and they suspect that they come from lbfgs optimiation from the scipy library.

I did not investigate further.
