### ISSUE TITLE
Check and correct the Lift Curve widget

### ISSUE THREAD

**Issue by minhpth** [biolab/orange3#5056]
Hi Orange team,

I'm using Orange on a predictive analysis project and I have the following issue:

- [x] **What's your use case?**

- I build and evaluate a simple Decision Tree with the Lift Curve widget. You may reproduce it with this set of data: [telco_churn_C50.zip](https://github.com/biolab/orange3/files/5474655/telco_churn_C50.zip)
![image](https://user-images.githubusercontent.com/16757200/97863321-13da9200-1d07-11eb-948c-4a62d654141a.png)

- In my opinion, the Lift Curve does not seem right... I understand there are different definitions of a Lift Curve, however, it should have an axis that actually shows the lift value. If I am not mistaken, the plot here is actually the ROC curve.
![image](https://user-images.githubusercontent.com/16757200/97863051-acbcdd80-1d06-11eb-9f48-1e57b1cb1776.png)

- You can also see in icon of the Lift Curve widget, the shape of it is different than the plot I have here.
![image](https://user-images.githubusercontent.com/16757200/97863847-f528cb00-1d07-11eb-89f5-c93af520f700.png)

- [x] **What's your proposed solution?**

- Since Lift Curve is a very popular method to evaluate a machine learning model in marketing, I would suggest to check again about the Lift Curve definition. If my opinion is correct, maybe we should re-implement the widget.

- I found that the library scikitplot has implemented a very nice example Lift Curve plot. You may find the documents here: https://scikit-plot.readthedocs.io/en/stable/metrics.html
![image](https://user-images.githubusercontent.com/16757200/97864089-5a7cbc00-1d08-11eb-8e93-99284531df8b.png)

- [x] **Are there any alternative solutions?**

- N/a

Thanks a lot and best regards,
Minh PHAN

**Comment by ales-erjavec** [comment]
What the widget actually plots is a cumulative gains chart.

**Comment by minhpth** [comment]
> What the widget actually plots is a cumulative gains chart.

Thank you for your reply. I got it. So, is it a good idea to add an option to flip the cumulative gains chart to the Lift curve ?

**Comment by janezd** [comment]
Thanks, @minhpth. I think it would be a good idea that we flip this to Lift curve, but we could also keep the current functionality as an option -- we'd add a check box "Show cumulative gains chart" -- if for nothing else than because it's easier to explain and then leads to lift chart.
