### ISSUE TITLE
Can Orange3 generate report in HTML file?

### ISSUE THREAD

**Issue by vijayakumarmariyappan** [biolab/orange3#5060]
Hi Team, 

     Can Orange3 generate report in HTML/anyfile format that can be opened in browser against dataset? 
Say for an example, I have titanic dataset, I uploaded that dataset to my server through angular app. In my server I have installed Orange3 and its API can generate html file/any file format report . Is there any API in Orange3.!!

Thank you for your help and time

**Comment by ajdapretnar** [comment]
There is `send_report` option (https://github.com/biolab/orange3/blob/85d35aa4daa3e6cc5004a0c0ba2ccfb9a8ab6917/Orange/widgets/data/owtransform.py#L119). And there's the OWReport (https://github.com/biolab/orange3/blob/37e7b0232760ec39b8206a578f63449fdd004615/Orange/widgets/report/owreport.py).
