### ISSUE TITLE
Zoom/Select not positioned properly

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#5063]
- [ ] **What's wrong?**

Zoom/Select buttons are positioned in a strange way.

- [ ] **How can we reproduce the problem?** 

Open any point-based visualization.

<img width="289" alt="Screen Shot 2020-11-03 at 10 44 08" src="https://user-images.githubusercontent.com/12524972/97997153-f5e55e00-1de8-11eb-9cf3-00e5948d3078.png">

Env info:
```
anyqt                     0.0.11                   pypi_0    pypi
pyqt                      5.12.3           py38he22c54c_1    conda-forge
pyqt5                     5.14.2                   pypi_0    pypi
pyqt5-sip                 12.7.2                   pypi_0    pypi
pyqtgraph                 0.11.0                   pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
qt                        5.12.5               h514805e_3    conda-forge
qtconsole                 4.7.3              pyh9f0ad1d_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
```

- [ ] **Which version of Orange are you using? How did you install Orange?**

3.28.dev

- [ ] **What is your operating system?**
OSX

**Comment by irgolic** [comment]
This is intentional, the last button doesn't change the selection type. 

Can you elaborate as to why it's wrong?

**Comment by ajdapretnar** [comment]
I never occurred to me these are different types of buttons. I consider them "Alter the view" buttons. If it is intentional, I'm fine either way. Perhaps a subtle dash between the buttons could be an alternative?
