### ISSUE TITLE
Merge columns into one

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#5066]
- [ ] **What's your use case?**

I have a dataset, where I wish to combine two or more columns into a single column, say a sum of values.

- [ ] **What's your proposed solution?**

Perhaps add a widget to enable merging (joining) columns with several aggregation methods (sum, mode, mean).

- [ ] **Are there any alternative solutions?**
Perhaps this is just my special use case. Tell me this is too specific and close it. Just an idea.

**Comment by irgolic** [comment]
We could add "non-expert" features for Feature Constructor, supporting easy aggregation methods.

**Comment by janezd** [comment]
@ajdapretnar, what about a widget Aggregate, which has set of radio buttons to choose the function (sum, product, min, max, mean, median, variance, count defined, count non-zero) and a list view to select a subset of numeric variables, with a button "All" that selects all?

This would construct a single new feature. If one would need to construct more (which would, I suppose, seldom be the case), Feature Constructor would be a better match, or (s)he can chain Aggregate widgets.

@irgolic, adding this to Feature Constructor seemed a good idea, but the more I think about it, the more it looks like a totally different widget. They serve a similar function, but the overlap is so small that it would only complicate the code (which is already complex).

**Comment by irgolic** [comment]
Users will expect Aggregate to be like pandas' aggregate (our Pivot Table).

It seems like a handy feature, but I'd refrain from adding new widgets unless the functionality really doesn't fit elsewhere. If not Feature Constructor, maybe Pivot Table could use this?

I've been in a situation before where I wanted to sum all the values in a feature, but Pivot can't do it. IIRC I gave all rows an additional categorical column with the same value and aggregated according to that. Not sure if this is related to the OP, but perhaps the solution could solve both.

**Comment by janezd** [comment]
Feature Constructor or Pivot Table, in either case we'd need a list view with all features, and it doesn't fit well into the layout, IMHO.

**Comment by ajdapretnar** [comment]
> I've been in a situation before where I wanted to sum all the values in a feature, but Pivot can't do it.

Yes, I've also often wanted to do it and resorted to Python Script. Even though it is a fairly straightforward task.

Pivot Table aggregates row-wise, while this aggregation is column-wise. Pandas' aggregate also has an option to aggregate column-wise.

I agree with @janezd - these are two quite different use cases, conceptually. One is groupby behaviour for rows, where rows would be aggregated on keys. I cannot image a case where the user would want to aggregate only row 1, 3, 17, and 24. The other use case is the one described above - a combination of column provides a new variable (and with it new information). It can be a sum of values or a mean of a group of values.

As much as I'd like to, I cannot imagine fitting this in any other widget. The only alternative is a Groupby widget, where the user selects row-wise or column-wise operation and the layout changes accordingly (if we perhaps want to make the widget a bit more pandas-like).
