### ISSUE TITLE
Can't launch from Anaconda Navigator pyQtgraph no attribute time.clock 

### ISSUE THREAD

**Issue by FungShen** [biolab/orange3#5068]
- [ ] **What's wrong?**

I downloaded Orange3 v 3.26 directly from Anaconda. When it finished installing, clicking 'launch' produces this error 
```Traceback (most recent call last):
File "C:\Users\fung2\anaconda3\Scripts\orange-canvas-script.py", line 6, in 
from Orange.canvas.__main__ import main
File "C:\Users\fung2\AppData\Roaming\Python\Python38\site-packages\Orange\__init__.py", line 33, in 
import pyqtgraph # import pyqtgraph first so that it can detect Qt5
File "C:\Users\fung2\AppData\Roaming\Python\Python38\site-packages\pyqtgraph\__init__.py", line 204, in 
from .graphicsItems.VTickGroup import * 
File "C:\Users\fung2\AppData\Roaming\Python\Python38\site-packages\pyqtgraph\graphicsItems\VTickGroup.py", line 7, in 
from .. import functions as fn
File "C:\Users\fung2\AppData\Roaming\Python\Python38\site-packages\pyqtgraph\functions.py", line 17, in 
from . import debug
File "C:\Users\fung2\AppData\Roaming\Python\Python38\site-packages\pyqtgraph\debug.py", line 11, in 
from . import ptime
File "C:\Users\fung2\AppData\Roaming\Python\Python38\site-packages\pyqtgraph\ptime.py", line 24, in 
cstart = systime.clock() ### Required to start the clock in windows
AttributeError: module 'time' has no attribute 'clock'
 ```

- [ ] **How can we reproduce the problem?** 
Install the latest Anaconda individual license, On the main page of Navigator, Orange3 is promoted. click 'Install'. When finished, 'Launch' will appear where it previously said 'Install'

Python 3.8, Anaconda3, Orange 3.26 

no file to upload

- [ ] **Which version of Orange are you using? How did you install Orange?**

Install the latest Anaconda individual license, On the main page of Navigator, Orange3 is promoted. click 'Install'. When finished, 'Launch' will appear where it previously said 'Install'

Python 3.8, Anaconda3, Orange 3.26 

- [ ] **What is your operating system?**

Windows 10 Professional

**Comment by janezd** [comment]
The problem is in pyqtgraph was fixed in https://github.com/pyqtgraph/pyqtgraph/pull/980. Can somebody who's more into pyqtgraph and anaconda check the versions and investigate why this happenned?

**Comment by markotoplak** [comment]
Thank you for your report. This bug was fixed long ago, but it seems that your Anaconda installation still runs pyqtgraph 0.10.0.

@FungShen, could you verify which version you have? In a command line you could do `conda list` to get all installed versions.

Your immediate solution is to add the conda-forge channel and then upgrade pyqtgraph from it. Also, because we have no influence over the official Anaconda packages we suggest that you either use our official packages (download from https://orange.biolab.si) or that you install orange3 from the conda-forge conda channel.

**Comment by FungShen** [comment]
I just uninstalled Anaconda and python and reinstalled everything and it works now. I think the issue had something to do with where the orange environment originally installed.
