### ISSUE TITLE
analyse film scenario  and export elements 

### ISSUE THREAD

**Issue by wadeeProd** [biolab/orange3#5076]
Hi, my first day in github, I'm here to discover more about your project,  I'm not a developer but a filmmaker. 
I'm building a website. with collaborative text edit app,  I'm looking for a tool to analyse film scenarios. 
I'm looking for results like: listing persons/names , locations, props/things.. included in the scenario.
Can I use your app for this purpose? 
If yes, what is the best roadmap to take? If no do you have suggestion of other open source app?
Big thanks for all your efforts guys. 
Cheers,
Wadee

**Comment by ajdapretnar** [comment]
@wadeeProd  Best resource to discover more about Orange is to visit https://orange.biolab.si/.

**Comment by wadeeProd** [comment]
Thank you, very interesting indeed.
