### ISSUE TITLE
Add-on install downgrades Orange

### ISSUE THREAD

**Issue by borondics** [biolab/orange3#5078]
Not sure this is the right place to report this, so please redirect it if necessary. It might be specific to one Add-on or multiple.

- [x] **What's wrong?**

When I install `orange3-text 1.2.0` from the Add-on menu one of the new packages conda installs is Orange3 itself.
```
## Package Plan ##

  environment location: ____/miniconda3

  added / updated specs:
    - orange3-text=1.2.0

The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    matplotlib-3.3.2           |   py37hf985489_1           6 KB  conda-forge
    matplotlib-base-3.3.2      |   py37hdacc966_1         6.8 MB  conda-forge
    typed-ast-1.4.1            |   py37h4b544eb_1         206 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         7.0 MB

The following NEW packages will be INSTALLED:
  orange3            pkgs/main/osx-64::orange3-3.26.0-py37hb1e8313_0
  orange3-text       conda-forge/noarch::orange3-text-1.2.0-py_0

```

The problem is that I am usually running the latest GitHub master and this means that my Orange is being downgraded by an Add-on. 

- [x] **How can we reproduce the problem?** 

Is there a way of having the Add-on require at least a specific version and not exactly one? Maybe this was a bug in the Text Add-on requirements. The `https://github.com/biolab/orange3-text/blob/master/requirements.txt` file seems to be set up correctly.

- [x] **What's your environment?**

- Operating system: Mac OSX 10.15.7
- Orange version: Usually GitHub master (3.28.0.dev0+29e992f in this case) but downgraded to orange3-3.26.0-py37hb1e8313_0 by the Add-on
- How you installed Orange: GitHub master / pip

**Comment by markotoplak** [comment]
Orange3-text feedstock is correct. It specifies `orange3 >=3.25.0`.

The problem here appears because you have a non-conda installed orange3 in a conda environment. Still, you shouldn't be seeing this.

BTW, do you know what did `pip freeze | grep range3` show you before? `pip` remembers installation version from the last time you did `pip install -e .`, and if that was long time ago, and then you just pulled from master, the system could think that you had some old version. But if you did `pip install -e .` recently, then I can not explain this behaviour.

**Comment by borondics** [comment]
Yeah, I did `pip install -e .` recently. It showed the correct, master version before.

**Comment by PrimozGodec** [comment]
@markotoplak maybe it is connected with my situation when I wanted to test this behaviour. I created new conda environment and tried to install orange3 from conda-forge channel:
```
conda install orange3 -c conda-forge
```
This command seems to ignore the specified channel and try to install orange `pkgs/main` channel where the latest version is `3.26.0.`. Other dependencies are mainly installed from conda-forge. It seems that cona enabled installing dependencies from mixed channels (in the past it was not possible) but I will still expect that the main package is installed from the selected channel.

**Comment by PrimozGodec** [comment]
https://github.com/conda/conda/issues/10348

**Comment by Locutus14** [comment]
This might be related to my issue, with text-mining, when I updated I lost the option to import documents. Does anyone have a work-around?
