### ISSUE TITLE
Need documentation for the new "Portable" zip file

### ISSUE THREAD

**Issue by xmatic** [biolab/orange3#5084]
There seems to be a new way to install Orange available. In this link: https://orange.biolab.si/download/#windows , I can see something called "**Portable Orange, Orange3-3.27.1.zip**".

I downloaded it, unzipped it, but couldn't figure out how to use it. (I tried using the commands: `orange-canvas`, `conda`, `pip`) in the `Orange.lnk` Command Line file (after navigating to the unzipped Orange folder), but none of these commands worked.

Please add some documentation on how to use it. Thank you.

**Comment by ales-erjavec** [comment]
1.) In the unziped folder there should be a *Orange* directory and an *Orange* link that starts the application.

2.) Inside the *Orange* directory there is also a *Orange Debug* link that should open a cmd window and start the application displaying the output/errors in the cmd window.

3.) The 'Orange Command Line' in the *Orange* directory will probably not work.

You might have some luck with running `pyhton -m Orange.canvas`, python -m pip ...` while in the *Orange* directory (or always use full path to `python` executable).

**Comment by xmatic** [comment]
> 1.) In the unziped folder there should be a _Orange_ directory and an _Orange_ link that starts the application.
> 
> 2.) Inside the _Orange_ directory there is also a _Orange Debug_ link that should open a cmd window and start the application displaying the output/errors in the cmd window.


Thanks for the reply.

The Orange link that you describe in 1) opens a cmd window in the system32 folder (in Windows). But the Orange application doesn't open.

Fortunately, I already have Orange set up and working in, but I was testing this Portable version to see how it worked.

I think a Portable, self-contained, version of Orange is an excellent idea, and I hope the devs keep working on it until it becomes very simple to use.

**Comment by thocevar** [comment]
You found the right `Orange.lnk` shortcut. It's right in front in the root folder of the zip file. I don't think it needs extra documentation.

However, I can't tell why it doesn't work for you. I just tried it on a clean install of Windows 10 and it works without a problem. What version are you using? If you check the properties of that shortcut it points to `%COMSPEC% /C start Orange\pythonw.exe -m Orange.canvas`. This should be the same as running `start Orange\pythonw.exe -m Orange.canvas` from a cmd window (while located in the same directory as `Orange.lnk`). Instead, you can try running `Orange\python.exe -m Orange.canvas -l4` from cmd to see any warning/errors.
