### ISSUE TITLE
Orange3 does not start in macOS Big Sur

### ISSUE THREAD

**Issue by gerardojuan** [biolab/orange3#5085]
- [ ] **What's wrong?**
Under macOS Big Sur the orange3.app (latest version 3.27.1) stalls during startup. No screens appear, only "Orange" in the Mac menu Bar. The app can only be closed using force quit, then Mac says "force quit python". Reinstalling did not help.

- [ ] **How can we reproduce the problem?** 
I think by installing Big Sur and opening Orange3.

- [ ] **What's your environment?**
- Operating system: macOS Big Sur. (MacBook Pro, mid 2018, i7, 16gb)
- Orange version: 3.27.1
- How you installed Orange: downloaded here: https://orange.biolab.si/download/#macos

**Comment by markotoplak** [comment]
And likely won't get solved for a while. Supporting bleeding edge MacOS is hard. Our dependencies, most importantly PyQt, need to update for Big Sur. I hope they do soon.
