### ISSUE TITLE
Polynomial Regression in Orange Linux

### ISSUE THREAD

**Issue by johnneuland** [biolab/orange3#5087]
- [ ] **What's wrong?**

According to this link, Orange3 also allows using Polynomial Regression on data. However, when I installed Orange on my Linux machine, it does not not show Polynomial Regression as an option under the models section where other ML algorithms are mentioned.

Am I missing something or is PR no longer possible?

- [ ] **What's your environment?**
Linux - Ubuntu

- How you installed Orange:
Virtual Environment

**Comment by janezd** [comment]
I don't see the link. Have you forgotten to include it?

The Polynomial regression widget is in Education add-on. You can use Options / Add-ons to install it.
