### ISSUE TITLE
Keyboard shortcut in Save File dialog not working

### ISSUE THREAD

**Issue by borondics** [biolab/orange3#5088]
_This might be more of a canvas or widget-base issue._

- [x] **What's wrong?**

The usual Cmd-C, Cmd-V, Cmd-A keyboard shortcuts don't work in the Save File window filename text box of `Save File` widget using the _Save as..._ button. When using the mouse and selecting Copy or Paste it is fine though.

- [x] **How can we reproduce the problem?** 

Load any data and try to save it.

- [x] **What's your environment?**

- Operating system: Mac OS X 10.15.7
- Orange version: Orange3 3.28.0.dev0+29e992f, latest orange-widget-base and orange-canvas-core
- How you installed Orange: GitHub master / pip install

**Comment by markotoplak** [comment]
I was able to replicate this on my Mac. This topic seems quite popular on the Qt bug tracker: https://bugreports.qt.io/browse/QTBUG-85679, https://bugreports.qt.io/browse/QTBUG-17291.

**Comment by janezd** [comment]
@markotoplak, thanks for the hint. This is actually easily fixable. At least on my machine/os.

**Comment by janezd** [comment]
At today's meeting, we said that adding a menu with Copy, Cut and Paste to file widgets (see https://github.com/biolab/orange-canvas-core/pull/158) would look too weird, so this can't be fixed until Qt developers recognize this as a bug and fix it, or provide another way to add those shortcuts.
