### ISSUE TITLE
OWDatasets: Reduce width

### ISSUE THREAD

**Issue by irgolic** [biolab/orange3#5091]
The widget is quite big at the moment, and many of the columns could be narrower by default.

**Current**
![Screenshot 2020-11-19 at 17 00 56](https://user-images.githubusercontent.com/24586651/99690776-cb520100-2a88-11eb-8185-e1efd6975ff5.png)

**Possible solution**
![Screenshot 2020-11-19 at 17 01 11](https://user-images.githubusercontent.com/24586651/99690813-d4db6900-2a88-11eb-9af8-b75bd1ec6f8b.png)

The sizeHint should not be set on the widget itself, it should be set on the table. To calculate it, each column's preferred width should be calculated by checking its values, and it should be clamped to a maximum value (i.e., long titles should elide).

**Comment by ajdapretnar** [comment]
Currently, if using `sizeHintForColumn`, the view doesn't change. I could not find a solution other than hardcoding the upper limit, which I don't think is desirable. Suggestions?

**Comment by irgolic** [comment]
Did you comment out the widget's sizeHint?

**Comment by ajdapretnar** [comment]
Commenting it out just "breaks" the view, not column width. Namely the window isn't wide enough. Columns, when resizing the window, are still too wide.
