### ISSUE TITLE
Issues with using RReliefF values for feature selection

### ISSUE THREAD

**Issue by Ahingsun** [biolab/orange3#5092]
- [ ] **What's wrong?**
I want to select features which work best for prediction of non-categorical values, and I chose the top 10 features with high RReliefF scores. However, it turns out that the prediction performance is worse when I chose the 10 features with highest RReliefF scores than when I chose the 10 features with lowest RReliefF scores. 
As far as I understand, higher RReliefF score indicates that the feature works better. Doesn't it? 
Should I choose the features with low RReliefF scores to select good features for prediction? 

I also have a question, is there any way that I can choose the number of features which works best (e.g. using n features is enough to predict as good as using all features)?

- [ ] **How can we reproduce the problem?** 
I upload the raw data, ows, and screenshot files. 
[orange_issue.zip](https://github.com/biolab/orange3/files/5577357/orange_issue.zip)

- [ ] **What's your environment?**

- Operating system: windows10
- Orange version: orange 3.26.0
- How you installed Orange: hmm I don't remember the details... from the orange website.

**Comment by janezd** [comment]
> As far as I understand, higher RReliefF score indicates that the feature works better. Doesn't it?

In general, you are of course correct, but this is just a heuristic. RReliefF is making and educated guess. :)

RReliefF's guesses will be wrong (or blind, random) under conditions in which it can't work. I believe that your data is a good example. You have very large number of variables, hence, Relief must compute distances in a very high dimensional space. Metrics there just ... breaks down, has no sense. So Relief, which is based on the notion of proximity, can't work.

And neither will any other method on your data.

In general, you would use some kind of internal cross validation for determining the optimal number of features or the feature subset (e.g. https://en.wikipedia.org/wiki/Feature_selection#Wrapper_method). But it won't work on your data. To select features, you need some additional source of information.

**Comment by Ahingsun** [comment]
Thanks for the kid answer!
