### ISSUE TITLE
how can i convert my python pandas data frame to orange python script

### ISSUE THREAD

**Issue by suhyun565** [biolab/orange3#5093]
from Orange.data.pandas_compat import table_from_frame
in_object=table_from_frame
out_object=df_sort_group_top3
df_sort_group_top3 = df.sort_values(by='장르').groupby('장르').head(3)
print(out_object)

#they say 'NameError: name 'df_sort_group_top3' is not defined'
 what is my problem ?

**Comment by markotoplak** [comment]
This does not seem like a bug. The Pythons script widget behaves as expected here. The code you show is syntactically incorrect.
