### ISSUE TITLE
need widget to visualize proportion (of total)

### ISSUE THREAD

**Issue by sleepybunn** [biolab/orange3#5098]
hi,

i've tried orange, it is very good.
however, in my opinion, it need improvement, until now, i can't find ideal widget to "visualise proportion from total" (e.g. treemaps / squarify or pie chart)
i've tried box plot, but it can only show proportion on categorical variable (not numerical), also i've tried the bar plot, but the bar can't be "split.
hopefully it can be provided in the future

many thanks, great work so far

**Comment by ajdapretnar** [comment]
You are describing Distributions. Bar plot can be split with Group By. Or you can use Mosaic Display.

**Comment by sleepybunn** [comment]
ah, then it means bar plot & mosaic can be used?

for example, i have data table with 3 columns (C1, C2, C3)
C1 = discrete variable
C2 = discrete variable
C3 = continuous variable

C1     C2     C3
G      AA      10 
H      AA      15
I       AA        7
J       BB       30
K       BB      32
L       CC      50

those data could be visualize beautifully with treemaps, could you suggest to visualize them in mosaic?

many thanks
