### ISSUE TITLE
how to show matplotlib plot result in orange widget?

### ISSUE THREAD

**Issue by sleepybunn** [biolab/orange3#5099]
hi,

many thanks for developing orange.
at this moment, i am able to use python script, i put database connector on the script, and it can extract data, then store it on orange data table
i want to know, can we put matplotlib on the script, and the plot result is used as "output" of the script (similar with out_data), and then be shown on separate widget?
because at this moment, there are still more visualization choice in matplotlib, than readily available on orange widget.

many thanks in advance

**Comment by ajdapretnar** [comment]
@sleepybunn Thank you for the questions. However, Github is not a place to ask questions. It is a place for reporting issues and suggesting features. Please use Discord for questions.

**Comment by sleepybunn** [comment]
ah, OK

**Comment by sleepybunn** [comment]
still trying creating discord account
