### ISSUE TITLE
need widget similar with treemap / squarify

### ISSUE THREAD

**Issue by sleepybunn** [biolab/orange3#5100]
hi,

i still can't find orange widget to visualize data as similar with treemap / squarify
for example, i have data table with 3 columns (C1, C2, C3)
C1 = discrete variable
C2 = discrete variable
C3 = continuous variable

C1    C2      C3
--      --       -- 
G      AA      10
H      AA      15
I       AA       7
J       BB       30
K      BB       32
L       CC      50

those data could be visualize beautifully with treemaps, could you suggest to visualize them in mosaic (or any other orange widget)? i've tried many things but no succeed, & i read on the documentation, mosaic is suited for "frequency based" data

many thanks

**Comment by ajdapretnar** [comment]
Please try with Discord. Use Github only for issues and feature request with appropriate template.

**Comment by sleepybunn** [comment]
hithank yousorry, i have created discord account, but cannot send message on orange group, seems permission problem--Sent from my Android phone with GMX Mail. Please excuse my brevity.On 27/11/2020, 17:32 Ajda <notifications@github.com> wrote:

   
  Please try with Discord. Use Github only for issues and feature request with appropriate template.
