### ISSUE TITLE
testing widget integration into Orange3 workflow (OWS)

### ISSUE THREAD

**Issue by mjolly** [biolab/orange3#5103]
Hi:

Are there any info links on continuous integration and testing of a home-grown widget into Orange3 in the development environment ?
The development environment can be PyCharm (windows) or Linux (virtual environment).

Currently, we don't know how to test a newly development widget in workflow (.OWS) in a dev environment.
And are manually adding the widget to the Orange3 GUI application and testing it, which is not sustainable workflow.

How is the Biolab orange3 group testing their widgets into the workflow(OWS) in a dev or test environment and using what tools ?

Thanks

**Comment by markotoplak** [comment]
What we do for developing widgets is:
- For quick tests we use the code after `if __name__ == "__main__":`, which runs the widget with some data. See any widget in this repo for an example.
- For more, we write widget tests, which check how widgets respond to a particular signal or user interaction.  For example, see https://github.com/biolab/orange3/blob/master/Orange/widgets/unsupervised/tests/test_owkmeans.py.
- Widget tests can include multiple communicating widgets, so in a way you make a small workflow. Like in `test_no_values_target` in https://github.com/biolab/orange3/blob/master/Orange/widgets/evaluate/tests/test_owpredictions.py.
- Orange tests also run some OWS files, but these we only use to see if workflows load successfully, not for testing the outputs. Like here: https://github.com/biolab/orange3/blob/master/Orange/widgets/tests/test_workflows.py

Was this helpful?

**Comment by mjolly** [comment]
Thanks for your response, Team Biolab
