### ISSUE TITLE
Scatterplot widget fails to allow definition of axes in Orange 3.27.1 on Mac Catalina 10.15

### ISSUE THREAD

**Issue by jpstarpaper** [biolab/orange3#5110]
- [ ] **What's wrong?**

I’m still working my way through the YouTube tutorial on using Orange to analyze Covid-19 data. For the desktop version of Orange, 3.27.1, the Scatterplot widget isn’t allowing me to define the X and Y axes. 

There’s no response from the dropdown, just a blank, white space where I’d need to choose “cases per million” for the X axis, and “Physicians per 100,000 people” for the Y axis. 

In the video, that choice happens at 4:46
https://www.youtube.com/watch?v=EfsqjFJC434&vl=en

- [ ] **How can we reproduce the problem?** 
You'd follow the Orange tutorial on YouTube and look for the lack of response from the dropdown for defining the axes (shown starting at 4:46 in the tutorial). 

I'm uploading my ows file and a screenshot of where I'm at when I see the fail. 

The fail happens at the point after we've added a Feature Constructor widget, then connected Scatterplot to it. Double-clicking Scatterplot brings up a pane in which we're supposed to choose elements to define the axes (a pane that also allows us to choose color, shape, size ... and other attributes). 
- [ ] **What's your environment?**
I'm on Mac 10.15, running Orange off my harddrive (in a previously reported bug I was using Orange via Anaconda Navigator). 

- Operating system: Mac Catalina 10.15
- Orange version: 3.27.1
- How you installed Orange: From a dmg file downloaded from:
https://orange.biolab.si/download/#macos

I downloaded the "Bundle" version for Mac. The filename is "Orange3-3.27.1-Python3.7.6.dmg"

[covid19_tutorial_scatter_plot_fails.ows.zip](https://github.com/biolab/orange3/files/5645735/covid19_tutorial_scatter_plot_fails.ows.zip)
![scatterplot_widget_fail_point_orange](https://user-images.githubusercontent.com/12688198/101219524-291e4580-3652-11eb-990f-bf6f85c3dce1.png)

**Comment by ajdapretnar** [comment]
Please see https://youtu.be/lb-x36xqJ-E on how to use Orange.
