### ISSUE TITLE
Launching error with Miniconda installation

### ISSUE THREAD

**Issue by KimHono** [biolab/orange3#5111]
Hi !
I've got the following error when installing Orange via Miniconda method:
`Traceback (most recent call last):`
`  File "/usr/bin/orange-canvas", line 5, in <module>`
`    from Orange.canvas.__main__ import main`
`ModuleNotFoundError: No module named 'Orange'`

Conda version : 4.9.2

**Comment by markotoplak** [comment]
I see that system's standard python is being executed. It looks that you are trying to run Orange from a shell that does not have conda activated. The miniconda installer probably showed you some instructions on activating conda in your shell (or asked about making conda python default).

**Comment by KimHono** [comment]
No, the installer didn't showed any warning or advice.
But is there a risk of conflict between Miniconda and Python3 ?

**Comment by markotoplak** [comment]
Miniconda installs its own python. And yes, you can use only one of them as the default python in a terminal, so you need to activate it in some way. I do not have it installed here so I can not help you with details.

If "conda" command is visible, you can try activating some environment as written here: https://docs.conda.io/projects/conda/en/latest/user-guide/getting-started.html

**Comment by KimHono** [comment]
Thanks, I've read this page. But I don't understand why I've got 2 environments with the same name:
`orange3     /opt/miniconda3/envs/orange3`
and
`orange3     /home/username/.conda/envs/orange3`
?

**Comment by markotoplak** [comment]
Hm. I would not know. If you activate one of them, does running orange-canvas work then?

**Comment by markotoplak** [comment]
Thank you for bringing cryptic installation instructions to our attention. I opened #5112 to address these issues in the future.

**Comment by KimHono** [comment]
> Hm. I would not know. If you activate one of them, does running orange-canvas work then?

The first one "orange3" env. in the list is activated, but `orange-canvas` doesn't work.
Same error as above.

**Comment by markotoplak** [comment]
@KimHono, I went through conda installation instructions on Linux myself and these instructions were missing explicit `conda activate orange3` after the environment was created.

Can you do `conda activate orange3` and then redo installation steps starting from (and including) adding conda-forge channel? This will probably be easier that pip installation you are attempting as an alternative.

**Comment by markotoplak** [comment]
And to get the newest version use `conda install orange3=3.27.1`, otherwise conda seems to install 3.26.0.
