### ISSUE TITLE
Failing to install Orange via Pip

### ISSUE THREAD

**Issue by KimHono** [biolab/orange3#5113]
Hi !
I tried to install Orange via the Pip method explained here : [https://github.com/biolab/orange3](url)
While proceeding with `pip install orange3` I saw these errors:
`  ERROR: Command errored out with exit status 1:
   command: ~/orange3venv/bin/python ~/orange3venv/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmp753675oj                                                                                                                                       
       cwd: /tmp/pip-install-u9ojt7yc/orange3`
and also
`  setup.py:155: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses          
    import imp`
and also
`  Orange/classification/_simple_tree.c: In function ‘gain_ratio_c’: 
Orange/classification/_simple_tree.c:63:2: warning: implicit declaration of function ‘qsort_r’; did you mean ‘qsort’? [-Wimplicit-function-declaration]                                                                                                                                                   
     63 |  qsort_r(base, nel, size, compar, thunk)
  Orange/classification/_simple_tree.c:147:2: note: in expansion of macro ‘QSORT_R_FUNC’                                                              
    147 |  QSORT_R_FUNC(examples, size, sizeof(struct Example), (void*) &compar_attr, compar_examples);  `
and also
`  Orange/classification/_tree_scorers.c: In function ‘__pyx_pf_6Orange_14classification_13_tree_scorers_2find_threshold_entropy’:                     
  Orange/classification/_tree_scorers.c:3115:27: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]                                                                                                                                              
   3115 |   __pyx_t_7 = ((__pyx_v_N <= __pyx_v_min_leaf) != 0); `
and also
`  Orange/classification/_tree_scorers.c: In function ‘__Pyx_modinit_type_init_code’:                                                                  
  Orange/classification/_tree_scorers.c:24988:25: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’                     
  24988 |   __pyx_type___pyx_array.tp_print = 0;`
and also
`  Orange/classification/_tree_scorers.c: In function ‘__Pyx_ParseOptionalKeywords’:                                                                   
  Orange/classification/_tree_scorers.c:25695:21: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]                     
  25695 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :`
And many more, then finally:
`ERROR: Could not build wheels for orange3 which use PEP 517 and cannot be installed directly
`
As I imagined, the result doesn't work:
`~/orange3venv/bin/python: Error while finding module specification for 'Orange.canvas' (ModuleNotFoundError: No module named 'Orange')
`

My system : 5.9.11-arch2-1
Python version 3.9.0 
Pip version 20.3.1

**Comment by markotoplak** [comment]
The what you posted are just warnings and I therefore had no idea what went wrong. Post the complete log, please, or at list the actual error with some neighboring context, please.

**Comment by KimHono** [comment]
To understand what's going on, I created a totally new virtual machine, and successfully installed Orange via pip.
But this time, Python's version is 3.8.6 and Linux is 5.9.11-3-MANJARO.

So, maybe the problems are only linked with the Python environment ?

**Comment by KimHono** [comment]
I post here the complete log.
[Orange_log.txt](https://github.com/biolab/orange3/files/5648649/Orange_log.txt)

System : 5.9.11-arch2-1
Python version 3.9.0

**Comment by markotoplak** [comment]
Thanks. This was fixed in #5080, but that was not released yet. Either use the master branch or use Orange with python<=3.8.
