### ISSUE TITLE
Error report on Failing to install Orange via Pip

### ISSUE THREAD

**Issue by bsnresearcher** [biolab/orange3#5114]
Error report on `pip install Orange3` at Python3.9.

Same problem at the issue "Failing to install Orange via Pip #5113"

The errors seems to be caused by obsolete of  'tp_print' from python3.9.

Should I wait wheel_dist package which corresponds with this problem? 

>  Orange/classification/_tree_scorers.c:24988:26: error: no member named 'tp_print' in 'struct _typeobject'
>    __pyx_type___pyx_array.tp_print = 0;
>    ~~~~~~~~~~~~~~~~~~~~~~ ^
>  Orange/classification/_tree_scorers.c:24993:32: error: no member named 'tp_print' in 'struct _typeobject'
>    __pyx_type___pyx_MemviewEnum.tp_print = 0;
>    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
>  Orange/classification/_tree_scorers.c:25008:31: error: no member named 'tp_print' in 'struct _typeobject'
>    __pyx_type___pyx_memoryview.tp_print = 0;
>    ~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
>  Orange/classification/_tree_scorers.c:25021:36: error: no member named 'tp_print' in 'struct _typeobject'
>    __pyx_type___pyx_memoryviewslice.tp_print = 0;

**Comment by markotoplak** [comment]
Thanks. This was fixed in #5080, but that was not released yet. Either use the master branch or use Orange with python<=3.8.
