### ISSUE TITLE
API: add function for adding new columns

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#5115]
- [ ] **What's your use case?**
I wish for an easy way to add new columns in Orange scripting.

- [ ] **What's your proposed solution?**
Something along the lines of:
```
iris = Table('iris')
iris.add_column(var, values)
```

- [ ] **Are there any alternative solutions?**
I was taught the way to add columns in Orange is:
```
from Orange.data import Table, Domain, ContinuousVariable

zoo = Table('zoo')
values = ['foo' for i in range(len(zoo))]
new_var = ContinuousVariable(name='String')
new_domain = Domain(attributes=zoo.domain.attributes,
                    metas=zoo.domain.metas+(new_var,))
out_data = zoo.transform(new_domain)
col, _ = out_data.get_column_view(new_var)
col[:] = values
```

Looking at the script closely, you see that it shouldn't work. But it does (no objections from Orange). As is expected. But the limitation of this method is that one can make silly mistakes as above (I forgot to replace ContVar with StrVar) without noticing. It would be lovely if Orange provided an API for adding new columns, which would check for such inconsistencies.

**Comment by janezd** [comment]
We prefer to think about `Table` is immutable.

I agree there should be a simpler way to add columns, but it should result in a new table.

**Comment by PrimozGodec** [comment]
In Orange3-text we had a method that actually added columns to the Corpus (Table). It was, as you said, a bad practice so we change it to the method which adds columns to the copy of the Corpus and returns it. I think something similar can be implemented for Orange too.

**Comment by ajdapretnar** [comment]
I think it is fairly common to want to add a new column (or more), so a nice little method with a copy would be lovely.
