### ISSUE TITLE
Scatter Plot: colors for more than 10 discrete values

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#5130]
When coloring the plot by discrete attributes with more than 10 values, colors are mapped according to all their values (i.e. the 103rd discrete value from the domain will have the 103rd color from discrete scale). However, Scatter Plot only shows top 10 values (most frequent), coloring other values with gray.

Would we rather have the original Orange mapping here? (blue, red, green, orange, yellow, etc.)? With the current state it can happen that two colors are very indistinct.

Up for discussion.

<img width="859" alt="Screen Shot 2020-12-15 at 16 21 16" src="https://user-images.githubusercontent.com/12524972/102235075-3f4dc080-3ef2-11eb-8396-b2e79ab4c414.png">

**Comment by janezd** [comment]
We discussed this a lot. The idea here was to adhere to the same coloring in all widgets, so that, say, class 5 is always green. Besides, these colors may have been set by the user...

**Comment by ajdapretnar** [comment]
Ok, thanks for the explanation.
