### ISSUE TITLE
Windows installers are getting too big; dropping Intel's mkl would make them smaller

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#5135]
Windows miniconda installer for Orange 3.27.1 is 495 MB, and standalone .zip is 533 MB. This is a problem, because Cloudflare cache only works for files up to 512 MB. Remember slow downloads when we were doing workshops abroad? We should not cross that limit.

I checked what was going on and a big part of that installer is Intel's MKL library. Replacing it with OpenBLAS yields 328 MB for the installer and 339 MB for the standalone .zip. Tests pass. Experimental installers for testing are here: https://ci.appveyor.com/project/markotoplak/orange3-installers/builds/36872318/job/fr2wdviuw4xba9du/artifacts

Replacing MKL with OpenBlas only slightly changes runtimes of some operations. Some of them might even be faster, especially on AMD's CPU, which MKL sometimes treats very conservatively, intentionally or not. For me, a smaller binary is a better compromise, but I might be biased as I type this on an AMD processor.

For that test binary I also made conda-forge the priority repository. We have seen that Anaconda's official repo is sloppily maintained for Orange3, and now I noticed that for newer OpenTSNE they still require numba, even though @pavlin-policar dropped it from requirements with 0.4. So this binary is smaller because drops MKL and numba.

Potential problems:
- What happens if OpenBLAS Orange is installed over MKL installed (previous) version? I anticipate problems...
- Some add-on installation could fail, if they require some library that is only MKL compatible. I can not think of any but these never cease to surprise me.

In any case, now that Orange is getting a facelift, it could also lose some weight.

**Comment by ajdapretnar** [comment]
> In any case, now that Orange is getting a facelift, it could also lose some weight.

😄 

So you are saying we should test the installers with all the add-ons?

**Comment by markotoplak** [comment]
> So you are saying we should test the installers with all the add-ons?

Yea. But I'd wait a bit, perhaps someone will point out why replacing MKL is a bad idea.

**Comment by pavlin-policar** [comment]
Other than a pretty steep performance hit on Intel processors, I think there really shouldn't be any issues with this. Some benchmarks can be found [here](https://software.intel.com/content/www/us/en/develop/articles/performance-comparison-of-openblas-and-intel-math-kernel-library-in-r.html). @acopar did benchmarks and he might know more.

Of course, you can easily argue that we only deal with small matrices in Orange, in which case the performance might drop from 0.02 seconds to 0.08 seconds, which is still invisible to our users, so it's unlikely to be too much an issue. Why not just have both options, and make OpenBLAS the default?

**Comment by markotoplak** [comment]
Looking at these - non-Intel - benchmarks, there seems to be not much of a difference: https://stackoverflow.com/questions/5260068/multithreaded-blas-in-python-numpy

**Comment by markotoplak** [comment]
> Why not just have both options, and make OpenBLAS the default?

Yes, we should document an easy option to switch to MKL. It should only be 1 conda command, I think.

**Comment by borondics** [comment]
> Other than a pretty steep performance hit on Intel processors, I think there really shouldn't be any issues with this.
So all the pre-2020 Apple computers would be affected?

> Of course, you can easily argue that we only deal with small matrices in Orange
Quasar deals with large datasets sometimes.

**Comment by irgolic** [comment]
> Of course, you can easily argue that we only deal with small matrices in Orange

This sets a bad precedent, could we knock off 11MB to hit the 512MB cutoff any other way?

**Comment by markotoplak** [comment]
@irgolic, for now, yes, we could knock it down a bit by taking care that OpenTSNE does not install unneeded dependencies, but add some dependencies and it is game over. The thing is that MKL is 1/3 of our package. This increases download times and disk space used for little benefits.

Anyway, the differences are not usually as drastic as that page show, usually they are in ~10%. Intel's experiments used an extreme Intel processor at a time, when, I suspect, OpenBLAS was not optimized for that particular processor. OpenBLAS, as MKL, uses different code paths for different processors.

Also, our Mac packages already use OpenBLAS. Do they seem that slow? :D So @borondics, no change for Mac users.

**Comment by stuart-cls** [comment]
> It should only be 1 conda command, I think.

In principle, but I found that current environment created by the (test openblas) installer cannot be successfully switched back using `conda install blas=*=mkl`

> Other than a pretty steep performance hit on Intel processors

I ran some [benchmarks from this page](https://jwalton.info/Python-MKL-openBLAS/) earlier this week on mkl vs openblas with latest python etc from conda-forge on a 4 core intel CPU (Windows 10). All functions were within 10% except the np.linalg.inv (10x) and np.linalg.det (12x).

**Comment by borondics** [comment]
Ah! So maybe it could be faster on Macs? Speed is a relative thing...
