### ISSUE TITLE
Orange3-Text installation 

### ISSUE THREAD

**Issue by Shaimaai** [biolab/orange3#5142]
- [ ] **What's wrong?** I can not install "Text" from (Add-On option) on Orange3 
 
<img width="486" alt="Screen Shot 2020-12-21 at 8 03 01 PM" src="https://user-images.githubusercontent.com/75612098/102796374-99a1c200-43c7-11eb-82dc-558d92548e3c.png">

 '''Command failed: python python -m pip install Orange3-Text==1.2.0 exited with non zero status'''

- [ ] **How can we reproduce the problem?** 

- [ ] **What's your environment?**

- Operating system: MacBook Air
- Orange version:
<img width="540" alt="Screen Shot 2020-12-21 at 8 05 22 PM" src="https://user-images.githubusercontent.com/75612098/102796631-fe5d1c80-43c7-11eb-81c7-36bfd85b7faf.png">

- How you installed Orange:  Orange website

**Comment by ajdapretnar** [comment]
Please add the log from "Show Details" button. Also let us know what is you OS version: High Sierra, Catalina, Big Sur,...

**Comment by Shaimaai** [comment]
> Please add the log from "Show Details" button. Also let us know what is you OS version: High Sierra, Catalina, Big Sur,...

Show Details: (below)

Collecting Orange3-Text==1.2.0
  Using cached https://files.pythonhosted.org/packages/64/9c/893738f0de1f44bb9445581a6a10e2fbe68b6946c15851a9b25a9c1332d7/Orange3_Text-1.2.0-py3-none-any.whl
ERROR: Could not install packages due to an EnvironmentError: [Errno 28] No space left on device

WARNING: You are using pip version 19.2.3, however version 20.3.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

OS Version:
<img width="572" alt="Screen Shot 2020-12-21 at 8 25 32 PM" src="https://user-images.githubusercontent.com/75612098/102798747-f3f05200-43ca-11eb-93e2-d382d338b751.png">

**Comment by Shaimaai** [comment]
Collecting Orange3-Text==1.2.0
  Using cached https://files.pythonhosted.org/packages/64/9c/893738f0de1f44bb9445581a6a10e2fbe68b6946c15851a9b25a9c1332d7/Orange3_Text-1.2.0-py3-none-any.whl
Collecting nltk<3.5,>=3.0.5 (from Orange3-Text==1.2.0)
Collecting lxml (from Orange3-Text==1.2.0)
  Using cached https://files.pythonhosted.org/packages/94/59/f44a83ea47c42af27e3afef9ee2a0a1a38f466d507dc568400537926b185/lxml-4.6.2-cp37-cp37m-macosx_10_9_x86_64.whl
Collecting biopython (from Orange3-Text==1.2.0)
  Using cached https://files.pythonhosted.org/packages/19/d9/3d21749fd4cee79f2c1b12cd577ffba458d8c529e13553e7cca6ae6d47aa/biopython-1.78-cp37-cp37m-macosx_10_9_x86_64.whl
Collecting pdfminer3k>=1.3.1 (from Orange3-Text==1.2.0)
  Using cached https://files.pythonhosted.org/packages/36/15/5ac4faa314c38b335cf4db37fc02dc02c14bf67f7641bea2fa5e5b7d4ff4/pdfminer3k-1.3.4-py3-none-any.whl
Requirement already satisfied: numpy in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from Orange3-Text==1.2.0) (1.19.4)
Requirement already satisfied: python-dateutil<3.0.0 in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from Orange3-Text==1.2.0) (2.8.1)
Requirement already satisfied: scikit-learn in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from Orange3-Text==1.2.0) (0.23.2)
Collecting docx2txt>=0.6 (from Orange3-Text==1.2.0)
Collecting beautifulsoup4 (from Orange3-Text==1.2.0)
  Using cached https://files.pythonhosted.org/packages/d1/41/e6495bd7d3781cee623ce23ea6ac73282a373088fcd0ddc809a047b18eae/beautifulsoup4-4.9.3-py3-none-any.whl
Requirement already satisfied: scipy in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from Orange3-Text==1.2.0) (1.5.4)
Collecting odfpy>=1.3.5 (from Orange3-Text==1.2.0)
Collecting ufal.udpipe>=1.2.0.3 (from Orange3-Text==1.2.0)
  Using cached https://files.pythonhosted.org/packages/7c/67/1c5e96cd59bc30390817b414a58848f2b9e0941d60cc76ef5da51675e867/ufal.udpipe-1.2.0.3-cp37-cp37m-macosx_10_6_intel.whl
Requirement already satisfied: Orange3>=3.25.0 in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from Orange3-Text==1.2.0) (3.27.1)
Collecting tweepy (from Orange3-Text==1.2.0)
  Using cached https://files.pythonhosted.org/packages/bb/7c/99d51f80f3b77b107ebae2634108717362c059a41384a1810d13e2429a81/tweepy-3.9.0-py2.py3-none-any.whl
Collecting wikipedia (from Orange3-Text==1.2.0)
Collecting gensim>=0.12.3 (from Orange3-Text==1.2.0)
  Using cached https://files.pythonhosted.org/packages/70/cf/87b25b265d23498b2b70ce873495cf7ef91394c4baff240210e26f3bc18a/gensim-3.8.3-cp37-cp37m-macosx_10_9_x86_64.whl
Collecting setuptools-git (from Orange3-Text==1.2.0)
  Using cached https://files.pythonhosted.org/packages/05/97/dd99fa9c0d9627a7b3c103a00f1566d8193aca8d473884ed258cca82b06f/setuptools_git-1.2-py2.py3-none-any.whl
Collecting simhash>=1.11 (from Orange3-Text==1.2.0)
  Using cached https://files.pythonhosted.org/packages/76/f8/65a885dd8615c6e241f6ff24e9479bba5bce2bd966aa4f71d772e3a65a19/simhash-2.0.0-py3-none-any.whl
Requirement already satisfied: six in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from nltk<3.5,>=3.0.5->Orange3-Text==1.2.0) (1.15.0)
Collecting ply (from pdfminer3k>=1.3.1->Orange3-Text==1.2.0)
  Using cached https://files.pythonhosted.org/packages/a3/58/35da89ee790598a0700ea49b2a66594140f44dec458c07e8e3d4979137fc/ply-3.11-py2.py3-none-any.whl
Requirement already satisfied: joblib>=0.11 in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from scikit-learn->Orange3-Text==1.2.0) (0.11)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from scikit-learn->Orange3-Text==1.2.0) (2.1.0)
Collecting soupsieve>1.2; python_version >= "3.0" (from beautifulsoup4->Orange3-Text==1.2.0)
  Using cached https://files.pythonhosted.org/packages/02/fb/1c65691a9aeb7bd6ac2aa505b84cb8b49ac29c976411c6ab3659425e045f/soupsieve-2.1-py3-none-any.whl
Collecting defusedxml (from odfpy>=1.3.5->Orange3-Text==1.2.0)
  Using cached https://files.pythonhosted.org/packages/06/74/9b387472866358ebc08732de3da6dc48e44b0aacd2ddaa5cb85ab7e986a2/defusedxml-0.6.0-py2.py3-none-any.whl
Requirement already satisfied: xlrd>=0.9.2 in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from Orange3>=3.25.0->Orange3-Text==1.2.0) (1.2.0)
Requirement already satisfied: baycomp>=1.0.2 in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from Orange3>=3.25.0->Orange3-Text==1.2.0) (1.0.2)
Requirement already satisfied: docutils in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from Orange3>=3.25.0->Orange3-Text==1.2.0) (0.16)
Requirement already satisfied: bottleneck>=1.0.0 in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from Orange3>=3.25.0->Orange3-Text==1.2.0) (1.3.2)
Requirement already satisfied: requests in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from Orange3>=3.25.0->Orange3-Text==1.2.0) (2.25.0)
Requirement already satisfied: pandas in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from Orange3>=3.25.0->Orange3-Text==1.2.0) (1.1.4)
Requirement already satisfied: networkx in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from Orange3>=3.25.0->Orange3-Text==1.2.0) (2.5)
Requirement already satisfied: setuptools>=36.3 in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from Orange3>=3.25.0->Orange3-Text==1.2.0) (41.2.0)
Requirement already satisfied: matplotlib>=2.0.0 in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from Orange3>=3.25.0->Orange3-Text==1.2.0) (3.3.3)
Requirement already satisfied: httpx~=0.14.0 in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from Orange3>=3.25.0->Orange3-Text==1.2.0) (0.14.3)
Requirement already satisfied: openpyxl in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from Orange3>=3.25.0->Orange3-Text==1.2.0) (3.0.5)
Requirement already satisfied: AnyQt>=0.0.11 in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from Orange3>=3.25.0->Orange3-Text==1.2.0) (0.0.11)
Requirement already satisfied: xlsxwriter in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from Orange3>=3.25.0->Orange3-Text==1.2.0) (1.3.7)
Requirement already satisfied: pip>=9.0 in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from Orange3>=3.25.0->Orange3-Text==1.2.0) (19.2.3)
Requirement already satisfied: keyrings.alt in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from Orange3>=3.25.0->Orange3-Text==1.2.0) (2.2)
Requirement already satisfied: openTSNE>=0.4.3 in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from Orange3>=3.25.0->Orange3-Text==1.2.0) (0.4.4)
Requirement already satisfied: PyQtWebEngine>=5.12 in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from Orange3>=3.25.0->Orange3-Text==1.2.0) (5.12.1)
Requirement already satisfied: python-louvain>=0.13 in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from Orange3>=3.25.0->Orange3-Text==1.2.0) (0.14)
Requirement already satisfied: orange-widget-base>=4.8.1 in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from Orange3>=3.25.0->Orange3-Text==1.2.0) (4.9.0)
Requirement already satisfied: pyqtgraph>=0.11.0 in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from Orange3>=3.25.0->Orange3-Text==1.2.0) (0.11.0)
Requirement already satisfied: PyQt5!=5.15.1,>=5.12 in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from Orange3>=3.25.0->Orange3-Text==1.2.0) (5.12.2)
Requirement already satisfied: chardet>=3.0.2 in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from Orange3>=3.25.0->Orange3-Text==1.2.0) (3.0.4)
Requirement already satisfied: serverfiles in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from Orange3>=3.25.0->Orange3-Text==1.2.0) (0.3.0)
Requirement already satisfied: pyyaml in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from Orange3>=3.25.0->Orange3-Text==1.2.0) (5.3.1)
Requirement already satisfied: orange-canvas-core<0.2a,>=0.1.18 in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from Orange3>=3.25.0->Orange3-Text==1.2.0) (0.1.18)
Requirement already satisfied: keyring in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from Orange3>=3.25.0->Orange3-Text==1.2.0) (10.3.1)
Collecting requests-oauthlib>=0.7.0 (from tweepy->Orange3-Text==1.2.0)
  Using cached https://files.pythonhosted.org/packages/a3/12/b92740d845ab62ea4edf04d2f4164d82532b5a0b03836d4d4e71c6f3d379/requests_oauthlib-1.3.0-py2.py3-none-any.whl
Collecting smart-open>=1.8.1 (from gensim>=0.12.3->Orange3-Text==1.2.0)
Requirement already satisfied: certifi>=2017.4.17 in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests->Orange3>=3.25.0->Orange3-Text==1.2.0) (2020.11.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests->Orange3>=3.25.0->Orange3-Text==1.2.0) (1.26.2)
Requirement already satisfied: idna<3,>=2.5 in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests->Orange3>=3.25.0->Orange3-Text==1.2.0) (2.10)
Requirement already satisfied: pytz>=2017.2 in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pandas->Orange3>=3.25.0->Orange3-Text==1.2.0) (2020.4)
Requirement already satisfied: decorator>=4.3.0 in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from networkx->Orange3>=3.25.0->Orange3-Text==1.2.0) (4.4.2)
Requirement already satisfied: cycler>=0.10 in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from matplotlib>=2.0.0->Orange3>=3.25.0->Orange3-Text==1.2.0) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from matplotlib>=2.0.0->Orange3>=3.25.0->Orange3-Text==1.2.0) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from matplotlib>=2.0.0->Orange3>=3.25.0->Orange3-Text==1.2.0) (1.3.1)
Requirement already satisfied: pillow>=6.2.0 in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from matplotlib>=2.0.0->Orange3>=3.25.0->Orange3-Text==1.2.0) (8.0.1)
Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from httpx~=0.14.0->Orange3>=3.25.0->Orange3-Text==1.2.0) (1.4.0)
Requirement already satisfied: sniffio in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from httpx~=0.14.0->Orange3>=3.25.0->Orange3-Text==1.2.0) (1.2.0)
Requirement already satisfied: httpcore==0.10.* in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from httpx~=0.14.0->Orange3>=3.25.0->Orange3-Text==1.2.0) (0.10.2)
Requirement already satisfied: et-xmlfile in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from openpyxl->Orange3>=3.25.0->Orange3-Text==1.2.0) (1.0.1)
Requirement already satisfied: jdcal in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from openpyxl->Orange3>=3.25.0->Orange3-Text==1.2.0) (1.4.1)
Requirement already satisfied: appnope; sys_platform == "darwin" in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from orange-widget-base>=4.8.1->Orange3>=3.25.0->Orange3-Text==1.2.0) (0.1.0)
Requirement already satisfied: PyQt5_sip<13,>=4.19.14 in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from PyQt5!=5.15.1,>=5.12->Orange3>=3.25.0->Orange3-Text==1.2.0) (12.8.1)
Requirement already satisfied: dictdiffer in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from orange-canvas-core<0.2a,>=0.1.18->Orange3>=3.25.0->Orange3-Text==1.2.0) (0.8.1)
Requirement already satisfied: commonmark>=0.8.1 in 
Also when I fixed the [ erron 28] I got the following issue!


/Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from orange-canvas-core<0.2a,>=0.1.18->Orange3>=3.25.0->Orange3-Text==1.2.0) (0.9.1)
Requirement already satisfied: cachecontrol[filecache] in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from orange-canvas-core<0.2a,>=0.1.18->Orange3>=3.25.0->Orange3-Text==1.2.0) (0.12.6)
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->tweepy->Orange3-Text==1.2.0)
  Using cached https://files.pythonhosted.org/packages/05/57/ce2e7a8fa7c0afb54a0581b14a65b56e62b5759dbc98e80627142b8a3704/oauthlib-3.1.0-py2.py3-none-any.whl
Requirement already satisfied: h11<0.10,>=0.8 in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from httpcore==0.10.*->httpx~=0.14.0->Orange3>=3.25.0->Orange3-Text==1.2.0) (0.9.0)
Requirement already satisfied: msgpack>=0.5.2 in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from cachecontrol[filecache]->orange-canvas-core<0.2a,>=0.1.18->Orange3>=3.25.0->Orange3-Text==1.2.0) (1.0.0)
Requirement already satisfied: lockfile>=0.9; extra == "filecache" in /Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from cachecontrol[filecache]->orange-canvas-core<0.2a,>=0.1.18->Orange3>=3.25.0->Orange3-Text==1.2.0) (0.12.2)
Installing collected packages: nltk, lxml, biopython, ply, pdfminer3k, docx2txt, soupsieve, beautifulsoup4, defusedxml, odfpy, ufal.udpipe, oauthlib, requests-oauthlib, tweepy, wikipedia, smart-open, gensim, setuptools-git, simhash, Orange3-Text
ERROR: Could not install packages due to an EnvironmentError: [Errno 30] Read-only file system: '/Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nltk-3.4.5.dist-info'

WARNING: You are using pip version 19.2.3, however version 20.3.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by PrimozGodec** [comment]
Hi, it seems that something strange is happening on at your operating system since the first message is written
```
ERROR: Could not install packages due to an EnvironmentError: [Errno 28] No space left on device
```

Can you inspect how much space do you have left at your hard drive? You can see it if you open Disk utility at your MacBook. You can find it in Applications or in Launchpad.

**Comment by Shaimaai** [comment]
I did, and the problem was: I should run it from the Desktop not from
Application.

Thanks a lot for your help, I really appreciate it.

**Comment by markotoplak** [comment]
I helped this user on Discord, and in the end we discovered that Orange was being run from the dmg.

They have been problems like this before, perhaps we could try detecting that Orange is run from the dmg and display a very specific error message. Now there was warning that permissions are insufficient for installation of add-ons, but users seem to ignore that one.

**Comment by ajdapretnar** [comment]
> perhaps we could try detecting that Orange is run from the dmg and display a very specific error message

Agree.
