### ISSUE TITLE
Max 1 target variable per domain

### ISSUE THREAD

**Issue by irgolic** [biolab/orange3#5144]
- [ ] **What's your use case?**

I'm a new user, and I'm picking up data mining as I go. I don't know what meta attributes are, and I'm not quite sure what a target variable is. Can I set multiple target variables? 
Upon doing so and connecting a model, a `Data has no target variable` error appears. Confusing. Rank displays `Data does not have a (single) target variable`, slightly better.

- [ ] **What's your proposed solution?**

Limit the number of target variables to one. If a new target variable is set, set the previous one to the role it previously played. Make sure this behavior is reflected in the file loading widget's domain editor and Select Columns. Make the Select Columns box 'target variable' box smaller, to fit one variable.

- [ ] **Are there any alternative solutions?**

Better, unified error messages.

**Comment by janezd** [comment]
Select columns and File will warn against multiple target variables.

Warning like the one above need to be made clearer.
