### ISSUE TITLE
OWTestAndScore: Copy/paste-able model information

### ISSUE THREAD

**Issue by irgolic** [biolab/orange3#5161]
- [ ] **What's your use case?**

I wanted to copy and paste that into a google doc or into anything.

- [ ] **What's your proposed solution?**

Make it possible to select models in the table, and copy them, loading tab-separated text into the clipboard.

- [ ] **Are there any alternative solutions?**

N/A

**Comment by janezd** [comment]
The alternative is to copy from report.

I support the suggestion, though.

**Comment by janezd** [comment]
Closed via #5203.
