### ISSUE TITLE
OWTable: Data table freezes with Ctrl+A on a big data set

### ISSUE THREAD

**Issue by irgolic** [biolab/orange3#5162]
- [ ] **What's wrong?**

(according to my understanding) Due to how selection is stored (each data instance individually), selecting a lot of points leads to a big .ows file, and is also very slow. 

How CSVFileImport works is, it stores ranges. Could selection be saved as a list of ranges too? You could identify rows by their global identifier.

- [ ] **How can we reproduce the problem?** 

Connect `Datasets -> Data Table`
Download `poker-hand`
Open Data Table, press Ctrl+A (CMD+A)

Orange will freeze for a solid minute.

- [ ] **What's your environment?**

- Operating system: OS X
- Orange version: 3.27.1
- How you installed Orange: Installer

**Comment by ales-erjavec** [comment]
I don't think this is related to how selection is stored. I think this is a Qt regression in QHeaderView.paintSection (it works quite fast on Qt 5.9).
