### ISSUE TITLE
Widget documentation missing for BarPlot

### ISSUE THREAD

**Issue by kaimikael** [biolab/orange3#5169]
- [ ] **What's wrong?**

If I click on the ? icon on a Bar Plot widget, I get the error message ```There is no documentation for this widget.```

- [ ] **How can we reproduce the problem?** 

As above.

- [ ] **What's your environment?**

- Operating system: macOS 11.1
- Orange version: 3.27.1
- How you installed Orange: Downloaded the disk image from https://orange.biolab.si/download/#macos

**Comment by ajdapretnar** [comment]
I have the same issue on OSX. I have removed Orange and installed it anew. No changes.
Bar plot is correctly listed in index.rst. Documentation builds locally without problems.

**Comment by ajdapretnar** [comment]
Issue: Bar Plot not in https://orange3.readthedocs.io/projects/orange-visual-programming/en/latest/. Check which branch is being pull for doc builds.

**Comment by ajdapretnar** [comment]
Debugged: Bar Plot was added to index.rst after the release (3.27.1). This is why it doesn't appear in the docs. Once the new release is out, Bar Plot will appear as well. This is why it is important to handle the docs properly at each new widget. ;)
