### ISSUE TITLE
Feature Statistics: put controls above main area

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#5173]
Feature Statistics has a large control area to the left. It only has one setting + apply button.

Remove control area. Put controls below the widget (similar to Venn Diagram).

**Comment by irgolic** [comment]
I know we did this with Venn, but should we really be doing this?

- Vertical space is usually more valuable than horizontal space,
- The control area can always be collapsed,
- It breaks OW standards (controls to the left, viz to the right).

If we decide to do this for all widgets with not a lot of controls, we should make it a feature – making it collapsible and easily settable as a GUI layout options.

**Comment by ajdapretnar** [comment]
TBH, Venn is not the only widget like that. File and Datasets are kindaaa like that, but I would say Correlations, Create Instance, Sieve Diagram, Distance Matrix are exactly like that.

You say yourself that vertical space is more valuable than horizontal? So what not make the most of it and move the single control at the top?

I agree, that collapsability is something that would not be fully supported with this option (yet).

**Comment by janezd** [comment]
As much as I don't like the current layout, neither of these two is to die for. Nicer than before, though. Comments?

<img width="803" alt="Screenshot 2021-01-29 at 14 09 00" src="https://user-images.githubusercontent.com/2387315/106278934-e0db6800-623b-11eb-8589-3538061fe39d.png">

<img width="779" alt="Screenshot 2021-01-29 at 14 10 57" src="https://user-images.githubusercontent.com/2387315/106278939-e33dc200-623b-11eb-8de1-01a1c1ea2105.png">

**Comment by janezd** [comment]
On top isn't so bad, though.

<img width="882" alt="Screenshot 2021-01-29 at 14 17 38" src="https://user-images.githubusercontent.com/2387315/106279502-c786eb80-623c-11eb-8dc6-d76eab430a29.png">

**Comment by ajdapretnar** [comment]
I actually like the second one best. 😆 UI is just hard.

**Comment by janezd** [comment]
If you like the second one, what about this one? (Top, no box.)

<img width="823" alt="Screenshot 2021-01-29 at 14 35 30" src="https://user-images.githubusercontent.com/2387315/106281265-48df7d80-623f-11eb-861f-3c11152fd29c.png">
