### ISSUE TITLE
Big margin above the apply button 

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#5174]
- [x] **What's wrong?**

As reported by @markotoplak in #5167,

> There is a big margin before the last button on my Linux machine, but I am OK with it.

![image](https://user-images.githubusercontent.com/552182/104027104-37b6ca00-51c7-11eb-8fbe-1a4778ba8471.png)

This is not an issue only with this widget, but also (some?) others. See #5167 for details.

- [X] **How can we reproduce the problem?** 
- [X] **What's your environment?**

@markotoplak noticed this on his linux machine, but I believe I've seen this on my mac some time ago, too.

**Comment by janezd** [comment]
@irgolic, will this be resolved by your changes? (@markotoplak?)

**Comment by irgolic** [comment]
https://github.com/biolab/orange-widget-base/pull/130 might fix it. If not, https://github.com/biolab/orange-widget-base/pull/128 surely will.

**Comment by janezd** [comment]
@markotoplak, can you check whether the recent commits in orange-widget-base solved this?

**Comment by markotoplak** [comment]
Looks sweet now (new widget-base, refactor-to-buttonsArea).

![image](https://user-images.githubusercontent.com/552182/108528892-31dafb00-72d4-11eb-846b-1b6638b59d55.png)
