### ISSUE TITLE
Expectation in Distribution Node ?

### ISSUE THREAD

**Issue by leaf918** [biolab/orange3#5175]
- [ ] **What's your use case?**

The distribution node is good ,and the bell curve is good too.

- [ ] **What's your proposed solution?**

Well,in some cases,I want to get the expection value from the bell curve or the raw data .Can you support it please?

- [ ] **Are there any alternative solutions?**

Thanks.

**Comment by janezd** [comment]
Can you be more specific? I suppose you are talking about the Distributions widget. *When* would you like to see the expected value of *what*?

Note that hovering over  the plot's elements already gives a lot of additional information.

**Comment by janezd** [comment]
Closed due to inactivity. Reopen if needed.
