### ISSUE TITLE
save data got "continues" instead of the actual data

### ISSUE THREAD

**Issue by DaiZack** [biolab/orange3#5200]
- Operating system: Win 10
- Orange version: 3.27.1
- How you installed Orange: standalone

I created a data table after a topic analysis (LDA) node outputting "all topics". When using ".xlsx", got no output file and when using '.csv' got only the column names with one row all "continuous".
like:

fodder_NN for_IN | follow_VB please_NN | followed_VBN | followed_VBN by_IN | followed_VBN sweden_JJ
-- | -- | -- | -- | --
continuous | continuous | continuous | continuous | continuous

PS: when saving the default datasets like iris data, it worked well.

**Comment by ajdapretnar** [comment]
Would you mind attaching a screenshot of your workflow? Thanks!

**Comment by DaiZack** [comment]
![image](https://user-images.githubusercontent.com/45176371/105048702-d948e180-5a39-11eb-8ee9-48735bb93f3e.png)

**Comment by ajdapretnar** [comment]
Well, you most likely haven't selected anything in the Data Table. Data Table is a visualization, it only outputs selected data instances.

**Comment by DaiZack** [comment]
I chose this data flow option, won't it pick all data?
![image](https://user-images.githubusercontent.com/45176371/105049062-43618680-5a3a-11eb-95db-b1015259dc9e.png)
![image](https://user-images.githubusercontent.com/45176371/105048961-29c03f00-5a3a-11eb-8130-1bf342c5451d.png)

**Comment by ajdapretnar** [comment]
Ah, right. I missed this detail. It does. But I would still encourage you to avoid Data Table in between.

**Comment by DaiZack** [comment]
BTW if I connect the save data to topic node directly, it yields the same result.
![image](https://user-images.githubusercontent.com/45176371/105049403-9b988880-5a3a-11eb-813e-3898269ceecc.png)
![image](https://user-images.githubusercontent.com/45176371/105049439-a3f0c380-5a3a-11eb-9e89-52e0bacbf84a.png)

**Comment by ajdapretnar** [comment]
Could be there's an error, but it is not displaying for you? What do you see, when you open log (View - Log)?

**Comment by ajdapretnar** [comment]
Probably will be fixed with: https://github.com/biolab/orange3-text/pull/615

**Comment by ajdapretnar** [comment]
@DaiZack Could you test this with the new version of Text add-on?

**Comment by DaiZack** [comment]
@ajdapretnar Yes the 1.3.1 text add-on works well. Thank you!
