### ISSUE TITLE
Error in installing orange 3.27

### ISSUE THREAD

**Issue by ayushgarg99** [biolab/orange3#5211]
![Untitled](https://user-images.githubusercontent.com/70329317/105972244-6d0d5400-60b1-11eb-96e1-a13b2576caad.jpg)
![Untitled](https://user-images.githubusercontent.com/70329317/105972354-8b734f80-60b1-11eb-8a0f-f81fce1b3a6d.png)

i m having multiple errors while installing orange software even though no such error occurred on another same laptop  .
can anyone plz tell how to resolve this issue?

**Comment by ajdapretnar** [comment]
Would you be able to copy-paste the entire error log here, please?

**Comment by janezd** [comment]
Closed due to inactivity.

**Comment by ayushgarg99** [comment]
I m not able to copy paste the log error .
So i have two screenshots of those error.
[image: 1.png][image: 2.png]

**Comment by janezd** [comment]
Images don't show. Can you upload them through the web interface?
