### ISSUE TITLE
"Color Density" should ignore category "Other"

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#5213]
I suppose this is unwanted. Data instances belonging to "Other" should probably be ignored.

To replicate, use any data with large number of categories, in which those belonging to the less frequent ones are in the majority. The below example is the network for last_fm.

![x](https://user-images.githubusercontent.com/2387315/105985604-f580fa00-609b-11eb-81cc-4466c7ff2c6e.png)

**Comment by ajdapretnar** [comment]
Ah, you a right! Can confirm, it is undesired.
