### ISSUE TITLE
Violin Plot

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3#5215]
Following is a proposal for a new widget that displays the violin plot. Notice that the widget has a resemblance to Box Plot, and is indeed an alternative way to show variable distributions. The need for the widget was raised by several important collaborators, including Genialis, and hence this issue and proposal for the creation of the widget.

![image](https://user-images.githubusercontent.com/726604/106121316-bc0dc480-6157-11eb-8e0c-0186207fa6f9.png)

- Variable and Subgroups panes are exactly like those in the Box Plot
- Box plot, Strip plot and Rug plot options trigger additional display of box plot, strip plot and rug plot. If shown together, box plot is on top, and strip plot is on the bottom. See a [guide](https://chartio.com/learn/charts/violin-plot-complete-guide/) for these kind of displays, and use the display style similar to that of [seaborn](https://seaborn.pydata.org/generated/seaborn.violinplot.html). The defaults are as shown in the figure above.
- Ordering subgroups orders the subgroup plot by increasing mean. See also the [guide](https://chartio.com/learn/charts/violin-plot-complete-guide/). This check box is disabled if Subgroups=None.
- Orientation can be vertical or horizontal. See example charts in [seaborn](https://seaborn.pydata.org/generated/seaborn.violinplot.html).
- Density estimations can use "Normal kernel", "Epanechnikov kernel" or "Triangular kernel". In the first approximation of the widget, this could be omitted and a default normal kernel could be used insted.

It would be great if the widget could support data selection. If only one violin is shown, than dragging over the violin can mark a variable range and selected the corresponding data points. If, in case of the subgroups, several violins are displayed, then the user can drag over plots that display the distributions for various subgroups, and modifier keys should be used to select data points from two or more subgroups.

**Comment by BlazZupan** [comment]
There is a violin plot already in the Filter widget in single-cell add-on, so this could be used as an example as well.

**Comment by VesnaT** [comment]
![image](https://user-images.githubusercontent.com/11465003/107034015-661fc900-67b6-11eb-8d9b-a105677a27a4.png)

![image](https://user-images.githubusercontent.com/11465003/107034053-759f1200-67b6-11eb-8489-0f1dafdd3d7f.png)
