### ISSUE TITLE
Fix expanding control areas

### ISSUE THREAD

**Issue by irgolic** [biolab/orange3#5225]
The left side scrolling PR broke some widget UIs, particularly those with listboxes that expand for the height of the controlArea.

This is fixed by setting
```
# stretch over buttonsArea
self.left_side.layout().setStretch(0, 9999999)
```
in all such widgets.

Non-exthustive list:
- box plot
- linear projection
- radviz

**Comment by markotoplak** [comment]
What if we added this to the base widget instead? Isn't that what we'd like in general? Do you foresee any problems in doing that?

I add another widget to the non-exhaustive list:
- spectroscopy / preprocess spectra
