### ISSUE TITLE
Allow drawing of scatterplot matrices

### ISSUE THREAD

**Issue by GMTSE** [biolab/orange3#5229]
- [ ] **What's your use case?**

The first thing I generally do when I acquire a new dataset is to plot a scatterplot matrix, in order to quickly discover any interesting things (too much NAs, strong attributes correlations, abnormalities/outliers, ...).

Unfortunately Orange  (3.27.1 with most plugins installed) does not seem to offer this possibility.

- [ ] **What's your proposed solution?**

There are several easy ways to build/display scatterplot matrices in Python/Pandas/Seaborn:
https://pandas.pydata.org/pandas-docs/stable/user_guide/visualization.html#scatter-matrix-plot
https://seaborn.pydata.org/examples/scatterplot_matrix.html

Would be great to make one of them accessible from the Orange GUI.

Thanks for the great tool!

**Comment by janezd** [comment]
We discussed this suggestion at today's core group's meeting.

Scatterplot matrices have been proposed and discussed before. They indeed look nice for four, maybe six variables, less so for more. For more, Orange has tools for automated search for interesting scatterplot and other projections, which serve a similar purpose.

There is no particular reason for not including scatter plot matrices in Orange but implementing them nicely is not trivial. None of core developers found them attractive enough to dedicate his time and energy - at least not now. If anybody from the community is ready to contribute, it would be great.

Suggestions that are not rejected, but represent a larger non-priority projects are collected in #4090, so I'm moving this one there.

**Comment by irgolic** [comment]
Also very soon you'll be able to easily do stuff like this in Python Script.
