### ISSUE TITLE
I'm having an error trying to install TEXT and Image Analysis Add Ons on Orange3

### ISSUE THREAD

**Issue by DadsValencia** [biolab/orange3#5234]
Command failed: python python -m pip install Orange3-Text exited with non zero status.

- [ ] **What's wrong?**

- [ ] **How can we reproduce the problem?** 

- [ ] **What's your environment?**

- Operating system: Mac OS El Capitan 10.11.6
- Orange version: Orange 3.22
- How you installed Orange: Got the old version from the orange website

**Comment by ajdapretnar** [comment]
Orange 3.22 is very old. How about updating it and trying to installed the add-on then?

**Comment by janezd** [comment]
Updates are not compatible with such old versions of Orange. But if you have a specific reason for still using Orange 3.22 (it has something you need? behaves differently from later versions?), please explain why.
