### ISSUE TITLE
Widget size tests measure physical resolution instead of logical

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#5235]
- [x] **What's wrong?**

The following widget is accused of being too wide on Windows.

Namely, it is said to have a width of 899. By the way of personal observation on my Mac, I discovered it to have a logical width of 447 pixels and a physical width of 894 pixels, which is close to what the tests report on Windows. This leads me to believe that tests incorrectly measure the logical width and therefore force us into widths that are half of what we considered permissible when creating the tests. To this I object.

I'm looking forward to resolution of this problem.

<img width="447" alt="Screenshot 2021-02-04 at 11 30 43" src="https://user-images.githubusercontent.com/2387315/106880632-e07c1a80-66dc-11eb-978b-8216b9c5c848.png">

- [x] **How can we reproduce the problem?** 

See https://github.com/biolab/orange3-network/pull/192.

- [x] **What's your environment?**

Our Windows tests on github actions.

**Comment by markotoplak** [comment]
That happens if the person who wrote the test has only low-dpi screens... :)

**Comment by janezd** [comment]
... and doesn't use Windows.

**Comment by PrimozGodec** [comment]
It looks clear. On my Retina screen widget's logical size is around 450px and physical size is around 900px. `minimumSizeHint` which is used in `test_minimum_size` return the number around 450px. I get similar numbers on Windows. 

The real issue is described and "fixed" here https://github.com/biolab/orange3-network/pull/197

**Comment by janezd** [comment]
Thanks!

There are no similar problems on other add-ons (or have they've been fixed and I've missed it?) and in this repo? So this issue can be closed?

**Comment by PrimozGodec** [comment]
Similar issues happened on Educational https://github.com/biolab/orange3-educational/pull/100. There I temporarily disabled `test_minimum_size`. I will try to enable them again but I think that the reason is the same.
