### ISSUE TITLE
Add "not contains" operator to Select Rows widget

### ISSUE THREAD

**Issue by alejodan** [biolab/orange3#5254]
- [ ] **What's your use case?**

I want to start from the same corpus to process different subsets of data. On the one hand, I want to process the rows that contain a certain string, and on the other hand I want to process the rows that DO NOT contain that string.

In order to do the second part, I need to exclude the lines from my corpus using the Select Rows widget, but I don't have a "not contains" operator.

- [ ] **What's your proposed solution?**

Add the "not contains" operator to Select Rows widget.

- [ ] **Are there any alternative solutions?**
My current solution is to have the data partitioned into two different files, using a widget corpus for each.

**Comment by janezd** [comment]
Select Rows has an additonal output "Unmatched Data". Does it solve your problem?

**Comment by alejodan** [comment]
Ok! I was just looking inside the widget and didn't see that option.
That solves it.
Thank you very much!

Regards,
Alejandro Rossi

ᐧ

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
