### ISSUE TITLE
"conda" command exited with error. Cannot continue.

### ISSUE THREAD

**Issue by GGuillemin** [biolab/orange3#5259]
- [ ] **What's wrong?**

During installation of Orange3-3.27.1-Miniconda-x86_64.exe (64 bit) In Win 10
I am getting the following error
"conda" command exited with error. Cannot continue.

- [ ] **How can we reproduce the problem?** 

Here is a transcript of the installation 
Creating an new conda env in "C:\Users\gguillem\AppData\Local\Programs\Orange"
Output folder: C:\Users\gguillem\AppData\Local\Temp\nsz36BA.tmp\Orange-installer-data\conda-pkgs
Extract: anyqt-0.0.11-pyh9f0ad1d_0.tar.bz2
Extract: baycomp-1.0.2-py_1.tar.bz2
Extract: blas-1.0-mkl.tar.bz2
Extract: bottleneck-1.3.2-py37h2a96729_1.tar.bz2
Extract: brotlipy-0.7.0-py37he774522_1000.tar.bz2
Extract: ca-certificates-2020.10.14-0.tar.bz2
Extract: cachecontrol-0.12.6-py_0.tar.bz2
Extract: certifi-2020.6.20-py37_0.tar.bz2
Extract: cffi-1.14.3-py37h7a1dbc1_0.tar.bz2
Extract: chardet-3.0.4-py37_1003.tar.bz2
Extract: commonmark-0.9.1-py_0.tar.bz2
Extract: conda-spec.txt
Extract: cryptography-3.1.1-py37h7a1dbc1_0.tar.bz2
Extract: cycler-0.10.0-py37_0.tar.bz2
Extract: decorator-4.4.2-py_0.tar.bz2
Extract: dictdiffer-0.8.0-py_0.tar.bz2
Extract: docutils-0.16-py37_1.tar.bz2
Extract: et_xmlfile-1.0.1-py_1001.tar.bz2
Extract: freetype-2.10.4-hd328e21_0.tar.bz2
Extract: future-0.18.2-py37_1.tar.bz2
Extract: h11-0.9.0-py_0.tar.bz2
Extract: h2-3.2.0-py37_1.tar.bz2
Extract: hpack-3.0.0-py37h28b3542_0.tar.bz2
Extract: httpcore-0.10.1-py_0.tar.bz2
Extract: httpx-0.14.3-py_0.tar.bz2
Extract: hyperframe-5.2.0-py_0.tar.bz2
Extract: icc_rt-2019.0.0-h0cc432a_1.tar.bz2
Extract: icu-67.1-h33f27b4_0.tar.bz2
Extract: idna-2.10-py_0.tar.bz2
Extract: importlib-metadata-2.0.0-py_1.tar.bz2
Extract: importlib_metadata-2.0.0-1.tar.bz2
Extract: install.bat
Extract: intel-openmp-2020.2-254.tar.bz2
Extract: jdcal-1.4.1-py_0.tar.bz2
Extract: joblib-0.17.0-py_0.tar.bz2
Extract: jpeg-9d-he774522_0.tar.bz2
Extract: keyring-21.4.0-py37_1.tar.bz2
Extract: keyrings.alt-4.0.0-py37_0.tar.bz2
Extract: kiwisolver-1.2.0-py37h74a9793_0.tar.bz2
Extract: libclang-10.0.1-default_hf44288c_1.tar.bz2
Extract: libpng-1.6.37-h2a8f88b_0.tar.bz2
Extract: libtiff-4.1.0-h56a325e_1.tar.bz2
Extract: llvmlite-0.34.0-py37h1a82afc_4.tar.bz2
Extract: lockfile-0.12.2-py37_0.tar.bz2
Extract: lz4-c-1.9.2-hf4a77e7_3.tar.bz2
Extract: matplotlib-base-3.3.2-py37hba9282a_0.tar.bz2
Extract: mkl-2020.2-256.tar.bz2
Extract: mkl-service-2.3.0-py37hb782905_0.tar.bz2
Extract: mkl_fft-1.2.0-py37h45dec08_0.tar.bz2
Extract: mkl_random-1.1.1-py37h47e9c7a_0.tar.bz2
Extract: msgpack-python-1.0.0-py37h74a9793_1.tar.bz2
Extract: networkx-2.5-py_0.tar.bz2
Extract: numba-0.51.2-py37hf9181ef_1.tar.bz2
Extract: numpy-1.16.6-py37h5510c5b_0.tar.bz2
Extract: numpy-base-1.16.6-py37hc3f5095_0.tar.bz2
Extract: olefile-0.46-py37_0.tar.bz2
Extract: openpyxl-3.0.5-py_0.tar.bz2
Extract: openssl-1.1.1h-he774522_0.tar.bz2
Extract: opentsne-0.4.3-py37h74a9793_1.tar.bz2
Extract: orange-canvas-core-0.1.18-py_0.tar.bz2
Extract: orange-widget-base-4.9.0-py_0.tar.bz2
Extract: orange3-3.27.1-py37h1834ac0_0.tar.bz2
Extract: pandas-1.1.3-py37ha925a31_0.tar.bz2
Extract: pillow-8.0.0-py37hca74424_0.tar.bz2
Extract: pip-20.2.4-py37_0.tar.bz2
Extract: pycparser-2.20-py_2.tar.bz2
Extract: pynndescent-0.4.8-py_1.tar.bz2
Extract: pyopenssl-19.1.0-py_1.tar.bz2
Extract: pyparsing-2.4.7-py_0.tar.bz2
Extract: pyqt-5.12.3-py37h1834ac0_4.tar.bz2
Extract: pyqtgraph-0.11.0-py_0.tar.bz2
Extract: pysocks-1.7.1-py37_1.tar.bz2
Extract: python-3.7.6-h60c2a47_2.tar.bz2
Extract: python-dateutil-2.8.1-py_0.tar.bz2
Extract: python-louvain-0.14-py_0.tar.bz2
Extract: python_abi-3.7-1_cp37m.tar.bz2
Extract: pytz-2020.1-py_0.tar.bz2
Extract: pywin32-ctypes-0.2.0-py37_1001.tar.bz2
Extract: pyyaml-5.3.1-py37he774522_1.tar.bz2
Extract: qt-5.12.9-hb2cf2c5_0.tar.bz2
Extract: requests-2.24.0-py_0.tar.bz2
Extract: rfc3986-1.4.0-py_0.tar.bz2
Extract: scikit-learn-0.23.2-py37h47e9c7a_0.tar.bz2
Extract: scipy-1.2.1-py37h29ff71c_0.tar.bz2
Extract: serverfiles-0.3.0-py37_0.tar.bz2
Extract: setuptools-50.3.0-py37h9490d1a_1.tar.bz2
Extract: sitecustomize.py
Extract: six-1.15.0-py_0.tar.bz2
Extract: sniffio-1.1.0-py37_2.tar.bz2
Extract: sqlite-3.33.0-h2a8f88b_0.tar.bz2
Extract: threadpoolctl-2.1.0-pyh5ca1d4c_0.tar.bz2
Extract: tk-8.6.10-he774522_0.tar.bz2
Extract: tornado-6.0.4-py37he774522_1.tar.bz2
Extract: urllib3-1.25.11-py_0.tar.bz2
Extract: vc-14.1-h0510ff6_4.tar.bz2
Extract: vs2015_runtime-14.16.27012-hf0eaf9b_3.tar.bz2
Extract: wheel-0.35.1-py_0.tar.bz2
Extract: win_inet_pton-1.1.0-py37_0.tar.bz2
Extract: wincertstore-0.2-py37_0.tar.bz2
Extract: xlrd-1.2.0-py37_0.tar.bz2
Extract: xlsxwriter-1.3.7-py_0.tar.bz2
Extract: xz-5.2.5-h62dcd97_0.tar.bz2
Extract: yaml-0.2.5-he774522_0.tar.bz2
Extract: zipp-3.3.1-py_0.tar.bz2
Extract: zlib-1.2.11-h62dcd97_4.tar.bz2
Extract: zstd-1.4.5-h04227a9_0.tar.bz2
Output folder: C:\Users\gguillem\AppData\Local\Temp\nsz36BA.tmp\Orange-installer-data\conda-pkgs
Installing packages (this might take a while)
Executing: cmd.exe /c install.bat "C:\Users\gguillem\AppData\Local\Programs\Orange" "C:\Users\gguillem\AppData\Local\Continuum\anaconda3\Scripts\conda.exe"
Creating a conda env in "C:\Users\gguillem\AppData\Local\Programs\Orange"

Downloading and Extracting Packages
           |   0%            |   0% ########## | 100% 
           |   0%            |   0% ########## | 100% 
           |   0%            |   0% 3          |   4% 7          |   7% 9          |   9% #2         |  12% #5         |  16% #9         |  20% ##3        |  23% ##6        |  27% ###        |  31% ###5       |  35% ####       |  40% ####4      |  44% ####7      |  47% #####1     |  51% #####5     |  56% #####9     |  60% ######3    |  63% ######6    |  66% ######9    |  70% #######3   |  74% #######7   |  77% ########1  |  81% ########5  |  85% ########8  |  89% #########1 |  92% #########4 |  95% #########7 |  97% ########## | 100% 
           |   0%            |   0% #6         |  16% ##         |  21% ###9       |  39% ####9      |  50% #####4     |  55% #####9     |  60% #######    |  70% ########   |  80% #########  |  90% ########## | 100% 
           |   0%            |   0% 4          |   5% #          |  11% ##2        |  22% ###3       |  33% ####5      |  45% #####9     |  59% #######7   |  77% #########  |  90% #########7 |  98% ########## | 100% 
           |   0%            |   0%            |   0%            |   0%            |   0%            |   1%            |   1% 1          |   1% 1          |   1% 1          |   1% 1          |   2% 1          |   2% 1          |   2% 2          |   2% 2          |   2% 2          |   3% 2          |   3% 2          |   3% 3          |   3% 3          |   3% 3          |   4% 3          |   4% 3          |   4% 4          |   4% 4          |   4% 4          |   5% 4          |   5% 5          |   5% 5          |   5% 5          |   5% 5          |   6% 5          |   6% 5          |   6% 6          |   6% 6          |   6% 6          |   7% 6          |   7% 6          |   7% 7          |   7% 7          |   7% 7          |   7% 7          |   7% 7          |   8ŀ䄀
"conda" command exited with error. Cannot continue.

- [ ] **What's your environment?**

- Operating system: Win 10
- Orange version: Orange3-3.27.1
- How you installed Orange:

**Comment by ales-erjavec** [comment]
Can you run `conda info` in your base anaconda environment and post the output?

**Comment by GGuillemin** [comment]
Hi 
Thanks for your help
I tried to run conda --version, and I do not think I have that installed. I also searched in my program files for conda or anaconda and I do not have any of them installed. Does that mean I need to install something prior to Orange?
Thanks

**Comment by ales-erjavec** [comment]
From the output you posted above it seems you have an anaconda installation in 'C:\Users\gguillem\AppData\Local\Continuum\anaconda3\Scripts\conda.exe'. An anaconda/miniconda installation is required for the installation (installer would prompt you to install miniconda if it did not detect an existing installation).

Can you open 'Command Prompt' and run
```
C:\Users\gguillem\AppData\Local\Continuum\anaconda3\Scripts\conda info
```
and post the output

**Comment by GGuillemin** [comment]
Hi 
Really thanks for the help, I guess I owe you at least a virtual coffee and a donout

Microsoft Windows [Version 10.0.17763.1697]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\gguillem>C:\Users\gguillem\AppData\Local\Continuum\anaconda3\Scripts\conda info

     active environment : None
       user config file : C:\Users\gguillem\.condarc
 populated config files : C:\Users\gguillem\.condarc
          conda version : 4.5.12
    conda-build version : 3.17.6
         python version : 3.7.1.final.0
       base environment : C:\Users\gguillem\AppData\Local\Continuum\anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\gguillem\AppData\Local\Continuum\anaconda3\pkgs
                          C:\Users\gguillem\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\gguillem\AppData\Local\Continuum\anaconda3\envs
                          C:\Users\gguillem\AppData\Local\conda\conda\envs
                          C:\Users\gguillem\.conda\envs
               platform : win-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False

**Comment by MrManny** [comment]
Had the same issue and error message. It kind of reminded me of #4772 when I had a similar problem.
I was able to resolve it by uninstalling Orange _and_ Miniconda through Windows' system settings before installing the new Orange.

**Comment by GGuillemin** [comment]
Hi guys. I did what you suggested, uninstalled a previous version of Anaconda, and reinstalled Orange, and it worked. Thanks both. I owe you guys some coffee and donouts

**Comment by raislinten** [comment]
> Hi guys. I did what you suggested, uninstalled a previous version of Anaconda, and reinstalled Orange, and it worked. Thanks both. I owe you guys some coffee and donouts

is it okay if we uninstall anaconda? i mean does the previous code system still working?

**Comment by ajdapretnar** [comment]
If you uninstall an existing Anaconda and then re-install Orange, the installation will install its own version of Miniconda to work with.
