### ISSUE TITLE
Decimal separator options in CSV File Import widget doesn't do anything.

### ISSUE THREAD

**Issue by hafizhmakmur** [biolab/orange3#5266]
- [ ] **What's wrong?**

Decimal separator in CSV File Import widget doesn't do anything. CSV File Import widget can't read numbers with comma as decimal separator even after specifying it in the options. CSV File Import will still be able to read numbers with dot as decimal separator even after specifying it in the options. Attempting to read csv file with comma numbers will yield
```
Traceback (most recent call last):
  File "pandas\_libs\parsers.pyx", line 1141, in pandas._libs.parsers.TextReader._convert_tokens
TypeError: Cannot cast array data from dtype('O') to dtype('float64') according to the rule 'safe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File etc etc
ValueError: could not convert string to float: '-9999,0'
```

- [ ] **How can we reproduce the problem?** 

1. Create a .csv file containing any data with numbers with comma as decimal. In my case,
```
A
-9999,0
```
2. Open a CSV File Import widget and import the file.
3. Open `Import Options...`. Specify the column as numeral. Specifiy number separator as `,`. Click OK.
4. There will appear "Unexpected error" in importing the file.

- [ ] **What's your environment?**

- Operating system: Windows 10
- Orange version: 3.26.0
- How you installed Orange: Using Anaconda Navigator 1.10.0

**Comment by ajdapretnar** [comment]
And the cell delimiter is also a comma?

I have tried to reproduce this, but it works on master for me, unless I missed something.

Unrelated, but you should probably set the conda-forge channel as suggested [here](https://orangedatamining.com/blog/2020/2020-02-24-anaconda-navigator/) and updated to the latest version.

**Comment by hafizhmakmur** [comment]
Oh yeah, the cell delimiter is semicolon. Is it really working with you? Is there any more information about my system that I can provide?

Btw regarding update, previously I tried to update with using add-ons like i see somewhere but I end up not be able to use Orange at all and i have to install PyQt5 manually. Maybe this method of updating will work.

**Comment by irgolic** [comment]
Can you reproduce this with pandas.read_csv?

**Comment by hafizhmakmur** [comment]
pandas.read_csv works well. After several experiments, somehow I can read the csv data with comma perfectly. But in my original data, in a column that I try to read as numeric, the first cell with comma decimal is shown as the error even though the real cell that procs the error (an unsanitized data) is far below that cell so I thought that it's the fault of the comma separator. I don't know if it's just how pandas shows the error or what but I have to hunt for the unsanitized data myself by scrolling and searching through >10000 rows.

**Comment by irgolic** [comment]
So pandas.read_csv reads the unsanitized data? Or does it show a better error?

**Comment by hafizhmakmur** [comment]
@irgolic pandas in python give the same exact error.
