### ISSUE TITLE
Condition on "Merge Data" lost every time software is closed

### ISSUE THREAD

**Issue by Alecampoy** [biolab/orange3#5272]
[bug.zip](https://github.com/biolab/orange3/files/5995690/bug.zip)

- [ ] **What's wrong?**

 I have concatenated 2 merge data widgets into a thirth merge data widget (comming from 4 pivot tablets that I want toghether) , all of them row matching by a class condition I created earlier. Every time when i close the software and open it again, the condition of the matching rows in the Merge Data widget is lost, so i must reconfigure every merge data widget again.

No error, simply the information is not saved in the document

- [ ] **How can we reproduce the problem?** 

In the zip file: the .ows and in the widget "archivos" should be the all files .tsv toghether but they must remain in their folders since the folder name is a information to create the class condition
[bug.zip](https://github.com/biolab/orange3/files/5995690/bug.zip)

Here is the issue
![imagen](https://user-images.githubusercontent.com/79199360/108196394-5b9bf280-7119-11eb-829d-b8fc04e65556.png)

- [ ] **What's your environment?**

- Operating system: Windows
- Orange version: 3.26
- How you installed Orange: Via Anaconda

**Comment by ajdapretnar** [comment]
@Alecampoy Thank you for reporting this and for a clear description. I have checked your workflow and it is very complicated. Could you reproduce the same issue with a smaller, simpler workflow? I have tried it with just two Pivot Tables and one Merge Data and the condition was saved. So perhaps it is an issue of Create Class or Feature Constructor. 🤷 It would help us greatly if you could repeat the problem with a simplified workflow. :)

**Comment by janezd** [comment]
Closed due to inactivity.

**Comment by irgolic** [comment]
Ah, didn't see – no worries, thanks for the bug report. :)
