### ISSUE TITLE
OWMergeData: + and x symbols are small and hard to click

### ISSUE THREAD

**Issue by irgolic** [biolab/orange3#5285]
Not sure if this happens only on Windows or elsewhere too.

It should be implemented like the buttons are in OWCreateClass.

**Comment by janezd** [comment]
I'd prefer it to be not like Create Class. This is one of the non-nicer widgets I've seen lately. :)

<img width="356" alt="Screenshot 2021-03-11 at 09 25 18" src="https://user-images.githubusercontent.com/2387315/110757497-beca0200-824b-11eb-8bcc-c66e51c27be6.png">

Meanwhile, Merge Data looks OK and I've no problems clicking the symbol.

<img width="403" alt="Screenshot 2021-03-11 at 09 27 41" src="https://user-images.githubusercontent.com/2387315/110757829-1c5e4e80-824c-11eb-8517-214c096e0b50.png">

**Comment by irgolic** [comment]
That's so weird.
This is what Create Class looks like for me:

<img width="468" alt="Screenshot 2021-03-11 at 13 38 54" src="https://user-images.githubusercontent.com/24586651/110795779-2180c500-826f-11eb-807f-91af9ac8b5cb.png">

**Comment by irgolic** [comment]
Janez was on PyQt5.9. On our currently supported versions, Create Class looks as it does in my screenshot.
