### ISSUE TITLE
Error "conda" command exited  with 255. Can not continue

### ISSUE THREAD

**Issue by thanhtuan2503** [biolab/orange3#5294]
- [x] **What's wrong?**
When I install orange 3.27.1 in my window 7 64 bit, I can't fininsh install and use orange because this error
![152305603_4098652333498604_5606756358136460890_n](https://user-images.githubusercontent.com/62798185/109021849-d783d500-76ed-11eb-8631-b4c6a0a84689.jpg)
![151503125_193556225895109_6032169384598016315_n](https://user-images.githubusercontent.com/62798185/109021861-d94d9880-76ed-11eb-908e-e3582805f67a.jpg)
And when I install anaconda or minianaconda, the cmd show it has been disabled by the administator

- [ ] **How can we reproduce the problem?** 

- [ ] **What's your environment?**

- Operating system:
- Orange version:
- How you installed Orange:

**Comment by ales-erjavec** [comment]
https://www.google.com/search?q=the+command+prompt+has+been+disabled+by+the+administrator

If you do not have permissions to modify the group policy then talk to your system administrator.
