### ISSUE TITLE
Select Rows: overlap of dropdown menu

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#5299]
- [ ] **What's wrong?**

When minimizing Select Rows, the dropdowns menus overlap.
<img width="435" alt="Screen Shot 2021-02-27 at 14 57 48" src="https://user-images.githubusercontent.com/12524972/109389315-5f472a80-790c-11eb-8263-0bc2391db23a.png">

- [ ] **How can we reproduce the problem?** 

Iris - Select Rows. Minimize the widget to the max.

- [ ] **What's your environment?**

- Operating system: OSX
- Orange version: 3.27.1
- How you installed Orange: installer

**Comment by janezd** [comment]
Fixed in new version.
