### ISSUE TITLE
Heat Map: don't show bow attributes if flag hidden=True

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#5306]
- [ ] **What's your use case?**

Some visualization widgets will ignore bow attributes if they have a hidden=True flag (in attributes of attributes). Heat Map would benefit from the same setup: ignoring bow attributes (and showing just sentiment, topics, etc.).

- [ ] **What's your proposed solution?**

Add the same option as Box Plot has it for hiding bow attributes.

- [ ] **Are there any alternative solutions?**

Keep it as is.

**Comment by ajdapretnar** [comment]
What do you think @PrimozGodec?

**Comment by PrimozGodec** [comment]
Hmm, it is a difficult one. On one side it would be nice to be consistent and remove hidden attributes. On the other side, what if someone wants to see embeddings on the heatmap. Then she/he would need to go through each attribute in the edit domain and change `hidden` attribute to `False`.

Another solution would be to remove hidden attributes from the heatmap and add a checkbox to the embedding widgets same as in the Bag of words widget.

I am actually more for this second option. This way we give the user the option to hide some attributes and still he can check embeddings with the heatmap.

**Comment by ajdapretnar** [comment]
Right, I forgot embeddings are also hidden. Yes, this would make sense - adding a checkbox to Doc Emb would make the most sense. And of course hiding hidden attributes in Heat Map.

**Comment by ajdapretnar** [comment]
I think this was the proposed solution:
- Add a checkbox to Document Embedding with the option to hide/unhide bow attributes (see BoW for example).
- Hide "hidden" attributes in Heat Map (as in Box Plot).

**Comment by ajdapretnar** [comment]
Partially fixed in https://github.com/biolab/orange3-text/pull/852.
The rest is fixed in https://github.com/biolab/orange3/pull/6000.
