### ISSUE TITLE
Test and Score Error "Test and train dataset have different target variables"

### ISSUE THREAD

**Issue by IKetchup** [biolab/orange3#5311]
- [ ] **What's wrong?**

Im having a problem on the widget "Test and score" used for classification. Im doing a classification on images and i would like to use the widget "test and score" with the option "Test on test data". 
I used select columns to select the feature "category" as target variable for the two datasets.

The training dataset is ordered in folders (so in class) with 1 image per folder. The feature "category is created by orange using the folder architecture.
For the test dataset the widget "create feature" create the feature "class_name" using a substring of each image and then I create the target variable "category" using the widget "create class". Finaly the feature category is setted as target variable with "select columns" widget.

The two datasets are passed to the "test and score" widget with the option "test on test data"

However I get the error "Test and train dataset have different target variables". 
I checked my datasets and i have the same target variable: category. 

Error message ```Test and train dataset have different target variables```

- [ ] **How can we reproduce the problem?** 

 

For each dataset (train and test) i used the widget select columns to choose the target variable as "category". Then i pass the datasets to the test and score widget and i got the following error: "Test and train dataset have different target variables"

Screeenshot of the ows file
![image](https://user-images.githubusercontent.com/72007646/110215709-8a50f180-7eab-11eb-9b19-fdb46d9428ef.png)
![image](https://user-images.githubusercontent.com/72007646/110215775-d56b0480-7eab-11eb-942a-80ac6a688a97.png)
![image](https://user-images.githubusercontent.com/72007646/110215790-e7e53e00-7eab-11eb-93a8-b12d2a34aa90.png)

Zip of the ows file (datasets are too big)

[save.zip](https://github.com/biolab/orange3/files/6095795/save.zip)

- [ ] **What's your environment?**

- Operating system: Windows 10
- Orange version: 3.27.1
- How you installed Orange: Official website

**Comment by IKetchup** [comment]
The problem come from Orange who create target variable when a folder have underfolder but doesn't associate this target variable with a same one but created manually

**Comment by ajdapretnar** [comment]
You can change this with Edit Domain - Unlink variable from its source variable. In this way all variables with the same names will be considered equal.

**Comment by IKetchup** [comment]
Its working well thanks
