### ISSUE TITLE
Exporting and saving results

### ISSUE THREAD

**Issue by richardharrishk** [biolab/orange3#5312]
- [ ] **What's your use case?**

It seems very difficult to export or save results to a readable format for a non programmer.   I can only get pickle  files which are hard to translate / convert.   It's fine to analyse data but we have to be able to report it in excel, primarily.

- [ ] **What's your proposed solution?**

 Please can we have a robust export to .xls, .png/jpeg or .pdf - in that order!  Thanks.

- [ ] **Are there any alternative solutions?**

**Comment by janezd** [comment]
What kind of results are you referring to? You write about png, so I'd assume you mean plots? At the bottom of the widget there's an icon for saving, which can save to png, svg, pdf...

**Comment by richardharrishk** [comment]
Dear Janez,

Thanks for coming back to me.  I really appreciate it as I have put a lot of time in today!

It's when I want to export text mining data - It believe that it drops the .csv option when you use the preprocessing widget and only offers the .pkl, pickle version….

Can the word counts be exported directly to excel - or do I have to use a python routine to “translate” the pickle file?  I can download to a pdf but that results in a lot of work and error if I am to do it on a good amount of data.  Any clues for a conversion to a .csv format would be very helpful.

I am much obliged for your assistance.

r

Richard Harris
夏理正
PhD student
HK: +852 9244-6622
UK: +44 7753 227687
richard.harris@cranfield.ac.uk<mailto:richard.harris@cranfield.ac.uk>
richardharris@portshelter.com<mailto:richardharris@portshelter.com>
www.portshelter.com<http://www.portshelter.com>
Skype: harrishk
twitter: richardharrishk

Currently undertaking PhD studies at Cranfield University on Narrative Finance. The impact of shock news on markets.








On 7 Mar 2021, at 19:56, Janez Demšar <notifications@github.com<mailto:notifications@github.com>> wrote:



What kind of results are you referring to? You write about png, so I'd assume you mean plots? At the bottom of the widget there's an icon for saving, which can save to png, svg, pdf...

**Comment by ajdapretnar** [comment]
@richardharrishk There are a couple of things to unravel here.

1. You are asking about how to save files after text analysis and complain they can be only saved as a pickle (.pkl). This is expected and it happens only after Bag of Words. The data becomes sparse as a dense format would be size-prohibitive. You can of course ("densify" the data)[https://github.com/biolab/orange-scripts/blob/master/scripts/Text/to_dense.py] with Python Script, but you are doing this at your own risk. After densifying the data, they can be saved as .csv or .xlsx.

2. Plots in Orange can be saved as .png, .svg or .pdf, but I do not know how this translates to text.

3. Any questions regarding Text add-on should be asked in the corresponding repository: https://github.com/biolab/orange3-text/issues
