### ISSUE TITLE
Reopen: Condition on "Merge Data" is lost every time software is closed 

### ISSUE THREAD

**Issue by Alecampoy** [biolab/orange3#5321]
Sorry that I open the issue again. The previous one was closed by an administrator due to inactivity, though it took me a while to prepare a concise workflow that replicates the error. I attach it here now.

- [ ] **What's wrong?**

 I have concatenated 2 merge data widgets into a thirth merge data widget (comming from 4 pivot tablets that I want to merge toghether) , all of them row matching by a class condition I created earlier. Every time when i close the software and open it again, the condition of the matching rows in the Merge Data widget is lost, so i must reconfigure every merge data widget again. There must be 3 Merge Data in that way, otherwise I cannot merge the 4 pivot tables

No error, simply the information is not saved in the document. Everytime I open the proyect I must reselect the Merge widget

- [ ] **How can we reproduce the problem?** 

In the zip file: the .ows and 5  .tsv files. To reproduce simply load the files in the "Multifile" widget (form spectroscopy). Then everything must work fine but the Merge Data (the condition in the merge data should be "Gusano"). After that, the workflow simply performs 2 plots. Once the Condition in the Merge Data is set, everytime I save the document, close Orange, and open it again, the condition is lost and I must reset it again.
[bug_reduced.zip](https://github.com/biolab/orange3/files/6109554/bug_reduced.zip)

Here is the issue
![imagen](https://user-images.githubusercontent.com/79199360/108196394-5b9bf280-7119-11eb-829d-b8fc04e65556.png)

- [ ] **What's your environment?**

- Operating system: Windows
- Orange version: 3.26
- How you installed Orange: Via Anaconda

**Comment by ajdapretnar** [comment]
Once again, is it possible to repeat this error with a simpler workflow? This is a very complicated workflow, which is hard if not impossible to debug.

**Comment by Alecampoy** [comment]
Sorry about it, I made the workflow as simple as possible to have the bug. Here removed all the common Create Class widgets. The Create Class right before the Pivot table is there to create a dummy or auxiliar class in order to get the results of the pivot table in just one colum for all samples (each sample is a .tsv file). In the Merge Data, the matching condition is "Gusano" (which comes from the Multifile), but despite the simplest workflow, every time I close the software this conditions is close and the Merge Data Condition gets blank. I realized it also happens by simply copy-pasting the entire workflow to another place of the whiteboard. I hope it helps now.
![imagen](https://user-images.githubusercontent.com/79199360/110629107-1ad94b80-81a4-11eb-9452-d02c94e2fc14.png)
[bug_simplest.zip](https://github.com/biolab/orange3/files/6115745/bug_simplest.zip)

In the file: the .ows plus 5 .tsv files that must be loaded with the Multifile. 

Thanks¡

**Comment by ajdapretnar** [comment]
Thanks! This will be of great help!

**Comment by ajdapretnar** [comment]
I can confirm that when I open your workflow, Merge Data doesn't open with the proposed settings.
However, if I set the condition as you proposed (to Gusano), then save the workflow, it will open with the correct settings.
This leaves me confused.

**Comment by Alecampoy** [comment]
Then I am even more confusing, I am replicating and it is not working as you say. Any suggestion I can check?
