### ISSUE TITLE
Graphs: manually set values

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#5332]
Many users have a similar request:

I’d like to be able to manually set both the minimum and maximum values for both x and y axes.  This would greatly simplify creating multiple plots to a common scale.

_Originally posted by @kaimikael in https://github.com/biolab/orange3/issues/4928#issuecomment-769698590_

Add minimum and maximum value per axis (add to Visual Settings perhaps?).

**Comment by janezd** [comment]
Related to #5023. We discussed this could be added to (appropriately renamed) Color widget, together with setting shapes.

Though graph-specific ranges would be fine, too.

**Comment by janezd** [comment]
Continues in #5377.
