### ISSUE TITLE
lift curve disappaered? (only cumulative gain present?)

### ISSUE THREAD

**Issue by wibrt** [biolab/orange3#5335]
Has the liftcurve option disappeared?

Based on
https://orangedatamining.com/widget-catalog/evaluate/liftcurve/
you can have 2 options (lift of cumulative gain),
but i see no option to to that?

Context:
orange 3.27.1
installed via pipenv on linux

Screenshots using the build in titanic dataset:
![image](https://user-images.githubusercontent.com/17875724/110923526-4a619280-8321-11eb-9ab9-427b55c9bd5d.png)

hth

**Comment by janezd** [comment]
It hasn't disappeared, it just hasn't appeared yet. :)

The widget was updated in Orange 3.28, which was released a week ago. Update and enjoy.

**Comment by wibrt** [comment]
Just waiting for 
https://pypi.org/project/Orange3/#history
then, 
because is not available through the pip python repo yet.

**Comment by markotoplak** [comment]
@wibrt, thanks for the report, 3.28.0 packages were just uploaded to PyPI.
