### ISSUE TITLE
A compatibility issue related to date types

### ISSUE THREAD

**Issue by syeLee** [biolab/orange3#5345]
It's none of the deploy environmental business.
Firstly, I imported a csv file via "CSV File Import" module, then I tried to view  the data's statisctic features,the software then throw an exception. 
I have found the reason，there is a column of data type in this csv file is date, the data looks like xxxx/xx/xx, the software does infer its type normally. However, take the date of 1905/03/14 as an example, the software internally stores its timestamp, which is a negative number. An exception will occur when the timestamp is converted to datetime.datetime data.My solution is to make the timestamp compatible here. 
Specific location: owfeaturestatics.py, function format_time_diff, 1st line.
Anyway, I have already dealt with it. If my analysis is wrong, I welcome criticism and correction, thank you!

**Comment by ajdapretnar** [comment]
I don't exactly understand what the issue is here and how to reproduce it.
I tried importing a data set with 1905/03/14 (and 1905-03-13 ISO standard and 03/14/1905 as Americans would write it) and none throw an exception in Feature Statistics.
Please specify what the issue is and how to replicate it. I suggest following the issue template.

**Comment by syeLee** [comment]
> I don't exactly understand what the issue is here and how to reproduce it.
> I tried importing a data set with 1905/03/14 (and 1905-03-13 ISO standard and 03/14/1905 as Americans would write it) and none throw an exception in Feature Statistics.
> Please specify what the issue is and how to replicate it. I suggest following the issue template.

You can create an example csv file like this:
```
test_dict = {'id':[1,2,3,4,5],'date':['1905/03/12','1976/04/12','2020/05/12','2009/12/12','2001/07/10']}
test_df = pd.DataFrame(test_dict)
test_df.to_csv("test.csv")
```
You can use "CSV File Import" load it, then use "Feature Statistics" analysis it，the issue will be reproduced.

**Comment by ajdapretnar** [comment]
@syeLee The provide code works fine for me. It could be the locale. Could you please send the file generated on your computer and also attach the output of `locale` when run from the terminal.

**Comment by syeLee** [comment]
@ajdapretnar Do you mean charset? It should be UTF-8. I can send you the file, your E-mail?

**Comment by syeLee** [comment]
@ajdapretnar 
![image](https://user-images.githubusercontent.com/34643958/111928587-04f64f80-8aef-11eb-97ce-f91a27145d12.png)

**Comment by janezd** [comment]
Discussion: If the user has a strange locale, Orange will enforce something better.
