### ISSUE TITLE
Datasets Widget Could Not Fetch Dataset List

### ISSUE THREAD

**Issue by sdfungayi** [biolab/orange3#5358]
The datasets widgets is not able to fetch dataset list.
![image](https://user-images.githubusercontent.com/81328264/112375032-739ffc80-8ceb-11eb-89c2-e900fc22c141.png)

My computer is not behind a proxy and is Orange is configured as such. See image below
![image](https://user-images.githubusercontent.com/81328264/112375320-d1344900-8ceb-11eb-96a9-55dfa6e61e62.png)

I have also disable the firewall on my computer just to find out if this works but the widget still cannot fetch the files.

**Comment by markotoplak** [comment]
Thanks for reporting this. It is unusual. We just had a workshop of 30+ mostly Windows users and no one had this problem.

Are there any other peculiarities about your system you suspect could cause this?

Where are you located?

Could you also try running Orange as the system administrator, just to see if that changes anything?

**Comment by markotoplak** [comment]
And more importantly, which version of Orange are using and how did you install it? Look into Help->About, please.

**Comment by sdfungayi** [comment]
I am running version 3.27.1
I downloaded from https://orangedatamining.com/download and installed by double clicking the exe file and following the flow.
I am running the software as the system administrator on Windows

This problem could be related to another that I reported here in which Orange is not able to access the internet: https://github.com/biolab/orange3/issues/3118#issuecomment-806142319

**Comment by sdfungayi** [comment]
SOLVED
The issue was with my firewall.
The problem persisted when I turned off my firewall. So I turned it back on and specifically opened for C:\program files\orange\python.exe, C:\program files\orange\pythonw.exe and C:\programdata\miniconda3\python.exe

**Comment by meta899** [comment]
Hello, I have also encountered this problem (the widget dataset "could not fetch dataset list"). Using MacOS Catalina and my Firewall is off. Have tried 2 different versions of Orange and they both share this problem. 

Thank you for help!
