### ISSUE TITLE
Interchange Crash after upgrading to 3.28

### ISSUE THREAD

**Issue by hsnam95** [biolab/orange3#5367]
- [ ] **What's wrong?**

Interchange crashes after upgrading to 3.28 from 3.27.

<img width="713" alt="Screen Shot 2021-03-26 at 11 50 44 PM" src="https://user-images.githubusercontent.com/13425018/112649800-185a3f80-8e8e-11eb-8584-034160aeabaf.png">

- [ ] **How can we reproduce the problem?** 

Please check the attached zip file with an ows file along with a text file.

- [ ] **What's your environment?**

- Operating system: OSX Catalina
- Orange version: 3.28
- How you installed Orange: dmg

[Archive.zip](https://github.com/biolab/orange3/files/6214769/Archive.zip)

**Comment by ajdapretnar** [comment]
@hsnam95 Textable is not one of our add-on. I suggest you report this issue to the developers of Textable: https://github.com/axanthos/orange3-textable

**Comment by markotoplak** [comment]
@ajdapretnar, thanks for finding this out.

I think we should still keep this issue open and figure out why does it fail... Did we change anything that we shouldn't have or are they using something we deprecated long ago?

**Comment by markotoplak** [comment]
I was able to replicate the problem easily. I get this:

```
  File "/home/marko/venv38/lib/python3.8/site-packages/_textable/widgets/OWTextableInterchange.py", line 239, in sendData
    self.send('Textable segmentation', None)
  File "/home/marko/dev/orange-widget-base/orangewidget/utils/signals.py", line 285, in send
    self.signalManager.send(self, signalName, value, id)
  File "/home/marko/dev/orange-widget-base/orangewidget/workflow/widgetsscheme.py", line 736, in send
    super().send(node, channel, value, signal_id)
  File "/home/marko/dev/orange-canvas-core/orangecanvas/scheme/signalmanager.py", line 492, in send
    raise RuntimeError(
RuntimeError: Sending multiple values on the same output channel via different ids is no longer supported.
```

The support for different ids on one signal was removed in biolab/orange-canvas-core#161. Per PR, the `id` argument of `send` is deprecated and still works if a single `id` is used. In OWTextableInterchange, that parameter is not used consistently. Only one call to send used the `id`.

If I make the following change in `OWTextableInterchange.py`, the errors disappear:
```
-            self.send('Textable segmentation', None, self)
+            self.send('Textable segmentation', None)
```

But I have no idea if that would break anything downstream. @ales-erjavec, why were these ids there previously? How did developers use them? Anyway, to fix this widget, if that `self` was used anywhere downstream, all sends could be modified to add it, and everything would still work fine. 

What should we do? Notify the add-on devs and tell them how to modify the code or change this runtime error into a warning and just discard the id argument in such cases?

**Comment by ales-erjavec** [comment]
> What should we do? Notify the add-on devs and tell them how to modify the code

[Yes](https://github.com/axanthos/orange3-textable/pull/14)

**Comment by markotoplak** [comment]
@ales-erjavec, thank you!
