### ISSUE TITLE
Not Working at all

### ISSUE THREAD

**Issue by Kaitlyn122** [biolab/orange3#5369]
I have tried for multiple hours, 18 in total for a school project that is due tonight at midnight to download this application. I have the newest version and despite it saying it is downloaded, it will not work. It claims it needs to be redownloaded over and over again and each time I do it, my computer has started to black out and mess up as if there is a virus now on it.  I have turned my computer off and back on, a task that now with the Orange application, my computer would no longer even do. It took half an hour for my computer to shut down and another half an hour to turn back on. I do not know what I am doing wrong. 

- [ ] **What's wrong?**

- [ ] **How can we reproduce the problem?** 

- [ ] **What's your environment?**

- Operating system:
- Orange version:
- How you installed Orange:

**Comment by janezd** [comment]
I don't see why and how would Orange say it would need to redownload itself. How does this look like?

You also haven't told us anything about your operating system and how are you installing Orange.

It is already around midnight in Europe (and Sunday, at that), so we're about to go to sleep soon.

**Comment by janezd** [comment]
Closed due to inactivity.

**Comment by Kaitlyn122** [comment]
Christina Kostas is inviting you to a scheduled Zoom meeting.

Topic: Christina Kostas's Zoom Meeting
Time: Apr 16, 2021 10:00 AM Central Time (US and Canada)

Join Zoom Meeting
https://us02web.zoom.us/j/85128368798?pwd=ZWlmSmZDSlhlMTVMam5KOHJDdzd6UT09

Meeting ID: 851 2836 8798
Passcode: TD78nS
