### ISSUE TITLE
[RFC] Move some widgets from Data, split Data category

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#5370]
@irgolic just showed me a prototype reorganization for the Data category. Looks promising! But looking at it I wondered why are some widgets even there. I'd suggest:

- Correlations -> Unsupervised
- Neighbours -> Unsupervised, works on distances.
- Outliers -> Unsupervised. I know it can be used to preprocess the data, but used heavy ML machinery and as such does not belong among the basic data-handling widgets.
- Rank -> Model. Not exactly basic data handling; has a pretty specific use. We mostly use it with a class variable, either to score features according to the Model (perfect for the category) or their connection to the class. Sidenote: this widget should maybe split into two widgets, both of which would still be a better fit for the Model category (one doing Gain Ratio, Relief & similar, and perhaps another, "Rank by Model"; stupid name, I know).
- Feature Statistics -> Visualize. Here I have doubts, but isn't this some kind of a data view? It could fit nicely with data Box Plot or Distributions. I assume it is here because we do not have a "Statistics" category...

Could anyone perhaps explain why were these widgets in the Data category in the first place? Could we move any of them?

**Comment by markotoplak** [comment]
Also, I proposed the following heuristic: does the widget use any kind of statistics other than an ordinary high schooler would recognize? If so, not "Data"! :)

**Comment by ajdapretnar** [comment]
> Could anyone perhaps explain why were these widgets in the Data category in the first place? Could we move any of them?

Because it was convenient, I suppose. 😆 

I agree with moving the widgets. One has to be careful to implement remapping for older versions of workflows, though. What about the docs?

**Comment by borondics** [comment]
I think a bit of reorganization is a great idea, I was wondering about this a while ago.

Also, it could be nice if packages, like Spectroscopy, could register widgets into other than their panel. Meaning, if a package has a file reader that would belong to the Data panel it could actually show up there. We had this issue come up recently during a workshop. Maybe this requires some major code changes though.

**Comment by ajdapretnar** [comment]
@borondics I am not entirely against having "data" widgets appear in Data pane, but I would assume such a reader is specific for the domain and would thus probably best fit into <domain> add-on. I would say Data widgets should be very general, while add-on "data" widgets can be specific. A general reader can thus be included easily in the core distribution (is it really easy to add general widget to the core distribution by an external developer?).
But again, I am not against it. Just my 2c. :)

**Comment by markotoplak** [comment]
> Also, it could be nice if packages, like Spectroscopy, could register widgets into other than their panel.

That is already possible. We did this to t-SNE some time ago, when it was actually in another package.

**Comment by irgolic** [comment]
My suggestion is to use categories to suggest a methodology to the user. For example,
- Load ->
- Wrangle ->
- Process ->
- Visualize ->
- Model ->
- Evaluate

Of course, widgets will not always be connected sequentially according to the above categories; the important part is that somebody who hasn't mined an instance of data in their life gets the gist of how to approach it.

Here's an example proposition of what the Data category split would look like:
![Screenshot 2021-03-29 at 13 15 40](https://user-images.githubusercontent.com/24586651/112843320-5f1c8500-909a-11eb-80f8-e677c27a99d2.png)

> Also, it could be nice if packages, like Spectroscopy, could register widgets into other than their panel. 

With the above reasoning, this would be sensible. An add-on should be able to add data wrangling or data loading steps. 

We're all over the place on data loading, though. IIRC the File widget actually supports registering new readers, but add-ons usually make their own widget. We could either delegate everything to two base File and Save widgets, or we could continue to encourage add-ons to make their own widgets.

**Comment by borondics** [comment]
I am not sure "Wrangle" is the best name, but this may be a personal preference.

I guess this new organization could also lead to renaming some widgets. If the categories are more 'strict', maybe saying `Data Info` within the _Data_ panel is not necessary. Although, when widgets are on the canvas it is not immediately obvious which panel they come from...

**Comment by irgolic** [comment]
I suppose the RFC is: What kind of methodology should we impose?

Relevant:
[R for data science: import, tidy, transform, visualize, and model data](https://books.google.co.uk/books/about/R_for_Data_Science.html?id=vfi3DQAAQBAJ&redir_esc=y)

**Comment by irgolic** [comment]
Discussion summary:

Move to Unsupervised:
- Correlations
- Neighbors
- Outliers

Move to Educational:
- Paint Data

Split from Data a category called Transform, containing all but:
- File
- CSV File Import
- Datasets
- SQL Table
- Data Info
- Data Table
- Feature Statistics
- Save Data
- Edit Domain
- Color
- Rank

**Comment by janezd** [comment]
Decision: let's do it and see whether we like it. For now, just rename, don't move files.

**Comment by ajdapretnar** [comment]
I've tried to do this, but the categories don't seem to be logged correctly.
I have explicitly added `category = "Unsupervised"`  to certain widgets. What happens is that Unsupervised category disappears and a new demo category with unsupervised widgets is created.

```
python -m Orange.canvas --clear-widget-settings --force-discovery -l 4
2021-11-19 16:11:36,690:warning:orangecanvas.registry.base: Creating a default category 'Unsupervised'.
2021-11-19 16:11:36,838:warning:orangecanvas.registry.base: Creating a default category 'Transform'.
2021-11-19 16:11:36,903:warning:orangecanvas.registry.base: Creating a default category 'Educational'.
/Users/ajda/orange/orange3/Orange/widgets/data/owpythonscript.py:538: UserWarning: register 'summarize' function for type object. To silence this warning, set auto_summary of 'Object' to False.
 object = MultiInput(
/Users/ajda/orange/orange3/Orange/widgets/data/owpythonscript.py:542: UserWarning: register 'summarize' function for type object. To silence this warning, set auto_summary of 'Object' to False.
 class Outputs:
2021-11-19 16:11:37,871:INFO:orangecanvas.registry.base: A category with 'Unsupervised' name already exists
```
