### ISSUE TITLE
MNIST training

### ISSUE THREAD

**Issue by liganega** [biolab/orange3#5373]
I am wondering whether and how the well known MINIST dataset can be trained using Orange3. 

The following is tried:

- Loading a manually exported cvs data file into Orange3
  - it took some time, and many of feature types are incorrectly recognized as categorical instead of numerical. 

- Building a table file manually using python script widget, but then Orange3 went down.

**Comment by janezd** [comment]
Thanks for the report.

Do you think it would help us replicate the problem and fix it (if necessary) if you sent the file that you tried to import? And fill the issue template, so that we know which OS and, even more important, which version of Orange you use? And tell us what you did in the Python Script Widget? And how did Orange go down? :)

**Comment by liganega** [comment]
Thank you for asking. 

Here is the info about the environment:

- Mac OSX 11.2.3, Quad core Intel Core i7, 16 GB memory
- Orange3 3.28.0, installed using the dmg installer,
- Anaconda was pre-installed, conda 4.9.2

and

- just started to use Orange3, but familiar with python.

Unfortunately I can't reproduce the proboem I had.
I don't remember exactly how I wrote the python script.
I just started to use Orange3 and  tried to mimic the explanation below in order to create table for MNIST from Numpy array:

https://orange3.readthedocs.io/projects/orange-data-mining-library/en/latest/reference/data.domain.html

The data was downloaded from the link below:

https://archive.ics.uci.edu/ml/machine-learning-databases/mnist-mld/

Using python script widget was not successful because it made Orange 3 go down. I don't remember exactly, but a bug report was sent to you, I think.

The second approach I tried was to load the saved csv file converted from a numpy array.  The loading process was successful although it took some time. To my surprise, the converted csv file was about 1.2 GB big, so everytime when I tried to do something Orange3 took horribly long time before it shows something. With frustration I just throwed everything. 

The second approach was made again with another mnist file download from the other site:

http://yann.lecun.com/exdb/mnist/

This time was the converted csv file was "only" 130GB big, and Orange3 could manage it to load although it takes several minutes for every step. But SVM model managed to make good predictions.

The size difference was probably because of the data types for images. The second one used int, the first one used float, I guess.

===

Here are my new questions. 

- Is it normal that Orange3 needs several minutes or more than 10 minutes to import 70,000 (28*28)-size images?

- Or is there another way to work directly with numpy array?

**Comment by janezd** [comment]
How did you load the data? In Python script, with the File widget or with CSV Import. (The latter is preferrable and faster.)

Which steps took minutes?

What do you mean by "directly working with numpy array"? Orange has its own data structure, which wraps numpy array and adds some data, like column names and types. If you'd like to work with numpy directly, you should do it in Python instead. Orange's SVM is actually from scikit-learn, and for reading of CSV files, it uses pandas.

**Comment by liganega** [comment]
Thank you for asking again.

But would you tell me how the mnist data set can be loaded into Orange3?

I don't care from which data repo. Several python libraries such as sklearn, tensorflow provides it. Or one can download it directly from below:

http://yann.lecun.com/exdb/mnist/

**Comment by janezd** [comment]
As far as I see, these files are in some proprietary format, so Orange cannot load them directly. You can use Python Script or an external script to put this into a different format. But even then, I don't know how to use them directly in Orange. That's why I'm asking what you actually did -- since you say it took a long time, you must had been doing something. :)

**Comment by liganega** [comment]
Ok, I explain you again. 

As for using Python Script: It was not successful for me to use it. I think I just wasn't familiar with it. 

It would be very helpful when there is a guide or a tutorial about writing a python script which transforms a numpy array or pandas dataframe into Table. Is there one?

The way I tried next was the following:

The data was loaded first as numpy array using python, and then converted into a csv file which was then loaded into Oragne3. But loading it to Orange3 took several minutes. The csv file was 130MB big.

**Comment by janezd** [comment]
We will replace the default script (Hello world) with one that generates and outputs a numpy array.

**Comment by liganega** [comment]
That sounds good! Thank you.
