### ISSUE TITLE
Error when trying to install Associate

### ISSUE THREAD

**Issue by pepsng** [biolab/orange3#5386]
The image is pretty much self explanatory. Running on Windows 10, 64bit orange installer with no PATH association, also running Anaconda on the same laptop. First time I use Orange for an assignment and throws the error. 

![image](https://user-images.githubusercontent.com/53281792/113666211-ed859d80-967c-11eb-9967-1863b1e7615e.png)

Any clues? already did a full conda/orange/python wipe and clean install.

**Comment by pepsng** [comment]
[New Update] Tried to install it via pip install Orange3-Associate in Anaconda Prompt, didn't work and asked for Microsoft Visual C++ 2014 or greater. Installed latest VC_redist, same error. 

Building wheels for collected packages: bottleneck
  Building wheel for bottleneck (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\ppino\miniconda3\python.exe' 'C:\Users\ppino\miniconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\ppino\AppData\Local\Temp\tmptf2owgpm'
       cwd: C:\Users\ppino\AppData\Local\Temp\pip-install-3mnwlj94\bottleneck
  Complete output (51 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\bottleneck
  copying bottleneck\_pytesttester.py -> build\lib.win-amd64-3.8\bottleneck
  copying bottleneck\_version.py -> build\lib.win-amd64-3.8\bottleneck
  copying bottleneck\__init__.py -> build\lib.win-amd64-3.8\bottleneck
  creating build\lib.win-amd64-3.8\bottleneck\benchmark
  copying bottleneck\benchmark\autotimeit.py -> build\lib.win-amd64-3.8\bottleneck\benchmark
  copying bottleneck\benchmark\bench.py -> build\lib.win-amd64-3.8\bottleneck\benchmark
  copying bottleneck\benchmark\bench_detailed.py -> build\lib.win-amd64-3.8\bottleneck\benchmark
  copying bottleneck\benchmark\__init__.py -> build\lib.win-amd64-3.8\bottleneck\benchmark
  creating build\lib.win-amd64-3.8\bottleneck\slow
  copying bottleneck\slow\move.py -> build\lib.win-amd64-3.8\bottleneck\slow
  copying bottleneck\slow\nonreduce.py -> build\lib.win-amd64-3.8\bottleneck\slow
  copying bottleneck\slow\nonreduce_axis.py -> build\lib.win-amd64-3.8\bottleneck\slow
  copying bottleneck\slow\reduce.py -> build\lib.win-amd64-3.8\bottleneck\slow
  copying bottleneck\slow\__init__.py -> build\lib.win-amd64-3.8\bottleneck\slow
  creating build\lib.win-amd64-3.8\bottleneck\src
  copying bottleneck\src\bn_config.py -> build\lib.win-amd64-3.8\bottleneck\src
  copying bottleneck\src\bn_template.py -> build\lib.win-amd64-3.8\bottleneck\src
  copying bottleneck\src\__init__.py -> build\lib.win-amd64-3.8\bottleneck\src
  creating build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\input_modification_test.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\list_input_test.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\memory_test.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\move_test.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\nonreduce_axis_test.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\nonreduce_test.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\reduce_test.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\scalar_input_test.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\util.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\__init__.py -> build\lib.win-amd64-3.8\bottleneck\tests
  UPDATING build\lib.win-amd64-3.8\bottleneck/_version.py
  set build\lib.win-amd64-3.8\bottleneck/_version.py to '1.3.2'
  running build_ext
  running config
  compiling '_configtest.c':



  int __attribute__((optimize("O3"))) have_attribute_optimize_opt_3(void*);

  int main(void)
  {
      return 0;
  }

  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for bottleneck
Failed to build bottleneck
ERROR: Could not build wheels for bottleneck which use PEP 517 and cannot be installed directly

I'm about to hit something D:<

**Comment by ajdapretnar** [comment]
I am slightly confused. You installed Orange with .exe and you have Anaconda pre-installed? (this could be one source of the problem) But also you have tried installing via Anaconda? Did you follow the [instructions](https://orangedatamining.com/blog/2020/2020-02-24-anaconda-navigator/) for installing Orange on Anaconda? And you tried to install with pip in that environment?

**Comment by ales-erjavec** [comment]
This is strange. In the dialog you have `python -m pip install rules association Orange3-Associate==1.1.8`. The `rules association` part should not be there in the command.
The error comes from trying to install a non-existing *association* package. *rules* is a completely unrelated package. You might have been able to add the *rules* to the installation via **Add-more** button/dialog, but not *association*. 

What steps exactly did you perform for installation?

**Comment by ajdapretnar** [comment]
@ales-erjavec Thanks for noticing this. We noticed the same issue in https://github.com/biolab/orange3-text/issues/633. Seems like Orange adds some arguments randomly in the add-on dialogue?

**Comment by PrimozGodec** [comment]
@ales-erjavec we have seen the same error already https://github.com/biolab/orange3-text/issues/633. In this case word, `text` was inserted in the command `pip install text orange3-text`. I and @ajdapretnar also taught that it might be due to using Add-more but I think it is not the case (since the person reporting the issue tried several different ways and always got the same behavior). I tried to reproduce the error but couldn't.

I think it is a hidden bug in Orange. Hope someone from the team can reproduce it.

**Comment by ales-erjavec** [comment]
> [New Update] Tried to install it via pip install Orange3-Associate in Anaconda Prompt, didn't work and asked for...

If you manage Orange installation through the command line be sure to work in the correct environment (Orange is installed in a separate environment distinct from the anaconda base/root). There should be a *Orange Command Prompt* entry in the start menu. Run any commands in that.

**Comment by pepsng** [comment]
I had anaconda previously installed. Then downloaded and ran Orange.exe from the page, which installed miniconda. Cleaned everything. Now I just installed anaconda again, and ran the conda clean --all ; conda clean --packages ; conda clean --tarballs

**Comment by pepsng** [comment]
> This is strange. In the dialog you have `python -m pip install rules association Orange3-Associate==1.1.8`. The `rules association` part should not be there in the command.
> The error comes from trying to install a non-existing _association_ package. _rules_ is a completely unrelated package. You might have been able to add the _rules_ to the installation via **Add-more** button/dialog, but not _association_.
> 
> What steps exactly did you perform for installation?

just ran the .exe file from the website. Nothing fancy.

**Comment by ales-erjavec** [comment]
@pepsng Can you open *Options*->*Settings* from the Orange's menu bar and in the *Add-ons* tab check that the *Pip Install arguments:* edit field is empty.

**Comment by pepsng** [comment]
> @pepsng Can you open _Options_->_Settings_ from the Orange's menu bar and in the _Add-ons_ tab check that the _Pip Install arguments:_ edit field is empty.

Now it won't even open :/ I think I'll learn to use Rstudio properly and reinstall Orange after formatting my SSD in a couple months. Thanks anyways guys!

**Comment by pepsng** [comment]
> @pepsng Can you open _Options_->_Settings_ from the Orange's menu bar and in the _Add-ons_ tab check that the _Pip Install arguments:_ edit field is empty.

This did the job. After reseting my whole python/conda , intalled miniconda then the navigator from prompt, and everything works just fine now. Thanks a lot!
