### ISSUE TITLE
Orange-canvas does not run

### ISSUE THREAD

**Issue by SpencerBowles** [biolab/orange3#5395]
I have recently installed Orange3 on my computer (Windows 10), but it is unable to run.

I have installed it in a conda environment using the instructions on the orange3 README file. I get no errors during instalation but when I try to run the program using `orange-canvas` it gives the following error:

(orange3) C:\Users\sgkb1>orange-canvas
Traceback (most recent call last):
  File "C:\Users\sgkb1\Anaconda3\envs\orange3\Scripts\orange-canvas-script.py", line 6, in <module>
    from Orange.canvas.__main__ import main
  File "C:\Users\sgkb1\Anaconda3\Lib\site-packages\Orange\__init__.py", line 7, in <module>
    raise ImportError("Compiled libraries cannot be found.\n"
ImportError: Compiled libraries cannot be found.
Try reinstalling the package with:
pip install --no-binary Orange3

How can I resolve this issue?

Spencer

**Comment by markotoplak** [comment]
Thanks for the report. It seems to be something specific so we would need a complete install log for debugging. Could you remove your Anaconda installation and start anew, and then include the complete installation log (all your commands and outputs)? Thanks!

**Comment by SpencerBowles** [comment]
Ok I uninstalled and reinstalled orange3 in my orange3 environment and now get a new error:
ImportError: cannot import name '_mklinit' from partially initialized module 'numpy' (most likely due to a circular import) (C:\Users\sgkb1\Anaconda3\Lib\site-packages\numpy\__init__.py)

I have attached full anaconda prompt output as a text file.

Thank you,
Spencer

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by PrimozGodec** [comment]
It is a strange error. It seems that numpy is not imported from your environment but it uses numpy from outside of the environment. What is the command you used to create your environment? Did you add any specific flag to the command?

**Comment by janezd** [comment]
Closed due to inactivity.
