### ISSUE TITLE
Curve fitting in Orange

### ISSUE THREAD

**Issue by bluewin4** [biolab/orange3#5400]
- [ ] **What's your use case?**
 

I am doing FTIR of proteins in order to observe their secondary structural transitions and I need to do curve fitting in order to do this. This means I need to be able to iteratively fit some set of distributions with fixed centers to my data in order to extract the information I need.

- [ ] **What's your proposed solution?**

![image](https://user-images.githubusercontent.com/47462814/115034501-92805180-9e99-11eb-899d-b852c61be43b.png)
![image](https://user-images.githubusercontent.com/47462814/115034520-98763280-9e99-11eb-9084-64f180a44c09.png)

Something like this would be perfect, the problem with those programs I showed currently is the difficulty of implementing them into a methodological workflow, so having something that runs natively in Orange would be a lifesaver for anyone doing protein FTIR or really any sort of peak deconvolution.

- [ ] **Are there any alternative solutions?**

**Comment by borondics** [comment]
Are you using the Orange Spectroscopy toolbox? (BTW, we have a pre-packaged installer of Orange with the Orange Spectroscopy and building a community around the Spectroscopy features. The website is [https://quasar.codes](https://quasar.codes))

There is a fitting widget that is very close to finishing and it will be released soon (in a month or so). You can get the current code from here https://github.com/Quasars/orange-spectroscopy/projects/2.

Try it out and let us know what you think!

**Comment by bluewin4** [comment]
Thank you! I can't wait to give it a spin :)
