### ISSUE TITLE
Orange 3.28 crashes at start-up on OS High Sierra 

### ISSUE THREAD

**Issue by guiom2959** [biolab/orange3#5402]
- [ ] **What's wrong?**

Installed Orange 3.28 using last dmg available on my macbook pro 2010 using high sierra. 
unable to run it, crashes at start-up, doesn't even open a window
crash report stack file linked. 

- [ ] **How can we reproduce the problem?** 

- [ ] **What's your environment?**

- Operating system: Mac Os High Sierra
- Orange version: 3.28
- How you installed Orange: using dmg file 
[crashReport.txt](https://github.com/biolab/orange3/files/6327953/crashReport.txt)

**Comment by ales-erjavec** [comment]
The problem is probably that 3rd-party catboost library that is included in the dmg is compiled for a newer CPU architecture. 

Can you try running
```bash
/Applications/Orange3.app/Contents/MacOS/pip uninstall catboost
```
in the Terminal and run again.

**Comment by guiom2959** [comment]
Hi ALes,
Thanks a lot. It does start now.

**Comment by markotoplak** [comment]
Thanks, @ales-erjavec, good find!

@VesnaT, catboost is an optional dependency, right? So apart from checking if catboot is installed, we should probably catch another exception that happens here. @ales-erjavec, do you remember which exception gets raised and when? At import?

**Comment by ales-erjavec** [comment]
There is no exception to catch. The process aborts with a SIGILL signal at import.

**Comment by janezd** [comment]
We discussed this at today's meeting. There's not much we can do about it, except for printing a warning to uninstall catboost if we detect the CPU architecture is too old.
