### ISSUE TITLE
increase visibility of data subset in the point-based visualizations

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3#5425]
In point-based visualisations, like t-SNE, it is very hard to see the data that comes in as a subset. Consider the following figure,

![image](https://user-images.githubusercontent.com/726604/117284448-1dd07f80-ae67-11eb-8c45-6b2b0f34aa24.png)

where a part of the data belongs to the data subset. Even though that cluster is well-defined, it is hard to spot it due to the density of the points around it. The problem becomes even more pronounced with larger data sets.

If the points that represent the selected data items sent to the widget are enlarged, though, they are clearly visible. For instance, following shows the same data as above:

![image](https://user-images.githubusercontent.com/726604/117291051-cf26e380-ae6e-11eb-8cb4-87bfaa40fe83.png)

I would propose a option (checkbox) that says "Enlarge subset instances", or something in this line. If this is implemented, it would be great to animate visualization change upon change in the input data subset, just like this is implemented when we the values in the column that dictates the size of the data points ("Size:").

**Comment by janezd** [comment]
Option 1: Slider for contrast in transparency between subset and others.
Option 2: Transparency is also applied to pen of points not in the subset.

**Comment by janezd** [comment]
Closed via #5684.
