### ISSUE TITLE
Error in parsing CSV file

### ISSUE THREAD

**Issue by PradipKumarDas** [biolab/orange3#5436]
Hello!

I noticed that Orange 3.26.0 is failing to import content from this attached CSV file (link below) and shows error message as "mpi_roof_2009b.csv was not loaded due to a text encoding error. The file might be saved in an unknown or invalid encoding, or it might be a binary file.". It is also strange because there is no issues when the same file gets loaded from Pandas running in Jupyter Notebook. Hence, I thought to check in this discussion if anyone knows any reason behind this behaviour. By the way, this CSV is a file that contains weather data at Jena and is from Max Planck Institute for Biogeochemistry (https://www.bgc-jena.mpg.de/index.php/Main/HomePage). No modifications were made to the original CSV file.

Regards,
Pradip Kumar Das
Bengaluru, Karnataka, India

[mpi_roof_2009a.csv](https://github.com/biolab/orange3/files/6470000/mpi_roof_2009a.csv)

**Comment by janezd** [comment]
Handled in #5438.
