### ISSUE TITLE
Orange 3.28 does not start

### ISSUE THREAD

**Issue by Abby-Ger** [biolab/orange3#5437]
When I run orange-canvas, my mouse indicates "busy" for a second, then the next terminal prompt appears, but the app does not start up. It worked properly for about one day. After that the software does not start. It does not show any error message. 

After running python -m orange.canvas -l 4 in the Orange Command Prompt the following message is displayed:

(C:\Users\XXXX\AppData\Local\Programs\Orange) C:\Users\XXXX>python -m orange.canvas -l 4
C:\Users\XXXX\AppData\Local\Programs\Orange\python.exe: Error while finding module specification for 'orange.canvas' (ModuleNotFoundError: No module named 'orange')

I start Orange directly from the Orange icon displayed in my desktop. I do not have installed a full version of Anaconda only the Anaconda files provided with the executable.

- Windows 10 (Version 1803)
- Orange 3.28
- I installed Orange 3.28 from the executable provided in the software website (Orange3-3.28.0-Miniconda-x86_64.exe (64 bit))

Thanks in advance.

**Comment by ales-erjavec** [comment]
> ... After running python -m orange.canvas -l 4 in the Orange Command Prompt ...

That should be `python -m Orange.canvas -l 4` with a capital O

**Comment by Abby-Ger** [comment]
Hi,

I tried with the capital O. It shows nothing.

**Comment by ajdapretnar** [comment]
Nothing as in no error or nothing at all? Does it perhaps take a long time to start?

**Comment by Abby-Ger** [comment]
Nothing at all. After double-clicking the orange icon, the pointer shows busy for 2-3 seconds and then stops.

**Comment by ajdapretnar** [comment]
I'm sorry, I still don't understand. Are you trying to run Orange from the command prompt with `python -m Orange.canvas -l 4` or are you running it by double-clicking the icon? If you are trying in the command prompt, which we ask you to do, what is the error log. Can you post it here, please?

**Comment by janezd** [comment]
Closed due to inactivity.
