### ISSUE TITLE
Documentation File for Preprocess Is Broken

### ISSUE THREAD

**Issue by sdfungayi** [biolab/orange3#5442]
It looks like documentation for Preprocess is broken from "4. Select relevant features" onward - numbering is mixed up and some descriptions/explanations are missing.

I am using version 3.28.0

**Comment by sdfungayi** [comment]
How do I get the updated documentation into my installation?

**Comment by markotoplak** [comment]
Read it here: https://orange3.readthedocs.io/projects/orange-visual-programming/en/master/widgets/data/preprocess.html

If you want it within Orange immediately: checkout the master repository and install, but this required some python/sysadmin skills and here you are on your own.
