### ISSUE TITLE
Integration PyCaret with Orange3

### ISSUE THREAD

**Issue by rogerpou** [biolab/orange3#5456]
- [ ] **What's your use case?**

Hi, i'm a Data Scientist interesting on making interactive data analysis with PyCaret. I tried to use Power BI but with the limitations of Python is really difficult to make such interactive analysis trough the filters.

- [ ] **What's your proposed solution?**

My suggestion would be to integrate such library (PyCaret) because Orange is able to have such interactivity with the plots... 

- [ ] **Are there any alternative solutions?**

**Comment by markotoplak** [comment]
We discussed PyCaret at our meeting. We do not see any gains for Orange as we are already using libraries that PyCaret wraps.

If you'd like to combine analyses in PyCaret with Orange visualization, feel free to use the Python Script widget. For PyCaret to work there you will need to install within the same Python environment that Orange is using. Also, you will need to convert PyCaret's outputs in `Orange.data.Table`.
