### ISSUE TITLE
Select Columns disappearing variables

### ISSUE THREAD

**Issue by robertcv** [biolab/orange3#5471]
**What's wrong?**
Variable disappears if you drag&drop it on top of another variable. This may also affect other widgets with the same GUI component.

**How can we reproduce the problem?** 
File(iris) -> Select Columns
Click and drag the `petal width` variable onto `petal length`. On letting go the `petal width` variable disappears both from the GUI and the output.

**What's your environment?**
- Operating system: Ubuntu 
- Orange version: master
- How you installed Orange: pip

**Comment by ajdapretnar** [comment]
Same as in https://github.com/biolab/orange3-text/issues/622.
