### ISSUE TITLE
Create Class Misclassifying

### ISSUE THREAD

**Issue by bluewin4** [biolab/orange3#5473]
- [ ] **What's wrong?**

![image](https://user-images.githubusercontent.com/47462814/121054912-ce91ad80-c78a-11eb-831c-bb915a8a8548.png)

When I attempt to create a class that includes information on the specific run this spectrum was taken from it seems to be pulling almost randomly. 

- [ ] **How can we reproduce the problem?** 

As you can see I already have a variety of other classes being pulled up but for some reason, this one is being particularly nasty. Of particular weirdness is that while I was messing with this the bug fixed itself. So probably not a very high priority but still weird as heck.

- [ ] **What's your environment?**

- Operating system: Windows 10
- Orange version: 3.28.0
- How you installed Orange: git pull

**Comment by bluewin4** [comment]
[Data.zip](https://github.com/biolab/orange3/files/6612420/Data.zip)

[bug.zip](https://github.com/biolab/orange3/files/6612427/bug.zip)

It popped up in another place, gonna try to cluelessly fix it. Will report back if I find a way to consistently fix

**Comment by markotoplak** [comment]
Thanks! Your screenshots clearly show that the classes got assigned wrongly. Can you reproduce the bug consistently?

**Comment by markotoplak** [comment]
@bluewin4, I tried your workflow and managed to reproduce the bug.

**Comment by markotoplak** [comment]
@bluewin4, thank you for brining this issue to our attention. The fix is released in Orange 3.29.3 (now available on github/pypi/conda-forge). The corresponding installers will be available tomorrow.

**Comment by bluewin4** [comment]
I'm just glad I'm not being bothersome! Thanks so much for the timely help with this stuff :)
