### ISSUE TITLE
The environment is inconsistent, please check the package plan carefully The following packages are causing the inconsistency:

### ISSUE THREAD

**Issue by Viromic** [biolab/orange3#5475]
- bioconda/linux-64::cooler==0.8.5=py37h1341992_0
  - conda-forge/noarch::orange3-bioinformatics==4.3.1=pyhd8ed1ab_0
  - defaults/noarch::dask==2021.4.0=pyhd3eb1b0_0
  - conda-forge/noarch::orange3-singlecell==1.4.0=py_0
  - bioconda/noarch::chromosight==1.3.1=py_0
  - defaults/linux-64::distributed==2021.5.0=py37h06a4308_0
  - conda-forge/noarch::orange3-educational==0.4.0=pyhd8ed1ab_0
  - conda-forge/linux-64::orange3-network==1.5.1=py37h0da4684_0
  - conda-forge/linux-64::orange3-geo==0.2.3=py37_1000

- [ ] **What's wrong?**

- [ ] **How can we reproduce the problem?** 

- [ ] **What's your environment?**

- Operating system:
- Orange version:
- How you installed Orange:

**Comment by PrimozGodec** [comment]
Can you please give me some more information? 
What is the version of Orange?
How did you try to install packages (add-ons)? Did you use Orange's add-on dialog or did you install it via the command line? W

**Comment by Viromic** [comment]
Version3 
It just stalls and states it is inconsistent

**Comment by Viromic** [comment]
perhaps it was the python 3.9 that broke 
it now it runs all right
