### ISSUE TITLE
Scatter plot problem

### ISSUE THREAD

**Issue by adam-pelikant** [biolab/orange3#5486]
- [ ] **What's wrong?**
Scatter plot do not present points i proper positions. I generate simple data set representing function Y=4*X*X and try to present it using scatter plot. Labels of points are correct but their position not. To check it I used two additional typów danych Excel and csv. Result is the same. Additionaly in two cases (script and Excel) I can not ad numerical column using Feature constructor using Z:=log(Y,2) formula. In this cases Y probably is not treat as number. Is it affected by the national settings (decimal separator)?

- [ ] **How can we reproduce the problem?** 

[Scatter plot problem.zip](https://github.com/biolab/orange3/files/6650521/Scatter.plot.problem.zip)

- [ ] **What's your environment?**

- Operating system: Windows 10
- Orange version: 3.29
- How you installed Orange:Using installer

**Comment by janezd** [comment]
Disable jittering. Jittering moves positions of points a bit to prevent overlapping. (From documentation: *Set jittering to prevent the dots overlapping. If Jitter continuous values is ticked, continuous instances will be dispersed.*)

@ajdapretnar et al: "will be dispersed" may not be the optimal description. Also, "continuous instances". Maybe we should rephrase that better. Though I doubt that anybody actually reads this.

**Comment by ajdapretnar** [comment]
Agree. I will rephrase to:
_If *Jitter continuous values* is checked, points are scattered around their original locations._
Better?

**Comment by janezd** [comment]
Much.

**Comment by adam-pelikant** [comment]
Thank you very much. I was blind.

**Comment by janezd** [comment]
Fixed via https://github.com/biolab/orange3/commit/75dca479da5887655a6b1067a90bc8407256d8af.
