### ISSUE TITLE
Use the widget's name as the name of the model?

### ISSUE THREAD

**Issue by pisarik** [biolab/orange3#5489]
Hi! Some feedback from BioSpec summer school:)

- [ ] **What's wrong?**

When the beginners want to compare the same model, for example, RF with different parameters, they create two RF widgets, set different parameters and connect them to Test and Score widget. 

The problem is that Test and Score then displays in the table the same names for two classifiers (Random Forest), so in this case you can't tell which results related to which classifiers.

![image](https://user-images.githubusercontent.com/3684845/122355475-993f4980-cf5a-11eb-9e46-1984e4ff98a6.png)

- [ ] **What's your environment?**

- Operating system: Linux (also Windows)
- Orange version: 3.29.3
- How you installed Orange: pip (also Quasar)

- [ ] **Possible solutions**
One simple solution is to highlight (select) appropriate widget in canvas, when User presses on some row in Test and Score widget. Another variation is after double click on a row pop ups canvas with widget selected (or maybe the widget's settings opened). It might be looking like this:

![image](https://user-images.githubusercontent.com/3684845/122356180-38644100-cf5b-11eb-9c34-deb31b4da4b2.png)

Another possible solution is to do something like this:
1) if you have duplicate widgets and therefore name conflicts, then try to use the widget's name
2) if you still have duplicates, then show warning and ask user to rename classifiers

**Comment by markotoplak** [comment]
Yes, this could have been handled better. If you open the RF widget (double click), you will see a field "Name". The name there will be shown in Test and Score.

**Comment by pisarik** [comment]
Aha, I haven't noticed it before:) Thanks!

**Comment by irgolic** [comment]
Could we sync the "Name" of the learner with the widget name?

**Comment by janezd** [comment]
Done via #5662.
