### ISSUE TITLE
Helper to install 3rd party packages

### ISSUE THREAD

**Issue by pisarik** [biolab/orange3#5490]
Hi! Some feedback from BioSpec summer school:)

- [ ] **What's your use case?**

During Summer School we have a Deep Learning module that uses Python Script widget. It would be nice if students also could run that workflow, but it requires them to install 3rd party packages as tensorflow, httpimport and etc.

So it is a pain to help to install packages to 20-30 people with different environments, who doesn't know how to install packages. 

- [ ] **What's your proposed solution?**

You already have quite similar module to install add-ons (python packages), it would be nice to provide some simple way to help to install 3rd party packages to people without computer science background. The simplest for implementation would be just to have a text field where you can type package name and press install:)

I think that in most cases simple package installation in the same environment that Orange installed should work well, since likely most inexperienced people use Windows+Anaconda and all other likely know how to install packages.

**Comment by markotoplak** [comment]
What you are looking for already exists but is not that well documented. See the "Add more..." button in the add-on dialog? So,the organizers could make a python package that depends on everything they need and ask the participants to install that. If you type in the package name in the add-on dialog you can install any package from conda-forge or pypi.

Alternatively, you can also install packages by dragging the package files (prepared as the ones on pypi) onto the add-on dialog window (we sometimes use this for testing).

So in your case, I'd make a biospec-2021-requirements package, put it onto pypi (and, for windows users, likely conda-forge locally hosted conda server, unless you are sure that pip/conda mixing works in your case) and be done with it. :)

**Comment by pisarik** [comment]
Thanks! It is super nice, I will try it tomorrow! 

I think it is late now to prepare a package on pypi or locally hosted conda server:) But it might be a good choice for the next year:)

How does it know what to use conda or pip? Anyway, I will test it tomorrow with summer school guys :) Everyone installed quasar (not sure whether it uses outside python/conda or packs python/conda with it).

**Comment by markotoplak** [comment]
Our Mac packages are based on pip and our windows packages are based on conda. Problematic, I know. :) The add-on window tries conda first, if it is available,  and if not it falls back to pip.

If you install per individual package it will, therefore, install it properly for the given installation.
