### ISSUE TITLE
Make the available options in a widget more obvious

### ISSUE THREAD

**Issue by kaimikael** [biolab/orange3#5492]
- [ ] **What's your use case?**

As shown in the attached screenshot, if I happen to open a widget scaled at a certain size, there is no indication that there are additional settings available below the ones visible.  I have to rescale the widget, happen to place the cursor in the right place so that the scrollbar pops up, or  read the manual carefully :-)  in order to notice that there are more options.
This is not a problem for experienced users, but I suspect it may be an issue for people just starting out with Orange.  (Well, I myself just got caught out, even having used Orange for a while!)

- [ ] **What's your proposed solution?**

A permanently visible scrollbar would make it apparent there is more to the pane than currently visible, but it seems they are not recommended these days.  
Would a triangle at the bottom of the visible portion help? (Might be tricky to implement?)
Making a more distinct border against the Zoom/Select items would make it clearer that the options are a separate item, and shadowing the border could suggest the border is a window into something larger.  User testing advisable.

- [ ] **Are there any alternative solutions?**

**Comment by kaimikael** [comment]
Ah, here’s the screenshot, couldn’t be added to the original entry for some reason.
<img width="976" alt="Screenshot 2021-06-17 at 11 30 13" src="https://user-images.githubusercontent.com/10616212/122374015-4b2e4400-cf62-11eb-961e-8a67767a1974.png">

**Comment by janezd** [comment]
This is a general macOS setting -- don't all applications behave like this? To have a permanently visible scroll bar, set "Show Scroll Bars" in Preferences/Geneal to "Always".

<img width="523" alt="Screenshot 2021-06-17 at 20 30 43" src="https://user-images.githubusercontent.com/2387315/122453868-fbc03600-cfaa-11eb-82d1-21fa231217fa.png">

**Comment by irgolic** [comment]
Adding a shadow above buttonsArea is a nice idea. I don't know an elegant way to code that though, would QFrame have that functionality @ales-erjavec? You're right though, would definitely need user testing.

**Comment by janezd** [comment]
@irgolic, the indicator of scrollability already exists. It's universal and everybody understands its meaning. It's called a *scroll bar*. No extra coding required. :)

If Orange should have an indicator that there is more contents below, then all other apps (with any scrollable area) on macOS have the same problem, IMHO.

**Comment by irgolic** [comment]
@janezd User testing that I did a month ago also indicated this is an issue. There's a universal indicator but apparently, it isn't sufficient.

**Comment by ajdapretnar** [comment]
Scroll bar behaviour is handled by Mac, not Orange. They are in System Preferences - General - Show scroll bars. Then select Always. I believe the issue happens only on Mac, which handles scrolling differently.

**Comment by ajdapretnar** [comment]
Sorry, I didn't see the above post. @janezd already explained.

**Comment by ajdapretnar** [comment]
Closing as this is related to the OS behaviour not the behaviour of Orange.
