### ISSUE TITLE
[DOC] Describe preprocessing also for other (unsupervised) methods

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#5507]
Our documentation often does not specify what actually happens to the data, which confuses uses who try to replicate the analysis in code or other packages. Examples: #5482, #5424. 

For learners, this was done in #5353. We also need this for other methods, I added PCA in #5506.

**Comment by ajdapretnar** [comment]
@markotoplak Any other widgets that are missing this? I added description to k-Means, which explicitly lists preprocessing anyway. You fixed PCA. t-SNE and Distances already explicitly describe normalization as checkbox. Similar description is missing for DBSCAN and Louvain Clustering (will add). As for MDS and SOM, do they normalize? I reckon not, but 🤷‍♀️. Did I miss any?
