### ISSUE TITLE
numpy.core._exceptions._ArrayMemoryError: Unable to allocate xxxMB of memory

### ISSUE THREAD

**Issue by liar666** [biolab/orange3#5515]
**What's wrong?**

With a simple dataflow (see below),  I get an error: "numpy.core._exceptions._ArrayMemoryError: Unable to allocate xxxMB of memory". 
Once I get this error, even if I clean my system memory (under Linux, using: `free && sync && echo 3 > /proc/sys/vm/drop_caches && free && swapoff -a && swapon -a`) and recover a few GB of memory, I get the same error over and over again for any action I do.
A few MB should be allocable since I have a few GB free now.

**How can we reproduce the problem?** 

I'm trying to run the following simple flow:
[UN15.ows.txt](https://github.com/biolab/orange3/files/6778778/UN15.ows.txt)
on "UNSW_NB15_training-set.csv" and "UNSW_NB15_testing-set.csv" from the network attacks data file from Kaggle: https://www.kaggle.com/mrwellsdavid/unsw-nb15

The flow consits in:
- 1 CSV import for the 85k lines
- 1 preprocessing + 1 select columns
- 4 models: Tree+RandomForest+SVM+NN
- 1 predictions+confusion matrix+ROCanalysis

To allow for predictions, I also have:
- 1 CSV import for the testset (see lik above)
- that passes trough copies of preprocess+select columns. 
  [SIDE NOTE: is there a way to reuse a Preprocess+Select Columns "filter sequence" created for a trainset for a testset? I couldn't find anything in the docs/videos]

At the beginning, I wanted to compare the various ML algorithms, but it takes too much time to run (particularly the NN), so I *disabled* the links from Select Columns(trainset) to NN/SVM/Tree. So data should only flow through RF now.

But I get the error : "numpy.core._exceptions._ArrayMemoryError: Unable to allocate xxxMB of memory". It is possible I have only a few memory left as I run several big Apps at the same time.
But the problem is: once I get this error, even if I clean my system memory (under Linux, using: `free && sync && echo 3 > /proc/sys/vm/drop_caches && free && swapoff -a && swapon -a`) and recover a few GB of memory, I get the same error over and over again for any action I do.

Is there anything I can do apart from quitting/restarting Orange (which generally leads to the same error as the whole flow is retried...)?

**What's your environment?**

- Operating system: Linux
- Orange version: 3.29
- How you installed Orange: pip

**Comment by liar666** [comment]
Bump?

Any news about this problem?

I've just tried a simple Logistic Regression + MLP on USNW NB15 dataset and I get the error on a machine with 19GB free!!!
`MiB Mem :  31828.0 total,  19264.6 free,  11853.9 used,    709.5 buff/cache`

**Comment by lanzagar** [comment]
Sorry for the late response. I could not really reproduce the memory problem but I can also not get the MLP learner to run on the data you mention - however it just takes a long time (and the memory does not really increase during that).
The MLP learner is just a wrapper around the scikit-learn class, so if anyone else has the time, they can check it on this data set.
As I can't identify an Orange bug I propose we close this issue.

For reference - you mentioned you can not run LogReg on this data, which works well for me and does not use a lot of memory. This is the output of free on my system before starting Orange and after running your workflow (without MLP).

```
~> free -h
               total        used        free      shared  buff/cache   available
Mem:            15Gi       263Mi        13Gi        27Mi       1.4Gi        14Gi
~> free -h
               total        used        free      shared  buff/cache   available
Mem:            15Gi       781Mi        12Gi        45Mi       1.8Gi        14Gi
```

> Is there anything I can do apart from quitting/restarting Orange (which generally leads to the same error as the whole flow is retried...)?

Just a side not (not a solution for the above):
If you have a saved workflow that crashes at startup you can sometimes work around that by using File -> Open and Freeze to load and do some changes before running it (like remove MLP).
