### ISSUE TITLE
Can't get widget from dragging 

### ISSUE THREAD

**Issue by bluewin4** [biolab/orange3#5533]
**What's wrong?**

I was trying to drag out from a widget to make a data table and I kept dragging but it won't work. Then it threw this error at me:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Exception: | AttributeError: 'NoneType' object has no attribute 'availableGeometry'
-- | --
Module: | orangecanvas.application.canvastooldock:648
Version: | 3.30.0.dev
Environment: | Python 3.8.8 on Windows 10 10.0.18362 AMD64
Machine ID: | 28a35e85-dec8-4cd4-b940-6519b257496e
Stack Trace: | Traceback (most recent call last): 
 File "C:\Program Files\Orange\lib\site-packages\orangecanvas\application\canvasmain.py", line 932, in on_quick_category_action    action = popup.exec(pos) 
 File "C:\Program Files\Orange\lib\site-packages\orangecanvas\application\canvastooldock.py", line 519, in exec    self.popup(pos) 
 File "C:\Program Files\Orange\lib\site-packages\orangecanvas\application\canvastooldock.py", line 512, in popup    geom = widget_popup_geometry(pos, self) 
 File "C:\Program Files\Orange\lib\site-packages\orangecanvas\application\canvastooldock.py", line 648, in widget_popup_geometry    screen_geom = screen.availableGeometry()AttributeError: 'NoneType' object has no attribute 'availableGeometry'
Local Variables: | OrderedDict([('pos', PyQt5.QtCore.QPoint(-1323, 105)),             ('screen', None),             ('size', PyQt5.QtCore.QSize(200, 720)),             ('widget',              <orangecanvas.application.canvastooldock.CategoryPopupMenu object at 0x00000216D9DA5820>)])

</body></html>

**How can we reproduce the problem?** 

I'm unsure, it just started happening after I messed with my workflow. I can restart the instance and it disappears, but I'll post if I get a workflow that continues to fail. It keeps popping back in seemingly at random but when I try to get it into a minimized workflow it disappears. 

**What's your environment?**

- Operating system: windows 10
- Orange version: 30.3.dev
- How you installed Orange: command line

**Comment by ales-erjavec** [comment]
The error will be fixed by https://github.com/biolab/orange-canvas-core/pull/194

**Comment by bluewin4** [comment]
Thank you for the response!
