### ISSUE TITLE
Can't export Evaluation Results to  DataTable

### ISSUE THREAD

**Issue by yuanxin-cq** [biolab/orange3#5551]
**I want to export this confusion matrix report :**

![3](https://user-images.githubusercontent.com/2495454/129432067-02e8b12c-80d1-4da3-9198-918513cc0f9d.png)

**This is my steps:**

_**step1:**_

![1](https://user-images.githubusercontent.com/2495454/129432083-89033fca-b0e9-44d5-99e8-ca3e6d9a6bb2.png)

**_step2:_**

![2](https://user-images.githubusercontent.com/2495454/129432087-22f39f44-437e-4ab2-b2fe-d6c2026c2f31.png)

**Comment by janezd** [comment]
Data Table shows data in which rows represent instances and columns correspond to variables. Confusion matrix does not contain data of such kind, thus it can't be fed to Data Table.
