### ISSUE TITLE
Select Data By Index: miserably looking widget

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#5574]
**What's your use case?**

It's not only that it looks miserable: the new tooltip (window at the bottom right) already shows more information than what's in the widget. The tooltip for the output is even larger.

<img width="394" alt="Screenshot 2021-08-28 at 20 13 11" src="https://user-images.githubusercontent.com/2387315/131227067-24666e74-2809-4a1d-bad4-346272306ce6.png">

**What's your proposed solution?**

None, but it'd be good to think what to put into this widget instead. Given its mysteriousness, there could simply be a short label explaining what the widget does, to inform the user who is randomly exploring the widgets.

**Comment by janezd** [comment]
Same for Apply Domain, just a tad less ugly.

<img width="296" alt="Screenshot 2021-08-28 at 21 04 12" src="https://user-images.githubusercontent.com/2387315/131228231-d9d88224-ccb7-4be1-9401-a0cc35313b7a.png">

**Comment by ajdapretnar** [comment]
What about a 5-row preview? In a no-thrills data table (no sorting, selection, etc.).
