### ISSUE TITLE
Hierarchical clustering does not show discrete variables in the annotations dropdown

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/orange3#5588]
**What's wrong?**

Opening this issue for discussion. 

Hierarchical clustering does not show discrete variables in the annotations dropdown when discrete variables are in the features part of the table and distance metric ignore discrete variables (e.g. Cosine distance). The reason for that is that discrete variable is filtered out from the table in `row_items` of `DistMatrix`. I think it should still be present in the Annotations dropdown since otherwise, users are confused about where is the attribute.

**How can we reproduce the problem?** 

1. Use the File widget and select the Iris dataset
2. Connect select columns and more the iris column to features
3. Connect the Distances widget and select cosine distance
4. Connect hierarchical clustering

<img width="875" alt="Screenshot 2021-09-08 at 12 49 05" src="https://user-images.githubusercontent.com/6421558/132497400-248889f5-269c-4942-aef5-bc2ee7fd05a4.png">

**What's your environment?**
- Operating system: Any
- Orange version: master - 3.30
- How you installed Orange: Doesn't matter

**Comment by ajdapretnar** [comment]
I see no reason why we should exclude them.

**Comment by janezd** [comment]
Yes, but I think it would be a good idea if Distances (re)moved discrete variables to metas in metrics in which they are ignored, as a signal to the user.
