### ISSUE TITLE
Gradient Boosting kills Orange

### ISSUE THREAD

**Issue by VesnaT** [biolab/orange3#5599]
**What's wrong?**

Orange unexpectedly terminates when tuning Gradient Boosting (xgboost) parameters. 

Log: 
[log.txt](https://github.com/biolab/orange3/files/7201197/log.txt)

**How can we reproduce the problem?** 

- Open the attached workflow. 
- Keep clicking (e.g. 10 clicks per second) the `Apply` button in the `Gradient Boosting` widget.

[xgboost_crash.ows.zip](https://github.com/biolab/orange3/files/7201211/xgboost_crash.ows.zip)

**What's your environment?**

- Operating system: macOS Catalina
- Orange version: master
- How you installed Orange: with pip from source

**Comment by markotoplak** [comment]
Can not replicate on macOS Mojave with the 3.30 test build (https://dev.azure.com/markotoplak/markotoplak/_build/results?buildId=25&view=artifacts&pathAsName=false&type=publishedArtifacts)

Can not replicate on my Linux system.

**Comment by PrimozGodec** [comment]
I cannot replicate it on Big Sur (11.5.2) with test build and neither with development version.

**Comment by markotoplak** [comment]
@VesnaT can replicate it reliably both with 3.30 test build (running on Qt 5.15) and 3.29.3 (current official build, uses Qt 5.12). She also updated libomp and it did not help.

**Comment by markotoplak** [comment]
She seems quite proud of her three-clicks-to-crash average.

**Comment by janezd** [comment]
The crash, which occurs in thread 35 in your log, has `xgboost::DMatrix* xgboost::DMatrix::Create<xgboost::data::DenseAdapter>` on the stack, which looks like the same function that crashed in tests on Mac. If this is indeed the same bug, #5613 should provide a temporary workaround and the next release of xgboost should contain a fix.

**Comment by VesnaT** [comment]
The temporary fix works for me.
