### ISSUE TITLE
Support for more math, in feature constructor

### ISSUE THREAD

**Issue by ThirstyGeo** [biolab/orange3#5601]
**What's your use case?**

Cannot, for example, calculate the geomtric mean of data using the feature constructor (no support for nth root, etc).

**What's your proposed solution?**

Allow function to accept writing of functions as per the python math library.

**Are there any alternative solutions?**

Possibly, a more robust 'calculator' widget.

**Comment by janezd** [comment]
What do you mean by "no support for n-th root"? You can compute the n-th root with the usual formula, `exp(log(x) / n)`, can't you?

If your computation exceeds what can be done in Feature Constructor, you can use the Python Script widget.
