### ISSUE TITLE
Data table: Select full rows results in an error

### ISSUE THREAD

**Issue by VesnaT** [biolab/orange3#5604]
**What's wrong?**

On `Data Table` widget, clicking upon `Select full rows` results in an error:
```
Traceback (most recent call last):
  File "/Users/vesna/orange-widget-base/orangewidget/gui.py", line 1971, in __call__
    self.func(**kwds)
  File "/Users/vesna/orange3/Orange/widgets/data/owtable.py", line 622, in _on_select_rows_changed
    for slot in self._inputs.values():
AttributeError: 'list' object has no attribute 'values'
```

**How can we reproduce the problem?** 

File -> Data Table (Click Select full rows in control area)

**What's your environment?**

- Operating system: macOS Catalina
- Orange version: master
- How you installed Orange: pip

**Comment by markotoplak** [comment]
Thanks! Looks like a regression of #4860
