### ISSUE TITLE
DLL error: pythoncom38.dll

### ISSUE THREAD

**Issue by ThirstyGeo** [biolab/orange3#5606]
**What's wrong?**

When adding any add-in, a dll error is raised:

![image](https://user-images.githubusercontent.com/17868615/134792195-7510c322-93ea-45d6-bc5f-388c261980d7.png)

I have uninstalled/rebooted/reinstalled a few times, but no success is resolving this.

**How can we reproduce the problem?** 

**What's your environment?**

- Operating system: Windows 10 Pro
- Orange version: 3.30
- How you installed Orange: minconda installer

**Comment by ales-erjavec** [comment]
At what point exactly does this happen? Opening add-ons? During/after installing?
Did you have Miniconda/Anaconda installed prior to installing Orange and if so which version?

**Comment by PrimozGodec** [comment]
This error happened to one of the participants at the workshop today. Here is the screenshot from his computer which shows that pythoncom38.dll exists on his computer.

![image001](https://user-images.githubusercontent.com/6421558/141439211-758314d6-43a9-4165-874e-d927e5f94c54.png)

It happened when he wanted to install an addon. So after he selected Orange3-text and clicked OK in the addon dialog.

It also happens when he wants to uninstall the addon by unchecking the addon and clicking OK.

Orange version: 3.30.2

**Comment by EduardoJacob** [comment]
I Installed Orange 3.30.2 and have exactly the same proble
![Screenshot 2021-11-13 153955](https://user-images.githubusercontent.com/6354191/141649916-b132cced-488d-46c8-8232-e880f4e69d2b.jpg)
m

**Comment by markotoplak** [comment]
@EduardoJacob, thanks for reporting this. At what point exactly does this happen? Opening add-ons? During/after installing?
Did you have Miniconda/Anaconda installed prior to installing Orange and if so which version? Did you have a version of Orange installed previously?

What is your Windows version? Be as specific as you can, please.

If there is anything else that you think of, please report.

**Comment by PrimozGodec** [comment]
@markotoplak it happens in Windows 10 (I do not know exactly which version maybe @EduardoJacob can help) with orange 3.30.2. No miniconda before. Look at my comment above.

It happens after when one selects addon to install and clicks ok. Same for unistall.

**Comment by wrochadel** [comment]
Did you find a solution?

**Comment by yosepito** [comment]
Same here. W10 64bit, I was able to install Cox and some other addons after the first installation yesterday. Today,  I tried to install education and text, but the same message appeared. I confirm the dll library is installed.
I installed this for ALL the users under my user account. Furthermore, I tried to open Orange with administrator privileges, just in case.
It is a problem of "not finding procedure point. I installed everything that came with Orange (I can't remember but it was Python and all those "condas"). However, in my case some Python was already pre-installed. How can I know which Python is active? 
the path in the message points to the folder already included in @EduardoJacob @PrimozGodec  and @ThirstyGeo images.

I think that all of we might have previous installations of python (some other Statistical software may use it such as SPSS), so, is it maybe causing the problem? in such case, How could we configure the python needed by Orange ?
anyway, I must congratulate authors for the software. It is an impressive work, very intuitive. I find that some explanation or documentation may be missing if one is not fluent in statistics, but searching some explanation on the web may help (for instance when one may use alternate algorithms but don't know when which one is better and the implications).

**Comment by ales-erjavec** [comment]
Can you try installing this [installer build](https://ci.appveyor.com/api/buildjobs/naegw3aok824oyah/artifacts/installers%2FOrange3-3.31.0.dev0%2Bf715500-Miniconda-x86_64.exe) from https://github.com/ales-erjavec/orange3-installers/pull/22

**Comment by ajdapretnar** [comment]
The error appeared also at a recent workshop with two participants. The case was the same for both. They worked on Windows 10, had Orange version 3.28.0 previously installed and updated Orange to 3.30.2. Then the error appeared when opening the Add-on dialogue.

I will ask the two participants to try the installer and see if it fixes the error.

**Comment by ajdapretnar** [comment]
One colleague confirms the installer works!

**Comment by PrimozGodec** [comment]
@ales-erjavec I just tested the installer on the computer where I reproduced the error and I can confirm that it works. :) thank you

**Comment by janezd** [comment]
Waiting for release.

**Comment by yosepito** [comment]
sorry for delay, I also confirm that dev release works smoothly. It does not yield that problem and it does not ask constantly for installing already installed add-ons.
thanks guys for this impressive work

**Comment by markotoplak** [comment]
The corrected installation is now served at https://orangedatamining.com/download/
