### ISSUE TITLE
Error in tests on workflow order

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#5609]
With my Orange configuration, I now get this:

```
======================================================================
FAIL: test_examples_order (test_workflows.TestWorkflows)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marko/dev/orange3/Orange/widgets/tests/test_workflows.py", line 71, in test_examples_order
    self.assertEqual(entry_points[2].name, ep_last.name)
AssertionError: 'educationaltutorials' != 'exampletutorials'
- educationaltutorials
+ exampletutorials
```

The likely culprit is #5600. Can anyone try the tests on master? Does it fail for you too?

**Comment by mw25** [comment]
I'm sorry, the failing test comes from my change.
Interestingly, the failing test shows that the functionality is correct: The workflows are now sorted first by entrypoint name and "educationaltutorials" is before "exampletutorials". When writing the test, I just hadn't taken into account that other add-ons might be installed as well.
If I install the educational add-on, I can reproduce the error. 
I will fix it.
