### ISSUE TITLE
Interchange doesnt work

### ISSUE THREAD

**Issue by asamarsal** [biolab/orange3#5612]
I've just update add-ons to the newest version. my text (v.1.5.1) and textable (v3.1.11). when i open up my old project (turn text into a word cloud), the interchange doesnt want to get input and output. i didnt know its a bug or there are new workflow to link. 

My project is there are a long text > into a segment > preprocess (transform to lowercase, stopword, regexp) > into a word cloud

Thanks

![interchangee](https://user-images.githubusercontent.com/34872359/135288583-92035d2f-8215-4e54-b941-6cc65d363b6f.png)
![Interchange](https://user-images.githubusercontent.com/34872359/135288616-008facbf-e01b-40da-8230-09a7893f2cda.PNG)

**Comment by ajdapretnar** [comment]
@asamarsal Sorry, but we don't develop Textable add-on. Please contact the developers to resolve the issue.
