### ISSUE TITLE
Python-Documentation 

### ISSUE THREAD

**Issue by ozi42** [biolab/orange3#5631]
Hello, can someone tell me, where I can find the missing Python-Documentation ?
https://orange3.readthedocs.io/projects/orange-data-mining-library/en/latest/reference/regression.html
I think a lot of the documentation is missing.

**Comment by markotoplak** [comment]
Thanks for the notification, some autodoc documentation is missing.

**Comment by ozi42** [comment]
comes the documentation online again?
