### ISSUE TITLE
Aggregate Columns default selection

### ISSUE THREAD

**Issue by robertcv** [biolab/orange3#5643]
**What's your use case?**
I am using this widget to calculate signature scores by choosing different sets of genes. I want to do this more interactively but currently, I can't as I need to manually select genes to be included in the aggregation. I am doing the selection in Gene Sets widget and I would like for the Aggregate Columns widget to use all columns if none are selected. Also, I would exclude meta fields from the list as they are normally excluded from computations in Orange.

**Comment by ajdapretnar** [comment]
In practice, this would probably mean:
- Aggregate Columns accepts Features input, which selected the input features for aggregation
- by default all features are selected (I am not sure I am in favor of this, needs discussion)

From what I know, Aggregate Columns already ignores Discrete and String variables.

**Comment by janezd** [comment]
The first option would require a new widget; its input would be a Table, and output would be a list of features. I do not like such "computational" widgets at all. Apply Domain is ugly enough, and Transpose, though useful, is quirky.

I'm not very happy with the second option, but it's useful. We could have Radio buttons
- All
- All, including meta attributes
- Selected variables

The last option would be followed by the current list view.

This would make behaviour explicit and cover all cases @robertcv and @ajdapretnar discussed.

Comments?

**Comment by ajdapretnar** [comment]
I don't understand the "first option would require a new widget"...? Aggregate Columns could, probably, just accept an additional input, just like Scatter Plot. The input type would be Features, just like Select Columns already outputs. The behaviour would also be the same as in Select Columns. *Use input features* appearing if Features input is present. No?

**Comment by janezd** [comment]
What I meant was: very few widgets provide output `Features`. More widgets, I guess, provide a table with a subset of columns, which could be used as Features, if there was a widget that would get a Table and output a list of features.

I don't oppose to Aggregate Columns having a Features input. But I'd still add radio buttons (for which we have plenty of space), because they cover different scenarios better and more explicitly.
