### ISSUE TITLE
Data Tables- Replace a feature-column with a meta-column

### ISSUE THREAD

**Issue by ozi42** [biolab/orange3#5645]
Hello, 

i have a data table. The Data Table has six features. 
Is it possible to declare the first two features-column as meta-colums?

-------------------------------------
CODE-Example:

data=copy.deepcopy(in_data)
print(data)

<< [[1.0, 2, 5, 3, 3, 9],
<< [1.0, 5, 10, 2, 4, 9],
<< [3.0, 5, 2, 5, 1, 1],
<< [0.9, 4, 5, 8, 8, 5]]

print(data.domain)

<<[ Jan, Feb, März, Apr, Mai, Juni]

-------------------------------------
 

Related to this example : The Features Jan and Feb should be Metas.

**Comment by ajdapretnar** [comment]
Are you referring to the code example?
Also, this is more appropriate as a discussion, not an issue, so moving it there.
