### ISSUE TITLE
Table widget should output sorted data

### ISSUE THREAD

**Issue by robertcv** [biolab/orange3#5655]
**What's wrong?**
It's the same issue as described in #4597. It looks like it was already fixed but it is not working currently. I would also like it to output the changed order of columns.

**How can we reproduce the problem?** 
Any data -> Data Table -> sort rows by any column -> connect to another Data Table -> order is not changed

**What's your environment?**

- Operating system: Ubuntu 20.04
- Orange version: 3.30.1
- How you installed Orange: pip

**Comment by JakaKokosar** [comment]
@robertcv Thank you for raising this issue. The behaviour of the Data Table widget is expected but probably not appropriately documented. Widget handles sorting but only on selected data (#4644). Let me explain:

Scenario 1 ->  Widget outputs all data by default (no sorting and selection).
![1](https://user-images.githubusercontent.com/15876321/141136590-fc0cdb1e-cdad-4614-b7f1-e5bf761665a8.png)

Scenario 2 ->  User sorts data by sepal length, and still, no rows are selected. Widget outputs unsorted (original) data.
![2](https://user-images.githubusercontent.com/15876321/141139488-9c34dfab-6c03-487f-9fcb-3b50f9305cd4.png)

Scenario 3 -> User sorts data by sepal length and selects some rows. Widget outputs selected data that is sorted like shown in the view table.
![3](https://user-images.githubusercontent.com/15876321/141139631-de60fffe-92c8-4b25-be14-e4c79aa32149.png)


Without this limitaion, data would need to be copied every time user changes sorting on table view. For large datasets this could be problematic.

**Comment by robertcv** [comment]
That's good to know, thank you!
