### ISSUE TITLE
GUI: Long labels fall out of controlArea

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#5675]
**What's wrong?**

In case of large labels for sliders, info text and such, labels fall out view in controlArea.

Here's an example from Distributions
<img width="307" alt="Screen Shot 2021-10-29 at 14 15 40" src="https://user-images.githubusercontent.com/12524972/139432818-83fd9261-5f00-44aa-ac8f-93ae25a2bb85.png">

**How can we reproduce the problem?** 
Datasets (HDI) - Distributions (show GNI attribute)

**What's your environment?**

- Operating system: OSX
- Orange version: 3.30.1
- How you installed Orange: dmg

**Comment by janezd** [comment]
Sliders in the following widgets

- **need attention / fixing**
    - [ ] Distributions
    - [ ] Pythagorean Trees (the label for tree depth is wide enough for some double-digit numbers; 99 is already partially cut)
    - [ ] Pythagorean Forest (same)
 
- **are positioned so that size is not a problem, or seem to be resized properly**:
    - Create Instance 
- **have labels of (pre)known widths, so they are properly sized**:
    - Associate
    - Itemsets
    - Data Sampler
    - Louvain Clustering
    - Neural network
    - Network Explorer
    - Outliers
    - Preprocess (in discretization)
    - Silhouette
    - t-sne
- **don't have a label (or have label below)**:
    - Choropleth
    - Gradient boosting (e.g. with catboost)
    - Hierarchical Clustering
    - Linear Regression
    - Logistic Regression
    - Paint Data
    - projections widgets (for size, transparency, jittering)
    - Randomize
    - Tree Viewer

**Comment by janezd** [comment]
I have checked the core widgets and some add-ons I have installed. I have only checked sliders. Labels and info text is another matter: I suppose an issue "check all widgets for anything that is truncated" is not actionable, so I'd stop here. Let us fix the tree places I found, and be aware of the problem in the future and in other places.
