### ISSUE TITLE
Feature Constructor: issues with sparse data

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#5686]
**What's wrong?**
Feature construction is a *lot* trickier for sparse data (practically not working).
When constructing a variable with year (instead of full date) I can use `str(Datetime)[:4]` on a normal data. On sparse, I get `AttributeError: 'list' object has no attribute 'ndim'`.

**How can we reproduce the problem?** 
Corpus (election-tweets-2016.tab).
Feature Constructor, add new variable Year with expression `str(Time)[:4]`. It works.
Pass the data to Bag of Words. Use Feature Constructor with the same expression. It doesn't work. Note that the error remains even if the variable is in metas (so technically not a part of bow).

<img width="487" alt="Screen Shot 2021-11-08 at 16 20 22" src="https://user-images.githubusercontent.com/12524972/140768606-07b1b263-bbb3-46cd-b696-f38089171541.png">

**What's your environment?**
- Operating system: OSX
- Orange version: 3.31.0.dev
- How you installed Orange: pip

**Comment by janezd** [comment]
Feature Constructor has been changed a lot and this was apparently fixed at some point.
