### ISSUE TITLE
Standalone group-by widget, allowing for >100 categories

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3#5691]
**What's your use case?**
I would like to group data from connected products by product ID. Let's say we have timestamped temperature and velocity measurements from more than 100 instances of a product taken every hour, so that there are more than 100 different product IDs in the column "product ID", each occurring in several rows. I want to know the average temperature and velocity of each product instance over the whole dataset. The product ID in fact appears as a categorical variable, even if the IDs are written as numbers.
The only way to get my averages is to use the Pivot Table widget and use the Grouped Data output port, but Pivot Table has a limitation of 100 categories. This is probably because Pivot Table crates a matrix so that the data relating to 100 categories produces 10,000 cells. Pivot Table seems overkill for this simple task: I need a table with 300 cells as output with 100 categories in the input.

**What's your proposed solution?**
A relatively straightforward Group-By widget that isn't as computation-intensive as Pivot Table, and that can simply aggregate the other columns for all the categories of a categorical variable, even if there are more than 100.

**Are there any alternative solutions?**
Split up the data in subsets with <= 100 categories using a spreadsheet program, run each of them through Pivot Table and Concatenate afterwards.

**Comment by ajdapretnar** [comment]
There's a new widget Group By that does exactly what you wish for. It is not yet in the release, but you can try it out in master.
