### ISSUE TITLE
Plots - Axes not matching with graphs

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/orange3#5697]
**What's wrong?**

Axes on various plots (scatter plot, hierarchical clustering) do not match with plots when using two screens (extended), and the screen is scaled. It only happens on Windows. It is a bug by photograph https://github.com/pyqtgraph/pyqtgraph/issues/756, but it seems it is not solved there. I see just some suggestions.

![error](https://user-images.githubusercontent.com/6421558/142237700-9b685a4a-4233-4af3-b44e-315e3588b9f0.png)

**How can we reproduce the problem?** 

1. Use laptop connected to externals string (external screen extends your screen). 
2. Set Scaling to 125% in display settings. 
3. Open scatter plot with some data connected. 

**What's your environment?**

- Operating system: Windows 10
- Orange version: 3.30.2
- How you installed Orange: Installer

**Comment by RitterD** [comment]
Hi,
i was able to fix this issue by adding this 2 lines **before** app = QApplication(sys.argv)

`QApplication.setHighDpiScaleFactorRoundingPolicy(Qt.HighDpiScaleFactorRoundingPolicy.PassThrough)
    QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)`

I hope it can fix ur issue as well
