### ISSUE TITLE
Heat Map: impossible to reset the visualization after zoom

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#5701]
**What's wrong?**

In Heat Map, one cannot reset zoom level to the original view.

Original:
<img width="842" alt="Screen Shot 2021-11-22 at 14 45 15" src="https://user-images.githubusercontent.com/12524972/142872901-857725b6-5f01-48ca-bf33-26626699dbd0.png">

After zoom:
<img width="842" alt="Screen Shot 2021-11-22 at 14 46 10" src="https://user-images.githubusercontent.com/12524972/142872933-f2c8dc51-182e-46c2-a786-3525b9a79fea.png">

**How can we reproduce the problem?** 

File (brown-selected) - Heat map.
The first view is compact and fits within a widget.
Press Ctrl++ just once.
Visualization gets really big.
Ctrl+0 zooms out a bit, but it doesn't return you to the compact view.
Switching Keep aspect ratio achieves nothing.

**What's your environment?**

- Operating system: OSX
- Orange version: 3.30.2dev
- How you installed Orange: pip

**Comment by ales-erjavec** [comment]
Press Ctrl+9

**Comment by ajdapretnar** [comment]
Thanks! Let's add that to the documentation. I still think it might be nice for non-expert users to have some buttons for zoom.
