### ISSUE TITLE
Plot Data squashing data outside the fixed range

### ISSUE THREAD

**Issue by robertcv** [biolab/orange3#5705]
**What's wrong?**
When using the brush in the Paint Data widget points get randomly plotted inside the set radius. When plotting near the [0, 1] edge points that would fall outside are moved on the edge to fit inside the range. This is not good as you destroy the randomness of the data. 

![Screenshot from 2021-11-24 15-12-30](https://user-images.githubusercontent.com/13180057/143254464-fa90df64-798b-4bd6-8482-7c23c823d1d1.png)

**What's your proposed solution?**
I would like it to either not modify the points that fall outside or just don't use those. 

**What's your environment?**

- Operating system: Ubuntu 20.04
- Orange version: 3.30.2
- How you installed Orange: pip

**Comment by janezd** [comment]
I can't reproduce this and I don't see how it could happen. Paint data applies the following scaling:

```python
def scale(values, min=0, max=1):
    """Return values scaled to [min, max]"""
    if len(values) == 0:
        return np.array([])
    minval = np.float_(bn.nanmin(values))
    ptp = bn.nanmax(values) - minval
    if ptp == 0:
        return np.clip(values, min, max)
    return (-minval + values) / ptp * (max - min) + min
```

Note that clipping is applied only when `nanmax(values)` equals `nanmin(values)`, so it would set all data to 0 or 1, which clearly doesn't happen in your case.

Can you upload the data that you feed into the Paint widget?

**Comment by janezd** [comment]
I haven't read your issue properly. Please ignore the previous comment.
