### ISSUE TITLE
Lazy outputs (... honour sorting in Data Table)

### ISSUE THREAD

**Issue by kaimikael** [biolab/orange3#5720]
**What's your use case?**

In the attached workflow I input a file with the populations of all Swedish municipalities.  They are a bit too many to comfortably display in a Bar Plot, but I thought I could use a Data Sampler to cut them down to size, as it were.  I turns out that the Data Sampler does not retain the original order of the data.  That is not a problem, I thought, I insert a Data Table where I can sort the data rows by population, but it seems the sorting is not retained when sending on to the Bar Plot, see attached screenshots.  This is inconvenient.  

**What's your proposed solution?**

I would like the Bar Plot to honour the sorting of rows done in the Data Table.

[Municipalities, Sweden.csv](https://github.com/biolab/orange3/files/7656761/Municipalities.Sweden.csv)
[PopulationPlot.zip](https://github.com/biolab/orange3/files/7656762/PopulationPlot.zip)
<img width="798" alt="Screenshot 2021-12-05 at 21 10 48" src="https://user-images.githubusercontent.com/10616212/144762803-410b4d7e-105b-4677-a76f-db0d53b4e7ef.png">
<img width="1132" alt="Screenshot 2021-12-05 at 21 11 02" src="https://user-images.githubusercontent.com/10616212/144762818-d3b95d3a-66be-4273-977f-3c2a7eba141f.png">

**Are there any alternative solutions?**

An alternative solution would be to allow me to drag the bars in the bar plot to put them in any order, but it would probably be very tedious for any larger data set.

**Comment by ajdapretnar** [comment]
The issue is explained here: https://github.com/biolab/orange3/issues/5655
It seems this cannot be solved easily.

**Comment by kaimikael** [comment]
Ah, I see, one has to explicitly _select_ the rows to get them in the right order to the next widget.  That’s not too onerous, but maybe it should be explicitly explained in the documentation for Data Table, it feel as if it should be a fairly common use case.

**Comment by janezd** [comment]
Thanks for this suggestion, because it revived the discussion about #5655 and resulted in an interesting idea: outputs could be lazy. A widget could offer a function to compute the output, but the function would be called (and the output computed) only when actually needed by some input.

We'll try the concept. I'm renaming the issue to make it easier to find.

**Comment by janezd** [comment]
Lazy signals do not seem difficult to implement. A quick and dirty solution (which probably breaks something) is to have

```python
class LazyValue:
    NoValue = object()

    def __init__(self, callable):
        self.callable = callable
        self.__cached = self.NoValue

    def __call__(self):
        if self.__cached is self.NoValue:
            self.__cached = self.callable()
        return self.__cached
```

and add

```python
 if isinstance(value, LazyValue):
        value = value()
```

to `WidgetsScheme.process_signal_input_default`. This allows doing things like

```python
        self.Outputs.annotated_data.send(LazyValue(lambda: create_annotated_table(table, rows)))
```

`create_annotated_table` will then be called only if the signal is attached to some input.

The problem, though, is that this also breaks summaries. Lazy signals should be able to provide hints (heuristic, if necessary) for summaries.  Many devils in details.

**Comment by janezd** [comment]
Done.
