### ISSUE TITLE
File widget: make file readers expicit

### ISSUE THREAD

**Issue by borondics** [biolab/orange3#5724]
**What's your use case?**

File loading is a bit frustrating, specifically for the extensions where the content can be of multiple formats and the file is not actively analyzed to determine which specific loader will try to load the file.

Let's say we are trying to load a TXT file which is not of the default TXT loader format. The user has to select the reader in the drop-down menu of the `...` dialog (I guess this window is the OS specific file browser). Then, if the reader is correct, the file gets loaded and we return to the File widget main window. However, if the user wants to load another TXT file with the previous structure, which is reasonable to expect, they have to select again the specific loader, the `...` dialog doesn't remember the previous choice (although the File widget does save this parameter and if the user simply clicks between the different items in the drop-down menu changing back and forth works).

**What's your proposed solution?**

It would be nice to set the file format to the last used in the `...` file selector dialog.

**Are there any alternative solutions?**
- Allow the file reader to analyze the structure of the file and select the appropriate reader based on the content. This could be fairly fast as the first few lines/bytes usually unambiguously determine the format.
- Try all available readers for that particular extension and use the one that doesn't fail. This might be slow?

**Comment by markotoplak** [comment]
For some context, some extensions (like Spectroscopy :) ) define other readers that also open `.txt` files.

We discussed this with @borondics. A good first step would be to show which reader is being used and allow the user to change the reader without going into the file dialog. The current reader selection (by choosing which file types the file dialog shows) is cryptic and hidden. Having a combo box with available readers would solve lots of the confusion.

Furthermore, by making readers explicit, we could relax the requirement that some readers can only open files with certain extensions. Text files often have various extensions. Currently, users must manually rename files (perhaps into `.txt` or `.csv`) to be able to use certain readers, which makes the user experience unnecessarily bad.
