### ISSUE TITLE
Build for M1 Mac

### ISSUE THREAD

**Issue by micsama** [biolab/orange3#5726]
**What's your use case?**

**What's your proposed solution?**

**Are there any alternative solutions?**

**Comment by janezd** [comment]
Can you donate one? :)

This will require some testing, and none of core developers has an M1 mac. One is ordered, we're waiting.

**Comment by markotoplak** [comment]
@wvdvegte, we hope it does. If you've tried it or know of anyone who did, we'd be love to hear about it.

**Comment by micsama** [comment]
> Orange currenty适用于M1 Mac的非本地功能Rosetta 2？

It works with Rosetta 2. but I thought it will be better if we have another  original build for M1 Mac

**Comment by micsama** [comment]
> @wvdvegte，我们希望如此。如果您尝试过它或知道有人尝试过，我们很乐意听到它。

I had clone the source code, and try to build it by myself, but its doesn't work. I can use brew to install PyQt  ,but there were something error with pyqtwebengine. Then I failed.

**Comment by ivaquero** [comment]
> Does Orange currenty work on M1 Macs non-natively, with Rosetta 2?

I am an M1 user. Yes, it works, but you can't use some add-ons, or it will break.

**Comment by markotoplak** [comment]
@ivaquero, which addons break it? Thanks.

**Comment by ivaquero** [comment]
@markotoplak I guess it's the text add-on. I can't open orange after installing it. I tried twice. I don't know how to track the log in the terminal, so I am not 100% sure.

**Comment by Wesseldr** [comment]
The latest version 3.31.1 now finds the M1 install of xgboost :-) 

> @markotoplak on OsX Intel the Orange3 + xgboost works when using: `brew install xgboost` after that the Extreme gradient boositng & random forest are available as options inside Orange3-GradientBoosting
> 
> However on the M1 Max the same trick does not work. o I presume this is an addon that breaks. Brew also now stores all files inside /opt/homebrew for all the M1 binaries instead of the old location of brew. /usr/local/Cellar/xgboost
> 
> I've also tried installing xgboost in my default miniconda python3.9 env, but that also leaves it undetected for Orange3. Not sure if Orange3 can take hints what conda environment to use :) I'm not that poweruser yet... The rest Orange3 works well on the M1 :)

UPDATE
@14Jan21, upgraded to the 3.31.1 version of Orange3, and can confirm the XGboost paths are now fixed and it is available in Orange3. A big thank you!!!!

**Comment by markotoplak** [comment]
@Wesseldr, thanks for the update, but it wasn't anything we fixed. :)

**Comment by wvdvegte** [comment]
Gradient Boosting also works on OS X Intel (Orange 3.31.1), without the brew command. Don't know how it was in my machine in previous versions - I've never tried it before.

**Comment by zrezke** [comment]
I had trouble getting Orange to work because of it's pyqt5 dependency, which I could not find a way to install correctly. However I installed pyqt6 using pip without any issues and so I manually went into the Orange source and bumped all pyqt5 imports to pyqt6... It seems to work now!

**Comment by markotoplak** [comment]
Using pyqt6 with the current version of Orange could be problematic. If you really decide to do that, use the code from #5884, which contains Qt6 specific fixes.

@janezd, @JakaKokosar, you are both running Orange on M1 Macs, right? Did you need to do anything special for Orange to run?

**Comment by zrezke** [comment]
Hmm, thanks I didn't know you were working on pyqt6 support.I will switch to https://github.com/biolab/orange3/pull/5884, if I encounter any issues. :)

**Comment by janezd** [comment]
@zrezke, we'd actually prefer if you switched to #5884, so you can report any issues there. :) Such changes always contain lots of small details that can go wrong.

**Comment by janezd** [comment]
@markotoplak, I'm running Orange in PyQt5 with Rosetta, so not (directly) on M1. With this setup, the only problem was to properly configure the development tools for building bottleneck.

Switching to M1 with PyQt6 will require installing (hopefully in parallel) of conda for M1. Not this week, yet.

**Comment by ivaquero** [comment]
Currently, `PyQt` and `PyQtWebEngine` on `conda-forge` have already supported osx-arm64. I just made a PR to trigger `conda-forge`'s arch migrator at https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3799.

**Comment by andrey-khropov** [comment]
> update: dependency `catboost` hindered the osx-arm64 migration [conda-forge/catboost-feedstock#97](https://github.com/conda-forge/catboost-feedstock/pull/97).

JFYI: CatBoost conda package does support osx-arm64 now: https://github.com/conda-forge/catboost-feedstock/pull/95.

**Comment by ahmfarisi** [comment]
For me as m1 user, it's only work if you run it with rosetta. Cheers

**Comment by janezd** [comment]
We can close this now, right?

**Comment by PrimozGodec** [comment]
Sure. Now we provide both arm wheels and [Apple Silicon installer](https://orangedatamining.com/download/#mac).
