### ISSUE TITLE
Edit Domain: unhelpful error message

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#5731]
**What's wrong?**

When editing column names in Edit Domain and having 100+ variables, I accidentally used the same name for two variable. Problem is, I have no idea which (because there are a 100 of them). Edit Domain says: "A variable name is duplicated."

Would be helpful is it said "Variable <name> is duplicated" or something, so that one knows how to fix the issue.
Alternatively it could output the data, but rename the bad variables as usual in Orange (and issue a warning).

**How can we reproduce the problem?** 

Just give two variables the same name in Edit Domain.

**What's your environment?**

- Operating system:
- Orange version:
- How you installed Orange:

**Comment by janezd** [comment]
Fixed via #5732.
