### ISSUE TITLE
Color file not correctly loaded?

### ISSUE THREAD

**Issue by kaimikael** [biolab/orange3#5742]
**What's wrong?**

I may be misunderstanding how this is supposed to work, on the other hand I will argue that the help window for Color does not show the SAVE/LOAD/RESET buttons and accordingly does not explain them :-)  (So the help page, at least, would need to be updated.)

Anyway, in the attached workflow I have a widget Color in which I set the colours for Japan and United States, respectively.  I have pressed SAVE in order to create a file GroupedChartsColourMap.colors.  In another branch of the workflow I want to reuse these colour settings, so in the widget Color (1) I have pressed LOAD in order to read the saved colours.  However, this does not seem to affect the colour settings for Japan and United States in that widget, they retain their defaults.

My assumption was that the SAVE/LOAD pair allows me to reuse colour maps in different workflows, but this does not happen?

**How can we reproduce the problem?** 

The workflow, data, and colors file are attached.  If you open the Color widget, you see the intended setting of country colours.  If you open Color (1), press LOAD and load the GroupedChartsColourMap.colors file, you can see that the colour settings in that widget are not affected.

**What's your environment?**

- Operating system: macOS 12.1
- Orange version: 3.30.2
- How you installed Orange: From disk image at https://orangedatamining.com/download/#macos

[ColourMap.zip](https://github.com/biolab/orange3/files/7735248/ColourMap.zip)

**Comment by janezd** [comment]
- "USA" is not the same country as "United States". Orange is smart, but not that smart. :)
- In fact, Orange is quite stupid. Even variable "Country" is not the same variable as "country". (We could make variable names case insensitive, but God knows how many old workflows this would break. And it would probably be a bad idea anyway.)

Rename "Country" and the country and it will work. :)

But a little warning would be nice nevertheless. I will change the widget to warn the user about ignored variable definitions ("country", in your case), but not about the values.

**Comment by kaimikael** [comment]
D'oh!  Two bugs of my own making!  Sorry about that.  
But an update of the manual to cover the colour map buttons would be nice at some point.
