### ISSUE TITLE
Table: copy does not guarantee unlock to suceed

### ISSUE THREAD

**Issue by VesnaT** [biolab/orange3#5746]
**What's wrong?**

Unlocking sparse data does not work.

**How can we reproduce the problem?** 

Any of the following results in an error (ValueError: 'metas'/'X' is a view into another table and cannot be unlocked)
```
from Orange.data import Table

Table.LOCKING = True
data = Table("zoo")
data = data.to_sparse()
with data.unlocked():
    pass
```

```
from Orange.data import Table

Table.LOCKING = True
data = Table("iris")
data = data.to_sparse()
with data.unlocked():
    pass
data = data.copy()
with data.unlocked():
    pass
```

**What's your environment?**

- Operating system: macOS Catalina
- Orange version: master
- How you installed Orange: pip

**Comment by markotoplak** [comment]
(Un)fortunately, both examples work fine for me. :)

I see that to_sparse goes through `transform()` which does not have any unlocking guarantees. I remember we were looking at this at that time, but I do not remember if there was ever a case where copy() after to_sparse() would not be unlockable. That would certainly be a bug, but for this one, I am not so sure.
