### ISSUE TITLE
Broken link on FAQ page

### ISSUE THREAD

**Issue by kaimikael** [biolab/orange3#5753]
**What's wrong?**

On the page https://orangedatamining.com/faq/, the heading “How to teach with Orange?” has a link to https://orangedatamining.com/categories/education/, it should be https://orangedatamining.com/blog/education/.

**How can we reproduce the problem?** 

**What's your environment?**

- Operating system:
- Orange version:
- How you installed Orange:

**Comment by ajdapretnar** [comment]
Fixed in https://github.com/biolab/orange-hugo/pull/287.

**Comment by ajdapretnar** [comment]
Thanks for the report!
