### ISSUE TITLE
Test and Score: move Target Class and Model Comparison closer the results they influence

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#5764]
Someone wrote me an email asking me why this happens to their data. I tried on `iris` and this is what I get:

![Screenshot_2022-01-05_16-50-27](https://user-images.githubusercontent.com/552182/148247474-1510a858-32c2-483f-91e5-00584aba69e5.png)

Is anyone aware of any theory why would this happen so regularly?

On `titanic`, I only see CA = Recall, Precision returns something else.

**Comment by ajdapretnar** [comment]
Got the same mail, literally just looking into this. 😅

**Comment by ajdapretnar** [comment]
For me, Recall seems off. Logistic regression on heart_disease. If I understand Recall correctly, it should be
146/173 for class = 0
and
112/130 for class = 1
Hence the average of the two values would be 0.8527. Actual Recall as reported in T&S is 0.851. Not far off, but not the same.

<img width="305" alt="Screen Shot 2022-01-05 at 16 59 17" src="https://user-images.githubusercontent.com/12524972/148248843-533f95d0-4fe5-4e6d-bf4c-8eb230a6ccc4.png">

**Comment by markotoplak** [comment]
I think that you should have divided TP with the number of positives in the data. And averages are weighted averages. So, CA and recall, respectively:

```
>>> (146+112)/303
0.8514851485148515
>>> 146/164*164/303 + 112/139*139/303
0.8514851485148515
```

To compute a useful recall the users have to select the target class. If they do not, the (weighted) average is used. And in (weighted) averaged recall, the P part cancels out and we get CA. Fun, isn't it? So I'd say that recall seems OK.

To get useful recall scores, users have to select the target class.

**Comment by janezd** [comment]
The same is then true for F1. But don't we just take one class as target?! Like in, say, nomogram?

**Comment by markotoplak** [comment]
Yea, there is a combo in the UI which allows you to do just that. :)

**Comment by markotoplak** [comment]
The Predictions widget is missing the target class value selector box though.

**Comment by janezd** [comment]
We could move "Target class combo" above "Evaluation Results" and "Model Comparison" above "Model Comparison".. 

Predictions needs combo for choosing the target class.

**Comment by janezd** [comment]
Would this look OK? I removed box titles not only because they're redundant but mostly because they made everything look messy (they use a smaller font and are placed outside the flow).

I like what this change does to the left side.

<img width="805" alt="Screenshot 2022-01-08 at 10 32 16" src="https://user-images.githubusercontent.com/2387315/148639290-09c99dac-2222-4c1f-8bc0-31df035a7890.png">

**Comment by markotoplak** [comment]
I like it! Thanks!
