### ISSUE TITLE
Add-Ons do not show up

### ISSUE THREAD

**Issue by DUTOrange** [biolab/orange3#5775]
**What's wrong?**

My workflow included frequent itemsets but when I open, it shows:
![image](https://user-images.githubusercontent.com/97541876/148994432-f245dd9f-5f75-42f6-b51d-cb3d8fc2203e.png)
It then installs and demands that I restart the application. After it restarts, the association widgets are not to be found in workflow or in widget bar.
![image](https://user-images.githubusercontent.com/97541876/148995572-49855940-30a9-4ceb-bbbe-117403772891.png)
 I often get an error message:
![image](https://user-images.githubusercontent.com/97541876/148995172-5d6d5e21-1466-48e1-8e65-b4ca4c0074b1.png)
 
Thanks

**How can we reproduce the problem?** 

Use older version of Orange and create a workflow with frequent rules and itemset. Save workflow
Upgrade Orange when prompted
Open saved workflow. Should inform you that it needs to install associate add-ins. If you choose add-in, it will download add-in and then ask to restart. After restarting, widgets do not show on canvas or on widget bar.

**What's your environment?**

- Operating system: Windows 11
- Orange version:3.31
- How you installed Orange: downloaded and installed off Orange website; latest upgrade seemed to have affected add-ins. Could use frequent itemset before latest upgrade

**Comment by ajdapretnar** [comment]
Would you mind pasting here the entire error message? Thanks!

**Comment by DUTOrange** [comment]
When I open a workflow with a frequent itemset (created in an earlier version) and then try to add on the Associate Add-In, it gives me an error message

Stack Trace:
Traceback (most recent call last):
  File "C:\Program Files\Orangev3\lib\site-packages\orangewidget\workflow\mainwindow.py", line 230, in closeEvent
    super().closeEvent(event)
  File "C:\Program Files\Orangev3\lib\site-packages\orangecanvas\application\canvasmain.py", line 2256, in closeEvent
    document.usageStatistics().close()
  File "C:\Program Files\Orangev3\lib\site-packages\orangecanvas\document\usagestatistics.py", line 441, in close
    UsageStatistics.statistics_sessions.remove(self)
ValueError: list.remove(x): x not in list

Local Variables:
OrderedDict([('self',
              <orangecanvas.document.usagestatistics.UsageStatistics object at 0x000001566EB5CB20>)])
I hope this helps

Cheers, Rich Millham

________________________________

**Comment by markotoplak** [comment]
Thanks for the report. These seem like two separate issues. 

I tried installing Associate onto a fresh Orange 3.31.0 installation (from the .exe installer from the webpage) and Associate installed fine for me.

What confuses me is that you report a similar setup. Could you perhaps open the Orange command prompt and try manual install: `conda install orange3-associate`.  Does it report any errors?

Then, run orange with `orange-canvas -l4`. What is the output to a terminal? Thanks!

**Comment by DUTOrange** [comment]
Hi. I had version 3.14.0 installed apparently (an old version which was called when I tried to open Orange). I downloaded (or rather it asked me to upgrade) to 3.31. The add-ons now work. Each upgrade will install in a new folder, as you know.
Incidentally, how do you open the Orange command prompt. I went into the Orange folder and there is a file called "Orange Command prompt" but it is a .bat file which, of course, does not allow me to enter any commands.
"Could you perhaps open the Orange command prompt and try manual install: conda install orange3-associate. "
Thanks Marko.

Cheers, Rich Millham

________________________________

**Comment by DUTOrange** [comment]
Thank you, Janez.

Cheers, Rich Millham

________________________________
