### ISSUE TITLE
Wish make  Test and Score & Confusion Matrix  report to structure data and can be saved automaticaly.

### ISSUE THREAD

**Issue by yuanxin-cq** [biolab/orange3#5777]
The pain points as below:

1.When we do a batch data process in Orange3,  Test and Score & Confusion Matrix  only can be saved one by one by hand and only can be saved in HTML.
2.It is painful to compare  batch of  reports in HTML, when do  parameter optimization.
3.It is hard to  compare , monitor Test and Score & Confusion Matrix  history continuously. 

Suggestion as below: 
1.Wish can make  Test and Score & Confusion Matrix report in structure data.
2.Wish can output report data to a datatable wideget. 
In this way, we can easily save report into database by python script widget.  

![pic](https://user-images.githubusercontent.com/2495454/149075557-e8d4a30b-3951-4569-a0a0-7966ede8a629.png)

**Comment by janezd** [comment]
Thank you for your suggestion. We discussed it at today's internal meeting and the main objection (at least mine) was that the usual tabular output has variables as columns and instances as rows, while confusion matrix is of a different kind. While its data could be put into ordinary table, this would be semantically wrong and thus wouldn't be very useful in other widgets, except for trivial cases like saving.

There is, however, a widget that already commits exactly this sin and is also useful for solving your problem. Use the Pivot widget, like this. It essentially constructs the confusion matrix and outputs it as a table that you can see and/or save.

<img width="634" alt="Screenshot 2022-01-14 at 09 58 49" src="https://user-images.githubusercontent.com/2387315/149487782-ab43331b-1343-4c63-8584-3c9fcba19f22.png">
