### ISSUE TITLE
Preprocess Text now in Transform category instead of Text

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#5783]
**What's wrong?**

After #5712, Preprocess Text is not put into Transform category instead of Text.
![Screen Shot 2022-01-14 at 10 32 19](https://user-images.githubusercontent.com/12524972/149494838-fb5c0594-0bcd-45a9-8daf-a7aaf9963433.png)

**How can we reproduce the problem?** 

Open Transform category with Text add-on installed.
The issue is not resolved even after running `--force-widget-discovery`.

**What's your environment?**

- Operating system: OSX
- Orange version: 3.31.1.dev
- How you installed Orange: pip

**Comment by markotoplak** [comment]
The problematic widget subclasses `Orange.widgets.data.owpreprocess.OWPreprocess`. I'd say it is `Preprocess Text`'s fault.

**Comment by ajdapretnar** [comment]
Is it though? Would its location in `orangecontrib.text `not take precedence? How does one fix this anyway? Specifically define `category=Text`?

**Comment by markotoplak** [comment]
The problem is that this widget now specifically defines category=Transform, because it subclasses a widget with that definition. And the definition needs to take precedence, otherwise we can never move any widget. So the subclassing (naughty :) ) widget needs to "undefine" it.

**Comment by ajdapretnar** [comment]
Aaaaa, got it! This makes sense (in a way). Ok, no problem, I will "undefine" it. :)
