### ISSUE TITLE
Feature Request: Quantile Regression

### ISSUE THREAD

**Issue by kkujaws1** [biolab/orange3#5789]
**What's your use case?**
 I am unable to find a low or no-cost GUI and workflow centric tool to perform quantile regression (e.g., rather than predicting the 50th percentile, predicting the 75th percentile).
 There is no problem in Orange or the underlying Python tools.
I am working with healthcare data and in some areas, it would be great to develop predictors of what 75th, 90th, 30th, etc. percentile performance would look like. I am far from a Python or R programmer. Orange has been a Godsend tool for me to go beyond the limitations of Excel and to avoid the costly licenses and (re)learning curve of SPSS. I see toolkits for R and Python but I am not fluent with those tools: https://scikit-learn.org/stable/auto_examples/linear_model/plot_quantile_regression.html

**What's your proposed solution?**
Add multi-variate quantile regression capabilities to Orange.

**Are there any alternative solutions?** Perhaps integration with scikit's Python tools: https://scikit-learn.org/stable/auto_examples/linear_model/plot_quantile_regression.html

**Comment by janezd** [comment]
Thanks for the idea. We shall have this in mind when implementing #5733. (I referenced this issue there, so I'm closing it for the sake of cleaning up. It won't be forgotten.)
