### ISSUE TITLE
Linkage option “Ward” not documented for Hierarchical Clustering widget

### ISSUE THREAD

**Issue by kaimikael** [biolab/orange3#5797]
**What's wrong?**

The Hierarchical Clustering widget has a drop-down menu for **Linkage** options.  The last one is called “Ward”, but has not been added to the documentation.  See attached screen shots.

<img width="240" alt="Screenshot 2022-01-20 at 09 32 07" src="https://user-images.githubusercontent.com/10616212/150302938-c9879526-336a-438b-8cc1-483f29a396f1.png">
<img width="747" alt="Screenshot 2022-01-20 at 09 33 33" src="https://user-images.githubusercontent.com/10616212/150302941-21f288e9-1992-4e13-bf19-ade4bfa49395.png">

**How can we reproduce the problem?** 

Add Hierarchical Clustering widget to canvas, open it, check available options in the Linkage menu, open the help by pressing **?**, compare.

**What's your environment?**

- Operating system: macOS 12.1
- Orange version: 3.31.1
- How you installed Orange: From the installer at https://orangedatamining.com/download/#macos

**Comment by ajdapretnar** [comment]
That's embarrassing. Thanks for reporting it!
