### ISSUE TITLE
widget (apply domain) bug with PCA

### ISSUE THREAD

**Issue by leaf918** [biolab/orange3#5805]
**What's wrong?**
cannot transform data as expecting.
![image](https://user-images.githubusercontent.com/170311/151140688-563b3492-d243-4c28-9f21-c250b5817cab.png)

![image](https://user-images.githubusercontent.com/170311/151142017-b9016b01-bce9-44fb-b268-2727aa5825f6.png)
the transformed data is wrong.

### **the following image represented the expecting correct transformed data.**

![image](https://user-images.githubusercontent.com/170311/151141501-f19005d7-b2da-405e-9f77-3bf74b5bdd0a.png)

**How can we reproduce the problem?** 

[superpixel_0124.zip](https://github.com/biolab/orange3/files/7940610/superpixel_0124.zip)

**What's your environment?**

- Operating system: linux
- Orange version:3.31.1
- How you installed Orange: conda

**Comment by markotoplak** [comment]
Orange seems to work as expected. If you, instead, connect the "Transformed Data" as "Template Data"  into Apply Domain, the transformation should work correctly.

The "Components" output of the PCA widget can not be used as transformation template. I understand why this is confusing: the components are indeed used internally when computing PCA scores, but the Apply Domain widget does not know that. It only has a input "Template Data" which applies whatever transformation was applied the given template data onto the new data set. Therefore,  the "Transformed Data" should be the template data.

Thanks for your report, it is indeed an interesting insight into how users would think in these type of scenarios. A similar explanation could be a good addition to the documentation.

**Comment by leaf918** [comment]
Yes,it works well for me .
the term 'template data' is confused,for me ,the PCA's output is clean ,but the components of PCA can be applied to any other components ,it's strange.
![image](https://user-images.githubusercontent.com/170311/151160943-8dc98d18-8777-4c71-9ad4-63912641b8c4.png)

Thanks.

**Comment by markotoplak** [comment]
To apply PCA you need more than just Components:
- you need to know the center of each columns
- (optional) you need to know the variance of each column, if Normalization was used
- (data dependent) you need to know how the data was converted into continuous, if there were any nominal columns

So that is why you can not use Apply Domain with components. They have a distinct meaning, you can visualize and interpret them in other widgets, though.
