### ISSUE TITLE
FR: Logistic Regression without Regularization

### ISSUE THREAD

**Issue by dsanalytics** [biolab/orange3#5816]
Would it be possible to have no-regularization option for LR widget? Right now, it's not possible to test "pure" LR. Thank you in advance.

![image](https://user-images.githubusercontent.com/32625394/152093438-42d3dcbb-e960-4766-ada5-3c6a546cbe55.png)

Env: Windows + Orange 3.31

**Comment by markotoplak** [comment]
Why is setting the regularization to very weak insufficient in your case? What is your use case?

**Comment by dsanalytics** [comment]
@markotoplak use case is serious research - very weak is not the same as off in science. 2 + 2 + 0.00001 is not the same as 4 in science. Saying: "Dear reader, I cannot turn this off, but trust me, it's very weak", does not look professional at all.

**Comment by janezd** [comment]
I agree with @markotoplak. Why would anyone want to use LR without regularization? It would not not look professional at all.

**Comment by dsanalytics** [comment]
@janezd I do not want to get into a debate, but I disagree. IMHO, regularization is the worst type of solution to overfitting. 
I guess this is another sklearn devs decision - hence I do not blame Orange.

**Comment by markotoplak** [comment]
Actually, blame Orange for this one. Scikit-learn allows no-regularization.

I vote for adding the no regularization option into the widget. I like how explicit that is, and might be useful when teaching classes. Orange does have that option with linear regression, why not here? When teaching, we worked around that by focusing on linear regression when explaining regularization, but why effectively block a similar lesson with log reg?

**Comment by dsanalytics** [comment]
@markotoplak in case you are putting reg-off option for NNs too, please check https://github.com/biolab/orange3/issues/5818 Thanks.

**Comment by dsanalytics** [comment]
@markotoplak @ajdapretnar can you open this now? I completely agree with Marko's reasoning:
> I like how explicit that is, and might be useful when teaching classes. Orange does have that option with linear regression, why not here? When teaching, we worked around that by focusing on linear regression when explaining regularization, but why effectively block a similar lesson with log reg?

**Comment by dsanalytics** [comment]
@markotoplak I'm quite certain that you're very busy, but would you mind giving some update with target dates for this? It's been more than 2 months. Thanks.

**Comment by dsanalytics** [comment]
@ajdapretnar @markotoplak I'm quite certain that you're very busy, but would you mind finishing this? It's been almost 6 months. Thank you.

**Comment by markotoplak** [comment]
@dsanalytics, thanks for the reminder.

But your tone offends me. Who are you to boss us around? What makes you think that you can do that? Have you contributed meaningfully to the project? Did you perhaps donate anything toward the cause? Or are you willing to hire programmers to implement this feature?

We will implement it when we feel like it and the more you bug us the later that is going to be.

**Comment by dsanalytics** [comment]
@markotoplak @janezd @ajdapretnar

Dear Marko, 

My humble contribution are suggestions/ideas and bug reports submitted over the years. Not big, but not nothing either. Orange team fixed some of those bugs and implemented some of those ideas, which made Orange a better product/tool IMHO.

Re this feature: You said "I vote for adding the no regularization option into the widget. ... ", which made me glad that I suggested something you liked too, and then you went MIA. And then you interpreted my polite reminder after 4 months as bossing you around. So how does not-bossing-you-around reminder sound like according to you? Also, how is one supposed to know whether you simply forgot, as opposed to being triggered and thin-skinned?

Last but not least, if you respond to peoples polite/respectful and infrequent suggestions/reminders with rudeness, how is that going to make them hold the team in high regard? I'm thick-skinned, so it's not a big deal, but many people are not and would make a mountain out of a molehill.

Regards

**Comment by ajdapretnar** [comment]
Since you're involving me in the discussion for some reason, I'll add my two cents.

We are an open source project. Anyone can contribute. What we do for Orange, we do in our free time or strictly tied to the funded projects. Anything outside of funded project tasks is our good will and our free time.

While providing suggestions for software improvement is good, it is the easy part. The hard part is integrating the change, testing it, writing documentation. This takes time and effort. So we prioritize tasks that are a) relevant to our current projects, b) beneficial for a wider Orange audience (usually bug fixes), and c) interesting to us. If we like the proposal, this does not in any way mean we will work on it any time soon. It is simply a statement that the suggestion is useful and that any contributor is welcome to resolve the issue.

In this spirit, if you deem the issue so important, feel free to submit the change yourself. Or hire someone who will, this is up to you.

**Comment by dsanalytics** [comment]
@ajdapretnar @janezd 

I only cc-ed, so to speak, you and the professor to keep you in the loop - that's all. 

Regards

**Comment by dsanalytics** [comment]
@janezd @ajdapretnar @markotoplak 

Thank you all - appreciated.
