### ISSUE TITLE
FR: Neural Network without Regularization

### ISSUE THREAD

**Issue by dsanalytics** [biolab/orange3#5818]
I know that very small alpha is essentially no regularization, but would it be possible to have zero for alpha as the left-most value on that slider, plus to have the label change to "Regularization: Off" if alpha set to zero? It'd just look more professional and easier to check visually. See 2 screenshots for what I mean. Thank you in advance.

![image](https://user-images.githubusercontent.com/32625394/152096369-2fe961fb-f7cc-4916-957a-2b00c1056e77.png) ![image](https://user-images.githubusercontent.com/32625394/152096476-76e5955f-a337-4ea7-891a-ca550e5ead8f.png)

Env: Windows + Orange 3.31

**Comment by janezd** [comment]
Resolved in #5824.
