### ISSUE TITLE
Color regions change when setting opacity of points

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#5825]
##### Geo version

0.2.8

##### Orange version

3.27.dev

##### Expected behavior
Color regions stay the same irrespective of point opacity. Or at least are as opaque as the points.

##### Actual behavior
Color regions randomly change when changing point opacity.

##### Steps to reproduce the behavior
Datasets (Philadelphia Crime) - Geo Map.
Color points. Set Color regions. Then drag the slider for opacity.

**Comment by janezd** [comment]
You can also observe this effect in scatterplot. If the number of points is above 1000, `class_density_image` takes 1000 points, sampled uniformly from a grid of buckets (see `Orange.widget.utils.classdensity.grid_sample`).
