### ISSUE TITLE
FR: Add Specificity to Test & Score and Predictions widgets reports grids

### ISSUE THREAD

**Issue by dsanalytics** [biolab/orange3#5831]
You have 4 out of 5 [1] the most important measures for CM in those grids in Test & Score and Predictions widgets. Could you add the 5th one, Specificity? A you know, it is important for ROC and many other things. Both grids shown [2].

[1] The list: 
- Precision
- Specificity (missing)
- Sensitivity = Hit Rate = Recall
- F1
- Accuracy = Classification Accuracy (CA)

[2] Grids
![image](https://user-images.githubusercontent.com/32625394/152626440-cbf6bbf3-8160-4d1d-bce8-9a5d478f104f.png)

**Comment by ajdapretnar** [comment]
Please refer to the documentation before opening an issue.

> The widget will compute a number of performance statistics. A few are shown by default. To see others, right-click on the header and select the desired statistic.
