### ISSUE TITLE
FR: Data Sheet widget - new spreadsheet-like data container widget

### ISSUE THREAD

**Issue by dsanalytics** [biolab/orange3#5832]
Currently, Orange does not seems to be self-contained as far as input data is concerned - i.e. not counting Paint Data widget. There's no widget to allow data to be just pasted or one-time imported into a grid just as one can do with Excel. If file/spreadsheet is used as the main source of data and consumed with File widget, then one needs to carry that file around along with the OWS file. Otherwise, changing the data to experiment - e.g. deleting a row or manually changing values in cells - becomes a hustle. Also, what if the source file is misplaced? Being self-contained is a basic feature for a DS tool. OWS file containing editable data it uses makes collaboration easy - e.g. sharing work between colleagues, sending results to someone for a follow up work, students submitting home work assignments, etc.

So I'd like to propose a Data Sheet widget - a simple grid-like table that one can paste data rows and header row into, edit manually including column names, select multiple rows to copy/delete them, sort, etc. - again pretty much as one can do in Excel with basic editing without any macro functions. Something that looks like Data Table but editable yet without allowing filtering by selection as DT allows - i.e. it should always send all data that's in it. I think that this would make Orange even better.

What do you think? Thank you in advance for considering it.

**Comment by janezd** [comment]
We are not going to implement Excel in Orange, this would be way too much work. You have four options:

- use files,
- use Google Sheets,
- use other DS tools, which are better than Orange (which is not professional at all),
- implement this feature yourself and submit the PR; we will gladly accept it (if you also promise to maintain it whenever there's a substantial change in Qt or our codebase).

**Comment by dsanalytics** [comment]
Nobody has asked for Excel - not sure where are you getting all this from professor. Just a simple grid, without any macro functionality, that allows input and basic editing of cells and storing of that data in OWS itself - just as I described. Although I've never used Qt, I'd not be surprised if ready-made OSS data editing grids are available. Think about it. Thank you advance.

**Comment by markotoplak** [comment]
There is a widget like this in the educational add-on: Create Table, but it is very basic. Making friendly UI as you suggest - even without computation - is not trivial. This is not a priority for the core team currently. But if anyone is willing to add it (if there is a Qt component that does it, even better), feel free.

**Comment by dsanalytics** [comment]
@markotoplak I understand - thank you.
