### ISSUE TITLE
getting error while installing it using python. I am using Ubuntu 20.04. 

### ISSUE THREAD

**Issue by cpagrawal** [biolab/orange3#5853]
installation error. 
![image](https://user-images.githubusercontent.com/23192500/154811752-2c81bc5b-df46-460b-8f3f-bed8d533cebb.png)

**Comment by thocevar** [comment]
This looks like a package version conflict. Which Python version are you using? You could try updating numpy first (`pip install -U numpy`) and then rerun Orange installation.

**Comment by markotoplak** [comment]
To me it also seems that you are trying to install Orange into the system python? To confirm this, did you have to use `sudo` with command?

External python packages should not be mixed with system python in Ubuntu (or Debian). Sometimes it will work, but sometimes you will break some other functionality. Therefore, when installing packages with pip, create a new python environment either with `virtualenv` or perhaps `conda`.

**Comment by cpagrawal** [comment]
thank you for help. it works now. 
@markotoplak  creating the virtual environment is good idea. I was working late night and it did not come in my mind. Thanks.
