### ISSUE TITLE
Ubunto 20.04 Installation Problem

### ISSUE THREAD

**Issue by spgva26** [biolab/orange3#5856]
I tried to install orange on my pc which the OS is ubuntu. I followed the pip installation as recommended on the orange website. When I run the command "python3 -m Orange.canvas" I get the following error.
AttributeError: module 'numpy.random' has no attribute 'BitGenerator'

**Comment by thocevar** [comment]
Which version of python (`python3 --version`) and numpy (`pip3 list | grep numpy`) are you using? I've just successfully installed Orange on a clean Ubuntu 20.04 with pip.

**Comment by spgva26** [comment]
Python 3.8.10
numpy 1.17.4

**Comment by spgva26** [comment]
Python 3.8.10
numpy 1.17.4

**Comment by thocevar** [comment]
Try updating numpy to the latest version (`pip install -U numpy`). Also consider using a virtual environment to avoid breaking any other dependencies by this update.

**Comment by spgva26** [comment]
Updating numpy solved it. Thank you
