### ISSUE TITLE
Save Data: autosave is deactivated

### ISSUE THREAD

**Issue by mw25** [biolab/orange3#5868]
**What's wrong?**

The Autosave-Checkbox in Save Data deactivates itself at every restart of Orange, though workflow and target path are in the same directory.

**How can we reproduce the problem?** 

I think it is a Windows-Issue:

Here:
https://github.com/biolab/orange3/blob/5f06ada600eac42138e362bba566824e69e7cd3a/Orange/widgets/utils/save/owsavebase.py#L116-L120

workflow_dir is a path with backslashes: "C:\\\\Users\\\\test\\\\Desktop\\\\TestDir"
absolute_path is a path with slashes: "C:/Users/test/Desktop/TestDir"
So `absolute_path.startswith(workflow_dir.rstrip("/"))` will always be false and the absolute path is written to `self.stored_path`.

**What's your environment?**

- Operating system: Windows 10
- Orange version: 3.32.0 dev
- How you installed Orange: clone from github

**Comment by janezd** [comment]
@mw25, thanks for another detailed report.

Almost nobody of core developers uses Windows. @thocevar could look into it ... but could you try fixing it and submitting a fix yourself? It seems it would suffice to call [os.path.normpath](https://docs.python.org/3/library/os.path.html#os.path.normcase) on both paths. On Windows, it will replace backslashes and also make the name case-insensitive, which is also necessary for this to work correctly.

**Comment by mw25** [comment]
Sorry for the delay in responding. I was not informed about your answer for some reason.

I will do a pull request as you suggest.
