### ISSUE TITLE
Orange.data.Table's is_view and is_copy do not work for sparse matrices: deprecate them

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#5878]
`Table.is_view` and `Table.is_copy` do not work for sparse matrices.

I do not think they are that useful because they are a conjunction of so many conditions. I think we should deprecate them instead of fixing them. PyCharm only finds one usage in the Orange3 repo, and even that in the tests.

So, I would deprecate and remove in Orange 3.33.

**Comment by janezd** [comment]
I support removing stuff that nobody uses, in particular if it's a method of `Table`.
