### ISSUE TITLE
Orange Installation Problem

### ISSUE THREAD

**Issue by spgvieira** [biolab/orange3#5883]
Hi! I keep getting the following problem when installing orange through pip on my pc with ubuntu. Any advice?

> pip install orange3
Defaulting to user installation because normal site-packages is not writeable
Collecting orange3
  Using cached Orange3-3.31.1.tar.gz (26.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      setup.py:173: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
        import imp
      running egg_info
      creating Orange3.egg-info
      writing Orange3.egg-info/PKG-INFO
      writing dependency_links to Orange3.egg-info/dependency_links.txt
      writing entry points to Orange3.egg-info/entry_points.txt
      writing requirements to Orange3.egg-info/requires.txt
      writing top-level names to Orange3.egg-info/top_level.txt
      writing manifest file 'Orange3.egg-info/SOURCES.txt'
      Cannot compile extensions. numpy and cython are required to build Orange.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by ales-erjavec** [comment]
Which version ubuntu, which version of Python, which version of pip?

From the output you it appears you do not have numpy or cython installed which are required for building from source. Note that this should be automatically handled as long as you have a sufficiently recent version of pip, which you probably do not. The best solution is to create a separate virtual environment for orange with a more recent pip version (**do not** try to upgrade the system provided pip):

```
python -m venv ~/.envs/orange3
source ~/.env/orange3/bin/activate
pip install -U pip
pip install orange3
```

**Comment by spgva26** [comment]
numpy                         1.22.3
Cython                        0.29.28
pip 22.0.4
Description:	Ubuntu 20.04.4 LTS
These are the versions the error keeps happening in the virtual environement

**Comment by janezd** [comment]
A lot of time has passed and we have not responded. In the meantime, there have been several new versions of Orange so the problem may have been resolved. @spgvieira, are you still interested and can you please try again?
