### ISSUE TITLE
Truncated violin plots

### ISSUE THREAD

**Issue by chourroutm** [biolab/orange3#5886]
**What's your use case?**

Most plotting and analysis software implement a truncated version of the violin plots (no upper or lower tail). This can be convenient to avoid negative values for measures that would have no physical sense, like concentrations in my use case.

The attached image shows how it renders in GraphPad Prism:
![Screenshot from 2022-03-10 15-39-25](https://user-images.githubusercontent.com/83714683/157686282-8e1319c1-f8e5-4858-a0db-928588a56a96.png)

**What's your proposed solution?**

Implementing a version of the violin plots that is truncated to the maximum and minimum values of the variable to display.

**Are there any alternative solutions?**
Exporting plots to SVG and cutting the tails of the violin plots, for example using Inkscape.

**Comment by janezd** [comment]
This makes sense. We discussed that it should be implemented via #5377, so I'm closing this (and we'll notice a reference there).
