### ISSUE TITLE
Python Script crashed Orange3

### ISSUE THREAD

**Issue by jianlao8** [biolab/orange3#5895]
Hello,

    Each time I ran the python script of the link (https://tda-api.readthedocs.io/en/latest/client.html) for TDA HTTP Client in Python Script Widget, the Orange3 crashed. I have to restart the Orange3 again.

    Can someone help to resolve this issue?

Thank you!

**Comment by markotoplak** [comment]
Could you provide a bit more info? Like you Orange version, how you installed, OS, and any info about the specific way Orange crashes.

Also, the code you linked requires that the tester sets a server (it seems to connect to localhost). Can you make a short code that uses a public server, so that we could just copy-paste and run? If you make it easy for us to replicate the problem, it will get solved sooner. :)

**Comment by jianlao8** [comment]
Hello,
    Thanks for your reply!
     My Orange 3 version is 3.31.1 and it is running on Windows 10  version 21H1. The code is running fine on Jupyter Notebook 6.4.8 on the same PC. The localhost is just set for the authentication. You can give any token and APIKEY that will give you an authentication error when running on Jupyter Notebook. I haven't tried on Linux because I have trouble installing Orange 3 in my Raspberry Pi 4B. You can help me to try Raspian 64bit that may not crash. 
 Thank you!

**Comment by jianlao8** [comment]
Where to get the error log?

**Comment by ajdapretnar** [comment]
Forgot you are probably running Orange as application in Windows. You can open Orange Command Prompt and run Orange there with `python -m Orange.canvas`. Try the script and post the log that appears in the command prompt after Orange crashes.

**Comment by ajdapretnar** [comment]
Orange Command Prompt is a separate app. You can find and run it with your regular app search (Windows key, search for Orange).

**Comment by jianlao8** [comment]
(stratigies) C:\Users\xxxx\TDAmeritrade>python -m Orange.canvas
C:\Users\xxxx\.conda\envs\stratigies\lib\site-packages\Orange\widgets\data\owpythonscript.py:538: UserWarning: register 'summarize' function for type object. To silence this warning, set auto_summary of 'Object' to False.
  object = MultiInput(
C:\Users\kenla\.conda\envs\stratigies\lib\site-packages\Orange\widgets\data\owpythonscript.py:542: UserWarning: register 'summarize' function for type object. To silence this warning, set auto_summary of 'Object' to False.
  class Outputs:
2022-03-15 11:20:34,799:ERROR:tda.auth: No webdriver_func set, cannot fetch token
Error in atexit._run_exitfuncs:

**Comment by markotoplak** [comment]
This is likely not an Orange issue.

I can not run the script you linked a a normal Python interpreter (not ipython, not jupyter) either. Python 3.7, on MacOS, with tda-api installed from pip, copied the code into the python interpreter (terminal) directly, and I get the same kind of crash you report. Orange was not used at all.

Therefore I am closing the issue. But am willing to reopen it, if you produce a script that:
1. Works in a normal python interpreter (jupyter or ipython often use additional "magic")
2. Does not work from a python script widget.

Also, provide which packages does a user need to install for testing.

Thanks!

**Comment by jianlao8** [comment]
Hi, 
Following is my python script that ran on Jupyter Notebook on the same PC which is running Orange3.



![image](https://user-images.githubusercontent.com/98107838/158634620-819ad516-4b8a-417d-ac0f-472de1a6c989.png)

**Comment by jianlao8** [comment]
Sorry,

The script on the TD link is missing "import httpx"
After adding to the script it worked in a Python Script Widget.
Case closed!

Thanks!
