### ISSUE TITLE
Find informative projections: Keep reproducible order of ranked variable pairs

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#5900]
**What's wrong?**

Running Find informative projections sometimes returns different order of variable pairs. This happens when two or more pairs have the same score and they are ranked randomly. This is a little confusing when the order on two machines is not the same.

Ideally, we would have reproducible ranking all the time. The easy way is to order variable pairs with same scores alphabetically.

**How can we reproduce the problem?** 

Datasets (Auto MPG) - Scatter Plot. Find informative projections.
<img width="432" alt="Screenshot 2022-03-17 at 08 55 46" src="https://user-images.githubusercontent.com/12524972/158764213-25cc44bf-3ab4-4690-8183-a371ab5cb9e6.png">
<img width="432" alt="Screenshot 2022-03-17 at 08 55 50" src="https://user-images.githubusercontent.com/12524972/158764232-23c15bbb-42dd-4e13-9e8c-e8ac3949b6ce.png">

**What's your environment?**

- Operating system: OSX
- Orange version: 3.32.dev
- How you installed Orange: pip

**Comment by markotoplak** [comment]
Does a problem also appear on the same computer and Orange installation?

**Comment by janezd** [comment]
Comment & Idea: `Orange.widgets.visualize.utils.run_vizrank`, which does the actual work, calls `bisect.bisect_left(scores, score)` to find the position for the score, where `scores` is a list of scores and `score` is the newly computed score. If we wanted to sort by attribute names (or whatever) as secondary keys, we could add this additional info (tuple of names) to `scores`.

While this is doable (the `score` attribute is rather internal-ish), but I'd very much prefer if we investigate another approach. There is (I suppose) nothing random in `bisect.bisect_left`. VizRank explores attributes in some specific order, defined by some heuristic. Maybe it would suffice to make this heuristic stable, e.g. by observing attribute names in case of ties.

**Comment by janezd** [comment]
As a matter of fact -- it already sorts by name. :) https://github.com/biolab/orange3/blob/master/Orange/widgets/visualize/owscatterplot.py#L98.

Randomness must be coming from ReliefF's sampling.
