### ISSUE TITLE
Show error by color in Predictions

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#5901]
**What's your use case?**

I want to observe regression predictions in Predictions widget. Currently, I only see numbers. It would be nice to have a visual signal in Predictions for how close the prediction is to the true value.

**What's your proposed solution?**

Perhaps give each instance a line below, showing the error. Currently, classification problems display a line underneath with probabilities. For regression, the longer the line, the greater the error (would this be confusing, because for classification longer lines mean higher probability?).

**Are there any alternative solutions?**
/

**Comment by janezd** [comment]
I would expect that the line length would correspond to the prediction. Except, perhaps: we would put a tick in the middle of the cell and then a red line would extend from the tick to the left (or right), showing the negative (or positive) error.

**Comment by janezd** [comment]
For classification, we could emphasize the correct class (by making others more transparent)
