### ISSUE TITLE
cannot install Image Analytics add-on: wrapped C/C++ object of type QWindow has been deleted

### ISSUE THREAD

**Issue by xliu019** [biolab/orange3#5905]
**What's wrong?**

When l was installing Image Analytics add-on, l encountered the following error: 

Exception:
RuntimeError: wrapped C/C++ object of type QWindow has been deleted
Module:
orangecanvas.application.addons:1139
Version:
3.31.1
Environment:
Python 3.8.8 on Windows 10 10.0.19041 AMD64
Installed Packages:
AnyQt==0.0.13, Bottleneck==1.3.2, CacheControl==0.12.10, Orange3==3.31.1, Pillow==8.4.0, PyQt5-sip==4.19.18, PyQt5==5.12.3, PyQtChart==5.12, PyQtWebEngine==5.12.1, PySocks==1.7.1, PyYAML==6.0, Pygments==2.11.2, QtPy==2.0.0, XlsxWriter==3.0.2, anyio==3.4.0, backcall==0.2.0, backports.functools-lru-cache==1.6.4, baycomp==1.0.2, brotlipy==0.7.0, catboost==1.0.3, certifi==2021.10.8, cffi==1.15.0, chardet==4.0.0, charset-normalizer==2.0.10, colorama==0.4.4, commonmark==0.9.1, cryptography==36.0.1, cycler==0.11.0, debugpy==1.5.1, decorator==5.1.1, dictdiffer==0.9.0, docutils==0.18.1, entrypoints==0.3, et-xmlfile==1.0.1, fonttools==4.28.5, future==0.18.2, h11==0.12.0, h2==4.1.0, hpack==4.0.0, httpcore==0.13.7, httpx==0.19.0, hyperframe==6.0.1, idna==3.1, importlib-metadata==4.10.0, ipykernel==6.6.1, ipython-genutils==0.2.0, ipython==7.31.0, jedi==0.18.1, joblib==1.1.0, jupyter-client==7.1.0, jupyter-core==4.9.1, keyring==23.4.0, keyrings.alt==4.0.2, kiwisolver==1.3.2, lockfile==0.12.2, matplotlib-inline==0.1.3, matplotlib==3.5.1, msgpack==1.0.3, munkres==1.1.4, nest-asyncio==1.5.4, networkx==2.6.3, numpy==1.19.5, olefile==0.46, openTSNE==0.6.1, openpyxl==3.0.9, orange-canvas-core==0.1.24, orange-widget-base==4.16.1, packaging==21.3, pandas==1.3.5, parso==0.8.3, pickleshare==0.7.5, pip==21.3.1, prompt-toolkit==3.0.24, pyOpenSSL==21.0.0, pycparser==2.21, pyparsing==3.0.6, pyqtgraph==0.12.3, python-dateutil==2.8.2, python-louvain==0.15, pytz==2021.3, pywin32-ctypes==0.2.0, pywin32==303, pyzmq==22.3.0, qasync==0.22.0, qtconsole==5.2.2, requests==2.27.1, rfc3986==1.5.0, scikit-learn==0.23.2, scipy==1.5.3, serverfiles==0.3.0, setuptools==60.3.1, six==1.16.0, sniffio==1.2.0, threadpoolctl==3.0.0, tornado==6.1, traitlets==5.1.1, typing-extensions==4.0.1, unicodedata2==14.0.0, urllib3==1.26.8, wcwidth==0.2.5, wheel==0.37.1, win-inet-pton==1.1.0, xlrd==2.0.1, zipp==3.6.0
Machine ID:
2877f3f4-65e3-4e33-92f2-41b2203496dd
Stack Trace:
Traceback (most recent call last):
  File "C:\Program Files\Orange\lib\site-packages\orangecanvas\application\addons.py", line 1139, in restart
    if any(w.isVisible() for w in windows):  # if a window close was cancelled
  File "C:\Program Files\Orange\lib\site-packages\orangecanvas\application\addons.py", line 1139, in <genexpr>
    if any(w.isVisible() for w in windows):  # if a window close was cancelled
RuntimeError: wrapped C/C++ object of type QWindow has been deleted

May l know what should l do?

**How can we reproduce the problem?** 

**What's your environment?**

- Operating system:
- Orange version:
- How you installed Orange:

**Comment by janezd** [comment]
@xliu019, @ales-erjavec will look into it. This may be difficult to debug and reproduce, though.

Does it happen every time you try it, or does it perhaps succeed if you restart Orange?

**Comment by xliu019** [comment]
It happens every time l try it, even after reinstalling Orange. @janezd @ales-erjavec

**Comment by ales-erjavec** [comment]
I cannot duplicate this. 

When you do the install do you have multiple orange windows open? Possibly with changes in them. I.e. does it ask to save before closing?

Also do you have the Orange's *Help* window opened when installing?

**Comment by xliu019** [comment]
![Orange_1](https://user-images.githubusercontent.com/6997360/159449245-16c02a60-890a-40d3-b8c1-04f788d85ad0.png)
![Orange_2](https://user-images.githubusercontent.com/6997360/159449252-c56cd75b-fb98-47bc-900d-8fffc5774a6f.png)
![Orange_3](https://user-images.githubusercontent.com/6997360/159449255-f4a4100f-eff0-4990-949c-e9f2753e7cfc.png)

Attached are the screenshots of windows that l can see while installing the add-on. After the third screen, l pressed ok to restart Orange, and then got the error message as above.

**Comment by xliu019** [comment]
Hi, l guess l found an alternative solution - l manage to run Orange from Anaconda and install the Image Analytics addon. It works now. Thanks!
