### ISSUE TITLE
Window for tutorials and usage statistics keeps showing at start 

### ISSUE THREAD

**Issue by delapraznik** [biolab/orange3#5907]
**What's wrong?**

When I open Orange I keep getting a window for Orange Tutorials and Anonymous Usage Statistics, even though I have clicked "Don't show again" a number of times. 
![image](https://user-images.githubusercontent.com/56200538/158997929-ec07b6c3-34c3-4e22-bc3b-32a37f4b635b.png)

![image](https://user-images.githubusercontent.com/56200538/158997842-bbf40ab8-f25f-4920-b63d-fd60f70c1076.png)

**How can we reproduce the problem?** 

The window appears when opening Orange anew. 

**What's your environment?**

- Operating system: macOS monterey
- Orange version: Version 3.31.1
- How you installed Orange: Website

**Comment by delapraznik** [comment]
Apparently the repository doesn't exist. 

<img width="802" alt="Screenshot 2022-04-25 at 15 37 18" src="https://user-images.githubusercontent.com/56200538/165104315-0ffa7f22-0e11-460f-a67f-bd7a1ece5608.png">

**Comment by markotoplak** [comment]
Are you running Orange from the .dmg directly or from /Applications or from another folder?

**Comment by delapraznik** [comment]
From /Applications.

**Comment by ales-erjavec** [comment]
Can you open up the Terminal.app application and run
```
ls -ld  ~/.config
```
paste the output.

**Comment by ales-erjavec** [comment]
Solution
```
sudo chmod $USER ~/.config
```
