### ISSUE TITLE
Feature Statistics widget: no statistics output. regression?

### ISSUE THREAD

**Issue by Autonom** [biolab/orange3#5908]
**What's wrong?**

It seems that there is no output statistics from the Feature Statistics widget.

**How can we reproduce the problem?** 

Add widget Datasets.  Select Auto MPG
Add widget Feature Statistics and link Datasets -> Feature statistics input
Add widget Data Table and link Feature_Statistics -> (Statistics) -> to Data Table

Look at the Data Table, it is empty.

I expected to see a data table with feature statistics (mean, median, etc) similar to here https://orangedatamining.com/widget-catalog/data/images/feature_statistics_example2.png

**What's your environment?**

- Operating system: Ubuntu
- Orange version: 3.30.1
- How you installed Orange: pip.

**Comment by ajdapretnar** [comment]
Feature Statistics outputs selected data. So you likely have not selected anything, hence the widget doesn't output the data.

@janezd @markotoplak Perhaps the Statistics output should output everything without selection?

**Comment by Autonom** [comment]
Thanks for the reply @ajdapretnar 

I can confirm that selecting the rows in Feature statistics widget makes statistics output appear.  This behaviour was not obvious to me - hence the bug report.

I agree with your suggestion of outputting everything without selection.  I think that is more intuitive behaviour.

**Comment by markotoplak** [comment]
Outputting stuff when non-selected may be problematic if additional computation is needed. Therefore I would not make it a default. Currently Orange has a single exception: a data table, and I'd keep it that way.

**Comment by markotoplak** [comment]
The question here is: should this particular output be selection dependent at all? For example, Scores coming from rank do not depend on the selection.

**Comment by ajdapretnar** [comment]
That's what I meant - it should not be selection dependent. It is exactly like Scores, it just output what is shown in the widget in a Table format.

**Comment by Autonom** [comment]
> Outputting everything instead of a selection when non-selected may be problematic if additional computation is needed. Therefore I would not make it a default. Currently Orange has a single exception: a data table, and I'd keep it that way.

I thought all widgets do computation by default?  Changing input data to a model and the learner immediately runs again.  Users quickly learn to disconnect widgets or disable automatic signal propagation.  Is feature statistics different?
