### ISSUE TITLE
Orange 3 Text Install

### ISSUE THREAD

**Issue by datanerdkim** [biolab/orange3#5912]
I've reinstalled Anaconda and tried install it with normal install as well as path install. I can get Orange 3 to install, Get a orange 3 env, but when I try to install the text module, it will install, but not load.  

I followed conda install instructions here: https://github.com/biolab/orange3-text/tree/ab528249621e1556b7a2aaef4d353cf56638ecb5

I've also gotten a zero sum error. Most of the errors seem centered around various PyQt5 libraries. I can use Orange 3 until I try to install the text module, but once I do, Orange 3 no longer will load.

**Comment by ajdapretnar** [comment]
@datanerdkim Could you please report Orange version and Text add-on version.

Also, could you perhaps run Orange with `python -m Orange.canvas -l 4` and post the output here?

**Comment by ajdapretnar** [comment]
Closed due to inactivity.
