### ISSUE TITLE
Data Table slow/blocking when column with long documents present

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/orange3#5915]
**What's wrong?**

The table is slowly loading data, blocking and is not responsive when the table with long texts in one of the columns at the input.

**How can we reproduce the problem?** 

Load `http://file.biolab.si/text-semantics/data/zakoni-o-registrih/` with the Import Documents and connect to the Data Table,  open try to scroll and try to close the window then.

<img width="522" alt="Screenshot 2022-03-23 at 12 29 38" src="https://user-images.githubusercontent.com/6421558/159690000-4b9811cd-89c6-423b-8428-065621b0b1fb.png">

**What's your environment?**

- Operating system: macOS (probably the same problem also elsewhere)
- Orange version: any, master, 3.31
- How you installed Orange: any way, pip, installer

**Comment by markotoplak** [comment]
My first suspect would be the tiny lines showing value ranges (and corresponding computations).

**Comment by janezd** [comment]
@PrimozGodec , @ales-erjavec is this issue (sufficiently) fixed by https://github.com/biolab/orange-widget-base/pull/195?
