### ISSUE TITLE
Color: error when deleting the widget or opening/closing a workflow with this widget

### ISSUE THREAD

**Issue by chourroutm** [biolab/orange3#5918]
**What's wrong?**

```
Traceback (most recent call last):  File "/home/chourroutm/.orange-env/lib/python3.8/site-packages/orangecanvas/scheme/widgetmanager.py", line 343, in __on_node_removed
    self.__remove_node(node)  File "/home/chourroutm/.orange-env/lib/python3.8/site-packages/orangecanvas/scheme
/widgetmanager.py", line 359, in __remove_node
    self.delete_widget_for_node(node, widget)  File "/home/chourroutm/.orange-env/lib/python3.8/site-packages/orangewidget/workflow
/widgetsscheme.py", line 331, in delete_widget_for_node
    widget.saveSettings()  File "/home/chourroutm/.orange-env/lib/python3.8/site-packages/orangewidget
/widget.py", line 1150, in saveSettings    self.settingsHandler.update_defaults(self)  File "/home/chourroutm/.orange-env/lib/python3.8/site-packages/orangewidget/settings.py", line 819, in update_defaults
    self.write_defaults()  File "/home/chourroutm/.orange-env/lib/python3.8/site-packages/orangewidget
/settings.py", line 532, in write_defaults
    self.write_defaults_file(settings_file)  File "/home/chourroutm/.orange-env/lib/python3.8/site-packages/orangewidget
/settings.py", line 782, in write_defaults_file
    pickle.dump([add_version(context) for context in self.global_contexts],
AttributeError: Can't pickle local object 'bind_variable.<locals>.cast'
```

**How can we reproduce the problem?** 

When I delete the widget, I get this error. When I close a workflow which used the Color widget, I usually get this error and some changes are not saved properly; when I then reopen it, I also get the above error.

**What's your environment?**

- Operating system: Linux Ubuntu 20.04 LTS
- Orange version: 3.31.1
- How you installed Orange: via pip

**Comment by markotoplak** [comment]
Thanks! Could you provide a screenshot of the workflow? Saving color widget settings seems to work for me. Could you share a screenshot of your workflow? To me it seems as if one of the upstream widgets corrupted data in a way so that it can not be saved.

As a further test: do you have problems if you create a workflow of only two widgets: Data and Color?

**Comment by chourroutm** [comment]
Hi, you were right! My data got corrupted, either by a Feature Constructor, Select Columns (with purge function enabled) or Edit Domain widget. After recreating the so-said widgets, the error disappeared, so I was not able to locate precisely the corruption or to reproduce it. I am closing this along with #5917.

**Comment by markotoplak** [comment]
@chourroutm, within Orange, if you don't use Python Script, that error should never happen. If it does, it is indeed a bug! If you ever find it again, please report it.
