### ISSUE TITLE
Group-by widget: Add support for Mode of categorical variables

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3#5955]
**What's your use case?**
For categorical variables, several aggregation options are greyed out in Group-by. For most, this certainly makes sense, but not for "Mode". Strange enough, in the Time Series > Aggregate widget, Mode is the _only_ available aggregation option for categorical variables. See [Time series - Issue #192](https://github.com/biolab/orange3-timeseries/issues/192).

**What's your proposed solution?**
Offer Mode as an aggregation option for categorical variables in Group-by.

**Are there any alternative solutions?**
Not that I know of.

**Comment by janezd** [comment]
Indeed. @VesnaT, do you remember any reason why Mode (Majority) is not available?

**Comment by ajdapretnar** [comment]
Perhaps @PrimozGodec is a better person to ask since he wrote the widget?

**Comment by janezd** [comment]
Oops, sorry, I thought this one was by @VesnaT. I probably confused it with Pivot. So, @PrimozGodec, any reason?
