### ISSUE TITLE
Debian 10 support - libQt5Core.so.5: version Qt_5.15 not found

### ISSUE THREAD

**Issue by hpsaturn** [biolab/orange3#5976]
## What's your use case?

# Legacy support to Debian stable version 10 (buster)

With the current branch `stable` on Orange3 repository, the installation flow fails in the last step, because the Qt library requeriment it's a little bit more big:

```python
python3 -m Orange.canvas
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/avp/tmp/src/orange3/orange3env/lib/python3.7/site-packages/Orange3-3.32.0-py3.7-linux-x86_64.egg/Orange/__init__.py", line 30, in <module>
    from AnyQt.QtCore import QObject
  File "/home/avp/tmp/src/orange3/orange3env/lib/python3.7/site-packages/AnyQt/QtCore.py", line 273, in <module>
    from PyQt5.QtCore import *
ImportError: /lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /home/avp/tmp/src/orange3/orange3env/lib/python3.7/site-packages/PyQt5-5.15.6-py3.7-linux-x86_64.egg/PyQt5/QtCore.abi3.so)
``` 

**Debian libraries**:

```bash
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5.11
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5.11.3
```

**Debian OS**:

```bash
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
``` 

## What's your proposed solution?

Maybe to have a old compatibility for GUI libraries or a standalone Docker launcher?

## Are there any alternative solutions?

Maybe use a different package, like snap or another auto-contained solution?

**Comment by ales-erjavec** [comment]
How did you install PyQt5? Did it build from source?

It seems that PyQt5 installed in the orange3env is linked to system Qt5 library which is to old. In general when you install PyQt5 with pip you should get a PyQt5 with a private copy of Qt5 (PyQt5-Qt5 package from pypi).


Try running
```bash
pip install --upgrade pip
pip install --force-reinstall --only-binary :all: PyQt5 PyQt5-Qt5
```
in the orange3env

**Comment by hpsaturn** [comment]
I will try again to follow the next guide:

http://biolab.github.io/install-orange/

is it ok?

**Comment by hpsaturn** [comment]
mmm, but is possible that the issue is in relation with this bug:

https://bugreports.qt.io/browse/QTBUG-88688

**Comment by ales-erjavec** [comment]
> mmm, but is possible that the issue is in relation with this bug:
> 
> https://bugreports.qt.io/browse/QTBUG-88688

Yes probably.

Can you try recreating the environment this time with 
```bash
pip install --only-binary :all: PyQt5~=5.14.0 PyQtWebEngine~=5.14.0
```

**Comment by hpsaturn** [comment]
Nice one!

Thanks, with only that it works!

> 
> ```shell
> pip install --only-binary :all: PyQt5~=5.14.0 PyQtWebEngine~=5.14.0
> ```

Maybe for other users I'm going to put here a little brief, because some things was different to official guide.

My steps:

```bash
python3.9 -m venv orange3env
source orange3env/bin/activate
python3 -m pip install --upgrade pip
git clone https://github.com/biolab/orange3
git clone https://github.com/biolab/orange-bio

cd orange3

pip install --only-binary :all: PyQt5~=5.14.0 PyQtWebEngine~=5.14.0

pip install -r requirements.txt
pip install -r requirements-gui.txt
pip install -r requirements-sql.txt
python setup.py develop

cd ../orange-bio/

python setup.py develop
python -m Orange.canvas
```
![screenshot20220521_154534](https://user-images.githubusercontent.com/423856/169654517-c2cd8531-28b0-485a-8908-1d829abad48a.jpg)
