### ISSUE TITLE
Linear Regression, SVM, Gradient Boost, Stoch. Grad. Desc. and Curve Fit require manual confirmation of output when connecting to explanation widgets

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3#5984]
**What's wrong?**
When connecting LR, SVM, GB, SGD or CF to one of the widgets of the Explain add-on (in regression or classification, wherever they apply), the output-input relation requires manual (re)confirmation. For all the other ML widgets, the correct connection, model-to-model, is automatically selected and no confirmation is needed. Therefore I guess the problem lies with the widgets mentioned in the title and not with the Explain widgets

**How can we reproduce the problem?** 
Connect one of these 'problematic' widgets to any of the Explain widgets, and a dialog box will pop up, where the connection model-to-model has to be reconfirmed. I think in almost all cases the correct connection has already been selected.
Connect any other ML widget and there is no popup and no need for reconfirmation.

**What's your environment?**
- Operating system: Mac OS 11.6.5
- Orange version: 3.32.0; Explain 0.5.3
- How you installed Orange: from DMG download

**Comment by ales-erjavec** [comment]
I cannot duplicate this. This is how it works for me:

![Peek 2022-05-24 11-29](https://user-images.githubusercontent.com/4716745/170000536-d7fbfe70-fef0-401d-a10f-467148ccb5f7.gif)

**Comment by wvdvegte** [comment]
Turns out it only happens if the input of the Explain widget is already connected to another ML widget. Example: when changing the connection from Random Forest to SVM, the connection has to be reconfirmed, when changing back to RF, it isn't needed.
https://user-images.githubusercontent.com/55989717/170019935-d12e13a5-1c40-42bd-84e6-11955a1aeefc.mov

**Comment by ajdapretnar** [comment]
This is expected and by design. SVM outputs two types of outputs, Data (Support Vectors) and Model. Explain Model accepts two types of input, Data and Model. The widget cannot know, which output you wish to connect where.

**Comment by wvdvegte** [comment]
Well, at least it has the correct connection selected already, so that  pressing Enter suffices.
But I guess some (like me) would experience this as a "minor UI inconsistency". I understand that there's no easy fix. The only one I could think of, is to have separate output and input connection points for each type of output or input a widget can handle. This is actually how it is done in RapidMiner, but it requires more thinking from the user.

**Comment by ajdapretnar** [comment]
A hint: you can already hold Shift when dragging the connection out and the widget will offer all its outputs/inputs.
