### ISSUE TITLE
Parallel processing for "Suggest features"

### ISSUE THREAD

**Issue by hydrastarmaster** [biolab/orange3#5996]
Processing is quite slow. E.g., I'm running a Radviz "Suggest features", and it only uses one core to calculate permutations.

Please extend multicore processing to "Suggest features" functions. Thanks.

**Comment by janezd** [comment]
Thank you for you suggestion.

We are gradually adding parallel processing to widgets, though this is not trivial so we need to prioritize. Parallel Radviz will come, too, eventually.
