### ISSUE TITLE
Scheduled data input

### ISSUE THREAD

**Issue by hydrastarmaster** [biolab/orange3#5997]
Use case: The user keeps the workflow open, and at predetermined intervals or times data and graphs start to update.
Current issue: It's useful to schedule the execution of time-consuming jobs that articulate with external processes. At present, the workflow runs only when opened.

Proposed solution:
(1): Add a "Start/Stop Workflow" item in the File menu. Inhibit auto-start at the opening.
(2): Add a "Schedule" widget that triggers the following data-input widget (file, .csv, SQL, ...) at a specified time, or intervals, or on input file/table update.

I'm trying to integrate Orange into a fully autonomous procedure that needs automatic model recalculations. I would like to use the visual workflow prototype before writing down some Python code with the library.

**Comment by janezd** [comment]
Orаnge can be run in batch mode - you can run Orange and pass a workflow as an argument. Please use this functionality instead. Widgets do not support being triggered - it's just not how they're implemented.
