### ISSUE TITLE
Refine Rank widget filter

### ISSUE THREAD

**Issue by hydrastarmaster** [biolab/orange3#5999]
Use case: We are trying to reduce the number of features in a model with the Rank widget. We would like to determine the most significant features _a priori_.

Problem: If we select N “best ranked” variables from the Rank widget, they are chosen from the feature table within the widget itself. The selection takes the topmost elements in the table, the order being determined on the basis of a sort column (just one and only one of the calculated scoring methods). The choice of the scoring method is a deterministic operation that should be in charge of the AI (at least, optionally).

Solution: Add a column of data within the Rank widget, with a weighted score that aggregates the calculated scoring methods results.

Current workaround: At the moment we are solving this case by calculating multiple instances of the Rank widget, eg. 1 with “Univariate Regression” and 1 with “RReliefF”. Then we make them converge into a Venn Diagram, where we permanently select the inner join on “Columns (features)”.

**Comment by ajdapretnar** [comment]
Just make sure you are using feature selection correctly. See the Preprocessing for predictive modeling section in  https://orangedatamining.com/widget-catalog/transform/preprocess/.

That of course wouldn't solve the issue. If I understand correctly, you'd like a meta-score, which would .... hm.... consider the rank and by which you could determine the top 10 features by all scores.

**Comment by hydrastarmaster** [comment]
Preprocessing is ok, I'm carefully reading the official documentation.

Yes, a meta-score "to bring 'em all", seems the easiest solution to apply. Allow me the similarity: a sort of "stack" meta-score.

**Comment by janezd** [comment]
We won't add this. Weighted sums of scores are meaningless (although the mass production of ML papers has undoubtedly presented dozens of "studies" that show its usefulness).
