### ISSUE TITLE
SQL with Firebird

### ISSUE THREAD

**Issue by hydrastarmaster** [biolab/orange3#6019]
We need to use our Firebird DB. No way to connect it.
Why Firebird? Because our Win10 server aborts (without any indication...!) the installation both of SQLServer and PostgreSQL, thus we started to use Firebird. Given its position in the open-source community, it seems convenient to make it connectable by the SQL widget.

Solution: Make Firebird connectable from the "SQL Table" widget.

**Comment by ajdapretnar** [comment]
It's a good idea. Feel free to implement it. Development documentation is available here: https://orange-widget-base.readthedocs.io/en/latest/ We are happy to review to code once you submit a PR.
