### ISSUE TITLE
Error when loading Excel with colored background

### ISSUE THREAD

**Issue by Chocoder** [biolab/orange3#6030]
Hello!

When loading Excel file with the File widget I get this error: colors must be ARGB hex values 

I guess that it is because my first Excel line is colored with some background...  I'm not able to configure the file formating (or manualy update it but very time consuming), so could we deal with that in the widget?

Thanks,

**Comment by janezd** [comment]
We can't solve this.

First, I can't replicate it, it works for me. 

But even if I could: the problem is not in Orange but in the library that Orange uses to read Excel data, openpyxl. Report any problems there, at https://github.com/theorchard/openpyxl.
