### ISSUE TITLE
"Louvain Clustering" progress indicator desync

### ISSUE THREAD

**Issue by hydrastarmaster** [biolab/orange3#6036]
"Louvain Clustering" progress bar (in the widget windows) and progress animation (in the workflow) are not synchronized. The percentage doesn't increment at the same time.

**Comment by janezd** [comment]
All widgets use the same functions for indicating progress. Any lack of synchronization is due to Qt threading, which - if it occurs (I haven't seen it yet) would be difficult to fix and is not important enough to invest time that could better be used on other, more important issues.
