### ISSUE TITLE
Some widgets crash orange when being dragged across two different monitors

### ISSUE THREAD

**Issue by HannesLum** [biolab/orange3#6040]
**What's wrong?**
It's a problem originally coming from PyQt (see [this](https://github.com/PyQt5/PyQt/issues/162) issue i posted), but I first investigated it via Orange and thought it might be good to bring it to your attention as well, just in case the issue persists.

When dragging certain widgets across two screens of different sizes, they get resized automatically, as any other window, but then the widgets enter an infinite resizing loop and become unresponsive until orange crashes. I looked through the Data and Transform category and found the following widgets with this behaviour:
Save Data, Data Sampler, Transpose, Concatenate, Select by Data Index, Apply Domain, Randomize (and "As Timeseries" from the add-on too, for that matter)
For some widgets it only happens the second time you drag across the screen:
Purge Domain,  Melt 

**How can we reproduce the problem?** 
The hardest part: Have two incompatible screens. Both of my screens have a resolution of 1920x1080 but their size in inches/cm is different. I'm not sure how my Windows 10 OS handles this exactly, but all windows are resized when dragged from one screen to another, so that eg text has a readable size. If you do that with the widgets mentioned above, orange will crash.

**What's your environment?**
- Operating system: Windows 10
- Orange version: 3.32.0
- Python version: 3.9
- PyQt5 version: 5.15.6
- How you installed Orange:
`pip install orange3` (though I installed an old version first and updated it at a later date)
- `QApplication.style().metaObject().className()`: QWindowsVistaStyle

**Comment by markotoplak** [comment]
Thanks for the report. An interesting find.

I am not sure if that is the official pyqt repository though. I think PyQt developers mostly communicate through the following mailing list: https://www.riverbankcomputing.com/mailman/listinfo/pyqt

**Comment by HannesLum** [comment]
Oh, thank you for the info, I'll send it there as well. Seems like it was a good idea to send it to you as well, as I actually wasn't sure either, if I got the right address.

**Comment by 892768447** [comment]
left: 1920x1080 100%
right: 1920x1080 125%

Slowly drag the window between the two screens

![image](https://user-images.githubusercontent.com/5131669/175863129-80ae583f-e415-4068-8289-f2e41e6904ca.png)


I think this Qt's or windows bug is caused by using 'MSWindowsFixedSizeDialogHint' and 'setFixedSize' of the top-level layout at the same time.

because remove MSWindowsFixedSizeDialogHint, use os.environ['QT_SCALE_FACTOR'] = '1.0' or a.setAttribute(Qt.AA_EnableHighDpiScaling, False) , the problem is still exist.

**Comment by HannesLum** [comment]
As  said, this problem is created because 'MSWindowsFixedSizeDialogHint' and 'setFixedSize' are used at the same time.
So technically, the solution of the problem would be in the [orange-widget-base](https://github.com/biolab/orange-widget-base) repository by changing [orangewidget/widget.py](https://github.com/biolab/orange-widget-base/blob/master/orangewidget/widget.py) so that it either only uses the 'MSWindowsFixedSizeDialogHint' flag or the 'setFixedSize' flag. Though, I have no idea which one is the better solution, or if there is another reason why both of them are used.

**Comment by 892768447** [comment]
https://github.com/biolab/orange-widget-base/blob/master/orangewidget/widget.py#L395
At present, I don't know what the requirements of this setting are.

eg: two screens with different zoom ratios
first: 1920x1080 100%
second: 1920x1080 125%

want to keep same size on first and second screen? eg: 400x300

**Comment by 892768447** [comment]
I remove `MSWindowsFixedSizeDialogHint` and base layout use `SetFixedSize`, This bug still exists when the moving window is between the two screens. 

Possible compatible methods: remove `MSWindowsFixedSizeDialogHint`(only for windows) and base layout `SetFixedSize`.
Then use `self.setFixedSize(self.width(), self.height())` or `self.setFixedSize(width, height)` Explicit value
or `setMinimumSize` `setMaximumSize` 


setFixedSize: https://code.woboq.org/qt5/qtbase/src/widgets/kernel/qwidget.cpp.html#_ZN7QWidget12setFixedSizeEii
setMaximumSize: https://code.woboq.org/qt5/qtbase/src/widgets/kernel/qwidget.cpp.html#_ZN7QWidget14setMaximumSizeEii

**Comment by 892768447** [comment]
```python
    def showEvent(self, event):
        if self.first_show:
            # Notice Here
            self.first_show = False
            self.setFixedSize(self.size())
            self.layout().setSizeConstraint(QVBoxLayout.SetDefaultConstraint)
        super(ResizingTest, self).showEvent(event)
```
set `setFixedSize`  and restoring the resize mode of the layout to `SetDefaultConstraint`

from this example: https://github.com/PyQt5/PyQt/files/8940133/resizing_window_crash.zip
source code:
```python
#!/usr/bin/python

from PyQt5.QtWidgets import QApplication, QLabel, QVBoxLayout, QGroupBox, QDialog, QWidget
from PyQt5.QtCore import Qt


class ResizingTest(QDialog):
    name = 'Resizing Test'

    resizing_enabled = False
    first_show = True

    def __init__(self):
        QDialog.__init__(self, None, Qt.Dialog)

        layout1 = QVBoxLayout(self)
        layout1.setContentsMargins(2, 2, 2, 2)
        if not self.resizing_enabled:
            layout1.setSizeConstraint(QVBoxLayout.SetFixedSize)

        gb = QGroupBox("title", self)
        layout2 = QVBoxLayout(gb)
        layout2.setContentsMargins(4, 4, 4, 4)
        layout1.addWidget(gb, 0)
        layout2.addWidget(QLabel('Well, this is just a teststring, hat hopefully is long enough to trigger the bug'))
    
    def showEvent(self, event):
        if self.first_show:
            # Notice Here
            self.first_show = False
            self.setFixedSize(self.size())
            self.layout().setSizeConstraint(QVBoxLayout.SetDefaultConstraint)
        super(ResizingTest, self).showEvent(event)

if __name__ == "__main__":

    a = QApplication([])
    print(QApplication.style().metaObject().className())
    ow = ResizingTest()
    ow.show()
    a.exec()

```
