### ISSUE TITLE
Merge data with multiple matches

### ISSUE THREAD

**Issue by Chocoder** [biolab/orange3#6041]
**What's your use case?**
Hello, I realised that the merge widget gives a warning when multiple matches are found...

[https://docs.microsoft.com/fr-fr/power-query/merge-queries-left-outer](https://docs.microsoft.com/fr-fr/power-query/merge-queries-left-outer)

[https://docs.microsoft.com/fr-fr/power-query/merge-queries-inner](https://docs.microsoft.com/fr-fr/power-query/merge-queries-inner)

In my use case I have a first table with a CountryID that could exists several time (ex: 1 1 3 4). In my second table those ID exist only one time (1 2 3). So I would like to merge - left or inner - the first table with the second one. Left comportment will matches 3 times (and let one empty cell in the Country column), inner will matches 3 times too (and let no empty cells in the Country column.

Is there a trick to use the existing Merge widget to apply this kind of table merging operation?

**What's your proposed solution?**
Use the same merge widget, with a warning if empty cells may appear, but authorizes the merge option.

**Are there any alternative solutions?**
Merge outside of Orange?
Design a widget with Python raw code?

**Comment by Chocoder** [comment]
@janezd hello! Any clue on that topic? You helped me on another one so I tried again! Thanks,

**Comment by janezd** [comment]
Are you sure you have not just reversed your input signals? As I understand your description, this is exactly what Merge is made for - in its current form.

**Comment by janezd** [comment]
Works for me: [Archive.zip](https://github.com/biolab/orange3/files/11132456/Archive.zip)
