### ISSUE TITLE
MDS: amount of explained variance

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#6070]
**What's your use case?**

I got a comment from a reviewer, that it would be useful if MDS showed the amount of explained variable. Given that most MDS projections start with PCA initialization, this could perhaps be useful.

**What's your proposed solution?**

Add info on amount of explained variance. Perhaps to the status bar or to the info box below parameter settings.

**Are there any alternative solutions?**
Look for the same info with PCA widget?

**Comment by ajdapretnar** [comment]
Here's what I found as well:

> The amount of generalized variance explained by the MDS solution can be expressed as P2 or Mardia criteria. P2 is the ratio of the sum of the eigenvalues over the total sum of the eigenvalues. Mardia criteria squares the numerator and denominator of the P2 values. Both are scaled from 0 to 1, with values closer to 1.0 indicating a good fit.

**Comment by janezd** [comment]
MDS starts with distances - even if the widget is given a table, it computes distances. Projection is non-linear so even if the original data was table-based, one can't "map" original coordinates to projection. I don't see how one could define explained variance. But then, I may not be an expert in MDS.

Mardia (which I haven't known before) measures the goodness of fit. Scikit doesn't have it, but we could display stress.
