### ISSUE TITLE
Edit Domain: enable setting the type for several variables at once

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#6088]
**What's your use case?**

Sometimes, one would like to convert several categorical variables to numeric (or vice-versa). This is not possible to do at the moment. One has to click every variables separately and set it.

**What's your proposed solution?**

Enable selecting several variables in Edit Domain and setting the type. I've checked and if the conversion cannot be done (i.e. transform text to numeric), the widget will output missing values for the erroneous variable. Which is quite smooth.

**Are there any alternative solutions?**
/

**Comment by mw25** [comment]
This feature would be very useful for me as well. 
In my case I miss the function in the DomainEditor of the File Widget: Select multiple variables/rows and change Type or Role (as far as possible).
