### ISSUE TITLE
EntropyMDL._normalize does not account if X is 0's

### ISSUE THREAD

**Issue by davzaman** [biolab/orange3#6099]
**What's wrong?**

[`EntropyMDL._normalize()`](https://github.com/biolab/orange3/blob/71b790662cfb5c712be16c067060eaddc671b034/Orange/preprocess/discretize.py#L691) divides by the scale which is the sum.
When X (across the axis) is 0's scale is 0 and therefore the denominator is 0 and you get a warning and a nan back.

`python3.9/site-packages/Orange/preprocess/discretize.py:551: RuntimeWarning: invalid value encountered in true_divide
  return X / scale`

I'm not sure if we'd want to enforce a warning, or just return 0 for those.

**How can we reproduce the problem?** 

```python
from Orange.preprocess import EntropyMDL
EntropyMDL._normalize( [[1., 0.], [0., 0.]], axis=1)
```

**What's your environment?**

- Operating system: Ubuntu/Linux
- Orange version: 3.32.0
- How you installed Orange: mamba/conda

**Comment by janezd** [comment]
Thanks for reporting this.

This function normalizes rows/columns to have a sum of 1, therefore I think that all-zero rows/columns should be replaces by 1 divided by number of columns/rows.

**Comment by janezd** [comment]
I saw your "bio" on github. :)

I obliged and added type hints to function definition (#6102). Happy?

**Comment by davzaman** [comment]
Thanks for the fixes and for the type hints 😆  I appreciate it!
