### ISSUE TITLE
Line Chart: improve ticks on single date, multiple hours

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#6103]
##### Timeseries version
master since biolab/orange3-timeseries#220 

##### Orange version

3.32.dev

##### Expected behavior
When the timeseries data belongs to a single date but to multiple hours, ticks should display only hours, i.e. 23:00.

##### Actual behavior
Ticks display the day + hour, which is quite unintuitive.

##### Steps to reproduce the behavior
[NewLog3.txt](https://github.com/biolab/orange3-timeseries/files/9251181/NewLog3.txt)
File - Line Chart.

##### Additional info (worksheets, data, screenshots, ...)
This is not major. It only happens after a certain width of the widget. When shrunk, the widget displays only hours.
<img width="1009" alt="Screenshot 2022-08-03 at 14 19 33" src="https://user-images.githubusercontent.com/12524972/182606012-4546c21a-3095-49cd-8853-4c6fcf5a14c0.png">

**Comment by janezd** [comment]
Moved from timeseries: the issue is in `owscatterplotgraph.AxisItem`'s adaptation for time variables. The same problem would appear in the scatter plot.
