### ISSUE TITLE
Error saving Library in Python Script

### ISSUE THREAD

**Issue by hydrastarmaster** [biolab/orange3#6110]
Environment: Win 10, current release (2022-08-28)
Orange version: 3.32.0
Widget: Python Script

(1)
Let's consider the default example of "Table from numpy". We want to save it into a file. From the script editor:
_Button "More" --> "Save selected script to file"_
We have to enter the name of the NEW file to write.... eg. _test.py_
_Button "Save"_

A popup says: "C:\testpath\test.py File cannot be found. Check the name and retry." (or something similar, I'm working on a Spanish locale at the moment).

(2)
When we have a multiple inputs that goes into the Data Table widget, the python script is indicated as "untitled". Can the user define the name?
![image](https://user-images.githubusercontent.com/41840980/187053727-0e826f9a-985c-4b68-9075-bd26317aba74.png)

**Comment by janezd** [comment]
(1) Works for me. It must be related to your installation of Windows, I suppose. Can you try a different path? `c:\testpath` exists and you are allowed to write to it?

(2) `out_data.name = "whatever"`

**Comment by hydrastarmaster** [comment]
(1) Working ok, it saves in Download. Thus the problem is just the message, which does not describe the true error.
(2) Thanks.

**Comment by janezd** [comment]
Orange does not show any messages here. It uses the Windows' file dialog to let the user choose the directory and filename, and then attempts to write the file. Orange does not open any dialogs with error messages here, so the (incorrect) message must had come from Windows, but I don't know at which point. I cannot replicate this.
