### ISSUE TITLE
Prediction widget shows no probabilities

### ISSUE THREAD

**Issue by alexanderfussan** [biolab/orange3#6111]
**Describe the bug**
The Prediction widget shows no probabilities for the predicted classes.

**To Reproduce**

**Expected behavior**
See probabilities for predicted classes in prediction Widget.

**Orange version:**
3.32

**Screenshots**
![grafik](https://user-images.githubusercontent.com/111502928/187162897-d7e4ea55-dc51-4b82-a6af-c548427f7887.png)

**Operating system:**
Windows 11

**Additional context**

**Comment by markotoplak** [comment]
Fixed in #5972. Maybe we need a release soon, this popped up multiple times already.
