### ISSUE TITLE
Test and Score reports wrong accuracy in multi-class domain for a target class

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3#6117]
**What's wrong?**

When using the Test and Score widget to report accuracy for a target class, the accuracies (AUC, CA, and precision, at least) are wrong. I have observed this error on the domain with six classes.

**How can we reproduce the problem?** 

- Install Single Cell add on
- Use Pancreas cells in human (sample)
- Cross validate random forest
- Observe the results for "pancreatic PP cell"
- Compare with Confusion Matrix (third row), which shows that only 2 of the 16 "pancreatic PP cells" have been classified correctly, whereas Test & Score report the classification accuracy of 0.991.

<img width="386" alt="image" src="https://user-images.githubusercontent.com/726604/187954702-507345c1-48c6-4623-922f-03efe077bb5c.png">

<img width="736" alt="image" src="https://user-images.githubusercontent.com/726604/187954776-f7b2e2d5-5d4a-4529-86f9-83cf21ffe8b2.png">

<img width="836" alt="image" src="https://user-images.githubusercontent.com/726604/187954859-b5f2ea29-ba88-424d-8ba1-4629efecc42b.png">

[bug-test-and-score.ows.zip](https://github.com/biolab/orange3/files/9471310/bug-test-and-score.ows.zip)

**What's your environment?**

Mac, Orange 3.32

**Comment by janezd** [comment]
I believe that CA does not depend on selected class. The score you expect, 2 / 16, is actually recall.

I agree that this may be misleading. What do you suggest?

That said, the CA, based on confusion matrix is 0.956, not 0.991. I can't explain this, we'd have to explore it with Predictions, I guess.

**Comment by BlazZupan** [comment]
Janez, thanks. Do I correctly understand that only Precision and Recall depend on target selection, and other measures do not. This may be confusing. It would be better if all the scores would apply only to the target class. I have yet to think what is CA then. This requires live debate (I am having Marko on the side, though, but would need to talk over with you).

**Comment by janezd** [comment]
@BlazZupan, I'm sorry, I was wrong. CA already depends on the target. Just run the widget (without canvas) and see the effect on Iris.

When the target class is set, all other classes are essentially merged, and this goes for all scorers.

There is no bug. Random forest correctly classified 2 pancreatic cells as pancreatic, and 1631-16 = 1615 non-pancreatic cells as non-pancreatic. That is, 1615+2=1617 correct classifications for 1631 instances. 1617/1631=0.991, as shown in Test and Score.

The score that you expected (correctly classified 2 out of 16) is just not classification accuracy but recall.

**Comment by BlazZupan** [comment]
I am closing this issue. Everything works fine.
