### ISSUE TITLE
AttributeError: module 'xlrd' has no attribute 'Book'

### ISSUE THREAD

**Issue by vengozhang** [biolab/orange3#6121]
When import Orange model arise " AttributeError: module 'xlrd' has no attribute 'Book' "
**What's wrong?**

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-b46b66c87f2c> in <module>
----> 1 import Orange
      2 import matplotlib.pyplot as plt
      3 names = ["first", "third", "second", "fourth" ]
      4 avranks =  [1.9, 3.2, 2.8, 3.3 ]
      5 cd = Orange.evaluation.compute_CD(avranks, 30) #tested on 30 datasets

D:\Users\admin\anaconda3\lib\site-packages\Orange\__init__.py in <module>
      2 # pylint: disable=wrong-import-position,wrong-import-order
      3 
----> 4 from Orange import data
      5 
      6 from .misc.lazy_module import _LazyModule

D:\Users\admin\anaconda3\lib\site-packages\Orange\data\__init__.py in <module>
      8 from .table import *
      9 from .io_util import *
---> 10 from .io import *
     11 from .filter import *
     12 from .pandas_compat import *

D:\Users\admin\anaconda3\lib\site-packages\Orange\data\io.py in <module>
    350 
    351 
--> 352 class XlsReader(_BaseExcelReader):
    353     """Reader for .xls files"""
    354     EXTENSIONS = ('.xls',)

D:\Users\admin\anaconda3\lib\site-packages\Orange\data\io.py in XlsReader()
    360 
    361     @property
--> 362     def workbook(self) -> xlrd.Book:
    363         if not self._workbook:
    364             self._workbook = xlrd.open_workbook(self.filename, on_demand=True)

AttributeError: module 'xlrd' has no attribute 'Book'

**How can we reproduce the problem?** 

**What's your environment?**

- Operating system:  window 10, anaconda3
- Orange version: Version: 3.32.0
- How you installed Orange: pip install Orange3

**Comment by janezd** [comment]
This is weird. Can you try to open Python and type

```python
import xlrd
print(xlrd.Book)
```

You can also try `pip freeze`: which version of xlrd do you have? As far as I know it is no longer maintained; 2.0.1 should be the latest version and should have attribute `Book`.

**Comment by ajdapretnar** [comment]
Closed due to inactivity.
