### ISSUE TITLE
Group by: Standard deviation and Sum of TimeVariable

### ISSUE THREAD

**Issue by mw25** [biolab/orange3#6125]
**What's wrong?**
In the Group by widget an error message appears when calculating the aggregations "Standard deviation" or "Sum" for a time variable.

**How can we reproduce the problem?** 

- Load Dataset with TimeVariable (e.g. "Banking Crises")
- Select in Group by widget the Aggregations "Standard deviation" or "Sum" for the TimeVariable.

![image](https://user-images.githubusercontent.com/67997227/188425338-5fec3472-5182-4203-86db-cf790fb5571e.png)
![image](https://user-images.githubusercontent.com/67997227/188425370-97230546-72d5-4005-b8a9-e6a751d66691.png)

**What's your environment?**
- Operating system: Win10
- Orange version: '3.32.0.dev0+94958aa'
- How you installed Orange: git clone

**Comment by PrimozGodec** [comment]
Thanks for reporting the issue. It seems like a bug. I will take a look.

**Comment by PrimozGodec** [comment]
It is fixed in #6133
