### ISSUE TITLE
Data Table: deprecate multiple Data inputs

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#6127]
Multiple inputs into the table are confusing:
- It is not obvious that they are available, nothing in the UI signals it until someone tries connecting it so.
- There is just a single selection coming out. Which one?
- The output can not be deduced by looking at the workflow.

So, does anyone need or want them?

I suggest we somehow "deprecate" them while still taking care that old workflows indeed still work.

**Comment by janezd** [comment]
- When potentially useful, that is, when probing data at different points in the flow, all tabs have the same name, so you can't know which shows which data.
 
I never liked this, either. I use multiple instances of the widget instead.

It is amazing, though, that the amount of code needed to support this is rather small. That said, it should be even easier to remove it, and without feeling sorry a lot.

**Comment by PrimozGodec** [comment]
I never use this functionality. It is easier to put multiple tables on the canvas.

**Comment by ajdapretnar** [comment]
I actually use it, but I won't missing it too much if we remove it.
