### ISSUE TITLE
Data Table needs a Data Subset input

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#6128]
A Data Subset input on a Data Table could seem redundant, but @BlazZupan just convinced me there is a case: when the table is sorted it would be indeed useful to see where a particular subset lies.

We try to make all visualizations support subsets. Data Table is a visualization and should be treated as such.

**Comment by markotoplak** [comment]
Adding a subset could be confusing due to the multi-input Data input. Thus, #6127.

**Comment by janezd** [comment]
Combined into #6315.

**Comment by wvdvegte** [comment]
Now what will happen to the selection and the sorting when the input data changes? I hope that if the selection was set to "all", still all the data remains selected and the sorting order remains.
I can understand that the selection is lost if not everything was selected.

**Comment by janezd** [comment]
Answer in #6315.
