### ISSUE TITLE
Test and Score - intuitive way to add new score

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/orange3#6131]
##### Issue

In Test and Score, the menu to add additional scores is hidden (regular users cannot easily find it):
<img width="786" alt="Screenshot 2022-09-09 at 10 26 18" src="https://user-images.githubusercontent.com/6421558/189306963-acb982f1-ec1a-41e9-919c-bb197b39c1dc.png">

##### Suggestion

Add a sign that would suggest to the user that it is possible to add additional scores. For example, tree dots:
![Screenshot 2022-09-09 at 10 26 181](https://user-images.githubusercontent.com/6421558/189307611-ddad1ab7-2895-46e1-ba4f-19f0667c6957.png)

**Comment by Kshitij-01** [comment]
I would like to contribute to this issue.

**Comment by ajdapretnar** [comment]
@Kshitij-01 I have assigned you to the issue. Feel free to submit a PR whenever you feel like it and we will review it. Thank you for volunteering!

**Comment by xacusta** [comment]
Hi there...
unfortunately in my Orange 3 version 3.33.0, it has less scores than showed in above pics. for example I don't have F1. Can anybody help me with this issue?

![Capture](https://user-images.githubusercontent.com/81536391/201584183-dee34c0e-1975-403f-b84e-9d84d73a31a2.PNG)

**Comment by VesnaT** [comment]
The available scores depend on target variable. The F1 score is only available for categorical targets.
