### ISSUE TITLE
Merge Data: add outputs for additional set operations

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3#6138]
**What's your use case?**
I would like to be able to subtract one dataset from another. Suppose I have two datasets with the same column names that have only some rows in common, i.e., these rows are identical. With Merge Data I can obtain the intersection between the two datasets, i.e., just the rows they have in common. But I want to have those rows from the first dataset that are not also in the second dataset. 

**What's your proposed solution?**
Add extra outputs to Merge Data, to be able to select data that is currently filtered out:
- Intersection (default, already available): intersection between inputs Data and Extra Data, currently called "Data"
- Data minus Extra Data: Rows that appear in Data but not in Extra Data
- Extra Data minus Data: Rows that appear in Extra Data but not in Data

**Are there any alternative solutions?**
Yes, using Venn Diagram as shown, and selecting the subset corresponding to the desired subtraction for output. This is however rather far-fetched.
![image](https://user-images.githubusercontent.com/55989717/190642208-c1bee320-a140-4c21-a2ee-637fde453796.png)

**Comment by janezd** [comment]
Thanks for the idea. We discussed it and there was consensus that we should do it.

Somebody said that this does not really belong to Merge. I now looked into it and this widget is indeed a lot about columns. We could add the proposed two operations here, but "Select by Data Index" could be a better fit. On the other hand, if we do this, the bottom part of Merge would be repeated in Select by Data Index; from this perspective it may be better to add the proposed functionality to Merge, as you suggested.

Finally, everything that Select by data Index does could be added as an option to Merge, which would then need to be properly renamed.

We should discuss this further.

**Comment by wvdvegte** [comment]
I agree that the name "Merge" would no longer be very appropriate if this functionality is added. Perhaps a new widget "Set Operations" that also includes the current functionality of Merge?

**Comment by janezd** [comment]
We discussed this further, as promised. :)

Venn diagram seems to be a reasonable way of doing it.

- Merge data is more about the SQL-style joining, that is, I have data with some keys into another table. Matching by keys makes no sense when subtracting.
- Select By Index would not compare rows by data at all, so it doesn't help.

But Venn diagram is exactly about operations that you describe here. So we concluded that you should probably just use Venn diagrams.
