### ISSUE TITLE
Icons and buttons not visible after installing Orange (on Windows)

### ISSUE THREAD

**Issue by WithoutUr** [biolab/orange3#6147]
![image](https://user-images.githubusercontent.com/111654688/192081962-f1489f81-c329-4fbd-a9f5-a7c2ed173588.png)

## **Expected bahavior**
Icons and buttons would render.

## **Actual behavior**
Icons and buttons do not render

## Download Step
1. follow [installation instructions](http://orange.biolab.si/download/)
2. launch Orange
3. load sample project

## **Environment**
- Windows
- Orange3-3.32
- Anaconda3
- Python 3.8

**Comment by ales-erjavec** [comment]
Can you run
```
conda info
```
in the environment where you have orange installed and post the output.


My guess is that the Qt5 SVG image plugin is not properly installed/detected.

**Comment by janezd** [comment]
Closed due to inactivity.
