### ISSUE TITLE
Changed code signature in macOS version 3.33.0?

### ISSUE THREAD

**Issue by suschizu** [biolab/orange3#6163]
I've received a warning that the code signature has changed in download since 3.32.0

https://download.biolab.si/download/files/Orange3-3.33.0-Python3.8.8.dmg

```
EXPECTED 
Univerza v Ljubljani, Fakulteta za racunalnistvo (556DY3FJ29) 
but FOUND 
Revelo d.o.o. (AX63C2T8RC)
```

can you confirm this?

**How can we reproduce the problem?** 
```
codesign -dv --verbose=4 path/to/app/Orange3.app
Authority=Developer ID Application: Revelo d.o.o. (AX63C2T8RC)

```

**What's your environment?**

macOS 12.6 / intel
```
CFBundleIdentifier: si.biolab.orange

CFBundleShortVersionString: 3.33.0

CFBundleVersion: 3.33.0
```

**Comment by PrimozGodec** [comment]
Thank you for noticing and reporting the issues. Yes, I can confirm that. It seems that the signing tool took the wrong certificate. We will fix the installer.

**Comment by suschizu** [comment]
great thanks for the confirmation :)
