### ISSUE TITLE
Widget save data shuffle the table columns

### ISSUE THREAD

**Issue by EGalloni** [biolab/orange3#6180]
Hi
I'm just starting using Orange and I realised that the widget "Save Data" when writing the xcel file shuffle the columns..
![image](https://user-images.githubusercontent.com/116362134/197203535-adcd2215-94a8-4b5f-842c-25bc60ecaa95.png)

This is how the Save data sees the input table (just the first columns
![image](https://user-images.githubusercontent.com/116362134/197204275-0b9b8555-1eb2-4686-9d9b-330cae2cbbd5.png)

This is how it is going on the file 

![image](https://user-images.githubusercontent.com/116362134/197203925-4de217b9-8e69-4907-a354-81179f1f3d78.png)

**What's wrong?**

**How can we reproduce the problem?** 

**What's your environment?**

- Operating system:
- Orange version:
- How you installed Orange:

**Comment by janezd** [comment]
Ha!

Data tables have three kinds of columns: "attributes", "class(es)" and "meta attributes". The order is defined only within each group. If the data in the file contains a mixture of the three (e.g. meta attributes, class, another meta attribute, attribute, meta attribute ...), this order is lost -- except that columns within each group will maintain their relative order.

- Table widget always shows class variables, followed by meta attributes, followed by ordinary attributes.
- Save widget always saves attributes, followed by classes, followed by meta attributes.

This is indeed a discrepancy. The latter was the original order, which was also used by Table, but at some point we changed it. In other words, Save does not change the order, it just uses a different order. :) File widget, on the other hand, just forgets the order.

Thanks for your observation. We definitely need to discuss this.

**Comment by EGalloni** [comment]
Thank you for the quick response!
Got you..it would be nice in future to be able edit how the table is saved,
you have fantastic graphic features but sometime also the text needs to
have its form :)

Il giorno ven 21 ott 2022 alle ore 15:24 Janez Demšar <
***@***.***> ha scritto:

**Comment by janezd** [comment]
Decision: Save data will use the same order as the Table widget.
