### ISSUE TITLE
Prediction widget does not export eval result.

### ISSUE THREAD

**Issue by leaf918** [biolab/orange3#6183]
**What's wrong?**

Described as the issue title.

**How can we reproduce the problem?** 
![image](https://user-images.githubusercontent.com/170311/197923885-823ede03-5d02-44f8-a466-65037072f9c4.png)

![image](https://user-images.githubusercontent.com/170311/197924061-d3b9de6f-4a06-46c8-902b-e3f43662ba40.png)

**What's your environment?**
v 3.33.

**Comment by janezd** [comment]
This is a different data type. "Data Table" shows data instances. "Evaluation Results" can be connected to widgets like ROC, Lift Curve, Calibration Plot and Confusion Matrix.

**Comment by janezd** [comment]
Predicted values are saved in Save Data in your workflow, aren't they?

You can also use Select Columns to removed any unwanted columns, e.g. the original data.

**Comment by leaf918** [comment]
The predicted values are saved in the Output node,
While I need the prediction node's diff value too in the output table.
