### ISSUE TITLE
No text mining button in Orange program in order to import documents.

### ISSUE THREAD

**Issue by oliviadelucci** [biolab/orange3#6184]
**What's wrong?**

When I downloaded the program orange onto my computer, it was downloaded without the text mining button. I am not able to import documents without that button. I tried to do an add on and run it on my computer but my computer gave me an error. 

**How can we reproduce the problem?** 

Describe steps or maybe with a video.

**What's your environment?**

- Operating system:
- Orange version: 3.33
- How you installed Orange: From the internet onto my computer.

**Comment by markotoplak** [comment]
Thanks for the report, but we can not help you unless you are more specific.

We'd need to know at least which operating system, which installer did you download (for some OSes they are multiple options; also, did you install through anaconda), and perhaps most importantly, what exactly was the error (copy-paste or make a screenshot).

**Comment by ajdapretnar** [comment]
It's as simple as installing the add-on. Go to Options - Add-ons and install Text.

**Comment by janezd** [comment]
Closed due to inactivity.
