### ISSUE TITLE
Portable Orange3-3.33.0. could not find pythonw.exe

### ISSUE THREAD

**Issue by huangliang0828** [biolab/orange3#6188]
win10 64bit
Portable Orange
[Orange3-3.33.0.zip](https://download.biolab.si/download/files/Orange3-3.33.0.zip)
No installation needed. Just extract the archive and open the shortcut in the extracted folder.
double click the 
shortcut，Orange ，it‘s target：%COMSPEC% /C start Orange\pythonw.exe -m Orange.canvas

could not find pythonw.exe, please check the name is correct？
checked the  pythonw.exe，it is in the  "G:\Orange3-3.33.0\Orange" all the time.
![1](https://user-images.githubusercontent.com/52817734/198811419-b1477627-c8d3-44b5-8a18-a61ec7e90d1f.png)
![2](https://user-images.githubusercontent.com/52817734/198811696-9f63cf5f-5987-4f5a-ae0a-37dc73671319.png)

**Comment by huangliang0828** [comment]
Portable Orange 
[Orange3-3.32.0.zip](https://download.biolab.si/download/files/Orange3-3.32.0.zip)
This version is running ok！

**Comment by markotoplak** [comment]
The user actually said that the old version was running OK, not the new one. :) But I have no idea what would cause the difference. It ran for me.
