### ISSUE TITLE
python script widget - problem with target variable 

### ISSUE THREAD

**Issue by Alecampoy** [biolab/orange3#6216]
Hi all

In order to use FreeViz into notebooks, I am using the python script widget. The problem is that FreeViz is giving me an error  `AttributeError: 'NoneType' object has no attribute 'is_discrete'`. I believe the reason is that I have no target variable defined -I was able to make it work with iris-.  
Question: I have been checking the documentation for hours but have not found any clear way to define one column as the target value.
Here is a copy of my code with a simplified dataset

```
>>> Table('iris').domain
[sepal length, sepal width, petal length, petal width | iris]
# I believe that ' | iris' is defined here as target
>>> data = Table.from_file('dataset.csv')
>>> data.domain
[condicion, N_branches, Branch_total_length, Branch_mean_length]
>>> df.domain[:]
(DiscreteVariable(name='condicion', values=('B003', 'HDF', 'P129', 'P130', 'P131')), ContinuousVariable(name='N_branches', number_of_decimals=0), ContinuousVariable(name='Branch_total_length', number_of_decimals=3), ContinuousVariable(name='Branch_mean_length', number_of_decimals=3))
>>> freeviz = FreeViz()
>>> model = freeviz(data)
AttributeError: 'NoneType' object has no attribute 'is_discrete'

```

**Comment by markotoplak** [comment]
You are right, I did not see any examples covering this in the docs either. The way to do it is to make a new `Domain` with your features rearranged into `attributes` and `class_vars` as you wish and then convert the data into the new domain. Probably something like this:

```
ndom = Orange.data.Domain(data.domain.attributes[:-1], class_vars=[data.domain.attributes[-1])
ndata = data.transform(ndom)
```

The above code assumes that your last column is your class. Modify accordingly.

If you have any ideas where and how to put this in the docs, you're welcome.

**Comment by Alecampoy** [comment]
Thank you very much, it worked. 
This domain and its handling is a bit obscure to me, I was looking in the documentation something analogous to dataframe feature handling for tables.
