### ISSUE TITLE
Test and Score Widget - Select and output best performing Learner(s).

### ISSUE THREAD

**Issue by leonardosegurat** [biolab/orange3#6222]
**What's your use case?**
Test and Score widget is super useful at comparing different Learners, but you then have to open the widget, check which one performs best and manually output the best performing Learner from its origin widget.

In a scenario where different Learners or hyperparameters are appropriate, it might be useful to test and score all of them and pick the best performing one to downstream widgets, or the top n performing one to the Stack widget.

**What's your proposed solution?**
Add a selection feature to Test and Score widget, similar to the one currently present in the Rank widget, to select a Learner based on its performance.
Have the widget output the selected learner, and allow multiple learners to be sent in the output for the widgets that support it.

**Are there any alternative solutions?**
Currently, just tedious manual routing of the best performing widget to the rest of the workflow.

**Comment by janezd** [comment]
Automated selection would (a) require additional controls (number of selected models, at least), and would tempt users to overfit. More importantly, Orange has no signal "list of Learners". Even if Test and Score output such signal, nobody would accept it. Note that stacking accepts multiple learners, which is not the same as list of learners.

I instead implemented the option to select a learner from the table, and the widget outputs it. However, when I tried to test this on canvas, I realized that almost no widget accepts a learner on input, and the few that accept learners (imputation, predictions, polynomial classification/regression) don't seem like reasonable candidates for outputs from Test and Score.
