### ISSUE TITLE
orange not installing on anaconda. It shows installing but it never gets installed. i'm having trouble installing orange on my PC, even when it got installed it said "Application not responding".

### ISSUE THREAD

**Issue by CraigAlestonPinto** [biolab/orange3#6230]
**What's wrong?**

**How can we reproduce the problem?** 

**What's your environment?**

- Operating system:
- Orange version:
- How you installed Orange:

**Comment by markotoplak** [comment]
Could you please add additional details? Like your OS, Anaconda version, version of Orange that installed and your python version.

**Comment by CraigAlestonPinto** [comment]
it got downloaded on anaconda. I'm so happy!, i just went to environments and i clicked the play button on orange, which is below the base root.
