### ISSUE TITLE
BUG: Zoom-In keyboard shortcut not working

### ISSUE THREAD

**Issue by dsanalytics** [biolab/orange3#6240]
It seems that the zoom-in shortcut Ctrl-+ is not working. Menu item for zoom-in works. No errors or crashes.

Env: Orange 3.33 + Windows10 Pro 64bit

**Comment by janezd** [comment]
Which keyboard layout do you use?

**Comment by dsanalytics** [comment]
Standard qwerty English US. No fancy macros or media buttons.

**Comment by ales-erjavec** [comment]
Did you try <kbd>ctrl+shift+=</kbd>?

**Comment by dsanalytics** [comment]
Yes, Ctrl-Shft-+ works. Ctrl-+ does nothing as it seems, thus it's available. Menu shortcut info shows what I tried.

![image](https://user-images.githubusercontent.com/32625394/207759089-e0faf6a5-5a4c-4a69-a4d6-54be13259b07.png)

**Comment by markotoplak** [comment]
@dsanalytics, weren't you originally pressing Ctrl+=? I think that particular key is a = if you do not press shift. 

Firefox, for example, works with both, Ctrl-+ and Ctrl-=. Should we also make Ctrl-= do the same in Orange?

**Comment by dsanalytics** [comment]
It's really up to the team, but yes, I was actually trying FF shortcuts - those are very common. MS Edge uses those as well, and most likely Chrome too. Also, FF and Edge have Ctrl-0 which returns to the default zoom no matter what the current zoom level is.

See what you can do if you have some time - thank you in advance.
