### ISSUE TITLE
Feature Constructor: change Select Feature dropdown to Select Variable or Select Column and offer more options to manipulate metas

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3#6253]
**What's your use case?**
In Feature Constructor, sometimes it makes sense to use an expression referring to a meta variable - for instance if the meta variable contains a number that has a meaning other than identifying the record. It is possible to manually type a meta variable into an expression, which is indeed parsed as would be intended, but metas cannot be selected from the Select Feature drop-down because they are not features.
Also, although manually typing the name works, if a new column refers to a meta variable, it automatically becomes another meta variable, with no option in any downstream widget (as far as I know) to change it to a feature. 
Likewise, it might also make sense to create a new variable using an expression referring to a target, rather than to other features.

**What's your proposed solution?**
Add all column names to the dropdown that is currently called Select Feature, and rename the dropdown to reflect the new functionality
Since the widget is named Feature constructor, it might make sense if all new variables that it outputs are features by default, even if they depend on an expression referring to a meta. On the other hand, there might als be use cases for creating new metas or targets

**Are there any alternative solutions?**
There might be some cumbersome workaround, but I haven't found one yet.

**Comment by wvdvegte** [comment]
I realized the metas are at the bottom of the drop-down list where I overlooked them.
Also, if all the values in the meta variable are numbers, it is possible to convert the meta variable to a numeric feature with Edit Domain. In my case, some cells contained text rather than numbers.
What still stands, ist that "Select Feature" is perhaps not the best name for the drop-down menu.

**Comment by janezd** [comment]
I'm puzzled: I just tried it, and it showed me meta attributes as well as target, and it puts a numeric feature constructed from meta attribute into normal features.

In the figure below, "type" is a target and "name" is meta attribute.

<img width="496" alt="Screenshot 2022-12-09 at 16 52 16" src="https://user-images.githubusercontent.com/2387315/206741325-78d13280-d72b-4f81-b343-b0cff9b26452.png">

**Comment by wvdvegte** [comment]
Yes, I discovered my problem had several different reasons - see my closing comment
Sorry for bothering you.
Only thing is that "Select Feature" is perhaps not the best name for the drop-down menu.

**Comment by janezd** [comment]
I see, I should have waited with my answer.

You're right, Select Variable would be better.

**Comment by wvdvegte** [comment]
What is perhaps also confusing, is that metas always come first in table view, yet at the very end in the drop-down menu

**Comment by janezd** [comment]
I agree, this is inconsistent. The "standard" order in combo boxes is target, metas, features (while in tables, metas come first). Yet in some contexts the order is changed according to expected use.

In this widgets, metas are seldom used, so they're at the bottom. Some widgets put them at the top, for instance when the user chooses the label, which would typically be some text.

I guess we'll keep the order as it is for now, but we'll keep this in mind in general.
