### ISSUE TITLE
Orange sw and notebook fatal crash - widget Topic Modeling 

### ISSUE THREAD

**Issue by MircoUNIMIB** [biolab/orange3#6275]
Windows 11 Home 
Orange 3.34

Anytime I try to use the "Topic Modeling" widget, pc crashes and have to restart the notebook. A few weeks ago had a fatal crash and spent hours with pc manufacturer customer service to reset the (new) notebook.

Have re-installed Orange from scratch and restarted the full (educational) project for data-mining but again have same issue and can move forward with the project.

Thanks, Mirco

**Comment by janezd** [comment]
Please tell us more. What were you doing with Topic Modeling, what kind of data did you have and so on? Topic modeling passes automated tests and works for those who developed it, so just knowing that it crashed for somebody doesn't help a lot in diagnosing the issue.

**Comment by janezd** [comment]
Closed due to inactivity.
