### ISSUE TITLE
My orange program was working correctly till yesterday. I can't open my work created in orange. I already changed the version but still I have the same error. Please help asap!

### ISSUE THREAD

**Issue by StephyCamacho** [biolab/orange3#6290]
**What's wrong?**

**How can we reproduce the problem?** 
 I opened Orange through Anaconda, I tried to open my recent work and I got an error. 

**What's your environment?**
 
- Operating system: Windows 10
- Orange version: Before update 3.32 now 3.33
- How you installed Orange: Anaconda. 

Here is the copy of my error 
Exception:
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 16397 (char 16396)
Module:
json.decoder:353
Version:
3.33.0
Environment:
Python 3.8.8 on Windows 10 10.0.22000 AMD64
Installed Packages:
AnyQt==0.2.0, Bottleneck==1.3.5, CacheControl==0.12.11, Orange3==3.33.0, Pillow==9.2.0, PyQt5-sip==12.11.0, PyQt5==5.15.7, PyQtWebEngine==5.15.4, PySocks==1.7.1, PyYAML==6.0, Pygments==2.13.0, QtPy==2.2.1, XlsxWriter==3.0.3, anyio==3.6.2, asttokens==2.0.8, backcall==0.2.0, backports.functools-lru-cache==1.6.4, baycomp==1.0.2, brotlipy==0.7.0, catboost==1.1, certifi==2022.9.24, cffi==1.15.1, chardet==5.0.0, charset-normalizer==2.1.1, colorama==0.4.5, commonmark==0.9.1, contourpy==1.0.5, cryptography==38.0.2, cycler==0.11.0, debugpy==1.6.3, decorator==5.1.1, dictdiffer==0.9.0, docutils==0.19, entrypoints==0.4, et-xmlfile==1.0.1, executing==1.1.1, fonttools==4.37.4, future==0.18.2, graphviz==0.20.1, h11==0.12.0, h2==4.1.0, hpack==4.0.0, httpcore==0.15.0, httpx==0.23.0, hyperframe==6.0.1, idna==3.4, importlib-metadata==4.11.4, ipykernel==6.14.0, ipython-genutils==0.2.0, ipython==8.4.0, jaraco.classes==3.2.2, jedi==0.18.1, joblib==1.2.0, jupyter-client==7.4.3, jupyter-core==4.11.1, keyring==23.9.3, keyrings.alt==4.0.2, kiwisolver==1.4.4, lockfile==0.12.2, matplotlib-inline==0.1.6, matplotlib==3.6.1, more-itertools==9.0.0, msgpack==1.0.4, munkres==1.1.4, nest-asyncio==1.5.6, networkx==2.8.7, numpy==1.21.6, openTSNE==0.6.1, openpyxl==3.0.10, orange-canvas-core==0.1.27, orange-widget-base==4.18.0, packaging==21.3, pandas==1.4.4, parso==0.8.3, pickleshare==0.7.5, pip==22.3, plotly==5.10.0, ply==3.11, prompt-toolkit==3.0.31, psutil==5.9.3, pure-eval==0.2.2, pyOpenSSL==22.1.0, pycparser==2.21, pyparsing==3.0.9, pyqtgraph==0.12.3, python-dateutil==2.8.2, python-louvain==0.15, pytz==2022.5, pywin32-ctypes==0.2.0, pywin32==303, pyzmq==24.0.1, qasync==0.23.0, qtconsole==5.3.2, requests==2.28.1, rfc3986==1.5.0, scikit-learn==1.1.2, scipy==1.7.3, serverfiles==0.3.0, setuptools==65.5.0, sip==6.7.2, six==1.16.0, sniffio==1.3.0, stack-data==0.5.1, tenacity==8.1.0, threadpoolctl==3.1.0, toml==0.10.2, tornado==6.2, traitlets==5.5.0, typing-extensions==4.4.0, unicodedata2==14.0.0, urllib3==1.26.11, wcwidth==0.2.5, wheel==0.37.1, win-inet-pton==1.1.0, xlrd==2.0.1, zipp==3.9.0
Machine ID:
2dc42d5d-f8af-4ab2-a096-2c4e4e68bf43
Stack Trace:
Traceback (most recent call last):
  File "C:\Users\Stephanny\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\application\canvasmain.py", line 1875, in open_recent
    if self.recent_scheme() == QDialog.Accepted:
  File "C:\Users\Stephanny\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\application\canvasmain.py", line 1813, in recent_scheme
    self.open_scheme_file(selected.path())
  File "C:\Users\Stephanny\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\application\canvasmain.py", line 1066, in open_scheme_file
    window.load_scheme(filename)
  File "C:\Users\Stephanny\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\application\canvasmain.py", line 1175, in load_scheme
    self.set_scheme(new_scheme, freeze_creation=True)
  File "C:\Users\Stephanny\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\application\canvasmain.py", line 1386, in set_scheme
    scheme_doc.setScheme(new_scheme)
  File "C:\Users\Stephanny\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\document\schemeedit.py", line 835, in setScheme
    self.__statistics.write_statistics()
  File "C:\Users\Stephanny\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\document\usagestatistics.py", line 425, in write_statistics
    data = json.load(f)
  File "C:\Users\Stephanny\AppData\Local\Programs\Orange\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Stephanny\AppData\Local\Programs\Orange\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Stephanny\AppData\Local\Programs\Orange\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Stephanny\AppData\Local\Programs\Orange\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 16397 (char 16396)

Local Variables:
OrderedDict([('idx', 0),
             ('s',
              '[{"Date": "2022-12-11", "Application Version": "3.33.0", '
              '"Operating System": "Windows 10", "Launch Count": 4, "Session": '
              '[{"Type": 1, "Events": [{"Type": 0, "Widget Name": '
              '"orange.widgets.data.file", "Widget": 0}]}, {"Type": 1, '
              '"Events": [{"Type": 0, "Widget Name": '
              '"orange.widgets.data.file", "Widget": 1}]}, {"Type": 0, '
              '"Events": [{"Type": 1, "Widget": 1}]}, {"Type": 1, "Events": '
              '[{"Type": 0, "Widget Name": "orange.widgets.data.info", '
              '"Widget": 2}]}, {"Type": 1, "Events": [{"Type": 0, "Widget '
              'Name": "orange.widgets.data.info", "Widget": 3}]}, {"Type": 0, '
              '"Events": [{"Type": 1, "Widget": 3}]}, {"Type": 0, "Events": '
              '[{"Type": 2, "Source Widget": 0, "Sink Widget": 2, "Source '
              'Channel": "Data", "Sink Channel": "Data", "Source Open": false, '
              '"Sink Open:": false}]}, {"Type": 1, "Events": [{"Type": 0, '
              '"Widget Name": "Orange.widgets.data.owtable", "Widget": 4}]}, '
              '{"Type": 1, "Events": [{"Type": 0, "Widget Name": '
              '"Orange.widgets.data.owtable", "Widget": 5}]}, {"Type": 0, '
              '"Events": [{"Type": 1, "Widget": 5}]}, {"Type": 0, "Events": '
              '[{"Type": 2, "Source Widget": 0, "Sink Widget": 4, "Source '
              'Channel": "Data", "Sink Channel": "Data", "Source Open": false, '
              '"Sink Open:": false}]}, {"Type": 4, "Events": [{"Type": 0, '
              '"Widget Name": "Orange.widgets.data.owpaintdata", "Widget": 6}, '
              '{"Type": 2, "Source Widget": 0, "Sink Widget": 6, "Source '
              'Channel": "Data", "Sink Channel": "Data", "Source Open": false, '
              '"Sink Open:": false}], "Extended Widget": 0, "Query": ""}, '
              '{"Type": 0, "Events": [{"Type": 3, "Source Widget": 0, "Sink '
              'Widget": 6, "Source Channel": "Data", "Sink Channel": "Data", '
              '"Source Open": false, "Sink Open:": false}, {"Type": 1, '
              '"Widget": 6}]}, {"Type": 1, "Events": [{"Type": 0, "Widget '
              'Name": "Orange.widgets.data.owfeaturestatistics", "Widget": '
              '7}]}, {"Type": 0, "Events": [{"Type": 2, "Source Widget": 0, '
              '"Sink Widget": 7, "Source Channel": "Data", "Sink Channel": '
              '"Data", "Source Open": false, "Sink Open:": false}]}, {"Type": '
              '1, "Events": [{"Type": 0, "Widget Name": '
              '"Orange.widgets.visualize.owdistributions", "Widget": 8}]}, '
              '{"Type": 1, "Events": [{"Type": 0, "Widget Name": '
              '"Orange.widgets.visualize.owdistributions", "Widget": 9}]}, '
              '{"Type": 0, "Events": [{"Type": 1, "Widget": 9}]}, {"Type": 0, '
              '"Events": [{"Type": 3, "Source Widget": 0, "Sink Widget": 7, '
              '"Source Channel": "Data", "Sink Channel": "Data", "Source '
              'Open": false, "Sink Open:": false}, {"Type": 1, "Widget": 7}]}, '
              '{"Type": 0, "Events": [{"Type": 2, "Source Widget": 0, "Sink '
              'Widget": 8, "Source Channel": "Data", "Sink Channel": "Data", '
              '"Source Open": false, "Sink Open:": false}]}]}, {"Date": '
              '"2022-12-11", "Application Version": "3.33.0", "Operating '
              'System": "Windows 10", "Launch Count": 6, "Session": [{"Type": '
              '1, "Events": [{"Type": 0, "Widget Name": '
              '"orange.widgets.data.file", "Widget": 0}]}, {"Type": 1, '
              '"Events": [{"Type": 0, "Widget Name": '
              '"Orange.widgets.visualize.owdistributions", "Widget": 1}]}, '
              '{"Type": 0, "Events": [{"Type": 2, "Source Widget": 0, "Sink '
              'Widget": 1, "Source Channel": "Data", "Sink Channel": "Data", '
              '"Source Open": false, "Sink Open:": false}]}, {"Type": 1, '
              '"Events": [{"Type": 0, "Widget Name": '
              '"Orange.widgets.data.oweditdomain", "Widget": 2}]}, {"Type": 1, '
              '"Events": [{"Type": 0, "Widget Name": '
              '"Orange.widgets.data.oweditdomain", "Widget": 3}]}, {"Type": 0, '
              '"Events": [{"Type": 1, "Widget": 3}]}, {"Type": 0, "Events": '
              '[{"Type": 2, "Source Widget": 0, "Sink Widget": 2, "Source '
              'Channel": "Data", "Sink Channel": "Data", "Source Open": false, '
              '"Sink Open:": false}]}, {"Type": 2, "Events": [{"Type": 0, '
              '"Widget Name": "Orange.widgets.data.owselectrows", "Widget": '
              '4}]}, {"Type": 2, "Events": [{"Type": 0, "Widget Name": '
              '"Orange.widgets.data.owselectcolumns", "Widget": 5}]}, {"Type": '
              '0, "Events": [{"Type": 2, "Source Widget": 2, "Sink Widget": 5, '
              '"Source Channel": "Data", "Sink Channel": "Data", "Source '
              'Open": false, "Sink Open:": false}]}, {"Type": 0, "Events": '
              '[{"Type": 2, "Source Widget": 2, "Sink Widget": 4, "Source '
              'Channel": "Data", "Sink Channel": "Data", "Source Open": false, '
              '"Sink Open:": false}]}, {"Type": 2, "Events": [{"Type": 0, '
              '"Widget Name": "Orange.widgets.data.owtable", "Widget": 6}]}, '
              '{"Type": 0, "Events": [{"Type": 2, "Source Widget": 5, "Sink '
              'Widget": 6, "Source Channel": "Data", "Sink Channel": "Data", '
              '"Source Open": false, "Sink Open:": false}]}, {"Type": 0, '
              '"Events": [{"Type": 3, "Source Widget": 5, "Sink Widget": 6, '
              '"Source Channel": "Data", "Sink Channel": "Data", "Source '
              'Open": false, "Sink Open:": false}, {"Type": 1, "Widget": 6}]}, '
              '{"Type": 2, "Events": [{"Type": 0, "Widget Name": '
              '"Orange.widgets.data.owtable", "Widget": 7}]}, {"Type": 0, '
              '"Events": [{"Type": 2, "Source Widget": 5, "Sink Widget": 7, '
              '"Source Channel": "Data", "Sink Channel": "Data", "Source '
              'Open": false, "Sink Open:": false}]}, {"Type": 1, "Events": '
              '[{"Type": 0, "Widget Name": '
              '"Orange.widgets.visualize.owdistributions", "Widget": 8}]}, '
              '{"Type": 0, "Events": [{"Type": 3, "Source Widget": 2, "Sink '
              'Widget": 5, "Source Channel": "Data", "Sink Channel": "Data", '
              '"Source Open": false, "Sink Open:": false}, {"Type": 2, "Source '
              'Widget": 8, "Sink Widget": 5, "Source Channel": "Selected '
              'Data", "Sink Channel": "Data", "Source Open": false, "Sink '
              'Open:": false}]}, {"Type": 0, "Events": [{"Type": 3, "Source '
              'Widget": 8, "Sink Widget": 5, "Source Channel": "Selected '
              'Data", "Sink Channel": "Data", "Source Open": false, "Sink '
              'Open:": false}]}, {"Type": 0, "Events": [{"Type": 2, "Source '
              'Widget": 7, "Sink Widget": 8, "Source Channel": "Selected '
              'Data", "Sink Channel": "Data", "Source Open": false, "Sink '
              'Open:": false}]}, {"Type": 0, "Events": [{"Type": 3, "Source '
              'Widget": 7, "Sink Widget": 8, "Source Channel": "Selected '
              'Data", "Sink Channel": "Data", "Source Open": false, "Sink '
              'Open:": false}, {"Type": 1, "Widget": 8}]}, {"Type": 0, '
              '"Events": [{"Type": 2, "Source Widget": 2, "Sink Widget": 5, '
              '"Source Channel": "Data", "Sink Channel": "Data", "Source '
              'Open": false, "Sink Open:": false}]}, {"Type": 4, "Events": '
              '[{"Type": 0, "Widget Name": "Orange.widgets.data.owtable", '
              '"Widget": 9}, {"Type": 2, "Source Widget": 4, "Sink Widget": 9, '
              '"Source Channel": "Matching Data", "Sink Channel": "Data", '
              '"Source Open": false, "Sink Open:": false}], "Extended Widget": '
              '4, "Query": ""}, {"Type": 4, "Events": [{"Type": 0, "Widget '
              'Name": "Orange.widgets.visualize.owdistributions", "Widget": '
              '10}, {"Type": 2, "Source Widget": 9, "Sink Widget": 10, "Source '
              'Channel": "Selected Data", "Sink Channel": "Data", "Source '
              'Open": false, "Sink Open:": false}], "Extended Widget": 9, '
              '"Query": ""}, {"Type": 0, "Events": [{"Type": 3, "Source '
              'Widget": 9, "Sink Widget": 10, "Source Channel": "Selected '
              'Data", "Sink Channel": "Data", "Source Open": false, "Sink '
              'Open:": false}, {"Type": 1, "Widget": 10}]}, {"Type": 0, '
              '"Events": [{"Type": 3, "Source Widget": 4, "Sink Widget": 9, '
              '"Source Channel": "Matching Data", "Sink Channel": "Data", '
              '"Source Open": false, "Sink Open:": false}, {"Type": 1, '
              '"Widget": 9}]}, {"Type": 2, "Events": [{"Type": 0, "Widget '
              'Name": "Orange.widgets.data.owdatasets", "Widget": 11}]}, '
              '{"Type": 1, "Events": [{"Type": 0, "Widget Name": '
              '"Orange.widgets.visualize.owdistributions", "Widget": 12}]}, '
              '{"Type": 1, "Events": [{"Type": 0, "Widget Name": '
              '"Orange.widgets.visualize.owdistributions", "Widget": 13}]}, '
              '{"Type": 0, "Events": [{"Type": 1, "Widget": 13}]}, {"Type": 0, '
              '"Events": [{"Type": 2, "Source Widget": 11, "Sink Widget": 12, '
              '"Source Channel": "Data", "Sink Channel": "Data", "Source '
              'Open": false, "Sink Open:": false}]}, {"Type": 0, "Events": '
              '[{"Type": 3, "Source Widget": 11, "Sink Widget": 12, "Source '
              'Channel": "Data", "Sink Channel": "Data", "Source Open": false, '
              '"Sink Open:": false}, {"Type": 1, "Widget": 12}]}, {"Type": 0, '
              '"Events": [{"Type": 1, "Widget": 11}]}, {"Type": 1, "Events": '
              '[{"Type": 0, "Widget Name": "Orange.widgets.data.owdatasets", '
              '"Widget": 14}]}, {"Type": 2, "Events": [{"Type": 0, "Widget '
              'Name": "Orange.widgets.visualize.owdistributions", "Widget": '
              '15}]}, {"Type": 0, "Events": [{"Type": 2, "Source Widget": 14, '
              '"Sink Widget": 15, "Source Channel": "Data", "Sink Channel": '
              '"Data", "Source Open": false, "Sink Open:": false}]}, {"Type": '
              '2, "Events": [{"Type": 0, "Widget Name": '
              '"Orange.widgets.data.owselectrows", "Widget": 16}]}, {"Type": '
              '0, "Events": [{"Type": 2, "Source Widget": 14, "Sink Widget": '
              '16, "Source Channel": "Data", "Sink Channel": "Data", "Source '
              'Open": false, "Sink Open:": false}]}, {"Type": 1, "Events": '
              '[{"Type": 0, "Widget Name": '
              '"Orange.widgets.data.owdatasampler", "Widget": 17}]}, {"Type": '
              '1, "Events": [{"Type": 0, "Widget Name": '
              '"Orange.widgets.data.owdatasampler", "Widget": 18}]}, {"Type": '
              '0, "Events": [{"Type": 1, "Widget": 18}]}, {"Type": 0, '
              '"Events": [{"Type": 2, "Source Widget": 16, "Sink Widget": 17, '
              '"Source Channel": "Matching Data", "Sink Channel": "Data", '
              '"Source Open": false, "Sink Open:": false}]}, {"Type": 2, '
              '"Events": [{"Type": 0, "Widget Name": '
              '"Orange.widgets.data.owconcatenate", "Widget": 19}]}, {"Type": '
              '0, "Events": [{"Type": 2, "Source Widget": 16, "Sink Widget": '
              '19, "Source Channel": "Matching Data", "Sink Channel": '
              '"Additional Data", "Source Open": false, "Sink Open:": '
              'false}]}, {"Type": 0, "Events": [{"Type": 3, "Source Widget": '
              '16, "Sink Widget": 19, "Source Channel": "Matching Data", "Sink '
              'Channel": "Additional Data", "Source Open": false, "Sink '
              'Open:": false}]}, {"Type": 0, "Events": [{"Type": 2, "Source '
              'Widget": 16, "Sink Widget": 19, "Source Channel": "Unmatched '
              'Data", "Sink Channel": "Additional Data", "Source Open": false, '
              '"Sink Open:": false}]}, {"Type": 0, "Events": [{"Type": 2, '
              '"Source Widget": 17, "Sink Widget": 19, "Source Channel": "Data '
              'Sample", "Sink Channel": "Additional Data", "Source Open": '
              'false, "Sink Open:": false}]}, {"Type": 2, "Events": [{"Type": '
              '0, "Widget Name": "Orange.widgets.visualize.owdistributions", '
              '"Widget": 20}]}, {"Type": 0, "Events": [{"Type": 2, "Source '
              'Widget": 19, "Sink Widget": 20, "Source Channel": "Data", "Sink '
              'Channel": "Data", "Source Open": false, "Sink Open:": false}]}, '
              '{"Type": 0, "Events": [{"Type": 3, "Source Widget": 17, "Sink '
              'Widget": 19, "Source Channel": "Data Sample", "Sink Channel": '
              '"Additional Data", "Source Open": false, "Sink Open:": '
              'false}]}, {"Type": 0, "Events": [{"Type": 2, "Source Widget": '
              '17, "Sink Widget": 19, "Source Channel": "Remaining Data", '
              '"Sink Channel": "Additional Data", "Source Open": false, "Sink '
              'Open:": false}]}, {"Type": 0, "Events": [{"Type": 3, "Source '
              'Widget": 17, "Sink Widget": 19, "Source Channel": "Remaining '
              'Data", "Sink Channel": "Additional Data", "Source Open": false, '
              '"Sink Open:": false}]}, {"Type": 0, "Events": [{"Type": 2, '
              '"Source Widget": 17, "Sink Widget": 19, "Source Channel": '
              '"Remaining Data", "Sink Channel": "Primary Data", "Source '
              'Open": false, "Sink Open:": false}]}, {"Type": 0, "Events": '
              '[{"Type": 3, "Source Widget": 17, "Sink Widget": 19, "Source '
              'Channel": "Remaining Data", "Sink Channel": "Primary Data", '
              '"Source Open": false, "Sink Open:": false}]}, {"Type": 0, '
              '"Events": [{"Type": 2, "Source Widget": 17, "Sink Widget": 19, '
              '"Source Channel": "Remaining Data", "Sink Channel": "Additional '
              'Data", "Source Open": false, "Sink Open:": false}]}, {"Type": '
              '0, "Events": [{"Type": 3, "Source Widget": 16, "Sink Widget": '
              '19, "Source Channel": "Unmatched Data", "Sink Channel": '
              '"Additional Data", "Source Open": false, "Sink Open:": '
              'false}]}, {"Type": 0, "Events": [{"Type": 2, "Source Widget": '
              '16, "Sink Widget": 19, "Source Channel": "Unmatched Data", '
              '"Sink Channel": "Primary Data", "Source Open": false, "Sink '
              'Open:": false}]}, {"Type": 0, "Events": [{"Type": 3, "Source '
              'Widget": 17, "Sink Widget": 19, "Source Channel": "Remaining '
              'Data", "Sink Channel": "Additional Data", "Source Open": false, '
              '"Sink Open:": false}]}, {"Type": 0, "Events": [{"Type": 2, '
              '"Source Widget": 17, "Sink Widget": 19, "Source Channel": "Data '
              'Sample", "Sink Channel": "Additional Data", "Source Open": '
              'false, "Sink Open:": false}]}]}, {"Date": "2022-12-11", '
              '"Application Version": "3.33.0", "Operating System": "Windows '
              '10", "Launch Count": 6, "Session": []}, {"Date": "2022-12-29", '
              '"Application Version": "3.33.0", "Operating System": "Windows '
              '10", "Launch Count": 9, "Session": []}, {"Date": "2022-12-29", '
              '"Application Version": "3.33.0", "Operating System": "Windows '
              '10", "Launch Count": 9, "Session": [{"Type": 1, "Events": '
              '[{"Type": 0, "Widget Name": "orange.widgets.data.file", '
              '"Widget": 0}]}, {"Type": 1, "Events": [{"Type": 0, "Widget '
              'Name": "orange.widgets.data.file", "Widget": 1}]}, {"Type": 0, '
              '"Events": [{"Type": 1, "Widget": 1}]}, {"Type": 1, "Events": '
              '[{"Type": 0, "Widget Name": '
              '"Orange.widgets.data.owdatasampler", "Widget": 2}]}, {"Type": '
              '1, "Events": [{"Type": 0, "Widget Name": '
              '"Orange.widgets.data.owdatasampler", "Widget": 3}]}, {"Type": '
              '0, "Events": [{"Type": 1, "Widget": 3}]}, {"Type": 0, "Events": '
              '[{"Type": 2, "Source Widget": 0, "Sink Widget": 2, "Source '
              'Channel": "Data", "Sink Channel": "Data", "Source Open": false, '
              '"Sink Open:": false}]}, {"Type": 0, "Events": [{"Type": 3, '
              '"Source Widget": 0, "Sink Widget": 2, "Source Channel": "Data", '
              '"Sink Channel": "Data", "Source Open": false, "Sink Open:": '
              'false}, {"Type": 1, "Widget": 0}]}, {"Type": 1, "Events": '
              '[{"Type": 0, "Widget Name": "orange.widgets.data.file", '
              '"Widget": 4}]}, {"Type": 1, "Events": [{"Type": 0, "Widget '
              'Name": "orange.widgets.data.file", "Widget": 5}]}, {"Type": 0, '
              '"Events": [{"Type": 1, "Widget": 5}]}, {"Type": 0, "Events": '
              '[{"Type": 2, "Source Widget": 4, "Sink Widget": 2, "Source '
              'Channel": "Data", "Sink Channel": "Data", "Source Open": false, '
              '"Sink Open:": false}]}, {"Type": 2, "Events": [{"Type": 0, '
              '"Widget Name": "Orange.widgets.data.owtable", "Widget": 6}]}, '
              '{"Type": 0, "Events": [{"Type": 2, "Source Widget": 2, "Sink '
              'Widget": 6, "Source Channel": "Data Sample", "Sink Channel": '
              '"Data", "Source Open": false, "Sink Open:": false}]}, {"Type": '
              '2, "Events": [{"Type": 0, "Widget Name": '
              '"Orange.widgets.data.owtable", "Widget": 7}]}, {"Type": 0, '
              '"Events": [{"Type": 2, "Source Widget": 2, "Sink Widget": 7, '
              '"Source Channel": "Data Sample", "Sink Channel": "Data", '
              '"Source Open": false, "Sink Open:": false}]}, {"Type": 0, '
              '"Events": [{"Type": 3, "Source Widget": 2, "Sink Widget": 7, '
              '"Source Channel": "Data Sample", "Sink Channel": "Data", '
              '"Source Open": false, "Sink Open:": false}]}, {"Type": 0, '
              '"Events": [{"Type": 2, "Source Widget": 2, "Sink Widget": 7, '
              '"Source Channel": "Remaining Data", "Sink Channel": "Data", '
              '"Source Open": false, "Sink Open:": false}]}, {"Type": 2, '
              '"Events": [{"Type": 0, "Widget Name": '
              '"Orange.widgets.data.owdatasampler", "Widget": 8}]}, {"Type": '
              '0, "Events": [{"Type": 2, "Source Widget": 2, "Sink Widget": 8, '
              '"Source Channel": "Data Sample", "Sink Channel": "Data", '
              '"Source Open": false, "Sink Open:": false}]}, {"Type": 4, '
              '"Events": [{"Type": 0, "Widget Name": '
              '"Orange.widgets.model.owneuralnetwork", "Widget": 9}, {"Type": '
              '2, "Source Widget": 8, "Sink Widget": 9, "Source Channel": '
              '"Data Sample", "Sink Channel": "Data", "Source Open": false, '
              '"Sink Open:": false}], "Extended Widget": 8, "Query": ""}, '
              '{"Type": 2, "Events": [{"Type": 0, "Widget Name": '
              '"Orange.widgets.evaluate.owpredictions", "Widget": 10}]}, '
              '{"Type": 0, "Events": [{"Type": 2, "Source Widget": 9, "Sink '
              'Widget": 10, "Source Channel": "Model", "Sink Channel": '
              '"Predictors", "Source Open": false, "Sink Open:": false}]}, '
              '{"Type": 0, "Events": [{"Type": 2, "Source Widget": 8, "Sink '
              'Widget": 10, "Source Channel": "Data Sample", "Sink Channel": '
              '"Data", "Source Open": false, "Sink Open:": false}]}, {"Type": '
              '0, "Events": [{"Type": 3, "Source Widget": 8, "Sink Widget": '
              '10, "Source Channel": "Data Sample", "Sink Channel": "Data", '
              '"Source Open": false, "Sink Open:": false}]}, {"Type": 0, '
              '"Events": [{"Type": 2, "Source Widget": 8, "Sink Widget": 10, '
              '"Source Channel": "Remaining Data", "Sink Channel": "Data", '
              '"Source Open": false, "Sink Open:": false}]}, {"Type": 4, '
              '"Events": [{"Type": 0, "Widget Name": '
              '"Orange.widgets.visualize.owscatterplot", "Widget": 11}, '
              '{"Type": 2, "Source Widget": 10, "Sink Widget": 11, "Source '
              'Channel": "Predictions", "Sink Channel": "Data", "Source Open": '
              'false, "Sink Open:": false}], "Extended Widget": 10, "Query": '
              '""}, {"Type": 2, "Events": [{"Type": 0, "Widget Name": '
              '"Orange.widgets.data.owtable", "Widget": 12}]}, {"Type": 2, '
              '"Events": [{"Type": 0, "Widget Name": '
              '"Orange.widgets.data.owtable", "Widget": 13}]}, {"Type": 0, '
              '"Events": [{"Type": 3, "Source Widget": 2, "Sink Widget": 8, '
              '"Source Channel": "Data Sample"'),
             ('self', <json.decoder.JSONDecoder object at 0x000001414CFA1A60>)])

**Comment by ales-erjavec** [comment]
Go to *Options* -> *Settings*, navigate to *Reporting* tab and uncheck *Share* statistics.

Alternatively remove the C:\Users\%USERNAME%\AppData\Local\Orange\3.34.0\usage-statistics.json file

**Comment by luisipiri** [comment]
> Vaya a _Opciones_ -> _Configuración_ , vaya a la pestaña _Informes_ y desactive _Compartir_ estadísticas.
> 
> Alternativamente, elimine el archivo C:\Users%USERNAME%\AppData\Local\Orange\3.34.0\usage-statistics.json

**Comment by luisipiri** [comment]
> Vaya a _Opciones_ -> _Configuración_ , vaya a la pestaña _Informes_ y desactive _Compartir_ estadísticas.
> 
> Alternativamente, elimine el archivo C:\Users%USERNAME%\AppData\Local\Orange\3.34.0\usage-statistics.json

Funciona de nuevo, Thank You!!!!!

**Comment by StephyCamacho** [comment]
Thank you, After deleting the share statistics option, now everything works.
