### ISSUE TITLE
Mi programa Orange (version 3.30) funcionaba correctamente hasta hace dos dias. Ahora no me deja abrir mi trabajo en Orange. Ayuda por favorr!!!

### ISSUE THREAD

**Issue by luisipiri** [biolab/orange3#6291]
**What's wrong?**

![Sin título](https://user-images.githubusercontent.com/122522322/212025917-df2bb912-6dee-4c97-8f65-9807ee159ec0.png)

**How can we reproduce the problem?** 

**What's your environment?**

- Operating system: Windows 10 Home
- Orange version: 3.33.0
- How you installed Orange: web orange

**Comment by janezd** [comment]
Praktično podvojeno sporočilo #6290, le v španščini.

Poleg tega prosimo, da na tej strani uporabljate angleščino. Tudi ostali počnemo tako, čeprav je materni jezik večine razvijalcev slovenščina. Hvala!
