### ISSUE TITLE
Sorting data in a way that is preserved when saving the workflow

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3#6311]
**What's your use case?**
For many visualizations it is useful to have the data sorted by one variable ascending or descending. For instance, the silhouette plot in k-Means clustering has this built-in already.  It would be even nicer to also have the option to apply multiple sort keys (first sort by x, then by y, then by z). There are also other use cases where it is useful to have smallest or largest values first or a string variable in alphabetic order.
Currently, this is only possible in Data Table by clicking on column headers, then Select All -> the default output Selected Data will provide the sorted data. But if the workflow is saved and reopened, the sorting order and the selection are lost

**What's your proposed solution?**
Either have an option in Data Table to "Keep selection and sort order when saving", or have a separate Sort widget. The interface could be similar to Custom Sort in Excel:
<img width="566" alt="image" src="https://user-images.githubusercontent.com/55989717/214310549-520b7826-8eec-4b1f-b68d-32458e765c80.png">

**Are there any alternative solutions?**
As said, using Data Table, and add instructions for the manual work that must be done after opening the file - for instance in an annotation or in the description of the widget instance.

**Comment by janezd** [comment]
Combined into #6315.
