### ISSUE TITLE
Row number as a variable

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3#6312]
**What's your use case?**
When using Select Rows, it should also be possible to select by row number. For example, in some datasets from connected products, the first x rows originate from prototypes or they are otherwise not representative, for instance due to start-up problems. In such cases it is useful to be able to use "row number is greater than" as a row selection criterion.
I have also once encountered a situation where I would have liked to use the row number as a variable in Feature Constructor, but I cannot remember what the exact use case was ...

**What's your proposed solution?**
Make the row number available as a variable in Select Rows and Feature Constructor. Even better, allow use such as
`newvar := existingvar (row - 2) * othervar`
in Feature Constructor to refer to the value of a variable 2 rows back (which will of course not work for the first two rows

**Are there any alternative solutions?**
Yes:
- use a Python Script as suggested [here](https://discord.com/channels/633376992607076354/822470786346516501/940962165001695242) or
- abuse Melt and Group By as suggested [here](https://discord.com/channels/633376992607076354/822470786346516501/1016643062480511056)

**Comment by janezd** [comment]
To select, why wouldn't you just select rows in Table?

Otherwise, if row number is meaningful, it should in my opinion be simply another column in the data file.

**Comment by wvdvegte** [comment]
> To select, why wouldn't you just select rows in Table?

Because selections in Table are lost if the workflow is saved.

**Comment by janezd** [comment]
That that's what we should fix instead. :)

**Comment by wvdvegte** [comment]
> That that's what we should fix instead. :)

Then, please also save the sorting order (#6311) :)

**Comment by janezd** [comment]
Combined into #6315.
