### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by caonetto** [biolab/orange3#6328]
Installed in ubuntu following conda instructions.
`python3 -m Orange.canvas
Traceback (most recent call last):
  File "/scratch/anaconda3/envs/orange3/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/scratch/anaconda3/envs/orange3/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/scratch/anaconda3/envs/orange3/lib/python3.10/site-packages/Orange/__init__.py", line 4, in <module>
    from Orange import data
  File "/scratch/anaconda3/envs/orange3/lib/python3.10/site-packages/Orange/data/__init__.py", line 4, in <module>
    from .variable import *
  File "/scratch/anaconda3/envs/orange3/lib/python3.10/site-packages/Orange/data/variable.py", line 17, in <module>
    from Orange.util import Registry, Reprable, OrangeDeprecationWarning
  File "/scratch/anaconda3/envs/orange3/lib/python3.10/site-packages/Orange/util.py", line 10, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
`

**Comment by markotoplak** [comment]
Thanks! Could you type `conda list` in your orange3 conda environment and report the version of the `setuptools` package?

**Comment by markotoplak** [comment]
I just tried instructions in Ubuntu 20.04 with the same python version. It worked on my system.

Please execute the following commands and report back:
```
conda activate orange3
python -c "import setuptools; print(setuptools.__file__); print(setuptools.version)"
pip freeze
```

I suspect clashes between conda and (perhaps) some user-folder-installed python packages, but that is a wild guess.

**Comment by caonetto** [comment]
> 

Hi Mark,
Thanks for your quick answer. Setuptools does not appear as installed.

**Comment by markotoplak** [comment]
> Output from "pip freeze"
> 
> ```
> Traceback (most recent call last):
>   File "/scratch/anaconda3/envs/orange3/bin/pip", line 6, in <module>
>     from pip._internal.cli.main import main
> ModuleNotFoundError: No module named 'pip'
> ```

It seems that something is very wrong with your anaconda environment. I see that you are in the environment, but even pip is not installed properly. So this is not an Orange issue and I am thus closing it.

But we can continue communicating here and I'll try to help. Could you also do the following commands - perhaps that will show something useful:

```
conda activate orange3
python -c "import sys; print(sys.path)"
python -c "import site; print(site.USER_SITE)"
```

Please check if you have anything in the path returned by the last command.
