### ISSUE TITLE
Concatenate: data source ID is not used if compute_value is ignore in comparison

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#6332]
### Discussed in https://github.com/biolab/orange3/discussions/6326

<div type='discussions-op-text'>

<sup>Originally posted by **Bigfoot-solutions** February  3, 2023</sup>
I am trying to concatenate a set of 20 datasets and use the "Append data source ID" option to retain visibility into which data element came from which input source. 

The issue I am running into is that even though the input data tables have unique names in the UI (Unit A logs, Unit X logs, etc) the data info widget still displays the name of every data table as "untitled", and the Concatenate widget appends source ID's of "untitled (0)" and "untitled (1)" apparently based on the order in which the tables were connected to the Concatenate widget. I have a work-around using the Create Class widget to rename the Source ID, but this is very brittle. 

Am I doing something wrong or should this be a bug report? Is there a mechanism for naming data tables that I can't find in the documentation? 

Thanks for any help. </div>

**Comment by markotoplak** [comment]
An important detail: the shared workflow  used the "Treat variables with the same name..." option.

**Comment by markotoplak** [comment]
Fixed in #6331.

**Comment by PrimozGodec** [comment]
This PR can be closed, right?
