### ISSUE TITLE
Calibration Plot: Calibration curve does not show isotonic calibration

### ISSUE THREAD

**Issue by brunap** [biolab/orange3#6334]
**What's wrong?**

In Calibration Plot widget Calibration curve metric does not plot isotonic calibration curve.

I used housing data set with test&score widget set on Test on train data.

<img width="574" alt="Screenshot 2023-02-09 at 11 00 43" src="https://user-images.githubusercontent.com/11367976/217783557-50f4963c-1b60-4bdc-bd80-eeb6a71ce141.png">

- Operating system: macos bigsur
- Orange version: 3.34.1
- How you installed Orange: installer

**Comment by janezd** [comment]
@brunap, for me, this shows a red mark above the calibration plot, and says that "Calibration plot requires a categorical target variable" -- as it should.

Can you check that you're indeed using the housing data? The one with numeric attributes and target?

**Comment by brunap** [comment]
@janezd Lan and I used housing data.

**Comment by lanzagar** [comment]
Conclusion is that the visualization in the widget does not show the calibration itself but the (pre-calibration) discrepancy between predicted and "actual" probabilities.
The radio button changes calibration between logistic and isotonic and the model on the output reflects this. The visualization remains the same.
