### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by noahnovsak** [biolab/orange3#6339]
All our tests are failng, my best guess is has something to do with openTSNE. Everything works with version 0.6.2 but not version 0.7.0.

to reproduce run `python -m unittest -v Orange.widgets.unsupervised.tests.test_owmanifoldlearning`.

**Comment by pavlin-policar** [comment]
I've spent the day tracking down the elusive bug, and I'm working on a new release as we speak. It should be out in ~30mins.

**Comment by pavlin-policar** [comment]
I've rerun the tests on #6277, and the bug in question appears resolved. Some tests are still failing, but not due to openTSNE anymore.
