### ISSUE TITLE
running as administrator but still getting 'failed to create menus'

### ISSUE THREAD

**Issue by dac2020** [biolab/orange3#6342]
**What's wrong?**

On a fully updated Windows 7 machine, I am trying to install the latest downloaded from;
https://orangedatamining.com/download/#windows

I cannot give any additional information because there is none to be found in the logs.
As noted in the title; running as administrator but still getting 'failed to create menus'

I'm not sure how you can reproduce the problem because I've looked for hours on the Internet for help and many others seem to have had this same problem. I do not like trying posted fixes as those can often cause new problems with shortcuts and workarounds. This is a Win7 system being used for specific tasks and I cannot break it.

Happy to provide what ever other information you would like, just not sure what that could be at the moment.

The installation is a simple click on the file which starts the main installer which then starts the miniconda install which is what fails. I also turned off defender and there is no other protection program running.

**Comment by dac2020** [comment]
Ah, that's one thing I didn't come across in any of the posts I read. Thank you. I'll install on a newer OS.

**Comment by markotoplak** [comment]
@dac2020, if you needed Orange on Windows 7, you could also install it manually with `conda` with older python.
