### ISSUE TITLE
"ImportError: libGL.so.1: cannot open shared object file" on Ubuntu 20.04

### ISSUE THREAD

**Issue by pearlmary** [biolab/orange3#6344]
Installed the following:
Pip install Orange3
pip install PyQt5
pip install PyQt5-sip
pip install PyQtWebEngine

PyQt5                    5.15.9
PyQt5-Qt5                5.15.2
PyQt5-sip                12.11.1
pyqtgraph                0.13.1
PyQtWebEngine            5.15.6
PyQtWebEngine-Qt5        5.15.2
Orange3                  3.32.0
Python 3.8.12, Ubuntu 20.04, numpy 1.22.0

**But I’m stuck with this error for 3+days. Can you provide the solution?**

(fairmed) root@537614b35cbf:/workspace/MEDFAIR# python
Python 3.8.12 | packaged by conda-forge | (default, Jan 30 2022, 23:42:07) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Orange
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/fairmed/lib/python3.8/site-packages/Orange/__init__.py", line 33, in <module>
    import pyqtgraph  # import pyqtgraph first so that it can detect Qt5
  File "/workspace/fairmed/lib/python3.8/site-packages/pyqtgraph/__init__.py", line 18, in <module>
    from .colors import palette
  File "/workspace/fairmed/lib/python3.8/site-packages/pyqtgraph/colors/palette.py", line 1, in <module>
    from ..Qt import QtGui
  File "/workspace/fairmed/lib/python3.8/site-packages/pyqtgraph/Qt/__init__.py", line 156, in <module>
    import PyQt5.QtGui
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

**Comment by markotoplak** [comment]
For PyQt to work on Ubuntu, you also need some other libraries. This is not Orange specific and a bit of searching about PyQt on Ubuntu could get you the same info. We do the following on our test Ubuntu 20.04 computers: 

`sudo apt-get install -y libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 libegl1-mesa libxcb-shape0`

**Comment by markotoplak** [comment]
If you do not have permissions to modify system installed packages, you will need to use conda instead to install pyqt. I did not test that path, but often conda packages bundle more system libraries with them.

**Comment by pearlmary** [comment]
> For PyQt to work on Ubuntu, you also need some other (system) libraries. This is not Orange specific and a bit of searching about PyQt on Ubuntu could get you the same info. We do the following on our test Ubuntu 20.04 computers:
> 
> `sudo apt-get install -y libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 libegl1-mesa libxcb-shape0`

I've done it. But still this issue is not resolved. The same error is repeated.

**Comment by markotoplak** [comment]
Hm, that should take care of it. Could you also try `sudo apt-get install libgl1-mesa-dev` ?

**Comment by pearlmary** [comment]
> Hm, that should take care of it. Could you also try `sudo apt-get install libgl1-mesa-dev` ?

Really a magical answer. Thank you so much. Now I can import Orange without any errors.

**Comment by markotoplak** [comment]
Thanks for the report.
