### ISSUE TITLE
Multilingual Orange

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#6350]
On macOS I modified an installed bundle:

- renamed Orange to Orange-si; same for orangewidget and orangecanvas.
- copied translated sources to Orange-si, orangewidget-si, orangecanvas-si

Now I can do either `ln -s Orange-en Orange` or `ln -s Orange-si Orange` (and the same for others) to switch between English and Slovenian.

- Could this (where `ln -s` would of course happen within Orange settings) be a way to distribute multilingual Orange?
- This would also work for Linux, I guess. What about Windows? In the worst case, we could simply rename.

Reminder: we would need a Slovenian distribution of Orange by mid-march.

**Comment by nairboon** [comment]
Are translations back on the plan for the future? Compared to #5409

**Comment by janezd** [comment]
They absolutely are! See this: https://github.com/biolab/orange3/pull/6616.

We can easily publish Orange in Slovenian, but it is a separate release, which is annoying, and it also doesn't work well with add-ons. We now have a mechanism with which you can switch between languages, there's just a single nasty problem left to solve.

Why are you asking?

**Comment by janezd** [comment]
Orange 3.38 supports switching between languages. Currently between English and Slovenian. :) Supporting other languages is only a question of having a (very dedicated) translator.

**Comment by vlebedynska** [comment]
Dear @janezd, I would like to contribute with a German translation. Is anyone already working on it?

**Comment by janezd** [comment]
No, there is no particular rush. :)

If you volunteer for this, it would be great!

Here are the [message files](https://github.com/user-attachments/files/18292168/msgs.zip) for the three core parts (widget base, canvas, orange). Null's need to be replaced either by translations or by `true`, which means that translation is not needed (this most often occurs for some kind of formatting strings or colors).

The file format is a simplified version of yaml; see [documentation](http://vidra.si/trubar/message-files/).

I wanted to give you instructions for testing your translations (it's encouraging to see how you progress :), but then I realized I don't have a good workflow for it. I'll have to think about it and get back to you.

Let me know if you need any help.

**Comment by janezd** [comment]
#7166 reminded me of this old outstanding debt (thanks @gengyabc!)

The process looks complicated, but it should work smoothly once you get it working. 

### Preparation

- Download and unzip the [current message files](https://github.com/user-attachments/files/22872941/orange-messages.zip)

- Clone or download repositories [orange3](https://github.com/biolab/orange3), [orange-canvas-core](https://github.com/biolab/orange-canvas-core) and [orange-widget-base](https://github.com/biolab/orange-widget-base). I'll assume they're in neighbouring directories.

- Create an environment for testing translations. My (weird) workflow is this:

  ```
  conda create -n o3-translation python=3.12
  conda activate o3-translation
  pip install pyqt6 orange3 cython trubar
  pip uninstall orange3
  ```

  Note: I do this because `pip install orange3` is the simplest way to get all dependencies, but we do `pip uninstall orange3` because we want to install our local version of Orange. (Uninstallation is perhaps unnecessary.) Instead of conda, you can use venv or any other environment manager.

- Configure the new language
  - In orange3/i18n, create a directory "de" or whatever language code (as a sibling of, say, "si")
  - Put the file msgs-orange3.jaml into the new directory; rename the file to msgs.jaml. 
  - open orange3/i18n/trubar-config.yaml, add a section for "de" (or whatever code), like this:
  
    ```
    de:
      name: Deutsch
      international-name: German
    ```

    Do the same for orange-canvas-core and orange-widget-base.
 
For the time being, let us forget about static files and auto-imports for functions for selecting plural forms - let's just get this working.

### Translation cycle

- Pick one widget, find the corresponding messages (e.g. search for owtable.py) and translate them.

   Note that these are f-strings (or sometimes strings for interpolation with `format` or `%`), so you have to include the `{variable}`, `{}` and `%` parts where necessary.

- Install orange-canvas-core and orange3:

    ```
	cd orange-canvas-core
	python setup.py install
	cd ../orange3
	python setup.py install
    cd .. # Important! Do not run Orange from orange3 directory -- it won't work.
    ```

    The trick is that setup will not only install Orange but also prepare compiled message tables. I could someday prepare a version of Trubar that would modify message tables in a more "on-the-fly" fashion, which will make this much simpler and faster -- but I have absolutely no time at the moment.

    Note: Whenever you run `python setup.py install` in orange-canvas-core, you will need to run it in orange3 as 
	well, otherwise Orange won't see other languages than English. This will not be a huge inconvenience, as there is not so much to translate in Orange Canvas Core.
	
- (**You will do this only once.**) Open Orange with `python -m Orange.canvas`. Open Preferences; German language should be available. Select it, restart Orange.

- Check the translation in the widget you translated.

Repeat this cycle (except switching to German) when you add or modify translations, you need to re-run `python setup.py install` in orange3 (or orange-canvas-core and then orange3) to update the compiled message tables.

### Language-specific details

The process refers to German language but it's obviously the same for any other language.

 ... except for helper functions, like `pl` in https://github.com/biolab/orange-canvas-core/blob/master/orangecanvas/localization/__init__.py for English and https://github.com/biolab/orange-canvas-core/blob/master/orangecanvas/localization/si.py for Slovenian.

ChatGPT wrote [this](https://chatgpt.com/s/t_68ebddf6bae48191b7c4d5c8b4772903) for German. Note that translator would let the function use the rule only if (s)he knows the rule applies to the particular word (e.g., for Apfel, you need to provide the function with both forms).

This can be done perfectly. Slovenian has four plural forms (with matching between nouns, adjective and verbs etc), but translations is grammatically correct (to my knowledge).

I know some German and could be of some minor assistance. As for Chinese, I fear I can't promise more than help with technical details.
