### ISSUE TITLE
SQL Table issue with mssql  pymssql

### ISSUE THREAD

**Issue by magicdeveloper** [biolab/orange3#6355]
**What's wrong?**

When I try to connect to MSSQL SERVER via Orange SQL Table I get next error
**Unable to connect: Adaptive Server is unavailable or does not exist**
 I have already install pymssql

put when I connect via python code using jupiter notebook with pymssql lib it is working fine like this

```
import pymssql 
print(pymssql.__version__)

host="RY0DGISSQL01"
server=r"RY0DGISSQL01\GISDEV,62500"  ## Here is the problem in Orange , I try "RY0DGISSQL01/GISDEV,62500" but still not working
port="62500"
user = "myuser"
password = "mypass"
database="GDC"

conn = pymssql.connect(host=host, server=server, port=port, user=user, password=password, database=database)

cursor = conn.cursor()
cursor.execute('SELECT *  FROM MyTable)

for row in cursor:
    print('row = %r' % (row,))  ## it is working fine and print my table
    

conn.close()



```

### I think Orange SQL Table screen needs to be modified to pass the port number and host name 
 my SQL server is "RY0DGISSQL01\GISDEV,62500"

I have no problem with connection via python code 
problem only with Orange SQL Table

Please Help

**Comment by lanzagar** [comment]
You can already pass the host name and port number to Orange, but they should be separated with a colon not a comma.
In the `Server` field specify `hostname:port`
If you still have problems, please attach a screenshot of the SQL Table widget with your connection parameters and the error.
