### ISSUE TITLE
Changing the classification target in the Test and Score widget does not change the confusion matrix numbers

### ISSUE THREAD

**Issue by rehoyt** [biolab/orange3#6386]
**What's wrong?**

**How can we reproduce the problem?** 

**What's your environment?**

- Operating system: MacOS: Ventura 13.2.1
- Orange version: 3.34.1
- How you installed Orange: download from website

**Comment by janezd** [comment]
Works as intended. Why would you expect them to change?

**Comment by rehoyt** [comment]
The confusion matrix can be confusing. We thought that when you selected the target = 0 it became 1 so the confusion matrix would change. I tried to pose a similar scenario in ChatGPT and here is their explanation in two screenshots
![image](https://user-images.githubusercontent.com/25651922/229297679-ae2a3051-4d14-4f97-91ea-ceac2c7cc90b.png)

![image](https://user-images.githubusercontent.com/25651922/229297634-1e8e0461-4769-4f12-b4ec-8fb4d2166a91.png)

**Comment by janezd** [comment]
Not in Orange.

https://orangedatamining.com/widget-catalog/evaluate/confusionmatrix/

>  I tried to pose a similar scenario in ChatGPT

Please don't use ChatGPT as an argument. :)
