### ISSUE TITLE
Square grid in Self-Organizing Map not working

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/orange3#6424]
**What's wrong?**

When one changes the type of grid, a Square grid, nothing happens (the grid is still hexagonal). 

<img width="914" alt="Screenshot 2023-04-24 at 15 39 42" src="https://user-images.githubusercontent.com/6421558/234013789-d2a2b1f1-c116-4603-8153-4ca6e4117808.png">

**How can we reproduce the problem?** 

1. File widget->SOM 
2. Change the grid to Square.

**Comment by ales-erjavec** [comment]
Press *Start* to rerun the optimization. Grid topology is parameter of the algorithm not just a visualization option.

**Comment by PrimozGodec** [comment]
Thanks, @ales-erjavec. I was not careful enough. Then I suggest implementing the info that tells the user to press start, such as it is done in t-SNE. I can volunteer to implement that.
