### ISSUE TITLE
OLEDB Support

### ISSUE THREAD

**Issue by simonaubertbd** [biolab/orange3#6434]
**What's your use case?**
I would like to connect through oledb to an existing database (Oracle here)

Well, I can't connect to the said database :)

**What's your proposed solution?**
The SQL Table Widget should allow a connection through OLEDB

**Are there any alternative solutions?**
Using excel to export data in file... but it's an alternative like coca cola is an alternative to coffee.

**Comment by janezd** [comment]
You're right. Coca cola is great when you finish a long bicycle ride, find yourself in some town, and need to quickly grab something to rehydrate before catching a train back home. But it wouldn't do anything (useful) for me in the morning. They are not interchangeable.

Now for OLEDB. :) First, Orange was conceived with in-memory data and when we tried to make it more database friendly, it never led anywhere. So all we have is a widget that is able to get the data from database (into memory). Second, Orange runs on Windows, macOS and Linux, but only one person in a core team of 15 developers runs Windows.

Therefore, Orange is not strong in databases and we do not have Windows specifics in minds a lot. To my understanding, OLEDB is a database connector for Windows, right? :)

Can't you just use ODBC instead (assuming it works)?

**Comment by simonaubertbd** [comment]
Hello @janezd  First of all, thanks for the answer. Yeah OLEDB is Windows-specific, just usually faster than ODBC (which does not work on Orange with my favorite databases, but this is another issue I raised and I hope will meet more success^^).
Well, I tried ;)

Best regards,

Simon

PS : full in-database is pretty cool, especially when you have big data.

**Comment by janezd** [comment]
> PS : full in-database is pretty cool, especially when you have big data.

I understand and absolutely agree. The problem is that we'd have to do so from the beginning, and probably we'd also have to decide either for memory or database. Trying to support both in the same code was one big mess. :(
