### ISSUE TITLE
Widget search

### ISSUE THREAD

**Issue by simonaubertbd** [biolab/orange3#6447]
**What's your use case?**
Hello all,

A small quick-win : I noticed the widgets are not alphabetically ordered. I understand this may be to get the most used at first (or maybe something like that). However this means I loose time to find the correct widget I want to use.

**What's your proposed solution?**

So, what I propose is a "search" space over or at the beginning of the widget list.
![image](https://github.com/biolab/orange3/assets/46959192/03d09b9e-35af-4153-aa3a-9df7cb142f2a)

**Are there any alternative solutions?**

No

Best regards,

Simon

**Comment by simonaubertbd** [comment]
Ok, @markotoplak  answered me here https://github.com/biolab/orange-canvas-core/issues/273

**Comment by markotoplak** [comment]
I am reopening this for further discussion.

The quick menu I suggested is not something that is easily discoverable.

**Comment by simonaubertbd** [comment]
@markotoplak  First of all, thanks a lot for your answer. Maybe having always the search bar permanently displayed would be better for UI? Not that it's difficult to double-click but for beginners like me, it can be frustrating to search how to search ;)  On most of the softwares I use (Tableau, Qlik, Alteryx), it's always displayed.

Best regards,

Simon

**Comment by simonaubertbd** [comment]
@janezd Whooooah that's pretty cool :) Thanks for your work and the amazing reactivity of the team!

Best regards,

Simon

**Comment by janezd** [comment]
Thank ales-erjavec. :) His coding never ceases to amaze me. I thought this would be difficult (because it is), but he makes it look simple.

**Comment by simonaubertbd** [comment]
So a big thank to @ales-erjavec , this will change the users life. (at least mine ^^ )
