### ISSUE TITLE
Run workflow and Save Data in command line (for scheduling or other)

### ISSUE THREAD

**Issue by simonaubertbd** [biolab/orange3#6449]
**What's your use case?**
Hello all. I would like to schedule my workflow that generates some files.
![image](https://github.com/biolab/orange3/assets/46959192/586fd999-721a-411a-9664-3deb15087a13)
I have passed this command line on windows cmd :
C:\Users\saubert\AppData\Local\Programs\Orange\pythonw.exe -s -m Orange.canvas "C:\Users\saubert\OneDrive - Business & Decision\Documents\untitled.ows"

However the only thing it does is that it opens Orange with the workflow but the files are not generated at all and I have to go to save data widget and generate the file. To be frank, I'm not that surprised because I copy paste from the icon shortcut.

**What's your proposed solution?*
I would like a way to save my date when I launch the workflow from command line (also, maybe it could be nice to close Orange when it ends). Maybe with an argument in command line ? Maybe on option on the save data widget?

**Are there any alternative solutions?**
Yes, having a monkey who opens the workflow, makes it run, checks the generated files and closes it. But that's pretty expensive in bananas. Or Asok from Dilbert.
Joke apart, I don't find any.

Scheduling does matter a lot because it means you can launch workflow at night when you sleep (at least when I sleep) and find the results when you wake up instead of loosing time to launch it, wait,etc in the morning.

**Comment by ales-erjavec** [comment]
You can try:
```
python.exe -s -m Orange.canvas.run %WORKFLOWFILE%
```
but this is experimental as Orange is not designed to run non-interactive.

**Comment by simonaubertbd** [comment]
Hello @ales-erjavec Thanks for the help. Sadly, it doesn't seem to work.

**Comment by ales-erjavec** [comment]
> Sadly, it doesn't seem to work.

Can you be more specific? How does it fail?

**Comment by simonaubertbd** [comment]
Oh sorry @ales-erjavec ! So, there is no error on cmd but the files are not generated. 
Best regards,
Simon

**Comment by ales-erjavec** [comment]
Do you have 'Autosave when receiving new data' checked in the Save Data widgets.

Can you run with 
```
python.exe -s -m Orange.canvas.run  -l4 %WORKFLOWFILE%
```
for a more detailed output.

**Comment by simonaubertbd** [comment]
@ales-erjavec  I use several "save data" widgets, some with the 'Autosave when receiving new data' checked, some without.

with the option -l4, here the result 
`C:\Users\saubert>C:\Users\saubert\AppData\Local\Programs\Orange\python.exe -s -m Orange.canvas.run -l4 "C:\Users\saubert\OneDrive - Business & Decision\Documents\untitled.ows"
DEBUG:orangecanvas.config:Activating configuration for <Orange.canvas.config.Config object at 0x0000029C39B93A90>
DEBUG:orangecanvas.registry.cache:Loading widget registry cache ('C:/Users/saubert/AppData/Local/Orange/cache\\3.35.0\\registry-cache.pck').
INFO:orangecanvas.registry.base:A category with 'Data' name already exists
INFO:orangecanvas.registry.base:A category with 'Visualize' name already exists
INFO:orangecanvas.registry.discovery:Ignoring 'C:\\Users\\saubert\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\Orange\\widgets\\visualize\\owscatterplotgraph.py'.
INFO:orangecanvas.registry.discovery:Ignoring 'C:\\Users\\saubert\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\Orange\\widgets\\visualize\\owtreeviewer2d.py'.
INFO:orangecanvas.registry.discovery:Ignoring 'C:\\Users\\saubert\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\Orange\\widgets\\visualize\\pythagorastreeviewer.py'.
INFO:orangecanvas.registry.base:A category with 'Model' name already exists
INFO:orangecanvas.registry.base:A category with 'Evaluate' name already exists
INFO:orangecanvas.registry.discovery:Ignoring 'C:\\Users\\saubert\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\Orange\\widgets\\evaluate\\contexthandlers.py'.
INFO:orangecanvas.registry.discovery:Ignoring 'C:\\Users\\saubert\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\Orange\\widgets\\evaluate\\utils.py'.
INFO:orangecanvas.registry.base:A category with 'Unsupervised' name already exists
DEBUG:sql_log:Logging started: 2023-05-21 21:15:56
DEBUG:matplotlib:matplotlib data path: C:\Users\saubert\AppData\Local\Programs\Orange\lib\site-packages\matplotlib\mpl-data
DEBUG:matplotlib:CONFIGDIR=C:\Users\saubert\.matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is win32
INFO:orangecanvas.scheme.scheme:Added node 'CSV File Import' to scheme ''.
INFO:orangecanvas.scheme.scheme:Added node 'Group by' to scheme ''.
INFO:orangecanvas.scheme.scheme:Added node 'Save Data tab' to scheme ''.
INFO:orangecanvas.scheme.scheme:Added node 'Data Table' to scheme ''.
INFO:orangecanvas.scheme.scheme:Added node 'Save Data csv' to scheme ''.
INFO:orangecanvas.scheme.scheme:Added node 'Save Data' to scheme ''.
INFO:orangecanvas.scheme.scheme:Added node 'Data Info' to scheme ''.
INFO:orangecanvas.scheme.scheme:Added link 'CSV File Import' ('Data') -> 'Group by' ('Data') to scheme ''.
INFO:orangecanvas.scheme.signalmanager:Scheduling signal data update for 'SchemeLink((CSV File Import, Data) -> (Group by, Data))'.
INFO:orangecanvas.scheme.scheme:Added link 'Group by' ('Data') -> 'Data Table' ('Data') to scheme ''.
INFO:orangecanvas.scheme.signalmanager:Scheduling signal data update for 'SchemeLink((Group by, Data) -> (Data Table, Data))'.
INFO:orangecanvas.scheme.scheme:Added link 'Data Table' ('Data') -> 'Save Data tab' ('Data') to scheme ''.
INFO:orangecanvas.scheme.signalmanager:Scheduling signal data update for 'SchemeLink((Data Table, Data) -> (Save Data tab, Data))'.
INFO:orangecanvas.scheme.scheme:Added link 'Data Table' ('Data') -> 'Save Data csv' ('Data') to scheme ''.
INFO:orangecanvas.scheme.signalmanager:Scheduling signal data update for 'SchemeLink((Data Table, Data) -> (Save Data csv, Data))'.
INFO:orangecanvas.scheme.scheme:Added link 'CSV File Import' ('Data') -> 'Save Data' ('Data') to scheme ''.
INFO:orangecanvas.scheme.signalmanager:Scheduling signal data update for 'SchemeLink((CSV File Import, Data) -> (Save Data, Data))'.
INFO:orangecanvas.scheme.scheme:Added link 'CSV File Import' ('Data') -> 'Data Info' ('Data') to scheme ''.
INFO:orangecanvas.scheme.signalmanager:Scheduling signal data update for 'SchemeLink((CSV File Import, Data) -> (Data Info, Data))'.
DEBUG:orangecanvas.scheme.widgetmanager:Creating widget for node SchemeNode(description_id='Orange.widgets.data.owcsvimport', title='CSV File Import', ...)
INFO:orangewidget.workflow.widgetsscheme:WidgetManager: Creating 'Orange.widgets.data.owcsvimport.OWCSVFileImport' instance 'CSV File Import'.
DEBUG:orangecanvas.scheme.widgetmanager:Creating widget for node SchemeNode(description_id='Orange.widgets.data.owgroupby', title='Group by', ...)
INFO:orangewidget.workflow.widgetsscheme:WidgetManager: Creating 'Orange.widgets.data.owgroupby.OWGroupBy' instance 'Group by'.
DEBUG:orangecanvas.scheme.widgetmanager:Creating widget for node SchemeNode(description_id='Orange.widgets.data.owsave', title='Save Data tab', ...)
INFO:orangewidget.workflow.widgetsscheme:WidgetManager: Creating 'Orange.widgets.data.owsave.OWSave' instance 'Save Data tab'.
DEBUG:orangecanvas.scheme.widgetmanager:Creating widget for node SchemeNode(description_id='Orange.widgets.data.owtable', title='Data Table', ...)
INFO:orangewidget.workflow.widgetsscheme:WidgetManager: Creating 'Orange.widgets.data.owtable.OWTable' instance 'Data Table'.
DEBUG:orangecanvas.scheme.widgetmanager:Creating widget for node SchemeNode(description_id='Orange.widgets.data.owsave', title='Save Data csv', ...)
INFO:orangewidget.workflow.widgetsscheme:WidgetManager: Creating 'Orange.widgets.data.owsave.OWSave' instance 'Save Data csv'.
DEBUG:orangecanvas.scheme.widgetmanager:Creating widget for node SchemeNode(description_id='Orange.widgets.data.owsave', title='Save Data', ...)
INFO:orangewidget.workflow.widgetsscheme:WidgetManager: Creating 'Orange.widgets.data.owsave.OWSave' instance 'Save Data'.
DEBUG:orangecanvas.scheme.widgetmanager:Creating widget for node SchemeNode(description_id='orange.widgets.data.info', title='Data Info', ...)
INFO:orangewidget.workflow.widgetsscheme:WidgetManager: Creating 'Orange.widgets.data.owdatainfo.OWDataInfo' instance 'Data Info'.
DEBUG:orangecanvas.scheme.signalmanager:'CSV File Import' sending <class 'pandas.core.frame.DataFrame'> (id: None) on channel 'Data Frame'
DEBUG:orangecanvas.scheme.signalmanager:'CSV File Import' sending <class 'Orange.data.table.Table'> (id: None) on channel 'Data'
DEBUG:orangecanvas.scheme.signalmanager:Process next, queued signals: 3, nactive: 0 (max_active: 1)
DEBUG:orangecanvas.scheme.signalmanager:Pending nodes: ['Group by', 'Save Data', 'Data Info']
DEBUG:orangecanvas.scheme.signalmanager:Blocking nodes: []
DEBUG:orangecanvas.scheme.signalmanager:Invalidated nodes: []
DEBUG:orangecanvas.scheme.signalmanager:Nodes ready for update: ['Group by', 'Save Data', 'Data Info']
DEBUG:orangecanvas.scheme.signalmanager:Processing 'Group by', sending 1 signals.
DEBUG:orangecanvas.scheme.signalmanager:'Group by' sending <class 'NoneType'> (id: None) on channel 'Data'
DEBUG:orangecanvas.scheme.signalmanager:'Group by' sending <class 'Orange.data.table.Table'> (id: None) on channel 'Data'
DEBUG:orangecanvas.scheme.signalmanager:Process next, queued signals: 4, nactive: 0 (max_active: 1)
DEBUG:orangecanvas.scheme.signalmanager:Pending nodes: ['Save Data', 'Data Info', 'Data Table']
DEBUG:orangecanvas.scheme.signalmanager:Blocking nodes: []
DEBUG:orangecanvas.scheme.signalmanager:Invalidated nodes: []
DEBUG:orangecanvas.scheme.signalmanager:Nodes ready for update: ['Save Data', 'Data Info', 'Data Table']
DEBUG:orangecanvas.scheme.signalmanager:Processing 'Save Data', sending 1 signals.
DEBUG:orangecanvas.scheme.signalmanager:Process next, queued signals: 3, nactive: 0 (max_active: 1)
DEBUG:orangecanvas.scheme.signalmanager:Pending nodes: ['Data Info', 'Data Table']
DEBUG:orangecanvas.scheme.signalmanager:Blocking nodes: []
DEBUG:orangecanvas.scheme.signalmanager:Invalidated nodes: []
DEBUG:orangecanvas.scheme.signalmanager:Nodes ready for update: ['Data Info', 'Data Table']
DEBUG:orangecanvas.scheme.signalmanager:Processing 'Data Info', sending 1 signals.
DEBUG:orangecanvas.scheme.signalmanager:Process next, queued signals: 2, nactive: 0 (max_active: 1)
DEBUG:orangecanvas.scheme.signalmanager:Pending nodes: ['Data Table']
DEBUG:orangecanvas.scheme.signalmanager:Blocking nodes: []
DEBUG:orangecanvas.scheme.signalmanager:Invalidated nodes: []
DEBUG:orangecanvas.scheme.signalmanager:Nodes ready for update: ['Data Table']
DEBUG:orangecanvas.scheme.signalmanager:Processing 'Data Table', sending 2 signals.
DEBUG:orangecanvas.scheme.signalmanager:'Data Table' sending <class 'Orange.data.table.Table'> (id: None) on channel 'Selected Data'
DEBUG:orangecanvas.scheme.signalmanager:'Data Table' sending <class 'Orange.data.table.Table'> (id: None) on channel 'Data'
DEBUG:orangecanvas.scheme.signalmanager:Process next, queued signals: 2, nactive: 0 (max_active: 1)
DEBUG:orangecanvas.scheme.signalmanager:Pending nodes: ['Save Data tab', 'Save Data csv']
DEBUG:orangecanvas.scheme.signalmanager:Blocking nodes: []
DEBUG:orangecanvas.scheme.signalmanager:Invalidated nodes: []
DEBUG:orangecanvas.scheme.signalmanager:Nodes ready for update: ['Save Data tab', 'Save Data csv']
DEBUG:orangecanvas.scheme.signalmanager:Processing 'Save Data tab', sending 1 signals.
DEBUG:orangecanvas.scheme.signalmanager:Process next, queued signals: 1, nactive: 0 (max_active: 1)
DEBUG:orangecanvas.scheme.signalmanager:Pending nodes: ['Save Data csv']
DEBUG:orangecanvas.scheme.signalmanager:Blocking nodes: []
DEBUG:orangecanvas.scheme.signalmanager:Invalidated nodes: []
DEBUG:orangecanvas.scheme.signalmanager:Nodes ready for update: ['Save Data csv']
DEBUG:orangecanvas.scheme.signalmanager:Processing 'Save Data csv', sending 1 signals.
INFO:orangecanvas.scheme.signalmanager:Scheduling close signal (SchemeLink((Data Table, Data) -> (Save Data tab, Data))).
INFO:orangecanvas.scheme.scheme:Removed link 'Data Table' ('Data') -> 'Save Data tab' ('Data') from scheme ''.
INFO:orangecanvas.scheme.scheme:Removed node 'Save Data tab' from scheme ''.
INFO:orangecanvas.scheme.signalmanager:Removing pending signals for 'Save Data tab'.
INFO:orangecanvas.scheme.signalmanager:Scheduling close signal (SchemeLink((Data Table, Data) -> (Save Data csv, Data))).
INFO:orangecanvas.scheme.scheme:Removed link 'Data Table' ('Data') -> 'Save Data csv' ('Data') from scheme ''.
INFO:orangecanvas.scheme.scheme:Removed node 'Save Data csv' from scheme ''.
INFO:orangecanvas.scheme.signalmanager:Removing pending signals for 'Save Data csv'.
INFO:orangecanvas.scheme.signalmanager:Scheduling close signal (SchemeLink((CSV File Import, Data) -> (Save Data, Data))).
INFO:orangecanvas.scheme.scheme:Removed link 'CSV File Import' ('Data') -> 'Save Data' ('Data') from scheme ''.
INFO:orangecanvas.scheme.scheme:Removed node 'Save Data' from scheme ''.
INFO:orangecanvas.scheme.signalmanager:Removing pending signals for 'Save Data'.
INFO:orangecanvas.scheme.signalmanager:Scheduling close signal (SchemeLink((CSV File Import, Data) -> (Data Info, Data))).
INFO:orangecanvas.scheme.scheme:Removed link 'CSV File Import' ('Data') -> 'Data Info' ('Data') from scheme ''.
INFO:orangecanvas.scheme.scheme:Removed node 'Data Info' from scheme ''.
INFO:orangecanvas.scheme.signalmanager:Removing pending signals for 'Data Info'.
INFO:orangecanvas.scheme.signalmanager:Scheduling close signal (SchemeLink((Group by, Data) -> (Data Table, Data))).
INFO:orangecanvas.scheme.scheme:Removed link 'Group by' ('Data') -> 'Data Table' ('Data') from scheme ''.
INFO:orangecanvas.scheme.scheme:Removed node 'Data Table' from scheme ''.
INFO:orangecanvas.scheme.signalmanager:Removing pending signals for 'Data Table'.
INFO:orangecanvas.scheme.signalmanager:Scheduling close signal (SchemeLink((CSV File Import, Data) -> (Group by, Data))).
INFO:orangecanvas.scheme.scheme:Removed link 'CSV File Import' ('Data') -> 'Group by' ('Data') from scheme ''.
INFO:orangecanvas.scheme.scheme:Removed node 'Group by' from scheme ''.
INFO:orangecanvas.scheme.signalmanager:Removing pending signals for 'Group by'.
INFO:orangecanvas.scheme.scheme:Removed node 'CSV File Import' from scheme ''.
INFO:orangecanvas.scheme.signalmanager:Removing pending signals for 'CSV File Import'.
DEBUG:orangewidget.workflow.widgetsscheme:Destroyed namespace for: CSV File Import
DEBUG:orangewidget.workflow.widgetsscheme:Destroyed namespace for: Group by
DEBUG:orangewidget.workflow.widgetsscheme:Destroyed namespace for: Data Table
DEBUG:orangewidget.workflow.widgetsscheme:Destroyed namespace for: Data Info
DEBUG:orangewidget.workflow.widgetsscheme:Destroyed namespace for: Save Data
DEBUG:orangewidget.workflow.widgetsscheme:Destroyed namespace for: Save Data csv
DEBUG:orangewidget.workflow.widgetsscheme:Destroyed namespace for: Save Data tab
`

**Comment by simonaubertbd** [comment]
Hello @ales-erjavec Ok, it works with the file in the same repository, the autosave option and the python.exe cmd line ! Thank you !

However, maybe it's me but there is maybe a lack of documentation for that nice feature. What about the following :
-online documentation with example
-a little label on the widget itself (like "check autosave and the same folder than the workflow (or subfolder) if launched by command line")
-a warning message when running the cmd and the save data does not save because the path selected is not good.

Best regards,

Simon

**Comment by janezd** [comment]
@ales-erjavec added the warning. As for documentation for running orange workflows from command line, this is not the intended use of Orange and it is not really supported and necessarily maintained. We therefore wouldn't want to promote it in documentation. :)

**Comment by simonaubertbd** [comment]
@janezd whoah, that was fast O_o . Thanks for all !
