### ISSUE TITLE
Save Data to more file format (and databases)

### ISSUE THREAD

**Issue by simonaubertbd** [biolab/orange3#6451]
**What's your use case?**
I would like a better format for my saved data, something that can be fast and where fields are well typed (in a csv, it's not). Some of the format I use or enjoy the most :
-hyper/qvx for Tableau and Qlik
-duckdb, an open-source embedded database that is quite fast (by the way, very nice project)
-several database (such as monetdb/snowflake/Apache Impala... ) that could be adressed through bulk load and/or odbc
-json/xml

**What's your proposed solution?**
Well, to support more file format for saved data

**Are there any alternative solutions?**
don't think so?

**Comment by janezd** [comment]
We support the idea, but there are too many formats to support (and maintain). This should belong to an add-on.

If you wish, you can thus write an add-on that does not contain any widgets but only file readers. File readers register new formats and the File widget will recognize the formats. If the reader is more complicated, with more options, that would of course require entirely new widgets.
