### ISSUE TITLE
Display path of file in input/output widgets

### ISSUE THREAD

**Issue by simonaubertbd** [biolab/orange3#6453]
**What's your use case?**
I have several files that has the name, let's say a "poll result.csv" in a "year" folder like 2018/data/poll_result.csv
The csv widget only displays the name of the file and I have no idea of which it is.
Same for the saved data tool, I don't know in which subfolder I write.

**What's your proposed solution?**
to display the full path of the file (at least 64 characters and the ability to develop for full path)

**Are there any alternative solutions?**
Having a good memory. Joke apart, a double click on the folder icon and then a click on the adress bar.

**Comment by janezd** [comment]
We discussed this at the core meeting.

To me, having full paths looks ugly and is usually redundant. Also, other programs, like Word, show just the name (which, I admit, sometimes annoys me as well). We can easily do two things, though:

- put a tool tip with full path on the combo,
- show a relevant part of the path only for files with the same name as another file shown in the drop down.

Dropdown items already have tooltips with full paths.

**Comment by simonaubertbd** [comment]
Hello @janezd and @VesnaT 

First of all, thanks. 

And secondly, Sorry, I'm just testing it on my 3.36.1 (on windows) and i have the folder when I use the File widget but not with the CSV File Import. Is it wanted and I need to open another enhancement issue or is it a bug?
![image](https://github.com/biolab/orange3/assets/46959192/bfbea4f4-3f67-459e-a769-e832cc0fba17)
![image](https://github.com/biolab/orange3/assets/46959192/4cff5409-d14d-40c3-a167-73ecfb9e73bc)

Best regards,

Simon
