### ISSUE TITLE
how to rename the name of the widget icon on the canvas?

### ISSUE THREAD

**Issue by leaf918** [biolab/orange3#6455]
**What's your use case?**
I want to rename the name of the widget icon on the canvas programmlly.But I canot find a method for doing that.

![image](https://github.com/biolab/orange3/assets/170311/e6caee56-8e03-48a9-b3e9-adb05361161b)

**Comment by janezd** [comment]
By "programmatically" you mean from a script? Where would that script run? And when?

You can modify an .ows file, it's just an xml.

**Comment by leaf918** [comment]
I am create a orange3 plugin lib,when the property in the widget has been modified,the widget icon's name expected to be modified.

**Comment by janezd** [comment]
Huh, this is not something that you were meant to do.

Look at `orangecanvas.scheme.node.SchemeNode.set_title`, and I think you might also need `orangecanvas.scheme.widgetmanager.WidgetManager.node_for_widget`. But then, you'll need to somehow get to the instance of widget manager and so forth.

This is not documented (much) and anything you do today may not work tomorrow (though it probably will).
