### ISSUE TITLE
Where to find source code for orangedemo widget tutorial?

### ISSUE THREAD

**Issue by stefaneidelloth** [biolab/orange3#6459]
Where can I find the full source code for

https://orange-widget-base.readthedocs.io/en/latest/tutorial.html#prerequisites

I don't get the example working. 

What are the file names (I tried int_number.py, following snake_case naming convention)?

Where exactly should I put the partial code snippets inside the previously shown classes? 

I am able to install the code as a package. 

However, when starting 
`
orange-canvas`

after installing my orangedemo package with `pip install .`
I only see a splash-screen. No GUI and no error message. 

=> I guess that the documentation is outdated. Maybe the imports and or setup.py needs to be updated but I don't know how. 

Related question:

https://github.com/biolab/orange3-example-addon/issues/16

**Comment by LaimeJesus** [comment]
Hey @stefaneidelloth , I am also new to the Orange development library, however I was able to run those examples:

Does your final result looks similar to one of these?

Result 1, I run my widget outside of Orange Canvas:
![Screenshot from 2023-06-15 16-33-03](https://github.com/biolab/orange3/assets/13955827/fd65de9c-d4ba-4ab9-a370-c7e111bacf9d)

Result 2, In this case, I have added my experimental add-on into the Orange workflow:

![Screenshot from 2023-06-15 16-30-27](https://github.com/biolab/orange3/assets/13955827/b0ff52f8-5494-4229-99f0-cea13caae876)

If your result does not coincide with some of them, please, don't be shy to add the exact commands that you run in your case.

For instance, I have run these examples in a "custom" virtual environment created with [Pipenv](https://pipenv.pypa.io/en/latest/) 
Then, I installed in the "normal way": orange3, orange-canvas-core, pyqt6, pyqt6-webengine and numpy. Finally, to add my "custom" add-on I run the installment of the current directory with the "-e ." option.

Let me know if anything of this helps you.

**Comment by stefaneidelloth** [comment]
Thank you for your efforts. I decided to use other tools.
