### ISSUE TITLE
Moveable and resizeable input data/output data window

### ISSUE THREAD

**Issue by simonaubertbd** [biolab/orange3#6468]
**What's your use case?**
Hello all,

A little UI/UX issue : when I'm on the input data/output data window, the window is huge even with only a few columns and I can't move it, so I can't see in the same time what is in my configuration window behind.

![image](https://github.com/biolab/orange3/assets/46959192/a7f9ab2a-7ac7-4995-b1dc-f186ac45e1d0)

**What's your proposed solution?**
My solution would be to make this window moveable and resizeable

**Are there any alternative solutions?**
Not that I know

Best regards,

Simon

**Comment by janezd** [comment]
I'm sorry to close to of your posted issues at once. :)

This "window" is meant as a transient preview, not much more than a tooltip. You click it, it's there; you click again, it's gone.

To see a more permanent table, use the Table widget. If you want to see just the table, click on the separator between the left and the right pane.

**Comment by simonaubertbd** [comment]
@janezd No trouble, it's more suggestions than issues and usually, on different softwares, I have more a 1/4 to 1/10 success ratio and on Orange, you already accepted a lot of mine these last weeks so I'm more than satisfied right now ;).
However, from a pure UI/UX point of view, I find it disturbing to have the preview over the widget settings and unable to have it side by side (and yes, I can use the Table widget but that means another widget while there is the preview that I can open directly on my groupby widget). But once again, it's maybe because I'm used to Alteryx that have a really nice preview feature.

Best regards,

Simon
