### ISSUE TITLE
Preferences Window : Apply/Cancel/OK  buttons logic

### ISSUE THREAD

**Issue by simonaubertbd** [biolab/orange3#6469]
**What's your use case?**
Hello,

on the Preferences Window, there is one button "Close" which may be ambiguous. 

**What's your proposed solution?**

I would like to have 3 buttons :
-Cancel : closes the window and doesn't save
-Apply : saves and stays on the window
-OK : saves and closes the window
with appropriate tooltip (the comment I wrote) on each.

this is a "standard" way to deal with it :) 

**Are there any alternative solutions?**
Not exactly

Best regards,

Simon

**Comment by janezd** [comment]
I don't think it's "standard". Actually, I rarely see it. I checked on my machine and found just a few programs with two or three buttons (VLC, Illustrator, PyCharm); most have just one or none(!), just X at the top (Chrome, Firefox, MS Office, Slack, Telegram, iTerm, and everything that comes with macOS). I suspect that buttons are more of a Linux-y and open-source-y thing, while macOS and phones prefer instant saving. (I've no idea about MS Windows current style, but MS Office on macOS is button-less.)

Anyway, instant saving is much easier to implement and Orange has it now. In absence of a clear "standard" (and, in my opinion, the trend going against buttons) I think we'd keep at as it is.

This is MS Word on macOS:

<img width="770" alt="Screenshot 2023-06-08 at 19 44 54" src="https://github.com/biolab/orange3/assets/2387315/fe9ad9b8-fec4-4fee-88e0-6ae66bf28615">

**Comment by simonaubertbd** [comment]
Hello @janezd I'm not a mac user at all, I'm an old Windows guy (at least since the nineties) ;)

On windows, what I use :
ODBC
![image](https://github.com/biolab/orange3/assets/46959192/923c2eef-1be7-4abc-8d76-6cb11f2fbce0)

Tableau 
![image](https://github.com/biolab/orange3/assets/46959192/23b553cd-a562-4227-8b2f-6d433fb4c57b)

Qlik
![image](https://github.com/biolab/orange3/assets/46959192/1a45a586-5d79-4437-b7b0-cd04bbc65e05)

But it's even a recommandation for WIndows UX 
https://learn.microsoft.com/en-us/previous-versions/windows/desktop/bb246415%28v=vs.85%29
![image](https://github.com/biolab/orange3/assets/46959192/71160372-ddef-4ce9-a202-f703749416a1)

here on my W10 laptop for something most recent ;)
![image](https://github.com/biolab/orange3/assets/46959192/df47f68b-c170-4831-a0dd-e1c628b94b3b)

Just a question : how do you cancel your settings on your screenshot when you may have touched something but you don't know if you did ?

Best regards,

Simon

**Comment by janezd** [comment]
Interesting. Especially about Microsoft. If so, it's indeed a macOS thing. iPhone works the same.

> Just a question : how do you cancel your settings on your screenshot when you may have touched something but you don't know if you did ?

You can't. :)
