### ISSUE TITLE
Bringing back more control in FreeViz

### ISSUE THREAD

**Issue by processo** [biolab/orange3#6479]
I brought this up in #5501 earlier and still comes up from time to time in my work, so I'll post it here as a feature request.

Older FreeViz (orange v2.4 or 2.6, I think) gave a lot of control to the user over the attractive and repulsive forces of the optimization process. I often found that a temporary increase in repulsive forces can push it out of a local minimum when it's stuck, achieving much better results (in some cases to almost perfect separation of classes). Would it be possible to bring back the force settings and add an option to disable auto-stopping?

**Comment by processo** [comment]
Here is a visual representation of how different FreeViz results can be.
(It is a document classification task with 100 numeric attributes (binary term occurence of the 100 most frequent words) and one topic attribute as target. In both cases I let it run until stopped by itself.)

Orange 3.35.0:
![orange 3 35 freeviz](https://github.com/biolab/orange3/assets/5299789/a1c5d469-0508-4979-b29a-5c69232a32e5)

Orange 1.0-py2.4 (Gaussian law, kernel width 0.1):
![orange 2 4 freeviz](https://github.com/biolab/orange3/assets/5299789/2f4f8ca8-6878-4d1c-b993-87fd7657175b)

**Comment by janezd** [comment]
I checked that code. Wow. So: different types of "kernels" are not coming back. That code was a hodgepodge of dreamed up formulae, documented in comments like `LAW_GAUSSIAN is based on a kind of log-likelihood estimation`. (What's worse, it didn't have much to do with log-likelihood at all. It transformed distances through something that looks like logistic function, but only for repulsive forces, while attractive used inverse linear.) The old behaviour could only be reimplemented by copying this awful inconsistent code. Perhaps.

Setting the ratio between force strengths is also arbitrary, but bearably so. I also have a feeling that it should suffice; the effect of different "types" of forces was probably rather random.

I implemented this in #6515. Can you check how it works for you?

**Comment by processo** [comment]
I checked it on the same data and separation has improved greatly.

Here is the result with gravity 2:
![freeviz gravity](https://github.com/biolab/orange3/assets/5299789/3b043e8c-7cb3-411f-aa7f-832b1fc605b2)
