### ISSUE TITLE
Pivot Table widget - wrong filtered data output

### ISSUE THREAD

**Issue by meritwagner** [biolab/orange3#6485]
Hi there,

I am experiencing a problem with the Pivot Table Widget, specifically with the "filtered data" output. I want to use the functionality to select specific groups of my pivoted table to analyze separately. When I select one of the groups as intended, the routing towards the output of the widget does not work correctly. As seen on the picture I select the group with 8 instances but the widget outputs 23 instances, which is the group left to it. 

![image](https://github.com/biolab/orange3/assets/50302615/fa1c74cd-45f7-4297-b6d1-5df15a8904c5)

When I select all of the groups, the number of outputted instances is also wrong, it doesn't include the most right column of groups. (>=30). The total count of instances in the output should be 94 but is only 50 with 44 instances missing from the most right column.

![image](https://github.com/biolab/orange3/assets/50302615/e843a988-2b6f-4f16-8a45-bb251006562a)

It seems to me that the selection is simply taking all the instances belonging to the group  left to the one I select with my mouse.

I'm using Orange 3.35 as Standalone on Windows 11.

Thanks a lot and all the best,
Merit

**Comment by janezd** [comment]
Huh, it works for me. There must be something else going on here. Could you share the workflow and the data? If the data is confidential, perhaps at least the workflow, so that we can see whether something happens with that data before?

**Comment by meritwagner** [comment]
Hi Janezd,

thanks for the check and reply. I am not sure why, but it seems to work now after creating a new file. Can't reproduce it anymore.

Thanks anyway!
Best regards, Merit
