### ISSUE TITLE
Differential Expression output error 

### ISSUE THREAD

**Issue by IaelWM** [biolab/orange3#6494]
**What's wrong?**

I'm trying to analyse a gene set and find which are differentially expressed between two sample sets, using the differential expression widget from the bioinformatics add-on v 4.7.1. The analysis works fine however when I try to click the "commit" button  a window pops up with the message below and the data table widget with the output is black
 '''Error encountered in widget **Differential Expression**: 

Traceback (most recent call last):
File: "D:\OrangeStat\lib\site-packages\orangewidget\gui.py", line 2009, in do_commit
commit ( )
File " D:\OrangeStat\lib\site-
packages\orangecontrib\bioinformatics\widgets\OWDifferentialExperission.py" line 1334, in commit
gene_ids = self.data.attributes [GENE_ID_ATTRIBUTES]
KeyError: 'gene_id_attribute'
'''
 
<img width="960" alt="Captura de tela 2023-07-04 131424" src="https://github.com/biolab/orange3/assets/43472687/6f224869-f973-4412-92b0-5d696ce5eaee">

<img width="960" alt="image" src="https://github.com/biolab/orange3/assets/43472687/688a200f-0835-42bd-a60f-4b9c5a271a68">

<img width="960" alt="image" src="https://github.com/biolab/orange3/assets/43472687/672009f4-4379-4cc9-a225-9a6be35daa04">

<img width="960" alt="Captura de tela 2023-07-04 131424" src="https://github.com/biolab/orange3/assets/43472687/6f224869-f973-4412-92b0-5d696ce5eaee">

<img width="960" alt="image" src="https://github.com/biolab/orange3/assets/43472687/a03ed2dd-64ae-43f4-a731-3ba6b7d12b1a">

**What's your environment?**

- Operating system: Windows 11
- Orange version: 3.35
- How you installed Orange: From the website

**Comment by JakaKokosar** [comment]
I am closing this issue, since it has already been opened here: https://github.com/biolab/orange3-bioinformatics/issues/334
