### ISSUE TITLE
Explain model widget - Numpy int deprecated

### ISSUE THREAD

**Issue by malay-manglish-datasets** [biolab/orange3#6495]
**What's wrong?**

Explain Model widget produced error as per picture attached.

![orange-numpy-em-prob](https://github.com/biolab/orange3/assets/46283922/d8bbe46e-09f4-4a5d-b9fd-84b8d0ad1e6d)

**How can we reproduce the problem?** 

![orange-numpy-em-prob2](https://github.com/biolab/orange3/assets/46283922/17c893f1-3981-4f3f-919a-13dca63d627e)

**What's your environment?**

- Operating system: Windows 11
- Orange version: 3.35
- How you installed Orange: Installer

**Comment by markotoplak** [comment]
Duplicate of https://github.com/biolab/orange3-explain/issues/60
