### ISSUE TITLE
Number of variables not updated in Linear projection

### ISSUE THREAD

**Issue by processo** [biolab/orange3#6502]
![num of vars](https://github.com/biolab/orange3/assets/5299789/e9f50015-8699-4550-92d4-f10e582d9897)

The _Number of variables_ field is not updated but the last used value is applied when a new _Linear projection_ is created.

How to reproduce:
1. create a _Linear projection_
2. open _Suggest features_; set _Number of variables_ to 4; run, pause and close
3. create a new _Linear projection_
4. open _Suggest features_; _Number of variables_ is the default 3 (don't change it); run and it will still search for 4 variables

OS: Windows 10 x64
Orange: 3.35.0

**Comment by janezd** [comment]
I tried these steps and but couldn't replicate the bug. Someone needs to investigate, though. Perhaps together with #6503.
