### ISSUE TITLE
A real "formula"/"calculation" widget

### ISSUE THREAD

**Issue by simonaubertbd** [biolab/orange3#6509]
**What's your use case?**
Hello,

I would like to make some calculations on my data 
-mathematics like Unit Price * Quantity = Amount
-string like Upper('simon')=SIMON
-logical, etc, etc...

I may have misread the documentation but the closest solution I found was the feature constructor (which is, I think, an unclear name). However the feature constructir is really limited today :
-no autocompletion
-no string, date, logical, conditional... functions (Or I missed it)
-not able to use multiline
-etc.. etc...

**What's your proposed solution?**

A new "formula" or "calculation" widget similar to what we find in other solutions, with far mor type and calculations available
Alteryx : 
![image](https://github.com/biolab/orange3/assets/46959192/02973315-e0a8-456f-bc3a-2d2444057d67)

Knime 
![image](https://github.com/biolab/orange3/assets/46959192/cd8fc2bd-440d-49f6-8c2e-04addf7ad90b)

Well here a way to make some python calculation, either by overwriting existing field either by creating new fields.. this can be sliced in several delivery such as 1 : the widget where you can type free python calculation 2 : with intellisense/help/autocomplete

**Are there any alternative solutions?**

None I found

Best regards

**Comment by janezd** [comment]
You're right about the name of the widgets. We'll renamed it to Formula and add "construct" and "calculation" as keywords.

As for your suggestion, there is a Python Script widget that allows writing arbitrary (Python) programs, yet it is more difficult to use. This widget, though, only offers Python expressions; multiline would be of little help here. Expressions can include many mathematical functions, and we can others. Autocompletion would make little sense - you can use combos to select functions and variables anyway.

Small print: Python Script is difficult to maintain and we don't want to add another similarly complicated widget.
