### ISSUE TITLE
Orange doesn't open after removing distutils

### ISSUE THREAD

**Issue by noahnovsak** [biolab/orange3#6522]
After removing distutils and replacing it with pkg_resources in PR #6506, Orange crashes with the following message:

```
-------------------------- AttributeError Exception ---------------------------
Traceback (most recent call last):
  File "/Users/noah/dev/orange-canvas-core/orangecanvas/main.py", line 154, in <lambda>
    lambda cd: self.show_splash_message(cd.name)
  File "/Users/noah/dev/orange3/Orange/canvas/__main__.py", line 447, in show_splash_message
    super().show_splash_message(message, color)
  File "/Users/noah/dev/orange-canvas-core/orangecanvas/main.py", line 102, in show_splash_message
    splash = self.splash_screen()
  File "/Users/noah/dev/orange-canvas-core/orangecanvas/main.py", line 128, in splash_screen
    pm, rect = self.config.splash_screen()
  File "/Users/noah/dev/orange3/Orange/canvas/config.py", line 113, in splash_screen
    version_comp = version_parsed.version
AttributeError: 'Version' object has no attribute 'version'
-------------------------------------------------------------------------------
```

It seems that replacing `version_parsed.version` with `version_parsed._version` works, but I'm not sure if it's just me.

**Comment by janezd** [comment]
It happens to me, too. We mustn't use `version_parsed._version`, though, it's private. The correct property is `version_parsed.release`.

But there's something else going on. I have two `Versions`, one in `site-packages/pkg_resources/__init__.py` and the other in `site-packages/pkg_resources/_vendor/__init__.py`. The former is used for probing the versions of add-ons, and it has property `version` (but not `release`). The latter is used when probing the version of Orange and it has `release` (but no `version`). 

Replacing `version_parsed.version` by `version_parsed.release` would patch the problem, but we need to understand what's happening to avoid having this same problem with (some?) add-ons.

This looks urgent.

**Comment by noahnovsak** [comment]
Yes, avoiding `version_parsed._version` makes sense to me. The rest of what you said however, not so much.

In `site-packages/pkg_resources/__init__.py` I find `packaging.version.Version`, but under `.../_vendor/...` I don't see anything. Or at least I don't find a version of `Versions` with a `version` property :)

At any rate I tried making sense of the whole `pkg_resources` module, but all I can find is that it is deprecated and should be replaced with `packaging` or `importlib`.
