### ISSUE TITLE
X instead of Twitter 

### ISSUE THREAD

**Issue by dariasin** [biolab/orange3#6546]
**What's wrong?**

Is Orange working with the new platform? 

**How can we reproduce the problem?** 

**What's your environment?**

- Operating system:
- Orange version:
- How you installed Orange:

**Comment by PrimozGodec** [comment]
Thank you for the question. As you have probably noticed, there are also some changes in API. The Twitter widget still works with Twitter API, but users who want to download tweets require at least a Basic (paid) API plan (a free plan is not enough anymore). In https://github.com/biolab/orange3-text/pull/996, we added a warning to the documentation and widget itself.
