### ISSUE TITLE
ROC Analysis Report Chart Inaccuracies

### ISSUE THREAD

**Issue by cnewell2** [biolab/orange3#6548]
**What's wrong?**
The ROC Analysis widget's report is not displaying the ROC curve accurately. The data and chart look  fine when you open the widget, but what displays in the report shows different axes labels and the data does not overlay on these axes accurately. In screenshot, report is on the right. Notice the differences in the images.

![ROC screenshot](https://github.com/biolab/orange3/assets/143036121/e900f921-d949-463a-b163-9d9fbacf8bff)

**How can we reproduce the problem?** 
1. Generate an ROC graph.
2. Open the ROC Widget and examine the curve. Note the x- and y- axes and labels.
3. Click on the Report button. Note the chart image in the report is not accurate.

**What's your environment?**

- Operating system: Ventura 13.1
- Orange version: 3.35
- How you installed Orange: DMG downloaded from https://orangedatamining.com/download/#macos

**Comment by ales-erjavec** [comment]
This is probably same/similar to https://github.com/biolab/orange3/issues/6543 

Are you by any chance using a dual monitor setup? 
What monitor scaling are you using (System Preferences / Display)?

**Comment by cnewell2** [comment]
Thank you for the reference to a potentially similar problem. 

I am not using a dual monitor setup, just the single monitor on my laptop, set to 1690x1050. I've changed the display resolution and tried every version (1920x1200, 1440x900, 1280x800, 1024x640) and all of then result in the same report issue with the chart.

**Comment by markotoplak** [comment]
Probably solved in biolab/orange-widget-base#253. Please update orange-widget-base and retry. Or wait for new packages of 3.36.1, which should come shortly.
