### ISSUE TITLE
Nomogram and Predictions widget report different class probabilities for the same naive Bayesian model

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3#6553]
**What's wrong?**
Given the same feature-value pairs for the data instances and the same model, nomogram should predict the same class probability as the Predict widget. It does not, and the numbers are different.

The attached workflow exemplifies this problem. I have considered the Titanic data set, create an instance with sex=female and status=third. Nomogram predicts probability of survival of 66%, whereas Predictions shows 82%. 

![image](https://github.com/biolab/orange3/assets/726604/83b25941-5504-4a47-b232-50f240bb189f)

I get similar problem one other data sets (e.g., Attrition), where sometime the differences are even more pronounced.

If I use logistic regression, the predictions in the Nomogram and Predictions match (the comparison requires that all feature values are defined).

**How can we reproduce the problem?** 

See the attached workflow.

[nomogram-vs-predictions.ows.zip](https://github.com/biolab/orange3/files/12445283/nomogram-vs-predictions.ows.zip)

**What's your environment?**

OS X, Orange 3.35, dmg.

**Comment by thocevar** [comment]
Naive Bayes model had a bug in `_dense_probs`. There is still a problem with sparse cases (`_sparse_probs`), which I'm unable to resolve. The tests should include the newly added `test_predict_missing_attributes` also for sparse cases, which currently fails. @janezd

**Comment by thocevar** [comment]
We managed to debug the sparse case as well.

**Comment by janezd** [comment]
@thocevar, this can be closed now, right?
