### ISSUE TITLE
ModuleNotFoundError: No module named 'pandas.core.arrays.sparse.dtype'

### ISSUE THREAD

**Issue by frankclaessen** [biolab/orange3#6565]
**What's wrong?**

At starting orange-canvas after installation I receive the following error message:

```File "/home/frankc/.conda/envs/orange3/lib/python3.11/site-packages/Orange/data/pandas_compat.py", line 10, in <module> from pandas.core.arrays.sparse.dtype import SparseDtype ModuleNotFoundError: No module named 'pandas.core.arrays.sparse.dtype'``` 

If I open an environment with Ipython and import pandas.core.arrays.sparse  as SP and then dir(SP) it indeed does not show the asked module, so actually missing.

Is it perhaps the current pandas version?

**How can we reproduce the problem?** 

Use a clean anaconda install and follow your own instructions.
Check the pandas module asked above - it does not exist

**What's your environment?**
Manjaro freshly installed
I installed anaconda from the AUR repository and followed your installation instructions.

**Comment by frankclaessen** [comment]
In the most recent pandas package dtype is to be found under pandas.core.arrays.sparsearray 

I guess that's the cause

Regards Frank

**Comment by PrimozGodec** [comment]
Thank you for writing the issue. We already noticed and fixed the error in https://github.com/biolab/orange3/pull/6559. We will prepare the release very soon (planned at the beginning of this week).

Currently the best solution is to just downgrade pandas with : `pip install pandas=2.0.3`
