### ISSUE TITLE
Favorites widget

### ISSUE THREAD

**Issue by simonaubertbd** [biolab/orange3#6569]
**What's your use case?**
Most of the time, I use less than 10 widgets in several categorie.

**What's your proposed solution?**
A new widget category, "favorites". You can right click on any widget and add it to the favorites. The category only displays when there is at least one favorite.

Here is a screenshot on Alteryx feature :
Adding a tool to favorite : 
![image](https://github.com/biolab/orange3/assets/46959192/c53cd800-b8a7-4ca5-be69-98ace5e3b9e0)

Result :
![image](https://github.com/biolab/orange3/assets/46959192/a38240df-fe0e-448f-be03-9ab012536ce3)

**Are there any alternative solutions?**
Not I found.

**Comment by ajdapretnar** [comment]
@simonaubertbd This is a nice idea, but why would you need such a category? The preferred way of using Orange is right-clicking on the canvas and typing the name of the widget. I cannot remember the last time I've used the actual category pane. They are mostly intended for Orange beginners, who like to see what is on offer. Or perhaps I've misunderstood the suggestion.

![case](https://github.com/biolab/orange3/assets/12524972/ef0eb340-6867-412f-893a-479153c7f522)

**Comment by simonaubertbd** [comment]
Hello @ajdapretnar  I use on a daily basis less than 10 boxes so having it in a dedicated category would help : no search needed and the right click is really unintuitive.

Best regards,
