### ISSUE TITLE
Installing new Fairness add-on makes Orange 3.36 crash on startup (Mac / Silicon)

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3#6571]
**What's wrong?**
Installing the new Fairness add-on makes Orange 3.36 crash on startup (Mac / Silicon).
To repair the broken program file, Orange 3.35 must be downloaded again from the website and then upgraded (without the Fairness add-on, obviously)

**How can we reproduce the problem?** 
With Orange upgraded to 3.36 and several other add-ons installed (all latest versions), add the Fairness add-on from the Add-ons menu and press the "Restart Orange" button (or whatever it's called). Orange will close and start to reload, but crashes somewhere in the process.

**What's your environment?**

- Operating system: Mac OS 13.5.2 on Silicon
- Orange version: 3.36
- How you installed Orange: 3.35 from DMG, upgrade to 3.36 from Add-ons

**Comment by markotoplak** [comment]
We confirm this happens to us too on Arm Macs.

On Intel Macs everything seems to work properly.

**Comment by markotoplak** [comment]
This should be fixed in the new release of the add-on. Thank you for your report.

**Comment by wvdvegte** [comment]
Thanks! @markotoplak, what version number should I be looking for? Since I cannot install the buggy version, I cannont see if there is an update available either ...
<img width="254" alt="image" src="https://github.com/biolab/orange3/assets/55989717/83cdb287-c4cf-458f-949a-3ecbfa845b79">

**Comment by markotoplak** [comment]
0.1.6 was released a day ago and should (theoretically) work.

**Comment by wvdvegte** [comment]
Right! I can confirm: no crash after installing it om my M1 Mac

**Comment by markotoplak** [comment]
Thanks for reporting it (and taking the risk :) ).
