### ISSUE TITLE
Distributions outputs wrong data

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#6576]
**What's wrong**

The widget's output does not match the selection.

**How can we reproduce the problem?** 

Load Zoo and pass it to Distributions. Show "type" and check "Sort categories by frequency".

When selecting the n-th column, the widget outputs data referring to the n-th value of the variable in the original, unsorted order.

It is pretty amazing that nobody noticed this so far.

**When fixing this** consider that the user can click "Sort categories by frequency" while something is selected. This shouldn't affect which values are selected (e.g. if one selects mammals and insects, they must still be selected).

**Don't forget** selection using keyboard, including, e.g. Shift-Right.

**What's your environment?**
- Operating system: macOS
- Orange version: latest master
- How you installed Orange: pip

**Comment by janezd** [comment]
@VesnaT would say that the original author of the current implementation of this widget hasn't written proper tests. The said author would hate that she'd be right.

**Comment by janezd** [comment]
@markotoplak, I assigned a milestone 3.36 to this. I hope the release can wait for a few more days. It's a part of an example in the book for teachers, and it's pretty embarrassing.

I can look at this tomorrow or on Sunday; it's probably not that difficult, but needs to be carefully fixed in several places.

**Comment by markotoplak** [comment]
Khm, I believe 3.36.0 was released one week ago, but we still did not publish final installers. @PrimozGodec, this looks like we'll go 3.36.1.

**Comment by PrimozGodec** [comment]
Hehe. I just wanted to start signing installers. Will wait until this is merged, and the we can make 3.36.1
