### ISSUE TITLE
Hierarchical Clustering with text: output cannot directly connect to corpus input

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3#6583]
**Describe the bug**
In previous versions of the Text-Mining add-on, it was possible to directly connect one of the two outputs of Hierarchical Clustering to a widget requiring a corpus on its input. Instead of a green corpus connection, it is now red and nothing is passed on.

**To Reproduce**
Perform Hierarchical Clustering after Bag of Words, connect it to a widget requiring a corpus on its input, for instance Word Cloud.

**Expected behavior**
Corpus is passed on to the next widget.

**Orange version:**
3.36

**Text add-on version:**
1.14.0

**Operating system:**
OSX 13.5.2 on Silicon

**Comment by ales-erjavec** [comment]
@janezd The quickest fix would be
```diff
diff --git a/orangecanvas/scheme/signalmanager.py b/orangecanvas/scheme/signalmanager.py
index c5e574d79..3e3020dca 100644
--- a/orangecanvas/scheme/signalmanager.py
+++ b/orangecanvas/scheme/signalmanager.py
@@ -1279,6 +1279,8 @@ def can_enable_dynamic(link, value):
     """
     Can the a dynamic `link` (:class:`SchemeLink`) be enabled for`value`.
     """
+    if LazyValue.is_lazy(value):
+        value = value.get_value()
     return isinstance(value, link.sink_types())
 

```
