### ISSUE TITLE
Save Distance Matrix did not work

### ISSUE THREAD

**Issue by ClaudioRetico** [biolab/orange3#6599]
In attached flow i generate various distance matrix and then i want save them. Yet the SAVE DISTANCE MATRIX did not work. I tried to decrease record sampled from about 10.000 to only 150 (as in Iris sample) but widget did not work.
If i try a simple flow with only IRIS data source, distance and save distance widget it works.

![flow](https://github.com/biolab/orange3/assets/28264701/81dc88c1-7014-4e20-b225-729284e111f8)
 
-->

**What's wrong?**
I input file name but nothing happen. The file is not generated and no message or error is displayed

**How can we reproduce the problem?** 
I upload low and anonymized data file:
[Riclusterizzo_Con_Orange_CreaDistanceMAtrix.zip](https://github.com/biolab/orange3/files/12930706/Riclusterizzo_Con_Orange_CreaDistanceMAtrix.zip)
[AbapCluster_DaTaamAI_20231014.xlsx](https://github.com/biolab/orange3/files/12931297/AbapCluster_DaTaamAI_20231014.xlsx)

**What's your environment?**

- Operating system: Windows 11
- Orange version: Orange 3.36.1 
- How you installed Orange: Portable

**Comment by ajdapretnar** [comment]
@ClaudioRetico Thank you for taking the time for such a detailed description. I have trouble replicating your workflow, because for some reason, Formula (Creo stringa concatenata) doesn't remember the setting (might be a separate bug in itself?). Would you mind writing the formula here so that I can inspect the issue further? Thank you.

**Comment by janezd** [comment]
@ajdapretnar, it's one of these. I'd take the first one.

```
nome_autore + " "  +luogo_di_nascita+ " " + data_di_nascita + " "+ luogo_di_morte + " "+data_di_morte+ " " +qualifica

"Autore: " + nome_autore + "," + cognome +" Nato a:" +luogo_di_nascita+ "in data " + data_di_nascita + " e morto a: "+ luogo_di_morte + "in data: "+data_di_morte+ "

"Autore: " + nome_autore + "," + cognome +" Nato a:" +luogo_di_nascita+ "in data " + data_di_nascita + " e morto a: "+ luogo_di_morte + "in data: "+data_di_morte+ " \xc3\xa8 stato un " +qualifica+" appartenente alla scuola" + scuola_di_appartenenza
```

**Comment by ClaudioRetico** [comment]
I confirm what @janezd  says.
I add that the column name in XLS need to be renamed as follow (i realize only now that i scrambled also them and this may be a problem in the flow):

Column1;id_file;tipo_file;nome_autore;cognome;luogo_di_nascita;luogo_di_morte;auth;codice_autore;cluster_autori_simili_kmeans;cluster_autori_simili_hdbscan;anagrafica;data_di_nascita;data_di_morte;qualifica;scuola_di_appartenenza

**Comment by ajdapretnar** [comment]
One final thing. Did you by any chance set three class variables? Would you mind sending a screenshot of Select Columns?

**Comment by ClaudioRetico** [comment]
I attach screenshot. no i did not set.
![Clipboard01](https://github.com/biolab/orange3/assets/28264701/e0c894da-0521-4385-a9b8-a85b5c2d110f)

**Comment by ajdapretnar** [comment]
I have checked this once again. First, the Excel file seems to be corrupt (the encoding is off and I can't get it to work). Nevertheless, I tried to replicate the workflow with what I had and every time I was able to save the matrix. So I'm out of ideas.
@janezd?

**Comment by ajdapretnar** [comment]
Close due to inactivity.

**Comment by janezd** [comment]
@ajdapretnar, thanks for cleaning up the old issues.

I just thought of something that could be happening here. Or maybe not, but it is a simple fix that might prevent this or some other problem: if the distance matrix contains a nan, Excel writer will report an error. I don't know whether there can even be a nan here, but adding a simple `if` before the last line of `Orange.misc._distmatrix_xlsx.write_matrix` can't hurt.
