### ISSUE TITLE
Hierarchical Clustering: distances between clusters as output (NxN distance matrix for N clusters)

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3#6617]
**What's your use case?**
I want to externally validate clustering outcomes based on distances between clusters: do subjects perceive items in the same cluster as a specific data item as more closely related to that item than items it the most-distant other cluster, or items in the nearest other cluster?
From hierarchical clustering, it is normally possible to apply Group By -> Cluster to the output to average the features, then apply Distances followed by Distance Matrix to [get the distances between clusters](https://discord.com/channels/633376992607076354/1166300000179982367/1166329312484540436). But hierarchical clustering is also often (incuding my use case) applied in text mining based on Bag-of-Words output, and Group By won't work with the sparse data prodouced by BoW.

**What's your proposed solution?**
Add an extra output to Hierarchical clustering that provides the mutual distances between all the clusters based on averaging the mutual distances between the items in each pair of clusters.

**Are there any alternative solutions?**
A workaround could be to use the distances on which HC is based also as input for MDS, merge the outputs from MDS and HC to get x and y values as well as a cluster number for each item in one table, get rid of the sparse data, then group by cluster to calculate the average x's and y's  per cluster and finally  Distances to get pairwise distances between the clusters.
However, I doubt this assessment is a mathematically correct approach.

**Comment by BlazZupan** [comment]
The task that you are describing can already be handled with a combination of existing widgets, as you can measure the distances between the clusters even if these come from text data. Consider the following workflow:

![image](https://github.com/biolab/orange3/assets/726604/0c01e726-7a37-4016-b62f-9f760569d642)

I have used the "words" data set and embedded it to get the vector representation of words, invoked hierarchical clustering, and then, as you suggested, used Group By to get a cluster's "average" representation. From there on, I can compute the distances and, as in the workflow above, can display these in the Distance Matrix or (not shown) work with them in the following pipeline.

I agree that outputting the distances by the Hierarchical Clustering widget would shorten the workflow. Still, we tend not to overload the outputs of the widgets with various signal types for non-typical uses, especially if the same task can be achieved with some combinations of the widgets already there.

Thank you for you suggestion, though.

**Comment by wvdvegte** [comment]
@BlazZupan, Knowing that it doesn't produce sparse data, I already tried Document Embedding (and SimHash, for that matter) on my corpus, but it provided less useful clustering results than BoW. The only thing I found that possibly allows me to group by cluster is by using Network from Distances:
![image](https://github.com/biolab/orange3/assets/55989717/1671dbc4-de00-4d6d-a25c-30f5533cb740)


Do you think this is also a mathematically correct way to get distances between clusters?

**Comment by wvdvegte** [comment]
@BlazZupan , I found another approach that gives me, in a sense, distances between the clusters:
<img width="1685" alt="image" src="https://github.com/biolab/orange3/assets/55989717/b4ca65de-cc4c-45aa-a5d6-b09d336f3e2b">
After hierarchical clustering, I remove the sparse data but leave the Cluster column, then merge with the data from before Bag of Words, then group by cluster, concatenating the texts from the one feature that holds my whole corpus, make the concatenated text of all items in each cluster the new corpus, once again preprocess, apply BoW and Distances.
This gives me a distance matrix that is completely different from the one resulting from my previous post. However, I have a feeling that the coordinates from network cannot be used to calculate distances, as the documentation suggests that the fact that nodes are connected by a line expresses that they are close to each other - not the distance between the nodes. Do you agree that this approach seems to make more sense?
