### ISSUE TITLE
Global configuration with supports_multiclass=False in Learner from base.py

### ISSUE THREAD

**Issue by linjing-lab** [biolab/orange3#6635]
**What's your use case?**

As a developer concentrate on building Python packages related to machine learning, I thought [class Learner from base.py](https://github.com/biolab/orange3/blob/2e79655dc01f380d2c2d64d269f85b4737ef803a/Orange/base.py#L43) could contribute to any folder related to subclasses that inherit the Learner parent class, like [classification](https://github.com/biolab/orange3/tree/master/Orange/classification), [ensembles](https://github.com/biolab/orange3/tree/master/Orange/ensembles), [regression](https://github.com/biolab/orange3/tree/master/Orange/regression). But the global configuration in Learner, or described in another way, the default False value inputed to the [supports_multiclass](https://github.com/biolab/orange3/blob/2e79655dc01f380d2c2d64d269f85b4737ef803a/Orange/base.py#L85C5-L85C25) did block the type of tasks with multiclass prefix. I think this is some of the issues brought about by the built-in algorithm of scikit-learn, as it is based on numpy, and numpy.ndarray may not support multiclass target input due to backward mode designed in scikit-learn. Because a simple [KNNLearner](https://github.com/biolab/orange3/blob/2e79655dc01f380d2c2d64d269f85b4737ef803a/Orange/classification/knn.py#L8C39-L8C39) wrapped from scikit-learn that has 2 False configuration, both supports_multiclass and supports_weights, I was concerned about the compatible use by given constraint named [incompatibility_reason](https://github.com/biolab/orange3/blob/2e79655dc01f380d2c2d64d269f85b4737ef803a/Orange/classification/base_classification.py#L9) in LearnerClassification, which was inherited by SklLearnerClassification (renamed as SklLearner).

**What's your proposed solution?**

I thought orange3 could adopt torch.Tensor from PyTorch as the foundation format instead of taking numpy.ndarray based functions highly wrapped in scikit-learn, while improving the parallel efficiency of the machine learning algorithms, it can support multiclass type target inputs.

**Are there any alternative solutions?**
For minimizing task types and maximizing runtime efficiency, I recommend [perming](https://github.com/linjing-lab/easy-pytorch/tree/main/released_box) project which I developed for a more compatible use with [type_of_target](https://github.com/scikit-learn/scikit-learn/blob/14995509a996ff5575c032fb7aead25bf6bb595c/sklearn/utils/multiclass.py#L222) defined in scikit-learn. Please forgive my suggestion, there are still many neural networks that can be used as the core method for bioinformatics, like [pytorch_geometric](https://github.com/pyg-team/pytorch_geometric) developed by pyg-team.

**Comment by BlazZupan** [comment]
Thank you for your suggestion. Changing the base format at this stage and moving away from wrappers around the scikit-learn would be a massive undertaking, especially as there would be no gain from a user perspective, as all classification widgets in Orange already support multi-class classification. 

However, your suggestion is helpful for our way forward, as we are already thinking about server-based Orange, where our pilot with the Dask framework, supported by CZI, has also helped us to gain experience in this area. Thank you very much for your comments and suggestions.

**Comment by markotoplak** [comment]
@linjing-lab, these default constraints are there to specify what the learner can do, and defaults are such that work well for most learners. Of course you can implement a learner that uses non-default values if the learner, of course, supports these capabilities.

Recently, for example, I implemented PLS that supports multiple targets (Quasars/orange-spectroscopy/pull/694).

**Comment by linjing-lab** [comment]
@markotoplak I sporadically use learner based on scikit-learn, so supports_multiclass=False makes no impact in my machine learning scenario.
