### ISSUE TITLE
Formula : ability to write a formula to change an existing variable

### ISSUE THREAD

**Issue by simonaubertbd** [biolab/orange3#6639]
**What's your use case?**
I have some formula to change existing fields, it's mainly cleansing it so I don't want to create a new variable.

**What's your proposed solution?**
On the formula widget, the ability to create a new OR to edit an existing variable.

**Are there any alternative solutions?**
creating a new one, changing its name and deleting the first one. Two more steps.

**Comment by janezd** [comment]
Note from discussion: we'd allow giving the new variable the same name as an existing one and in this case replace it. The widget would show an information (bottom-right) about this.

**Comment by simonaubertbd** [comment]
Hello @janezd  That would be perfect. 
Best regards,
Simon

**Comment by janezd** [comment]
I just merged it. Feature was added by @ales-erjavec.
