### ISSUE TITLE
Text annotation : something richer with url, color, text size, etc...

### ISSUE THREAD

**Issue by simonaubertbd** [biolab/orange3#6641]
**What's your use case?**
I would like to emphasize some part of my annotations, and put a link to some documentations, adding some pictures/logos... well making my annotations way richer than basic text.

**What's your proposed solution?**
An RTF or HTML editor would be pretty cool.

**Are there any alternative solutions?**
Not I see.

**Comment by wvdvegte** [comment]
Already there - richt-click on the edge of the box surrounding the annotation and you'll get this:
<img width="365" alt="image" src="https://github.com/biolab/orange3/assets/55989717/9cf04f69-d18a-40de-9445-c28d47dd5783">

**Comment by simonaubertbd** [comment]
@wvdvegte Ok, thanks... shame on me, I didn't even try a right click.  😨 
However I have two comments  :
1/i played with html and most of times, it didn't take into account my Render Option and I have to re-select plain text and re-click on html
2/to my defense, for the other widgets, the configuration is not by right-click so it doesn't look natural, intuitive.

Best regards,

Simon
