### ISSUE TITLE
OCR (optical character recognition) in images

### ISSUE THREAD

**Issue by simonaubertbd** [biolab/orange3#6642]
**What's your use case?**
I would like to extract text in image/pdf document.

**What's your proposed solution?**
An OCR module in the image add-on to extract text. Some modules exists in python for that. Some documentation here (well; sadly in french https://www.aranacorp.com/fr/reconnaissance-de-texte-avec-python/)  and what I understand is that you could use pytesseract.

**Are there any alternative solutions?**
No

**Comment by janezd** [comment]
Would this be really useful? How does one get a large collection of QR codes that he would like to text-mine?

We discussed this at the meeting on Friday. On the first glance, it could belong to the image analytics add-on, but it is rather about texts, so it could be in text add-on. However, our resources are limited, and the QR widget had no advocates in the group. If you wish to have it and you consider it worth of your effort, go for it. At first, your code would be accepted to the prototype add-on; if it's useful, it can the move to its more appropriate permanent place.
