### ISSUE TITLE
Bulk .ows reader for monitoring our assets

### ISSUE THREAD

**Issue by simonaubertbd** [biolab/orange3#6643]
**What's your use case?**
I would like to analyse my orange workflows (.ows), and for that, what would be better than using Orange Data Mining ?

**What's your proposed solution?**
A tool where you can send folders or adresses (like \\srv_simon\odm\workflows\prod*2023*.ows and \\srv_simon\odm\workflows\), choose if you want to scan subfolders. 2 output : 
-workflow level (1 row by workflow),worfklname and adress of the workflow, some files metadata (creation, etc)
-node level : worfklname and adress of the workflow, the used tools, etc, the annotations.

**Are there any alternative solutions?**
Using something else than Orange but that means no cool inception.

**Comment by janezd** [comment]
The idea is interesting, but probably not very useful. At any rate, it doesn't have to be a part of Orange. OWS files are ordinary xmls, and the features that you suggest do not require even that Orange is installed. So if you think this could benefit others as well, you can provide such a tool to the community.
