### ISSUE TITLE
predictions displaying error that the target is not in domain

### ISSUE THREAD

**Issue by marcosherif** [biolab/orange3#6644]
**What's wrong?**

 the predictions is displaying that error 
 Some predictor(s) failed (see more ...)
- Random Forest: Random Forest: 'fetal_health' is not in domain
![image](https://github.com/biolab/orange3/assets/68437948/76dfbebc-ee2c-40ea-9a2b-b8608125d71a)
![image](https://github.com/biolab/orange3/assets/68437948/dae690a8-75f4-499c-aa50-8b45056670de)
![image](https://github.com/biolab/orange3/assets/68437948/0f82b5f4-8f96-4f68-81b5-1fc772bd9a46)

**How can we reproduce the problem?** 

[fetal_health_data.csv](https://github.com/biolab/orange3/files/13403821/fetal_health_data.csv)

**What's your environment?**

- Operating system: windows 11
- Orange version: 3.31.1
- How you installed Orange: downloaded from the website

**Comment by janezd** [comment]
Curious. I tried reproducing it, but it works for me. Could you also attach an .ows file?

**Comment by marcosherif** [comment]
yes of course here it is cause i can't upload it on github

**Comment by janezd** [comment]
Github allows zip file. Here's your file: [Model Training.ows.zip](https://github.com/biolab/orange3/files/13404494/Model.Training.ows.zip). (But right now I have another work, this will have to wait.)

**Comment by VesnaT** [comment]
The problem appears due to Imputer (Model based)
![image](https://github.com/biolab/orange3/assets/11465003/ce35d0eb-eae3-40e4-905d-c1eb3a8c1713)

**Comment by marcosherif** [comment]
Thanks a lot!! I changed the method of imputation and it's working now

**Comment by janezd** [comment]
I'm glad to see that it solved your problem. Still, Orange should behave better; I'm reopening the issue.

**Comment by janezd** [comment]
Note: Model-based imputer shouldn't use the class variable.

**Comment by markotoplak** [comment]
Hm, @VesnaT, as @janezd says I only get this problem when I impute the class. And this widget does indeed also impute the class with a default method.
