### ISSUE TITLE
CN2 Rule Induction: name of widget does not show up in Predictions if unedited

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3#6649]
**What's wrong?**
If the output of CN2 Rule Induction is connected to Predictions, the widget name does not appear as header of the column with predictions or in the performance scores. If the name of the widget is changed manually, the name does appear.

<img width="790" alt="image" src="https://github.com/biolab/orange3/assets/55989717/b2237711-5bf7-49d8-bd10-eeb27022fa69">

**How can we reproduce the problem?** 

[CN2 bug.ows.zip](https://github.com/biolab/orange3/files/13439327/CN2.bug.ows.zip)

**What's your environment?**

- Operating system: Mac OS Sonoma (also observed on Windows)
- Orange version: 3.36.2
- How you installed Orange: from DMG

**Comment by janezd** [comment]
Thanks. It was even worse than you reported: I connected Tree, Neural Networks and CN2 to Predictions and Orange failed with `max of empty sequence` error.
