### ISSUE TITLE
Dark mode on Mac: widget names in white text on white background, therefore invisible

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3#6653]
**What's wrong?**
When using Dark mode on a Mac, the text displaying names of widgets changes to withe, while  background color of the canvas remains white. This makes the text unreadable (unless the user draws a selection box around the widgets):
![image](https://github.com/biolab/orange3/assets/55989717/a624f154-27f9-442e-a2f3-03060daafc8b)

Also the text describing the dataflows changes to white, but changes to black after having drawn a selection box around the dataflows. This bug is related to #5410.

Suggestion: invert everything when dark mode is active.

**How can we reproduce the problem?** 
N/A

**What's your environment?**

- Operating system: Mac OS 14.1
- Orange version: 3.36.2
- How you installed Orange: from DMG

**Comment by ales-erjavec** [comment]
This happens when switching dark/light mode on mac while Orange is opened right? It does not happen when starting it while in dark mode?

**Comment by wvdvegte** [comment]
Right. My Mac is set to automatically go to Night Shift and Dark Mode at sunset. This is when it happened, yesterday. If I select Dark mode, then open Orange, I'm getting white text on a black background, as expected. And if I select Light Mode with Orange open in Dark Mode, I'm getting black text on a black background which again cannot be read.

**Comment by HoutanSadeghi** [comment]
Orange on my Mac is on a black background and on my wife’s pc appeared on a white background. I do not mind either. However on certain occasions it becomes difficult to read numbers on a black background eg Box plot. So I go to system setting - Appearance and choose a light background then it looks like the one on windows.
