### ISSUE TITLE
Stacking Widget: "Stack failed with an error" when using Time Slice as Data source

### ISSUE THREAD

**Issue by ereztison** [biolab/orange3#6665]
**What's wrong?**
When using the Stacking widget with Time Slice as Data source and Test and Score widget on the other side, a "Stack failed with an error" message appears (on the Test and Score widget).
There is no error if Data Sampler (or no widget) is used to slice the data instead the Time Slice widget.

The log shows repeated errors like this one, not sure if this is THE one:
```
TransformDomain should define __eq__ and __hash__ to be used for compute_shared
ComputeValueProjector should define __eq__ and __hash__ to be used for compute_value
or set InheritEq = True if inherited methods suffice
```

Attached is a screenshot of the problem reproduces with "ParlaMint" dataset, in order to have a time field to Time Slice with I used the From and To variables as meta:
<img width="2560" alt="image" src="https://github.com/biolab/orange3/assets/6105200/84358393-2828-4649-a32b-260a60debc84">

**How can we reproduce the problem?** 
Attached is a zip of the .ows file also appears in the screenshot (where all relevant widget windows are open):
[Stacking with Time Slice problem report.ows.zip](https://github.com/biolab/orange3/files/13557015/Stacking.with.Time.Slice.problem.report.ows.zip)

**What's your environment?**
OS: macOS 12.7
Orange version: 3.36.2
Orange installed using the .dmg in the download page

**Comment by ajdapretnar** [comment]
I'm trying to reproduce this, but cannot get to the Stacking error. However, the error that does appear in Test and Score says "Target variable has only one value." This is because in ParlaMint, the target variable is tied to the time period, so if you are using Time Slice, inevitably, you'll get only a single variable.

**Comment by ereztison** [comment]
Thank you for replying, I was using the ParlaMint dataset just as an example to a dataset all of us have access to, the problem occurred also in other time series. I was wondering if the attached .ows throws the Stacking error on you machine.

**Comment by processo** [comment]
@ereztison Just wondering what the warning message is when you hover over the yellow triangle with mouse.

**Comment by processo** [comment]
@ereztison Thanks. Pity that `assert` had no message.
