### ISSUE TITLE
Feature Statistics Widget : count, count distinct, same for categorical, etc...

### ISSUE THREAD

**Issue by simonaubertbd** [biolab/orange3#6667]
**What's your use case?**
Hello. I would like to analyze quickly a dataset before working on it. The Feature Statistics would do the job but sadly, I miss some informations.
![image](https://github.com/biolab/orange3/assets/46959192/80aa4402-f06e-432d-b195-f206a07640af)

**What's your proposed solution?**
-new calculations such as : count, count distinct,standard deviation, shortest and longest values
-apply to all fields when possible (so also categorical)

**Are there any alternative solutions?**
None I know

Best regards,

Simon

**Comment by ajdapretnar** [comment]
Let's see some of the proposed options.
- count: this is already available via missing (inverse)
- count distinct: unsure how is this relevant for numeric variables. For categorical it might be nice to have it somewhere. Currently, on hover in Box Plot, there's a message "categorical variable with 4 values". Could be expose this more?
- Standard deviation: this is dispersion in Feature statistics.
- shortest/longest value: this is more appropriate for Text mining.

**Comment by simonaubertbd** [comment]
Hello @ajdapretnar 
First of all, thanks for your answer and your time :

-count : yes, I can do the inverse but that's unnecessary operation ;)

-count distinct : even for numeric variable, it can be interesting (like : how many amount do I have ?). Is it more work to have it on both numeric and caterigocal variables?

-Standard deviation: this is dispersion in Feature statistics.===> oops, my bad. However, the good term is, I thing, standard deviation (e.g. : https://en.wikipedia.org/wiki/Standard_deviation ). Maybe a change in the name ?

-shortest/longest value: well, maybe it's me but I love to have only one widget for all my stats/summary ;)

Best regards,

Simon

**Comment by simonaubertbd** [comment]
Hello @ajdapretnar  Ok, I understand your point of view. That said, even the count distinct would be cool.

Best regards,

Simon
