### ISSUE TITLE
Installed Geo and Timeseries add-ons, now Orange crashes on start-up

### ISSUE THREAD

**Issue by kaimikael** [biolab/orange3#6671]
**What's wrong?**

I just installed Orange 3.36.1, which seemed to work fine.  However, then I added the Geo and Timeseries add-ons and after that Orange crashes on start-up.  I tried reinstalling Orange and then install the add-ons separately, but individually they don’t seem to cause problems, however with both installed Orange crashes.  I attach the crash log below.  

BTW, is there any way of uninstalling the add-ons from outside Orange?  I looked in the obvious directories but saw nothing I could just throw away.

**How can we reproduce the problem?** 

Install Orange.
Start Orange.
Select Options → Add-ons, check Geo and Timeseries.  Install.
On restart, Orange crashes.

**What's your environment?**

- Operating system: macOS 14.1.1
- Orange version: 3.36.1
- How you installed Orange: Downloaded https://download.biolab.si/download/files/Orange3-3.36.1-Python3.9.12.dmg, dragged the app to Applications.

[orange.log](https://github.com/biolab/orange3/files/13627322/orange.log)

**Comment by wvdvegte** [comment]
Could it be related to this [bug report](https://github.com/biolab/orange3-timeseries/issues/261)?
Would it help if you update to Orange 3.36.2 first (through the Add-ons menu)?

**Comment by kaimikael** [comment]
Yes, that resolved the problem, but how come there is an upgrade to 3.36.2 in the Add-Ons menu (I didn’t even realise that was what it was until you asked for it), while there is no such installer at https://orangedatamining.com/download/?

**Comment by markotoplak** [comment]
@PrimozGodec, I do not understand why does upgrading to 3.36.2 fixes @kaimikael's problem. Do you perhaps know why?

**Comment by markotoplak** [comment]
We believe this may be because Orange 3.36.1 required scikit-learn < 1.2, and if any add-ons (or its dependecies) upgraded it, that could be problematic. Orange 3.36.2 in contrast, works well with scikit-learn 1.3 and would not exhibit such problems.

Regarding non-availabilty of packages: the certificates we use to sign packages expired and we are in process of getting new ones.
