### ISSUE TITLE
Orange not connecting to internet to update add-ons

### ISSUE THREAD

**Issue by flogistof** [biolab/orange3#6701]
**What's wrong?**

Orange 3,36,2 shows an error message when I try to add or update the add-ons.
Error occurs on Windows 10 installations on different computers and networks.
Details of the error message:
"
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Orange\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\User\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\application\addons.py", line 510, in <lambda>
    lambda config=config: (config, list_available_versions(config)),
  File "C:\Users\User\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\application\utils\addons.py", line 338, in list_available_versions
    session = _session()
  File "C:\Users\User\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\application\utils\addons.py", line 299, in _session
    session = requests_cache.CachedSession(
AttributeError: module 'requests_cache' has no attribute 'CachedSession'

"

**What's your environment?**

- Operating system: Win10 Pro
- Orange version: 3,36,2
- How you installed Orange: Windows installer

**Comment by markotoplak** [comment]
I see you mentioned the Windows installer. How did you install 3.36.2? Installed 3.36.1 first and then upgraded within the add-on dialog? Or did you find (currently hidden) 3.36.2 Windows package on the web page?

**Comment by flogistof** [comment]
I installed 3.36.1 and upgraded subsequently to 3.36.2 with add-on dialog.


Em ter., 9 de jan. de 2024 19:58, Marko Toplak ***@***.***>
escreveu:

**Comment by PrimozGodec** [comment]
This is a strange error. I tried the same procedure you did: Installing 3.36.1 through the installer and updating it to 3.36.2, but it still works for me. It seems something is wrong with the library requests-cache that Orange uses.

Can you try the following:
- Open Orange Command Prompt from the Windows Start menu
- Run command `conda list` 
- Paste here the line which tells what the version of the library requests-cache

**Comment by PrimozGodec** [comment]
I'm closing this since we cannot reproduce it and due to inactivity. @flogistof (or anyone else), if you still have an issue, please reopen with additional information.
