### ISSUE TITLE
Is there any way to import the trained model as a load model widget and fine-tuning?

### ISSUE THREAD

**Issue by cislove98** [biolab/orange3#6707]

**Comment by markotoplak** [comment]
I do not think there are any widgets that currently support that.

We did similar things in the past though. For example, I wrote a domain-specific prototype widget that does exactly that some time ago, so there are no technological barriers...

But to make it work the type of the model to refit would need to be precisely defined.

**Comment by markotoplak** [comment]
Currently there are no widgets like this, but in the future, we might add some.

We are open to contributions from this space. If anyone is thinking about such developments, such project would be best started as an add-on.
