### ISSUE TITLE
Orange keep crashing in M1 Macbook

### ISSUE THREAD

**Issue by sophiiae** [biolab/orange3#6709]
**What's wrong?**

I'm using an M1 Macbook Air (macOS 13.2). Orange (newest version 3.36.2) keeps crashing when I try to open a .csv dataset file, open datasets,  click the file button, or click a few buttons. Don't see any error message. 

https://github.com/biolab/orange3/assets/18622886/449ccb80-c15a-4b7f-96eb-f0344e08f2d8

https://github.com/biolab/orange3/assets/18622886/b69169bd-aa46-4cf4-824b-b2c553691dd6

https://github.com/biolab/orange3/assets/18622886/ba66df20-a8c8-41dd-912b-4cd2708ba99c

**How can we reproduce the problem?** 

**What's your environment?**

- Operating system: macOS 13.2
- Orange version: 3.26.2
- How you installed Orange: 
   Download Orange from https://orangedatamining.com/download/#mac 
   Orange for Apple silicon [Orange3-3.36.2-Python3.9.12-arm64.dmg](https://download.biolab.si/download/files/Orange3-3.36.2-Python3.9.12-arm64.dmg)

**Comment by markotoplak** [comment]
Thanks. @BlazZupan also reported this, so now it is confirmed.

You can download the previous version, which should not have that problem, here: https://download.biolab.si/download/files/Orange3-3.36.1-Python3.9.12-arm64.dmg

Please report if the older version works.

**Comment by markotoplak** [comment]
We just published new 3.36.2 packages that should fix these problem at https://orangedatamining.com/download/ 

Therefore, I am closing this issue. Please reopen if the issue persists.
