### ISSUE TITLE
AttributeError: module 'Orange.widgets.gui' has no attribute 'WebviewWidge

### ISSUE THREAD

**Issue by JoaoGabrielTN** [biolab/orange3#6713]
orange 3.3
orange-text 1.15.0
OS linux mint victoria
run it with the "python3 -m Orange.canvas" command

Expected behavior
It's suposed to create a worcloud from a corpus file.

Actual behavior
when run it appears an error message: 'Orange.widgets.gui' has no attribute 'WebviewWidget'.

Steps to reproduce the behavior
Create corpus 
link corpus to preprrocessing text
link preprocessing to wordcloud
try to open wordcloud

**Comment by JoaoGabrielTN** [comment]
I solved it by installing webview through "pip3 install pywebview[qt]". The wordcloud widget opens, but does not show the wordcloud. 
![Wordcloud error](https://github.com/biolab/orange3/assets/101192385/6f807061-3c4e-43af-adf6-ea9fd5f037d2)

**Comment by markotoplak** [comment]
The thing to install is actually `pyqtwebegine`. The problem stems from the fact that we could not add PyQt as a dependency of the pip package because that leads to other problems. 

How to install `pyqtwebegine` depends on how PyQt was installed.

- If you are using your system's system python installation directly and if your PyQt came with your Linux distribution, install the proper distribution package.

- If you installed PyQt it from pip, then continue with pip. But first, you will need to know which version of PyQt you have: run `pip3 freeze | grep -i pyqt`

  - If you see PyQt5 in the results, install pyqtwebengine: `pip3 install pyqtwebengine`

  - If you see PyQt6 in the results, install it so: `pip3 install pyqt6-webengine`

Thanks for opening the issue. I'll also check our installation instructions to see how we can improve them. Please report if any of these helped.

**Comment by ales-erjavec** [comment]
@JoaoGabrielTN Can you try runing
```sh
QTWEBENGINE_CHROMIUM_FLAGS="--disable-gpu --no-sandbox" orange-canvas
```

**Comment by markotoplak** [comment]
@JoaoGabrielTN, could you also try to see if the reports work? Open the File widget and click the report icon (third small icon at the bottom). Something like this should show up. 

![a](https://github.com/biolab/orange3/assets/552182/1a1fbc3c-083d-4277-8208-b1e580d8b1bd)

If you see a File description on the right, the problem is likely isolated to Text mining widgets.

**Comment by JoaoGabrielTN** [comment]
> ```shell
> QTWEBENGINE_CHROMIUM_FLAGS="--disable-gpu --no-sandbox" orange-canvas
> ```

Thank you, this resolved the problem. The wordcloud now appears when I plot it.

**Comment by markotoplak** [comment]
@JoaoGabrielTN, can you perhaps try if it also works if you only use a single flag? Or do you need both?

@ales-erjavec, why does this work? What was your idea when you suggested the solution?

**Comment by markotoplak** [comment]
With new version of PyQT5 I now need `QTWEBENGINE_CHROMIUM_FLAGS="--no-sandbox"` web engine to work.

**Comment by kaustuvchatterjee** [comment]
Even after running QTWEBENGINE_CHROMIUM_FLAGS="--disable-gpu --no-sandbox" orange-canvas, I get the same error.
Version: | 3.37.0
Environment: | Python 3.12.4 on Linux 6.9.10-200.fc40.x86_64

pip3 freeze | grep -i pyqt
PyQt5==5.15.10
PyQt5-sip==12.13.0
pyqtgraph==0.13.7
PyQtWebEngine==5.15.7
PyQtWebEngine-Qt5==5.15.14

Error:
Traceback (most recent call last):
  File "/home/kaustuv/.local/lib/python3.12/site-packages/orangecanvas/scheme/widgetmanager.py", line 404, in __process_init_queue
    self.ensure_created(node)
  File "/home/kaustuv/.local/lib/python3.12/site-packages/orangecanvas/scheme/widgetmanager.py", line 350, in ensure_created
    self.__add_widget_for_node(node)
  File "/home/kaustuv/.local/lib/python3.12/site-packages/orangecanvas/scheme/widgetmanager.py", line 243, in __add_widget_for_node
    w = self.create_widget_for_node(node)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kaustuv/.local/lib/python3.12/site-packages/orangewidget/workflow/widgetsscheme.py", line 300, in create_widget_for_node
    widget = self.create_widget_instance(node)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kaustuv/.local/lib/python3.12/site-packages/orangewidget/workflow/widgetsscheme.py", line 413, in create_widget_instance
    widget.__init__()
  File "/home/kaustuv/.local/lib/python3.12/site-packages/orangecontrib/text/widgets/owwordcloud.py", line 149, in __init__
    self.on_corpus_change(None)
  File "/home/kaustuv/.local/lib/python3.12/site-packages/orangewidget/utils/signals.py", line 208, in summarize_wrapper
    method(widget, value)
  File "/home/kaustuv/.local/lib/python3.12/site-packages/orangecontrib/text/widgets/owwordcloud.py", line 427, in on_corpus_change
    self.handle_input()
  File "/home/kaustuv/.local/lib/python3.12/site-packages/orangecontrib/text/widgets/owwordcloud.py", line 443, in handle_input
    self.clear()
  File "/home/kaustuv/.local/lib/python3.12/site-packages/orangecontrib/text/widgets/owwordcloud.py", line 455, in clear
    self._new_webview()
  File "/home/kaustuv/.local/lib/python3.12/site-packages/orangecontrib/text/widgets/owwordcloud.py", line 182, in _new_webview
    class Webview(gui.WebviewWidget):
                  ^^^^^^^^^^^^^^^^^
AttributeError: module 'Orange.widgets.gui' has no attribute 'WebviewWidget'

**Comment by kaustuvchatterjee** [comment]
Resolved the issue by installing python3-qt5-webengine using dnf.

> Even after running QTWEBENGINE_CHROMIUM_FLAGS="--disable-gpu --no-sandbox" orange-canvas, I get the same error. Version: | 3.37.0 Environment: | Python 3.12.4 on Linux 6.9.10-200.fc40.x86_64
> 
> pip3 freeze | grep -i pyqt PyQt5==5.15.10 PyQt5-sip==12.13.0 pyqtgraph==0.13.7 PyQtWebEngine==5.15.7 PyQtWebEngine-Qt5==5.15.14
> 
> Error: Traceback (most recent call last): File "/home/kaustuv/.local/lib/python3.12/site-packages/orangecanvas/scheme/widgetmanager.py", line 404, in __process_init_queue self.ensure_created(node) File "/home/kaustuv/.local/lib/python3.12/site-packages/orangecanvas/scheme/widgetmanager.py", line 350, in ensure_created self.__add_widget_for_node(node) File "/home/kaustuv/.local/lib/python3.12/site-packages/orangecanvas/scheme/widgetmanager.py", line 243, in __add_widget_for_node w = self.create_widget_for_node(node) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/kaustuv/.local/lib/python3.12/site-packages/orangewidget/workflow/widgetsscheme.py", line 300, in create_widget_for_node widget = self.create_widget_instance(node) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/kaustuv/.local/lib/python3.12/site-packages/orangewidget/workflow/widgetsscheme.py", line 413, in create_widget_instance widget.**init**() File "/home/kaustuv/.local/lib/python3.12/site-packages/orangecontrib/text/widgets/owwordcloud.py", line 149, in **init** self.on_corpus_change(None) File "/home/kaustuv/.local/lib/python3.12/site-packages/orangewidget/utils/signals.py", line 208, in summarize_wrapper method(widget, value) File "/home/kaustuv/.local/lib/python3.12/site-packages/orangecontrib/text/widgets/owwordcloud.py", line 427, in on_corpus_change self.handle_input() File "/home/kaustuv/.local/lib/python3.12/site-packages/orangecontrib/text/widgets/owwordcloud.py", line 443, in handle_input self.clear() File "/home/kaustuv/.local/lib/python3.12/site-packages/orangecontrib/text/widgets/owwordcloud.py", line 455, in clear self._new_webview() File "/home/kaustuv/.local/lib/python3.12/site-packages/orangecontrib/text/widgets/owwordcloud.py", line 182, in _new_webview class Webview(gui.WebviewWidget): ^^^^^^^^^^^^^^^^^ AttributeError: module 'Orange.widgets.gui' has no attribute 'WebviewWidget'

**Comment by gmolledaj** [comment]
Closed? The problem persists, on LinuxMint 22 Wilma. Installing

**Comment by gmolledaj** [comment]
Now I upgraded packages: pip install --upgrade beautifulsoup4 oauthlib websockets brotli pycryptodomex pyqt5  pyqtwebengine
and now the program close with error:
Could not find QtWebEngineProcess
Abortado (`core' generado)

**Comment by markotoplak** [comment]
Please show us what you see with: `pip freeze | grep -i pyqt`

Just to confirm - do you have problems with other widgets, like "File" too?

**Comment by gmolledaj** [comment]
> Please show us what you see with: `pip freeze | grep -i pyqt`
> 
> Just to confirm - do you have problems with other widgets, like "File" too?

PyQt5==5.15.11
PyQt5-Qt5==5.15.16
PyQt5_sip==12.16.1
pyqtgraph==0.13.3
PyQtWebEngine==5.15.7
PyQtWebEngine-Qt5==5.15.2

**Comment by markotoplak** [comment]
Did you try starting Orange like this: `QTWEBENGINE_CHROMIUM_FLAGS="--disable-gpu --no-sandbox" orange-canvas`?

**Comment by gmolledaj** [comment]
> Did you try starting Orange like this: `QTWEBENGINE_CHROMIUM_FLAGS="--disable-gpu --no-sandbox" orange-canvas`?
Same behavior:
$ QTWEBENGINE_CHROMIUM_FLAGS="--disable-gpu --no-sandbox" orange-canvas
Could not find QtWebEngineProcess
Abortado (`core' generado)

**Comment by gmolledaj** [comment]
> Did you try starting Orange like this: `QTWEBENGINE_CHROMIUM_FLAGS="--disable-gpu --no-sandbox" orange-canvas`?

Mismo resultado: $ QTWEBENGINE_CHROMIUM_FLAGS="--disable-gpu --no-sandbox" orange-canvas
Could not find QtWebEngineProcess
Abortado (`core' generado)

**Comment by markotoplak** [comment]
@gmolledaj, thanks for trying out these options. I have no idea why it does not work on your system.

Another option is to try with Qt6. This will likely require that you make a new environment (just to be sure there are no Qt5/6 conflicts) and instead install Qt6 packages. Here is what I see in my environment (on closely related Ubuntu 24.04):

```
$ pip freeze | grep -i pyqt
PyQt6==6.8.0
PyQt6-Qt6==6.8.1
PyQt6-WebEngine==6.8.0
PyQt6-WebEngine-Qt6==6.8.1
PyQt6_sip==13.9.1
pyqtgraph==0.13.7
```

**Comment by gmolledaj** [comment]
Thanks, now say: (orange3) ...:~/miniconda3/envs$ pip freeze | grep -i pyqt
PyQt6==6.8.0
PyQt6-Qt6==6.8.1
PyQt6-WebEngine==6.8.0
PyQt6-WebEngine-Qt6==6.8.1
PyQt6_sip==13.9.1
pyqtgraph==0.13.3
(orange3) ...:~/miniconda3/envs$ orange-canvas
Traceback (most recent call last):
  File "/home/.../miniconda3/envs/orange3/bin/orange-canvas", line 5, in <module>
    from Orange.canvas.__main__ import main
  File "/home/.../miniconda3/envs/orange3/lib/python3.10/site-packages/Orange/__init__.py", line 30, in <module>
    from AnyQt.QtCore import QObject
  File "/home/.../.local/lib/python3.10/site-packages/AnyQt/QtCore.py", line 274, in <module>
    from PyQt5.QtCore import *
ModuleNotFoundError: No module named 'PyQt5.QtCore'

**Comment by gmolledaj** [comment]
SOLVE: After completely uninstalling pyqt5 and installing pyqt6 I saw that it kept loading pyqt5, uninstalled in my system with synaptic and when running orange-cavas I got the error No module named 'PyQt5.QtCore'
I saw that it took qt5 from ~/.local/lib/python3.10.
I renamed that folder and installed the whole env and orange3 again. SOLVED. Works great. Thanks a lot.
