### ISSUE TITLE
Cannot select radio buttons in Hierarchical Clustering

### ISSUE THREAD

**Issue by processo** [biolab/orange3#6715]
In Hierarchical Clustering selecting None (in Pruning) or Manual (in Selection) only works in a narrow area under the radio button and its text (red area on image).

![image](https://github.com/biolab/orange3/assets/5299789/96dadc69-d63e-439f-a998-fffdc26b8d37)

OS: Windows 10
Orange: 3.36.2

**Comment by markotoplak** [comment]
Thanks. Is this isolated to Hierarchical Clustering or do you get it in other widgets with radio buttons too? Try Distances, please, and report.

**Comment by processo** [comment]
SVM > SVM Type > SVM is also broken. The others are working fine.
