### ISSUE TITLE
Orange and PyMC?

### ISSUE THREAD

**Issue by MoritzImendoerffer** [biolab/orange3#6720]
**What's your use case?**
Bayesian Modelling e.g. using [PyMC](https://www.pymc.io/welcome.html) has already a visual representation built into it's concept. E.g. converting the model to `pm.model_to_graphviz(model)`

Adapting the Orange framework to Bayesian or probabalist modelling in general, might lower the bounds for students to learn these concepts.

**What's your proposed solution?**
I haven't looked into the details but there is a functionality within PyMC to convert a model to networkX:
https://www.pymc.io/projects/docs/en/stable/_modules/pymc/model_graph.html

Would it be possible to do the inverse step? There is already an extension for NetworkX implemented in Orange. 

That might be a starting point to generate PyMC models in Orange graphically.

I am not a professional software developer neither an expert in Bayesian modelling but I can code and would be willing to invest some time developing a prototype if someone else is interested.

**Are there any alternative solutions?**
I haven't found any by googling.

**Comment by janezd** [comment]
This is a nice idea ... but.

What one would need is not, e. g. a widget for Bayesian modelling, but rather a new kind of Orange that would look like the existing, but with a completely different set of "widgets" that would represent different ... distributions, probably. That is, we would reuse the canvas, but not widgets, like in [Oasys](https://www.aps.anl.gov/Science/Scientific-Software/OASYS).

Quite some time ago I discussed this with an expert in Bayesian modelling, who said that he's actually tried the idea but it was just too complicated. Still, I'd be happy to try it, but this would require a very eager PhD student and a good advisor from the Bayesian side.

For the sake of keeping the list of open issues tractable, I'm closing this issue, but we'll keep the idea in mind.
