### ISSUE TITLE
Installation via Miniconda fails on Ubuntu 23.10

### ISSUE THREAD

**Issue by sm8ps** [biolab/orange3#6724]
**What's wrong?**

I tried to install Orange3 by following the specified procedure. 
1. install Miniconda
2. `conda config --add channels conda-forge`
3. `conda config --set channel_priority strict`
4. `conda create python=3 --yes --name orange3`
5. `conda activate orange3`
6. `conda install orange3`
The output then gives countless many errors 
```
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
```
Finally it says:
```
failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package orange3-3.33.0-py310h769672d_0 requires python >=3.10,<3.11.0a0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ orange3 is installable with the potential options
│  ├─ orange3 [3.10.0|3.11.0|...|3.9.1] would require
│  │  └─ python [3.5* |>=3.5,<3.6.0a0 ], which can be installed;
│  ├─ orange3 [3.10.0|3.11.0|...|3.9.1] would require
│  │  └─ python 3.6* , which can be installed;
│  ├─ orange3 [3.13.0|3.14.0|...|3.30.1] would require
│  │  └─ python >=3.6,<3.7.0a0 , which can be installed;
│  ├─ orange3 [3.18.0|3.19.0|...|3.32.0] would require
│  │  └─ python >=3.7,<3.8.0a0 , which can be installed;
│  ├─ orange3 [3.24.0|3.24.1|...|3.36.2] would require
│  │  └─ python >=3.8,<3.9.0a0 , which can be installed;
│  ├─ orange3 [3.28.0|3.29.0|...|3.36.2] would require
│  │  └─ python >=3.9,<3.10.0a0 , which can be installed;
│  ├─ orange3 [3.3.10|3.3.6|3.3.7|3.3.8|3.3.9] would require
│  │  └─ python 3.4* , which can be installed;
│  ├─ orange3 [3.33.0|3.34.0|...|3.36.2] would require
│  │  └─ python >=3.10,<3.11.0a0 , which can be installed;
│  ├─ orange3 [3.36.0|3.36.1|3.36.2] would require
│  │  └─ python >=3.11,<3.12.0a0 , which can be installed;
│  └─ orange3 [3.11.0|3.13.0|...|3.34.0] conflicts with any installable versions previously reported;
└─ pin-1 is not installable because it requires
   └─ python 3.12.* , which conflicts with any installable versions previously reported.

Pins seem to be involved in the conflict. Currently pinned specs:
 - python 3.12.* (labeled as 'pin-1')
```

I get the following Python versions in the different environments:

```
(base) $ python3 --version
Python 3.11.5
(base) $ conda activate orange3
(orange3) $ python3 --version
Python 3.12.1
```

I have searched all over for any pointer but I am still at loss about what to do.

**How can we reproduce the problem?** 

I presume there is nothing that specific about my installation that it could not be reproduced.

**What's your environment?**

- Operating system: Ubuntu 23.10

**Comment by markotoplak** [comment]
Thanks.

Could you also try to specify a python version when making a conda environment, such as `conda create python=3.10 --yes --name orange3`? Before that, please remove your old orange3 environment.

**Comment by sm8ps** [comment]
Many thanks for your consideration!
```
(base) $ conda-env remove -n orange3
(base) $ conda create python=3.10 --yes --name orange3
(base) $ python3 --version
Python 3.11.5
(base) $ conda activate orange3
(orange3) $ python3 --version
Python 3.10.13
```

**Comment by sm8ps** [comment]
I knew there was somehting more! (: As a matter of fact, the installation did run through. Thanks a lot for your help @markotoplak .
Do you think that this hint should be included in the installation instructions "[Installing with Conda](https://github.com/biolab/orange3?tab=readme-ov-file#installing-with-conda)"?

**Comment by markotoplak** [comment]
@sm8ps, thanks for bringing this to our attention, we need to update the instructions.

**Comment by sm8ps** [comment]
PS Kudos for your response, @markotoplak!
