### ISSUE TITLE
Widget Predictions error

### ISSUE THREAD

**Issue by diegovendas** [biolab/orange3#6732]
![image](https://github.com/biolab/orange3/assets/160022648/ce7107f0-1336-465e-81be-917a7d68bbac)
![image](https://github.com/biolab/orange3/assets/160022648/518e41de-b524-49a7-9e35-47ea56307b57)
![image](https://github.com/biolab/orange3/assets/160022648/030e5a24-fec5-4522-a6f7-f1c220b03d85)
![image](https://github.com/biolab/orange3/assets/160022648/990721fe-ca41-4da1-8874-222a1b6ff7d4)
![image](https://github.com/biolab/orange3/assets/160022648/5b69b4fa-927b-45fe-9035-33f58938605b)
![image](https://github.com/biolab/orange3/assets/160022648/052610fd-a23f-4445-9d74-4b630156b919)

**Hello dear friends!

Please, can someone help me!

I'm not a programmer, I'm just a user, I think I'm making a mistake in some procedure, because every time I try to use an unsupervised widget, an error occurs in the "Predictions" widget!**

**At first I thought the error was due to some incorrect treatment in the data input classes!

So I did another test in text format, and the same error happens, every time I include an unsupervised widget the "Predictions" bug

I've already reinstalled orange, I've done everything, but the error persists!** 

**My execution environment information:**

- Operating system: Windows 10 Pro, 22H2, 19045.3930, Windows Feature Experience Pack 1000.19053.1000.0
- Orange version: 3.36.2
- How you installed Orange: execute as administrator

**Comment by diegovendas** [comment]
Hello friend!

I'm actually trying to predict grades for a school competition!

There are 15 subjects, scores vary from 1 to 25 in these 15 subjects!

That's why I created a "contest" column where each line contains the number of each contest!
and 15 more columns with the respective school grades "ranging from 1 to 25"

the school grade for competition 30 is:
06, 07, 08, 09, 10, 12, 13, 14, 15, 16, 17, 20, 21, 23, 25

I'll try to attach the excel files so you can try to simulate, thanks!

[13-02-2024-resultados-01-32.csv](https://github.com/biolab/orange3/files/14280315/13-02-2024-resultados-01-32.csv)
[previsao_01-32.xlsx](https://github.com/biolab/orange3/files/14280316/previsao_01-32.xlsx)
[resultados_expandidos_ajustados_01-32.xlsx](https://github.com/biolab/orange3/files/14280317/resultados_expandidos_ajustados_01-32.xlsx)

**Comment by diegovendas** [comment]
A friend told me that this seems like a lack of imputation!

but I don't know how to solve it!

**Comment by markotoplak** [comment]
Ok, if I understand your issue, you are pointing out that Predictions show bad results if you train it on one k-means clustering and predict it on another k-means clustering.

Well, this is expected. The clusters you get may have different meanings (if nothing else, their names can be swapped). Thus, a model built on clustering won't perform well on another unless the clusterings are almost identical.

If I misunderstood your issue, please comment.

**Comment by diegovendas** [comment]
> Ok, se eu entendo seu problema, você está apontando que as previsões mostram resultados ruins se você treiná-lo em um agrupamento k-means e prevê-lo em outro agrupamento k-means.
> 
> Bem, isso é esperado. Os clusters que você obtém podem ter significados diferentes (se nada mais, seus nomes podem ser trocados). Assim, um modelo construído em clustering não terá um bom desempenho em outro, a menos que os clusterings sejam quase idênticos.
> 
> Se eu entendi mal o seu problema, por favor, comente.

Hello friend, thanks for asking!

Another friend told me that my use case should not be treated with Kmeans, but with ARIMA, because according to him, my use case requires time series analysis!

I will attach the spreadsheets that I need to predict, to make it clearer and more objective!
[AULAS_EXPANDIDAS.xlsx](https://github.com/biolab/orange3/files/14311538/AULAS_EXPANDIDAS.xlsx)
[AULAS_EXPANDIDAS_PREVISAO.xlsx](https://github.com/biolab/orange3/files/14311539/AULAS_EXPANDIDAS_PREVISAO.xlsx)

the result of line 35 is = CALVICIE 3, FACIAL 5, DESIGNER 6 and PEDICURE 8:
3, 5, 6 and 8!

Please, can you generate a project that makes this prediction based on the spreadsheets I am sending?

![image](https://github.com/biolab/orange3/assets/160022648/bb034459-bcb6-44e5-ad66-90f42d1a6f5b)

I've tried everything I can, but I can't!
