### ISSUE TITLE
 sklearn 1.1.3 can be upgraded?

### ISSUE THREAD

**Issue by msokouti1** [biolab/orange3#6745]
Greetings!

This is to ask if the sklearn 1.1.3 can be upgraded to the latest on (i.e., 1.4) in Orange3 in which get_params can be used to extract the weights and biases of a trained neural network model?
As in the sklearn 1.1.3 the weights and biases are not available for further analyses in python.

Many thanks in advance

**Comment by markotoplak** [comment]
The current release of Orange (3.36.2) does not support scikit-learn 1.4 yet, but you can upgrade to 1.3 (not sure if that suffices).

The next release, likely available next week, will support 1.4, as the current master also does.
