### ISSUE TITLE
Import Images Widget Info Typo

### ISSUE THREAD

**Issue by foongminwong** [biolab/orange3#6753]
**What's wrong?**
I imported an `image-data` folder with 3 labeled subfolders - `broccoli`, `capsicum`, `tomato` using the Image Analytics Add-on.
![image](https://github.com/biolab/orange3/assets/23441795/21256f6f-de50-496b-83b0-29cd00ef8134)

It showed `3 categorys`, instead of `3 categories`.

![image](https://github.com/biolab/orange3/assets/23441795/6ef7bb6d-b1a1-45e5-95fe-f801ee0a6b49)

I tested by adding these two lines to [orange3/Orange/widgets/utils/localization/__init__.py](https://github.com/biolab/orange3/blob/master/Orange/widgets/utils/localization/__init__.py) locally, it somehow fixed the typo.

![image](https://github.com/biolab/orange3/assets/23441795/844eb034-587b-4c44-84e9-56ca483e5606)

**What's your environment?**

- Operating system: Windows 10
- Orange version: 3.36.2
- How you installed Orange: `pip install Orange3`

**Comment by janezd** [comment]
Thanks for telling us.

Note for whomever takes this issue: this function shouldn't be here at all. Widgets should use https://github.com/biolab/orange-canvas-core/blob/master/orangecanvas/utils/localization/__init__.py instead. For backward compatibility, [orange3/Orange/widgets/utils/localization/init.py](https://github.com/biolab/orange3/blob/master/Orange/widgets/utils/localization/__init__.py) should just import and re-export the former function, which also already properly implements the rule for plural of nouns ending with -y.
