### ISSUE TITLE
Cannot view tabs to load data or start working with orange after upgrading

### ISSUE THREAD

**Issue by Radingwana** [biolab/orange3#6765]
**What's wrong?**

I cant open tabs to load, transform or just work on the platform after upgrading. it is blank, i tried refreshing the machine and restarting with no luck. the orange is installed via anaconda
![orange](https://github.com/biolab/orange3/assets/147332306/e0710c33-066f-4713-93a7-012e76756bbd)
_

**How can we reproduce the problem?** 

**What's your environment?**

- Operating system:
- Orange version:
- How you installed Orange:

**Comment by ales-erjavec** [comment]
Can you please open "Orange Command Prompt" (from the windows Start Menu) and run `orange-canvas -l4` and post the output.

**Comment by Radingwana** [comment]
Hi Aleš
I have downloaded orange outside the anaconda environment, it works. Thank you.

Kind Regards
Promat Radingwana
076 287 1192
________________________________
