### ISSUE TITLE
Could not Fetch Dataset when using Orange

### ISSUE THREAD

**Issue by kerwindevries** [biolab/orange3#6770]
When trying to utilise the dataset widget on Orange, i get error "could not fetch dataset list". 
I have also tried to allow the Orange application through my firewall, but still get the same error.
Can you please assist.

**Comment by kerwindevries** [comment]
Detail from log:
Traceback (most recent call last):
  File "C:\Program Files\Orange\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "C:\Program Files\Orange\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

When trying to open "Add-Ons" get the following error message: " insufficient permission to install add-ons. Try starting Orange as system adminstrator or install Orange in user folder".
![image](https://github.com/biolab/orange3/assets/164471429/6f48af94-16ce-40fd-be0a-b8485d4a817a)


Note I am using my work laptop, and when going into Options> Settings> Network, it is blank.

**Comment by kerwindevries** [comment]
Hi,

I am busy with a tutorial in a course that I am attending.
Is there anyway to download a dataset and then upload it?
I need the german credit risk dataset.

Regards,
Kerwin

**Comment by lanzagar** [comment]
While you are working on solving the issue, you can download datasets manually from the browser and open the file with the File widget instead. The dataset you mentioned is here https://datasets.biolab.si/core/german-credit-data.tab (you might need to right click the link and Save as)
