### ISSUE TITLE
Installation problem "conda" command exited with 1. Cannot continue.

### ISSUE THREAD

**Issue by dongne1004** [biolab/orange3#6775]
After deleting miniconda, I tried installing Orange several times, but the same problem keeps happening.ㅠㅠ
Please help.

Creating an new conda env in "C:\Program Files\Orange"
Output folder: C:\WINDOWS\TEMP\nsd91E.tmp\Orange-installer-data\conda-pkgs
Extract: _py-xgboost-mutex-2.0-cpu_0.tar.bz2
Extract: anyio-4.1.0-pyhd8ed1ab_0.conda
Extract: anyqt-0.2.0-pyh6c4a22f_0.tar.bz2
Extract: asttokens-2.4.1-pyhd8ed1ab_0.conda
Extract: attrs-23.1.0-pyh71513ae_1.conda
Extract: baycomp-1.0.2-py_1.tar.bz2
Extract: blas-2.120-openblas.conda
Extract: blas-devel-3.9.0-20_win64_openblas.conda
Extract: bottleneck-1.3.7-py39hd88c2e4_1.conda
Extract: brotli-1.1.0-hcfcfb64_1.conda
Extract: brotli-bin-1.1.0-hcfcfb64_1.conda
Extract: brotli-python-1.1.0-py39h99910a6_1.conda
Extract: bzip2-1.0.8-hcfcfb64_5.conda
Extract: ca-certificates-2023.11.17-h56e8100_0.conda
Extract: cairo-1.18.0-h1fef639_0.conda
Extract: catboost-1.2.2-py39hcbf5309_0.conda
Extract: cattrs-23.2.3-pyhd8ed1ab_0.conda
Extract: certifi-2023.11.17-pyhd8ed1ab_0.conda
Extract: chardet-5.2.0-py39hcbf5309_1.conda
Extract: charset-normalizer-3.3.2-pyhd8ed1ab_0.conda
Extract: colorama-0.4.6-pyhd8ed1ab_0.tar.bz2
Extract: comm-0.1.4-pyhd8ed1ab_0.conda
Extract: commonmark-0.9.1-py_0.tar.bz2
Extract: conda-spec.txt
Extract: contourpy-1.2.0-py39h1f6ef14_0.conda
Extract: cycler-0.12.1-pyhd8ed1ab_0.conda
Extract: debugpy-1.8.0-py39h99910a6_1.conda
Extract: decorator-5.1.1-pyhd8ed1ab_0.tar.bz2
Extract: dictdiffer-0.9.0-pyhd8ed1ab_0.tar.bz2
Extract: docutils-0.20.1-py39hcbf5309_3.conda
Extract: et_xmlfile-1.1.0-pyhd8ed1ab_0.conda
Extract: exceptiongroup-1.2.0-pyhd8ed1ab_0.conda
Extract: executing-2.0.1-pyhd8ed1ab_0.conda
Extract: expat-2.5.0-h63175ca_1.conda
Extract: font-ttf-dejavu-sans-mono-2.37-hab24e00_0.tar.bz2
Extract: font-ttf-inconsolata-3.000-h77eed37_0.tar.bz2
Extract: font-ttf-source-code-pro-2.038-h77eed37_0.tar.bz2
Extract: font-ttf-ubuntu-0.83-h77eed37_1.conda
Extract: fontconfig-2.14.2-hbde0cde_0.conda
Extract: fonts-conda-ecosystem-1-0.tar.bz2
Extract: fonts-conda-forge-1-0.tar.bz2
Extract: fonttools-4.46.0-py39ha55989b_0.conda
Extract: freetype-2.12.1-hdaf720e_2.conda
Extract: fribidi-1.0.10-h8d14728_0.tar.bz2
Extract: future-0.18.3-pyhd8ed1ab_0.conda
Extract: getopt-win32-0.1-hcfcfb64_1.conda
Extract: gettext-0.21.1-h5728263_0.tar.bz2
Extract: glib-2.78.3-h12be248_0.conda
Extract: glib-tools-2.78.3-h12be248_0.conda
Extract: graphite2-1.3.13-1000.tar.bz2
Extract: graphviz-9.0.0-h51cb2cd_1.conda
Extract: gst-plugins-base-1.22.7-h001b923_0.conda
Extract: gstreamer-1.22.7-hb4038d2_0.conda
Extract: gts-0.7.6-h6b5321d_4.conda
Extract: h11-0.14.0-pyhd8ed1ab_0.tar.bz2
Extract: h2-4.1.0-pyhd8ed1ab_0.tar.bz2
Extract: harfbuzz-8.3.0-h7ab893a_0.conda
Extract: hpack-4.0.0-pyh9f0ad1d_0.tar.bz2
Extract: httpcore-1.0.2-pyhd8ed1ab_0.conda
Extract: httpx-0.25.2-pyhd8ed1ab_0.conda
Extract: hyperframe-6.0.1-pyhd8ed1ab_0.tar.bz2
Extract: icu-73.2-h63175ca_0.conda
Extract: idna-3.6-pyhd8ed1ab_0.conda
Extract: importlib-metadata-7.0.0-pyha770c72_0.conda
Extract: importlib-resources-6.1.1-pyhd8ed1ab_0.conda
Extract: importlib_metadata-7.0.0-hd8ed1ab_0.conda
Extract: importlib_resources-6.1.1-pyhd8ed1ab_0.conda
Extract: install.bat
Extract: ipykernel-6.26.0-pyha63f2e9_0.conda
Extract: ipython-8.18.1-pyh7428d3b_3.conda
Extract: itsdangerous-2.1.2-pyhd8ed1ab_0.tar.bz2
Extract: jaraco.classes-3.3.0-pyhd8ed1ab_0.conda
Extract: jedi-0.19.1-pyhd8ed1ab_0.conda
Extract: joblib-1.3.2-pyhd8ed1ab_0.conda
Extract: jupyter_client-8.6.0-pyhd8ed1ab_0.conda
Extract: jupyter_core-5.5.0-py39hcbf5309_0.conda
Extract: keyring-24.3.0-py39hcbf5309_0.conda
Extract: keyrings.alt-4.2.0-pyhd8ed1ab_0.conda
Extract: kiwisolver-1.4.5-py39h1f6ef14_1.conda
Extract: krb5-1.21.2-heb0366b_0.conda
Extract: lcms2-2.16-h67d730c_0.conda
Extract: lerc-4.0.0-h63175ca_0.tar.bz2
Extract: libblas-3.9.0-20_win64_openblas.conda
Extract: libbrotlicommon-1.1.0-hcfcfb64_1.conda
Extract: libbrotlidec-1.1.0-hcfcfb64_1.conda
Extract: libbrotlienc-1.1.0-hcfcfb64_1.conda
Extract: libcblas-3.9.0-20_win64_openblas.conda
Extract: libclang-15.0.7-default_hde6756a_4.conda
Extract: libclang13-15.0.7-default_h85b4d89_4.conda
Extract: libdeflate-1.19-hcfcfb64_0.conda
Extract: libexpat-2.5.0-h63175ca_1.conda
Extract: libffi-3.4.2-h8ffe710_5.tar.bz2
Extract: libflang-5.0.0-h6538335_20180525.tar.bz2
Extract: libgd-2.3.3-h312136b_9.conda
Extract: libglib-2.78.3-h16e383f_0.conda
Extract: libiconv-1.17-h8ffe710_0.tar.bz2
Extract: libjpeg-turbo-3.0.0-hcfcfb64_1.conda
Extract: liblapack-3.9.0-20_win64_openblas.conda
Extract: liblapacke-3.9.0-20_win64_openblas.conda
Extract: libogg-1.3.4-h8ffe710_1.tar.bz2
Extract: libopenblas-0.3.25-pthreads_hc140b1d_0.conda
Extract: libpng-1.6.39-h19919ed_0.conda
Extract: libsodium-1.0.18-h8d14728_1.tar.bz2
Extract: libsqlite-3.44.2-hcfcfb64_0.conda
Extract: libtiff-4.6.0-h6e2ebb7_2.conda
Extract: libvorbis-1.3.7-h0e60522_0.tar.bz2
Extract: libwebp-1.3.2-hcfcfb64_1.conda
Extract: libwebp-base-1.3.2-hcfcfb64_0.conda
Extract: libxcb-1.15-hcd874cb_0.conda
Extract: libxgboost-1.7.6-cpu_h0f92c63_6.conda
Extract: libxml2-2.12.2-hc3477c8_0.conda
Extract: libzlib-1.2.13-hcfcfb64_5.conda
Extract: llvm-meta-5.0.0-0.tar.bz2
Extract: m2w64-gcc-libgfortran-5.3.0-6.tar.bz2
Extract: m2w64-gcc-libs-5.3.0-7.tar.bz2
Extract: m2w64-gcc-libs-core-5.3.0-7.tar.bz2
Extract: m2w64-gmp-6.1.0-2.tar.bz2
Extract: m2w64-libwinpthread-git-5.0.0.4634.697f757-2.tar.bz2
Extract: matplotlib-base-3.8.2-py39hf19769e_0.conda
Extract: matplotlib-inline-0.1.6-pyhd8ed1ab_0.tar.bz2
Extract: more-itertools-10.1.0-pyhd8ed1ab_0.conda
Extract: msys2-conda-epoch-20160418-1.tar.bz2
Extract: munkres-1.1.4-pyh9f0ad1d_0.tar.bz2
Extract: nest-asyncio-1.5.8-pyhd8ed1ab_0.conda
Extract: networkx-3.2.1-pyhd8ed1ab_0.conda
Extract: numpy-1.24.4-py39h816b6a6_0.conda
Extract: openblas-0.3.25-pthreads_h3721920_0.conda
Extract: openjpeg-2.5.0-h3d672ee_3.conda
Extract: openmp-5.0.0-vc14_1.tar.bz2
Extract: openpyxl-3.1.2-py39ha55989b_1.conda
Extract: openssl-3.2.0-hcfcfb64_1.conda
Extract: opentsne-1.0.1-py39h5c3ab46_1.conda
Extract: orange-canvas-core-0.1.35-pyhd8ed1ab_0.conda
Extract: orange-widget-base-4.22.0-pyhd8ed1ab_0.conda
Extract: orange3-3.36.2-py39h32e6231_0.conda
Extract: packaging-23.2-pyhd8ed1ab_0.conda
Extract: pandas-1.5.3-py39h2ba5b7c_1.conda
Extract: pango-1.50.14-h07c897b_2.conda
Extract: parso-0.8.3-pyhd8ed1ab_0.tar.bz2
Extract: pcre2-10.42-h17e33f8_0.conda
Extract: pickleshare-0.7.5-py_1003.tar.bz2
Extract: pillow-10.1.0-py39h368b509_0.conda
Extract: pip-23.3.1-pyhd8ed1ab_0.conda
Extract: pixman-0.42.2-h63175ca_0.conda
Extract: platformdirs-4.1.0-pyhd8ed1ab_0.conda
Extract: plotly-5.18.0-pyhd8ed1ab_0.conda
Extract: ply-3.11-py_1.tar.bz2
Extract: pooch-1.8.0-pyhd8ed1ab_0.conda
Extract: prompt-toolkit-3.0.41-pyha770c72_0.conda
Extract: psutil-5.9.5-py39ha55989b_1.conda
Extract: pthread-stubs-0.4-hcd874cb_1001.tar.bz2
Extract: pure_eval-0.2.2-pyhd8ed1ab_0.tar.bz2
Extract: py-xgboost-1.7.6-cpu_py39hd3de297_6.conda
Extract: pygments-2.17.2-pyhd8ed1ab_0.conda
Extract: pyparsing-3.1.1-pyhd8ed1ab_0.conda
Extract: pyqt-5.15.9-py39hb77abff_5.conda
Extract: pyqt5-sip-12.12.2-py39h99910a6_5.conda
Extract: pyqtgraph-0.13.3-pyhd8ed1ab_0.conda
Extract: pyqtwebengine-5.15.9-py39h2f4a3f1_5.conda
Extract: pysocks-1.7.1-pyh0701188_6.tar.bz2
Extract: python-3.9.12-hcf16a7b_1_cpython.tar.bz2
Extract: python-dateutil-2.8.2-pyhd8ed1ab_0.tar.bz2
Extract: python-graphviz-0.20.1-pyh22cad53_0.tar.bz2
Extract: python-louvain-0.16-pyhd8ed1ab_0.conda
Extract: python_abi-3.9-4_cp39.conda
Extract: pytz-2023.3.post1-pyhd8ed1ab_0.conda
Extract: pywin32-306-py39h99910a6_2.conda
Extract: pywin32-ctypes-0.2.2-py39hcbf5309_1.conda
Extract: pyyaml-6.0.1-py39ha55989b_1.conda
Extract: pyzmq-25.1.2-py39h7eaf5a6_0.conda
Extract: qasync-0.27.1-pyh9208f05_0.conda
Extract: qt-main-5.15.8-h9e85ed6_17.conda
Extract: qt-webengine-5.15.8-h4bf5c4e_4.tar.bz2
Extract: qtconsole-5.5.1-pyhd8ed1ab_0.conda
Extract: qtconsole-base-5.5.1-pyha770c72_0.conda
Extract: qtpy-2.4.1-pyhd8ed1ab_0.conda
Extract: requests-2.31.0-pyhd8ed1ab_0.conda
Extract: requests-cache-1.1.1-pyhd8ed1ab_0.conda
Extract: scikit-learn-1.1.3-py39h6fe01c0_1.tar.bz2
Extract: scipy-1.10.1-py39hde5eda1_3.conda
Extract: serverfiles-0.3.0-py_0.tar.bz2
Extract: setuptools-68.2.2-pyhd8ed1ab_0.conda
Extract: sip-6.7.12-py39h99910a6_0.conda
Extract: sitecustomize.py
Extract: six-1.16.0-pyh6c4a22f_0.tar.bz2
Extract: sniffio-1.3.0-pyhd8ed1ab_0.tar.bz2
Extract: sqlite-3.44.2-hcfcfb64_0.conda
Extract: stack_data-0.6.2-pyhd8ed1ab_0.conda
Extract: tenacity-8.2.3-pyhd8ed1ab_0.conda
Extract: threadpoolctl-3.2.0-pyha21a80b_0.conda
Extract: tk-8.6.13-h5226925_1.conda
Extract: toml-0.10.2-pyhd8ed1ab_0.tar.bz2
Extract: tomli-2.0.1-pyhd8ed1ab_0.tar.bz2
Extract: tornado-6.3.3-py39ha55989b_1.conda
Extract: traitlets-5.14.0-pyhd8ed1ab_0.conda
Extract: typing-extensions-4.8.0-hd8ed1ab_0.conda
Extract: typing_extensions-4.8.0-pyha770c72_0.conda
Extract: tzdata-2023c-h71feb2d_0.conda
Extract: ucrt-10.0.22621.0-h57928b3_0.tar.bz2
Extract: ujson-5.8.0-py39h99910a6_0.conda
Extract: unicodedata2-15.1.0-py39ha55989b_0.conda
Extract: url-normalize-1.4.3-pyhd8ed1ab_0.tar.bz2
Extract: urllib3-2.1.0-pyhd8ed1ab_0.conda
Extract: vc-14.3-h64f974e_17.conda
Extract: vc14_runtime-14.36.32532-hdcecf7f_17.conda
Extract: vs2015_runtime-14.36.32532-h05e6639_17.conda
Extract: wcwidth-0.2.12-pyhd8ed1ab_0.conda
Extract: wheel-0.42.0-pyhd8ed1ab_0.conda
Extract: win_inet_pton-1.1.0-pyhd8ed1ab_6.tar.bz2
Extract: xgboost-1.7.6-cpu_py39hd3de297_6.conda
Extract: xlrd-2.0.1-pyhd8ed1ab_3.tar.bz2
Extract: xlsxwriter-3.1.9-pyhd8ed1ab_0.conda
Extract: xorg-kbproto-1.0.7-hcd874cb_1002.tar.bz2
Extract: xorg-libice-1.1.1-hcd874cb_0.conda
Extract: xorg-libsm-1.2.4-hcd874cb_0.conda
Extract: xorg-libx11-1.8.7-hefa74cf_0.conda
Extract: xorg-libxau-1.0.11-hcd874cb_0.conda
Extract: xorg-libxdmcp-1.1.3-hcd874cb_0.tar.bz2
Extract: xorg-libxext-1.3.4-hcd874cb_2.conda
Extract: xorg-libxpm-3.5.17-hcd874cb_0.conda
Extract: xorg-libxt-1.3.0-hcd874cb_1.conda
Extract: xorg-xextproto-7.3.0-hcd874cb_1003.conda
Extract: xorg-xproto-7.0.31-hcd874cb_1007.tar.bz2
Extract: xz-5.2.6-h8d14728_0.tar.bz2
Extract: yaml-0.2.5-h8ffe710_2.tar.bz2
Extract: zeromq-4.3.5-h63175ca_0.conda
Extract: zipp-3.17.0-pyhd8ed1ab_0.conda
Extract: zlib-1.2.13-hcfcfb64_5.conda
Extract: zstd-1.5.5-h12be248_0.conda
Output folder: C:\WINDOWS\TEMP\nsd91E.tmp\Orange-installer-data\conda-pkgs
Installing packages (this might take a while)
Executing: cmd.exe /c install.bat "C:\Program Files\Orange" "C:\Users\A021122\Miniconda3\condabin\conda.bat"
Creating a conda env in "C:\Program Files\Orange"
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = 'C:\Tribon\M3\Vitesse;C:\Tribon\M3\Vitesse\Basic_Design;C:\Tribon\M3\Vitesse\Lib;C:\Tribon\M3\Vitesse\Projects;C:\Tribon\M3\bin\python'
  program name = 'C:\Users\A021122\Miniconda3\python.exe'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = 'C:\\Users\\A021122\\Miniconda3\\python.exe'
  sys.base_prefix = 'C:\\Users\\A021122\\Miniconda3'
  sys.base_exec_prefix = 'C:\\Users\\A021122\\Miniconda3'
  sys.platlibdir = 'lib'
  sys.executable = 'C:\\Users\\A021122\\Miniconda3\\python.exe'
  sys.prefix = 'C:\\Users\\A021122\\Miniconda3'
  sys.exec_prefix = 'C:\\Users\\A021122\\Miniconda3'
  sys.path = [
    'C:\\Tribon\\M3\\Vitesse',
    'C:\\Tribon\\M3\\Vitesse\\Basic_Design',
    'C:\\Tribon\\M3\\Vitesse\\Lib',
    'C:\\Tribon\\M3\\Vitesse\\Projects',
    'C:\\Tribon\\M3\\bin\\python',
    'C:\\Users\\A021122\\Miniconda3\\python39.zip',
    'C:\\Users\\A021122\\Miniconda3\\DLLs',
    'C:\\Users\\A021122\\Miniconda3\\lib',
    'C:\\Users\\A021122\\Miniconda3',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ImportError: bad magic number in 'encodings': b';\xf2\r\n'

Current thread 0x00000630 (most recent call first):
<no Python frame>
"conda" command exited with 1. Cannot continue.

I 

**What's wrong?**

**How can we reproduce the problem?** 

**What's your environment?**

- Operating system: Window 10 
- Orange version: 3.36.2 
- How you installed Orange:

**Comment by ales-erjavec** [comment]
My guess is this because you have a PYTHONPATH set in the env variables (`PYTHONPATH = 'C:\Tribon\M3\Vitesse;C:\Tribon\M3\Vitesse\Basic_Design;C:\Tribon\M3\Vitesse\Lib;C:\Tribon\M3\Vitesse\Projects;C:\Tribon\M3\bin\python'`)

I do not think you will be able to use Orange at the same time as Vitesse at least without hassle. You might try temporarily renaming the  `C:\Tribon\M3\Vitesse` directory to e.g. `C:\Tribon\M3\Vitesse_` and try rerunning the Orange installer.
