### ISSUE TITLE
Saving Workflow as SVG for documentation

### ISSUE THREAD

**Issue by simonaubertbd** [biolab/orange3#6777]
**What's your use case?**
I would like to export the workfow as a SVG file for documentation. Screenshots are too often bad quality and not resizeable. (this is common feature on etl/dataprep software)

**What's your proposed solution?**
A button/entry menu to export all the workflow in SVG.

**Are there any alternative solutions?**
Screenshot and then inkscape but that's ugly.

**Comment by janezd** [comment]
@ales-erjavec said this is doable and not too complicated, so somebody (probably he) will do it ... eventually.
