### ISSUE TITLE
More detailed Workflow Info

### ISSUE THREAD

**Issue by simonaubertbd** [biolab/orange3#6778]
**What's your use case?**
Having a description is cool but it's not easy to build a monitoring of your assets when all the information are in the same field.

**What's your proposed solution?**
Different fields such as :
-author(s)
-organisation
-version
-link to some documentation

**Are there any alternative solutions?**
making a template for documentation

**Comment by janezd** [comment]
We discussed this internally: there is no universal set of fields. You will have to use your own template.
