### ISSUE TITLE
Delete/rename features

### ISSUE THREAD

**Issue by alaindebecker** [biolab/orange3#6787]
### What's your use case?
I need to change the name of some features and remove some. A frequent question for which I could not find a specialised widget.

My data is a _Qty_ by _Date_ which needed to be grouped by week. Using a **Formula** I created  a  _week_ number  followed a **Group by** to get 3 columns: _week_, _Date-Max. value_ and _Qty-Sum_. For some reason, I had to revert it to the columns of the original table: _Qty_, _Date_. 

As I did not found any widget to do this, I used the following workaround: 

1) A  **Formula** to create _Qty_ :=_Qty-Sum_ and _Date_:=_Date-Max. value_;
2) A **Select Columns** to remove the three unwanted column. 

Two steps (and a lot of reasoning and testing the first time) just to rearrange the column labels. 

### What's your proposed solution?

I think you could adapt the **Formula** widget so as to only keep wanted columns.

For example:
- Copying by default all the existing features in the report frame ; 
- Each of them with a tick box, to say if they had to apear or not in the output ;
- The current _remove_ button can be deleted, because the logic will become unmanagable with the number of columns.
- And to nicely remain compatible with usage in previous versions, replace the said _remove_ button by a check box labeled "Keep all features" which will be checked by default.

### Are there any alternative solutions?

- A totaly new widget.
- Adapting the **Select Column** widget.
- Implement the functionality on the **Formula** with a different UI.

Although adpting the **Formula** (which after all is a widget to specify the features) seems the more intuitive from a user point of view.

**Comment by janezd** [comment]
We would prefer not to add new widgets for functionality that is easily achieved by others. Orange already has a large number of them, which is - to our experience - scary for many users. Besides, the more widgets we have, the more difficult it is for the user to find the widgets they need. The may even write issues in which they would ask for widgets that already exist. :)

Your suggestion would make the already complex Formula widget even more complicated by adding new tick boxes, while not offering anything that cannot be done with Select Columns (and *Edit Domain for renaming columns*).
