### ISSUE TITLE
A friendlier log display

### ISSUE THREAD

**Issue by simonaubertbd** [biolab/orange3#6797]
**What's your use case?**
Reading the log, it's not easy to have immediatly the info I look for.

**What's your proposed solution?**
some formatting, especially indentation, colors (like bold red when error)... link to the tool, etc
Maybe having the date time in a separate column

**Are there any alternative solutions?**
Probably?

As a comparison :
 Orange Data Mining
![image](https://github.com/biolab/orange3/assets/46959192/51ca19c9-5ef9-42b1-8f34-750b7370ab13)

Alteryx
![image](https://github.com/biolab/orange3/assets/46959192/6b2f409e-0952-429d-95a0-cd5bd09f5a87)

Best regards,

Simon

**Comment by janezd** [comment]
This is not the same thing. Orange shows information like that in Alteryx log in the status bar of the widgets. There, it is formatted, has a color-coded icon etc.

Stack trace from Orange is a result of a bug; it is not meant to happen, and when it does, it is meant to be read by developers, which need a stack trace (there is not "tool", but a chain of function calls ...). Colors are pointless: this is always an error. Indentation is such as set by Python. Date and time are redundant.
