### ISSUE TITLE
? (upper border) not working on most windows

### ISSUE THREAD

**Issue by simonaubertbd** [biolab/orange3#6798]
**What's wrong?**
When I click on the ? icon on the upper border, nothing happens. Here on Preferences but same on the widgets I tested
![image](https://github.com/biolab/orange3/assets/46959192/b6dcc6c7-6257-4de5-98f5-7f3aa4090bc5)

**How can we reproduce the problem?** 
By just clicking on the icon

**What's your environment?**

- Operating system: Windows 10
- Orange version: 3.36.2
- How you installed Orange: windows installer

**Comment by markotoplak** [comment]
Thanks!

**Comment by janezd** [comment]
We will disappear it. :)
