### ISSUE TITLE
Feature request: Way to convert Pandas dataframe to Table object

### ISSUE THREAD

**Issue by fccoelho** [biolab/orange3#68]
Hi, Pandas is quickly becoming a standard in data analysis in the scientific Python community. So I think you should consider adding support for converting data in a pandas Dataframe to an Orange table object.

The other day I had a very complex csv which I wanted to read into Orange. The available CSV Importer couldn't read it but pandas, or a straight python script loaded without problems. So I added a Python Script block to my project. But then I got stuck because I couldn't find a way to transform the imported table into an Orange Table Object.

Perhaps better documentation on how to buiid a Table from raw data would already help a lot.

**Comment by mfitzp** [comment]
I'm wondering if there would be potential for Pandas DataFrames (or a subclass) to be used as the internal data object for Orange? If there is a move towards numpy anyway, they work very nicely together + you get a lot of functionality for free.

**Comment by janezd** [comment]
We have seriously considered using Pandas instead of pure numpy, but we would have to add to many things on our own, so we decided it would be easier to start from numpy.

However, Orange is no longer limited to data in a single format. It can already use data which is stored in SQL and only moves it to local memory when needed (e.g. it would compute naive bayesian classifier on the database, without moving the data to the client). Adding Pandas DataFrames should be even simpler. It is not on any short-term list - our priority now is to port most of Orange 2 first - but we can do it in the future.

**Comment by mfitzp** [comment]
@janezd That's great to hear. I can understand the thinking - Pandas does bring it's own restrictions as a base format (not least of all only allowing up to 2D data - which is limiting for image data, etc. depending on your plans for Orange). The restriction of data formats in Orange has previously prevented me from implementing some tools... time to take another look!

**Comment by janezd** [comment]
Check this: http://docs.orange.biolab.si/3/modules/data.table.html. The data is still 2d, but it can be, for instance, a view into a 3d array. It is much more flexible now.

**Comment by jamartinh** [comment]
```
def construct_domain(df):
    columns = OrderedDict(df.dtypes)

    def create_variable(col):
        if col[1].__str__().startswith('float'):
            return Orange.data.ContinuousVariable(col[0])
        if col[1].__str__().startswith('int') and len(df[col[0]].unique()) > 50:
            return Orange.data.ContinuousVariable(col[0])
        if col[1].__str__().startswith('date'):
            df[col[0]] = df[col[0]].values.astype(np.str)
        if col[1].__str__() == 'object':
            df[col[0]] = df[col[0]].astype(type(""))

        return Orange.data.DiscreteVariable(col[0], values = df[col[0]].unique().tolist())

    return Orange.data.Domain(list(map(create_variable, columns.items())))
```

```
def pandas_to_orange(df):
    domain = construct_domain(df)
    orange_table = Orange.data.Table.from_list(domain = domain, rows = df.values.tolist())
    return orange_table
```

**Comment by janezd** [comment]
Can you create a pull request with this? This makes it easier to follow the code and its potential changes.

**Comment by jamartinh** [comment]
There's a new add on available, Orange3-spark.  

This add on include widgets to convert between Spark<--->Pandas<-->Orange

Perhaps the Pandas<--->Orange widgets can be included in the Default orange distro?

**Comment by kernc** [comment]
@jamartinh Could be, but can you please explain how they would be used?

**Comment by sahmed95** [comment]
Hi, I have worked with Pandas and numpy for data analysis projects and have a good grasp on them. I came across Orange as an alternative to WEKA in favour of python based data analysis and visualisation. I would like to try this as I am interested in GSoc 2016 and I found this issue in your ideas page.

To start, should I make a function that converts orange.data.table to pandas.DataFrame object and a pandas.DataFrame to orange.data.table like @jamartinh suggested and open a PR?

**Comment by ajdapretnar** [comment]
@kernc Can we close the issue since implementing Pandas dataframe is our GSoC project? Or we do it after the project is done?

**Comment by kernc** [comment]
Is the issue fixed? :smile_cat:

**Comment by ajdapretnar** [comment]
It's a feature request, not an issue per se. Thus yes, feature request is accepted and is in the process of implementation.
Also see this: https://github.com/biolab/orange3/pull/796

**Comment by sstanovnik** [comment]
With the new pandas implementation (#1347) , there's a `Table.from_dataframe` method that resolves this issue.
