### ISSUE TITLE
 Vrirus detected in installation file for Windows: Gen:Variant.Cerbu.123329 / cannot install software.

### ISSUE THREAD

**Issue by limtileong** [biolab/orange3#6824]
While installing orange for windows, my BIDDEFENDER Anti-virus app detected a virus 

The file C:\Users\limti\anaconda3\pkgs\expat-2.6.2-h63175ca_0\Library\bin\expat.dll has been detected as infected with Gen:Variant.Cerbu.123329 and Bitdefender could not clean this item. A device restart is required to finalize the cleaning process.

Creating an new conda env in "C:\Users\limti\AppData\Local\Programs\Orange"
Output folder: C:\Users\limti\AppData\Local\Temp\nsb2B10.tmp\Orange-installer-data\conda-pkgs
Extract: _py-xgboost-mutex-2.0-cpu_0.tar.bz2
Extract: anyio-4.3.0-pyhd8ed1ab_0.conda
Extract: anyqt-0.2.0-pyh6c4a22f_0.tar.bz2
Extract: asttokens-2.4.1-pyhd8ed1ab_0.conda
Extract: attrs-23.2.0-pyh71513ae_0.conda
Extract: backports-1.0-pyhd8ed1ab_3.conda
Extract: backports.tarfile-1.0.0-pyhd8ed1ab_1.conda
Extract: baycomp-1.0.2-py_1.tar.bz2
Extract: blas-2.120-openblas.conda
Extract: blas-devel-3.9.0-20_win64_openblas.conda
Extract: bottleneck-1.3.8-py311h59ca53f_0.conda
Extract: brotli-1.1.0-hcfcfb64_1.conda
Extract: brotli-bin-1.1.0-hcfcfb64_1.conda
Extract: brotli-python-1.1.0-py311h12c1d0e_1.conda
Extract: bzip2-1.0.8-hcfcfb64_5.conda
Extract: ca-certificates-2024.2.2-h56e8100_0.conda
Extract: cairo-1.18.0-h1fef639_0.conda
Extract: catboost-1.2.5-py311h1ea47a8_0.conda
Extract: cattrs-23.2.3-pyhd8ed1ab_0.conda
Extract: certifi-2024.2.2-pyhd8ed1ab_0.conda
Extract: chardet-5.2.0-py311h1ea47a8_1.conda
Extract: charset-normalizer-3.3.2-pyhd8ed1ab_0.conda
Extract: colorama-0.4.6-pyhd8ed1ab_0.tar.bz2
Extract: comm-0.2.2-pyhd8ed1ab_0.conda
Extract: commonmark-0.9.1-py_0.tar.bz2
Extract: conda-spec.txt
Extract: contourpy-1.2.1-py311h005e61a_0.conda
Extract: cycler-0.12.1-pyhd8ed1ab_0.conda
Extract: debugpy-1.8.1-py311h12c1d0e_0.conda
Extract: decorator-5.1.1-pyhd8ed1ab_0.tar.bz2
Extract: dictdiffer-0.9.0-pyhd8ed1ab_0.tar.bz2
Extract: docutils-0.21.2-pyhd8ed1ab_0.conda
Extract: et_xmlfile-1.1.0-pyhd8ed1ab_0.conda
Extract: exceptiongroup-1.2.0-pyhd8ed1ab_2.conda
Extract: executing-2.0.1-pyhd8ed1ab_0.conda
Extract: expat-2.6.2-h63175ca_0.conda
Extract: font-ttf-dejavu-sans-mono-2.37-hab24e00_0.tar.bz2
Extract: font-ttf-inconsolata-3.000-h77eed37_0.tar.bz2
Extract: font-ttf-source-code-pro-2.038-h77eed37_0.tar.bz2
Extract: font-ttf-ubuntu-0.83-h77eed37_2.conda
Extract: fontconfig-2.14.2-hbde0cde_0.conda
Extract: fonts-conda-ecosystem-1-0.tar.bz2
Extract: fonts-conda-forge-1-0.tar.bz2
Extract: fonttools-4.52.4-py311he736701_0.conda
Extract: freetype-2.12.1-hdaf720e_2.conda
Extract: fribidi-1.0.10-h8d14728_0.tar.bz2
Extract: future-1.0.0-pyhd8ed1ab_0.conda
Extract: getopt-win32-0.1-hcfcfb64_1.conda
Extract: gettext-0.22.5-h5728263_2.conda
Extract: gettext-tools-0.22.5-h7d00a51_2.conda
Extract: glib-2.80.2-h0df6a38_0.conda
Extract: glib-tools-2.80.2-h2f9d560_0.conda
Extract: graphite2-1.3.13-h63175ca_1003.conda
Extract: graphviz-11.0.0-h09e431a_0.conda
Extract: gst-plugins-base-1.22.9-h001b923_1.conda
Extract: gstreamer-1.22.9-hb4038d2_1.conda
Extract: gts-0.7.6-h6b5321d_4.conda
Extract: h11-0.14.0-pyhd8ed1ab_0.tar.bz2
Extract: h2-4.1.0-pyhd8ed1ab_0.tar.bz2
Extract: harfbuzz-8.5.0-h81778c3_0.conda
Extract: hpack-4.0.0-pyh9f0ad1d_0.tar.bz2
Extract: httpcore-1.0.5-pyhd8ed1ab_0.conda
Extract: httpx-0.27.0-pyhd8ed1ab_0.conda
Extract: hyperframe-6.0.1-pyhd8ed1ab_0.tar.bz2
Extract: icu-73.2-h63175ca_0.conda
Extract: idna-3.7-pyhd8ed1ab_0.conda
Extract: importlib-metadata-7.1.0-pyha770c72_0.conda
Extract: importlib_metadata-7.1.0-hd8ed1ab_0.conda
Extract: importlib_resources-6.4.0-pyhd8ed1ab_0.conda
Extract: install.bat
Extract: ipykernel-6.29.3-pyha63f2e9_0.conda
Extract: ipython-8.24.0-pyh7428d3b_0.conda
Extract: itsdangerous-2.2.0-pyhd8ed1ab_0.conda
Extract: jaraco.classes-3.4.0-pyhd8ed1ab_1.conda
Extract: jaraco.context-5.3.0-pyhd8ed1ab_1.conda
Extract: jaraco.functools-4.0.0-pyhd8ed1ab_0.conda
Extract: jedi-0.19.1-pyhd8ed1ab_0.conda
Extract: joblib-1.4.2-pyhd8ed1ab_0.conda
Extract: jupyter_client-8.6.2-pyhd8ed1ab_0.conda
Extract: jupyter_core-5.7.2-py311h1ea47a8_0.conda
Extract: keyring-25.2.1-pyh7428d3b_0.conda
Extract: keyrings.alt-5.0.1-pyhd8ed1ab_1.conda
Extract: kiwisolver-1.4.5-py311h005e61a_1.conda
Extract: krb5-1.21.2-heb0366b_0.conda
Extract: lcms2-2.16-h67d730c_0.conda
Extract: lerc-4.0.0-h63175ca_0.tar.bz2
Extract: libasprintf-0.22.5-h5728263_2.conda
Extract: libasprintf-devel-0.22.5-h5728263_2.conda
Extract: libblas-3.9.0-20_win64_openblas.conda
Extract: libbrotlicommon-1.1.0-hcfcfb64_1.conda
Extract: libbrotlidec-1.1.0-hcfcfb64_1.conda
Extract: libbrotlienc-1.1.0-hcfcfb64_1.conda
Extract: libcblas-3.9.0-20_win64_openblas.conda
Extract: libclang13-18.1.6-default_hf64faad_0.conda
Extract: libdeflate-1.20-hcfcfb64_0.conda
Extract: libexpat-2.6.2-h63175ca_0.conda
Extract: libffi-3.4.2-h8ffe710_5.tar.bz2
Extract: libflang-5.0.0-h6538335_20180525.tar.bz2
Extract: libgd-2.3.3-h312136b_9.conda
Extract: libgettextpo-0.22.5-h5728263_2.conda
Extract: libgettextpo-devel-0.22.5-h5728263_2.conda
Extract: libglib-2.80.2-h0df6a38_0.conda
Extract: libiconv-1.17-hcfcfb64_2.conda
Extract: libintl-0.22.5-h5728263_2.conda
Extract: libintl-devel-0.22.5-h5728263_2.conda
Extract: libjpeg-turbo-3.0.0-hcfcfb64_1.conda
Extract: liblapack-3.9.0-20_win64_openblas.conda
Extract: liblapacke-3.9.0-20_win64_openblas.conda
Extract: libogg-1.3.4-h8ffe710_1.tar.bz2
Extract: libopenblas-0.3.25-pthreads_hc140b1d_0.conda
Extract: libpng-1.6.43-h19919ed_0.conda
Extract: libsodium-1.0.18-h8d14728_1.tar.bz2
Extract: libsqlite-3.45.3-hcfcfb64_0.conda
Extract: libtiff-4.6.0-hddb2be6_3.conda
Extract: libvorbis-1.3.7-h0e60522_0.tar.bz2
Extract: libwebp-1.4.0-h2466b09_0.conda
Extract: libwebp-base-1.4.0-hcfcfb64_0.conda
Extract: libxcb-1.15-hcd874cb_0.conda
Extract: libxgboost-2.0.3-cpu_hb3f76d0_4.conda
Extract: libzlib-1.2.13-h2466b09_6.conda
Extract: llvm-meta-5.0.0-0.tar.bz2
Extract: m2w64-gcc-libgfortran-5.3.0-6.tar.bz2
Extract: m2w64-gcc-libs-5.3.0-7.tar.bz2
Extract: m2w64-gcc-libs-core-5.3.0-7.tar.bz2
Extract: m2w64-gmp-6.1.0-2.tar.bz2
Extract: m2w64-libwinpthread-git-5.0.0.4634.697f757-2.tar.bz2
Extract: matplotlib-base-3.8.4-py311h9b31f6e_2.conda
Extract: matplotlib-inline-0.1.7-pyhd8ed1ab_0.conda
Extract: more-itertools-10.2.0-pyhd8ed1ab_0.conda
Extract: msys2-conda-epoch-20160418-1.tar.bz2
Extract: munkres-1.1.4-pyh9f0ad1d_0.tar.bz2
Extract: nest-asyncio-1.6.0-pyhd8ed1ab_0.conda
Extract: networkx-3.3-pyhd8ed1ab_1.conda
Extract: numpy-1.24.4-py311h0b4df5a_0.conda
Extract: openblas-0.3.25-pthreads_h3721920_0.conda
Extract: openjpeg-2.5.2-h3d672ee_0.conda
Extract: openmp-5.0.0-vc14_1.tar.bz2
Extract: openpyxl-3.1.2-py311ha68e1ae_1.conda
Extract: openssl-3.3.0-h2466b09_3.conda
Extract: opentsne-1.0.1-py311h9b10771_2.conda
Extract: orange-canvas-core-0.2.1-pyhd8ed1ab_0.conda
Extract: orange-widget-base-4.24.0-pyhd8ed1ab_0.conda
Extract: orange3-3.37.0-py311hbc92ba2_0.conda
Extract: packaging-24.0-pyhd8ed1ab_0.conda
Extract: pandas-1.5.3-py311hf63dbb6_1.conda
Extract: pango-1.52.2-h07c897b_0.conda
Extract: parso-0.8.4-pyhd8ed1ab_0.conda
Extract: pcre2-10.43-h17e33f8_0.conda
Extract: pickleshare-0.7.5-py_1003.tar.bz2
Extract: pillow-10.3.0-py311h6819b35_0.conda
Extract: pip-24.0-pyhd8ed1ab_0.conda
Extract: pixman-0.43.4-h63175ca_0.conda
Extract: platformdirs-4.2.2-pyhd8ed1ab_0.conda
Extract: plotly-5.22.0-pyhd8ed1ab_0.conda
Extract: ply-3.11-pyhd8ed1ab_2.conda
Extract: pooch-1.8.1-pyhd8ed1ab_0.conda
Extract: prompt-toolkit-3.0.42-pyha770c72_0.conda
Extract: psutil-5.9.8-py311ha68e1ae_0.conda
Extract: pthread-stubs-0.4-hcd874cb_1001.tar.bz2
Extract: pure_eval-0.2.2-pyhd8ed1ab_0.tar.bz2
Extract: py-xgboost-2.0.3-cpu_pyh995e691_4.conda
Extract: pygments-2.18.0-pyhd8ed1ab_0.conda
Extract: pyparsing-3.1.2-pyhd8ed1ab_0.conda
Extract: pyqt-5.15.9-py311h125bc19_5.conda
Extract: pyqt5-sip-12.12.2-py311h12c1d0e_5.conda
Extract: pyqtgraph-0.13.7-pyhd8ed1ab_0.conda
Extract: pyqtwebengine-5.15.9-py311h5a77453_5.conda
Extract: pysocks-1.7.1-pyh0701188_6.tar.bz2
Extract: python-3.11.8-h2628c8c_0_cpython.conda
Extract: python-dateutil-2.9.0-pyhd8ed1ab_0.conda
Extract: python-graphviz-0.20.3-pyh717bed2_0.conda
Extract: python-louvain-0.16-pyhd8ed1ab_0.conda
Extract: python_abi-3.11-4_cp311.conda
Extract: pytz-2024.1-pyhd8ed1ab_0.conda
Extract: pywin32-306-py311h12c1d0e_2.conda
Extract: pywin32-ctypes-0.2.2-py311h1ea47a8_1.conda
Extract: pyyaml-6.0.1-py311ha68e1ae_1.conda
Extract: pyzmq-26.0.3-py311h484c95c_0.conda
Extract: qasync-0.27.1-pyh9208f05_0.conda
Extract: qt-main-5.15.8-h9e85ed6_20.conda
Extract: qt-webengine-5.15.8-h4bf5c4e_4.tar.bz2
Extract: qtconsole-5.5.2-pyhd8ed1ab_0.conda
Extract: qtconsole-base-5.5.2-pyha770c72_0.conda
Extract: qtpy-2.4.1-pyhd8ed1ab_0.conda
Extract: requests-2.32.3-pyhd8ed1ab_0.conda
Extract: requests-cache-1.2.0-pyhd8ed1ab_1.conda
Extract: scikit-learn-1.3.2-py311h142b183_2.conda
Extract: scipy-1.10.1-py311h37ff6ca_3.conda
Extract: serverfiles-0.3.0-py_0.tar.bz2
Extract: setuptools-70.0.0-pyhd8ed1ab_0.conda
Extract: sip-6.7.12-py311h12c1d0e_0.conda
Extract: sitecustomize.py
Extract: six-1.16.0-pyh6c4a22f_0.tar.bz2
Extract: sniffio-1.3.1-pyhd8ed1ab_0.conda
Extract: stack_data-0.6.2-pyhd8ed1ab_0.conda
Extract: tenacity-8.3.0-pyhd8ed1ab_0.conda
Extract: threadpoolctl-3.5.0-pyhc1e730c_0.conda
Extract: tk-8.6.13-h5226925_1.conda
Extract: toml-0.10.2-pyhd8ed1ab_0.tar.bz2
Extract: tomli-2.0.1-pyhd8ed1ab_0.tar.bz2
Extract: tornado-6.4-py311ha68e1ae_0.conda
Extract: traitlets-5.14.3-pyhd8ed1ab_0.conda
Extract: typing-extensions-4.11.0-hd8ed1ab_0.conda
Extract: typing_extensions-4.11.0-pyha770c72_0.conda
Extract: tzdata-2024a-h0c530f3_0.conda
Extract: ucrt-10.0.22621.0-h57928b3_0.tar.bz2
Extract: ujson-5.10.0-py311hda3d55a_0.conda
Extract: url-normalize-1.4.3-pyhd8ed1ab_0.tar.bz2
Extract: urllib3-2.2.1-pyhd8ed1ab_0.conda
Extract: vc-14.3-ha32ba9b_20.conda
Extract: vc14_runtime-14.38.33135-h835141b_20.conda
Extract: vs2015_runtime-14.38.33135-h22015db_20.conda
Extract: wcwidth-0.2.13-pyhd8ed1ab_0.conda
Extract: wheel-0.43.0-pyhd8ed1ab_1.conda
Extract: win_inet_pton-1.1.0-pyhd8ed1ab_6.tar.bz2
Extract: xgboost-2.0.3-cpu_pyhb8f9a19_4.conda
Extract: xlrd-2.0.1-pyhd8ed1ab_3.tar.bz2
Extract: xlsxwriter-3.1.9-pyhd8ed1ab_0.conda
Extract: xorg-kbproto-1.0.7-hcd874cb_1002.tar.bz2
Extract: xorg-libice-1.1.1-hcd874cb_0.conda
Extract: xorg-libsm-1.2.4-hcd874cb_0.conda
Extract: xorg-libx11-1.8.9-hefa74cf_0.conda
Extract: xorg-libxau-1.0.11-hcd874cb_0.conda
Extract: xorg-libxdmcp-1.1.3-hcd874cb_0.tar.bz2
Extract: xorg-libxext-1.3.4-hcd874cb_2.conda
Extract: xorg-libxpm-3.5.17-hcd874cb_0.conda
Extract: xorg-libxt-1.3.0-hcd874cb_1.conda
Extract: xorg-xextproto-7.3.0-hcd874cb_1003.conda
Extract: xorg-xproto-7.0.31-hcd874cb_1007.tar.bz2
Extract: xz-5.2.6-h8d14728_0.tar.bz2
Extract: yaml-0.2.5-h8ffe710_2.tar.bz2
Extract: zeromq-4.3.5-he1f189c_4.conda
Extract: zipp-3.17.0-pyhd8ed1ab_0.conda
Extract: zlib-1.2.13-h2466b09_6.conda
Extract: zstd-1.5.6-h0ea2cb4_0.conda
Output folder: C:\Users\limti\AppData\Local\Temp\nsb2B10.tmp\Orange-installer-data\conda-pkgs
Installing packages (this might take a while)
Executing: cmd.exe /c install.bat "C:\Users\limti\AppData\Local\Programs\Orange" "C:\Users\limti\anaconda3\condabin\conda.bat"
Creating a conda env in "C:\Users\limti\AppData\Local\Programs\Orange"

Downloading and Extracting Packages
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
           |   0% ########## | 100% 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
ERROR conda.core.link:_execute(700): An error occurred while installing package '<unknown>::libexpat-2.6.2-h63175ca_0'.
Rolling back transaction: ...working... done

[Errno 13] Permission denied: 'C:\\Users\\limti\\anaconda3\\pkgs\\libexpat-2.6.2-h63175ca_0\\Library\\bin\\libexpat.dll'
()
"conda" command exited with 1. Cannot continue.

**What's wrong?**

**How can we reproduce the problem?** 

**What's your environment?**

- Operating system:
- Orange version:
- How you installed Orange:

**Comment by ales-erjavec** [comment]
> The file C:\Users\limti\anaconda3\pkgs\expat-2.6.2-h63175ca_0\Library\bin\expat.dll has been detected as infected with Gen:Variant.Cerbu.123329 and Bitdefender could not clean this item. A device restart is required to finalize the cleaning process.

The `expat-2.6.2-h63175ca_0` (sha256:f5a13d4bc591a4dc210954f492dd59a0ecf9b9d2ab28bf2ece755ca8f69ec1b4)  is from [conda-forge](https://anaconda.org/conda-forge/expat/files) The `Library/bin/expat.dll`(sha256:e3c28b818c84b13da7f325f6588a6e9cffe8d25b7e2f9e3fbf75bd42ea058108) itself does not appear to be flagged as malicious (https://www.virustotal.com/gui/file/e3c28b818c84b13da7f325f6588a6e9cffe8d25b7e2f9e3fbf75bd42ea058108/detection).

I am guessing this is a false positive.
