### ISSUE TITLE
Problem when import Table module

### ISSUE THREAD

**Issue by Isaamarod** [biolab/orange3#6847]
After install Orange thorught pip when try to import _**from Orange.data import Table**_   it launchs the following error:
```ModuleNotFoundError: No module named 'pandas.core.arrays.sparse.dtype'```

File /usr/local/lib64/python3.9/site-packages/Orange/__init__.py:4
      1 # This module is a mixture of imports and code, so we allow import anywhere
      2 # pylint: disable=wrong-import-position,wrong-import-order
----> 4 from Orange import data
      6 from .misc.lazy_module import _LazyModule
      7 from .misc.datasets import _DatasetInfo

File /usr/local/lib64/python3.9/site-packages/Orange/data/__init__.py:12
     10 from .io import *
     11 from .filter import *
---> 12 from .pandas_compat import *
     13 from .aggregate import *

File /usr/local/lib64/python3.9/site-packages/Orange/data/pandas_compat.py:9
      7 import pandas as pd
      8 from pandas.core.arrays import SparseArray
----> 9 from pandas.core.arrays.sparse.dtype import SparseDtype
     10 from pandas.api.types import (
     11     is_categorical_dtype, is_object_dtype,
     12     is_datetime64_any_dtype, is_numeric_dtype, is_integer_dtype
     13 )
     15 from Orange.data import (
     16     Table, Domain, DiscreteVariable, StringVariable, TimeVariable,
     17     ContinuousVariable,
     18 )

**Comment by markotoplak** [comment]
Could you give more details about how you installed it? System-wide, virtual environment, user packages? What is your platform?

I just tried pip-installing into a fresh virtual python 3.10 environment on Linux and did not get the same issue.

Can you do `pip freeze` and show us the output? I guess some packages have conflicts...

**Comment by markotoplak** [comment]
Here is mine `pip freeze`:

```
anyio==4.4.0
AnyQt==0.2.0
asttokens==2.4.1
attrs==23.2.0
backports.tarfile==1.2.0
baycomp==1.0.3
Bottleneck==1.4.0
catboost==1.2.5
cattrs==23.2.3
certifi==2024.7.4
cffi==1.16.0
chardet==5.2.0
charset-normalizer==3.3.2
comm==0.2.2
commonmark==0.9.1
contourpy==1.2.1
cryptography==42.0.8
cycler==0.12.1
debugpy==1.8.2
decorator==5.1.1
dictdiffer==0.9.0
docutils==0.21.2
et-xmlfile==1.1.0
exceptiongroup==1.2.1
executing==2.0.1
fonttools==4.53.0
graphviz==0.20.3
h11==0.14.0
httpcore==1.0.5
httpx==0.27.0
idna==3.7
importlib_metadata==8.0.0
ipykernel==6.29.5
ipython==8.26.0
jaraco.classes==3.4.0
jaraco.context==5.3.0
jaraco.functools==4.0.1
jedi==0.19.1
jeepney==0.8.0
joblib==1.4.2
jupyter_client==8.6.2
jupyter_core==5.7.2
keyring==25.2.1
keyrings.alt==5.0.1
kiwisolver==1.4.5
matplotlib==3.9.1
matplotlib-inline==0.1.7
more-itertools==10.3.0
nest-asyncio==1.6.0
networkx==3.3
numpy==1.26.4
nvidia-nccl-cu12==2.22.3
openpyxl==3.1.5
openTSNE==1.0.1
orange-canvas-core==0.2.1
orange-widget-base==4.24.0
Orange3==3.37.0
packaging==24.1
pandas==2.2.2
parso==0.8.4
pexpect==4.9.0
pillow==10.4.0
pkg_resources==0.0.0
platformdirs==4.2.2
plotly==5.22.0
prompt_toolkit==3.0.47
psutil==6.0.0
ptyprocess==0.7.0
pure-eval==0.2.2
pycparser==2.22
Pygments==2.18.0
pyparsing==3.1.2
PyQt5==5.15.10
PyQt5-Qt5==5.15.14
PyQt5-sip==12.13.0
pyqtgraph==0.13.7
python-dateutil==2.9.0.post0
python-louvain==0.16
pytz==2024.1
PyYAML==6.0.1
pyzmq==26.0.3
qasync==0.27.1
qtconsole==5.5.2
QtPy==2.4.1
requests==2.32.3
requests-cache==1.2.1
scikit-learn==1.4.2
scipy==1.14.0
SecretStorage==3.3.3
serverfiles==0.3.1
six==1.16.0
sniffio==1.3.1
stack-data==0.6.3
tenacity==8.4.2
threadpoolctl==3.5.0
tornado==6.4.1
traitlets==5.14.3
typing_extensions==4.12.2
tzdata==2024.1
url-normalize==1.4.3
urllib3==2.2.2
wcwidth==0.2.13
xgboost==2.1.0
xlrd==2.0.1
XlsxWriter==3.2.0
zipp==3.19.2
```

**Comment by Isaamarod** [comment]
Yes, of course:


- Environment Jupyter Notebook in a Linux server
- Python version:  3.9.19 
- Installation command:
!pip install orange3
- Freeze: 
alembic==1.11.1
anyio==3.7.1
AnyQt==0.2.0
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asttokens==2.2.1
async-generator==1.10
attrs==23.1.0
backcall==0.2.0
baycomp==1.0.3
beautifulsoup4==4.12.2
bleach==6.0.0
Bottleneck==1.3.7
cattrs==23.1.2
certifi==2023.5.7
certipy==0.1.3
cffi==1.15.1
chardet==5.2.0
charset-normalizer==3.2.0
cloudpickle==3.0.0
comm==0.1.3
commonmark==0.9.1
contourpy==1.1.0
cryptography==41.0.2
cycler==0.11.0
dbus-python==1.2.18
debugpy==1.6.7
decorator==5.1.1
defusedxml==0.7.1
dictdiffer==0.9.0
distro==1.5.0
docutils==0.20.1
et-xmlfile==1.1.0
exceptiongroup==1.1.2
executing==1.2.0
fastjsonschema==2.17.1
fonttools==4.42.1
fqdn==1.5.1
gpg==1.15.1
greenlet==2.0.2
h11==0.14.0
httpcore==0.17.3
httpx==0.24.1
idna==3.4
imbalanced-learn==0.12.3
imblearn==0.0
importlib-metadata==6.8.0
importlib-resources==6.0.1
ipykernel==6.24.0
ipython==8.14.0
ipython-genutils==0.2.0
isoduration==20.11.0
jaraco.classes==3.3.0
jedi==0.18.2
jeepney==0.8.0
Jinja2==3.1.2
joblib==1.3.2
jsonpointer==2.4
jsonschema==4.18.0
jsonschema-specifications==2023.6.1
jupyter-events==0.6.3
jupyter-telemetry==0.1.0
jupyter_client==8.3.0
jupyter_core==5.3.1
jupyter_server==2.7.0
jupyter_server_terminals==0.4.4
jupyterhub==4.0.1
jupyterlab-pygments==0.2.2
keyring==24.2.0
keyrings.alt==5.0.0
kiwisolver==1.4.5
libcomps==0.1.18
llvmlite==0.43.0
Mako==1.2.4
MarkupSafe==2.1.3
matplotlib==3.7.2
matplotlib-inline==0.1.6
mistune==3.0.1
more-itertools==10.1.0
nbclassic==1.0.0
nbclient==0.8.0
nbconvert==7.6.0
nbformat==5.9.1
nest-asyncio==1.5.6
networkx==3.1
nftables==0.1
notebook==6.5.4
notebook_shim==0.2.3
numba==0.60.0
numpy==1.25.2
oauthlib==3.2.2
openpyxl==3.1.2
openTSNE==1.0.0
**orange-canvas-core==0.1.32
orange-widget-base==4.21.0
Orange3==3.35.0**
overrides==7.3.1
packaging==23.1
pamela==1.1.0
pandas==2.2.2
pandocfilters==1.5.0
parso==0.8.3
patsy==0.5.6
pexpect==4.8.0
pickleshare==0.7.5
Pillow==10.0.0
platformdirs==3.8.1
prometheus-client==0.17.1
prompt-toolkit==3.0.39
psutil==5.9.5
ptyprocess==0.7.0
pure-eval==0.2.2
pyarrow==16.1.0
pycairo==1.20.1
pycparser==2.21
Pygments==2.15.1
PyGObject==3.40.1
pyOpenSSL==23.2.0
pyparsing==3.0.9
PyQt5==5.15.9
PyQt5-Qt5==5.15.2
PyQt5-sip==12.12.2
pyqtgraph==0.13.3
PyQtWebEngine==5.15.6
PyQtWebEngine-Qt5==5.15.2
python-dateutil==2.8.2
python-json-logger==2.0.7
python-louvain==0.16
pytz==2023.3.post1
PyYAML==6.0
pyzmq==25.1.0
qasync==0.24.0
qtconsole==5.4.4
QtPy==2.4.0
referencing==0.29.1
requests==2.31.0
requests-cache==1.1.0
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rpds-py==0.8.10
rpm==4.16.1.3
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
scikit-learn==1.1.3
scipy==1.11.2
seaborn==0.13.2
SecretStorage==3.3.3
selinux==3.5
Send2Trash==1.8.2
sepolicy==3.5
serverfiles==0.3.1
setools==4.4.1
shap==0.45.1
six==1.15.0
slicer==0.0.8
sniffio==1.3.0
soupsieve==2.4.1
SQLAlchemy==2.0.18
stack-data==0.6.2
statsmodels==0.14.2
sudospawner==0.5.2
systemd-python==234
terminado==0.17.1
threadpoolctl==3.2.0
tinycss2==1.2.1
tornado==6.3.2
tqdm==4.66.4
traitlets==5.9.0
typing_extensions==4.7.1
tzdata==2023.3
uri-template==1.3.0
url-normalize==1.4.3
urllib3==2.0.3
wcwidth==0.2.6
webcolors==1.13
webencodings==0.5.1
websocket-client==1.6.1
xgboost==2.0.3
xlrd==2.0.1
XlsxWriter==3.1.2
zipp==3.16.0

- Error:
```
from Orange.data import Table
from Orange.preprocess import Impute, Model
from Orange.modelling import TreeLearner
df = pd.DataFrame([["a", "x"],
                   [np.nan, "y"],
                   ["a", np.nan]])
data = Table(df)
imputer = Impute(method=Model(TreeLearner()))
impute_heart = imputer(data)

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[6], line 1
----> 1 from Orange.data import Table
      2 from Orange.preprocess import Impute, Model
      3 from Orange.modelling import TreeLearner

File /usr/local/lib64/python3.9/site-packages/Orange/__init__.py:4
      1 # This module is a mixture of imports and code, so we allow import anywhere
      2 # pylint: disable=wrong-import-position,wrong-import-order
----> 4 from Orange import data
      6 from .misc.lazy_module import _LazyModule
      7 from .misc.datasets import _DatasetInfo

File /usr/local/lib64/python3.9/site-packages/Orange/data/__init__.py:12
     10 from .io import *
     11 from .filter import *
---> 12 from .pandas_compat import *
     13 from .aggregate import *

File /usr/local/lib64/python3.9/site-packages/Orange/data/pandas_compat.py:9
      7 import pandas as pd
      8 from pandas.core.arrays import SparseArray
----> 9 from pandas.core.arrays.sparse.dtype import SparseDtype
     10 from pandas.api.types import (
     11     is_categorical_dtype, is_object_dtype,
     12     is_datetime64_any_dtype, is_numeric_dtype, is_integer_dtype
     13 )
     15 from Orange.data import (
     16     Table, Domain, DiscreteVariable, StringVariable, TimeVariable,
     17     ContinuousVariable,
     18 )

ModuleNotFoundError: No module named 'pandas.core.arrays.sparse.dtype'

**Comment by markotoplak** [comment]
I tried recreating your environment, and downgrading `pandas` to `2.0.3` solved the issue. Therefore, try installing `pandas==2.0.3` with pip.

I also noticed that your are using an old version of Orange. The latest version, 3.37.0, should not have this problem (I remembered that we fixed something like this). Perhaps better than the above recommendation, could you try to upgrade orange3: `pip install -U orange3` or `pip install orange3==3.37.0`.

**Comment by Zoey-Wu-ed** [comment]
@markotoplak You are definitely a great person! Thank you so much! If anyone else encounters the same issue: No module named 'pandas.core.arrays.sparse.dtype', try pip install pandas==2.0.3 and pip install orange3==3.30.
