### ISSUE TITLE
FreeViz: wrong direction of arrows

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#6854]
**What's wrong?**

I assume the arrows in the projection should be pointing away from the center, not towards it. I might be wrong.
<img width="657" alt="Screenshot 2024-07-17 at 15 34 50" src="https://github.com/user-attachments/assets/d1f82570-641b-4f29-aae6-1c666efc6c5c">

**How can we reproduce the problem?** 

File (zoo) - FreeViz

**What's your environment?**

- Operating system: OSX
- Orange version: 3.37.0
- How you installed Orange: dmg

**Comment by markotoplak** [comment]
Tufte would probably ask why do we need arrows anyway. :)
