### ISSUE TITLE
Edit Domain: no way to get rid of warning "categories mapping for [variable] does not apply to current input" after change in upstream Formula

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3#6861]
**What's wrong?**
When changing the mapping of categories of a categorical variable in Edit Domain, Edit Domain displays a warning  "categories mapping for [variable] does not apply to current input" once changes in an upstream Formula produce different or additional categories. Even when adapting the category mappings to the new inputs, the warning persists.

**How can we reproduce the problem?** 
[edit domain category mappings.ows.zip](https://github.com/user-attachments/files/16359530/edit.domain.category.mappings.ows.zip)
In the Formula in the attached workflow, change 'America' in the if statement to 'North America'. Edit Domain will show the warning, although in its dialog box the category name has already been updated. Even when explicitly defining an new mapping based on the new category names, the warning doesn't go away.

**What's your environment?**

- Operating system: Mac OS 14.5
- Orange version: 3.37
- How you installed Orange: from DMG followed by updates using the internal installer within Orange

**Comment by janezd** [comment]
Thank you for another great bug report! If we offered bounties, you'd be rich by now. :)
