### ISSUE TITLE
Discretize: rounding problem

### ISSUE THREAD

**Issue by ZanMervic** [biolab/orange3#6876]
**What's wrong?**

Using PCA on the Titanic dataset and discretizing the output results in strange rounding of the values by the disretization. This results with multiple values with the same "name".

This is the workflow I have (I have also included the .ows):
![image](https://github.com/user-attachments/assets/960067f6-1a7e-4d4c-ae5b-ccc06b4844f6)

Here on the left is the Data Table that shows the results of the PCA (pay attention to the PC7 attribute). On the right we can see the results of the Discretize widget, the discretized PC7 attribute has been rounded strangely, there are also multiple PC7 values with the same "name" (highlighted).

![image](https://github.com/user-attachments/assets/a01c24a0-43c9-446c-bc8e-f33bf7e0e806)

**How can we reproduce the problem?** 
Zip of the workflow:
[discretize_bug.zip](https://github.com/user-attachments/files/16691162/discretize_bug.zip)

To reproduce the problem, set the PCA components to 8 in the provided workflow.

![image](https://github.com/user-attachments/assets/6eb45bc4-7d43-4f13-9196-25837efa05a7)

**What's your environment?**

- Operating system: Windows 10
- Orange version: 3.38
- How you installed Orange: Using pip in a conda environment

**Comment by janezd** [comment]
Rounding was introduced in df34d9081e1fbe25466980b17a082ce210e821b5.

I think we could (and probably should) simply add `bins_ = np.unique(bins_)` after rounding.

Decimal binning doesn't guarantee to give the exact number of intervals specified by the user, but returns the closest match across different possible "nice" thresholds. If rounding+unique decrease the number of intervals for a certain bin width, the method may choose another (smaller) width, or return smaller number of bins; both are OK.

If you wish, change this (don't forget to add a simple test).

**Comment by janezd** [comment]
@markotoplak, this was fixed in a410361107724d878c254d350715351c058050a5, right?

**Comment by markotoplak** [comment]
Fixed by #6878.
