### ISSUE TITLE
Switch the language of orange3 interface to Chinese.

### ISSUE THREAD

**Issue by TonyEinstein** [biolab/orange3#6881]
**What's your use case?**

Because there is no Chinese version of orange3 software, a group of people in China have translated it and sold it at a high price. As a student and a learning enthusiast, its price is unbearable. I hope I can add an option to switch the software language to Chinese in the settings, which can be downloaded and used as a plug-in

**What's your proposed solution?**

1. Chinese language packs are downloaded as plug-ins.
2. Add options about Chinese language packs in the settings.

**Are there any alternative solutions?**
Use the default language of the computer system.

**Comment by janezd** [comment]
@TonyEinstein, Orange is licensed as GPL. It is illegal to sell it in its original or modified form. I would appreciate if you could provide us with a link to that group so we can take an appropriate action.

As for your request: in #6828 we prepared everything for switching languages, and we translated Orange to Slovenian. We expect to release it soon. We would love to support a Chinese translation if somebody prepares it.

This brings us back to that group: if they translated Orange, their translation is already licensed under GPL (whether they like it or not -- to my understanding) and we can simply incorporate their translations into the official multilingual Orange. This is another good reason why I'd like to contact the group that you mention.

**Comment by simonaubertbd** [comment]
"a group of people in China have translated it and sold it at a high price"

Whoah, without even a conversation with the Orange Data Mining team !

**Comment by TonyEinstein** [comment]
> @TonyEinstein, Orange is licensed as GPL. It is illegal to sell it in its original or modified form. I would appreciate if you could provide us with a link to that group so we can take an appropriate action.
> 
> As for your request: in #6828 we prepared everything for switching languages, and we translated Orange to Slovenian. We expect to release it soon. We would love to support a Chinese translation if somebody prepares it.
> 
> This brings us back to that group: if they translated Orange, their translation is already licensed under GPL (whether they like it or not -- to my understanding) and we can simply incorporate their translations into the official multilingual Orange. This is another good reason why I'd like to contact the group that you mention.

I contacted them in this article [(Chinese version of the publicity address).](https://blog.csdn.net/err2008/article/details/128787981) I'm not sure whether the other party is a studio or a company, and I'm also not sure whether the other party has obtained the license of GPL. The other party said that it has served many companies and the price is not very friendly, so I have this suggestion for this project. This linked article has their QQ group number at the beginning, so you can contact them through this.

**Comment by janezd** [comment]
I apologize, but even after translating the page I'm not sure that I understand it. To my (possibly incorrect) understanding, this page describes how to contact them through chat (Weixin)? If this is how they operate, I wouldn't mind much. Some guy probably ran some automated translation over the Python sources to produce a terrible (and quite possibly buggy) translation. If anybody falls for this ... let him.

Nevertheless, I support your suggestion and would very welcome any volunteers ready to prepare and maintain a Chinese (or any other) translation. Here is an example of how it is done (for Slovenian): https://github.com/biolab/orange3/blob/6c742f75b95cee79c48855700459e7c4d82428da/i18n/si/msgs.jaml

**Comment by zhuyubei** [comment]
> @TonyEinstein, Orange is licensed as GPL. It is illegal to sell it in its original or modified form. I would appreciate if you could provide us with a link to that group so we can take an appropriate action.
> 
> As for your request: in #6828 we prepared everything for switching languages, and we translated Orange to Slovenian. We expect to release it soon. We would love to support a Chinese translation if somebody prepares it.
> 
> This brings us back to that group: if they translated Orange, their translation is already licensed under GPL (whether they like it or not -- to my understanding) and we can simply incorporate their translations into the official multilingual Orange. This is another good reason why I'd like to contact the group that you mention.

The GPL license does not limit user not to sell the software. When user distributes the software, he needs to provide the source code of it.

**Comment by gengyabc** [comment]
We have translated the orange to Chinese and we make it open sourced and still under GPL as you can see here https://github.com/szzyiit/orange3. The Orange team has contacted us years ago but we have very limited time to maintain it. 

I don't know if somebody is selling our translation😭

**Comment by TonyEinstein** [comment]
> We have translated the orange to Chinese and we make it open sourced and still under GPL as you can see here https://github.com/szzyiit/orange3. The Orange team has contacted us years ago but we have very limited time to maintain it.
> 
> I don't know if somebody is selling our translation😭

Thank you very much for sharing.
