### ISSUE TITLE
Hierechical clustering: allow Top N > 20

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3#6883]
**What's your use case?**
For some reason, the setting Top N to prescribe the number of clusters in Hierarchical Clustering doesn't allow values > 20. Using the Height Ratio selection it is however possible to further break down the clusters, but this can be cumbersome. For instance in a large text corpus with hundreds of documents it sometimes makes sense to create large numbers of clusters.

**What's your proposed solution?**
Allow more than 20 clusters when using Top N.

**Comment by janezd** [comment]
Note: agreed, but if the number of clusters is too large, the widget will show a warning that some widget may become slow with categorical variables with many values.
