### ISSUE TITLE
Logistic Regression 

### ISSUE THREAD

**Issue by TilenG2** [biolab/orange3#6885]
**What's wrong?**

Logistic Regression gets parameter 'none' instead of None as shown in the image

![image](https://github.com/user-attachments/assets/47dbee26-50cf-49bf-b008-d1bb7b04a887)

**How can we reproduce the problem?** 
Load the iris dataset into Logistic Regression widget and set None in the drop-down as seen in the image.

**What's your environment?**

- Operating system: linux, debian based
- Orange version: 3.37.0
- How you installed Orange: pip

**Comment by janezd** [comment]
Thanks for the report. This used to work, but apparently something has changed in the Scikit learn library. Should be fixed in #6886.
