### ISSUE TITLE
Deal with Anaconda license change

### ISSUE THREAD

**Issue by woutdenolf** [biolab/orange3#6888]
Summary of the changes: https://www.datacamp.com/blog/navigating-anaconda-licensing

As far as I understand, Orange3 and the add-ons are on the conda-forge channel which stays free. The Windows installer installs miniconda3 (perhaps the MacOS one as well?).

Would it be possible to use [miniforge3](https://github.com/conda-forge/miniforge) instead in the installer? It is faster and has `conda-forge` instead of `default` as default channel. Or keep miniconda3 and remove the `default` anaconda channel.

If you see other effects of the license change, it would be good to address them.

**Comment by markotoplak** [comment]
Thank you for bringing this to our attention

 Only the Windows version uses conda for now, and all packages come from conda forge. We have been discussing abandoning miniconda in binary packages and just work with straight up packages from pip a while ago. This seems like a good motivating factor.

**Comment by janezd** [comment]
Discussion summary: big companies seem to start avoiding miniconda. We should probably move. We have to see whether migrating to miniforge is just a question of replacing the executable.

**Comment by markotoplak** [comment]
We just published Orange 3.38, which is not, for Windows, based on Miniforge. Thanks to @woutdenolf for notifying us and @ales-erjavec for the actual installers.

The downloads are here: https://orangedatamining.com/download/
