### ISSUE TITLE
Problem with SVM widget (degree must be int but only allows float)

### ISSUE THREAD

**Issue by TonciG** [biolab/orange3#6892]
**What's wrong?**

Got this error when try to use SVM widget:
Fitting failed.
The 'degree' parameter of SVC must be an int in the range [0, inf). Got 3.0 instead.

![Untitled](https://github.com/user-attachments/assets/32cec1a9-4ee7-4f9e-a659-2dd6fb372653)

The problem is that degree (d) hyperparameter of this widget only allows for float values yet the error message clearly says that this ought to be integer.

**How can we reproduce the problem?** 

**What's your environment?**

- Operating system:
- Orange version:
- How you installed Orange:

**Comment by janezd** [comment]
Thanks for reporting this.

This bug, which became evident with the new version of Scikit-learn, was first reported in #6853 (and later in #6868), and is fixed in #6866.

A temporary workaround is described in https://github.com/biolab/orange3/issues/6853#issuecomment-2264889702.

**Comment by TonciG** [comment]
Thanks for your response Janez.

When are you planning the release of new Orange version with this bug fixed?

Thanks,
Tonci

**Comment by markotoplak** [comment]
@TonciG, finally released. Sorry for the wait.

**Comment by TonciG** [comment]
Thanks guys for your hard work and the great software!
Tonci
