### ISSUE TITLE
Add menu option to clean up copied-widget sequence numbers

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3#6893]
**What's your use case?**
I'd like to have a quick way for removing all numberings added to widgets when they've been copy-pasted. So that all widget names like this
<img width="141" alt="image" src="https://github.com/user-attachments/assets/b9f33800-ae42-4d24-b2db-f61dba741877"> 

can easily be changed into this with one action:
<img width="90" alt="image" src="https://github.com/user-attachments/assets/e7535aad-de5c-43a9-90dc-adc5cb23b702">

**What's your proposed solution?**
Add a menu item "Remove widget copy counts" or something similar, perhaps under Edit.

**Are there any alternative solutions?**
Manual editing of all concerned widget names

**Comment by janezd** [comment]
Discussion summary: we'd like to avoid overwhelming the user by having many small functions like this. A better solution would be to avoid this situation at all, e.g., if the user copies a widget `Save Data (2)`, the copied widget is `Save Data (3)` (or `Save Data (4)` if `Save Data (3)` already exists; in general `Save Data (<n>)`, where `<n>` is the lowest unoccupied number).

**Comment by wvdvegte** [comment]
Indeed, that would already be better than the current behavior.
