### ISSUE TITLE
Cartesian product detection in join tool

### ISSUE THREAD

**Issue by simonaubertbd** [biolab/orange3#6899]
**What's your use case?**
Cartesian product is a common issue when joining dataset with a bad key. It's not always easy to detect and users can even forget to check for it because they think they know their data.

**What's your proposed solution?**
What I suggest is an option to check if there will be a cartesian product on the join tool.

-there is a label "Cartesian product (non join key uniqueness) detection"
-under it a drop down menu with three choices
      -do nothing
      -fail
      -warning
      
Algo :
if do nothing==> well... do nothing more than actual behaviour.
if "fail" or "warning" : count distinct of join key (potentially a combination of fields) versus count row on each side of the join. If no count distinct is equal to simple count, display a warning or an error message.

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/saubert/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/saubert/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

order_id | customer_id | amount
-- | -- | --
1 | 1 | 100
2 | 1 | 150
3 | 2 | 142
4 | 2 | 145
5 | 1 | 145

</body>

</html>

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/saubert/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/saubert/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

customer_id | customer_name
-- | --
1 | toto
2 | tata
2 | titi

</body>

</html>

on customer_id

=> count distinct left : 2; count left : 5
=> count distinct right : 2; count right : 3
2<>5 and 2<>3
=> there will be a cartesian product

=> for the count, it must be a count(*) or a sum(1) but not a count of the field itself because of the null.

**Are there any alternative solutions?**
N/A

Best regards,

Simon

**Comment by janezd** [comment]
Please see https://github.com/biolab/orange3/issues/6932#issuecomment-2495400689.

**Comment by simonaubertbd** [comment]
I just developed it on [Amphi](https://github.com/amphi-ai/amphi-etl)

<img width="536" height="359" alt="Image" src="https://github.com/user-attachments/assets/95bf0a62-79a9-4420-95fa-c7d1bf182b89" />
