### ISSUE TITLE
Predictions puts "?" regression error values on output while a regular numeric value is shown in its own visualization/dialog box

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3#6911]
**What's wrong?**
**How can we reproduce the problem?**
In the attached workflow using user reviews from Kaggle (included), open Select Columns, and drag 3 out of 4 features to 'Ignored' so that 'compound' is left as the only feature. Now for several rows, Predictions will produce a "?" on its output for 'Linear Regression (error)' while a regular numeric value is shown in its own visualization/dialog box. For instance, for row 347, the error is shown as 2 in the Predictions visualization/dialog box, but instead Data Table (1) shows a "?"

[Review Mining.zip](https://github.com/user-attachments/files/17330611/Review.Mining.zip)

**What's your environment?**

- Operating system: Mac OS Sequoia
- Orange version: 3.37.0
- How you installed Orange: from dmg; updates through add-ons menu

**Comment by processo** [comment]
I can confirm this. When the _Absolute difference_ output of Predictions would be exactly 2 it is turned into missing (?), no matter the model or data.

**Comment by janezd** [comment]
I cannot reproduce the error. I also tried with a simpler workflow, in which I just create the data, but still no luck.

To make sure we're trying this on the same data: could you upload the data the comes from Select Columns?

**Comment by markotoplak** [comment]
Orange 3.38.1 with the fix for this problem was just released. Download it here: https://orangedatamining.com/download
