### ISSUE TITLE
Multi-Tab User Interface

### ISSUE THREAD

**Issue by simonaubertbd** [biolab/orange3#6922]
**What's your use case?**

I think we all love having several tabs in our applications, instead of several windows. There are a lot of good reasons for that 
1. Space Efficiency

    Tabs allow users to switch between multiple pages or documents within the same window, avoiding screen clutter. With many windows, your screen space may become overwhelmed, making it hard to find and manage content.

2. Organizational Benefits

    Tabs keep everything neatly organized in one place. This is especially useful when working with related content (e.g., research, projects, or web browsing). It reduces the need to minimize or switch between multiple windows, streamlining workflows.

3. System Performance

    Running many windows can consume more system resources like memory (RAM) and processing power than using tabs in one window. Keeping everything in one window with multiple tabs often leads to better performance.

4. Easier Navigation

    Tabs are usually displayed in a single line at the top of the window, making it easy to click through or use shortcuts (e.g., Ctrl + Tab) to navigate between them. Managing several windows requires clicking through the taskbar or using more involved keyboard shortcuts (e.g., Alt + Tab).

5. Reduced Distraction

    Multiple windows can lead to distractions since they may overlap and interrupt focus. Tabs, on the other hand, allow users to switch focus only when needed while keeping everything clean and contained in a single frame.

6. Session Management

    Modern browsers often save tabs when closed and offer easy ways to restore them, making it easier to resume your session. Managing many windows can make this process more cumbersome.

**What's your proposed solution?**
As we can see here, developed by @zhuyubei
![378136961-4d84772a-3ef5-4ae1-a7b0-fb1406a32bbc](https://github.com/user-attachments/assets/aaefc841-49a0-4a6d-b8d2-dc64936821e8)

https://github.com/biolab/orange3/issues/6699

**Are there any alternative solutions?**
N/A

Best regards,

Simon

**Comment by zhuyubei** [comment]
But this will have a big change in orange-canvas-core. I don't know the roadmap or priority of Orange3.

**Comment by janezd** [comment]
We have had multi-tab user interface in the past -- these things are not very difficult to do, it's just a question of where you put Qt's components. But it turned out to be much more confusing than useful, so we dropped it.
