### ISSUE TITLE
File reader improvement

### ISSUE THREAD

**Issue by borondics** [biolab/orange3#6929]
**What's your use case?**

It seems to me that file readers are not easily joinable, meaning that if there are more than one file formats for some software (example for `Orange` would be **Excel**), the readers have to be implemented and if they are in different classes, they will appear as different options in the `File` widget.

This can become a bit extreme when handling many file types, as shown in the picture below in `Quasar` - notice the multiple readers for the same instrument type such as **Agilent** or **NeaSpec**.

<img width="864" alt="image" src="https://github.com/user-attachments/assets/7910909e-7a1c-4859-8008-f1f607e7f93d">

**What's your proposed solution?**

It would be nice to be able to add meta readers that would aggregate individual classes which in turn would not show up as separate options in the list of file formats.

**Are there any alternative solutions?**

Not that I can think of.

**Comment by janezd** [comment]
Could you have a single reader that would accept .dmt, .dat, and .seq and then delegate the work to the appropriate "subreader"?

**Comment by borondics** [comment]
Hi Janez, We were discussing this with @markotoplak yesterday and it seems we could use the current architecture to do what I wanted here. Let me give it a try first and then I'll get back to you on this.

**Comment by markotoplak** [comment]
Yes, we discussed precisely this yesterday and Orange does not hinder us here.

As a related note, adding functionalities to file readers so that they could quickly sniff the file and decide, if they are compatible with the format, could be helpful - but that is another issue.
