### ISSUE TITLE
Add-on dialog on conda: cannot update Orange from 3.37.0 to 3.38.0 (EDIT: also problems with add-ons)

### ISSUE THREAD

**Issue by TonciG** [biolab/orange3#6938]
**What's wrong?**

Fail to update Orange to the latest version via Options - Add-ons...
I check the box for Orange update (to 3.38.0) in the Add-ons.
After a few seconds I get the message that I need to restart the software for the change to take place.
However, after the restart I end up with the same old version (3.37.0).
Tried this many times and I always get the same result.

**How can we reproduce the problem?** 

**What's your environment?**

- Operating system: 64-bit Windows 10 Enterprise with Windows Feature Experience Pack
- Orange version: 3.37.0
- How you installed Orange: The version I currently use was downloaded from your website.

**Comment by markotoplak** [comment]
How was your 3.37.0 installed? Which package did you use? Miniconda or zip? Did you install for all users or just for your user? If you installed for all users you'd have to run Orange as an administrator to update.

These kinds of updates sometimes actually work, but we do not advertise them because they can have issues. It could help us if you provide the debug output of this installation: you can see it if you run "orange-canvas -l4" from the Orange command prompt and then do the update process.

The safest update is to download the new package from the website, remove the old version, and install the new one.

**Comment by TonciG** [comment]
I used miniconda to install Orange and it was only for single user, since I do  not have admin rights.

I have used Orange for 5 or 6 years now and would almost always I update the software in this way. It is much quicker and better way of doing it than downloading it from the website. This is the first time I have experienced a problem with this method. The funny thing is that a few days ago I updated the software in exactly the same way but on my second laptop (same company). No problem at all!

I have done what you suggested, please find attached the debug output. 
[debug output.txt](https://github.com/user-attachments/files/17921593/debug.output.txt)

**Comment by TonciG** [comment]
Just tried to update a few add-ons (Text, Network, and Fairness) this way but I get the same result as with Orange update above.

**Comment by markotoplak** [comment]
Yes, @janezd, it is not trubar. I have no idea what it is.

**Comment by markotoplak** [comment]
I tried this: I installed Orange with the Windows 3.37 conda installer, then I tried upgrading as @TonciG. I get the same issue: nothing seems to be update, and I see "All requested packages already installed." in the log.

**Comment by markotoplak** [comment]
I tried debugging this. Orange add-on procedure runs `C:\Users\marko\AppData\Local\Programs\Orange\Scripts\conda.bat install --yes --quiet --satisfied-skip-solve orange3=3.38.0`.

I tried running `C:\Users\marko\AppData\Local\Programs\Orange\Scripts\conda.bat install --satisfied-skip-solve orange3=3.38.0` and got the same behavior.

But when I executed `C:\Users\marko\AppData\Local\Programs\Orange\Scripts\conda.bat install orange3=3.38.0` the update worked flawlessly

So here ` --satisfied-skip-solve` did something I did not except. Do you have any idea, @ales-erjavec? Or perhaps,  @PrimozGodec, please comment if you remembered something?

**Comment by markotoplak** [comment]
It is even worse! In the "Orange command prompt", I installed orange3-imageanalytics=0.12.4 (not the last version). Then I tried updating in the dialog - and - it did not work! There was exactly the same issue.

Also, an user wrote me this in October: 
> So I have tried three times on updating but it is not doing it, it seems it tried to do it, it restarts Quasar, but when I go back to add-ons it still doesn't appear updated.

So this bug not only prevents updating Orange, but also prevents updating add-ons.

**Comment by markotoplak** [comment]
Orange 3.38.1 with the fix for the problem was just released. Download it here: https://orangedatamining.com/download
