### ISSUE TITLE
Problems with Excel/csv reader in Orange 3.38

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#6945]
**What's wrong?**

#6862 fixed reading of flags in 1-line header format, but it "recognizes" flags that are not.

The attached file has an attribute *1999-12-01 Towards a nuclear-weapon-free world:#the need for a new agenda*. The part before `#` is recognized as flag (I don't know which flags is it supposed to contain) and reading fails when converting the column data into floats.

I think that the code should be more strict about what is recognized as flag. Probably it has to be something like `[cm]?[CDST]?#` and that's it. 

**How can we reproduce the problem?** 

Load the file [un-resolutions-1.csv](https://github.com/user-attachments/files/17970212/un-resolutions-1.csv) with the File widget. (CSV Reader works.)

**What's your environment?**

Oranga 3.38 - dmg or from github.

**Comment by markotoplak** [comment]
Orange 3.38.1 with the fix for this problem was just released. Download it here: https://orangedatamining.com/download
