### ISSUE TITLE
Miniconda won't download for Mac

### ISSUE THREAD

**Issue by LiNG571** [biolab/orange3#6946]
I am trying to use the Miniconda installer for Organge. This page says it is possible:
 https://orangedatamining.com/blog/miniconda-installer/

However, clicking on the 'Miniconda Installer' link in the page takes me to an error page. This is the error I get:
```404 Not Found
nginx/1.18.0 (Ubuntu)```

Attached is also a screen shot.

I have a Macboo
<img width="1465" alt="Screenshot 2024-12-02 at 15 29 49" src="https://github.com/user-attachments/assets/bcee3cda-f0ad-4b1f-a332-f71ef8723d79">
k air M2. Is it not compatible maybe with it?

**Comment by markotoplak** [comment]
Orange with Miniconda (now superseded by Miniforge) installer is only built for Windows. The blog post you mention is quite old. For the newest installers, see https://orangedatamining.com/download/. The Mac packages are DMG images, which are not conda-based.

It is indeed possible to manually install Orange withing a conda repository on Macs. For instructions about this, see the Anaconda section on https://orangedatamining.com/download/

**Comment by janezd** [comment]
@markotoplak, should we edit the blog, perhaps?
