### ISSUE TITLE
Clustering (hierarchical vs. others): inconsistent handling of items that cannot be assigned to a cluster

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3#6954]
**What's wrong?**
For records that cannot be clustered, most clustering widgets produce a "?" in the Cluster column. Only Hierarchical Clustering assigns a cluster number to each record. However, when the dividing line is slid to the right, clusters of only one record may appear, which are in fact not clusters (or if they are, clusters of one item should also get their own cluster number from the other clustering widgets).
This is problematic when comparing different clustering approaches applied to the same dataset. Silhouette Plot, for instance gives a warning if there are "?"s in the Cluster column but treats one-item clusters from hierarchical clustering as true clusters.
I'd propose to let Hierarchical Clustering produce a "?" in the Cluster column if a "cluster" has only one record.

**Comment by markotoplak** [comment]
We tend to handle "outliers" in the same way as the original method does. One data point staying in their own cluster can also be useful data. Therefore we are not going to modify the existing behaviour.
