### ISSUE TITLE
Orange freezes when trying to pass the "titanic" dataset to Data Table

### ISSUE THREAD

**Issue by ypanagis** [biolab/orange3#856]
This started when trying to reproduce an error  I had when trying to build a mosaic plot. So initially I was able to load the Titanic dataset and connect the Data Table widget to the File. 

Then I closed Orange and opened again trying  to reopen titanic.tab and to reconnect the Data Table. Now Orange freezes whenever I try to make the connection and I have to shut it down completely. My workspace is attached as `ows.txt` file. I am running `Orange 3.2.dev0` in Windows 7 x64 and Python 3.4

[untitled2.ows.txt](https://github.com/biolab/orange3/files/36873/untitled2.ows.txt)

**Comment by ales-erjavec** [comment]
Can you please locate the canvas.log file in '\Users\USERNAME\AppData\Roaming\Orange\3.2.dev\canvas\canvas.log' and post it here (the AppData directory is hidden so you need to check the 'Show hidden files in Explorer's 'Organize/Folder Options -> View' tab)?

**Comment by ypanagis** [comment]
I tried some other things yesterday in Orange and the log must have changed. Also today the Orange doesn't freeeze with the above procedure. It was a strange behaviour though...
