### ISSUE TITLE
How can I make a new add on available for installing trough the Orange add on installer?

### ISSUE THREAD

**Issue by jamartinh** [biolab/orange3#882]
Hello, I am developing an extension to allow Orange work with Apache spark ML lib.

I will need help with some internal issues of Orange.

Any volunteers to help?

https://github.com/jamartinh/Orange-Spark

Best,
Jose

**Comment by kernc** [comment]
> How can I make a new add on available for installing trough the Orange add on installer?

https://github.com/jamartinh/Orange-Spark/blob/master/setup.py#L27

You publish it on PyPI.

--------
I look forward to testing it. I should also find some time to review it. Great work!

**Comment by jamartinh** [comment]
Thanks !
Now it is done!
