### ISSUE TITLE
Problems with conda package

### ISSUE THREAD

**Issue by ahmadia** [biolab/orange3#944]
Hey folks,

We're having some issues with users trying to use Orange on Windows from Anaconda/conda.  Is this something you all are interested in helping us support? The issue is here: https://github.com/ContinuumIO/anaconda-issues/issues/597

There appears to be an existing package here: https://anaconda.org/anaconda/orange

I don't know if the package is correct or has problems.  I'm happy to answer questions about how to maintain packages on Anaconda.org and build with conda, but I'm not familiar enough with Orange itself to put together a conda package for it.

**Comment by ales-erjavec** [comment]
A quick look at the contents of the .tar.bz2 packages does reveal that the orange-canvas executable is missing from the windows package, but is present in the others. 
In a normal ``python setup.py install``  the executable is created and installed by setuptools 'gui_scripts' entry_point.

**Comment by ahmadia** [comment]
Thanks folks for the help, we've resolved this on our side and `conda install orange` should now work for all three platforms.
