### ISSUE TITLE
Python 3.5 Windows 10

### ISSUE THREAD

**Issue by jamartinh** [biolab/orange3#948]
Hi, this, line is causing me an error in python 3.5 windows 10 

lib = ctypes.pydll.LoadLibrary(os.path.join(path, "_grid_density" + sysconfig.get_config_var("SO")))

It seems this will happen in every import using this method.

The problem is that python 3.5 Anaconda has empty SO (".pyd") 

I can import the library just by importing _grid_density since the python import recognize the correct extension.

**Comment by kernc** [comment]
How did you manage to install Orange with Anaconda Python 3.5?

**Comment by jamartinh** [comment]
After installing requirements...

python setup.py develop

I have visual studio 2015 community.
64 bits python.

**Comment by jamartinh** [comment]
Thanks !!!

**Comment by kernc** [comment]
@jamartinh are you confirming it now works?

**Comment by jamartinh** [comment]
Yes, it seems to work now!

2016-01-17 5:01 GMT+01:00 Kernc <notifications@github.com>:

> @jamartinh <https://github.com/jamartinh> are you confirming it now works?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biolab/orange3/issues/948#issuecomment-172290068>.
>



-- 
/ .- .-.. .-.. / -.-- --- ..- / -. . . -.. / .. ... / .-.. --- ...- .
José Antonio Martín H. (PhD)           E-Mail: jamartinh@fdi.ucm.es
Computer Science Faculty               Phone: (+34) 91 3947650
Complutense University of Madrid       Fax: (+34) 91 3947527
C/ Prof. José García Santesmases,s/n   28040 Madrid, Spain
web: http://www.dacya.ucm.es/jam/
LinkedIn: http://www.linkedin.com/in/jamartinh (Let's connect)
.-.. --- ...- . / .. ... / .- .-.. .-.. / .-- . / -. . . -..
