### ISSUE TITLE
File data is not getting loaded

### ISSUE THREAD

**Issue by tastyminerals** [biolab/orange3#965]
**Steps to reproduce:**
* Installed `orange-python 3.1.1`.
* Created a tab delimited file of the following format:

```
feature1	 feature2	 class
2.306369658241986	2.120199243103004	0
2.204974314655459	1.300788301610075	0
2.926289909766701	1.479770738670901	0
1.215988525863422	2.698607360474	0
```

* Saved the file as **data.csv**
* Opened **Orange** with `python -m Orange.canvas`
* Dragged **File** widget to the canvas, right-clicked and loaded the file
* Saw the message `Info  no data loaded`

Why the file is not getting loaded?

**Comment by kernc** [comment]
Sorry, what is that you call `orange-python 3.1.1`? Please install the latest release from http://orange.biolab.si.

With the latest Orange, I can load that file just fine.
![screenshot - 01102016 - 05 21 33 pm](https://cloud.githubusercontent.com/assets/684364/12222508/bcb1bce0-b7be-11e5-885f-c62efdcad5e6.png)

**Comment by tastyminerals** [comment]
Thanks, everything works when installed from github.
