### ISSUE TITLE
Running Add-ons produces an Error

### ISSUE THREAD

**Issue by tastyminerals** [biolab/orange3#966]
**Steps to reproduce:**
* Do `sudo pip install Orange3-DataFusion`
* Do `sudo pip install Orange3-Network`
* Run Orange
* Open **Add-ons** tab

The following message window appears:
```
--------------------------------------------------------------------------------
KeyError                                      Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/Orange/canvas/application/addons.py", line 418, in _set_packages
    packages = f.result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.5/site-packages/Orange/canvas/application/addons.py", line 544, in list_pypi_addons
    Installable(release["name"], release["version"],
KeyError: 'name'
```

Seriously, guys, **Orange** is in sort of unusable state.
I have been using the app on a daily basis in my work few years ago.
It was pretty stable.

**Comment by kernc** [comment]
Ack. Please retry with the latest version.

**Comment by tastyminerals** [comment]
Tried with **3.2.dev0** from github.
Same error but below it also says:
`You don't have permissions to write into Orange directory`

**Comment by kernc** [comment]
Thanks for your report. You can easily solve it by installing orange into a virtualenv you have permission to write to, e.g.
```bash
virtualenv -p python3 orange3venv
source orange3venv/bin/activate
cd orange3
python setup.py develop  # or install if you don't ever intend to submit patches
```
This will install Orange, including add-ons later on, into that virtualenv instead of _/usr/local/lib/python..._ In fact, best have a look at this [shell script](http://biolab.github.io/install-orange/setup-ubuntu.sh).

@biolab Should we install add-ons into _~/.local/Orange3/add-ons/_ (or equivalent) with `pip install --target` and insert the same path into `sys.path` on initialization? IIUC, this should solve this issue, any similar issues, and the need to _install_ the dmg on Macs.

**Comment by tastyminerals** [comment]
You should probably rename the script into some distro agnostic.
It does not have anything ubuntu specific and didn't use it only because of mentioned "ubuntu" .

**Comment by tastyminerals** [comment]
Also, I am not 100% sure but **ubuntu** should use `python2` for `python` call. So, in the script `python setup.py develop` will call `python2`.

**Comment by kernc** [comment]
> You've obviously tested it on ubuntu already though...

Haha. Good one. :smile:

**Comment by lanzagar** [comment]
> @biolab Should we install add-ons into ~/.local/share/Orange3/add-ons/ (or equivalent)
> with pip install --target and insert the same path into sys.path on initialization?
> IIUC, this should solve this issue, any similar issues, and the need to install the dmg on Macs.

I use `pip install --user` on my system for almost all pip installs and it works as it should. No need for root privileges, uses a sensible location on all platforms and no need to insert locations into `sys.path` (should be there by default).

**Comment by milothatch** [comment]
Hi all,
I confirm the said error in the Windows version. I've installed yesterday's built on 64-bit Windows 8.1 Home Premium, German, with Python 3.4, and full admin rights. The error message was virtually the same as above save the paths and code line numbers.
